### ISSUE TITLE
FR: Ability to disable all CSS and JavaScript

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#10013]
**Does your feature request involve difficulty completing a task? Please describe.**
- Certain downloaded websites for offline reading can come with unnecessary JavaScript. This can make some HTML files take an unusually long time to open
- There does not appear to be an option to disable all CSS all at once, only specific overrides

**Describe the solution you'd like**
UI options to ignore/disable CSS and JavaScript

**Describe alternatives you've considered**
- To disable JavaScript, manual editing of HTML files and removing all `<script>` tags
- To disable CSS, basically adding a combination of other style options into one CSS styletweak, e.g.:
```
* {
  margin: 0 !important;
  padding: 0 !important;
  color: inherit !important;
  background-color: inherit !important;
  font-family: inherit !important;
  font-size: inherit !important;
}
```

**Comment by poire-z** [comment]
Are you certain you are talking about KOReader ? :)

> Certain downloaded websites for offline reading can come with unnecessary JavaScript. This can make some HTML files take an unusually long time to open

We have ZERO support for Javascript.
We need to "parse" (actually skip) any `<script>` tag content we meet, so this takes as much time (probably less) as parsing any text the size of their content. But we don't execute it, we just ignore it.
What may happen, given the complexity that can happen inside  `<script>`, is that we may parse it incorrectly, and not skip some parts of the script, and display it as text. But we did spend time on trying to parse it properly.

> There does not appear to be an option to disable all CSS all at once, only specific overrides

Come on, how can you expect KOReader to not have that ?! :)

![image](https://user-images.githubusercontent.com/24273478/211393359-916432f7-f818-40b3-8ac0-1f2c71e6fe61.png)

If some saved web pages seems to take a long time to open/render, it's more probably because they wrap all their content in many nested `<table>` - which makes it harder to render - and probably even harder on each page turn (that may need to rerender the whole thing).
The solution in that case is to use some browser extension where you can select some inner content and save only that, without the header/footer/sidepanel crap. Like https://github.com/alexadam/save-as-ebook.
Or use Wallabag or stuff like that to generate EPUBs from urls.

**Comment by gbyl** [comment]
I can't believe I missed the `Embedded Style` toggle after using KOReader for so long! As for JavaScript, your explanation makes much more sense as a cause for any lag. I'll give those extensions a try. Thanks!
