### ISSUE TITLE
Cannot Open EPUB Properly With URL Encoding (Percent Encoding) in Files

### ISSUE THREAD

**Issue by esverde** [koreader/koreader#10021]
* KOReader version: 2022.11
* Device: Kindle PaperWhite 5

#### Issue
While a EPUB file have **URL Encoding (Percent Encoding)** in XHTML's link href to CSS style file, koreader cannot decode this link address then find CSS style file.
eg. 
```
<link href="../Styles/_%3A%2A%7C%3A%2A%2A%2A%7C__%2A%7C%3A_%7C_%2A_%7C.css" type="text/css" rel="stylesheet"/>
```

**Comment by poire-z** [comment]
It's some spread bits of a mess how we handle filenames and href/src attributes, and the need for their %-decoding.
I'm not sure the specs say urls in href/src can or should be url-encoded, and we may find both types in the wild. We had some past issues about that, also in the opf, and if I remember right, also some %-encoding in the filenames in the ZIP, that we were not finding because we were %-decoding the url to them in the .opf...)

I believe/think they should not be decoded too early at HTML parsing time, and their attributes should be stored in the DOM/cache as they appear (not decoded). And that we should only url-decode them when about to be used/accessed. Do you share that thought ?
I think it's what we do, as that snippet:
```html
<head>
  <link href="style%2Ecss" type="text/css" charset="UTF-8" rel="stylesheet"/>
  <link href="%73tyle.css" type="text/css" charset="UTF-8" rel="stylesheet"/>
</head>
<body>
  <p>zzz</p>
  <img src="c%6fver%2Ejpg" style="width: 200px; height: 200px"/>
  <p class="debutchapitre">En remontant
```
appears as:
![image](https://user-images.githubusercontent.com/24273478/212114032-d1703bbd-a0a2-4a79-8174-798ad7d2c141.png)

And indeed, these css would not be found.
But the image would be, as we already have some code that tries finding the file first with url-decoding, then without:
```c
    lString32 refName = getObjectImageRefName(true);
    if ( refName.empty() )
        return ref;
    ref = getDocument()->_urlImageMap.get(refName);
    if (!ref.isNull()) {
        if ( ((NodeImageProxy*)ref.get())->IsInvalid() )
            return LVImageSourceRef();
        return ref;
    }
    // we should also try without percent decoding (for fb3, but may happen with bad other documents)
    lString32 altrefName = getObjectImageRefName(false);
```
We also have that for some getHref() function.
Also https://github.com/koreader/crengine/commit/fed8da73c.

In that spirit, we could just go with:
```diff
    bool Parse(lString32 cssFile, LVStyleSheet &dest)
    {
        bool ret = false;
        if ( cssFile.empty() )
            return ret;

        StyleSheetCache &cache = _document->getStyleSheetCache();
        LVStyleSheet *cached = cache.get(cssFile);
        if (cached) {
            dest.merge(*cached);
            return true;
        }

        LVStyleSheet *styleSheet = new LVStyleSheet(_document);
        lString32 codeBase = cssFile;
        LVExtractLastPathElement(codeBase);
        LVContainerRef container = _document->getContainer();
        if (!container.isNull()) {
            LVStreamRef cssStream = container->OpenStream(cssFile.c_str(), LVOM_READ);
+           if (cssStream.isNull())
+               cssStream = container->OpenStream(DecodeHTMLUrlString(cssFile).c_str(), LVOM_READ);
            if (!cssStream.isNull()) {
                lString32 css;
                css << LVReadTextFile(cssStream);
                int offset = _inProgress.add(cssFile);
                ret = Parse(codeBase, css, *styleSheet) || ret;
                _inProgress.erase(offset, 1);
            }
        }
```
as a quick no-risk hack.
Which may still not work, as the cssFile path is combined with the possible subdirectories subpath (ie `OPS/` in my screenshot above) before - and this subdirectory may or may not (not sure) have been previous url-decoded - so in extra edgy cases where the directory contains real `%`, this could fail...

**Comment by Jamesernator** [comment]
> I'm not sure the specs say urls in href/src can or should be url-encoded, and we may find both types in the wild.

The [epub spec](https://www.w3.org/TR/epub-33/#sec-overview-relations-url) refers to use the [url spec](https://url.spec.whatwg.org/) if possible (falling back to the [classic uri spec](https://www.rfc-editor.org/rfc/rfc3986) if full support is not possible). Although in either case percent encoding is expected to be handled for percent encoding that is syntatically correct, the modern url spec allows `%` to be treated as-is if not followed by 2 hex digits.
