### ISSUE TITLE
workflow for autosuspend,autostandby and autoshutdown with koreader in kobo glo hd with a cover

### ISSUE THREAD

**Issue by rogergithubbing** [koreader/koreader#10117]
Hi,

Reading the manual I cannot get how to properly configure koreader with the setup in the Re:

In fact I cannot understand the difference between standby and suspend.

How should I configure everything ? Right now I have autosuspend in 10m + autoshutdown in 5d, thus, I avoid the battery to be exhausted in case I forget to close the cover, or when (rare) the cover does not make proper contact.

Thanks!

**Comment by NiLuJe** [comment]
The defaut values are sensible for daily readers.

If you don't use your device every day, you might want to increase the autoshutdown delay (I set like to 14 days, which might be the max?).

You shouldn't need to enable autostandby except on very spécieux devices (Elipsa & Sage).

**Comment by rogergithubbing** [comment]
Ok, thanks for your help, but can you please answer the specific questions
I was asking ?

Best regards,

**Comment by NiLuJe** [comment]
Well, that's it, really. The ranges in the UI have sensible extrema, and you've understood the purpose behind each option, so it's up to your personal preference and usual workflows. I see nothing wrong with the values you've detailed.

**Comment by rogergithubbing** [comment]
Ok, but  I wasnasking:

-what's the difference between standby and suspend ? 

Also...

-The device consumes the same in both modes ?
-When the cover is closed, which mode is triggered?

Thanks again!

**Comment by pazos** [comment]
> what's the difference between standby and suspend ?

suspend stops all cpu cores until an interrupt happens. Works on most devices. While the device is suspended you cannot interact with it. The way to wake up a suspended device is pressing the power button, using a magnet or a RTC alarm.

standby reduces the power comsuption while you're reading, is only recommended on certain platforms or devices which consume huge amounts of power when idle. It has a noticeable impact on some devices because we spend huge amount of microseconds reading a static page on a eink screen.

> The device consumes the same in both modes ?

First, which device? Always include your device/platform when asking a question or reporting a bug :)

Second. Nope, see my previous answer

> When the cover is closed, which mode is triggered?

It suspends to ram, like your laptop.
