### ISSUE TITLE
Tag unwanted, outdated or too old FR

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#10154]
To give a hint to new developers (or just to show that the KOReader developers are cool and working hard and the number of unsolved issues is small) someone might want to tag old FR in a meaningful way.

**Comment by Frenzie** [comment]
We try. ^_^

**Comment by mergen3107** [comment]
I tried to close some of my FR/issues :D

**Comment by pazos** [comment]
I like tags :)

I think they're useful for devs/contributors, not exactly for end users.

We have a few which I find useful but maybe we don't all understand them in the same way. 

Here're a few and my interpretation:

`won't fix` -> "nobody cares enough to implement, patches welcome"
`can't fix` -> "nobody can implement"
`out of scope` -> "a FR beyond the limits of what's the app purpose"
`rejected` -> "a FR that might fit in the limits but it is too niche, too obscure, too fragile, to even accept patches"
`question` -> "issues that are not issues in the issue tracker :p"
`documentation` -> "mostly inherited from question, but contains interesting docs in case someone wants to port it to user guide/wiki or filter by previously answered questions"

**Comment by Frenzie** [comment]
I'm not sure if won't fix implies patches welcome, agreed on the rest.

**Comment by zwim** [comment]
@pazos  @Frenzie 
What about adding another tag: "Patches welcome" (maybe "Patches or User-Patches welcome")?

What about pinning a dedicated issue about explaining the tags (for explaining our interpretation of certain/all tags, and if these are meant for end users or developers)?
Perhaps some of you want to do that?

**Comment by Frenzie** [comment]
@zwim The explanation exists ftr.

![image](https://user-images.githubusercontent.com/202757/221282782-665b3955-2856-49c1-9107-98fa3bfa901f.png)

Also when you hover over a tag.

**Comment by zwim** [comment]
@Frenzie  Oh I see, but hover only works for a tag with a description. 
For "normal" tag like `Kobo`, `Firmware` and so on there is additional information when "hovering". Perhaps this explains, why I have not noticed that github feature yet.

Maybe it might help (some users who are as clumsy as I am) that someone (you?) to add a description to any tag? And (!) to add a more detailed description.
(But a pinned issue with the same content might/can help more? By now we have only 3 issues, so the number of pinned issues should not be a problem.)

Something like: 
*) `enhancement` : `a user proposed improvement`
*) `Android`: `mostly/only applicable for Android`
*) for other platforms  the same
*) `bug`: `your bug / something we can solve`
*) `firmware`: `some issues with a certain firmware, doesn't need to be a bug; issue can be solved by a firmware change`
*) `not our bug`: `something which we can not solve, maybe firmware dependend`.
*) `rejected`: `a hard statement, please read the whole thread for explanatione`
*) and so on.

 
And there is `out of date` which means in my opinion, it is old and technically outdated.
And there should be `out of interest, not really wanted` which could mean: Nobody is interested in  this, PR won't necessarily be accepted.

Whats your opinion

**Comment by Frenzie** [comment]
If you don't understand that Android means Android I'm really not sure how repeating that in more words will help, lol

**Comment by zwim** [comment]
Year right. But it is not about Android, it is about the hover feature. If you hover about three tag which show nothing, it could be that you never hover about an other tag :-)

**Comment by Frenzie** [comment]
Anyway, tags are pretty irrelevant to searching for issues imho, except as a developer if you're working on Android you might look to see if there are some quick fixes lying around while you're in there.

**Comment by zwim** [comment]
Are we arguing in circles right now?????

First my suggestion was to add an issue in explaining what which tag exactly means (iirc there have been some discussion in the past about that)

Then it came up that we are even not d'accord right now (see https://github.com/koreader/koreader/issues/10154#issuecomment-1444313756)).

> I'm not sure if won't fix implies patches welcome, agreed on the rest.

Then there was the statement, that anybody can see a context when hovering (but this is not true for all tags, and some tag descriptions are missing, so hovering does not show anything). 

Then my reply that if someone hovered three times, not seeing any more information, won't do that anymore.
And your last reply was 

> Anyway, tags are pretty irrelevant to searching for issues imho, except as a developer

So we are at the beginning of this issue:
https://github.com/koreader/koreader/issues/10154#issue-1594166345

> To give a hint to new developers (or just to show that the KOReader developers are cool and working hard and the number of unsolved issues is small) someone might want to tag old FR in a meaningful way.

So now, what shall we do?
I would propose to add a pinned issue explaining the meaning of each tag (so that hovering works, and also that the devolopers are d'accord)!

**Comment by Frenzie** [comment]
> Then it came up that we are even not d'accord right now (see https://github.com/koreader/koreader/issues/10154#issuecomment-1444313756)).

I don't consider that a disagreement: we have `help wanted` and `rejected` after all for when we're not somewhere in the middle. I think pazos is simply trying to emphasize that it's not rejected, and that might be how I'd prefer to phrase it. But it's either a very subtle distinction or none at all. :-)

> So now, what shall we do?

<img src=https://user-images.githubusercontent.com/202757/221299753-a907507e-813f-4b0f-98f6-f9826f64fb6e.png width=45% align=right> I have to say I'm struggling a bit to understand what concerns you. When I look at the issues I see most of them are tagged meaningfully, and I think we all pitch in to achieve that. It's easier to tag bugs meaningfully (bug, firmware, some specific platform) than feature requests (at best it might relate to a plugin or something). Additionally, a number of years ago I started adding all PRs and issues they close to milestones every month so we now get to enjoy [this](https://github.com/koreader/koreader/milestone/11?closed=1).

When in doubt about an old issue I'd suggest to just ask there. Forums are against necro; I'm not — provided it's actually related to the issue, don't go posting about some brand new Android 13 problem saying it's the same as some mesozoic Android 2.3 issue. ;-)

**Comment by zwim** [comment]
Thanks for your elaboration. I will think about it, and closing this now.

**Comment by Frenzie** [comment]
I'm not sure what kind of music you like, so here's a random selection for the night. ;-P

https://www.arte.tv/de/videos/107208-000-A/emmanuel-tjeknavorian-und-alain-altinoglu/

https://www.youtube.com/watch?v=G3LvhdFEOqs

https://www.youtube.com/watch?v=m2l3pcdlqmk

**Comment by zwim** [comment]
:-)

**Comment by poire-z** [comment]
Except for the obviously crazy ideas, it's often hard to tag early as `rejected` or `won't fix` a FR: ok, it's a direct answer, but it may feel really impolite and hurt the user.
When it's not about part of the code or features that I have experience with or any enhancement would affect me, I just don't comment anything and let the FR/issue be.
When it is (ie. crengine, footnotes, style tweaks...), I just write about why it's complicated/unfeasible and why any implementation would be complicated/twisted and add too much code/maintenance/burden/weakness that it's probably not a good idea and better forget it.
But still not tagging it as "rejected/forget it". It has happened a few times in the past that I had written a lot about why it's a bad idea, and somebody came up with another point of view at the issue and bright ideas that 1) solved the issue/FR 2) without all the complicated problems `I` had envisionned :)

I expressed that elsewhere, but it hurts me in my stomach when I see some of you being polite and write "patch welcome" :) Because no, not welcome: reviewing and being tactful takes time and energy. I don't want anybody to think they can just come up with a quick patch and that we will be happy. For those who dare, despite our absence of encouragements, ok, we'll spend the time and energy.

Also, take the example of the issues/FRs about the .sdr alternate location requests: it's not crazy, and it feels like it is a lot of work that will be fragile and impact a lot of code. It's not something we can "reject", and it's not something we can encourage any "new developper" to have a go at it. So, what tag ? `High hanging fruit` ? :) And when I thought about it, given all the impacted code, I would trust only one person to have a go at it (which he did :) - but then again, I wouldn't want to "assign" the FR to him (which would be a way to say "PR not welcome, just wait" :) and impose some work to somebody else. So, it was best left as untagged in the long meantime.


> And there should be out of interest, not really wanted which could mean: Nobody is interested in this, PR won't necessarily be accepted.

Agree with something like that, it just has to be that tactful and that not encouraging :)

> What about adding another tag: "Patches welcome" (maybe "Patches or User-Patches welcome")?

`User patch welcome` is a great idea ! For half-crazy ideas, or things you know would be hard to implement or justify for the UX: it's not a direct `reject`, just a tactful way to say: we don't want that in the main code, but _we think_ someone can probably quickly solve that with a user patch (that we won't have to review :)
