### ISSUE TITLE
Toggle Bookmark browsing mode via gesture

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10192]
Is it not possible to enable/disable the Bookmark browsing mode via gesture input?

I couldn't find it anywhere in the functions that can be assigned to gestures. It is a pretty nice feature that I only recently discovered and it would be great to be able to call it via gesture.

Thanks

**Comment by hius07** [comment]
Besides, the indicators for Bookmark browsing mode are "open book" in the left top corner and "dogear" in the right, simultaneously.
I find that the dogear in the unbookmarked page is confusing. It is better to find a new icon (maybe just mdlight "bookmark") for the left top corner, without showing the dogear as an indicator.

**Comment by hius07** [comment]
Do we need this in cre documents? (Skim widget does the work perfectly)

**Comment by poire-z** [comment]
(Not familiar with the feature,)

> "open book" in the left top corner and "dogear" in the right, simultaneously.
I find that the dogear in the unbookmarked page is confusing. 

Isn't it just that the dogear in the right is because you are actually browsing bookmarked pages ? :) so, not a sign that this feature is activated, but a sign that it is working by leading you to really bookmarked pages ?
Can you turn page when you reach such a bookmarked page and see non-bookmarked pages before & after ? Then it's good to still see the dogear so you can go back to the bookmarked page you went to, to again navigate to the next bookmarked page ?

**Comment by hius07** [comment]
The dogear appears when activating the mode, as an indicator (line 279).
https://github.com/koreader/koreader/blob/a3d42ac3444f78e354d7aad2926a476f29813fe5/frontend/apps/reader/modules/readerpaging.lua#L271-L291

**Comment by hius07** [comment]
Then, naviagting while staying in the mode, the dogear appears on page-bookmarked pages only, as intended. So we see the left "open book" only (and cannot distinguish whether we are in Bookmark browsing mode or in Page flipping mode).

**Comment by poire-z** [comment]
I see.
So, yes, may be another dedicated icon for each of them ? May be not too different from the existing one (ie. the existing one + a dogear ?) so to not confuse existing users?
Or, totally different ones if we get some imagination :) because they indeed look a bit "old style".
(I guess most of us don't use these modes, but some older users may be accustomed to them, so a bit tough to kill them, even if they are somehow redundant and poor substitutes to Skim and Page browser.)

**Comment by hius07** [comment]
Maybe a (rotated) dogear in the left corner, without "open book"?

Another question to @jonnyl2: now you jumps to the next bookmark which can be either a page bookmark (with a dogear) or a highlighted text. Is it okay? Maybe it should jump to the page bookmarks only, skipping the highlights?

**Comment by jonnyl2** [comment]
@hius07 I like the way it is now; jumping to either highlights or page bookmarks. Especially in reflowable documents I usually prefer using highlights over bookmarks, as changing doc properties like font, margins or device (screen size), etc. messes with the relative bookmark position.

Btw, before discovering this bookmark browsing feature by accident, I used direct gestures or Skim Document to jump between bookmarks, which worked fine. What I really like about the bookmark browsing though is that once you exit out of it, you're always back at where you started from. With the other navigation tools I sometimes got lost in the document and then had to check the Book Map to find my previous position.

**Comment by hius07** [comment]
Got it, thanks.
Just a hint: Skim does not save location history, so after exiting from it `Go back to previous location` will bring you to the start of the trip.

**Comment by hius07** [comment]
<img width="250" alt="02" src="https://user-images.githubusercontent.com/62179190/224479187-4dfbfe4e-46f3-41ca-b544-4dd3d6b03853.png">

**Comment by jonnyl2** [comment]
> Just a hint: Skim does not save location history, so after exiting from it `Go back to previous location` will bring you to the start of the trip.

That's good to know, thanks. What remains is that the navigation window covers quite a large part of the screen which makes the tool impractical to use if you want to review the pages' contents. Also, you can't do things like editing highlights, look up dictionary entries, etc. without closing the window.
