### ISSUE TITLE
FR: Change daily hourly range for reading statistics

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10250]
KOReader's reading statistics features and calendar views are very helpful and user-friendly.

However, I spend a lot of time reading between the hours of ~23:00-01:00 (or similar) and these reading sessions are then reflected as two separate days on the calendar, which (although technically correct) makes little intuitive sense. Also, if I'm reading in the afternoon and check how much time I've already spent reading that day, I'm not interested in the time I spent  before I went to sleep (e.g., 0:00-0:55), as I would consider that the previous day. Further, if I check the "days reading this book" info on a book, it will also list the dates where I only read for a few minutes past midnight, even if I didn't open the book again later that day at all. 

I would suggest that the Statistics Calendar is changed such that a day starts at 4:00 and ends at 3:59, and that the reading statistics collected for this entire time range are counted towards the same day accordingly. Or, that the daily beginning hour can be manually adjusted by the user, if this doesn't complicate things too much.

Thank you for considering this request.

**Comment by jonnyl2** [comment]
I just realized there have been discussions on this issue, so I'm closing this.

**Comment by poire-z** [comment]
> I just realized there have been discussions on this issue, so I'm closing this.

Where ? Cross reference please :)

**Comment by jonnyl2** [comment]
Shortly after posting I found open case #2978 which requests a resolution to a similar issue. Although I just noticed now that that case is several years old. So if you'd like to reopen this one then that would certainly be fine with me.

Thanks for checking in.

**Comment by poire-z** [comment]
Like we have a `Calendar weeks starts on Monday>`, I think we could have a `Day starts at 04:00` (the default would still be 00:00 to keep things natural).
Then, I guess it may be just a matter of accounting for that and adding/substracting 4*3600 in _a few_ selected places :)
It probably shouldn't impact the month view, only the day timeline view, and may be the Time spent reading today & Pages read today - and nothing else.
(pinging @weijiuqiao for thoughts, and in case you are bored :)

**Comment by weijiuqiao** [comment]
Since the calendar view is kind of a preview of each day's view, it might be more reasonable to have them synchronized?
I'm not very bored unfortunately 😂  I recently got a new job which is quite demanding. But I can still take a look at this one :)

**Comment by poire-z** [comment]
Good for you :)

> it might be more reasonable to have them synchronized?

Yes, it should be the default, but I can see the appeal for some users to have a small shift if they are used to read up to 2am - and start afresh when they wake up at 8am, like me - although if this was implemented, it may happen I'll find it confusing and will soon be back to the default. So, dunno if it's worth it :)

There is also another issue (that you probably can't experience if you don't have DST in your country):  https://github.com/koreader/koreader/issues/10248#issuecomment-1485032900

**Comment by protist** [comment]
I just installed Koreader on a new system, and realised that this had been implemented. Thank you! That's a great start to partway addressing #2978 (which I originally filed). I just wanted to note that while the fix here addresses the graphical daily and monthly outlines, IMO the part that is more important is addressing the text statistics. Personally, that's where I go to see how much I have read "today". i.e. Tools icon > `Reading statistics` > `Current book`. (FWIW `Reading progress` also needs to be fixed.)

**Comment by jonnyl2** [comment]
I agree; seeing accurate daily reading statistics (a "day" in the sense of the time from getting up in the morning to going to bed at night) was also the main idea of my initial issue. There is also #12371 requesting this.

I am not sure how this could be implemented, though. I was thinking that perhaps the SQL-queries for the daily reading times could be offset by the setting somehow. Maybe it would make it easier if instead of allowing any hour to be set as the starting time for day, we allow just two settings: the standard 0:00-0:00, and an alternative 4:00-4:00. That latter one should probably cover 98%+ of users interested in this feature. 

@weijiuqiao, do you have any thoughts?

**Comment by protist** [comment]
FWIW I just found a very similar stat in the tools icon menu > `Reading statistics` > `Today's timeline`, as per this image from #10752. Here the duration correctly accounts for the altered time for "new day". Perhaps this might make it easier to port this value onto the other statistic views? Also, FWIW I also set the time to 4:00, so that's consistent with your suggestion @jonnyl2 .

![daily statistics graph](https://private-user-images.githubusercontent.com/95502269/256353102-50d77ea0-e286-4d55-a888-7fa17db646b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDY4NDQsIm5iZiI6MTczMDYwNjU0NCwicGF0aCI6Ii85NTUwMjI2OS8yNTYzNTMxMDItNTBkNzdlYTAtZTI4Ni00ZDU1LWE4ODgtN2ZhMTdkYjY0NmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA0MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MDI3NmE2ODVjZGFkZDBjZWRiYmU2NWU5YmRkYzEwZmNkYjQ5YjBjMTE2YmNhNjU4YWM5NDQ5MWUzYjJhYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1NSMrxcPjY_lIc1Tr943c9bbHQCA3t5v2OxN5hscZ3Q)
