### ISSUE TITLE
FR: Add interval between tap and horizontal swipe when reading

### ISSUE THREAD

**Issue by kaznelson** [koreader/koreader#10265]
_**Does your feature request involve difficulty completing a task? Please describe.**_
Both tap and swipe have been enabled in the "Turn pages" settings menu.
Tap interval in the "Gesture intervals" settings menu is enabled and set 400.
But when an extra/random tap occurs after a horisontal swipe (or vice versa), there is no interval between them.

_**Describe the solution you'd like**_
Is it possible to add a interval between tap and horisontal swipe when reading to "Gesture intervals" settings menu?

_**Describe alternatives you've considered**_
When tap and swipe page turning, there is no alternative solution.

**Comment by NiLuJe** [comment]
> Tap interval in the "Gesture intervals" settings menu is enabled and set 400.

:scream:  Why?

**Comment by NiLuJe** [comment]
But after overcoming my initial horror, no, the interval is very specifically tied to the tap state, a cross-state interval would be a *nightmare* ;).

**Comment by kaznelson** [comment]
**NiLuJe**
Arthrosis of the fingers. Random-erroneous tap's are regular... :(

**Comment by NiLuJe** [comment]
I was afraid you were going to say something like that :/.

To expand on my previous answer, I've scrapped a few round of design *and* implementations of the gesture engine because they were too bogged down by cross-state and/or cross-contact tracking; and this would require *both* (otherwise, suddenyl two-finger gestures don't work anymore because the second contact gets debounced ;o)).
