### ISSUE TITLE
Downgrade option

### ISSUE THREAD

**Issue by tjimofbis** [koreader/koreader#10379]
Please add the ability to choose previous stable versions of the software in case there is a critical error in the current stable build.

**Comment by NiLuJe** [comment]
They don't magically disappear from the server, everything is archived at https://github.com/koreader/koreader/releases and (for several months, at least) on the OTA server.

Plugging that into the UI is not really feasible, because that's not how it works (zsync).

**Comment by NiLuJe** [comment]
Plus, the standard operating procedure if a critical error *does* manage to sneak into a stable, is that we fix it and roll a new patch release ;).

**Comment by pazos** [comment]
> Okay, how about providing the option to roll back to the version of the software that was installed before the update? 

Not possible

>> because that's not how it works (zsync).

> Or making it optional to backup the installed version of the software before update?

It is actually optional. On an actual reader you can always backup the entire installation directory before applying an update.

But there're no plans for integration on the UI because there's no good reason to do so:

1. If there's a critical error you need to apply the changes yourself (as you did recently), you get the same output by applying a saved backup or unziping a previous release (your settings are kept, never overwritten)
2. Doing a backup on each update wears your storage a lot, wastes your space and involves some cpu time if you want an archive with all the files inside.
3. Also, a feature like this would require cleaning previous backups after the update went ok but before we add new backups (but how many shall we keep?, shall we add a setting for that too?)

**Comment by NiLuJe** [comment]
It would also mean that we'd actually have to technically support
downgrades. We don't. The only downgrades that should be done should be
done so under developer supervision (because we know how far back it's safe
and/or relevant to issue x or y), or after a full backup if unsupervised.
