### ISSUE TITLE
Reading Progress Menu shift to right in RTL language

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#10386]
* KOReader version: 2023.04-12
* Device: KindlePW 3

#### Issue
in RTL language (Persian and Arabic tested) Reading statics shift place similar to screenshots
English Correct
![english](https://user-images.githubusercontent.com/25131576/236009285-1ead41cf-09d5-4a1b-a1c7-f312b6b20138.jpg)
Persian menu Shift
![persian](https://user-images.githubusercontent.com/25131576/236009363-185c5397-aa5f-446c-83bc-185486db1e5d.jpg)
Arabic menu Shift
![arabic](https://user-images.githubusercontent.com/25131576/236009437-4cf4cb96-42db-41ce-91b5-b634f5d1c86f.jpg)

#### Steps to reproduce
1. change Koreader language to Arabic or Persian (RTL language)
2. open menu from top with swipe
3. go to Reading statics > Reading Progress

like above screenshot whole menu shift to right of screen
if you back  to English menu show in correct position

**Comment by Frenzie** [comment]
What specifically should be different?

**Comment by poire-z** [comment]
There is an issue, the content is shifted to the right, and there's a big blank column on the left:
![image](https://user-images.githubusercontent.com/24273478/236022535-475cae5e-64bd-45f7-a6d0-f464df5e7fb0.png)

It's something I met often when adapting for RTL UI, so there's probably an easy fix.

But this menu must be the KOReader thingie that has been the less visited/modified since its birth.
It is badly built and sized, here's how it's been looking for ages on my small emulator, truncated, overlaps...:

![image](https://user-images.githubusercontent.com/24273478/236023089-ec911d34-fce0-420f-b00c-c3c3149f56fa.png)

If it were just me, I would just remove it :)
Is there some people really using it ?

**Comment by Frenzie** [comment]
> There is an issue, the content is shifted to the right, and there's a big blank column on the left:

Oh, I didn't realize that was part of the image. It's all just white over here. :-)
