### ISSUE TITLE
FR: warmth toggle

### ISSUE THREAD

**Issue by ghost** [koreader/koreader#10385]
**Does your feature request involve difficulty completing a task? Please describe.**
On Boox Leaf the "toggle frontlight" only toggles cold light, leaving warm light untouched.
So the default gesture for tap bottom left corner only toggles cold light. If you edit it to also set warmth to 0, it works as intended (for disabling the frontlight at least). But when tapping it again only cold light is turned back on.

**Describe the solution you'd like**
I'd like a gesture for "toggle warmth", alternating it between 0 and whatever setting it was on before. This way on the Leaf model users can simply include that gesture in the bottom left corner tap to make it work as intended.

**Describe alternatives you've considered**
I'm not sure if the frontlight toggle is working correctly on the Leaf. It's possible something is missing that is making it control only the cold light or maybe that's how it's meant to work. Maybe that can be fixed instead if so.

**Comment by pazos** [comment]
It should toggle both, like in the rest of platforms.

I'm not sure if it works that way on any other android eink device. AFAIK warmth lights were added long time after the rest of android stuff. Maybe @zwim knows, as he used to have a Tolino and did quite a lot android development.

Anyhow, none of the developers/contributor has an android eink device, so we cannot fix it.

Help very welcome :)

**Comment by NiLuJe** [comment]
That's going to be problematic on the Aura One, where warmth and brightness are tied, FWIW ;).

**Comment by pazos** [comment]
pinging @mergen3107, IIRC you were trying to do something related to this ticket. In case you want to try the suggestions above.

**Comment by mergen3107** [comment]
Thanks @pazos !
I’ll try shen I have time

**Comment by mergen3107** [comment]
Sorry guys, I am slowly going through all my pings. 

#8120 is the PR I started once, but then lost interest in, because I assigned the physical back button (using ButtonMapper app) to open frontlight window from Onyx upon long press. So, I didn't need KOReader's switches anymore.
(Another alternative is using GentleGlow app with button bindings, swipe bindings from Onyx, or just from the notification shade). 

Feel free to get some ideas from there. It needed some general improvements which I didn't get to fix. 

Now I don't have Onyx Boox on hand all the time, so I can't promise to fix it.
