### ISSUE TITLE
touch issues with sway nightly

### ISSUE THREAD

**Issue by hrdl-github** [koreader/koreader#10417]
* KOReader version: 2023.04
* Device: Surface Go (mainline Linux), PineNote (both sway nightly with the wayland backend)

#### Issue
I've been using sway nightly as it features support for cancelling gestures. Before https://github.com/swaywm/sway/commit/4666d1785bfb6635e6e8604de383c91714bceebc touch events did not affect the pointer, which is consistent which e.g. plasma-wayland. Since https://github.com/swaywm/sway/commit/4666d1785bfb6635e6e8604de383c91714bceebc touch down events induce a cursor leave event if it was on the same surface, and the last touch up event induces a cursor enter event. See https://github.com/swaywm/sway/issues/7577 for some sample wayland events.

When the cursor is on KOReader and a touch down and a touch up event are induced to initiate a tap, SDL also fires a `TOUCHMOTION` event, probably due to the cursor being restored. This results in not a tap gesture, but a pan gesture.

I can provide some logs if you think this makes sense, but I think my description covers everything of relevance. I saw that https://github.com/koreader/koreader-base/pull/1599 introduced a non-working (and therefore commented out) check https://github.com/koreader/koreader-base/blob/66b21534def34109c478759adb75364ac13694a4/ffi/SDL2_0.lua#L369
The check does not work because `event.motion.which == 0` (vs -1).

I'm not sure yet if this is an issue with KOReader, SDL, or sway. I'm filing an issue here because I'm beginning to think that sway's behaviour is not unreasonable despite differing from e.g. plasma-wayland.

#### Steps to reproduce
1. Install a recent nightly version of sway (and wlroots)
2. Launch KOReader. Place the cursor on KOReader
3. Initiate a touch event with the intention to tap

**Comment by Frenzie** [comment]
> I saw that https://github.com/koreader/koreader-base/pull/1599 introduced a non-working (and therefore commented out) check https://github.com/koreader/koreader-base/blob/66b21534def34109c478759adb75364ac13694a4/ffi/SDL2_0.lua#L369

Either the comment or it being there at all is a mistake.

**Comment by Frenzie** [comment]
> I can provide some logs if you think this makes sense, but I think my description covers everything of relevance. I saw that https://github.com/koreader/koreader-base/pull/1599 introduced a non-working (and therefore commented out) check https://github.com/koreader/koreader-base/blob/66b21534def34109c478759adb75364ac13694a4/ffi/SDL2_0.lua#L369
The check does not work because event.motion.which == 0 (vs -1).

You managed to confuse me with "non-working (and therefore commented out)". ^_^ It works perfectly; I'd merely accidentally left it commented for whatever reason because the overall effect is indistinguishable for our purposes. It's just an extra event saying effectively the same thing.

**Comment by Frenzie** [comment]
> When the cursor is on KOReader and a touch down and a touch up event are induced to initiate a tap, SDL also fires a TOUCHMOTION event, probably due to the cursor being restored. This results in not a tap gesture, but a pan gesture.
> 
> I can provide some logs if you think this makes sense

This description doesn't make much sense to me actually, because you're simply describing a completely normal click or tap. There will always be a few pixels of movement.

**Comment by Frenzie** [comment]
In short, if you want to trigger an accidental swipe you have to give it a really enthusiastic try. An intentional tap rarely generates more than about 5-10 physical px of movement even at 300 DPI, and note the `scaleBySize()` on there meaning you'd have to go closer to 70. Which is simple to do, just a little flick, but if you're having a fake mouse movement at the same spot where you just lifted your finger, no matter how silly that might be for SDL to do, it doesn't seem that it should normally cause any issues.

https://github.com/koreader/koreader/blob/d8b3878e8afd700f138606e8e720611f289cc0e2/frontend/device/gesturedetector.lua#LL117C22-L117C22

**Comment by Frenzie** [comment]
There's nothing to fix. Or that's not true exactly, as I stated [here](https://github.com/koreader/koreader-base/blob/66b21534def34109c478759adb75364ac13694a4/ffi/SDL2_0.lua#L230-L231) a tester can easily trigger this scenario by using a mouse and a touchscreen simultaneously,[1] which could be avoided by using first come first serve, but the specific problem here is a bug in sway or SDL. That mouse movement should come after up, not before.

[1] Though much more easily in the reverse manner by clicking with a pointing device and doing a tap somewhere with a finger to trigger a swipe.

**Comment by Frenzie** [comment]
Anyway, I was planning to fix that actual issue eventually but you're welcome to submit a PR. ;-)
