### ISSUE TITLE
Resize events at launch time are missed with setting start_with = "last"

### ISSUE THREAD

**Issue by hrdl-github** [koreader/koreader#10427]
* KOReader version: 2023.04
* Device: SDL, wayland and x11 SDL backends. Tested under sway

#### Issue
When KOReader loads a document instead of the file manager at start-up SDL events are temporarily discarded. This includes window events that affect resizing, leaving KOReader with the default 600px x 800px buffer. Resizing the window afterwards fixes the issue.

#### Steps to reproduce
1. Use a tiling window manager, which by default ignore requests for specific window sizes
2. Configure `start_with = "last"`
3. Open a document
4. Restart KOReader. The document is either disorted or occupies only part of the window. Updating the view will result in a distorted document.

##### koreader.log
[koreader.log](https://github.com/koreader/koreader/files/11463792/koreader.log)

**Comment by poire-z** [comment]
Possibly caused by some `Input:inhibitInput(true)`  , that we have in a few places, like this one probably hitting you:
https://github.com/koreader/koreader/commit/81f2aed086ac98a08a24b37d67cb9db8028478c3#diff-5ae53f0997771f2561fbab2fe2cd8b2bcc0db70393b7e5c4c49e788440ee11a9R113

These are needed on Android to prevent "application not responding", and useful on other devices so any tap done while the document is loaded are not processed once it is loaded (and move you a few pages away from the last page you didn't even see).
So, I don't know how we might adress that, so `some` events are kept/processed once the loading is done - or just delay the document loading.

> This includes window events that affect resizing

Do you mean user window resize events, ie the user resizing manually while seeing "Opening..."?
Or some generic Window manager stuff that should be processed at startup before we block with "Opening..."?

**Comment by poire-z** [comment]
We already don't inhibit some events, around here:
https://github.com/koreader/koreader/blob/a52a4158a95fadb3e0d09d4ef04c0d1cb78c0317/frontend/device/input.lua#L1382-L1407
Wait for @NiLuJe thoughts, if it's the right way to handle this case.

**Comment by NiLuJe** [comment]
I don't really see a cleaner solution than *not* monkey-patching `handleSdlEv` there.

It actually makes perfect sense, as that is neeeearly only used for actual non-input events... except for a weird bit of manual mousewheel panning emulation (which is in front instead of the actual SDL input handler in base because it directly sends GestureDetector events, so it has to go through UIManager, I guess?).
I imagine a proper fix would be handling the wheel properly, period; but that's another kettle of fish.

**Comment by poire-z** [comment]
But, assuming the order of things is the following:
- start koreader
- load the document, rendered for the initial screen size
- we get sent a resize event by the tiling window manager
- we're done loading & rendering, and if the resize event is processed at this point, there goes a new rerendering (or partial rendering + animation + reload) - which is not a fun user experience :/

I don't know the delay until this resize event, but may be, on SDL (only?), we should just scheduleIn() the loading to give a chance for any "late startup" event to be processed?

As for the next blockings (after a good startup and document displayed) when changeing settings and rerendering, I guess it's for the user to not play with resizing, or if he does, to bear the rerendering it will cause (but with partial rerendering, it's now less an issue).

**Comment by NiLuJe** [comment]
I can't test that, so I haven't even looked/thought about the actual timings involved ;).

**Comment by Frenzie** [comment]
@NiLuJe 
> It actually makes perfect sense, as that is neeeearly only used for actual non-input events... except for a weird bit of manual mousewheel panning emulation (which is in front instead of the actual SDL input handler in base because it directly sends GestureDetector events, so it has to go through UIManager, I guess?).

Yes, doing that in front makes it possible to improve, doing it in base would be convoluted and bad. Also compare the gamepad stuff which works reasonably well but I find it inelegant.

**Comment by NiLuJe** [comment]
Regardless of the timing concerns raised above, `Input:inhibitInput` was only ever meant to nerf *input* events, so leaving SdlEv (mostly) alone makes perfect sense (e.g., we leave Android events alone).

Given the mwheel concerns raised above, a simple approach would be to go through a simple wrapper that passes through every event except for `ev.code == SDL_MOUSEWHEEL` instead of just ingoring *everything* via voidEv.

**Comment by NiLuJe** [comment]
Something along the lines of

```diff
diff --git a/frontend/device/input.lua b/frontend/device/input.lua
index dee9fcf53..9b4da110c 100644
--- a/frontend/device/input.lua
+++ b/frontend/device/input.lua
@@ -1404,7 +1404,16 @@ function Input:inhibitInput(toggle)
         end
         if not self._sdl_ev_handler then
             self._sdl_ev_handler = self.handleSdlEv
-            self.handleSdlEv = self.voidEv
+            -- This is mainly used for non-input events, so we mostly want to leave it alone (#10427).
+            -- The only exception being mwheel handling, which we *do* want to inhibit.
+            self.handleSdlEv = function(this, ev)
+                local SDL_MOUSEWHEEL = 1027
+                if ev.code == SDL_MOUSEWHEEL then
+                    return
+                else
+                    return self._sdl_ev_handler(this, ev)
+                end
+            end
         end
         if not self._generic_ev_handler then
             self._generic_ev_handler = self.handleGenericEv
```

(Untested)

**Comment by NiLuJe** [comment]
Or ```diff
diff --git a/frontend/device/input.lua b/frontend/device/input.lua
index dee9fcf53..b3c0d1d7b 100644
--- a/frontend/device/input.lua
+++ b/frontend/device/input.lua
@@ -1404,7 +1404,16 @@ function Input:inhibitInput(toggle)
         end
         if not self._sdl_ev_handler then
             self._sdl_ev_handler = self.handleSdlEv
-            self.handleSdlEv = self.voidEv
+            -- This is mainly used for non-input events, so we mostly want to leave it alone (#10427).
+            -- The only exception being mwheel handling, which we *do* want to inhibit.
+            self.handleSdlEv = function(this, ev)
+                local SDL_MOUSEWHEEL = 1027
+                if ev.code == SDL_MOUSEWHEEL then
+                    return
+                else
+                    return this:_sdl_ev_handler(ev)
+                end
+            end
         end
         if not self._generic_ev_handler then
             self._generic_ev_handler = self.handleGenericEv
```

`self` should match `this`, it's `Input`, and it's a singleton. But it's the convention we use for other custom handlers anyway ;).

**Comment by Frenzie** [comment]
Seems fine for now.
