### ISSUE TITLE
FR: "Enable Partial Renderings" Please add an option to Surpress graphical depiction of internal processes

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#10437]
KOReader Enable Partial Renderings

The stated purpose of the "Enable Partial Renderings" option is to allow these internal processes to take place without interrupting the user.

When selected, however, the reader is interrupted by graphical animations in the upper right corner of the text, completely negating any intended advantage of this preference setting.

Can we please have the option to suppress the graphical depiction of the system's internal machinations?

**Comment by poire-z** [comment]
> The stated purpose of the "Enable Partial Renderings" option is to allow these internal processes to take place without interrupting the user.
> completely negating any intended advantage of this preference setting.

Nope. The stated purpose or intended advantage is to have quicker rendering/preview of the current chapter so the user can judge if this is good enough or not.
It is not so the user can just go on reading (of course, he can) because many things are screwed at this point, so he better know that with these icons - and we want to let him know koreader is blocked reloading at some point.
So, no, I don't think we should have an option to discard such information.
And you're not touching settings that often when really reading, so you shouldn't see these icons often.

**Comment by poire-z** [comment]
Also see https://github.com/koreader/koreader/issues/10392#issuecomment-1536389255.
> If you really want to have what you wish - for yourself, and live with the side effects, I'm quite sure you could user-patch some frontend/apps/reader/modules/readerrolling.lua methods to not trigger that full rerendering and not show the icons - and live with that unsane state until you trigger a document reloading via a gesture - which should do the proper rerendering when the document is reloaded.

So, you could probably user-patch these icons/animation out - but your responsability :)

**Comment by zmixnyc** [comment]
Yes I understand..

You say: "The stated purpose or intended advantage is to have quicker rendering/preview of the current chapter _**so the user can judge if this is good enough or not**_."

If the user does not have a choice to abort the process, then it's functionally no different than waiting for full renderings, innit?

 If the intention is to break down the various processes into separate procedures  and allow the most important user interface functions to be restored quickly (such as page turns), in an attempt to be the least disruptive to the user, then why not add an option to suppress the internal behavior, you could add an explanation "Certain Functions may be unresponsive while document is being processed".    Windows had an intrusive GUI thing called "clippy" that would assert itself in a similar way - usually quite distracting.

**Comment by NiLuJe** [comment]
Except you then have no no idea when/how/why stuff is randomly broken and for how long, which is.. worse?

(Unless you have some wonky DPI settings or a really old/tiny device, that icon should be barely visible).

**Comment by zmixnyc** [comment]
> Except you then have no no idea when/how/why stuff is randomly broken and for how long, which is... worse?
> 
> (Unless you have some wonky DPI settings or a really old/tiny device, that icon should be barely visible).

True, which is why it would be an option for the advanced user...

**Comment by NiLuJe** [comment]
At which point we're back to user patches, which is the ultimate "for the advanced user" approach ;).

**Comment by NiLuJe** [comment]
To expand on that, I think that both disabling the icons *and* having an option to do so would be actively harmful to UX.

I absolutely *abhor* the "no chrome" approach of "modern" (read: Apple) UIs. I *want* to know what the fuck is happening, always, everywhere, all the time. And, if possibly, *why*.

**Comment by poire-z** [comment]
> If the user does not have a choice to abort the process, then it's functionally no different than waiting for full renderings, innit?

Yes, we'll have to reload, even if you go back to the previous setting.
But if you do, you'll see that the icon with the gear is displayed for a really short amount of time (because the previous cache file is valid for the settings you went back to), so, there's that :) Showing the details make the user knoledgable and having a grasp of what's happening, figuring out his own conclusions.

> If the intention is to break down the various processes into separate procedures and allow the most important user interface functions to be restored quickly (such as page turns) in an attempt to be the least disruptive to the user, then why not add an option to suppress the display of internal behavior

Because KOReader is explicite and honnest :) It doesn't do things behind your back, it doesn't pretend it knows things better than you, how the book should look... That's why you're using it, isn't it ? :)
And yes, I'm like @NiLuJe : I want to know what's happening. So, our dev/geek mindset goes in how it's desgined. We're anyway trying to make things smooth and simple, but not to the expense of going too obscure (ie. style tweaks have a simple description, and with long-press you see the technical CSS).

> (it's like a waiter at a restaurant talking over your conversation to tell you he's pouring you some water) 

Which is fine by me :) and hmmm, you requested to get that water (you did change the settings :), the waiter and his kob deserve a bit of respect and being looked at with a smile :)

And again, you're not always requesting your glass to be filled during that dinner ! so, you'll have most of the time to yourself for your private conversation, and reading :) Clippy will be soon gone.
If you're constantly tweaking settings and are annoyed by our Kolippy, you may have another problem (and your reading statistics must be full of holes - unless Kolippy distracts you enough for you to not turn pages :) he then has done his job !)

Again, user patches for things you are really annoyed with. Even myself, I patch KOReader for many things I don't dare propose here.

**Comment by Frenzie** [comment]
> I absolutely abhor the "no chrome" approach of "modern" (read: Apple) UIs. 

That's being very kind to non-Apple.

**Comment by offset-torque** [comment]
I understand your irritation **zmixnyc** because the indicator catches my eyes too. But I too think this indicator is necessary to communicate **"Hey I am still working here"** to the user (reminds me of the HDD light on the PCs). 

I think part of the problem is that the indicator is new so it is getting your attention strongly (because it is an unexpected stimuli). With time your brain will learn to ignore it since it is really tiny and don't stay there for long. As an example, when "highlight indicator" was added, it was getting my attention too automatically like this. Now I barely notice it. Maybe just give yourself time to accomodate.

**Comment by poire-z** [comment]
Consensus on not having such option.
User-patching that should be doable for the really needy.
