### ISSUE TITLE
Wikipedia ePubs are unreadable

### ISSUE THREAD

**Issue by ajs256** [koreader/koreader#10459]
* KOReader version: 2023.04
* Device: Kindle PW5

#### Issue
Most ePubs downloaded through KOReader's builtin Wikipedia tool are unreadable, only having one page with the title and occasionally some content from the start of the article.

#### Steps to reproduce
1. Search Wikipedia for anything (I first noticed this with the article [`SAT`](https://en.wikipedia.org/wiki/SAT). 
2. Save the article as an ePub.
3. Open it.
4. Notice that you can't read any content.

I can provide KOReader's logs if you can't reproduce it, but I'm not near my Kindle right now.

**Comment by poire-z** [comment]
I can reproduce with your article (but no problem with a few other Wikipedia FR articles I tried).
Looks like it is because there are unbalanced/unclosed `<link>` among these
```
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1033289096">
[...]
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1129693374">
```
so the text stops there, and the remaining is considered inner content of `<link>` waiting for a `</link>`.

crengine uses an XHTML/XML parser for EPUBs, so it expects balanced HTML.
We used to get that from Wikipedia API, but I guess they failed it here :/

I guess we can just fix (or remove) any `<link.*>`, among the other massages we do in:
https://github.com/koreader/koreader/blob/7e98b9de4b5917a2568779d7281cfc67e770c73d/frontend/ui/wikipedia.lua#L1217-L1274
