### ISSUE TITLE
Disable/Hide fonts

### ISSUE THREAD

**Issue by ShinxA1** [koreader/koreader#10613]
Hi, I'm using KOReader on Kindle Paperwhite 5 and would like to know if it's possible to hide these fonts? that's 24 fonts and only Bookerly which I use *rarely*. I would like only the fonts I use for reading to be visible. In the "Font Settings" menu, I disabled the "Use additional fallback fonts" option, but nothing happens. 
Thanks for KOReader! :D

![Reader_2023-06-25_075323~2](https://github.com/koreader/koreader/assets/127334528/13730bca-791d-4395-88ab-a9d7fc5127cf)

**Comment by pazos** [comment]
Already requested in https://www.mobileread.com/forums/showthread.php?t=332219

And already answered in https://github.com/koreader/koreader/issues/6107#issuecomment-672712604

**tl;dr**: not planned

**Comment by pazos** [comment]
Oh, wait. System fonts can be toggled on/off on different platforms. https://github.com/koreader/koreader/blob/master/frontend/ui/elements/font_settings.lua

Pinging @NiLuJe about the kindle

**Comment by hius07** [comment]
Nope for Kindle and Kobo
https://github.com/koreader/koreader/blob/b8af326836374b82cccdadafef869d1d5decac69/frontend/apps/reader/modules/readerfont.lua#L710-L713

**Comment by pazos** [comment]
Yup, I know that. I was pinging to see if there's a way to implement the same on kindles. Don't know if you, @hius07, have a kindle and/or you're willing to implement/test.

**Comment by NiLuJe** [comment]
We already blacklist a metric shitton of system fonts on Kindle, for various compatibility reasons over the years; so I'm not quite sure I see the interest?

(Also, there are relatively few families shipped, and they're all pretty decent).

**Comment by poire-z** [comment]
In some of these requests, I think I understand these users want to not see OUR shipped fonts (ie. Noto Sans*, FreeSans, FreeSerif...), to somehow get their 3 preferred fonts in a single menu.

**Comment by jonnyl2** [comment]
Piggybacking on this FR; for some time I've had the idea of submitting a FR for a more elaborate font manager, which provides a larger preview window for installed fonts (full screen, with custom preview text) and that allows adding fonts to a favorites list (the latter probably also addressing the mentioned requests here). 

(The existing option of producing a font test document with all installed font is excellent, but if new fonts are frequently installed and tried out, a more 'live' option would be more user-friendly.)

If there is any interest by the developers I am happy to discuss the idea further.

**Comment by poire-z** [comment]
> provides a larger preview window for installed fonts (full screen, with custom preview text) 

For this preview window to really show the font quality, we'll want crengine to render that preview text - and we currently can't have crengine display multiple documents/text (crengine could, but really too much work in frontend to drive that).
So, switching documents would be all we could do - which is what happens when you generate the font test document. And this font test document would then display only your single font, which is a bit limited - I am often comparing a new font with my existing favorites (and others, to see if it's not too similar to another one).
So, a single font display preview feels a bit useless to me. Not really interested.

> allows adding fonts to a favorites list (the latter probably also addressing the mentioned requests here).

Well, my thoughts it that we don't need to address these requests :)
People having really different favorite fonts can make themselves a quick menu (does that work? I think @mergen3107 does that), or assign each to a gesture.
I think the current menu should show them all to indicate which are fallbacks, which are monospace, and what is there and could be used by crengine. I don't feel like masking things (and adding hard to explain mask/unmask/favorize menu items) that could make it even less clear.

I must say I'm lucky: my 2 favorite fonts, Bitter and Capita, happen to fall in the font list first menu :) so I'm not annoyed with having to navigate menu pages to switch between these 2. I understand other users may be, so their request. But QuickMenu might be the solution for them.
Not sure it is our job to generate a alt menu with all but our fonts - some users may like ONE of our fonts and want it included in their "alt menu".

**Comment by mergen3107** [comment]
Yep, I use QuickMenu with one profile per one font (+ line spacing + size + font weight, so I have the same number of lines on each font, but that’s unrelated here). 

So all these profiles have “show in action list”, then one gesture has all these profiles selected + “show as quick menu” enabled. So that when you active the gesture, you see all those profiles you checked. 

Works like a charm! I have like 6-7 fonts that I mostly use, and honestly I find it hard to appreciate new fonts because generally speaking I have most of the various arch-types of fonts so to say, so they differences are much less noticeable on new fonts. 

I set this up a few months ago and never tweaked them again.

**Comment by jonnyl2** [comment]
@poire-z (or anyone), let me suggest something a bit more simple, without any separate favorites list or complex font preview. Feel free to shoot it down again :)

In the Book menu, introduce a new Font Manager option. This will open a new full-screen window listing all fonts, with a checkmark next to each font (akin to the "Manage installed dictionaries" feature). By default, all fonts and newly installed fonts are checked. Only checked fonts are listed in the Fonts list (the current menu option to change the book font). If users don't want certain fonts to be listed there, they can simply uncheck them in the Font Manager, but they will still be available for system use. 

Things to consider:

- Fonts can be listed either in plain text or in the respective typeface (the former is probably easier)
- Allow (or don't allow) sorting the fonts (again, like in the dictionary manager, where sorting is possible). If possible, sorting them would also change the order in the Font menu where the actual selection is made.
- I would suggest to add a `Generate font test document` button in this manager so one could generate a test document after checking/unchecking the desired fonts. Only selected fonts will be reproduced in the document.

**Comment by poire-z** [comment]
Sorry, but not interested :/
We have something simple and consistent that works, no need to complexify that (and for us to work on something we mostly don't need and I can't advocate for). And people who want access to a subset of them can use a QuickMenu.

(Alternative idea: `Font settings > [ ] Show fonts sorted by most recently used`, so your 3 favorite fonts end up in the first pannel. Selecting a font in any book would update an array in the global G_reader_settings, used for sorting the fonts in that menu after alphabetical ordering.)

**Comment by jonnyl2** [comment]
>Alternative idea: Font settings > [ ] Show fonts sorted by most recently used

I like the idea! To me personally that makes more sense than a QuickMenu, because my taste and preferences keep changing :)
