### ISSUE TITLE
FR: Page turn animation for android

### ISSUE THREAD

**Issue by mshoumans** [koreader/koreader#10622]
Kindle has page turn animations. I wonder if Koreader has plans to support page turn animation or any kind of page animation in the future?

**Comment by NiLuJe** [comment]
What's available on Kindle is a driver-level feature, so, no, not really.

**Comment by ALmnoo** [comment]
> What's available on Kindle is a driver-level feature, so, no, not really.

KT6 uses MT8110 CPU, the same as PW5, and it also supports page turning animation, but Amazon does not seem to enable it on FW, so we can see that it works after enabling page turning animation on KOReader. I think it should be possible to enable it by modifying the system file, but since I don't understand the code of Kindle firmware, I have no way to do this. Do you know how to do it?

**Comment by ALmnoo** [comment]
> Kindle 上提供的是驱动程序级别的功能，因此，事实并非如此。

@NiLuJe KT6 uses MT8110 CPU, the same as PW5, and it also supports page turning animation, but Amazon does not seem to enable it on FW, so we can see that it works after enabling page turning animation on KOReader. I think it should be possible to enable it by modifying the system file, but since I don't understand the code of Kindle firmware, I have no way to do this. Do you know how to do it?
