### ISSUE TITLE
FR: 7-zip (or Zstandard?) file support

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [koreader/koreader#10675]
7z files offer noticeably better compression in many cases - 7zip support (in the manner of zip) would be really nice.

My problem stems from needing to fit many text files onto a small storage space - converting an ebook to .txt and then zipping it works well, but compressing it as 7z works even better. And even marginal gains add up over the span of enough files.

PS: here's a neat batch script to do such bulk txt conversion for all epubs in the current directory:
`for /r %%1 in (*.epub) do "C:\Program Files\Calibre2\ebook-convert.exe" "%%~dpn1.epub" "%%~dpn1.txt"`

Another script to compress all the txt files to zip (in the naming format Koreader supports) in the script's directory recursively:
```
setlocal enabledelayedexpansion

for /r %%F in (*.txt) do (
  set "filename=%%~nF"
  set "extension=%%~xF"
  set "newname=!filename!!extension!.zip"
  "C:\Program Files\7-Zip\7z.exe" a -tzip -mx9 "%%~dpnF.zip" "%%F"
  ren "%%~dpnF.zip" "!newname!"
)

endlocal
```

**Comment by Frenzie** [comment]
On the flipside, including a 7-zip library would use up quite a bit of space too.

.tar.zst might perhaps be cobbled together using parts we already have. Zstandard generally compresses more while simultaneously decompressing faster at the most useful settings.

**Comment by iFUCKINGHATEcomputers** [comment]
Dope, hope it works.

**Comment by poire-z** [comment]
Dunno about the size, and this would be the less worrying topic.
A plugin won't help, we'd need to add C code to MuPDF and crengine so _them_ can deal with the new archive format. Handling ZIP is already complex, so not eager to see more of such code added in crengine.

**Comment by pazos** [comment]
The size shouldn't be too much of a problem for uncompressing 7z. The library we use on android weights ~55kB on 32 bit arm.

Problems are feature bloatness, lack of human resources and wasted resources (cpu cycles,iops, battery...)

**Comment by iFUCKINGHATEcomputers** [comment]
@pazos 
>lack of human resources

Naturally, fair enough.

>wasted resources (cpu cycles,iops, battery...)

Doesn't that only happen while the files themselves are being viewed? If the alternative is not being able to fit them in at all, I'd prefer to sacrifice some battery to occasionally read them.

**Comment by pazos** [comment]
>> feature bloatness

> As in, difficulty to maintain it in perpetuity?

Also as in https://en.wikipedia.org/wiki/Feature_creep

This is a document viewer that supports a bunch of formats.
Each format has its own structure, following its own spec (if any).
Some of the formats use zip as a container. Either mandatory (epubs) or optionally (fictionbook).
While zip is also a compression algorithm, its main usage is as an archiver to put a bunch of files inside (like tar)

You requested support for compressed files (7z or zstd) but there's no reflowable document format with that spec, so in order to fullfit your request somebody needs to "spec-up" something that makes a bunch of text files inside a compressed archive somehow a format on its own (like cbz/cbr/cbt are for comics).

Because you're aiming at reading those files on the fly (makes sense because uncompress them turns the whole process meaningless) serious work needs to be done on the reader engine. And the one that **does the work**, @poire-z, just stated above:

> Handling ZIP is already complex, so not eager to see more of such code added in crengine.

**Comment by Methaneus** [comment]
Going to comment that I do think it'd be worthwhile addition.

And no, not just because I just batch-zipped a _lot_ of comics and manga without realizing it's all in the 7z format, and assumed KOreader would support it. No sir.
