### ISSUE TITLE
FR: Add hide screen cutout option for Android version

### ISSUE THREAD

**Issue by mio-19** [koreader/koreader#10698]
**Does your feature request involve difficulty completing a task? Please describe.**
No

**Describe the solution you'd like**
^

**Describe alternatives you've considered**

**Additional context**

**Comment by mio-19** [comment]
@pazos Is it a design choice or something?

**Comment by pazos** [comment]
Since you didn't provide any useful info in your feature request I assumed you did run on a device below android 9 that has a cutout. There're no APIs to figure out the cutout size below android 9 and we won't plan to add support for it.

Next time please spend a bit of time providing info in feature requests and/or bugs.

**Comment by mio-19** [comment]
> Next time please spend a bit of time providing info in feature requests and/or bugs.

Sorry about that
Reopened an issue with info https://github.com/koreader/koreader/issues/10709
