### ISSUE TITLE
Dev advice: IDE for Lua

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10708]
Hey guys,

I am sorry if this is an absurdly stupid question, bit I wanted to ask it here first before I go all with heavy duty solutions. 

Is there a good IDE for KOReader development?
Specifically, I am trying to make my life easier to trace the frontlight variables, but I am lost of what module comes first, when it is invoked and most importantly what variable survive where. For example, between generic/specific powerd.lua and device.lua. 

I am coming from the perspective of Matlab :D where everything is shown in the workspace and functions can be debugged line by line with their own workspace if needed. Just wanted to know if there is something like that to help me in Lua, like solutions that you guys usually use. 

Thanks!

**Comment by Frenzie** [comment]
I just use Geany usually but ZeroBrane is good.

**Comment by NiLuJe** [comment]
I just use Kate with the Lua LSP, but ZeroBrane is good (it is designed for Lua, after all) ;).

**Comment by NiLuJe** [comment]
But, mostly, regardless of the IDE/editor, ripgrep will be your friend ;).

**Comment by mergen3107** [comment]
Thank you so much guys!

**Comment by Frenzie** [comment]
Sometimes I also use Kate but without any LSP stuff. ;-P

**Comment by clach04** [comment]
Thanks for asking this, I'd never heard of ZeroBrane before!
  * https://github.com/pkulchenko/ZeroBraneStudio
  * https://studio.zerobrane.com/

**Comment by mergen3107** [comment]
@NiLuJe 
Thanks for the `ripgrep`, it is REALLY fast!

Now, I `git clone`d ZeroBraneStudio, but how do I "open" koreader project? It only lets me open singular .lua files...

**Comment by pazos** [comment]
@mergen3107: Did you try VS Code?

It usually gives the 120% of what 99% developers want :)

**Comment by mergen3107** [comment]
@pazos Thank you! I haven’t, but will try soon :D

**Comment by hugleo** [comment]
You can use grep ;-)

cd koreader/frontend

$ grep -ilr "FileChooser:show_file" ./* 2>/dev/null
./apps/filemanager/filemanagermenu.lua
./apps/filemanager/filemanagerfilesearcher.lua
./ui/widget/filechooser.lua

$ grep -ilr "nilOrTrue" ./* 2>/dev/null
./apps/filemanager/filemanager.lua
./apps/filemanager/filemanagerutil.lua
./apps/filemanager/filemanagermenu.lua
...


Or some more tips here: https://github.com/koreader/koreader/issues/10708

**Comment by pazos** [comment]
Also, while my recommendation of vscode still stands, both vim/neovim and emacs are good candidates.

Here's emacs showcasing integration with luacheck (via flycheck)
![Captura desde 2023-09-15 23-01-05](https://github.com/koreader/koreader/assets/975883/03ab9da5-42c4-4f01-8c86-d7bfc476deb5)

And with lua-lsp (via eglot)
![Captura desde 2023-09-15 23-02-07](https://github.com/koreader/koreader/assets/975883/7d1c26de-3a77-411d-a3b8-0a6c4186158e)

The lsp client in emacs (eglot) seems to behave better than the client bundled with neovim for a project of the size of KOReader. Some features, like renaming, are better handled with other packages (projectile works great)

Neovim shines because lua is a 1st class citizen there, so treesitter works almost out of the box. Not there yet in emacs for lua.

Both projects are quite okayish for editing lua. As it is GNU nano :smile:
