### ISSUE TITLE
Kobo Libra 2 freezes and reboots on KOReader exit

### ISSUE THREAD

**Issue by infiniumX** [koreader/koreader#10713]
* KOReader version: 2023.06.1
* Device: Kobo Libra 2 32GB - firmware 4.37.21586

#### Issue

When you try to exit KOReader to the Kobo home screen initially you see the loading dots and after some loading the dots freeze. The device stays frozen like this for maybe 1 min then reboots (indicator light flashes). Sometimes the KOReader manages to exit cleanly, but if you open a book and then exit it hangs for sure. It also happened on older firmware (4.35.XXX and later) and older KOReader (all last three versions, don't know before that, my Kobo is new). 
Just now to get the crash.log file I connected the Kobo, downloaded the file and safely disconnected. KOReader displayed that the usb is disconnected and restarted KOReader, then I immediately exited and it managed to exit cleanly to Kobo home. But then I opened KOReader again, opened a book and tried to exit and it did the whole freeze>reboot routine. After that I reconnected and saved the crash.log file again to have the latest crash info if it's there at all.

#### Steps to reproduce

Open KOReader from NickelMenu > open any epub book > click Main menu > Exit > Exit  

##### `crash.log` (if applicable)
[crash.zip](https://github.com/koreader/koreader/files/12096246/crash.zip)

**Comment by NiLuJe** [comment]
(It might also be a weird device-specific Nickel restart failure and unrelated to the above issue, the fact that this has worked as well as it has over the years is still a minor miracle).

**Comment by NiLuJe** [comment]
On that note, a couple of things to try:

* If you're not already using KFMon to start KOReader, try that way (even via an NM generator, like what the OCP does).
* Try with the KFMon boot spinner instead of the stock one (c.f., https://github.com/NiLuJe/kfmon#things-to-watch-out-for , TL;DR: `touch /mnt/onboard/.adds/kfmon/config/BAR`); it's way less stupid, and *should* be far less prone to the aforementioned issue if that was indeed the problem.
