### ISSUE TITLE
KOReader makes calls to Microsoft on load

### ISSUE THREAD

**Issue by jamescridland** [koreader/koreader#10736]
* KOReader version: 2023.06.1
* Device: Android - Boox Poke 3

#### Issue

If the sync feature is on, KOReader phones home to Microsoft on load, restart and repeatedly during use. It is using the domain dns.msftncsi.com 

#### Steps to reproduce

Turn on the sync feature, registering if necessary.

Use a secure DNS service like NextDNS or pihole, or I assume also use the DuckDuckGo app that monitors network traffic from apps.

On load of the app, you will see a connection made to dns.msftncsi.com

I'm not a massive fan of this, which is sending data to Microsoft. It seems undesirable for those who value privacy for their data to be sent to the US without my consent (no matter how benign the data or reason).

#### Workaround

Turn off the syncing feature.

**Comment by jamescridland** [comment]
https://github.com/koreader/koreader/blob/618f065de4ef1ab5d9df385e42b655980b1e72f3/frontend/ui/network/manager.lua#L409

This appears to be in the code here.

**Comment by poire-z** [comment]
See the comments around.
This looks like just a DNS lookup, using YOUR configured (or obtained from your DHCP service) DNS server - so no data is sent to Microsoft. (Your DNS server may end up forwarding the DNS request up to Microsoft top DNS servers, but just as much as they do for all the Windows PC out there :)

Give how many computers on the net use this microsoft hostname to check connectivity, there's no reason to use some other hostname - on the contrary, nothing more anonymous that wearing the same hat as all the other people in the street :)

**Comment by jamescridland** [comment]
Any reason that it isn't using the sync.koreader.rocks address to check for connectivity? Why use a third party?

**Comment by pazos** [comment]
> Any reason that it isn't using the sync.koreader.rocks address to check for connectivity? Why use a third party?

it is dns. For the 99.999999999999999% of the users resolving any dns query is third party. For the rest of them, who are running unbound or bind on their own machines, probably cloudflare, microsoft, alibaba or google will have faster authoritative dns servers.

So the only reason to change is FUD.

**Comment by jamescridland** [comment]
Thanks for the response.

I don't understand the use of a third-party Microsoft domain. Why isn't the test DNS check one to `sync.koreader.rocks` which is the service used later by the connection? The use of the KOReader domain would be perfectly adequate here, and would also ensure that you don't have other people wondering why the app is seemingly calling Microsoft's servers (even if it is, as you say, just a DNS check).

The use of the Microsoft domain makes an extra DNS query which isn't needed in this case. So the only reason to change is to a) reduce the number of DNS calls (every little helps), and b) stop a recurrence of this issue being posted in future by someone else curious as to why KOReader is phoning home to Microsoft.

Would be interested if there is a valid reason *not* to change.

**Comment by NiLuJe** [comment]
> a valid reason _not_ to change.

Reliability.

As explained repeatedly, we're not the only ones doing this, so there's a rather minimal chance of it ever breaking.

Our own domain (or anybody else's, realistically), not so much.

**Comment by Frenzie** [comment]
Though there are others that are presumably equally dependable, like for example `http://connectivity-check.ubuntu.com/` and `http://network-test.debian.org/nm`. Of course then people would complain about phoning home to Canonical/Debian/KOReader.[1] ;-)

On Android specifically a more reasonable question would be why we're not just deferring to the system, like for example with https://developer.android.com/reference/android/net/NetworkInfo#isConnected() though that's apparently deprecated now. Which perhaps answers the question, implementing something custom for Android is a fair bit of work for little gain.

[1] Keep in mind that there's no reason to ever connect to koreader.rocks with the exception of sync if enabled and updates if manually checked.

**Comment by Frenzie** [comment]
> Koreader does not need to do any of this in the first place.

Keep in mind Android is the special case, not the reverse. In any case, you don't need to defend that proposition; it's either a mere coincidence or just really hard to implement.

https://github.com/koreader/koreader/blob/2ba3353d8a356234ee8343475ef7c0fa27e9b047/frontend/device/android/device.lua#L299-L305

**Comment by pazos** [comment]
> And no, none of this is 'FUD'. This is a valuable report.

Ohhhh yeah. It is `FUD` based on lack of understanding about how dns works.

>  No piece of metadata is too small for adversaries with infinite budgets, processing power, and the storage to never delete even the most mundane request in your lifetime. Software should never make requests without asking. I understand there was no harm intended here, but don't label inquiries 'FUD' just because you're not aware.

This is basically nonsense with the same underlying cause.

Please spend a few minutes and try to understand how your dns service works. It translates domains to ips. 

I agree, you should run your own recursive dns resolver as no 3rd party is good enough if you care about "adversaries with infinite budgets, processing power, and the storage to never delete even the most mundane request in your lifetime".

It is even worse than that as most people uses the dns servers their isp provide, so they (isp's) can keep track of their users entire navigation history.

Is not our duty to address misinformation and not our duty to address false claims with borked workarounds that do nothing to defeat the real problem: dns might be used for tracking you and we can do nothing to fix that.

If somebody finds a way to figure out basic wan connectivity using a method that leaks less info that a single dns query then ok. If people are just worried about that specific dns query and blames this program for doing it I'm going to repeat myself: your focus is **wrong**. Changing a domain owned by microsoft to a domain owned by somebody else is just a cosmetic workaround that **DOES NOTHING** other than providing you a **FALSE SENSE OF PRIVACY**  because you left unaddressed the real issue here: **who runs the service that translates domains to ips on my network? do it trust them? what I can do if I don't trust them?**

**Comment by NiLuJe** [comment]
:100: what @pazos just said. And that's coming from someone who actually *is* using his own root server as a DNS resolver (although, to be frank, it's mostly because ISP's have historically sucked at that in France, and nothing crazy ^^).

**Comment by jamescridland** [comment]
I would, gently, point out that anyone looking at network traffic will see KOReader calling Microsoft, and - rightly - wonder what the hell is going on.

@pazos might feel it's fair to slap me down for this report, and make me feel stupid. The developer knows best, and the user is ignorant. I would, again, gently point out that this could be avoided if it didn't make a spurious DNS call to a Microsoft domain that is not usual behaviour by most Android apps.

On a very basic level, using Google's standard equivalent would be more sensible for Android - I don't run any Microsoft software, and it stood out like a sore thumb. It's also likely that the Google equivalent domain would be already cached by the system, if not the closest DNS. That would be a simple "if then" statement to set a more appropriate domain, if the developer is too lazy to implement the proper solution.

**Comment by poire-z** [comment]
Your report is fine, and lead to discussion and explanations, and knowledge, and should hopefully make you feel smarter :)

> I would, gently, point out that anyone looking at network traffic will _see_ KOReader calling Microsoft, and - rightly - wonder what the hell is going on.

But KOReader _is_ still _not_ calling Microsoft.
Most of these anyone looking at netword traffic will see KOReader is _not_ calling Microsoft.
A few of these anyone will wrongly analyze this traffic and _think_ and persuade themselves that KOReader is calling Microsoft - and wonder what the hell is going on. And ask :) And get some serious answers. And hopefully will be convinced and have learned something.

No real reason to change what we do because some people may think wrong (scratched my head to find some analogy but didn't...)

We need something solid, and a Microsoft hostname used by millions of computers in the world is garanteed to be reliable now and for years.
We could switch to another (as solid) Big Name hostname (Apple, Google...) but why ? No reason to _favorize_ one more than the other (I didn't write "trust", as we don't need to trust them, we would still not be calling them). (We need to trust they are and will stay solid though :)
We can't use any koreader.rocks hostname, because it is not solid (I don't even know who manage this domain - and the domain could disappear in 2 years because somebody forgot to renew it, and it may need months to fix that - and in the meantime, all KOReaders installed in the past, possibly not updated for years but working fine - would not work anymore... and would not be able to go online to update :)

As for Android, your Android does not do "just a simple DNS lookup that never reach Google". Your Android calls its home, Google, it does (at least my Android 6 at the time I looked at its traffic) some http request to some Google hostname to toggle that Wifi icon when you switch Wifi on.

KOReader doesn't do any http request anywhere (except when you willingly tap Translate, Wikipedia, Update, Sync...)

**Comment by NiLuJe** [comment]
> anyone looking at network traffic will see KOReader calling Microsoft

As we've repeatedly said, no they won't, unless they have severe reading comprehension issue,s or are utterly unaware of the basics of how DNS works.

Case in point, this is a wireshark excerpt from doing just that on that piece of code, with a cold DNS cache.

![dns_resolution_101](https://github.com/koreader/koreader/assets/111974/78a9838f-e99b-4f60-a53d-769922a042be)

And, lo and behold, the only thing you're talking to is... your DNS resolver.

```
$ resolvectl status                                                                                                                                                                                                                                                                                                               
  Current DNS Server: 91.121.152.196
```

**Comment by jamescridland** [comment]
Agreed, it's just a DNS call. I understand that. There's little need to insult users by saying "they have severe reading comprehension issues". That's just plain rude.

My point, as I'm having to repeatedly say, is that anyone looking at network traffic will see KOReader making a DNS request to a Microsoft domain, **and be concerned that it is doing so.** It'll show up in Pihole, it'll show up in Control-D or in nextDNS, it'll show up in most anti-tracking apps. You will get more concerned users wondering why KOReader is apparently making a call (it's a DNS request, yes) to an entirely unrelated server and wonder what's going on.

It's difficult, I know, but telling your users that they're stupid and thick is not a great look, when a number of tools that they use will report, quite accurately, that KOReader kicks off a DNS request for a Microsoft domain.

Anyway, since you feel it appropriate to belittle users, I'm going to close this issue.

**Comment by NiLuJe** [comment]
What I feel appropriate is using accurate language to prevent anybody from jumping to hilariously far-fetched conclusions.

While I can agree on the fact that DNS requests can be an indicator of bad actors or misbehaving software, this is clearly not the case here, so I clearly don't see what the fuss this is supposed to be about.

**Comment by NiLuJe** [comment]
And, FWIW, the "reading comprehension" comment was a general comment about Joe Random coming up on something like the excerpt above and seeing mentions of "GiantEvilCorp.com" in a field somewhere and going "ruh roh", without understanding what that field actually entails. Hence the conclusion that talking *about* != talking *to*.

**Comment by jamescridland** [comment]
Again - treating users like idiots is not a bright plan.
