### ISSUE TITLE
Translation user interface is confusing

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#10787]
Translation is not a feature I use in KOReader. I looked at it to add this feature to the user guide.
It took me around 30 seconds to understand what I am seeing and I still don't know why I am seeing this.

**See, a translation interface is simple:** 
Two boxes. You enter text into one. Translated text appears in the other. Every service is exactly like this.

This is what I see:

![koreader translate](https://github.com/koreader/koreader/assets/84420582/dd18217e-d4b1-49f9-b0e6-615348497c32)

I selected one sentence and got back **five** translations.
First part looks ok: Original sentence and under it, the translation.

- But then my sentence is cut up into two pieces apparently randomly (why?)
- Then two parts are translated into two slightly different versions (why?)
- In some other tests these two translations were the same (also why?)

And there is no clue in the user interface to tell me what is going on here.
There is a concentric box icon which means "original" (apparently).
And there is a black circle which is translation (of course).
And some numbered circles.

**QUESTIONS:**
- We are embedding full wikipedia articles in that window. Can't we add some words here to clarify what are these sentences?
- Why KOReader cuts up my single sentence into multiple slightly-different-translated sentences?
- I think this feature is using the **Google translate** service but there is no indication of this information. Is it a secret? Is it shameful? Users don't need to know this? They have to know this because there are lots of users who try to avoid Google services. Maybe they don't want to send their texts to Google corporation.

Here is a quick mockup:

![koreader translate mockup](https://github.com/koreader/koreader/assets/84420582/877fa30c-0796-42dd-a998-39f2052efa31)

**Comment by Frenzie** [comment]
I didn't look at the code but that looks like what it thinks the best translation is followed by alternatives with less confidence? Seems sensible enough to me to get a better idea of what it might mean; you're better at context.

![Screenshot_2023-08-06-09-30-50-11_1aff61e6bd981aaa4ba9d0245eb6c04f](https://github.com/koreader/koreader/assets/202757/3de92ec5-761e-45e9-ac44-ea655aa6f3af)

**Comment by hius07** [comment]
> * But then my sentence is cut up into two pieces apparently randomly (why?)

It's done by Google Translate itself when returning alternate translations of the text.

**Comment by offset-torque** [comment]
> **Frenzie** - I didn't look at the code but that looks like what it thinks the best translation is followed by alternatives with less confidence? Seems sensible enough to me to get a better idea of what it might mean; you're better at context.

I thought like that too. Also I had a theory why it is cut up (KOReader cuts at certain punctuation marks) but apparently it is done by Google according to **hius07**.

See, the problem is, as a user I am (like you) trying to guess what is going on here. A user interface shouldn't force users to guess or come up with theories.

This is the default GT (google translate) interface. Nearly everyone interacts with this when using GT:
![google_translate_gui](https://github.com/koreader/koreader/assets/84420582/f1f4fb36-94fb-48a4-a5af-18b9e153d83c)

There is no indicator or clue that there are alternate translations. So an ordinary user can't make this connection. On top of this we don't even tell the user that he is actually using GT when he invoke this feature. So probably no one can surely know this is the case, unless they use GT API directly.

Solution is simple. I made a few tests and apparently GT cuts (or tries to cut) at sentence boundaries. 
So we add a title line above those sentences saying:
`Alternative translations for individual sentences:`

**Comment by Frenzie** [comment]
> See, the problem is, as a user I am (like you) trying to guess what is going on here. A user interface shouldn't force users to guess or come up with theories.

I'd hardly call it a guess because it's identical to every dictionary. I actually find it very well chosen by whoever wrote it. I reject your implicit classification of the average user as some ignoramus with no clue what a dictionary is. ;-)

<img src=https://github.com/koreader/koreader/assets/202757/0ee59abc-9b9f-4d72-b53d-8ec75a3b7c59 width=45%> <img src=https://github.com/koreader/koreader/assets/202757/aa4a704a-55be-43f5-97ef-9e252e726e56 width=45%>

**Comment by offset-torque** [comment]
Did you notice the name of this feature? It is **Translate** not **Dictionary** ;)  Key is the expectation. When you call your feature "translation" people expect it to work like other "translations" they used. And none (literally zero) of the online translation services look like your pictures.

Also this feature is not an "other meanings" feature like in a dictionary. It is a neural network imagining things. Here is the example from my mockup screenshot:

![bella](https://github.com/koreader/koreader/assets/84420582/82df6dbf-5f9c-47ca-9292-7bbb8338c84d)

Helene is just beautiful, we know this. But in the Google alternate universe she is the most beautiful apparently. You can't find "most beautiful" under the "beautiful" entry in any dictionary.

> I reject your implicit classification of the average user as some ignoramus with no clue what a dictionary is. ;-)

Online translating already replaced dictionaries (and human translators) and LLM AI models will replace online translation services. Soon there won't be anyone left who ever touched a dictionary made of dead trees :)

**Comment by poire-z** [comment]
It's all Google splitting the input text in parts (sentences, sub-sentences, dunno).
And it's their API returning alternative suggestions - we could request not to have them, but why not ? Depending on the languages involved, the alternates may be more different than beautiful/most beautiful, and I have been happy a few times seeing the correct translation (for the context) among the alternates (usually translating from German, Latin or Greek).

I'm not (may be as a poweruser) for overloading the UI with unuseful text like "from Google", "Alternative translations" (would waste a line :).
Maybe it's because you're _not_ using it that you found it odd - somebody really in need for it would just discover the results and "get" it and be fine with it.

Alternative solutions to the (non-:)problems mentionned:
Have a checkbox in the Translation settings: `[ ] Show alternate translations of parts`.
Have a first-time use popup "Translation uses Google services. If you don't like that, don't use it.". I mentionned in the past that I don't like having "don't nag me again" dialogs that we won't be able to show again, so... but this is not a choice dialog, so not really minding.

**Comment by Frenzie** [comment]
Translation: the Google Translate web UI sucks. Google Translate sucks therefore we should suck too sucks as an argument. :-D

If we check my _translation_ dictionary, we see the exact same meanings of suck you'd find in a monolingual dictionary:
<img src=https://github.com/koreader/koreader/assets/202757/f839d5a9-288d-4e17-ac77-2f9572022bd3 width=45%>

If we check Linguee or Bab.la, we get the same meaning 1 and 2 generated by algorithm (although for some reason we also get sick?):
![image](https://github.com/koreader/koreader/assets/202757/aed29665-98c4-4ae8-8c81-45eee79c7b27)

I'm particularly fond of the sources of the word used in context, which are hidden in a traditional paper dictionary.
![image](https://github.com/koreader/koreader/assets/202757/209fef24-7841-4cbe-8ad3-9383ef7b9df4)

> Also this feature is not an "other meanings" feature like in a dictionary. It is a neural network imagining things.

That's pretty much the same thing. Sometimes it'll come up with something clever, sometimes something dumb. Helen is the most beautiful woman on earth, so contextually it makes sense. And it correctly gave it a lower rating. I can easily see a human doing the same thing using reasoning that isn't dissimilar.

1. beautiful? most beautiful? least beautiful?
2. Helen

1, 2 ⇒ Helen is the most beautiful

Except the algorithm comes up with that because `most beautiful` is often written next to `Helen` while we happen to know it as a property of Helen. It's similar but not quite the same.

And yes, a dictionary might do the same thing. I looked it up just in case and while my dictionary here only says `She was a very beautiful woman` as a sample sentence under `beautiful`, it could've easily said `Helen is the most beautiful woman`.

**Comment by Frenzie** [comment]
@poire-z 
> I'm not (may be as a poweruser) for overloading the UI with unuseful text like "from Google", "Alternative translations" (would waste a line :).

You could also just say `(Google)` with an implication that something like #9045 might make sense. (For European languages DeepL is significantly better than Google Translate — perhaps not necessarily at accuracy which is quite good for both, but at sounding relatively natural.)

**Comment by offset-torque** [comment]
I am not against alternate translations and I didn't suggest removing anything.
I just pointed out some UI problems. Fixing or ignoring is up to you (devs).

**"Users will get it eventually, they are not stupid."** attitude is the root cause of bad UX.

Why am I even writing a user guide according to this logic? 
Users will discover everything if they really need it, right?

**Comment by Frenzie** [comment]
> "Users will get it eventually, they are not stupid." attitude is the root cause of bad UX.

It may or may not be, but my argument is that everybody will get it *immediately*, and that includes people from 1923 who'd first have to figure out how to work a mouse.

**Comment by offset-torque** [comment]
Of course they will get it immediately just like they will get that we are using GT API. 
Example user:
- Translation doesn't work when my wifi is off so it should be an online service
- KOReader is open source, which means they don't have money to host their own service so it should be a 3rd party
- Yandex, nope Russian war
- Deepl, nope too many languages to choose from
- Bing, nope translation is not gibberish
- **So it is Google !!!** Elementary, my dear Watson.

Easy deduction, anyone with half brain can follow so we don't need to indicate this anywhere.

**Comment by pazos** [comment]
> Of course they will get it immediately just like they will get that we are using GT API. Example user:
> 
> * Translation doesn't work when my wifi is off so it should be an online service
> * KOReader is open source, which means they don't have money to host their own service so it should be a 3rd party
> * Yandex, nope Russian war
> * Deepl, nope too many languages to choose from
> * Bing, nope translation is not gibberish
> * **So it is Google !!!** Elementary, my dear Watson.
> 
> Easy deduction, anyone with half brain can follow so we don't need to indicate this anywhere.

Yay. I would love to see those obscure ways of enlightenment :)
And these users, after the deduction, will ask why the feature is not announced properly.

And then we will point to https://github.com/koreader/koreader#main-features under the **"integrated"** dot.

**Comment by Frenzie** [comment]
I am they. I looked at this dialog for possibly the first time ever today and not only was it immediately clear, I was impressed with just how successful and well designed it was at being clear and obvious.

You have an original. You have a translation numbered 1. You have a slightly different translation numbered 2. QED.

**Comment by Frenzie** [comment]
Like, I'm not saying I don't want to change anything, I'm saying holy fuck, this is actually amazing, why isn't the crappy Google Translate web UI like this?

**Comment by Frenzie** [comment]
NB I still won't use it.

**Comment by offset-torque** [comment]
Every time I have a UI/UX discussion with you guys, I remember this comic: [xkcd-Average Familiarity](https://xkcd.com/2501/)

**Comment by poire-z** [comment]
> "Users will get it eventually, they are not stupid." attitude is the root cause of bad UX.

Well, we're still discussing :)
The other extrema is when the app is taking you by the hand everywhere, stating the obvious all along, and it's annoying and noisy and slow to get things done.
We may have the tendency toward the other extrema, but I don't think we're that radical: we usually think about having things intuitive and put some explanations in help text.... so give us a bit of credit for a not-so-bad UX :)

I wouldn't really mind a appended harcoded `Translation from South-Vietnamese (Google)`, but it could get long and annoying - and once you know, you don't really care seeing Google in the title of all your translation window.
But may be a mention of Google in the Translate settings could be a good thing (for legal reasons too - I dunno if and what one is somehow required to write when using such services).
(Also, it's possible this API will die one day, or require a app key - from what I remember, there is one non-explicite parameter-value that we need to provide to have it work without a key - otherwise, you get an error from the API - it might be because of some older app in the wild that they didn't want to kill yet.)

> Why am I even writing a user guide according to this logic?

I can't answer for you :) And I'd like to hear your answer ! (ie. you love the app in spite of its flaws, you love the devs - or arguing with the devs :) you don't really love the app but it's the only one that does things you want...) Please tell :)

> Users will discover everything if they really need it, right?

My thoughts about the User Guide:
- it gives a nearly exhaustive overview of the app features - so at start or even after using it for some time, you can go read it to see what you haven't discovered.
- for features we are not "taking you by the hand", and may have not-explicite behaviours, one can go to the User Guide and see the explanation of how it works and why it was made this way - so the user may then think "_ok, exactly as I ended up understanding it, that's a great and intuitive idea !_" or "_ok, that's dumb, but ok, with the explanation I get it, even if I would have wish it otherwise (and I'm going to open an issue because there's a better way to handle that, and I'm telling you, and once told, the devs will realize it's indeed great and better_" :)

(There are also other things that are not intuitive, or we didn't manage to settle on something explicite - ie. the select mode icon - and we ended up saying that more details will be available in the User Guide.)

**Comment by Frenzie** [comment]
> [the manual] gives a nearly exhaustive overview of the app features - so at start or even after using it for some time, you can go read it to see what you haven't discovered.

It's a really great way to search for "can it do this (and if so, how)" or just to skim to get an idea of what it can do. I don't think anybody would read it from A-Z, so it's a lot like a dictionary! ;-D

**Comment by Frenzie** [comment]
@offset-torque 
> Every time I have a UI/UX discussion with you guys, I remember this comic: [xkcd-Average Familiarity](https://xkcd.com/2501/)

I am or am supposed to be an above average user of reference works, but I don't think I'm saying anything I wouldn't have when I was 10 back in '96, learning English by playing [_Entomorph: Plague of the Darkfall_](https://en.wikipedia.org/wiki/Entomorph:_Plague_of_the_Darkfall) with a dictionary in hand (or a few years later reading _The Boys from Brazil_ and _The Lord of the Rings_, by then with barely any dictionary use :-).

**Comment by hius07** [comment]
> to add this feature to the user guide

Please note, that the "Alternate translations" section is not the end.
When translating one word, the "Definitions" section follows.

**Comment by offset-torque** [comment]
**@poire-z** 
> We may have the tendency toward the other extrema, but I don't think we're that radical: we usually think about having things intuitive and put some explanations in help text.... so give us a bit of credit for a not-so-bad UX :)

Our overall UX is good now, that's why this translation issue stood out to me. Generally in our UI, if something is not clear we have **long-press help text** (bottom bar) or **info button** (book map) or **about button** (plugins). Here we leave the user to figure out himself (eventually they will of course). 

After **@hius07** comment I noticed that there is a **Definitions** section. Now look at this mockup and tell me that keeping these lines instead of proper explanatory headings is objectively better for the user.

![translate_mockup2](https://github.com/koreader/koreader/assets/84420582/4f7614a8-583e-40bc-9b94-4a8b7e97a5e5)

If you think this is hand-holding, this example might clarify:
The glass door you are approaching might be a **PUSH** door or a **PULL** door.
Architect can say **"Well I don't want to clutter my nice door with an ugly sign. Users will surely find out. I don't want to hand-hold them for a simple thing like opening a door."** He is technically correct. No one gets stuck at a door. 

But it costs users a cognitive load while approaching **"Should I push or pull this door"** and now user is looking for clues (but there are no clues, wasted effort) and make an attempt and fail 50 percent of time. All this (tiny effort X number of users) can be avoided with a simple **PULL** sign. 

If your success metric is **"number of people got stuck at the door"** this door is perfect. Zero users got stuck = 100% success rate. If the metric is **"can users use this door without any thinking and trial/error"** then this door fails.

Now this is the crux of our disagreement. You can even call this our **"parenting style"**. I want to make the user think less. You (plural) are saying a bit of thinking won't kill. To be frank, they are both true and borders are really vague. But as an ordinary user I prefer the smooth experience (don't make me think unnecessarily) so that's why I am generally advocating for it.

Current translate UI is the glass door. Surely users will figure out: **"Oh that's my paragraph split up."**, **"These might be alternate translations"**, **"This looks like a definition"**. Are these few seconds of effort justified or wasted? Now we are in the philosophical territory. One side goes to **"you are wasting precious time of users' life which is avoidable and collectively these will pile up"** and other side goes to **"if a user wants to use a program surely a bit of effort is expected and if this is not life itself then what is?"**.

And yes both of these perspectives can be true at the same time. That's why I am not overly insistent. I saw a problem (from my perspective) and reported. That's it.

---

>  I can't answer for you :) And I'd like to hear your answer ! (ie. you love the app in spite of its flaws, you love the devs - or arguing with the devs :) you don't really love the app but it's the only one that does things you want...) Please tell :)

Lean, fast, powerful and open source. How can a person not love KOReader!

I am writing the guide for many reasons:
- **I needed a guide:** KOReader is complex and configurable which I like in a software. That's why I am using an extremely configurable linux desktop environment. There are tons of e-reader apps on Android that are so simple anyone can understand all of the features in 5 minutes without a guidance. KOReader is not that and I like tweaking everything so I needed answers.
- **Everyone needs a guide:** I hate wasted effort whether it is mine or someone else's (it is noticeable I guess :). KOReader devs are responsive and helpful. If I have asked questions without an intention of writing a guide, I am sure you will answer the same as I saw many times in other users' issues. But that answers would be buried in issues and long discussions so they would be asked again and again by other users. I am collecting the knowledge in a single place so users can read it directly or they could be pointed to the guide instead of explaining everything again and again.
- And this is my way of giving back to the community.

**Comment by offset-torque** [comment]
@pazos
> And then we will point to https://github.com/koreader/koreader#main-features under the "integrated" dot.

I didn't notice this. I guess this is enough, since it is in a highly visible place. I also added it to the guide so this covers the situation I think. I retract my position to indicate Google in the UI.

**Comment by poire-z** [comment]
> Now look at this mockup and tell me that keeping these lines instead of proper explanatory headings is objectively better for the user.

The thing is that the content in this window is a single plain text box - we can't style it to add some padding above the headings like you did, or use bold or underline (and neither size invididual lines content so to reach the right margins with a computed bunch of underscores).

So, all we could get is:

![image](https://github.com/koreader/koreader/assets/24273478/c26e9859-59d0-4a19-8a7a-7fcfcc19504b)

![image](https://github.com/koreader/koreader/assets/24273478/f43c1ae6-dfc8-4c48-9f59-26efab418f3b)

![image](https://github.com/koreader/koreader/assets/24273478/cbbe35a3-c85b-41b2-b5cd-766d35db9320)

![image](https://github.com/koreader/koreader/assets/24273478/6dd5435d-3103-4edc-a4d0-4efa53f36084)

Yes, this says what is what - but these "headings" are undistinguishable from the real valuable text one has to focus on.
The issue with `_____ Alternate translations` is that these would be l10n-translated, and could end up long, and would wrap to 2 lines, and make it less distinguishable/ignorable. (And also, it looks a bit odd and "bad taste developper unaesthetical" as you could put it :)

Another left black symbol for these headings would also make them less stand out from the existing symbols.
In case you have ideas, it's easy to test them playing around there:
```diff
--- a/frontend/ui/translator.lua
+++ b/frontend/ui/translator.lua
@@ -590,3 +590,5 @@ function Translator:_showTranslation(text, detailed_view, source_lang, target_la
             -- Alternative translations:
-            table.insert(output, "________")
+--            table.insert(output, "________")
+            table.insert(output, "Alternate translations:")
+--            table.insert(output, "________ Alternate translations:")
             for i, r in ipairs(result[6]) do
@@ -606,3 +608,5 @@ function Translator:_showTranslation(text, detailed_view, source_lang, target_la
             -- Definition(word)
-            table.insert(output, "________")
+--            table.insert(output, "________")
+            table.insert(output, "Definition:")
+--            table.insert(output, "________ Definition:")
             for i, r in ipairs(result[13]) do
```

Or waste a line with an additional blank line:
![image](https://github.com/koreader/koreader/assets/24273478/bcd2b79b-b971-4b6a-9231-88d89dde71e0)

![image](https://github.com/koreader/koreader/assets/24273478/a4731670-62ea-497b-8409-94c8e747d3b7)

**Comment by offset-torque** [comment]
Thanks for testing the idea **poire-z**. First two options are really cluttered I see. I can't say that is an improvement.

"Additional line" version looks good I think. I checked on my Libra. 
It doesn't look like it would be a problem.
- **Single word lookup** and **one sentence translate** still fits on single page, plenty of space.
- A **2 sentence translation** already exceeds one page (because each sentenceX3) so one extra line is not that bad there. Users need to scroll already.

Just my quick test of course. Open to discussion.

**Comment by poire-z** [comment]
So, what would be the correct English for these two, plural or singular? Like on your screenshot? Alternate translations plural and Definition singular ?
(Will have to wait for after v.2023.07 - because of... translations :)

**Comment by Frenzie** [comment]
Sounds good to me.

**Comment by offset-torque** [comment]
Yep. Your last screenshot looks perfect.

**Comment by poire-z** [comment]
#10799 if no more comments and you need it before it's merged to make screenshots for the User Guide.

**Comment by offset-torque** [comment]
Thanks for implementing this **poire-z**. This is in the **2023.08** milestone now so I think I can wait for the release to take the screenshots.
