### ISSUE TITLE
FR: Add recent books android home screen widget

### ISSUE THREAD

**Issue by qirlib** [koreader/koreader#10916]
Having a recent books stripe on my main screen would be very cool. [There is an existing widget](https://librera.mobi/faq/how-to-configure-the-widget/) from Librera for this but I would like one which opens KOReader.

**Comment by NiLuJe** [comment]
We're not a real Android app, I doubt we can really do widgets at all.

**Comment by qirlib** [comment]
Can you do a separate plugin apk and then do magic android inter-process communication?

**Comment by pazos** [comment]
> We're not a real Android app

100% agree

>  I doubt we can really do widgets at all.

Actually we *can*, with a lot of pain and using a bunch of callbacks. But we're not going to do it. 

> Can you do a separate plugin apk and then do magic android inter-process communication?

We're not going to do it (in APK or otherwise). It is not a matter of working-around stuff. We did that for a bunch of other things and it *mostly* works.

The whole point of the android port of KOReader is that we, the users, get for free whatever improvements happen on the common codebase.

There's no specific development on the KOReader android front. Other than maintaning stuff.
