### ISSUE TITLE
Feature request: note taking functionality

### ISSUE THREAD

**Issue by bilyyuan** [koreader/koreader#1095]
As the title. It bothered me very much.
I forget whether it is has worked or not.
For both old version [at least 6 month ago] and latest version, notes are not workable.
Added: Other function are works, problem only effects note. it exists on both scanning and non scanning pdf books.

**Comment by Markismus** [comment]
[Chrox mentioned](https://github.com/koreader/koreader/pull/464#issuecomment-32706593) a year ago that the text input module should be improved before we could use notes. This hasn't happened yet. 
The keyboard layout still boggles me, too. For instance when I am trying to find ß. It's there, though buried.

**Comment by richo67** [comment]
I wonder, is it still the case that keyboard layout is blocking factor for having note taking and highlight feature in koreader?

**Comment by houqp** [comment]
Not anymore, we have full keyboard now. Although we still don't have input method for CJK.

**Comment by richo67** [comment]
Please excuse my ignorance what is CJK?

**Comment by KenMaltby** [comment]
Chinese, Japanese, Korean

**Comment by richo67** [comment]
Thanks Ken!
Is the  lack of input for these languages the reason for not having possibility to write notes for highlighted text in ebook (ePub,mobi,..)?

**Comment by houqp** [comment]
Thanks Ken for the explanation. Lack of CJK input method is only a blocker for taking notes in CJK languages. There is no blocker for supporting notes taking for languages like English.

**Comment by joelostblom** [comment]
Does this issue encompass all types of note-taking features in KOreader or specifically annotating highlighted text? Phrased another way: If I want to write something down while reading an epub/PDF, is there currently any possible way of doing this with KOreader (even if it involves switching to a dedicated note taking app or annotating a bookmark/page rather than a selection of text)?

If this is not possible yet, is an annotation feature on the roadmap (or maybe even being worked on already) or is it still in the planning stages and unlikely to see a release in the upcoming months/years?

**Comment by mergen3107** [comment]
So are there any news on adding this notes functionality?
Moreover, why can't you just start implementing this feature at least for current input method?
That's seems unfair to me, because I don't use CJK input, but make notes on my book highlights very often.

**Comment by sqlicone** [comment]
Will the possibility of adding notes to PDF highlights be added any time in the future??
It's a really crucial feature for me, as I work at a university and read lots of pdfs that I need to note.
I'm considering buying a Kobo Aura One to use Koreader, but if I can't write notes on pdfs then I'll have to go with a Kindle, because even though the screen is so small I can still add notes with their firmware.
Thanks

**Comment by retrography** [comment]
If we enable that option, at least those of us with a bluetooth keyboard can use it...

**Comment by danielarmengolaltayo** [comment]
Hi all!

Yesterday I discovered KOReader, installed it in my recently purchased Kobo Clara HD and played a little bit with it. 

First of all, congratulations to all the people involved in the development of this project, it’s amazing to see such a complete product, with lots of extra features that comercial eReaders doesn’t have. I’ve been digging in the mobileread forums, the wiki and the issues page here in GitHub, and it’s beautiful to see the energy of the community explaining how the software works and providing support for newcomers.

The reason for this message is to follow up with the conversation about the status of this feature, to know if it will be implemented in a near future or not, and to highlight its importance. 

Let me explain what it brings me here. 

These are the basics I am looking for an eReader to do:
1. good reading experience on different file formats
2. dictionary and translation
3. highlights and notes
4. extra features and customization are also appreciated

…and this is what I found in KOReader:
1. lots of file formats and better reading experience with .pdf than an average eReader software
2. good implementation, online and offline
3. highlights text and export, but, **no notes**
4. lots of extra features to play around, plugins, etc…

I compared the Kobo Clara HD with the Kindle Paperwhite, and I decided to buy the former because it supports more file formats, among other minor reasons. After a few days of using the Kobo, I realize that when you export the highlights and notes you get an unordered text file, without any reference to the location of the highlight or note, to rearrange them. 

What a disappointment! All of a sudden, the function of highlighting text and taking notes completely lost its usefulness to me.

Then, I did some research to check if there was any solution or alternative available out there (I found some options that are worth exploring in Windows, but I am a Mac user), to finally come to KOReader. Everything seemed promising until I came across the disabled “notes” button, and later, this and other threads commenting about the feature not yet implemented, with such conversations initiated a long time ago.

My impression is that this feature is something that will not be implemented soon (at least not before a week, when my return period for my Kobo expires, if I want to get a Kindle instead), so that’s why I think it’s important to talk about the implications.

From what I see (at least happening in this range of eReaders which are the ones I researched), Amazon’s approach is the most complete and reliable in terms of how to manage the highlights and notes in your ebooks. It does not surprise me at all, and this is the reason:

Put it plain and simple, there is value in highlighting and taking notes in a book, not only on a personal level, but also collectively. That’s why, for example, we see the [top highlight](https://blog.medium.com/introducing-highlights-a4df69e8ed43) text on Medium. Amazon gives us an easy-to-use option to highlight and take notes and the ability to manage them online, not just because they want to offer us the best product, but also because they can have access to the value we generate by using their service. I have no proof that they use the highlights/notes, but what I know is that it would be stupid not to do it (if we see it from their point of view), and if they are not doing it right now, I’m sure they will do it at some point in the future.

That’s why I prefer to manage my highlights and notes locally, where I really own my data.

The thing is, that even knowing what Amazon could be doing with my data, if they are the only ones offering a good and convenient service to me, I'll probably use it as many others.

This is why I think it is important to discuss certain implications to understand what is being developed here, because I really know that is easy to forget about priorities when there are features more attractive or fun or challenging to be developed. And having more and more features is always cool, but sometimes, focusing on just the importants and developing them to obtain an excellent result is ofen more relevant to reach a larger audience, which means a greater impact on society.

With all that, I’m not saying that there is no excellence in here, I just want to share a view, willing to know what the community think about it. Any comment or idea will be highly appreciated. Thanks a lot for your time. 

:-)

**Comment by KenMaltby** [comment]
While I think highly of the Kobo implementation of KOReader, it should be noted that KOReader runs on the Kindle devices, as well.  Also, in both the stock software remains fully functional and available for use. 

As for providing your notes to Amazon, to use an online service/feature, it's not something I would do.  There is a Highlight extraction program for KOReader (in addition to the evernote plug-in) available on MR.  

Luck;
Ken

**Comment by KenMaltby** [comment]
KOReader Highlights utility. https://www.mobileread.com/forums/showthread.php?t=265433

**Comment by poire-z** [comment]
Except for this orphan `Add note` button, we already have some stuff:

Select some text, tap Highlight button => text highlighted.
Tap this highlight => `Delete | Edit` buttons , `Edit` => Rudimentory text editor to edit/replace the selected text.

Later, `Bookmarks` menu > full page bookmarks list, showing the edited text (or the first lines).
Hold on one of them => Bookmark details with the full text + `Rename this bookmark | Remove this bookmark` buttons ; `Rename this bookmark` => rudimentary text editor.

These can be exported and managed on a PC (no Mac it seems) with https://github.com/noembryo/KoHighlights.

Outside of book content, you have in the Tools menu a less rudimentary text editor so you can create and edit any file (My ideas.txt, My words to lookup.txt).

Some link to other issues with related discussion #3415 #4115.
And (possibly outdated) screenshots for the things described above: #3275 #4084 #4135 #4124

I don't know what more we could do with this Add note, except indeed for PDF embedded stuff.
Or make it a shortcut to the Edit bookmark as suggested in https://github.com/koreader/koreader/issues/4115#issue-345341768, with the full page text editor.

**Comment by danielarmengolaltayo** [comment]
I checked what @Frenzie and @poire-z pointed out with "edit bookmarks/highlights to include further notes", but the result is what @KenMaltby mentioned [here](https://github.com/koreader/koreader/issues/3415#issuecomment-338994047) and [here](https://github.com/koreader/koreader/issues/3415#issuecomment-339039760). This is a way to add notes and checking them using the device, but don't appear when you export them using the Evernote plugin (on an ePub file, exporting to html). Export to the local clipping text file is not working for me (telling me there is nothing to export, mabye same as [#4019](https://github.com/koreader/koreader/issues/4019) or related to [#3690](https://github.com/koreader/koreader/issues/3690)), but I didn't fight too much to make it work after seeing the result in the html export.

@KenMaltby What I'm trying to understand now is if KOReader works for me or not, regardless of the device. The way how Kobo orders the notes is not useful for me, and if KOReader is not useful for my purposes either, I'll be forced to switch to Kindle (and then, if at some point KOReader includes the features I need, I can always return and install it on my Kindle).

@KenMaltby @poire-z I'm a Mac user, but I have bootcamp installed with Windows. Is not practical for me to switch to Windows each time I want to manage the notes, but I gave a try to KoHighlights. Same result as exporting html with the Evernote plugin.

@poire-z Using the text editor seems the only way to do what I need without using another device or pen+paper, but I have my doubts if it will be practical for me. I'll check it out. 

Thank you all for your quick responses.

**Comment by poire-z** [comment]
I didn't even know we had that export to HTML feature :)
It's somehow working on the emulator (with missing edits), and it's kinda pretty:

![image](https://user-images.githubusercontent.com/24273478/51070334-d7c0d380-163f-11e9-8eea-6febb9e09017.png)

The export to html code ([exportBooknotesToHTML](https://github.com/koreader/koreader/blob/ab09dedf33e3cc18f3cf84530d88a77f8ac90cc6/plugins/evernote.koplugin/main.lua#L463-L474), [note.tpl](https://github.com/koreader/koreader/blob/master/plugins/evernote.koplugin/note.tpl) and [slt2.lua](https://github.com/koreader/koreader/blob/master/plugins/evernote.koplugin/slt2.lua)) does not look that complicated, so I guess it shouldn't be hard to enhance or fix (but probably not withing a week). Any taker?

> 3. highlights text and export, but, no notes

So, OK, there are 2 things:
- The note _taking_ part. Does what we have (edit highlight, hold and edit bookmark) is enough?
- The note _exporting_ part, which seems to be there but might tbe broken, but could still be _attractive or fun or challenging to be developed_

**Comment by arooni** [comment]
Would love to see this how it's implemented in Kindle devices.  Note stored separately from highlights

**Comment by retrography** [comment]
The same here. This is the main missing feature that prevents me from using Koreader as my default reader for PDF files on all devices.

**Comment by poire-z** [comment]
Looking at the animated screenshots at https://www.amazon.com/b/?node=11627044011 (and screenshot in https://github.com/koreader/koreader/issues/3054#issuecomment-423662217), it seems we could make most people happy with just doing the trick proposed by @embryo10 in #4115:
> So, how about using this "Add Note" option to highlight and open the edit dialog in one go?

(If we later wish to add the feature to save notes into the PDF file, we can just add a checkbox in `Document>` to additionally do that - like we already have `Document> Save document (write highlights into PDF)` )

Cause a Notes looks just like a highlight, with some comment added, and that comment could just be added in the book settings in the `bookmarks` section, as it was discussed in #3415.

That would not look complicated. The minor sad thing is that we already named the setting that holds the original text: `bookmark["notes"]` - while the setting that holds the edited or replaced original text (so, a note :) is named `bookmark["text"]`... So, the _note_ should go in `bookmark["text"]` , or a new `bookmark["comment"]` if we don't want to mess too much with past things.
(Examples of the `bookmarks` and `highlight` data structures in https://github.com/koreader/koreader/issues/3415#issuecomment-338996571 - might be out of date. I understand `highlight` is mostly used for the technical drawing of them - and that our stuff should go in `bookmarks`.)

How the user can see them later is another question or enhancement: mixed like we currently do in the Bookmarks list, or in individual lists like Kindle. We could just extend our Bookmakes view to display 4 tabs: `All | Bookmarked pages | Highlights (plain) | Highlights (annotated)`.

Pinging @embryo10 as you already gave some thoughts to this.

**Comment by embryo10** [comment]
This will be really helpful (lots of clicks wasted there..)

About the naming problem, the "notes"/"text" keys should not get swapped, because older KoReader versions might corrupt newer `metadata.epub.lua` files and vice versa. The same goes for the KoHighlights app.
I think its fine to have the "notes" with the original text and a "comments" key with the comments.

As @poire-z mentioned, in the `metadata.epub.lua` the "text" key resides in the "bookmarks" key and not in the "highlight". Also, these two keys have most of their contends the same.
E.g. All the keys in a "highlight" (["pos1"], ["text"], ["pos0"], ["datetime"]) are also in the "bookmark" entry. The only key specific to "highlight" is the ["drawer"].
It seems so easy to merge them, but I'm missing something for sure here ;o)

About the user display, perhaps two tabs ("Bookmarks" and "Highlights") are enough, since I always used these two differently.
For me a Bookmark is a "mark" of a page and a Highlight is a "mark" of some text..

**Comment by arooni** [comment]
The above solution sounds elegant but I'm not familiar with the code base.  I saw PDF mentioned several times... I'd hope that the solutions would work for all documents formats (epub mobi etc )...

**Comment by Quintus** [comment]
> The note taking part. Does what we have (edit highlight, hold and edit bookmark) is enough?

I suggest allowing multiple kinds of highlights in a document, either via colour (not feasable on monochrome displays), or (preferred, because works on monochrome) underlining with straight lines, dashes, points, overline, etc. Different shades of gray as background colour could also work, but may not be visually distinguishable easily.

Use case: I'm a (German) law student and need to read and work through lots of articles and court decisions. In these texts I usually need to mark arguments pro and contra certain positions. It would be great if I could just use different kinds of highlight to distinguish these arguments at a glance. Adding a note for each highlight using the bookmark rename trick would be quite a bit of work, and doesn't give a quick overview when viewing the document.

Background: I recently purchased an old used Kobo eReader for playing around with eReaders as I have no experience with them. I'm still finding my way around hacking them, but the default reader (nickel) appears to be a little limited to me and KOReader looks like a good alternative.

**Comment by Frenzie** [comment]
With document → highlighting you can already do that, actually.

Underline (_permettant_), invert (_un rapport_) and lighten (_celui_):
![Screenshot_2019-04-10_21-39-49](https://user-images.githubusercontent.com/202757/55908254-37942f80-5bd9-11e9-8d7d-8074e9bfa52b.png)

**Comment by Frenzie** [comment]
@Galunid Interested in creating another cycler? ;-)

**Comment by Quintus** [comment]
Oh cool. Thank you for the pointer! Now I really need to get into getting KOReader onto the device.

**Comment by NiLuJe** [comment]
@Quintus : I tried to make that as painless as possible for new users ;).

See [wiki](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices) and the [install scripts](https://www.mobileread.com/forums/showthread.php?t=314220) ;).

**Comment by Galunid** [comment]
@Frenzie Sure, I didn't really know you could do that. I always thought it was one type for all highlights. I'll try to find some time tomorrow. Btw this is pretty cool feature.

**Comment by poire-z** [comment]
I don't know if people who highlight and add notes need to distinguish simple highlights from hightlights with notes - but if yes, there could be some menu options to associate one of these 3 styles to simple highlights and another to those with notes.

**Comment by Quintus** [comment]
@NiLuJe I already got things to work by now. I installed ksm and then koreader, and of course I tried the advice given above on highlighting. Everything works like a charm so far. Great work! Thank you everyone!

Why did I use the manual method? It's nothing against your work, really! I just like to know what's going on on my devices and how everything works together. I actually already was through [this page](https://wiki.mobileread.com/wiki/Kobo_Touch_Hacking) and enabled telnet to get a root shell (which turned out to not be required thanks to KoboRoot.tgz, but was still fun -- maybe I return to it when fiddling with [getting Debian on the device](https://github.com/lgeek/okreader)). But that's just me. I appreciate your efforts and will sure recommend it.

> I don't know if people who highlight and add notes need to distinguish simple highlights from hightlights with notes

My use case would be actually against that. I need to add notes to at least two different kinds of highlights; if I find an argument not convincing on either side of a dispute, I note what I think about it at it. That should work with any of the available highlights as I use the highlights to distinguish the two sides.

Thanks everyone!

**Comment by Frenzie** [comment]
@Quintus Also see network → SSH server in KOReader. At first I didn't really see the point, but I've come to be quite fond of it.

**Comment by Quintus** [comment]
@Frenzie Very nice feature indeed. Thanks for the hint!

**Comment by beelzebielsk** [comment]
> I don't know if people who highlight and add notes need to distinguish simple highlights from hightlights with notes - but if yes, there could be some menu options to associate one of these 3 styles to simple highlights and another to those with notes.

I'd like to be able to distinguish between the two. I prefer how the kindle does it: it adds a little footnote number to the highlight, it numbers your notes. Since notes are currently indistinguishable from bookmarks/highlights numbering might be funny. I'd settle for just a little box or dot where the kindle puts the number.

**Comment by Toromtomtom** [comment]
FYI: I have drafted a [pull request](https://github.com/koreader/koreader/pull/7411) that allows storing the bookmark contents into the corresponding PDF annotation.

**Comment by poire-z** [comment]
Implemented in #7411
