### ISSUE TITLE
FR: Enable access to Wikia/Fandom pages in the Wikipedia plugin

### ISSUE THREAD

**Issue by aero31aero** [koreader/koreader#10959]
**Does your feature request involve difficulty completing a task? Please describe.**
I'd love to be able to access Wikia/Fandom pages of a book/fandom easily.

**Describe the solution you'd like**
Since there is some overlap between the Wikipedia plugin and what I am thinking of here, I figured this would be the right place to start a discussion on it.

If we could configure the "wiki" url to be, say, `https://my-favorite-series.fandom.com`, would we be able to access the pages directly, as well as how Wikipedia pages work?

In the best case scenario, I'd love to be able to just type in a url when reading a book, and hopefully that setting will be respected for that book.

**Describe alternatives you've considered**

Downloading a dump of the fandom-dot-com wiki, and converting it to a dictionary, then sending that dictionary to KOReader's dictionary folder. It'd definitely work, but it'd be a headache, and also, you'd have to keep the dictionary up-to-date periodically.

**Additional context**

My current usecase is reading a weird Chinese novel with way too many characters and I'm sure I'm forgetting half the characters, but I don't wanna pull up my phone to look them up while reading when KOReader could theoretically handle this.

**Comment by pazos** [comment]
Hi

The wikipedia feature isn't a plugin. It is part of the core application. See [readerwikipedia.lua](https://github.com/koreader/koreader/blob/7d3456edc104940af1445e48194d3bb919ab7593/frontend/apps/reader/modules/readerwikipedia.lua) and [ui/wikipedia.lua](https://github.com/koreader/koreader/blob/7d3456edc104940af1445e48194d3bb919ab7593/frontend/ui/wikipedia.lua).

I'm fairly sure we won't want to add more complexity in the core for a niche user case :)

My two cents would be: 
1. start by moving the wikipedia to a proper plugin. 
2. submit a patch that keeps the current behaviour as is.

Even if the patch is rejected because reasons I could figure out right now you'll have most of the work done for your fandom/wikia plugin. Just copy `wikipedia.koplugin` to `wikia.koplugin` and start hacking :)

**Comment by poire-z** [comment]
Yes, probably too niche and user-taste-and-interest-variable for us to accept anything like that.

Wikipedia has the feature of being generic enough and informative on many topics, and available in many languages, all by using a single common API.

> If we could configure the "wiki" url to be, say, https://my-favorite-series.fandom.com, would we be able to access the pages directly, as well as how Wikipedia pages work?

Depends if your Wiki site uses the [MediaWiki code](https://github.com/wikimedia/mediawiki). Some other Wiki sites than Wikipedia do use the MediaWiki system, and they probably inherit the API Wikipedia provides. So, if it's the case, you could just change the URL at:
https://github.com/koreader/koreader/blob/7d3456edc104940af1445e48194d3bb919ab7593/frontend/ui/wikipedia.lua#L22-L25

You could even do that from a [user patch](https://github.com/koreader/koreader/wiki/User-patches) that you could enable when you need it on some books, instead of Wikipedia.

If not, there's a whole bunch of code to rewrite to use any API of your Wiki site, or parse HTML pages if there is not - and we don't want to know about it :)

> My current usecase is reading a weird Chinese novel with way too many characters and I'm sure I'm forgetting half the characters, but I don't wanna pull up my phone to look them up while reading when KOReader could theoretically handle this.

When I know that there will be many characters in that book, I start highlighting their names in the section that introduce/present them - so I can quickly find them back from our Bookmarks list.

**Comment by aero31aero** [comment]
Yeah, I didn't bother mentioning this earlier, but of course being Mediawiki based would be a prerequisite. For example, fandom.com wikis all support `https://wiki-name.fandom.com/api.php?action=query....` type URLs. Slight difference from Wikipedia, its not /w/api.php, which I'm not sure why, but I'm hoping just changing the URL will work, in which case, I'd be happy with just writing a user-patch.

**Comment by aero31aero** [comment]
I played around with this and well, fandom wikis apparently don't like exposing the API in standard ways? That, plus fandom itself being a very morally weird space, makes me agree that this feature doesn't need to be a part of KOReader. A workaround is downloading the wiki's export file and making a dictionary for KOReader, like I suggested initially.
