### ISSUE TITLE
FR: support to toggle WiFi on rooted Android

### ISSUE THREAD

**Issue by Gabriel85** [koreader/koreader#10980]
On Android it is not possible to toggle WiFi on or off automatically. Instead it opens the system dialogue.
On rooted devices the shell command "svc wifi [enable|disable]" could be used instead.
I have tested it on Android 4.4 and 13, so it should be fine with all supported versions.

**Comment by pazos** [comment]
No, not planned.

I guess you can make yourself an user-patch by overriding parts of https://github.com/koreader/koreader/blob/master/frontend/device/android/device.lua#L288-L308 and just `os.execute`'ing the command.

**Comment by Gabriel85** [comment]
I was thinking about that. But I have no clue how to use one to redefine a function. Any tips?
But still I think it would be useful in general, since Koreader already uses root, when available, for setting the warm light.

**Comment by NiLuJe** [comment]
Well, nothing fancy, require NetworkMgr and just c/p your variant of

```
    function NetworkMgr:turnOnWifi(complete_callback)
        android.openWifiSettings()
    end
    function NetworkMgr:turnOffWifi(complete_callback)
        android.openWifiSettings()
    end
```

In a late patch (IIRC, 2-).

**Comment by pazos** [comment]
Yup, what NiLuJe said.

Remember to gather logs with adb . After all, that `svc wifi` should be a command present on the device and reachable by applications. SELinux context would prevent apps to reach privilegied commands, but I guess that's the power of `sudo` on modern android devices.

> But still I think it would be useful in general, since Koreader already uses root, when available, for setting the warm light.

Yep, they (eink and warmth) are the exceptions where root is allowed. Mostly because there's no APIs and the mess is confined to a few devices that use that particular driver.

Root stuff on common code would be a mess. Specially because there're also API calls to do what you intend to do with root. 

We used that in the past, but have no fine grain control over what happens on the background. See https://github.com/koreader/koreader/issues/5787 for some context.
