### ISSUE TITLE
FR: Make style tweak groups individually selectable 

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#11161]
**Does your feature request involve difficulty completing a task? Please describe.**

I try to keep most of the publisher's original style choices and apply tweaks only where I'm really bothered by some detail. The KOReader style tweaks offer great flexibility, but unfortunately follow kind of an 'all or nothing' approach. Turning on (or off) just a small part of the tweaks requires many taps and meddling with deeper menu settings to check/uncheck selections for a particular book.

For example, for some books I'd just like to adjust the justification; for others I don't like the footnotes. On others again it may only be some paragraph or line spacing issue. The KOReader built-in style tweak presets allow tweaking all of these with a neatly organized UI, but doesn't currently allow selecting or unselecting the individual groups of tweaks I prefer for a particular book.

**Describe the solution you'd like**

Allow checking/unchecking the style tweak categories as well as the user and book specific tweaks separately:

![image](https://github.com/koreader/koreader/assets/95502269/bcba16b5-db11-4720-bb13-b53c38b5ef5f)

- When checked, the number of tweaks enabled in the submenus shown in parentheses will be active
- When unchecked, the parentheses will still show the number of tweaks selected in the submenus, but they will be inactive

**Describe alternatives you've considered**

A lighter (but less flexible) alternative would be to just allow the control of the user and book-pecific style tweaks separately, like this:

![image](https://github.com/koreader/koreader/assets/95502269/9831724a-e75c-4b90-b960-4b79a01502b5)

(This way, individually selectable user style tweaks can be added and activated without having to unselect all of the KOReader preset tweaks.)

**Additional context**

An additional FR would be that long-pressing a user style tweak adds a button `Open in text editor` (similar to how long pressing user patches opens them in the text editor). This would make it a lot easier to quickly adjust some user style settings in the CSS file.

**Comment by hius07** [comment]
A profile with a group of tweaks?

**Comment by mergen3107** [comment]
My thoughts exactly. 

You are not using them in full. 
1) Add tweaks to dispatcher by long pressing them. 

2) Create one profile per "group". 

3) It is not advisable to enable ALL tweaks in a single group, because many things are contradictory. For example, widows/orphans. So keep track of performance impact when applying these groups as well.

**Comment by mergen3107** [comment]
4) Even if this is not enough, create your own style tweaks and repeat steps 1-3 above.

**Comment by poire-z** [comment]
I don't think this make sense, except for not having to go into the submenu. These categories are just for organizing the tweaks and make have the menus short. You usually start from 0, then enable the ones you think you need, see if they work, and if they don't, disable it and enable another one. At the end, you probably have only 1 or 2 by "category", possibly not really related, and you don't even remember which. Enabling/disabling a "category" would just speed things up when.... when what ?
All these tweaks are done when you start reading a book. We both spend a 3-15 minutes setting up tweaks when starting a book, I don't think the few seconds you would gain with that matter.

Moreover, it's technically complex to implement (need to keep the ones checked in the list, and have another list of the disabled parent catagories...), and UI-wise cumbersome (more visual noise for no obvious practicality).

> A lighter (but less flexible) alternative would be to just allow the control of the user and book-pecific style tweaks separately, like this:

That I can understand, and I did miss that in the past and was bothered having to go into the submenu to disable _some_ tweaks while keeping my "Book style tweaks" (often, because I had another better handmade variation). But often, there were others I did not have to override and want to keep. So, the use case is again limited.
Also, it was bothering mostly because at the time, it needed a full rerendering each time you toggle a tweak. But since partial rerenderings, this has never been an issue. Just a few finger dances to go into our quick menus and really find out what I have and decide if I want that disable or not.

> An additional FR would be that long-pressing a user style tweak adds a button Open in text editor (similar to how long pressing user patches opens them in the text editor). This would make it a lot easier to quickly adjust some user style settings in the CSS file.

Open Text editor and then what? Clone it as a user style tweak ? Append it to Book style tweak?
We already have something more versatile: after long-press on a tweak, you see its description and source CSS. You can tap that monospace CSS part to copy it into the clipboard, and then you can go into Book style tweak to paste it, where you want it, and edit/fix/adapt it.

**Comment by jonnyl2** [comment]
Thank you all for the responses and advice.

I just updated to the latest nightly (server is back up, yay!) but I am still running into the issue mentioned in closed issue #11071; adding a style tweak to the action list works fine, but removing it causes KOReader to crash. I pasted the stack traceback below but I'll gladly open a separate bug report if requested:


<details>

<summary>Crash details</summary>

```
./luajit: plugins/gestures.koplugin/main.lua:1221: attempt to index local 'gesture' (a boolean value)
stack traceback:
	plugins/gestures.koplugin/main.lua:1221: in function 'updateProfiles'
	plugins/profiles.koplugin/main.lua:393: in function 'updateProfiles'
	frontend/apps/reader/modules/readerstyletweak.lua:570: in function 'toggle_tweak_in_dispatcher_callback'
	frontend/apps/reader/modules/readerstyletweak.lua:131: in function 'callback'
	frontend/ui/widget/buttontable.lua:80: in function 'callback'
	frontend/ui/widget/button.lua:415: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:262: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:907: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1436: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1534: in function 'handleInput'
	frontend/ui/uimanager.lua:1578: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x000140cd
!!!!
Uh oh, something went awry... (Crash n°1: 11/27/23 @ 12:25:30)
Running FW 4.35.20400 on Linux 3.0.35+ (#5031 PREEMPT Tue Mar 30 14:26:27 CST 2021)
Attempting to restart KOReader . . .
!!!!
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/27/23-12:25:45
 [*] Version: v2023.10-35-gd3787eee6_2023-11-27
```

</details>

Poire-z:
>after long-press on a tweak, you see its description and source CSS. You can tap that monospace CSS part to copy it into the clipboard, and then you can go into Book style tweak to paste it, where you want it, and edit/fix/adapt it.

I didn't know about this and that is indeed helpful. As a side question, is there any way to quickly delete the contents of the whole file in the text editor? I've often had the need to just wipe the document and start from scratch, but I couldn't find any way of doing this. 

I'll close this as completed as the original item has been resolved. If I have any further question on style tweak set-ups, I might follow up in here. I hope that's okay. Thanks again.

**Comment by hius07** [comment]
> adding a style tweak to the action list works fine, but removing it causes KOReader to crash

Cannot reproduce.
Can you show your koreader/settings/gestures.lua.

**Comment by jonnyl2** [comment]
>Cannot reproduce.
Can you show your koreader/settings/gestures.lua.

[gestures.lua.txt](https://github.com/koreader/koreader/files/13474814/gestures.lua.txt)

**Comment by hius07** [comment]
Thank you, I do not use custom multiswipes that cause the crash. I'll fix soonest.

**Comment by jonnyl2** [comment]
@poire-z Are contractions in letter spacing not supported? E.g. `body {letter-spacing: -.1em}`

I thought I was going mad trying to add this tweak as nothing happened. Then I changed it to a positive (expansion) and that works fine.

**Comment by mergen3107** [comment]
Did you try `Word expansion` in the bottom menu? Altough it applies expansions to all the text...

**Comment by jonnyl2** [comment]
@mergen3107 Unfortunately it also doesn't allow contractions.

**Comment by poire-z** [comment]
Looks like since 2019, we expect letter-spacing to be positive when parsing:
https://github.com/koreader/crengine/pull/273/files#diff-2264ac60342dc99df1cb88bd8bcb2a2531312c3359a52365d0382f9b96aa358b
(so, my `// only margin accepts negative values` seems to be a lie :)).

But even if the field holding letter_spacing has always been a "signed int" (so, accepting negative values), since 2008, it would have been capped to 0:
https://github.com/koreader/crengine/blob/f6abee69d5ea10660e0e76f76c3cb41ce1fa1fbe/crengine/src/lvfntman.cpp#L4052-L4066

So, yes, negative letter-spacing is not supported.
Seems nobody (except you :)) has ever complained about it.
Anyway, not sure I'd want to do anything about it, why make the text uglier ? :)

**Comment by jonnyl2** [comment]
Thank you. On an older device I had (that didn't support KOReader), the software (possibly MoonReader) supported contracting and expanding the letter spacing via swipe gesture along the edge of the screen. I thought some fonts looked much better with contracted letter spacing (especially in two-column mode), and it allowed for more text as well.

But it's not a huge deal :)

**Comment by jonnyl2** [comment]
Hi @poire-z, I have some questions on word spacing, if I may. Specifically, 

1. How is the distribution of the widths of the spaces determined, and how are they measured (e.g., empty space between the last and first letters of the two words, or some other reference points)?

2. Is there a way to tweak the spacing after certain letters (e.g., after punctuation)?

For example, most spaces on these 2 lines are about 10-13px wide, but the space after the period is only 7px:

![image](https://github.com/koreader/koreader/assets/95502269/1899f7ae-0d9e-4436-85ed-4bfe534b49a4)

<img width="120" alt="image" src="https://github.com/koreader/koreader/assets/95502269/8de051ed-1df5-4e49-b547-b240d160b7f7">

What causes the much reduced space after the period? (I could provide more examples if needed.)

For info, I set the scaling to 95% and the reduction to 85% -- doesn't that mean that the width of a space should not go lower than 81% of its regular width (.95*.85)? It seems that some of the spaces get narrower than the expected width, especially after punctuation marks.

**Comment by jonnyl2** [comment]
Could it be that the period is ignored for some reason?

Without it, the width would be 11px, so in line with the other spaces:

<img width="174" alt="image" src="https://github.com/koreader/koreader/assets/95502269/94b01974-9f15-47ac-a9fd-e8227b470ef8">

**Comment by poire-z** [comment]
> For info, I set the scaling to 95% and the reduction to 85% -- doesn't that mean that the width of a space should not go lower than 81% of its regular width (.95*.85)? 

Looks like you got how it works right, so I won't explain more (details about how crengine does text justification must be in my various Word Spacing PRs).

There is **no** specific/different handling in the code of a space following punctuations.

So, all that you may see is probably caused:
- by the font (negative left side bearing of your `T` for example, having parts of its glyph drawn before it's "origin x" (our code, when adjusting spacing, just sizes spaces (all on a line by the same amount) by making them smaller or larger than their nominal width, so moving the "origin x" of the glyph after them).
You can check how strong this is with various fonts, I guess it may be quite variable.
- And by the font kerning (which can furthermore adjust this "origin x" depending on the previous char; that is, `oT` or ` T` or `TT` won't have the T on the right at the same shift after their previous character).
You can set Kerning to off (or between fast and best to see if the kerning implement between FreeType and Harfbuzz differ) in the bottom menu to see how this plays.

> Is there a way to tweak the spacing after certain letters (e.g., after punctuation)?

None in crengine/KOReader. It's all font designer decisions, that we (not we, but Freetype and Harbuzz, just interpreting the rules in the font files) follow. Only by hacking the font itself and tweaking its kerning tables (so you can kill any kerning it may have been ` ` and `T`).

**Comment by jonnyl2** [comment]
Thank you, that's very helpful. The spacing after punctuation marks does seem to be better with other fonts. That's a pity, because I really liked the Adobe Caslon Pro font.
