### ISSUE TITLE
EPUB only shows one page: Jono Bacon, The Art of Community, second Edition (archive.org)

### ISSUE THREAD

**Issue by kolAflash** [koreader/koreader#11268]
* [f-droid.org](https://f-droid.org/en/packages/org.koreader.launcher.fdroid/)
  * KOReader version: v2023.10 (Android)
  * Device: Fairphone 3+ (Android-12, [e/OS/-12.3](https://e.foundation/))
* [github.com: koreader-android-arm64-v2023.10.apk](https://github.com/koreader/koreader/releases/download/v2023.10/koreader-android-arm64-v2023.10.apk)
  * KOReader version: v2023.10 (Android)
  * Device: Google Pixel 4a (Android-13)

#### Issue
EPUB does not open. KOReader shows only a single white page.  
https://archive.org/download/ArtOfCommunitySecondEdition/Art_of_Community_Second_Edition.epub

_(It is a free ebook. See PDF from original authors website: https://www.jonobacon.com/wp-content/uploads/2019/01/jonobacon-art_of_community_second_edition.pdf )_

**Comment by mergen3107** [comment]
Verbose crash.log please?

**Comment by Frenzie** [comment]
No need, it reproduces easily without showing anything of interest.

epubcheck is not super happy with this file btw. It might be related.

**Comment by Frenzie** [comment]
Yeah, I think the explanation is fairly simple: all the text/html pages are ignored.

@poire-z given we have a pretty decent text/html parser do you suppose this is easy to ignore?
```xml
  <manifest>
    <item href="nav.xhtml" id="nav" media-type="application/xhtml+xml" properties="nav"/>
    <item href="notice.html" id="chapter_0" media-type="text/html"/>
    <item href="page_0.html" id="chapter_1" media-type="text/html"/>
<!-- etc. -->
```

**Comment by poire-z** [comment]
We discussed our 2 parsers previously in #8306 and https://github.com/koreader/crengine/pull/370.

But this is not the issue with this book. Here, crengine fails finding any HTML file because of these `media-type="text/html"`, and it expects only `application/xhtml+xml`.
Change all of these `text/html` to `application/xhtml+xml`, and it works: these HTML files are properly balanced XHTML.
I don't know if the EPUB specs says we should consider `text/html`.

But this books and these HTML files suck :) each HTML file is probably a OCR of each hardcopy book's page, sentences are cut, there is no formatting....

So, given than 1) this is the first report of such an EPUB and 2) the EPUB itself sucks and is probably just from some automated otherformat to EPUB quick ugly crappy transformation program.... I'm for not doing anything about it :)

**Comment by Frenzie** [comment]
Works for me. As stated epubcheck is quite clear about the problem.

**Comment by kolAflash** [comment]
Thanks for checking this! :-)

Additional finding:  
The [linked](https://archive.org/download/ArtOfCommunitySecondEdition/Art_of_Community_Second_Edition.epub) epub file opens fine in [MuPDF-viewer-1.23.7a](https://f-droid.org/de/packages/com.artifex.mupdf.viewer.app/) on Android and in [Calibre-6.13](https://calibre-ebook.com/) on Debian-12 GNU/Linux.

**Comment by poire-z** [comment]
Different ways to parse the OPF file:

We first parse the MANIFEST and keep track of all files and their type - and then parse the SPINE, which tells in the correct order which HTML file makes out the book, and we check they are indeed in the manifest with a correct media-type.

MuPDF directly goes at parsing the SPINE and use the file as-is (assuming that if it is in the SPINE, it is a valid HTML file). Which somehow makes sense and is forgiving to crappy media-type. I don't see at a glance a reason of not doing it that way - but our parsing is quite complex that I don't really want to go at modifying it. (That is, until I stumble on a correct EPUB just like yours and I need to have it work :))

Or maybe... I think I've read that the SPINE can contain other things than HTML files, like SVG files. So, MuPDF may have issues with such EPUBs, maybe just no real harm if they just fail parsing these SVG files as HTML and ignoring them. Dunno.

**Comment by Frenzie** [comment]
> Or maybe... I think I've read that the SPINE can contain other things than HTML files, like SVG files. So, MuPDF may have issues with such EPUBs, maybe just no real harm if they just fail parsing these SVG files as HTML and ignoring them. Dunno.

This one also had jpegs iirc.

**Comment by poire-z** [comment]
In the manifest, yes, there should be all the files in the zip, including images and css.
But in the spine, only xhtml (+ possibly svg) that makes the fragments:
```xml
  <spine toc="ncx">
    <itemref idref="cover"/>
    <itemref idref="nav"/>
    <itemref idref="chapter_0"/>
    <itemref idref="chapter_1"/>
    <itemref idref="chapter_2"/>
...
```

**Comment by poire-z** [comment]
Another point about this: if we were to relax this requirement and accept files with mediatype other than `application/xhtml+xml` (ie. `text/html` or `*/*html*`), we get the risk of previously opened documents, having parts we did ignore, getting them now, and having all highlights made previously no longer corresponding to the original document fragment index...
I don't know how serious this issue would be (people having read and highlight previously "incomplete" books :), or correct epubs having crappy text/html files at start...)

So, I guess it would need a new cre_dom_version (which I think is accessible to the EPUB parsing code), which would enable this only on books never yet opened.

So, 1) should I go at relaxing this requirement, and 2) expect "html" in the mediatype or 3) not care about the mediatype and accept anything in the `<spine>` and eat what we can eat (or fail, not caring how, when some fragment fails).

**Comment by Frenzie** [comment]
I don't think I'd bother, but since it probably won't take *that* long and you seem interested in it… why not? :-)

**Comment by poire-z** [comment]
OK, so as I need to introduce a DOM_VERSION_CURRENT bump, I tried to make it future proof.

Copying bits of my comments in the code to explain it:

```diff
-#define DOM_VERSION_CURRENT 20210904
+#define DOM_VERSION_CURRENT 20240111

+// 20240111: we now parse and create a <DocFragment> for all items in the
+// EPUB <spine>, and not only those with media-type="application/xhtml+xml".
+// This means we can insert <DocFragment> in the DOM that wouldn't be here
+// before, and risk DocFragment[index] in xpointers to get the index shifted.

 [...]
+    // Create a DocFragment for each and all items in the EPUB's <spine>
+    bool relaxed_spine = true;
+    if ( m_doc->getDOMVersionRequested() < 20240111 ) {
+        // Only accept spine items with media-type="application/xhtml+xml
+        relaxed_spine = false;
+    }

 [...]
-        if (spineItems[i]->is_xhtml) {
+        if (relaxed_spine || spineItems[i]->is_xhtml) {
             lString32 name = LVCombinePaths(codeBase, spineItems[i]->href);
             {
+                // We want to make sure all spineItems get a DocFragment made,
+                // even if we don't support or fail parsing them: we let this
+                // fact be known, and if we later fix/support their handling,
+                // we won't be inserting a new DocFragment between existing
+                // ones and get all xpointers (highlights, last page) invalid
+                // because their DocFragment index has been shifted.
+                bool handled = false;
 [...]
+                if ( !handled ) {
+                    CRLog::error("Document type is not XML/XHTML for fragment %s", LCSTR(name));
+                    appender.setFragmentType(U"SpineItemUnsupported");
+                    // Create a dummy DocFragment with info about what we couldn't handle
```

While I were at it, because SVG are supposed to be accepted in the `<spine>` (even if I have not a single book with that), I added support for them.

I'll also add some attributes to DocFragment:
-  `T=` when non-standard, unsupported or SVG, DocFragment, so we know and can target them with styletweaks to make them `display:none` if bothered.
- `Source=the/path/to/the/file.xhtml` in the EPUB, so we can see the filepath for easier investigation/fix in the EPUB (for years, I've been picking the number in the only thing we had, the number in `<DocFragment id='_doc_fragment_6'>` and count spine items in the .opf, never knowing if I should start counting at 0 or 1.... This will make that easier.)

So, we may get spurious pages in the book (here in scroll mode to show more of them).
With this .opf:
```xml
  <manifest>
    <item href="pgepub.css" id="item1" media-type="text/css"/>
    <item href="www.gutenberg.org@files@17646@17646-0-0.html" id="id00000" media-type="application/xhtml+xml"/>
    <item href="../svgs/drawing.svg" id="svg1" media-type="application/svg+xml"/>
    <item href="../test-html5.html" id="html1" media-type="application/xhtml+xml"/>
    <item href="../test-htmlbad.html" id="htmlbad1" media-type="text/html"/>
    <item href="../test-htmlbad2.html" id="htmlbad2" media-type="text/html"/>
    <item href="cover.jpg" id="item2" media-type="image/jpeg"/>
  </manifest>
  <spine toc="ncx">
    <itemref idref="html1" linear="yes"/>
    <itemref idref="htmlbad1" linear="yes"/>
    <itemref idref="htmlbad2" linear="yes"/>
    <itemref idref="svg1" linear="yes"/>
    <itemref idref="item1" linear="yes"/>
    <itemref idref="item2" linear="yes"/>
    <itemref idref="id00000" linear="yes"/>
```
![image](https://github.com/koreader/koreader/assets/24273478/73563ea4-84fc-405e-bf32-25cf6ffe27ff)

With this kind of DOM:

![image](https://github.com/koreader/koreader/assets/24273478/5e1bc960-0b4e-441b-8090-7ec213275579)
![image](https://github.com/koreader/koreader/assets/24273478/cee79d8b-a3bb-48a9-82ff-39f06e46f173)
![image](https://github.com/koreader/koreader/assets/24273478/f107b35a-f19e-43f9-b749-d83bb848779e)
![image](https://github.com/koreader/koreader/assets/24273478/877bed50-c22c-4892-b021-e1f2a7ebfdb5)

Fine with these ideas - and bothering the users with info in hardcoded english about items not supported (rather than letting them not know about that) ?
