### ISSUE TITLE
Crash on document open

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#11348]
* KOReader version: 2024.01-10
* Device: Onyx Page fv 3.5(Android 11)

#### Issue
Crash on opening any document. 
#### Steps to reproduce
Start KOreader. History and file manager appear OK. When any document (either ePUB or PDF is opened, its text appears and immediately after that cras log page pops up.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:
[bluetooth_content_share_121627.log](https://github.com/koreader/koreader/files/13927748/bluetooth_content_share_121627.log)

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by ptrm** [comment]
+1 on Onyx Tab Ultra C, firmware 3.5 (2023-11-22_07-29_3.5_946657f755, Android 11)
[crash.txt](https://github.com/koreader/koreader/files/13927946/crash.txt)

**Comment by pazos** [comment]
Cannot reproduce here on regular android devices (phone, tablet, emulators).

Please get me logs (pidcat if possible).
See https://github.com/koreader/koreader/blob/dcfcc81dcf54f9347841b5d303075e7c8d9941f3/kodev#L1167-L1181

 The crash activity at this point is useless on devices that tend to crash (onyx, ireader, some samsung stock, pixels...) and only provides relevant info (info before the crash itself) on devices that are rock solid :/

**Comment by ilyats** [comment]
I attached a crashlog in the main message

**Comment by NiLuJe** [comment]
> I attached a crashlog in the main message

And as was mentioned earlier, whatever was attached is completely unhelpful. Please get us proper logcats/pidcats as detailed above.

**Comment by NiLuJe** [comment]
> Stable 2024.01 works fine

That's... interesting, because there aren't really many changes involved...

https://github.com/koreader/koreader/compare/v2024.01...dcfcc81dcf54f9347841b5d303075e7c8d9941f3

(So, yeah, definitely want logs w/ verbose debug logging enabled ;)).

**Comment by hugleo** [comment]
@NiLuJe , is because the commit from yesterday https://github.com/koreader/koreader-base/commit/5f9b9b6f89d6865ba0247adc09aecaa593c9e03f

Crash here because nil values: https://github.com/koreader/koreader-base/blob/master/ffi/blitbuffer.lua#L1075C1-L1075C23

Seems fine when we start kroeader UI.

01-13 14:52:23.965  8412  8444 V KOReader: blitFrom 292 2349 0 0 124 124
01-13 14:52:23.965  8412  8444 V KOReader: Debung Info
01-13 14:52:23.965  8412  8444 V KOReader: x  292
01-13 14:52:23.965  8412  8444 V KOReader: y  2349
01-13 14:52:23.965  8412  8444 V KOReader: w  124
01-13 14:52:23.965  8412  8444 V KOReader: h  124
01-13 14:52:23.965  8412  8444 V KOReader: alignment  nil
01-13 14:52:23.965  8412  8444 V KOReader: max_w  1860
01-13 14:52:23.965  8412  8444 V KOReader: max_h  2480
01-13 14:52:23.965  8412  8444 V KOReader: Debung Info
01-13 14:52:23.965  8412  8444 V KOReader: x  523
01-13 14:52:23.965  8412  8444 V KOReader: y  2342
01-13 14:52:23.965  8412  8444 V KOReader: w  138
01-13 14:52:23.965  8412  8444 V KOReader: h  138
01-13 14:52:23.965  8412  8444 V KOReader: alignment  nil
01-13 14:52:23.965  8412  8444 V KOReader: max_w  1860
01-13 14:52:23.965  8412  8444 V KOReader: max_h  2480
01-13 14:52:23.965  8412  8444 V KOReader: blitFrom 530 2349 0 0 124 124
01-13 14:52:23.965  8412  8444 V KOReader: Debung Info
01-13 14:52:23.965  8412  8444 V KOReader: x  530
01-13 14:52:23.965  8412  8444 V KOReader: y  2349
01-13 14:52:23.965  8412  8444 V KOReader: w  124
01-13 14:52:23.965  8412  8444 V KOReader: h  124
01-13 14:52:23.966  8412  8444 V KOReader: alignment  nil
01-13 14:52:23.966  8412  8444 V KOReader: max_w  1860
01-13 14:52:23.966  8412  8444 V KOReader: max_h  2480
01-13 14:52:23.966  8412  8444 V KOReader: Debung Info
01-13 14:52:23.966  8412  8444 V KOReader: x  761
01-13 14:52:23.966  8412  8444 V KOReader: y  2354
01-13 14:52:23.966  8412  8444 V KOReader: w  337
01-13 14:52:23.966  8412  8444 V KOReader: h  113
01-13 14:52:23.966  8412  8444 V KOReader: alignment  nil
01-13 14:52:23.966  8412  8444 V KOReader: max_w  1860
01-13 14:52:23.966  8412  8444 V KOReader: max_h  2480
01-13 14:52:23.969  8412  8444 V KOReader: Debung Info
01-13 14:52:23.969  8412  8444 V KOReader: x  1198
01-13 14:52:23.969  8412  8444 V KOReader: y  2342
01-13 14:52:23.969  8412  8444 V KOReader: w  138
01-13 14:52:23.969  8412  8444 V KOReader: h  138
01-13 14:52:23.970  8412  8444 V KOReader: alignment  nil
01-13 14:52:23.970  8412  8444 V KOReader: max_w  1860
01-13 14:52:23.970  8412  8444 V KOReader: max_h  2480


But if we try to open a document we enter in this function function BB_mt.__index:getBoundedRect(x, y, w, h, alignment) with all nil values.

01-13 14:57:36.026  8412  8444 V KOReader: setDirty partial from widget ReaderUI w/ NO region; dithering: nil
01-13 14:57:36.026  8412  8444 V KOReader: validateAndFixToc(): quick scan
01-13 14:57:36.026  8412  8444 V KOReader: validateAndFixToc(): TOC is fine
01-13 14:57:36.027  8412  8444 V KOReader: _refresh: Enqueued full update for region 0 0 1860 2480 dithering: false
01-13 14:57:36.027  8412  8444 V KOReader: setDirty partial from widget ReaderUI w/ NO region; dithering: nil
01-13 14:57:36.029  8412  8444 V KOReader: init scroll page states nil
01-13 14:57:36.043  8412  8444 V KOReader: CoverImage: onReaderReady
01-13 14:57:36.048  8412  8444 V KOReader: android.setIgnoreInput false
01-13 14:57:36.048  8412  8444 V KOReader: Spinning up new ReaderUI instance table: 0x759eefd680
01-13 14:57:36.048  8412  8444 V KOReader: show widget: ReaderUI
01-13 14:57:36.049  8412  8444 V KOReader: _refresh: Enqueued full update for region 0 0 1860 2480 dithering: false
01-13 14:57:36.049  8412  8444 V KOReader: setDirty full from widget ReaderUI w/ NO region; dithering: nil
01-13 14:57:36.050  8412  8444 V KOReader: painting widget: ReaderUI
01-13 14:57:36.733  8412  8444 V KOReader: _refresh: Enqueued full update for region 0 0 1860 2480 dithering: false
01-13 14:57:36.771  8412  8444 V KOReader: Debung Info
01-13 14:57:36.771  8412  8444 V KOReader: x  nil
01-13 14:57:36.771  8412  8444 V KOReader: y  nil
01-13 14:57:36.771  8412  8444 V KOReader: w  nil
01-13 14:57:36.771  8412  8444 V KOReader: h  nil
01-13 14:57:36.771  8412  8444 V KOReader: alignment  nil
01-13 14:57:36.771  8412  8444 V KOReader: max_w  1860
01-13 14:57:36.771  8412  8444 V KOReader: max_h  2480
01-13 14:57:36.771  8412  8444 E NativeThread: Failed to run script: ffi/blitbuffer.lua:1075: attempt to compare number with nil

**Comment by NiLuJe** [comment]
Can you stick a `print(debug.traceback()` in there? UIManager should *never* be be passing `nils`...

**Comment by NiLuJe** [comment]
Oh, wait, I see it. Android's `framebuffer:_updateFull` >_<".

**Comment by hugleo** [comment]
Tested and working!

**Comment by mergen3107** [comment]
I like that I opened a whole can of worms :D sorry!
