### ISSUE TITLE
cr3.ini crengine.page.header.font.face does not change font from Noto Sans 

### ISSUE THREAD

**Issue by sdothum** [koreader/koreader#11418]
* KOReader version: 2023.10
* Device: Kobo Libra 2

#### Issue

cr3.ini has entry for font face. Changing it from the Noto Sans default does alter the typeface of the alt status bar.

#### Steps to reproduce

Manually edit the cr3.ini file "crengine.page.header.font.face=..." with new font family.

(looking at the original merged code i did not see any section handling crengine.page.header.font.face.. if that is the case, any chance of it being added?)

EDIT: i don't need the UI menu to be amended. i am perfectly happy to edit the cr3.ini file.

**Comment by poire-z** [comment]
This part of crengine (dealing with its own settings read/save from/into cr3.ini) is not something we actively care about and maintain. The less I have to touch all that mess, the happier I am.

Fortunately, this specific settings is setable from KOReader (and that's probably why the cr3.ini value is overridden and has no effect:
https://github.com/koreader/koreader/blob/38a14ff3a070d0d31d9d7d369863d0af5390ae16/frontend/apps/reader/modules/readerfont.lua#L174-L177

So, if you set in your settings.reader.lua `["header_font"] = "Comic Sans MS",`, you should get it.... on future opened books. Because someone had the stupid idea to save the value at opening time into each book metadata.epub.lua .... so, you'd need to manually edit each of them to remove the old value (Noto sans).
(Or user-patch ReaderFont.onReadSettings to force your preferred value.)

**Comment by hius07** [comment]
I think we can remove
https://github.com/koreader/koreader/blob/38a14ff3a070d0d31d9d7d369863d0af5390ae16/frontend/apps/reader/modules/readerfont.lua#L177
and let the setting from cr3.ini affect all books.

**Comment by poire-z** [comment]
Or may be just remove the `config:read/saveSetting("header_font_face")`, and let any one set in G_reader_settings be used ? (some users may already have set it there).

I don't like this cr3.ini stuff, its lifecycle is a bit obscure, and I would not trust it to be not overridden, and I make no garantee my past and future tweaks to crengine don't mess with or ignore/override things from it :)
If there's anything to set in crengine, I think the right way to do it is with a user-patch using stuff like
`self._document:setIntProperty("crengine.image.scaling.zoomin.block.mode", 0)`

**Comment by hius07** [comment]
The main inconvenience of settings.reader.lua is that it cannot be edited by our text editor.

**Comment by sdothum** [comment]
hius07 wrote:

> I think we can remove
> 
> self.ui.document:setHeaderFont(self.header_font_face) 
> 
> and let the setting from cr3.ini affect all books.

This appears to work! Thank you!!

This issue can be closed (as a working solution -- for now -- has been provided to me).. unless further discussion would be useful. 

I for one, love splitting information content between the alt status bar and footer status bar. Having both set to my desired font *finally!* -- i mucked around for so long without success -- adds the finishing touch to my KOReader setup.

**Comment by poire-z** [comment]
I think this has been taken care of by #11463.
