### ISSUE TITLE
FR: Using partial rendering on already opened books

### ISSUE THREAD

**Issue by molivier-fcms** [koreader/koreader#11496]
Last March @poire-z has introduced the highly welcomed partial rendering. Now changing display settings is "computing-latency-free" with big e-books... while the settings are applied inside the book.

**Does your feature request involve difficulty completing a task? Please describe.**
Let's suppose I apply a global change from a ebook X (default font size, removing progress bar ... whatever).

With my current font size, I've got a few ebooks that have hundreds of pages. Opening them requires between 20 to 45 seconds of rendering.

**Describe the solution you'd like**
For ebooks that have been already rendered once, I would opening the ebook with their current display settings (the settings they had when they have been closed), and then immediately apply the new settings and launching a partial rendering.

It would be a trick, but it could allow a quick opening while keeping the rendering process in background.

**Comment by poire-z** [comment]
I understand your request.
Not easy to solve: it would need us to remember the "global settings" state at the time of last opening of that book, to use these instead of the current ones when reopening the book. In the crengine book cache, there is just a "hash" of all the settings to just help notice that the cache has stuff that matches or not the applied settings when the book is reopened.
Remembering the old settings, just so that they are applied on book opening, to later apply any new/same global ones, feels quite tedious, and would just help with this specific (corner) case.
So, probably no go for me.

**Comment by molivier-fcms** [comment]
I understand. I had not looked at the content of the metadata stored beside ebooks. The hash you are talking about is `partial_md5_checksum` ? It's a clever idea to keep track of current settings in a such minimal way.

I agree to do not bloat koreader. I close this issue.

**Comment by poire-z** [comment]
>  The hash you are talking about is partial_md5_checksum ?

No, this one is a hash of the book file content, and shouldn't change :) it's used with our sync stuff and possibly a few other things to identify uniquely a book.

The one I'm talking about isn't stored in plain sight. It is stored as a few bytes in the binary cache files (ie. `cache/cr3cache/Louis-Ferdin-la_nuit.epub.8c007c16.1.cr3`), and it is just computed by crengine from the settings we fed to it.
Our frontend code may sometimes ask crengine what is this hash (do detect if it should recompute other things), and we see that logged in debug mode, ie.:
```
02/26/24-17:43:06 DEBUG rendering hash changed: 2756414016 > 3713667574
02/26/24-17:43:17 DEBUG rendering hash changed: 3713667574 > 3761705143

```
