### ISSUE TITLE
FR: Current Chapter Progress Bar

### ISSUE THREAD

**Issue by Bluemoondragon07** [koreader/koreader#11500]
Currently, the progress bar shows the progress for the entire book. It's nice. BUT—wouldn't a similar progress bar for the current chapter also be nice?

Ever read on Wattpad? People write loooooong books on Wattpad. This is why Wattpad only shows the progress bar for the current chapter. It makes people forget that they have 112 chapters to go and encourages them to keep reading.

I think a current chapter progress bar would be good for people who need to read a long, long book. Or maybe if they downloaded the kind of long fanfiction I'm talking about. Or need to speed-read a thick biology book.

Maybe a chapter count would also be good, as suggested in #11070.

Perhaps this option would change the default status bar to show chapter progress. Maybe it could add an extra progress bar—maybe a vertical one on the left and or right? Or—it utilizes the alternate progress bar. I don't like option 3, but that's another option. Optimally, I think it should change the regular progress bar so that the alternate one could be used for total book progress at the same time.

Just some suggestions.

**Comment by offset-torque** [comment]
I agree that this can be useful. Now I think about it, 80% of time I look at the status bar, the reason is to see how much is left in the current chapter.

**Easiest (to implement) solution I can think of:** Maybe we can assign a gesture (double tap or swipe left-right on the status bar area) to switch between "whole book progress bar" and "chapter progress bar". No extra settings or menus, it will use the same properties as the original progress bar.
