### ISSUE TITLE
The display backlight blinks when the page is fully refreshed in night mode

### ISSUE THREAD

**Issue by egodamager** [koreader/koreader#11529]
* KOReader version: 2024.03.1
* Device: KOA2

#### Issue
The display backlight blinks when the page is fully refreshed in night mode. This is a bit annoying, causing a strobe effect. Perhaps this is intended to protect against the backlight of the display when the screen is filled with white, but can I somehow change this? At the same time, this is not the case on my Kindle Voyage; the backlight is always on. Without night mode everything works fine (the backlight does not blink). To be clear, I set up a full display refresh for each page and made 2 videos::

oasis 2 with backlight blinking
https://github.com/koreader/koreader/assets/38221932/64dd4d16-4fc2-40c0-9c0b-a796ad441428

voyage without blinking
https://github.com/koreader/koreader/assets/38221932/1e801c4b-1995-4ffa-8d36-82fc521149cd

The settings and version of the koreader are identical.

#### Steps to reproduce
1. turn on night mode
2. scroll 6 pages until the display is completely updated
3. done

**Comment by egodamager** [comment]
I decided to change the full page refresh interval to every 60 pages. Surprisingly, on Oasis 2, even after 60 pages, I don’t see any garbage from the previous pages, it immediately dissolves. Perhaps this will work for more pages. In Voyage, garbage from previous pages is visible after 2 pages. Now the fact that the backlight on the oasis turns off when the page is refreshed is an advantage, since there is no bright glow in the eyes of the white canvas, and blinking once every 60 pages is not so critical

**Comment by NiLuJe** [comment]
FWIW, it's a kernel feature exclusive to (some?) modern Kindles, aimed at lessening the impact of the flash + backlight combo in nightmode, since the usual black flash now becomes white, which can be blinding.

IIRC, it's unclear to me whether we actually have any way to control it (my own interpretation of it was a no, so much so that I was under the impression that this wasn't actually implemented on production devices).

So, if for nothing else than proving that this behavior did, in fact, hit a production device, thanks ;).

On that note, for science: @mergen3107 does the Scribe still do that? (I... don't think the PW5 does?).

**Comment by mergen3107** [comment]
@NiLuJe 
Err, I found out stuff, don't know if it's for good or not. Here is the story:
1) Currently I don't use nightmode and refresh rate is set to None - Scribe's screen seems to be artifact free enough for me even after 100-120 pages of reading in one session.
2) I enabled Night mode and screen refresh - to find out that screen refresh every page or 6 pages (the only ones I tried) doesn't work :D nor does work chapter boundary refresh. Only manual screen refresh via diagonal swipe and menu refreshes work (when "Avoid mandatory flashes in menu" is turned off - but typically I have it on). 
3) Nightmode has no effect on screen refreshes. 
4) Manual refresh doesn't trigger backlight on/off. I don't think I never noticed this behavior anywhere on this Kindle. 

It doesn't bother me at all, but I can provide verbose logs later if you need them (on mobile now).

**Comment by egodamager** [comment]
@NiLuJe, you are absolutely right. I checked this in a standard reader - exactly the same behavior with the backlight flickering.

I can also confirm that PW4 also flickers. It looks like this behavior started with either the 8th or 9th generation

**Comment by NiLuJe** [comment]
@mergen3107: IIRC, the screen refresh rate setting is different whether you're in nightmode or not (and I don't recall how obvious that is in the UI). That could explain some of the inconsistencies ;).

**Comment by mergen3107** [comment]
The thing is, refresh interval doesn't work in non-nightmode too! :D only manual refresh and UI refresh work, but this has never bothered me - maybe that's why I didn't know it doesn't work. 

Don't have access to PC yet, will create a new ticket later - maybe worth considering. Although it is unrelated to this ticket, sorry I couldn't help

**Comment by mergen3107** [comment]
Alright I found the culprit. Screen refreshes don't work when page turn animations are enabled - my mistake was testing it only in a fb2 book. 

With page turn animations disabled, I tried the nightmode again - Scribe does **not** turn off backlight during page refreshes.
