### ISSUE TITLE
Unable to refresh metadata information (tags) from Calibre.

### ISSUE THREAD

**Issue by tarkeez** [koreader/koreader#11573]
* KOReader version: 2024.03.1
* Device: Onyx Boox Page (Android)

#### Issue
If I update some metadata for a given book in Calibre (tags, title, etc.) and connect the device and select update cached metadata on device from the device menu in Calibre, the metadata doesn't get updated in koreader. I have to delete the book from the device and re-send it for the updated values to show.

#### Steps to reproduce
Send a book to device from Calibre.
Update some metadata field in Calibre
Select update cached metadata on device
Select the book or folder in koreader and select Refresh cached book information
The update metadata (visible in Calibre) is not updated in koreader

**edit** This is a problem for me because I use Calibre to organize books into collections, and use the collection tags to find books to read in koreader (all my books are files in a single flat folder). I actually use a custom column in Calibre (not tags) and edited the Calibre metadata search plugin to browse that custom column, but the point in the same -- the metadata doesn't seem to update without deleting and resending the book.

**Comment by pazos** [comment]
I'm afraid you'll need to ask calibre dev or contributors about how the specific function works. Here nobody knows :)

I'm not implying there's a bug there but I don't know if there's anything to fix in our implementation :p

For instance, if you "connect to calibre" using an usb cable via MTP calibre device then the issue isn't ours, since there calibre is the one that updates metadata json files on device. We just read metadata from there.

If you "connect to calibre" using wireless **and** you cannot reproduce the same issue using  usb/mtp then the issue happens on our implementation but I'm still not sure where. Maybe it is even worse than that and the smart device app/server - part of calibre, doesn't inform about metadata changes unless they're sending books or uses another function that we ignore.

So, please:

1. try to reproduce in both wireless and wired transfers.
2a. if it happens on both methods ask for help in calibre forums and link to this ticket
2b. if it happens only on wireless transfers ask for help in calibre forums and link to this ticket

**Comment by tarkeez** [comment]
Thanks for your reply.

So you are right and I should have searched before posting. Calibre's update metadata function doesn't work like I thought. I guess on first transfer, koreader reads the embedded metadata and stores it in cache, but any subsequent changes to a book in Calibre doesn't get updated because that is only reflected in the metadata.calibre file which is not where ereaders get the book metadata. You have to delete and re-transfer. 

So I guess the trick here is to get the metadata right on the first go, he he.

As for the koreader calibre plugin, it does update the metadata because I guess it reads from the metadata.calibre file, so at least it's possible to browse what I need.

Closing this as it is not koreader related then, thanks.
