### ISSUE TITLE
No tags under "calibre metadata search"

### ISSUE THREAD

**Issue by 7hir7een** [koreader/koreader#11611]
* KOReader version: v2024.03.01
* Device: Kobo Libra 2

#### Issue
When I go to _Calibre metadata search_ then select _Browse tags_, there are no tags populating.

I have tried reinstalling koreader from scratch (just copying over my dictionaries to the new install), and the issue persists.

My home folder for koreader is /mnt/onboard/Books.  I use this same folder setup for my mother's Kobo, and hers will populate tags.  Her Calibre library is a smaller subset of mine, but lives on the same MacBook.

I have no idea how to begin troubleshooting this, other than the fresh install of koreader that I already tried.

Any help is greatly appreciated!

**Comment by jonstump** [comment]
Here to add that I experienced something similar. I'm unsure if this is what you experience @7hir7een, a new issue, or a limitation of OPDS.

I recently installed Koreader on my Kindle Voyage. I tried connecting to calibre two different ways. One through the Calibre plugin and the other adding Calibre as an OPDS source. I noticed the same issue if I downloaded my books via my Calibre library using OPDS. If I connected to Calibre wirelessly via the plugin and sent the books from Calibre to the device it worked properly. So I've exclusively transferred books that way so far.

I figured I would mention this because I basically experienced what you mentioned on the same device and was able to troubleshoot it to how I was transferring my books. Hope this helps
