### ISSUE TITLE
Bug: Corrupted path names when using Calibre Wireless Device.

### ISSUE THREAD

**Issue by KridOCaign** [koreader/koreader#11629]
* KOReader version:2024.03.1
* Device: Onyx Page 2

#### Issue
When connected to Calibre via a wireless connection, and having Calibre create subfolders for books, KOReader will send some books to folders with corrupted names, while others are sent to the correct places.

#### Steps to reproduce
Calibre save template:
{#collection}/{authors}/{title} - {authors} ({id})
One collection is named "Classical Lit"
Upon sending 7 books in the "Classical Lit" collection to KOReader, 6 went into the "Classic Lit" folder, and one went to a folder named "ClaLit"

**Comment by pazos** [comment]
I'm not sure if this is a bug here. We just receive a `lpath` that's generated on the server (calibre) based on the save template.

If the files are received correctly (ie: nor corrupted nor empty) we did our work properly.

Please review your collection's names and make sure you didn't make a mistake on your end.

I wouldn't mind to have a test case (a zipped calibre library with as few books as possible that's used to reproduce your issue) in case you double checked this isn't caused by some calibre configuration / settings you did.

**Comment by pazos** [comment]
No response, closing
