### ISSUE TITLE
fb2 image centering doesn't work anymore

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11623]
* KOReader version: v2023.03.1-39
* Device: Kindle Scribe

#### Issue
Image centering doesn't work anymore in fb2 books.
I noticed this in my book that started reading on v2023.03.1 - where all images are centered OK even without my tweaks.
But on -39 all images are aligned to the left.

In another fb2 book, I did it by hand:
```
image + p {
    text-align: center !important;
    font-size: 0.8rem
}
```
but in -39 it doesn't work.

Maybe it was broken recently, not necessarily in -39, during the fb2 style tweaks overhaul? @poire-z ?

I am on mobile now, but I can provide the book and logs later.

I hope it is easily reproducible. 

Thanks!

**Comment by poire-z** [comment]
It's possible stuff changed because of https://github.com/koreader/crengine/pull/555.
But your "solution" tweak looks a bit odd:
`image + p {` would apply to the P, not to the IMAGE.
Also, `text-align: center` may work with inline image(s) in a paragraph, but not on block image. Maybe the newly added `text-align: -cr-html-align-center` would work better?

I'd need some sample book to see the tags.

**Comment by mergen3107** [comment]
Thank you!

Here are the two books:
[Библиотека приключений №2 - 17 - Аркадий и Борис Стругацкие, Анатолий Днепров - Страна Багровых Туч. Глиняный Бог.fb2.zip](https://github.com/koreader/koreader/files/14886495/2.-.17.-.-.fb2.zip)
This one has `<image l:href="..."/>` for images.

[Борис Акунин - Алмазная Колесница.fb2.zip](https://github.com/koreader/koreader/files/14886496/-.fb2.zip)

Sorry for the confusion, I copied the wrong tweak.
For all books, I use the following style tweak applied by default:
```
img {
    text-align: center;
    display: block;
}
```
This worked OK for both books on v2023.03.1.

Then, for the second book, I also did:
```
image + p {
    text-align: center !important;
    font-size: 0.8rem
}
title + image + p {
    text-align: justify !important;
    font-size: 1.0rem
}

```
Images in this book have image titles as `p`, so I need to find image's immediate sibling `p` and make it centered. Then, I have to find the next `p` which is from the regular text and make it justified again :D

**Comment by mergen3107** [comment]
> Maybe the newly added `text-align: -cr-html-align-center` would work better?

This didn't work for `img` or `image`.

**Comment by poire-z** [comment]
So, it's indeed caused by https://github.com/koreader/crengine/commit/1544bcfbf63ec32fe415aacbc1090c56a0a52903.

The code to render images is a bit odd, and I have not changed it: a block image is its own container, and previously, it was taking the full width, so if I add `image { border: 1px solid blue; }` we used to have:
![image](https://github.com/koreader/koreader/assets/24273478/201a0815-cad2-4bce-a1c3-07dd600d10d8)
The border box takes the full width, and the image itself is centered in its container because of `text-align:center` (but that's not really the proper way to center block images, `margin-left/right: auto` is) in https://github.com/koreader/crengine/blob/55429c37868322408df15cfb0d26bc839b90cccf/cr3gui/data/fb2.css#L13
All looked good, because FB2 image don't get borders.

Now, with this fix, we resize the container to the width of the image, so:
![image](https://github.com/koreader/koreader/assets/24273478/bcc783eb-bfca-4a26-b3a2-cd76f02ede65)
and `text-align:center` has nothing to center because the image fits in its container.

If you all (@dmalinovsky @hius07) expect such block images (those not reset to inline when inside a P or LI: https://github.com/koreader/crengine/blob/55429c37868322408df15cfb0d26bc839b90cccf/cr3gui/data/fb2.css#L13-L15 ) to be centered (**but then, why did you need such styletweaks?!**), I think this can be achieved with:
```diff
--- a/cr3gui/data/fb2.css
+++ b/cr3gui/data/fb2.css
@@ -11,5 +11,5 @@

-image { text-align: center; text-indent: 0; display: block }
+image { text-align: center; text-indent: 0; display: block; margin: 0 auto; }
 p image { display: inline }
 li image { display: inline }
```
![image](https://github.com/koreader/koreader/assets/24273478/defeb3cc-f84b-47f6-ae3e-c6673fb5294a)

Can you (and @dmalinovsky) test this change and tell if all is good with it, and if you still need other tweaks?
(It looks like images are centered too in your 2nd bigger FB2 book.)

**Comment by dmalinovsky** [comment]
@poire-z, I've tested with the following style (without ineffective `text-align`):

```css
image { text-indent: 0; display: block; margin: 0 auto; }
```

And the images are centered now, thanks.

**Comment by mergen3107** [comment]
@poire-z 
Thank you so much!
It works great in both books :D 
I'll leave it as a global styletweak for now

**Comment by mergen3107** [comment]
> (without ineffective `text-align`)

I confirm that this is not making any difference in both books

**Comment by mergen3107** [comment]
Thank you very much @poire-z !
