### ISSUE TITLE
Respect Booxs physical key full refresh?

### ISSUE THREAD

**Issue by Chloewubooks** [koreader/koreader#11638]
I am wondering is there a way to respect the system's physical key function/shortcut(full refresh in this case) in Koreader ? or is there a way to set the gesture to be able to manually do the full refresh quickly?
I understand there are options to set custom page count/chapter for full refresh, but it'd be better to be able to allow manual full refresh since it's probably the most used(and difficult to predict when would need a full refresh) function for a e-ink reader. 
Thank you.

**Comment by pazos** [comment]
> I am wondering is there a way to respect the system's physical key function/shortcut(full refresh in this case) in Koreader 

If it is an standard android event, forwarded to apps, you should be able to catch it in (verbose) logs and remap it whichever action you like following https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-keys

If the button does something that the system itself consumes without forwarding it to apps then it isn't possible to assign any behaviour.

I'll bet the second option applies here and the only reason the button doesn't do its job while KOReader is on the foreground is because we use custom epd routines. But nobody knows without testing it :)

**Comment by pazos** [comment]
BTW, a short diagonal swipe does the same job on supported devices  :)

See https://koreader.rocks/user_guide/#predefinedgestures
