### ISSUE TITLE
Hard-coded `NotoSansArabicUI` not available upstream https://notofonts.github.io/

### ISSUE THREAD

**Issue by eNV25** [koreader/koreader#11657]
* KOReader version: v2024.03.1
* Device: Linux Desktop Arch Linux

#### Issue

The `NotoSansArabicUI` font is not available upstream any more. It only seems to be available on Debian. The `NotoNaskhArabicUI` is available, though.

https://notofonts.github.io/

Errors after deleting `/usr/lib/koreader/fonts/noto/NotoSansArabicUI-*`:

```
04/10/24-18:21:15 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:39: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
04/10/24-18:21:15 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:39: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
04/10/24-18:21:15 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:39: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
04/10/24-18:21:15 INFO  Loading plugins from directory: plugins
04/10/24-18:21:15 INFO  Loading plugins from directory: /home/x/.config/koreader/plugins/
04/10/24-18:21:15 ERROR #! Font  NotoSansArabicUI-Bold.ttf  ( NotoSansArabicUI-Bold.ttf ) not supported:  ./ffi/freetype.lua:39: Failed to load font './fonts/NotoSansArabicUI-Bold.ttf', freetype error code: 1
04/10/24-18:21:15 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:39: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
04/10/24-18:21:15 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:39: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
04/10/24-18:21:15 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:39: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
04/10/24-18:21:15 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:39: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
04/10/24-18:21:15 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:39: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
```

**Comment by eNV25** [comment]
I previously mentioned it here: https://github.com/koreader/koreader/issues/10925#issuecomment-2047176556

**Comment by eNV25** [comment]
Actually, no. I'm talking about the use of a deprecated font in the koreader Debian package. It prevents koreader from being packaged properly on Arch Linux.

**Comment by pazos** [comment]
I have no problems to answer to the actual maintainer of the aur package and address its concens.

Fonts are part of the software we release. On the deb package some fonts are removed or slightly changed since they're already on the system or they're cheap to get as package deps.

If the aur package maintainer wants to do the same it is free to do so. See my previous post, forward it to the maintainer and let us receive some feedback from the actual people that has being maintaining this package for a few years without much problems.

**Comment by eNV25** [comment]
My solution is to get the deprecated `NotoSansArabicUI` fonts from Debian Salsa, since they're not available anywhere else.

**Comment by pazos** [comment]
I understand.

Again: contact the aur package maintainer or deploy your own.

In any case your issues will fade away if you repack arch blobs from binaries within a tar.gz and not from debian blobs. That's why I linked https://github.com/koreader/koreader/pull/9351 in the first place.

The reason I'm not in a hurry for commiting those changes here is because the aur package seems to be well maintained, `rpm` based distros have `alien` to convert from deb and debian packages are covered here, upstream.

Here, upstream, there's no plan to add support for any linux distro other than debian or for any package management system other than appimage.

So please reread all my coments here and contact the maintainer of the package you're trying to improve.

**Comment by pazos** [comment]
Umm, I see your comment in https://aur.archlinux.org/packages/koreader-bin. That's a pile of hacks :)

I understand it works for you. It might work for others too. From my PoV it makes things messier.
Did you try to contact the maintainer?

Maybe we can try it here, pinging @zzy-ac (hoping it shares the nick between github and aur :))

Are you willing to change upstream binaries from a deb package to tar.gz?
If so we ship a generic x86_64 linux release with all the assets ASAP.


**devendoring**

Libraries and binaries shouldn't be replaced (maybe with the exception of `tar`?)
Fonts can be replaced without problems if the distro provides better alternatives.

BTW, if you're *you*, thank you for keeping `koreader-bin` always updated. Last two years as a happy user ;)

**Comment by eNV25** [comment]
I'm not the AUR maintainer for `koreader-bin`, but I do maintain other packages on the AUR. By the way, AUR packages are user produced content.

I think it would be great if you distribute a generic tarball. It should be designed to be installed in `/opt`. Symlinks can be then used to add it to `PATH` and install the `.desktop` file and icon to the correct place. Discord has a package like that. e.g.:

```
bsdtar xf kodeader-linux.tar.gz -C /opt/
```

Regarding vendoring, I don't have a problem with that. Some packages in Arch Linux have vendored dependencies. e.g. the chromium package and some electron-based packages.

If koreader were to be added to an actual distro, they would want it to be built from source. But I'm not particularly interested in that.

**Comment by zzy-ac** [comment]
Received, currently there is no time. If you need it, please leave your aur name and I will help you add a co maintainer.

**Comment by zzy-ac** [comment]
Received, currently there is no time. If you need it, please leave your aur name and I will help you add a co maintainer.

**Comment by eNV25** [comment]
Creating a generic tarball should be as simple as using the files from your AppImage. `koreader.AppImage --appimage-extract`. Maybe I should do that for my personal package in the meantime.

**Comment by pazos** [comment]
> I think it would be great if you distribute a generic tarball. It should be designed to be installed in `/opt`. Symlinks can be then used to add it to `PATH` and install the `.desktop` file and icon to the correct place. 

Yay, the specific path is up to you. The package will look like: https://fs.pazos.eu/share/AL4y7e0P

Releasing the package that way makes possible to uncompress it in $HOME/.local for the current user or in /usr for all users.

Of course you're free to install in whatever path you want, just double check it works because the "binary" is just a shell scripts that jumps to assets dir and invokes luajit from there.

> Regarding vendoring, I don't have a problem with that. Some packages in Arch Linux have vendored dependencies. e.g. the chromium package and some electron-based packages.

I think you can save about 10M just by removing fonts that are already available in arch.
For instance in debian we include `noto` as a dep but not `noto-extras` because the later weights 200MB+ and we just use a single CJK font of 15MB

**Comment by pazos** [comment]
@eNV25, @zzy-ac: starting from v2024.07 the best way to build ko packages from binaries is the generic linux tar.xz release.

I would recommend you to move to it, as it removes deps on fonts non available as part of arch repos.
