### ISSUE TITLE
Blank spaces appear between words in some EPUB

### ISSUE THREAD

**Issue by vvyoko** [koreader/koreader#11692]
* KOReader version:2024.03.1
* Device:kindle and android

#### Issue
Left side is Calibre ebook-viewer
Right side is koreader
Disable embedded css in koreader cant fix(not css wrong)

![123](https://github.com/koreader/koreader/assets/2145741/3c58a540-cf07-4468-88d6-e7e9cc1a7bc3)

#### Steps to reproduce
Test epub file

[test.zip](https://github.com/koreader/koreader/files/15020075/test.zip)

**Comment by poire-z** [comment]
Indeed:

![image](https://github.com/koreader/koreader/assets/24273478/cbd27c91-6236-4fb0-835d-0b995dcc9e02)

This U+200C is https://en.wikipedia.org/wiki/Zero-width_non-joiner.
Any idea why this would be used there, just after most 个. What does this 个 means ? It is advertized as being a "modifier letter", so some kind of diacritic for CJK ?!

Caused by https://github.com/koreader/crengine/commit/68c58f5eb and U+200C not considered a punctuation or space, so as a western letter (ie. just as `z`, so space added on both sides of this zero-width thingie :/)
And it seems it is explicitely not considered a punctuation or space, as it may indeed be used inside words (like a soft hyphen - but the Wikipedia page says _This is also an effect of a space character_):
https://github.com/koreader/crengine/blob/1a9e79e25a5b4510d7aaff238d5239f2da70d8d0/crengine/src/lvstring.cpp#L5004-L5008
May be we could hardcode rules in the add-space code rules, or consider it a diacritic, and have that code explicitely not add space when it is a standalone diacritic... Not sure yet what's the best way to handle that.
Dunno how common it is used in CJK books, any idea?

With Kerning off, we don't add these spaces:
![image](https://github.com/koreader/koreader/assets/24273478/ee15bc67-80b0-4db3-b8db-7fcf38c5659e)
With Kerning fast, we do:
![image](https://github.com/koreader/koreader/assets/24273478/e0fc5370-17bc-470a-b7ba-7b0b0baa241e)

Strangely, when not using Kerning best, there are these little vertical gray bars instead :/ Looks like some font (and/or one of our fallback fonts?) provide this glyph (not even black). I don't get them when using the Code2000 font (here with Kerning off):
![image](https://github.com/koreader/koreader/assets/24273478/6931a3ca-4ce2-4e9e-bbf2-5c5fa9f9294e)

**Comment by Frenzie** [comment]
> Looks like some font (and/or one of our fallback fonts?) provide this glyph (not even black).

That sounds like a font issue. Very strange. O.o
