### ISSUE TITLE
FR: Thai language word break doesn't work

### ISSUE THREAD

**Issue by inganault** [koreader/koreader#11701]
## Problem
KOReader use [libunibreak](https://github.com/adah1972/libunibreak) find location to break lines.
However, it doesn't support breaking SEA languages: Thai, Burmese, Lao, Khmer outlined in [UAX14](https://www.unicode.org/reports/tr14/).

These languages don't have space to easily detect word boundary location so it need some kind of NLP algorithm which is not simple to implement.

```
text = "ประเทศไทยรวมเลือดเนื้อชาติเชื้อไทย เป็นประชารัฐไผทของไทยทุกส่วน"

Expected
|ประเทศไทยรวมเลือดเนื้อชาติเชื้อไทย เป็น |
|ประชารัฐไผทของไทยทุกส่วน           |

KOReader / libunibreak
|ประเทศไทยรวมเลือดเนื้อชาติเชื้อไทย     |
|เป็นประชารัฐไผทของไทยทุกส่วน        |
```

## Existing Solution
Chrome and Firefox use break iterator from [ICU](https://github.com/unicode-org/icu) which is a LSTM neural network, in past they have used [libthai](https://github.com/tlwg/libthai).

Most line breaking libraries I found are either use ICU or don't bother breaking SEA languages.

### 1. Use ICU4C instead of libunibreak
It probably bloat the koreader program size by a few MBs and make building harder. I'm not sure if there is a reason why koreader don't use ICU in the first place.

### 2. Use libthai for Thai sentence
libthai is probably easier to build and include in the executable, but it look like a hack rather than a clean solution and it won't support Burmese, Lao and Khmer.

### 3. Don't fix
Use an external tool or make a plugin to insert `&#x200b;` ZERO WIDTH SPACE between word in epub files, but this will make searching unusable.

### 4. Fix libunibreak
Implement a neural network runtime in C in libunibreak, a very big task.

---
If solution (1) or (2) is acceptable, I will try to implement it.

**Comment by poire-z** [comment]
(SEA = South East Asia)

> 1. Use ICU4C instead of libunibreak
>  I'm not sure if there is a reason why koreader don't use ICU in the first place.

The reason was that crengine (our EPUB engine) did not use any other library and used to characterize chars and break lines by itself with some simple logic.
We later needed to do better (and get rid of that ugly and hard to maintain logic), so we choose libunibreak because it was simple and small, and does the job - and is quite tweakable (some stuff in https://github.com/koreader/crengine/blob/master/crengine/src/textlang.cpp).

I can see mentions of ICU in various other unrelated issues (ie. requests for support for Wikipedia ZIM files and libraries depending of  ICU) and some fellow maintainers not wanting to ship this monster).
On my side (having implemented most stuff related to libunibreak), I also don't want to change it and get into learning another library, that may not be that flexible or fast.

Technically, we use it for EPUB (https://github.com/koreader/crengine/blob/1a9e79e25a5b4510d7aaff238d5239f2da70d8d0/crengine/src/lvtextfm.cpp#L1495) but also for KOReader's UI (https://github.com/koreader/koreader-base/blob/865bed4c2f91c9808520fab24046685c409d8607/xtext.cpp#L741), ie. for showing Wikipedia lookup results, which I guess is also crap with Thai.
It is nice because it allows us to flag chars for linebreak AND do a lot of other stuff in a single pass/iteration of the chars. I don't know about ICU, but if it would not allow us to do that, and would require to be fed the whole text independantly, and need more datastructures, it would require lots of changes there, probably be slower, and would be a no-go.

> 2. Use libthai for Thai sentence
> but it look like a hack rather than a clean solution and it won't support Burmese, Lao and Khmer.

Indeed, we don't want to ship and build (and code very specific stuff) with other stuff that will be useful to 0.1% of our users.

> 3. Don't fix
Use an external tool or make a plugin

Probably only with some external tool. And you could insert `<wbr>` instead of ZERO WIDTH SPACE. But our current searching code would still fail as it searches only in individual text nodes (it's on my todo list to fix that, and get search to match on text spanning multiple text nodes).
But not with a plugin or at the XML parsing phase: this is even more a hack.

> 4. Fix libunibreak
Implement a neural network runtime in C in libunibreak, a very big task.

You don't need to hack libunibreak: let it do its simple stuff its simple way.
But we could have hooks/tweaks in OUR code (both crengine and xtext.cpp) around where we interact with libunibreak, to do more stuff when the text language code is one of the SEA ones, or when we detect Unicode chars from their scripts.
I don't have much time these weeks to give it more thoughts, but some quick ones:

libunibreak (or our code) can probably detect sequence of chars of SEA by their category "SA".
https://www.unicode.org/reports/tr14/#SA
When meeting and leaving a sequence of such SA - and only in that case - may be give that sequence of chars (existing buffer + char start/end index) to some other hook, that would itself do the extra work (so, only when needed) and insert break points in that past sequence.
This hook would be dedicated code in some other C file (or module), or could even be plugged in from our Lua frontend, and implemented in Lua - and there it could be a plugin, and dictionaries could be downloaded when needed.

We could even steal logic or code from ICU. I don't know how complex it is, and if it's really neural network mumbo jumbo - we don't want anything really complex and hungry.
https://unicode-org.github.io/icu/userguide/boundaryanalysis/#dictionary-based-breakiterator
There are some text files at https://searchfox.org/mozilla-release/source/intl/icu/source/data/brkitr
(with thai stuff in the subdirectories dictionaries/ and lstm/) that may be we could re-use.
It shouldn't be more intrusive than what we have for hyphenation (https://github.com/koreader/crengine/blob/master/crengine/src/hyphman.cpp, a single C module with the logic there, parsing dictionaries text files when needed only) - and this service could be used from frontend for our UI text.

lstm: https://www.google.com/search?hl=en&num=25&q=lstm :/ Dunno how huge and stealable the involved code in ICU is.
May be there are less perfect but simpler solutions that could do good enough?

> 3. Don't fix

That is still my preferred option :) How do other EPUB reading softwares (ie. on Android) do? I guess lots of them doing it well use some Web rendering engine like chrome/webkit, and have it work well.
If SEA users have alternative solutions, and KOReader doesn't work for them, well, be it. I don't really want to have our stuff more bloated/fragile (and the involved code paths later being never really tested with SEAR when tweaked) for these "niche" users (ok, even if you are millions :)).

**Comment by Frenzie** [comment]
> That is still my preferred option :) How do other EPUB reading softwares (ie. on Android) do? I guess lots of them doing it well use some Web rendering engine like chrome/webkit, and have it work well.

They depend on ICU, although I'm not even sure if they use it for line breaking specifically. It's used for [a lot more](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl).

It's one of the largest things even in those engines:

https://docs.google.com/document/d/1aC64nJZ4nKeah-KwsGuAAf2vDApYhkPPhdz2km3zlrg/edit#heading=h.nlqy1c1murmy

![image](https://github.com/koreader/koreader/assets/202757/314bfb55-dd0e-4a14-b1c1-5cad754785f3)

https://firefox-source-docs.mozilla.org/intl/icu.html

**Comment by inganault** [comment]
> And you could insert <wbr> instead of ZERO WIDTH SPACE.

Only ZERO WIDTH SPACE is working for me, `<wbr>` don't. I haven't look into the code but I believe it is treating `<wbr>` like `<span></span>` which don't break text.

I don't think there are anyone using `<wbr>` enough to notice this issue.

> When meeting and leaving a sequence of such SA - and only in that case - may be give that sequence of chars (existing buffer + char start/end index) to some other hook, that would itself do the extra work (so, only when needed) and flag break points in that past sequence.

This might be the only way to add SA line breaking to current codebase without rewriting the text layout code.
The nature of these languages won't allow single pass because they are context dependent.

> We could even steal logic or code from ICU.

The ICU breakiterator can be used 2 mode, lstm and dictionary.

Dictionary mode have larger data and faster processing. However, using only the dictionary don't work well enough, it needs some preprocessing and rule-based hacks when dictionary don't work (which ICU don't have). If you combine all these, the result is libthai.

LSTM mode is the default mode, it breaks lines a lot better than dictionary. It have 2 implementation, ICU4C and [ICU4X](https://github.com/unicode-org/icu4x/tree/cb7e9151356373baac7ebb5f80d3d5c4436b57e0/components/segmenter).

ICU4X is more modern and modular. I tried building only icu_segmenter it resulted in 0.7MB working executable. The main problem is that ICU4X builds with Rust...
And, ICU4C has too much bloat for KOReader.

---

My conclusion is to
- Extract [LSTMBreakEngine](https://github.com/unicode-org/icu/blob/0e4c2d8bc68bbd46f2b74c0404e0cc26a98251f7/icu4c/source/common/lstmbe.cpp) from ICU4C.
- Get compiled ICU data needed from somewhere, it should be around 0.5MB.
- Patch crengine/src/lvtextfm.cpp to use lstm when it encountered SA text chunks.

Meanwhile, [my external tool](https://github.com/inganault/epub-thai-wordbreak) works good enough for reading if anyone is looking for it.

**Comment by poire-z** [comment]
> `<wbr>` don't. I haven't look into the code but I believe it is treating `<wbr>` like `<span></span>` which don't break text.
> 
> I don't think there are anyone using `<wbr>` enough to notice this issue.

On indeed, I don't think I've ever seen or added anything handling that :/ Adding that to my toLookAt list.

> My conclusion is to

Good thinking :) I wouldn't want it any other way :)

> Extract [LSTMBreakEngine](https://github.com/unicode-org/icu/blob/0e4c2d8bc68bbd46f2b74c0404e0cc26a98251f7/icu4c/source/common/lstmbe.cpp) from ICU4C.

Dunno how much stuff this uses from other included files, but if you manage to get something that small and independant/standalone, it would be really fine.
Note that crengine has its own kind of "standard C++ library" (lvtypes, lvref, lvstring, lvarray, lvptrvec, lvhash...), so I hope this code does not uses too many stuff from the outside and that you can somehow translate stuff to what's available in crengine (I had frowned upon PR bringing `std::` stuff in the past). I'd like to keep crengine simple and homogenous, and not a patchwork of many stuff.

**Comment by inganault** [comment]
I managed to extract the engine from ICU with no dependencies https://github.com/inganault/crengine/commit/2149f9a1a79b00086d10d4bfa15809808e482e80 (+300 KB to release zip).

It works, but in my Kobo, it takes 5 minutes to render a volume of Thai novel on the first load, so *I will not merging it*. I saw this coming but didn't expected it to be this bad. For a comparison, all other reader in Kobo (Plato and stock reader) also cannot do this feature.
The performance should be acceptable for Android user with a more modern CPU. I think feature gating this with some checkbox in UI should be okay, if anyone is interested in continuing this issue.

I also looked into supporting `<wbr>`. A easy hack is to turn a el_wbr into ZERO WIDTH SPACE in lvrend.cpp::RenderFinalBlock or add a new flag LTEXT_* for wbr.
However, this don't fix searching without some effort on searching. I don't see its worth unless anyone actually got a book that use `<wbr>`.

Thanks poire-z a lot for extensive guidance and feedbacks.

**Comment by poire-z** [comment]
Thanks for trying :) Your integration looks rather clean. (But not insisting, I guess it would need more work on the build/packaging side).

How big a book was that _volume of Thai novel_  ? Was that like 200 or 2000 pages ?
And how page turning speed was/degraded ? (We rerender each paragraph as you turn to new pages.)

> For a comparison, all other reader in Kobo (Plato and stock reader) also cannot do this feature.

Just curious: what's the alternative then for reading these languages?
I guess the following is just unbearable? Or are you really used to that ? Wouldn't it be better to allow wrap anywhere - or would that be even worse ?
![image](https://github.com/koreader/koreader/assets/24273478/27b45979-22ff-4bd0-a27a-f831cab4e07b)
Also, does that mean Thai still use spaces? Where and why are they allowed, and why not everywhere ? :)

**Comment by inganault** [comment]
The leftover work from my branch would be an interface to disable it from lua side and UI things.
Building + packaging is not a problem because they are only new c++ files and we only need to run the data generation manually each new data version release.
I am happy to finish this if anyone want this feature, but KOReader + Epub + Thai user is probably so rare. It won't worth cluttering your repo if we didn't see anyone going to use it, not even myself.

FYI, the languages that are problematic here are only 20% of Southeast Asia. Other countries use roman-alphabet-derived writing system or Chinese.

> How big a book was that volume of Thai novel ? And how page turning speed was/degraded ?

About 500 A5 pages. Page turn is noticeable but usable in Kobo. A device with good processor will not notice it.

> What's the alternative then for reading these languages?

The de facto file format for sharing a book here is pdf, so no layout problem. Most Thai e-book store have their DRM-locked smartphone app (Android/iOS = webview -> no problem). Epub without DRM is therefore, rare.

> I guess the following is just unbearable? Or are you really used to that ?

I read pdf and English epub in Kobo. This is the first time I try Thai epub. In you picture, `ใน` broken in to `ใ | น` is equivalent to hyphenating `in` into `i- | n`.

> Also, does that mean Thai still use spaces? Where and why are they allowed, and why not everywhere ? :)

Spaces usage in Thai is similar to comma and full-space in English, a little pause when speaking.

**Comment by benoit-pierre** [comment]
Would something like this be relevant: https://github.com/google/budoux ?

**Comment by inganault** [comment]
> Would something like this be relevant: https://github.com/google/budoux ?

Thanks, I haven't seen that.

Their algorithm is faster and easier to implement than ICU, and can also be used for CJK, but the training data for Thai in that repo is quite limited (1000 sentences from internet). I will look into improving it first if I have time.

**Comment by benoit-pierre** [comment]
Note that there's a [Zig version](https://github.com/Cloudef/zig-budoux/) that can be used to generate a C header and static library. That might be of use for a first POC.
