### ISSUE TITLE
Kindle Scribe: Orientation broken if launched after Kindle Reader's Landscape

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11743]
* KOReader version: 2024.03.1-51 with a fix for swipe animations (https://github.com/koreader/koreader-base/pull/1719)
* Device: Kindle Scribe (FW 5.16.2)

#### Issue
I found a critical bug when I launched KOReader after rotating the Kindle Reader's layout to landscape, but only under certain conditions.

#### Steps to reproduce
1) Exit KOReader while it is in a landscape (orientation code `1`) fb2 book with two columns.
2) Launch any Kindle book.
3) Rotate it to Landscape. It rotates so that the wide bezel is now on the top. I believe this is orientation code `3`, if Portrait is `0` (when the wide bezel is on the left).
4) (!) Important step to reproduce this bug. Rotate Kindle physically to the other landscape orientation (`1` in this reference). Stay in this orientation with wide bezel on bottom.
5) Exit Kindle Reader - it will be in Portrait orientation.
6) Launch KOReader.
7) Upon launch, the text is rotated in Portrait orientation (`0`), although I exited when it was in landscape orientation (`1`). Text is still in two columns.
Most importantly, touch is not aligned with the UI anymore but in a very weird state:
-- Physical bottom (we are still with wide bezel on bottom) is the "UI" bottom. For example, I can toggle the progress bar.
-- The rest of the sensor area looks like it is in a rectangular shape, but the UI's rectangle and the sensor rectangle are 90 degrees apart :D 
What I mean by this:
-- About 60% of the width is useful for the sensor. Of that, tapping on 25% of width does page back, swiping the other 75% of width does page forward.
-- I cannot reach the sensor area to summon the top menu at all - it must outside the physical bezel.

I just have to exit KOReader via gesture, and then rotate Kindle Reader back to Portrait. I tried going to the other Landscape, but the sensor layer is again rotated, but aligned differently.

I am pretty sure I need to look at the orientation code in the Kindle init for the Scribe.
Meanwhile, this is is just a mere report :D 

Thanks! 

##### `crash.log`
[crash1.txt](https://github.com/koreader/koreader/files/15204329/crash1.txt)

**Comment by ZhaoMJ** [comment]
I'm still experiencing a similar issue - after launching Koreader in the upside-down (code 2) or counter-clockwise position (code 4), the touch seems to be in the correct orientation but the display is entirely flipped (i.e. as if placed in the upright or clockwise orientation respectively.) 
I'm using 2024.07 on Kindle Scribe FW 5.16.6.1, and I don't recall this happening with 2024.04 on FW 5.16.2.1, so it might be either a regression due to your fix or a side effect of the newer FW. 
I don't want to downgrade to test this out though, because the hard floats really give a significant performance boost, at least very noticeable for the built-in Print Replica viewer.

BTW, I wonder why there's still no official build for KindleHF?

**Comment by mergen3107** [comment]
Sorry, I only tested it on 5.16.2

**Comment by mergen3107** [comment]
@ZhaoMJ 
In crash.log, when KOReader starts there line about orientation. Can you show them here?

I suspect lipc commands changed

**Comment by ZhaoMJ** [comment]
@mergen3107 it shows `orientation_code = D`. Here's the full log with verbose logging enabled.
[crash.log](https://github.com/user-attachments/files/16258210/crash.log)

**Comment by mergen3107** [comment]
@ZhaoMJ 
That’s interesting, thanks!
So it seems lipc works OK.

I haven’t upgraded to hf FW yet, so in mean time please use portrait orientations.
