### ISSUE TITLE
FR: Book Metadata Improvements (Embedded Metadata Search, Book Covers in File Search, Google Books API Integration)

### ISSUE THREAD

**Issue by Bluemoondragon07** [koreader/koreader#11943]
I have some ideas for improving metadata features:

1. Option to browse by tags, author, etc. for embedded metadata, too—not just calibre metadata. The current `also search in book metadata` kind of does this, but does not allow "browsing" in the same way calibre metadata search does.
2. Book covers/thumbnails in file search/calibre search.
3. Ability to select books in file search/calibre search modal. This would be useful for bulk adding books to collections.
4. Ability to bulk edit custom metadata in the regular file browser. As of now, books need to be edited for custom tags or series one by one. It would be useful to select multiple books and edit their fields at the same time. However, this might require a separate function for 'adding' metadata versus 'overwriting' metadata for the selected books. For example, adding a keyword would simply append the text to the existing keywords, preceded by a "|" if not empty already.
5. Consider adding keywords as a field that can show up in the file browser "detailed list"
6. Consider using [Google Books api](https://developers.google.com/books/docs/overview) to find book description/metadata online. Maybe even update local books with new metadata, but that might be too complicated and is even a feature apps like calibre are used for. 

These changes would improve the app for those who categorize their books using metadata. None of these are urgent or essential features or anything like that, but just ideas that I think would be very useful if implemented.

**Comment by offset-torque** [comment]
**I am asking out of curiousity because I really can't wrap my mind around this:**

Why would a user want to do all this library management stuff on a slow device with a slow monochrome screen, considering that they also have to synchronize these books back to their "main library" on their computer after editing.

**Calibre** is available on every platform and works on even 15 year old computers. If someone tells me I have to edit lots of books, I will take that ancient computer without hesitation over my new Kobo because it has a bigger color screen user interface and a real keyboard.

**Comment by pazos** [comment]
> I have some ideas for improving metadata features.

Tickets with "some ideas" are difficult to track because some ideas might get rejected, other are out scope. 

1. Is not possible ATM
2. Long press on a entry will show you metadata, including cover.
3. Is not possible ATM
4-6 Out of scope.

Please consider keeping track or participating in #8472.
