### ISSUE TITLE
Keyboard in FM starts with special characters

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#11990]
* KOReader version: v2024.04.134-g8977e5e12_2024-06-01 (and earlier)
* Device: PocketBook Era

#### Issue
When tapping the bottom line in the File Manager (the one saying `<< < page N of M > >>`), a pop-up shows, and the keyboard pops up.  This keyboard has the special characters button (bottom left) activated, which is only rarely useful.  Almost always, I want to type a few letters to `Go to letter`.  The other main option is `Go to page`, but page numbers are visible on the standard page too.

#### Steps to reproduce
1. If necessary, tap the file cabinet icon to get into the file manager
2. Tap the bottom line of a folder taking more than a single page
3. Behold the keyboard

**Comment by hius07** [comment]
Yes, this should be fixed.

Technically it was erroneously done (maybe by me) because of inconsistency in the default input type in InputText:
https://github.com/koreader/koreader/blob/81d2db150f24118f3dfb31510c7568b6a80f2f72/frontend/ui/widget/inputtext.lua#L27
and in InputContainer `onInput`:
https://github.com/koreader/koreader/blob/81d2db150f24118f3dfb31510c7568b6a80f2f72/frontend/ui/widget/container/inputcontainer.lua#L368
