### ISSUE TITLE
Arabic keyboard ث letter is doubled, ظ is missing

### ISSUE THREAD

**Issue by hasan7105** [koreader/koreader#12005]
Hi everyone, the arabic keyboard have the letter ث doubled,  while don't have the ظ letter ,I slove this by gonig to the keyboard folder and edit it the Arabic keyboard file , but when I update the koreader its return to the same problem doubled ث  letter , so can any one help whith this problem thanks.
![image](https://github.com/koreader/koreader/assets/96575780/de6b21f9-b3ae-4e6a-8d04-379207aaae16)

**Comment by benoit-pierre** [comment]
Which file do you modify?

**Comment by benoit-pierre** [comment]
You should be able to make a PR with through the github interface: https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository.

**Comment by poire-z** [comment]
> Hi everyone, the arabic keyboard have the letter ث doubled, while don't have the ظ letter 

Pinging the Arabic keyboard author @WaseemAlkurdi (and the other Arabic reader I remember @zeyadas because of his [famous line](https://github.com/koreader/koreader/issues/6938#issuecomment-737326995)).
Is it on purpose, or an oversight ? Is ظ really missing ?

> but when I update the koreader its return to the same problem 

Yep, if it is an error, best to fix it here on github in the project as suggested, so it is fixed for everybody - and you when you update KOReader :)

**Comment by Zeyadas** [comment]
I'm late here, and by the way it's another Arabian tradition to be late.
Yes, the letter ظ was missing and the letter ث was duplicated.
And it's fixed. 😁
