### ISSUE TITLE
FR: Page Browser - long-press to set this page as book cover

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12117]
**Does your feature request involve difficulty completing a task? Please describe.**
@poire-z 
Is it possible to re-use generated page thumbnail from Page Browser to be used as book cover?

**Describe the solution you'd like**
Open Page Browser
Long-press any page
Popup-menu - set as book cover

I think the size of the page browser thumbnails (3x3 grid on Kindle Scribe, for example) should be OK quality/size for book covers in FM and History.

**Describe alternatives you've considered**
Take a screenshot.
Open Book Information
Edit cover and find this screenshot.
Works, but mega tedious :D

**Additional context**
I have multiple science articles that have poor first page, but OK title page at page 2.
For now, I just ignore covers in History.

Thanks!

**Comment by hius07** [comment]
Screenshot dialog has a button "Set as book cover".

**Comment by poire-z** [comment]
Not fond of having "Set as wallpaper" stuff among usual thingies - it is too Windows-like, I have seen it everywhere for the last 20 years, and never used it once. So, not in KOReader on my watch :)

Also, in PageBrowser, long-press has no popup menu (unless hidden stuff is enabled), so you would transform a "long-press to bookmark" practical default into a popup menu just to get this. For something you may use only once per book.

In any case, the least intrusive solution would be, in the Sleep screen submenu which was reworked recently, to have a new item "Use current page as sleep screen". Writing this, I think we have discussed this (because I remember that the wording I just used is ambiguous, and could mean 1) use _this page that you see now_ as a wallpaper" or 2) always use the _last/currently reading page_ as wallpaper. So, it feels this feature may already exist ?! @Commodore64user: does it?

**Comment by mergen3107** [comment]
> Screenshot dialog has a button "Set as book cover".
I seriously need to learn how to read :D 
Thanks!

**Comment by mergen3107** [comment]
> "long-press to bookmark" practical default 

Again, I probably need to go to an optometrist xD 
I did long press and the page refreshed. I thought, maybe it is just a refresh and long pressed again.
So I didn't see the bookmark sign on the page...

**Comment by mergen3107** [comment]
Thank you @hius07 @poire-z
Closing this as not planned for other people to know.

**Comment by Commodore64user** [comment]
@poire-z 

> "Use current page as sleep screen".

This does not exist, no. I think you are confusing it with the discussion we had about the "hide book cover for current [spicy] book"
