### ISSUE TITLE
Tags in popup fotnote

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#12144]
@poire-z could you look at it:

![1](https://github.com/koreader/koreader/assets/62179190/0715d087-8ce3-44ff-b3f3-1df2c84ebbd4)

![2](https://github.com/koreader/koreader/assets/62179190/675ae64c-0721-42fb-855b-5fcd2b203b5f)

![3](https://github.com/koreader/koreader/assets/62179190/87365423-e6e0-4e85-9181-6b235dcf1e52)

**Comment by poire-z** [comment]
I think it's a change of behaviour in MuPDF since the latest update.

We get and feed MuPDF with:
![image](https://github.com/koreader/koreader/assets/24273478/48d2722d-7f60-4894-a91d-60cd49fcf4e1)
and it renders it as you did show it:
![image](https://github.com/koreader/koreader/assets/24273478/3d1f9815-549a-4940-9a69-19a02df1e4cb)

I think MuPDF tries to render the content of a HTML `<title>` as-is, that is: not expecting any tag in it, so rendering `<` and `>` as-is.

If we rename everywhere `title` to `ztitle`:
```diff
--- a/frontend/apps/reader/modules/readerlink.lua
+++ b/frontend/apps/reader/modules/readerlink.lua
@@ -1447,9 +1447,12 @@ function ReaderLink:showAsFootnotePopup(link, neglect_current_location)
     end

     -- if false then -- for debug, to display html
+         UIManager:show( require("ui/widget/textviewer"):new{text = html})
     --     UIManager:show( require("ui/widget/textviewer"):new{text = html})
     --     return true
     -- end
+    html = html:gsub("<title>", "<ztitle>")
+    html = html:gsub("</title>", "</ztitle>")

     -- As we stay on the current page, we can highlight the selected link
     -- (which might not be seen when covered by FootnoteWidget)
--- a/frontend/ui/widget/footnotewidget.lua
+++ b/frontend/ui/widget/footnotewidget.lua
@@ -91,9 +91,9 @@ text-author { display: block; font-weight: bold; font-style: italic; }
  * the footnote number on the same line as the first paragraph via its
  * support of "display: run-in" and a possibly added autoBoxing element) */
 body > section > autoBoxing > *,
-body > section > autoBoxing > title > *,
-body > section > title,
-body > section > title > p,
+body > section > autoBoxing > ztitle > *,
+body > section > ztitle,
+body > section > ztitle > p,
 body > section > p {
     display: inline;
 }
```
it renders as before:
![image](https://github.com/koreader/koreader/assets/24273478/b82b9835-05a3-4cd6-9287-198fd5dfc7ef)

This solution is ugly, so we'll have to look if there's another one .
May be MuPDF can be told the content is/comes from FB2 so it behave differently. Or may be there's some CSS to tweak how `title` content is parsed/rendered.

**Comment by poire-z** [comment]
It looks like MuPDF uses https://github.com/google/gumbo-parser that it ships as thirdparty when parsing "html" - and this parser handles `<title>` as per specs, expecting only text content https://html.spec.whatwg.org/multipage/semantics.html#the-title-element.

If we tell mupdf the document is not `"html"` but `"xhtml"` here:
https://github.com/koreader/koreader/blob/75d3e4c2dcc184281fff490431e98123b6ba0c26/frontend/ui/widget/htmlboxwidget.lua#L55
it renders ok.
With "xhtml", it goes thru the first branch here - while with "html", it goes through the last branch:
https://github.com/ArtifexSoftware/mupdf/blob/113055096abdbde1996669061f64b6463421970e/source/html/html-parse.c#L1522-L1551
So, with "xhtml", it tries first to parse it as balanced XML, and if it succeeds, it is done. Otherwise, it falls back to the gumbo HTML5 parser, like with "html".

Dunno if it is safe and sane to go with "xhtml" always (also with dict results, which may be crap HTML, so fail XML, but fallback to HTML5 - but may be XML will succeed but won't do the right thing unlike HTML5).
Or just use "xhtml" with footnote content that we get from crengine and we are sure it is balanced XML because it's XML from FB2 or EPUB, or because it has already been parsed from HTML by crengine itself.

**Comment by hius07** [comment]
> Or just use "xhtml" with footnote content that we get from crengine and we are sure it is balanced XML because it's XML from FB2 or EPUB, or because it has already been parsed from HTML by crengine itself.

Looks like a good solution.

**Comment by Frenzie** [comment]
> Dunno if it is safe and sane to go with "xhtml" always

Most questions about HTML dictionaries not working come from content that failed to parse as XML. But for footnote popups, yes, that sounds like a plan.
