### ISSUE TITLE
FR: show image and paragraph breaks in footnote, be able to click on footnote to follow the footnote hyperlink

### ISSUE THREAD

**Issue by lightmaster** [koreader/koreader#12258]
**Does your feature request involve difficulty completing a task? Please describe.**
I have an epub file where one of the footnotes is an `<img>`. In the epub reader built into Calibre, it is able to show the image as a popup on top of the current page. In KOReader (on Kobo if it matters), this same footnote pops up as `[image]`. There is also no way to travel from the chapter to the footnotes "chapter" to see that footnote fully rendered. If I manually select it in the ToC, I do see the image as expected.

I also noticed that the footnotes popup does not show paragraph breaks.

**Describe the solution you'd like**
Be able to show an image and paragraph breaks in the footnotes popup, and be able to click on the footnotes popup to travel to that footnote (follow the hyperlink).

**Describe alternatives you've considered**
Manually flip through the 50 pages of footnotes to find the right one to view the image.

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by hius07** [comment]
> be able to click on the footnotes popup to travel to that footnote (follow the hyperlink)

Long-press on the footnote number in the text - Follow Link,

**Comment by poire-z** [comment]
> There is also no way to travel from the chapter to the footnotes "chapter" to see that footnote fully rendered.

There is (at least on touch devices): swipe left/west.
If you have `Tap & gestures > Links > [x] Swipe to follow links` enabled, and if you can get used to using swipe instead of the easy-to-miss-the-link tap, you can just use:
- swipe left to show the footnote popup
- swipe left again to jump to the footnote page and see it rendered in the book
- swipe right to get back to the original page.

As for "paragraph breaks" (which is a bit too generic, there are multiple ways to implement that), it works:

![image](https://github.com/user-attachments/assets/1be01ec7-9d0f-49c1-9311-d90cac670f3e)

`08/01/24-08:48:15 DEBUG HTML: <aside lang="fr" class="ntb" epub:type="footnote" disabledID="_doc_fragment_12_ ntb-049"><p class="txt_ssalinea"><a href="#_doc_fragment_11_ ap_ntb-049-1">43</a>.âCharles PÃ©Â­pin,<i> Les VerÂ­tus de lâÃ©chec</i>, AlÂ­laÂ­ry ÃdiÂ­tions, 2016.<br/>with a BR beÂ­fore<br/>and anoÂ­ther.</p><p>And anoÂ­ther PaÂ­raÂ­graph<br/>with a BR beÂ­fore.</p></aside>`

But I can see some case where it doesn't work:
![image](https://github.com/user-attachments/assets/e869d767-31ca-4228-b7eb-eb1e43164106)

`08/01/24-08:50:17 DEBUG HTML: <li dir="ltr" lang="fr" disabledID="_doc_fragment_0_ cite_note-Lemerle196044-26"><div><autoBoxing><span class="mw-cite-backlink noprint "><a href="#_doc_fragment_0_ cite_ref-Lemerle196044_26-0">â</a> </span><span class="reference-text"><a href="#_doc_fragment_0_ Lemerle1960">LeÂ­merle 1960</a>, <abbr class="abbr" title="page(s)">p.</abbr>Â 44. </span><br/>with a BR beÂ­fore.</autoBoxing><p>This is in a P</p></div></li>`

If I make it a bit more HTML clean:
![image](https://github.com/user-attachments/assets/6b28a192-e3b6-4eb2-b245-016ca89ade61)

Adding `autoBoxing { display: block; }` to the CSS seems to help in this case. Can you add these 2 lines (without the leading `+`) to this file and see if it solves it also for your book?

```diff
--- a/frontend/ui/widget/footnotewidget.lua
+++ b/frontend/ui/widget/footnotewidget.lua
@@ -72,6 +72,9 @@ body > li { list-style-type: none; }
 /* Remove any (possibly multiple) backlinks in Wikipedia EPUBs footnotes */
 .noprint { display: none; }

+/* Let MuPDF know about crengine internal elements */
+autoBoxing { display: block; }
+
 /* Style some FB2 tags not known to MuPDF */
 strike, strikethrough { text-decoration: line-through; }
 underline   { text-decoration: underline; }
```

If not, well, HTML/CSS may have tricks that don't travel well from crengine (rendering the book) to HTML snippet to MuPDF (which renders the footnote popup).

**Comment by lightmaster** [comment]
> > be able to click on the footnotes popup to travel to that footnote (follow the hyperlink)
> 
> Long-press on the footnote number in the text - Follow Link (it requires "Ask with popup dialog" setting for Long-press on text).

I saw it pulled up the dictionary definition of the number, didn't notice the "Follow Link" prompt.
&nbsp;
&nbsp;
&nbsp;
@poire-z Here's the HTML for the Footnote that wasn't line breaking:

```html
<aside id="footnote-6791-1" epub:type="footnote"><a href="Chapter34.xhtml#footnote-6791-1-backlink">1</a>
While researching impact speeds for this answer, I came across a discussion on the Straight Dope Message
Board about survivable fall heights. One poster compared a fall from height to being hit by a bus. Another
user, a medical examiner, replied that this was a bad comparison:<br/><br/><i>“When hit by a car, the vast
majority of people are not run over; they are run under. The lower legs break, sending them into the air.
They usually strike the hood of the car, often with the back of the head impacting the windshield, ‘starring’
the windshield, possibly leaving a few hairs in the glass. They then go over the top of the car. They are still
alive, although with broken legs, and maybe with head pain from the nonfatal windshield impact. They die when
they hit the ground. They die from head injury.”</i><br/><br/>The lesson: Don’t mess with medical examiners.
They’re apparently pretty hardcore.</aside>
```

![20240801_193421](https://github.com/user-attachments/assets/5a65151c-86b2-4352-8435-080eadda42d8)
&nbsp;
&nbsp;
&nbsp;
> Adding `autoBoxing { display: block; }` to the CSS seems to help in this case.

I'll try adding that to see if it helps.
&nbsp;
&nbsp;
&nbsp;
> If you have `Tap & gestures > Links > [x] Swipe to follow links` enabled, and if you can get used to using swipe instead of the easy-to-miss-the-link tap

Just tried that, and it breaks being able to swipe left or right to go to the next/previous page if there's a link anywhere on the screen. Considering how rarely I have ever wanted to follow a footnote to the Footnotes.xhtml file, not that big of a deal to me. Just though that adding tapping the popup to follow the link would be a nice feature.
&nbsp;
&nbsp;
&nbsp;
How hard/likely would it be to get images supported in footnotes?

**Comment by lightmaster** [comment]
> > Adding `autoBoxing { display: block; }` to the CSS seems to help in this case.
> 
> I'll try adding that to see if it helps.

I tried adding those lines to `footnotewidget.lua` and it didn't help. Tried adding `display: block;` to the `aside` CSS, didn't help. I did try replacing the `<br /><br />` with `<p>` tags and that did work.

**Comment by hius07** [comment]
> > Long-press on the footnote number in the text - Follow Link (it requires "Ask with popup dialog" setting for Long-press on text).
> 
> I saw it pulled up the dictionary definition of the number, didn't notice the "Follow Link" prompt.

Because you have checked "Dictionary on single-word selection" setting.

**Comment by poire-z** [comment]
> Just though that adding tapping the popup to follow the link would be a nice feature.

Even if you don't enable "Swipe to follow links", you can still swipe in the footnote popup to jump to the target. A swipe to follow feels more natural than a "tap anywhere" in that footnote popup (moreover, such a footnote popup, when the footnote is long, will scroll, and tap left/right side is used to scroll it, like in the dict lookup result - so possible conflict/inconsistency with using tap to jump).

> Tried adding display: block; to the aside CSS

Doing that makes it work for me (hardcoding your HTML snippet into footnotewidget.lua for testing).
`aside, autoBoxing { display: block; }`
Strange that MuPDF would know it's block. Even wrapping all the HTML with `<div>...</div>` (so, having `<div><aside>...</aside></div>`) does not make it work :/
There's been an update to MuPDF with v2024.07, so it's possible it broke/changed a few things that used to work...

> How hard/likely would it be to get images supported in footnotes?

Unlikely. This is rare, and would need to 1) look if there are images in the HTML , 2) extract them to save them in a dir on the device, 3) rewrite the HTML so src= to these images work , and 4) give that to MuPDF so it can find and use the images. (and the images may have their size styled via CSS, that we don't forward to MuPDF, because it's usually not needed for text, so one may get huge or small images).

**Comment by Frenzie** [comment]
base64 should presumably take care of steps 2, 3, and 4 a bit easier ;-)

**Comment by poire-z** [comment]
Mhhh.
MuPDF quite sucks at HTML :/
With this snippet:
```html
<aside lang="fr" class="ntb" epub:type="footnote" disabledID="_doc_fragment_12_ ntb-049">
 <p class="txt_ssalinea">
   <a href="#_doc_fragment_11_ ap_ntb-049-1">43</a>.âCharles PÃ©pin,<i> Les Vertus de lâÃ©chec</i>, Allary Ãditions, 2016.<br/>
   with a BR before
   <br/>and another.
 </p>
 <p>And another Paragraph<br/>with a BR before.</p>
 <p>And another <span>Paragraph<br/>with</span> a BR before.</p>
</aside>
```
crengine renders it as:
![image](https://github.com/user-attachments/assets/c05368eb-c9d8-4e49-b95b-b84463e581d4)

Mupdf, with "xhtml":
![image](https://github.com/user-attachments/assets/6d67235f-8a15-4bc9-9316-11c746446030)
(notice the last BR inside SPAN is postponed and ensured after the SPAN ends :/

MuPDF with "html":
![image](https://github.com/user-attachments/assets/460eaccf-2bc8-48ba-b36a-6ed9cc3fa768)
(Stuff after a BR are reordered and put before everything else :/).

Firefox:
![image](https://github.com/user-attachments/assets/78c1932a-6613-4429-bbf9-9c48290ef9ba)

I notice in the MuPDF source `aside` is not set as `display:block` (unlike H1,H2...) while they are in the specs - and it seems to be messy when BR are set in imbricated inline elements....

We can't even wrap the footnote content in a `<div>` because then every unknown tag (like aside) becomes inline, and BR inside then get messed up.
We could in our footnote widget CSS set `display:block` on all elements missing it, and we would get:
![image](https://github.com/user-attachments/assets/ed97a4b7-96ff-4b9d-9b81-7d8fc90a0f73)
which is a tad better, but still prone to the BR in imbricated inlines, which may be rare though.

**Comment by poire-z** [comment]
Made better by #12406 (but not fully solved, as it's a MuPDF deficiency) - at least for the paragraph break part - I don't think we can easily and nicely get images, which must also be rare - MuPDF may show them as [IMAGE], and the user can jump to the footnote in the book to see that image properly rendered.
