### ISSUE TITLE
Book status in History popup

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#12273]
Another really minor feature that I miss sometimes, is to have the Book Status available as a button in the history long press popup for a book.
Some times I would like to see the rating or the review I gave to an older reading, or change them after reading something else (another book of the same series etc.).

To do that now, I have to re-open the older book, change the things I want, and re-open the currently reading book again.
([rant] This brings the older book at the top of the History list, a thing that it shouldn't happen for finished books since I remember there was a feature implementation for this exact thing, but maybe it's not on by default and I didn't find it with a quick search of the menu, but that is a totally different story. [/rant] 😛 )

I know that this popup is getting really loaded as time goes by, but hey..

**Comment by jonnyl2** [comment]
+1 for this. Perhaps `Book description` could be launched via long-press on `Book information`, as 'Book description' is part of 'Book information' anyway (and can be opened from that screen as well). 

That way, no extra button would need to be added.

**Comment by jonnyl2** [comment]
The setting you're looking for is in the File browser top menu, File cabinet tab, Settings >, History settings >, ☑︎ Freeze last read date of finished books.

**Comment by poire-z** [comment]
> `Book description` could be launched via long-press on `Book information`, as 'Book description' is part of 'Book information' anyway (and can be opened from that screen as well).

-1 to sacrificying `Book description` on the altar of `Book status` that a limited number of users use (I guess).

**Comment by noembryo** [comment]
> The setting you're looking for is in the File browser top menu, File cabinet tab, Settings >, History settings >, ☑︎ Freeze last read date of finished books.

Thank you for the info.
I would never find it there, because I keep forgetting that there are different settings in the file manger.
Can't convince myself that it's a different program (than the reader).

**Comment by jonnyl2** [comment]
>[poire-z] -1 to sacrificying Book description on the altar of Book status that a limited number of users use (I guess).

But relegated to long-press is not sacrificed? I thought thought it'd be the most logical, because it's part of the Book information anyway.

But Book status via long-press on `Book information` would be just as good for me, but I'm not the requester :)

**Comment by noembryo** [comment]
Book Information panel is a good place to add a "Status" property with a "Tap to display" value, similar to the "Cover image" property..
So, no new button is needed that way.
Even the "Book description" can be removed since all the info are in this one place, although I can see the practicality to have a visible shortcut for us lazy people.. 😉

**Comment by jonnyl2** [comment]
Or all buttons are left alone and Book status is opened via long-press on any one of the already available status buttons `Reading`, `On hold`, or `Finished`? This makes the most sense as they _are_ about the book status. And wouldn't require opening two separate screens.

**Comment by poire-z** [comment]
(My use case for that popup is mostly to just delete the book I'm done reading, or read Book description. I hardly go to Book information, because I have most of that (title, authors) in the mosaic or detailed list item. And I have the "hint for book with description" that tells me there this additional thing to read. Having it in that popup is just perfect, I don't need to go to Book information.)

**Comment by jonnyl2** [comment]
@poire-z: then I certainly understand that you like to have the Book description accessible with one tap. But if fewer users use the Book status screen, then that'd probably only be because it's relatively hidden at the moment. The Book status screen allows giving the book a star-rating and adding a short review or summary. What better starting point for those actions would there be than the list of books already opened and/or read? IMO, it definitely belongs in the History. This just my quick sales pitch :). _How_ it is launched from the History is of secondary importance (to me at least).

**Comment by hius07** [comment]
Screenshots in the PR.

**Comment by noembryo** [comment]
> Screenshots in the PR.

Great idea!! 🥳 
What happens if the review has many lines?
Perhaps a multiline widget?
Anyway, this is the best way to implement it..
Thanks 👍

**Comment by hius07** [comment]
Sure, multiline reviews are okay.
