### ISSUE TITLE
FR: a very STABLE release

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12339]
Please don’t take this ticket too harsh, I (as a die-hard beta tester which I am OK with) am just trying to help regular users and new comers :D 

**Does your feature request involve difficulty completing a task? Please describe.**
Monthly releases got a bit more buggy recently. 2024.07 seems to have many issues that are being fixed very quickly, but still the 2024.07 release is therefore not really stable anymore, more like just another nightly.

**Describe the solution you'd like**
Should we introduce a QA checklist before the monthly release?
Say,
1) open a fb2 book with images
2) open a book with complex TOC 
3) (other files with complex or others important structures)

Also, tag “bug” reveals 68 unclosed issues, should we focus on addressing those?

https://github.com/koreader/koreader/issues?q=is%3Aopen+is%3Aissue+label%3Abug

**Describe alternatives you've considered**
Doing all this by hand and when time comes and by different people and (hopefully) reporting it here :D 

**Additional context**
This ticket is designed to help mostly non-devs/non-testers to just enjoy KOReader without needing to open a ticket.

I am about to gift our Kobo Clara HD to a family member (high school) and I wouldn’t expect them to understand and be able to report bug in KOReader. I would expect them just to read books and enjoy life :D

**Comment by Frenzie** [comment]
> Another idea is to have this automated.

It is, ftr. ;-)

**Comment by mergen3107** [comment]
Great! It exists for epub. Now we need it for fb2 (since I found that images were broken on stable), pdf, djvu, etc :D

**Comment by pazos** [comment]
1. The very stable release is the last nightly unless it introduces some new bug that affects you :)
2. In that case the very stable release is the nightly after the bug is fixed, unless you can spot some other bug. In that case go back to 1.
3. Congrats, very stable release :)

Jokes aside. A lot of changes between 2024.04 and 2024.07. That's why there wasn't a .05 or .06 version. I was expecting some bug to slip into the "stable" release just because most people doesn't use nightly and run KOReader in devices we can't test.

Real end users (you're not one of them, @mergen3107 :)) shouldn't have FOMO and stay on a version that works for them (even if it's two years old), unless they want to try a new feature. In that case the call to action is:

1. Update to last stable.
2. Did you spot a new bug? -> update to last nightly
3. Did your bug persist? -> see if it is reported. It is not? -> report it.

Also, users that know the previous version was golden can always revert to it until they wait for 3 to be resolved.
New users which find a bug the very first time they install KOReader aren't that lucky. Sadly we're short of devs and hopefully we're not chassing fame, so I think we can focus on users that are willing to take some time  figuring out if/how/which version of KO works for them, if any.

But yeah, the last release (the nightly) is always the very stable release. Unless it isn't :)

**Comment by pazos** [comment]
> Also, tag “bug” reveals 68 unclosed issues, should we focus on addressing those?

The problem with some of them is that there are not reproducible unless you have some particular device of a specific platform, sometimes on a particular firmware.

Others require to use a certain feature that's there (because almost everything is there!) but not actively used by people that are watching bug lists :)

But, yeah. If somebody has the time and the motivation (and the device, firmware or usage required to reproduce the issue) I would recommend to go and try to reproduce older bugs and see if they can. If they can they can attempt to fix them. If the bug isn't reproducible and the ticket isn't well documented it might be better to close the issue and wait for somebody to report it again (hopefully this time with better reproduction steps)

**Comment by mergen3107** [comment]
> 1. Update to last stable.
2. Did you spot a new bug? -> update to last nightly
3. Did your bug persist? -> see if it is reported. It is not? -> report it.

> Also, users that know the previous version was golden can always revert to it until they wait for 3 to be resolved.

That is exactly what I am trying to address here. (1) should be the only item in that list above. Currently 2024.07 has many bugs, so it is not a good rollback backup.

For example, images in fb2 books - this was also replicated in the emulator and got missed. So my proposal is to add a QA routine to be able to catch it early.

> But yeah, the last release (the nightly) is always the very stable release. Unless it isn't :) 

**I** do understand that :D but you see, how hard it is for me to advocate for KOReader and convince people if I end my pitch with these words? :D 

Although, admittedly, people don't realize that, say, iOS and Android apps have way worse QA control sometimes - and their "updates with bug fixes every other day" are basically like our nightlies :D except that here devs are plain honest about what was actually fixed

**Comment by mergen3107** [comment]
Thank you for your inputs @pazos !

**Comment by hius07** [comment]
I was going to say some words but @pazos did it much better.

**Comment by Frenzie** [comment]
> That is exactly what I am trying to address here. (1) should be the only item in that list above. Currently 2024.07 has many bugs, so it is not a good rollback backup.

To be clear, I've done what you suggest in the OP before a release for many years. The act of tagging means I'm sufficiently satisfied on Kobo and Android. If we are truly worried that something specific like images in FB2 might break an automated test should be added for that. Also note that I might not necessarily consider something like dictionaries not working on Android or images not displaying in FB2 a release blocker but that's situational (e.g., is there an easy culprit to revert, is there a dev available to work on it, etc.).

**Comment by mergen3107** [comment]
> Also note that I might not necessarily consider something like dictionaries not working on Android or images not displaying in FB2 a release blocker

This is one of the main points where I would like to bring attention. Maybe, in my mind “stable vs nightly” is about the same as, for example, Ubuntu LTS vs yearly releases, or maybe openSUSE Leap (stable, low period of updates) vs openSUSE Tumbleweed (bleeding edge).

Because say images in fb2 an broken dictionaries will break experience for those who updated to the next stable version.

For example, I can’t right now tell my non-techy friends with einks to just go an update to 2024.07. I can tell them like, wait until nightly 74 (or whatever the fix is), but you can already see how weak this point :D next logical question is “are you sure this nightly is good good?” - and I don’t know, actually :D

**Comment by NiLuJe** [comment]
> I can’t right now tell my non-techy friends with einks to just go an update to 2024.07

And that's perfectly fine.

@pazos summarized it perfectly above.

If you're not comfortable running a nightly because your current release has a blocking issue *for you* (and, again, @Frenzie said everything there is to say about the subject: time is the limiting factor, so choices have to be made, and they'll be colored by what we can actually test and/or care about), just roll-back to the previous release.

**Comment by poire-z** [comment]
QA, schQAss...
We may add a fb2 with image test, and it will work - another FB2 doing images differently may not work. We'll notice the difference when you will report it. You @mergen3107 , not the test. You are much better at testing than a CI/QA test!

As for the commit causing issues with that FB2 with images book, it was merged & bumped after v2024.07 - just because it felt it could be risky. It is not in the current stable I think.

**Comment by mergen3107** [comment]
> As for the commit causing issues with that FB2 with images book, it was merged & bumped after v2024.07 - just because it felt it could be risky. It is not in the current stable I think.

Well, it was discovered on 2024.07 though… :D

**Comment by Commodore64user** [comment]
perhaps when the next stable comes out 24.08, a note could be added to 24.07 indicating or advising [future users] to either use the previous or next stable version, in other words discourage its use.

**Comment by pazos** [comment]
> You @mergen3107 , not the test. You are much better at testing than a CI/QA test!

100% agree :)

> perhaps when the next stable comes out 24.08, a note could be added to 24.07 indicating or advising [future users] to either use the previous or next stable version, in other words discourage its use.

Absolutely not :)

We have had major bugs and regressions on monthlies before and never instructed users to use one or other version. That's work for maintainers and cognitive overhead for end users. 

Much better to do a point release when the bug fix deserves it. We did that in the past.

This time I'm not sure if it worths the time. Only @Frenzie knows :)

IMHO point releases are for "entire platform crashes", "no engine for epub", "filemanager hangs up entirely". But I have no problem with it if you think it applies here.

Also please remember that even in the case of "entire platform crashes" or "no engine for epub" some users will be unaffected.

**Comment by mergen3107** [comment]
"As not planned" = "Not as described in the OP".
Otherwise, the rollout process stays the same, for better or worse :D

**Comment by Frenzie** [comment]
> Otherwise, the rollout process stays the same, for better or worse :D

I did delay for a month due to some Android concerns, ftr. ;-)

**Comment by pazos** [comment]
Life without (too many) releases is a joy. Even more when less releases means more development :)
