### ISSUE TITLE
FR: visual indicator of last closed document in the filemanager

### ISSUE THREAD

**Issue by wasamasa** [koreader/koreader#1235]
I'm using the november nightly on my Kobo Aura HD and am kind of missing the feature that swiping to the right at the end of a document in a directory loads the next one and views it from the beginning. Currently I'm looking up what file I'm reading in the history list, then enter the file manager to find the next one, but that's a good bit more tedious than the way the Nickel software does it.

**Comment by wasamasa** [comment]
@ad1217 Thanks, that would indeed work out for me.

To contribute something more meaningful to advance progress, what other input events than single taps on a specific zone can be detected on all supported devices? I didn't have so much luck doing long holds reliably, hence the question.

**Comment by chrox** [comment]
@ad1217 You can find currently support gestures [here](https://github.com/koreader/koreader/blob/master/frontend/device/gesturedetector.lua#L6-L23). It should work on all Kindle, Kobo, PocketBook and Android devices except that on some Kobo devices some two_finger_* gestures may not work as expected.

**Comment by wasamasa** [comment]
@chrox Looks good, how about combining the last page, a double tap and an opt-in setting?

**Comment by chrox** [comment]
Sorry @wasamasa, I don't think automatically open *next* book in any case makes sense to me. I mean *next* is a vague concept here because we have different sorting options now in the filemanager, the documents can be sorted with alphabetically(or reversed) and with date the book was added(or reversed). Even though we arbitrarily use the alphabetic order for the next document, I cannot see much worth of the feature.

I agree with you that currently there is no easy way to distinguish between some documents that have very long filenames. The right way to solve this problem is showing meta data on the filemanager as proposed in #578 or we can mark the document that was just closed with an underline so that you can choose which ever the next document in the filemanager.

**Comment by wasamasa** [comment]
I understand your concern and wouldn't mind an enhancement that aids me in browsing my library to select the next book I'd like to read. Combining the feature of the file browser to show the last opened directory, scrolling or centering around the last-opened file and visually highlighting it with an underline could do the trick.

The reason why I've proposed the initial approach is because it seemed easy to implement and because I know it from other existing readers, including [SimpleComic.app](http://dancingtortoise.com/simplecomic/), [mcomix](http://sourceforge.net/p/mcomix/wiki/Home/) and the original reader application on my Kobo Aura HD. As far as I can tell all of them select the next one by alphabetical ASCII sorting of the file names which isn't ideal, but good enough.

**Comment by ad1217** [comment]
As an alternative, would it be possible to have a directory with a special extension be treated like a unified book, with each file a chapter? Therefore it would automatically switch between files, save progress, and not interfere with normal operation.

**Comment by wasamasa** [comment]
That could work for me, I assume you're speaking of a model à la `Foo.app` on OS X.

**Comment by wasamasa** [comment]
Nice, thank you very much!
