### ISSUE TITLE
Image size display error

### ISSUE THREAD

**Issue by Huahddd** [koreader/koreader#12405]
* KOReader version: 2024.07
* Device: kobo forma

#### Issue
Large images are displayed very small. Picture 1 is the correct display, picture 2 is the current koreader display. The display size of the images was correct in the past version, and this error appeared after an update (I forgot which update).
I uploaded the epub file with the error, and you can see the error at the beginning of each chapter. Many other books may have this error as well.
![1](https://github.com/user-attachments/assets/6671b0d5-98a1-4b5f-9851-cf368f43584b)
![2](https://github.com/user-attachments/assets/7db790d2-4985-4708-9289-4e07d31571d3)
[book.zip](https://github.com/user-attachments/files/16740904/book.zip)

**Comment by mergen3107** [comment]
Did you try dpi settings in the bottom menu? (Not to confuse with ones in Top menu). 

Smaller the number, larger the images

**Comment by poire-z** [comment]
> Smaller the number, larger the images

No, smaller the number, smaller the images :)

Nothing specific about this image, it's aligned right, and get a fixed height of 150px.

![image](https://github.com/user-attachments/assets/d44cfdb2-b228-4956-a611-bebca342f635)

These 150px are indeed scaled by the bottom Zoop/DPI value:
![image](https://github.com/user-attachments/assets/cead72b3-6c3b-4791-8bda-c133efbaa076)

With 96, we use the 150px as-is, so it's small on our high dpi devices.
You are free to increase it - and you may get how other sofware (which may scale CSS/HTML pixels according to your device DPI) to show it bigger:
![image](https://github.com/user-attachments/assets/3a9ecfdc-ce15-4a89-9f36-e80b72fdb7b5)
with 212dpi, we will render these 150 px as  `150 x (212/96) = 330px`.

(I insist on keeping our default to 96px, and not switch it to the device DPI, because if we do that, we may get a lot of other things bigger, ie. any `margin: 12pt` used in Word-based documents, and the whole thing would look big and full of empty space. Best to keep decorations small and show the content, and let the user increase Zoom when he feels it is needed.)

**Comment by Huahddd** [comment]
ok，my problem is solved. thank u
