### ISSUE TITLE
The cursor does not move by tapping, in "Edit highlighted text" window.

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12444]
* KOReader version: v2024.07-160
* Device: PB 628

#### Issue
When editing a long highlighted text which extends over two or more pages, if we want to move the cursor to a point on the second or next page by tapping it, the cursor will move to that point but on the first page.

![Reader_2024-08-31_211454 (Small) (Phone)](https://github.com/user-attachments/assets/8b3c3592-f9a9-4360-88bf-0a00bc653ffa)

#### Steps to reproduce
Highlight a long text. Open the Bookmark list and select the highlight to edit the text. Use the arrow to move to the second (or third, etc.) page (screen of highlighted text). Tap on a point in the text to move the cursor to it. The text moves to the first page (beginning of the text) and the cursor moves to the point on the screen you have tapped.

**Comment by hius07** [comment]
Somebody has broken InputDialog, including the Text editor, recently I believe.

**Comment by poire-z** [comment]
This issue seems solved if we comment out the `self:focus()` on line 146:
https://github.com/koreader/koreader/blob/d097dc0f8c00d39b02be6b046199baf5033c120a/frontend/ui/widget/inputtext.lua#L138-L147
Added by @NiLuJe 's big #12361.
It seems this `:focus()` will call `TextBoxWidget:focus()` that does a whole `:free()/:init()`, which seems quite uneeded and expensive for this case where we just reposition the cursor inside a perfectly fine textboxwidget (and even if we were to focus on a button, and back to that textbox, this :free/init would be uneeded.

(I don't have the courage to give this more thoughts, I hope @NiLuJe can :))

**Comment by NiLuJe** [comment]
I was under the impression that simply did `self.focus = true`, which is pretty much all I wanted to do IIRC ;).

Will give it another look tomorrow ;).
