### ISSUE TITLE
Write highlight to PDF: uncentered pop-up window

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12500]
* KOReader version: v2024.07-172
* Device: PB628

#### Issue
When saving highlights in pdf with a prompt is enabled, after closing a pdf file that has been read in landscape mode, the prompt pop-up window "Write highlights into this PDF?" is not centered, as shown in the screenshot below.

![FileManager_2024-09-09 (Small)](https://github.com/user-attachments/assets/8b74d8f5-39ca-472a-9a3f-2e6ed152ee10)

**Comment by hius07** [comment]
This dialog is extremely ugly. It appears after the document is closed, when we see either the file browser or (even worse) other document.
Given the current architecture it cannot be fixed with reasonable measures.

I am going to rewrite this setting, featuring:
-"always" and "disable" only, no "prompt"
-per document and global settings
-optional notification about the current setting on opening a document
-actions "Save all highlights to pdf file" and 'Delete all highlights from pdf file"
Hope this satisfies users' requirements.

**Comment by NiLuJe** [comment]
:100:, I haven't looked at the code, but given when it shows up and what it does, I'm also worried it currently does very naghty things re: lifecycle concerns.

So, killing it with fire has my vote ;).

**Comment by hius07** [comment]
Impressive gymnastics:
https://github.com/koreader/koreader/blob/7ff40a341242abd586d2e6a49f3777465ab8950e/frontend/apps/reader/modules/readermenu.lua#L390-L403
