### ISSUE TITLE
KOReader ignores Bluetooth page turner

### ISSUE THREAD

**Issue by rivermoo2n** [koreader/koreader#12541]
hi
im not really sure if this supposed to go here but im running out of options
well, my issue:
i bought an 8bitdo zero 2 to use as a page turner and it works on the main launcher but on koreader dont. 
(I have an ereader android based where i had to download the arm version instead of the arm64, not sure if it matters tbh)
i was told to remap the keys to volume up and down but i havent had luck (i mean it does work on my laptop but not my ereader)

i dont know what else to do
is there anything to do at all or is there no option? 

thanks in advance

**Comment by NiLuJe** [comment]
Yes, we kill bluetooth by design on Kobo.

Duplicate of #9059, which has more details about why, and possibly a WIP third-party plugin.

**Comment by Frenzie** [comment]
> on Kobo

I think it says Android. But @rivermoo2n please provide more complete device info.

**Comment by NiLuJe** [comment]
Oops ^^.

**Comment by Frenzie** [comment]
Volume up/down work on Android in principle. Maybe @pazos knows if they'll work on BT controllers.

**Comment by rivermoo2n** [comment]
> I think it says Android. But @rivermoo2n please provide more complete device info.

Its a NabukAurora, current android version 8.1.0 @Frenzie

**Comment by rivermoo2n** [comment]
> Oops ^^.

is it closed for good? @NiLuJe

**Comment by pazos** [comment]
On android we support all kind of Human Interface Devices, both via bluetooth and usb.

Some notes:

1. We don't support composability, so keyboard input is not possible (you can pair a key event with a KO action, but not typing directly on the program)
2. We don't support indexing the input device that generates the event, so we react blindly, assuming the keymap applies to **all** input devices.

With that in mind, your user case should be supported with https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-keys (the last sentence has a link with instructions to debug and get the events the bluetooth controller is sending)

But if your device has physical keys attached and the bluetooth controller produces the same key events when you remap one you will remap the other, too. In that case it would be better to use a 3rd party android app that remaps the keys on your bluetooth device and send the proper keys to KO (or unused keys that you can remap following the wiki above)

> is it closed for good?

It will be closed, eventually. It can stay open for a while but doesn't change much on the grand scheme of things ;)

**Comment by rivermoo2n** [comment]
> With that in mind, your user case should be supported with https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-keys (the last sentence has a link with instructions to debug and get the events the bluetooth controller is sending)

> It also might be a duplicate of https://github.com/koreader/koreader/issues/6544 (if the controller produces nil when pressing a button or doesn't produce an output)

honestly i've been trying everything.. i did  the adb thing but it gets stuck on `adb shell logcat KOReader:* *:S | grep "key event =>"` and it never produces an output but i havent found what else to do about it

**im not sure which mode of my 8bitdo zero 2 i should be trying to remap too**

i download the `event_map.lua` and it doesnt work either
i have remapped it through other softwares such as JoyToKey and a random one but it doesnt work :(

is there anything else to do?

**Comment by pazos** [comment]
Yay. It looks you're not comfortable enough to tinker with your hardware device + android. If that's the case I would suggest you to get another page turner. Most of the simple ones produce regular key events that are easier to remap or you don't need to remap them at all!.

Or, if you like a lot your gadget, change the application :)


If I'm wrong you can try again: but you'll need to grasp the `adb` + device config + host os "rules" yourself by following one of the many guides available online.

**Comment by rivermoo2n** [comment]
> Yay. It looks you're not comfortable enough to tinker with your hardware device + android. If that's the case I would suggest you to get another page turner. Most of the simple ones produce regular key events that are easier to remap or you don't need to remap them at all!.

Yeah im not confortable to tinker stuff around... 

> Or, if you like a lot your gadget, change the application :)

no! i like koreader better :D
I guess ill sell mine and get common page turner so i dont have to mess with configurations jajaja

thanks for the help!

**Comment by pazos** [comment]
wait a few hours before selling it. I think I figured out why it doesn't work :)

**Comment by rivermoo2n** [comment]
> wait a few hours/days before selling it. I think I figured out why it doesn't work :)

Okay ! I'll do , thanks you again :)

**Comment by pazos** [comment]
@rivermoo2n: in the mean time...

Could you pair your 8bit thingy with a regular android phone, install https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay&hl=en_US&pli=1

Then it is a matter of:
1. launch the app
2. press, one by one, each button
3.  and document which "code" is used on KeyDown.

????

That would make things way faster for your particular case :)

**Comment by rivermoo2n** [comment]
> @rivermoo2n: in the mean time...
> 
> Could you pair your 8bit thingy with a regular android phone, install https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay&hl=en_US&pli=1
> 
I can't download the app, it doesn't let me. I tried searching for an apk and it doesn't let me either.
I tried with another phone and well, doesn't work

Since the plan it remapping the keys, would JoyToKey work? Tho I'm still wondering in which mode I should be keymapping the 8bitdo zero 2 🙇‍♀️

**Comment by pazos** [comment]
@rivermoo2n: I hope you still have that 8bit-do controller. If so, please follow the instructions.

1. Pair your controller with an android device
2. On that device download the latest KOReader nightly: **[32bits](https://ota.koreader.rocks/koreader-android-arm-v2024.07-225-ge45119453_2024-10-01.apk)** or **[64bits](https://ota.koreader.rocks/koreader-android-arm64-v2024.07-225-ge45119453_2024-10-01.apk)**. Use the 32bits version if you're not sure.
3. In KOReader's File Manager you'll need to go to Tools -> More tools -> Developer opts -> Start eink test compatibility (or smth similar, I'm talking from memory)

On the test activity most of the instructions you'll see won't apply here, but if you press a button (from the device itself or from a bluetooth controller) you'll see a popup telling you which number is.

Please do it for each button on your controller, at least for d-pad, since I'm very curious to know which events are being emmited.


The kind of report I would love is something like:

- dpad up : x
- dpad down: y
- dpad left: w
- dpad right: z

**Comment by rivermoo2n** [comment]
@pazos hi, still have the 8bitdo :D
I tried what you told me but nothing popped up sadly
I did it on Android, Windows and Keyboard mode.
Things I noticed:
- My devices is unsupported but on Rockchip RK3026 the test e-ink works (I know, not the point but still)
- on Android and Windows mode when I press the keys they kind of work ONLY on the test, for example: if I open the test light, with the pad I can increase the dim and with B I can close the test
Yet, no numbers pop up


Side note:
I remember messing around with `adb shell getevent` since it should tell me which event are being triggered.

Thanks for still helping me!

**Comment by pazos** [comment]
> Thanks for still helping me!

You're welcome. But I'm going to stop here :)

Your "no works" across the board provides very little feedback and this is no longer an issue here but with your skills following intructions.

I would suggest to try again as a last chance because it looks like you didn't download the proper version linked above.
If you did download and install the proper version and yet you don't see a popup/toast on the screen when you press any button then your device has broken notifications and you'll need to do the test on another, working device.

**Comment by rivermoo2n** [comment]
> Your "no works" across the board provides very little feedback and this is no longer an issue here but with your skills following intructions.

I'm sorry. i had some issue when downloading the Koreader you linked so i ended up going for the latest version on the page. my bad

> I would suggest to try again as a last chance because it looks like you didn't download the proper version linked above.

I managed to do it! 
1. i used the start compatibility test and adb shell to get the keys (https://github.com/koreader/koreader/issues/5761#issuecomment-573345775)

2. i created the `event_map.lua` file with the following code with the help of ChatGPT (https://github.com/koreader/koreader/wiki/Keymapping) :

```lua
return {
    -- D-pad mappings
    [19] = "Up",       -- D-pad Up
    [20] = "Down",     -- D-pad Down
    [21] = "Left",     -- D-pad Left
    [22] = "Right",    -- D-pad Right
    
    -- Button mappings
    [99] = "Up",       -- X button mapped to Up
    [100] = "Left",    -- Y button mapped to Left
    [96] = "Right",    -- A button mapped to Right
    [97] = "Down",     -- B button mapped to Down
    
    -- Shoulder buttons
    [103] = "R",       -- R button (Right shoulder)
    [102] = "L",       -- L button (Left shoulder)
}

``` 
**Most parts of the code are useless**. The pad doesnt work at all but the A button and the Y button do the job of turning the pages. Thats all i need

Again, thanks for the help !

**Comment by titandrive** [comment]
This is one of the only threads that shows up when searching google to solve this very issue. I spent literally my entire weekend trying to figure out how to use my page turners and kept coming back to this post. Thought I would update it with some of my findings. 

Currently, the only way to use controllers is via the above linked keymapping. But keymapping explicitly ignores many keycodes, namely multimedia keys (play, pause, next track) and d-pads. And there's no way to overcome this via keymapping. I tried for *hours* this weekend. 

This is even more frustrating because most page turners send multimedia keycodes making them very frustrating and nearly impossible to setup without all sorts of hacky workarounds.

I managed to throw together a plugin today via Claude that overcomes both issues: it is way easier to use then keymapping (which is decidedly not beginner friendly) *and* it supports all keycodes. 

I think support for page turners is an important accessibility issue that Koreader doesn't take as seriously as it should. 

https://github.com/onatbas/bluetooth.koplugin
