### ISSUE TITLE
Plugin: On demand direct (on-device) epub download from the Anna's archive using API endpoints

### ISSUE THREAD

**Issue by arpanghosh8453** [koreader/koreader#12597]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently, you can download books and sideload it for later reading but there is no on device browser for file download from the internet. This plugin development can potentially help the people who want to download a book directly on demand from the internet on their e-ink device while reading. 

**Describe the solution you'd like**

I have found this 3-rd party API wrapper : https://rapidapi.com/tribestick-tribestick-default/api/annas-archive-api for https://annas-archive.org/

It works quite well for popular books. The documentation is straightforward. The free plan includes 3000 monthly requests, which sums up to 1500 books (search request and download link request) per month using your free API token. Here is a example search request and response :

![image](https://github.com/user-attachments/assets/f442ce13-d68a-4d38-a858-77fce637b101)

For downloading the chosen option, one can just pass the MD5 hash to the get download link endpoint:

![image](https://github.com/user-attachments/assets/411eb035-8f7d-464b-8a83-e009cde331b8)

The sort is by default based on relevance, so the top result is most of the time what one needs. I can make this plugin myself and open a PR, but with my limited lua ability and familiarity with KOReaders setup, the best I can do is to get the search name/text in an input box and download the top result in a pre-defined folder defined in a config file (along with other customizable parameters, like Language, filetype etc.). But given the top result is not the one you always need, it will be better to have a popup displaying the search response in a more user friendly way (possibly with the extracted image from the links) and let the user pick the one to download, if any. I won't be able to develop such features, and hence I am posting this as an issue to get the view of the developers here on this. I understand this is a 3-rd party plugin with a free tire option, and may not be ideal for integration with this project. But as there are default plugins with support for readwise (fully paid, no free tire), I hope this can be added as an optional plugin too. This will be a very nice feature to have, specially for e-ink devices without browser, where the only option is to connect and copy from a wired or wireless device (through calibre etc.) where you already downloaded the books. This plugin will enable on demand arbitrary book download with just an internet connection. Let me know your thoughts.

**Comment by pazos** [comment]
> Currently, you can download books and sideload it for later reading but there is no on device browser for file download from the internet. 

Yes, we have :). It is called OPDS, it is an standard that can interface with free and privative book services, including your own self hosted instances.


> I understand this is a 3-rd party plugin with a free tire option, and may not be ideal for integration with this project.

100% correct.

> But as there are default plugins with support for readwise (fully paid, no free tire), I hope this can be added as an optional plugin too.

Yay. The exporter is the plugin. Since it was made modular somebody added support for readwise. Maybe on the future somebody adds support for yet another crap. We can tolerate it as long as it doesn't add burden to support. In that regard "readwise" is a better exporter than "memos" even when the later is free, self hostable, software.

But for a plugin that only supports a single crap it is better to put it elsewhere outside this repo. It should find a place in https://github.com/koreader/contrib as long as somebody develops it and submits it to that repo.

Another case in point is AI. A general AI plugin that can interface with particular models would be good here. Since that potential plugin is also modular somebody might want to write support for a particular AI crap, and that's OK IMHO.

A plugin that interfaces with a particular AI crap?. That's better elsewhere.
