### ISSUE TITLE
Calibre not syncing collections

### ISSUE THREAD

**Issue by shawly** [koreader/koreader#12593]
* KOReader version: 2024.07
* Device: Kobo Aura

#### Issue

When I use KOReaders calibre plugin I tried to use the feature you can see in this screenshot to automatically create collections based on metadata:

![image](https://github.com/user-attachments/assets/c09ddeb1-1f62-4782-a68c-bcff452e2422)

But when sending a book the collections stay empty, no new collections are created in koreader either.
Looking through the code of the calibre plugin, it seems that this isn't implemented?

#### Steps to reproduce

 - Connect koreader to calibre
 - Change device configuration to use metadata for collections
 - Try to send book
 - Check if collection was created in koreader or in the calibre collections column on the device

**Comment by pazos** [comment]
Not implemented. Won't be implemented. KOReader lacks the concept of a library, so all things library can't be implemented.

**Comment by shawly** [comment]
So users are supposed to either manually edit the collection.lua under settings/ or manually add books to collections through koreader?

**Comment by Frenzie** [comment]
Collections are a decade (?) newer than the plugin but indeed it might be possible to do something with that if one were motivated (not me, I ignore calibre :-).

**Comment by pazos** [comment]
Ah. my bad. I didn't know we have something called collections as a separate "view".

> it might be possible to do something with that if one were motivated (not me, I ignore calibre :-).

Yeah, it is doable but not easy. We currently use 3 different code paths to deal with calibre metadata (but they're redundant, AFAICT) and none of them support custom columns. We do it purposely because handling custom columns might be a nightmare that none of us here wants to address.

Also, even if somebody wants to implement this I think we shouldn't follow the "#collections" hack, that's part of nickel processing. Or maybe we do (like we inherit sidecar dirs from kindle) but making sure that's documented as a feature of the program, not from a specific platform.

Pinging @NiLuJe, as it is the other maintainer that uses calibre here.

**Comment by NiLuJe** [comment]
Yeah, I stopped using collections de day Kindle broke nested collections, and that was maybe 10-years ago now. Haven't missed the concept since ;).

**Comment by NiLuJe** [comment]
(Also, let me haunt this issue some more with the ghost of an SQL implementation of collections ;p).

**Comment by shawly** [comment]
> Also, even if somebody wants to implement this I think we shouldn't follow the "#collections" hack, that's part of nickel processing. Or maybe we do (like we inherit sidecar dirs from kindle) but making sure that's documented as a feature of the program, not from a specific platform.

Since the calibre plugin uses the smart device driver, the plugin wouldn't need to handle custom columns right?

The collection of values from the custom defined columns (like in my screenshot) is handled by calibre [here](https://github.com/kovidgoyal/calibre/blob/cc16d900ae8371e59a87bc23a904204f92789b4d/src/calibre/devices/smart_device_app/driver.py#L1401) and then [sent to the client](https://github.com/kovidgoyal/calibre/blob/cc16d900ae8371e59a87bc23a904204f92789b4d/src/calibre/devices/smart_device_app/driver.py#L1424C23-L1424C34) which would be the koreader plugin, if it had implemented the SEND_BOOKLISTS operation which it currently doesn't implement as far as I can see. So to add books to collections one would need to implement this op code.

The display of columns would probably be handled by the already implemented op GET_BOOK_COUNT [here](https://github.com/kovidgoyal/calibre/blob/cc16d900ae8371e59a87bc23a904204f92789b4d/src/calibre/devices/smart_device_app/driver.py#L1291C45-L1291C59) but I haven't exactly understood yet how collections from a device are mapped to the calibre device view. I think it is implemented in the [CollectionsBookList#get_collections](https://github.com/kovidgoyal/calibre/blob/cc16d900ae8371e59a87bc23a904204f92789b4d/src/calibre/devices/usbms/books.py#L161) itself but I don't get what the koplugin would need to send to calibre..

**Comment by pazos** [comment]
> Since the calibre plugin uses the smart device driver, the plugin wouldn't need to handle custom columns right?

I'm not entirely sure what are you trying to imply.

During wireless transfers we, the client, are in charge of doing everything on the client side and communicate back to the server. The original calibrecompanion plugin just ignored any kind of metadata other than the file name and react to `SendBook` dumping binary data to a file.

Then I rewrote it, so the information persists between sessions. That's great because the client can now report the books it actually has, among many other things.

In order to not reinvent the wheel we choose to dump the metadata to a json file, like calibre does on wired transfers. In order to not waste space we choose to discard all the fields in the json object that we don't care. That's all of them, except https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/metadata.lua#L18-L27

But more important than that. I didn't realize the feature you're requesting is not possible **at all** (at least not without very hackish, ugly code) in wired transfers, since there we don't do a thing :/

So, I'm afraid this is going to be in the realm of user patches, if somebody provides one. Feel free to play with the current plugin (ours). It contains a bunch of debug statements about the json chunks calibre send us. You'll need to hack on that code and react differently when a book contains metadata telling you it belongs to a collection.

I'm going to close as not planned. Feel free to ask any question if you attempt to do it on your own. It would be a cool patch/plugin.

**Comment by shawly** [comment]
> > Since the calibre plugin uses the smart device driver, the plugin wouldn't need to handle custom columns right?
> 
> I'm not entirely sure what are you trying to imply.

Sorry I worded this poorly, the calibre driver that is used for wireless clients is the "smart device" driver I linked.

> But more important than that. I didn't realize the feature you're requesting is not possible at all (at least not without very hackish, ugly code) in wired transfers, since there we don't do a thing :/

Yeah I got that, I hoped we could at least add this feature to the calibre plugin. If both wired and wireless transfer need to support this feature we would probably need a custom calibre driver. But I definitely don't think I'm up to the task of writing this.

> So, I'm afraid this is going to be in the realm of user patches, if somebody provides one.

Didn't knew about user patches, is there any documentation or example on how to write a userpatch? I've never touched anything lua related. Can I just copy the calibre plugin lua files into koreader/userpatches and override functions like that or are there any constraints?

**Comment by Frenzie** [comment]
Depending on what you're looking for it might be quite a bit easier to duplicate the plugin.

**Comment by pazos** [comment]
> Yeah I got that, I hoped we could at least add this feature to the calibre plugin. If both wired and wireless transfer need to support this feature we would probably need a custom calibre driver.

It should be easier than that if we shift the focus to the collections view and add a button there that let us to import from calibre metadata.

That way both wired and wireless transfers would end up in collections and the changes required in the calibre plugin are minimal: just make sure we don't discard the specific field used to mark a book as part of a collection.

I'm okay with that from the calibre plugin PoV. Not sure what @hius07 might think from the collections PoV.

> Didn't knew about user patches, is there any documentation or example on how to write a userpatch? I've never touched anything lua related. Can I just copy the calibre plugin lua files into koreader/userpatches and override functions like that or are there any constraints?

What @Frenzie says: copy calibre.koplugin to mycalibre.koplugin, change its metadata accordly and start hacking on that (make sure the original is disabled on settings)

You could also figure out how things work quickly if you do a wired transfer of a couple of books with that same template and lurk into the metadata.calibre file on the root of the usb mountpoint.

**Comment by hius07** [comment]
Currently managing collection is done manually, to avoid duplication/overwriting, all checks are handled by FileManagerCollection.
If the checks are not needed, it's rather easy:
https://github.com/koreader/koreader/blob/f0e5acfd263dc9245483d7f7627676dbd06fadbb/frontend/readcollection.lua#L291
https://github.com/koreader/koreader/blob/f0e5acfd263dc9245483d7f7627676dbd06fadbb/frontend/readcollection.lua#L124
