### ISSUE TITLE
KOReader is dereferencing symbolic links when opening files

### ISSUE THREAD

**Issue by rhatto** [koreader/koreader#12624]
* KOReader version: 2024.07
* Device: Debian Bookworm on AMD64

#### Issue

* If a file is a symbolic link, KOReader opens the link target and not the link origin.
* This results in a sidecar folder named after the symbolic link destination/target, and not with the original file name as expected.
* In other words, KOReader is dereferencing the file name in case of a symlink.
* Existing sidecar folders named after the symbolic link are also being ignored.
* This is happening since KOReader version `2024.07`, and was introduced on commit d82815952ee7b9bc070b12fc3441afaf9a550473 as part of https://github.com/koreader/koreader/pull/11563.
* This impacts use cases in which files are managed through [git-annex](https://git-annex.branchable.com/).

#### Steps to reproduce

* Install KOReader `2024.07` on a fresh system (without previous reader configuration).
* Get a PDF and save it as `a.pdf`.
* Make a symbolic link: `ln -s a.pdf b.pdf`.
* Open KOReader.
* Browse `b.pdf`.
* Close `b.pdf`, or exit KOReader.

##### Debug log

[koreader.log](https://github.com/user-attachments/files/17342596/koreader.log)

#### Actual result

* Resulting sidecar/metadata folder is `a.sdr`.
* If there was an existing `b.sdr` folder (created with a previous KOReader version), it's just ignored.

#### Expected result

* It was expected that the sidecar folder would be `b.sdr`, as with KOReader versions prior to `2024.07`.
* Otherwise, if the actual behavior is the desired one, it would be expected at least an UI option to disable symbolic link dereferencing, so existing use cases/workflows could still work.

#### Fix / workaround

This is the proposed fix (although not sure if it introduces new issues):

* Comment [line 604 from koreader/frontend/apps/reader/readerui.lua](https://github.com/koreader/koreader/blob/85591c75ce216cde605ba2fb8abbcc4df4aabfbe/frontend/apps/reader/readerui.lua#L606):

```lua
    --file = ffiUtil.realpath(file)
```

**Comment by Frenzie** [comment]
I'd assume something slightly more complex is needed, or put another way I assume that line isn't randomly there. Can't check atm in any case.

**Comment by hius07** [comment]
As I recall, this change was done to fix a non-critical issue: some plugins (MoveToArchive? do not remember exactly) passed to ReaderUI shortened filepath, ie `.\book\book.epub` instead of `\mnt\us\book\book.epub`.
Symbolic links (erroneously) were not taken into account.
I think the change can be reverted.

In the meantime, we need some unification with filepaths handling: DocSettings doesn't do any conversion, but ReadHistory and ReadCollections do:
https://github.com/koreader/koreader/blob/85591c75ce216cde605ba2fb8abbcc4df4aabfbe/frontend/readhistory.lua#L25-L26
And FileManager does as well in some operations, for example:
https://github.com/koreader/koreader/blob/85591c75ce216cde605ba2fb8abbcc4df4aabfbe/frontend/apps/filemanager/filemanager.lua#L856-L859

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by hius07** [comment]
The line removed in https://github.com/koreader/koreader/pull/12902.
