### ISSUE TITLE
Phantom Pages

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12653]
* KOReader version: v2024.07-251
* Device: PB628

#### Issue
I attempted to go to a page, which is in a hidden flow, through a highlight in the bookmarks list and I had a crash.
I opened the Page browser and I saw that the pages (2 pages) couldn't be displayed, as you can see below.
When I tried to go to these pages by turning the pages of the book, I also had a crash.
It's the book mentioned in [this comment](https://github.com/koreader/koreader/issues/11318#issuecomment-2357915681).
However I can see the pages in a pdf program.
Any idea what's going on?

![Reader_2024-10-17_204151 (Medium)](https://github.com/user-attachments/assets/740e5700-1684-46c8-8a6f-fd69a5dfe95b)

##### `crash.log` (if applicable)
[crash 17-10-2024.log](https://github.com/user-attachments/files/17434837/crash.17-10-2024.log)

**Comment by hius07** [comment]
A bug from https://github.com/koreader/koreader/pull/11044:
https://github.com/koreader/koreader/blob/716ed1f19d0c3f49225cd12730155336435d7455/frontend/apps/reader/modules/readerhighlight.lua#L2416
It should be `self.view.highlight.saved_color`.

Not reported yet, because nobody had multipage highlight in pdf.
