### ISSUE TITLE
Cancel the pop-up window after clicking "wifi connection"

### ISSUE THREAD

**Issue by Huahddd** [koreader/koreader#12719]
**Does your feature request involve difficulty completing a task? Please describe.**
After clicking on wifi connection, an annoying window appears, sometimes it lasts for a long time.

**Describe the solution you'd like**
Is it possible to cancel this pop-up window?

**Describe alternatives you've considered**
When I turn on the WiFi function, KoReader will automatically connect to WiFi for you. Is it possible to turn on the WiFi function but not connect to WiFi (like the WiFi function of Kobo and Kindle)?

**Comment by Bre-Mue** [comment]
I see this is marked as unable to fix, saying the autoconnect in the background must happen 
> A long-press will display the scan result, but nothing will ever prevent wpa_supplicant from doing its auto-connect in the background, so, no, not really.

but what about the popup issue? 

Is there a way to minimize it instead of essentially taking over the device? (Icon/dialogue box i can close/etc?)

I keep it online due to progress sync but it basically locks up my kobo and sometimes causes it to have extreme delays/freeze when I go to read offline. Why can't it just not connect and try again later while I read?

**Comment by shuvashish76** [comment]
@Frenzie Duplicate of #13518
@Bre-Mue as workaround see my comment: https://github.com/koreader/koreader/issues/11098#issuecomment-4200988167
