### ISSUE TITLE
links are not working in .pdf file

### ISSUE THREAD

**Issue by user-aug-2-2024** [koreader/koreader#12755]
* android 2024.07
* tap **IBGE, 2023** in text Indigenous or yellow (IBGE, 2023). on page 9
* it doesnt jump to reference
* all reference links in text are not working
* [.pdf file issue](https://github.com/user-attachments/files/17832970/10.1111_jlca.12676.pdf)

**Comment by Frenzie** [comment]
I can't confirm in 2024.11 and the reference links work, including that one, though I don't think it should be any different.

**Comment by benoit-pierre** [comment]
Regarding your first example (clicking IBGE, 2023, on page 9), maybe because the link target is on the same page, the jump (testing on master) can be inconsistent: in continuous page mode, zoom to width:
- when the previous page is partially shown, clicking on the link jumps at the beginning of page 9
- but when the view is at the start of page 9, clicking scrolls the top of the view to just before the target (showing part of the next page)

**Comment by benoit-pierre** [comment]
And in non-continuous mode:
* when the view is at the beginning of the page, clicking scrolls to align the bottom of the view with the bottom of the page
* and when already showing the bottom of the page, nothing happen

**Comment by Frenzie** [comment]
That feature doesn't work in PDF for now.
