### ISSUE TITLE
KOReader 2024.11 freezes on the Tolinos

### ISSUE THREAD

**Issue by BurkSchu** [koreader/koreader#12769]
* KOReader version: 2024.11
* Device: Tolino Epos 2

#### Issue

After starting KOReader 2024.11 I can't do anything on the Tolino  Epos 2, the reader only reacts to the switch-off button.

#### Steps to reproduce
Start KOReader 2024.11 on the Tolino Epos 2

##### `crash.log` (if applicable)
I have no crash log

**Comment by Frenzie** [comment]
Pinging @hugleo  https://github.com/koreader/android-luajit-launcher/pull/521

**Comment by hugleo** [comment]
Maybe TOLINO_EPOS2 light driver belongs to tolinoroot after all? https://github.com/koreader/koreader/issues/12706
But can be something else since is not crashing for  https://github.com/koreader/koreader/issues/12706 and the changes https://github.com/koreader/android-luajit-launcher/pull/521 was already in place.

**Comment by pazos** [comment]
> Maybe TOLINO_EPOS2 light driver belongs to tolinoroot after all?

Nope. Pinging @benoit-pierre because I think we overlooked this case on the DeviceInfo refactor.

Before the refactor the device was both `TOLINO` and `TOLINO_EPOS2`. The former had assigned a eink driver (which no longer is asigned based on this ticket). The later had assigned a lights driver.

It should be a matter of adding all `TOLINO_`'s its own eink driver (the same as TOLINO).

So new tolinos, with custom light drivers will need to be added to the eink factory too. Because if they don't they would drop its eink capabilities :/

**Comment by pazos** [comment]
All tolinos with a custom light driver are affected on 2024.11 :)

**Comment by benoit-pierre** [comment]
So:
```diff
 app/src/main/java/org/koreader/launcher/device/EPDFactory.kt | 1 +
 1 file changed, 1 insertion(+)

diff --git i/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt w/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
index 57e4a7c..ec8b3cc 100644
--- i/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
+++ w/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
@@ -78,6 +78,7 @@ object EPDFactory {
                 DeviceInfo.Id.ONYX_JDREAD,
                 DeviceInfo.Id.RIDI_PAPER_3,
                 DeviceInfo.Id.TOLINO,
+                DeviceInfo.Id.TOLINO_EPOS2,
                 -> {
                     logController("Tolino/NTX")
                     TolinoEPDController()
```
And so on?

**Comment by pazos** [comment]
yup, all of them.

The problem IMHO is

> So new tolinos with custom light drivers will need to be added to the eink factory too. Because if they don't they would drop its eink capabilities :/

Needs to be done for each new device. A bit of nonsense. I can live with it. I would love to avoid it, nonetheless :)

**Comment by BurkSchu** [comment]
The newest nightly version koreader-android-arm-v2024.11-15-gc124425ac_2024-11-22.apk does work!

**Comment by pazos** [comment]
> I have Tolino Vision 6.
> 
> No freezes. But brightness is not adjustable.

Quite true. The devices that crash on release 2024.11 are the ones with adjustable warmth.

Tolinos without custom drivers work just fine.

**Comment by hugleo** [comment]
> 2024.11 also Freezes on Tolino Vision 3 with Firmware 16.2.x . (One to add to the list, I guess.)

report drivers that work here: https://github.com/koreader/koreader/issues/8482
