### ISSUE TITLE
Links in .mobi documents do not work at all. Links in .epub works but are not underlined

### ISSUE THREAD

**Issue by ironschloong** [koreader/koreader#12775]
* KOReader version: 2024.07
* Device: Kindle Oasis 2

#### Issue 
Links do not work at all in .mobi documents. Links that are available on the default kindle reader do not appear and does nothing when tapped. The table of contents is also not available. The option "Tap to follow link" is activated.
Links in .epub documents work but are not underlined. Normally on the default reader they are underlined. Table of contents is available.

#### Steps to reproduce
Open any .mobi document with links in KOReader
Open any .epub document with links in KOReader
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by poire-z** [comment]
> Links do not work at all in .mobi documents

.mobi are not really supported or cared for. The engine may open and parse .mobi books, but we don't really know and never really cared about how stuff happens, what works and what doesn't. .mobi is a thing of the past, and versions of books in another format are probably available.

> Links in .epub documents work but are not underlined. Normally on the default reader they are underlined. Table of contents is available.

In *all* EPUBs ?!
We follow the publisher CSS styling of books. If they are not underlined in _some_ books, it's probably because the epub CSS says `text-decoration:none` which overrides our default of `text-decoration: underline`.
You can force `text-decoration: underline` back with our style tweak:
![image](https://github.com/user-attachments/assets/c2197abf-27be-41a5-8df6-a9c591415b31)

**Comment by ironschloong** [comment]
I guess I will convert my books to Epub then. Thank you!
