### ISSUE TITLE
Cloud storage / WebDAV: folder is invisible if it has the same name as the current folder

### ISSUE THREAD

**Issue by BrendanL79** [koreader/koreader#12783]
* KOReader version: 2024.11
* Device: Kobo Libra Colour

#### Issue

When browsing a WebDAV cloud storage, if the current folder contains a folder with the same name as the current folder, that folder does not appear. The invisible folder can be browsed by setting the starting folder in the storage config, but of course this means any parents or siblings of the folder become inaccessible.

#### Steps to reproduce
Set up a WebDAV storage with the following folders:
/a 
/a/a
/a/b
/a/c

Set up the storage in KOreader and browse to "/a" .

Observe that only "b" and "c" appear to be present.

NOTE: this may happen with other storage types (FTP and Dropbox) but I did not test them.

##### `crash.log` (if applicable)
N/A

**Comment by hius07** [comment]
FTP and Dropbox not affected.

**Comment by mergen3107** [comment]
I got help from @NiLuJe back then

**Comment by BrendanL79** [comment]
I can take a crack at fixing it - I've always wanted to learn WebDAV and Lua 😊

**Comment by hius07** [comment]
Sure. As far as I can see, this string is incorrect
https://github.com/koreader/koreader/blob/c124425ac3d66b4d90ee0cffe40f0d667290e40a/frontend/apps/cloudstorage/webdavapi.lua#L107
because the folder is not added to the list
https://github.com/koreader/koreader/blob/c124425ac3d66b4d90ee0cffe40f0d667290e40a/frontend/apps/cloudstorage/webdavapi.lua#L114-L120
The changes were made in the above mentioned PR.
