### ISSUE TITLE
FR: Eliminate "items per page" settings

### ISSUE THREAD

**Issue by dtcyganok** [koreader/koreader#12847]
Let's take a look

**Advantages**

1. give some flexibility to the user

**Disadvantages**

1. create additional cognitive load on the user (force the user to think about)
2. make UI more complex (additional menu items, additional value pickers)
3. are not modern (give a feeling of an outdated interface)
4. increase maintenance burden (additional code)

Besides, I believe nobody uses these settings, but it's just a personal guess.
So why not use a common sense based value instead that takes into account screen metrics and device orientation?

**Comment by poire-z** [comment]
I do use it - to make sure Book information fills one page.
It may also helps people using other KVPage based widgets to get much more items if they can read it.

The fact that we use the same value in landscape mode - and didn't think it may need another choice for in landscape - is probably because most of us developers don't use landscape mode and never cared much about it.

> **Disadvantages**
> 
>     1. create additional cognitive load on the user (force the user to think about)
>     2. make UI more complex (additional menu items, additional value pickers)
>     4. increase maintenance burden (additional code)

If you start with that, you're going to create a lot of FRs :) better start investigating another app :)

**Comment by Frenzie** [comment]
I think it would be more helpful to open actionable bug reports for specific issues with landscape than to hide it underneath an unrelated difference of opinion.

> So why not use a common sense based value instead that takes into account screen metrics and device orientation?

That simply describes the situation as is, imho.

**Comment by dtcyganok** [comment]
> hide it underneath an unrelated difference of opinion

I didn't hide anything. I suggested improvement

I didn't see any justification of the rejection... It's really motivating :/ Way to go...

**Comment by poire-z** [comment]
> It's really motivating :/ Way to go...

If it can slow down your motivation to opening FRs, that's indeed the way to go :)

You opened https://github.com/koreader/koreader/issues/12817#issuecomment-2509385995, then #12838, then now #12847 about something totally related (KeyValuePage font size, auto or fixed sizing, behaviour in landscape). This spreading of informations, justifications and opinions is not something that help and not the way to go, it feels we and you will just be just repeating ourselves.

**Comment by pazos** [comment]
> I didn't see any justification of the rejection... It's really motivating :/ Way to go...

You might be new to collaborative software development. You might also be new tothe program. We take the burst of feature requests and bug reports as a sign of your love for the program and understand you're trying to improve it.

Please try to focus on specific bug reports, like https://github.com/koreader/koreader/issues/12841, which might lead to actions. There's plenty of other things you might want to do, like improve documentation, translations...

Everybody here started like that, focusing on little things. Not trying to change the world the first week.

While you think you're helping with this PR we just perceive a low efort "I don't like it, here's something vague, lets implement it, why not?". That's a slap in the face.

If you plan to contribute code (or documentation or translations or..) please start small. If you want to contribute ideas, sketches... please **also stay small**.

As for the justification for the rejection:

You were rejected by a maintainer (well, you were rejected by three, read the clues).

Rejections are not final. The label isn't meant to be harsh. Is meant to be informative. Having rejected issues might help for users that do some research before opening tickets in order to prevent duplicates. 

When I mean rejections are not final I mean we're humans and everything can change. But we don't support feature request based on user ranting.

**Comment by Frenzie** [comment]
The current default is perfect, yet you seem to be unhappy with it. That's the justification in a nutshell. ;-)

> I didn't hide anything. I suggested improvement

Hide is a bit tongue in cheek, but improving landscape doesn't entail anything else. I didn't find out until the final word in the OP what the actual issue is.

**Comment by dtcyganok** [comment]
@Frenzie It's not a bug report, it's a FR. The landscape problems are just a subproduct.

@poire-z  Some misunderstood have taken a place. I didn't mean some relation to the previous topics. Those relations exist in a developer mind only. Things like `KeyValuePage` are hidden to me.

@pazos I assume your community have some rules by some reasons
> Not trying to change the world the first week.
> please also stay small.

Seriously? No, thanks. I perceive this as "you're nobody here, you're too small to make such suggestions"
I'm not going to prove my usefulness to anyone. I'd rather create a fork.
So feel free to close my other suggestions, if they are "too big" and bother you so much.

P.S. today is my last day of 'low effort' contribution to koreader

**Comment by pazos** [comment]
> P.S. today is my last day of 'low effort' contribution to koreader

It's your choice.

> So feel free to close my other suggestions, if they are "too big" and bother you so much.

Yeps, that's one of the ways I'm contributing. Closing, reopening, linking tickets. I'll do what I consider and expect feedback when I do something wrong, because I do ;) Pair reviewing is wonderful. 

In the future when approaching developers about the software they do on they free time remind yourself they're not there to fullfit your needs. Be nice and follow their recommendations. 

We're here for fun. Nobody wants a passive-agressive drama act as part of their hobbies.

**Comment by dtcyganok** [comment]
@pazos Please leave psychoanalysis and false labels (such as "passive-agressive drama") for someone else . I am not a submissive pet. I openly say what I don't like

In the future when approaching any contributors remind yourself they're not here to fulfill their needs.

> We're here for fun.

That's exactly why I'm not going to contribute anymore

**Comment by dtcyganok** [comment]
And no offense guys, but I have strong feeling of lack of common sense in many ways...
