### ISSUE TITLE
FR: Save annotation "last update" timestamps in metadata.epub.lua

### ISSUE THREAD

**Issue by righteous-coder** [koreader/koreader#12957]
**Does your feature request involve difficulty completing a task? Please describe.**

This is more of a QoL improvement for plugin/tool developers dealing with annotations/highlights. Currently, annotations saved in metadata.epub.lua have a `datetime` field, which apparently shows the creation time (It does NOT get updated when I edit note or style on KOReader, from my testing). So as a developer, if you want to, say, synchronize annotations between multiple devices, you don't have a way to tell which device has the newest version of a specific annotation.

**Describe the solution you'd like**

I want either `datetime` to be updated upon editing, or a new field like `datetime_lastmodified` to be added.

**Describe alternatives you've considered**

I haven't any.

**Additional context**

Currently, annotations have these fields:
```
        [109] = {
            ["chapter"] = "Chapter 2",
            ["datetime"] = "2024-11-17 17:57:33",
            ["drawer"] = "underscore",
            ["page"] = "/body/DocFragment[11]/body/div/div/p[154]/span[2]/text().25",
            ["pageno"] = 54,
            ["pos0"] = "/body/DocFragment[11]/body/div/div/p[154]/span[2]/text().25",
            ["pos1"] = "/body/DocFragment[11]/body/div/div/p[154]/span[2]/text().33",
            ["text"] = "i am a super nice person",
        },
```

**Comment by hius07** [comment]
> synchronize annotations between multiple devices

How do you do this?

**Comment by hius07** [comment]
@noembryo opinion is welcome.

**Comment by righteous-coder** [comment]
Actually I'm using noembryo's KoHighlights.

And this issue is related to this: https://github.com/noembryo/KoHighlights/issues/54

**Comment by noembryo** [comment]
I think that this is the simplest solution to [this](https://github.com/noembryo/KoHighlights/issues/54).
KOHighlights checks for the `text` of the annotation and then if it's the same checks for the datetime.
If it's also the same, assumes that the annotation doesn't need to sync since it's identical.
But I was wrong, hence the FR..

**Comment by hius07** [comment]
I do not see any drawbacks to update the annotation datetime field on editing (note, style, boundaries...).
@poire-z ? @ichnilatis-gr ?

**Comment by ichnilatis-gr** [comment]
Interesting! I hadn't thought of that until now. The truth is that I don't use notes too much, but it would be helpful if they were updated.

**Comment by poire-z** [comment]
> I do not see any drawbacks to update the annotation datetime field on editing (note, style, boundaries...).

The drawback would be that we lose the info about the time when we created that highlight and first read that page.
May be it's bearable to have the date changed if I add a note or correct the text, but if I just change the style or color, having it suddenly get its datetime update to now feels like a bug.

I'm also not fond of such a suggestion :) Let's change the meaning because somebody requested it. Somebody else will later come in and complain the datetime changes and it should not :)

Ideally, we should store them as 2 different keys. (In the past when we discussed annotations, I was advocating to store as much stuff in it, even if we don't use it - while you (as often :)) want to just have what we actually use.

You actually suggested at https://github.com/koreader/koreader/issues/5794#issuecomment-943004179 to have - which I think would have been the better choice:
> (1.6) `date_cr`, `date_ch` - dates of the annotation creation and last change to have

So, I think a new field `datetime_updated` would be a better and versatile solution.

**Comment by noembryo** [comment]
Another suggestion if I may.
If `datetime_updated` is added, is it possible to initially have the same value as `datetime`?
That way, I can use it instead of `datetime` on all checks.

**Comment by Frenzie** [comment]
> If datetime_updated is added, is it possible to initially have the same value as datetime?

Imo that's clearly the correct behavior.

**Comment by hius07** [comment]
Thanks, I agree.
