### ISSUE TITLE
FR: mathify selection or documents 

### ISSUE THREAD

**Issue by hrdl-github** [koreader/koreader#12972]
I read a fair amount of articles extracted from websites using Mozilla's readable using third-party CLI tools. This often results in math notation being copied as latex without extra annotation or alt image. 

I'd like KOReader to replace latex notation with rendered images of selections upon request in HTML and possibly epub documents. If this works well this could be done automatically in a pre-document basis 

Ideally I'd fix this at the source so the contents are also rendered in my regular browser, chawan.

**Comment by poire-z** [comment]
I think it is not KOReader' job to do that.
The Latext notation you see is plain text in the HTML content (unless it's inside some HTML tag we don't support and process as some dummy inline tag?), there's no reason for KOReader/crengine to try to guess if that text is something else than text...
It should be done by the tool that generates these HTML/EPUB documents.
We support MathML, so may be there's something to convert these math notations (or just let them be if they are originally in) to MathML instead of Latext.

**Comment by Frenzie** [comment]
It's better convert it to SVG at the time of conversion.
