### ISSUE TITLE
Startpage/homescreen for koreader

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1313]
I was thinking about how a homescreen or startpage for koreader would look like. And here is my first idea:

![koreader-startpage-search](https://cloud.githubusercontent.com/assets/1377943/5240001/e6645072-78f7-11e4-9a7c-2ba1fbf708b0.png)

There are several elements to it:
- The panel, which shows the indicator for battery and maybe wifi (if the resource problem is fixed), the date and/or clock and the settings gear, which opens the system wide settings (like it does now).

![koreader-startpage-search-top-panel](https://cloud.githubusercontent.com/assets/1377943/5240025/32de2e18-78f9-11e4-840b-fe00c6431c6d.png)
- The search, which would combine both the file search and the calibre catalogue search that we now have in the fourth tab of the filemanager.

![koreader-startpage-search-search](https://cloud.githubusercontent.com/assets/1377943/5240027/556034d6-78f9-11e4-9e5f-29cd6a871bf4.png)
- A list with the history of documents read, which is basically a more polished "History" which now is in the pokeball tab. It shows document title (not file name) and author, or file name if no meta data available.

![koreader-startpage-search-recent2](https://cloud.githubusercontent.com/assets/1377943/5240123/5e3a9bb6-78fc-11e4-8858-3aae40322f90.png)
-  Then there is the shortcut to the bookmark index, which is especially helpful if you have non-fiction books, if you are writing a review or just want to jump to a bookmark in another book.

![koreader-startpage-search-bookmark-index](https://cloud.githubusercontent.com/assets/1377943/5240034/bdb0f250-78f9-11e4-99a0-c837789b5289.png)
- And then there is the bottom panel which has the shortcuts to the a flat book list or library, the filemanager and apps.
  Apps would be the place where i would put the OPDS catalog and other applications, but more on that later.

![koreader-startpage-search-panel](https://cloud.githubusercontent.com/assets/1377943/5240054/c4e4b592-78fa-11e4-9a7b-f9753ff333fa.png)

I would like to hear your thoughts about the mockup and explanation about which widgets could be used to build certain elements.

(I will need weeks until i fully understand how the widgets work and how the UI is organised).

**Comment by ersi-dnd** [comment]
Prior to working on a fancy homescreen, how about some more startup options? 

Right now Koreader can be set to open at startup either the file manager (folder view) or the last opened book. At the same time, Koreader contains a History list which could also make sense as a startup option. 

To make History list as a sensible startup option, it should display differently. Instead of having frames around it, it should display just like the file manager, only filtered/sorted by last viewed files, regardless of folder location.

Another possible startup option that some may want - files sorted by last added date. Again regardless of folder location. 

To sort by metadata (things other than filenames), there should be a capability to edit Title and Author. Files often enough don't come with sensible metadata (unless you actually pay for an e-book). Title and Author have to be edited to make sensible. (I suspect that Calibre has this function, but I am not using Calibre. Perhaps I should.)

**Comment by ersi-dnd** [comment]
Apparently, my suggestions could be implemented within the context of the File Manager. So, my suggestions would be just options to open up the File Manager in specific determined views. 

Another sensible option would be to open up the File Manager in the folder where it last left off :)

**Comment by houqp** [comment]
@ersi-dnd , these are very useful features. That said, I am afraid we don't have enough resources to work on this right now. I will be happy to accept patches that implement those features though.

**Comment by tigran123** [comment]
I think letting Koreader have anything to do with metadata is a very bad idea because it is not scalable. For example, nobody in the right mind would use Nickel (Kobo's builtin proprietary software) simply because it will never complete the "Processing content..." stage of building its internal metadata database for a reasonably large collection (say 50,000 books on a 128GB card).

The second reason is that metadata in 80% of the cases contains garbage --- I am talking only about printed books (pdf/djvu), not ebooks. Yes, most of ebooks contain valid metadata, but books do not and I personally only use Koreader for printed books and never for ebooks (for ebooks  a superior option, imho, is to use CoolReader). And whenever I give away a device to a friend (nowadays Kobo Mini are my favourite option --- as they cost only £18 plus £15 for 64GB micro sd plus £1.99 for a case!) with Koreader and CoolReader pre-installed I always tell the user to remember that Koreader is only for PDF and DjVu and CoolReader is for everything else (except something exotic like Word documents for which one may have to use Koreader, but I never tried to read such exotic stuff).

**Comment by houqp** [comment]
@tigran123 like @hwhw said, earlier, we can make the home screen optional so people can still use filemamanger as default based on their own preference. 

One of the biggest problem with nickel and kindle is they use sqlite for indexing, which is known for slowness on large tables. We should be able to get way better performance by switching to key value storage like leveldb/rocksdb. That said, for large collections, it's better to build the index with PC on the first run then sync it to KOReader.

> about printed books (pdf/djvu), not ebooks. Yes, most ebooks contain valid metadata, but books do not and I personally only use Koreader for printed books and never for ebooks (for ebooks a superior option, imho, is to use CoolReader).

Interesting, is it because of the difference in UI? @chrox a and @frankyifei  have made many improvements and bug fixes to our own fork of CREngine. We sent those patches upstream, but looks like the author does not have time to review them.

**Comment by tigran123** [comment]
The problem with indexing metadata lies, imho, not in the use of sqlite or any other database, but with the inherent impossibility of obtaining the data as the PDF file itself has to be read and the relevant objects found. When you type `pdfinfo file.pdf` notice that it takes ages to extract the data (about 0.024s on a very fast machine). A typical eInk device is at least 10 times slower, so it probably would take 0.2s per file. Now multiply this by 20,000 and you get 4000 seconds, that is more than 1 hour.

As for Koreader vs CoolReader question --- no, it is not because of UI, but for some unknown reason CoolReader seems to renger the glyphs slightly better (for some fonts that I use, like Arno Pro and Academy). But I know this should be impossible as I was told by Sergey Vlasov just a few days ago that crengine used by Koreader is already ahead of the one used by CoolReader and in fact Sergey is contemplating to upgrade CoolReader to use Koreader's fixed crengine to benefit from all the fixes you have done.

Maybe I should do a fair experiment, that is set up both Koreader and CoolReader to use exactly the same fonts on exactly the same book and make screenshots in both and then carefully look at the screenshots on a computer. That would be better than just some "anecdotal" evidence of CoolReader's supposed "better rendering" :)

**Comment by houqp** [comment]
> The problem with indexing metadata lies, imho, not in the use of sqlite or any other database, but with the inherent impossibility of obtaining the data fast as the PDF file itself has to be read and the relevant objects found. When you type pdfinfo file.pdf notice that it takes ages to extract the data (about 0.024s on a very fast machine). A typical eInk device is at least 10 times slower, so it probably would take 0.2s per file. Now multiply this by 20,000 and you get 4000 seconds, that is more than 1 hour.

Ha, I see why are you so against indexing now ;) I agree it's a bad idea to parse the metadata inside the document. I wouldn't be surprised if the parsing process is even slower in other formats. By metadata, I was mainly referring to our own stuff, like tags for books, reviews, collections etc. I think indexing document just by filename should be enough.

> As for Koreader vs CoolReader question --- no, it is not because of UI, but for some unknown reason CoolReader seems to renger the glyphs slightly better (for some fonts that I use, like Arno Pro and Academy). But I know this should be impossible as I was told by Sergey Vlasov just a few days ago that crengine used by Koreader is already ahead of the one used by CoolReader and in fact Sergey is contemplating to upgrade CoolReader to use Koreader's fixed crengine to benefit from all the fixes you have done.

Maybe it's because we are using a newer version of freetype. The font rendering issue is definitely something we should investigate. I have created an issue for tracking purpose.

**Comment by tigran123** [comment]
And I decided to give Koreader a fair trial and tried to open the file which CoolReader reads perfectly fine (with all the formulas etc) --- Albert Messiah, Quantum Mechanics, 2014 (2 vols in 1, Dover Pubs) in ePub format and it failed to open it, i.e. crashed and the `crash.log` says just one line `Floating point exception`. I'll open an issue for this now.

**Comment by houqp** [comment]
@tigran123 Will you be able to upload the font faces (Arno Pro and Academy) you mentioned in the previous comment online for us to access?

**Comment by lightonflux** [comment]
5 years later and the functionality of koreader is too much for this homepage. The other mockups are much better. Therefore i close this issue. But feel free to reference it in future discussions.
