### ISSUE TITLE
Standby timeout is wanted.

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1356]
__Conclusion of my questions about fast battery drainage. See [here](https://github.com/koreader/koreader/issues/1356#issuecomment-66427025).__

Lately I have run into a completely unresponsive device only to find out later it ran totally out of juice. The device is new (3 weeks old) and I am only experiencing this for the last week or so.

_Does anyone else have this problem, too?_

_Could it be related to putting the device on standby in koreader?_

When I recharge the device jumps rather fast to 49% (10 minutes) and then takes about an hour to get to 87%. Now it charges at 1%/3minutes. This seems a rather unrealistic way of charging.

_Does anyone else see this behaviour, too?_

_What could be wrong?_

**Comment by Frenzie** [comment]
@chrox [suggested](https://github.com/koreader/koreader/issues/1565#issuecomment-113902786) this is only needed on Kobo?

**Comment by chrox** [comment]
Yes, none of Kindle, Pocketbook or Android devices has this problem because on those platforms the power management service will handle input timeout and suspend the whole system for both native programs and thirdparty programs. But I suspect on Kobo the service is bundled with nickle and if it's killed like in koreader there will be no power management at all.

**Comment by cenobitic** [comment]
Sorry to ask again, but I did not get it. Is it possible to provide a suspend setting extra for Kobo devices? Or is it not possible as this kind of service is too deep down to the kernel?

**Comment by houqp** [comment]
fixed by #1917
