### ISSUE TITLE
About selecting a word

### ISSUE THREAD

**Issue by Juddd** [koreader/koreader#1363]
submit to a uncomfortable experience.“Sort[list]”,for example,while I try to elect the “Sort”,the whole string to be included.Because there's no space between “t” and “[”,could you make it more smart?

**Comment by chrox** [comment]
Actually your argument is not valid. How could the program know that you want to select the word "Sort" other than the following part "list"? Since we cannot make arbitrary decision on which part of the string is the word the user wants we will feed the whole sting to further process.

Your problem can be solved by manually input a word to search or dict look-up.

**Comment by Juddd** [comment]
I think it is a single problem rather than you cannot fix it,because none a word have notation such as "[",so distinguishing the "sort" from "list" is a pice of cake.Am i right about this?
