### ISSUE TITLE
KOBO_TOUCH_MIRRORED = true doesnt work on my old Kobo Touch

### ISSUE THREAD

**Issue by ottischwenk** [koreader/koreader#1374]
I have an old Kobo Touch with fixed Flash and Koreader cannot be handled because of touch problem (turned to right)
I tried KOBO_TOUCH_MIRRORED = true in defaults.lua but no change in behavior.

Kobo Version 3.11
Koreader koreader-kobo-arm-linux-gnueabihf-v2014.11-13-gc041e7c

Koreader stable works correct in this manner

Regards, Werner

**Comment by chrox** [comment]
I don't think any [change](https://github.com/koreader/koreader/compare/v2014.11-stable...v2014.12.22-nightly) between koreader-kobo-arm-linux-gnueabihf-v2014.11-13-gc041e7c and koreader-kobo-arm-linux-gnueabihf-v2014.11 could affect the behavior of KOBO_TOUCH_MIRRORED in defaults.lua. And since there is no further confirmation from other users I would close this now. Probably you could check the consistency of the device disk.
