### ISSUE TITLE
Create dictionary/font resources that comply with copyright law

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1420]
Wikipedia:

> OpenDyslexic is a free typeface/font designed to mitigate some of the common reading errors caused by [dyslexia](https://en.wikipedia.org/wiki/Dyslexia). 

It has a compatible license and is widely used in schools or even other eReader software like nickel.

http://opendyslexic.org/

I think it would be handy for some people if they don't have to manually load it on to the device.

**Comment by chrox** [comment]
The reason to include OpenDyslexic font in koreader release package is not sufficient. Koreader release package has already contained a basic set of font files that cover a good portion of written characters used in modern world. If the buildin fonts don't satisfy special use, users can also copy TTF font files into koreader's fonts directory and select the fonts in koreader's menu.

**Comment by Markismus** [comment]
I think this is part of a more general problem: How to make available and install dictionaries and fonts in a more streamlined way. 

In #622 I already made an issue of the problem of installing those on android. Most people don't have root access, so an installation would be rather nice. 

In #323 I mentioned the distribution of custom made dictionaries. Although it seems quite straigth forward to install those on ereaders, people on mobileread keep getting into a mess of problems. 
Simply releasing packages with working dictionaries and Tesseract data would at least give them a working dictionary system from which to proceed.

For this I would suggest a separate subproject: koreader/fonts, koreader/dictionaries. It would contain the installation releases for the different platforms. Installation should be analogous to the koreader installation, so that no new skills are needed nor much time to find out how to make it work.

So how would this work with releases? Should they show up on the koreader-release list? Does it have its own? Than we should link to it from the wiki.

I am quite willing to prepare the kobo files. Would anyone be interested in helping with kindle or android? 

Any obvious problems I failed to see?

**Comment by chrox** [comment]
How about showing links of dictionaries and fonts and let the users download them directly in koreader if they would like to add them? It's technically feasible but we should make sure all resources comply with copyright law and usually the last thing is more difficult.

**Comment by Markismus** [comment]
Sounds rather nice. Could we combine it with a koreader github repository, so that the links remain available at least for as long koreader remains available? It would probably be easier than finding out how to install the files in all the different devices.

**Comment by houqp** [comment]
+1 on dedicated repo for building extra font/dictionary release.

**Comment by Markismus** [comment]
Looking at dictionaries collected on mobilereads they only put down a disclaimer ([see here](http://www.mobileread.com/forums/showthread.php?t=16419)):

>This work is assumed to be in the Life+70 public domain OR the copyright holder has given specific permission for distribution. Copyright laws differ throughout the world, and it may still be under copyright in some countries. Before downloading, please check your country's copyright laws. If the book is under copyright in your country, do not download or redistribute this work.
>
>To report a copyright violation you can [contact us here](http://www.mobileread.com/forums/report.php?p=118728).

So instead of complying, we assume compliance and take it down when someone claims it isn't. Seems less work. Would this be acceptable to you @chrox?

**Comment by chrox** [comment]
Sorry for the late reply I was on vacation last week. And I'm pretty OK with that. I hate copyright laws of any form so much that I wish someday someone could really break them.

**Comment by Frenzie** [comment]
Here's a list of dictionaries with a free license. I'll add the link to the wiki.

https://tuxor1337.github.io/firedict/dictionaries.html

**Comment by nguha** [comment]
@Frenzie That FireDict link is dead, but the same content is now available at https://tuxor1337.frama.io/firedict/dictionaries.html Could you please update it on the wiki?

Here are a few more sources for freely licensed StarDict dictionaries:
- [Dictionary info](http://www.dictinfo.com/) - English Wiktionary exports by Joel Korhonen
- [StarDict Dictionaries -- 星际译王词库 词典下载](http://download.huzheng.org) - Exports in a multitude of languages from multiple sources (dict.org, freedict.de, mova.org) by Hu Zheng
- [libredict.org](http://www.libredict.org/en/) - Russian Wiktionary exports by Nikolay Shaplov
- [Michal Čihař - Dictionaries for StarDict](https://cihar.com/software/slovnik/) - Czech dictionaries by Michal Čihař

It would be nice to have it all listed on the wiki.

Also, here are a couple more conversion tools that I found:
- [wiktionary-convert](https://github.com/korhoj/wiktionary-convert/)
- [wiktionary-export](https://github.com/dhyannataraj/wiktionary-export)

**Comment by Frenzie** [comment]
I'll close this issue because I added a dictionary download option to v2019.01 (#3176).
