### ISSUE TITLE
Kobo Aura - change screen light in suspend

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1429]
When the device is suspended i can still turn on/off the light via the hardware button. Is that expected behavior?

Running the current nightly on a Kobo Aura.

Edit: It only works when the device goes into sleep, so a few seconds after pressing the lock button.

**Comment by chrox** [comment]
Kobo seems have no system-wide suspending mechanism that runs as a background service so that the main reader program doesn't need to handle the lower level power management by itself. The drawback of the design is that the whole system is not extensible. It requires every other third party applications implement their own power management facilities which at most time is discouraging and ridiculous. You won't run into this problem when using Koreader for Kindle, pocketbook and Android.

**Comment by chrox** [comment]
The only reason is that the device is not really suspended. Probably the https://github.com/koreader/koreader/blob/master/platform/kobo/suspend.sh does not work on your device.

**Comment by lightonflux** [comment]
I think it does work, but it takes around 30sec. Then the device is in proper sleep (i think) and doesn't react to any input, except power and reset.

**Comment by chrox** [comment]
It seems the OP has already solved this problem by making the device calm down for half a minute. Closing this now.
