### ISSUE TITLE
Back from links - command in menu instead of swipe 'east'

### ISSUE THREAD

**Issue by elvenic** [koreader/koreader#1443]
Currently, when you jump to a link, the way to go back to the link origin is to swipe back ('east', from rignt to left) - and the Koreader will jump not to the prev.page, but to link origin. At least that I've got from reading ReaderLink.lua source. 

But that is useful only for links like to short footnotes, where, after reading the footnote, you most likely want to return back to the link origin.

I think it is useless for links like in the table of contents, because after you jump to a chapter, swipe several pages 'west' as you read the chapter, then want to go back one page in this chapter by swiping 'east', you will be suddenly thrown back to the table of contents because ReaderLink rememberes that you jumped to the capter through the link and interpretes first swipe 'east' as command to go to the link origin (table of contents in our case).

I personally think that better design choice would be, instead of using first 'east' swipe to go back to the link origin, to have separete command 'Back' in the menu, or something similar, to go back. For example, the CoolReader implements jumping back this way.

**Comment by Markismus** [comment]
I think you address two problems:

1. Hard to find out what gestures do. I was thinking in the direction of #1371: At least bundle the gestures wiki with koreader and make them accessible via the help menu.

2. Link handling. I rather think along the lines of a bookmark screen toggle. If you jump from a link, then on screen a jump back icon appears. If you clink it it disappears, if you turn 3 pages forward it disappears, if you swipe east while the icon exists you jump back. 
This keeps the rather graceful handling of links, while signaling it is in effect and allowing it to be disabled.

**Comment by elvenic** [comment]
Marksimus, 

Link handling as you described - with icon that disappears on any new page change - would be better then what we have now. But still it would not work if: a) I really want to go back after I've visited several pages (for example, link to a note or comment that is longer then one page, and that, of course depends on the book font size/page margins/etc.), b) if after the first jump I see another link and jump to it (recursive jumping?) and then want to go back two links.

Also, keeping an icon on the page visible while you read the page, can be aesthetically not pleasing to some people
 
I still think that the best approach would be for the koreader to keep a stack of link jump locations where on jump to link, the prev. location is pushed to it's top. A location would be popped from it's top only on the action 'jump back to link origin'. Normal 'go to next/prev page' actions would not change the stack. And, of course, that would require to have a 'jump back' command available all the time (or, at least, when the stack is not empty). For example, through the menu. 

And, from my reading of ReaderLink.lua file, I think koreader already maintains a stack of link jumps - if my understanding of lua 'tables' is correct.

Lua as a language seems to be nice enough, but I don't have any knowledge of it other then what I deduced from 15 minutes of looking at the ReaderLink.lua code. And the user interface handling looks quite intimidating. Otherwise I may have thought that I would be able to provide a patch for this feature myself :)

**Comment by Biep** [comment]
But having a gesture would be nice, as continually having to open the menu when reading a footnote-ridden text is bothersome.  What about a bottom-right-to-top-left swipe, or a two-finger left swipe (for ltr text)?

**Comment by Frenzie** [comment]
@Biep You can use the "swipe to go back setting" but I'd recommend using one of the other newer footnote related settings instead.

Settings → Links → Show footnotes in popup looks like this (left a page with a footnote, right what happens when tapping it):

<img src=https://user-images.githubusercontent.com/202757/52880602-abc6cf80-3162-11e9-9d6e-e1cd4ddcf59a.png width=40%><img src=https://user-images.githubusercontent.com/202757/52880603-abc6cf80-3162-11e9-9e00-bb89cbd52e71.png width=40%>

But I personally prefer Document → Style tweaks → Miscellaneous → In-page footnotes. That looks like this:
![screenshot_2019-02-15_20-47-27](https://user-images.githubusercontent.com/202757/52880699-ee88a780-3162-11e9-9326-864179473b55.png)

Pinging @AlanSP1 since I don't think this is documented in the wiki yet? I might be wrong. Cross-ref to #4102.

**Comment by AlanSP1** [comment]
We had it, but I added this additional info (showing footnote in popup after tapping on footnote link).

https://github.com/koreader/koreader/wiki/In-page-footnotes

**Comment by Biep** [comment]
Aha - I didn't know about those settings, but now see they exist for Epubs.  Really nice!  I very much appreciate all the hard and thoughtful work you all are putting into KOReader.

But I mostly read scientific pdfs, and there the footnote and reference indicators are simply changed into links - and the settings in the document menu you show aren't there when reading pdfs.
Also - often nineteen out of twenty footnotes are just references, and when I jump to a footnote I read ahead to see when the next _interesting_ footnote is.  One cannot do that with pop-up footnotes.

So a gesture to jump back the last link would still be very much appreciated.  Also, would it be a good idea to allow the user to associate taps and gestures actions - the way hotkeys can be in many programs?

**Comment by Frenzie** [comment]
Like I said, there's a "swipe to go back" setting. ;-)

> Also, would it be a good idea to allow the user to associate taps and gestures actions - the way hotkeys can be in many programs?

Of course. It's also very difficult.

**Comment by Biep** [comment]
"Like I said, there's a "swipe to go back" setting. ;-)"

Yes - but that would interfere with swiping to go to the previous page, as per the original issue, wouldn't it?  Or am I missing something?

**Comment by Biep** [comment]
"Of course. It's also very difficult."
Definitely not trivialising the work you all are doing - but what would be especially hard about it?  Recognising the gestures is already something done, so it would seem all that would be needed would be an extra indirection: upon receiving gesture X, look in a table which command to execute.
And of course some interface (but just Lua code editing would work for a first version) to allow the user to make changes to this table.

(I imagine gestures are along the lines: "a touch of duration in the interval [a, b] starting in region [c, d, e ,f] and ending in region [g, h, i, j]", but maybe that is vastly underestimating the issue..  Of course some gestures would be local, such as tapping a word, so that is already a complication.)

**Comment by Frenzie** [comment]
> Yes - but that would interfere with swiping to go to the previous page, as per the original issue, wouldn't it? Or am I missing something?

Yes, I don't like that gesture at all.

> so it would seem all that would be needed would be an extra indirection: upon receiving gesture X, look in a table which command to execute.

Well sure, most things that are difficult are so in the requiring time and effort sense. Anyway, this particular command should be simple enough to add to the current prototypical gesture manager if you'd like to have a go:

https://github.com/koreader/koreader/blob/5eb4fc5c2d6816bc7d936788bac65901232dccb2/frontend/apps/reader/modules/readergesture.lua

PS Please move discussion to a more appropriate issue like #4333 (although that particular one may be a duplicate).

**Comment by poire-z** [comment]
> Yes - but that would interfere with swiping to go to the previous page, as per the original issue, wouldn't it? Or am I missing something?

Just mentionning this for completness, as this won't help you if you really turn pages with swipes and never use taps:
When following links (to footnotes or internal sections), hiting a table of content entry, using the Skim to widget, original page is stored in a "location stack".
When using swipe to go back, this location stack is pop'ed, and you go the the previous remembered location. Once it is emptied, the next swipe will not move (some kind of resistance, and a popup tells you the location stack is empty). The following next swipes will behave as go to previous page.
(I use that on EPUBs, but I guess it works the same in PDFs).

**Comment by Biep** [comment]
Wait - you mean in epubs I could separate the gestures: tap being "to the previous page" and swipe meaning "back to the origin of the last jump (unless there is none, then go to previous page, unless there is none, then do nothing)"?  I hardly ever read epubs, but that would fulfil my need.
If it were possible to have the same behaviour for pdfs, that would help me enormously.  Unfortunately, with pdfs, the menu doesn't contain the option to use the swipe to jump back.

Wait!  I went to an epub and set that option, and now also see it (selected) in my pdf menu!  And it works!  Wow!

**Comment by poire-z** [comment]
(I waited!)
Well, looking at the code, the `Gear icon > Links > Swipe to go back` should show on all document formats.
And tap on left on screen to go to previous page, tap on right of screen to go to next page are the first gestures one would use, and obviously work on all documents.
Swipe left or right are just there because why not.

Tapping on a link has priority over a tap for next/prev page, and follow that link.
Other options in the `Link>` submenu allows for disabling tap on link (and use swipe nearest the link to follow link), which helps on page with many links (like Wikipedia EPUBs).

**Comment by Biep** [comment]
Beautiful!

**Comment by Biep** [comment]
I realise I want another behaviour - ideally linkable to a forward (left-to-right) swipe.
I read lots of huge pdfs, say 1000 pages text followed by 100 pages of footnotes - and of course those footnotes are not well-behaved, so KOReader doesn't recognise them as such.
My reading consists of reading a few lines, reaching an endnote, going to the menu and doing "Go to" whatever page in the footnote section I am at, reading the endnote, and swiping back (r2l) to return to my main text.  The point is: the next time I want to reference a endnote, it almost certainly is on the page I just jumped back from.  So if sweeping back is Ctrl+Z, then I want Ctrl+Y (or Shift+Ctrl+Z), or whatever "redo" is on your system.  Actually, I do **not** want to redo and go where I went the first time, because after a while the current endnote is many pages further than my original jump to the first endnote - I want to jump to the place from where I just jumped back.  The endnote I need will be on that page, or at the beginning of the next.

I am sure I am not the only one doing this dance from text to endnotes and back, so I think this is a generally useful feature: find the first endnote, jump to page 1, and then for every footnote swipe l2r to read it, and swipe r2l to return to the main text.

Am I making sense?

**Comment by Frenzie** [comment]
Could you please try to distill what part of "go back to previous location" isn't working for you? I frequently use it.

1. Click link or bookmark.
2. Read around where you ended up, go back and forth a bit.
3. Go back to previous location (i.e., back at position where you were in step 1).

I don't really understand where "redo" would come into play tbh. Are you talking about scanned facsimiles that *don't* have links (i.e., one of my primary use cases)? For that I use bookmarks.

When multiswipes are properly fixed up and packaged in the next stable, you won't even have to perform the current fairly minimal effort anymore. You can just multiswipe back to previous location (left, right) and multiswipe to latest bookmark (right, left). But I've been happily using the existing mechanism for years.

**Comment by Biep** [comment]
Indeed: pdfs with lots of footnotes that are not links.
"Go back to previous location" works fine - but it is only half of what I'd like to have.  Endnotes are a (slowly) moving target, so the next endnote is basically where I just started my jump back - so now I'd like to jump there with one sweep.  In that way my reading becomes trivial:
Sweep l2r to go to the footnote; sweep r2l to return to the text.  Repeat ad lib.

**Comment by Frenzie** [comment]
One would normally use bookmarks for that (top right corner). The rest of the process is exactly how you described it.

I suppose you could submit a PR for "maximum location" or some such, if you want.

**Comment by poire-z** [comment]
> One would normally use bookmarks for that (top right corner). 

And activate `Swipe to jump to latest bookmark` https://github.com/koreader/koreader/issues/3654#issuecomment-362256907 https://github.com/koreader/koreader/pull/3207
Holding on that menu option would give you some explanation and advices (so, check that too on the other items in the Links> submenu):

> Swipe to the left to go the most recently bookmarked page.
> This can be useful to **quickly swipe back and forth** between what you are reading and some reference page (for example notes, a map or a characters list).
> If any of the other Swipe to follow link options is enabled, this will work only when the current page contains no link.

OK, if you bookmark a lot, you may need to jump again to that footnote page to unbookmark and rebookmark it so it stays the latest bookmark.
Not a two location stacks, but good and flexible enough.

**Comment by Biep** [comment]
So every time I go to the next page of footnotes I'd have to unbookmark the old page and bookmark the new one?  That sounds like almost as much work as using the "Go to" every time..  But I'll go try it first.

**Comment by Frenzie** [comment]
You don't have to unbookmark the old page. You just have to bookmark the new one.

**Comment by Biep** [comment]
OK.  Haven't used bookmarks yet.  The bookmark is the top right dog ear?
So my request would amount to not having to set that bookmark, i.e. not having to click at the top right of every endnote page.

**Comment by Biep** [comment]
> I suppose you could submit a PR for "maximum location" or some such, if you want.
What do you mean by "maximum location"?
My idea was this: there is code that stores the origin of a jump - otherwise "jump back" would not be possible.  I'd like to jump to the origin of the last back jump (and do so by swiping l2r).

P.S.: being the neurotic person that I am, I'd still go back and unbookmark, because the existence of all those unnecessary dog ears would bother me and distract me from my studying - but that is just me.

**Comment by poire-z** [comment]
> I'd still go back and unbookmark

Just don't think about it that way, you will do it naturally:

- swipe to jump to latest bookmark: the footnote target is there, you read it normally, whether it's fully contained on that bookmarked page, or it continues on next page(s).
- swipe back to main text
- new footnote, swipe to jump to latest bookmark: you'll see that your footnote number is not there and you need to tap to go to some next page - when you realize that (and this process may become natural), you will just do:
  - tap top right corner to unbookmark that old footnote page
  - tap right area to go to next footnote page
  - tap top right corner to bookmark that new footnote page
- and you'll be fine for minutes/hours until you have to do that (now natural) 3-taps sequence again (because _Endnotes are a (slowly) moving target, so the next endnote is basically where I just started my jump back_)

> it sounds like a rather simple addition.

It may or may not be, but it will surely be many hours of work by one of us (or you :)
So please give many hours to these suggestions and workflow first :)

**Comment by Biep** [comment]
> So please give many hours to these suggestions and workflow first :)

I shall.  And please don't think I am not immensely grateful for all the hard work you all are doing - because I am!  Kudos to you all (including to you specifically for adding the swipe options)!

**Comment by Frenzie** [comment]
@poire-z It could however be made simple in a more generic way, if you could bind a gesture to a string of commands. In this case, something like `add bookmark & go back to previous location` coupled with `go to latest bookmark & remove bookmark`. (Of course this might not be the best macro to combine with genuine bookmarks, but that aside.)

A simplistic macro implementation like that might be relatively easy to patch into the gesture manager.

**Comment by poire-z** [comment]
> something like `add bookmark & go back to previous location` coupled with `go to latest bookmark & remove bookmark`. 

That's a neat idea and way to think about @Biep wish that I didn't think about :). This could be made into a checkbox (dependant of Jump to latest bookmark being enabled), and could be handled by the jump-to-latest-bookmark and go-back code to do that automatically (without even needing a gesture).

It's a bit limiting we have to use bookmarks for that, as it prevents/complicates making regular bookmarks.

So, I don't know. May be it could be made an independant option `Swipe to jump to alternage page` (but how to mark that page the first time a as being now the alternate one),  and we'd just remember orig_page or alt_page when you swipe forward or back. A bit of hidden/independant "latest bookmark". Swipe-to-go-back would just have to see if we're in that alt state to go back to orig page, or do its usual work if not.
Might be hard to explain that new option :)

(And of course, these actions could be bound to the new multiswipe gestures as an alternative to simple swipe.)

**Comment by Frenzie** [comment]
I didn't mean it as something to add to the program, but as an emergent property from allowing for simple macro-like chained actions.

**Comment by poire-z** [comment]
Sharing more thoughts on this, just to not lose them :|

We could have a new notion of _tracked page_, and some gestures to next/prev/rotate among tracked pages.

When on some page, you could set it as a tracked page. So, on a PDF with no footnotes link and no real TOC, you could set the in-book TOC first page as a tracked page, and the first page of footnotes as another tracked page. And your current position in the main book text would just be another tracked page.

With `Swipe to go to next tracked page` (or some other multiswipe gesture), you could easily rotate among these: the tracked page you jump to become the current position in the book. When you `Swipe to go to next tracked page`, the previous tracked page is remembered to be the page you were when you left it to go to another tracked page. Swipe to rotate among them, and you could quickly jump to various parts of the books, and advance among each.
It would be totally independant of bookmarks.
Generic feature, many possible usages. Hard to explain :) and would need some UI indicator of in which you are (some number inside the dogear?), and a way to start a new tracked page (well, if you have set one, you are in it, so as you advance to select another one, you're moving the one you're in... bit not obvious...)

Would that make sense?

> I didn't mean it as something to add to the program, but as an emergent property from allowing for simple macro-like chained actions.

Yep, I got that. But _simple macro-like chained actions_ is quite something to add to the program :) Absolutely mutually non-exclusive with the other ideas discussed here.

**Comment by Biep** [comment]
For me it would suffice, but having a standard location "origin of last jump" would probably be nicer.  Indeed the start value of that location would be something arbitrary, such as the first page, or the current page.  (Given my use case, the last page could also be a nice default :-)

Given Freddie's idea to make it programmable, the fact that abuses bookmarks would just be a feature of the code I happen to have assigned to those swipes, not something inherently ugly.
Adding named bookmarks would also solve the problem :-)

**Comment by poire-z** [comment]
You can already rename a bookmark (Bookmarks menu item, hold on one in the list).
But that don't change the fact that our bookmarks are not tracking, they reference the page you once set it on.

But indeed, bookmarking the current page, giving it a name "Joe's current position" or "Where I'm at in footnotes", and being able to flag it as "tracking" could have it follow your prev/next page moves (and only these). It could very well be the technical support for these _tracked pages_ without much new work, and already a UI to edit/manage them :) with different behaviours (I guess we'd not want a dogear on our current page).

**Comment by Biep** [comment]
Yes, "tracking" or "visible" could be properties of bookmarks.  If "tracking" had levels, a bookmark that even tracked jumps could make whatever current mechanism is there to reopen a book at the page where one left it unnecessary: just jump to the bookmark "actual page" when a book is opened.
If you want, "implicit" could be another property.  Implicit bookmarks are not stored in the "latest" pointer, so making the workhorse bookmarks implicit would have them not interfere with any "jump to latest bookmark" actions of the user.
First-class bookmarks, yay!

I don't know how the gestures would work, but suppose they are associated with lua functions.  Then JumpToNextNamedBookmark("Biep") might yield a function that did just that - and if I had two tracking bookmarks named "Biep", the gesture would alternate between them.  My wife could use a different gesture, associated with JumpToNextNamedBookmark("Evelin"), and our reading activities wouldn't interfere (apart from fighting for the ereader).
Slightly more advanced users could write a lua function themselves, making Frenzie's chained commands, or conditional commands, easy.
