### ISSUE TITLE
Building koreader on Debian Jessie

### ISSUE THREAD

**Issue by oxniu** [koreader/koreader#1469]
I'm compiling some app for KPW1 on Debian Jessie, the default TC has a GLIBCXX version 3.4.20, as show:
Leo@Leo:~$ strings /usr/lib/arm-linux-gnueabi/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH

But KPW1 only support up to GLIBCXX_3.4.14, when I run the app in KPW1, it throws exceptions like 'GLIBCXX_3.4.20 not found'.

How can I solve this problem? It has troubled me for a long time.

**Comment by NiLuJe** [comment]
Either link against libtsdc++ statically (-static-libstdc++), and risk eating dirt on other ABI mismatches, or use/build a TC more tailored to your target device.

**Comment by chrox** [comment]
> But KPW1 only support up to GLIBCXX_3.4.14, when I run the app in KPW1, it throws exceptions like 'GLIBCXX_3.4.20 not found'.
On which library does it throw out the error? 

Koreader now supports quite a long list of devices, with each of the device multiple firmware may use different versions of GCC tool-chains. Take PocketBook for example, one single model may use 4.x or 5.x firmware that have different GLIBCXX versions so that some features that rely on `libzmq.so` won't run on 4.x firmware. I also tried the `-static-libstdc++` approach proposed by @NiLuJe but the building system would not buy it. And I reopen #480 which suggests that we include `libstdc++` in the libs dir and set `LD_LIBRARY_PATH` to include the libs dir in `koreader.sh`. That probably is much easier to solve this kind of problem.

**Comment by NiLuJe** [comment]
My comment in #480 was obviously wrong, the `-static-libstdc++` should of course go in LDFLAGS, which might explain why that didn't work for you ;). That, or something isn't honoring LDFLAGS ;).

Of course, shipping it as a shared library would also do the trick, but I'm not quite sure which solution would actually have the lower overhead... ;). I'd be willing to bet on static, strangely enough :).

**Comment by NiLuJe** [comment]
As for picking up the path of the TC's shared lib:

```
readlink -f "$(gcc -print-file-name='libstdc++.so')"
```

Does the job here, and I don't think that's a terribly new feature, but I might be wrong.

**Comment by chrox** [comment]
:thumbsup: That's purely awesome.

**Comment by NiLuJe** [comment]
Hmm. It's been a while since I built everything on my own TC, but I *think* I had to use static-libstdc++ and it worked.

A quick check w/ readelf points to libs/libtesseract.so.3, libs/libdjvulibre.so.21, libs/libcrengine.so, libs/libk2pdfopt.so.2, libs/libkoreader-cre.so and libs/libzmq.so.4 being the only things linking against the C++ stdlib, so the buildsystem of one of those might not be honoring LDFLAGS properly.

**Comment by oxniu** [comment]
@chrox The library which throws out the error is libtesseract. I tracked the function calling and found an entry which libtesseract used only included in GLIBCXX 3.4.20 in default Jessie TC environment.

I can provide the related info later.

**Comment by chrox** [comment]
Now could you try building koreader on your Debian Jessie with #1471? The libstdc++.so.6 dependencies are all cleared off. I hope it works for you.

**Comment by oxniu** [comment]
It works perfectly now! Thanks! @chrox
