### ISSUE TITLE
Ota update does not select newest update on number basis. 2 out of 3 servers are down!

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1512]
Trying to update to v222 from v189, I got the response that no new update was available. So I changed channels between nightly and stable and bank---no joy. I changed server from vislab to koreader,ak-team to hal9k and there I got the response that I could update to version 2014110003!! 

So that last rather unexpected response seems to suggest that the implementation is working. Server http://vislab.bjmu.edu.cn/apps/koreader/ota/ is empty, though.
Server http://koreader.ak-team.com/ only shows the file favicon.ico.
Server http://hal9k.ifsc.usp.br/koreader/ does show all the latest updates. However, it assumes that 2014-11-3-.... is newer that 2014-11-222-....

So the implementation should not use single digit comparison, but rather whole number comparison 2014 with 2014, 11 with 11, and 3 with 222.

~~Where is the code is this handled?~~[otamanager.lua](https://github.com/koreader/koreader/blob/master/frontend/ui/otamanager.lua#L93)
Why is there a dot in line 94: ` string.format("%.4d", revision or "0")` Doesn't that format 4 decimal places, instead of 4 decimals? Was it meant to generate 0003 and 0222 out of resp. 3 and 222:  ` string.format("%04d", revision or "0")`? 
Or was it meant to be a floating number %.4f? Still 3.0000 seems rather smaller than 222.0000. Still can't find where the revision values are compared.

**Comment by NiLuJe** [comment]
I'm guessing @chrox pulled the broken releases until we're done cleaning my messes?

Sorry about that ;).

**Comment by Markismus** [comment]
No worries. Was nice looking into the that part of the code for the first time, anyway.

**Comment by chrox** [comment]
```
Actually the `"%.4d"` and `"%04d"` formats are identical in this case.
~ $ luajit
LuaJIT 2.1.0-alpha -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> for i = 0, 99999 do
>> assert(string.format("%.4d", i) == string.format("%04d", i))
>> print(string.format("%.4d", i), string.format("%04d", i))
>> end
0000	0000	
0001	0001	
0002	0002	
0003	0003	
0004	0004	
0005	0005	
0006	0006	
0007	0007	
0008	0008	
0009	0009	
0010	0010	
0011	0011	
0012	0012	
0013	0013	
0014	0014	
0015	0015	
0016	0016	
0017	0017	
0018	0018	
0019	0019	
0020	0020	
0021	0021	
0022	0022	
0023	0023	
0024	0024	
0025	0025	
0026	0026	
0027	0027	
0028	0028	
0029	0029	
0030	0030	
0031	0031	
0032	0032	
0033	0033	
0034	0034	
0035	0035	
0036	0036	
0037	0037	
0038	0038	
0039	0039	
0040	0040	
0041	0041	
0042	0042	
0043	0043	
0044	0044	
0045	0045	
0046	0046	
0047	0047	
0048	0048	
0049	0049	
0050	0050	
0051	0051	
0052	0052	
0053	0053	
0054	0054	
0055	0055	
0056	0056	
0057	0057	
0058	0058	
0059	0059	
0060	0060	
0061	0061	
0062	0062	
0063	0063	
0064	0064	
0065	0065	
0066	0066	
0067	0067	
0068	0068	
0069	0069	
0070	0070	
0071	0071	
0072	0072	
0073	0073	
0074	0074	
0075	0075	
0076	0076	
0077	0077	
0078	0078	
0079	0079	
0080	0080	
0081	0081	
0082	0082	
0083	0083	
0084	0084	
0085	0085	
0086	0086	
0087	0087	
0088	0088	
0089	0089	
0090	0090	
0091	0091	
0092	0092	
0093	0093	
0094	0094	
0095	0095	
0096	0096	
0097	0097	
0098	0098	
0099	0099	
0100	0100	
0101	0101	
0102	0102	
0103	0103	
0104	0104	
0105	0105	
...
```

**Comment by Markismus** [comment]
So where do you thing the comparison error arose?

**Comment by chrox** [comment]
There is no bug regarding version comparison in otamanager. The current comparison is that if it finds the version at otaserver *different from* your local version it will prompt the user to update. See [here](https://github.com/koreader/koreader/blob/master/frontend/ui/otamanager.lua#L110) (the comment however being a little bit misleading). Since nightly build are always the latest build it's guaranteed that a different nightly build version in the ota server will be the latest nightly build. 

And in this way we can also host stable release with the nightly release in the same directory. Note that stable release version number is always smaller than latest nightly. Users can also rollback from latest nightly to latest stable. If we choose to really compare the version number there needs additional logic to support rollback to stable. Actually the 2014110003 you found was the v2014.11-stable, and you were asked to rollback to stable release because you choosed the stable channel.

**Comment by chrox** [comment]
And Lua simply call the C standard function `sprintf` to format string in this way:
`%[flag][min width][precision][length modifier][conversion specifier] `

I cannot say "%.4d" or "%04d" which is better in this case. But "%.4d" only uses the precision field ".4" while "%04d" uses two fields, the zero flag "0" and the min width field "4". I would prefer the first one since one precision filed could solve this problem.

Ref: http://www.cprogramming.com/tutorial/printf-format-strings.html

**Comment by chrox** [comment]
Closing this now.
