### ISSUE TITLE
networkmgr: unable to check network connectivity (www.example.com is down)

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#1522]
@chrox 

$ nslookup www.example.com
Server:	127.0.1.1
Address:	127.0.1.1#53

** server can't find www.example.com: REFUSED

So my kobo think it isn't online. This just affects OTA updates. Changing back to www.google.com or www.example.org does the trick for me

(I live in Spain, BTW)

**Comment by NiLuJe** [comment]
Random comment: since it's used for the OTA stuff, why not try to lookup one (or more) of the OTA servers, instead of a third-party?

**Comment by houqp** [comment]
The check is for network connectivity in general not just OTA. Checking on OTA server is not much different from checking example.com, unless we are sure all OTA servers have high availability. How about put a list of domain there? i.e. check example.com, if failed check google. We can throw in github or linkedin in the list too.

I think one of the reason we did not use google in the first place is because it's partially blocked in places like China :(

**Comment by pazos** [comment]
But for other services the lookup is after being unable to reach those services. 

in otamanager is a must before trying to connect to an OTA server

**Comment by pazos** [comment]
Ok, Found the root of my problems!! 

My lan router (iomega iconnect) uses google DNS (8.8.8.8), not those provided by my ISP.
The weird thing is that www.example.com  and www.example.org point at the same IP:  93.184.216.34 but only the latter is on google's nameserver.

In my case I solved it adding a line in /etc/hosts. But It could be nice to change www.example.com to www.example.org because some basic setups (like mine) rely on google DNS servers.

@NiLuJe @houqp , If you wish to improve this it would be awesome, but for me issue is closed. Thanks for make possible this wonderful software  :+1:
