### ISSUE TITLE
[Kobo] [Enhancement] keep frontlight level between nickel & koreader

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#1523]
@NiLuJe @Frenzie @WS64 @houqp 

Hi, I'm on FW 3.15 and I can read frontlight status from nickel with:
`while true; do cat /mnt/onboard/.kobo/Kobo/Kobo\ eReader.conf  | grep FrontLightLevel; done`

Just move nickel's brightness slider and you'll check :)

So it will be nice to keep light settings between readers :8ball:

**Comment by chrox** [comment]
Sounds like a good hack. :+1:

**Comment by pazos** [comment]
I would like to implement this myself but I have no idea where to start. Anyways we must keep current implementation if we can't find this FrontLightLevel string in kobo config.

Any ideas?

**Comment by Frenzie** [comment]
Ah sorry, you posted this right as I was in the middle of moving and I simply ignored all non-essential notifications (which includes KOReader). The most relevant location, if you're still interested in implementing this, is probably [uimanager.lua](https://github.com/koreader/koreader/blob/a30fe26de01e7e5a9adc55857ee7cfc430b812bc/frontend/ui/uimanager.lua#L62-L64), but also see [frontend/device/kobo/](https://github.com/koreader/koreader/tree/master/frontend/device/kobo) and [ffi/kobolight.lua](https://github.com/koreader/koreader-base/blob/master/ffi/kobolight.lua).

**Comment by tbm** [comment]
I'd also like to see this feature.

**Comment by dset0x** [comment]
I started working on this but I've discovered some duplicate/strange behaviour and I am not sure which way is preferred.

When I start koreader from KSM, the following takes place:

1. `frontend/ui/uimanager.lua`

**Comment by dset0x** [comment]
I started working on this but I've discovered some duplicate/strange behaviour and I am not sure which way is preferred.

When I start koreader from KSM, the following takes place:

0. [`ffi/kobolight/open`](https://github.com/koreader/koreader-base/blob/master/ffi/kobolight.lua#L73) runs. This initializes `brightness = 0` and `isOn = false`.

1. [`frontend/ui/uimanager.lua`](https://github.com/koreader/koreader/blob/master/frontend/ui/uimanager.lua#L63) uses the value of `KOBO_LIGHT_ON_START` from [`defaults.lua`](https://github.com/koreader/koreader/blob/master/defaults.lua#L176) to call the following stack:

    ```
generic/powerd/setIntensity
kobo/powerd/setIntensityHW
ffi/kobolight/setBrightness  
    ```
This results in: (a) brightness actually changes and (b) new values for `self.brightness` and `self.isOn` are stored.

2. [`koreader/reader.lua`](https://github.com/koreader/koreader/blob/master/reader.lua#L116) checks if `powerd.restore_settings` ([`frontend/device/kobo/powerd.lua`](https://github.com/koreader/koreader/blob/master/frontend/device/kobo/powerd.lua)) is enabled. Then, if `frontlight_intensity` is set in the `settings.reader.lua` file, it replaces the hard-coded value of `powerd.flIntensity` with that. Then, calls the following stack (which implicitly uses `powerd.flIntensity`):

    ```
generic/powerd/setIntensityWithoutHW
kobo/powerd/setIntensitySW
ffi/kobolight/restoreBrightness 
    ```
This results in: (a) `self.brightness` and and `self.savedBrightness` are modified.

Now, if we had loaded KSM with brightness 1 and koreader with `KOBO_LIGHT_ON_START = -1`. Then we toggle the brightness twice, we end up with `brightness = 20`, since that's what `settings.reader.lua` contains (and so does ffi's memory).

The problem begins with having configuration in two places (`defaults.lua` and `settings.reader.lua`). Which one should be kept? Should I feel free to remove all the logic from `koreader/reader.lua`? In that case, what happens with the brightness settings in `settings.reader.lua` and `frontend/device/kobo/powerd.lua`?

**Comment by houqp** [comment]
@dset0x Thanks for taking stab at this issue ;) You are right, `KOBO_LIGHT_ON_START` should have the lowest priority. The setting in `settings.reader.lua` should have the same priority as the kobo setting so that we can synchronize between nickel and koreader.

If you are going to always use `Kobo eReader.conf` to override frontlight_intensity, then we should probably also update `Kobo eReader.conf` when exiting from koreader. Otherwise we will have issues with following two scenarios:

* User changed frontlight settings in koreader, but nickel never picks it up
* User changed frontlight settings in nickel to 50%, then started koreader and changed it to 14%. Restarting koreader will revert the setting back to 50%, which is not expected.
