### ISSUE TITLE
FR: Title of the book somewhere

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1532]
Hi

It would be nice if the title and the author etc are show somewhere. It may sound weird to ask for such thing at first, but sometimes the reader might put the erader aside and come back and might want to know which book and author it was.

**Comment by Markismus** [comment]
You could open the history and look at the top entry, c.q. the current book your are reading.

**Comment by pdo-smith** [comment]
Gerroon,
The title and author are shown in the top status line if they are contained in the book's metadata.

**Comment by gerroon** [comment]
@pdo-smith 

I assume you mean epub. How about the Djvu and Pdf formats?

@Markismus 
That is just a work around. It would be nice if it is a betterintegrated feature.

**Comment by apletnev** [comment]
I've added this feature in #1730 but it does not work for PDF and DJVU. The problem is pdf's and djvu's usually without meta information about themselves, so i can't get real information about current reading pdf or djvu book. 

![status](https://cloud.githubusercontent.com/assets/220872/12758438/ded1fc12-c9e4-11e5-988d-73833e7c0557.png)

**Comment by Frenzie** [comment]
Hm? I have loads of PDFs and DjVus with metadata. :)

**Comment by houqp** [comment]
@apletnev what meta info do you need? Looks like the most important bits are current page and total pages? Those can be obtained from the book settings. For other info, we can leave it out blank.

**Comment by apletnev** [comment]
Added support of PDF. https://github.com/koreader/koreader/pull/1806

**Comment by chrox** [comment]
Implemented in #1806.
