### ISSUE TITLE
A notepad like freature. 

### ISSUE THREAD

**Issue by RuanMedGar** [koreader/koreader#1536]
I think that e-ink readers should have a tool to make notes not only when reading a book. It would be useful in a class context, for example.

**Comment by Markismus** [comment]
Nice thought. Koreader doesn't even provide one for reading books yet, so this issue seems a little bit out of our ballpark...So I'll close this issue.

If you're the owner of a Kobo device I would recommend [Sergeyvl's KoboLauncher](http://www.mobileread.com/forums/showthread.php?t=222803) amongst others it includes a notepad just for taking notes without reading a book.

For the still-not-much-ongoing work on a note feature for koreader see #1095.
