### ISSUE TITLE
Refresh page after removing highlighted text

### ISSUE THREAD

**Issue by lenisko** [koreader/koreader#1558]
Like in topic.
Page should refresh after removing highlight, or we can't tell for sure if it was deleted.

**Comment by NiLuJe** [comment]
It already should, IIRC?

(At least for CRE stuff, can't speak for PDF/DjVu).

----

NB: I might be wildly mistaken, but I distinctly remember, when playing with the refresh modes, making sure that the refreshing when clearing a highlight was handle in a specific way so that it did so in a pleasing and efficient way.

**Comment by lenisko** [comment]
Kindle PW2, koreader-nightly-20150608

That's right, box with delete & edit options disappear, but text is still highlighted till I turn page.
It's very small case so I think, but confusing sometimes.

**Comment by NiLuJe** [comment]
On which kind of documents? Because that definitely shouldn't happen on ePubs, at least (AFAIR).

**Comment by chrox** [comment]
I can reproduce this on both PDF and Epub documents by first highlight text and then delete the highlight. The text is still in highlight state although it's actually deleted so probably a screen refresh issue.

**Comment by lenisko** [comment]
Indeed, it's same for PDF, EPUB and MOBI. Maybe some call to refresh function after removing highlight is missing?
