### ISSUE TITLE
Slipit a PDF into 6-inch

### ISSUE THREAD

**Issue by Juddd** [koreader/koreader#1574]
I have a confusion to the reflow model,which result to a substantial clerical error.Could you slipit a line words to two lines,or another smallest measurement which is more comfortable to read.If you don't recognize the word ,you'll not make a clerical error.

**Comment by chrox** [comment]
Currently there indeed is no OCR in the reflowing process. But the reflowing results sometimes are still unreliable. [This article](http://vislab.bjmu.edu.cn/blog/hwangxin/2012/10/read-scanned-pdfs-with-kindlepdfviewer/) has a short description of the reflowing algorithm of K2pdfopt the reflow engine of koreader. Since this issue does not raise a particular problem I'm closing it now.
