### ISSUE TITLE
order of images in mobi file

### ISSUE THREAD

**Issue by frankyifei** [koreader/koreader#1650]
The order of the images are not correctly shown.

**Comment by chrox** [comment]
Please consider converting mobi to epub which should have better support. I doubt there is any worth to invest time into mobi format considering that we still support mainstream epub poorly.

**Comment by sebnapi** [comment]
What a pitty! At least you could fix the order.

**Comment by houqp** [comment]
@sebnapi it might not be a simple fix. We welcome other people to send us patches for this though.

**Comment by Frenzie** [comment]
I'm not really interested in mobi, but I think there's some info missing. Does this apply to *any* file with images or is there a particular testcase? And even if it does apply to any file with images, we'd still need a testcase. None of my regular sources (e.g. Archive.org and dbnl.org) offer mobi. Basically what I'm saying is you need to erase any resistance to a possible quick fix. ;)

**Comment by sebnapi** [comment]
I have the problem with these files, [epub](http://dl.dropboxusercontent.com/u/15164593/The%20Definitive%20Book%20of%20Body%20Language%20-%20Barbara%20Pease.epub) works well but [mobi](http://dl.dropboxusercontent.com/u/15164593/The%20Definitive%20Book%20of%20Body%20Language%20-%20Barbara%20Pease.mobi) displays the pictures somewhat randomly (you can download them and upload them internally, only for testing purposes). I use KOReader on the Kindle. Kindle doesn't support epubs, my girlfriend uses the built-in reader and I use KOReader because I love the evernote plugin, which is btw. great, thus if I want to use both readers I upload mobi files.

**Comment by houqp** [comment]
The biggest problem with mobi is it's a proprietary format designed by amazon for user lock-in :( Has it been an open spec like epub, we will have no problem spending more resources on it.

Out of curiosity, what's the reason that your GF prefer the built-in reader than koreader?
