### ISSUE TITLE
FR: Custom central place for .sdr folders

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1695]
Hi

I would be great if one could define a custom path for the sdrs. The main issue is that they pollute the folders. Lets say I have 500 books in a page and if I check those book one by one I will have another 500 folders in there.

The other issue is that it would be much easier to sync the sdr folders that way even if the books are scattered on the system, using Syncthing, Dropbox etc. 

thanks

**Comment by chrox** [comment]
On Kindle the `sdr` directories are also created by native reader application so it's not a problem. We may need an option to disable it on other platforms. But I'm not sure if a centralized `sdr` heap is a good idea. In a centralized directory to save these files you need to store the absolute path of each book which is always not right if you migrate these files to another device, like from Kindle to Android. On the contrary, storing `sdr` besides the real documents won't have this problem and is more portable in all Koreader supported platforms. BTW, I have 7 books in my Kindle right now, so not my problem.

**Comment by gerroon** [comment]
How about giving this option on Android and not in other platforms?

**Comment by houqp** [comment]
I am with chrox on this one. We used to put all document settings into a centralized directory back when kindle is the only supported platform. After people start porting koreader to other platforms, setting syncing became an issue because different platforms have different filesystem layouts and centralized sdr requires storing absolute path for books to work.

Puting sdr dir together with the book make the setting portable between any platforms. You just need to copy the whole directory and everything will just work. Which is awesome.

You are of course welcome to develop a plugin to implement centralized sdr structure since koreader is open-source software ;)  Adding another option for this to koreader core is going to further complicate the code base and makes it harder to maintain. Our setting module is not very well structured right now because of some legacy reasons.

**Comment by gerroon** [comment]
Hi

Do not get me wrong I like the way it is now. I was just trying to figure out an easy way to sync those settings across devices without moving large number of books as well.

**Comment by timofonic** [comment]
What about this? Any news?

Could you use some kind of sync protocol? Even Google Drive and Dropbox support would be a good start. SSHFS and such would be amazing!

**Comment by houqp** [comment]
@timofonic Google drive and Dropbox should just work out of box if you sync the whole document folder.
