### ISSUE TITLE
Can we add our own "OTA" URL, and use zsync for other files?

### ISSUE THREAD

**Issue by KenMaltby** [koreader/koreader#1700]
I can use "zsyncmake.exe" to create a KoboRoot.tar.zsync  on my PC.  As long as we have a working zsync client, it would be nice to be able to use it to transfer compressed files wirelessly. I was able add a share to the list of OTA servers, and just got a "OTA package is not available on develop channel." message. I am thinking that it indicates that my .zsync file was checked and found wanting.  (The KoboRoot.tar.zsync  is for the KoboRoot.tgz that installs KSM08.)

**Comment by KenMaltby** [comment]
How about if it doesn't see an "OTA package", but does see an .zsync file, it downloads the file into an input folder.  I am pretty sure you can specify that in the zsyncmake options.

**Comment by chrox** [comment]
The koreader "Zsync" plugin (unfortunately it has nothing to do with the zsync binary which is used in the OTA update) is almost for your needs. It uses ZeroMQ to detect peers on the same network that can talk each other so that you don't even have to input the host address. Just publish a file in one device or your desktop and subscribe on the other device, Zeromq will do the rest magic.

But currently "Zsync" plugin can only sync document opened in the publishing device. Maybe we will implement the plugins in filemanager so that generic files could be handled by the plugins. Then you will be able to run a koreader instance on your desktop and another instance on your Kobo and sync any file you want.

**Comment by KenMaltby** [comment]
A filemanager option would be the best way to go, in my opinion.
