### ISSUE TITLE
Changing defaults using GUI doesn't affect defaults.persistent.lua file

### ISSUE THREAD

**Issue by GeneralFailer** [koreader/koreader#1701]
The title, basically. Because of this, every time a new book is opened, the renderer uses the font size value from the defaults.persistent.lua file, while the interface displays the value I set as default as the one used (i.e. the one in the defaults.lua).
I launch the program with KUAL on Kindle Touch.

**Comment by Markismus** [comment]
I had this problem, too. Can't remember whether I gave up and edited the file manually or that chrox's  PR to allow array inserts solved the problem.   

Comments at the time suggested that the culprit probably was read-write errors due to file access or even block device access. I could also be that the SD-card did not sync with the writebuffer before the system stops.

Seeing your other issue, #1702, it could be a file write problem. The lua-files with bookmarks and highlights that koreader generates, have given me rather a lot of unexpected behaviour, lately. 

I've been reading a rather thick book and every other day I find koreader suddenly back at KSM. Not a big problem, but a lot of the time there is has been no history entry for the book, nor bookmarks in the book. It seems no files get generated, if koreader suddenly quits, c.q. crashes. When I have time, I'll have a look at my crash.log.

**Comment by KenMaltby** [comment]
As I remember it, dropping to the File Manager, was supposed to cause the saving of everything.

**Comment by GeneralFailer** [comment]
There's also an EPUB file opening which causes the program to crash to the Kindle home screen for me. Maybe it's connected to all this.
http://www.mobileread.com/forums/showpost.php?p=3198970&postcount=855
