### ISSUE TITLE
Statistics planed features, any suggestions? 

### ISSUE THREAD

**Issue by apletnev** [koreader/koreader#1712]
Hello guys, I want to add a few features into the Statistics plugin and want to discuss architecture approach. I'd like to add a "complete" window after finish the book. The complete window has next items: score, add note, mark as read, move to folder, show stat, etc. We have the same future request “FR: Marked as read #1576”.
In this case I can do it like this:
The Complete component will be independent in reader/modules/ like readercompletebook.lua and save in some format info about completion. The component can throw event like bookFinish in that case e.q the statistics plugin will catch event and add in to it's data info about the complete. The File manager before show the list of books uses the data from the component and marks appropriate books as read.

Also we have “FR: Time to Read #1707" in the status bar. I can’t add this feature because the statistics is a plugin, and has low coupling with other components e.q readerfooter.lua. I do not think it is a good idea to link core components with plugins. Based on that, maybe we move the statistics from plugins to core component? Like readerstatistics.lua?

Also i want to add some goals in to the statistics, for example minimum pages to read in day. It is will be like some gamification for reading. Maybe will add some achieves for fun. )
  
The statistics plugin requires correct time and date, what do you think about add in to the koreader settings synchronisation with some time servers? 

Any suggestions, comments, proposals?

**Comment by Frenzie** [comment]
I like the idea of integrating this with #1576.

Plugin or core — you're probably right about that, but I reckon e.g. @chrox has a more useful opinion on that.

> Also i want to add some goals in to the statistics, for example minimum pages to read in day. It is will be like some gamification for reading. Maybe will add some achieves for fun. )

People seem to like that. 

> The statistics plugin requires correct time and date, what do you think about add in to the koreader settings synchronisation with some time servers? 

While I'm not opposed to the idea (at least on Kobo devices; my H2O loses a minute every week or so), I don't see how correct time and date matter? A minute is a minute regardless whether the device thinks it's November 2015 or January 2010.

**Comment by chrox** [comment]
Actually a plugin module in every aspect is treat equal to a reader module, see [here](https://github.com/koreader/koreader/blob/master/frontend/apps/reader/readerui.lua#L296-L301). A plugin module can access the parent `ui` and other reader modules like this `self.ui.rolling` or `self.ui.paging`. And it can receive `ReadSettings` and `SaveSettings` events just like a regular reader module by defining the corresponding event handlers like this:
```
function YourPlugin:onReadSettings(config)
    self.stats = config:readSetting("stats") or {}
end

function YourPlugin:onSaveSettings()
    self.ui.doc_settings:saveSetting("stats", self.stats)
end
```

So my suggestion is that we keep the Statistics Plugin but save the stats data to the document history file so that other modules can also read. For example, in the cover view of Koreader we can read the stats info of a document and display the size of the cover proportional to total read time. And the function of `readercompletebook` emitting the `BookFinished` event can be implemented in `readerrolling` and `readerpaging` both of which are aware of the reading progress, one for EPUB and the other for PDF.

As for syncing to time servers, it's just not an application's duty to fix a problem of the underlying system. Probably you can write a script that runs in the background to sync with a time server and run that script when starting koreader.

**Comment by Frenzie** [comment]
> As for syncing to time servers, it's just not an application's duty to fix a problem of the underlying system.

That's debatable. Supporting a frontlight switch is a problem of a lack of a physical switch in the hardware. ;) On a proper computer or even on an Android device things like WiFi and time synchronization are dealt with by the system, but on e.g. a Kobo device KOReader effectively replaces the "system" (i.e. Nickel). It's the kind of action that makes sense to be performed alongside [checking for updates](https://github.com/koreader/koreader/blob/d93f8a743bf86385cfcf70f4b2e025ad8bcf94e3/frontend/ui/otamanager.lua#L69) or [after enabling WiFi](https://github.com/koreader/koreader/blob/f892bc0b727286ca482213d7b3ceffb438a2a234/frontend/ui/networkmgr.lua#L31).

NB Booting into Nickel every couple of months to fix the time (or doing so via the command line) is certainly nowhere close to annoying enough to motivate me to implement such a thing. And because KOReader isn't the only alternative reading software it might very well make more sense to have a little script running running on the KB Start Menu side of things. It'd execute `ntpd -q -p example.com` (depends on the version and compile-time options for busybox; I don't recall the Kobo version out of hand) or `rdate -s time.protocol.server.org` (should always work).

**Comment by chrox** [comment]
Yes, it's perfectly suitable to be implemented in Kobo Start Menu which aims to replace Nickel. As for Koreader it's essentially an application for document reading. More and more hacks/workarounds to fix fragmented underlying systems will be a burden on Koreader and eventually lead to unmaintainable complexity. The best way to avoid this complexity is moving these code to an additional layer between the system and the application, say koreader launchers on each platform.

**Comment by apletnev** [comment]
Gents, 
some final clarifications:
1. Save the statistics data in to the history file e.q "[..#..#test#] sample.pdf.lua"
2. Add UI component  #1576 - Complete book (score, add note, mark as read, move to folder, show stat). Any additional suggestions?
3. Add the complete book feature into the readerrolling and readerpaging
4. Add #1707 in to the status bar (get info from history file)
5. I use koreader in the kindle and have a problem with date sync. If it is difficult add time sync, maybe better to add in to the settings menu component like datetimepicker that helps us to set up manually date?

@chrox, @Frenzie  what do you think?

**Comment by Yaretzki** [comment]
Hello,
In status bar there is information about pages left in chapter. Is it possible to link this information together with average time per page in order to get time left to read chapter?
Y.

**Comment by Frenzie** [comment]
@apletnev 

> 2. Add UI component #1576 - Complete book (score, add note, mark as read, move to folder, show stat). Any additional suggestions?

What does "score" do?

**Comment by apletnev** [comment]
@Frenzie 
It is rating e.q 5 stars

**Comment by Frenzie** [comment]
Better call it "rate" or "rating" then depending on whether you were going
for the verb or the noun? :)

On Wed, Nov 18, 2015 at 1:19 PM, Alexander Pletnev <notifications@github.com

**Comment by AlanSP1** [comment]
Few comments:

1) Having option to setup time (manually is in my opinion better) in koreader (or KSM, I'll ask tshering) is a great help to avoid completely nickel, which is something I strive to.

2) Having time to read in status bar is great. Ok, not very helpful, but I wanted to say that. :)

3) When setting statistics options, I don't see old ones, just see that default ones are 5 and 90 seconds. Even if I changed them, I always see default ones. It would be much better to have confirmation that I set wanted options. It also would help to know if we need to change them, or if we are satisfied. Feedback from options is very useful.

4) Now that we have statistics module, I think it would be great to have shortcut to statistics for current book, beside option to put time to read book in the status bar. I think that placing icon for statistics in lower bar when we access menus (where are options to change font size, orientation, etc) is best place.

Accessing statistics plugin from upper bar is fine, but quick access to current book-specific statistics is needed in my opinion.

**Comment by AlanSP1** [comment]
About setting date/time manually from KSM, it looks like it won't happen any time soon, if ever. I asked tshering and his answer is that it probably never happen: http://www.mobileread.com/forums/showpost.php?p=3211405&postcount=45

If it could be done from koreader then, it would be great. This is actually only reason why I use nickel.

**Comment by Frenzie** [comment]
That shouldn't mean that he won't accept contributions. Just that he won't
look at it himself.

**Comment by AlanSP1** [comment]
So, we need someone who would know how to program this feature and add it in KSM.

**Comment by KenMaltby** [comment]
Tshering mentioned one way, using busybox. http://www.mobileread.com/forums/showpost.php?p=3211849&postcount=47

**Comment by Frenzie** [comment]
I believe that just `date 23:30` should do, with seconds optional. Also note what I [mentioned above](https://github.com/koreader/koreader/issues/1712#issuecomment-155100070) about synchronizing with a time server using `ntpd -q -p pool.ntp.org`. You can find pools only relevant to your region using http://www.pool.ntp.org/en/.

**Comment by AlanSP1** [comment]
I just saw tshering's post that @KenMaltby mentions and it is actually really simple thing to change time that way. Didn't know that KSM has terminal (yes, I'm a bit ashamed).

And if we have wifi access, we can use ntpd command to sync time to them, as @Frenzie mentions.

So, in a way, this is solved at least for me. But, if there is a simpler way from koreader, like it is in nickle, for some users that may be better solution.
