### ISSUE TITLE
One And Two or More Chinese Characters Highlight Issues Function When in Dictionary Pop-Up Window

### ISSUE THREAD

**Issue by Sopheus** [koreader/koreader#1726]
Hello,

Straight to the point:

When using highlight function when in KoReader's dictionary pop-up window there are two issues:

1 Issue. Select one Chinese character word. Push dictionary option. Dictionary pop-up window appears. Push "Highlight" button, result - selected character and the next one highlighted, when KoReader was supposed to highlight only one character.

2 Issue. Select two or more Chinese characters word. Push dictionary option. Dictionary pop-up window appears. Push "Highlight" button, result - KoReader crushes to Home Screen.

Any way to overcome this or should we wait any improvements on the matter?

P.S. I provide the link to original Chinese dictionary and book that I use in the video for test.

Video:

https://mega.nz/#!zlERVIoB!qY-PTuintgMP5BPqywFzVG3dEI_rzeVXi4rpObv9q5s

Archive with book and dictionary for test:

https://mega.nz/#!fwczhDLZ!qZTkv5_8edHDLJL5jPnjiiPfMDaOpcsYkmfakV6d1DE

**Comment by chrox** [comment]
Thanks for the report. Currently the supports for Chinese language are rather limited. We hope to improve them in the future.

**Comment by timofonic** [comment]
Did you visit the Onyx forums? Your name seems chinese and maybe you
understand it, excuse me if I'm wrong.

I did see some forum posts about it in the chinese Onyx forums. I have zero
knowledge about chinese, just looking for newer firmwares for my M96Plus
and used the Google translator (sometimes it puts very funny things, but I
managed to understand these weird metaphores) :)

http://bbs.onyx-international.com.cn/thread-23679-1-1.html

There's a surprisingly big amount of posts about KOreader in their forums!
https://encrypted.google.com/search?q=koreader+site:bbs.onyx-international.com.cn&ie=utf-8

Are there some KOreader PR on the chinese ereader communities? :D


Kind regards.

**Comment by Sopheus** [comment]
No, I am not Chinese, but I am study Chinese. I know nothing about Onyx forums, but I think that good software do not need PR, especially when it is free. I do hope that creators address the issues I described above and after that, I bet 100%, that KoReader audience will greatly increase.

**Comment by timofonic** [comment]
I don't agree about that, because many amazing projects died because they
weren't enough known.

It's a common issue in FOSS and other aspects of life too.

That's the reason promoting, funding and making events is important for
FOSS.

And KOreader needs more support:

-E-reader manufacturing companies might opt for using it in their products
instead proprietary solutions.
- They would collaborate, but invest less development than doing it
themselves.
- Users would receive a reader software that evolves more dynamically, open
and supportive to feedback.
- They would concentrate in other aspects of their product, like OS and
hardware.
(about software, they would collaborate with communities such as XDA too).
- Their sponsorship and adoption of KOreader in their products might
benefit both sides: Users would see it as a more open and customizable
platform with less hidden stuff than the rest, both the project and the
company would receive more attention and be more known too.


In certain way, this project looks a bit like Rockbox. Their lack of active
adoption of their firmware in produced hardware made it stagnant. There's a
worse case, known as OpenInkPot.

OpenWRT is in better health, of course. But they lack many organizing and
massive reverse engineering in order to not have lots of half-baked efforts
too.


Sorry, I don't believe in "good attracts the good" entirely. There's a
tendency, but quite often that needs to be more known. Sometimes you are in
the right age and do it in the right moment, but that's a very uncommon
case.

KOreader now has an user forum in mobilereader. That provides feedback and
gives visibility to the project. Now I think there's need of a website and
a XDA forum, because there are people still developing for Nook and those
could be potential contributors to an ebook reader available for Android
devices. and there's lots of developers there, not just Android!

Anyway, I accept all kind of opinions and your reply would be quite
interesting. But that's mine as ereader, FOSS, reading and technology
enthusiast.

Kind regards.

**Comment by Sopheus** [comment]
Yeah, I get your point and I am agree, question is Chinese enthusiasts community could be very closed one, they can make something on KoReader basis and will not share it with other world :(

**Comment by poire-z** [comment]
Should be fixed by https://github.com/koreader/crengine/pull/204 (for issue 1, hopefully issue 2 has been solved since) , available in current nightly.
