### ISSUE TITLE
Dictionaries not working

### ISSUE THREAD

**Issue by colibris79** [koreader/koreader#1731]
Hi,
Updated from v2014.11 to last v2015.11 in my Kobo Mini (firmware 3.4.1) and dictionaries don't work anymore. Went back to the previous one and it is working again. Would it need a firmware update?

**Comment by Frenzie** [comment]
A firmware update shouldn't affect anything. I wonder if this could be related to #1234?

Oh yeah, and just to rule out silliness — you do mean updated (on the same install) and not a fresh install? Because KOReader doesn't come with any dictionaries by default. I merely ask because I once spent way too much time trying all kinds of configuration changes on my computer only to discover a cable wasn't plugged in… so it's always worthwhile to emphasize double-checking the simple "there's no way I would've overlooked that" kind of issues. ;-)

**Comment by colibris79** [comment]
Hi Frenzie. Thanks for your quick respond. I finally installed firmware 3.15.0 after a factory reset and the dictionaries are working like a charm... :)
So maybe you were right and the dictionaries were not there (but I kind of think they were because I did this twice...). Anyways is working now. Thanks!
