### ISSUE TITLE
[FR] Add RichTextWidget

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1776]
[Due to the discussion on mobileread](http://www.mobileread.com/forums/showthread.php?p=3242259#post3242259), I was wondering how the content of the dictionary window is generated? 

I remember content from Währig that had a _lot_ of tags that were displayed: rendering the text unreadable. Would it be possible for the coolreader engine to generate those formatted entries and thus allow for more Stardict dictionaries to be used with koreader?

**Comment by chrox** [comment]
The most important thing that I concern is the memory usage of crengine when rending a fragment of HTML in the pdf reader. And I have little confidence that crengine could properly recollect the memory it allocated especially when multiple instances of crengine will be used in these case. Meanwhile, the MuPDF library now could handle some basic XML-based documents and it has a much lower memory footprint, maybe we can try using it to build a `RichTextWidget`.

**Comment by Markismus** [comment]
Ah, nice! I'll try to experiment with it.

**Comment by robert00s** [comment]
@Frenzie 
I think we can close it. Now formatting is really good.

![screenshot 2017-08-17 20-05-08](https://user-images.githubusercontent.com/22982594/29426637-90552af6-8387-11e7-92c6-9c4987a24179.jpg)

**Comment by Frenzie** [comment]
True, but it doesn't do relatively simple things like bold or italic. I changed the title to better reflect the proposal by @chrox, which I think is worth keeping open so as not to forget about it.

**Comment by TnS-hun** [comment]
I started tinkering with this. I'm doing the widget from scratch, using the ImageWidget as a basis and MuPDF for rendering but I don't know if this is the right approach or if there is an easier way.

**Comment by Frenzie** [comment]
An ImageWidget with some extras (e.g., hold to find word) sounds about right to me. Pinging @chrox who may have given it some more thought?

**Comment by poire-z** [comment]
I don't know if by _generic component_ you meant a reader engine for html/epub (which indeed would be huge :) or just a generic lua widget.
But a generic widget would be nice, and `textboxwidget `would be a good thing to clone for HTML support (no need to support initially the whole text selection with Hold).
I thought you could build a `htmlboxwidget`, and get the benefit of `scrolltextwidget `to wrap it with scrollbars and paging into slices of the stuff rendered by Mupdf, but it seems `scrolltextwidget `is a bit tied to the internals of `textboxwidget`. But that could be easy to overcome.
With a `scrolltextwidget `that could support with an additional option `is_html `both `textboxwidget `and some `htmlboxwidget`, they could be used as is by the higher-level `dictquicklookup `and `textviewer`.
(Dunno if you planned to still use the `dictquicklookup `widget for your HTML dictionary needs, but that would be nice. ReaderDictionary could may be guess if the dict content is HTML from the .ifo, or from the result themselves, and propagate that down to the the lower-level widget choice.

When I had a quick look some weeks ago at mupdf rendering of HTML, it looked to me the width and height of the rendered page was harcoded (https://github.com/ArtifexSoftware/mupdf/blob/7307a7f232b27b22176b8f68364e43e09ce393cc/source/fitz/document.c#L11-L12). So, it may still needs some patching to mupdf sources :|

**Comment by TnS-hun** [comment]
> I don't know if by generic component you meant a reader engine for html/epub (which indeed would be huge :) or just a generic lua widget.

I meant a generic RichTextWidget that can be used for other things beside the dictionary. But now that the widget is almost complete, I see that only a very small part of it is related to the dictionary, it could be refactored later to be more generic, and for example use it for Wikipedia too.

Page turning, scroll bars and selection by holding work, `textboxwidget` and `scrolltextwidget` were very useful to copy from. :)

> Dunno if you planned to still use the dictquicklookupwidget for your HTML dictionary needs, but that would be nice.

It works with `dictquicklookup`, the `ScrollTextWidget:new` call must be replaced with the new widget's constructor when the dictionary is HTML, but no other changes are required in `dictquicklookup`.

> ReaderDictionary could may be guess if the dict content is HTML from the .ifo, or from the result themselves

That's one of the questions I had: how to decide when to use the HTML dictionary.

What stylesheet to use for the HTML? Try to load it from the dictionary's file name + ".css"?

There are two problems:
1. the user stylesheet is [tied](https://github.com/ArtifexSoftware/mupdf/blob/master/include/mupdf/fitz/context.h#L379) to the context instead of the document. So if there are two HTML dictionaries with different stylesheets then they require separate contexts or the styleesheet must be injected into the HTML. I think the latter is easier considering that the context is used everywhere simply as `context()` in mupdf.lua.
2. the Nimbus font — forced by the external font patch — doesn't contain the [IPA symbols](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet) so it's not too good for the dictionary. What would be the best course of action here? Add support for the Noto font family in the patch and set that for the dictionary from CSS?

> When I had a quick look some weeks ago at mupdf rendering of HTML, it looked to me the width and height of the rendered page was harcoded

Fortunately that was easy to solve with [fz_layout_document](https://github.com/ArtifexSoftware/mupdf/blob/master/include/mupdf/fitz/document.h#L407).

**Comment by poire-z** [comment]
Nice :)

> how to decide when to use the HTML dictionary

I have no HTML dict, so I don't know if there's some hint in the .ifo file, could you check?
Otherwise, you could factor out in another function the [dumb detection if string is some html](https://github.com/koreader/koreader/blob/1d1b005b1ad98d3dad2703d94288e4245a63e265/frontend/util.lua#L501-L526) in `frontend/util.lua`. With that, it could be guessed from the result itself.

> What stylesheet to use for the HTML? Try to load it from the dictionary's file name + ".css"?

Is this really needed ? Do you have 2 dicts that wouldn't show both nicely with a unique css? (there are some sample css in crengine data directory that work usually well with most epub, you could try them).

> or the styleesheet must be injected into the HTML. I think the latter is easier

Looks fine to me, and somehow more flexible. As long as you provide a HTML string, it's easy to prepend something to that HTML string. And your new widget could hide this, if you can provide some `css_file_path` or `css_content` in its parameters.

>  the Nimbus font — forced by the external font patch — doesn't contain the IPA symbols so it's not too good for the dictionary. What would be the best course of action here? Add support for the Noto font family in the patch and set that for the dictionary from CSS?

I don't like these Nimbus fonts :) I used them in that patch as a quick & easy solution.
We could may be hardcode some of our other fonts, if we find some that go along well.
Ideally, our fonts (including users' sideloaded fonts) should be fed to mupdf from lua code on initialisation (like it's done for crengine), with abitlity to set a default font (distinguish serif/sans-serif/monospace?).
But if all that can be done with some injected css (can mupdf loads the fonts from file paths?), it's also more flexible.
(There is also a need for a fallback font, #3564)

**Comment by Frenzie** [comment]
As a quick side note, Tex Gyre Pagella is one of my favorite fonts.

**Comment by TnS-hun** [comment]
> I have no HTML dict, so I don't know if there's some hint in the .ifo file, could you check?

I think the [sametypesequence=h](https://github.com/huzheng001/stardict-3/blob/master/dict/doc/StarDictFileFormat#L367) in the .ifo can be used for this. It's not perfect because ideally sdcv would report the data type for each entries in the JSON but I think searching for that string in the .ifo will be a good enough check.

> Do you have 2 dicts that wouldn't show both nicely with a unique css? (there are some sample css in crengine data directory that work usually well with most epub, you could try them).

Unfortunately one of the dictionaries I'm using doesn't use `<b>`, `<i>`, instead of those it uses `<span>` with different CSS classes for styling.

> Ideally, our fonts (including users' sideloaded fonts) should be fed to mupdf from lua code on initialisation (like it's done for crengine), with abitlity to set a default font (distinguish serif/sans-serif/monospace?).

That would be the best. But how would KOReader/MuPDF know which file belongs to which type?

For example for Noto Sans there are four font files (NotoSans-Bold.ttf, NotoSans-BoldItalic.ttf, NotoSans-Italic.ttf, NotoSans-Regular.ttf) but they're named totally differently for Nimbus (NimbusSanL-Bol.cff, NimbusSanL-BolIta.cff, NimbusSanL-Reg.cff, NimbusSanL-RegIta.cff).

> But if all that can be done with some injected css (can mupdf loads the fonts from file paths?)

It looks like MuPDF can [load](https://github.com/ArtifexSoftware/mupdf/blob/master/source/html/css-apply.c#L703) font files from paths specified in the CSS but I didn't test it.

**Comment by poire-z** [comment]
> I think the sametypesequence=h

I have 2 french dicts (Petit Robert 2003 and 2007) that have this `sametypesequence=h` , but the texts I get in the json outpout of sdcv seem to be pure text, no HTML tag (dunno if it's sdcv that strip the HTML). So I don't know if `sametypesequence=h` is a really good hint.

> Unfortunately one of the dictionaries I'm using doesn't use `<b>`, `<i>`, instead of those it uses `<span>` with different CSS classes for styling.

Couldn't you add styles for all these in a single css file? People could complete it with new span classes as they discover the need with other new HTML dicts. I guess the chances for same span classnames with different behaviour for 2 dicts are low.

> But how would KOReader/MuPDF know which file belongs to which type?

Well, I dunno...
I think crengine gets feed with all the font files, and is able to classify them with italic/bold, and use the appropriate one. Although it considers all fonts (except if named Times New Roman) to be sans-serif.
May be it's something missing from MuPDF html support, which could be a limitation for using it as a rendering engine. But for your HTML dict needs, you could just use our main NotoSans regular for the css body element?

**Comment by Frenzie** [comment]
@poire-z sdcv should supply the entries with HTML. It's filtered somewhere.

**Comment by TnS-hun** [comment]
> So I don't know if sametypesequence=h is a really good hint.

I downloaded about 20 random StarDict dictionaries and two of them were HTML and properly marked as such in the .ifo, two were xdxf and marked as x, and the rest were text and marked as m.

But we can use the string contents based detection if you think that's more reliable.

> Couldn't you add styles for all these in a single css file? People could complete it with new span classes as they discover the need with other new HTML dicts. I guess the chances for same span classnames with different behaviour for 2 dicts are low.

All class names are single letters in that dictionary. :) I think they did that to save space.

> But for your HTML dict needs, you could just use our main NotoSans regular for the css body element?

That's what I ended up doing. NotoSans is now handled by the external font patch.

While working on NotoSans I noticed a function ([fz_install_load_system_font_funcs](https://github.com/ArtifexSoftware/mupdf/blob/master/include/mupdf/fitz/font.h#L192-L201)) that we could use instead/beside of the external font patch.

> @poire-z sdcv should supply the entries with HTML. It's filtered somewhere.

It is filtered in [readerdictionary.lua](https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerdictionary.lua#L334).

**Comment by poire-z** [comment]
> It is filtered in readerdictionary.lua

Oh, right :) If i bypass that `tidyMarkup`, I see my Petit Roberts output HTML (with only `<br>` for the 2003, but div and span with styles for the 2007).

> But we can use the string contents based detection if you think that's more reliable.

No, with the above discovery, I think now `sametypesequence=h`  is reliable enough.

> All class names are single letters in that dictionary. :) I think they did that to save space.

Guess the chances that 2 different HTML dictionary makers deciding on single letter classnames, but using common ones for different purpose is also very low :)

> While working on NotoSans I noticed a function (fz_install_load_system_font_funcs) that we could use instead/beside of the external font patch.

That could be nice (I wouldn't like we stick with the initial html font patch I quickly did with my limited C experience - it feels hacky and limited with hardcoded font names and paths, there is surely a way to make it lookup font files based on their name).

**Comment by Frenzie** [comment]
@TnS-hun I figured either there or some utility function called from there but I was just leaving a quick note from my phone. ;-)
