### ISSUE TITLE
Image display support

### ISSUE THREAD

**Issue by roger64** [koreader/koreader#1813]
Thank you for your tireless work with Koreader!!

While text display support is pretty good, image display seems to be a weak spot for Koreader. Unless I missed something, Koreader ignore some basic CSS properties for images (like _width_ -absolute or relative- or _float_) and applies to all of them an equal treatment. You can choose either to let their size unchanged or increased by a factor two (or three?) till it reaches the full width or height. By default, _cr3.in_i picks up the latter solution.

This one size rule cannot fit all.

I join one EPUB which has been published recently on Mobile Read. It contains some images in the first chapter that illustrate the problems we are facing:
1. The svg cover should be displayed on the same page. As the center image is oversized, we find text in page 1, the image in page 2 and the last text in page 3.
1. Floating images are treated as block images and go with the flow of text, carrying with them one word of text.
2. The decoration image (_adorno_) at the end of each chapter is displayed full width while it should be displayed only with a 5em width.

For all three kinds of images, the intended effects are ruined by a faulty display.
[Uploading Claudio Bombarnac.epub.zip…]

it can also be downloaded from  here
http://www.mobileread.com/forums/showthread.php?t=268249&highlight=bombarnac

Roger

**Comment by KenMaltby** [comment]
The MR thread:  http://www.mobileread.com/forums/showthread.php?t=270756

**Comment by frankyifei** [comment]
Cre ignores most of these features. it only supports simple image display.

**Comment by roger64** [comment]
If I had to choose between the three items above,  I would really appreciate a better support for svg wrappers (applying the size of the viewbox). With incoming EPUB3, we meet more and more of them on ebooks.

**Comment by medwatt** [comment]
I have some epubs with mathematical notations presented as inline images and currently KoReader just treats them as block elements and puts each in a new line.

**Comment by djalma2k** [comment]
> The svg cover should be displayed on the same page.

Seems there isn't svg support in the cre code :/  (http://www.mobileread.com/forums/showpost.php?p=3280669&postcount=8)

and would be nice to have it:
http://www.mobileread.com/forums/showpost.php?p=3280580&postcount=7

Regards.

**Comment by roger64** [comment]
I just remarked today with version 2015.11-507-gef260f0 on a PW3 that the property _width: xx%_ works now consistently (integrated style enabled) which helps a lot for the display of all relative size centered images. This is a neat progress. Thank you!!

Support is still missing for the _float_ property and everything related to _svg_ (including wrappers).

**Comment by Markismus** [comment]
I am reading Mandelbrot's _The Fractal Geometry of Nature_. The pdf- and dvju-versions of the book keep crashing on me, so I was rather glad that I found an epub-version on LibGen.

[Benoit B. Mandelbrot-The Fractal Geometry of Nature-W. H. Freeman and Company (1982).epub.zip](https://github.com/koreader/koreader/files/378422/Benoit.B.Mandelbrot-The.Fractal.Geometry.of.Nature-W.H.Freeman.and.Company.1982.epub.zip)
 Unfortunately the inline images that are used for some characters are not displayed inline in koreader, but are in vlasovsoft's coolreader (and in Nickel's epub, but that messes up the layout too much.)

Aren't we using the same coolreader engine as Sergey anymore? Could we use his solution for koreader?

koreader (v2015.11-533-g1d2150c):
![reader_2012-may-04_101847](https://cloud.githubusercontent.com/assets/5269101/17060731/ac402a12-502b-11e6-9343-c2b98676788a.png)
vlasovsoft's coolreader:
![img_20160722_163807](https://cloud.githubusercontent.com/assets/5269101/17060794/e9fea806-502b-11e6-8b17-a9c2c35e1fc7.jpg)

**Comment by houqp** [comment]
> I am reading Mandelbrot's The Fractal Geometry of Nature. The pdf- and dvju-versions of the book keep crashing on me, so I was rather glad that I found an epub-version on LibGen.

Do you still have the pdf and djvu version? Can be a good test case for us to find out the bug.

> Aren't we using the same coolreader engine as Sergey anymore? Could we use his solution for koreader?

Our crengine fork has diverged too much from other forks. So we will have to fix this bug in the code. I am tagging this issue into the stable release milestone.

**Comment by Markismus** [comment]
Yes, I have zipped both for you:
[Mandelbrot, Benoit.part1.zip](https://github.com/koreader/koreader/files/383597/Mandelbrot.Benoit.part1.zip)
[Mandelbrot, Benoit.part2.zip](https://github.com/koreader/koreader/files/383598/Mandelbrot.Benoit.part2.zip)
[Mandelbrot, Benoit.part3.zip](https://github.com/koreader/koreader/files/383599/Mandelbrot.Benoit.part3.zip)
[Mandelbrot, Benoit.part4.zip](https://github.com/koreader/koreader/files/383600/Mandelbrot.Benoit.part4.zip)
[Mandelbrot, Benoit.part5.zip](https://github.com/koreader/koreader/files/383601/Mandelbrot.Benoit.part5.zip)

The way I usually stumble into trouble with them is reading them in landscape with zoom to content width and scrolling. Searching the issues I found a post where I wrote that with the Kobo Aura I was able to read the pdf-file with reflow turned on. Now on the Kobo Aura H2O when the document crashes, it keeps crashing instantly when reopening the file. So I have to delete the sdr-file and read until the cycle repeats itself. My current speculation is that the read-write access to the sdr-file is the culprit. (I have replaced the stock 4GB microSD with a 64GB microSD card, so that introduces another uncertain factor.)

About coolreader: So we can't automatically merge because of divergence. Are there already tools to help visualize code parts for merger for these forks? It would seem wasteful just to neglect the work done on coolreader by other forks.

**Comment by frankyifei** [comment]
Add "div img{display:inline}" in your epub.css will fix this

**Comment by Markismus** [comment]
@frankyifei You're a godsend! Totally missed this post and been reading on coolreader for the past month--it's quite different from koreader! Will try and get back to you. I think I already tried the clear external style, btw.

**Comment by Markismus** [comment]
I get a lot of segmentation faults in koreader nowadays--could this be dependent on my device? (Or is Mandelbrot hexed?)

**Comment by Markismus** [comment]
[The Fractal Geometry of Nature - Benoit B. Mandelbrot.zip](https://github.com/koreader/koreader/files/454574/The.Fractal.Geometry.of.Nature.-.Benoit.B.Mandelbrot.zip)
Does anyone else get a segfault when they clear all styles?

**Comment by Markismus** [comment]
I did a factory reset, created a 4th 60GB ext2 partition for the library  and reinstalled _everything_. Now when I clear the styles, there is no segmentation fault: So that's a big win. However, the aforementioned little in-line
![reader_2016-sep-06_093612](https://cloud.githubusercontent.com/assets/5269101/18265342/8e9d554e-7415-11e6-98f8-7f3d70bbe93e.png)
 image still is drawn between the lines:

**Comment by poire-z** [comment]
I think most of the images issues described above have been solved or workarounded by:
https://github.com/koreader/crengine/pull/194 images are now inline by default
https://github.com/koreader/crengine/pull/213 images can be scaled independantly of text by the added Zoom/DPI setting
https://github.com/koreader/crengine/pull/240 support of vertical align of inline images related to surrounded text, and ability to tweak it with style tweaks.
https://github.com/koreader/crengine/pull/71 https://github.com/koreader/koreader/issues/2668 limited support for external SVG images

What's left unsupported are:
- "svg wrappers" (inline SVG tags inside the HTML) are not supported, so images and surrounded text are treated as inline images and plain text, which usually works quite alright as a fallback (and so, image scaling is possible with the Zoom/DPI setting mentionned above).
- `float:`'ing elements, and so floating images

**Comment by Frenzie** [comment]
Closing since this is largely fixed, see above.
