### ISSUE TITLE
Poor image quality in epub files...

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#1833]
Using Koreader 2015.11 stable and nightly-20160216
Device: Kobo Glo HD
Comparison between Sony PRS-T3 (left) and Kobo Glo HD using koreader (right):

Showing an image (epub) in normal mode
http://postimg.org/image/dzx7t739f
Showing an image (epub) in sleep mode:
http://postimg.org/image/ikje84myr

Using "nickel" in Kobo Glo HD:
Normal mode:
http://postimg.org/image/roht8kojn
Sleep mode:
http://postimg.org/image/8xfvyetz7

Seems some type of posterization (lack of dithering)... I don't know if it's a bug or maybe a setting to save cpu cycles when the image is rendered (nickel)....
Anyway, in case it's not a bug, how I could increase the image quality to a setting similar to Sony T3?
Regards and Thanks in advance!!!

**Comment by NiLuJe** [comment]
Yup, no dithering, and the hardware 'dithering' is crappy.

**Comment by djalma2k** [comment]
Well, I don't know if you are meaning that "hardware dithering" is crapp in a general sense or that it's the Kobo's hardware implementation? Surely you are right, I don't doubt that; but where or what is the crappy side of the "dithering": Bad side effects like ghosting or something like that? Because to me the"nickel" dithering seems good enough to my eyes or at least an improvement over the "naked"-raw image; and sony's implementation seems almost perfect to me...
Anyway, as I asked before is there any setting in there to enable it (hardware dithering or software if It could be possible)? My guess is not for your answer, but I appreciate you explain it to me.
Thanks in advance and Regards.

**Comment by houqp** [comment]
@chrox and @frankyifei knows more about CRengine. I am not aware of hardware dithering support. Can you upload the book or extract that image for us to test?

**Comment by djalma2k** [comment]
http://m.zbigz.com/myfiles?url=magnet:?xt=urn:btih:6B8597560E1DD5F6C485DD597E3E3ADD93922B60&dn=EPL_El_amante&tr=http://tracker.tfile.me/announce&tr=http://91.121.54.8:6969/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.publicbt.com:80&tr=udp://open.demonii.com:1337/announce

**Comment by NiLuJe** [comment]
By HW I meant what the eInk driver/controller does behind the scenes.

That's what gives you a lot of crappy banding, instead of the nice smooth gradients you'd have with proper dithering to the right palette ;).

**Comment by frankyifei** [comment]
The original image is 24bit image.
opened the epub in emulator, looks not bad.
opened on my kindle, it looks like no dithering. then I did a screenshot and opened it on computer, the screenshot is a normal 8bit grayscale image and looks not bad. The "no dithering" look is like a 32 color image. I converted the original image to a 32 color grayscale one. they look very similar.
![cover2](https://cloud.githubusercontent.com/assets/8104251/13176647/b280e15a-d763-11e5-9dac-3b959169bcfd.jpg)

The CRE is not to blame here since the screenshot is a nice 8bit 256 color image. But why does it look like a 4bit 32 color image when displaced in real device?

**Comment by NiLuJe** [comment]
Because real eInk devices have a much more limited palette (16 shades of grey), and unless you do something about it, it looks terrilble ;).

**Comment by pkb** [comment]
Below is screenshot of CoolReader with 4 bit gray buffer:
![amante](https://cloud.githubusercontent.com/assets/1302948/13194054/c86dd54a-d7ae-11e5-98b3-2f6f1ff8f8a1.jpg)

**Comment by houqp** [comment]
Yeah, looks like we are using crengine wrong. `drawCurrentPage` always set it to 8bpp. We need to set the BPP according to the underlining device screen. Time to do an audit and make sure it's done for djvulibre and mupdf too :-/

**Comment by djalma2k** [comment]
@houqp I know that probably it isn't a relief but with coolreader by vlasovsoft is happening the same, at least to me :/
Anyway, I did 2 battery test using gimp and using an imagemagick's command: "mogrify" to apply "software dithering" to a test images and see the results shown in a real eink device.
Test1 (8bits images transformed using  gimp):
http://postimg.org/gallery/3331zw9ss/
```
$ identify *
color_index_optimum_palete_16.jpg JPEG 600x900 600x900+0+0 8-bit sRGB 126KB 0.000u 0:00.000
color_index_optimum_palete_16_with_dither_2.jpg[1] JPEG 600x900 600x900+0+0 8-bit sRGB 122KB 0.000u 0:00.000
color_index_optimum_palete_16_with_dither_3.jpg[2] JPEG 600x900 600x900+0+0 8-bit sRGB 129KB 0.000u 0:00.000
color_index_optimum_palete_16_with_dither_3_transparency_on.jpg[3] JPEG 600x900 600x900+0+0 8-bit sRGB 129KB 0.000u 0:00.000
color_index_optimum_palete_16_with_normal_dither.jpg[4] JPEG 600x900 600x900+0+0 8-bit sRGB 124KB 0.000u 0:00.000
cover.jpg[5] JPEG 600x900 600x900+0+0 8-bit sRGB 138KB 0.000u 0:00.000
grey_scale_16.jpg[6] JPEG 600x900 600x900+0+0 8-bit Gray 256c 134KB 0.000u 0:00.000
grey_scale_full.jpg[7] JPEG 600x900 600x900+0+0 8-bit Gray 256c 121KB 0.000u 0:00.000
grey_scale_index_1_bit_with_dither_3_transparency_on.jpg[8] JPEG 600x900 600x900+0+0 8-bit sRGB 128KB 0.000u 0:00.000
grey_scale_index_1_bit_with_dither_normal.jpg[9] JPEG 600x900 600x900+0+0 8-bit sRGB 125KB 0.000u 0:00.000
grey_scale_index_palete_16.jpg[10] JPEG 600x900 600x900+0+0 8-bit sRGB 124KB 0.000u 0:00.000
grey_scale_index_palete_16_with_dither_2.jpg[11] JPEG 600x900 600x900+0+0 8-bit sRGB 126KB 0.000u 0:00.000
grey_scale_index_palete_16_with_dither_3.jpg[12] JPEG 600x900 600x900+0+0 8-bit sRGB 125KB 0.000u 0:00.000
grey_scale_index_palete_16_with_dither_3_transparency_on.jpg[13] JPEG 600x900 600x900+0+0 8-bit sRGB 125KB 0.000u 0:00.000
grey_scale_index_palete_16_with_dither_normal.jpg[14] JPEG 600x900 600x900+0+0 8-bit sRGB 126KB 0.000u 0:00.000
rgb_16.jpg[15] JPEG 600x900 600x900+0+0 8-bit sRGB 134KB 0.000u 0:00.000
```
Only looks good images with dither applied. (except images with 1bit(black-white)).
Test2 (Applying over this images the following command:mogrify -colors 16 *) (Seems like mogrify applied auto dithering with some parameters and probably colors is one of them)
With Test2 the original cover image and the "grayscale full" image look good in the eink device.
Regards.
PS: grey_scale_16 means that the original image is posterized to a 16 levels of grey.

**Comment by houqp** [comment]
I just tried forcing CREngine to do 4bpp rendering on my kobo and the result looks way better than 8bpp :) @djalma2k were you running coolreader in 4bpp mode?

**Comment by djalma2k** [comment]
@houqp No, no, no, sorry about confusion, I was talking about the standar mode (8 bits I suppose). I dont know how to set it to 4 bits :/

**Comment by houqp** [comment]
Nice, let's implement the dynamic BPP settings first then ;)

**Comment by NiLuJe** [comment]
Yep, I can clearly see a standard ordered dithering pattern in that 4bpp screenshot, which is good, means CRe has a away to do it. (And while ordered dither isn't perfect, it's probably the cheapest method when you don't know the exact target palette... Which, technically, we do here, which is why doing it the right way via ImageMagick [which is what I do for the ScreenSavers hack on Kindles, and on calibre's side for my Kobo] looks even better)

**Comment by djalma2k** [comment]
@NiLuJe Thanks 4 your explanation and your IM batch (and bash :P ) processing script. :+1:  You probably save me a lot of time of checking this in the future... :)))
Regards.

**Comment by NiLuJe** [comment]
@poire-z / @Frenzie : So, err, I don't know why, but I spent the night playing with ordered dither algorithm, and after a few false starts, I ended up doing what I should have done from the start, which was looking at what IM actually does.

So, err, I imported the algo [into FBInk](https://github.com/NiLuJe/FBInk/commit/12dad2a3b32a23a5b53687f8d7e41f2c2344a083) to test, and it works pretty nicely, and it doesn't murder performance.

So, TL;DR: I can (I think) fairly easily plug that into CRe, much like what was done for nightmode, but I have a few questions.
The best place to put that is probably *during* image decoding or blitting, instead of another "loop over a rectangle" pass (sidebar: that's true of the nightmode inversion, too, technically).
That's easy enough for CRe, but for the rest our our UI (i.e., ImageWidget), that's slightly more annoying, as we can only do it during blitting.
That'd imply another couple of blitting function (setDitheredPixel/setpmulDItheredPixel), and duplicate that in the C port.
Or add yet another "loop over a rectangle" pass with a simple dither_rect function.

What do you guys think?

Also, sidebar: ideally, the cover thumbnails should be stored *dithered*, but I don't remember exactly when/how they're rendered and how they're stored, so that's one thing to look at.

And, sidebar 2: When doing a "show fullscreen cover" for an ePub, CRe just passes the raw jpeg data, it doesn't render it, right? We just pass that to mupdf, and we get a BB back, right?

**Comment by poire-z** [comment]
> instead of adding another "loop over a rectangle" pass (sidebar: that's true of the nightmode inversion, too, technically).

Yeah, that was just a courtesy to night mode users: you want images inverted-invertedback, you have them, you don't need to know it's a little bit slower because of another pass (but as it's just on a single page rendering, when it has images, it's hardly noticable). (Well, that was either that, or spending a few nights with the various format decoding code and Ms Maths)

> that's slightly more annoying, as we can only do it during blitting.
That'd imply another couple of blitting functions (setDitheredPixel/setpmulDItheredPixel), and duplicate that in the C port. >_<".
Or add yet another "loop over a rectangle" pass with a simple dither_rect function.
 
Well, in the more common non-night mode case, I'd rather have things fast (as they are now, after you had killed the many _loop over a rectangle_ recently :) as I'm not than sensitive to the absence of dithering.
But again, it's on a page by page basis, or when showing some images, so we are already expecting the small delay needed by image rendering. So, I guess we wouldn't really notice an additional "loop over a rectangle" (except when ultra zooming in ImageViewer, were we already build a super huge BB in memory just to crop into it.)
So, either way :)

> Also, sidebar: ideally, the cover thumbnails should be stored dithered, but I don't remember exactly when/how they're rendered and how they're stored, so that's one thing to look at.
And, sidebar 2: When doing a "show fullscreen cover" for an ePub, CRe just passes the raw jpeg data, it doesn't decode/render it, right? We just pass that to mupdf, and we get a BB back, right?

Right. All the `ZZZdocument:getCoverPageImage() ` get what they can from the underlying library (jpg or png file raw content from cre), and return a BB.
Also see https://github.com/koreader/koreader/issues/4774#issuecomment-471672118 , https://github.com/koreader/koreader/pull/4625#issuecomment-465680558 and https://github.com/koreader/koreader/pull/4541#issuecomment-459841150

**Comment by Frenzie** [comment]
Incidentally, I noticed some ugly-ish image display in crengine on a regular screen recently. Hold on…

![Screenshot_2019-04-07_10-25-41](https://user-images.githubusercontent.com/202757/55680844-8a42c280-591f-11e9-9be7-5cc2f297b284.png)
![Screenshot_2019-04-07_10-25-48](https://user-images.githubusercontent.com/202757/55680845-8a42c280-591f-11e9-9e98-e8f07c2589dd.png)

**Comment by NiLuJe** [comment]
That looks like nearest neighbor scaling artefacts, and that's a very fine
test case for scaling artefacts (leaves, the lines of the eiffel tower). I
don't actually recall what CRe uses when scaling, but that's probably it.

If you pull the cover and open it in KOReader, we're using nearest neighbor
when there, too (bb scale) vs. Mupdf in the show cover view.

**Comment by Frenzie** [comment]
Oh right, my old friend nearest neighbor. :-P

I guess I figured crengine would use something nicer (like MuPDF).

**Comment by NiLuJe** [comment]
It's slightly less problematic in practice because we tend to never need
scaling on actual hi dpi devices, but, yeah, not great.

Less trivial to implement, too ;p.

**Comment by Frenzie** [comment]
It's still usually scaled, even on the Kobo Aura One format where this particular photo is almost the native resolution. It's just looks less bad. ;-)

**Comment by NiLuJe** [comment]
Yeah, scaling is another kettle of fish entirely...

After looking around a bit, doing it right takes time. Stuff that does it really fast is genrally using SIMD or threading, which is a hard pass for us, as none of the stuff I looked at actually have NEON implementations (zimg, Pillow-simd; vips).

imlib2 does some arcane magic that might not be too bad in terms of perf. but I don't understand a lick of it. IIRC, that's what's Qt4/Qt5 scaling is based on. It might also be what MuPDF's is using/based on.

So, the easiest test I could do is plug stb_image_resize into FBInk, and see how hard it was hitting ;p.

```diff
diff --git a/fbink.c b/fbink.c
index 49c7d90..1286c2c 100644
--- a/fbink.c
+++ b/fbink.c
@@ -60,6 +60,11 @@
 #      pragma GCC diagnostic ignored "-Wsuggest-attribute=pure"
 #      include "stb/stb_image.h"
 #      pragma GCC diagnostic pop
+#define STB_IMAGE_RESIZE_IMPLEMENTATION
+#define STB_IMAGE_RESIZE_STATIC
+//#define STBIR_SATURATE_INT
+#define STBIR_MAX_CHANNELS 4
+#      include "stb/stb_image_resize.h"
 #endif
 
 #ifdef FBINK_WITH_OPENTYPE
@@ -6068,8 +6073,17 @@ int
                return ERRCODE(EXIT_FAILURE);
        }
 
+       // Scale it via stbir
+       unsigned char* sdata = NULL;
+       sdata = malloc(viewWidth * viewHeight * req_n);
+       if (stbir_resize_uint8(data, w, h, 0, sdata, viewWidth, viewHeight, 0, req_n) != 1) {
+               WARN("Failed to rescale image data");
+               rv = ERRCODE(EXIT_FAILURE);
+               goto cleanup;
+       }
+
        // Finally, draw it on screen
-       if (draw_image(fbfd, data, w, h, n, req_n, x_off, y_off, fbink_cfg) != EXIT_SUCCESS) {
+       if (draw_image(fbfd, sdata, viewWidth, viewHeight, n, req_n, x_off, y_off, fbink_cfg) != EXIT_SUCCESS) {
                WARN("Failed to display image data on screen");
                rv = ERRCODE(EXIT_FAILURE);
                goto cleanup;
@@ -6079,6 +6093,7 @@ int
 cleanup:
        // Free the buffer holding our decoded image data
        stbi_image_free(data);
+       free(sdata);
 
        return rv;
 #else
```

The answer would be: pretty hard. Roughly 2s *at best* to resize 1440p to 1080*1440.

Also, we *probably* can't do that (or any convolution filters, AFAICT) *during* the decoding, because maths. At least I certainly can't xD.

So, yeah, not an easy task ;).

Unlike (ordered) dithering, which is basically one pixel in, one pixel out ;).

**Comment by NiLuJe** [comment]
Okay, played with Qt's scaling this afternoon.

We end up around the ~300ms mark, with potentially a good third of that being having to go through a new buffer ;).

A few quirks with the code as it stands:

* I obviously had to rip it out of Qt5, so it's a bit of a mess, and will probably conflict with actual Qt5 since I don't do C++ namespace shenanigans, and I didn't rename anything ;).
* It only accepts RGB/RGBA input (i.e., BBRGB24 or BBRGB32), and always outputs RGBA.
* It features NEON variants... but they happen to be slower in every case I tested (upscale/downscale/rgb/rgba). o_O. Unless I'm doing it wrong, I don't tjink ti's an alignment issue either, as I tried to do this right.

**Comment by NiLuJe** [comment]
Sidebar: I don't particularly like it as a "storage" scaler, as it's on the blurry side of things, but it is fast, so that's perfect for a "display" scaler ;).

**Comment by NiLuJe** [comment]
Messy code in [FBInk's qimagescale branch](https://github.com/NiLuJe/FBInk/tree/qimagescale) ;).

**Comment by NiLuJe** [comment]
The main issue in CRe's case being we can't scale *during* decode, unlike what's currently being done.

Which means we'd have to re-loop at the end of decoding, *AND* do every bit of processing that's currently being done line-by-line at that time, too, because we both need the RGBA input, and dithering/grayscaling needs to be the final step.

That won't be particularly pretty, and it probably won't be very efficient either.

Should I bother with this? (Scaling, I mean. Dithering is trivial ;)).

**Comment by NiLuJe** [comment]
Good news: SIMD is not slower, I'd just fucked up my ifdefs, which ended up running *both* code variants... -_-".

Also, everybody and their uncle is storing image data in 32bpp buffers, so the fact that this is what it was expecting was only an issue for FBInk. Which I just fixed, so, you can now feed it anything, stbi will convert to 32bpp. This fixes ignore_alpha, which otherwise was repeating the first quarter of the image on the right edge of the screen ;).

**Comment by poire-z** [comment]
(I don't undestand everything :| but I trust your decisions :)

> That will basically scale anything you feed it to full-screen

You mean that for dithering a 20x20px image, the code needs to scale it full screen (so, mallocing a good amount of memory) to do its stuff? :|

> Sidebar: I don't particularly like it as a "storage" scaler, as it's on the blurry side of things, but it is fast, so that's perfect for a "display" scaler ;).

Just a note about CoverBrowser: it will scale the cover BB to the "prefered" size (so, mosaic, or list size, depending on what mode you selected), and store it into sqlite db. When used to display in History, it may rescale that (because FileBrowser and History thumbnails may differ by a few pixels, because of the surrounding layout differences, title, etc...)

**Comment by NiLuJe** [comment]
No, that full screen scaling comment was specifically about how it's used by the test FBInk branch ;).

In CRe, dithering is not a concern, it can be done at the time grayscaling is currently done. One pixel in, one pixel out.

Scaling will need to be done onEndDecode, and will need a malloc for a 32bpp buffer of the scaled dimensions.

**Comment by NiLuJe** [comment]
Hmm, that cover browser thing would indeed make storing those dithered the wrong thing to do, then... ;).

**Comment by NiLuJe** [comment]
Okay, in CRe-land, dithering is a go in my master branch.

Now for the fun/ugly part or mangling everything for the added scaling pass...

**Comment by poire-z** [comment]
Come on, 4 lines of code to do the dithering?! And you called that complicated ! :)
Looks clean to me :) (even if I don't understand a pixel to all that and the Wikipedia page... my maths are long gone...)

**Comment by NiLuJe** [comment]
:D

Yeah, I have yet to figure out how to do LUTs right in Lua when it'll come time to do that in the Lua blitter, so, not out of the woods yet ;p.

**Comment by NiLuJe** [comment]
![Smoothie](https://user-images.githubusercontent.com/111974/56067282-db691100-5d7a-11e9-8fc2-03e709d63787.png)

I have a problem.... It's faster than the nearest-neighbor scaler :D.

**Comment by NiLuJe** [comment]
(That probably won't be true on ARM, but, hey, I take what I can get :D).

Not quite ready yet, as my test ebook with a PNG is rendering the image unscaled, so I'll have to check what's happening there... ;).

**Comment by NiLuJe** [comment]
False alarm! It's faster because no scaling was done at all :D.

**Comment by NiLuJe** [comment]
Oh, of course >_<".

I never actually have an input buffer with the full image, I only get a single line.
Need to construct it myself during a LineDecode pass if smoothscale.

**Comment by NiLuJe** [comment]
Surprisingly, it works much better when you start actually processing the data you want, instead of the data you *thought* you had xD.

**Comment by NiLuJe** [comment]
![Smoothie_ForReal](https://user-images.githubusercontent.com/111974/56070933-225f0280-5d8b-11e9-8eab-b46191f9a6d0.png)

Okay, for real this time ;p.

It's barely any slower on x64 (it's around 10ms with nearest-neighbor), we'll see how it fares on ARM ;).

**Comment by NiLuJe** [comment]
Okay, toggleable at will with the base/frontend changes from my cre-img branches ;).

**Comment by poire-z** [comment]
Looks good.
I just wonder if we'll really need a toggle for that in the bottom menu. It's good for testing, but once you're ok with it, it should either be the default (if not too slower), or a setting in the top menu. It feels like it's not a setting you would enable or disable _per document_ (like most bottom toggles are, except may be the one for the status bar).

**Comment by NiLuJe** [comment]
Okay, nearly done with the base/front part, started testing on an H2O :).

Completely unscientific test on one single book:

No dithering, nearest neighbor: 225ms
Dithering, nearest neighbor: 240ms
Dithering, smooth scaling: 475ms

So, it's not the worst ;).

Dithering is pretty cheap in C, as expected.
I don't have numbers with the Lua blitter, but it's probably not very pretty, but it's essentially used in ImageWidget, so, that's not too bad.

The cost of scaling isn't too bad, but the jump in quality is often much less visible than what we get from dithering, so I am inclined to keep it as a non-default, per document setting, since it entirely depends on the source images and the target resolution ;).

**Comment by NiLuJe** [comment]
Oh yeah, the Lua BB version of dithering is getting *trounced* by the C BB version :D.

**Comment by houqp** [comment]
time to replace Lua BB with C BB for all platforms? :P

**Comment by NiLuJe** [comment]
Yep, that's the plan, nightmode being nonfunctional was kind of the last blocker now that everything's @ 8bpp ;).

**Comment by NiLuJe** [comment]
And here's a [Kobo test build](http://files.ak-team.com/niluje/kopub/koreader-kobo-arm-kobo-linux-gnueabihf-v2019.04-25-g06a73ba5_2019-04-13.zip) (and the matching [C BB](http://files.ak-team.com/niluje/kopub/kobo-cbb-v2019.04-25.tar.gz)) ;).

**Comment by NiLuJe** [comment]
Re: smooth scaling. It might actually have a more visible intact on !eInk platforms, which thankfully enough, should generally be beefier, so the perf impact will be less prominent ;).

**Comment by NiLuJe** [comment]
Also, note to self re: switching to the C BB. Double-check that it won't horribly crash when it's being replaced during an OTA update. It has a tendency to when being replaced manually (because I guess the ffi calls try to jump directly to function addresses that have moved in the new binary?).

**Comment by poire-z** [comment]
> And here's a Kobo test build (and the matching C BB) ;).

Had a quick tour, no issue except one:
With the lua blitter only, when Book info > Cover > Tap to display:
```
./luajit: ./ffi/blitbuffer.lua:316: attempt to call global 'dither_o8x8' (a nil value)
stack traceback:
    ./ffi/blitbuffer.lua:316: in function 'ditherpmulblend'
    ./ffi/blitbuffer.lua:876: in function 'setter'
    ./ffi/blitbuffer.lua:1003: in function <./ffi/blitbuffer.lua:995>
    ./ffi/blitbuffer.lua:1089: in function 'blitFrom'
    ./ffi/blitbuffer.lua:1149: in function 'ditherpmulalphablitFrom'
    frontend/ui/widget/imagewidget.lua:367: in function 'paintTo'
    frontend/ui/widget/container/centercontainer.lua:24: in function 'paintTo'
```

I'm not able to notice any change with Image scaling: fast vs best - but that may be just my eyes limitations :)
Also, no real change in the Blitting took... timings whether lua or C blitting.

(I won't be able to test or review next week, so here's one in advance:)
Since https://github.com/koreader/koreader/pull/4580#issuecomment-462659161 by @houqp , we _should not (?)_ use `Screen` in the *document modules, but `CanvasContext` instead - so, there were the needs to add some level of indirection for each stuff that came from Screen.

**Comment by NiLuJe** [comment]
@poire-z : Ups, should be fixed now, thanks! :).

I'll admit having a hard time figuring out what actually belongs in CanvasContext.
All of those are arguable user-toggled, not really hardware-specific (even hw_dithering, since it can be disabled).

I'll also add that a crapload of stuff is still using Screen: for stuff that *is* in CanvasContext, too ;).

**Comment by houqp** [comment]
Sorry about the confusion. If it doesn't make sense to you, then feel free to just ignore it for now. I can help refactor after it's merged.

The goal is to remove any hardware specific module (screen, device, etc) from document related module's dependencies.

The expectation of adding that indirection is to make other developers more productive. If it's not achieving the goal, then I think it's OK to break it for now. As time goes, hopefully it will become clearer why this separation is needed. I am only at the first step of decoupling the core :)

**Comment by NiLuJe** [comment]
@houqp : To be perfectly honest, I'm the wrong guy to test this kind of stuff, as *any* kind of extra indirection is liable to annoy me more than anything (I am *terrible* at OOP ;)).

But that's just me, and I certainly get the idea behind the thing ;).
