### ISSUE TITLE
Missing Wi-Fi prompt in calibre wireless connection

### ISSUE THREAD

**Issue by m4kh** [koreader/koreader#1909]
- KOReader version: koreader-nightly-20160315
- Device: Kobo Glo HD
#### Issue

If Wi-Fi is turned off, the calibre wireless connection shows the error `Cannot connect to calibre server`. In this case, it might be more intuitive to first ask for turning Wi-Fi on. Similar functionality is already implemented for `OTA update`.
#### Steps to reproduce

If Wi-Fi is turned off, hit `Connect` in the `Calibre wireless connection` menu. A prompt appears showing `Cannot connect to calibre server`.

**Comment by KenMaltby** [comment]
The error message is not misleading, KOReader cannot connect the the server with the Wi-Fi off.  

But - it sounds like it is missing the Wi-Fi prompt, that the other functions that rely on the Wi-Fi have.

**Comment by m4kh** [comment]
That's what I tried to say. Thanks for the correction. I will change the title of the issue accordingly.

**Comment by chrox** [comment]
This is by design or at least by current limitation. We check wifi connectivity not by checking if the device has an IP address but by trying to connecting to the dns server. So if we are in a local network that are not connected to internet, the wifi status check will fail, but we still can use calibre wireless connction. That's why we don't check wifi status when connecting calibre server.

**Comment by KenMaltby** [comment]
To use the calibre wireless functions, not only must the device's WiFi be on, but the appropriate wireless function of calibre must be running.  Perhaps there is something that can be checked for each of the functions?
