### ISSUE TITLE
Suggestion: add "Open last opened document" in file manager

### ISSUE THREAD

**Issue by SsnL** [koreader/koreader#1925]
I often find myself accidentally open file manager. In such cases, I would love if I can just reopen last document from there, rather than either reopen KOReader entirely, or search in file manager.

Thanks.

**Comment by Frenzie** [comment]
Note that the Pokeball menu > History effectively serves this purpose.

**Comment by SsnL** [comment]
Ah dumb me. Never noticed that option before.

**Comment by Frenzie** [comment]
To be fair, who the heck knows what Pokeball means. =P

I'll close this then.

**Comment by houqp** [comment]
> To be fair, who the heck knows what Pokeball means. =P

LOL. Someone should propose a better icon.

There is also an option in filemanager to automatically open last viewed book. You can hold on the menu item to set it as the default behavior.

**Comment by Frenzie** [comment]
> LOL. Someone should propose a better icon.

History would be a clock or an hourglass, but since it's a menu with other things as well I don't have a ready suggestion. Since our icons hail from [here](https://github.com/Templarian/WindowsIcons/tree/master/WindowsPhone/svg) maybe it could be worthwhile to take a look at them all in order to come up with a few suitable candidates.

> There is also an option in filemanager to automatically open last viewed book. You can hold on the menu item to set it as the default behavior.

Speaking of which, out of a small sampling among a handful of my friends and acquaintances, everyone seems to agree that should be the default. See e.g. @ersi-dnd's post [here](http://thedndsanctuary.eu/index.php?topic=1853.msg52622#msg52622). Personally I'm not sure how much it matters given that I tend to simply suspend within the book I'm reading.

**Comment by ersi-dnd** [comment]
Actually, I am satisfied enough when there's an _option_ to set the app to open the last book on startup. Koreader already has this option.

I make my comments regarding e-readers while having very little familiarity with them. I have only very recently acquired a Pocketbook and I don't know how the interface of other e-readers differs from it. When I installed Koreader, I tended to expect it to look and behave the same as the default inbuilt app, but this is not a smart expectation. 

At best, Koreader should have the configurability to approximate the behaviour of the inbuilt app. It's less relevant to behave the same out of the box.

**Comment by Frenzie** [comment]
In any case, fwiw everyone* has enabled that option. But yeah, I think it's fine as it is.

* Um, 3 people, 4 including myself. =P

**Comment by houqp** [comment]
> History would be a clock or an hourglass, but since it's a menu with other things as well I don't have a ready suggestion. Since our icons hail from here maybe it could be worthwhile to take a look at them all in order to come up with a few suitable candidates.

That section was meant to be misc, so we need to pick an icon to reflect that.

> In any case, fwiw, everyone* has enabled that option. But yeah, I think it's fine as it is.

Fun fact, I also recently enabled it on my kobo.... If we are going to change the default behavior, we need to make sure it does not break the existing options in KUAL menu. Or even better, have an intro widget like http://introjs.com/ to guide user through the new changes.
