### ISSUE TITLE
Investigate font rendering quality in CREngine

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#1929]
Quote from the discussion in #1313:

> As for Koreader vs CoolReader question --- no, it is not because of UI, but for some unknown reason CoolReader seems to renger the glyphs slightly better (for some fonts that I use, like Arno Pro and Academy).

**Comment by NiLuJe** [comment]
AutoHint vs. BCI (or even... unhinted?!)?

cf. https://github.com/koreader/koreader-base/pull/199/commits/ed43255b1912d4e388a096ef0c19027a6bea32ae

**Comment by frankyifei** [comment]
I noticed a little difference. Fonts are handled using fontconfig in CoolReader, does it relevant?

**Comment by houqp** [comment]
AFAIK, frontconfig only helps discovering fontface files and has nothing to do with the rendering bit. What @NiLuJe points out is more likely the cause. @frankyifei were you able to spot the rendering difference from CR and KOR? I haven't had time to test it on my side yet.

**Comment by frankyifei** [comment]
a screenshot, very little difference. 
![fonts](https://cloud.githubusercontent.com/assets/8104251/14132509/33618cb8-f68e-11e5-9d6e-525a81be8d57.jpg)

**Comment by houqp** [comment]
I don't see much difference from the screenshot. @tigran123 did mention it only happens to some specific font faces though.

**Comment by Frenzie** [comment]
@houqp fontconfig can provide the configuration for something like `props->setInt(PROP_FONT_HINTING, 2);` though (not saying it does in our case)

**Comment by NiLuJe** [comment]
If you want to see dramatic differences between bytecode hinting and the
autohinter, check with Consolas, if you have a Win7+ somewhere ;).

As for fontconfig, yeah, it's used to handle choosing font families /
styles, and eventually rendering settings, like hinting. No idea to which
extent CRe actually uses it though.

**Comment by NiLuJe** [comment]
Some differences also tend to be much more marked on e-ink than on an lcd
screen...

**Comment by NiLuJe** [comment]
If CR is using an older freetype version than ours, and the original report
was about a CFF font, and not a truetype one, there have been massive
changes (for the better) when hinting those natively.

**Comment by houqp** [comment]
Looking at lvfntman.cpp, looks like it's just using FC for the following font attributes: ` Font family:%s style:%s weight:%d slant:%d spacing:%d file:%s`.

@NiLuJe isn't auto hinting suppose to produce better result? Looks like coolreader is using autothint as default hinting setting.

Anyway, I think we should first find a font face that we can use to reproduce the difference.

**Comment by NiLuJe** [comment]
I tend to like what the autohinter does, yeah, and in fact, I'm using it a
lot on my desktop (I have a fairly complex ft + fc setup ;p).

But on e-ink devices, provided the bytecode is halfway decent, native
hunting will often produce much sharper results, which both looks better
and are less prone to ghosting.

But since some fonts have truly terrible bytecode, we also default to the
autohinter to avoid glaring rendering issues...

**Comment by NiLuJe** [comment]
A few examples, although a bit less dramatic since I'm using a SPR-enabled FT build, which more closely follows the MS ClearType guidelines, which means it tends to smooth over some of the native truetype hinting I was talking about.

With KOReader's build, since we don't care about SPR, we get a differently tweaked native hinter (v35 vs. v38, IIRC), which will expose some more issues.

First is Consolas, which is much sharper/bolder w/ BCI, and then Gentium Book Basic (which happens to be utterly mangled w/ the v35 BCI hinter, which you can't really see here :D).
![screenshot_20160331_154735](https://cloud.githubusercontent.com/assets/111974/14177905/afb1dc30-f758-11e5-8cb4-5ee637c79491.png)
![screenshot_20160331_154851](https://cloud.githubusercontent.com/assets/111974/14177906/b30c8fa6-f758-11e5-84e4-5b5c51b47101.png)

**Comment by NiLuJe** [comment]
Or B&H's Luxi family, which is even more broken w/ v35:

![screenshot_20160331_155731](https://cloud.githubusercontent.com/assets/111974/14178074/6661ff32-f759-11e5-8b23-ab3d923abaf8.png)
![screenshot_20160331_155801](https://cloud.githubusercontent.com/assets/111974/14178079/6926f27c-f759-11e5-8c19-93d49dcb7587.png)

**Comment by NiLuJe** [comment]
One thing I'm not sure about how it all works out is if FT ever outputs more than 16 shades of grey, and how we actually dither or remap that to the right eInk palette...

**Comment by djalma2k** [comment]
Can someone test with the embedded text in the following book?
`http://m.zbigz.com/myfiles?url=magnet:?xt=urn:btih:0D7A00D965E2F3C8EFB7E026D4408BE6F29F1E10&dn=EPL_Los_piratas_fantasmas&tr=http://tracker.tfile.me/announce&tr=http://91.121.54.8:6969/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.publicbt.com:80&tr=udp://open.demonii.com:1337/announce`

It don't seems "clear" enought to me (if you doing a comparison with a pc monitor and calibre (~100ppp). I know that images aren't at the same scale but... :/
Kobo glo HD 300ppp:
![reader_2016-mar-31_203210](https://cloud.githubusercontent.com/assets/17313916/14187139/d5b55546-f781-11e5-8b05-42fe7426b0e7.png)

vs

![nitidez_2_calibre](https://cloud.githubusercontent.com/assets/17313916/14187178/097a8b3a-f782-11e5-8fc0-37cc2e97d414.jpg)

Regards.

**Comment by NiLuJe** [comment]
The chapter titles will probably get mangled with anything not using native hinting, that's to be expected with such peculiar fonts.

**Comment by djalma2k** [comment]
Ok, following @KenMaltby advice for #1936, I just was testing with "Set render style" menu option and setting this to ~~""No style"", I got this:
![reader_2016-apr-01_001610](https://cloud.githubusercontent.com/assets/17313916/14192792/33c51bb2-f7a0-11e5-95ca-0425004b5ebe.png)
Then, IMHO It's no related to this.
Sorry if I've wasted your time with this little test... :/
Regards.

**Comment by houqp** [comment]
> One thing I'm not sure about how it all works out is if FT ever outputs more than 16 shades of grey, and how we actually dither or remap that to the right eInk palette...

We are not doing any dithering or remapping for eink. By 16 shades of grey, you mean 4 bit bitmap?

**Comment by NiLuJe** [comment]
No, I was thinking of the actual 16 shades of grey (which, granted, would fit in a 4bit bitmap ;p).

**Comment by tigran123** [comment]
A year later I am again raising this as now (with latest Koreader + latest CoolReader on Kobo Aura One) again this is becoming visually quite obvious. CoolReader's rendering of fb2 files was superior to Koreader's (I tried to setup identical parameters of course) but I had no choice but to use Koreader for reading fb2 because CoolReader currently does not support highlights and I always record the typos and update the original (on lib.rus.ec) so that others benefit from my corrections. With CoolReader this is impossible, but with Koreader you just highlight the misspelled word and go on reading. And when the whole book is finished you fix all the errors in the physical file on the computer.

So, now, I need to remember how to make screenshots via some strange swipe in Koreader and also in CoolReader, so I can present the proof for all to see. The font used was Paratype Academy (as it is most pleasing for reading Russian fiction books :)

**Comment by poire-z** [comment]
There's a new toggle in the bottom menu "**B**" since a few weeks ago: _Font hinting_, which allows you to set different hinting methods as dicussed above in this issue (Native = BCI, Auto = Freetype algorithm)
"Off" may give you "_letters in a word a little bit closer_ ", and may be Native will work well with your font, if it has good hinting included.

**Comment by Frenzie** [comment]
> So, now, I need to remember how to make screenshots via some strange swipe in Koreader and also in CoolReader, so I can present the proof for all to see.

Just top left to bottom right should do the trick.

**Comment by KenMaltby** [comment]
... or bottom right to top left.

**Comment by tigran123** [comment]
I managed to make the screenshot in Koreader, but the screenshot function in CoolReader (recently added) produced garbage (probably because it was untested on Kobo Aura One's very high resolution screen). I emailed to Sergey Vlasov showing the resulting screenshot.

**Comment by tigran123** [comment]
Ok, here are the promised images, only made on Aura HD, not Aura One because I have installed the very latest CoolReader (with the fix for screenshot function) on the Aura HD only, at the moment.

First the CoolReader (version `pbchess_2017.09.30_kobo.zip`):

![CoolReader](http://www.bibles.org.uk/screenshots/coolreader.png)

Koreader (version `koreader-kobo-arm-linux-gnueabihf-v2015.11-558-g3df3631`) with Font hinting set to Auto:

![Koreader-Auto](http://www.bibles.org.uk/screenshots/Koreader-Auto.png)

Koreader with Font hinting set to Native:

![Koreader-Auto](http://www.bibles.org.uk/screenshots/Koreader-Native.png)

Koreader with Font hinting set to Off:

![Koreader-Auto](http://www.bibles.org.uk/screenshots/Koreader-Off.png)

IMO, only the "Auto" setting matches the rendering quality of CoolReader. Both "Native" and "Off" are inferior: e.g. look at the word "было" on the second line --- its "o" is the wrong size and sticks out. Also, the distance between "ю" and "р" in the word "юрту" on the next line is too big in "Native". Also, some other such minor imperfections can be found in both "Native" and "Off", but "Auto" seems to match CoolReader's quality. So, given the fact that Koreader supports highlights (and CoolReader at the moment does not), I am switching to Koreader even for reading ebooks, except for those very few cases which CoolReader handles and Koreader doesn't (e.g. that enormous epub book by Messiah on Quantum Mechanics which Koreader now opens (a year ago it couldn't) but is so slow to switch to it and sometimes crashes when waking up with it opened).

**Comment by Frenzie** [comment]
> IMO, only the "Auto" setting matches the rendering quality of CoolReader. 

But the misleadingly named auto is already the default. Or was that still different last year?

If auto looks better than native, then either the font designer didn't do a good job or they disagree with you about what looks better. :-P In this case it seems to be regular intended overshooting like a font designer would want, while the auto-hinting actually fails to put such proper typography into practice. However, it looks like the application of hinting overshoots too much, even though the results should be minimal at these resolutions. I'd go with off on this one (and possibly on everything over 250 DPI or so).

**Comment by tigran123** [comment]
Here are two more screenshots, these ones made on the Kobo Mini.

This is Koreader:
![Koreader-Mini](http://www.bibles.org.uk/screenshots/Koreader-Mini.png)

This is CoolReader
![CoolReader-Mini](http://www.bibles.org.uk/screenshots/CoolReader-Mini.png)

So, now I see why CoolReader felt more comfortable at least on Kobo Mini --- because the letters are slightly bolder (but I did NOT select "bold" in CoolReader's Settings and, btw, if I select "bold" in Koreader's Settings then it will be far too bold, i.e. much heavier than in CoolReader).

**Comment by poire-z** [comment]
Closing this, as we added quite a few new settings to tweak font and text rendering (font hinting, font kerning, contrast), and more recent discussions about this have been done in https://github.com/koreader/crengine/pull/230 and https://github.com/koreader/crengine/issues/247.

**Comment by Frenzie** [comment]
And thank you for all that! :-)

**Comment by Frenzie** [comment]
Glad to hear it! And I agree, options are good. :-)
