### ISSUE TITLE
Long time waiting for ebook to be displayed after device start

### ISSUE THREAD

**Issue by mwozny123** [koreader/koreader#1949]
- KOReader version:
  I know this problem since I use Koreader, but I used workaround.  
  I'm currently using v2015.11-175
- Device:
  Pocketbook touch lux 3
#### Issue

Opening ebook (after device and then koreader start up) gets "stuck" on "Opening file XXX" info for a long time.
E.g. for [this 5mb PDF manual](http://www.x-plane.com/files/manuals/X-Plane_10_Desktop_manual.pdf) it takes nearly 5 minutes to disappear "Opening file XXX" info, and show last read page (here in the middle of book).
- Workaround: press next page button or tap touch a screen, couple seconds after  "Opening file XXX" is displayed, then ebook is displayed straight after.

For similar size Epub file ofter it's even longer. I remember once I had waited over 10minuts for epub, and workaround didn't work.
#### Steps to reproduce

(Re)start device, open Koreader, open PDF/Epub ebook.

**Comment by RedKage** [comment]
I just installed Koreader on my PocketBook Lux 3 (626) and I experience the same "issue."
Click on any ePub and I got this little popup

> ( i ) opening xxxx ...

And this thing sits there for a long time. But, if I tap the screen, or presse previous/next buttons, usually the popup dissapears after 5 secs.

Aside from this little bug (I guess) this popup does not indicate that something is going on. When I saw for the 1st time this popup I didn't know what it meant. Really. Seriously.
We'd need an hourglass animation or something to show us that the software is actively doing something. Because I was like "duh you are opening the stuff, obviously, I tapped on that thing."

**Comment by RedKage** [comment]
Possible duplicate here: https://github.com/koreader/koreader/issues/1155
And there:https://github.com/koreader/koreader/issues/1955

**Comment by houqp** [comment]
Yes, this issue has been filed before. The bad news is none of us has the device so it's very hard to debug :(

**Comment by houqp** [comment]
The animation though, it's a good idea. Probably worth a separate issue. To implement it, we need to make some major refactors in the core UI framework.

**Comment by RedKage** [comment]
Maybe adding a feature for the animation?
In the mean time simply adding an ellipsis (like "loading **...**") would indicate that something is going on. Could be easier to implement.

For debugging this, maybe I can do something? I'm more of a C#/.NET/ Micro$oft developer but I can manage on Unix fine. Is there anything I can do, a log I can pull off or something to help you guys?

**Comment by houqp** [comment]
Yeah, adding ellipsis makes sense. @RedKage , the line you need to change is at: https://github.com/koreader/koreader/blob/master/frontend/apps/reader/readerui.lua#L340. It's better to use the actual ellipsis symbol `…` instead of `...`.

@RedKage , is Pocketbook touch lux 3 running android? If so, do have access to adb logcat?

**Comment by RedKage** [comment]
No, the PocketBook aren't running on Android, it's some kinda custom Linux.
You want me to do a pull request for the ellipsis?

**Comment by houqp** [comment]
> No, the PocketBook aren't running on Android, it's some kinda custom Linux.
Do you have ssh access to the device? That will make debugging this issue a lot easier.

> You want me to do a pull request for the ellipsis?
Yep :)

**Comment by Frenzie** [comment]
Presumably fixed by #4712. If not, please reopen or create a new issue.
