### ISSUE TITLE
Koreader does not respect the .sdr file

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1962]
* KOReader version: koreader-nightly-20160413
* Device: Samnsung Galaxy Tab

#### Issue
I am syncing my books folder using Syncthing between devices. Syncthing works fine but Koreader does not like to pick up the page number where I left of from another device that is synced via syncthing. 

For instance I am on page 92 with a book on DeviceA, I see that the .sdr file is synced to the other device DeviceB. I also open the sdr file in a text editor to make sure the latest recorded page number is 92 on DeviceB. All that information seems to come from the DeviceA properly. But when I open the book on DeviceB, Koreader opens the page at 70 which is wrong. 

I even deleted the cache files in Koreader folder but that did not help.

#### Steps to reproduce
Open a book from a synched folder on an Android device, read for a while and close Koreader. Sync the folder and open the book with synced settings on another Android device using Koreader.

**Comment by Hzj-jie** [comment]
This is a legacy issue, since we prefer history files (in /history folder) instead of .sdr folder.
We plan to eventually remove history folder, but use only sdr folder. But now history list is still based on history folder. So it's not a simple change.
I will send out a very quick fix to prefer sdr folder first.

**Comment by gerroon** [comment]
@Hzj-jie 

It will be great if the sdr file given priority over other stuff as you mentioned. Thanks for looking into it.

**Comment by houqp** [comment]
Thanks @Hzj-jie for fixing it. @gerroon next release should pick up the fix.

**Comment by tigran123** [comment]
Hmmm, wait, if you rely entirely on the .sdr and abandon history directory then all the annotations support will stop working with readonly mounted micro sd cards? Isn't that a very serious problem? Please don't make it stop working with readonly location of books.

**Comment by KenMaltby** [comment]
Has anyone actually had any problem that relates to having the external uSD card mounted, or remounted as read/write?  I have remounted it with the start of KOReader for a long time, and encountered no related problems.

**Comment by NiLuJe** [comment]
Didn't we actually also fix the sdcard issue, making sure it's always mounted rw?

**Comment by KenMaltby** [comment]
Right, mnt/SD is now rw with KOReader active, just like I have had it.  There should be no "readonly location of books" that KOReader's "annotations support " would need to work with.

**Comment by tigran123** [comment]
Requiring that micro sd card is always mounted rw is a bad idea, because in the event of crash the card will be corrupted in the following sense: fsck.vfat will complain that backup boot block is not matching the original. Ok, a person who understands vfat filesystem (and who understands that the boot sector of a filesystem on a device which you are never going to boot from is irrelevant) will know how to fix it, simply by forcing fsck.vfat to copy one way or another. But still, technically, this is "data corruption" and I merely described the most benign scenario, but in practice you can get a real data corruption, i.e. of the actual data files written to in the .sdr directory.

@KenMaltby as for your question --- you can easily reproduce the problem by forcing a reboot via long press of the power button and then verifying the card with fsck.vfat. The problem will always occur, 10 out of 10 (unless you are particularly lucky :)

**Comment by KenMaltby** [comment]
I have had my mnt/sd remounted rw continuously since at least July of 2014.  I am sure I have rebooted that way a few times, I haven't encountered any problems or signs of  "filesystem/metdata corruption" .

**Comment by tigran123** [comment]
@KenMaltby Really? And it happens to me literally 10 out of 10 times which makes me believe that you simply haven't noticed the corruption. Have you actually executed fsck.vfat on the card manually after such forced reboot?

**Comment by KenMaltby** [comment]
I have it on good authority that doing so would provide the indication of a problem. Not that a backup mismatch would worry me that much.  Besides I seldom do much with Linux, I'm mostly a Windows guy. I haven't run into any problems rebooting and while I am not as sure of perfection, things appear to me to be steadily improving.  (Forcing me to make such a statement, may have tempted fate.)

**Comment by NiLuJe** [comment]
In any case, the fact that it's KOReader and not nickel which happens to be mounting the card rw does not make it *more* dangerous. FAT32 simply sucks and deals badly with power loss, that's a fact.

**Comment by tigran123** [comment]
@KenMaltby Ok, I am almost 100% sure that your card wouldn't pass fsck.vfat check. However, the real problem is actually twofold:

1. Reformatting the card and restoring the books from backup is, theoretically, no big deal. In practice, restoring a 100GB collection on a 128GB microsd can take several hours.

2. If you store all the annotations on microsd rather than onboard history then these will be lost when the card is reformatted. (ok, they can be copied before reformatting, but I wouldn't trust the data that came from corrupted filesystem).

I would actually advocate getting rid of .sdr support altogether and storing all the annotations in onboard history. There is no need to pollute the book repository (which should always be mounted readonly) with application-specific data. Data and applications should be kept separate. And '.sdr' is the part of application (like fonts or tessdata) and should be stored together with application, not with the data.

**Comment by NiLuJe** [comment]
The argument in favor of sidecar files vs. a centralized location is making it much, much easier to support cross-device synchronization.

**Comment by tigran123** [comment]
@NiLuJe Yes, you are right --- FAT32 deals badly with power loss, that's a fact. So, to avoid the consequences of this fact I suggest not to mount it readwrite. This is the reason why Kobo developers decided to have it readonly by default.

As for cross-device synchronization, interesting.... because this is important to me also (as I use multiple devices too). But I always assumed that such synchronization is impossible because the information stored would be device-specific (namely, screen-size specific) and so there is no benefit in trying to sync it at all. Are you saying that this assumption is false? I am willing to try it, but I would be VERY VERY surprized to learn that Koreader has become so sophisticated as to manage to handle annotations in a device-independent manner....

**Comment by NiLuJe** [comment]
I have the whole SSH/rsync & co running over WiFi or USB fine with my Kobo port of all my [http://www.mobileread.com/forums/showthread.php?t=254214](Kindle stuff).

I think some people started using syncthing for the sake of simplicity, too, so that also should be available somewhere on MR.

**Comment by houqp** [comment]
> As for cross-device synchronization, interesting.... because this is important to me also (as I use multiple devices too).

As @NiLuJe already mentioned, cross device synchronization is the main driver for introducing sdr directories. Another huge advantage is to better support moving files around. With the old history file, all file paths are hard-coded into the history file name, which means changing document location will break the document setting. Asking users to update the history file name manually is a very bad user experience since the device specific absolute path should not be exposed directly to them. Also imagine the case you have to move/rename one directory that contains hundreds of books, it will be very hard to update all the history files accordingly. sdr solves these problems perfectly.

> But I always assumed that such synchronization is impossible because the information stored would be device-specific (namely, screen-size specific) and so there is no benefit in trying to sync it at all. Are you saying that this assumption is false? I am willing to try it, but I would be VERY VERY surprized to learn that Koreader has become so sophisticated as to manage to handle annotations in a device-independent manner....

It's supposed to work out of box. At least I don't recall any book meta data is screen-size specific. If is any, we should take a look at it to see if we can make it work for any size.

> Btw, are you also saying that it is possible to have a centralized machine (running Linux with rsync, sshd etc) and then somehow hack usbnet script on Kobo to use WiFi rather than USB (and run dropbear on it or maybe something else as well, to make rsync work) and then rsync all Kobo devices remotely? That would be an ideal setup and the idea occurred to me a month ago, but I thought it is not possible and gave up. Maybe I should revisit it. That would be very convenient and then, yes, having .sdr support would be a bonus, not a liability. Even worth risking to have sd card rw :)

Yes, I know manhy people are doing this. @NiLuJe has his fancy setup, @chrox also wrote a KOReader sync service: https://github.com/koreader/koreader-sync-server.

**Comment by KenMaltby** [comment]
I would think the only element, that would be greatly effected by display on different devices, would be how to pass the displayed page, from device to device.  The same book on a 10.1" display using a small font might be on page 20 but that same progress location in the book might be page 200 on a 4" phone. 

I don't see how the book's metadata would be affected at all, unless you were talking about how the metadata were to be handled.

**Comment by houqp** [comment]
For books handled by CRengine (i.e. books without fixed pages), we track the progress by xpointer, which points to the element inside the document. For example, it can be a paragraph, an image or even a character. So it's typesetting agnostic. You should always be able to restore to the same location regardless of how many pages the book is rendered into.

For PDFs and DJVUs, we just track by page number, which is good enough ;)

**Comment by KenMaltby** [comment]
Right, so device dependency even less likely.

**Comment by gerroon** [comment]
Any word on this bug? There was the discussion about making the .sdr having higher priority over the history stuff.

thanks

**Comment by houqp** [comment]
@gerroon sdr should now has the highest priority now: https://github.com/koreader/koreader/pull/1965.

Are you still experiencing this issue?

**Comment by gerroon** [comment]
@houqp 
I am using Android. Is this in the latest available version of Android?

**Comment by houqp** [comment]
It should be. Any build after Apr 14, 2016 should has the patch in place.

**Comment by chrox** [comment]
Now there is no settings files in the history directory as implemented in #2063, sdr should the only source of truth. Please reopen this if you still have problem with the latest nightly release.
