### ISSUE TITLE
New logo, feedback

### ISSUE THREAD

**Issue by comradekingu** [koreader/koreader#2000]
- KOReader version: all
- Device: all
#### Issue

New logo
#### Steps to reproduce

![koreader](https://cloud.githubusercontent.com/assets/13802408/14938147/0f1cac02-0f1b-11e6-9649-0754af8f23c9.png)

**Comment by KenMaltby** [comment]
I guess the 2000 issue could be one where logo candidates are discussed.  

Not sure this four color logo would be best, maybe some others will appear over time.

**Comment by Frenzie** [comment]
There could be a color as well as a manually optimized b&w. That being
said, I don't know if pixels (however fake) give the right idea. :)
On Apr 30, 2016 10:17 PM, "Ken Maltby" <notifications@github.com> wrote:

I guess the 2000 issue could be one where logo candidates are discussed.

Not sure this four color logo would be best, maybe some others will appear
over time.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/koreader/koreader/issues/2000#issuecomment-215992433>

**Comment by chrox** [comment]
There is already one candidate for the Koreader Android port:
![image](https://cloud.githubusercontent.com/assets/751535/15265962/5339de8a-19c7-11e6-9db5-9dec8639c737.png)

**Comment by gerroon** [comment]
I cant read the "reader" part ;)

**Comment by pavlukivan** [comment]
@chrox that looks like logo for a camera...

**Comment by lenisko** [comment]
Lets see... we have K.O. in name then reader. Maybe some ebook reader with punching fist on screen ? :smile: 

also @chrox indeed, this one looks like for camera application

**Comment by AliLozano** [comment]
Si se aceptan sugerencias.. 
![koreader](https://cloud.githubusercontent.com/assets/1187993/15480270/3a9cea1e-20ea-11e6-90b9-c0ced4e282ec.jpg)

**Comment by AliLozano** [comment]
Or this:
![koreader2](https://cloud.githubusercontent.com/assets/1187993/15521717/d92c94a2-21d2-11e6-9d34-905717a550b1.jpg)

**Comment by houqp** [comment]
The flat design looks pretty neat :)

**Comment by chrox** [comment]
@AliLozano  Looks interesting. Could we make the icon more like a book, i.e. adjusting the aspect ratio?

**Comment by baskerville** [comment]
A slight variation around @AliLozano's work:

![koreader-small](https://cloud.githubusercontent.com/assets/159419/19831636/4f871286-9e0f-11e6-878f-061759a58556.png)

**Comment by houqp** [comment]
I like this one because it brings out both letters in KO ;)

**Comment by houqp** [comment]
Everyone on board with using @baskerville 's latest design? Of course, credits should be given to both @AliLozano and @baskerville  ;)

**Comment by Frenzie** [comment]
I definitely like the shapes, but maybe a little more color even though it'll look something like that on E Eink anyway? I like the colors proposed by @AliLozano. Also note that on the website I selected a bunch of pastels in the links, probably aided by Adobe Kuler: http://koreader.rocks/

(Not that the website has to stay the same or anything, but it could be an idea to check what goes with the website as much as any other angle.)

Besides that I think the gray is a little too gray. Making it all white or at least a lot brighter has more oomph to it. I'll refrain from firing up Inkscape although I'm sorely tempted. :-P

![4f871286-9e0f-11e6-878f-061759a58556](https://cloud.githubusercontent.com/assets/202757/24791341/06c1db42-1b7a-11e7-9a64-47b8d3c88497.png)
![4f871286-9e0f-11e6-878f-061759a58556-black](https://cloud.githubusercontent.com/assets/202757/24791579/f8d976a6-1b7a-11e7-91fc-7feff54e1365.png)

**Comment by retrue** [comment]
I like more Alilozano version and I have been playing a little with it, adding a big O too.
It has been edited with Mspaint, so look at the idea only, please.
![ko](https://cloud.githubusercontent.com/assets/18194241/24794486/273b2cdc-1b86-11e7-9507-d03e8a900a78.png)

**Comment by baskerville** [comment]
![koreader-logo-colors](https://cloud.githubusercontent.com/assets/159419/24827247/1b8f67ec-1c47-11e7-962d-e65b37d5194d.png)

**Comment by Frenzie** [comment]
I prefer the greenish teal in the middle.

1. Teal
2. Blue
3. Red

**Comment by baskerville** [comment]
![koreader-logo-big_medium_small](https://cloud.githubusercontent.com/assets/159419/24830304/da297300-1c83-11e7-95d7-ea00a33cc77e.png)

Teal, gray, monochrome.

**Comment by Frenzie** [comment]
Okay, I prefer teal over greenish teal. :-)

**Comment by houqp** [comment]
@retrue Alilozano version indeed looks better, however I think the letter O is very important here since it stands for `open`. Putting the `O` to the left makes the box too wide and doesn't look like a book anymore. That's why I think @baskerville 's adaption makes the most sense here.

@Frenzie I like the whiter font version too.

I prefer the gray color over teal. Because it is less distracting and gives me a very calm feeling. But I am also fine with teal.

**Comment by AliLozano** [comment]
Hi! Thanks you all. it's good that you liked the logo i've made, I like the @baskerville's version too, Sorry for haven't answer before, The work doesn't leave me, by other hand, my kobo/koreader died with a white screen, and I can't fix it :(. 
I've made some changes to @baskerville's version(removed shadows, because it could make the text ilegible in some devices and the corners more rounded) and besides I've created a square versión, for mobile icon.

PD: I've uploaded editable file as pdf, you are free for modificate it. :) 
![Logo Koreader Preview](https://cloud.githubusercontent.com/assets/1187993/24867591/480a25d6-1dd3-11e7-8df9-4daefa896606.png)

[koreader.pdf: Editable ](https://github.com/koreader/koreader/files/910447/koreader.pdf)

**Comment by Frenzie** [comment]
I think it's great, but what about the Keep Calm font's license? 

Here are a couple that might be more suitable license-wise:

http://www.tug.dk/FontCatalogue/sourcesanspro/
https://fonts.google.com/specimen/Hammersmith+One

**Comment by KenMaltby** [comment]
I kinda like our existing one:
![koreader](https://cloud.githubusercontent.com/assets/14007369/24885152/89f97930-1e12-11e7-9b3a-0d899af96e90.png)
Can't it fit on a book, if that is the issue?

**Comment by houqp** [comment]
Thanks @AliLozano for the new design, i think they look great too!

@KenMaltby I think some tried doing that, but it doesn't fit :P On top of that, I prefer a simpler flat design. We can still keep using this one for our github org icon :)
