### ISSUE TITLE
Kindle Touch - NATIVE keyboard support

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2014]
* KOReader version: ALL
* Device: ALL Kindles

#### Issue
It would **SUPER helpful** to have an option to use **NATIVE** keyboard on Kindles.

#### Steps to reproduce
Recently I have [added](http://www.the-ebook.org/forum/viewtopic.php?p=1284430#1284430) Kazakh keys for my Kindle Touch. I very-very much would like to use it in KOreader as well - for full text search, books renaming and (future) note taking in my native language!

Thank you in advance!

**Comment by houqp** [comment]
This is not going to be an easy task because amazon does not open up the native system to 3rd party developers. It will be easier to just add the native keyboard into KOReader's virtualkeyboard module directly.

**Comment by mergen3107** [comment]
Could you please elaborate on that a little bit?
I get confused. So do you mean that Amazon is blocking native keyboard for 3rd party developers and their apps?
Is KOreader on different level than, for example, Leafpad is? I mean they both are run from KUAL, and Leafpad has access to use the native keyboard. I don't understand why KOreader is so restricted.

**Comment by mergen3107** [comment]
Is it the same reason why KOreader has no access to Password Lock feature? (https://github.com/koreader/koreader/issues/2011)
I am sorry for being (probably) really annoying by asking so many questions, but I really would like to understand the first principles of KOreader-Kindle interactions in order to able to better find bugs and suggest realistic enhancements :) 
Thank you!

**Comment by mergen3107** [comment]
Currently my keyboard in KOreader has two input languages: English and Russian-Ukrainian.
How can I change additional symbols (in ABC tab)? I'd like to replace Ukrainian diacritics with Kazakh ones. I couldn't find language-specific input configurations inside koreader/frontend/device folder. I can see only English layout.
Thank you!

**Comment by mergen3107** [comment]
For those interested, replaced the Russian-Ukrainian keyboard layout to Russian-Kazakh one.
Change Russian transliterated layout with conventional "йцукен" (analogue of "qwerty" in English).
You can take it [here](https://yadi.sk/d/S28EaW1VraPi5).
Extract to koreader/ with replacing the file.
**Warning!** After updating the build of koreader, make sure you copy this file again since it is overwritten by stock.
Thank you all for help!

**Comment by houqp** [comment]
Nice, glad you found the file by yourself :) As a low hanging fruit, we should definitely add keyboard language setting support so user can set their preferred language in reader setting. Let's use this issue for this feature request.

Regarding to you first question, KOReader is completely written from scratch and uses none of the kindle system stuff. Except for the part that accesses system resources like frontlight control, but this is transparent from users since it is hidden from our UI. The upside of writing everything from scratch is it makes it very easy to port KOReader to various platforms and devices. We try to integrate with the native kindle system as much as possible, for example, @chrox wrote the KPVBooklet. But there are things that are not exposed by the native system like the screen saver password protection functionality.

**Comment by mergen3107** [comment]
@houqp thank you very much for detailed explanation! I am getting more and more conscious about KOreader's functionality :) Now I see how expensive it is to pay for keeping KOreader versatile across all platforms.

**Comment by chrox** [comment]
Yes, interacting with the Kindle native system from Koreader is not an easy job. Maybe it's much easier to do this in Android. Anyway we probably won't invest time in this problem. Closing this now.
