### ISSUE TITLE
Battery level isn't shown correctly on Nook Glowlight Plus

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2025]
* KOReader version: latest nightly by 10th of May
* Device: Nook Glowlight Plus (the newest one)

#### Issue
Here is the [quoting](http://forum.xda-developers.com/showpost.php?p=66801124&postcount=9) of the user **cemunleashed** from xda-developers Nook forum:

> Screen refresh doesn't work.

> OCR slows down device(Even if it's disabled.Had to delete it from /sdcard/koreader )

> Battery level isn't shown correctly

#### Nook set up
For making KOReader live on NGP, [here](http://www.mobileread.com/forums/showthread.php?t=271505)  the user **thinredline** from mobileread suggests to use a patch file.
Maybe we should incorporate that into .apk? For example, rename patch.lua to Nookpatch.lua and make KOReader identify the device just like it does with Kobo.

Thank you!

**Comment by houqp** [comment]
We should merge those patches into KOReader instead. I have relied to the thread.

**Comment by chrox** [comment]
> OCR slows down device(Even if it's disabled.Had to delete it from /sdcard/koreader )

This is not true. KOReader only OCRs single words when highlighting them. And it won't initialize the OCR engine when it's not necessary.

> local screen = require("android").screen 
screen.height = screen.height + 10

> require("jit.opt").start("sizemcode=64","maxmcode=512", "recunroll=8", "callunroll=12", "loopunroll=60", "instunroll=16", "tryside=16", "hotexit=160", "hotloop=57344", "maxsnap=160000", "maxside=32000", "maxirconst=160000", "maxrecord=1280000", "maxtrace=320000")

> for i=1,1000 do end  -- Force allocation of one large segment

The essential part of the patch is already incorporated into latest KOReader. See [here](https://github.com/koreader/android-luajit-launcher/blob/master/assets/android.lua#L19-L22). And thinredline's patch has a flaw that `for i=1,1000 do end` will never do the work of allocating a mcode segment because `hotloop=57344` it needs a loop of at least 57344 iterations.

**Comment by chrox** [comment]
Anyway the battery level problem should be a valid issue. Because we use a [hard-coded battery file](https://github.com/koreader/koreader/blob/master/frontend/device/android/powerd.lua#L4) to read battery level on Android we should switch to [a standard Android API](https://developer.android.com/training/monitoring-device-state/battery-monitoring.html).

**Comment by verge-36** [comment]
Yep.OCR was my mistake, turns out my tessdata download was corrupted.
