### ISSUE TITLE
Crashes and Frozen very often on Kobo Touch

### ISSUE THREAD

**Issue by enigma90** [koreader/koreader#2052]
* KOReader version: koreader-nightly-20160529
* Device: Kobo Touch

#### Steps to reproduce

Sometimes it just gets frozen when entering the program. Sometimes it crashes when I want to continue to read a book by opening "History" from the menu. Rather buggy this version is. I am getting back to nightly-20160513. Below is the crash log.

-----------
/luajit: frontend/readhistory.lua:75: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	frontend/readhistory.lua:75: in function '_read'
	frontend/readhistory.lua:96: in function '_init'
	frontend/readhistory.lua:119: in main chunk
	[C]: in function 'require'
	frontend/apps/filemanager/filemanagerhistory.lua:29: in function 'updateItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:68: in function 'onShowHist'
	frontend/apps/filemanager/filemanagerhistory.lua:22: in function 'callback'
	frontend/ui/widget/touchmenu.lua:567: in function 'action'
	frontend/ui/uimanager.lua:440: in function '_checkTasks'
	frontend/ui/uimanager.lua:587: in function 'handleInput'
	frontend/ui/uimanager.lua:678: in function 'run'
	./reader.lua:172: in main chunk
	[C]: at 0x0000bea5

**Comment by houqp** [comment]
The cash looks weird. What was the content of `history.lua` when the crash happens? Does it happen every time?

I wonder whether the freezes are caused by this commit: https://github.com/koreader/koreader/commit/82a3e0f9ad9416119248f177a3dc7b2bcec79fc5.

@enigma90 , if you don't mind, could you help test it by removing the following line?
https://github.com/koreader/koreader/commit/82a3e0f9ad9416119248f177a3dc7b2bcec79fc5#diff-af2469c8d76fe761129c12ee49d4f86aR33

**Comment by enigma90** [comment]
weird indeed. I just got back to this version to see if I could reduplicate the results, but everything seems fine so far. False alarm, I guess. Sorry.....

**Comment by houqp** [comment]
No worry. Then it looks like a filesystem corruption, which also explains why you are getting empty content from `history.lua`. Feel free to reopen this issue if the crash happens again.
