### ISSUE TITLE
Problem with chapter tick marks

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#2054]
* KOReader version: 2015-11-408
* Device: Kobo Glo HD

#### Issue

Same problem as #1905 but it only "hits" a few epubs of my collection. The vast majority shows the tick marks.

#### Steps to reproduce
Load the following [book](http://m.zbigz.com/myfiles?url=magnet:?xt=urn:btih:7CBFF2D42C37713C6BB7835BADFA9A1389B3FEB4&dn=EPL_Sueno_en_el_pabellon_rojo&tr=http://tracker.tfile.me/announce&tr=http://91.121.54.8:6969/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.publicbt.com:80&tr=udp://open.demonii.com:1337/announce)
Regards

**Comment by houqp** [comment]
Thanks for the report. There are two issues here.

1. Because the book is pretty large, the reader set the footer tick marks before the document itself is fully loaded. I will send out a patch soon to fix this.
2. After the first bug is fixed, it still won't show the tick marks because the number of tick marks in this book exceeds the maximum threshold (126 > 100) we have in the reader.

**Comment by houqp** [comment]
@chrox do you remember why max_ticks is set to 100 in readerfooter?

**Comment by chrox** [comment]
Actually if the ticks are more than 100 the progress bar will be so crowded that you cannot distinguish between the ticks. Yeah, it might be over engineered.
