### ISSUE TITLE
[FR] Improvement of some menus for landscape mode

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#2093]
- KOReader version: All versions < 2015-11-477
- Device: Kobo Glo HD
#### Issue

Some menus can be improved when landscape mode is used. For example:
In vertical mode you can check the text changes "without closing the menu":
![reader_2016-jun-20_155239](https://cloud.githubusercontent.com/assets/17313916/16197240/9b32734e-3701-11e6-8014-7ba77ac77e6a.png)
In landscape mode you can't check the text changes and you need to close the menu:
![reader_2016-jun-20_155129](https://cloud.githubusercontent.com/assets/17313916/16197269/bb18f430-3701-11e6-9508-1440c5bed5c6.png)
I'm not only referring to the fonts menu, but the hyphenation menu and probably other that I just forget :/
Regards.

**Comment by Frenzie** [comment]
Besides not changing anything, there are two possible solutions to this problem.

1. Make the menu shorter. Say, 6 items instead of 10. This is the easiest but I'm not sure if the pay-off is worth the added annoyance.
2. Make the menu less wide. This is harder but probably better. On the other hand, I kind of like being able to tap a menu item from the right side of the screen.

**Comment by djalma2k** [comment]
Maybe a third: make this type of menu a wdget like the dictionary.
Anyway, in my opinion and assuming that I have correctly understood you(...pay-off is worth...), the first one is the best and the "troubles" of this solution could be palliated changing the number of items per page in function of total items.
Regards.

**Comment by poire-z** [comment]
The Font, Hyphenation/Typography and Style tweaks menu had their number of items reduced over these last months, so we can see off they affect the text.
I guess this then now also helps when in Landscape mode.
