### ISSUE TITLE
List markers pushed off screen

### ISSUE THREAD

**Issue by bbgordon** [koreader/koreader#2097]
The implementation for `list-style-position: outside` assumed negative indent added extra padding before text to make room for the marker. My pull request for koreader/koreader#2046 broke this.

I had difficulty with this because we don't find out how much space is needed for the marker until renderFinalBlock. As far as I can tell the caller (renderBlockElement via ldomNode::renderFinalBlock) doesn't give that function access to change the padding or width.

I figured out a fix that calculates the marker width twice: once when padding out the element and once when rendering it. I'll submit a pull request. If there's a preferable way please let me know!

Other ideas I considered:
1. Revert. ;)
2. Associate with each src_text_fragment_t in renderFinalBlock. This would allow eventually fixing other bugs like nested lists or `<li><p>foo</p><p>bar</p></li>`. I didn't think adding a parallel padding computation was clean, nor is it a general solution (nested elements may have padding on more than one side).
3. Completely change `<li>` rendering to work like the erm_block code path in renderBlockElement. This may be necessary to fix the aforementioned pre-existing bugs but I'd like to fix my regression sooner.

**Comment by frankyifei** [comment]
in my opinion, your last change #2046 makes no much difference in rendering results and not many books use this feature. adding more code to fix this may change the book format in other place or introduce other bug. maybe it is better to revert it.

**Comment by bbgordon** [comment]
I have a lot of books containing poetry, lyrics, or equations that use it.

While making my changes I found a few other bugs with list items:

EPUB with various kinds of numbered lists:
[testepub.zip](https://github.com/koreader/koreader/files/324884/testepub.zip)

Screenshots from fc6aa51e3901e4a9a6fbb8a25231616b3e36b24d before any of my changes:

![before1](https://cloud.githubusercontent.com/assets/9062053/16219456/79ef0b90-3754-11e6-9257-d3a1d7b02d39.png)
![before2](https://cloud.githubusercontent.com/assets/9062053/16219457/7b6bc814-3754-11e6-8757-4abba2658a58.png)
![before3](https://cloud.githubusercontent.com/assets/9062053/16219459/7e04cc92-3754-11e6-9a71-89d9d21afaf1.png)

Notice that block elements inside a list element are flush with the left margin instead of being moved rightward as one would expect. When a list item wraps to the next page the indent also gets lost. The padding-top on the "Pellentesque..." paragraph is not honored because this comes from inside renderFinalBlock.

Screenshots with koreader/crengine#59:

![after1](https://cloud.githubusercontent.com/assets/9062053/16219525/02bace8c-3755-11e6-84cc-0ec88015e6b6.png)
![after2](https://cloud.githubusercontent.com/assets/9062053/16219526/04135cfe-3755-11e6-9181-e9fdc46bd208.png)
![after3](https://cloud.githubusercontent.com/assets/9062053/16219529/0542137c-3755-11e6-9e2f-f182b4bd8c7e.png)

Chrome for comparison: 
![chrome](https://cloud.githubusercontent.com/assets/9062053/16219534/0b5c2d7e-3755-11e6-822a-724714ced99c.png)

I think the difference between Chrome and crengine in alignment on the fourth inside list marker is due to epub.css.

I haven't exhaustively tested this yet so I may find more corner cases over the next few weeks. You're correct that it's pretty hairy, especially the hack I used to make renderBlockElement() "draw" text inline.

**Comment by houqp** [comment]
If you are planning to fix this properly, then I prefer we do it right the first time instead of putting in bandages over bandages :) If you think the refactoring is going to take awhile, then let's revert the commit. Otherwise, I think it's fine to leave the nightly broken for a short amount of time. I like that you are using chrome's layout engine as a reference.

**Comment by frankyifei** [comment]
this is a epub test suite for reading system. You may find it useful when testing CRE. under` /css2.1/s12.6.2` you can find epubs with different list styles.
[epub-conform-epubs-1_0_4.zip](https://github.com/koreader/koreader/files/325847/epub-conform-epubs-1_0_4.zip)

**Comment by bbgordon** [comment]
koreader/crengine#59 has all the fixes shown in the screenshot. My main question is about the code quality.

**Comment by frankyifei** [comment]
@bbgordon ， if you tested with the test suite I uploaded. you will find your commits break many tests under /css2.1/s12.6.2. even your last commits [#59](https://github.com/koreader/crengine/pull/59) did not fix it and created other problems.
I think best way is to revert your [#54](https://github.com/koreader/crengine/pull/54) commit, because it really breaks normal features and your last commit changes many things that we need to test. The cost / benefit ratio seems not so economical here for a small feature(negative x). 
For example, list-000-ordered.epub in test suite. 
it was normal 
![reader_2016-jun-26_223627](https://cloud.githubusercontent.com/assets/8104251/16362474/0272837c-3bef-11e6-98c1-0877a11058d3.png)
After negative x change
![reader_2016-jun-26_223746](https://cloud.githubusercontent.com/assets/8104251/16362479/11727260-3bef-11e6-91b5-266850773ddf.png)
After latest change
![reader_2016-jun-26_223451](https://cloud.githubusercontent.com/assets/8104251/16362488/292fb34a-3bef-11e6-8f62-212fd82aa4c6.png)
 
And @chrox @houqp if you have time, can you guys have a look?

**Comment by frankyifei** [comment]
I'd better open a new issue for this
