### ISSUE TITLE
FR Disable selection in flip mode

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2101]
Hi

it would be great if the text selection is disabled in flip mode because it is easy to select underlying text while dragging fingers across screen.

I am using the android version

**Comment by chrox** [comment]
Yes, the user experience of the page flipping page is horrible in some circumstances such as what you described above, but it's definitely not adding yet another menu option to disable selection to solve this since flipping mode provides "column zoom mode" for regular reading. Feature request #1327 may be a better solution to this. Closing this in favor of #1327.

**Comment by gerroon** [comment]
I see. I was thinking that text selection should be disabled in the flip mode for real. And column mode does not seem to fit in there in my view but you guys are the designers of this stuff.
