### ISSUE TITLE
Screen fully refreshed after staying on a page for a minute

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2145]
* KOReader version: 513 nightly build
* Device: Kobo Aura HD

#### Issue

When auto refresh time feature has been enabled, and after staying on a page for around one minute, the screen automatically fully refreshed.

#### Steps to reproduce

I believe this issue relates to my recent change to set dirty region in TextWidge:setText. And the size of status bar is entire screen (no idea whether this is expected). Currently a work around is to set the page full refresh time as 99 page to reduce the possibility of this kind of full refresh. But is it expected that the status bar covers the entire screen?

**Comment by houqp** [comment]
As I mentioned in that PR, we should not call setDirty in TextWidget. If we call it in the parent widget (filemanager), this issue won't happen. I will send a PR to address it later.

**Comment by houqp** [comment]
The fact that status bar is has a size of full screen is not expected. That's a separate issue we should look into :)

**Comment by NiLuJe** [comment]
It definitely did not use to be, I remember playing with it before the whole UIManager refactor ;).

**Comment by retrue** [comment]
I have noticed this bug in my Kobo Mini too, after updating from version 2015.11-512 to version 2015.11-520.

**Comment by houqp** [comment]
@retrue , can you try the patch in https://github.com/koreader/koreader/pull/2147? I did a quick test and it seems to fix the issue for me.

**Comment by retrue** [comment]
^^;
Sorry, I know nothing about programming, so I don't know how to apply the patch.

**Comment by Hzj-jie** [comment]
Oh, seems I have misunderstood your comment in my PR.
Now I quite understand your meaning, but I still have concern about it. Is there any reason we should not setDirty in TextWidget? I know the implementation detail of UIManager restricts it, but logically we should setDirty each time TextWidget:setText called. Otherwise some text change may not reflect to the screen.

**Comment by houqp** [comment]
It's a tradeoff between efficiency and lines of code. Let's say you have three widgets to update: `a1`, `a2`, `a3` and they are all contained within `b`.

If you call the `setDirty` in `a*` widgets,  you will register 3 refresh requests. The UI framework will need to figure out how to batch and merge those requests. There are also cases where you need to refresh the background of `b`, so asking the UI framework to fresh `a*` is redundant work.

It's less work if you just tell the UI framework to refresh `b`. Only one request is registered and there is no extra logic that needs to be handled in the `UIManager`.

This of course requires app developers writing more code because they need to keep track of which part of the widget needs to be refreshed. It's not a big issue right now because eink screen is mostly static. But as we move on to add more animations for other platforms, it can become a headache. The UI framework needs a revamp after this stable release. We should either rewrite it to move it out as a standalone window management service or switch to existing UI frameworks.

**Comment by seacatwu** [comment]
kpw3 too

**Comment by chrox** [comment]
The status bar is actually of the same size with the screen, see [here](https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerfooter.lua#L104):
```lua
self[1] = BottomContainer:new{
        dimen = Screen:getSize(),
        BottomContainer:new{
            dimen = Geom:new{w = screen_width, h = self.height*2},
            FrameContainer:new{
                self.horizontal_group,
                background = Blitbuffer.COLOR_WHITE,
                bordersize = 0,
                padding = 0,
            }
        }
    }
```
So the full refresh of the screen is totally expected but it will be fixed in #2147.

**Comment by chrox** [comment]
Fixed in #2147.

**Comment by Hzj-jie** [comment]
Is the status bar expected to be that large?

**Comment by chrox** [comment]
If we use `BottomContainer` to layout the status bar, Yes. A better layout would be something like `align: bottom` with `margin-top: self.height`, and it will be my major goal to achieve in the undergoing refactoring of the widget system, a formal css-like layout engine.

**Comment by houqp** [comment]
There is also a constrained based UI layout design pattern adopted by iOS. I personally think it's a better design than CSS like layout DSL. The biggest advantage is you get to validate and find out any layout conflict at compile time without running the app at all.

It's also more intuitive to read. For example, you can define the following constrain for footer widget:
```
top(screen_top, (screen_height-self.height))
```

**Comment by chrox** [comment]
CSS with the flexible box model is much more concise and descriptive. And most importantly, facebook open-sourced a javascript implementation of flexbox named [css-layout](https://github.com/facebook/css-layout) and it's used in [react-native](https://github.com/facebook/react-native) in both Android and iOS. And css-layout can be transpiled to Lua easily.

**Comment by houqp** [comment]
IMHO, I wouldn't say CSS is much more concise and descriptive. It's more about how the DSL is designed to express the design pattern. That said, you might have to write a little bit more code to define a complete constrain set in constrained based approach in order to pass the static analysis, which I think is exactly what's great about it. CSS tends to require various hacks to work around layout issues.

I also think css-layout can be a great choice mainly because it's a tiny subset of CSS and battled tested in production. If we can reuse the code, it would be a huge win. Any reason why we need to transpile it to Lua? Why not use the C frontend directly through FFI?

**Comment by chrox** [comment]
> CSS tends to require various hacks to work around layout issues and there is no guarantee on how the final layout is going to look like.

It is mostly true for pre-flexbox CSS by the lack of layout capability, but it's [solved in CSS3 with flexbox model](https://philipwalton.github.io/solved-by-flexbox/).

I still have no idea why we need static analysis on widget layout. Is it still necessary if the UI is rendered on the fly as the code is written?

The C library is one option but the API is less intuitive. The Javascript and Lua version can modify node object/table in-place while if we use the C library we must covert the nodes to C structures back and forth.

**Comment by houqp** [comment]
> It is mostly true for pre-flexbox CSS by the lack of layout capability, but it's solved in CSS3 with flexbox model.
>
> I still have no idea why we need static analysis on widget layout. Is it still necessary if the UI is rendered on the fly as the code is written?

Flexbox eliminates many of the existing CSS frustrations. But fundamentally, it's still tackling the layout problem with the same mindset. The core problem is CSS does not enforce a full constrain set. The layout engine will happily take whatever the user provides and produces a best effort layout result. If there are multiple solutions to the given constrains, it will pick one for the user. This ambiguousness is the source of many CSS issues. This becomes worse when there are conflicting layout rules. That's what I mean by no guarantee of final layout result. Because there is noway for user to check whether they have given the layout engine enough information. User will only know something is going wrong by manually looking at the final result (at runtime). And a lot of times, it can be a tedious task to link the visual glitch back to the CSS rules.

Now imagine that the layout engine can give you a warning when the layout rules given are conflicting or not enough to form a complete constrain set that yield a single solution. This way, you know what needs to be fixed and once it compiles, you are confident the final layout result will always be the same in any circumstance. Because the solution is unique. Other benefits includes the ability to find out redundant layout rules at compile time etc.

That said, although I have spent many years working with CSS stuff, I have only worked on iOS apps for 2 weeks. So my exposure to constrain based layout engine is limited. Perhaps I will run into other issues that does not exist in CSS if I go deeper. So far, my experience with it has been very positive. I would say almost zero frustration. It's also a little bit unfair to compare both because CSS is used to layout websites in all kinds of browsers running on all kinds of devices, so I get why they want a more relaxed model.

Anyway, given the amount of engineering effort that's needed to implement this, I think it's probably an over engineered solution at this point. We have many other important tasks on our plates and we shouldn't be spending too much resources on this. Using a solid production ready css-layout implementation is already a big step forward for us. So I am very excited about this :)


> The C library is one option but the API is less intuitive. The Javascript and Lua version can modify node object/table in-place while if we use the C library we must covert the nodes to C structures back and forth.

Just asking because it seems like a non-trivia amount of work to reimplement everything including tests in Lua.
