### ISSUE TITLE
koreader for pocketbook has performance degeneration

### ISSUE THREAD

**Issue by andruha30** [koreader/koreader#2149]
- KOReader version:
- Device:

**Comment by andruha30** [comment]
It takes much time to open pdf and djvu file up to 1 minute or even more
I cant find ukrainian keyboard when renaming the file.Only russian and english ones
Cursor cant be placed at the beginning of the line when renaming a file it jumps wherever but not where i want
I have to tap up to 5-6 times to enter the menu while reading the book

**Comment by houqp** [comment]
@andruha30 the previous version 483 does not have this issue right?

**Comment by andruha30** [comment]
I think 431 is all right

**Comment by chrox** [comment]
I didn't notice any performance degeneration on Kindle and Android from 431 to latest nightly build.
@houqp Could it be some side effect of this https://github.com/koreader/koreader-base/commit/12c9781ad592a521928c5977077e0028ca74400d that is specific to Pocketbook devices? Is it possible that some child processes are not terminated after exiting Koreader so that after several launchs of koreader there are many stalled koreader process?

@andruha30 Did you try the latest nightly build with a clean installation after a system reboot?

**Comment by andruha30** [comment]
Frankly speaking I havent noticed any changes/Still hardly to open some files as
[Opovidi_pro_starodavnii_Kyiv.pdf](https://github.com/koreader/koreader/files/367351/Opovidi_pro_starodavnii_Kyiv.pdf)

**Comment by houqp** [comment]
@andruha30 , can you confirm that the performance issue remains even after a refresh reboot? Is it just pdf/djvu or also happening for epubs?

**Comment by andruha30** [comment]
I cleaned all the previous koreader files by hand and then put the new ones?then reboot the device.Still opens very long time...I tap on the line with the opening file 2-3 times and very often it works the file opens.... 
Mostly it happens for pdf\djvu files because of the quality of  scan I guess..

**Comment by Frenzie** [comment]
Presumably fixed by #4646. If not, please reopen or create a new issue.
