### ISSUE TITLE
make scroll mode default for pdf and djvu?

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2157]
scroll mode has been stable for awhile and I think it's ready to be set as the default mode since it provides a much better experience than page mode. thoughts?

**Comment by tigran123** [comment]
I agree. But, of course, the button which allows to turn it off should stay in its usual place, as sometimes turning scroll mode off is absolutely necessary. For example, when Crop setting Auto doesn't work and one has to define the cropbox manually it is necessary to turn Scroll Off so that the concept of "current page" is well defined. And this, in turn, is required because one has to define manual cropbox for "this" and for the "next" (= this + 1) page sometimes (if the margins are not symmetric).

Anyway, yes, for 99% of the books (i.e. all those except typeset by myself specifically for 7" eInk devices --- these are best read in page mode) I turn scroll mode On before reading.

**Comment by Frenzie** [comment]
Agreed.

**Comment by tigran123** [comment]
Speaking of defaults: it would be nice to have "Show hidden files" to be ON by default too. Although I never boot into Nickel, I still name my books directory ".Books" to make sure that if I accidentally do that, it won't hang forever trying to analyse metadata of thousands of books.

**Comment by KenMaltby** [comment]
While "defaults.persistent.lua" still works, you can have "DSHOWHIDDENFILES = true" 

There is also a: "DSCROLL_MODE = 0"  still in mine.

**Comment by chrox** [comment]
That will be great. :+1:

**Comment by Eduardomb22** [comment]
How do I enable the "scroll mode"? Is this the reflow option? Thanks
