### ISSUE TITLE
Status bar is off when starting new book, needs few presses to become visible

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#2172]
* KOReader version: 2015.11-276
* Device: Kobo H2O

Status bar is off (not visible) when opening new book. It takes few presses to become visible. I noticed it just today and read this post: http://www.mobileread.com/forums/showpost.php?p=3342930&postcount=2624

#### Steps to reproduce
I read with status bar on. And, just finished last book, opened new one and there was no status bar. Tried to see if something changed in options, everything was as it should be. Then I pressed lowest part of screen, nothing. I pressed again, and again, not sure how many times, but suddenly there it is, status bar is back again.

Then I read about this on MR and saw that there's also someone who noticed same behavior, so I'm not only one.

EDIT: I just tested other book, it started with status bar on. But, using history I returned to previous with status bar off, it was still off on my return to it. Two taps (now I paid attention) and it's back on. Changing books, it looks that something influences status of status bar.

It looks like for some books you need to turn it on, for some it already is as it should be. Not sure if it completely blame of koreader now that I noticed that for other book it is fine.

**Comment by houqp** [comment]
I notice that you are using a very old version, can you give the latest 533 a try? We have fixed many bugs since 276.

**Comment by WolfBackGR** [comment]
I'm just trying the latest nighty (I think is the 546 release -OTA update).
The same here. The status bar is disappeared in every boot of Koreader.
I must hit the bottom of the screen a few times to appeared again every time I opened the same book.

**Comment by AlanSP1** [comment]
At the moment I can't test latest version, but it seems that if it doesn't work for @WolfBackGR , it wouldn't work for me.

Probably it is something within book (both I tested are epubs) that "confuses" status bar.

**Comment by houqp** [comment]
Hmm... not able to reproduce on my side. Could you paste the content of `settings.reader.lua` here? Once the footer is toggled to present in a book, other books should have the footer too.

**Comment by houqp** [comment]
Also, I wonder it's because the status bar is too small to tap on H2O. You can adjust the tap region bey changing the y and h value for DTAP_ZONE_MINIBAR: https://github.com/koreader/koreader/blob/master/defaults.lua#L73.

For example, set y to `14/16` and h to `2/16`.

**Comment by houqp** [comment]
Another question, what's the last working version that does not have this bug?

**Comment by WolfBackGR** [comment]
In my case the problem is not the behavior of the progress bar. It's appeared at the first tap on the bottom of the screen.
The problem is that the progress bar came up with a blank line every time I opened the same book. I keep the progress bar and current time visible, I close the book, I opened again (the same book) and the progress bar is disappeared. Every time I must hit the bottom of the screen to appeared again...
In stable release the status bar is showing by default, thought. Came up with the same state as when the book is closed and opened again.

I was rolling back to 485 nighty. The same here, and this is my settings.reader.lua 

```
-- we can read Lua syntax here!
return {
    ["copt_font_gamma"] = "35",
    ["night_mode"] = false,
    ["ota_channel"] = "nightly",
    ["filemanagermenu_tab_index"] = 2,
    ["footer"] = {
        ["progress_bar"] = true,
        ["disabled"] = false,
        ["book_time_to_read"] = false,
        ["toc_markers"] = true,
        ["auto_refresh_time"] = false,
        ["battery"] = true,
        ["pages_left"] = true,
        ["all_at_once"] = false,
        ["page_progress"] = false,
        ["time"] = true,
        ["percentage"] = false,
        ["chapter_time_to_read"] = false
    },
    ["show_hidden"] = true,
    ["fm_screen_mode"] = "portrait",
    ["frontlight_intensity"] = 39,
    ["lastfile"] = "/mnt/onboard/Books/Dean Devlin/Mera Anexartesias - Dean Devlin.epub",
    ["open_last"] = true,
    ["show_advanced"] = true,
    ["evernote"] = {
        ["username"] = "",
        ["html_export"] = false
    },
    ["lastdir"] = "/mnt/onboard/Books/David Morell",
    ["reverse_collate"] = false,
    ["reader_footer_mode"] = 2,
    ["kosync"] = {
        ["auto_sync"] = true
    },
    ["statistics"] = {
        ["is_enabled"] = true,
        ["min_sec"] = 5,
        ["max_sec"] = 300
    }
}
```

**Comment by AlanSP1** [comment]
This is my settings.reader.lua:

`-- we can read Lua syntax here!
return {
	["floating_punctuation"] = 0,
	["night_mode"] = false,
	["ota_channel"] = "nightly",
	["filemanagermenu_tab_index"] = 1,
	["footer"] = {
		["progress_bar"] = true,
		["disabled"] = false,
		["book_time_to_read"] = true,
		["toc_markers"] = true,
		["auto_refresh_time"] = true,
		["battery"] = true,
		["pages_left"] = true,
		["all_at_once"] = true,
		["page_progress"] = true,
		["time"] = true,
		["percentage"] = true,
		["chapter_time_to_read"] = true
	},
	["show_hidden"] = true,
	["fm_screen_mode"] = "portrait",
	["frontlight_intensity"] = 20,
	["lastfile"] = "/mnt/onboard/.Books/Najvaznije/0 Fat-Burning Machine by Mike Berland, Gale Bernhardt.epub",
	["open_last"] = true,
	["copt_font_size"] = 16,
	["ota_server"] = "http://hal9k.ifsc.usp.br:80/koreader/",
	["follow_links"] = false,
	["evernote"] = {
		["username"] = "",
		["html_export"] = false
	},
	["lastdir"] = "/mnt/onboard/.Books/Najvaznije",
	["reader_footer_mode"] = 1,
	["show_advanced"] = true,
	["statistics"] = {
		["is_enabled"] = true,
		["min_sec"] = 5,
		["max_sec"] = 490
	},
	["kosync"] = {
		["auto_sync"] = true
	}
} `

About taping zone, I'm sure it works (and I know how to chage it). But, it takes two taps to get back status bar back on if it isn't shown.

It looks like this: koreader thinks it's on, but it isn't shown. First tap turns it off, so it isn't visibile, second tap turns it back on, but now it is visibile.

Last version I'm sure it worked just fine for me is stable version, but I didn't changed that much versions (don't do OTA etc). I know it is not that much of a help.

I know that settings should be propagated from book to book (at least some of them). But, as I wrote, it looks like koreader thinks that status bar is on, but it isn't shown, hence two taps to show it again. Like something need to be resetted or something. And, it isn't same for all books.

Now when I know that I can get status bar back with two taps, it's not that much of a problem, but first time I saw this, I thought that something in ebook disabled status bar from showing.

One more detail that could be important, at the moment I first noticed that I had full status bar (the upper one) on, with everything off except graphical progress bar. After that I turned off full status bar and next book didn't had that problem.

Maybe you could try testing this with upper status bar on, with same settings as I have (not sure what settings of upper bar are for @WolfBackGR ).

Book settings where this happens are as follow:

`-- we can read Lua syntax here!
return {
	["font_embolden"] = 0,
	["copt_line_spacing"] = 100,
	["copt_page_margins"] = {
		[1] = 10,
		[2] = 15,
		[3] = 10,
		[4] = 15
	},
	["render_mode"] = 0,
	["highlight_drawer"] = "lighten",
	["bookmarks"] = {},
	["gamma"] = 1,
	["font_size"] = 16,
	["screen_mode"] = "portrait",
	["show_overlap_enable"] = false,
	["last_xpointer"] = "/body/DocFragment[8]/body/h2[2]/span/text().0",
	["stats"] = {
		["performance_in_pages"] = {
			[1468946788] = 4,
			[1468948503] = 22,
			[1468946735] = 2,
			[1468950678] = 28,
			[1468947822] = 10,
			[1468946841] = 6,
			[1468948216] = 17,
			[1468964788] = 28,
			[1468947963] = 12,
			[1468946971] = 7,
			[1468947570] = 9,
			[1468948179] = 16,
			[1468947183] = 8,
			[1468948138] = 15,
			[1468948498] = 21,
			[1468948314] = 18,
			[1468948346] = 19,
			[1468946730] = 1,
			[1468946753] = 3,
			[1468947725] = 10,
			[1468950517] = 26,
			[1468946961] = 8,
			[1468950325] = 25,
			[1468948397] = 20,
			[1468946802] = 7,
			[1468946877] = 7,
			[1468950532] = 27,
			[1468947869] = 11,
			[1468950260] = 24,
			[1468946863] = 5,
			[1468947005] = 6,
			[1468948074] = 14,
			[1468948026] = 13
		},
		["authors"] = "Mike Berland",
		["notes"] = 0,
		["total_time_in_sec"] = 2428,
		["title"] = "Fat-Burning Machine",
		["highlights"] = 0,
		["pages"] = 310,
		["series"] = "",
		["language"] = "En"
	},
	["gamma_index"] = 15,
	["config_panel_index"] = 1,
	["highlights_imported"] = true,
	["line_space_percent"] = 100,
	["header_font_face"] = "Noto Sans",
	["floating_punctuation"] = 0,
	["copt_screen_mode"] = "portrait",
	["hyph_alg"] = "English_US_hyphen_(Alan).pdb",
	["copt_font_weight"] = 0,
	["copt_status_line"] = 0,
	["font_face"] = "Noto Serif",
	["readermenu_tab_index"] = 4,
	["percent_finished"] = 0.093548387096774,
	["rotation_mode"] = 0,
	["embedded_css"] = true,
	["copt_font_size"] = 16,
	["highlight_disabled"] = false,
	["page_overlap_style"] = "dim",
	["copt_view_mode"] = 0,
	["css"] = "./data/epub.css",
	["highlight"] = {},
	["copt_font_gamma"] = 15,
	["copt_embedded_css"] = 1,
	["bookmarks_sorted"] = true
} `

OK, just tested this theory, for me this option is what turns this bug on and off:

DCREREADER_PROGRESS_BAR = 1 (or 0).

When it is 0, i.e. full (upper) progress bar is on, the bug is there, i.e. there's no mini progress bar. And vice versa. I tested with two new books, each with different setting (0 or 1).

One thing I also noticed, lower graphical progress bar doesn't show chapters also when the bug is in effect even if TC (time to read chapter) sees chapters. So it is also related in some way, or may be different bug.

Just to mention, if it is important, I store my settings in defaults.persistent.lua, not defaults.lua (who know what might affect this bug).

One question, when I open book with settings to see full progress bar, even if I change it later in defaults.persistent.lua, I see full progress bar through whole book. Which setting affect this behavior, so I can manually change it per book?

**Comment by KenMaltby** [comment]
It is one of the bottom reader menu items, the bottom Gear icon.  You could try Long Pressing your selection, to set your default.

**Comment by AlanSP1** [comment]
Thanks @KenMaltby this did the trick for removing full progress bar when it is there.

**Comment by houqp** [comment]
Oh, now it makes more sense to me if it's not display properly on first launch :P Thanks you both for the detailed information. I will take a deeper look when I get back home.

> One thing I also noticed, lower graphical progress bar doesn't show chapters also when the bug is in effect even if TC (time to read chapter) sees chapters. So it is also related in some way, or may be different bug.

We used to have a maximum chapters count threshold for the mini bar. If there are more than 100 chapters, we just dropped it. That restriction has been removed since then. Not sure whether your build has that patch though. You can check the content of frontend/apps/reader/modules/readerfooter.lua against this patch:
https://github.com/koreader/koreader/commit/ad88192d85504da4bf94e254c88ce3a952d71e1b

> Just to mention, if it is important, I store my settings in defaults.persistent.lua, not defaults.lua (who know what might affect this bug).

You should always make your changes in `defaults.persistent.lua` so it won't get overwritten by updates. I was being lazy to ask you to change `defaults.lua` because not everyone has `defaults.persistent.lua`.

**Comment by houqp** [comment]
So looks like this is expected behavior with epub files if you are using full progress bar instead of the mini one. Only one of them can be enabled by default. @WolfBackGR , can you confirm that you are also using full progress bar for epub files?

**Comment by tigran123** [comment]
@AlanSP1 Why do you consider this a bug? I consider the behaviour you describe as a bug. Status bar should be OFF by default, because for books (printed books, not ebooks) it should only become visible when you want to check the battery status or some other info, but if you leave it ON then it will obscure the text and will be very irritating.

But for ebooks the concept of page is not inherent in the design of the book itself, so it is constructed on the fly by the reader which has the freedom to avoid overlapping with the status bar. For printed books (i.e. PDF and DjVu files) there is no such freedom (unless you use a super-powerful but only 90% reliable mechanism built into Koreader called popularly "Reflow" but which does a hell of a lot more than a typical "reflow" of commercial products like Adobe's Digital Editions).

Now, as for the multiple presses ---- @AlanSP1 just select the option "Show all at once" in the menu and then only a single press will turn the status bar ON and OFF.

However, if you made status bar to be visible and then quit Koreader and restart it and it becomes invisible, then that would be a real bug. But this doesn't seem to be the case according to your description.

**Comment by WolfBackGR** [comment]
> However, if you made status bar to be visible and then quit Koreader and restart it and it becomes invisible, then that would be a real bug. But this doesn't seem to be the case according to your description.

This is, exactly, my case.

> @WolfBackGR , can you confirm that you are also using full progress bar for epub files?

Yeap! I read only epub files and I use the full progress bar as default.

**Comment by AlanSP1** [comment]
@tigran123 
This is just the way I like it and this way is something how it was on my previous ebook readers. Even "normal" paper books usually have some forms of statistics (paper number, book title, author...).

Anyway, I consider this great, that anyone can have reading style (s)he prefers. For me, I like a lot of statistics. If you prefer clean page, why not, read it that way.

Multiple taps are explained, I got it right:

First tap to turn off status bar that isn't visible, but is considered on by koreader.
Second tap to turn it on and now it becomes visible.

And I use all my statistics on one status bar bar, i.e. I use show all at once option. And I choose to show all possible statistics.

And why I consider this a bug? Well, I thought that just one press would bring status bar. Also, before (I think) I could have both status bars visible without any intervention on my side.

**Comment by tigran123** [comment]
@AlanSP1 Yes, the normal printed books have the page headings and that is what I prefer to see, because I almost exclusively read printed books on Koreader, not ebooks.

Printed books are the ones which have the concept of page, i.e. they are stored as PDF (typeset books) or DjVu (scanned books) files. Ebooks are those which consist of a one-dimensional stream of characters which the viewing software is free to render as glyphs from some user-chosen typeface family (aka "font") and assemble into two-dimensional objects like paragraphs and pages according to the capabilities of the screen and user choices. Because of this freedom the viewing software can add some status bar  or other info without any degradation.

**Comment by KenMaltby** [comment]
I suppose that you could add a "long press" ability to make a startup (when not using "all at once") default for a checked option.  That would establish where, in the list of selected options, the displayed option(s) are started, before the tapping on the right end of the mini-bar moves through the list.  I take it that it now defaults to the "disabled" option?

**Comment by tigran123** [comment]
long press is reserved for looking up words from the dictionary. For a long time this functionality was BROKEN because long press at the bottom cause a "Go to page" dialog thus making the bottom line inaccessible. But, fortunately, recently this was fixed and the "Go to page" dialog is gone. It looks up the words in the bottom line correctly.

Note that I am talking about printed books only. For ebooks the software can avoid rendering the text in the area used by the status bar and the whole issue disappears. But for printed books (typeset PDF and scanned DjVu) it is impossible, without sacrificing the valuable screen space for rendering the printed page. Or, doing something awful (!!! please don't even think about it!) like re-rendering the page in the partial rectangle if the status bar is visible and rendering it full screen if the bar is invisible. Such design would be a very bad idea because it would mess up the whole "scroll ON" continuity.

**Comment by KenMaltby** [comment]
Long Press, in menus, is being used to bring up a message box to offer "default" settings and/or provide for entering user provided data.  I was referring to the options in the Reader menu "Status bar" selection.

**Comment by tigran123** [comment]
Ah, I see. I thought you meant long-pressing the bottom area of the screen :)
