### ISSUE TITLE
FR: Native Android Keyboard (Keyboard in Book Status very slow, misses letters)

### ISSUE THREAD

**Issue by edwintorok** [koreader/koreader#2241]
- KOReader version: koreader-android-arm-linux-androideabi-v2015.11-587-ga55a987.apk
- Device:  Tolino Vision 3 HD (Android 4.0.4)

KOReader is a huge improvement in reading PDFs over the native reader on the Tolino device
due to reflow!
I've encountered some issues though, if these are fixed KOReader would provide a nearly flawless experience.
#### Issue

Typing notes on the 'book status'  screen is very slow, I have to wait about 1-2s every 1-2 characters I type, which makes entering notes  cumbersome. It is as if KOReader would wait until the character shows up on the EInk display before accepting more characters, or there is a limit on how many characters I can type until it has redrawn.
The keyboard used by tolino itself (e.g. in the browser, I guess this is the Android keyboard) works a lot better (obviously there is a little delay with characters showing up due to EInk, but I can type ahead a few characters without problems).

OTOH using same KOReader version on Samsung Galaxy Tab 3 7" WiFi (SM-T210, Android 4.4.2) typing is quite comparable to the native keyboard, and I don't notice any slowness, but of course this is not an EInk device.
#### Steps to reproduce

Open any PDF/EPub
Go to book status
Start typing notes, and see how long it takes for you to enter a small string, e.g. "testing typing".
 Takes about 17s to enter correctly by waiting a bit after 2-3 chars, if I go any faster than that, e.g. if I try to enter it in about 10s then some characters will be missing (e.g. the 'n' in testing', or the final 'g' in 'typing').
If I try to enter it with thumbs and 2 hands I get something like 'tesigypg' with several letters missing.

With the native android keyboard I can enter that text in about 7s (by using the thumbs and 2 hands).
Also on the native keyboard the space between the keys on the virtual keyboard is larger vertically, making it a bit easier to hit the right letters.

Would it be possible to allow using the native Android keyboard on the android builds, or improve the builtin keyboard so that it works just as well as the native one on EInk devices?

**Comment by edwintorok** [comment]
logcat from typing 'testing typing' at several speeds, as you can see it misses some chars: https://gist.github.com/edwintorok/723a76383e716fa5049b5251ccd6c0bb

**Comment by mirh** [comment]
Can confirm this is still an issue on Vision 4 HD and 20180110 nightly.

**Comment by mirh** [comment]
Still a thing. 
[This is system keyboard](https://github.com/koreader/koreader/files/2805578/LatinIME.apk.zip) btw.

**Comment by pazos** [comment]
@mirh.

It isn't as easy as it seems.

To add this feature we need to:
1. create a viewport as part of the android device abstraction and handle it based on surface changes. 
2. create hooks to trigger keyboard show/hide events and pass them from lua to java.
3. catch whatever kind of events the virtual keyboard throws, parse them and generate the kind of events koreader handles (which are not android specific)

If somebody wants to implement this it will be great because we can use 1 to handle rotation and do other fancy stuff too.

**Comment by mirh** [comment]
So... What you are telling me is that this happens because it isn't a native library/package and there's whatever overhead?

**Comment by pazos** [comment]
> What you are telling me is that this happens because it isn't a native library/package and there's whatever overhead?

No. I'm telling you that somebody that have the motivation to add this feature will probably need to look at some specific parts of the code and make sure that everything works.  

> Is this happening on other devices then?

KOReader uses the same keyboard on all platforms. Is a virtual keyboard too, like the android apk you linked, but embedded in the program.

On pure linux e-ink devices, like Kindles, Kobos and Bqs, KOReader works waaay better than on 
 android e-ink devices. This is in general, because we take care of all e-ink refreshes, and this affect to the keyboard speed too.

If your device is a non-eink and is recent enough (7.1 or superior) I would expect the same speed writting on both virtual keyboards, but obviously not the same "look&feel". YMMV, because some devices have some quirks.

> why on android would you even have to be forced to use this "dedicated" keyboard?

We're "forced" because nobody wrote the code needed for handling an external (from the point of view of KOReader) virtual keyboard. https://stackoverflow.com/questions/5864790/how-to-show-the-soft-keyboard-on-native-activity

**Comment by pazos** [comment]
Nobody tried to implement IME on android. Closing as won't fix. PR's still welcome

**Comment by mirh** [comment]
"Atm nobody is available to fix" can't be a "closed wontfix"

**Comment by pazos** [comment]
> "Atm nobody is available to fix" can't be a "closed wontfix"

It's not a fix. It is a feature. A very difficult feature indeed. Just for android.

So lets make it "No contributor or maintainer attempted to implement it. No maintainer plans to implement it. Patches welcome" :)

There's also "out of scope", which means "rejected, doesn't fit in the project". I don't think it applies here, but I'm not sure :p

**Comment by mirh** [comment]
Keyboard is just unusable as of now, so I would quite think it's relevant. 

Anyway, the point is that people are far quicker to find out an open issue (since they are experiencing it) than a closed one.
