### ISSUE TITLE
Koreader integration with GoodReads

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#2325]
I'm preparing KO integration with GoodReads portal.
I'm using GoodReads api: https://www.goodreads.com/api

I have a question. How to create new plugin in KO? Temporarily I created GoodReads submenu in Statistics :)

At this moment it's look that:
- we can search book 
![1](https://cloud.githubusercontent.com/assets/22982594/20137977/0f38d49a-a67e-11e6-99d6-3564f8d7e53e.png)

![2](https://cloud.githubusercontent.com/assets/22982594/20137984/13766644-a67e-11e6-81d2-b6a71055481f.png)

- in search results we can check information about selected book

![3](https://cloud.githubusercontent.com/assets/22982594/20138009/3048796a-a67e-11e6-9727-c286ef7b5772.png)
![4](https://cloud.githubusercontent.com/assets/22982594/20138011/329cb820-a67e-11e6-8fd7-98373d150144.png)
![5](https://cloud.githubusercontent.com/assets/22982594/20138013/350448c6-a67e-11e6-9bc1-d0e01649af3b.png)

**Comment by houqp** [comment]
Looks really cool! I will write up the documentation tonight for the plugin development process.

**Comment by houqp** [comment]
OK, totally got side tracked by work today because of being oncall. I will try again on finishing up the doc tomorrow night. 

Long story short, to create a plugin named `foo`, just create a directory named `foo.koplugin` under the `plugins` directory. Then under `plugins/foo.koplugin`, create a filed called `main.lua`. Whatever gets returned from this file (a table) will be the plugin object that got [registered](https://github.com/koreader/koreader/blob/76cef07c079e979de6aac6b540c9cc2b672b6f57/frontend/apps/reader/pluginloader.lua#L16) into the plugin system. All the reader events will be available for the plugin. Looks like all you need is adding an entry to the reader menu, in this case, you just need to define the `addToMainMenu` [method](https://github.com/koreader/koreader/blob/master/plugins/zsync.koplugin/main.lua#L26) for the table you return in `main.lua` file. The reader initialization process will call this method on all registered tables in the system, including all loaded plugins.

**Comment by robert00s** [comment]
@houqp Thanks :)

**Comment by robert00s** [comment]
Next question :)
Is there any way to dynamically update keyvaluepage widget? I fetch a list of first 20 books from GoodReads from single xml query. I show this query in keyvaluepage. I would like in the backgroud fetch next query (with 20 more results - books 21 to 40), and to update keyvaluepage to see more results e.g . going to the next page.

**Comment by houqp** [comment]
There is no easy way to do background operation, which is something I would like to add. The closest thing I can think of is fetching items for the next page on page turn action, which means user will have to wait for the network IO to finish before we can display the new page. 

I think in reality, fetching 40 or even 80 items at once should be good enough for most of the use-cases? I would imagine most people will only look at the first couple results. If they really want to go through more than 40 items, then we can fire up another request synchronously and update the UI.

**Comment by Frenzie** [comment]
Implemented in #2346.
