### ISSUE TITLE
Lock the file manager's orientation?

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2342]
For some unknown reason, the file manager sometimes toggles to landscape mode and I have to manually change the value of `fm_screen_mode` in `settings.reader.lua` to get back to portrait mode.

Is there a way to prevent the modification of `fm_screen_mode`?

**Comment by Frenzie** [comment]
I seem to recall that the filemanager in landscape has something to do with
coming out of a document in landscape.

**Comment by houqp** [comment]
Based on the code, looks like it only updates `fm_screen_mode` when you close the filemanager [1]. So did you ever exit the reader in landscape mode?

[1]: https://github.com/koreader/koreader/blob/master/frontend/apps/filemanager/filemanager.lua#L333

**Comment by cramoisi** [comment]
Could you tell me how this is expected to work ? As a matter of usability (since there is more room in portrait mode than in landscape) I expect the FM to always be in portrait mode even after exiting a book displayed in landscape mode (my usage is the exact opposite as in [#2565](https://github.com/koreader/koreader/issues/2565)). At this time the thing is quite like having a spirit of it's own.

**Comment by Frenzie** [comment]
@cramoisi The way it works (and also how I personally want it to work) is that the file manager is always in portrait. I've never seen the bug described in the OP.

**Comment by Frenzie** [comment]
Please reopen this if it pops up again.
