### ISSUE TITLE
Info about UI Layout

### ISSUE THREAD

**Issue by apletnev** [koreader/koreader#2351]
Currently It is quite difficult to modify UI, especially when you want to create a new component, because we haven't any information about layout, ugly example

```
UIManager:setDirty(self.view.dialog, "ui", self[1][1][1].dimen)), -- WAT?
```

 Also for check UI we have to restart the application after every change in UI. 

@houqp Could you please provide information about layout in koreader? Why component have to be in self[1]?
What are the differences between FrameContainer and CenterContainer? Why one of them has border but other has not?

How to quickly modify UI without struggle and restarting? 
Thanks.

**Comment by houqp** [comment]
You raised many good points @apletnev , our custom UI framework is due for another rewrite. I think after we cut the next stable release, I will focus on improving the frameworks, toolings and documentations to improve developer happiness. So if you can help resolving issue in: https://github.com/koreader/koreader/milestone/4, you can help push the process forward ;)

OK, back to your questions.

The reason we have `self[1][1][1].dimen` is someone was being lazy. You can make this code more readable by assigning `self[1][1][1]` to a variable:

In `ReaderFooter:init()`, do:

```lua
self.footer_frame = FrameContainer:new{ ... }
self[1] = BottomContainer:new{
    dimen = Geom:new{},
    BottomContainer:new{
        dimen = Geom:new{w = 0, h = self.height*2},
        self.footer_frame,
    }
}
```

Then in `ReaderFooter:_updateFooterText()` do:

```lua
 UIManager:setDirty(self.view.dialog, "ui", self.footer_frame.dimen)
```

> @houqp Could you please provide information about layout in koreader? Why component have to be in self[1]?

We really should write up documentation about this. Long story short, you can put any widget as self[1]. When the UI framework draws a widget, it calls its paintTo method. By default, the paintTo method will just draw whatever is in `self[1]`: https://github.com/koreader/koreader/blob/master/frontend/ui/widget/container/widgetcontainer.lua#L48.

> What are the differences between FrameContainer and CenterContainer? Why one of them has border but other has not?

FrameContainer handles the styling like frames, padding, margin, background, etc. CenterContainer handles position of it's `self[1]`, so it just draws `self[1]` into the center of its own dimension.

> How to quickly modify UI without struggle and restarting?

Five years ago, when the project was still called KindlePdfViewer and we still have the legacy UI framework (it's so hacky that I wouldn't even call it a frameowkr), I wrote a vim plugin to auto reload the whole emulator on file changes. Too bad it's not working for the current system anymore ;P

Nowadays, I develop UI widgets using `./kodev wbuilder` command: http://koreader.rocks/doc/topics/Hacking.md.html

Which still requires restarting the emulator, but you can load up just the widget instead of the full reader.

Ideally, we should have the emulator watch a file for reload, so then your editor can just touch that file to signal the emualtor to redraw everything with the new code. But this is not implemented.
