### ISSUE TITLE
Fullscreen request on Android Device

### ISSUE THREAD

**Issue by song19931218** [koreader/koreader#2357]
I have been deeply disturbed by the system status bar when being to dive into a reading. 
Therefore, to get a fullscreen reading, I have installed another software that can remove or hide,said exactly, the status bar.
 It will be really great if there is a fullscreen function within Koreader itself.

is there a solution ?

**Comment by houqp** [comment]
Yes, otherwise games won't be able to go full screen ;) KOReader is basically written like a game in Android because it's just drawing raw pixels to the screen buffer.

**Comment by Frenzie** [comment]
Implemented in #2938.

**Comment by ildar** [comment]
It's now disabled for newer Android versions: https://github.com/koreader/koreader/blob/master/frontend/ui/elements/common_settings_menu_table.lua#L153 , it is made by https://github.com/koreader/koreader/commit/b15c2ed0c5e7130790f266843401d0ceafbb0478

1. why disabled for newer versions?
2. Could it be implemented for newer versions?

Please reopen this issue. Thanks.

**Comment by Frenzie** [comment]
Presumably it didn't work anyway. Pinging @pazos

**Comment by pazos** [comment]
> why disabled for newer versions?

because it just works for devices with ice cream sandwitch which implemented some sort of navigation bar on the status bar (ie: ereaders with a top bar and buttons).

Could it be implemented for newer versions?

all versions start in fullscreen mode. From kitkat onwards it is called immersive sticky and you can show status bar and buttons by swipping (they will be hidden after a few seconds).

@ildar: could you please tell me which device do you have and which problem are you experiencing? thanks!

**Comment by ildar** [comment]
Anybody please reopen this one? Having this option is very desirable. Thanks
