### ISSUE TITLE
How to discard progress bar on minibar?

### ISSUE THREAD

**Issue by roger64** [koreader/koreader#2361]
Hi,

Since the last year, I used a mini-bar with these three items: pages, battery and time. Recently, a fourth item has been added alongside the former three: a plain progress bar that I do not manage to discard.

I read that 15 days ago there has been a "footer refactoring" of some kind.

So from a discrete and convenient mini-bar setting, I now have a very different and - for me - unpleasant one

* KOReader version: v2015.11-694-g64bc5cd (also on v2015.11-675-g09f2db3)
* Device: Kindle PW3 (2015 edition)

#### Issue
Cannot discard progress bar in mini-bar even with the following setting in persistent.lua file

[CODE]
-- configure "mini" progress bar
DMINIBAR_ALL_AT_ONCE = true
DMINIBAR_PROGRESSBAR = false
DMINIBAR_TIME = true
DMINIBAR_PAGES = true
DMINIBAR_NEXT_CHAPTER = false
DMINIBAR_BATTERY = true
[/CODE]

#### Steps to reproduce

Try the above settings.

**Comment by Frenzie** [comment]
I assume you mean #2317?

**Comment by roger64** [comment]
@Frenzie 
Yes. I have been informed through MobileRead (Alan_S) but it's very probably a direct consequence of [#2317.]
The items "progress bar" and "pages" were different and I think they should stay so because:
- Koreader's advantage is first and foremost about providing choice for the user. 
- to see a full progress bar as a bottom line is really different than a plain figure.

**Comment by Frenzie** [comment]
Have you tried changing the footer settings through the visual menu, btw?

**Comment by retrue** [comment]
I tried to change the footer setting through the visual menu and i was not able to discard the progress bar on minibar.

**Comment by houqp** [comment]
As I mentioned in #2317, item `progress bar` was removed completely because it was partially broken and introduced a lot of complexity into the footer display logic (I guess that's why it was partially broken). To simplify the code, I decided to remove this setting because a progress bar only fills up the remaining space at the bottom after all other text information has been drawn, so I thought no one would want to disable it. It fills up the empty space in the mini bar to make it look better and also provides extra information. Notice the progress bar and pages info are still treated differently, you can verify this by disabling all info then toggling "pages" info.

Now that you guys raised this issue, I would like to know more about why you want to disable the progress bar completely. Is it because it visually looks bad or because you were afraid of it taking up spaces from other text info?

BTW, I am not trying to reject your request, just trying to figure out what's the use-case and if this really needed to be included into the core code.

**Comment by oldhasbeen** [comment]
I would not have raised that issue by myself but since it is now addressed: I have always removed the progress bar. Never been interested in that feature. Current Page number/total page numbers in the book is meaningful info for me. Progress bar can anyway be conveniently displayed in the top with the full progress bar setting if I want. To crowd the bottom with it distracts me. Is a personal thing.

**Comment by Frenzie** [comment]
Btw, I find the way these settings work confusing. I have enabled "show all at once" and then disabled stuff that doesn't interest me like book & chapter time to read. If you disable "show all at once" you get a progress bar and the current page.

I can understand why one wouldn't want the status bar. It's a rather thick visual element at the bottom. How hard would it be to just draw it in all white or something like that?

**Comment by retrue** [comment]
In my case I have a Kobo Mini and I read in portrait mode. That means that the space at the bottom of the device is small. I have activated a lot of information to display there: hour, battery, number of pages/total pages, pages until end of chapter and percentage of read book. All that means that the space that remains for the bar progress is very small. It visually looks bad because it is too cluttered and it doesn't add useful info.
![reader_2016-nov-20_123316](https://cloud.githubusercontent.com/assets/18194241/20462412/d3301c4e-af1d-11e6-813c-c699739729ed.png)
On the Kobo Mini the bar looks even smaller.

**Comment by Frenzie** [comment]
@retrue I do think it adds useful info, but like I said it's definitely visually cluttered.

**Comment by AlanSP1** [comment]
@Frenzie 

> I can understand why one wouldn't want the status bar. It's a rather thick visual element at the bottom. How hard would it be to just draw it in all white or something like that?

You now have option to remove chapter marks from status bar. I think that you're asking about this? It is called "Show table of content markers". Also, from defaults.lua you can control its size (thickness), if you want that. I made mine 10px thick.

On general note, how I like to use it, I like to have all info I can get (well, we all are different in our own way). So my progress bar is pretty small one, even on my H2O. That's why I asked for option of placing progress bar in a new line, where it would be only progress bar, and having all other info where it is. Of course, controlled by setting. Asked it here: https://github.com/koreader/koreader/issues/1933

This is my preference and I get that some like to have this much differently from my preference.

So, if it is possible, I would like there is option to completely disable progress bar for people who like it that way.

**Comment by Frenzie** [comment]
No, I mean draw it in white/transparent. It doesn't need to be really
disabled, it just needs to look that way.

**Comment by Frenzie** [comment]
My own preference is as I already indicated. With progress bar & chapter marks, but when I don't want it I just toggle the whole thing on and off.

**Comment by AlanSP1** [comment]
@Frenzie I misunderstood what you meant. But, all in all, I'm agreeing with you that it would be good to have option to remove it completely for people who like it that way.

I know people who want their device looks as close to books as they can. I prefer many statistics, but why not make the most versatile solution as possible.

**Comment by trekk2810** [comment]
I never used the progress bar, infact I find it visual distracting.  I like reading with only _page numbers/clock/battery status_ shown as text, so personally I would prefer the option to discard the progress bar :)

**Comment by roger64** [comment]
This is how I like (and used) to read. I never used the progress bar because I find too distracting. And having to toggle on and off is not really a progress...

http://pix.toile-libre.org/?img=1449824107.png

**Comment by Frenzie** [comment]
I think that looks good!

**Comment by houqp** [comment]
I see, thanks for all the feedback so far. Now that I know it's visually distracting, I think it makes sense to have the disabling feature implemented in the core.

Not painting that bar is the easy part, the hard part is making it a togglable mode when "show all at once" is disabled. The code was evolved into the current state by keep adding features without a proper design and the progress bar was treated as special case for unknown reason and makes the logic convoluted. Given on the feedback so far, looks like the use-case is to disable it completely instead of make it togglable, which makes it a lot easier to add. So yes, I will add an setting to support it.

I also thinking whether we should just support "show all at once" mode and remove the tap to cycle through various footer mode feature. I personally don't find it useful. Thoughts?

**Comment by Frenzie** [comment]
I think cycle could potentially be useful on a small and/or low-DPI screen
while only cycling between two or three things max. That being said, I
certainly wouldn't miss it.

**Comment by roger64** [comment]
@houqp 

Thanks for your quick help for giving us again the choice to disable the progress bar. 

As you ask some user feedback about it, I find the "show all at once" option quite useful. Why "cycle" through three (or more) different options when you can have three of them together on a six inch screen? (see image above).

Anyway, as a guiding principle, what increases the user choice seems good, and whatever limits it will always make someone unhappy.

**Comment by oldhasbeen** [comment]
@houqp 
I do not see any value in cycling through the footer display. I have all I want displayed at the same time. And since the goto page call is linked to the footer display I would find it rather annoying to cycle through all options to turn it off. And I need to turn it off to avoid goto page interference when I look up words in the dictionary in the last two lines or so.

**Comment by AlanSP1** [comment]
@houqp 

> Given on the feedback so far, looks like the use-case is to disable it completely instead of make it togglable, which makes it a lot easier to add. So yes, I will add an setting to support it.

I'm not sure if you mean you'll disable it completely for all or just add option that enables it be disabled for users that don't want to see it in any mode. I still prefer having status bar visible for myself. Just in case if you wanted to disable it for all.

About show all at once, this is only option I use and I don't want to cycle through numerous progress bars. I don't know if there is people who don't use show all at once, but I don't and don't have a need for this. I like to see all things in one status bar.

**Comment by KenMaltby** [comment]
I don't use "Show all at once" and prefer to cycle through the few I use whenever I need them.

**Comment by houqp** [comment]
Interesting, I will just keep the tap to cycle mode feature for now then. But I am planning to make "show all at once" with only pages info enabled by default. This whole UX needs to be revisited for the next-gen UI.

**Comment by roger64** [comment]
Hi

Though I understood that you had agreed to reverse this progress bar "forced" display, I am not aware of any change allowing the user to discard the progress bar. Maybe I missed something? Will it be implemented with the incoming release? Or will we have to wait for the "next-gen UI" you were speaking about? Could you please provide us with some information about it?

2017 greetings.

**Comment by houqp** [comment]
I just haven't had time to make the change yet. I will close the ticket when it's done. It can be done in the current UI.

**Comment by roger64** [comment]
Thank you for your help.

**Comment by roger64** [comment]
Hi
With the 8th of March release, I had hoped the users which dislike the progress bar would at last be able to avoid it, but it seems to stay longer on our screens, like it or not.
Thank you for your tireless work.

**Comment by houqp** [comment]
Sorry for the delay, I got most of the work done for this change on the plane last week. Should be able to wrap it up this weekend.

**Comment by roger64** [comment]
Thanks for this good news. Quite happy that you landed safely!

**Comment by houqp** [comment]
I have renamed the footer setting from `progress_bar` to `disable_progress_bar`. You should be able to start testing this in the next nightly build. I will submit a PR later to implement automatic setting migration to make this transition seamless to users.

**Comment by Biep** [comment]
So is there a way to have all the information shown at once?  If so, how do I choose that option?  It doesn't show up when cycling through the options.
Ideally, there should be a tick menu, where one can indicate what information one wants to see (and if the order could be changed there that would be truly ideal).  Another option would be a format string.

**Comment by Frenzie** [comment]
Please feel free to open a new issue, or you can also use the forum.

The statusbar can be set up under settings → statusbar:

![screenshot_2019-01-30_17-23-01](https://user-images.githubusercontent.com/202757/51995838-d56dce80-24b3-11e9-8af3-b085d0cb3947.png)

![screenshot_2019-01-30_17-24-13](https://user-images.githubusercontent.com/202757/51995857-df8fcd00-24b3-11e9-9f80-90616a6c5fda.png)

**Comment by Biep** [comment]
Ah, ik heb het gevonden.  Bij mij staat die statusbalk niet daar, maar onderaan staat "Page 1 of 2", en ik kan naar pagina 2 van het menu, waar eenzaam die statusbalkverwijzing staat.
Vreemd dat het gepagineerd is, want er was ruimschoots ruimte voor een extra regel op de eerste pagina.

Hoe dan ook: Dank!!

 ---- On wo, 30 jan 2019 17:24:26 +0100 Frans de Jonge <notifications@github.com> wrote ----
