### ISSUE TITLE
Remove the *Opening file…* notification

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2365]
I'm trying to remove the notification that appears each time a file is opened: I don't find it necessary.

I've tried commenting this:
```
    UIManager:show(InfoMessage:new{
        text = T(_("Opening file '%1'."), file),
        timeout = 0.0,
    })
```
out in `frontend/apps/reader/readerui.lua` but it triggers a crash and `crash.log` doesn't provide any hints on why *koreader* crashed.

**Comment by AlanSP1** [comment]
I found that information useful.

Without that information, I might think that I didn't press anything. Some of my books take a time to open (3 or more seconds, some more than 10 seconds). This info in some way tells me that I did action and now have to wait.

Speaking about this, with one book I have crash that leaves device on that notification. After a long time I realized it is not that long that book needs to be opened, but that device has crashed. But having this notification is more helpful than not.

If you remove that notification, we should be able to have option o still see it.

**Comment by baskerville** [comment]
There's already a feedback: the foreground and background colors of the corresponding entry are swapped.

**Comment by AlanSP1** [comment]
When you start koreader, you also need to wait to open file. Notification, at least for me, helps me understand that I'm waiting for file to open. But, I don't mind having option for making this notification on or off.

People generally want to have some feedback, that device is working on something. That's why Microsoft started to use dynamic progress bars, people prefer UI that way. I'm just saying...

**Comment by KenMaltby** [comment]
The info in the box is a detailed conformation that the proper book is the one opening.  More than just that some file is opening.

**Comment by Eduardomb22** [comment]
don´t remove it.

**Comment by KenMaltby** [comment]
There is a problem with the "Downloading" text that overlays, and obscures the info you could use to find a downloaded file.  You might lose track of where the downloading folder is set.

**Comment by houqp** [comment]
@baskerville I don't have my dev machine right now, what error were you getting? Can you paste it here?

I am also curious why you find this popup annoying since the popup disappeared automatically after the book is loaded.

**Comment by baskerville** [comment]
I'm not getting any error: *koreader* just crashes and there's no backtrace in `crash.log`.

I find the popup useless because the other feedback already conveys enough information to me. But I won't mind making this optional.

**Comment by AlanSP1** [comment]
From my perspective, having this as an option and having by default notification visible is fine for me. People who dislike notification can easily disable it, others who don't mind (or find it useful) can continue to have things as before.

**Comment by houqp** [comment]
I took a quick look at it. It's because koreader decided to exit the UI loop because there is no widget to show(after filemanager is closed and before readerui is launched). @baskerville it would be much easier to develop with the emulator, you can set that up with vagrant: https://github.com/koreader/virdevenv/tree/master/vm/ubuntu.

**Comment by Frenzie** [comment]
I'll close this for now, but PRs welcome. ;-)
