### ISSUE TITLE
Various small fixes

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#2394]
(follow up of #2391, see intro there)

disable-wifi.sh
- added a "sleep 1" between "rmmod -r dhd" and "rmmod -r sdio_wifi_pwr", otherwise my kobo glo HD hangs

frontend/apps/reader/modules/readerbookmark.lua
- Reverted this commit : https://github.com/koreader/koreader/commit/a049eddcbc3a440be423b461fd15bec1a0971c82 otherwise, if one changes font size or orientation, one lose all his "dog ear" (top right), cause epub's xpointer of start of page is no more the same as what was recorded.
@houqp : what was that commit for ?

frontend/apps/reader/modules/readertoc.lua
- Added missing reset of self.expanded_nodes in ReaderToc:resetToc() : otherwise, if on a page in a 2nd level section, if you switch orientation (resetToc() called), the TOC is stuck with the section you're in unexpandable.

frontend/ui/widget/imagewidget.lua
- Don't cache image when when self.height > 200 (screensaver images)
- Avoid multiple rendering of the same image (ImageWidget:_render() is called 2 times when displaying a screensaver) : saves 500ms in displaying screensaver image.

frontend/ui/widget/networksetting.lua
- Added missing progress = 0 in  MinimalPaginator.new(), otherwise crash if wpa_supplicant has already connected

frontend/device/generic/device.lua
- Added to Network Info : connected SSID and a quick ping of the default gateway (os.execute linux commands, works on my kobo, would have to be checked on other devices)

frontend/ui/uimanager.lua
- In UIManager:_refresh(), if mode == full, reset self.refresh_count to 0 so that when we explicitly request a screen refresh (via diagonal swipe), the couting to self.FULL_REFRESH_COUNT is reset.

data/epub.css
- commented out for h1, h2, h3, .title, .title1, .title2, .title3 : "/* page-break-before: always; */" , otherwise, if chapter starts with a title in h1, h2..., when jumping from TOC, or using prev/nextChapter, one lands on a blank page. Works for my epubs, dunno if that can have side effects with some layouts.

**Comment by houqp** [comment]
I am happy to merge all these fixes :) Feel free to send us a PR.

> Reverted this commit : a049edd otherwise, if one changes font size or orientation, one lose all his "dog ear" (top right), cause epub's xpointer of start of page is no more the same as what was recorded.
@houqp : what was that commit for ?

My bad for not putting more info into the commit message. I should also have written a unit test for that commit. I hate the past me now :( You are correct that this commit introduced a bug for dog ear display. 

The semantic of this method is to check whether `item.page` and `pn_or_xp` fall in the same page. So calling `self.ui.document:isXPointerInCurrentPage(item.page)` without `pn_or_xp` is definitely not correct. What we actually need here is `self.ui.document:areXPointersInSamePage(item.page, pn_or_xp)`. `areXPointersInSamePage` is something I made up here, I need to look into crengine's code to see if it actually supports it. If not, we will have to implement it ourselves. I have created an issue as a reminder for myself: https://github.com/koreader/koreader/issues/2395. You are welcome take a stab at this too.

> commented out for h1, h2, h3, .title, .title1, .title2, .title3 : "/* page-break-before: always; */" , otherwise, if chapter starts with a title in h1, h2..., when jumping from TOC, or using prev/nextChapter, one lands on a blank page. Works for my epubs, dunno if that can have side effects with some layouts.

This sounds like a bug to me. Do you only see the blank pages with the chapter jump? Or are those blank pages always there between chapters? I recall @frankyifei fixed a similar issue before.

**Comment by poire-z** [comment]
Still learning git/github, so what's the right thing to do in this case ?
- 7 branches & 7 PRs with each a single commit ?
- 1 branch & 1 PR, with 7 individual commits for each fix ?
- 1 branch & 1 PR, with a single commit for all ?

> You are welcome take a stab at this too.

Not sure i can help (I can read some C, but that cre code is tough - i definitely can't write any C and don't have the build environment - i'm just able to hack lua and test directly on the reader)
Should i still let this revert in, as a temporary fix ?

> Do you only see the blank pages with the chapter jump? Or are those blank pages always there between chapters? 

They are always there, even when next-pag'ing and meeting a new chapter.
It happens with 10% of my epub. In one of them, there is :
in `toc.xhtml`
```
        <li id="toc6">
          <a href="c01.xhtml">some title</a>
        </li>
```
in `c01.xhtml` :
```
    <body epub:type="chapter bodymatter">
    <p class="header"> </p>
    <section epub:type="chapter bodymatter" class="chapter">
    <a id="page-9"/>
    <a id="title2"/><h1 class="title"><b>some title</b></h1>
    <a id="page-10"/>
```
The TOC entry points to a xhtml file. There is a quite empty (it actually contains some unicode other kind of space - i should really check it's not a unicode page break - I don't have the file at hand) `<p>` (probably to move the title a bit down), then the title, and this epub.css adds the page break in between.
Commenting /* page-break-before: always; */ has the side effect that koreader won't add itself a page break before titles - may be people got used to that, to see new titles on a new page.
But it's may be more respecful to the publisher intention.
(Also, dunno if this epub.css is a work of the community, or if it comes from some standard that we better not move from too much ?)

**Comment by Frenzie** [comment]
I'd say one PR/branch per big feature (e.g., 1 for file manager, 1 for
reader) and the commits can (and sometimes should) be smaller. Like changed
dialog X, fixed bug Y can all belong to the file manager branch.

On Dec 2, 2016 14:55, "poire-z" <notifications@github.com> wrote:

Still learning git/github, so what's the right thing to do in this case ?

   - 7 branches & 7 PRs with each a single commit ?
   - 1 branch & 1 PR, with 7 individual commits for each fix ?
   - 1 branch & 1 PR, with a single commit for all ?

You are welcome take a stab at this too.

Not sure i can help (I can read some C, but that cre code is tough - i
definitely can't write any C and don't have the build environment - i'm
just able to hack lua and test directly on the reader)
Should i still let this revert in, as a temporary fix ?

Do you only see the blank pages with the chapter jump? Or are those blank
pages always there between chapters?

They are always there, even when next-pag'ing and meeting a new chapter.
It happens with 10% of my epub. In one of them, there is :
in toc.xhtml

        <li id="toc6">
          <a href="c01.xhtml">some title</a>
        </li>

in c01.xhtml :

    <body epub:type="chapter bodymatter">
    <p class="header"> </p>
    <section epub:type="chapter bodymatter" class="chapter">
    <a id="page-9"/>
    <a id="title2"/><h1 class="title"><b>some title</b></h1>
    <a id="page-10"/>

The TOC entry points to a xhtml file. There is a quite empty (it actually
contains some unicode other kind of space - i should really check it's not
a unicode page break - I don't have the file at hand) <p> (probably to move
the title a bit down), then the title, and this epub.css adds the page
break in between.
Commenting /* page-break-before: always; */ has the side effect that
koreader won't add itself a page break before titles - may be people got
used to that, to see new titles on a new page.
But it's may be more respecful to the publisher intention.
(Also, dunno if this epub.css is a work of the community, or if it comes
from some standard that we better not move from too much ?)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/koreader/koreader/issues/2394#issuecomment-264458894>,
or mute the thread

**Comment by poire-z** [comment]
> I'd say one PR/branch per big feature (e.g., 1 for file manager, 1 for reader) and the commits can (and sometimes should) be smaller. Like changed dialog X, fixed bug Y can all belong to the file manager branch.

Yes, sounds fine for my other 3 issues.
But for this one with 7 or 8 unrelated fixes (unrelated except for the smallness) ?
Do you prefer 1 commit "Various small fixes (see #2394)" in the commit history?
Or history cluttered with 7 commits, yet with more useful messages ("fix toc stuck in some cases", "fix crash on glo hd" .. )?
Also, from your side when reviewing/merging, if I do 7 commits, can u decide to merge only a few of them ? Or they are chained and it's all or nothing ? Just curious and worried about doing things right.

**Comment by Frenzie** [comment]
Personally I prefer smaller but I don't think there's really a project
standard. @houqp?

On Dec 2, 2016 17:22, "poire-z" <notifications@github.com> wrote:

I'd say one PR/branch per big feature (e.g., 1 for file manager, 1 for
reader) and the commits can (and sometimes should) be smaller. Like changed
dialog X, fixed bug Y can all belong to the file manager branch.

Yes, sounds fine for my other 3 issues.
But for this one with 7 or 8 unrelated fixes (unrelated except for the
smallness) ?
Do you prefer 1 commit "Various small fixes (see #2394
<https://github.com/koreader/koreader/issues/2394>)" in the commit history?
Or history cluttered with 7 commits, yet with more useful messages ("fix
toc stuck in some cases", "fix crash on glo hd" .. )?
Also, from your side when reviewing/merging, if I do 7 commits, can u
decide to merge only a few of them ? Or they are chained and it's all or
nothing ? Just curious and worried about doing things right.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/koreader/koreader/issues/2394#issuecomment-264494768>,
or mute the thread

**Comment by houqp** [comment]
> Yes, sounds fine for my other 3 issues.
But for this one with 7 or 8 unrelated fixes (unrelated except for the smallness) ?
Do you prefer 1 commit "Various small fixes (see #2394)" in the commit history?
Or history cluttered with 7 commits, yet with more useful messages ("fix toc stuck in some cases", "fix crash on glo hd" .. )?

Commits should always be minimal and self contained. So please split the patch logically to multiple commits. If two changes fix two different bugs, they should be two commits. This will make git bisecting much easier in the future if any of the commit introduces new bugs into the system. You can still put all the misc bug fixes from this issue into one branch and one PR if that's easier for you. I sometimes make one PR with various misc fixes too. Because the concept of PR is not part of git and will not be logged in the commit history, it's fine to group unrelated stuff into one PR if necessary.

> Also, from your side when reviewing/merging, if I do 7 commits, can u decide to merge only a few of them ? Or they are chained and it's all or nothing ? Just curious and worried about doing things right.

We can use `git cherry-pick` to only pull in a subset of your commits If we want.

**Comment by houqp** [comment]
> Not sure i can help (I can read some C, but that cre code is tough - i definitely can't write any C and don't have the build environment - i'm just able to hack lua and test directly on the reader)
Should i still let this revert in, as a temporary fix ?

You can let this revert in. I definitely recommend you setup the build environment at least for the emulator. This will make it a lot easier for you to test your changes and save you a lot of time. If you find it too much trouble to set everything up following the README, we also provide a virtual machine solution to get you started: https://github.com/koreader/virdevenv/tree/master/vm/ubuntu

> They are always there, even when next-pag'ing and meeting a new chapter.

This sounds like the issue @frankyifei worked on before. Can you provide the book for us to see if it's an expected behavior? epub.css is a work of the community.

**Comment by frankyifei** [comment]
The problem for page-break handling is that most of the epubs do not care much about it. And I believe  it is an important difference between webpage and ebooks. There is little usage of this property in webpage but many ebooks are converted from webpages.
Generally speaking, epub.css make most of epub look better and I'm satisfied with the result. So I think they should not be changed. If most of your books have problem with the epub.css, it is easy to change it in your device. I have several customized css files on my kindle.

**Comment by Frenzie** [comment]
Agreed. I think `h3` is debatable, but for `h2` and especially `h1` that's definitely for the best.

**Comment by poire-z** [comment]
(I did not include that epub.css patch in my PR, and I wont mind just changing mine.)
For you to witness what I see, here's an example [Chapters.zip](https://github.com/koreader/koreader/files/631197/Chapters.zip) , an epub made by other people with calibre from a word document (guessed from the style names). Some of these .calibre styles already include that `page-break-before: always` .

With the current epub.css, when jumping to a chapter from the toc (or with nextChapter):
- with embedded styles on : land on last page of previous chapter (next page = blank page, next next page = chapter first page)
- with embedded styles off : land on blank page (next page = chapter first page)

With my patched epub.css:
- with embedded styles on : land correctly on chapter page (on a new page)
- with embedded styles off : land correctly on chapter page (but no page break at start of chapter = u land on a page with both the end of prev chapter, and the content of the new chapter).

(I haven't my device at hand, i wrote that from memory, may be i mixed the "with embedded on/off" descriptions, sorry if i did - I also haven't tested it with nickel reader)

**Comment by Frenzie** [comment]
Per spec page-break-before:always simply means what you think it means. Not
to add in an empty white page, but that  a page break should be added if
there isn't one. It sounds like crengine might be sticking in an extra page
for *each* style rather than checking if it already happened?

**Comment by houqp** [comment]
That's what I think it should be too. page-break-before should only force content be rendered on a new page rather than adding an empty white page. I don't see any reason why people would want that white page. Perhaps a bug in crengine?

**Comment by Frenzie** [comment]
Can this be closed or is there still anything left?

**Comment by poire-z** [comment]
Most things were commited.
There's just the epub.css discussion, which may come down to personal preferences, and the current behavious does not seem to bug any people (and I can fix that in my own patch).
So yes, can be closed. Closing.

**Comment by Frenzie** [comment]
@poire-z Of course the behavior bugs me, also see #2047 (sorry for not noticing before). But your workaround bugs me more. :-P
