### ISSUE TITLE
Info about Events

### ISSUE THREAD

**Issue by apletnev** [koreader/koreader#2397]
* KOReader version: any
* Device: any

Hi, there!

@houqp Could you please share information about events in Koreader?
Maybe you will provide documentation about it? How to propagate events from child to parent? For example if I display my custom inputcontainer and receive "tap" event, I can't propagate it to other containers. I can't find information (example) about it. 

Thank you.

**Comment by houqp** [comment]
Yes, I will write up the doc for you. If you get stuck in anything else in the future, please don't waste your time poking around unless you are interested in the UI framework implementation. Always file an issue here to push us improve the documentation ;)

**Comment by apletnev** [comment]
@houqp thank you. waiting for new WIKI page. ;)

**Comment by houqp** [comment]
It will be in the code and and get published to koreader.rocks/doc automatically by the travis build. I added some initial doc in https://github.com/koreader/koreader/pull/2408. Will keep adding more this weekend.

**Comment by houqp** [comment]
New doc will be ready once https://github.com/koreader/koreader/pull/2416 is merged. Let me know if you need more clarification on how the system works.

**Comment by houqp** [comment]
@apletnev please check out http://koreader.rocks/doc/topics/Events.md.html

**Comment by apletnev** [comment]
@houqp thank you very much.

**Comment by apletnev** [comment]
@houqp I've read your documentation. And I have additional questions.

For example, if I show a new widget on the screen, I have to register touch zones for it like this:     
```
self.ui:registerTouchZones
```
Set screen_zone method and handle my events. But if I do not want to handle my events, want to pass them to bottom layers as is. Is it possible? 

![screen shot 2016-12-12 at 18 48 39](https://cloud.githubusercontent.com/assets/220872/21108314/7656d86e-c09d-11e6-84f7-380c55014930.png)

See example, i've placed two vertical lines on screen and tapped on screen. I want that the ReaderPaging component handles events (onTapForward, onTapBackward). So the question is it possible to propagate all events from my custom widget to other layers?

Thanks.

**Comment by houqp** [comment]
`self.ui:registerTouchZones` is not required.

If your widget is only for visualization and does not want to handle any input, then you don't have to make it inherits from inputcontainer widget.

I think the issue here is if you show a widget with `UIManager:show`, the new widget will be put into top of the widget stack. And right now, events are only sent to the top widget [[1]](https://github.com/koreader/koreader/blob/master/frontend/ui/uimanager.lua#L378). Since readerui(contains paging) is under the newly created widget, it will not receive the input event.

There are couple ways to pass event down to the widget that's not at the top of the stack. If you let me know what you are creating, I can better understand your usecase and help find the proper solution.

**Comment by apletnev** [comment]
I want to create a simple plugin based on this idea https://youtu.be/jeOHqI9SqOI I've created it and you are right, i've showed it by UIManager:show like other plugins.

**Comment by houqp** [comment]
Ha, I see, this is a cool idea :) So to keep all the input events to the readerui, you need to keep it at the top of the widget stack. The way we add visualization to readerui currently is through the [readerview component](https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerview.lua#L114).

You can start experiment with that as a builtin widget for now. The plugin system does not support tapping into readerview at this point. I will make this part pluggable if I have time this weekend :)
