### ISSUE TITLE
Fails to download book from OPDS with colon in filename

### ISSUE THREAD

**Issue by NickSavage** [koreader/koreader#2433]
* KOReader version: 2015.11-696
* Device: Kindle Paperwhite 3

#### Issue

I have a calibre server set up on the local network that I want to pull books from into koreader. This is functional for all books except books with colons in the filename, where koreader throws the error: "Could not save file to [local directory]"

**Comment by Frenzie** [comment]
The problem is that `:` isn't allowed as part of a filename in Windows, or in this case presumably on Windows file systems like FAT32. One possible solution would be to automatically remove `\/:*?"<>|` (the problematic Windows characters; only `/` is problematic on Linux).

So, just thinking aloud, in pseudo or at least completely untested code, something like:

```lua
function util.sanitizeFilename(str)
    str=str:gsub('\/:*?"<>|','')
    return str
end
```
