### ISSUE TITLE
Android keys are different on updates?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2437]
Hi

It looks like the Android apk keys are changing everytime there is an update on http://build.koreader.rocks/download/nightly/. I have to uninstall the installed version and reinstall the new version. This can only only happen if the apks are generated with different keys or the integrity of the apks have changed.

This is a bit of hassle for me because I have to uninstall and reinstall but the issue is that I use couple other apps to manage the limited space on my Cm67 so  I have to go through bunch of loops on an eink screen to get this going properly. I want to test the new versions but when it is such hassle I just avoid it.

thanks

**Comment by houqp** [comment]
Weird, all of the new nightly builds should be signed with the same key. Only previous nightly builds (the ones uploaded on github) are signed with a different debug key. What version of android is running on Cm67.

**Comment by gerroon** [comment]
@houqp 
Unfortunately that is not the case. I stopped using the github releases, I only use the rocks server. If you are hundred percent sure that the keys are the same then there are 2 options

- Something else changes the apk signatures

- Someone messes with the server uploads and uploads meddled binaries.

**Comment by houqp** [comment]
Not likely due to attack on the server. If the attacker is smart enough to get into the server, he/she should be smart enough to sign all binaries with the same key. It's probably I am not signing the apk correctly. I will take a look as soon as I have time to work on this. If someone else want to take a look at it, here is the code that signs the api: https://github.com/koreader/koreader-misc/blob/master/nightswatcher/nightswatcher.py#L75

**Comment by Frenzie** [comment]
Closing this because I haven't seen any problems.
