### ISSUE TITLE
Don't keep removed files in the history

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2477]
If a file (that appears in the history) is removed through the long press file dialog, then it will still be present in the history.

**Comment by Frenzie** [comment]
Whether that's a problem is debatable. It is, after all, a *history*, so I'd say this is desired behavior. What presumably isn't is what happens when you tap on a deleted file.

**Comment by poire-z** [comment]
Actually, the history cleans itself of unexisting files when:
- first time opened
- opening a document for reading (even if already presents in history)

So you would see your entries removed as soon as you quit filemanager (exiting reader or opening a document).
It also surprised me, so I'll provide a fix (easy, just a few lines to copy and paste from my "Purge .sdr" callback into the "Delete" one).

**Comment by Frenzie** [comment]
@poire-z Then undesired deletion already occurs and this is a bug that should be fixed. Expected history behavior is that *all* history be kept and non-existing files might either be grayed out or simply display a "this file does not exist" error message when you try to access them. Anything else would be confusing at best.

So if I understand correctly:

* The desired behavior [should usually occur](https://github.com/koreader/koreader/blob/f95ad00b9e4a1e3bed1f00b0c93afc3efa308b3f/frontend/apps/reader/readerui.lua#L339), i.e., a message is shown that the file does not exist.
* But in some circumstances there's a bug that results in deletion of items from the history.

**Comment by KenMaltby** [comment]
I assume this about actually deleting a file from your device and it then not being removed from the history list.  Removing it from the History listing by long press option, doesn't/shouldn't remove the file from the device. The greyed out approach sounds good.

**Comment by poire-z** [comment]
> Then undesired deletion already occurs and this is a bug that should be fixed. Expected history behavior is that all history be kept 

Depends on how one sees this history feature.

If one sees it as a "reading log" like you seem to do, it's indeed a bug. But it's first a very poor reading log :) : just the filename, no available info of when the reading started, when it was done, when file was deleted...

If one sees it as mostly a way to jump to currently read books like baskerville or I do, it's a feature to have the history cleaned of deleted files, and a nice one to not have to do it ourselves after deleting a file (even if they would be greyed out, i would feel the need to go there to clean them and have an uncluttered history with just my current opened books).

The current behaviour is perfect for my use case (and i assume for most people, if nobody submited an issue about this behaviour) , except for the occasional lag in history auto-cleaning observed by baskerville.

No worry about your other concerns:
Removing a file from history does not remove the file from the device (@KenMaltby : yes, it is indeed about deleting the file in filemanager after a "are you sure?" popup)
A message is indeed shown when you click on a an history item whose file is nore more there.

**Comment by Frenzie** [comment]
It's a file opening log, not a reading log. It's exactly the same as "recently used files" in every other application. You expect it to be there because you opened that file, regardless whether or not it still exists. (Unless you grew up in [the Soviet Union](http://www.tc.umn.edu/~hick0088/classes/csci_2101/false.html). :-P)

> If one sees it as mostly a way to jump to currently read books like baskerville or I do

So do I. Anything more than 5, maybe 10 entries is just there to hopefully never be looked at again. It's faster to open a file through a reasonably well-ordered folder structure in the file manager than through that unsorted mess. But it's there if you need it. Like if you forgot to jot down the exact Archive.org ID. Or if you download a book from Gallica, it has names like `Un_milliardaire_antique___Hérode_[...]Graindor_Paul_bpt6k5682013w`. That last part is rather important in case of multiple editions. This is useful information that you should keep track of if you intend to use it again. Unfortunately you sometimes fail to for some reason. But note that this has nothing to do with *reading*, only with opening. I might've just glanced at the title page and a few paragraphs of the introduction, maybe not even that. The point is that history is history.

> i would feel the need to go there to clean them and have an uncluttered history with just my current opened books).

I can certainly see where you're coming from, but *history* it's not. :-)

> The current behaviour is perfect for my use case (and i assume for most people, if nobody submited an issue about this behaviour) , except for the occasional lag in history auto-cleaning observed by baskerville.

Like I said, confusing at best. In actual practice it's conceivable that I lost some history and didn't even realize it. That's much worse.

Btw, glancing through the code I don't see it calling delete anywhere but upon user request?

**Comment by Hzj-jie** [comment]
If the history is coming from a very old history file (in koreader/history folder), removing a file won't impact the history list. This change to deprecate the old history file happened 7 month ago, so it's more likely you won't be impacted by it.
As @poire-z said, for newly opened books, history list should be cleaned each time it's regenerated, i.e. open FileManager; or a new entry has been added, i.e. open a new book. Nonexistent files will be removed from history list. The reason readhistory module does not actively remove item when deleting a file in FileManager is because of performance concern. Lua does not provide a simple binary search method, you may find several TODOs in readhistory.lua.

If the behavior is other than the two mentioned above, it should be a bug.

I do not really think purging .sdr folder in readhistory for nonexistent files is the right thing to do. IMO, anything related to permanently delete information should be warned to user and an approval is required. For the .sdr folder, it contains user highlightings, bookmarks, reading progress. Even the associated book has been deleted, users can still restore everything by copying the book file back, or export highlights to evernote / html.

**Comment by Frenzie** [comment]
> Nonexistent files will be removed from history list. 

I consider that a bug. I don't live in the [Soviet Union](https://en.wikipedia.org/wiki/Censorship_of_images_in_the_Soviet_Union), you know. :-P But seriously, silently losing data is a bad thing. [These lines](https://github.com/koreader/koreader/blob/ced671bc6916c929a8d8224a7106e84abfe26184/frontend/readhistory.lua#L50-L54) should be removed.

**Comment by ersi-dnd** [comment]
Good evening. I'm a (somewhat) happy user of Pocketbook Inkpad 2 + Koreader. 

Pocketbook Inkpad 2 has its nasty bugs. One of them is that the microSD card suddenly, in the middle of reading out of the blue, vanishes from the system (fails to be recognised all of a sudden). Luckily it doesn't happen too often, about once or twice a month. When this happens, Pocketbook automatically re-scans the library, and that's how I see that most of my library has vanished.

When this bug occurs while I am in Koreader, my file manager *and history* in Koreader become empty. Usually this only lasts until I restart to fix things. My history list is my reference list - list of files roughly in the order of importance - and I'd be very happy to see it stay put. 

Once, however, it happened that my history list in Koreader vanished for good. Then I had to re-create it by painful bloody suffering. I am not sure if the irreversible deletion of the entire Koreader history occurred due to Koreader crash (I'm positive though that it *did* crash on the occasion) or because of the Pocketbook bug, but it would be great if the list were steady and secure.

Is there a specific file that keeps the history?

**Comment by Frenzie** [comment]
As @ersi-dnd indicated files might not be available for some reason (e.g., path not mounted), which turns a more theoretical problem into a practical one. How about this as a compromise? The harmful lines will be moved to an explicit user invocation, something like this:

![screenshot_2017-02-25_19-09-42](https://cloud.githubusercontent.com/assets/202757/23333600/47eebd76-fb8e-11e6-8737-3abe4c59eb44.png)

**Comment by poire-z** [comment]
That looks fine for people with the mount problem, and I admit the current auto cleaning behaviour may be unwanted for them. And also for devices with SD cards where people can switch cards.
So, this proposal, and the removal of the auto cleaning where it happens, are good.
But I'd like it if there is a (default'ly unset) 'autoremove_deleted_items_from_history' setting that will make the current auto-cleaning still happen for those who like it :)
