### ISSUE TITLE
A button in text search doesn't work

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2489]
* KOReader version: Last nightly builds
* Device:

#### Issue
When you search for a word in a document it appears a bar with four buttons. The first button, to go to the first apparition of that word in the document, doesn't work. The other three buttons work correctly.

![reader_2017-jan-13_144315](https://cloud.githubusercontent.com/assets/18194241/21932258/f1c2dc58-d99f-11e6-853f-a7994f55eb0a.png)

**Comment by retrue** [comment]
In other book, that first button works, so I don't know why it didn't work with that book.
I would have to try with several books to try to identify what is the problem.

**Comment by Eduardomb22** [comment]
The button works fine here.

**Comment by retrue** [comment]
It worked for me too in other book, but it didn't work when I opened the issue.
What I mean is that on certain circunstances, the button doesn't work. Maybe it is the book or maybe it is the word. Maybe it works if I look for a rare word in the book but it doesn't work is the word appears often.
I don't know. Maybe one of the developpers could look at the code and see if there is something missing or maybe this issue should be shelved until I or somebody else can find a concrete example.

**Comment by retrue** [comment]
Confirmed. Using last nightly build.
Different word, different book. A word that appears only ten times or so in the book and the button to search for first appearition of the word doesn't work.

**Comment by Frenzie** [comment]
I suspect it's a problem in crengine itself. I've been using this KOReader-generated Wikipedia article EPUB for some quick tests: [Statistics.EN.epub.zip](https://github.com/koreader/koreader/files/887481/Statistics.EN.epub.zip) (remove the extra .zip; that's just for uploading it on GitHub).


I've been able to identify at least two scenarios that don't play out quite how I would expect them to:

1. Search for the word `organization` in `Statistics.EN.epub`. There are two results, but the last result (which is actually "organization*s*") only shows up by pressing the next arrow and not by pressing the last arrow. Is this the same behavior you've found?
2. Search for the word `data`. You'll only be able to get to the first result if you're sufficiently far away from it. Although actually I suspect it might be going to the wrong page without finding the first result because that's a link.

**Comment by retrue** [comment]
I can send by email the book I am reading to any developer who wants to check this problem. It is happening with several books. First button in search doesn't work. The other three buttons work.

**Comment by Frenzie** [comment]
I can't promise to fix it, but I'll certainly take a peek at it to see if I can figure out a better way to reproduce the problem. If you want to e-mail, I've got mine listed here: http://fransdejonge.com/about/

**Comment by houqp** [comment]
definitely sounds like a bug in crengine :(
