### ISSUE TITLE
Last nightly build (2015.11-816) should be removed from OTA servers.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2509]
* KOReader version: v2015.11-816
* Device: Kobo Mini

#### Issue
I have just updated through OTA to version 816 from last nightly build (814). With the update I have lost all the information that KOReader had about my books. The history is still there, but when I open any book in the history, it appears like I had never opened it before: No bookmarks, last page open, book status, font and font size chosen, hyphenation preferences, etc. All of that is lost.
Last nightly build should be removed from OTA servers to avoid that other users lost all that info.

**Comment by poire-z** [comment]
Confirmed: metadata file in `<filename>.sdr/` directory is now named `epub.lua`, instead of `metadata.epub.lua` .
The `metadata` part has been forgotten by there: https://github.com/koreader/koreader/commit/529d1b3d33007c697ab8f0d731fee8abd67c17c5#diff-76de9a14e1e42ed4e9ff8249052ddb05L76

The `metadata.epub.lua` is not lost, and should be used again once this is fixed. You can rename those for the books you read in the meantime, and renamed back when fixed.

**Comment by poire-z** [comment]
Btw, been curious: do we have any stats about how many users download (manually and/vs OTA) nightly builds ?

**Comment by houqp** [comment]
oops, thanks for the report! I have removed that build from the server. New build should show up in roughly 30 minutes: https://gitlab.com/koreader/nightly-builds/pipelines/5956812/builds

@poire-z we keep all the access log on the server, but they are not being analyzed.

**Comment by poire-z** [comment]
Build is still named 816 (shouldn't it be 817 with the fixing commit?)
It does not include the fix (docsettings.lua still as before).

**Comment by retrue** [comment]
Yes, I have just updated to this new 816, manually because I already had installed the previous 816, and the problem is not fixed.

**Comment by houqp** [comment]
My bad, I forgot the gitlab builds are cloning from gitlab mirror instead of github. Gitlab mirror wasn't updated automatically at the time I triggered the build. I have retriggered all the builds on gitlab. 817 should be available in 30min.
