### ISSUE TITLE
Calibre wireless connection not established (correctly)

### ISSUE THREAD

**Issue by allati** [koreader/koreader#2540]
* KOReader version: v2015.11-847-g726b15a
* Device: Kobo Aura H2O

#### Issue
Several months ago Koreader nightlies stopped connecting to Calibre wireless server. It didn't bother me enough to remember exact build when it happened, so I cannot provide version info when the problem began. Latest stable release (koreader-stable-v2015.11) works OK however.

#### Steps to reproduce
1. Start wireless server in Calibre. Server starts.
2. Connect Koreader to Calibre wireless. Client says that it is connected.
3. Calibre does not react to established connection, no connected device menus appear, no "On device" column. If you try to do anything related to wireless connection in Calibre (i.e. open "share" menu or try to upload a book), it's UI becomes unresponsive.

I compared network traffic of working and affected by the issue versions of Koreader. The difference is that after Koreader opens connection and Calibre server sends it's version, capabilities, etc., stable version of Koreader responds back with info about itself (like version, known formats and the like), but affected version does not respond at all.

I tried doing fresh install of latest and oldest available nightlies (v2015.11-793-gf95ad00, v2015.11-847-g726b15a), but neither worked.

**Comment by matkara** [comment]
+1 
Device: Kobo Aura One
KOReader version: v2015.11-894-gd168db9

Calibre becomes unresponsive once the connection is established, just as described in Allati's post.
It is more a Calibre problem than a KOReader issue though.

**Comment by matkara** [comment]
It might actually come from KOReader, see this [thread](https://www.mobileread.com/forums/showthread.php?p=3492078)

**Comment by Frenzie** [comment]
I see no contradiction there. It's a (recent?) calibre issue that surfaces
because of something KOReader does or doesn't do. I assume it's easier to
fix on this end but that whole GUI freezing business is all calibre. :-p

On Mar 18, 2017 17:42, "matkara" <notifications@github.com> wrote:

It might actually come from KOReader, see this thread
<https://www.mobileread.com/forums/showthread.php?p=3492078>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/koreader/koreader/issues/2540#issuecomment-287558223>,
or mute the thread

**Comment by matkara** [comment]
>  I assume it's easier to fix on this end but that whole GUI freezing business is all calibre. :-p

True ;)

These soft are great, that's why paradoxically people are reporting bugs and unexpected behaviors ;)

**Comment by lgeek** [comment]
I've looked a bit into this. The calibre companion plugin uses a StreamMessageQueue, which is registered with UIManager:insertZMQ(). The problem seems to be in UIManager:handleInput(): wait_until is never nil and therefore "if not wait_until" never succeeds and waitEvent() is never called on the StreamMessageQueue. I was able to get the plugin to (sort of) work by hacking the inner loop to execute unconditionally. However, other input events have to trigger during that time so that handleInput() keeps executing. Now, I have no idea how this stuff is supposed to work. Is ZeroMQ supposed to execute a callback at some point, which is lost?

**Comment by Frenzie** [comment]
Hm, I just tried this and it seems to be working fine for me. I tried sending a file and it was received.
![screenshot_2017-03-31_15-35-34](https://cloud.githubusercontent.com/assets/202757/24552693/c1405f78-1627-11e7-81bb-458a18348384.png)

**Comment by lgeek** [comment]
@Frenzie Hmm, I was using the git master head 4 days ago when I've posted that (albeit on okreader, not Nickel). Something I've noticed is that you're using an older calibre version, but I don't think it would matter since the issue appeared to be on the koreader side.

**Comment by matkara** [comment]
Allati and I are running koreader under the Aura flavor. Would it matter?

**Comment by Frenzie** [comment]
It does indeed make a difference. I tested this on the emulator, first locally and just to be sure also remotely over wifi (from my laptop), which works. But with my H2O I can reproduce the calibre freeze.

I'll build a Kobo release to see if it's related to other (newer) libraries on my system. Although given that iirc the nightlies are built on Ubuntu 16.04 I doubt it should.

Note to self: update the readme with this extra Kobo build dependency:
```
libc6-dev-i386
```

**Comment by houqp** [comment]
@lgeek's root cause analysis is correct.

Difference being in emulator, `wait_until` can be `nil`. But in kobo, there are some default always scheduled tasks like auto suspend that will make `wait_until` never set to `nil`. Features like auto suspend are added long after the zmq integration.

I think a proper fix will require a deeper integration of our input event loop's select call with zmq's poller. The current implementation is a little bit hacky because it only checks the zmq poller when the input loop is completely idle :(

**Comment by houqp** [comment]
So I can think of two approaches for the proper fix here:

1. spin up a separate thread/process for a zmq event loop, which writes readable signal into the current main input event loop through fd. this is how we are handling uevent right now.
2. refactor the main input event loop to use zmq_poll instead of select, which means we need to wrap all the existing fds a zmq_pollitem_t.

I think option 1 is cleaner and easier to implement.

**Comment by deviantintegral** [comment]
Running koreader-nightly-20170430 and Calibre 2.8.4, I'm not even getting that traceback (assuming launching Calibre in debug mode is right). KOReader shows as connected, but Calibre doesn't show any trace of it.

An OK-but-slow workaround for now is to launch the Calibre web server, and use the web browser to transfer files, and then load them back up in KOReader.

**Comment by KenMaltby** [comment]
Not a fix, but until it gets fixed, a better workaround would be to, start the calibre content server and then use KOReader's OPDS connection to wirelessly acquire your ebooks, from your calibre library.

**Comment by gerroon** [comment]
I seem to suffer from this bug on Android. I use nightlies. It says it is connected in Koreader, but Calibre shows no device connected.

**Comment by rjbergerud** [comment]
@KenMaltby Could you explain how to do this in more detail?
> Not a fix, but until it gets fixed, a better workaround would be to, start the calibre content server and then use KOReader's OPDS connection to wirelessly acquire your ebooks, from your calibre library.

**Comment by KenMaltby** [comment]
First you open calibre on your PC (the PC needs to be attached to a Wireless Network/Router).  Find the "Connect/share" icon, click on that.  Click on "Start Content Server", the three blue balls should turn green.  Click on the "Connect/share" icon again and note the IP address and port.  The rest you do on your KOReader equipped device.  Open KOReader and go to the File Browser.  Poke the search icon and select the "OPDS catalog" option.  Then select "Local calibre catalog", if your Wifi isn't on turnit on.  Once the WiFi is connected, select the "Local calibre catalog" again, and you should see a listing of sort options to the calibre library.  (I usually use "By Newest").  Once you have found a book you want to download from the calibre library onto your device, poke it and you should get a message box with download options.  If you don't have a download directory listed, or you want to use a different one, poke on the "Choose download directory by long-pressing" then long-press on the folder you want to use, among those listed. 

Luck;
Ken

**Comment by rjbergerud** [comment]
@KenMaltby Thank you, that works great.  I didn't notice the "Local calibre catalog" option, and was trying to set it up like any other OPDS, and for some reason that wasn't working.

**Comment by pewpewpewter** [comment]
Hope this gets fixed. Wireless Calibre sync was the sole reason I installed koreader (just downloading over the network is insufficient for my needs, and I'm having great troubles with the Kobo not being recognized over USB), and was quite disappointed to see it doesn't work with my Aura One.

**Comment by Regala** [comment]
Hey @allati just to make sure you can use the wireless connection feature using v2015.11 stable from here: [](https://github.com/koreader/koreader/releases/tag/v2015.11-stable) ?

I'm trying that version using KSM 08 and [patched](https://www.mobileread.com/forums/showpost.php?p=3389190&postcount=221). My device is Kobo Glo HD.

**Comment by ToxicFrog** [comment]
For the record, this appears to still be broken in v2015.11-1422-g021e3db.

**Comment by ToxicFrog** [comment]
Here's a patch that appears to fix it: https://gist.github.com/ToxicFrog/287af96fcfa3f5f5687d4f42650fda0d

It doesn't do any major refactoring, just forces the input event queue to wake up every 50ms if any ZMQs are registered. This shouldn't adversely affect battery life in general because most of the time there are no ZMQs; only zsync and calibre-wireless use them.

**Comment by Frenzie** [comment]
Could you please submit that as a PR? It looks slightly better than what we have plus you say it works. ;-)

**Comment by max-cw** [comment]
I tried the patch and now it is showed as connected. It looks like I can send files too, but the books that are already on the device doesn't seem to show up. Maybe I did something wrong?

**Comment by ToxicFrog** [comment]
No, on further testing it's doing the same thing to me. :( The books show up as "on device" after I send them, but if I disconnect and reconnect the kobo they stop showing up in calibre. I don't know if this is a problem with my fix or some other issue with the plugin, though.

I also had one "koreader exited unexpectedly" when copying a large number of books onto it over wifi -- is there any way to get a stack trace when this happens?

**Comment by Frenzie** [comment]
The simple option is just to start it with the `-d` flag if you just want the basic LuaJIT error message. But you can go all out by compiling a build with debugging symbols if you like. :-P

**Comment by ToxicFrog** [comment]
Starting it with -d is just a matter of editing `/.adds/koreader/koreader.sh`  to call `./reader.lua -d ${args}`?

Also, after further investigation it looks like it not displaying any books as "on device" is an existing problem -- calibre sends a `GET_BOOK_COUNT` message and expects the device to respond with a total book count, followed by N messages, one for each book. The implementation in koreader always responds that it has 0 books.

**Comment by ToxicFrog** [comment]
I think I found out why it's crashing, at least:

```
    local filename = inbox_dir .. "/" .. arg.lpath
    DEBUG("write to file", filename)
    local outfile = io.open(filename, "wb")
```

If the intermediate directories don't exist, outfile will be nil and it'll throw when it later tries to call `outfile:write()`. And it's consistently crashing when I try to send books by authors who aren't already on the device (and thus don't have author directories yet).

This should be a pretty straightforward fix -- I have an implementation of `lfs.mkdirs()` already lying around I can use.

**Comment by ToxicFrog** [comment]
Ok, I have that working. Going to clean it up into a branch and submit a PR tomorrow, hopefully.

**Comment by Frenzie** [comment]
Thanks!

**Comment by ToxicFrog** [comment]
:/ The fact that koreader is AGPL now rather than plain GPL (why was it changed?) complicates things -- I'm going to need to ask for special dispensation from work to submit patches. So it may be a few weeks rather than a few days.

**Comment by chrox** [comment]
Just because two of koreader's major dependencies, mupdf and libk2pdfopt, changed to AGPL from plain GPL. So if we want to use their static libraries we must be AGPL too. For some platforms they have to be static.

**Comment by ToxicFrog** [comment]
Sorry this took so long, but here's #3558 incorporating the ZMQ fix and the intermediate directories fix as separate commits.

Some of the stuff in the latter it might be worth pulling out into a separate "lfs utils" module, since they may be useful more broadly than just here.

**Comment by robert00s** [comment]
Is the problem still exist after #3558?

**Comment by allati** [comment]
Thanks for pinging this issue -- I didn't know it was fixed in scope of other tickets. I do not see any issues with Calibre wireless connection now! Thanks to everyone involved!
