### ISSUE TITLE
Plugin management

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2544]
* KOReader version: Up to 4f1cabc
* Device: independent

#### Issue

Since we are adding plugins, we may need a feature to let users hide unwanted plugins to reduce the length of plugin menu. Hidden plugins can still be retrieved in 'Other plugins' menu item.

**Comment by houqp** [comment]
What's even better is a full-fledged plugin manager that can:

1. disable plugins
2. update plugins
3. install new plugins

**Comment by retrue** [comment]
I like houqp suggestion about the plugin manager. 
About hiding entries in the menu, I dedicated some thinking to that problem a few weeks ago, but my idea wass more ambitious. Too ambitious in fact because a new UI will be implemented in the future.
My idea was to make use of the Show advaced options feature and going much further.
You would have three modes:
- A simple mode, where only the more basic menu entries were shown.
- An advanced mode, where everything is shown (like it is now).
- A personalised mode, where the user would use as start point the advanced mode and where the user could remove menu entries, moved them from a submenu to the upper menu and maybe creating a generic submenu called "Others" where moving other menu entries that he intended to use less but didn't want to have removed from his personalised mode. Of course, the user could not move menu entries from let's say pokeball to gear or tools or vice versa, but he could have control about all the options inside gear, tools, pokeball, etc.
For example, in my personalised mode I would remove all the Language menu entries except Spanish, French and English. In hyphenation I would leave only "none", both English, Spanish and French. In gear menu I would remove Save document, move Wi-Fi connection to the upper menu and remove Network, etc.
But implementing this idea would be a lot of work, and I know nothing about programation...   ^^; so I cannot implement it myself.

**Comment by Frenzie** [comment]
> Of course, the user could not move menu entries from let's say pokeball to gear or tools or vice versa, but he could have control about all the options inside gear, tools, pokeball, etc.

I don't think there's an of course there. In good old Opera/Presto I had a completely customized [menu.ini](https://github.com/koreader/koreader/files/784960/menu.ini.zip). The way it worked was that you added the sections you wanted to change and the rest simply stuck to the default. The attached file is a somewhat excessive example of a complete GUI overhaul.

In Opera's spiritual successor [Otter Browser](http://otter-browser.org/) (disclaimer: I'm involved) afaik currently only the context menus can be customized (cf. https://github.com/OtterBrowser/otter-browser/commit/0b51c92c39af7977a652b7880e0935e794c5b449).

Anyway, to implement the menu following principles much like Otter's or Opera's would be a sensible approach that could also very easily allow for minimal or complete user menu customization.

> In gear menu I would remove Save document, move Wi-Fi connection to the upper menu and remove Network, etc.

Also see  #1590. The defaults are currently suboptimal or at the very least not always the result of deliberate decisions due to some technical constraints.

**Comment by retrue** [comment]
Should I open a feature request?

**Comment by Hzj-jie** [comment]
Oh, this conversation goes too far :)
It's ideal to have a menu reordering feature. But I think we can open another feature request to track the issue.
Going back to the plugin management itself, I agree to @HouQP, a full-featured plugin management should have these functionalities. But as long as we do not have a plugin repository, it's not really reasonable to have installation / update features. For installation, users always need to copy the plugin files to the device. For update, where should we update from? But I think we can simplify the installation from copying a folder to copying a zip file.

So I think we can separate the feature into four,
1. Disable / enable plugins, or in another word, preferred / seldom used plugins. This looks like a simple feature we can achieve soon.
2. Allow a plugin to be packed into a zip file, instead of a folder.
3. Move plugins into a standalone github repository. This is questionable. The advantage is we can release a full package with all plugins, or a common package with most-used plugins for regular users, and a minimum package without plugins for advanced users.
4. Plugin repository. A user can download / install / update plugins online. This is do a fancy feature, but I doubt whether it's worthy. We do not have too many plugins now or in a foreseeable future.

**Comment by rduplain** [comment]
A solution worth mentioning in the meantime, before this feature is available:

> Disable / enable plugins, or in another word, preferred / seldom used plugins. This looks like a simple feature we can achieve soon.

You can simply remove each unused plugin's .koplugin directory from KOReader's `plugins` directory. I confirmed that this works, using the simulator. (Any reason why you wouldn't want to do this?) For example, I removed these plugin directories since I would not be configuring them:

* calibrecompanion.koplugin
* evernote.koplugin
* kosync.koplugin
* newsdownloader.koplugin
* zsync.koplugin

You could just remove (or move to a temporary location) the .koplugin directory from the device after install.

**Comment by Frenzie** [comment]
@rduplain 

> Any reason why you wouldn't want to do this?

Generally none, other than that an OTA update will recreate them.

Incidentally, I implemented custom menu ordering shortly thereafter. See https://github.com/koreader/koreader/issues/2898#issuecomment-301587960 and #3164

**Comment by poire-z** [comment]
Disabling some plugins with a manually added setting is now possible with #4054.

**Comment by robert00s** [comment]
Done in #4159 and #4054.
We don't need update and install plugins because after every KO update we get all plugins folder that has less than 700k.
