### ISSUE TITLE
reorganize touch menu items

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2562]
Sub ticket created for general UX discussion from23 https://github.com/koreader/koreader/issues/2555.

@pazos created proposed a solution to replace the home tab with misc items:

![test2](https://cloud.githubusercontent.com/assets/975883/23150022/6817060e-f7f0-11e6-8544-640455a39b73.png)

I think this is a good step forward and will be happy to accept the change. We need to change the home icon with a new one so people won't get confused and set the wrong expectation if they are already used to the current behavior.

We will probably need better icons for all other tabs too so suggestions welcome.

**Comment by retrue** [comment]
To replace Home icon I had thought of a door with an arrow. Doing a search on Google Image I have found several ones that I like. Dunno if they are free but something similar could be drawn.
![mobile_interface-01-512](https://cloud.githubusercontent.com/assets/18194241/23205806/7f675326-f8eb-11e6-9bc1-b4e2cd7162f3.png)
![door-exit-with-arrow-to-the-right_318-40597](https://cloud.githubusercontent.com/assets/18194241/23205809/814a52ce-f8eb-11e6-90d1-c94ac4d75957.jpg)
![24-512](https://cloud.githubusercontent.com/assets/18194241/23205814/848658b6-f8eb-11e6-9211-641377780ea1.png)

**Comment by Frenzie** [comment]
Other than pokeball, I don't think the icons are problematic.

* Gear = settings
* Pokeball = wtf?
* Tools = tools
* Magnifying glass = search
* Home = home. Should be positioned on the furthest possible right and an off icon of some sort would be clearer because it could be misinterpreted as "KOReader home" as opposed to "OS home". I think putting Exit right underneath Help isn't exactly the most useful. Without an in-depth rewrite I suppose we could stick an extra line in if that's what we wanted to do?

Overall I'd be more interested in adding icons to individual menu entries for quicker visual identification. https://github.com/Templarian has plenty others available. Clock for history, question mark or lifebuoy for help, etc.

@retrue Icons that fit in directly with the current bunch can be found here: https://github.com/Templarian/WindowsIcons/tree/master/WindowsPhone/light

![appbar door leave](https://cloud.githubusercontent.com/assets/202757/23205944/20355de8-f8ec-11e6-9e5f-b519e2686830.png)

That guy's a decent source of icons regardless, cf. https://cdn.materialdesignicons.com/light/0.2.63/ (and his blog: http://templarian.com/)

**Comment by pazos** [comment]
pokedex icon should be replaced (or deleted) . Right now it has the following items:

on filemanager app: history, open last document, ota update, version and help
on reader app: history, ota update, version and help

help isn't useful at all. Just displays "please report bugs to github.com/koreader".  It would be awesome to have some kind of koreader manual on epub, not listed on the filemanager but accesible from the help button.

I think that both OTA update and version are more related to exit (and maybe reboot, poweroff..) than to history or last document.

**Comment by Frenzie** [comment]
True, so maybe replace pokeball with clock or some such to indicate history. I can't find an appropriate history icon atm so I'll just drop this one (appbar.timer.rewind) 'cause I have to leave right now.

![appbar timer rewind](https://cloud.githubusercontent.com/assets/202757/23213406/0f5ac412-f90b-11e6-9c5a-6da864183fc8.png)



There's also this leaving home icon:
![appbar home variant leave](https://cloud.githubusercontent.com/assets/202757/23213335/e0085cb0-f90a-11e6-9fdf-a08fd9cd0b68.png)

But if it's a traditional help menu I'm not sure if something like that is appropriate. Maybe stick with home after all?

**Comment by KenMaltby** [comment]
The original suggestion seems a lot like "About" and could include the reference to the WiKi (like the current help references "Issues".  

As I remember it, the Home icon originally brought you back to the File Manager,  and to the folder that was "Set as HOME directory", so the logic was sound.  Perhaps the Home icon could offer a menu with "Go to Home directory" as its first option.  Then an "Exit" icon like one of these: https://duckduckgo.com/?q=exit+icon+png&t=h_&ia=images&iax=1&iai=http%3A%2F%2Ficons.iconarchive.com%2Ficons%2Foxygen-icons.org%2Foxygen%2F256%2FActions-application-exit-icon.png The current "File list" icon could be removed.  

The Help option launching an .epub manual (or converted WiKi, perhaps) is a great idea.  Maybe with a "Quick Start" section that could be offered in a popup message box (with an option to: "View Quick Start"), to new users.  It would include a check box to have it not appear on future start ups.

**Comment by Frenzie** [comment]
Note that #1371 is about bundling the wiki, although I'm not entirely sure if it's currently sufficiently structured for that. It could be worse though.

**Comment by pazos** [comment]
Quick preview of @Frenzie suggested history icon in koreader (with the changes in home menu). The icon hasn't the same size of the others, but you'll get the idea.

On the file manager:
![file manager 1](https://cloud.githubusercontent.com/assets/975883/23271166/d869c9e8-f9f6-11e6-9caf-e724cdb0ed95.png)
![file manager 2](https://cloud.githubusercontent.com/assets/975883/23271170/dc8d1a7a-f9f6-11e6-877e-4d00ea3ac39d.png)

On the reader:
![reader 1](https://cloud.githubusercontent.com/assets/975883/23271178/e2da9362-f9f6-11e6-9cc5-1462f25a7552.png)
![reader2](https://cloud.githubusercontent.com/assets/975883/23271180/e55d5f48-f9f6-11e6-8fba-fff8b0b06bd3.png)

Al alternative order in top menus:
![reader-alt](https://cloud.githubusercontent.com/assets/975883/23271357/803658da-f9f7-11e6-8aba-4d2c1049649b.png)

Opinions?

**Comment by Frenzie** [comment]
I like it except that it's a timer rather than a clock. Unfortunately the license of the current icons is no derived works, so I can't do something obvious like combining appbar.clock with the rewind arrow.

PS This is appbar.clock:
![appbar clock](https://cloud.githubusercontent.com/assets/202757/23272261/d5367128-f9fa-11e6-92c8-72215a9dfd9d.png)

**Comment by pazos** [comment]
Another preview, with an icon from wikimedia.

![preview](https://cloud.githubusercontent.com/assets/975883/23273217/729868a6-f9fe-11e6-8f70-8b5d0549a5a3.png)

**Comment by pazos** [comment]
Also, in the code, pokedex menu is called the "info" menu. So "Book status" makes sense in this menu, but not on history menu

**Comment by Frenzie** [comment]
Right, in that case I'd move book status over to the bookmark menu. Anyway, it's just a thought as several people have requested direct access to history.

For info there's appbar.information.circle and appbar.information.
![appbar information circle](https://cloud.githubusercontent.com/assets/202757/23274228/2af609a0-fa02-11e6-9338-204850681c60.png) ![appbar information](https://cloud.githubusercontent.com/assets/202757/23274229/2af9b73a-fa02-11e6-838e-26713a8aca76.png)

That icon from Wikipedia isn't bad although I'd make some adjustments. What's the source?

**Comment by pazos** [comment]
Is part of google's material icons.
https://commons.wikimedia.org/wiki/File:Ic_history_48px.svg

**Comment by Frenzie** [comment]
See, I like that pointy end in the other icon, here's a quick edit. :-P

[Ic_history_48px.svg.zip](https://github.com/koreader/koreader/files/797482/Ic_history_48px.svg.zip)

![ic_history_48px svg](https://cloud.githubusercontent.com/assets/202757/23275217/fcc6cc8c-fa05-11e6-8891-62a0a13a89e8.png)

**Comment by houqp** [comment]
OK, so looks like the concensus here is to repurpose home tab as "system tab" which includes the following items:
* help
* version (about)
* update
* exit

In this case, a home icon is not an accurate representation of the functionalities.

Allocating one tab for time related features seems like a waste because I can't think of other related things that can be put into there. Perhaps we can create a generic "action/feature" tab?

**Comment by Frenzie** [comment]
Speaking only for myself, pokeball → history is by far what I do the most so I'm sympathetic to the various requests for basically a dedicated button. But the icon discussion is largely separate and should probably be a different issue.

My proposal would be to kill the pokeball, move book status over to either page corner bookmark or tools, and stick the rest of pokeball under the "file" menu.

![appbar page corner bookmark](https://cloud.githubusercontent.com/assets/202757/23306659/c277a3ea-faa4-11e6-8570-725490faef1b.png)
* Table of contents
* Bookmarks
* Go to
* Skim to
* Follow Links
* **Book status**

![appbar pokeball](https://cloud.githubusercontent.com/assets/202757/23306699/eb3123b0-faa4-11e6-8a06-1641251f5a9f.png)
* <del>Gone</del>

appbar.lines.horizontal (hm, isn't the hamburger menu supposed to be only 3? :-P)
![appbar lines horizontal 4](https://cloud.githubusercontent.com/assets/202757/23306625/a4fc69cc-faa4-11e6-852e-083257a13b4b.png)
* History
* Open last document
* Update
* Help
* Version
* Exit

> Allocating one tab for time related features seems like a waste because I can't think of other related things that can be put into there. Perhaps we can introduce a generic "action/feature" tab?

Not necessarily a bad idea, but how do you distinguish between "tools" and "generic action/feature"? Even without adding icons to the mix the distinction is unclear to me.

One thing that could be done is to separate out finding-related tools. Dictionary, Wikipedia, Fulltext search, Goodreads. This could declutter the tools menu.

**Comment by pazos** [comment]
@Frenzie: book status makes sense in bookmarks, all those items are related to the book itself.

I miss a "file manager menu". One that include the items in the search tab and both history and open last document, and maybe some options just for the file browser (show hidden files, sorting..)".

I also feel that the settings tab should display the same items on both file browser and reader app, like network, screen, language, night mode....

**Comment by pazos** [comment]
also, replace pokedex on reader app with a search tab with: search in dictionary, search in wikipedia and search full text

**Comment by Frenzie** [comment]
@pazos 

> book status makes sense in bookmarks, all those items are related to the book itself.

Maybe, maybe not. They're all navigational and in that sense it'd make more sense in the hamburger menu on the right. The problem in a sense is that status kind of mixes "book info/properties" and "book status" together. As a fun exercise, here's the "book information" (from the file manager) implemented as a reader menu item:

```lua
table.insert(self.tab_item_table.info, {

					text = _("Book information"),

					callback = function()
						local FileManager = require("apps/filemanager/filemanager")
						local KeyValuePage = require("ui/widget/keyvaluepage")
						local book_info_metadata = FileManager:bookInformation(self.ui.document.file)
						DEBUG(book_info_metadata)
						if  book_info_metadata then
							UIManager:show(KeyValuePage:new{
								title = _("Book information"),
								kv_pairs = book_info_metadata,
							})
						else
							UIManager:show(InfoMessage:new{
								text = _("Cannot fetch information for a selected book"),
							})
						end
						UIManager:close(self.file_dialog)
					end,
})
```

> I also feel that the settings tab should display the same items on both file browser and reader app, like network, screen, language, night mode....

But it does? Those are the common settings.

> also, replace pokedex on reader app with a search tab with: search in dictionary, search in wikipedia and search full text

Yup, already proposed it above! Probably insufficiently clear. ;-) 

I'll reorganize the menus today and stick it in a PR with screenshots.

**Comment by Frenzie** [comment]
@Hzj-jie @pazos Taking this out of #2572

> It doesn't need to be the "search" tab, but a more generic file "explorer" tag. AFAIK both options are avaliable only from the file manager app, but not from the reader app.

With the caveat that I don't think different modes should necessarily have the same hamburger menu considering they're different modes, I agree with the wish to unify the modes as much as possible. I'd like to do so by adding rather than substracting, namely by adding (folder) properties to the filemanager and adding open last document to the reader. However, I really do think that recent files/history and properties/info[1] make sense in hamburger. In many file managers there's "properties" much like in document viewers and editors. 

To illustrate, here are a couple of screenshots from Thunar as it happens to be my file manager of choice.

Folder properties, probably most commonly accessed by right-clicking on a folder but in this case by File → Properties.
![screenshot_2017-02-28_08-15-01](https://cloud.githubusercontent.com/assets/202757/23395283/12e3c430-fd8e-11e6-9279-a25c19c683c1.png)

File properties, accessed in this case by right clicking in the very same file manager but in an audio player something similar might be opened through File → Properties.
![screenshot_2017-02-28_08-15-17](https://cloud.githubusercontent.com/assets/202757/23395284/13001518-fd8e-11e6-89e0-0d16e933c2d3.png)

[1] NB This actually isn't quite the same as *book status*, but aligns better with the separate *book information* dialog.

**Comment by Frenzie** [comment]
Okay, with #2601 finished any further reorganization of the menus (including, e.g., #2648) has ceased to be a laborious process. The default menu configuration can be found in:

* [frontend/ui/elements/filemanager_menu_order.lua](https://github.com/koreader/koreader/blob/0318a048b40f236cd45d47bf5a321c473e4d87a1/frontend/ui/elements/filemanager_menu_order.lua)
* [frontend/ui/elements/reader_menu_order.lua](https://github.com/koreader/koreader/blob/0318a048b40f236cd45d47bf5a321c473e4d87a1/frontend/ui/elements/reader_menu_order.lua)

It can be overwritten on a per-user basis by creating files named `filemanager_menu_order.lua` and `reader_menu_order.lua` in `settings/`. You only need to copy the (sub)menu you want to customize.

**Comment by retrue** [comment]
@Frenzie Could you copy the default filemanager_menu_order.lua and reader_menu_order.lua in the wiki?
Adding to some explanation would be even better.
It seems that the options to choose personalised menu and go back to standard menu have not been added yet.

**Comment by AlanSP1** [comment]
Yes, I think this should be documented, if it isn't already in wiki and any other documentation there is or will be.

**Comment by Frenzie** [comment]
> It seems that the options to choose personalised menu and go back to standard menu have not been added yet.

Right, this issue is unrelated to #2564 except in the sense that easily allowing user customization is a natural result of making menu configuration sensible. This is about where to place menu items, separators, etc. which was previously only partially possible.

**Comment by Frenzie** [comment]
Copying [this](https://github.com/koreader/koreader/pull/2693#discussion_r108881433) where it belongs so it won't get lost.

Typeset menu should be something along these lines:
```lua
        -- rendering stuff
        "page_overlap",
        "switch_zoom_mode",
        "set_render_style",
        --sep, I don't think highlight options go with anything else really
        "highlight_options",
        --sep, font-related (typeset) stuff
        "change_font",
        "floating_punctuation",
        "hyphenation",
        --sep, "reading experience" stuff
        "read_timer"
        --speed reading?
```

* Move GoodReads over to find menu.
* Group all of the statistics together with proper separator placement.
* Rename "Statistics" to "Reading statistics" because we now also have Battery & Storage Statistics

* Advanced settings & Developer options… tools or hamburger?

**Comment by Frenzie** [comment]
I'll close this because all of the big stuff is done.
