### ISSUE TITLE
improve install instructions for kobo

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#2575]
to include kfmon, and point KSM8 Instead of KSM7. 

Fmon instructions are too complicated. It isn't fair.

I use fmon in my devices, with 0 failures. In fact, fmon does NOT trigger any action during re-indexing after a logout from kobo account. So I'm very happy with it, but seems a pain in the ass to install it for the first time (need to flash 2 koboroot.tgz - one for fmon itself and the other for the koreader trigger). Also It can be reduced in complexity and improved with some checks.

I don't know If we can build fmon as part of koreader and make a proper KoboRoot.tgz file to install, for people who want to install the launcher just to run KOreader. The new install must be compatible with current implementations.

**Comment by houqp** [comment]
We can definitely include a koreader+fmon artifact in our build process. All of our builds scripts are managed in gitlab right now: https://gitlab.com/koreader/nightly-builds/blob/master/build_release.sh.

If you want to take a stab at it, I can give you access to the gitlab repo so you can add build instructions for koreader+fmon KoboRoot.tgz. Then I can update our nightswatcher script to upload the artifact to build.koreader.rocks/download.

**Comment by Frenzie** [comment]
> point KSM8 Instead of KSM7.

Could you be a bit more specific? Because this page points to KSM8: https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices

**Comment by pazos** [comment]
@Frenzie : Sorry, I didn't mean the wiki, but [this](https://github.com/koreader/koreader/tree/master/platform/kobo/fmon)

The wiki seems fine, but the proccess to install koreader with fmon is incomplete. The link to the fmon mobileread thread points to a file: fmon.zip, which includes the binary, but no ways to install it or handle it. The only way of installing fmon for new users, other than to build a custom KoboRoot.tgz, is install Kobo Launcher, and then follow KOreader instructions for Kobo.

@houqp: I was thinking about add a few lines in https://github.com/koreader/koreader/blob/master/Makefile#L184
but I din't know about the gitlab repo.

**Comment by houqp** [comment]
@pazos that works too, we can then invoke the make command in gitlab ci.

**Comment by houqp** [comment]
BTW, what happened to kfmon? I thought it's supposed to be a replacement for fmon?

**Comment by pazos** [comment]
@houqp: it is a replacement for fmon, but it requires a reboot to work. @NiLuJe add a way to back to nickel without reboot, but it doesn't work for me

The problem seems not related to kfmon, but to koreader.sh script. @NiLuJe also found that nickel could crash on suspend after switching between nickel & koreader a few times, so a reboot is consider safer.

Honestly, I think most battery issues on kobos happen because the switch, or for some kobo stuff in koreader (mainly the screensaver thing). I have a machine running just koreader and a few shell scripts, that worked over a year without problems. It has great uptime (It isn't home right now, but I'll check) and works as clean as after a reboot. Of course wifi crashes sometimes, but thats all.

About the screensaver thing, I tried it a few times but it had an strange behaviur with the sleep cover and some unexpected wake ups. Everything is OK with the sleeping message.

**Comment by houqp** [comment]
> The problem seems not related to kfmon, but to koreader.sh script. @NiLuJe also found that nickel could crash on suspend after switching between nickel & koreader a few times, so a reboot is consider safer.

Isn't fmon very similar to kfmon? How come fmon doesn't cause nickel to crash?

> I have a machine running just koreader and a few shell scripts, that worked over a year without problems. It has great uptime (It isn't home right now, but I'll check) and works as clean as after a reboot. Of course wifi crashes sometimes, but thats all.

Good to know! KOReader actually has couple suspend issues fixed in the last couple months and I am fixing the last known one in https://github.com/koreader/koreader/pull/2527. I have never run into wifi crashes before. Does it crash the whole reader? If you run into it in the future, please don't forget to file an issue with it ;)

> BTW, our nickel.sh file doesn't work with new mark6 hardware, which expects other nickel invocations. I can make a patch for this but I can't test myself. Devices with issues: kobo aura one, kobo aura 2nd, maybe touch2 or glohd?

Can you submit the patch in a PR? We can review and test it together.

**Comment by NiLuJe** [comment]
Still alive \o/.

Can't remember exactly what the issues w/ switching back & forth were, but I'm sure I put those down somewhere ;D.
Mostly related to nickel getting somehow borked when restarted (usually missing touchscreen, crazy suspend, some minor fb issues, potentially some spurious db issues).

It's been a while since I checked, but I *think* I got rid of most of those on my end. WHich ones wree you mostly encountering, @pazos?

One major issue that's fixed in the source but not in the builds is a stupid oversight rendering it useless when its config has been touched from an OS X system. But I just need to find some time to push an updated build for that ;).

**Comment by NiLuJe** [comment]
As for why fmon would behave differently from kfmon, the best I could come up with is because of how each of them are started.

Fmon needs to patch the system startup script, IIRC; while kfmon is started via udev. This means that they possibly end up with a slightly different env.
The final form of my attempt at fixing this discrepancy was siphoning the complete nickel environment when KOReader was started from kfmon. This has been part of KOReader's startup script for quite a while now, so I would hope that the initial wonkyness has been taken care of, but you never know... ;).

**Comment by pazos** [comment]
> Fmon needs to patch the system startup script
...
> One other thing I'm confused with is that we always try to kill fmon on startup, so I'm not so sure fmon actually handles all of this any better, since that would mean people would actually have to resort to a reboot at some point t get it back up and running, or am I missing something?

fmon modifies /etc/init.d/on-animator.sh, which is invoked by nickel.sh. It is the script that displays the boot animation every time we return koreader. So fmon is launched again. 

> It's been a while since I checked, but I think I got rid of most of those along the way (some of it involved adding some more craziness in KOReader's startup script, indeed). Which ones were you mostly encountering

yep, koreader.sh is a weird file. My problem seems related to those lines:
https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L48

I would expect that https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L55
works fine in kfmon. Anyways, all those export are again in nickel.sh

**Comment by NiLuJe** [comment]
Ah, right, thanks for the fmon clarification ;).

IIRC, killing the WiFi in our nickel.sh got rid of those stalls on my end.

Part of nickel's env seems to be pulled out of thin air by the nickel binary itself at runtime, so that siphoning appears necessary to attempt to more closely match it (vs. the *very* bare env we get from udev).

**Comment by pazos** [comment]
@houqp @NiLuJe @Frenzie 
Ok. About this issue, in short:

1. nickel.sh is broken in FW > 4. This doesn't happen on every device, just new mark6 hardware is affected. Look at https://github.com/gtalusan/kobo-nightmode/blob/master/installer/root/autorun.sh, to see the different ways of call nickel.

2. koreader.sh is broken in FW > 4. KSM8 works because it uses another script to run koreader. A workaround is in #2542, but we're waiting for #2502 to be fixed. 

3. Kobo instructions are not the problem. The platform is the problem :(. We need to fix 1 and 2. Until then those of us trying to run koreader without KSM need to hack the files ourselves.

Shorter again: in FW>4 running koreader from KSM works, running koreader from shell doesn't. a-w-e-s-o-m-e

I could fix 1 but need a couple of days to have time. :+1:

**Comment by pazos** [comment]
1. nickel.sh works fine on FW4.3 in mark6 hardware. I was wrong.
2. made a PR for this bug.

As for the instructions: maybe a mobileread thread under koreader forum is fine for most users and easy to implement by me (just need to update the KoboRoot.tgz file).

**Comment by KenMaltby** [comment]
I can make it a sticky.

**Comment by houqp** [comment]
Can we make all the instruction changes in our [wiki](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices) instead? We can then point to the wiki in the sticky thread in MR.

**Comment by pazos** [comment]
@houqp: yes, We can
@KenMaltby: that would be awesome, thanks

The simpliest installation is: "unzip contents of fmon-koreader.zip in the rootfs of your Kobo usb partition and unplug the device. The device will upgrade itself and reboot after that. After the reboot you must see a new tile in your home screen (or under your books). Then plug the device to the computer again and copy koreader folder under .adds, unplug and reboot again"

Sample content: [fmon-koreader.zip](https://github.com/koreader/koreader/files/905315/fmon-koreader.zip)
