### ISSUE TITLE
koreader doesn't work on Kobo H2O

### ISSUE THREAD

**Issue by fayebian** [koreader/koreader#2593]
* KOReader version: KBStartMenu
* Device: Kobo H2O

#### Issue

A month ago I got my Kobo H2O and managed to install Koreader on it, however, after I followed the system update by Kobo yesterday, the koreader start menu disappeared and only nickle was running. 

I tried to reinstall koreader start menu following the same steps I did last time, but found that after I connected the device to my Mac, the device folder is empty and I can't find the .kobo folder which is supposed to be where I put my KoboRoot.tgz into. I tried to just drag the kbmenupngs folder and the KoboRoot.tgz right into the root of the device, and then disconnect. It didn't work, the device started with nickel and the things I put into it turned into pictures (like dozens of arrows and icons...)

I have been googling for some solutions but got no answer, could someone please help me? 

Thank you so much!

**Comment by pazos** [comment]
Sorry, but you will need to find good file browser and forget about finder. Forklift2 is at price $0 in the mac app store. [mucommander](http://www.mucommander.com/) is free and works great.

Files starting with dots ".", like ".kobo" are hidden by default on unix like systems (osx, linux, bsds). Your brand new file browser has an option to show hidden files and thats it.

Please follow instructions from koreader wiki and remember that FW > 4 requires KSM (and a extra patch) to work, because the new framebuffer introduced 

In current installs of KSM you should use ".adds" instead of ".kobo" to install your software. (koreader, coolreader..), and ".kobo" just to upgrade the device with KoboRoot.tgz.

**Comment by fayebian** [comment]
Hi Pazos, I don't know how to quote you directly but I hope you can see my reply... thank you so much I can't believe it's as simple as that! Took me hours to search for solutions.

I am a complete newbie and without the detailed instructions and all the help I won't be able to get it to work properly, thank you for everyone contributing to koreader I love it!

**Comment by Frenzie** [comment]
You can quote by prefixing some text with `>`.

@pazos Are you saying [this](http://lifehacker.com/188892/show-hidden-files-in-finder) config setting no longer applies or that it's horribly annoying that you can't quickly toggle through the GUI?

**Comment by pazos** [comment]
@Frenzie it should work, but it's annoying. I could live with osx, but finder, what?.

**Comment by Frenzie** [comment]
@pazos I've never really used it much but I've seen proper Mac users do some pretty efficient stuff in quickly going through documents with the keyboard in what I assume was Finder.
