### ISSUE TITLE
Highlights in top of the page are not clickable

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2608]
* KOReader version: Up to f47d257
* Device: independent

#### Issue

The menu will be triggered instead.

**Comment by Frenzie** [comment]
Tough to say to what extent this is a bug. Triggering the menu is rather
important.

**Comment by houqp** [comment]
yeah, that's something we should clean up. Basically, single tap should not be used to trigger special actions like showing menus. Because any position in the document can respond to the tap event.

In the current implementation, menu tab is explicitly defined to have higher priority to highlight tap event because like @Frenzie said, it's a rather important action. It's possible to run into a state where all the top area are filled with highlights, which causes you not able to trigger the menu to exit the reader.

**Comment by AlanSP1** [comment]
This is something definitely related with tap zones, how they are set by default.

On my device I made tap zone for status bar much lower, so I can access text. Menu zone is maybe also a bit too high, "intruding" too much into text. It also could be easily sorted with custom definition of menu tap zone.

Maybe if default tap zones are much smaller? Or, they react to long press, in which case this should be explained to users.

**Comment by Frenzie** [comment]
I think regional slide could make sense.

**Comment by KenMaltby** [comment]
My new Galaxy S7 Active (I finally joined this era) uses a drop down menu that you flick down from the top of the screen.  If this is common practice on these new fangled mobile phones, it could be one answer.

If I ran into such a conflict, at the top or bottom of the page, it might be better if the menu call were ignored, as I could always just page forward or back to call a menu, after doing the highlight I wanted.

**Comment by Frenzie** [comment]
Right, that's what I meant. A slide from top to bottom in the menu activation area of the screen could activate the menu.

> If I ran into such a conflict, at the top or bottom of the page, it might be better if the menu call were ignored, as I could always just page forward or back to call a menu, after doing the highlight I wanted.

The whole page could be highlighted or otherwise clickable, but I suppose back and forward gesture always works. Which is why adding one for the menu, whether as primary or backup, does seem like it could be a good idea.

I've actually run into the opposite problem. On [this EPUB](http://www.gutenberg.org/ebooks/17489) I'm pretty sure it's impossible to activate the menu as opposed to clicking links at the top of the page on every first page of a chapter.

**Comment by retrue** [comment]
In #2410 I posted that sometimes it was very difficult to open the menu in some cases. I suggested a double tap as back-up gesture to open it.

**Comment by KenMaltby** [comment]
@retrue; The problem here is that the menu blocks the highlighting or clicking, maybe as a primary not a backup?

 @Frenzie ; I meant that if the highlighting or clicking had the priority, you could do the highlighting you needed then, if you needed to access the menu, you could go to a page where there was no conflict and then you could poke for the menu normally.

**Comment by retrue** [comment]
@KenMaltby I don't think it matters if it is as primary or as backup. What it matters is that there should be other way to access the menu.
The current gesture, tapping the upper zone of the screen, is the most obvious way to access the menu and it should be kept in any case.

**Comment by retrue** [comment]
But to remove that priority to the current gesture to call menu cannot be implemented until an alternative to call menu is implemented.

**Comment by houqp** [comment]
Here is a list of gestures that we can't use for special actions like invoking the menu:

1. single tap (used for page forward/backward)
2. hold (used for hightlight, dict lookup)
3. slide (used for scrolling)

Overwriting any of the above action for invoking menu will interfere with document manipulations. Two finger tab might be the best candidate there. The only issue with using two finger tap is not all devices support multi touch. Another option is double tab.

**Comment by AlanSP1** [comment]
Double tap as alternative way to invoke menu sounds good to me.

Of course, if we can go for single tap into menu tap zone. Which probably should be configured a bit lower by default.

**Comment by Frenzie** [comment]
@houqp 
> slide (used for scrolling)

I don't much see that as an issue. You could have half the current top-menu tap area on top and bottom for menu and status bar and then you'd still have this humongous space available for initiating scrolling. 

![screenshot_2017-03-05_14-34-01](https://cloud.githubusercontent.com/assets/202757/23587633/f9ae0bde-01b0-11e7-84c1-b050273c9898.png)

Something like that. If it works that way in Android, Sailfish OS and Ubuntu Phone I reckon it can't be all bad.

**Comment by KenMaltby** [comment]
Assuming that the "tap" and "Hold" gestures are still detected and functional in the swipe area, that should work.

**Comment by Frenzie** [comment]
You can already do all three so why not? 

I should probably clarify that the only thing important here is where you initiate the slide. So it's not like you'd have to do a mini-slide for the menu, or be really careful while scrolling.

**Comment by houqp** [comment]
That's a good point! Slide is not actually used for interacting with elements in the document, so we should be able to use it for different features by splitting the screen region.

**Comment by Frenzie** [comment]
This is actually looking almost ridiculously easy to implement. You just need to replace `ges = "tap"` with `ges = "swipe"` and implement a simple direction check.

```lua
function FileManagerMenu:onTapShowMenu(arg, ges)
    if ges.direction == "south" then
        self:onShowMenu()
        return true
    end
end
```

Of course a full implementation would also:

* Dismiss the menu when swiping up.
* Make sure documents aren't scrolled (even a little bit) when activating the menu/statusbar.

And of course there should be a quickstart document that says something like "swipe down on the top of the screen to activate the menu."

**Comment by houqp** [comment]
Yes, easy to implement. Need to ship a starter guide to help notify people of the changes though.

**Comment by poire-z** [comment]
Just read in #2724:
> This guide will explain that (soon) you will have to swipe south at the top of the screen to activate the menu

Really ? No more tap on top ? I'm not at all used to swiping (and my gloHD screen is less slippery than my phone screen, swipe from top is less easy than on the phone).

Can't we let Tap in along this new slide south ? With a low priority so that links and highlights catch that Tap first (and return false if no link or no highlight there) and let it propagate finally to the thing that shows the menu ?

**Comment by Frenzie** [comment]
Funny, I think it's much easier to swipe on my H2O than on glass screens, and it doesn't tend to leave horrible fingerprints to boot. Note that swipe doesn't mean some drawn-out gesture: the tiniest flick will do.

To the point, this issue in its various forms is actually the only thing about KOReader that actively annoys me. It includes sometimes triggering a link instead of the menu, and other times triggering the menu instead of a link or highlight. As long as single tap is overloaded you just can't win.

Like I indicated above, I think swipe makes by far the most sense because we're already used to it on Android, Sailfish OS, Ubuntu Phone, as well as Windows.

If you're curious to see what it feels like, you can try my swipe for menu branch: https://github.com/Frenzie/koreader/tree/slide_menu As far as I'm concerned it's working very well. :-)

**Comment by poire-z** [comment]
I understand the reasoning (although one can still hit a link when taping to go page forward or back, so should we remove go back/forward with tap and force swipe east and west ? :)), and i see the coherency with other platforms.
It's just that it will be (for me, and for some others) a new habbit to get, and an old one to forget.
Anyway, your patch is simple enough that I can revert it back if I really can't get used to it, so i'm fine with it :)

**Comment by houqp** [comment]
tap forward/backward is less of an issue in the sense that we already support swipe east/west to go forward/backward. So users can already workaround the link problem using swipes.

I still see the value of keeping tap forward/backward for now since it's easier to trigger than swipe and provides a better experience. We can also remove this binding if anyone complained about it in the future.

**Comment by chrox** [comment]
> Yes, easy to implement. Need to ship a starter guide to help notify people of the changes though.

No, it's not that easy. A quick start guide won't help for experienced users who are already familiar with the tap to show menu interaction manner. And what's more important is that swiping down gesture in Eink device is not as intuitive as in mobile phones which have responsive screens and smooth animations that give users realtime feedback of the swiping. And lacking of the feedback will make the swiping to show gesture much less user friendly.

**Comment by Frenzie** [comment]
Mobile phone touch lags behind like crazy. Just move up and down a bit to see. :-) More pertinent to the topic, I'm not quite sure how that criticism applies to swiping more than it does to interaction with most of these button-less E Ink devices in general. But since I'm swayed by the KOReader/other ereader argument I won't belabor the point.

Also, cross-ref with #2932.

**Comment by houqp** [comment]
Like @poire-z said, it's a new habbit to get, and an old one to forget for all the existing users including me. Took me couple days to get used to it. So I can totally understand why old users would not like this change. And now I find the swipe down works better than the old tapping design.

A lot of the frustration with swipe design I have seen so far boils down to two things:

* swipe gestures not recognized properly
* it also triggers screen scroll

All of these are bugs that we need to fix. Our gesture recognition code definitely needs tuning on each individual platform but it's not a easy thing to do given that developers have limited access to devices. For the extra scrolling annoyance, my previous patched fixed the issue for my kobo, but looks like it doesn't fix the issue for some other platforms. I was really annoyed when I first upgraded my device with the gesture change and noticed it scrolls the page every single time I bring up the menu.

I am probably also biased because swipes detection works really well on my kobo in general. I now also use swipes for page forward/backward because my hand can stay and operate in the same screen area without having to move around. It also avoids accidentally clicking on links which is very common on papers which have lots of references. My kobo actually has problem detecting tap gestures occasionally, but that's another bug that we need to fix :)

Personally, I think it's a good habit to use swipe whenever possible if it works well for your device. Otherwise you will always run into that surprise (and really annoying) moment when you want to invoke the menu but ended up jumping to a random location in the book. Then you might not even remember you can swipe down to bring up the menu since you rarely used. And if you do, now you need to bring up the menu and do couple more clicks to go back to the previous location. If you use swipe consistently, you won't have to worry about this issue forever.

**Comment by Frenzie** [comment]
> And now I find the swipe down works better than the old tapping design.

Much better. I initially made the change for testing largely out of curiosity (see https://github.com/koreader/koreader/issues/2608#issuecomment-291189675) and I was astounded by just how incredibly well it worked in practice.

> I now also use swipes for page forward/backward because my hand can stay and operate in the same screen area without having to move around.

I've been doing that for years. It's not only easier but also much more dependable. With tap you tend not to know whether you actually tapped or not precisely due to the lack of feedback, it can accidentally turn into a swipe, you can accidentally double-tap, etc. Swiping is much harder to mess up.

> It also avoids accidentally clicking on links which is very common on papers which have lots of references.

Yup, that happens all. the. time. Also in EPUBs. Since making this change I haven't cursed at KOReader once for doing something I didn't want it to do.

I support everything we outlined a few months ago and think that swiping should be the default, with tap disabled. But I also recognize that there are people who'd like to tap anyway. In the back of my mind I've been trying to figure out how to deal with that for close to two months now but I haven't come up with anything I like ("just add a setting" doesn't really sound much better than "just do both").
