### ISSUE TITLE
Power button does not work on Kindle Voyage without framework

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2663]
* KOReader version: 897
* Device: Kindle Voyage

#### Issue
Pressing power button cannot make the device sleep. But magnetic cover works well. 

#### Steps to reproduce
Start KOReader from kindle launcher with (no framework) opinion.
Press power button.

It looks like in the kindle input
https://github.com/koreader/koreader-base/blob/master/input/input-kindle.h
it does not detect the power button. I cannot quite tell if it's possible.

**Comment by houqp** [comment]
Can you run the `lipc-wait-event` command in a shell to see you are indeed getting the power button event? Maybe the action is renamed to something else.

**Comment by Hzj-jie** [comment]
I will have a try soon.

And I doubt whether we can receive the light sensor from it. (I am still looking for a way to "smartly" change front light intensity.)

**Comment by Hzj-jie** [comment]
Confirmed. We cannot receive any notification once framework has been stopped.

**Comment by Hzj-jie** [comment]
The power button event can be received from /dev/input/event0.

**Comment by NiLuJe** [comment]
Oh, joy. -_-".

**Comment by NiLuJe** [comment]
FWIW, also happens on my PW2 on FW 5.8.1.

I binned the 'no framework' as reserved to legacy devices in the docs.

**Comment by NiLuJe** [comment]
As mentioned earlier, that startup variant has been hidden on FW 5.x, closing ;).

**Comment by mireq** [comment]
Here is fix for PW2 - https://github.com/mireq/koreader/commit/154472f2a450cc73690a0becfb378302a04ab063
Now suspend works without framework. Koreader has now much more available RAM and is more stable.

**Comment by NiLuJe** [comment]
@mireq: Feel free to put that in a PR so we can discuss it further (and ideally, generalize it to other devices), as it looks rather sound ;).

**Comment by mireq** [comment]
@NiLuJe this is just proof of concept. Much better will be if powerd accepts power button like in case of started framework.

I have played with decompiler and fixed this issue. Here is my plugin, which fixes power button: https://github.com/mireq/KOReader-without-framework-support-for-Amazon-Kindle/blob/master/kindle_no_framework_helper.koplugin/main.lua

Now little explanation. First, why run Koreader without framework? Because cvm (framework) is extermly memory hungry. KOreader can crash after opening large PDF because cvm eats too much memory. Here is KOreader running under cvm:

![memory_1](https://user-images.githubusercontent.com/33599/168482959-30b0a50c-e1ea-4c87-8c05-f60288819e0f.png)

And KOreader without framework
![memory_2](https://user-images.githubusercontent.com/33599/168482985-dbca59a2-db3a-49f2-8c9a-752df39151ef.png)

And video
[![Kterm](https://img.youtube.com/vi/GHr8WD_MjzE/hqdefault.jpg)](http://www.youtube.com/watch?v=GHr8WD_MjzE "Kterm")

Now few comments to code:

After pressing power button powerd checks libelektra properties ``system/daemon/powerd/KAF_NAME`` and ``system/daemon/powerd/KAF_FRAMEWORK_STARTED``
This will return ``com.lab126.kaf`` and ``frameworkStarted``
To mock KAF, property ``frameworkStarted`` under service ``com.lab126.kaf`` should be created

If KOReader runs under framework, then registering service ``com.lab126.kaf`` will fail and handle will be nil (all other calls are ignored).

Second thing, which is checked in powerd is ``system/daemon/powerd/BLANKET_NAME`` and ``system/daemon/powerd/BLANKET_LOAD`` which resolves to ``com.lab126.blanket load``. If property ``load`` contains ``'splash'``, power button is ignored. Solution is unload call with ``splash`` argument. Last thing is disabling builtin screensaver.
