### ISSUE TITLE
Maximum Font Size Limitation?

### ISSUE THREAD

**Issue by WinterL** [koreader/koreader#2686]
* KOReader version: v2015.11-894-gd168db9
* Device: Kobo Glo HD, Android

#### Issue
Maximum Font Size Limitation

Does the koreader have a maximum font size limitation? 
I can not increase font size over 44pt, any suggestion?

If this is a default limitation, any configuration can modify it?
Even 44pt is too small for me.
I tried to modify DPI, only UI font size be modified, the epub font size no changed.

Please give me some help, thanks!

**Comment by a-kohout** [comment]
I can reproduce this on my Kobo Glo HD.
KOReader version: v2015.11-930-g0318a04
The font stops getting bigger after size 44. The GUI however keeps telling "Font size set to XX"

**Comment by Frenzie** [comment]
Huh, interesting. On the emulator at the default size the font size keeps increasing all the way up to 72. But if I run it at, e.g., `./kodev run -w=1500 -h=1600` then the default font size is already much larger and it doesn't get any bigger from 31 at what is in pixels the same size.

https://github.com/koreader/koreader/blob/8b7e18a7d7d0e9422d0da31da0df4f157b383ae8/frontend/apps/reader/modules/readerfont.lua#L143-L156

The 72 thing must be crengine related, because removing that line only makes the counter go up further without actually increasing past 72. The fact that control isn't smooth and maxes out earlier than the indicator would have you believe could be related to the Screen:scaleBySize line.

In crengine I could find this fairly irrelevant bit of code but it does corroborate the max of 72:
https://github.com/koreader/crengine/blob/a09aac18672f5f9c57d87457afbac205001ed793/android/src/org/coolreader/crengine/OptionsDialog.java#L45-L48

I'm guessing an actually relevant file might be https://github.com/koreader/crengine/blob/a09aac18672f5f9c57d87457afbac205001ed793/crengine/src/lvdocview.cpp 

@frankyifei You've actually looked more closely at the crengine code, any ideas?

**Comment by Frenzie** [comment]
Oh, I found it!

https://github.com/koreader/crengine/blob/a09aac18672f5f9c57d87457afbac205001ed793/crengine/src/lvrend.cpp#L905-L906

I probably won't have time to try compiling this tonight, but I reckon that increasing that value to something more sensible (144? actually why not more?) should do the trick.

**Comment by WinterL** [comment]
Thanks for confirmation!
KOReader is very important reading APP for me since Kobo usually froze on reading large epub file.

**Comment by Frenzie** [comment]
Some playing around shows that certain assumptions are present in more places than one. Halfway to getting annoyed I realized there's an upstream of sorts and it turns out this issue has already been fixed there: https://sourceforge.net/p/crengine/crengine/ci/8c734fcb859859a79755511fbe1af5b7572298d0/~

I guess our branches have diverged too much (bleurgh) but it should be easy enough to adapt. It also feels a bit like it'd be a waste of time though. :-(

**Comment by houqp** [comment]
that particular patch should be easy to backport

**Comment by Frenzie** [comment]
Sure, it's tiny, but the whole diversion is just annoying. :-)

**Comment by houqp** [comment]
Yes, I spent like 2 hours trying to merge with upstream a year ago and gave up at the end :(

**Comment by rudism** [comment]
This problem also exists for me on the Android nightly v2015.11-1054-g6870bc2 (as well as previous versions). My Nexus 6P stops visually increasing the font size beyond 30 (despite the message popping up to tell me the font size has increased). I don't notice the same problem on my Nexus 7 2013, but the 6P has a much higher DPI/resolution (1440x2560). Happens with both built-in fonts and when I use my own TTF files in the `fonts` directory.
