### ISSUE TITLE
Nightly downloads: wrong file extension

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2694]
Some of the archives provided in http://build.koreader.rocks/download/nightly/ have the extension `.targz`: this should be `.tar.gz` or `.tgz`.

**Comment by Frenzie** [comment]
It's on purpose, see #1644

> The .targz file is only an intermediate reference file in the OTA server, zsync use it to incrementally update a local .tar file so users never see this strange .targz, so it should be OK.

However, I see that @houqp added the nightly URL to the wiki (imo for good reason as updating GitHub is a manual process)
https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices/_compare/433cec176df7437dd45a6f60bf0ed419ee9c0ac4...1a1feac895e13eb63f055fee022c7528efe6a89c

@houqp How about a simple symlink on the filesystem end? A .tar.gz for users and a .targz for zsync that would preferably be hidden from view in the server?

If we switched to/enabled [Fancy Index](https://www.nginx.com/resources/wiki/modules/fancy_index/) we could make it look a little better and use the `fancyindex_ignore` directive.

**Comment by Frenzie** [comment]
Closing since .targz files are for internal use only, and no longer present in the regular nightly download directory since https://github.com/koreader/koreader-misc/pull/27

![screenshot_2019-02-21_17-05-06](https://user-images.githubusercontent.com/202757/53183040-e87b4680-35fa-11e9-970b-217e4c245b14.png)
