### ISSUE TITLE
History menu item jumps around when switching between the file browser and an open book

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#2749]
Book status menu item is in the wrong place. In my opinion it belongs under the leftmost button as either the top or bottom item.

The way it is now, under the rightmost menu along with general history, it is out of place because it is found there only when a book is open, but it is gone from the menu when the file browser is open. When the file browser is open, History becomes the topmost menu item. It's confusing when History item moves like this. 

I'd like menu items to have their proper places so they don't move.

**Comment by Frenzie** [comment]
But history is always the top menu item?

![screenshot_2017-04-10_15-27-11](https://cloud.githubusercontent.com/assets/202757/24863686/347a6bf0-1e02-11e7-8b73-aafe82a4a6bb.png)
![screenshot_2017-04-10_15-27-19](https://cloud.githubusercontent.com/assets/202757/24863687/3499b6cc-1e02-11e7-81bb-f0328b70f137.png)

**Comment by ersi-dnd** [comment]
Well, good for you that yours looks like that. My version doesn't.

On both Android and Pocketbook, when a book is open, then in the rightmost menu Book status is on top, History second. When the file browser is open, History is on top and Open last document is second.

Android version v2015.11-894-gd168db9

Pocketbook version number exactly the same.

**Comment by Frenzie** [comment]
d168db9 is from early February. I've since implemented a menu sorting system (that was previously only possible in a very limited fashion) and have also done some initial menu reorganization (including separators, new separator display thanks to @baskerville). I'm closing this in favor of #2562 which is nearing completion.

Android builds are utterly ridiculous (i.e., random failures) and the whole thing is alpha quality but there's a more recent build that succeeded last week: http://build.koreader.rocks/download/nightly/v2015.11-935-g1b700c0/koreader-android-arm-linux-androideabi-v2015.11-935-g1b700c0.apk
