### ISSUE TITLE
Screen unresponsive after wake-up

### ISSUE THREAD

**Issue by wvhulle** [koreader/koreader#2793]
* KOReader version: koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-994-ga1ec64b.
* Device: Kobo Aura One

#### Issue

After opening the cover I need to press ~10 times until the screen responds to presses.

#### Steps to reproduce

- open pdf in Koreader 
- close cover
- walk around for an hour
- open cover

**Comment by houqp** [comment]
@wvhulle this only happens when you let the device idle for a long time? Could you send us the crash.log in your koreader folder for more info?

**Comment by wvhulle** [comment]
in the past weeks it didn't happen anymore, but it happens more often that the KOreader process just died.
[crash.log.txt](https://github.com/koreader/koreader/files/968238/crash.log.txt)

**Comment by Frenzie** [comment]
@wvhulle Have you noticed any changes?

**Comment by altacus** [comment]
I would also like to confirm this bug on a Kobo Auro H2O (first gen) w/nightly build 20180110. When putting the kobo into power save (quick power button press) and then waking it up (another quick power button press) the screen is unresponsive to page turns, the menu seems to come up. 

I've reverted to the stable version and this problem is not there.

**Comment by NiLuJe** [comment]
Should be fixed since #3895
