### ISSUE TITLE
FR: illustrative graphic for swipe down menu

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2815]
I cant click on the top to bring the top bar, it seems like the top bar is gone.
This is the troubled version.
http://build.koreader.rocks/download/nightly/v2015.11-995-gd6c81f5/koreader-android-arm-linux-androideabi-v2015.11-995-gd6c81f5.apk

I also tested the one from April 15 and that one functions properly.

**Comment by Frenzie** [comment]
The menu was changed to activate by swipe to allow for tapping links and highlights in the top part of the document. Also see #2786.

Adding an instruction graphic similar to the kobo light controller is on my roadmap, but I may not get around to it for another month.

**Comment by gerroon** [comment]
I am notr sure if I understand how the new system work but if it is a swipe down it might not work so well with eink Android devices.

**Comment by mwoz123** [comment]
@gerroon +1

**Comment by KenMaltby** [comment]
@gerroon ; so does a swipe down from the top of the screen, on your eink Android device, bring out the menu?

**Comment by mwoz123** [comment]
I think it should work as swipe back and forth works. 

But this is rather a problem of changing something that people were used to. 

Why we cannot have both tap or swipe for menu? 
Do you plan to introduce something else as top tap? 

Tap for menu was with koreader for ages (since beginning?), 
And tap for menu is rather a standard in eink software.  

I bet old koreader users won't even look at the new manual, 
and will report bugs that menu is not working. 

If I remember right kindle had (few pages) graphical info/manual where to tap to open menu, next page etc. 
Maybe more people will spot the change if they don't have to read the manual text?

**Comment by Frenzie** [comment]
I haven't quite figured out the way to graphically indicate this but here's some concept art.

![screenshot_2017-04-29_15-27-45-hand](https://cloud.githubusercontent.com/assets/202757/25555933/0f6069be-2cf3-11e7-85e7-9c770e2bcba6.png)

**Comment by mwoz123** [comment]
I suggest to replace top bar icons with word "menu" it will be easier for beginners. 

And I'd place it below the arrow(maybe with word "swipe"). 

I remember that kindle touch, when started for the first time had quick start Guide 
Which was something like pages 5 to 8 from below document : 
http://www.google.pl/url?sa=t&source=web&cd=3&ved=0ahUKEwjnxPCU7cnTAhVHRiYKHXv5BGsQFgghMAI&url=https%3A%2F%2Fkindle.s3.amazonaws.com%2FKindle_Touch_User_Guide_3rd_Edition_enUS.pdf&usg=AFQjCNHrBNpCdmlYX2SPUXJCn4ffGofmUw

Ps sorry for Google in link. I'm writing from phone

**Comment by Frenzie** [comment]
The model is the frontlight gesture controller, as I already wrote in https://github.com/koreader/koreader/issues/2815#issuecomment-297235702. That means there'd be some kind of info dialog in the middle of the screen to go along with the graphic. The above is the mockup I created for the graphic a few weeks ago, which should be text-free. That being said, with SVG support possibly coming (see https://github.com/koreader/koreader/issues/2668#issuecomment-298094366) I suppose it needn't be.

## Frontlight gesture controller

![screenshot_2017-04-29_16-37-11](https://cloud.githubusercontent.com/assets/202757/25556318/a2ed6ef0-2cfa-11e7-9026-fbac7ce52f20.png)

## First start

The way I envision first start is basically this:

1. Language selection.
2. Info graphic about menu (i.e., what you *really* need to know).
3. Quickstart guide.

Those are the main things I'd like to see implemented before the next stable release. I won't have time to do so myself for a few weeks at least.

**Comment by wvhulle** [comment]
For me, on Kobo Aura One, swiping from the top almost always triggers a pageturn unless I make a really long swipe. This behaviour is really inconvenient, a manual or tooltip won't help.  I understand that being able to interact with the top part of pages is important, but opening the menu should still be possible without a possible page turn. 

Either you increase the top margin and loose a lot space for content or you arrange some small _static region_ that does not conflict with hightlighting, links or reading and opens the top menu. Swiping is not a good solution because screen refreshes are to slow and so are easily confused with taps, especially by new users.

I think this would be a good solution: 

- Reserve two central areas (for top and bottom menus) for single tapping and show it to first time users (the Kobo way)
- ask for confirmation when tapping a link, always (as it is not so common to follow links)
- only highlighting is done by long pressing (does not conflict with any other functions)
- tapping the sides is a pageturn

**Comment by KenMaltby** [comment]
It works fine on my AuraHD.  I just slide my thumb/finger off the top bezel down about an inch, a quick flick really.  It is new, so this old dog, still occasionally finds myself tapping, and wondering where's the menu, but "life is change" I can adapt.

**Comment by gerroon** [comment]
I am having couple issues with this new system too. I tested this on normal android phone.

- Swiping down brings up the system tray or whatever it is called on Android which is very very annoying because when I try to get rid of the tray it also puts hides the top menu, I have to swipe up in a way.

- Most of the time swiping down also does some movement in the page. I use scrolling with pdfs and epubs. Again that is annoying too.

- I will try this on my eink adndroid device but it is a bit of pain to install it on my device because I do no symlinks to maintain the device space. I will try to report about it later.


I am very interested in reverting this behavior back. I do not mind if it is the default thing as long as I have a way to go back to tapping.

**Comment by z3t0** [comment]
> I am very interested in reverting this behavior back. I do not mind if it is the default thing as long as I have a way to go back to tapping.

Agreed, we should consider adding an option to toggle this behaviour.

**Comment by poire-z** [comment]
Choice between Tap and Swipe to activate menu is available since #3060.
