### ISSUE TITLE
Filesystem?

### ISSUE THREAD

**Issue by z3t0** [koreader/koreader#2852]
I am trying to track down where the file for `local lfs = require("libs/libkoreader-lfs")` is. Can't seem to find it...

**Comment by Frenzie** [comment]
lfs will be in koreader-base (different repo).

On May 3, 2017 06:50, "Rafi Khan" <notifications@github.com> wrote:

I am trying to track down where the file for local lfs =
require("libs/libkoreader-lfs") is. Can't seem to find it...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/koreader/koreader/issues/2852>, or mute the thread

**Comment by z3t0** [comment]
Got it thanks.
