### ISSUE TITLE
CSS: Hanging indents are shifted to the right

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2857]
* KOReader version: v2015.11-1024-g3b813c7
* Device: Emulator

#### Issue
Hanging indents seem to be miscalculated.
A p block with a hanging indent is shifted to the right by an equal amount.

Koreader:
![screen shot 2017-05-04 at 23 00 42](https://cloud.githubusercontent.com/assets/26367956/25724853/b76fe9ee-311d-11e7-80c5-952307415bdc.png)

Expected:
![screen shot 2017-05-04 at 23 00 48](https://cloud.githubusercontent.com/assets/26367956/25724857/bcd6c7d6-311d-11e7-801a-b15bc1723f3d.png)

CSS:
```
p {
  text-indent: 0;
  margin: 0;
}

p.hangingindent {
  text-indent: -1.5em;
  padding-left: 1.5em;
}
```

HTML:
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<p class="hangingindent">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
```

#### Steps to reproduce
[untitled.epub.zip](https://github.com/koreader/koreader/files/977559/untitled.epub.zip)

**Comment by Frenzie** [comment]
Phrasing it as "hanging indents" probably obstructs the real issue. It looks more like "negative values not supported" or something like that? Is that a global problem or text-indent only?

**Comment by a-kohout** [comment]
Negative text indent does work, but only as expected when inside a div with at least the same amount of (positive) margin, so its position won't have to be negative.
A negative x position outside the viewport seems to be unsupported and set to 0, before padding is applied.
So from a practical point of view, where hanging indents are applied to p tags, the title does make sense. Negative margins are a different story #2878.

Sigil:
![screen shot 2017-05-06 at 16 43 00](https://cloud.githubusercontent.com/assets/26367956/25829561/417f2866-3457-11e7-8d96-bf66f527edc2.png)

Koreader:
![screen shot 2017-05-06 at 16 44 52](https://cloud.githubusercontent.com/assets/26367956/25829563/4a4cce94-3457-11e7-9cf2-c8cfe50d2d9b.png)

**Steps to reproduce:**
[indents.epub.zip](https://github.com/koreader/koreader/files/985108/indents.epub.zip)

**Comment by Frenzie** [comment]
@poire-z The document in the OP seems to crash the current version of the program.

**Comment by poire-z** [comment]
untitled.epub does not crash for me.
Can you provide some gdb output?

**Comment by Frenzie** [comment]
It doesn't seem to be working out atm, but this is the error message:
```
./luajit: frontend/apps/reader/readerui.lua:710: attempt to yield across C-call boundary
```

**Comment by Frenzie** [comment]
The indents one does the same thing. Do you have any special settings enabled?

```

01/16/20-20:13:02 DEBUG Hyphenation: no algo set
01/16/20-20:13:02 DEBUG CreDocument: set hyphenation left hyphen min 2
01/16/20-20:13:02 DEBUG CreDocument: set hyphenation right hyphen min 2
01/16/20-20:13:02 DEBUG CreDocument: set hyphenation trust soft hyphens 0
01/16/20-20:13:02 DEBUG Hyphenation: keeping current crengine algo: English_US.pattern
01/16/20-20:13:02 DEBUG CreDocument: requesting DOM version: 20180528
01/16/20-20:13:02 DEBUG CreDocument: set visible page count 1
01/16/20-20:13:02 DEBUG CreDocument: loading document...
01/16/20-20:13:02 WARN  Cre error loading file: File with supported extension not fouind in archive.
01/16/20-20:13:02 DEBUG CreDocument: loading failed.
01/16/20-20:13:02 WARN  crengine failed recognizing or parsing this file: unsupported or invalid document
01/16/20-20:13:02 DEBUG ImageWidget: _render'ing resources/info-i.png
01/16/20-20:13:02 DEBUG renderImageData: using MuPDF
01/16/20-20:13:02 DEBUG Mupdf.renderImage true cdata<struct BlitBuffer8>: 0x40d451d0
01/16/20-20:13:02 DEBUG cache image|resources/info-i.png||
01/16/20-20:13:02 DEBUG show widget: table: 0x413f7d50
01/16/20-20:13:02 DEBUG setDirty nil from widget table: 0x413f7d50 w/ NO region 
01/16/20-20:13:02 DEBUG setDirty via a func from widget table: 0x413f7d50
./luajit: frontend/apps/reader/readerui.lua:710: attempt to yield across C-call boundary
```

Btw, typo `extension not fouind in archive`

**Comment by poire-z** [comment]
Are you loading the .zip ? (have your renamed it to .epub, instead of uncompressing it?)
So, it's not really a crash (ala segfault), just crengine reporting it can't read it - but you don't get the `Failed recognizing or parsing this file: unsupported or invalid document.\nKOReader will exit now` InfoMessage? I get it, and it's all messed up (InfoMessage can be moved, but screen not clean, and KOReader exits).
I get this in this case:
```
01/16/20-20:31:03 DEBUG CreDocument: set visible page count 1
01/16/20-20:31:03 DEBUG CreDocument: loading document...
01/16/20-20:31:03 WARN  Cre error loading file: File with supported extension not fouind in archive.
01/16/20-20:31:03 DEBUG CreDocument: loading failed.
01/16/20-20:31:03 WARN  crengine failed recognizing or parsing this file: unsupported or invalid document
01/16/20-20:31:03 DEBUG ImageWidget: _render'ing resources/info-i.png
```
I don't get "readerui.lua:710: attempt to yield across C-call boundary". Curious why you get it.
Doing something special with that InfoMessage ? :)

Anyway, exiting after opening such an unreadable file is an known sad fact::
https://github.com/koreader/koreader/blob/b111ccc2b803fc78425d9791fcc8bb7a9a704e6e/frontend/apps/reader/readerui.lua#L686-L714

**Comment by Frenzie** [comment]
Oh, you're right, they're EPUBs packed in zip files. That's very unintuitive. :-) But there's still the crash.

> So, it's not really a crash (ala segfault), just crengine reporting it can't read it - but you don't get the Failed recognizing or parsing this file: unsupported or invalid document.\nKOReader will exit now InfoMessage?

Nope.

Anyway, here are the current renderings.

<img src=https://user-images.githubusercontent.com/202757/72557529-3a772b80-38a1-11ea-97d1-cc17fbae0b3a.png width=45%><img src=https://user-images.githubusercontent.com/202757/72557528-39de9500-38a1-11ea-91ad-ea708f2ed770.png width=45%>

**Comment by poire-z** [comment]
I still don't get your `readerui.lua:710: attempt to yield across C-call boundary`. InfoMessage shown? One or two (I see "Failed..." over the "Opening ..." one)? Start with file browser or book? etc... :)

**Comment by Frenzie** [comment]
> Start with file browser or book? etc...

Ah, it only happens if you open the file directly, not if you go through the file browser.

**Comment by poire-z** [comment]
Via command line or Start with: last file?
I still don't get it with both :)
AppImage or emulator?

**Comment by Frenzie** [comment]
Doesn't matter as long as it's drag & drop, it looks like.

**Comment by poire-z** [comment]
What? You mean you get it **only** when you drag & drop? (I can't drag&drop).

**Comment by Frenzie** [comment]
Apparently so. It seems to work when opening it from the command line and the file browser.

**Comment by poire-z** [comment]
OK, good :)
So, may be there's a code path with drag&drop that call the showReader stuff without doing the coroutine stuff (needed to be able to ask for a password for PDF), and so, at this point, it is not in a coroutine.
```
~ $ lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> coroutine.yield();
attempt to yield across metamethod/C-call boundary
> print(coroutine.running())
nil
```
If it can't/shouldn't be coroutine-wrapped, we could just add in readerui.lua lines 686+ stuff line:
`if coroutine.running() then coroutine.yield() end`

**Comment by Frenzie** [comment]
I don't think I've ever seen a password-protected PDF in the wild. But sure, it's possible I added drag & drop as a proof of concept while forgetting about certain niceties, or perhaps those niceties were added or changed later. :-)

**Comment by poire-z** [comment]
Back to the original issue:
https://www.w3.org/TR/css-text-3/#text-indent-property mentions some additional keywords:
> - each-line: Indentation affects the first line of each block container and each line after a forced line break (but not lines after a soft wrap break). 
> - hanging: Inverts which lines are affected. 

Current crengine implementation parses negative values. But when the "hanging" keyword is there, it negates the parsed value. So, it may be that there has been no real support for negative values (for technical reason: the text shouldn't overflow its formatting area), and an internal negative value is just there to carry the "hanging" property.
So, `text-indent: 2em hanging` is considered the same as `text-indent: -2em`, but crengine might probably handle it as how `text-indent: 2em hanging` _should be handled_: all except the first line are indented by that amount.
"_should be handled_", because I can't compare :) [no browser supports that `hanging` keyword](https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent#Browser_compatibility), so I can't even check if `hanging` is supposed to work like this.

Also, it looks like crengine re-applies `text-indent` after a `<BR/>` (which I thought was what should happen), while it shouldn't (as the specs states). So, in effect, if behaves like if the `each-line` keyword was there (that is also not supported by any browser).
I guess this one should be fixed?

**Comment by Frenzie** [comment]
It's a pity they don't include Prince in those tables.

Yeah, it's probably better to fix it.
