### ISSUE TITLE
File manager: display books' thumbnails (and descriptions)?

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2906]
* KOReader version:
* Device: Kobo Glo HD

#### Issue
Would it be possible to display a thumbnails of each book's cover in the file manager, as well as the book's description? Don't know if it is possible as it's great that the file manger is responsive even if the library is huge... but this would be a great enhancement!

**Comment by KenMaltby** [comment]
Doing that for all the listed books would certainly effect the file manager's ability to be "responsive".  There is a long press option "Book information", you might add a thumbnail generation and display (for documents with cover images).  Not sure about a book description, there may be an online source for such a thing.

**Comment by Brnoch** [comment]
I understand the problem.
The way I use Koreader is maybe different from many users. I've chosen to put my whole library on my Kobo. I'd like to choose the next book I want to read the way I do it in a bookshop, looking at the cover and the description on the back. Right now, I need to do it in Calibre or in another book server COPS.

**Comment by oldhasbeen** [comment]
I have all my books and documents (large number) sorted in folders which are labelled into respective genres. I cannot have this with Nickel or many other devices. They all build a database containing all books with thumbnails of each of them. Many books mean a big data base with long access time and heaps of processing power needed. Large data storage capability is rather useless then (thousands of documents/books cannot be conveniently and effectively managed with such data based systems). We can observe that external storage is disappearing in new ereaders and I guess one reason therefore is the sluggish user experience resulting from the bottleneck of thumbnail processing and re-organizing all the time when new additions/deletions are done. 
My main reason for using Koreader is exactly that it does **not** work on data bases. Otherwise I would ditch it and use the OEM Nickel system.

**Comment by Brnoch** [comment]
I also use folders based on the genre, countries and author name. And I find it useful to do so.
And as you notice, responsiveness is critical (like you, one of the main reasons I abandoned Nikel was that it doesn't manage big libraires). 
But I don't know if it possible to manage thumnails, and eventually descriptions without affecting the responsiveness. Thumnails can be created/saved in a separate folder, and not included in a database. 
As far as I know, Nikel seems to index the whole content of the book, creating a record in the database for each page / chapter, so that the database is huge.

**Comment by Frenzie** [comment]
It could be done without affecting responsiveness too much by not waiting for thumbnails to be generated the first time. Thumbnails will be saved in .sdr in the future, initially for the history dialog redesign but it could also be used in the filemanager. Regardless, there should be a way to disable it not just for performance reasons, but also because it'd probably half the amount of files that can be displayed at once.

For me, KOReader's three biggest features are:

1. No-nonsense, fast filemanager (love at first sight)
2. Actually usable PDF
3. DjVu

Without those, I would've returned my H2O to the store, impressive display be damned. Everything else is just icing on the cake.

**Comment by Brnoch** [comment]
If thumbnails can be implemented as an option, like the file explorer on a PC, that would be great.
When you say the file manager should not wait for thumbnails to be generated the first time, do you mean that each book should be opened once so that its thumbnail would be generated? This would make the functionality much less usefull (as the thumbnails, like the description, is not only a way to identify a book, but also a way to choose the next one to be read).
Regarding the description, do you intend to make something in the future? I don't see any of them on the book notice that appears after a long-press on the book's title. They can be useful too to pick-up a new book.

**Comment by AlanSP1** [comment]
You can check this issue: https://github.com/koreader/koreader/issues/2614

There's talk about new book manager (vs. file manager). It would more or less be what you want.

Some people (myself included) don't want book manager, but some are more accustomed to managing books and not files. Not to recapitulate what is said in linked issue, check it yourself.

**Comment by Frenzie** [comment]
> When you say the file manager should not wait for thumbnails to be generated the first time, do you mean that each book should be opened once so that its thumbnail would be generated?

No, I mean something more like:

1. Get file list (same as now)
2. Determine which books in the list have thumbnails
3. Draw file browser (including existing thumbnails)
4. Continue generating missing thumbnails in the background (which would technically mean opening each book once)

As opposed to:

1. Get file list
2. Create list of books and whether they have thumbnails
3. Generate missing thumbnails
4. Draw file browser with all thumbnails

**Comment by KenMaltby** [comment]
So a background .sdr generation? (I know there will be the inevitable "Why not an SQL db, then?")  I don't know if that processing would have a noticeable effect on reading performance.  There is still the problem of the thumbnail inclusion in the file browser, drastically limiting the files listed on a page.  (I take the cfont down to 18 and set the Screen:scaleBySize to (28) giving much more of the file name and more listed per page.)

**Comment by Frenzie** [comment]
An SQL database might work better for metadata, but it'd be pretty awful for thumbnails. Anyway, I would never implement anything like this myself. I'm just brainstorming some ways in which it might work without falling prey to the Nickel behavior of: "hey, let's render your device unusable for half an hour because you had the gall to put a few files on there."

It's basically how it works in at least some PHP online galleries. You can make them try to generate all remaining thumbnails but you can also let them do it on the fly while loading the page, i.e., one page at a time. Due to the nature of browsers that equals slowly loading them in.

**Comment by Brnoch** [comment]
The way I use koreader (putting all books in a Genre/Country/Author
folder), the fact that the number of books displayed per page is limited
when you inclued thumbnails would'nt be a problem for me. But I know that
there are several ways to use koreader and that mine is not better than
others.

Basically, I think that many features that can bring the user experience
closer to the one you have in a physical library (where you can see
physically the books, their size, the cover, the presentation in the back,
and then open it to read a few pages) can improve it.
And that the file explorer in Windows (or Mac, but I don't know it
precisely) can be a good example: you can chose if you want a simple and
compact list or to include details/thumbnails.

Anyway, the responsiveness has the priority and if it means that the
thumbnails shall be generated in the background, and displayed after the
list, I don't think that it is a problem.

2017-05-19 19:10 GMT+02:00 Frans de Jonge <notifications@github.com>:

**Comment by ersi-dnd** [comment]
In Pocketbook, the file manager (Pocketbook's file manager) generates icons for the files from the first page and displays the description. It doesn't display file names, except by opening the book and taking a look under its details while in the book. To my disappointment, I have discovered that Pocketbook's file manager even doesn't search by file name, obviously a crucial missing feature.

One of the reasons Koreader is very valuable to me is the ability to list and search the files by file names rather than anything else.

**Comment by Brnoch** [comment]
Yes, for sure, the search functionality by filename should remain intact.

2017-06-06 7:06 GMT+02:00 ersi-dnd <notifications@github.com>:

**Comment by Frenzie** [comment]
Implemented in #2940.
