### ISSUE TITLE
Dismal Archive.org pdfs performance

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2929]
Hi

KR is really really really bad with scanned pdfs, and it is really really bad on pretty fast android devices as well. I really hope that it gets some performance upgrades.

Try some some of these old books

https://archive.org/search.php?query=painting%20figure&and[]=mediatype%3A%22texts%22&and[]=collection%3A%22americana%22&and[]=languageSorter%3A%22English%22

**Comment by KenMaltby** [comment]
"KR"?

**Comment by Frenzie** [comment]
Is there any program that isn't terribly slow on "really bad PDF"? But I'd
say you should be going with their DjVus. Really bad DjVus handle
(slightly) better than really bad PDFs. Plus you can disable the yellowed
page background on the fly.

With https://jwilk.net/software/pdf2djvu you can also create inferior but
much faster DjVus from PDF.

**Comment by gerroon** [comment]
@Frenzie

Actually apps like DocumentViewer, MoonReader, EbookDroid etc are generally 10x better than Koreader. They are nowhere near being snappy with those pdfs but compared to Koreader, they are pretty quick. Koreader takes like 3-4 secs a page flip really.

**Comment by gerroon** [comment]
Btw there is no Djv support on Koreader for Android, so djvu option is no good really.

**Comment by Frenzie** [comment]
Cou

**Comment by Frenzie** [comment]
Could you be a little more specific than "some of these"?

**Comment by gerroon** [comment]
Any of those books that are older books will be scanned in that "bad format". You can try any of the books in the archive url I gave.

Maybe this?
https://archive.org/details/landscapefigurec00hart

**Comment by Frenzie** [comment]
Document Viewer on my phone also takes an eternity to load a page in spite of it being heaps and gobs faster than my H2O. The difference as I see it is that it doesn't freeze the GUI, and that's a pretty big deal, but then again Document Viewer just crashed on that PDF after chugging away at it for a while. :-P

I can tell you that the DjVu version is orders of magnitude faster. It's close to usable on H2O. Since you say some other app already works better anyway (is KOReader slower on Android or something?) I'd go with DjVu in another app for the moment.

**Comment by gerroon** [comment]
Koreader on Android does not come with djvu libraries, it does not open them.

Document Viewer tends tends to be more bug prone , you need to try EbookDroid. Trust me I use these pdfs every day on galaxy tablets and Ebookdroid is very reasonalbe especially with cached pages.

**Comment by gerroon** [comment]
Also the weird thing is that the speed of Koreader does not change across cpus and devices. Running Koreader on a super fast android with  8 cores is no different than running it ona single core 1 ghz device. It would be nice if we get proper cpu uses if they are available.

**Comment by chrox** [comment]
It's true that koreader only use one system thread in most of the time doing ui rendering and backend document rendering except when pre-rendering the next page it creates another thread. So koreader hardly  can make use of the multiple cores CPU.

**Comment by gerroon** [comment]
@chrox

That is fine but the speed of the original thread does not change even between 1ghz or 2ghz cpu, not even talking about multiple cores. It seems like the experience of Koreader between super slow devices and super fasts devices is almost same.

**Comment by houqp** [comment]
Maybe it's not the rendering that's taking all the CPU. LUAJIT on a lot of android devices fallbacks to interpreter mode. But since we wrote almost everything in Lua, we actually heavily depends on the JIT engine to optimize the hot path for us. I have experienced koreader taking seconds to change a page in filemanager before on android due to this :(

**Comment by Frenzie** [comment]
I'd add that GHz isn't everything and that a lot of the faster Android devices are only faster for short bursts (because a few seconds is all it needs to feel significantly faster). Samsung devices were notorious for throttling back extremely aggressively. You can also add the subjective experience (or at least my subjective experience) that anything over 10-15 seconds pretty much counts as "eternity" regardless whether it ultimately takes one or two minutes.

**Comment by gerroon** [comment]
Can something be done to speed up JIT? It would be nice if Koreader experience gets linearly faster as the cpus of the devices get faster. In my experience (I use Koreader on 6 different various android devices with various speeds), Koreader is always feel like I am running it on a slow Eink device, regardless of the device speed and screen type.

**Comment by ersi-dnd** [comment]
RAM can make quite a difference with Koreader. I used to own a Pocketbook Sense device that I really liked in terms of how it fit in hand, but 250 MB RAM meant that Koreader simply didn't open many heavier pdf's. At all. Whereas with Pocketbook's own reader app, while it never failed to open anything, it could take literally ten minutes or more to open a file and then another ten minutes to turn a page.

Now I have Pocketbook Touch HD, 500 MB RAM, much snappier. And yes, when you take things from archive.org then djvu is a noticeably more workable format.

**Comment by Frenzie** [comment]
I'll close this because the C blitter now offers excellent performance on all Android devices and the real issue is just that the PDF is too heavy. On my phone KOReader actually performs really well on the problematic PDF compared to other viewers, and only the straight-up MuPDF app does better out of those I tried.

Also of course DjVu has worked on Android for a while now, so for Archive.org in particular there's a much better alternative. Even for other sources the `pdf2djvu` command is something to consider. Not for KOReader, just in general.
