### ISSUE TITLE
Frontlight flashes then turns off upon launching; KOReader↔Nickel frontlight sync broken

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2974]
* KOReader version: v2015.11-1064-gbd92d68
* Device: Kobo Glo HD

#### Issue
Another bug introduced by #2941.
1. Current frontlight value is no longer synced to Nickel's config file.
    (if `KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true`(default))
2. `KOBO_LIGHT_ON_START` is completely ignored.
    KOReader always starts with the frontlight on, intensity 20.
    * This happens regardless of the value in `KOBO_LIGHT_ON_START`

Expected behavior: (`defaults.lua`)
```
KOBO_LIGHT_ON_START = -2           -- -1, -2 or 0-100. -1 leaves light as it
                                   -- is, -2 uses 'Kobo eReader.conf', other
                                   -- sets light on start/wake up
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true  -- Save brightness set in KOreader
                                         -- with nickel's 'Kobo eReader.conf'
```

This issue appeared in `v2015.11-1059-g63f2284`

**Comment by a-kohout** [comment]
Pinging @Hzj-jie

**Comment by Hzj-jie** [comment]
I am looking.

**Comment by Hzj-jie** [comment]
Well, the auto-close function is a little bit tricky.
Would you mind to try the latest version? A recent refactor to the frontlight control logic introduced several issues.

**Comment by a-kohout** [comment]
Same behavior unfortunately (`v2015.11-1068-gc8be274`)
Do you want me to test some debug code?

**Comment by Hzj-jie** [comment]
I just realized the ota update has stopped for several days.
So does the version you are using contain https://github.com/koreader/koreader/commit/c8be27481c8dee2336ab0fa3e22cb91da3f047ee?

But according to your description, it seems like the "Kobo eReader.conf" cannot be opened by KOReader any more. If it was not so complex, would you mind to inspect if in https://github.com/koreader/koreader/blob/master/frontend/device/kobo/powerd.lua#L23 self.has_fl_state_cfg is true, and if "/mnt/onboard/.kobo/Kobo/Kobo eReader.conf" is still existing?

Thank you.

**Comment by a-kohout** [comment]
Yes, I compiled it using the official [virdevenv](https://github.com/koreader/virdevenv/tree/master/vm/ubuntu)

`Kobo eReader.conf` is not changed at all.

The problem seems to be bigger than just file-access related.
This config disables updating of `Kobo eReader.conf` and sets the light value to be restored from `settings.reader.lua`. Yet it always comes back with intensity level 20:
```
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = false
KOBO_LIGHT_ON_START = -1
```
`/mnt/onboard/.kobo/Kobo/Kobo eReader.conf`exists and works with an older version of KOReader.

The value of `self.has_fl_state_cfg` is __false__

**Comment by Hzj-jie** [comment]
Once KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = false, it's expected that Kobo eReader.conf is not changed at all. Have I misunderstood your meaning?
But I do find a leftover, which impacts the logic when KOReader is started. I have updated it at 808766b7f389ca9066d9468f850786a8f3eb7523.

**Comment by a-kohout** [comment]
The unexpected thing is, that `KOBO_LIGHT_ON_START` is ignored, ie:
* `KOBO_LIGHT_ON_START = -1` --> should restore light intensity from `settings.reader.lua` 
* `KOBO_LIGHT_ON_START = 50` --> should restore light intensity to 50

Unfortunately `v2015.11-1071-g970f2e7` is even worse:
* `KOBO_LIGHT_ON_START`and `KOBO_SYNC_BRIGHTNESS_WITH_NICKEL`are still ignored
* Frontlight flashes (around intensity 20 I'd guess) when starting KOReader, then turns off.
* Opening the Frontlight menu immediately turns the light to level 1 and shows the Intensity being `0`
    * Touching `-1`allows the intensity setting that's being displayed on the screen to go negative.
    * In this state `Toggle`doesn't work. 
    * `Toggle`also doesn't work when the light setting is `1`. It only works for levels 2 and higher.
    * When the level is 1, swiping down using the one or two finger gesture doesn't turn the light off. The GUI says "Frontlight is off" though.
        * A quick swipe from levels 2 and higher does turn the light off.

**Comment by a-kohout** [comment]
After going to sleep and waking back up Nickel syncing seems to be working. Although the value it syncs to Nickel is incremented by 1. `KOBO_LIGHT_ON_START = 50` also works after waking from sleep.

**Comment by a-kohout** [comment]
I tried to narrow it down further on a clean install of `v2015.11-1072-g4ec96e3`
The expected default behavior would be to use and sync the light value to `Kobo eReader.conf`
KOReader synced the light value to `Kobo eReader.conf` the first time I started it.
It stopped updating it while using it on subsequent lauches.
It does correctly restore the light intensity using the value in `Kobo eReader.conf` when turning the light on by a 1-finger swipe up.
When opening the frontlight menu it turns the light on at level 1 (See 2nd comment above)

**Comment by Hzj-jie** [comment]
Sorry for the misunderstanding before, I finally understand the issue you have mentioned. Let me summarize them based on my understanding and my knowledge of KOReader.
1. If frontlight is off, restarting KOReader will turn on the frontlight then turn it off, i.e. flashes.
  - This is because of a legacy logic in https://github.com/koreader/koreader/blob/master/reader.lua#L140. This condition section should be removed, since PowerD has tried to restore the frontlight state already. Meanwhile https://github.com/koreader/koreader/blob/master/frontend/device/kobo/device.lua#L187 should also be removed, and the "frontlight_intensity" and "is_frontlight_on" settings in G_reader_settings.
2. The frontlight levels in KOReader and Nickel are not consistent: setting 15 in KOReader will indeed as 16 in Nickel.
  - I do not think this is a new issue, the behavior has not been changed during the last refactor work. I personally do not use Nickel at all. So if this was an issue, I will update the logic: it's a pretty simple change.
3. The condition at https://github.com/koreader/koreader/blob/master/frontend/device/kobo/powerd.lua#L33 is wrong: not having frontlight state should not impact the synchronization of frontlight level.
4. Once frontlight is off, opening frontlight menu will turn on the frontlight at level 1.
  - This is because in https://github.com/koreader/koreader/blob/master/frontend/ui/widget/frontlightwidget.lua#L106, the frontlight level is always set in its initialization, which is unnecessary. But setting the level to a value less than fl_min will end up setting it to fl_min (https://github.com/koreader/koreader/blob/master/frontend/device/generic/powerd.lua#L121).
  - In general, FrontLightWidget does not need to store the frontlight level or fl_min / fl_max.

I will fix them one by one.

But KOBO_LIGHT_ON_START is really a very old global configuration which should be removed for a long time. Are you still using it?

**Comment by a-kohout** [comment]
Yes, I've set `KOBO_LIGHT_ON_START`to -1 so KOReader won't always start with the light on at the last intensity disregarding if it was on or off (Since it restores from `Kobo eReader.conf`)
If you want to get rid of `KOBO_LIGHT_ON_START` and `KOBO_SYNC_BRIGHTNESS_WITH_NICKEL`, you could implement the following:

* When the light gets toggled off --> Write a light intensity of 0 to `Kobo eReader.conf`
    * Still save the previous intensity value in `settings.reader.lua`
Upon starting KOReader:
* If the light intensity in `Kobo eReader.conf` is 0, restore the value from `settings.reader.lua` but leave the light off.
* If the light intensity in `Kobo eReader.conf` is greater than 0, restore that value and turn the light on.

These changes would make the light consistent when switching back and forth from Nickel.
It would also make KOReader turn the light back on if it was on before quitting. On versions before the AutoFrontlight PR it forgets the previous light value and starts with the light off (if `KOBO_LIGHT_ON_START` is -1)
