### ISSUE TITLE
Long wikipedia definition goes out of the window

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#3099]
When we have long wikipedia definition the text goes out of the window.
Like that:
![screenshot 2017-08-18 20-51-01](https://user-images.githubusercontent.com/22982594/29473283-79a2034e-8457-11e7-9f43-2b1c5a265af5.jpg)

**Comment by Frenzie** [comment]
A job for `RenderText:truncateTextByWidth()` I suppose.

**Comment by poire-z** [comment]
Quite tricky to fix, as here we use a Button (because we want a hold_callback), but Button centers text in itself, and if we provide a width (the dictquiclookup width), shorter text is centered in a wide button.
We could calculate in dictquicklookup the text width, but I think it should be done in lower level widgets,  button or textwidget themselves, which they half do if we provide a width, but with many side effects on centering...
I made something by introducing a max_width attribute to Button and TextWidget, that only dictquicklookup would use for now, to avoid side effects on other Buttons and TextWidgets.
Probably not the right generic fix for too-long text in buttons or other textwidget containers, but may be the simplest and safest for now.
