### ISSUE TITLE
Debian support

### ISSUE THREAD

**Issue by zaoqi** [koreader/koreader#3108]
Debian GNU/Linux on Kobo Aura HD:
https://www.mobileread.com/forums/showthread.php?t=247920

**Comment by Frenzie** [comment]
Gosh, on the one hand you'd think that should be the easiest because it's more or less normal Debian, while on the other hand all the scripts and infrastructure are based around the idea that a "desktop" device (e.g., with Debian) is a development machine.

**Comment by anarcat** [comment]
Yep. The "emulator" approach is kind of weird: while it's nice to replicate the environment of the e-reader for *some* development purposes, other development can operate fine in a native app. For example, I'm looking at writing support for wallabag in #2621 and that's just a regular plugin: I don't need a "touch-screen", ICC profiles or "e-ink" emulation or any of that kind stuff. I just want to run Koreader. ;)

Furthermore, *packaging* koreader for Debian would be great as well, but as part of that process you would need to get rid of a lot of re-rolled libraries like OpenSSL, mupdf, libpng and so on, because Debian usually frowns on "convenience copies of code" such as those. They also make compile times much longer than necessary and are a burden to maintenance... 

FWIW, there's another project of running Debian on Kobo readers in [okreader](https://github.com/lgeek/okreader)...

**Comment by Frenzie** [comment]
> I don't need a "touch-screen", ICC profiles or "e-ink" emulation or any of that kind stuff. I just want to run Koreader. ;)

That's highly debatable. That's how you end up with Android and Chrome. :-P They run fairly well on my i7 4790, which is probably about the closest you can get to Google dev 64-core drool machines while keeping motherboard + CPU + 32 GB RAM reasonably priced. Come to think of it, the price has actually gone up since I bought it a few years ago, mainly courtesy of RAM. Admittedly you could go much cheaper on the CPU now, with something like an AMD Ryzen 5 1600. Anyway, point being that it's orders of magnitude faster than most devices on which the program is actually being used which leads to a disconnect.

> "convenience copies of code"

KOReader is made for embedded devices. It's the exact opposite of convenience. You don't even want to know how much I cursed at Android to get these "convenience" copies properly included. Examples: https://github.com/koreader/koreader-base/pull/521 https://github.com/koreader/koreader-base/pull/546

On Debian I could just link against libdjvulibre. *That*'s convenience.

NB I'm not particularly interested in spending my time on this. I'd definitely keep it in mind if [CMake annoyed me too much](https://github.com/koreader/koreader/issues/3496#issuecomment-372042304)… but for now the motto is: PRs welcome!

**Comment by anarcat** [comment]
> Anyway, point being that it's orders of magnitude faster than most devices on which the program is actually being used which leads to a disconnect.

Oh, of course: I don't mean to say that there shouldn't be an emulator. I'm just arguing that there is definitely room for a faster development environment. I will, in the end, run things on my actual Kobo: that's the final goal... And yes, there's possibly a disconnect that could affect development, but I'm not that crippling the emulator will help developers write more efficient code so much. And besides, there are better way of doing this than complicating the build chain. ;)

> KOReader is made for embedded devices. It's the exact opposite of convenience. You don't even want to know how much I cursed at Android to get these "convenience" copies properly included.

You're right, I really don't want to know. Any time I touch Android development was a nightmare. ;)

But yeah, this is a wishlist, don't worry about it so much. Don't mind me, it's just the usual rant from a Debian developer WTF'ing at yet another libpng build. ;)

**Comment by pazos** [comment]
@anarcat 

I do like the idea of releasing a dpkg package of KOReader as an alternative of the appimage but I see no real benefit of being "supported" by Debian. We do release a lot of nightlies and, as @Frenzie said, we're targetting embedded devices. Being supported by Debian would mean another dll hell (we're tied to system libraries, if there is a bump in a library we will need a new branch to support Debian) without any real benefit.

On the other hand building a debian package from a working emulator should be really easy (see https://github.com/NiLuJe/FBInk/blob/master/tools/do_debian_package.sh as an example)

**Comment by zaoqi-unsafe** [comment]
I just want to get koreader worked without breaking debian and X11 on kobo

**Comment by pazos** [comment]
I'm in for adding a native debian target (the emulator without debug symbols packaged for debian under /usr/local/). It should be easy enough to add a couple of targets for arm platforms (armel and armhf) as long as we target generic armv7 devices and build them with standard ubuntu-linaro cross toolchains.

@Frenzie: does this make any sense?

**Comment by Frenzie** [comment]
If you're offering to put in the work, sure. ;-) 

Note that the emulator is built for native. The AppImage is the most relevant for the basic use case.

**Comment by pazos** [comment]
Bumping for testing purposes
