### ISSUE TITLE
Page Crop without Reflow

### ISSUE THREAD

**Issue by zaoqi** [koreader/koreader#3120]

**Comment by Frenzie** [comment]
I'm not entirely sure what you mean? I can crop and reflow separately.

**Comment by zaoqi** [comment]
Reflow doesn't support "The Reasoned Schemer" http://vdisk.weibo.com/s/A4FI6ecMOymq

**Comment by Frenzie** [comment]
Due to the nature of that kind of mathematical/programming content it would be hard to get satisfactory results, but both reflow (2) and autocrop (3) seem to be working how I'd expect them to.

Since reflow doesn't play nice with this kind of content I'd go for landscape (4) if regular portrait mode is too small.

### 1. Regular
![screenshot_2017-08-22_10-55-51](https://user-images.githubusercontent.com/202757/29557195-87b65178-8728-11e7-86d0-9227fe8c931b.png)

### 2. Reflow
![screenshot_2017-08-22_10-54-42](https://user-images.githubusercontent.com/202757/29557138-6639532e-8728-11e7-88c2-a1a00caef256.png)

### 3. Autocrop
![screenshot_2017-08-22_10-56-04](https://user-images.githubusercontent.com/202757/29557196-87b9344c-8728-11e7-8014-9fd6aa5eb473.png)

### 4. Landscape
![screenshot_2017-08-22_10-59-01](https://user-images.githubusercontent.com/202757/29557325-0006b334-8729-11e7-87ea-e086fa2ef808.png)

**Comment by zaoqi** [comment]
How to Autocrop?

**Comment by Frenzie** [comment]
In the bottom menu, second icon from the left. 
![screenshot_2017-08-22_11-09-07](https://user-images.githubusercontent.com/202757/29557742-560a759e-872a-11e7-9d78-3d44d8854d17.png)

**Comment by Frenzie** [comment]
I'll close this now. :-)
