### ISSUE TITLE
CSS: Link declared media queries are not evaluated

### ISSUE THREAD

**Issue by ajkq** [koreader/koreader#3179]
* KOReader version: v2015.11-1188-g12af617
* Device: Emulator

#### Issue
Link declared media queries are not evaluated, both stylesheets are applied
```
<link href="../Styles/epub.css" type="text/css" rel="stylesheet"/>
<link href="../Styles/kf8.css" media="amzn-kf8" type="text/css" rel="stylesheet"/>
```

`kf8.css`
```
body {
  text-decoration: line-through;
}
```
iBooks/ADE/Sigil/Calibre gets it right.
Koreader wrongly applies line-through.

`epub.css`
```
body {
  font-size: 2em;
}
@media amzn-kf8 {
  body {
    background-color: silver;
  }
}
```
CSS declared media queries are ignored.
Background color is not applied (correct).

#### Steps to reproduce
[untitled.epub.zip](https://github.com/koreader/koreader/files/1279265/untitled.epub.zip)

**Comment by Frenzie** [comment]
Support for something like `@media all and (min-width: 8cm)` would be very nice to have, but the fact that there exists something like `@media amzn-kf8` (even though of course that shouldn't do anything) makes me cringe.

**Comment by poire-z** [comment]
Just thinking: if we were going to solve #7199, and parse or skip `@media some constraints { ... }`, and if we were to not implement the parsing and checks from "some constraints" (like `(min-width: 8cm)`), what would be the best (or less worse) thing to do: parse it, or skip it?

**Comment by Frenzie** [comment]
You should skip them, otherwise you'd get extremely unexpected behavior.

```css
@media all and (min-width: 30cm) {
 /* things */
}
@media all and (min-width: 20cm) {
 /* now we're overriding the above!? */
}
@media all and (min-width: 10cm) {
 /* and overriding that too, randomly mixing display properties tailored for different sizes */
}
@media all and (min-width: 5cm) {
 /* ooh boy, is this a mess or what */
}
```

Whereas if they're ignored as they should be, the base style applies.

Incidentally, I would mildly suggest supporting `@media all`, and ideally also `@media screen` and `@media print` (NB screen/print would need to be some kind of toggle, probably default to screen.)

I really need a way to automatically query my corpus of Humble Bundle EPUBs for EPUB/CSS features they use to see what happens in the wild. :-)

**Comment by poire-z** [comment]
Working on properly parsing (actually, rather properly skipping :) at-rules https://github.com/koreader/koreader/issues/7199#issuecomment-767480712 .

Regarding `@media` specifically: I can handle parsing simple strings like "all" or "screen".
Looking at what's in all my >200 test EPUBs, I see very little use of `screen` (1 book, + the O'Reilly ones I guess) and `print` (2 books), and this is the complete list I get:
```
@media (max-width: 480px) {
@media all and (orientation:landscape) {
@media all and (orientation:portrait) {
@media all and (prefers-color-scheme: dark){
@media all{
@media amzn-kf8
@media amzn-kf8 {
@media amzn-mobi {
@media amzn-mobi, amzn-kf8 {
@media amzn-mobi7 {
@media not amzn-mobi {
@media not amzn-mobi, not amzn-kf8 {
@media not amzn-mobi7 {
@media print {
@media print{
@media screen and (min-width:500px) {
@media tv {
```
We would skip all of these (except "all").

But in the recent O'Reilly books mentionned at https://github.com/baskerville/plato/issues/183, there is a shitload of ugly CSS, and a huge list of `@media` queries like:
```
@media (max-width:540px){
@media (max-width:768px){
@media (min-width:32.5625em){
@media (min-width:450px){
@media (min-width:768px){
@media (min-width:78.125em){
@media all and (max-width:900px){
@media only screen and (device-aspect-ratio:40 / 71) and (orientation:landscape){
@media only screen and (max-device-width:30em) and (orientation:landscape){
@media only screen and (max-device-width:30em){
@media only screen and (max-width:32.5625em){
@media only screen and (max-width:520px){
@media only screen and (min-device-width:48em) and (device-height:64em) and (orientation:landscape){
@media only screen and (min-device-width:48em) and (device-height:64em) and (orientation:portrait){
@media only screen and (min-width:1250px){
@media only screen and (min-width:1280px) and (max-width:1600px){
@media only screen and (min-width:1601px){
@media only screen and (min-width:521px) and (max-width:1249px){
@media only screen and (min-width:78.125em){
@media print{
@media screen and (max-height:26.25em){
@media screen and (max-height:33.75em){
@media screen and (max-width:1250px){
@media screen and (max-width:23.75em){
@media screen and (max-width:26.25em){
@media screen and (max-width:28.125em){
@media screen and (max-width:30.9375em){
@media screen and (max-width:30em){
@media screen and (max-width:32.5625em),(max-height:26.25em){
@media screen and (max-width:32.5625em),screen and (max-height:25.0625em){
@media screen and (max-width:32.5625em){
@media screen and (max-width:32.5em),screen and (max-height:26.25em){
@media screen and (max-width:32.5em),screen and (max-height:33.75em){
@media screen and (max-width:32.5em){
@media screen and (max-width:32.625em){
@media screen and (max-width:320px){
@media screen and (max-width:34.375em){
@media screen and (max-width:40.625em){
@media screen and (max-width:43.75em){
@media screen and (max-width:449px){
@media screen and (max-width:45em){
@media screen and (max-width:48em){
@media screen and (max-width:49.375em){
@media screen and (max-width:49.4375em) and (-webkit-min-device-pixel-ratio:0){
@media screen and (max-width:49.4375em){
@media screen and (max-width:50em){
@media screen and (max-width:51.1875em) and (max-width:45em){
@media screen and (max-width:51.1875em){
@media screen and (max-width:51.25em){
@media screen and (max-width:51.3125em){
@media screen and (max-width:53.125em) and (min-width:45.0625em){
@media screen and (max-width:53.125em){
@media screen and (max-width:53.75em){
@media screen and (max-width:56.25em){
@media screen and (max-width:580px){
@media screen and (max-width:620px){
@media screen and (max-width:767px){
@media screen and (max-width:78.125em){
@media screen and (max-width:800px) and (orientation:landscape),screen and (max-height:300px){
@media screen and (min-height:1050px){
@media screen and (min-height:26.25em){
@media screen and (min-height:570px){
@media screen and (min-height:840px){
@media screen and (min-width:1024px) and (orientation:landscape){
@media screen and (min-width:1250px){
@media screen and (min-width:137.5625em){
@media screen and (min-width:179em){
@media screen and (min-width:20em){
@media screen and (min-width:220.4375em){
@media screen and (min-width:30em){
@media screen and (min-width:32.5625em) and (min-height:26.25em){
@media screen and (min-width:32.5625em) and (min-height:33.6875em){
@media screen and (min-width:32.5625em) and (min-height:420px){
@media screen and (min-width:32.5625em){
@media screen and (min-width:32.5em),screen and (max-height:33.75em){
@media screen and (min-width:32.625em){
@media screen and (min-width:40.625em){
@media screen and (min-width:41.9375em) and (min-height:26.25em){
@media screen and (min-width:45.0625em){
@media screen and (min-width:450px){
@media screen and (min-width:45em){
@media screen and (min-width:48.0625em){
@media screen and (min-width:49.4375em) and (min-height:26.25em){
@media screen and (min-width:49.4375em) and (min-height:420px){
@media screen and (min-width:49.4375em){
@media screen and (min-width:521px) and (min-height:420px){
@media screen and (min-width:650px){
@media screen and (min-width:768px) and (max-width:1279px){
@media screen and (min-width:96.125em){
```
Totally ridiculous...

I guess sizes in 'em' there are actually 'rem' and reference the main font size ?

Is it worth trying to parse "simple" combinations that would contains only consecutive `and (prop:size|keyword)` ? 
I see `only screen` is used so that "older browsers", not recognizing "only" as a device type, would skip it. Should we just pretend we're "older" and give up on the most complex ones?
If we were to handle simple combinations, would it be bad if we were not handling accompanying more complex combinations (with "or" or nested `( (...) or (...) )`) ? That is: rather everything, or nothing at all ? And handling some of them is worse ?

Just skipping properly at-rules make these O'Reilly books look a lot better - but there's still some minor alignment issues (that we can solve with "Ignore page margins" et al.) - I wonder if properly applying all these `@media` crap would make it really better or not that much (I'd need to implement it to see ... I'd like to know that before getting into working on it :)

**Comment by Frenzie** [comment]
> I guess sizes in 'em' there are actually 'rem' and reference the main font size ?

In this case they will be the same, yes. It's the `em` for the `:root`, which is the same as `rem` for `:not(:root)` elements.

> Should we just pretend we're "older" and give up on the most complex ones?

Reference:
https://www.w3.org/TR/css3-mediaqueries/#media0

The main purpose is to prevent an older browser thinking it supports `@screen` and therefor it'll apply it even though it doesn't understand more complex media queries. Because initially you could specify something like `@media screen, print` and any other random stuff at the end would just be truncated. At a glance the above CSS doesn't seem to make any sense because the same complex media query exists both with and without `only` (which also seems to invalidate your rationale).

Given the above it seems that you should just drop media queries you can't parse (I believe that's per spec), and there's really no reason to not just ignore `only` like a newer browser would.

> If we were to handle simple combinations, would it be bad if we were not handling accompanying more complex combinations (with "or" or nested ( (...) or (...) )) ? That is: rather everything, or nothing at all ? And handling some of them is worse ?

Traditionally we should only use simple media queries because otherwise IE7 for example might get confused. By simple I mean the `@media screen and min-width` only. I suppose that in 2021 that's less of a concern, but even so I think that almost all queries are either simple or relatively simple complex ones of the form `@media screen and min-width and max-width`. So I think handling those will be quite advantageous, while the negative effects of not handling truly complex ones are probably fairly small.

> Just skipping properly at-rules make these O'Reilly books look a lot better - but there's still some minor alignment issues (that we can solve with "Ignore page margins" et al.) - I wonder if properly applying all these @media crap would make it really better or not that much (I'd need to implement it to see ... I'd like to know that before getting into working on it :)

The difference should normally be fairly small but still better. A few font size differences, full-width images instead of left/right floats, that kind of thing. I'll have to take a peek at some O'Reilly books I suppose. I have a whole bunch on Humble Bundle.

**Comment by poire-z** [comment]
Just thinking: it publishers ought to make the book look ok for renderer that don't support "media min/max-width/height", we may just ignore them.
Because not ignoring them, we'll have different renderings on different devices/emulators, and another variable when debugging/reproducing issues :/ Consistency über alles!

**Comment by Frenzie** [comment]
The main kind of changes on small screens (e.g., mobile phones) will be full-width sized images as opposed to something floating on the left or right for example. Maybe some small typographical changes to similar effect (e.g., slightly smaller headings, less fancy alignment), smaller margins.

In well-designed documents the non-media query styles will be more or less equivalent to the small screen styles, so not supporting at least simple media queries (e.g., `@media screen and min/max-width`) is likely to yield what we'd probably consider inferior results.

I assume this should be fairly easy to see in some of the aforementioned O'Reilly EPUBs resizing a calibre window around a bit.

**Comment by poire-z** [comment]
Some numbers.
Among all my test epubs, I see ZERO occurence of the use of `media=` inside `<link...>` inside `*htm*` files inside EPUBs such as in the original post above:
`<link href="../Styles/kf8.css" media="amzn-kf8" type="text/css" rel="stylesheet"/>`

Also, I see only 2 occurence of `@media .. print`:
- in the infamous nwt_italian.epub (where it just sets some background and borders color to black - and we can do that on all elements with an existing style tweak)
- in some epub3-internallinks.epub I must have found on some EPUB3 samples page, where it contains nothing much interesting, but fixed font sizes:
```css
@media print {

body.opening {
font-size: 24pt;
padding-top: 20%;
padding-bottom: 10%;
padding-right: 1%;
padding-left: 1%;
}

div#mainBlock { }

/* title block */

.opening div.title h2.sub {
margin: 0 .15em .75em .15em;
font-size: 1.5em;
color: gray;
}
div.title { }
h1.main { }
h2.sub { }
h3 { font-size: 160%; }
h3.revisionNumber { display:none; }


/* creator block
********************************************/
div.creater { }
dl { }
dl dt {
        font-size: 90%;
}
dl dd {
        font-size: 120%;
        font-weight: bold;
        margin-bottom: 0.2em;
}

div.summary { font-family:serif; }
div.keyword { display:none; }

/*
********************************************/
div.publisherCompany { }
div.publisherCompany h3 { font-size: 130%; }

}
```

> and `@media print` (NB screen/print would need to be some kind of toggle, probably default to screen.)

I guess I won't bother with such a toggle (which would have no effect on 99% of books, except by ignoring `@media screen` - which might be useful, but won't have any effect on 94% of books), and just ignore any `@media print` section.
(From some specs: "print" is "intended for paged material and documents viewed on a screen in print preview mode")

**Comment by poire-z** [comment]
Something I find a bit odd about for example `@media min-width: 1000px` to detect large screen devices.
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/width
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-width

https://www.w3.org/TR/css3-mediaqueries/#units says:
> The units used in media queries are the same as in other parts of CSS. For example, the pixel unit represents CSS pixels and not physical pixels. 

So, this means that on high DPI devices with screen size larger than 2000px, that you might want to detect with such media queries - the device/browsers being high dpi should probably scale the `1000px`, so 1 CSS px = 3 screen px for example on a 300 dpi device. So, this should translate to `@media min-width: 3000screenPX`.
Which means this media query won't match - and these can't be used to detect them :)

Did I miss something ?
(I have a too cheap normal-DPI laptop, so can't test how it works out of the box :)

(In KOReader, this means they will match differently depending on the Zoom/DPI bottom setting.)

**Comment by Frenzie** [comment]
> Which means this media query won't match - and these can't be used to detect them :)
> 
> Did I miss something ?

Your example above is for detecting the widest of widths. It sounds like you're looking for 
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution

> In KOReader, this means they will match differently depending on the Zoom/DPI bottom setting

Same in browsers.

But I'm not sure what you're asking

**Comment by Frenzie** [comment]
> (I have a too cheap normal-DPI laptop, so can't test how it works out of the box :)

You can just zoom out btw.

**Comment by poire-z** [comment]
> But I'm not sure what you're asking

Let's say I'm a web page author and I want to do different things whether cheap 1024x768 laptop or expensive 3000x2000 computer.
I could feel naively about using as this properties' name states:
```css
@media screen and (min-device-size:1600px) { div::before { content: "you are high" } }`
```
But it feels this won't match on this 3000x2000 if the default/user set "scaling for dpi" (which Windows would probably set to 175% or 200%).
It will match only when the user has decreased Windows's Scaling setting to 100% or 125%.
Right ?

(It might be fine, in the spirit of _"you author don't need to know the real screen size, you'll get the apparent/virtual screen size no matter how rich the user is, which you don't need to know"_ :)

**Comment by Frenzie** [comment]
See above, you can use `@media (min-resolution: 300dpi) {`.

**Comment by poire-z** [comment]
That could catch a small high dpi phone. I want to catch a > 1600 screen px device.

But I don't really need a solution :) I just need you to tell me that what I find odd is just right and the way it should be (according to the specs and your CSS/screen/DPI familiar mind :)

**Comment by Frenzie** [comment]
Those combine. Something along these lines would be (pretending to be) phone-sized:

```css
@media only screen
  and (min-device-width: 300px)
  and (max-device-width: 800px)
  and (resolution: 300dpi) {
}
```

Put in 1600px and 300 DPI and you've got… well, probably nothing. The Dell UltraSharp UP3218K is 280 DPI. But put in 1600px and 150 DPI and you've got your UHD desktop monitors.

Of course, as people often have to be reminded for some reason, monitor size is *not* window size. I'm typing this right now in a reported window.innerWidth of 670.
