### ISSUE TITLE
Delay when select word around end of chapter (some epub books).

### ISSUE THREAD

**Issue by webstatic** [koreader/koreader#3187]
* KOReader version:  v2017.08.21-nightly
* Device: kobo mini

#### Issue
The problem only happen on some epub books.
This one for example.
 https://drive.google.com/drive/folders/0B-5XtCxJULf4ejJCcjA5QmEwb1E

When select word around end of chapter, it will delay about 3s before highlight word and open dictionary.
Delay time depend on how long chapter are.
And back to normal when start new chapter.

When I've changed file libcrengine.so to last version (v2017.06.12-nightly), it fixed.
So I think the problem may cause by some change on this file, between these two versions. 

#### Steps to reproduce
open this one -> https://drive.google.com/drive/folders/0B-5XtCxJULf4ejJCcjA5QmEwb1E
go to last page of some chapter (2 or 3).
select some word.

**Comment by poire-z** [comment]
Just confirming this with the book provided: it takes 1 second at start of chapter, 3-4 seconds at end of chapter on GLO HD, but it's not noticable on the emulator.
I checked with the oldest version I still got around (v2015.11-1082-gdffa2f2, Jul 14), and behaviour is the same.
Can't verify it is different with a version from 2017.06.12, but there was not much work on crengine between June 12 and July 14, and none that looks like it could be used in looking for hold word...

**Comment by robert00s** [comment]
I confirm that the problem is also on my Kindle (on one of my book). I think it's probably problem with highlight and getting position of word in crengine.

**Comment by webstatic** [comment]
I only copy file libcrengine.so from this  "koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1054-g6870bc2", and replace to that file of Latest release, and it work. 
(I have to clear cr3cache before)

It work for now, but I don't need to do this every other versions.

**Comment by poire-z** [comment]
https://github.com/koreader/koreader/blob/2b3b3107191354e60d59a0fdbbaced3490bf8462/frontend/document/credocument.lua#L182-L185

For a word at end of a chapter for this book, on the emulator, getTextFromPosition takes 5ms. getWordFromPosition takes 500ms (10ms for a word at start of next chapter).

Reverting https://github.com/koreader/crengine/commit/090059e18346f6851e2836cd117be2021c795a58 makes getWordFromPosition take 5ms at end of chapter (3ms at start of next chapter).
It is not the *1000 stuff, but the commented stuff in lvtinydom.cpp (`//cause crash problem`).
Uncommenting it makes getWordFromPosition() takes 5ms.

(But I must say that it's been some time I haven't had a crash with crengine, so I suppose we shouldn't blindly uncomment it...)

**Comment by webstatic** [comment]
So that is optimization html structure code, and sometime cause crash on some books.

How about another normal book, are they (this problem code) also optimize it?
Or it only optimize some specific book?.

I've found 2 books of this problem after last update.
But I not find the crashing problem (on last version) yet.
So I not sure it will be worthwhile trade off.

**Comment by poire-z** [comment]
It was just that this optimisation was may be the cause of some crashes on specific books, and the easiest way to avoid crashes was to remove it, expecting no side-effect. There's been no side effect until you reported one :)
So, it may need more investigation, but this part of the code is a bit over my head.

Just reporting this (with current crengine, with mentionned commit not reversed):
In this book provided, considering the file 3.html, there are 2 `<br/>` in this page.
Removing the one at the end of the page makes getWordFromPosition() takes again 5ms (instead of 500ms with it):

```
      <li>¿2ch Meijin site: i2chmeijin.blogg.fc2.com, boujin-kun: shogis.com/s</li>
    </ol>
    <br/>
</body>
</html>
```

It looks then related to the analysis by @frankyifei about `<br/>` in his commit message and https://github.com/koreader/crengine/pull/73 .

**Comment by frankyifei** [comment]
I got another way to deal with the crash problem, we can avoid call autoboxChildren() when the book cache is created. like add this line` if (this->getDocument()->_cacheFile == NULL)` before the two calls to autoboxChildren(). Because if the book cache is created, it is highly risky to modify dom tree through this method. How about this? It can solve #3192 as well.

**Comment by poire-z** [comment]
Well, bravo !
Your solution looks nice and simple, and do fix:
- all my crashes on my sample books that did (books > 300K with some `<br/>` here and there, and a few others): my procedure was: rm -rf cr3cache > open book (embedded styles on by default) > close book (cache created) > re-open book > toggle embedded styles off >used to crash, but no more with this patch
- #3192 : following text that used to stick to header is now correcly in its own paragraph
- #3187 : getWordFromPosition() for words at end of chapter takes 5ms instead of 500/1000ms.

**Comment by poire-z** [comment]
Btw, dunno if that will be needed for your patch, but when trying stuff, got some crash on normal books because cache format was changed. It may be best to change/increment the cache version so users with already opened books with cache won't crash and have their cache recreated:

https://github.com/koreader/crengine/blob/f5cf8fa132e2dfd2cf2bc62f25ab01969b7a8a70/crengine/src/lvtinydom.cpp#L14-L16

**Comment by frankyifei** [comment]
ok, that's a good idea since we have changed cache format. I will create a PR soon.
