### ISSUE TITLE
Performance of bookmarks drops significant from 2c1e7f2

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#3261]
* KOReader version: started from 201512246
* Device: irrelevant

#### Issue
After 2c1e7f2, the performance of bookmarks drops significant. After adding ~120 bookmarks, KOReader becomes extremely slow. And the process usage raises to 100% when opening menu or turning pages.

**Comment by Hzj-jie** [comment]
Last known good version should be three or four days ago.

**Comment by Frenzie** [comment]
Odd, I see nothing at all like that on my H2O.

**Comment by Hzj-jie** [comment]
No, this issue cannot be reproduced on Kobo.
Last known good: 1233-g4713926
Bad: 1235-g2c1e7f2

**Comment by Frenzie** [comment]
So just this?

https://github.com/koreader/koreader/compare/4713926...2c1e7f2

Does it happen no matter what or only if you use crengine?

**Comment by poire-z** [comment]
Do you need to do some specific action (viewing History, opening an epub, not happening when you open a pdf?) to trigger that ? Does it happen on startup if you start only to filemanager ?

**Comment by poire-z** [comment]
> ps output shows KOReader itself (luajit process) uses over 50 processor resource.

Do you mean there is 50 luajit processes ? Had you browsed FileManager or History with the coverbroser display modes ?

**Comment by Hzj-jie** [comment]
Sorry, I mean 50% processor resource.
Yes, it looks like the issue happened after I opened a large epub file and recovered after I closed the book.
I tried to clear the cache of crengine, but no improvement.

I doubt the root cause is
https://github.com/koreader/crengine/compare/b1cf4ecea498106ecc335751557a9001392daeab...8eefe54e40e4c3f56392e7d8ee2fe43848d53256#diff-77f6525e33d2fd1aeeb073a64dd8d759. It may increase the complexity of ldomNode::autoboxChildren() function and cause KOReader won't be able to handle large file well. The epub file is 7.2M with ~12K pages.

I have not tried the same file on my Kobo, so it may also be impacted by the issue.

**Comment by Hzj-jie** [comment]
Interesting, I cannot reproduce the issue on Kobo with the same book. Something else may be wrong.

**Comment by poire-z** [comment]
(Backup and) purge .sdr if you had one maybe ? Can think there is a last_xpointer or something that does not exist anymore in the dOM with the autobox stuff change, and we don't know how crengine behave in that case.

**Comment by frankyifei** [comment]
I changed cache file version number. is that related to this?

**Comment by poire-z** [comment]
> I noticed file manager crashed several times when I changed to grid view with thumbview.

Do you mean KOReader crashed (any log?) ?
Or that you just got some items saying "_not readable by engine, too many interruptions or crashes_", in which case, it's a security feature: metadata extraction from books is done by forking koreader to just have crengine open the book, and a current indexation is killed whenever a new one is neeeded (when you quit filemanager, when you swipe to next page and new book need indexing) - or if a book opening was taking more than 300 seconds: after 3 tries at background opening a book, this book is flagged with this message, and no more tries will happen (unless you Hold and chose _Refresh cached book information_).

**Comment by frankyifei** [comment]
It just crashes the kindle ui and forces kindle into starting screen.

**Comment by poire-z** [comment]
The _koreader ui_ or some other kindle stuff (never used a kindle). Any log about this crash?

**Comment by frankyifei** [comment]
it's kindle stuff. I tested again and thumbview crashed kindle stuff again. Maybe it used too much system resources. When I exit from koreader, it gave me blank screen and I had to restart kindle manually.

**Comment by poire-z** [comment]
@frankyifei : any more info or context? Does that happen if you browse/start browsing from any directory, whatever the kind of books in it? Or with some dir containing specific books? pdf, epub? If you stay in classic mode, can crengine open all the books? And with mosaic mode or list modes too ? list mode with no image?
No log at all?

Can you try deleting the coverbrowser db (thru menu Display mode / bookinfo db management), to see if it happens again with a fresh db, and no rescaling needed (with a recent nightly - tomorrow's nightly should include mupdf scaling to cover image while coverbrowser indexes books, which may add another uncertainty :|

Since what version have you noticed that? (lately, there's been some changes of mine related to cover browser and history, yours about crengine, some of mine about imagewidget now scaling images with mupdf, that could all be involved in that...)

**Comment by frankyifei** [comment]
Koreader did not crash at first. I assume it is some books on my device caused this. 
I tested again, after deleting coverbrowser, kindle ui restarts at background when koreader finds two books (no book information: too many interruptions or crashes), at this time, koreader is still running and responsive. Then I have another large epub has no book information. This time the kindle became unresponsive and I had to restart kindle manually.
`09/29/17-16:10:52 INFO  Seen 3 previous attempts at info extraction /mnt/us/documents/蛮荒系列合集(树下野狐).epub , too many, ignoring it.
09/29/17-16:12:47 INFO  Seen 3 previous attempts at info extraction /mnt/us/documents/蹉跎【炫锋版】.epub , too many, ignoring it.
09/29/17-16:15:24 INFO  Seen 3 previous attempts at info extraction /mnt/us/documents/鹿鼎记.epub , too many, ignoring it.
`

**Comment by poire-z** [comment]
Also, once indexing has been tried 3 times for each book, and they all show `Seen 3 previous attempts at info extraction, too many, ignoring it`, no more indexing should happen and it should be fine.
Is it ? Or does the crash still happen at this point ? (in which case, it's not an indexing problem...)

Any way to see linux logs on kindle ? May be the kernel had killed some processes cause of memory usage.

**Comment by frankyifei** [comment]
I dont think autobox children is the reason. it is only called when there is some inline text inside a tag. 
But maybe the disabled cache is the reason. I tested newest version on emulator, it used up my 4gb ram in my virtualbox when generating thumbview for a 14mb pure text epub.
It only happens when trying to index the file. Like you said, once it tried 3 times, it works well with the message(no information). 
I tested with enabled cache for indexing on emulator(modifid line 309). It works well but I dont know if it is suitable for eink devices. It looks like large ebooks when opening with disabled cache uses too much ram, it even freezes my virtual machine for 5 seconds.

**Comment by poire-z** [comment]
Well, I guess we should just remove this disabling of cache in BookInfoManager:extractBookInfo() , and try to find a way to have crengine delete the cachefile it just created at some point (or better: delete it only if it created it in this session, not if it was already existing). Either by setting a new property instructing it to do that, or by having a method to be called from credocument.lua via cre.cpp to have the cache file deleted, that BookInfoManager could call when/after closing the document.
This cache stuff happens again in lvtintydom.cpp (I'll look at it, but if you have time, as you're more conforable than me with crengine, you can look too :)
(I don't find any cache files volume or number management, so cached files are never clean automatically ? we could just not bother if it had that)

Or simpler: do that from lua, we could guess the cache filename by doing what is done in
https://github.com/koreader/crengine/blob/8eefe54e40e4c3f56392e7d8ee2fe43848d53256/crengine/src/lvtinydom.cpp#L9219-L9249
and check that crengine doesn't crash when, even if present in its cr3cache.inx index, the cache file is no more there.

**Comment by frankyifei** [comment]
why not just fetch metadata and cover image from the epub file directly? importing epub files creates dom tree and cache file during the loading process, which is not necessary if we only need metadata and cover image.

**Comment by poire-z** [comment]
Because crengine does that for .txt, .html, .fb2 too :) well, all its supported types. I know it's a bit expensive,, but we know that way it's openable/readable by the engine, and there's no stuff to re-implement on the lua side, for all these supported formats :|
May be we could add a flag to https://github.com/koreader/koreader-base/blob/master/cre.cpp#L420 (or a new method) and down in crengine to do a _lazy-load_, just enough to get the metadata and cover, and not build the DOM (and so, not creating a cache, which would solve this cache problem too).

**Comment by frankyifei** [comment]
is it possible to save the cache file in a temporary folder and delete the folder after metadata is fetched？ it can be done from the lua side, I assume it is easier.

**Comment by poire-z** [comment]
Nicest and easiest idea indeed :) It's possible, I'll do that.

For your big books, what is the size of their cache files? We would need 9 x this size for an indexation step.
I wonder if we can use some tmpfs (/tmp or /dev/shm), for them, to avoir sdcard write. Even if it's probably safer to use `cre.initCache(DataStorage:getDataDir() .. "/cache/cr3tmp", 1024*1024*32)` .

But wait, there is a maxsize there, and crengine does indeed some vacuuming at https://github.com/koreader/crengine/blob/8eefe54e40e4c3f56392e7d8ee2fe43848d53256/crengine/src/lvtinydom.cpp#L9143.
So may be we could just use `cre.initCache(DataStorage:getDataDir() .. "/cache/cr3tmp", 1024*1024*4)` (4 Mb, if that's ok for one of your book) in bookinfomanager.lua line 309, and don't care about cleaning it.
Could you try that with your big books (delete bookinfo db, re-do what you did) ?

**Comment by frankyifei** [comment]
my 13mb epub has a 25mb cache file, it's pure text.

**Comment by poire-z** [comment]
OK, implemented with 0 as cache size, with some cleanup of tmpdir when leaving filebrowser.
Can you confirm with next nightly it works as intended (no ui crash) on your kindle with the same books you tested with?

**Comment by Hzj-jie** [comment]
I believe the original problem is because of the increment of memory usage. KOReader works well on small files.
We should have some ways to reduce the memory usage from crengine, but that beyonds this issue.

**Comment by Frenzie** [comment]
Speaking of cache, I think there might be a crash related to that newly exposed font hinting setting. I can't quite seem to put my finger on it though (except that I've seen it twice; once in the emulator and just yet in the doc I'm reading; log tomorrow).

**Comment by Eduardomb22** [comment]
@poire-z . Did u fix this problem? I was getting 50-60% processor usage with Kindle and now at 1267 I´m getting the normal usage, like 2%.

**Comment by Frenzie** [comment]
@Eduardomb22 The problem is hopefully fixed in v2015.11-1267-g7da2998.

@poire-z Okay, here's the error. I'm not quite sure yet what's happening.
```
09/30/17-23:20:58 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
[!] doShowReader coroutine crashed:
frontend/apps/reader/modules/readertoc.lua:171: attempt to compare nil with number
stack traceback:
	frontend/apps/reader/modules/readertoc.lua:217: in function 'getChapterPagesLeft'
	frontend/apps/reader/modules/readerfooter.lua:70: in function 'gen'
	frontend/apps/reader/modules/readerfooter.lua:467: in function 'genFooterText'
	frontend/apps/reader/modules/readerfooter.lua:542: in function 'updateFooterText'
	frontend/apps/reader/modules/readerfooter.lua:532: in function 'updateFooterPos'
	frontend/apps/reader/modules/readerfooter.lua:574: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
	frontend/apps/reader/modules/readerrolling.lua:552: in function '_gotoPos'
	frontend/apps/reader/modules/readerrolling.lua:568: in function '_gotoXPointer'
	frontend/apps/reader/modules/readerrolling.lua:107: in function 'setupXpointer'
	frontend/apps/reader/modules/readerrolling.lua:168: in function 'v'
	frontend/apps/reader/readerui.lua:360: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/reader/readerui.lua:439: in function 'doShowReader'
	frontend/apps/reader/readerui.lua:399: in function <frontend/apps/reader/readerui.lua:398>09/30/17-23:21:02 INFO  quitting uimanager
09/30/17-23:21:02 INFO  no dialog left to show
```

**Comment by poire-z** [comment]
Good to know it's somehow fixed in 1267, but I don't understand what really happened, and how this has been fixed :) I see nothing really related to fixing a cpu or memory stuff in https://github.com/koreader/koreader/compare/4713926...7da2998 ...

@Frenzie : you said above it was related to font hinting. Is it still ? with the order in the error msg, pageno was nil

**Comment by Frenzie** [comment]
@poire-z No, I'm pretty sure that was a red herring, sorry about that. It's just that I played around with it because you mentioned it somewhere.

**Comment by Frenzie** [comment]
Okay, so I'm not really into EPUBs so I'm less likely to notice problems there, but it seems like any of the currently Humble Bundle EPUBs crash for me on reopening after you exit them. I'll check if it's the same on any random EPUB (e.g., from Gutenberg or DBNL) that's freely available.

**Comment by Frenzie** [comment]
@poire-z Yes, it happens for me on any random book. I figured out the problem: it's scroll mode. I think I enabled it on EPUB by default for testing a few months ago.

**Comment by poire-z** [comment]
Regarding time taken by crengine to open big books:
I timed things with one 3000 pages brazilian law book (thanks Eduardomb22) which happens to have a huge TOC, and, on my emulator, the loading time is mostly spent in the following calls:
- credocument:loadDocument() takes 2 seconds with or without cr3cache existing
- credocument:renderDocument() takes 4 seconds with or without cr3cache existing
- ReaderFooter:onReaderReady() takes 0 seconds if "Show chapter markers" is disabled, and if enabled:
    - 11 seconds if cr3cache existed
    - 6 seconds if no existing cr3cache
- ReaderFooter:onPageUpdate() takes 0 seconds if "Pages left in chapter" is disabled, and if enabled:
    - 11 seconds if cr3cache existed
    - 6 seconds if no existing cr3cache
- If both "Show chapter markers" and "Pages left in chapter" are enabled, and if cr3cache exists, they take 22 seconds.

So, if we were to improve loading, we better work on the TOC stuff (which is lua, but also involves calls to crengine, dunno which take more time).
And we could just simply remove the cr3cache when leaving a document, just like it was done for coverbrowser above. Does this cr3cache helps in other situations?
@frankyifei and @Hzj-jie : do you have "Show chapter markers" or "Pages left in chapter" enabled for footer? And does things feel quicker for you too, and memory usage reduced, if you disable these (and delete readers' cache) ?

**Comment by poire-z** [comment]
Turned out the 11 seconds (or 6 when no existing cr3cache) is the time taken by crengine when `doc->text_view->getToc()` is called. But the multiple calls can at least be avoided.

**Comment by frankyifei** [comment]
Agree, book opening is very slow when TOC is large.  can we optimize it? I remember Xpath code is involved here and its implemention is very slow.

**Comment by poire-z** [comment]
Some more tests results:

(I had made some modifications (lua side only) to have a "volatile cache", thinking that a cache is needed to not use too much memory when loading, but it's bad when re-opening a document (as noticed 2 posts above, for books with big TOC), so better delete that cache when closing. Then tried it with some other kind documents, and it's worse...)

Results with a 7Mb books of 10 000 pages with only a few dozens TOC entries on my emulator:

step | if no cache yet | with previously made cache
---- | ---------------- | --------------------------
loaddocument | 25 seconds | 3 seconds (a)
render | 25 seconds | 25 seconds
toc extraction | 20 seconds | 20 seconds 
document closing | 20 seconds (b) | 0 seconds

(a): because cache is used (b): because the cache is written

(I also thought I would correct a bug there by using a proper `document:close()` that would call some kind of crengine:close() :
https://github.com/koreader/koreader/blob/34ad91c3f0baa2ca21bf6add35c1ce6bb0297bbe/plugins/coverbrowser.koplugin/bookinfomanager.lua#L444
but that makes crengine create the cache and take an additional 20 seconds, so better stay with a unproper close for faster metadata & cover extraction).

**Comment by Hzj-jie** [comment]
@poire-z yes, I have chapter marker enabled on my devices.

**Comment by Hzj-jie** [comment]
The issue still happens in latest version (1314).
By observing the output of top command, the processor usage increases to 100% when popping up menu or turning pages, but not when turning on / off frontlight by tapping bottom-left corner.

**Comment by Hzj-jie** [comment]
I have also tested the behavior on Kobo. It also uses more processor resource with recent builds, though the lag is not as significant as Kindle. Maybe Kindle has a weaker processor or luajit has a worse performance on Kindle or the stock software uses more processor resource (the mysterious fsp process).

**Comment by poire-z** [comment]
> processor usage increases to 100% when popping up menu 

At first opening, there is now icons rescaling with mupdf. Do you observe it also on next openings ?
Could you activate debug logs, and try to observe a delay in log line timestamps, so we can know between which steps this excessive cpu usage happen?
Is it still related to having a big book, or a book with a big TOC, or does it happen even with small ones?

**Comment by poire-z** [comment]
Also, just to know if it's similar to #3308 or not, if you have Reading stats enabled, try turning them off and restarting.

**Comment by Hzj-jie** [comment]
No, the delay happens every time I open the menu. And yes, it happens when a very large epub is opened.
I disabled the reading statistics, nothing changes.

I made a mistake before, the lag happens when I turn on / off the front light.

**Comment by Hzj-jie** [comment]
Removing the sidecar file resolves the issue. I believe I have a very large sidecar (~500K). But it does not look like a simple problem.

**Comment by poire-z** [comment]
I can't tell about bookmarks, as I have no book with more than 3 bookmarks :)

But, regarding some of the other things mentionned in this issue and what I can notice:
On the emulator, opening a 10,000 pages book (7.5 MB), with 0 bookmark and < 100 TOC entries, takes 60 seconds (with existing cache = opening once, and measuring second opening). Then changing page or **opening the menus** take 1 to 2 second (meaning it's long and a bad user experience).
(The delay in menu opening is caused by ReaderView asking crengine to draw the small text part visible between the 2 menus - it is indeed crengine that is responsible for this delay).

I have checked with various checkouts of crengine (and stuff commented out in base/cre.cpp) at different points in time along the last 6 months, and I always get the same 60 seconds opening time, and 1-2 second menu opening delays,:
https://github.com/koreader/crengine/commit/f5cf8fa132e2dfd2cf2bc62f25ab01969b7a8a70 (the one just before https://github.com/koreader/koreader/commit/2c1e7f2a4f2201e0fecfadda207ca34fcaafe2f7)
https://github.com/koreader/crengine/commit/d0854294e0a9259d9c160b5fe9c91a123a63528b
https://github.com/koreader/crengine/commit/727a0d2f8ca8eb7d08b7e926252155edbbe53ebc

So, I guess the performance of crengine has been bad on big books for a long time, but it has not noticably got worse (nor better) over the last months.

Do you really notice a sensible change betore and after https://github.com/koreader/koreader/commit/2c1e7f2a4f2201e0fecfadda207ca34fcaafe2f7 ? Could you check with a build before june 25th ? (Some changes introduced June 26th, with side effects noticed over the summer, were mostly reverted by https://github.com/koreader/koreader/commit/2c1e7f2a4f2201e0fecfadda207ca34fcaafe2f7)

**Comment by Hzj-jie** [comment]
Yes, I won't say the performance of the version before 2c1e7f2 is great, but at least it's much faster when 200+ bookmarks are added.

**Comment by KenMaltby** [comment]
I don't know about Kindles, but with Kobos, the "Bookmarks" are not just dogeared pages, they also include highlighted text.  Perhaps several paragraphs of text.  If you are adding hundreds to the .sdr of a book, there might be an impact on performance, if reading somehow triggers some interaction involving the whole .sdr.  (Perhaps a delusion, but I sorta remember some talk of a process where the file is "cloned" and updated then overwrites the original.)

**Comment by Frenzie** [comment]
> (Perhaps a delusion, but I sorta remember some talk of a process where the file is "cloned" and updated then overwrites the original.)

That's only on saving.

**Comment by poire-z** [comment]
Can you check how it does with next nightly (>=1419) (in case the bookmarks mentionned in this issue were actually highlights) ?
There was an obvious slow down with long highlights, as seen on #3503 and hopefully fixed in #3508 .

**Comment by poire-z** [comment]
@Hzj-jie @Eduardomb22 : has #3508 had any good effect on your books-with-many-bookmarks loading time?

**Comment by poire-z** [comment]
Did some poor man's profiling (with google-pprof) of that big book loading time, and noticed there were a lot of time spent in some zlib stuff (inflate/deflate).
Tried changing https://github.com/koreader/crengine/blob/a3eeb1bf2663506fa84c38470aca6fa66d9636df/crengine/src/lvtinydom.cpp#L21-L22
```c
/// data compression level (0=no compression, 1=fast compressions, 3=normal compression)
#define DOC_DATA_COMPRESSION_LEVEL 1 // 0, 1, 3 (0=no compression)
```

With that big book with a small TOC on the emulator:

COMP_LEVEL | cache before | load time | render time | resulting cache size
---- | ---------------- | -------------------------- | ---------------- | ----------------
1 | no cache yet | 20 seconds | 37 seconds | 20 Mb
1 | existing cache | 3 seconds | 50 seconds | 20 Mb
0 | no cache yet | 18 seconds | 16 seconds | 60 Mb
0 | existing cache | 3 seconds | 19 seconds | 60 Mb

I guess crengine does a lot of small picks in the cache: read, decompress, use, trash.
Not using compression gives a x2-2.5 boost, but uses more disk space / IO read & writes, which may have some noticable delay on devices with SDcards, when 60 Mb need to be read instead of 20 (although the content will be cached by the OS into RAM, so it will only happen at startup). I noticed (not measurable) that page turns may be a bit faster too.
(On a device, that same book loading time would probably go from 5mn to 2mn... which is still too much).
Also, the increase in cache size would trash other books's caches more quickly.

Should we use `#define DOC_DATA_COMPRESSION_LEVEL 0` ?
(As noticed above, we can't just use no cache at all, as then, it would need too much memory.)
(Tried tweaking some other values in the top of lvtinydoc.cpp, with no read noticable effect.)

**Comment by Eduardomb22** [comment]
@poire-z At the moment, I have a book with 31 bookmarks and it is ok, can´t see any performance drop, but I don´t if 31 is able to cause some drop. I can´t compare the performance before your update because I wasn´t using bookmarks at the time.

**Comment by frankyifei** [comment]
guess changing deflate to a better algorithm will help, maybe lz4?

**Comment by poire-z** [comment]
@Eduardomb22 : with ur comment from oct 1: _Did u fix this problem? I was getting 50-60% processor usage with Kindle and now at 1267 I´m getting the normal usage, like 2%._ , and the fact that there was no real obvious code change that could have solved that - and others' comments - I was thinking it's more about specific books (large TOC, big nb of pages), or specific usage (many bookmarks/highlights), that this cpu peaks may happen.
And as I know you have quite big books, thought you would be more likely to experience again these 50-60% cpu usage if they should happen again (meaning #3508 is not enough). (Dunno if you still have some books you read previously with more bookmarks, that you remember were slow, if you could browse them again, to get a feeling if it feels really smoother or not).

@frankyifei : dunno much about compression algorithms and the gain in speed with other ones (crengine is already using "fast" zlib mode) - and dunno if the way crengine uses it (lots of small read/uncompress, if i get that right) has been benchmarked (guess benchmarks are mostly made with big continuous streams). It may be a lot of work to update crengine code to test it, so don't know if it's really worth it (when there's the quick solution to just disable it :).

**Comment by Hzj-jie** [comment]
Won't reproduce on 1750. Close for now.
