### ISSUE TITLE
Pdf: switch default zoom mode gives broken page

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3330]
* KOReader version: v2015.11-1287-g5a2c8e4
* Device: Kobo Aura One

#### Issue
Same problem as described in this thread (but with an addition): 
https://github.com/koreader/koreader/issues/3015

#### Steps to reproduce
1. Open an unopened pdf.
2. Change to bookmark browsing mode.
3. Switch default zoom mode by long press either "Zoom to fit content width", "Zoom to fit content height" or "Zoom to fit content".
4. Go back to file manager and purge the pdf.
5. Open same pdf again (or another unopened pdf).

**Comment by Frenzie** [comment]
Sounds like a cache problem. It should be fixable by file browser → tools → developer options → clear reader's caches. Could you confirm that works around the problem?

If so, we should programmatically clear the cache somewhere down the line

**Comment by gerhaher** [comment]
No, the problem is still there.

**Comment by Frenzie** [comment]
I'm afraid I still can't manage to reproduce this. (With or without that odd bookmark browsing mode step.)

**Comment by gerhaher** [comment]
And you haven´t forgot to set reflow to default?

But what is odd? If you want to change the default zoom mode, isn't that how you do it? 
By the way, setting the default zoom mode doesn't work either, it goes back to "Zoom to fit page" all the time.

**Comment by Frenzie** [comment]
I followed the steps you provided. Where does reflow go in the list?

**Comment by gerhaher** [comment]
Sorry, I wasn't clear enough.

I refered to this issue: https://github.com/koreader/koreader/issues/3015

So the first step is to set reflow to default.
And then come the steps I provided. That's why I called this an "addition".

I have also removed the settings.reader.lua file, so I should have no odd settings.

**Comment by Frenzie** [comment]
Oh, I see. The easiest way to trigger this is:

1. Reflow on by default.
2. Zoom mode content width/height default (through other file or a hack like flip mode; steps 1 and 2 can be switched).
3. Close, purge .sdr and reopen or open another document.

It looks to me like what happens is that both zoom mode and reflow are applied, so that zoom mode applies to the regular content width rather than the reflowed content width. Normally reflow turns zoom mode to something custom.

With any luck it should be easy to fix, but I don't have time atm. :-)

**Comment by Frenzie** [comment]
Btw, there might be some relation to e1b3c93.

**Comment by poire-z** [comment]
Haven't checked, but might be out of date. Please re-open if it still happens.
