### ISSUE TITLE
The display is blank until clicked

### ISSUE THREAD

**Issue by marmistrz** [koreader/koreader#3355]
* KOReader version: koreader-nightly-20171004
* Device: InkBook Classic 2 (Android)

#### Issue
The display is blank until clicked, straightaway after launching the app
#### Steps to reproduce
1. Open Koreader. 
2. See the blank screen.
3. Click anywhere

**Comment by Frenzie** [comment]
I'll close this because it shouldn't be an issue in the latest nightlies. You can grab today's here: http://build.koreader.rocks/download/nightly/v2015.11-1339-gb4bb322/koreader-android-arm-linux-androideabi-v2015.11-1339-gb4bb322.apk

The actual problem still exists to some extent but it shouldn't on startup.

**Comment by Frenzie** [comment]
Oh btw I'll be on Gitter for a bit if you want any help with that DjVu thing. Combined with #3353 (`ANDROID_ARCH=x86 ./kodev run android`) you can also easily test in an Android x86 emulator.
