### ISSUE TITLE
Create output directory for Koreader release files

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3444]
* KOReader version: git
* Device: pc

#### Issue
Too many koreader release files in koreader parent directory - creates mess. 
Koreader release packages should be placed to separate folder e.g.  <koreader_parent_dir>/`output`, `release` etc

After some clean up:
> $ ls
base
COPYING
data
datastorage.lua
defaults.lua
doc
front
frontend
kodev
koreader-android-arm-linux-androideabi
koreader-android-arm-linux-androideabi-debug
koreader-android-arm-linux-androideabi-v2015.11-1367-g9861ed2.targz
koreader-android-arm-linux-androideabi-v2015.11-1368-g02a0415.targz
koreader-android-arm-linux-androideabi-v2015.11-1369-g89fdf84.apk
koreader-android-arm-linux-androideabi-v2015.11-1369-g89fdf84.targz
koreader-android-arm-linux-androideabi-v2015.11-1370-g5ee6c01.targz
koreader-android-arm-linux-androideabi-v2015.11-1376-ge8aeb3c.targz
koreader-android-arm-linux-androideabi-v2015.11-1381-g97aee14.apk
koreader-android-arm-linux-androideabi-v2015.11-1381-g97aee14.targz
koreader-android-arm-linux-androideabi-v2015.11-1382-gb24ff86.apk
koreader-android-arm-linux-androideabi-v2015.11-1382-gb24ff86.targz
koreader-android-arm-linux-androideabi-v2015.11-1388-gb1c9027.apk
koreader-android-arm-linux-androideabi-v2015.11-1388-gb1c9027.targz
koreader-android-arm-linux-androideabi-v2015.11-1390-g0d64806.apk
koreader-android-arm-linux-androideabi-v2015.11-1390-g0d64806.targz
koreader-android-i686-linux-android
koreader-android-i686-linux-android-v2015.11-1369-g89fdf84.apk
koreader-android-i686-linux-android-v2015.11-1369-g89fdf84.targz
koreader-android-i686-linux-android-v2015.11-1370-g5ee6c01.targz
koreader-emulator-x86_64-linux-gnu
koreader-emulator-x86_64-linux-gnu-debug~
l10n
Makefile
platform
plugins
reader.lua
README.md
resources
setupkoenv.lua
spec
test
tools

#### Steps to reproduce
Develop build Koreader release packages couple time, day by day.

**Comment by Frenzie** [comment]
Seems pretty much like a distinction without a difference to me?

**Comment by KenMaltby** [comment]
As you are talking about files on your PC, the files you decide to keep and how they are organized,  are purely a personal choice.  (I have most all the Kobo version releases from "koreader-v2013.03-207-gd7df349.zip" to the present. Around 400 release packages. )  There must have been some reason they make terabyte storage devices now a days.

**Comment by mwoz123** [comment]
Yes, but wouldn't it be better if by default packages have been created in separate dir than mixed with other files in parent dir? 

This separate dir for output files seems to be a common practice...

**Comment by Frenzie** [comment]
Perhaps, but other than "oh look, another GB" it doesn't bother me. And for that it really makes no difference what folder it's in. Something like `./kodev release --purge` might be worth adding for that purpose but that's a separate issue.

Something like this (from the koreader.rocks server):
```bash
#!/bin/bash
# Script to purge all nightly artifacts that's older than 30 days

DIR="`pwd`/download/nightly `pwd`/ota"

echo "=== Disk usage before purge:"
df -h

echo "=== List of directories to purge":
echo "=== End of list"
find ${DIR} -maxdepth 1 -ctime +30 -exec ls -lh {} \;

read -p "[*] Press enter to purge with above list. Ctrl-C to cancel."

sudo find ${DIR} -maxdepth 1 -ctime +30 -exec rm -rf {} \;

echo "=== Disk usage after purge:"
df -h
```

> This separate dir for output files seems to be a common practice...

This can't be changed because it would break all nightly build servers except koreader.rocks. Well, of course it'd break that one too, but I can update the GitLab nightly build. (I don't particularly want to but it should be only a few lines.)

If that weren't in the way then you could submit a PR that ensured, `build` or `release` existed, and replaced the 8 or so relevant lines like this:

https://github.com/koreader/koreader/blob/369cf4f102bfdd691a696bf149a89f0e4c43ead2/Makefile#L177

with `../release/kobo-etc`

So I've tagged this wontfix on account of the nightly build servers. We could, however, discuss what a possible `release` subdirectory would look like (i.e., is `release` the right name, etc.) using examples.

To return to the "common practice". It seems to me that source-dir builds are common practice, but a bad one. Besides the unfortunate exception of luajit in android-luajit-launcher, we *build* everything in separate arch build directories. But these release files are already clearly differentiated in name, so there is certainly no fundamental flaw in the sense which I presume you're talking about.

**Comment by KenMaltby** [comment]
As to the servers, having a way for users to find earlier releases, not only makes it easier for the users with marginal devices find a version that works with their device, but it helps if they can identify the last version that works for them, when a problem occurs.  Limiting it to 30 days worth might be counterproductive.

**Comment by Frenzie** [comment]
It's not limited on purpose. I mean it is, but it's a simple matter of available disk space.

I didn't store the before purging values, but suffice it to say that it was about to be full again. ;-)
```
/dev/sda1        29G   18G   12G  61% /
```

There are the releases on GitHub and if you look hard enough on GitLab you'll be able to find pretty much every nightly build ever by putting the right commit hash from [here](https://gitlab.com/koreader/nightly-builds/commits/master) into this url.

Recent:
https://gitlab.com/koreader/nightly-builds/commit/dbc5ddc383879944b517ffc3bb5de4e07210895d/pipelines

Half a year up to last week:
https://gitlab.com/koreader/nightly-builds/commit/9cc1fec7d9bfbf928c950f422ad3cd365590e140/pipelines

A year ago:
https://gitlab.com/koreader/nightly-builds/commit/4ffba6c0cb8bace9b7fccf346e71f6772e9efe24/pipelines

**Comment by mwoz123** [comment]
My initial thought was to make it better organized. 
The bash "screenshot" was just to better clarify how it can became a mess.  

Is not a big deal for me but thought that can be one of those small good improvements. 

If you don't want it that's ok,and can be closed.

**Comment by Frenzie** [comment]
Alright, I'll close it then. It'd break the nightly builds out of my control.
