### ISSUE TITLE
Extend quickstart guide, add gesture info

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3484]
* KOReader version: all
* Device: all

#### Issue
Gestures are undocumented. I discovered there's a gesture for light control when I was trying to change font size . How many more that users are not aware?

Maybe we should also add something more to guide?

**Comment by Frenzie** [comment]
There might be undocumented gestures (Kobos don't do multi-touch; blame the Kindle people) but gestures are certainly not undocumented.

https://github.com/koreader/koreader/wiki/KOReader-Gestures

**Comment by AlanSP1** [comment]
I agree that gestures are documented, but it may be useful for people who don't go to wiki to include basic info about them in quick start guide. I would also include basic info about changing gesture zones.

It would make quick start guide even more useful, even if it don't get read that much, as we know it from people who couldn't find out info on swipe menu access gesture.

**Comment by cramoisi** [comment]
I sometimes increase the font size within koreader by accident with a gesture i can't figure out (and not mentioned in your link). Any Idea of it ?

**Comment by Frenzie** [comment]
@robert00s added a pinch gesture for that I believe.

**Comment by ersi-dnd** [comment]
On Pocketbook devices, sliding two fingers up/down seems to interact with the frontlight. It would be nice to get a confirmation from whoever implemented it and have it documented also.

**Comment by chrox** [comment]
From [the very beginning](https://github.com/koreader/koreader/commit/ed33937af2b71624c55ae518b3e8bc21a3a0494a#diff-4253aad425f1ae54fb0e9fe767a523d3) of the frontlight module it provided the function of two fingers panning to control the frontlight but it was only for Kindle devices and that's why it was not documented in the wiki page. Since now it seems Android and Pocketbook devices also have this function we could update the [KOReader Gestures wiki page](https://github.com/koreader/koreader/wiki/KOReader-Gestures).

**Comment by Frenzie** [comment]
Closing since @chrox added this to the wiki.
