### ISSUE TITLE
Koreader Dictionary lookup is slow on android

### ISSUE THREAD

**Issue by cmoig** [koreader/koreader#3496]
hi ,
i own both a kindle voyage and a samsung galaxy tab s
i have noticed that looking up in dictionary much more slow on my android tablet than on my kindle .

(I love Koreader , and thank you for the hard work )

**Comment by Frenzie** [comment]
Could you be using an older version on Kindle? Newer sdcv is slower due to synonyms; exactly what to do about that is still an open issue upstream at https://github.com/Dushistov/sdcv/issues/31

**Comment by theojesed** [comment]
I am having the same problem [Kindle PW2 (locking) and Android (slow)], I really liked the new version of KOReader, but I use the dictionary a lot, what is the latest version in which it works normally for Android and Kindle?

**Comment by Frenzie** [comment]
Pinging @poire-z and @ecraven because I'm not terribly affected by this. Anyhow, any build from before October '17 will have old sdcv.

**Comment by poire-z** [comment]
I don't really read on my android, I just test things. I only have two dicts, and on a recent phone with good cpu, it's fast enough.
But on Kobo, I still use our old sdcv 0.4, which is indeed faster than upstream 0.5.2, with 8 dictionaries.

I don't remember if our 0.4 build worked on newest kobo firmware (unlike our 0.5.2 builds). If they did, I would have no problem if we got back to building our 0.4 (but I know you would :)

**Comment by Frenzie** [comment]
> I don't remember if our 0.4 build worked on newest kobo firmware (unlike our 0.5.2 builds).

It does and doesn't under the same conditions, but iirc 0.4 doesn't build on Ubuntu 17.10 and newer (that is, newer compilers and/or libs).

> If they did, I would have no problem if we got back to building our 0.4 (but I know you would :)

I'd rather patch out https://github.com/Dushistov/sdcv/pull/20 (piece of cake for now) if it's really that big of a deal. Or figure out why it's an order of magnitude slower. And anyway, our patches were slightly reworked by @ecraven and finally integrated upstream. I wouldn't want to disrespect all of that hard work. ;-)

That being said, I will admit to finding CMake annoying (e.g., a small but typical example [here](https://github.com/Dushistov/sdcv/issues/39#issuecomment-345404759)). I think I twice literally had to look at the source to solve what seemed like incredibly basic problems that shouldn't be problems in the first place. It's unpredictable. Cross compiling is awful. Not a fan.

Autotools is also somewhat difficult, so in that sense it may not be much better than CMake. Moreover, it [doesn't play very nice with Windows](https://autotools.io/libtool/windows.html). But Autotools is consistent and predictable and it cross-compiles well.

[Meson](http://mesonbuild.com/) takes the basic idea that I presume to be behind CMake but actually does it. Instead of fighting against CMake or being confused by esoteric Autotools stuff you'll likely never need you can actually get things done a million times more efficiently. Just look at [lovely stuff like this](http://mesonbuild.com/Wrap-dependency-system-manual.html).

Feel free to disagree, of course. I know plenty of people must disagree about CMake or it wouldn't be so widely used. ;-)

**Comment by theojesed** [comment]
Sorry for my ignorance, but is there any way to use the new updates with the old dictionary?

**Comment by Frenzie** [comment]
On Kindle you should be able to toss in any sdcv executable you like. On Android that's not quite an option although it might be possible through adb.

(You can run commands through adb as the KOReader app, so you'd probably be able to replace the sdcv executable with another one at will. Suffice it to say that it's not straightforward.)

**Comment by theojesed** [comment]
Not sure if I got it right how toss in an sdvc executable, but I'll try. Thank you very much.

**Comment by Frenzie** [comment]
Today I saw these notes on taming CMake a little:

http://perezmeyer.blogspot.com/2018/11/cross-compiling-cmake-based-projects.html

(Unfortunately nothing I didn't already know by now. :-P)

**Comment by NiLuJe** [comment]
[Yup!](http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Misc/CMakeCross.txt) ;).

**Comment by rtega** [comment]
It looks like sdcv has finally resolved this issue. Will it be merged in koreader?

**Comment by Frenzie** [comment]
Yes, I'll bump it soon unless someone else does it before I get to it. Please feel free to submit a bump PR (but if you can't test it locally it's probably better to just wait a few days — or set up a build environment! ;-) ).

**Comment by rtega** [comment]
I'll just patiently wait. Thanks!
