### ISSUE TITLE
KOreader slowing down as i added highlights

### ISSUE THREAD

**Issue by abdoulayeYATERA** [koreader/koreader#3503]
* KOReader version:
v2015.11-1412-g819212f (this issue didn't apprear with this version)
* Device:
Kobo Aura one
#### Issue
As put highlights in my book, the device goes slower and slower.
The device is slow only when the book is opened.
I have to purge the ".sdr" to get the device back at normal speed.
#### Steps to reproduce
Add highlights
#### Data
This is an example (it's a free book from wikisource) and the sdr file.
[data.zip](https://github.com/koreader/koreader/files/1485844/data.zip)

You'r doing a great work.
Thank's for your help.

**Comment by Frenzie** [comment]
Could be the same as #3261?

**Comment by abdoulayeYATERA** [comment]
probably! I can confirm that in my case the highlights are the cause (i rarely use bookmarks). I just modified the sdr file and delete only the highlights part, the speed is ok after that ...

**Comment by poire-z** [comment]
Thanks for providing the book and its sdr.
It's noticable on the emulator, and most of the time is spent in:
https://github.com/koreader/koreader/blob/b37ae2d681c49c21c0dfa5a1913258a948f9c002/frontend/apps/reader/modules/readerhighlight.lua#L191 
https://github.com/koreader/koreader/blob/b37ae2d681c49c21c0dfa5a1913258a948f9c002/frontend/apps/reader/modules/readerview.lua#L475
(800ms each, so, > 4 times this on a device I guess)
mostly because for credocuments, ALL the hightlights are checked and getScreenBoxesFromPositions(pos0, pos1) is called for each of them.
This can be avoided by first checking if getPageFromXPointer(pos0) or getPageFromXPointer(pos1) happens to be on current page, before calling getScreenBoxesFromPositions(() if it is.
I'll push something tomorrow.

**Comment by poire-z** [comment]
@abdoulayeYATERA : can you please tell us if there's a sensible improvement on your device with next nightly (>=1419) ?

**Comment by abdoulayeYATERA** [comment]
Hello, tested with the same device, book and sdr files. It's ok!! Thank's for the fix.
