### ISSUE TITLE
Wish: Enter Go to page from Skim mode dialog

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#3526]
Thank you for this latest release (koreader-nightly-20171023). I haven't installed it yet on all my devices, but on the one I have it looks awesome.

There is this minor issue: Skim mode dialog reads "Go to page" as its title. I think it should say "Skim mode" instead.

And I have a wish: In the Go to page dialog, we have the button "Skim mode" which enters Skim mode. How about adding a Go to page button in the Skim mode dialog?

**Comment by robert00s** [comment]
> And I have a wish: In the Go to page dialog, we have the button "Skim mode" which enters Skim mode. How about adding a Go to page button in the Skim mode dialog?

Try to tap in page number to go back from "Skim mode" to "Go to page"

**Comment by ersi-dnd** [comment]
@robert00s 
Wow, it works! But shouldn't the page number in the Skim dialog look like a button, just like everything else around it? This way it would occur to people to press it.

**Comment by ersi-dnd** [comment]
Looking at the Go to page and Skim mode dialogs, looks like Skim mode dialog is meant to be an extension to the Go to page dialog: In Go to page dialog, press Skim mode, and you can do as if more stuff, that's why the "Go to page" title stays there. 

I have this suggestion: Make Skim mode an actual expansion of the Go to page dialog, i.e. retain the full Go to page dialog when Skim mode opens. When the user presses Skim mode, then instead of switching away from Go to page dialog, make Go to page dialog expand to include the Skim mode controls.

This leaves us with the keyboard detail: When Skim mode dialog opens, the keyboard vanishes (probably because the Skim mode dialog is so big). My idea is this: The new expanded dialog includes the Go to page form. When the user places the focus there, the Skim mode controls should vanish and the keyboard reappear.

(All this is unnecessary, really, only cosmetics. As it is, all the functions are there, I just found it confusing that the Skim mode is titled Go to page.)

**Comment by robert00s** [comment]
> I have this suggestion: Make Skim mode an actual expansion of the Go to page dialog, i.e. retain the full Go to page dialog when Skim mode opens. When the user presses Skim mode, then instead of switching away from Go to page dialog, make Go to page dialog expand to include the Skim mode controls.

Let's leave as it is :)
After your suggestion Go to page/Skim mode widget will we too big.

>  I just found it confusing that the Skim mode is titled Go to page.)

I'll prepare PR for this soon.

Note that skim mode is the default mode when long press on status bar for serveral weeks.

**Comment by ersi-dnd** [comment]
@robert00s 
> After your suggestion Go to page/Skim mode widget will we too big.
Yes, could be. Another thing that most definitely is too big is Table of Contents. Mostly that thing is entirely empty, and to get out of it there is a too tiny cross in the corner. I'd like the Table of Contents dialog to be small (particularly when it's empty, or, even better, not show up at all when there is nothing to show) so I can hit anywhere around it to get rid of it, just like with Go to page dialog. And there could be a shortcut button to Bookmarks somewhere in the Table of Contents dialog, just like you can get back and forth between Go to and Skim to dialogs.

I see that you merged something related to this issue. I updated Koreader now, but the skim dialog still reads Go to page on top. Did I update too fast?

**Comment by poire-z** [comment]
> Did I update too fast?

Yes, not yet merged, still discussed in #4223.

> Another thing that most definitely is too big is Table of Contents

(Well, if you see that many empty ToC, why are you hitting this menu that often? :) already requested in #3997)
It shouldn't be smaller when there is ToC content. I don't mind having it empty when no ToC, but I may not mind either if there was an InfoMessage instead. But it should show something, just for feedback, so you don't go thinking your gesture didn't work and try it again.

I discovered a few weeks ago that, for people with multitouch devices that use the 2-finger swipe to show ToC or Bookmarks, that you can close it with that same 2-finger swipe in the other direction.

But I ended it up adding for myself _Swipe south_ to close these (because I was too often missing that little cross in the corner - but I don't think we should add a big fat button to this view, that I'd rather like clean of distractions).
Small patch, that makes it work with Toc, Bookmarks and History (but not with FileBrowser thanks to the conditions - so no conflict with _Swipe to show menu_):
```diff
--- orig_koreader/frontend/ui/widget/menu.lua
+++ koreader/frontend/ui/widget/menu.lua
 function Menu:onSwipe(arg, ges_ev)
     if ges_ev.direction == "west" then
         self:onNextPage()
     elseif ges_ev.direction == "east" then
         self:onPrevPage()
+    -- easier closing (than tap on button at top right)
+    elseif ges_ev.direction == "south" and self.has_close_button and not self.no_title then
+        self:onClose()
     else
         -- trigger full refresh
         UIManager:setDirty(nil, "full")
--- orig_koreader/plugins/coverbrowser.koplugin/covermenu.lua
+++ koreader/plugins/coverbrowser.koplugin/covermenu.lua
 function CoverMenu:onSwipe(arg, ges_ev)
     if ges_ev.direction == "west" then
         self:onNextPage()
     elseif ges_ev.direction == "east" then
         self:onPrevPage()
+    -- easier closing (than tap on button at top right)
+    elseif ges_ev.direction == "south" and self.has_close_button and not self.no_title then
+        self:onClose()
     elseif ges_ev.direction ~= "north" and ges_ev.direction ~= "south" then
         -- but not if north/south, and we're triggering menu
         -- trigger full refresh
```
Should I PR that?

**Comment by ersi-dnd** [comment]
@poire-z 
> (Well, if you see that many empty ToC, why are you hitting this menu that often? :) 

By mistake. The usual scenario is, when a book is open, I bring up the menus and the first menu with Table of contents on top is auto-expanded, I want to go to the top-right corner to the ☰ menu but it hits the Table of contents instead. So the next question in that situation is how to get rid of the Table of contents, but it's not easy to get rid of it.

> Should I PR that?

What does this mean? I don't know what PR means.

I am slowly beginning to understand that you have some configuration options available for swipes. I would like to set them for the things I use most, such as switching nightmode on and off, getting in and out of bookmarks and history, etc. Are there instructions for this somewhere?

**Comment by poire-z** [comment]
> I don't know what PR means.

_Pull Request_. I was asking the other developers if I should push this change (that I made for myself) to the main code, so that everybody gets _Swipe south_ to close TOC, Bookmarks, History.

> I am slowly beginning to understand that you have some configuration options available for swipes

No, we don't have that. There's no way to change behaviour of gestures, except what is available thru menu that allows disabling them (opening menu, following links, getting back from links).

> By mistake [...] I want to go to the top-right corner to the ☰ menu but it hits the Table of contents instead

But at this point, your finger is around the top right corner, near the `x` close button, so should be quite fast to close :)

**Comment by Frenzie** [comment]
Is there a rationale behind it?

**Comment by poire-z** [comment]
If _it_ = _Swipe south_ , not much but:
- for non full screen dialogs, I most often use Tap outside to close than the `x` button
- on full screen dialogs, you can't Tap outside, so Swipe is the next easiest gesture
- swipe left and right are used in these menus to change page - south and north are not
- swipe _south_ brings _down_ the window
- swipe south reminds me of the swipe from top of screen to bottom to close a full-screen app in Windows 8 & 10 in tablet mode (dunno if there's something similar in Android)

And it feels quite natural since I've been using it.

**Comment by Frenzie** [comment]
> swipe left and right are used in these menus to change page - south and north are not

Up and down feel like basically the same thing though.

**Comment by ersi-dnd** [comment]
@poire-z 
> But at this point, your finger is around the top right corner, near the x close button, so should be quite fast to close :)

One would assume so, but it does not work in reality. Just like it keeps hitting the TOC when I am aiming at ☰ , it also misses the x. Consistently so. At the same time, the Cancel or Dismiss buttons around the Go to page or other dialogs always react as expected, which is why I would like more buttons like this.

**Comment by ersi-dnd** [comment]
> No, we don't have that. There's no way to change behaviour of gestures

In the latest git update I see that this has changed. Under Cogwheel > Device we now have Gesture manager and I can set a tap in corner to toggle night mode. It looks like something that would perhaps better be placed into Plugins menu, where the Frontlight gesture controller resides. 

Besides, it would be nice if Frontlight gesture controller would, in addition to just toggling the light on-off, optionally open up the frontlight dialog. Just a setting to switch the gesture action between the toggle and the dialog.

Thank you for your great work!

**Comment by poire-z** [comment]
@ersi-dnd : has the `swipe down to close TOC` helped getting out of it more easily?
Can #3997 be closed?

**Comment by ersi-dnd** [comment]
And can the same or similar be implemented in history list?

**Comment by poire-z** [comment]
That should already work.
In #4237:
> Mostly all that have a close button at top right, that may be hard to reach or hit for some people:
> TOC, Bookmarks, History, KeyValuePage (Book information, Statistics...), Book status...

**Comment by Frenzie** [comment]
@ersi-dnd I'll close this issue now since it looks resolved. Please feel free to reopen this one or to start a new issue.

**Comment by ersi-dnd** [comment]
Yes, it is resolved. Thank you!
