### ISSUE TITLE
href in stardict

### ISSUE THREAD

**Issue by alex125** [koreader/koreader#3588]
* KOReader version: v2015.11-1457
* Device: Kobo 

#### Issue
Now that html dictionaries are implemented (thanks a lot, this is really great), is there any chance to also implement links within stardict dictionaries?

The syntax in the dict.dz file is  `<a href="bword://dictionary_entry">text</a>`.
A tap on `text` should jump to the entry `dictionary_entry` (or open it in another window).
Of course a long tap on `text` does already work as long as `text` and `dictionary_entry` are identical but often they are not.

**Comment by Frenzie** [comment]
Getting the link content is probably the hardest part, but of course
already implemented elsewhere. Sounds like a nice enhancement. :)

On Jan 10, 2018 09:37, "alex125" <notifications@github.com> wrote:


   - KOReader version: v2015.11-1457
   - Device: Kobo

Issue

Now that html dictionaries are implemented (thanks a lot, this is really
great), is there any chance to also implement links within stardict
dictionaries?

The syntax in the dict.dz file is <a href="bword://dictionary_
entry">text</a>.
A tap on text should jump to the entry dictionary_entry (or open it in
another window).
Of course a long tap on text does already work as long as text and
dictionary_entry are identical but often they are not.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/koreader/koreader/issues/3588>, or mute the thread

**Comment by TnS-hun** [comment]
> The syntax in the dict.dz file is `<a href="bword://dictionary_entry">text</a>`.

I've checked a dozen HTML dictionaries and those that use links all use that URL format. Out of curiosity: is there any standard where this is mentioned?

**Comment by Frenzie** [comment]
It's the bword "protocol" in the first and only I therefore checked: Etymology Online. :-)

What do you mean by URL format though? I don't see anything against the URL/URI specs in that bword thing. Do you mean their most common occurrence with the HTTP protocol?

**Comment by Frenzie** [comment]
@TnS-hun Example from https://github.com/koreader/koreader/pull/3573#issuecomment-356950297 (oddly enough it seems to refer to itself, but whatever)

```html
<dt>need</dt><dd>Old English <i>neodian</i> <span style="color: #47A">"be necessary, be required (for some purpose); require, have need of,"</span> from the same root as <a href="bword://need">need</a> (n.). Meaning <span style="color: #47A">"to be under obligation (to do something)"</span> is from late 14c. Related: <i>Needed</i>; <i>needing</i>. The adjectival phrase <i>need-to-know</i> is attested from 1952. Dismissive phrase <i>who needs it?</i>, popular from c.1960, is a translated Yiddishism.</dd>
```

**Comment by TnS-hun** [comment]
What I meant in my previous comment is that I couldn't find any mention of the bword protocol in the StarDict format description at all, but apparently all dictionaries use the `bword://dictionary_entry` format.

But for example this handles `query://` too.
https://github.com/huzheng001/stardict-3/blob/c00d1e928bc91cc3bfa6bc6ba50a35bf121eb259/dict/src/stardict.cpp#L187-L200

I'm mostly done with this feature, only two things are missing: limiting sdcv to the current dictionary and turning off fuzzy search. I don't think these should be added to [ReaderDictionary:stardictLookup](https://github.com/koreader/koreader/blob/e3895102578ddb932d3eb44ff155a97cb325a5ec/frontend/apps/reader/modules/readerdictionary.lua#L463), that function is already long enough, so I think I'll create a new function.

As only one dictionary will be searched I don't know if Trapper:dismissablePopen is needed or not.

Wouldn't it be better to unify the way sdcv gets its parameters on Android and non-Android? The former gets a list, the latter gets a string. I would prefer the former.

**Comment by alex125** [comment]
> Out of curiosity: is there any standard where this is mentioned?

I think the `bword://` syntax comes from babylon format
[](http://siripong-english.blogspot.de/2011/04/custom-dictionary-w-stardict-in-babylon.html)

Most stardict dictionaries have been converted from babylon (.bgl) or Lingvo (.dsl) dictionaries.
When using pyglossary for conversion, babylon dictionaries get converted with `bword://` while lingvo dictionaries get converted with `<a href="word">word</a>` without the `bword://`.

Both variants work with GoldenDict but some other Android App using stardict dictionaries (don't remember which one) I used some time ago actually required the `bword://` to work correctly. 

If implementing in koreader it would probably be best to make it work with either format for the reference link as both versions can occur in existing stardict dictionaries.

**Comment by poire-z** [comment]
> limiting sdcv to the current dictionary and turning off fuzzy search. I don't think these should be added to ReaderDictionary:stardictLookup, 

You could just add a 4th parameter (`dictname`, the dictionary name to use in a `-u` option instead of the `sdcv_dictnames_options*`), and build the specific arguments for sdcv in that case u get the 4th argument (with fuzzy search disabled), no ?

> As only one dictionary will be searched I don't know if Trapper:dismissablePopen is needed or not.

May be not, as the word must exists, so it would be fast
(I have some work in progress that adds a transparent invisible TrapWidget that is used when one call Trapper:dismissablePopen() without an infomessage, that could be used even when fuzzy search is disabled - just in case sdcv gets stuck).

> Wouldn't it be better to unify the way sdcv gets its parameters on Android and non-Android? The former gets a list, the latter gets a string. I would prefer the former.

Could be better yes (beware the different kind of quoting - `self.sdcv_dictnames_options_raw ` vs `self.sdcv_dictnames_options_escaped` - and the need to quote when you turn that list into a string back).

I haven't tried it, but I wonder if the standard `io.popen()` would work on Android (as the fork() stuff done for coverbrowser plugin, that I thought wouldn't work on android, actually just did work. We could then get rid of the android/non-android distinction, and Android could get dismissable.

Oh, and if you add Tap to HtmlBoxWidget to follow bword links, try to make it disable'able :) May be just by re-using the existing `G_reader_settings:isFalse("tap_to_follow_links")`. (I use tap for scrolling, and I would be bothered if I had to look where I tap to be sure i'm not taping a link).

**Comment by poire-z** [comment]
> I haven't tried it, but I wonder if the standard io.popen() would work on Android (as the fork() stuff done for coverbrowser plugin, that I thought wouldn't work on android, actually just did work. We could then get rid of the android/non-android distinction, and Android could get dismissable.

I just tried it, and it works on my Android 6.0.1 phone.
If that is true for all android versions (why not? It's basic linux stuff, but we should test it), we could:

in `base/ffi/util.lua` : [util.getNonBlockingReadSize()](https://github.com/koreader/koreader-base/blob/feca07cc6f32271c9a904f67372719b13fe292d7/ffi/util.lua#L223-L228) works on Android, so we could remove the test.

And this could be removed, as the `else `part works on Android (and it is dismissable, and shows _Dictionary lookup canceled_, and process is collected, no zombie):
https://github.com/koreader/koreader/blob/cffe95b54af5e7501d08d45ad3de0f5d5d663801/frontend/apps/reader/modules/readerdictionary.lua#L516-L526

**Comment by TnS-hun** [comment]
> When using pyglossary for conversion, babylon dictionaries get converted with bword:// while lingvo dictionaries get converted with <a href="word">word</a> without the bword://.

Thanks for the information. Both will be supported.

@poire-z:

I created a [separate function](https://github.com/TnS-hun/koreader/blob/patch-html-dictionary-link-support/frontend/apps/reader/modules/readerdictionary.lua#L498) that just starts sdcv searching for the given word, using the passed dictionaries and optionally using fuzzy search.

Instead of storing the list of enabled dictionaries in two already formatted command line strings for the two platforms (Android, non-Android) there is now only a single list that only contains the dictionary names.

This way both the HTML dictionary links and the normal search can use the same function.

I think the code is now a bit clearer but let me know what you think.

I didn't change the code to use io.popen on Android too because I couldn't test it, and there is some additional trickery on non-Android platforms ("; echo"), but I can change it if you have tested it and it worked.

Thanks for the warning about the tap_to_follow_links setting. :)
