### ISSUE TITLE
Items per page in reading statistics

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3620]
Is it possible to manually change the default value (14 for me) somewhere?

**Comment by poire-z** [comment]
We have the KeyValuePage widget that is used to display a few things:
- dictionary and wikipedia lookup history
- book information
- most reading statistics views
- systemstat and batterystat plugins (and the deprecated GoodReads one)

It uses a hardcoded `item.height_default = Screen:scaleBySize(30)` from size.lua, and a hardcoded font face/size - so we most probably all get 14 items per page.

As we made item per page and item font size configurable for Menu and its various instances, we could make KeyValuePage also have that configurable.
May be it doesn't need per-individual-using-widget values (because that's tiresome to do, and they most probably all display quite small bits of text), we could at least have these settings that would apply to all of the above, which would keep some kind of consistency.
If yes, where to have these 2 settings in our menus ? :) and what user-facing name to give to this "KeyValuePage" widget ?

Or should we try to use the ones set for "Items per page" (which has a default of 14 too) - even if what was set for filenames/search results might be needlessly too small for KeyValue stuff, but we know the user can read that size.

(Or we could have it auto-try to decrease the height/font size to display all of a 15-20 list on a single page?)

(Thought about this as I was re-ordering/adding some items in the 2 different book statistics panels to make them a bit more consistent, and I have a page break at not the most appropriate place, between 2 related statistics...)

**Comment by NiLuJe** [comment]
IIRC, the look and feel of KVP was modeled after Menu (so much so that I can never tell which one a widget is using without checking), so having both follow the same rules would feel fine?

**Comment by hius07** [comment]
> having both follow the same rules

+1

**Comment by hius07** [comment]
Quite a bit of guys at 4pda.ru are still with vlasovsoft CoolReader (which actually stopped developing) saying "Uh, KOReader is so complicated, too many settings". It might have sense :)

**Comment by Frenzie** [comment]
I agree on the code side to some extent, but on the user side I ignore the vast majority of settings. ;-P

**Comment by hius07** [comment]
Anyway, it's hard to find the universal name and place for these discussed settings.
Maybe, `Information and statistics settings` in the hamburger menu below the`Book information`.
Another place - the first item in the Tools menu.

**Comment by NiLuJe** [comment]
macOS ruined UX for everybody. I *hate* minimalist UIs. Some peopole *love* 'em.

We *definitely* fall on the "KDE" side of the equation (aka., "All The Things \o/").

**Comment by poire-z** [comment]
> the look and feel of KVP was modeled after Menu (so much so that I can never tell which one a widget is using without checking), so having both follow the same rules would feel fine?

Tried re-using Items per page setting used for files and search results, but with the settings I have for them (20), KVPage was becoming too small (my computed default was 14, looks like I'm fine with 16, 20 is too much/small).

The nb of items in KVPage is also DPI dependant, so we can't go with a hardcoded value for items per page. I get 12 or 9 on my emulator depending on the Screen dpi setting, 14 on my device with auto screen dpi. S, I have to try keeping these as the default, so people won't notice any change.

But 16 looks like the optimal value :) We have (or will have) 16 items in the Current book reading statistics, Dictionary downloads took each 4 items, so 16 is nice to not break a page in an entry...

> Anyway, it's hard to find the universal name and place for these discussed settings.
Maybe, Info and statistics settings in the hamburger menu below theBook information.
Another place - the first item in the Tools menu.

I'll add another setting in the File browser settings: `Info lists items per page` (other suggestion?).
<kbd>![image](https://user-images.githubusercontent.com/24273478/107848564-a86b8a80-6df4-11eb-8468-64b0343ddea2.png)</kbd>

With 16, the (a bit updated) Current book stats would look rather nice:
<kbd>![image](https://user-images.githubusercontent.com/24273478/107848590-ea94cc00-6df4-11eb-9b51-94872a32bc2a.png)</kbd>

**Comment by hius07** [comment]
Do we need `Page 1 of 1` when there is only one page?
ToC and Bookmarks windows don't have it.

**Comment by poire-z** [comment]
If we do it like in Menu.lua, this should do it:
```diff
--- a/frontend/ui/widget/keyvaluepage.lua
+++ b/frontend/ui/widget/keyvaluepage.lua
@@ -598,3 +598,9 @@ function KeyValuePage:_populateItems()
     end
-    self.page_info_text:setText(T(_("Page %1 of %2"), self.show_page, self.pages))
+    if self.pages > 1 then
+        self.page_info_text:setText(T(_("Page %1 of %2"), self.show_page, self.pages))
+        self.page_info_text:enable()
+    else
+        self.page_info_text:setText("");
+        self.page_info_text:disable()
+    end
     self.page_info_left_chev:showHide(self.pages > 1)
```

**Comment by hius07** [comment]
Yeah, I'm not a fan of redundant wordings )

BTW, 'No choices available' in ToC etc. is now flashing to grey and is hardly visible, so maybe get rid of it as well?
Blank screen is self-explanatory.

Since touching the page selector, what are the reasons to call 'Enter page number' dialog with a long press?
Short tap is free here.

**Comment by poire-z** [comment]
> Do we need Page 1 of 1 when there is only one page?

Even in the ToC, where expanding/collapsing entries could have this `< Page 1 of 2 >` switched to nothing?
Although it currently does switch between `< Page 1 of 2 >` and `<< < Page 1 of 3 > >>`.

**Comment by Frenzie** [comment]
I think it gives you the confidence that you're not missing anything (sometimes the bottom is cut off on some Android systems, how can you be sure it's not that), and a consistent UI even if it is in some sense redundant.

**Comment by poire-z** [comment]
> BTW, 'No choices available' in ToC etc. is now flashing to grey and is hardly visible, so maybe get rid of it as well?

```diff
--- a/frontend/ui/widget/menu.lua
+++ b/frontend/ui/widget/menu.lua
@@ -969,3 +969,2 @@ function Menu:updatePageInfo(select_number)
             self.page_info_text:setText(FFIUtil.template(_("Page %1 of %2"), self.page, self.page_num))
-            self.page_info_text:enable()
         else
@@ -985,4 +984,3 @@ function Menu:updatePageInfo(select_number)
     else
-        self.page_info_text:setText(_("No choices available"))
-        self.page_info_text:disable()
+        self.page_info_text:setText("");
     end
```


> Since touching the page selector, what are the reasons to call 'Enter page number' dialog with a long press?
Short tap is free here.

This involves the same kind of tweak to Button that we did for hold_callback / hold_input in 6132e8c9.
I might leave that (and the above:) to @NiLuJe , so you can find a way to not mess your whole flash_ui history in `git blame` with indentation :)

**Comment by hius07** [comment]
> Even in the ToC, where expanding/collapsing entries could have this `< Page 1 of 2 >` switched to nothing?

> the confidence that you're not missing anything

Agree, both are important reasons.
Thus, it is better to switch on 'Page 1 of 1' for ToC, Bookmarks etc. for consistency.
And show << < and > >> in grey when only one page?

**Comment by hius07** [comment]
More for consistency: ok-button text in 'Enter page number' dialog is different in `menu.lua` and `keyvaluepage.lua`.

**Comment by NiLuJe** [comment]
@Frenzie's point above is doubly true the for the "No choices available" thing.

I can hack around it to make sure its input handler is disabled, while still printing it in black?

**Comment by NiLuJe** [comment]
Counterargument: Menu is what's used in the FM, and showing a "Page 1 of 1" mention at the bottom is ugly as hell there ;).

**Comment by NiLuJe** [comment]
As for the Menu/KVP inconsistency, there isn't one for Menus that don't need a "Go to *letter*".

"Enter page number" as a title and a standard "OK" button feels just fine for the others?

**Comment by NiLuJe** [comment]
And with those "No choices available" / "SIngle page" labels once again being black, not displaying the arrows is a strong hint that there's no input interaction possible.

c.f., #7335

**Comment by hius07** [comment]
Sorry, forgot about FM. So there are 4 'Go to page' dialogs (three modules):
1) page in book
2) page in ToC etc (without letters)
3) page in FM (with letters)
4) page in Book info etc

The header might be
'Enter page number' for 1,2,4
'Enter page number or letter' for 3

The buttons might be
'Cancel', 'Skim', 'Page' for 1
'Cancel', 'Letter', 'Page' for 3
'Cancel', 'Page' for 2,4

Thinking about arrows for a while...

**Comment by hius07** [comment]
Regarding page selector, for maximum consistency:

`<< < Page 1 of n > >>` always visible, even when one page only available, no need for 'No choices available'.
Arrows are greyed depending on the number of pages and current page.

**Comment by hius07** [comment]
Sorry, I didn't understand why page selector needed a hold, not just a tap.

**Comment by poire-z** [comment]
Hijacking this issue for a question just a little bit unrelated.

When testing fonts, I'm a bit tired, after closing the menu and browsing a few pages, when going back to it, to be on page 1 and have to tap 6 times to go to page 6 where I have my font checked, to check and test the next one - and again and again...

I have something ready to open the menu (only those equiped with a `.show_menu_item_id_on_menu_open_func`) on the page with the checked item.

Is that ok from a UI/UX perspective ?

There are not many menus that could benefit from it. A quick look around and I found these:
- Fonts (a few page to many more, no real reason to stick to 1st page - and as we don't show the selected font name in the previous menu, it might help getting to know quicker which font is currently in use)
- Language (4 pages, but English is first, we may want it to show first?)
- Translation from/to> languages (same)
- File manager "Sort by>" (1 or 2 pages only)
- Gesture manager: each set of action are around 5 pages.

Thoughts?

**Comment by Frenzie** [comment]
That's probably okay, although I'll counter that sometimes I close it and reopen to get back to page 1. ;-)

**Comment by NiLuJe** [comment]
Sounds good, yeah ;).

**Comment by poire-z** [comment]
Been playing with it - and got a bit annoyed :) It's practical for the use case I mentionned - but otherwise, I felt a bit lost/suprised - but I guess I & people will get used to it.
But we need a way to get back fast to page 1 - otherwise, it's taps fest again :)

I don't want to add <kbd><<</kbd> and <kbd>>></kbd> to our touch menu bottom already has a up chevron on the left and the time+battery on the right, so risk of overflow/crowdyness - and it's mostly non useful on all the other menu.
So, long-press on <kbd><</kbd> and <kbd>></kbd> ?
```diff
     self.page_info_left_chev = Button:new{
         icon = chevron_left,
         callback = function() self:onPrevPage() end,
+        hold_callback = function() self:onFirstPage() end,
         bordersize = 0,
         show_parent = self.show_parent,
     }
+function TouchMenu:onFirstPage()
+    self.page = 1
+    self:updateItems()
+    return true
+end
```
does it.
@NiLuJe : no flash when long-press on these - is that ok with long-presses ? Or do I need to add some stuff to get you your flashes and whistles?

**Comment by NiLuJe** [comment]
There's a few things that don't flash on hold (the pagination buttons, actually ^^), so I wouldn't worry about it much (besides, it's mostly sitting under your finger on a hold anyway ;o)).

**Comment by Frenzie** [comment]
> So, long-press on < and > ?

Yeah, that's sensible enough.
