### ISSUE TITLE
FR: Abritrary number of columns in column view

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#3685]
* KOReader version: ca6a4868069c2ddb58bedf8497690440d1440d1f
* Device: all

Two-column navigation was implemented in #3674.

@FranMarelli Perhaps you've already thought about improvements, but @ersi-dnd wrote down quite extensive thoughts and information about multi-column modes [here](https://thedndsanctuary.eu/index.php?topic=3089.msg78721#msg78721)

> Please-please an arbitrary number of columns. In Pocketbook's reader app, you can select two or three, and three is sufficient for almost everything. Pocketbook does not attempt to detect the columns, it auto-divides the whole page to two or three and when the user thinks/sees it does not fit properly a column, you can drag on the touchscreen (this works splendidly in Pocketbook, not awkwardly or glitchily). 

Looking around a little, arbitrary columns may not be the hardest thing given that you do something like that for the two columns?

https://github.com/koreader/koreader/blob/ca6a4868069c2ddb58bedf8497690440d1440d1f/frontend/apps/reader/modules/readerzooming.lua#L272-L273

@ersi Do you have any more information (e.g., screenshots/pictures) about the concrete way this works in Pocketbook?

**Comment by ersi-dnd** [comment]
Here's how it works in Neo reader (Onyx Boox)
![screenshot_2018-02-18-21-03-23](https://user-images.githubusercontent.com/6865273/36355750-a33f813e-14f0-11e8-836a-850095b28ca1.png)

First look at the "Direction" row. There are four possible directionalities. This should be sufficient for all reasonable use cases. However, instead of designing the GUI the same way in Koreader, I suggest having the behaviour as a conjunction of the existing setting "Read from right to left" with the to-be-created setting "use rows in multi-column mode (horizontal/vertical)" in multi-column mode.

The Column row shows how Neo reader permits selecting the number and placement of columns. My idea with the placeable rectangle, which is hopefully more flexible, is as follows.
![screenshot_2018-02-18-21-03-01](https://user-images.githubusercontent.com/6865273/36355799-668b655e-14f1-11e8-996a-c67d12cc80e3.png)

This would be the positioning of the starting point for multi-column reading. Once the starting point is set, let the conjunction of "Read from right to left" with "use rows in multi-column mode (horizontal/vertical)" do its thing.

Happy to clarify further if needed :)

**Comment by Frenzie** [comment]
> Somehow the Pocketbook bit appealed most to you?

I have no idea if it appeals or not. I'm just curious how they present the option, and whether it appeals or not can't be judged until afterwards. ;-)

Thanks for the screenshots!

**Comment by Frenzie** [comment]
I've actually been using zoom to fit column surprisingly much and it's been working great for me. But yeah. :-)

**Comment by ersi-dnd** [comment]
"But yeah" meaning "No, there is no setting to split the page into more than two columns"? 

Look at for example this and think how you would navigate it with Koreader http://gallica.bnf.fr/ark:/12148/bpt6k5610314.item
This is what I have in mind as a use case for an arbitrary number of columns.

**Comment by ersi-dnd** [comment]
Here's another picture, better than before, I think.
![screenshot_2018-06-08-12-50-51](https://user-images.githubusercontent.com/6865273/41173616-504f55a0-6b60-11e8-9017-604b7c2cc365.png)

This page has two columns, but the column division is broken by one paragraph in between. I placed the starting-point thingy to the lower section with columns. Once the highlighted portion is read, I would need to move actually right for the next bit, not lower. This is why it would be useful to implement somehow ways to move from the starting point in any direction.

But as a first rough move, it would be good enough to give the current "zoom to column" function a setting to split the page in three and four and maybe even more, not just two.

**Comment by ersi-dnd** [comment]
Here https://github.com/koreader/koreader/blob/c93bbec40d4e5d6a229672e4985303fdb11900cd/defaults.lua

we have 
`DKOPTREADER_CONFIG_MAX_COLUMNS = 2 -- range from 1 to 4`

Changing this number has no effect that I can notice. Is it related to what we are talking about or not? What is its effect supposed to be?

**Comment by Frenzie** [comment]
@ersi-dnd That's for EPUB, isn't it?

**Comment by KenMaltby** [comment]
As I understood it the DKOPTREADER settings were for the PDF rendering.  You might have to delve into the CR3 settings/ini to deal with this for epubs.

**Comment by ersi-dnd** [comment]
@Frenzie You mean is the setting for epub? I would like and expect it to be for pdf files, related to "zoom to fit column", but if not, well, then not. It remains to be seen what it does.

**Comment by Frenzie** [comment]
@ersi-dnd It's used here:

https://github.com/koreader/koreader/blob/895372f781a4f5d0ddfb315f779c4e414415de2c/frontend/ui/data/koptoptions.lua#L85-L98

https://github.com/koreader/koreader/blob/076bf406fd0fb5d9b9acf7ceed2475f2dc3e94e9/frontend/document/koptinterface.lua#L84

So it must have something to do with k2pdfopt, the reflow mechanism for PDF and DjVu.

**Comment by ersi-dnd** [comment]
I dreamed up a name for this feature, if you ever get around to implementing it: Page-crawler

The feature: Determine a number of columns, assign the starting point, and crawl the page in some pattern.

I think Page crawler rhymes nicely with other menu items of Koreader, such as Perception expander and Gesture manager.
