### ISSUE TITLE
Select multiple words from inside a dictionary

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3717]
Dictionary lookup of multiple words in books is easy, you just hold and drag. 

But when you do the same from inside a dictionary it's a little more troublesome:
1. When you drag, there is now a high risk that you just move the dictionary window
2. The selected words don't turn greyish
3. If the long press is too long the Wi-Fi window opens

A trick that often works is to use two fingers and simultaneously press the first and last word of the phrase. But I guess that isn't obvious for everybody.

Maybe this could be improved?

**Comment by Frenzie** [comment]
Pinging @poire-z 

The moving the window is kind of your fault. Maybe it doesn't need to be on the *whole* window. ;-)

**Comment by poire-z** [comment]
> 1. When you drag, there is now a high risk that you just move the dictionary window

Looks like a bug in #3636: hold/pan/swipe from inside the definition shouldn't cause a widget move, but Pan (no hold at start, but hold at end, which is a Pan) actually does :( . (@Frenzie : I took care of that, guess I let that one among the three possible move gestures move the whole window, or more probably, it's while fixing some other stuff that this happened).

2) is very hard to do (and not worth the effort I think)

3) is because of a shortcut: if you hold > 2 seconds, it searches in the other of _dict or wikipedia_ that you were in. So, if you were in a dict, it allows you to go directly do the wikipedia search. May be this 2.0 seconds could be increased if it's really too low.
https://github.com/koreader/koreader/blob/8a5b88878995e23b8869e4da14543145b182cd7f/frontend/ui/widget/dictquicklookup.lua#L135-L144

**Comment by Frenzie** [comment]
Seems to work well enough now, so closing. :-)
