### ISSUE TITLE
FR: Switch internationalization to Weblate

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#3754]
* KOReader version: 78fbc14
* Device: all

#### Issue

According to @anarcat it could simplify and improve certain aspects of the workflow. This issue is to track ideas and requirements.

https://github.com/koreader/koreader/issues/2621#issuecomment-372986629

**Comment by anarcat** [comment]
So I was asked to provide a workflow example, so here we go... I'm using Weblate for the [Monkeysign project](https://0xacab.org/monkeysphere/monkeysign/). There is this [web interface](https://hosted.weblate.org/projects/monkeysphere/monkeysign/) where people can sign in and contribute translations. Say I spoke German, I would go to the [german translation page](https://hosted.weblate.org/projects/monkeysphere/monkeysign/de/) and hit `Tranlsate`. There I am shown with a simple form where I can submit translations, but I can also "suggest" them in which case they wait for moderation before being committed. There's also a batch edit mode (called "Zen") where multiple translations can be entered more quickly.

Once a translation is done, it gets committed into git, in a repository that is publicly available. The main developers (ie. me) will, before a release, pull from that repository and merge it in the release branch after a summary review. One thing I find annoying there is that some "empty" translations sometimes shows up: a translator would come to the project and start a (say) Russian translation but never translate any string. Or we'd have partial translations like Ukrainian (3 words?!). It's harmless, but there's a `.po` file there that's just mostly empty. Completely empty .po files do not get committed into git, so it's not such a big deal.

When new code is pushed to the main Monkeysign repository, there is a (web) hook that tells Weblate to pull changes. Weblate merges those in and will notice new strings needing translation and update the web interface accordingly.

Strings can also be translated using normal po tools by editing the files directly in the normal git repository, which was a requirement for us: we didn't want to depend on a web interface.

There's also a [commandline client](https://github.com/WeblateOrg/wlc) to operate the weblate repository from the commandline. From there you can list projects, translations, download translations and so on.

I'm happy to answer any other question you might have about Weblate. Apart from that one annoyance I've found above, weblate has served us very well. It mostly stays out of the way while allowing people to contribute translations fairly easily, and the web interface is always getting better. All the translations we have of Monkeysign (except a *partial* french translation) come from Weblate users.

You can host your own [weblate instance](https://github.com/WeblateOrg/weblate) or you can ask to be hosted for free, since this is a free software project (although they welcome donations). Here are their [hosting plans](https://weblate.org/en/hosting/).

**Comment by Frenzie** [comment]
Our budget is about €15. It'll have to be the free option. :-)

@cramoisi Mentioned how it can be difficult to get a proper overview of where strings are. It doesn't look to me like Weblate gives any more context indications than Transifex. Is that correct?

![screenshot_2018-03-15_16-45-19](https://user-images.githubusercontent.com/202757/37474288-50192fee-2870-11e8-8f16-96a351fe7600.png)

(I do think it's presented clearer in Weblate.)

**Comment by anarcat** [comment]
I think this issue is known, documented in: https://github.com/WeblateOrg/weblate/issues/1801

Basically, the "source string location" would need to be expandable somehow. Would it be sufficient if it would be link to a web view of the git repo, for example? Or should it be inlined in the web UI?

**Comment by Frenzie** [comment]
Sounds fine to me, but @cramoisi raised the point. :-)

But like I said, it's not positive or negative as far as Weblate goes. It's roughly the same as Transifex.

**Comment by cramoisi** [comment]
It's because I'm much into "I will translate this menu and then this plugin (which is attached to this plugin, etc). A more visual approach, in fact. It's hard to see how the string will bring together something coherent but it will do :)

(anyway, where can we discuss some relevant - or irrelevant- point about traduction ?)

**Comment by Frenzie** [comment]
Today on Transifex:

![screenshot_2019-02-17_14-49-04](https://user-images.githubusercontent.com/202757/52913976-6cfc5b00-32c3-11e9-85f6-30a04cf24a41.png)

**Comment by anarcat** [comment]
> I think this issue is known, documented in: [WeblateOrg/weblate#1801](https://github.com/WeblateOrg/weblate/issues/1801)

FWIW, that specific issue was fixed upstream.

**Comment by Frenzie** [comment]
Just a quick update to keep you guys apprised. I've contacted Weblate and they say they'll be happy to host our translations.

Unless I'm overlooking something, that means:

[ ] Commit the translations. (Easy. Pull from Transifex and commit.)
[ ] Inform everyone. (Transifex has announcements.)
[ ] Freeze translation activity on Transifex. (Not sure how.)

**Comment by pazos** [comment]
@Frenzie: Does that mean fetch translations without a token?.  I would love to see the fdroid package finally translated. :+1:

**Comment by Frenzie** [comment]
Yeah, because the translations would just live in the repo.

https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commit

I could maybe make that work with Transifex too but it seems a bit focused on keeping the translations on Tx.

https://docs.transifex.com/transifex-github-integrations/github-tx-ui

Of course I could also do it manually through a GitLab CI trigger or whatever but it seems overall more convenient this way.

**Comment by pazos** [comment]
Did a quick look at weblate. Amazing.

To move users to weblate it could be nice to add a new resource with a string "migrated to weblate, read more on https://github.com/koreader/koreader" and don't update other resources anymore.

Ofc, if some new contribution happens on transifex that's not available on weblate we can merge it manually

**Comment by Frenzie** [comment]
Until Weblate is set up I'll just leave Transifex as it is. An update should about as simple as `tx pull` followed by committing the changes.

**Comment by Frenzie** [comment]
I just received notice that Weblate is now up and running. I'll probably let it slide for the December release but this ticket will finally be able to be closed soon.

**Comment by Frenzie** [comment]
I uploaded @pazos' suggestion to Transifex, disabled the Transifex push in 49f06f8d36227d11809906d7e5677d25a5c71d76, and Weblate is now fully operational.

So everyone can head over to https://hosted.weblate.org/projects/koreader/koreader and start translating! ;-)

I'm already really happy about Weblate, because now many issues with spacing are automatically signaled to translators. The quality of the translations has already improved in the past few hours thanks to Weblate alone.

### Text on Transifex
![Screenshot_2019-12-31_11-13-35](https://user-images.githubusercontent.com/202757/71618129-a0d02e80-2bbe-11ea-9510-dd6f5e43c717.png)
