### ISSUE TITLE
Wiki downloader UI improvements

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#3757]
* KOReader version: FEATURE_REQUEST
* Device: kobo glod hd

ISSUES
+++++

when I browse a wiki article that's saved, I click on a link and I want to see a meaningful dialog, that allows me to download the article without too many clicks.

right now I have to:

1) reply to "do you want to connect to wifi to download a wiki article" - of course the answer is YES, no need to ask even if I'm not connected; just say "connecting" and the dialog if the prev WiFi spot is not in the air;

2) I need to click on the same link of the original epub 3 times to get connected to wifi (see issue https://github.com/koreader/koreader/issues/3743 )

3) I need to view the preview and click SAVE AS EPUB - I'd want to skip this screen, I don't need the preview when I'm on a bus and when I'm holding a e-reader with 1 hand; preview may be a pop-up window with the content on a pop-up (or upper half) of the SAVE dialog;

4) I need to wait once again for the download of the same wiki article (what the preview is for, then?)

5) I need to reply standard or hi-res pictures do I want (oh man.... every time!!!)

6) I need to answer to "do I wanna open the downloaded EPUB?" - well sometimes I say YES, but most of times I'm continuing reading the original article, so no need to ask, just close the dialog but when I click on the same link (whose article is already downloaded) again then open the downloaded EPUB locally (instead of going online); may be a little icon / text sign next to the link - would direct me again onto the download process; I understand that 6.1) tracking of the downloaded EPUB that was moved into another folder, 6.2) parsing html and 6.3) injecting the icon in DOM etc etc - is a big hassle; I realize that;

so all those items mentioned above are necessary (I agree) but annoying to click - all over again for each next article I want to see;

My suggestion would be to combine all those questions in one dialog that I set up once and click YES to get the article. one hand use, single-tasking UI, basically emulating offline browser behavior - would be the best experience;

SUGGESTIONS
+++++++++

after I click on the article inside a EPUB downloaded from wiki - the dialog shows up with YES or NO:

1) wifi connection: [name of the network] - just to show me I'm connected, and let me choose another wifi AP;

2) Save To: [the folder where I saved my last EPUB to]
LINK: use the folder of current EPUB [\Wikipedia\medicine\teeth]
ICON: folder browser to select another folder

3) images: tri-state selector with [no pitures] [med-resolution] [high-resolution]

4) checkbox "OPEN THE ARTICLE AFTER DOWNLOADING" (which I will keep OFF)

5) PREVIEW: expandable area, if I click then download and fill the preview area below with text only, just like it works now (I may change my mind and won't save anything if I see the content - prevents download + delete)

6) SAVE AS EPUB or CANCEL

7) keep the dictionary URL - LOCATION OF EPUB somewhere in wiki plugin folder, that will know if I already downloaded the article; if YES I DID then modify the link (between reading the epub and feeding it into the HTML render) so that it point to the local EPUB, with an icon to re-download it again; whenever the user moves / deletes / copies the files with the browser on the initial screen - this hash-table may get overwritten by the move / delete / copy operation so that there would be a consistent storage for the clicks to get redirected to local downloaded EPUBs/HTMLs; re-scan / repair the hash-table of downloaded articles might also an option;

8) KEEP THE SETTINGS in this dialog and make them survive the koreader restart and OTA update

I know it's too much of hassle for an open-source project. but
1) I'm ready to pay for these features;
2) I can probably do it myself and commit back (please tell me quickly how the project is organized in terms of folders and cross-module invocation conventions);

**Comment by Frenzie** [comment]
Almost everything you want to do probably hangs out somewhere in `frontend/`.

The Wikipedia stuff specifically in 
https://github.com/koreader/koreader/blob/14063249ab2369b2c8ab7edd5216b1596d541372/frontend/apps/reader/modules/readerwikipedia.lua
and
https://github.com/koreader/koreader/blob/14063249ab2369b2c8ab7edd5216b1596d541372/frontend/ui/wikipedia.lua

There are some docs here: http://koreader.rocks/doc/

Also see http://koreader.rocks/doc/topics/Development.html (somewhat outdated)

**Comment by poire-z** [comment]
Your 2 first points about WIFI are real, and there are already other issues opened about them.

> I need to view the preview and click SAVE AS EPUB - I'd want to skip this screen

You at least don't need to wait: you can dismiss it by clicking anywhere: the dict window will display "wikipedia lookup cancelled", and you'll have the usual Save as EPUB button to go on.
Also, and that's a generic behaviour of confirm boxes: click anywhere outside the box chooses cancel (or the button on the left). So, on a bus with 1 hand, that may help.

I wouldn't call it _Preview_ anyway. For me, it's the main view (and Save as EPUB is a bonus, a _postview_ :)
But let's call it preview for the next sentences...
This window show images since a few months ago. Before that, I used to Save as EPUB to be able to see pictures, which were my main use of wikipedia lookup: see some old city on a map, see some personality face... I used to save 80% of my lookups to EPUB for that. Now that the preview show images and allow zooming them, my Save as EPUB usage went down to 10% of my lookups.
Also, with a first widget as you described, with all the options you want, and Preview as a additional button, you'd probably often go see this preview, just to see if the content is valuable, long enough. I often get 2-3 paragraphs articles for the obscure things I lookup, that I can read quickly on this preview - no need to bother saving it as EPUB.

> I need to wait once again for the download of the same wiki article (what the preview is for, then?)

These are not the same HTTP requests (preview is formatted plain text made by wikipedia servers, EPUB needs html, toc...)

> I need to reply standard or hi-res pictures do I want (oh man.... every time!!!)

On a bus, with a slow internet link, I guess you may want to know how many images there are, before deciding, also based on the article (depending on the subject, you may not care about images, and you just want them inline in the epub), if you really need standard or hi-res. The few taps you want to avoid are nothing compared to the 30-120 seconds needed to download 146 images.

> when I click on the same link (whose article is already downloaded) again then open the downloaded EPUB locally (instead of going online); 

This is a good idea: we could check at least, before going online do a lookup, if there is an EPUB of that link's article in the currently-being-read article EPUB directory (assuming you filled articles about the same topic in the same directory). No need to excessively bother keeping a DB and moving files around. (Injecting icons around link in the EPUB DOM is nearly impossible with our epub engine.)

About your wikipedia EPUB filling needs, there is a new option now: `Save wikipedia EPUB in current book directory` (https://github.com/koreader/koreader/pull/3762#issuecomment-373439286 and followups), which may or not make things easier for you.

Anyway, if you're going to work on having all that you want (and that's really huge work), I ask for it to not be the default and not replace the current behaviour.

In the meantime, to see if it's enough, you may try just patching the current code on your device, and comment a few things, like:

Put true or false (what you want) on the first 2 lines, and comment what follows:
https://github.com/koreader/koreader/blob/24c013274430addac6e51b0d9d1c91df0999c132/frontend/ui/wikipedia.lua#L779-L793

....
Comment the  `UIManager:show(ConfirmBox:new{` (and their associated closing `})` ) and let it just do what is done in the `ok_callback` or `cancel_callback` depending on what you want:
https://github.com/koreader/koreader/blob/24c013274430addac6e51b0d9d1c91df0999c132/frontend/ui/widget/dictquicklookup.lua#L352-L362

....

If some confirm boxes are really annoying (on this wikipedia topic or another), we may be can just make them auto-confirming :) Like:
1) Give each possibly annoying `ConfirmBox:new{}` a `confirmbox_id="wiki_saved_read_now"`
2) Have `ConfirmBox:onShow()` looks if there is a `G_reader_setting("confirm_answer_wiki_saved_read_now")` with `true` or `false `, so user can individually add settings for the confirmbox they don't want to see...
3) make it call the appropriate callback and prevent being displayed

**Comment by poire-z** [comment]
> Your 2 first points about WIFI are real, and there are already other issues opened about them.

And should be solved since #6424.

As for the other Wikipedia points, one has been implemented. On the others, I disagreeed :) and nobody else ever requested them.
So, closing.
