### ISSUE TITLE
The new "extracting metadata" feature: when tapping outside the "question-windows" 

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3763]
* KOReader version: v2015.11-1573-g0a4fb89_2018-03-15/ 
* Device: KA1

#### Issue
When you tap somewhere outside the last three "question-windows" (subdirectories, refresh and prune) the process just continues with the next window. 
I guess it is not meant to be like this. Instead the window should just disappear and the process aborted.

**Comment by poire-z** [comment]
That's the behaviour of ConfirmBox since https://github.com/koreader/koreader/pull/2493#discussion_r96161198 and https://github.com/koreader/koreader/commit/97d34c5bb0de21a8c2ad2cb47ead64b2d3de89ff:
```
ConfirmBox: allow dismissing/cancelling by taping outside,
to keep UX consistent.
```
It's fine when the buttons are `Cancel | OK` (and when it's a simple one-question process - what about when there are multiple, should it cancel this one or the whole process), but when using other button texts, it may be confusing.
I usually try to make the left one (called when taping outside) the less impacting, which is the case for this one (Here only, Don't refresh, Don't prune). Anyway, as you can interrupt the process just later, and it's not destructive wherever it's interrupted, it shouldn't harm.

Is this behaviour surprising in other places?
If there are reasons to allow for a different behaviour, technically:
We could have ConfirmBox calling `cancel_callback(dismissed)` with a parameter (false if button tapped, true if dismissed by taping outside), so callers can decide what to do, if a different processing of these 2 cases is prefered.
For the dialog driven by Trapper (here, and in the Wikipedia Save as EPUB dialog), may be we could have `Trapper:confirm()` return false if button tapped, nil if dismissed by taping outside.

**Comment by poire-z** [comment]
Closing as no comment on the generic topic.
