### ISSUE TITLE
Progress bar with chapter markers inaccurate in landscape mode

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3778]
* KOReader version: v2015.11-1573-g0a4fb89_2018-03-15/ 
* Device: KA1

#### Issue
In landscape mode the progress bar isn't coordinated with the chapter markers. The bar seems to lag.

Not all epubs are affected (and no pdfs AFAIK).

I've added an example. First portrait mode and then in landscape. Same place in a book (a new chapter).
![reader_2018-mar-19_183716](https://user-images.githubusercontent.com/32645430/37613591-b19cdf50-2ba8-11e8-9d44-5f67be842f07.png)
![reader_2018-mar-19_183658](https://user-images.githubusercontent.com/32645430/37613598-b4db050c-2ba8-11e8-8bb0-dd52e0fdf672.png)

**Comment by Frenzie** [comment]
Pinging @poire-z to ask if it might be related to #3740.

I haven't managed reproduce this in real-life conditions. I can trigger it by resizing the window but that's more likely to be indirectly related to #3740.

**Comment by poire-z** [comment]
I dunno, it may or may not :| #3740 being pure frontend code, it should be easy to test without.
In the onChangeScreenMode(), there was and is a self:onUpdatePos() which triggers via a scheduleIn a UpdateToc event.
Does it gets ok when you go to next page ?

**Comment by Frenzie** [comment]
Actually I can reproduce it in real-life(ish) conditions. All you need is a sufficiently large window. (You'd think Aura One size would be big enough to notice but I didn't see an obvious problem without pixel counting.)

```
./kodev run -w=2000 -h=2500
```

The progressbar can seemingly run both fast and slow. What's special about resizing the window (as opposed to switching portrait/landscape) is that the program as a whole becomes slightly confused about locations, including the TOC. The reason I thought it might potentially be related is because it looks a bit like sends you where the chapter marks end up but that was probably just an illusion or a fluke. In any case it's a different, otherwise irrelevant issue. ;-)

Here's the problem demonstrated by switching from landscape (good) to portrait (bad). What's good depends on what loads first.

<img src=https://user-images.githubusercontent.com/202757/37682855-fd4dfd98-2c8a-11e8-9dfa-74738501c7a3.png width=30%>
<img src=https://user-images.githubusercontent.com/202757/37682856-fd738400-2c8a-11e8-8826-892eafe42a31.png width=30%>

And portrait (good) to landscape (bad):

<img src=https://user-images.githubusercontent.com/202757/37682927-2c168cda-2c8b-11e8-9939-bdce68a10f6a.png width=30%>
<img src=https://user-images.githubusercontent.com/202757/37682928-2c356b0a-2c8b-11e8-9618-9640e563df50.png width=30%>

The bar is good, but the position of the chapter marks isn't.

**Comment by gerhaher** [comment]
This bug isn't fixed.

**Comment by Frenzie** [comment]
Sorry, GH isn't intelligent enough to interpret words like might or maybe.

@poire-z that's why I type thing like references issue# ;-)

**Comment by gerhaher** [comment]
Sorry do disappoint you, but I see no improvement at all. With most recent version: 
![Reader_2019-Sep-24_165444](https://user-images.githubusercontent.com/32645430/65523718-fd032280-deec-11e9-8360-65acb0b77793.png)
![Reader_2019-Sep-24_165418](https://user-images.githubusercontent.com/32645430/65523733-0096a980-deed-11e9-8650-e06ad3cc348b.png)

**Comment by robert00s** [comment]
Thanks for info.
I think I found solution. I prepare fix soon.
