### ISSUE TITLE
Can't change download directory for OPDS

### ISSUE THREAD

**Issue by bahusoid** [koreader/koreader#3798]
KOReader version: 1598-g680b53e_2018-03-23
Device: Android 4.4,  Nook GLP

Download dialog says:
"Choose download directory by long-pressing"

But nothing happens: dialog is just slightly moved (if long-pressing on file download button) or become semi-transparent .

**Comment by Frenzie** [comment]
Looks like it's a slightly deceptive button text. You just tap that one, but you have to long-press once you're in the filechooser.

**Comment by KenMaltby** [comment]
Since the info box also gives what the current download directory is, you might make the option just "Change Download Directory" .  (I notice on mine that it is taking a very long time for the "Chooser" to appear, didn't notice when that may have started.)  The chooser could have a two line title and say "Long-press to choose download directory".  (Or it might fit on one line?)

Luck;
Ken

**Comment by Frenzie** [comment]
Yes, that's how it was. Clearly the reducing confusion part needs a slight rethink. :-)

https://github.com/koreader/koreader/commit/3492b8b117e6401f145acf346f6e4be4db2752ad

**Comment by KenMaltby** [comment]
As the chooser page could be used elsewhere, you could make the page title be just " Long-press to choose directory".

**Comment by bahusoid** [comment]
Indeed :) Thanks for clarification - for some reasons I didn't get that it's also a button :)
I agree with @KenMaltby  that "long-press message" better be present on the actual file chooser.
