### ISSUE TITLE
Increase word spacing upper limit in settings

### ISSUE THREAD

**Issue by kiike** [koreader/koreader#3805]
As per our gitter.im conversation, it was suggested that I opened this FR: there's a limit for word spacing that is perhaps too small for those who want to achieve a look similar to the Kobo default style.

Here's a screenshot of the default rendering settings of KOReader in the left, the default settings of Kobo stock reader in the middle, and tweaked settings KOReader in the right screenshot:

![reader comparison](https://ptpb.pw/AFCTzh3jyb1RgUVHZl8q0dt_Vrd7.png)

**Comment by Frenzie** [comment]
So people won't have to read the chat, here's what I wrote:

> @kiike Create a persistent.defaults.lua with `DKOPTREADER_CONFIG_LINE_SPACING = 2`. See https://github.com/koreader/koreader/blob/c93bbec40d4e5d6a229672e4985303fdb11900cd/defaults.lua#L92
> 
> I'm not sure why a wider range isn't available from the UI. Could you open an FR? :)

**Comment by poire-z** [comment]
For line spacing, the **cre**ngine (epub) settings are not the DKOPT* (pdf), but the DCRE*:
https://github.com/koreader/koreader/blob/c93bbec40d4e5d6a229672e4985303fdb11900cd/defaults.lua#L123-L126

What you set there are available in the bottom menu.
I tried with 500, and it was too huge for me :)

Dunno about letter or word spacing.
There is another setting (not exposed to koreader), that can be set in data/cr3.ini:
`crengine.style.space.condensing.percent=50`

**Comment by Frenzie** [comment]
Oops, I didn't even notice I typoed that.

I don't think double line spacing is quite out there as something one might regularly wish to attain though. :-)

**Comment by cramoisi** [comment]
@kiike looking at your screenshots, you meant line-spacing don't you ? From your Kepub, I noticed two thing : there is no hyphenation (so you should disable it in koreader if you don't want it) and this means much space between words (because they are not cut at the end of the line). The linespacing is also 1.5 or 2.0 but if I'm remember correctly, the kepub renderer force the linespacing to be user defined even when it's set in the kepub's css. KOReader won't do that (I think) so you have to remove the line in your kepub css before setting it anywhere. Also, perhaps you should disable "all external style" in KOReader style. That aside, and linespacing > 1.5 is something only schools ask for.

@Frenzie @poire-z  
For letter-spacing inside a word  (more or less "kerning") you could try the  letter-spacing property or text-rendering: optimizeLegibility; if it's supported... Although the font-kerning property is something epub3 should support. For spacing between words ; there is the word-spacing css1 which is default and correctly supported by KOReader last time I checked. But because I tried it I can say it's something complicated to achieve and won't be consistent among books. On KOReader it's too much work without a user stylesheet (I mean a style which is applied after the rest and takes the upper hand)

**Comment by Frenzie** [comment]
@cramoisi Our rendering engine is over ten years old. I think there's little reason to expect fancy CSS3 properties. :-P (Anyway, we don't do the equivalent of optimizeSpeed and kerning is enabled by default.)

You can however play around with the quality settings in cr3.ini if I'm not mistaken. Unless that's a compile time setting.

**Comment by cramoisi** [comment]
@Frenzie : yup. Just wanted to say some tests could be done on the user side if the wants to modify the display of it's book.

I'm pretty sure kobo doesn't render these CSS3  properties. Perhaps Kindle does it in a way of their own (with bookerly and their new book format). But not kobo, it's epub3 compatible in a way that their renderer won't crash when parsing a css3 property and that's all :)

**Comment by kiike** [comment]
@cramoisi actually I probably meant to mention both line spacing and word spacing upper limits but only ended up talking about word spacing. Actually, I spent the weekend  reading in KOReader and Plato and now I can't stand the look of the huge line and word spacing in the screenshot in the middle. I'll check what disabling the style does and how the situation changes, just for reference. Cheers!

**Comment by Frenzie** [comment]
@kiike Note that if you long-press on a file and choose Open with… → MuPDF you'll get the same rendering engine as in Plato. Features are still somewhat limited for now.

**Comment by cramoisi** [comment]
@kiike line spacing at 1.2- 1.5 can be easier for the eyes, it depends of the fonts (and of the eyes and tastes of the reader) but big (and tiny) word spacing is something recognized as a problem for the reader when you have to format a text (hence the introduction of hyphen, etc.).  Your eyes (your brain) won't recognize two words as distincts without a min. size between them and on the opposite, your brain won't recognize the flow of a sentence above a max. size. All the trick is to be in between

**Comment by poire-z** [comment]
Closing this as some word spacing config (Word gap) has been added recently with #4026 and #4045
