### ISSUE TITLE
Hardware back button does not work on Android

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3816]
Hardware buttons used to work, like pressing back would go back or exit koreader. Now it does not work. It does nothing.

I tested it with v2015.11-1606-g3ead3f0_2018-03-28 on Lollipop.

thanks

**Comment by onde2rock** [comment]
The behavior was recently changed to not exit Koreader on back keys. But it should still go back when in menu.

**Comment by Frenzie** [comment]
I don't think there's really a good solution here. Android is special:

https://developer.android.com/design/patterns/navigation.html

> The system Back button is used to navigate, in reverse chronological order, through the history of screens the user has recently worked with. It is generally based on the temporal relationships between screens, rather than the app's hierarchy.
> 
> When the previously viewed screen is also the hierarchical parent of the current screen, pressing the Back button has the same result as pressing an Up button—this is a common occurrence. However, unlike the Up button, which ensures the user remains within your app, the Back button can return the user to the Home screen, or even to a different app.

The up button is the one that looks suspiciously similar to a left button, so you might be a tad confused by the official terminology.

I definitely want a history stack of some sort. We have a location stack, but that's limited to links. (And it should remain so. It's useful that way.)

https://github.com/koreader/koreader/blob/82ca050a1724737243c7938994f1fb25de432794/frontend/apps/reader/modules/readerlink.lua#L19-L21

But as to our own behavior, I am confused to find that the back button doesn't close on Android but closes on desktop. If there is to be a difference in behavior, the reverse would make more sense.

**Comment by onde2rock** [comment]
Was done in: https://github.com/koreader/koreader/pull/3745/commits/115bb281f1d1cd7f4bf53748fb6982ffbc076135

discussed in https://github.com/koreader/koreader/pull/3745#issuecomment-372932625

**Comment by Frenzie** [comment]
For the record, SDL isn't quite the same thing as the desktop emulator. On Ubuntu Touch and Sailfish, SDL is simply the app. It's certainly not impossible that switching some Android stuff over to SDL (such as `ffi/framebuffer_android` and `ffi/input_android`) could be helpful.

There's an example of an app using LuaJIT and SDL [here](https://bitbucket.org/MartinFelis/love-android-sdl2/overview). We draw directly to an `ANativeWindow_Buffer`. But through the SDL methods we already use anyway, we'd have a convenient wrapper for the exact same thing. Various SDL-related things I wrote this week would be easy to duplicate on Android, but with SDL it'd simply be there *right now* for free. 

If I have time one of my next goals is implementing multitouch on SDL. On the desktop emulator that's merely for testing, since unlike a game controller it doesn't have much practical use, but on Ubuntu Touch, Sailfish, and Android it'd be more relevant. Of course Android already supports multitouch, but that's about the only thing it does that our SDL implementation currently doesn't.

SDL is a first-class citizen, not just the emulator. Emulator-specific stuff (like `EMULATE_READER_FLASH=200`) should generally be behind flags or toggles of some sort, but can be activated by default through `kodev run`. Although in my opinion a flag for this particular feature doesn't make much sense. I can kill the program with Alt+F4, by clicking X, right-click on the taskbar → close or Ctrl+C in the terminal.

(As an aside, this is a very good readme: https://hg.libsdl.org/SDL/file/default/docs/README-android.md )

More or less correctly treating back the Android way would quit only after exhausting your reader location stack (and then probably first returning to the file browser and exhausting its location stack in turn). In practice many reader apps treat back more like "up", which annoys me. Whether ultimately quitting on should be done as a general principle is a slightly different question, but one that'd be largely moot after adding a location stack.

**Comment by onde2rock** [comment]
> would quit only after exhausting your reader location stack (and then probably first returning to the file browser and exhausting its location stack in turn).

If I understand it right, this seem to be the best approch to take. In fact, when I first began reading the code, I was little bit surprised that was not how koreader was doing it.

**Comment by Frenzie** [comment]
I think it shouldn't be too hard either, at least for the reader. We already have the link-based location stack in place (which like I said I want to keep for the `back to previous location` gesture/menu entry) so it should be easy to duplicate or adjust.

You interested? :-)

**Comment by Frenzie** [comment]
> If I understand it right, this seem to be the best approch to take. In fact, when I first began reading the code, I was little bit surprised that was not how koreader was doing it.

Btw, it's probably just that on the touch-based devices that KOReader was originally made for you already have back in the sense of previous/next page (tap in left/right of screen or swipe left/right) and that's sufficient for the vast majority of use cases. It's only on devices with a dedicated back button that the lack of a location stack becomes apparent.

There is a slight distinction between previous page and previous location, which is pretty much why we only have a previous location action. Its use case is as follows:

1. The page has a link (e.g., to a footnote).
2. You click the link.
3. You read a few pages at the link's location.
4. You go back to "previous location" (= page with original link).

By contrast, true back would offer the following less convenient alternative:

1. You're on a page with a footnote.
2. You follow the footnote.
3. You read the multipage footnote.
4. You have to execute a back action several times.

This does make me realize there's one question to be resolved in the implementation of the true back location stack: does "go back to previous location" *add* to it or does it remove several pages from the true back location stack? I'm inclined to think it should add to it.

**Comment by onde2rock** [comment]
> You interested? :-)

Hum, not really, first I'm not really sure I understand the problem and second, there seems to be a few other problem that I consider more important than this one. Sorry
