### ISSUE TITLE
Automatic warmth

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3825]
* KOReader version: v2015.11-1618-gba46376_2018-04-01
* Device: KA1

I'm not sure how Github works. Are "closed" threads still active (people reading them)? Threads dealing with natural light and automatic setting were closed, so I open a new one here. :)

Anyway I want to add some comments about this new great feature by dengste. 

1. When maximum is reached it should stay there for several hours. Even if your normal bedtime is for example 23.00, some days you just want to continue reading. :-)
For inspiration: In nickel, no matter what your chosen bedtime is, the light starts to go back to daylight around 4 a.m and is finished around 8.00 a.m.

2. There is no way to save the setting to always have the automatic warmth enabled.

3. Maybe (or maybe not) it would be a good thing to allow the users to choose their prefered maximum level, i.e. if they would prefer something lower than 100%.

4. Some fixes are needed. From my Kobo Aura One:

![reader_2018-apr-02_105019](https://user-images.githubusercontent.com/32645430/38244354-b978d9f2-373a-11e8-8851-ff6b422b30db.png)

**Comment by Frenzie** [comment]
> I'm not sure how Github works. Are "closed" threads still active (people reading them)? Threads dealing with natural light and automatic setting were closed, so I open a new one here. :)

People who are subscribed still receive e-mails but new issues are much easier to track. When you take a quick look at the issues you check what *open* issues exist for Kobo (for example). You don't wonder which closed issues might've received comments.

However, please do refer back to the issue number with `#1234`.

Pinging @dengste

**Comment by dengste** [comment]
Regarding the comments:

1. It probably makes sense to hold maximum warmth for a couple of hours after bedtime. I'm not very fond of hard-coding a fixed time like 4am in there, though. I deliberately made it possible to set any time as "bedtime", since not all people actually sleep at night, for whatever reason.

2. The setting should be saved automatically and also be synced with Nickel's configuration. Doesn't that work for you?

3. I agree it would be nice to have that configurable. I might do that, but at the moment I'm working on other stuff. The easy workaround is to set a later bedtime; the more complicated fix is to change the 'warmth' progression through the 'Configure' button.

4. Yeah, I modified my DPI setting to have smaller fonts... I guess I'll have to reduce the font size there.

**Comment by Frenzie** [comment]
Or just stick them underneath each other? :-)

**Comment by cramoisi** [comment]
or trim them. you don't need to repeat warmth under the warmth section (or just auto for automatic) ; and you could say max for maximum. There is a similar thing in the configure menu : your "save settings" overflows the button ; but since we are in the settings menu just saying "save" is enough, i think (I made this change on my ka1)

**Comment by gerhaher** [comment]
Thanks for your answer @dengste!

> It probably makes sense to hold maximum warmth for a couple of hours after bedtime. I'm not very fond of hard-coding a fixed time like 4am in there, though. I deliberately made it possible to set any time as "bedtime", since not all people actually sleep at night, for whatever reason.

Yeah, 2 or 3 hours would be fine.

> The setting should be saved automatically and also be synced with Nickel's configuration. Doesn't that work for you?

No, unless there is something more I must do (except for ticking the Automatic warmth box). Every time I exit KOReader the automatic warmth box becomes unticked.

**Comment by AlanSP1** [comment]
There could be setting below setting for achieving maximum warmth, something like: **Hold it for:** and there you set for how long you hold maximum value.

**Comment by gerhaher** [comment]
> That's weird. Have you modified KOBO_LIGHT_ON_START by any chance?

In what way? In the "Advanced setting" I have set KOBO_LIGHT_ON_START to 20. Nothing else.

**Comment by dengste** [comment]
> No I don't think so. In what way? In the "Advanced settings" I have set KOBO_LIGHT_ON_START to 20. Nothing else.

Well, if you set KOBO_LIGHT_ON_START to 20, koreader does not read the frontlightsettings at all but simply sets intensity to 20. This also applies to the warmth settings, including automatic warmth, so that's why your settings does not stick. If you set it back to -2 (which means syncing with Nickle) it should work. Maybe we should change that. This whole KOBO_LIGHT_ON_START thingy is a bit confusing.

**Comment by gerhaher** [comment]
You are right. Now it works.
I've had that setting for a long time for some reason I don't remember now.

Thanks for your time and help!

**Comment by poire-z** [comment]
> Maybe we should change that. This whole KOBO_LIGHT_ON_START thingy is a bit confusing.

I had some thoughts about that in #3103 - but forgot about them (as all the frontlight bugs had finally been solved, I figured it was best to not touch that anymore)

**Comment by dengste** [comment]
I've reduced the text in the widget, and max. warmth is now kept for 2h after bedtime. What's left is to make this configurable, but first I want to work on light sensor support.

**Comment by Frenzie** [comment]
For light sensor, if reasonably possible it would be preferable to generalize the currently Kindle-specific https://github.com/koreader/koreader/blob/7a28c7d7aa5a38e6f3acb5ee9246017c96e8d8ff/plugins/autofrontlight.koplugin/main.lua

**Comment by Frenzie** [comment]
At a glance the most important part of that is:

https://github.com/koreader/koreader/blob/7a28c7d7aa5a38e6f3acb5ee9246017c96e8d8ff/plugins/autofrontlight.koplugin/main.lua#L55

Which leads to:

https://github.com/koreader/koreader/blob/7a28c7d7aa5a38e6f3acb5ee9246017c96e8d8ff/frontend/device/kindle/device.lua#L141-L154

Doesn't look hard in principle, depending a bit on what the Kobo in question outputs. Which Kobos have light sensors? The One and the H2Ov2?

**Comment by dengste** [comment]
It seems the Kindle outputs 16bit unsigned, and the Kobo does as well. There are two issues with the current "ambientBrightnessLevel": The output value in [0 4] is not granular enough. It is OK for deciding whether to turn frontlight on/off (which is what the autofrontlight plugin does), but not for setting the frontlight level depending on the ambient brightness. The second issue is that the Kobo has two sensors: one for visible light (sensitivity peaks around 450nm) and one for infrared (around 850nm). The latter can be used to detect sunlight, as artificial light usually does not emit as much IR as the sun. I think in Nickel, turning frontlight on/off is done solely depending on IR light (the option says "turn off in bright sunlight"), whereas the frontlight level is set depending on visible light (I think simply "the more, the brighter").
So I think of extending the interface to have 'visibleBrightness' and 'IRBrightness', both returning 16bit unsigned. I think it would make sense to have 'powerd' use a 'light_sensor' object for that, so that we can generalize on different sensors, just like we do for the frontlight.
Unfortunately, I don't know which Kobos besides the Aura One have light sensors (and which ones and how to access them).

**Comment by poire-z** [comment]
Cross ref #5372

**Comment by poire-z** [comment]
Implemented by #8129.
