### ISSUE TITLE
Can't set Page Overlap Enabled/Disabled as default

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#3932]
As of right now, tapping-and-holding on "Enable" or "Disable" under Page Overlap does not allow setting as default. This is inconsistent with other UI behaviour (and annoying to me because I use that feature often).

Thanks.

**Comment by Frenzie** [comment]
Looks like that whole submenu has a TODO for a rewrite: 

https://github.com/koreader/koreader/blob/229c492979b89a70f6660a1d00874caaa488c70a/frontend/apps/reader/modules/readerpaging.lua#L184-L203

**Comment by KenMaltby** [comment]
I thought there were more options, at one time, but there are "Page overlap >" options to: Disable, Arrow, or Gray out.

**Comment by ersi-dnd** [comment]
@KenMaltby 
I have not noticed that Page overlap would be enabled in new books that I open. I have to enable it, then it stays on for that particular book.

When in Scroll Mode, Page overlap menu item is grayed out. And the tiny triangle is not there, so evidently Page overlap is off in Scroll Mode and cannot be enabled at all, because the menu item is grayed out.

"Gray out" option for Page overlap is visually stunning, but not much of a use when you are trying to read the grayed out half. The tiny triangle is a better option when the user's plan is to read both halves of the screen.

**Comment by ersi-dnd** [comment]
There's also a DSHOWOVERLAP setting in the Advanced configuration thingie. As far as I can see, changing it has no effect.

**Comment by KenMaltby** [comment]
I don't see why there would be any page overlap, with scroll mode.  I almost never use the scroll mode though, so it is not something my opinion should impact on much.  It would be hard for the developers to establish this kind of issue's impact on users.  For my usage having it a "per book" setting is fine.  In your case, where you have a number of similar documents and have custom settings in place, having it applied to all documents as a default, might make sense.  I am always for more user options.

**Comment by ersi-dnd** [comment]
I think page overlap is rigidly off in scroll mode because in scroll mode it scrolls a full-page length by default. It either didn't occur to anybody that someone might scroll a half-page length or the feature is not completed yet. 

When scrolling a half-page length, I don't see why the page overlap indicator should not be there. Half-page scrolling is there in some of my most favourite apps, such as Elinks, w3m, less, and Ebookdroid.

**Comment by hius07** [comment]
The issue can be closed (with https://github.com/koreader/koreader/pull/8180).
