### ISSUE TITLE
how to reduce line height in table of content

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#4007]
* KOReader version: all ?
* Device: all

Don't know why it's only strike me now but i found there is too much space between items in the TOC. It's probably good as it for touching and following link but I was wondering if it's possible to reduce the space between items (don't know if it's related to the recent cleaning of css, @poire-z ?)

**Comment by poire-z** [comment]
That Table of Content is a widget built by the lua code and has nothing to do with crengine and the CSS or styles stuff.
But you can select the number of items per page since #3589 (you have to switch to File browser to access the Items per page menu, it's a global setting that affects most of the list-like widgets).
I guess with more items per page, there will be less space in between items :) (I have it set to 20 on my GloHD)

**Comment by cramoisi** [comment]
@poire-z yup, i've read the widget before asking. I've always thought the "items per page" option was filemanager related only (and was puzzled because in koreader actual default behavior (with coverbrowser) the list can't exceed 10 items even if you don't display the cover. So I set it to 10 and this explains that.

I think KOReader needs a "first run wizard", it would auto-solve a lot of questions regarding basic configuration.
