### ISSUE TITLE
Idea: Koreader option to edit and save text files? 

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#4033]
* KOReader version: all
* Device:all

#### Issue

As we have keyboard implement in koreader, and viewing text documents is not a problem, we have file browser, why not add option to edit and save text files? 

Lua language has option to save files. 

Would it be hard to create editable area? 

This way we could edit configuration e.g. News downloader config right from koreader file browser.

**Comment by cramoisi** [comment]
I would probably use it to make and edit basic list files

**Comment by ersi-dnd** [comment]
There already is a terminal emulator in Koreader. Can nano (or vi, or both) be bundled with it?

**Comment by NiLuJe** [comment]
We can't reliably support anything non-ASCII on Kobo because the libc setup is broken, and locales are broken, so widechar support is broken.

We'd need something with a self-contained libc & locale code... Right now, the only thing where I can get proper unicode handling on Kobo is busybox, with very careful settings...

**Comment by NiLuJe** [comment]
Busybox only has a very basic vi applet, so I'm not sure how fun to use that would be...

**Comment by mwoz123** [comment]
But do we have to do this via terminal +separate app?

We already have virtual keyboard, and single line editable text field. 

Can't we just make single line editable widget bigger (full-screen?) with mulilines?

Then few buttons (could be bottom bar) : save, discard and maybe arrows( move up, move down, left, right) ?
For open we already have file browser.

I don't know have about keyboard arrows, but IMHO basic "save"/"discard" backend shouldn't be too complicated..

**Comment by mwoz123** [comment]
ps: "teminal" plugin now works this way ->open editable text input -> user type command -> process -> hide editable text input -> show read-only multilines text popup.

**Comment by Frenzie** [comment]
So just take it, adjust it slightly, and see what happens. ;-)

Perhaps I'm speaking mainly for myself, but I don't think too many people would be interested because in the unlikely event that you'd want to edit a text file you already have other options for basic text editors. E.g., as part of vlasovsoft launcher or one of the myriad of choices on Android.

**Comment by mwoz123** [comment]
> So just take it, adjust it slightly, and see what happens. ;-)

UI changes are still big thing for me. Are you saying it cannot be done this way?

**Comment by robert00s** [comment]
Similar: #1719
