### ISSUE TITLE
lua development problem - use TextEditor plugin in NewsDownloader

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#4073]
#### Issue
I'm trying write code that use Text Editor plugin ( #4070) in news-downloader plugin so it would be possible to edit configuration.

I found that  `texteditor` should be added to `package.path` because it's not in path.

So I added it to newsdownloader:
```
package.path = "plugins/texteditor.koplugin/main.lua;" .. package.path
local TextEditor = require("plugins/texteditor.koplugin/main")
```
but then I've error in console:
```
07/12/18-12:32:31 WARN  Error when loading plugins/texteditor.koplugin/main.lua plugins/texteditor.koplugin/main.lua:5: loop or previous error loading module 'ui/widget/pathchooser'
07/12/18-12:32:31 DEBUG AutoSuspend: deprecateLastTas
```
Moreover with that not only NewsDownloader but also TextEditor is not visible in menu.
Without upper lines they both  are visible in menu and work.

Can someone help?

**Comment by Frenzie** [comment]
Is there a particular reason you're trying to shortcut the plugin system?

**Comment by mwoz123** [comment]
I don't understand. I'm trying to import TextEditor in NewsDownloader. 
So it can be used there (in newsdownloader `main.lua`) for editing news downloader feed config (feed_config.lua)

**Comment by poire-z** [comment]
You can't really use a plugin from another plugin.
If you want to use it, it should be a proper widget in frontend/ui/widget/.

But please hold for a few days, as I'll need some time to correctly fix inputdialog/inputtext/scrolltextwidget/textboxwidget to better handle multi pages text. If done right, this should solve most of your #4070 issues, as well as a few others (like editing huge highlights), and you could remove the word "basic" :)
I think you'll be able to just use inputdialog from newsdownloader (or a frontend/ui/widget/texteditor).
Your texteditor plugin can stay, as it will provide the standalone file browsing/saving feature, but it will use this improved inputdialog or a proper texteditor widget.

**Comment by mwoz123** [comment]
Seriously? :O
Is it a koreader limit? Or lua limit?
Anyway IMHO it seems stupid limitation :/

Re-using this plugin in other koreader parts (e.g. To be able to quickly change news downloaded feed config) was the main reason why I started to writing it:/

Not sure if I'd be able to change it to widget..

**Comment by Frenzie** [comment]
Plugins can communicate through various means so that shouldn't be an issue, but as @poire-z said in this case it makes more sense to improve the widget.

**Comment by poire-z** [comment]
> Seriously? :O
> Is it a koreader limit? Or lua limit?
> Anyway IMHO it seems stupid limitation :/
> Any workarounds?

There is only one workaround: you studying the code base, before racing at doing things with only a vague idea of where you're in...

> Re-using this plugin in other koreader parts (e.g. To be able to quickly change news downloaded feed config) was the main reason why I started to writing it:/

So, you start to write things without really understanding what you need? :|

No koreader part _re-uses_ any plugin. They re-use **widgets**.
Plugins are standalone features, that provide services to the user, register to menus, listen for events... to do some stuff. And to do that, plugins _use_ many **widgets**.
(Plugins and widgets are pure koreader things, that's how koreader is architectured. They are not related to lua.)

So, what did you write?
You wrote a plugin that can be launched from the menu, present an empty **ImputContainer**, use a **Button** to launch a **PathChooser**, allowing to select a file. Your plugin does indeed read the file content, feed it to the **InputContainer**, and have a callback called so that it can save the content to the file back.
Which is **nice**, as some people wanted that.
But what's lacking for it to be usable is an InputContainer that allow editing text on the 2nd++ pages, and where keys (arrows, del, append) behave like in a proper text editor. And an ImputContainer that can be sized to correctly fit the available space above the keyboard. (In case you read the posts here as little as you read the code base, I repeat: I am fixing this for you, don't go at it! wait).

How did you plan to use your plugin from NewsDownloader?
You don't need any PathChooser. You mostly only need the InputContainer, and stuff to read and save the file.
Would you need to show the `Open` button? No, that would be confusing, the user could open another file, how would you know that, what would you do?. From NewsDownloader, you would directly launch it with the filepath of `feed_config.lua`, or its content, and you don't need a `Open` button. Only a `Cancel` and `Save`.
So, from there, you don't need much of your TextEditor plugin. You just needs an InputContainer widget that is functionnal.

From NewsDownloader, you would have 2 options:
- read the content of `feed_config.lua` , instantiate an `InputContainer` with that content string, and have a callback save that string to the file. That's it: you load and save the content in the NewsDownloader code. You don't need anything else, no plugin, no other widget that this InputContainer.
- the InputContainer only deals with a text string. You could write a proper `FileEditor` widget, that would get provided a file path, load the file content, instantiate a InputContainer, and have a callback called to save the content to the file. With that, your NewsDownloader would just instantiate a `FileEditor` widget and don't even need to do the save/load, and that would be one more available widget for other developers to _re-use_. And for your TextEditor plugin to re-use too.

But please stick to the first option for now.

**Comment by mwoz123** [comment]
I wrote TextEditor as plugin beacuse:
- I know not everyone want this feature
- feature might not be accepted as Koreader core feature,
- I had idea (shared with society) about editing text and how it could be written  
- I already wrote koreader widget, so it was something I should be able to write alone or with some help
- I thought writing this as plugin (rather than only part of news-downloader) would make it reuseable, but now I know it's untrue. [I didn't find entry in koreader wiki/api saying widget can't use another widget. Maybe I overlooked it.. But if not hope you don't ask me to read all PR comments...]

When I'm not sure I try to share my thoughts/ ask for help when I couldn't solve problem.

I would like to believe in your post you're not saying that I shouldn't ask and should be expert in lua & koreader to write here..

ps: I spend additional time for learning/developing "open" functionality as I was sure TextEditor plugin won't be accepted without "open" feature.

**Comment by poire-z** [comment]
You still look confused with your use of the words _widget_ and _plugin_.
Forget my harsh words in my previous post, and please re-read it. I understand what you wanted to write and do, and when I wrote _So, what did you write?_, it was not criticism: it was just me explaining to you what has been written so far, and why you _don't need_ to use your TextEditor plugin in your NewsDownloader plugin (even if you understand now you _can't_ use it :) 

May be this will get clearer to you when you proceed with both your plugins, but it's necessary it becomes clear.

I'll add a few things, using different words:
- I fixed and enhanced the **InputDialog widget** in #4084. This is **THE unique text editing widget** in the koreader code base (frontend & plugins): all the code that need user to input text use it.
- you should think about your TextEditor plugin more as a **File Editor plugin** to avoid confusion: it allows selecting a file (using the **PathChooser widget**), and editing it (using the **InputDialog widget**). The only thing that your plugin needs to additionally do is reading and writting the file.
- your TextEditor plugin, being a File Editor, absolutely needs a `Open file` button :) The **text editing widget** does not, as we can provide it with strings that do not come from files.
- your **NewsDownloader plugin** does not need a `Open` button either: you know which file you want to propose the user to edit. So, it only needs the **text editing widget** (which now can work as a full screen text editor), and to additionally read and write the file. This (reading/writing) is indeed duplicated between your 2 plugins, but you may additionally want to do some stuff in NewsDownloader, like verifying that it's proper lua before saving it to the file, so it won't crash koreader or your plugin and have the user stuck. So, that's dedicated work that doesn't need to be in your TextEditor plugin.


> I would like to believe in your post you're not saying that I shouldn't ask and should be expert in lua & koreader

I didn't mean to be cruel. You can ask, but please read & re-read & re-re-read our answers. What I wrote in this post and the previous one should be clear to you before you go on.

A few more words about plugins & widgets:
- plugins are standalone features: you should be able to remove or add one without anything breaking (including other plugins) - they still are part of the shipped koreader, and there wasn't a easy way until recently to disable any of them - so they are part of koreader.
- widgets are re-usable components, so all features can use them: removing one could break tons of things (the InputDialog text editing widget was bad at multi lines editing - it didn't really bother me, until you came in with your TextEditor plugin that was just unusable with the broken InputDialog widget - we could have co-piloted you to fix it, but that would have been hell for both you and me :) so I finally spent 20+ hours fixing it so you can benefit from it and we don't have to live with a broken text input widget).

**Comment by mwoz123** [comment]
yeah I meant "plugin" where I wrote "widget". 
Ok.Thanks.

> verifying that it's proper lua before saving it

btw is there a way to do that? I thought about  running download feeds to verify.

**Comment by Frenzie** [comment]
You can do some kind of isolated pcall I imagine.

**Comment by poire-z** [comment]
Answered and applied in #4126.
