### ISSUE TITLE
Editing wiki - providing some form of manual

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#4102]
I see I can edit wiki and make changes, create new files. I'm willing to step by step add most useful info about how to use koreader, but I will need help.

For this, we can use this thread.

For starters, I created this page: https://github.com/koreader/koreader/wiki/Screen-saver-options and also linked it in this page: https://github.com/koreader/koreader/wiki/Features-list (at the end of list, screensaver).

At the moment I'm not satisfied how it looks, so I need suggestions. Also, I'd like to have settings.reader.lua examples within wiki, to make things easier for people to use.

First, to make this screensaver page full, can I have all options within settings.reader.lua file (i.e. how it should look within this file with syntax) here and what editing to use to make it look nicer than it looks now.

In the future you can use this thread to notify me about new features to be added to wiki (and old that are still missing).

Also, we need to have some form of uniformity within wiki, my general idea is to have one page with all features and within it linked all pages with further explanations and examples. And, of course, if some of you are willing to help make wiki with me, great.

**Comment by Frenzie** [comment]
Note that I put in quite a bit of effort to create the side nav.

**Comment by robert00s** [comment]
@Frenzie 
I want to add screenshots from KO and refresh another. Where can I put png files. Another repository? Add folder to existing https://github.com/koreader/koreader.github.io? I can also create new issue with screenshots https://help.github.com/articles/adding-images-to-wikis/

**Comment by poire-z** [comment]
Thanks for your promising work on this ! :)

(I discovered too the wiki syntax is different than this github issues/PR syntax which is ridiculous... didn't really want to learn a new one so...)

A few links to some PR (that I remember, so most are mine :) that added not-yet-advertised-on-the-wiki features, and/or possibly undocumented (except in the PR) gestures/small features:

- Hold on buttons/titles/menu items to get more info (not many for now, but good to advertize) #3952 #3967 #3980
- Hold on a single word > dict (because that's the most common use) - Hold more than 3s > highlight menu with more options #3199
- EPUB: follow link/Back with Swipe (useful with small fonts) + markers + location stack #3207 #3202 #3669 
- EPUB: hold on image to view image in ImageViewer (which allow zooming, panning...): #2493 #2519 #2522.
- EPUB: limited SVG support #2832
- EPUB: alternative TOC from document headings (Hold on "Table of content") #4011 
- EPUB: Style tweaks #3944
- Dict & wikipedia histories #3161 #3549
- Dict/Wiki: cancel lookups that take time with Tap #3228
- HTML dictionary support #3573 (and tweaking the final HTML is possible with tricks from #3585)
- Wikipedia lookup results with images (tap on image to see image caption, hold on image to view full screen) #3609 (the animated image may find its place in the wiki "Wikipedia" page)
- Wikipedia articles can be saved as EPUB #2507 
- Some widgets can be moved/made transparent (to see text under them if needed) #3636 (animated image available too)
- Bookmarks can be edited/renamed by taping on them or, in the bookmark list widget, by holding on them  #3275
- File browser: hold on filename for popup menu
- Book information (and other KeyValuePage stuff): hold on trucated item to view full text #2993

There are many others that are available thru menus (like Style tweaks) that are obvious/self-documenting, so less need for a long article, but they should probably be mentionned in the Feature list page (or some decicated pages for EPUB/HTML vs DJVU/PDF as these have quite different features).

**Comment by Frenzie** [comment]
@robert00s You should probably be able to just put 'em in the wiki repo if you clone it locally. That's also how I organized it in folders, which is something only of use when checking out the repo.

Note that you could consider preprocessing PNGs with pngquant. It's lossy, but especially for b&w images like ours there should be no visible quality loss.

I wrote down some tips here: https://fransdejonge.com/2017/03/image-optimization-guide/#optimizing-png

**Comment by KenMaltby** [comment]
Perhaps, in time, a summery with link to the full item in the manual could be included in a long press of the menu titles.  This could be the in-line manual, that the user could come to expect, so they can understand menu options and how they can be properly used.  Having them addressed first in the wiki should make adding the inline tip/info much easier.

**Comment by robert00s** [comment]
@Frenzie Thanks for info. It works. 
I'll use pngquant after adding more PNGs.

**Comment by AlanSP1** [comment]
@Frenzie 
> Note that I put in quite a bit of effort to create the side nav.

You mean in wiki? How to add certain links to it? I see there's some links on the side (that's why I used already existing Feature list page, it is there), so it is possible...

**Comment by AlanSP1** [comment]
@poire-z 

> A few links to some PR (that I remember, so most are mine :) that added not-yet-advertised-on-the-wiki features, and/or possibly undocumented (except in the PR) gestures/small features:

Thanks, I'll go through your list and add info one by one, as well as explanation if it is needed.

**Comment by AlanSP1** [comment]
@robert00s 
I'm not sure with this images, can I just hot link them within wiki (I guess I can).

And yes, setting for targeting single image, is it single? Or it is just understood if you target single image?

Also, can you put here examples of settings.reader.lua commands for poweroff, sleeping, etc. commands, to include them within wiki (as syntax is very important, I already managed to delete my settings.reader.lua without having backup before).

**Comment by AlanSP1** [comment]
I'll work slowly (to not loose interest soon), but hoping to work steady. So, I added page about pressing and holding: https://github.com/koreader/koreader/wiki/Press-and-hold-function

**Comment by Frenzie** [comment]
> I see there's some links on the side

Not "some" but all. One of the ways to edit it is through the edit button (next to "Installation").

**Comment by AlanSP1** [comment]
Thanks, I saw a bit later edit button.

**Comment by AlanSP1** [comment]
I mentioned HTML dictionaries, but I'm not exactly sure how to install and tweak them. It would be good if someone who knows exactly what to do to add some more info on the subject: https://github.com/koreader/koreader/wiki/Dictionary-support

**Comment by poire-z** [comment]
HTML dicts are just stardict dictionaries, that happen to have the text in HTML.
You can't really know when you download such a dict if it is HTML or plain text. Details in #3606.
But KOReader should detect that and use the HTML widget or the text widget accordingly. And even do the right thing if the HTML is bad and MuPDF (the HTML rendered) doesn't like it (https://github.com/koreader/koreader/issues/3606#issuecomment-361204753).
So, nothing special about installation or usage (dunno if it even deserves its own section on your page).

As for tweaking them, that will be for advanced users, and they'll have some (lots of) work to do. I don' think there will be many that interested in speding the time, so the issues/PRs you linked may help them, so links should be enough. (You can add #3606 then).

**Comment by AlanSP1** [comment]
Thanks, I changed accordingly part about HTML dictionaries, with added link to sample files.

**Comment by AlanSP1** [comment]
I just started file manager page (https://github.com/koreader/koreader/wiki/File-manager), but it needs much more info than what I know about it.

Can you please give me most important and relevant PRs and info about File manager?

Also, you can mention other important PRs and features to be mentioned. It is easier to me if you give me information as @poire-z give with his first post here, and I incorporate it afterwards, item by item into wiki.

**Comment by Frenzie** [comment]
Btw, I also try to write about some of this stuff in release notes, see for example https://github.com/koreader/koreader/releases/tag/v2018.04.10-beta ;-)

**Comment by AlanSP1** [comment]
Thanks, excellent suggestion, I'll look in release notes and take them as starting point for adding info in wiki.

**Comment by Frenzie** [comment]
@AlanSP1 Sorry, I must've missed or forgotten to respond to your question in August. Could you please e-mail me (see [here](https://fransdejonge.com/about/)) or send me a PM on Gitter?

**Comment by Frenzie** [comment]
We now have a proper manual at http://koreader.rocks/user_guide/ thanks to @offset-torque.

See https://github.com/koreader/koreader/issues/11147 if you think anything's missing or unclear.
