### ISSUE TITLE
Auto crop not working on some pages

### ISSUE THREAD

**Issue by onaka-itai** [koreader/koreader#4106]
* KOReader version: v2015.11-1735-g14e7730 (Latest release)
* Device: Kobo Aura HD

#### Issue

Similar to #3376, using "fit to content width" sometimes does not work as it should. I checked the image(s) in Photoshop and it doesn't appear to have off-white pixels that would prevent accurate detection of the actual content. 

I was wondering if there could be an option to set some sort of tolerance for cropping out white areas around the border with auto crop, rather than setting it to semi-auto and adjusting it every other page.

Using reflow removes a bit too much on lighter-inked pages, so I would rather not use that.

#### Steps to reproduce

Enable auto-cropping, and set zoom mode to "fit to content width."

Open the following files on Koreader:

This page gets cropped and fitted with no problems. 
![working_crop](https://user-images.githubusercontent.com/12203640/43180905-69604b28-8f8f-11e8-95bf-1277aaf0e483.png)

This page does not:
![nonworking_crop](https://user-images.githubusercontent.com/12203640/43180931-9590b732-8f8f-11e8-9288-358095b20d8e.png)

I'm not sure what's causing it to work on the first page, but not the other. The second image does not have an off-white border running around it, just as it is on the first image.

**Comment by seacatwu** [comment]
Yes, I have this problem too.
:(

**Comment by hugleo** [comment]
I believe the problem was introduced in https://github.com/koreader/koreader/issues/970 :

https://github.com/koreader/koreader/blob/b4424b468591ac8a7f4bedd343a4841c6797c5f1/frontend/apps/reader/modules/readerzooming.lua#L529-L535

It seems that the crop values are included in the ubbox_dimen var, and self.view:onBBoxUpdate(nil) with nil is being called.
I've changed for test to self.view:onBBoxUpdate(ubbox_dimen) and got the image cropped.

**Comment by Frenzie** [comment]
Isn't that describing the situation before that else was introduced to work around whatever the problem is there?

**Comment by hugleo** [comment]
I didn't fix it, just test like reverting back :)
