### ISSUE TITLE
History menu shows deleted .lua files

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#4118]
* KOReader version: 2015.11-1564
* Device: Kobo Glo

I don't know if this is still happening after the 2015.11-1564, but the History menu is getting cluttered with .lua (deleted) entries.
![deleted files](https://user-images.githubusercontent.com/8684739/43343045-817ff5c2-91ed-11e8-8fe2-b52026e9733e.png)

Sorry in advance if its already fixed...

**Comment by poire-z** [comment]
It's already fixed, if you want it fixed (some people don't) :)
See https://github.com/koreader/koreader/pull/2583#issuecomment-282509524 and #3129:
<kbd>![othersettings](https://user-images.githubusercontent.com/24273478/29665061-9217c074-88d2-11e7-8ce7-10a2886c012e.png)</kbd>
(last checkbox)

**Comment by embryo10** [comment]
Actually, I don't want to automatically remove deleted files from History, since I like to have a reference to the already read books.
The problem is that the deleted entries are not books but instead (maybe) auto-generated files from KoReader..
..so its not fixed :o(

**Comment by poire-z** [comment]
Oh, right, didn't notice that (and read your words too quickly) :|
~~I've never ever seen such entries, even with nightly from 5 months ago. Worth an update to a recent nightly.~~

Mhhh, I may have one such .lua. Are these entries from documents generated by the RSS New downloader plugin?
History entries should be in the `history.lua` file, but I have one named as your file in the obsolete `history/` directory: 
 "koreader-emulator-x86_64-linux-gnu-debug/koreader/history/[#koreader#koreader-emulator-x86_64-linux-gnu-debug#koreader#news#Reuters_ World News#] 18-07-16_22-58_After pummeling allies_ Trump ends wild Europe trip with Putin embrace.html.lua"

Do you have that kind of file too?

https://github.com/koreader/koreader/blob/c1965ea8a9877a86293f90e47bbc370db2be1125/plugins/newsdownloader.koplugin/main.lua#L391-L399
I guess it removes it from history, and also remove the docsetting, and some other code executed after try to save the docsetting or history, and it fallbacks to some old history/docsetting method to do that...

**Comment by poire-z** [comment]
Had a hard time trying to reproduce that, but I did:
News downloader > Download News
Go to news folder, open some file
While this file is displayed: News downloader > Remove news
Exit reader or switch to another document: the docsetting for the file that was read has to be saved, but the file and its container directory do not exist anymore: the docsetting code fallbacks to another place to save the book settings:
```
closing reader
closing document
cre cache used: none
close document
NewsDownloader: document_full_path: /koreader/koreader-emulator-x86_64-linux-gnu-debug/koreader/news/Reuters_ World News/18-07-28_06-35_Cambodia sets up polling stations_ officials expect 60 perNewsDownloader: news_download_dir_path: /koreader/koreader-emulator-x86_64-linux-gnu-debug/koreader/news/
NewsDownloader: removing NewsDownloader file from history.
close widget ReaderUI
save default dictionary
Write to  /koreader/koreader-emulator-x86_64-linux-gnu-debug/koreader/news/Reuters_ World News/18-07-28_06-35_Cambodia sets up polling stations_ officials expect 60 percent turnout.sdr/metadata.
==> Write to  ./history/[#space#kobo#koreader#koreader-emulator-x86_64-linux-gnu-debug#koreader#news#Reuters_ World News#] 18-07-28_06-35_Cambodia sets up polling stations_ officials expect 60 perce_refresh: Enqueued full update for region 0 0 600 610
no dialog left to show
quitting uimanager
```

I don't think this history/docsetting behaviour need to be changed (as it provides a safe fallback to save the docsetting somewhere in case of problem, instead of just losing it).

But in the same way we don't allow in History to delete the currently opened document, NewsDownloader should may be now allow "Remove news" while a news document is opened. Pinging @mwoz123 .

**Comment by poire-z** [comment]
Mhhh, obviously, as your files are EPUB, there are not from RSS/News Downloader... (but there's still this small issue with NewsDownloader).
But could it be some similar issue with directories or file disappearing ?
Do you have files in your `koreader/history/` directory ?

**Comment by mwoz123** [comment]
I don't quite understand..
should I block/remove option to remove all news when koreader has open book, and leave it when it's in file browsing mode?
The issue with epub files in certainly not caused by news downloader

**Comment by poire-z** [comment]
> should I block/remove option to remove all news when koreader has open book, and leave it when it's in file browsing mode?

No, not that radical :)
You should check if the currently opened book full path starts with your News downloader root directory. 
If yes, better to not delete the file currently read, and the easier solution is to not delete anything :)
If no, it's another book, not a news file, and you can still allow deleting the news dir.

But I dunno, may be once we understand the why & how of this original issue, we'll end up avoiding writting the settings in that old `history/` dir, and you won't need to change anything (you could remove the news dir even if a news file is opened, the file will be deleted, no pb for the reader, but when you close and koreader wants to save the sidecar file, it won't be able to, and may just drop it - if we decide that is fine).
So, let's wait a bit.

**Comment by poire-z** [comment]
> But I thought that this was not still the case, since starting auto-generated the .sdr folders.

That's no more the case indeed, but there is still code that deals with them, and under certain conditions, there may be unwanted fallback code at play, which I suspect may still be the cause of what you notice.

Well, I've never seen anything like these `.lua (deleted)` since I use KOReader (except for that NewDownloader try out I did), and it looks like most used don't have them.

Any more info you could give us (I'm blank with ideas just looking at the code) ?
- If they don't come from the old history directory, are these `.lua (deleted)` entries really in the history.lua file ? If not, any trace of them anywhere else?
- Any correlation with the "Finished" status of the epub (they appear just after one of these - except for the Alexandra Braken, but may be on next page? - and that unfinished James Blish doesn't have it). Anything specific you may have done with the files that have this `.lua (deleted)` ghost vs those that don't have it?
- 100% sure it's not your KOHighlight that could have generated that? :)

**Comment by embryo10** [comment]
It started with the 1564 update.
Every book I opened, produce that (epub/pdf).
No entries in the history.lua
I was on vacations, so no KoHighlight there.
Just updated to 1800 and all is back to normal. No more ghost .lua (deleted) files...

**Comment by poire-z** [comment]
> Just updated to 1800 and all is back to normal. No more ghost .lua (deleted) files...

You mean that those that were there (on your screenshot) are no more there with 1800 ?! (and you didn't `Remove from history` them?). And your real good history entries are still there?

So, issue closed?

**Comment by embryo10** [comment]
Yes, that's correct.
Issue is closed OK.

**Comment by embryo10** [comment]
After some restarts and checking other things, I just open the history and there are back...
... and I must been mistaken about the history.lua too, cause now there are these epub.lua entries there.

**Comment by poire-z** [comment]
Well, we need to find ouy what may triggers this.
Backup your settings.reader.lua and history.lua.
1) remove the history.lua, start with none, open a few books, close them: does History have the .lua(deleted)? If yes, try to find on what conditions thay may happen, or not.
2) remove your settings.reader.lua, start with default settings, open a few books...

Just to see if it's a "corrupted" history.lua, or some obscure settings combination in your settings that could cause that.

**Comment by embryo10** [comment]
Actually, all the .lua files I have in history are from books I've opened with the 1564.
I could not create a new one with the books I tried.
I tried with the old settings/history and without them.
There is a possibility that it needs some reading time for the file creation, but I will check that after some days, when I get to read some more.

**Comment by mwoz123** [comment]
>You should check if the currently opened book full path starts with your News downloader root directory.
If yes, better to not delete the file currently read, and the easier solution is to not delete anything :)
If no, it's another book, not a news file, and you can still allow deleting the news dir.

But currently only on document close I remove current file (if it's from news downloader dir) from history.
There's no other code for removing news from history (at least I don't know other code).
How would I then remove it from history?
As far as I know this code shouldn't block removal of any other files (from non-news downloader dirs).

**Comment by mwoz123** [comment]
ok. now I get it;) 
Thanks. 
Please ping me again if it turns out N.D. needs to be changed.

**Comment by poire-z** [comment]
I guess I fixed the future appearance of any new .lua file in your History in #4138.
You may have to manually remove the past ones.

Why that happened to you, I'm not sure.
I guess for you to have these .lua entries in History, your books may have, at some point, been in a readonly directory/filesystem, that later became writable (that's why your koreader/history/ is empty). And the .lua came from some backup of the files in koreader/history/ named with .old that weren't discarded when merging the 2 history sources).
Are your book son your Kobo Glo SD card (wikipedia tells me it has a SD card slot) ? Coud that SD card be at some occasion read-only ? or corrupted to the point creating files (sidecar directory + metadata.lua) could occasionally fail, so it's created in koreader/history/ - and later succeed ?

**Comment by poire-z** [comment]
@mwoz123 : ok, no need to do anything (the docsettings of the currently read News file will be saved in koreader/history/ , and stay there, but I don't really care :)

But another thing: you may want to change the `C.remove` to `os.remove` in:
https://github.com/koreader/koreader/blob/9971eb8533528cbb86707d81770ba26b1b8aaa9b/plugins/newsdownloader.koplugin/main.lua#L358-L359
as it crashes on my emulator (if you happen to have another file in that news directory and go thru this bit of code):
`./luajit: plugins/newsdownloader.koplugin/main.lua:359: missing declaration for symbol 'remove'
`

**Comment by NiLuJe** [comment]
Yep, that's a C call, and it's called unlink in Posix, not remove ;).

**Comment by embryo10** [comment]
@poire-z The books are on the external sd card.
I never intentionally mount it as read only.

The setup includes KSM7 (I know is old, but I like to have the config files to the user partition and with no use of Nickel, I don't need to upgrade)

What I do is:
* Boot to KSM and just open KoReader.
* After some reading I could see first deleted file.
* Finishing the book, I start reading a new one.
* No mounting to external PC or anything in between.
* Always shutdowns between the reading sessions (sleep in my device spends more battery than reading)
* After some reading a new ghost entry appeared.

There are no hints of card corruption, but I can't be absolute about it.
