### ISSUE TITLE
Random screensaver with epubs

### ISSUE THREAD

**Issue by emacsomancer** [koreader/koreader#4136]
* KOReader version:  koreader-beta-20180729
* Device: Kobo Aura HD

#### Issue
Even when "use last book's cover as screensaver" is checked, when browsing an epub, the cover seems to be a random cover/page image rather than the last book's cover. Works normally with pdfs, but not with epubs.
#### Steps to reproduce
Open an .epub, make device sleep.

**Comment by poire-z** [comment]
PDFs always have a cover: it's the image of the first page.
EPUBs may not have a cover: the cover image has to be specified in the metadata. When there is no such cover in an EPUB metadata (you can check if you use a File browser Display mode that displays covers: if there is none displayed, there is none in the EPUB), the screensaver falls back to using a random image from your random image directory.
Does that explains what you observe?

There is a feature request #2917 to fallback to the first page, or select another one. Which is now possible by taking a screenshot (long diagonal swipe from one corner to the diagonally opposed one) and setting it as screensaver image, #4113 (modified since the screenshots in first post).

**Comment by emacsomancer** [comment]
@poire-z Yes, that is what I observe. So then this is known already, so I'll close the issue.
