### ISSUE TITLE
touch zone for bookmark is too large

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#4149]
* KOReader version: since image bookmark dogear scaling update
* Device: all

#### Issue
The touch zone which triggers the bookmark (dogear.png) is much larger / longer since the update (2 cm from the top) and it interferes with the page turning.

**Comment by cramoisi** [comment]
@poire-z  :-)

**Comment by poire-z** [comment]
I don't think what I did in #4081 (if that's why you're pinging me :) has any effect on the bookmark page tap area. I just changed the size of the dogear icon.
The tap area looks like it's not related to the icon size. It should still be, as it was:
https://github.com/koreader/koreader/blob/637abfdf84fb1125e05952bc73e41f80a612cb46/frontend/apps/reader/modules/readerdogear.lua#L80-L88

https://github.com/koreader/koreader/blob/637abfdf84fb1125e05952bc73e41f80a612cb46/defaults.lua#L76

This default would make it ~ 1.1cm x 1.5cm on my GloHD

**Comment by cramoisi** [comment]
That was for that. I don't know, it looks like I just noticed that now and it was always like that :) I always had the feeling that I had to touch the corner to get the bookmark... But you're right since it's like that on my pre #4081 gloHD install. ; let's close this then ;p
