### ISSUE TITLE
Problem with a symbol using Crengine

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#4196]
Hey, I have a book which has a symbol that crengine doesn't display. It is fine if I use a ebook reader at PC.

Reproduce => Go to ( "capítulo I Estado fiscal, liberdade e tributação" and then "3 As funções fiscais")

COMPUTER

![computer](https://user-images.githubusercontent.com/20425689/45029993-d3950180-b020-11e8-865f-2d797bf45eee.png)

KOREADER
![reader_2018-sep-04_085905](https://user-images.githubusercontent.com/20425689/45030265-a8f77880-b021-11e8-9c4a-d6104d8633db.png)

Is there a way to fix it?

**Comment by poire-z** [comment]
Not sure why...
Looking at the bytes in the HTML file, this symbol is the 3 bytes EF8284 in UTF8:
`2d42 223e _ef82 84_20 6469 7374 720a   |       -B">... distr.`
which http://www.fileformat.info/info/unicode/char/f084/index.htm says it's not a valid unicode character, and part of the block PRIVATE_USE_AREA ...
It's used in a P with this style:
```
p.BODY2_BODY-2-I--II--A--B {
        font-family:"Myriad Pro", sans-serif;
```
I just downloaded a (possibly fake) Myriad Pro font to see if that font would provide a glyph for this character, but no.
So, I don't know why your computer software displays it with a glyph that looks allright... May be they had the good idea to use a nice looking glyph as the replacement character for invalid characters :)

FreeSerif is the most complete font we ship for glyphs and other languages except CJK - it does not have it.

Firefox displays this miolo5.xhtml as:
<kbd>![image](https://user-images.githubusercontent.com/24273478/45035958-87b37e00-b05b-11e8-8295-984aa19b044f.png)</kbd>

I just checked to be sure with reverting the latest crengine commits (from upstream) that deal with XML parsing and UTF8 decoding: still not displayed.

How does the original Kindle/Kobo software display it ? (can Kindle display epub?)

**Comment by Eduardomb22** [comment]
The epub works fine at calibre and with Icecream Ebook reader

Kindle can't display epub, but if I convert it to .mobi, it's display like your post at Firefox: F084

Well, thanks for looking into it, and for the explain =)

**Comment by NiLuJe** [comment]
FWIW, the sane in-spec choice for a bullet-point seems to be U+2022 (•) ;).

**Comment by NiLuJe** [comment]
The Private Use block being what it is, I'm seeing a 4 in a square with Consolas in my text editor ;).

**Comment by poire-z** [comment]
Some news about this issue:
The book (Portugues para Concursos) from https://github.com/koreader/koreader/issues/4197#issuecomment-419166008 that also exhibits this problem uses:
`span.seta{font-family:"Wingdings 3",sans-serif;font-style:normal;font-weight:normal}`
and it happens Wingdings 3 uses this unicode private area:
https://www.myfonts.com/fonts/ascender/wingdings/3/ (mouse over each char to see its `Private Use U+F0xx`)
https://en.wikipedia.org/wiki/Wingdings#Wingdings_3

This Wingdings 3 font is not embedded in the epub, so I guess it works for @Eduardomb22 because you have it among your system fonts, and calibre uses it.
If you were to drop it into koreader fonts/ directory, it would currently not be used, but we can make it use it with a simple patch.

crengine checks that a font has glyphs for a-zA-Z0-9, and if not discard it (note that crengine does not do that check for embedded fonts - but it would still not use it because we don't select the symbol charmap).
But we can use in a few places something like:
```c
             bool charset = checkCharSet( face );
+            if (!charset) {
+                if (FT_Select_Charmap(face, ft_encoding_unicode)) // returns 0 on success
+                    // If no unicode charmap found, try symbol charmap
+                    if (!FT_Select_Charmap(face, ft_encoding_symbol))
+                        // It has a symbol charmap: consider it valid
+                        charset = true;
+            }
```

<kbd>![image](https://user-images.githubusercontent.com/24273478/47952479-444c9180-df70-11e8-9684-2a5d42c2812d.png)</kbd>

(Then, a minor followup question is: should we show such fonts in KOReader font lists, or just hide them there).

However, the book from this issue (Direito Tributario.epub) uses a font named `Myriad Pro` (not embedded in the EPUB - found a few downloads on the web but...), that looks like it does not benefit from this patch, and the bullet is not displayed.
If I set Windings 3 as the fallback font, I get a glyph, but it's not the bullet you get with calibre:
<kbd>![image](https://user-images.githubusercontent.com/24273478/47952550-7dd1cc80-df71-11e8-8044-8c80a9e0f57e.png)</kbd>
So, @Eduardomb22 , if you have some Myriad Pro fonts on your system, can you make them available so I can see how it behaves with "correct" Myriad Pro fonts?

A few links about this issue and workarounds:
https://bugs.chromium.org/p/chromium/issues/detail?id=489452
https://mail.python.org/pipermail/image-sig/2003-September/002433.html
https://lists.nongnu.org/archive/html/freetype/2001-10/msg00027.html

**Comment by Eduardomb22** [comment]
I have those, take a look, but I don't know if they are the correct ones. Thanks for helping with it =)
[Font.zip](https://github.com/koreader/koreader/files/2545022/Font.zip)

**Comment by poire-z** [comment]
Thanks.
Ok, nothing different with your fonts (you can remove the link), bullet is still not displayed...

**Comment by poire-z** [comment]
So, symbol fonts should be supported after #4378.
The arrows symbol in the book from https://github.com/koreader/koreader/issues/4197#issuecomment-419166008 were in Winding3, and Winding3 was correctly set as the font-family in the styles of that book (but that font wasn't embedded in the EPUB, so you need to have it in KOReader font directory).

But the sample in the first post of this issue is still quite obscure to me: the styles reference the MyriadPro font, which does not include a glyph for U+F084.
So, I assume calibre finds a glyph for it in some other fonts.
I guess calibre supports multiple fallback fonts, and @Eduardomb22 must have one that has this glyph.

KOReader/crengine supports only ONE fallback font (that can be set with Hold). So, for some books like this one that really don't set the font to use, and that don't embed any symbol font, you may need to drop a few of your symbol fonts in koreader font dir, and try setting each as fallback until you find one that displays the glyph correctly...

**Comment by Eduardomb22** [comment]
Thanks for the explain and for the fix!

**Comment by Eduardomb22** [comment]
@poire-z Do u still have this epub? I´m looking into removing the margins at the pages from this epub, but seems koreader´s margin css hack can´t do it, maybe because this epub uses @page for rendering the margins? Do you know? 
If I choose to ignore all stylies ( at koreader) the margin is correct removed, but it will also removes the margins from quotes and other stuff.

**Comment by poire-z** [comment]
I still have it.
I had a hard time finding why by just looking at the HTML and CSS. Had to hack the css inside by removing parts till I found the one that prevents the tweaks from working:

<kbd>![image](https://user-images.githubusercontent.com/24273478/50617256-82245280-0eec-11e9-84e3-1d13f103d1be.png)</kbd>

The fact that the publisher himself added `!important` makes this style still override the one we set via style tweaks, even if we used `!important` too.

We had a discussion about this around https://github.com/koreader/koreader/issues/1430#issuecomment-384998959 (I haven't re-read the whole thing).
The implemented rules then were simple: `!important` are not overriden, except by `!important` that come later.
A bit sad indeed that then, we can't do anything with books like this one of yours :|

@Frenzie : any thought?

**Comment by Eduardomb22** [comment]
Thanks. I will edit the epub and remove this !important. At least we have a way to fix it. =)

**Comment by Frenzie** [comment]
@poire-z The spec doesn't leave any doubt that user `!important` is always supposed to win out ([spec link](https://www.w3.org/TR/CSS21/cascade.html#cascading-order)), and I doubt anyone among us disagrees with the spec on that one. But as I recall you said that'd be hard to add. :-)

**Comment by poire-z** [comment]
Yes, the specs model doesn't really fit into our way of handling the various CSS.

But I think I found a solution: we'll add another lUInt64 bitmap:
```diff
typedef struct css_style_rec_tag {
    int                  refCount; // for reference counting
    lUInt32              hash; // cache calculated hash value here
    lUInt64              important;  // bitmap for !important (used only by LVCssDeclaration)
                                     // we have currently below 53 css properties
                                     // lvstsheet knows about 68, which are mapped to these 52
                                     // update bits above if you add new properties below
+   lUInt64              importance; // bitmap for important bit's importance/origin
+                                   // (allows for 2 level of !important importance)
    css_display_t        display;
```

so we know, for each !important that was set, _the importance of it's !important_ :) and whether a new !important coming from a lower importance CSS (embedded or inline styles) can override or not a !important previously set from a higher importance CSS (our external CSS + added styletweaks).
Should work without too much overhead.

**Comment by Frenzie** [comment]
Alright, works for me. :+1:
