### ISSUE TITLE
Epub does not page break on new section.

### ISSUE THREAD

**Issue by dellistic** [koreader/koreader#4207]
* KOReader version: v2015.11-1800-g0924b57_2018-07-29
* Device: Kobo Aura ONE

#### Issue
An epub book I have does not 'page break' for individual html sections (they are different html files inside the epub).
The same epub page breaks properly in nickel and also on calibre epub reader.

#### Steps to reproduce
Load the book. Go to chapter ONE. (or chapter TWO)
Instead of being a new page by itself, it has lines from the previous section.

I kept the first 6 sections of the original epub as an attached sample epub.
[sample.epub.zip](https://github.com/koreader/koreader/files/2363360/sample.epub.zip)

Notes: I'm using a freshly koreader, and ksm09. I just got my KA1 this week.
I noticed the style is 'auto' and using 'epub.css'. 
(I was researching on this topic but it seems like the problem is specific to how this book is formatted, but I don't see anything weird from the style sheet css)

**Comment by poire-z** [comment]
(I thought you were talking about the HTML 5 `<section>` tag, that we don't add a page-break for (yet), but no, your book has none. We should probably think if [some of these HTML5 tags](https://www.w3.org/TR/html5/sections.html) need this `page-break-before: always`.)

What you call section is what crengine calls `<DocFragment>`, an internal tag that it adds that contains the content of each individual HTML file of the EPUB.

And these `<DocFragment>` usually produce a page break:
https://github.com/koreader/crengine/blob/313458d174c8b1d98be5d205b5c879d74aa14652/cr3gui/data/epub.css#L11-L14

But indeed, it does not work with this book of yours.
It's not because of the embedded styles, the same happen when you disable them.
After parsing, it looks like this at the place where 2 HTML files met:
```xml
Things were looking up.</p>
        <div class="calibre1"/>
        <div class="mbp_pagebreak" id="_doc_fragment_5_ calibre_pb_4"/>
      </div>
    </body>
  </DocFragment>
  <DocFragment StyleSheet="stylesheet.css" id="_doc_fragment_6">
    <stylesheet href="./">@import url("page_styles.css");
</stylesheet>
    <body class="calibre">
      <div id="_doc_fragment_6_ filepos1934" class="calibre1"/>
      <div id="_doc_fragment_6_ filepos31176" class="calibre1">
        <autoBoxing>
          <a/>
        </autoBoxing>
        <p class="calibre_8">
          <span class="calibre3">
            <span class="bold">TWO</span>
          </span>
        </p>
        <p class="calibre_9">Nairobi was launched
```
The DocFragment should produce a page break, but it does not.

Looks like this bug is caused by the empty HTML tags at the start of the HTML files.
Adds just one of these `ZZZ` to the HTML and the page-break happens:
```html
  <body class="calibre">
<div id="filepos1934" class="calibre1">ZZZ
</div><div id="filepos31176" class="calibre1"><a>ZZZ</a><p class="calibre_8"><span class="calibre3"><span class="bold">TWO</span>
```
I guess it's when it meets a HTML node that it checks the page-break rules from the previous and next node, and the fact that the node is empty makes it may be just ignore the node and the rules...
I'll look at the code and if there's an easy fix when I have time.
