### ISSUE TITLE
[Suggestion]: provide a bitcoin address for donations.

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#4235]
Why donations?. Not sure about the infrastructure behind KOReader but I'm sure it has some costs. At least the domain koreader.rocks and/or the site hosting.

Why bitcoin? p2p, easy to use, can provide control over funds to multiple parties if required(w/ multisig), doesn't require giving personal information (like paypal or any other digital method of payment)

*Disclaimer*: I want to make a little donation to help w/ costs. Even if you tell me there aren't costs at all I want to donate for further expenses.

**Comment by Frenzie** [comment]
The server's VPS is provided for free by @Hzj-jie's employer. All other infrastructure is provided for free by GitHub, GitLab, Travis CI and CircleCI.

I suspect the koreader.rocks domain name is paid for (or somehow provided by) @houqp. I'd have to ask, or maybe the ping will draw sufficient attention. :-)

**Comment by didierm** [comment]
Related to https://github.com/koreader/koreader/pull/3944#issuecomment-390904251 (request to provide a PayPal address for donations).

**Comment by robert00s** [comment]
@Frenzie @poire-z @pazos @NiLuJe @houqp 
What do you say about providing PayPal for donations and purchasing a Pocketbook for testing?
Like @NiLuJe in https://github.com/koreader/koreader/issues/2095#issuecomment-515538113 said:
>We lack active developer(s) with PB devices

We have currently 30 open inssues with PB devices.

**Comment by NiLuJe** [comment]
That won't help finding free time and/or motivation to work on it, though ;).

**Comment by poire-z** [comment]
> and purchasing a Pocketbook for testing

Why not, if one of us wants a PB to play with.
(Actually commenting to say I'm not that one :)

**Comment by Frenzie** [comment]
Tbh I'm not sure how motivated I am either but on the flipside holding a real device in your hands can be motivating.

**Comment by pazos** [comment]
> What do you say about providing PayPal for donations and purchasing a Pocketbook for testing?

Sounds cool. Actually we can promote [bountysource](https://www.bountysource.com/teams/koreader) too. Having a *hint* on the README might help.

In general I think that the bountysource way is preferable (things done -> reward) but for the Pocketbook thingy paypal seems better.

disclaimer: not interested at all in Pocketbooks.

offtopic: interested in Linux hacker-friendly eink devices like the [Remarkable](https://github.com/canselcik/libremarkable/issues/17#issuecomment-465375334). 

Of course I don't have one and I won't buy one in the near future, but if I see a bounty of 150€ available to add support to the Remarkable I would buy one just for fun and try to get the reward. In that scenario a current owner would take a cheaper bounty. 

That seems fair to me, motivate random skilled individuals around the world with the device in hand and a bounty reward waiting for them.

Paypal et al. seem cool for a general "I want to donate, thanks for the program" and, in that respect, buying a pocketbook seems like one of the best things to spend the money.

I'm going to donate too :smile:

**Comment by NiLuJe** [comment]
See also https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository for native integration into the GH UI ;).

**Comment by Frenzie** [comment]
Liberapay looks interesting. Weblate and (since more recently) FreshRSS use it.

I've created an account to investigate:
https://liberapay.com/Frenzie/receiving/

**Comment by didierm** [comment]
Ouch ; Liberapay (or PayPal ?) apparently incurs an 8% transaction fee ?

**Comment by Frenzie** [comment]
A transaction fee is likely (mostly?) PayPal. Liberapay says they prefer Stripe but I don't have an account yet. Thanks for donating! 

I'd also have to set up a KOReader team/organization of course. At this point I've basically only created an account and explored the interface.

**Comment by Frenzie** [comment]
A heads up for other people reading along… this Stripe stuff is pretty weird and confusing right now. I figured I could hit two birds with one stone by setting up Stripe for both GitHub Sponsors and Liberapay. I then proceeded to fill out the necessary info through the links provided by GitHub.

Now I've set up an account (not yet verified), but curiously Stripe via Liberapay still asked me to sign in. In this it asked for a username+pass, but I didn't have one because it seems to log in through GH. I figured it's just a case of having to set up a password, but I couldn't find anything. Trying "forgot password" instead, I get this:

> This account is linked to a business that works with Stripe. To view details, sign in to their website or app directly.

<img src=https://user-images.githubusercontent.com/202757/67478654-c12eba80-f65c-11e9-9636-8457a411f56d.png width=50%>

I guess I'll wait a few days to see what happens after it's verified, but right now this seems pretty absurd and dispiriting. It's not a huge deal to create separate accounts for GitHub and Liberapay in principle, but I'd have used different e-mail addresses for that purpose if I'd known. But why should I need to be vetted by presumably the exact same process for any Stripe instance I want to connect to some website? Would a "normal" Stripe account (created through stripe.com) avoid such issues? Why are these accounts supposedly separate yet also making it so that my preferred e-mail address is already used?

<img src=https://user-images.githubusercontent.com/202757/67480618-9a728300-f660-11e9-938d-dccf8ee4c897.png width=60%>

The docs: https://stripe.com/docs/multiple-accounts

But of course none of the instructions there work because I can't log in or get a password as stated above.

**Comment by Frenzie** [comment]
I added a Liberapay link using the new GitHub sponsors button.

https://github.com/koreader/koreader/pull/5770
https://liberapay.com/KOReader

It seems to work well enough. :-)

**Comment by NiLuJe** [comment]
Sidebar: I'm partial to the "tip jar" approach to donation (vs. the recurring model of Liberapay), but that's just me ;).

Also, the name of the platform that does just that completely eludes me right now :D.

**Comment by KenMaltby** [comment]
Funny, I can't get the authorize access to my Github acct, button, to work; for adding my avatar. It shows it as an option, but the big green button doesn't give me a pointing finger cursor.
Luck;
Ken

**Comment by Frenzie** [comment]
Weird, hopefully just a fluke.

**Comment by Frenzie** [comment]
@KenMaltby Strange, I don't know what that could be. Also thanks, I hadn't set GitHub as an avatar source on the KOReader page yet. :-)

**Comment by Frenzie** [comment]
@NiLuJe https://en.tipeee.com/

**Comment by NiLuJe** [comment]
Also https://ko-fi.com/ ;).

**Comment by pazos** [comment]
I like the tip jar approach too. Please consider them as an alternative :smile: 

BTW, https://github.com/koreader/koreader/blob/master/README.md#support is out of date: "At this moment we don't support any form of monetary donation, but you can create a bounty for the specific bug or feature request you want and motivate others to do the work."
