### ISSUE TITLE
Margins of pdfs very small on

### ISSUE THREAD

**Issue by wvhulle** [koreader/koreader#4255]
* KOReader version: v2015.11-1860-g9fda983_2018-09-29
* Device: Kobo Aura One

#### Issue

The options to change the margins from small to large don't change much compared to the standard software. It only changes a fraction of the screen size. This probably happens because the Kobo Aura One has a lot of pixels. Could the default be made bigger, please?

#### Steps to reproduce

Install any version of Koreader.

**Comment by Frenzie** [comment]
I'd have to check if it's DPI scaled. I forget, what kind of granularity does Nickel offer?

**Comment by wvhulle** [comment]
Sorry, how do you mean DPI scaled? The rest of the interface is scaled normally for high dpi. Only the margins are not DPI scaled. Nickel has broader margins on sides, top, and bottom which is sometimes more comfortable to read.

**Comment by wvhulle** [comment]
Shouldn’t auto/semi/manual cropping be independent from setting the margin size? It seems like the problem is that the DPI setting does not have influence on the size of the margins?

**Comment by Frenzie** [comment]
It does seem to be affected by DPI, but in a slightly outdated manner:

https://github.com/koreader/koreader/blob/850be52177a08114013fa6af11a36f1e4081918a/frontend/apps/reader/modules/readerzooming.lua#L288

That should perhaps be changed to something like:
```lua
Screen:scaleBySize(self.ui.document.configurable.page_margin)
```

(I haven't followed the code paths in detail so I might be overlooking something.)

But I also notice that the GUI setting only supports `values = {0.05, 0.10, 0.25},`, whereas the defaults.lua says it can go all the way up to 1:

https://github.com/koreader/koreader/blob/b8d95984d1a19cec00bf4c076d6caa170c1f89f8/defaults.lua#L91

**Comment by Frenzie** [comment]
In the meantime we've had https://github.com/koreader/koreader/pull/7104, so something similar should be done for paged documents.

**Comment by gbyl** [comment]
Documenting here that the extra range from `DKOPTREADER_CONFIG_PAGE_MARGIN` does not produce a perceptible difference in margin https://github.com/koreader/koreader/issues/7233#issuecomment-773411624 Issue likely to be DPI-related.

**Comment by Roi03** [comment]
I know this is an open source community but is there a way to use financial rewards to speed up patches? KO-Reader is so close to becoming a definite answer for E-Readers especially when it comes to Scientific Journals that its a shame to be missing this feature.

**Comment by Frenzie** [comment]
Some people have used Bountysource but I seem to recall reading something bad about them recently.

**Comment by poire-z** [comment]
Well, me too I'd like to have larger margins the few times I have to read a PDF, after I auto/semiauto-crop it.

```diff
--- a/frontend/ui/data/koptoptions.lua
+++ b/frontend/ui/data/koptoptions.lua
@@ -103,12 +103,19 @@ In 'semi-auto' and 'manual' modes, you may need to define areas once on an odd p
             {
                 name = "page_margin",
                 name_text = _("Margin"),
-                toggle = {C_("Page margin", "small"), C_("Page margin", "medium"), C_("Page margin", "large")},
-                values = {0.05, 0.10, 0.25},
+                -- toggle = {C_("Page margin", "small"), C_("Page margin", "medium"), C_("Page margin", "large")},
+                buttonprogress = true,
+                values = {0.05, 0.10, 0.25, 0.40, 0.55, 0.70, 0.85, 1.00},
                 default_value = G_defaults:readSetting("DKOPTREADER_CONFIG_PAGE_MARGIN"),
                 event = "MarginUpdate",
                 name_text_hold_callback = optionsutil.showValues,
                 help_text = _([[Set margins to be applied after page-crop and zoom modes are applied.]]),
+                more_options = true,
+                more_options_param = {
+                    value_step = 0.05, value_hold_step = 0.15,
+                    value_min = 0.05, value_max = 1.50,
+                    precision = "%.2f",
+                },
             },
             {
                 name = "auto_straighten",
```
Just adding more values to `values = {0.05, 0.10, 0.25, 0.40, 0.55, 0.70, 0.85, 1.00},` , keeping the 3 original ones at start and not changing anything else, is enough to get something usable and larger margins.
(And we can go above 1.00, 1.40 had some effects, but depending on Screen DPI, at some point it had none and was inducing some small drift to the left.)

![image](https://user-images.githubusercontent.com/24273478/224344030-a0c8c551-a1db-44f2-9ec5-367e762810d7.png)

![image](https://user-images.githubusercontent.com/24273478/224344118-4b6e7d06-ac0f-4cdf-8d9d-4ab0df690d7c.png)
(and if that one is too obscure with its unitless value, I'd rather just remove that "more_options" buttons so to not have to think more :)

I'm not sure what the unit is (may be _inch_), and it indeed changes with our Screen DPI value - but well, I don't want to change anything and need to migrate settings - for something I don't really want to understand :)

> Documenting here that the extra range from DKOPTREADER_CONFIG_PAGE_MARGIN does not produce a perceptible difference in margin 

@gbyl: I guess this was because you had already set a value for your document(s) at the time, so this global default did not apply.
Can you (and other users that commented here) check and replace your `frontend/ui/data/koptoptions.lua` with this one: [koptoptions.lua.txt](https://github.com/koreader/koreader/files/10942988/koptoptions.lua.txt) and see if that works for you?

**Comment by poire-z** [comment]
Tested on my Kobo, and it would somehow work.
But there are some issues: if you choose some larger margin that what we are used to, it gets "semi-auto" crop confused: I often use it to crop out page header and footer, and after I set the crop area, some bits of the header are still in the page. Getting back to the crop area selector, I don't find the crop lines as I set them :/
But no problem with manual crop.

Also, the margin is applied on all 4 sides - I don't really mind the added spacing between pages in continuous mode, but ideally, I'd want more horizontal margin, and less vertical margin, so it reads better in continuous mode.

But not really wanting to dig into our kopt stuff :/

**Comment by poire-z** [comment]
> But there are some issues: if you choose some larger margin that what we are used to, it gets "semi-auto" crop confused: I often use it to crop out page header and footer, and after I set the crop area, some bits of the header are still in the page. Getting back to the crop area selector, I don't find the crop lines as I set them :/

From what I understand, in semi-auto mode (and in auto, without the manual rect), we draw a rect, then kopt tries to find the blackbox in it, then add our margin to that blackbox - so making it a bit larger, and when the margin is large, it may include some header or decoration you explicitely wanted out...
And later, when you tap semi-auto again, you see that final rectangle (not the one you draw), and if you just apply it again, it won't find the same blackbox as before (because now, there are the decorations in), and it will add some margins to that, and your rectangle will get bigger (until there's no decoration anymore and the blackbox+margins becomes constant)...

Moreover, in "manual" mode, the margins are not added, so you get the margins from the rectangle you did draw (which stays constant) - but it's hard to get that drawing balanced, so I prefer semi-auto.

Moveover, the visual margin you get is different whether in reflow mode or not...

So, well, I may still add more page_margins values in koptoptions.lua - it can just be helpful in some cases, and won't help in others - but it's just more tools available to the user, even if there's nothing (already) really consistent in kopt world :)

**Comment by gbyl** [comment]
@poire-z Just adding that I was able to test this on a 10.3" device (native DPI: 226; KOReader UI DPI: 200), and it works wonders! Thank you for this excellent contribution.
