### ISSUE TITLE
koreader-appimage crashes on start

### ISSUE THREAD

**Issue by carlmeier** [koreader/koreader#4298]
* KOReader version: koreader-appimage-x86_64-linux-gnu-v2018.11.AppImage
* Device: Arch 

crash log:

It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/01/18-11:08:33
 [*] Version: v2018.11

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (assisted searchpath): ./libs/libSDL2.so
ffi.load: SDL
ffi.load: SDL
11/01/18-11:08:33 INFO  initializing for device SDL
11/01/18-11:08:33 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
ffi.load: libs/libfreetype.so.6
./luajit: frontend/version.lua:33: attempt to perform arithmetic on a string value
stack traceback:
	frontend/version.lua:33: in function 'getNormalizedVersion'
	frontend/version.lua:42: in function 'getNormalizedCurrentVersion'
	frontend/ui/quickstart.lua:17: in main chunk
	[C]: in function 'require'
	./reader.lua:99: in main chunk
	[C]: at 0x00404960

**Comment by Frenzie** [comment]
Well, that's embarrassing. My test tag of `bla` worked but I neglected to test `v2018.11`.

I'll fix it state pede.

**Comment by aveao** [comment]
Thanks for the quick fix! I was having crashes due to this.

**Comment by Frenzie** [comment]
Everything has gone through a very long period of testing with "beta" releases that were basically stable versions, going back even to when they were still called "nightly" by tradition. Except for one tiny thing… tagging a stable release. I thought that only meant that the automated backend infrastructure wasn't ready for it.

The good news is that today I'll be able to iron out the glitches related to tagging a stable release, so that everything will go a lot smoother next time.

The bad news is that OTA-updating to a stable may be broken for more or less the same reason. (Not that the AppImage is affected by that.)

Anyway, I'll be able to start uploading actually working builds within 10 minutes. Thanks for reporting, because I'd only tested the latest automated nightly as a last-minute check! (It's exactly the same in every way, except that it's called `v2015.11-1902-g1e69fae_2018-10-31` so that it doesn't break the Version module.)
