### ISSUE TITLE
Can it be ported to some platforms without Linux?

### ISSUE THREAD

**Issue by zaoqi-unsafe** [koreader/koreader#4318]
Such as TI nspire/ndless

**Comment by Frenzie** [comment]
A quick search shows a video of something called "nDoom 2," which would suggest that it might be theoretically possible, provided it's the actual Doom 2 engine with some adjustments for drawing to the screen and not something written from scratch in something like TI Basic.

(Also, we actually have some provisions to build on Windows, although presumably that was unintentionally broken years ago because we don't have CI set up for it.)

**Comment by Frenzie** [comment]
I'll close this now. Please feel free to ask more questions.
