### ISSUE TITLE
Page changing when swiping to show/hide Android status bar

### ISSUE THREAD

**Issue by Nick1412** [koreader/koreader#4326]
* KOReader version: 2018.11.1
* Device: Likebook Mars T80D

Issue: While in an . epub document, when I swipe on top of the screen to show/hide the device's status bar it changes page.

Can/could swiping up/down to change page be disabled?

**Comment by Frenzie** [comment]
But swiping up/down doesn't change page?

**Comment by poire-z** [comment]
Looks like it doesn't on PDF, but it does on EPUB:
https://github.com/koreader/koreader/blob/772cdefe92e67b2a0b16abccb316ebea269aa24c/frontend/apps/reader/modules/readerrolling.lua#L357-L361

I've been bothered by this issue on my android phone, when swiping from the bottom to show the bottom bar to get the home/applist buttons: it changed page. So, I always quit koreader with its Exit menu item to keep the page I was on.

I thought it should be solved on the Android/APK/java side, like if the start of the swipe is the bottom border, it's because it was started from outside, so ignore it. (couldn't figure how to go implement that in android, but didn't bother much as I really don't use android).

But just disabling swipe north and south would be a quite easier solution to this problem :) But it could be that some people do use these gestures. (Or just disable them on Android ?)

**Comment by Nick1412** [comment]
Maybe there could be an option in the (advanced) settings to disable the north/south swipe for those who want to do so.

**Comment by Frenzie** [comment]
I mean in the gesture manager. :-)

**Comment by Frenzie** [comment]
I just tried this and part of the reason I never noticed it also because I use swipe for menus. So I might unintentionally trigger the KOReader menu, but no page turns.

**Comment by Nick1412** [comment]
That's a way around the issue indeed but still, it could be convenient to have the option to disable north/south swipe for page turning (as long as it doesn't affect page scrolling in .pdf files).
