### ISSUE TITLE
Question: Highlighting on Kindle 4 (non-interactive)

### ISSUE THREAD

**Issue by samba2** [koreader/koreader#4329]
* KOReader version: 2018.11
* Device: Kindle 4.1.3

#### Steps to reproduce
The Kindle 4 has no touch-display. Instead it provides a virtual keyboard (in the Amazon reader) and four arrow keys to navigate left, right, up and down. 
When reading an epub is it possible to highlight text using those arrow keys or is a touch-display needed?

**Comment by Frenzie** [comment]
I'm afraid we currently don't have that functionality, and I think it would take a fair bit of effort to add. Could you describe the workflow as a point of inspiration, should someone decide to tackle this? Pinging @onde2rock just in case of potential interest.

As a general note, this kind of functionality could also be useful on touch-screens for more precise selection since sometimes it can be hard to select the first word of a sentence or some such.

**Comment by samba2** [comment]
The original software provides "adding comments" and "highlighting". The first one is in my eyes unbearable - too much fiddling with the arrow keys to select the single characters. Its a bit like writing SMS back in the days.
Which leaves "highlighting" as the only viable use case (in my opinion).

It works like this:
- I am reading a document
- to enter highlighting I press either the "up" or "down" arrow key
- pressing "up" positions a blinking cursor on the lowest possible text position (usually the footer)
- pressing "down" positions the blinking cursor at the very top e.g. in front of the first character
- also a little help text box is displayed saying "press the middle button" to start selecting
- this text is positioned at top top when the cursor is at the bottom and vice versa
- I can now move the cursor around to the position where I want to start highlighting
- In the middle of the arrow keys is an other button which usually starts the KOReader page menu (where I can e.g. change the screen orientation)
- When I am in "blinking cursor" aka "selection" mode, this middle button on the Kindle almost starts the selection
- since the original software allows to "add notes" or "to highlight" the little help text box changes to a dialog asking "do you want to add notes or highlight?" I select "highlight" (since I think taking notes is not really useful this extra dialog could go, pressing the "middle" key could directly start "highlighting")
- I can now use the "right" arrow to select the text. the behaviour after pressing the middle key is like holding the Shift key on a keyboard and than using the keyboard arrow keys to select.
- the little help text box now says "press middle button" to stop selection
- When I do this in the little help text box I am asked if I want to finish the selection or not
- I choose "yes"
- I am then still in the "moving cursor" mode. The help text again says "press middle button" to start the selection so I could start over selecting something else.
- to go back to reading mode i press the "back" key

All clearity gone by now? ;-)

PS: I am a dev at day time but unfortunately I currently don't find the time to get into KOReader development in my spare time. But I am happy to act as a (hopefully) competent user.

**Comment by Frenzie** [comment]
Wow, they went all out on that. Thanks for sharing!

**Comment by onde2rock** [comment]
Yeah, look like a bunch of code need to be written. I will look to see if I can reuse the code that does the touch selection, since it's dealing with document backend libraries, it can be a pain.

I will look into it, if it's not to hard, I may give it a try.

**Comment by ofalvai** [comment]
Is there any update on this issue? I'd love to use KOReader on my old Kindle 4, but unable to highlight text is a blocker for me :(

**Comment by NiLuJe** [comment]
Without someone interested actually doing the work, extremely unlikely.

**Comment by poire-z** [comment]
Solved by #8877.

**Comment by Commodore64user** [comment]
> and I think it would take a fair bit of effort to add.

you think rightly there

> Wow, they went all out on that.

so did we

> it can be a pain

it has been 

> if it's not to hard

famous last words, 

> Without someone interested actually doing the work,

well...

https://github.com/user-attachments/assets/8c09ccb6-722a-4da1-ba12-8adaa1cdab50

**Comment by mergen3107** [comment]
Now it looks a lot like native UI highlighting

**Comment by Commodore64user** [comment]
but I still legitimately need more from crengine, as we already know, the ripple-ray, but more importantly; accurate and truthful split-hyphenation metadata. the heuristics no longer hold here.. it works in the footage for "centrepiece", but it fails in other unexpected places, for example:

this is clearly not a hyphenated word, correctly flagged as far as the heuristic is concerned but it fails the checks because the first get text range return 11 chars instead of 10 for the probes.

<img width="540" height="143" alt="Image" src="https://github.com/user-attachments/assets/f3a0d798-b9bc-4850-b797-18abf89170bf" />

```
04/12/26-14:29:49 DEBUG ReaderTextSelection: Target line hit at Y: 142 - Breaking loop. 
04/12/26-14:29:49 DEBUG CreDocument: get text range {
  pos0 = "/body/DocFragment[12]/body/h1[56]/text().0",
  pos1 = "/body/DocFragment[12]/body/h1[56]/text().11",
  text = "censorship "
} --[[table: 0x0125485210]] 
04/12/26-14:29:49 DEBUG ReaderTextSelection: Potential split word detected: censorship  | box h/w: 41 / 175 | effective width: 520 
04/12/26-14:29:49 DEBUG CreDocument: get text range {
  pos0 = "/body/DocFragment[12]/body/h1[56]/text().0",
  pos1 = "/body/DocFragment[12]/body/h1[56]/text().10",
  text = "censorship"
} --[[table: 0x012523acf0]] 
ReaderTextSelection: Split word validation - probe 1:   censorship      at      213     152.25
04/12/26-14:29:49 DEBUG CreDocument: get text range {
  pos0 = "/body/DocFragment[12]/body/h1[56]/text().0",
  pos1 = "/body/DocFragment[12]/body/h1[56]/text().10",
  text = "censorship"
} --[[table: 0x01252015a0]] 
ReaderTextSelection: Split word validation - probe 2:   censorship      at      334     172.75
ReaderTextSelection: Split word validation - original word:     censorship 
04/12/26-14:29:49 DEBUG ReaderTextSelection: Split word validation for: censorship  | split word?: true 
```

to make matters worse, it only fails when you move up from the right side, if you move up from the left, no issues, i.e., `is_split=false`

incidentally it seems to me, that this 

https://github.com/koreader/koreader/blob/c5c0b1aa0cb4d0b31d6e51979d01e73fd9e999b7/frontend/util.lua#L23-L28

is a problematic function, character classes in lua are byte-oriented not character-oriented

but I digress, cleaning the string is not a valid solution anyway.

**Comment by omer-faruq** [comment]
Using AI, I created a patch for this purpose, which may help: 2-precise-line-word-navigation.lua on this repo: https://github.com/omer-faruq/koreader-user-patches

**Comment by Commodore64user** [comment]
so working on the overlay I found myself encountering a bit of an issue, these two events

https://github.com/koreader/koreader/blob/50a7fc66a6ccf004ffa9c632bebb4640bce21eb5/frontend/apps/reader/modules/readerrolling.lua#L131-L132

get duplicated because (overlay is an InputContainer) the `onPanning` handler,

https://github.com/koreader/koreader/blob/50a7fc66a6ccf004ffa9c632bebb4640bce21eb5/frontend/apps/reader/modules/readerrolling.lua#L953-L962

broadcasts an event, which is then consumed by readerUI and the overlay, but I ask, why is it broadcasting an event here in the first place? shouldn't it be just a single-dispatch call (e.g., `self:onGotoViewRel`)

**Comment by poire-z** [comment]
Indeed, it could be replaced.
"why?" - because it worked and the author did not pay much attention, or we have still a few of these uneeded ones here and there & copy/paste.
