### ISSUE TITLE
When going from Reader to 'History' + 'View full size cover' and back to Reader

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4346]
* KOReader version: v2018.11.1-27-gafc4be3_2018-11-16/
* Device: KA1

#### Issue
When reading a book and open 'History' and 'View full size cover' and then go back to reading you end up on some previous page of the book and the page counting is messy.

#### Steps to reproduce
1. Ensure that you have books in your 'History'-page
2. Open a new book and page forward several pages. 50 pages should be enough, but 100 pages probably makes the issue more obvious. You can use the +10 feature. Or just use 'Go to location'.
3. Open 'History' and longpress on a book and open 'View full size cover'.
4. Close cover window and close 'History'
5. Now things have happened with the book you read. The 'Current page' and 'Pages left in chapter' figures are the same but the text are from some previous part of the book. Which means that 'Current page' and 'Pages left in chapter' values aren't correct. So for example if you open table of contents and tap on a chapter you end up somewhere in the middle of a chapter.
If you go to file manager and then reopen the book the page counting returns to correct values, but (if you have page forward or something similar) you are still on the same previous place in the book.

**Comment by poire-z** [comment]
I can reproduce it.
It happens also when History is in Classic display mode, and you select `Book information` on a document without a .sdr (so, metadata not cached in the metadata.lua file, and need to open the book to get them).
Actually, just having crengine open a 2nd book (to extract metadata or cover image) causes some problem, like current book cache being invalid on next load).

Cool Reader / original crengine is supposed to be able to open multiple books simultaneously.
We don't have that requirement in KOReader (except indeed, when getting metadata or cover image...), and it's quite possible I took some shortcuts related to that in my last months modifications... Like using global variables... There was already a `bool gFlgFloatingPunctuationEnabled`, I added `gDOMVersionRequested`, `gRenderDPI`, `gRenderScaleFontWithDPI`, `gRootFontSize`.
Could be because of that (I hope), and may be I re-set them too early (in which case, I should re-set them later, and the requirement would become that we can _load_ multiple document, but we can only have a single one _rendered_ at a same time, which would be fine enough for KOReader.

**Comment by poire-z** [comment]
OK, not cause of my changes :) And I think there's no change needed on crengine side.

There are just a few settings (that ends up being accounted in a [GlobalHash](https://github.com/koreader/crengine/blob/89b0650e425013da81bc73c6d7676599d8b13c62/crengine/src/lvtinydom.cpp#L350-L369)) that are (re)set when [creating a new CRE document](https://github.com/koreader/koreader-base/blob/84299a585587f306230c448f80e4e4811f2f990d/cre.cpp#L346-L364).

I'll move these in a new cre.cpp method `readDefaults()` (that apply settings from cr3.ini - that could possibly be removed totally and hardcoded in crengine - but may be some people have put some specific crengine settings in it, so let's keep it) that will be called only by ReaderUI when opening a document for display - and not by the other code that just opens a document for next just calling `loadDocument(only_metadata)`

Also, [setting a default fallback font](https://github.com/koreader/koreader/blob/3f7f5f07bf9602013255c45c55f1e5f71ca8293b/frontend/document/credocument.lua#L135-L137)  (which ends up in `fontMan->GetFontListHash(documentId)`) will have to be moved at start of [CreDocument:render()](https://github.com/koreader/koreader/blob/3f7f5f07bf9602013255c45c55f1e5f71ca8293b/frontend/document/credocument.lua#L177-L179) so that too will be done only when displaying.

**Comment by poire-z** [comment]
@gerhaher : can you confirm this is fixed in today's nightly `v2018.11.1-34-g3c6c15e`, in all the various ways you managed to trigger the bug?

**Comment by gerhaher** [comment]
Seems OK, I can't trigger it.
