### ISSUE TITLE
Wi-Fi connection menu option always unchecked

### ISSUE THREAD

**Issue by dwma** [koreader/koreader#4380]
* KOReader version: 2018.12
* Device: Kindle Paperwhite 1 running 5.3.3 factory image.

#### Issue
Network > Wi-Fi connection menu option is always unchecked regardless of connection state. Tapping on it will always offer to connect the device, even if it's already connected.

#### Steps to reproduce
1. Have Wi-Fi turned on.
2. Go to Network > Wi-Fi connection.
3. Checkbox will be unchecked.

**Comment by pazos** [comment]
@dwma @NiLuJe: `/sys/class/net/<iface>/carrier` is present since 2.6.12
https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net

The implementation on Cervantes does just that [here](https://github.com/koreader/koreader/blob/master/frontend/device/cervantes/device.lua#L16-L22) and [here](https://github.com/koreader/koreader/blob/master/frontend/device/cervantes/device.lua#L174-L176).

**Comment by NiLuJe** [comment]
Barring that, there's probably also an lipc call, I just haven't had time to dig up a Kindle yet ;).
