### ISSUE TITLE
epub:case element not supported

### ISSUE THREAD

**Issue by SFL01** [koreader/koreader#4381]
* KOReader version: 12.2018
* Device: KA1

#### Issue
Formulas in an epub are wrongly shown, as their structure is shown before them.
( see pictures below )
The epub is correctly shown on calibre and with nickel. Tried some format conversion with calibre, but can't resolve anyway.
The book is freely available at this page:
https://www.degruyter.com/view/product/495845
With Koreader
![img_20181206_190321286](https://user-images.githubusercontent.com/45668841/49604003-0f779400-f98d-11e8-83de-e1d136560706.jpg)
With nickel
![photo_2018-12-06_19-04-02](https://user-images.githubusercontent.com/45668841/49604104-55345c80-f98d-11e8-9a4d-d160e3d70f42.jpg)

**Comment by Frenzie** [comment]
The formulae are actually present in two ways: MathML and as an image. It looks like crengine as well as MuPDF render both elements.

![screenshot_2018-12-06_20-07-49](https://user-images.githubusercontent.com/202757/49606087-a6931a80-f992-11e8-9ce3-8e4789c16c2a.png)

@poire-z This looks superficially simple, in this case if the MathML namespace is supported use that, otherwise fall back to the image.
```xml
<epub:switch id="chapter01_1_30"><epub:case required-namespace="http://www.w3.org/1998/Math/MathML"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="equation"> <mrow> <mi>S</mi><mo>=</mo><mrow><mo>{</mo> <mrow> <mi>H</mi><mo>,</mo><mi>T</mi></mrow> <mo>}</mo></mrow><mo>=</mo><mrow><mo>{</mo> <mrow> <mi>T</mi><mo>,</mo><mi>H</mi></mrow> <mo>}</mo></mrow><mo>.</mo></mrow></math></epub:case><epub:default><span class="display-equation"><img src="../graphic/12_chapter01_fig_14.png" class="Image432" alt=""/></span></epub:default></epub:switch></div>
```

Spec here: http://www.idpf.org/epub/30/spec/epub30-contentdocs.html#sec-xhtml-epub-case

**Comment by poire-z** [comment]
I see.
But easier for now to ignore any `<math>` element (as it will look uglier (*) than an image anyway) with some style tweak:
Create `koreader/styletweaks/ignore_mathml.css` with:
`math { display: none; }`
And enable it via Style tweaks > users style tweaks, and you'll get:

<kbd>![image](https://user-images.githubusercontent.com/24273478/49606971-0e4a6500-f995-11e8-88e3-17b6435310db.png)</kbd>

Haven't tried if we can toggle the reverse with a style tweak for `epub:default` :)

(*) actually, the mathml gets worse with #4378 :( 
<kbd>![image](https://user-images.githubusercontent.com/24273478/49607216-9f214080-f995-11e8-9557-ca7650790a2a.png)</kbd>

**Comment by Frenzie** [comment]
Is there any actual MathML support or is it just the case that here that the meaning is basically just plain-text display?

Note that there are also basic MathML stylesheets that come quite far indeed, although I'm not sure if they would come quite as far on crengine.

**Comment by poire-z** [comment]
There is no MathML support, like there's no inline-xml SVG support: it's just a bunch of unknown elements, that are considered by default as `display: inline`, that act each just like a SPAN.

The whole `epub:switch epub:case epub:default` comes down to this for crengine:
`<span>(<span>P</span>)</span> <img src=...>`

**Comment by Frenzie** [comment]
Still sounds superficially simple though, at least for this particular case. Ignore MathML and fall back to whatever's in the fallback. :-)

**Comment by poire-z** [comment]
Dunno how you mean _superficially_ , but I wouldn't know how/where in crengine to go at that :)

I somehow prefer the control of style tweaks, so one (who can View HTML and understand what happens) can try both display options, without us deciding that crengine should just drop MathML (even if just when in a `epub:switch`).

**Comment by Frenzie** [comment]
> Dunno how you mean superficially , but I wouldn't know how/where in crengine to go at that :)

That's *exactly* what I mean by that. It looks like something that would be easy from the surface ("superficially") but probably isn't when you actually get into it.

> without us deciding that crengine should just drop MathML (even if just when in a epub:switch).

But then you always get an ugly as well as against the spec result by default. The whole reason for it is to say that if you don't support X, then here's a nice fallback.

Now I'm very much of the user > author persuasion, but putting unnecessary configuration hardships on the user isn't the best default imo. :-)

**Comment by poire-z** [comment]
I guess it could be implemented either in [setNodeStyle](https://github.com/koreader/crengine/blob/7d040f6e2f4a7808813ac33419c9bf4be3f3cce9/crengine/src/lvrend.cpp#L3979-L4049) or later in [ldomNode::initNodeRendMethod](https://github.com/koreader/crengine/blob/7d040f6e2f4a7808813ac33419c9bf4be3f3cce9/crengine/src/lvtinydom.cpp#L4587-L4609). That is, choice hardcoded, or we would need a whole configuration/toggle to be passed from Lua up to crengine...

Or simpler, as there is really no namespace that we support that could be mentionned in `epub:case`, we just could add to epub.css:
```css
/* Ignore EPUB3 epub:case */
case { display: none; }
```
And some style tweak to toggle the (hopefully single) alternative:
```css
/* Ignore EPUB3 epub:default and activate epub:case */
case { display: inline; }
default { display: none; }
```
(I think `:` is already used for pseudo elements/classes in CSS, so I guess we can't use prefixed `epub:case` or `epub:default` in any CSS... so, if no one uses plain HTML tags `<CASE>` or `<DEFAULT>`, that could do the trick.)

**Comment by Frenzie** [comment]
You type `epub\:case`, for the record. ;-)

**Comment by Frenzie** [comment]
That being said, it would be better to use `@namespace epub "http://etc"` and then you can use the `epub|case` selector. But given that we don't support namespaces...

**Comment by poire-z** [comment]
I gave `epub\:case` a try, but it doesn't work with crengine.
That's quite expected, because there's no parsing support for that in lvstsheet.cpp, and even if the namespaces are still accessible from the ldomNode objects, they are totally ignored in the stylesheet parsing and check-declaration-against-node code.
I guess implementing this would be long and make the whole lvstsheet code quite more complicated and ugly, for little benefit.
Easier to go with `case { display: }` and `default { display: }`, either with one in epub.css, or both options as style tweaks for people who needs it.
Or just hardcode (with no going back), possibly at XML parsing time (there's less support/functions for namespaces for elements that there are for attributes), the skip/`display:none` of `epub:case`.

Or may be early in setNodeStyle set it to display:none, so we can still re-enable it with style tweaks. I'll have a quick try.
