### ISSUE TITLE
Cervantes 4 does not restore wifi after sleep

### ISSUE THREAD

**Issue by avsej** [koreader/koreader#4422]
* KOReader version: v2018.12-5-g74c3c90_2018-12-07
* Device: BQ Cervantes 4

#### Issue
Any reason why Cervantes devices do not implement [NetworkMgr:restoreWifiAsync()](https://github.com/koreader/koreader/blob/295cc55e03e07f705f67efad247bbea515379bff/frontend/device/cervantes/device.lua#L172-L173)?

It is annoying to go throw multiple steps/clicks to re-enable wifi after sleep? (btw is it possible to skip scan dialog and try connect to known and visible network first?)

#### Steps to reproduce
* connect to wifi
* put device to sleep
* wake device up

Expected: wifi will be reconnected.

**Comment by pazos** [comment]
> Any reason why Cervantes devices do not implement NetworkMgr:restoreWifiAsync()?

restoreWifiAsync is just a wrapper to asynchronously call enable-wifi.sh and obtain-ip.sh. This works on kobos where the `enable-wifi.sh` script uses a wpa configuration file to store all the networks ssids/passwords. So wpa_supplicant will try to associate to a network and then the dhcp client obtains a lease.

> btw is it possible to skip scan dialog and try connect to known and visible network first?

It should be possible to use [turnOnWifiAndWaitForConnection](https://github.com/koreader/koreader/blob/master/frontend/ui/network/manager.lua#L64)  but we need to reimplement [turnOnWifi](https://github.com/koreader/koreader/blob/master/frontend/device/cervantes/device.lua#L160) to try to associate to the last ap before showing the menu.

It is not trivial to fix, at least for me, but if you want to give it a try please read https://github.com/koreader/koreader/blob/master/frontend/ui/network/manager.lua.

Another alternative is to write a new backend for the network manager to use connman instead of wpa_supplicant, like BQ is doing in their software.

And, last but not least, if you're using your device on known locations with known ap hosts you can write your own configuration file with wpa_passphrase "essid" "password" >> "wpa.conf" and use that in [wpa_supplicant](https://github.com/koreader/koreader/blob/master/platform/cervantes/enable-wifi.sh#L19) with the `-c` option followed by the full path to your configuration file. In that case it will be possible to reimplement restoreWifiAsync like kobo does (by reverting [these commits](https://github.com/koreader/koreader/pull/4341/files/be7bd5ed6c53c54c5fe07869ba2818078adce0d1..29c9f8246088188ffc5c9c06f9526af24f04e818) )
