### ISSUE TITLE
[Request] Show the actual page number instead of %

### ISSUE THREAD

**Issue by Akebu** [koreader/koreader#4436]
* KOReader version: v2018.12
* Device: Kobo GLO HD

With the display mode set on "Detailed list with cover images and metadata", the file browser show the % of a book. Ex : 20% of 385 pages

It is possible to add an option for showing the actual page number instead ? Ex: 78 of 385 pages 

Regards

**Comment by Frenzie** [comment]
Pinging @poire-z

**Comment by poire-z** [comment]
If we're fine with a possible +1/-1 error (because of rounding issues, or scroll mode between 2 pages), we could just add a `if BookInfoManager:getSetting("show_page_instead_of_percent") then` in there:
https://github.com/koreader/koreader/blob/e30bfd34e69a30cf41f89cdadf715f8b247250fb/plugins/coverbrowser.koplugin/listmenu.lua#L365-L370
and get the current page number to display with `Math.round(percent_finished * pages)`.
(The current page is not saved in docsettings for EPUB, but it is for PDF - but using it would need a bit more work in the sidecar stuff caching (done above that code snippet) that I'd like to avoid :).

I'm personally not sure knowing I'm at page 287 of 315 pages is really helpful. I would always do the math in my head to get a %, or get the number of pages left (would we rather not prefer that?)
Also, `287 of 315 pages` sounds a bit incomplete to me, `page 287 of 395` would sound better, but then, all other displayed strings end with `pages`, so there would be a little cosmetic shift :)

I didn't know how `20 % of 315 pages` was translated in french, so I just had a look, and it seems there's a little error as the % is missing: 
```
#: plugins/coverbrowser.koplugin/listmenu.lua:367
msgid "%1 % of %2 pages"
msgstr "%1 sur %2 pages"
```
Anyway, what would be your suggestions for the string with page number, both in english and in french?

**Comment by Frenzie** [comment]
`page x of y` is good, as is `25 % of 5 pages`.

**Comment by Akebu** [comment]
Showing the number of pages left is a good idea, maybe you can add theses differents format : 
```
X% of Y pages
page X of Y
X% read
X% left
```

**Comment by poire-z** [comment]
Suggested implementation in #4439.
