### ISSUE TITLE
[Android 8+]: Can't open file(s) from other application.

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#4441]
* KOReader version: All
* Device: Android

#### Issue

KOReader will open associated files *if* the program is not running yet. Otherwise it will open with the filemanager.

Also, on newer devices KOReader is not able to open any document from a third party application.
 

#### Steps to reproduce

Android 2.3-7.1:
1. Make sure KOReader is not running.
2. Open a document from other app. KOReader will start and the document will be opened.
3. Without closing KOReader open other document from an external application. KOReader will gain focus again but won't open the new document.

Android 8.0+:
1. Open a document from another app. KOReader will start w/ the filemanager.

**Comment by pazos** [comment]
Ok, to expand a little bit (android 2.3-7.1)

We got the file to open at launch via [llapp_main.lua](https://github.com/koreader/koreader/blob/master/platform/android/llapp_main.lua#L12-L31). 

The intent that we got stays forever during the activity lifetime, except if we set a new intent. To do that we have to override onNewIntent in MainActivity.java
```java
    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }
``` 

and pass it to the frontend  (device/android/device.lua) on onResume() via
 
```lua
            elseif ev.code == C.APP_CMD_RESUME then
                local new_file = android.getIntent()
                if new_file ~= nil then
                    logger.warn("New file opened: " .. new_file)
                end
```

Of course to do that we need to modify a little bit the following files:

#### llapp_main.lua

```diff
--- a/platform/android/llapp_main.lua
+++ b/platform/android/llapp_main.lua
@@ -10,25 +10,7 @@ ffi.cdef[[
 ]]
 
 -- check uri of the intent that starts this application
-local file = A.jni:context(A.app.activity.vm, function(JNI)
-    local uri = JNI:callObjectMethod(
-        JNI:callObjectMethod(
-            A.app.activity.clazz,
-            "getIntent",
-            "()Landroid/content/Intent;"
-        ),
-        "getData",
-        "()Landroid/net/Uri;"
-    )
-    if uri ~= nil then
-        local path = JNI:callObjectMethod(
-            uri,
-            "getPath",
-            "()Ljava/lang/String;"
-        )
-        return JNI:to_string(path)
-    end
-end)
+local file = A.getIntent()
```

#### android.lua

```diff
--- a/assets/android.lua
+++ b/assets/android.lua
@@ -1232,6 +1232,28 @@ local function run(android_app_state)
                 JNI:to_string(JNI:getObjectField(app_info, "nativeLibraryDir", "Ljava/lang/String;"))
         end)
 
+    android.getIntent = function()
+        return JNI:context(android.app.activity.vm, function(JNI)
+            local uri = JNI:callObjectMethod(
+                JNI:callObjectMethod(
+                    android.app.activity.clazz,
+                    "getIntent",
+                    "()Landroid/content/Intent;"
+                ),
+                "getData",
+                "()Landroid/net/Uri;"
+            )
+            if uri ~= nil then
+                local path = JNI:callObjectMethod(
+                    uri,
+                    "getPath",
+                    "()Ljava/lang/String;"
+                )
+                return JNI:to_string(path)
+            end
+        end)
+    end
+
```
I got on logcat `01-04 20:37:45.733 15730 15744 W KOReader:  New file opened: /storage/emulated/0/Download/9781783989645.epub`

@Frenzie @poire-z:

So, now that the platform specific bits are done, my question is: do we have a way to open the new file (saving the old one if needed)?

Please help because I'm lost in a lua ocean :cry:

**Comment by Frenzie** [comment]
I implemented the same in SDL myself last year. See #3793 and #3827.

https://github.com/koreader/koreader/blob/41b885f073d950539e89f66c5a3b1daa97e630de/frontend/device/sdl/device.lua#L130-L135

**Comment by pazos** [comment]
@Frenzie It works!!!

**Comment by poire-z** [comment]
Yep, there are stuff for that in the last 40% of frontend/apps/reader/readerui.lua :)
Including: https://github.com/koreader/koreader/blob/41b885f073d950539e89f66c5a3b1daa97e630de/frontend/apps/reader/readerui.lua#L686-L692

@Frenzie : at a quick glance again at this code, it looks like your call to `ReaderUI:doShowReader(dropped_file_path)` might be bypassing some preliminary checks done in `ReaderUI:showReader` (bookmarks incompatibilities, file existence, use of `ReaderUI:showReaderCoroutine`).

I additionally added in `ReaderUI:switchDocument` the closing of menus (otherwise, they stayed !) and of highlights. Might be needed if you ever happened to get a dropped file or an intent while there are some menus or highlight dialog still open (not sure, it's been a while, but it's worth testing what happens).

**Comment by Frenzie** [comment]
Fair enough, at the time I implemented it it was mostly as a debugging/testing aid, so I didn't sufficiently check such matters. Of course, that kind of thing comes back to bite you when you subsequently think that hey, it's like a desktop app now. ;-)

**Comment by Frenzie** [comment]
Anyway, it should all be good if we switch to switchDocument (wink, wink), right?

**Comment by poire-z** [comment]
Possibly, but worth testing :)
With some additional stuff may be neeed to check if there is or not a ReaderUI instance, and how it works if we were in FileManager, etc...

**Comment by pazos** [comment]
I give it a try yesterday, it seems that android oreo killed the way to get the absolute path of a file from an uri. You can get the filename, read the contents via inputstream and store that stream in a file in the cache folder.

So yes, android is broken. The solution is worse than doing nothing. Maybe we can open a document explaining the user why the feature doesn't work and why android is so hostile when a user open a supported file in their favorite application.

**Comment by Frenzie** [comment]
> You can get the filename, read the contents via inputstream and store that stream in a file in the cache folder.

For files < 10 MB or so that's still tremendously stupid but I guess you wouldn't really notice, but what if you're dealing with bigger files? O_o

**Comment by pazos** [comment]
I tried with other programs (ReadEra and Lithium). They open the file well and the file gets added to recent contents. If you open the book again from program history it will open almost instantly, but if you're openning the book again via intent the file will be imported again.

Didn't meassure timmings because I can't differenciate copying to cache storage and opening the file, but the difference between opening a file knowing its path and go through the import stuff is noticeable.

Coolreader wasn't adapted to oreo crapware, so it will try to open the file using old methods and will fail.

**Comment by Frenzie** [comment]
But how does this make any sense? I know how deeply broken Android is, but now it can't even support normal everyday use?

Run of the mill use case 1: I download one of my Humble Bundle comics or larger ebooks. By coincidence the one I landed on is 1.3 GB, but the basic fact remains that they're all hundreds of MB.

![screenshot_2019-03-03_18-11-24](https://user-images.githubusercontent.com/202757/53698638-d9a54880-3ddf-11e9-9e9f-a1a1c2101f33.png)

Run of the mill use case 2: I download an mp3 file, for instance [this one](http://www.college-de-france.fr//site/vinciane-pirenne-delforge/course-2019-02-28-11h00.htm). At 50 MB it's actually somewhat on the smaller side. (Only some come in podcast form so they can be grabbed by AntennaPod.)

**Comment by pazos** [comment]
> But how does this make any sense? I know how deeply broken Android is, but now it can't even support normal everyday use?

It doesn't make any sense. Any sense at all, but it is called a "security feature", so..err.

I see a few options:
1 - disable action.VIEW if scheme ~= file. (Everything will work inside KOReader as always but the program won't be shown in the "app picker" for supported mimetypes).
2 - get the file name and search the whole sdcard(s) looking for a file that matches that name.
3 - if firmware_rev > oreo show a Infomessage: you tried to open the file "filename" but this version of android cannot provide us the full path of your file, so we cannot open it directly. Please install a non-broken version of android (if exists) or just open the file using KOReader filemanager.

I don't see the duplicate and open method as a valid alternative.

**Comment by pazos** [comment]
A good example for adding the "import content" stuff is [LibreraReader](https://github.com/foobnix/LibreraReader/blob/bc7034e257df1837c4116183b3d98f0b38fa0cf6/app/src/main/java/com/foobnix/OpenerActivity.java#L34-L80).

**Comment by Frenzie** [comment]
Could you also add some links to relevant docs here? For others and future reference.

**Comment by pazos** [comment]
#### android intent docs:
https://developer.android.com/guide/components/intents-filters
https://developer.android.com/reference/android/content/Intent.html#ACTION_VIEW
https://developer.android.com/reference/android/content/Intent.html#getData()

#### this explains why we cannot obtain a full path from an intent uri
https://stackoverflow.com/a/53080567

#### which leads to:
https://commonsware.com/blog/2016/03/15/how-consume-content-uri.html
https://developer.android.com/reference/android/content/ContentResolver.html#openInputStream(android.net.Uri)

**Comment by Frenzie** [comment]
Ah, this explains why some apps feel so broken in how they handle files. I thought it was them being stupid, but it's them not copying the InputStream for safekeeping…

I'm going to need a while to grab my head around this. This might indeed trump it all.

Now I read your before-last link. I cannot being to express how distasteful and condescending that was.

https://commonsware.com/blog/2016/03/15/how-consume-content-uri.html
> How Long Can I Use the Uri?
>
>Not long.
>
>Assuming that nothing happens on the provider’s side, the Uri should be valid for the duration of your process, but it may not be valid after that.
>
>Think of a Uri as being akin to a deep-link URL to some content that requires authentication. The URL that you get may be good right now, because the user has an authenticated session. The URL may be good for a little while longer, so long as the session is still around. But eventually that session will time out, and the URL will not be useful any longer.

Which is why one downloads files. To the local filesystem. Where it's available forevermore. Duh.

> Google’s vision is for content Uri values to be the Android equivalent of http/https in Web apps: universally understood and used.

That's not even close to equivalent. That's a direct contradiction to the above. Because — get this — only files that require authentication require authentication. I know, it's a tautology. My local files work *until such time as I delete them*. In fact, so do my URLs. There's some trickery involved, but if you go to http://frans.lowter.us/2005/12/aha-i-am-a-student/ you'll end up on https://fransdejonge.com/2005/12/aha-i-am-a-student/. All of my URIs still work now, 14 years later. Don't you *dare* tell me this is comparable. Don't you dare tell me that my local filesystem paths, also stable for over a decade thanks to a permanent URI system known as "mount points" is in any way inferior to this complete and utter bile.

More flexible? More fine-grained security? Get the fuck out of here.

**Comment by pazos** [comment]
> More flexible? More fine-grained security? Get out of here

The new approach can prevent metadata leaking among other stuff. We only see the bad parts of it because we are the destination of the content and not the provider. And probably we're a corner case and **google just doesn't care** :tm: 

case study: a random bank app, where you can download pdfs with information. The program does not provides a pdf viewer and relies on the system, which queries packages with the action.VIEW for its mimetype.

To download the pdf you need read and write permission granted on the bank app, but to open it with some random viewer you won't need to grant that permission on the viewer.

As the permission *read and write sdcard* is considered special(a.k.a insecure), it is **bad design** to allow  those random pdf viewers to even read the sdcard (we're talking about sandboxes here, not about the desktop paradigm).

So in a certain way google is trying to fix what was broken and in their way to *almost* fix basic **security issues** they managed to get a system where:

- system apps have all permissions they want even if they're contentspyware like google services, or plain malware like most **pepuchi** phones. **Google apps have all permissions granted** and *some* 
**vendor services are tracking** *something* on your phone.

- installed apps are **ready for billing** and  providing the false feeling of **user choice** asking for each permission when the user use that function for the first time.

So, in that sense Apple did it better, since it is the only vendor that can put crapware on your phone. Also they restricted what the user can do with their phone first, so another point for them.

You would love iOS /s

**Comment by Frenzie** [comment]
> The new approach can prevent metadata leaking among other stuff. We only see the bad parts of it because we are the destination of the content and not the provider. And probably we're a corner case and google just doesn't care tm

No, I'm not speaking as a developer. I'm speaking as a user. 

> case study: a random bank app, where you can download pdfs with information. The program does not provides a pdf viewer and relies on the system, which queries packages with the action.VIEW for its mimetype.
>
>To download the pdf you need read and write permission granted on the bank app, but to open it with some random viewer you won't need to grant that permission on the viewer.

This sounds superficially sensible as a niche use case. It could even almost work as a generalized approach *if and only if* the provider could state that the URI in question can safely remain available forever.

I say almost, because having multiple distinct URIs or paths to the same file would still be a usability nightmare. For the vast majority of files, what I want *as a user* is a \~URI~ that remain stable unless I purposefully change them. As opposed to the OS assigning multiple URIs to the same file for \~flexibility~ and \~security~.

Incidentally, as a user I still need to store my bank PDFs because even if I were to remain a customer, they start deleting their records after a few years. Or in any case not showing them to me anymore without the ability to export them either.

So no, this case study still makes absolutely no sense whatsoever. One obviously needs these PDFs locally and evidently you need viewers to open them.

Filesystems other than FAT32 also happen to have a little something called access rights. The supposed lack of flexibility was quite purposefully manufactured and self-imposed.

Basically all we've got here is a complex over-engineered reimplementation of a temporary directory with dynamic read/write access rights. How much should we bet that as icing on the cake it'll also be a 100 times slower?

> As the permission read and write sdcard is considered special(a.k.a insecure), it is bad design to allow those random pdf viewers to even read the sdcard (we're talking about sandboxes here, not about the desktop paradigm).

The sandbox "paradigm" makes my \~smart~ "computer" a mostly worthless piece of metal and plastic when it's disconnected. And how exactly is it supposed to be more secure if all my info is stored on Google's servers, anyway? They could be spied on, lost or stolen 24/7. Of course I'm more secure with a device that can't do much of anything, but a Nokia 3310 can(not) do all that for less than € 50.

I'll also drop this here: https://lateblt.livejournal.com/308120.html

> You would love iOS /s

Out of the box it's a usability nightmare (whoever came up with this concept of "autocorrect" has a serious screw loose), but apps seemed to be capable of opening files without delay or forgetting about them, unlike on Android. (Perhaps this is merely indicative of them actually thinking things out properly at the start, regardless of the merits of what they thought out, instead of constantly breaking things.) The second thing I noticed, after autocorrect, is that you apparently can't send or receive files over Bluetooth.

So yes, iOS would seem to be even worse than Android (as a user). Quite an achievement, I must say.

**Comment by pazos** [comment]
> Incidentally, as a user I still need to store my bank PDFs because even if I were to remain a customer, they start deleting their records after a few years. Or in any case not showing them to me anymore without the ability to export them either.

> So no, this case study still makes absolutely no sense whatsoever. One obviously needs these PDFs locally and evidently you need viewers to open them.

As an user you can do whatever you want with your pdf files. Hell you can even take a screenshot and share it via instagram or print copies on paper and expose your account state. But the idea is that the actions involved (take a screenshot, print a copy, view the pdf) aren't leaking by themselves.

> The sandbox "paradigm" makes my ~smart~ "computer" a mostly worthless piece of metal and plastic when it's disconnected. And how exactly is it supposed to be more secure if all my info is stored on Google's servers, anyway?

True, this is by design. Lets say you are fine with google or apple having acess to all your files but you don't trust some other party. So you have an option to store your sensitive data on the cloud and downloading locally whenever you want. If you try to preview that file on some clumsy application you are "safe" unless you granted the application the "insecure" permissions. In that case you shot yourself in the foot (they say).

**Comment by Frenzie** [comment]
> As an user you can do whatever you want with your pdf files. Hell you can even take a screenshot and share it via instagram or print copies on paper and expose your account state. But the idea is that the actions involved (take a screenshot, print a copy, view the pdf) aren't leaking by themselves.

I don't see how an app storing its own copy of the file being processed is any less "leaky" unless you prevent them from doing that. My available disk space would be leaking away pretty quickly though.

I suppose you mean none of my other files would have the potential of "leaking" at the same time, but you can very easily achieve such sandboxing with ACL. (Google even cleverly made apps their own users… one of the few things about Android that doesn't strike me as broken by design.)

https://bencane.com/2012/05/27/acl-using-access-control-lists-on-linux/

**Comment by pazos** [comment]
I'm closing this issue since, strictly speaking, cannot be fixed.

https://github.com/koreader/android-luajit-launcher/pull/138 is still open as a way to workaround android limitations, but even with workarounds we can't solve this issue: **"cannot open files from other applications"**
