### ISSUE TITLE
Enable inverted button mapping on Forma

### ISSUE THREAD

**Issue by alethiophile** [koreader/koreader#4446]
* KOReader version: v2018.12-44-g41b885f_2019-01-03
* Device: Kobo Forma

#### Issue
On the Forma, I find the "default" (bottom next, top previous) button layout basically unusable. Nickel offers an option to invert the sense of the buttons, but Koreader doesn't.

(I could always just hack the mapping file manually for this one device, but that's annoying and fragile.)

#### Steps to reproduce
1. Invert button mapping in Nickel
2. Run Koreader
3. Notice buttons are still in default mapping, cringe with anticipated RSI

**Comment by Frenzie** [comment]
> (I could always just hack the mapping file manually for this one device, but that's annoying and fragile.)

Annoying perhaps, but fragile depends on how you hack it. ;-)

I think I might have a branch around somewhere with simple user event map support; I'll have to remember to look for it.

**Comment by poire-z** [comment]
There is also (already implemented) the possibility to override keymap by creating `koreader/settings/event_map.lua` (see mine for the emulator in https://github.com/koreader/koreader/pull/3862#issue-181100453).

If the default keymap is:
https://github.com/koreader/koreader/blob/ea424e621ea88ef0519e86112b0373adb5b6efa2/frontend/device/kobo/device.lua#L240-L250

creating `koreader/settings/event_map.lua` with these 2 keys inverted might work:
```
return {
            [194] = "RPgBack",
            [193] = "RPgFwd",
 }
```

**Comment by NiLuJe** [comment]
Is this documented anywhere? (pinging the great Wiki wizard @AlanSP1 ;)).

**Comment by poire-z** [comment]
I guess that if that works, it could just be made into a menu item in `Navigation> Invert next/prev buttons` (shown on device with keys), and the inversion of `193` and `194` taken care in frontend/device/kobo/device.lua where `G_reader_settings` is available and already used (for `kobo_touch_switch_xy`).

**Comment by AlanSP1** [comment]
> Is this documented anywhere? (pinging the great Wiki wizard @AlanSP1 ;)).

I didn't documented it (before). And I didn't know that there's possibility for keymap editing, as I have H2O and it doesn't have physical keys.

I'm going to create document now:

**Comment by NiLuJe** [comment]
I was thinking about doing it in kobo/device, but it's a tiny bit clunky because the mapping is initalized *after* the per-device setup, in a global init sink.

Which implies setting a flag in the per-devcie bit, and mangling the event map setup in the global init.

That felt clunky and I wasn't quite sure how to go about it, but now that I know there's already something roughly doing something similar somewhere, I can see how that works...

**Comment by poire-z** [comment]
> until we get nickel's config read, whenever that is, to track Nickel's status of this flag.

I don't think we'd need to have that sync'ed with Nickel, we have our own settings, and it's not something the user will change often :) (or should we because of that orientation/rotation sensor?)

(I understand syncing frontlight level and state make sense to avoid hurting our eyes, or getting in the dark, or illuminating the room, when switching reader app).

**Comment by NiLuJe** [comment]
Eh, true enough ;p.
