### ISSUE TITLE
[feature request] within scroll mode, make next/previous page render like it does in page mode [epubs]

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4533]
* KOReader version: 2019.01.01
* Device: PW4

#### Issue
I highlight a lot of text.  B/c multi page highlight doesn't seem supported currently, I need to be in scroll mode to get the text that I want to highlight all on one page.  Ideally there'd be multi page highlight but until then, I do this.

I've noticed that simply tapping the next page does turn the page but then it 'clips' (see attachment) text at the top/bottom line.  I'd like it if hitting next page resulted in the same top/bottom margin as it would in page mode.  

![image](https://user-images.githubusercontent.com/556667/52082868-8bdcbc80-2563-11e9-962f-2ef7aacd8d95.png)

**Comment by DanBenHa** [comment]
I would also like this. My reader is Kobo Glo HD.

**Comment by NiLuJe** [comment]
That's a very old bug (there might actually be something still open about this).

Last time I checked (which was, err, a few years ago), at a very quick glance (I don't use scroll mode), the "take the status bar into account" bit seemed sane, but obviously, it isn't ;).

See also the DOVERLAP shenanigans which make no damn sense.

**Comment by poire-z** [comment]
Not sure it's a bug :)

Scroll mode with EPUB is just cutting and showing slices of the big document considered as a single huge image of eg. width 1000 and height 400,000.
So, there's no way to avoid cutting in the middle of a text line (we avoid that in page mode, because crengine then find the best cut point, between text lines, when splitting them into pages) - and there's some stuff with clipping in crengine where drawing glyphs at clipping boundaries may sometimes have some of them not drawn.

You can see how it would look with some added top and bottom margins with:
```diff
--- a/frontend/apps/reader/modules/readerview.lua
+++ b/frontend/apps/reader/modules/readerview.lua
@@ -424,11 +424,14 @@ function ReaderView:drawPageView(bb, x, y)
 end

 function ReaderView:drawScrollView(bb, x, y)
+    local smaller_visible_area = self.visible_area:copy()
+    smaller_visible_area.h = smaller_visible_area.h - 40
     self.ui.document:drawCurrentViewByPos(
         bb,
         x + self.state.offset.x,
-        y + self.state.offset.y,
-        self.visible_area,
+        y + self.state.offset.y + 20,
+        -- self.visible_area,
+        smaller_visible_area,
         self.state.pos)
 end
```
And you would get text lines cut with some blank space above or below, which looks to me even worse (currently, these cuts happen at the bezel boundaries, so you get it:  _of course it's cut, we can't draw outside of screen_ :)

<img src="https://user-images.githubusercontent.com/24273478/52107458-af9d1280-25f6-11e9-957d-f30ffa131143.png" width=300> <img src="https://user-images.githubusercontent.com/24273478/52107705-b0827400-25f7-11e9-9cb6-a4004dad258b.png" width=300>

And we do take footer height into account, and that overlap thing can make sense, to somehow survive the arbitrary cut lines that can become unreadable, by having them in grey on the next page. Scroll mode in cre doesn't use the DOVERLAP settings, but try to guess the height of that grey area needed to show 1 or more lines of text (which obviously, as we cut slices in the raw document and have no access to what font is used at that cut point, can stil be wrong):

https://github.com/koreader/koreader/blob/c0c4bcdace7121133ffd5f19f9848e040261801c/frontend/apps/reader/modules/readerrolling.lua#L45-L46

https://github.com/koreader/koreader/blob/c0c4bcdace7121133ffd5f19f9848e040261801c/frontend/apps/reader/modules/readerrolling.lua#L525-L534

So, well, scroll mode is just what is is: not that nice and useful, and if we were to make it better, it would become page mode :)

**Comment by Frenzie** [comment]
I'll close this since it's kind of contradictory and multi-page highlight is a thing now. ;-)
