### ISSUE TITLE
FR: Modify behavior of highlighting across pages (don't go back to beginning of the highlight upon completion)

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4574]
* KOReader version: 2019.02 nightly
* Device: PW4

hey team!

so I _love_ being able to highlight text across multiple pages on my PW, thanks to the most recent nightly.

but one thing i've noticed is that if i "miss" (i..e highlight the wrong bit of text) the software goes back to previous page position.

it seems like the best user experience would be (of course I have no idea how hard to implement this would be so please take your grain of salt):

do not move the user back to the original page position, but rather leave the user on the most recent page highlighted.  why?  also, chances are the user has read the pages they're highlighting and so there's no need to go back to a previous page. 

also would be in line with how kindle does it, not that that should really matter deeply

**Comment by poire-z** [comment]
> but one thing i've noticed is that if i "miss" (i..e highlight the wrong bit of text) the software goes back to previous page position.

Well, that's good isn't it? So you can re-do the highlighting process from the start - instead of being a bit lost in the next page you haven't really yet figured out the layout because in scroll mode you saw only some part of it.

> chances are the user has read the pages they're highlighting and so there's no need to go back to a previous page.

Or chances he has not really read it seriously while finger fighting with highlights, and want to re-read it.
Anyway, you're just one page back. Better to show again the start of the highlight, so you tap forward and see the end of the highlight, and you can check all is ok, and go on reading.

And logically, if you have read what you want to highlight, you would have started the highlight from the end (so, from the 2nd page), and selected text backward: you would be scrolled up, and continue selecting to the start. In that case, you'll be brought back to the 2nd page, so to the end of the highlight (which is what you request).

I think the current behaviour is the less surprising.

(Also, when you are already in scroll mode, there is no previous page restoration.)

**Comment by NiLuJe** [comment]
Yeah, going back to the *original* position makes more sense to me, too, FWIW.

**Comment by arooni** [comment]
Interesting... I can accept that I might be in the minority.  

I guess what I most often do is highlight something and then decide to highlight a little more based on the text that I couldn't see on the next page.  As I'm highlighting it I'm reading it so I have no need to go back to the previous page.  

I think if the #4555 is something that people want this may be an issue (i.e. how to adjust the highlight by one word forward/back if the highlight spans two or more pages?

**Comment by Frenzie** [comment]
@arooni I would highlight from the start, not the end, and it seems disorienting to me to switch back to where you started the highlight (no matter if it's at the "end" or the "start").

But it's not really clear to me how I'm supposed to do try out this multipage highlight thing?
