### ISSUE TITLE
[bug?] after downloading a dictionary on an android device via koreader, and restarting, doesn't show up as installed dictionary

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4586]
* KOReader version: 2019.02.01 stable
* Device: Kindle fire 10

#### Steps to reproduce
1) install koreader latest apk on your device
2) go to download dictionaries on lookup menu, download dictionary.  
3) download dictionary.  
4) restart koreader
5) see 'installed dictionaries (0)' even though you've already downloaded the dictionary (verified this with trying to download it again, but says "overwrite?"    

*update: same happened on my google pixel xl

**Comment by Frenzie** [comment]
The problem is one that I noted elsewhere, though I can't seem to find where. In this case the tar executable doesn't seem to have proper access.
```
02-15 11:14:09.800  6091  6104 V KOReader:  file downloaded to /storage/emulated/0/koreader/data/dict/gcide.tar.gz
02-15 11:14:09.806  6091  6104 W KOReader: command ./tar xf "/storage/emulated/0/koreader/data/dict/gcide.tar.gz" -C "/storage/emulated/0/koreader/data/dict" returned 2
02-15 11:14:09.806  6091  6104 V KOReader:  stdout: 
02-15 11:14:09.806  6091  6104 V KOReader:  stderr: ./tar: "/storage/emulated/0/koreader/data/dict/gcide.tar.gz": Cannot open: No such file or directory
02-15 11:14:09.806  6091  6104 V KOReader: ./tar: Error is not recoverable: exiting now
```

Error handling could definitely be better here.

The extraction command works if I run it as root, but it doesn't when run from KOReader — which seems weird, because KOReader has permission to write here.

Investigating with the proper user:
```
$ adb exec-out run-as org.koreader.launcher /data/user/0/org.koreader.launcher/files/tar xf "/storage/emulated/0/koreader/data/dict/gcide.tar.gz" -C "/storage/emulated/0/koreader/data/dict"
/data/user/0/org.koreader.launcher/files/tar: gcide/stardict.idx: Cannot utime: Operation not permitted
/data/user/0/org.koreader.launcher/files/tar: gcide/stardict.dict.dz: Cannot utime: Operation not permitted
/data/user/0/org.koreader.launcher/files/tar: gcide/stardict.syn: Cannot utime: Operation not permitted
/data/user/0/org.koreader.launcher/files/tar: gcide/stardict.ifo: Cannot utime: Operation not permitted
/data/user/0/org.koreader.launcher/files/tar: gcide: Cannot utime: Operation not permitted
/data/user/0/org.koreader.launcher/files/tar: gcide: Cannot change mode to rwxrwxr-x: Operation not permitted
/data/user/0/org.koreader.launcher/files/tar: Exiting with failure status due to previous errors
```

```
root@generic_x86:/storage/emulated/0/koreader # ls -l
drwxrwx--x root     sdcard_rw          2019-01-09 18:16 cache
drwxrwx--x root     sdcard_rw          2017-10-22 22:05 clipboard
drwxrwx--x root     sdcard_rw          2017-11-06 13:28 data
drwxrwx--x root     sdcard_rw          2018-11-22 20:37 help
drwxrwx--x root     sdcard_rw          2017-10-22 22:05 history
-rw-rw---- root     sdcard_rw     1031 2019-02-10 20:36 history.lua
drwxrwx--x root     sdcard_rw          2017-10-22 22:05 news
drwxrwx--x root     sdcard_rw          2018-12-14 16:45 ota
drwxrwx--x root     sdcard_rw          2017-10-22 22:05 screenshots
drwxrwx--x root     sdcard_rw          2018-03-05 15:00 send2ebook
drwxrwx--x root     sdcard_rw          2019-02-15 11:24 settings
-rw-rw---- root     sdcard_rw     1624 2019-02-15 11:24 settings.reader.lua
-rw-rw---- root     sdcard_rw     1624 2019-02-15 11:24 settings.reader.lua.old
drwxrwx--x root     sdcard_rw          2018-11-22 20:27 styletweaks
d data/    
```

Okay, so the ownership on these folders looks wrong. They're all owned by root, even though they were created by KOReader. I suspect there might be some kind of FAT32 involvement here.

The investigation continues…

**Comment by poire-z** [comment]
I guess as it's FAT, there's no permissions/owner/group, so it shows root:sdcard_rw as I guess it's how it's mounted.
Might only need to look at tar options to have it not try to change perms/ownership, or just not return a failure status if these fails.

**Comment by Frenzie** [comment]
Okay, the simple diplomatically phrased answer that Android is odd and a little slow:[1] https://issuetracker.google.com/issues/36930892#c128

[1] We'll leave the undiplomatic way of phrasing it to the imagination. https://stackoverflow.com/questions/2033914/is-quitting-an-application-frowned-upon/18691453#comment18083659_4904919 https://www.xda-developers.com/diving-into-sdcardfs-how-googles-fuse-replacement-will-reduce-io-overhead/

@poire-z Adding `-m` half works, which could potentially even be added generally (but I'm against braindead and stupid Android pandering — I would add a full Android check to clearly shame it). I can't seem to find anything in the tar manual about not messing with permissions though.

```
$ adb exec-out run-as org.koreader.launcher /data/user/0/org.koreader.launcher/files/tar xfm "/storage/emulated/0/koreader/data/dict/gcide.tar.gz" -C "/storage/emulated/0/koreader/data/dict"
/data/user/0/org.koreader.launcher/files/tar: gcide: Cannot change mode to rwxrwxr-x: Operation not permitted
/data/user/0/org.koreader.launcher/files/tar: Exiting with failure status due to previous errors
```

(Technically setting executable here is actually a flaw in the gcide .tar.gz file itself, but since the same problem would exist when setting more appropriate permissions it's pretty much besides the point.)

**Comment by Frenzie** [comment]
Other options like `--no-same-permissions` apply the user's umask. There doesn't seem to be a "just ignore the damned permissions altogether" option. Because we have successful extraction here, at least from my command. There doesn't seem to be from KOReader, so I might be overlooking something still.

I was thinking I might be able to pipe this stuff from tar to LuaJIT and just write it that way… it sounds overly complicated but I'm not really seeing another solution at this point.

**Comment by Frenzie** [comment]
@poire-z 

> Might only need to look at tar options to have it not try to change perms/ownership, or just not return a failure status if these fails.

Ooh, actually that might work. We can't rely on the error status as such, but if the error status only has `Cannot change mode` errors then it can still be regarded as a success. I'll give that idea some playtime later.

**Comment by poire-z** [comment]
Btw, `util.unpackArchive()` doesn't seem to clean up the extracted stuff when tar returns an error. So, even if it does, the extracted dict content should be there and work, no?

**Comment by Frenzie** [comment]
In the course of investigating tar I completely forgot about the original issue:

```
02-15 11:14:09.806  6091  6104 V KOReader:  stderr: ./tar: "/storage/emulated/0/koreader/data/dict/gcide.tar.gz": Cannot open: No such file or directory
```

**Comment by pazos** [comment]
`tar xf` should work. It is already used in https://github.com/koreader/koreader/blob/master/platform/android/llapp_main.lua#L27.

BTW that line seems wrong because we're relying on system tar instead of using our own binary.

**Comment by Frenzie** [comment]
@pazos That OTA stuff is exactly what I was talking about when I said that "I noted [the same problem] elsewhere, though I can't seem to find [in which issue]." The system tar thing is true, though probably irrelevant as far as the actual problem goes. There's some stuff there worth investigating in any case.

**Comment by Frenzie** [comment]
@pazos I realize now why I couldn't find it. It's the same error, but with zsync instead.

```
W/KOReader( 3664): command ./zsync -o '/storage/sdcard/koreader/ota/koreader.updated.tar' -u 'http://ota.koreader.rocks:80/' '/storage/sdcard/koreader/ota/koreader-android-x86-latest-nightly.zsync' returned 2
V/KOReader( 3664):  stdout: 
V/KOReader( 3664):  stderr: '/storage/sdcard/koreader/ota/koreader-android-x86-latest-nightly.zsync': No such file or directory
```

I suspect this problem may only affect Android 4.0 and higher, though that's a moot point.

Anyway, one of the perhaps more obvious things I hadn't tried is `io.popen` instead of `os.execute`. Using a pipe that way does in fact seem to work, but it has the obvious drawback of not getting a return value.

But it looks like we might be able to get around that thanks to Lua 5.2 stuff: https://github.com/LuaJIT/LuaJIT/commit/cfca926cc2e2b63e94492f0a1f5c033f6db3a6f5

**Comment by poire-z** [comment]
Fwiw, we have in base/ffi/util.lua [util.execute(...)](https://github.com/koreader/koreader-base/blob/3492c1fcec0eca4718eb54c3aa1b2d87ab511eba/ffi/util.lua#L205-L220) which uses some android module specific stuff on Android (dunno why or what it does, just pointing that out).

**Comment by Frenzie** [comment]
@poire-z Ah, thanks.

https://github.com/koreader/koreader-base/commit/6078a77d92580c5244f834e965d0fbed11ba917b

It's not quite clear to me why it would be safer than os.execute, but either way [the Android stuff](https://github.com/koreader/android-luajit-launcher/blob/bd0e58711d3268ec383b7d379ea06590f38166f6/assets/android.lua#L1566-L1611) might be another possible solution (although when using Lua 5.2 io.popen that entire function could probably be deprecated — anyway, focus, focus…).

**Comment by Frenzie** [comment]
@poire-z The good news is that it works, at least as well as might be expected:

```
02-15 16:21:08.267  7376  7389 V KOReader:  file downloaded to /storage/emulated/0/koreader/data/dict/gcide.tar.gz
02-15 16:21:08.351  7376  7389 W KOReader: command ./tar xf /storage/emulated/0/koreader/data/dict/gcide.tar.gz -C /storage/emulated/0/koreader/data/dict returned 2
02-15 16:21:08.351  7376  7389 V KOReader:  stdout: 
02-15 16:21:08.351  7376  7389 V KOReader:  stderr: ./tar: gcide/stardict.idx: Cannot utime: Operation not permitted
02-15 16:21:08.351  7376  7389 V KOReader: ./tar: gcide/stardict.dict.dz: Cannot utime: Operation not permitted
02-15 16:21:08.351  7376  7389 V KOReader: ./tar: gcide/stardict.syn: Cannot utime: Operation not permitted
02-15 16:21:08.351  7376  7389 V KOReader: ./tar: gcide/stardict.ifo: Cannot utime: Operation not permitted
02-15 16:21:08.351  7376  7389 V KOReader: ./tar: gcide: Cannot utime: Operation not permitted
02-15 16:21:08.351  7376  7389 V KOReader: ./tar: gcide: Cannot change mode to rwx------: Operation not permitted
02-15 16:21:08.351  7376  7389 V KOReader: ./tar: Exiting with failure status due to previous errors
```

But, um, os.execute on Android is literally that exact same function since it's overwritten right there. Which is actually a very helpful thing to realize, because that means that most of the issue probably originates [right here](https://github.com/koreader/android-luajit-launcher/blob/bd0e58711d3268ec383b7d379ea06590f38166f6/assets/android.lua#L1640).

**Comment by Frenzie** [comment]
Just using plain `os.execute` (as opposed to the special Android one) works. This is good. This doesn't give us any info about stdout and stderr.

Using this patched function also works:
```diff
diff --git a/assets/android.lua b/assets/android.lua
index c248377..6f82c14 100644
--- a/assets/android.lua
+++ b/assets/android.lua
@@ -1637,7 +1637,12 @@ local function run(android_app_state)
     os.execute = function(command) -- luacheck: ignore 122
         if command == nil then return -1 end
         local argv = {}
-        command:gsub("([^ ]+)", function(arg) table.insert(argv, arg) end)
+        command:gsub("([^ ]+)", function(arg)
+            -- strip quotes around argument, since they are not necessary here
+            arg = arg:gsub('"(.*)"', "%1") -- strip double quotes
+            arg = arg:gsub("'(.*)'", "%1") -- strip single quotes
+            table.insert(argv, arg)
+        end)
         return android.execute(unpack(argv))
     end
```

For the moment I propose the latter, but if I find the time I'd like to experiment with Lua 5.2 io.popen instead.

**Comment by pazos** [comment]
@Frenzie does the patched function fix the "Cannot utime" issue or just the "No such file or directory"?

**Comment by Frenzie** [comment]
@pazos Just no such file or directory. It's caused by the fact that `os.execute` takes a full command whereas `android.execute` takes a command and arguments separately. Splitting on spaces in the Android-specific `os.execute` override thus causes correctly quoted arguments to have quotes where there should be none.

The other stuff is largely a non-issue, except that tar annoyingly returns an error status due to one of the countless fundamental deliberate Android design flaws.

As an aside, KOReader seems to run alright with `-DLUAJIT_ENABLE_LUA52COMPAT` (which includes better return values for `os.execute` and `io.popen`). I didn't test it in great detail of course.

### 5.2 compat compile flag
```lua
koreader$ ./luajit 
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> bla, alb, blabla = os.execute("echo asdfasdf")
asdfasdf
> print(bla)
true
> print(alb)
exit
> print(blabla)
0
```

### Regular 5.1
```lua
koreader$ ./luajit 
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> bla, alb, blabla = os.execute("echo asdfasdf")
asdfasdf
> print(bla)
0
> print(alb)
nil
```

For io.popen, that works like this:

### 5.2
```lua
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> file = io.popen("dmesg")
> output = file:read("*all")
> rc = {file:close()}
-- this is now the same as os.execute, only "true" in 5.1
> print(rc[1])
true
> print(rc[2])
exit
> print(rc[3])
0
-- but now we also have output
> print(output
>> )
[    0.000000] microcode: microcode updated early to revision 0x25, date = 2018-04-02
[    0.000000] Linux version 4.19.0-2-amd64 (debian-kernel@lists.debian.org) (gcc version 8.2.0 (Debian 8.2.0-14)) #1 SMP Debian 4.19.16-1 (2019-01-17)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.19.0-2-amd64 root=UUID=385ba27c-d50a-4ffb-8bca-591b59847ce6 ro quiet
-- etc.
-- or replicating our os.execute example above:
> file = io.popen("echo asdfasdf")
> output = file:read("*all")
> rc = {file:close()}
> print(rc[1], rc[2], rc[3])
true	exit	0
> print(output)
asdfasdf

> 
```

Btw @NiLuJe any thoughts on `-DLUAJIT_ENABLE_LUA52COMPAT`?

**Comment by NiLuJe** [comment]
IIRC, it's designed to have minimal impact on existing codebases?

**Comment by Frenzie** [comment]
@NiLuJe Yes, afaik it's basically just a few niceties like the above, that are unlikely to break much of anything. And even if it does break something, fixing it should be as straightforward as it comes.

It's more the reverse that worries me.
