### ISSUE TITLE
Screensaver issue when landscape reading

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4621]
* KOReader version: v2019.02-57-ge3bcd6c_2019-02-19/ 
* Device: KA1

#### Issue
Part of screensaver picture is left on screen when you start the device after put it to sleep when reading in landscape mode. (It disappears after screen refresh.)
Example:
![img_20190219_135323709](https://user-images.githubusercontent.com/32645430/53016838-e1173a00-344e-11e9-9d95-ebf7ca73ce2c.jpg)

#### Steps to reproduce
Put your device to sleep when reading book in landscape. 
Start the device.

**Comment by Frenzie** [comment]
Confirmed.

Changing this line from #4541 to `yes` works around the problem, but the underlying cause is clearly some more insidious portrait/landscape confusion somewhere:

https://github.com/koreader/koreader/blob/388871a2c3ac50ad1c2e0d474c9a1ed708900774/frontend/device/kobo/device.lua#L36-L37

Pinging @NiLuJe who might know something otoh.

**Comment by NiLuJe** [comment]
Huh. I'll look into it ;).
