### ISSUE TITLE
Merging highlights

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#4670]
There was a question in a KoHighlights' [issue](https://github.com/noembryo/KoHighlights/issues/1#issuecomment-467427732) from a user, about the possibility to merge different highlights from the same book in different devices.
My answer was negative at first, because I thought that with different devices, the position info in the highlight would create problems when read from other devices.

But then I thought that I don't know that for sure, so here I am, asking.
The highlight's data consists from two keys.
One in the `["bookmarks"]` key and another at the `["highlight"]` key.
E.g. this inside the `["bookmarks"]`
```
        [3] =     {
            ["text"] = "fair!",
            ["notes"] = "wasn’t fairl",
            ["datetime"] = "2019-02-20 22:54:10",
            ["highlighted"] = true,
            ["page"] = "/body/DocFragment[20]/body/div[2]/p[30]/text().392",
            ["pos0"] = "/body/DocFragment[20]/body/div[2]/p[30]/text().392",
            ["pos1"] = "/body/DocFragment[20]/body/div[2]/p[30]/text().404"
        },
```
and this inside the `["highlight"]`
```
        [209] =     {
            [1] =         {
                ["drawer"] = "lighten",
                ["datetime"] = "2019-02-20 22:54:10",
                ["text"] = "wasn’t fairl",
                ["pos0"] = "/body/DocFragment[20]/body/div[2]/p[30]/text().392",
                ["pos1"] = "/body/DocFragment[20]/body/div[2]/p[30]/text().404"
            }
        },
```
And the question is this:
If I open the same book with another device and highlight the exact same words, are the `["page"] ["pos0"] ["pos1"]` going to be the same?

A second question, about the `[209]` key is:
If this number is not right (since a different screen format and/or font and/or size would produce different amount of pages) what would happen to the highlight?

Is there anything else that I missed and needs to be addressed?

**Comment by poire-z** [comment]
From what I understand from having read the code:
Both the `highlight` and `bookmarks` tables are updated when a highlight is made (or adjusted with the recently added feature).
Why there was at one time the need to have 2 tables, I don't know. But currently, the `highlight` is used by the drawing code (to draw the little grey boxes or underlines), while the `bookmarks` is used for bookmark listing, editing text...

I don't think the `[209]` key matters. It's the original page number that this highlight was on when it was added, but indeed, when you change font size, the page numbers changes, so this key is just a slot. The code loop thru each subtree (to meet all the bookmarks/highlights), ignoring this value.

The `["page"]` you mention is actually a XPointer (xpath), and looks like it is the same as `pos0` value.
Later, when displaying, I guess the code gets the current page that this xpointer is in, so it's queried dynamically from the engine.

The xpointers should be stable across devices, but there are cases when changes/fixes/new features in crengine may make them invalid.
When I added such stuff, i took care of updating another thing that you can find in the metadata.lua:
`["cre_dom_version"] = 20180528,`
And I took care that a past'ly opened book would request it's old dom version so the engine would still work the same way it did previously (so, voluntarily disabling fixes and features in that case), so the highlights are not broken. (It's quite possible that I missed some changes that could break highlights and forgot to upgrade the engine dom version - but when I knew that it could, I did ensure that).
Some discussion about that in #3940 and #3976 and https://github.com/koreader/crengine/pull/172#issuecomment-386384050

So, highlights you would took from 2 books with the same `cre_dom_version` should be similar and mergeable.
Those from books opened with different koreader versions that happened to be different enough to have different `cre_dom_version` may be unmergable, and some highlights from one not be shown on the other.

You can see the historical cre_dom_version and the whys at https://github.com/koreader/crengine/blob/fca482f9c57bc8fd9a7e047b6eb6f7f6ab4211a7/crengine/src/lvtinydom.cpp#L15-L57
(There was a bunch in may 2018, none since - but I may bump it again in a few weeks if I ever manage to add support for float:s)

**Comment by poire-z** [comment]
The side effect of this is that if you had opened a book in 2016, even on the laster koreader nightly version, you would request the engine to behave like it did in 2016 (even if you have never highlighted anything), so the highlight if any would still show - and you would not get some fixes and new features.

The only solution to get these fixes and new features is to explicitely "Purge .sdr" (so losing your highlights), so, as there's no past, the engine will use the lastest and best dom version.

**Comment by noembryo** [comment]
This is very promising. It does give me something to check before creating a non working file.
I can ensure that the `cre_dom_version` is the same before merging anything.
I have to read these links you provided, but since the page key is irrelevant, I think that is doable..
Thanks for the answer.

**Comment by poire-z** [comment]
Just mentionning that for completness (I think that's no concern of yours with kohighlights):

When one get this popup (from #3968, after playing with _some_ styletweaks - mostly those with `display:` changes):

<kbd>![image](https://user-images.githubusercontent.com/24273478/40278101-28db056c-5c2b-11e8-99da-680579e3c728.png)</kbd>

The document is fully reloaded, the DOM is rebuilt (with no cre_dom_version change), with styles that may change the xpaths, and so break some highlights.
Reverting the style tweak that provoked that message should bring back the past highlights.

I don't know if it can be a feature or not for kohighlight to backup/save the list of styletweaks, to eventually allow restoring its state if the user feels like "damned, I lose them, fortunately I backuped them in kohighlights". (But you told me you don't do restore I think.)

**Comment by noembryo** [comment]
I try to avoid messing around with KoReader apart from editing the metadata files (for the comment only).
Looking at an example, I only see a `["css"]` key but nothing about styletweaks.
Maybe its not there because I never used them.
If there was something in the metadata file, I could try to warn at least the user about a potential problem..

**Comment by poire-z** [comment]
One can have:
```lua
    ["style_tweaks"] = {
        ["lineheight_all_inherit"] = true,
        ["titles_page-break-before_avoid "] = true,
        ["widows_orphans_all_5"] = true
    },
```
But yeah, nothing for you to worry about, you can't know from kohighlight what has happened and if some mess happened. So don't worry :)
I was just updating this issue with all the info I could think of on the topic of losing highlights, for reference, so I can link to it in the future.

**Comment by noembryo** [comment]
... and another thing ...
What is the difference between the `["partial_md5_checksum"]` and the `["stats"]["md5"]` keys?
It would be very helpful if I could use one of them to ID the books and merge only the same book's highlights.

**Comment by Frenzie** [comment]
It's used on the sync server, so in principle it shouldn't change.

See:
https://github.com/koreader/koreader-sync-server#privacy-and-security
https://github.com/koreader/koreader/issues/3530#issuecomment-348945447

https://github.com/koreader/koreader/blob/f2a9ed0b79b783d709c7b0c55abe165f12782bef/frontend/document/document.lua#L113-L159

The stats thing I don't know about. It looks suspiciously similar:
https://github.com/koreader/koreader/blob/b1215812cb99a1e9e8cbb2ce99da94eca12a3324/plugins/statistics.koplugin/main.lua#L268-L287

**Comment by houqp** [comment]
I would use `partial_md5_checksum` over `["stats"]["md5"]`.

**Comment by houqp** [comment]
And highlight config should point to the same text regardless how the book is rendered for all document types, if not, it's a bug we need to fix.

**Comment by noembryo** [comment]
Added the (experimental) option to merge highlights with [v0.6.1.0](https://github.com/noembryo/KoHighlights/releases)
As a bonus, it can also sync positions now..

**Comment by poire-z** [comment]
Btw, positions too (as they are xpointers) may change when `cre_dom_version` changes.
When a `last_xpointer` is not found, you're just brought to the 1st page, so no real harm done. So I dunno if that should be a worry to you.

**Comment by noembryo** [comment]
Well, to sync 2 books, they have to be on the same `cre_dom_version`.
And I think that the `last_xpointer` key was added to metadata earlier than `cre_dom_version` key (or wasn't?)

**Comment by poire-z** [comment]
> And I think that the last_xpointer key was added to metadata earlier 

Yes it was. But its value is updated from the engine, with the dom version in use. So no problem if you make all that dependant of needing the same `cre_dom_version`.

Just giving more details about this cre_dom_version:
When opening an old book that has not been opened for years, but that has a metadata.lua (technically, a `last_xpointer` set), KOReader requests cre_dom_version to be the older it knows: `20171225`. 
If no metadata.lua (technically no `last_xpointer` set), it requests the newest/lateset cre_dom_version (currently: `20180528`).

https://github.com/koreader/koreader/blob/779909343c80501fc223376f4b9e0d46f183c9fd/frontend/apps/reader/modules/readerrolling.lua#L121-L142

(The comment `(EPUB will use the same...` is wrong now - it may have been right on the first increment - I'll remove it).

**Comment by noembryo** [comment]
So, if all the older metadata are treated as `20171225`, do they also get a `last_xpointer` key?
Because if they don't, I have to check for its existence..

**Comment by poire-z** [comment]
Yes, they do. If they have been opened with a > 201805 koreader, they will get a `cre_dom_version ` **and** a `last_xpointer`.

`last_xpointer` should be there if the document has been opened since 2013-2014 (before I jumped in): https://github.com/koreader/koreader/commit/e7e6a2be9c3258c452a8329db3c2d56638e99480  and #980.

There is code to use a previous setting when `last_xpointer` is not present, and to convert it to a last_xpointer:
https://github.com/koreader/koreader/blob/779909343c80501fc223376f4b9e0d46f183c9fd/frontend/apps/reader/modules/readerrolling.lua#L144-L158

**Comment by noembryo** [comment]
OK then, we're all set!
Lets hope now that the merging actually works ;o)

**Comment by arooni** [comment]
Is there something I need to do to enable the syncing of highlights between devices?  Just installed the latest nightly (3/5/2019) and I don't see highlights syncing from my PW4 to my Kindle Fire Tablet... am I doing something wrong?

**Comment by Frenzie** [comment]
This is a third-party app. The built-in sync stuff hasn't changed in years. I think I had to restart it one or two years ago and that's about it. :-P

**Comment by arooni** [comment]
So sounds like I shouldn't hold my breath for highlighting sync to be baked into Koreader ;)

**Comment by Frenzie** [comment]
I don't think anybody's actively doing anything with it, no. :-)
