### ISSUE TITLE
[bug?] [android] Sliding finger along left hand side of screen doesn't adjust backlight

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4681]
* KOReader version: 2019.02 stable
* Device: Fire 10 tab

#### Issue

Sliding one finger on left hand margin doesn't adjust backlight as it does on Kindle.  Two finger adjustment seems to work fine however.

**Comment by Frenzie** [comment]
It's intentional behavior since it's more of a crutch for single-touch devices.
https://github.com/koreader/koreader/blob/4547b2d65f7e01e16e87f877fed4505fc2883505/plugins/kobolight.koplugin/main.lua#L3

Also see #2587, but that's about when the plugin was also responsible for the frontlight toggle in the bottom left. (Now part of the core and freely assignable in gesture manager.)

**Comment by pazos** [comment]
It is useful on kobos and cervantes with colour light where a slide in the right margin will adjust natural light.
