### ISSUE TITLE
Even more Gesture Manager action suggestions

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#4687]
Now that the Gesture Manager has been massively revamped, here are some more features I personally use often:
- [x] Wikipedia lookup
- [x] Dictionary lookup
- [x] Toggle Reflow

There are more, but the action list is already pretty long at this point. Probably shouldn't bloat it with niche features.

**Comment by Frenzie** [comment]
Ah, reflow! I forgot about that one since fit to content width usually does the trick for me.

Fulltext search is another one that goes along with Wikipedia/Dictionary.

**Comment by gerhaher** [comment]
Fulltext search
Go to page
Go to previous/next chapter
"Go to file manager"

**Comment by Frenzie** [comment]
Dictionary, Wikipedia, and fulltext search would require some refactoring so they use events for showing the window. Not difficult, but not quite a quickie.

**Comment by Frenzie** [comment]
- [ ] Follow nearest link

**Comment by poire-z** [comment]
Might need another to be complete (currently doable by long-press on `Go back to previous location`):
- [ ] Clear location stack

**Comment by Frenzie** [comment]
Would you mind doing it? :-) (I won't tonight, in any case.)

**Comment by poire-z** [comment]
ok, on it.

**Comment by poire-z** [comment]
I don't see why anybody would need this one (but I actually missed it today:):
- [ ] Exit (and why not Restart)

(@Frenzie : I feel like Exit might be tricky, I remember you spent some time on making it work correctly - so, is it? if you feel like adding it :)

Also, we have 3 forward-back-forward. The 4th one is missing: `east west east ` - might be worth adding as the available ones by default as it's some easy to do gesture.

**Comment by Frenzie** [comment]
@poire-z It shouldn't be difficult since now you can just call the self.ui.menu:exitorRestart() method. The problem was in getting it right. ;-) Just sending a Close event around like we used to could lead to unpredictable results.

https://github.com/koreader/koreader/blob/5e01a0c264b3c324ec2f3d34190637890ffaf548/frontend/apps/filemanager/filemanagermenu.lua#L375-L401

https://github.com/koreader/koreader/blob/5e01a0c264b3c324ec2f3d34190637890ffaf548/frontend/apps/reader/modules/readermenu.lua#L248-L280

> Also, we have 3 forward-back-forward. The 4th one is missing: east west east - might be worth adding as the available ones by default as it's some easy to do gesture.

Sure. In the same obvious missing easy gestures you've got all the other diagonal ones.

Also, do you have an idea for an action on northeast, southeast, northeast? I don't have a clear vision for it like with the other gestures, but I like how it looks. :-P

**Comment by poire-z** [comment]
> northeast, southeast, northeast? 

Not really. Triple full refresh , to really really really remove ghosting? :)

Would we need separators in the list of gestures? (doubles same axe, double orthogonal, triples, diagonal doubles...)

**Comment by Frenzie** [comment]
If you see a simple way to add it, sure. :-)

**Comment by NiLuJe** [comment]
refreshFull() -> clear() -> refreshFull() -> foorceRepaint() -> refreshFull()

(Or something to that effect :D).
