### ISSUE TITLE
about format:epub、mobi

### ISSUE THREAD

**Issue by GzxdH** [koreader/koreader#4745]
How do I support mobi format, just for presentation。
my ide：Android Studio。

**Comment by GzxdH** [comment]
please help me ~ thank you ~

**Comment by Frenzie** [comment]
You'd probably either want to find a library that renders Mobipocket (like crengine) or one that converts it to something with wider support like EPUB or PDF.

**Comment by pazos** [comment]
@GzxdH: you can try [thornyreader](https://github.com/irrationalunzen/thornyreader). It seems easier to integrate on an android studio project.

**Comment by Frenzie** [comment]
@pazos That looks very interesting and I hadn't heard of it, thanks for mentioning it! I Always good to see another project supporting DjVu.

@poire-z It contains another crengine fork that looks like might have some commits potentially of great interest to us. (RTL! Bidi! :-D Bunch of footnotes stuff. And lots more…)

https://github.com/irrationalunzen/thornyreader/commits/master/crengine/src

It's a pity that crengine has split up so much. Also pinging @virxkane. And pinging @Tarasus because we have our own set of interesting commits [here](https://github.com/koreader/crengine/commits/master).

**Comment by GzxdH** [comment]
Thank you. I'll try. @Frenzie @pazos

**Comment by poire-z** [comment]
> It contains another crengine fork that looks like might have some commits potentially of great interest to us. (RTL! Bidi! :-D Bunch of footnotes stuff. And lots more…)

Interesting. Put some notes after an evening reading it in https://github.com/koreader/crengine/issues/267.

**Comment by pazos** [comment]
Closing this issue since OP is doing well with FBReader ;)
