### ISSUE TITLE
Words overlap or have no space between them

### ISSUE THREAD

**Issue by jacquescousteau** [koreader/koreader#4756]
* KOReader version: v2019.02
* Device: KOA

#### Issue

About once per 2-4 pages two words will have the space between them lost, such that the second word starts exactly where the first word ends, or such that the last letter of the first word overlaps the first letter of the last word. 

Seems to affect all epubs that I’ve read. 

Settings: font hinting = native, font kerning = best, word gap = medium

Increasing the font size when an error is present on the page will cause the two words to be displayed properly, but then decreasing back to the previous font size will cause the issue to come back on the same two words, suggesting that there is some determinism in when the bug occurs. 

I can provide a sample ePub and location, but again it seems to be dependent on font size. Repro is difficult for this one.

**Comment by NiLuJe** [comment]
IIRC, something of the sort was discussed a while ago, and @poire-z might have fixed it since. Could you try the latest nightly to chekc if you can still reproduce it?

**Comment by poire-z** [comment]
If you have it with "best" only, and not with "good", it has probably been fixed since #4593. Noticed in https://github.com/koreader/koreader/issues/4577#issuecomment-462908911.
The cause was that there was a hyphenation on a previous line that happened on a ligature - which was then no more a ligature, and the char widths computation got messed up.

**Comment by jacquescousteau** [comment]
Confirmed, have it with “best” only. 

Thanks.
