### ISSUE TITLE
Irregular exit when 'Show more links as footnotes'

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4840]
* KOReader version: v2019.03.1-45-gb7b4cdd_2019-03-25/  

* Device: KA1

#### Issue
When I have 'Show more links as footnotes' enabled, some of the links concerned result in a crash when I tap on the screen to close the footnote pop up window.

#### Steps to reproduce
Book (split) in question: 
[The Wretched - Victor Hugo.zip](https://github.com/koreader/koreader/files/3007280/The.Wretched.-.Victor.Hugo.zip)

These links crash KOReader for me:
'palabres'
'de Maistre'
##### 
[crash.log](https://github.com/koreader/koreader/files/3007269/crash.log)

**Comment by poire-z** [comment]
OK, easy fix, I'll PR it later today.
Happened because the link coherency check finds that link not coherent, so no higlighlit of the link and no unhighlight callback made, and try to call that.

Notes to self:
- I thought we were done with the "not a coherent xpointer" - but it happened on this, possibly because it's some italic and we are since some weeks ago adjusting the start of the Rect, so it's possible in this check, we use one without the adjustment which is now outside of the rect, so no more coherency. A simple x+2 makes it valid again:
```diff
 function ReaderLink:isXpointerCoherent(a_xpointer)
     -- Get screen coordinates of xpointer
+    logger.warn("<", a_xpointer)
     local screen_y, screen_x = self.ui.document:getScreenPositionFromXPointer(a_xpointer)
     -- Get again link and a_xpointer from this position
-    local re_link_xpointer, re_a_xpointer = self.ui.document:getLinkFromPosition({x = screen_x, y = screen_y}) -- luacheck: no unused
+    local re_link_xpointer, re_a_xpointer = self.ui.document:getLinkFromPosition({x = screen_x+2, y = screen_y}) -- luacheck: no unused
+    logger.warn(">", re_a_xpointer)
     -- We should get the same a_xpointer. If not, crengine has messed up
     -- and we should not trust this xpointer to get back to this link.
     if re_a_xpointer ~= a_xpointer then
```

<kbd>![image](https://user-images.githubusercontent.com/24273478/54996775-7ebfd500-4fca-11e9-9cbe-a5d895d7be1e.png)</kbd>
- No unhighlight is done when exiting the footnote popup with the Esc key.
