### ISSUE TITLE
KA1: Two-finger swipes in landscape not working

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4843]
I noticed that the recently added two-finger swipes feature didn't work in landscape with my KA1. I was thinking of opening a New issue... and then I read this: 
> This can't be fixed by KOReader.

https://github.com/koreader/koreader/issues/2473#issuecomment-290391412

So is that comment 2 years ago, still the final word of this issue?

**Comment by Frenzie** [comment]
Unless Kobo updated the kernel/driver (which seems unlikely), it would be. And that's assuming it's a driver issue rather than an actual hardware issue, in which case there's no theoretical way to do anything about it either. There's https://github.com/lgeek/okreader but it doesn't support the KA1.

KOReader (as well as Nickel) are acting on the touch events supplied by the driver.

**Comment by Frenzie** [comment]
Closing since it's a hardware issue.
