### ISSUE TITLE
Sugestion - Finished to read a book must sorted to the end

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#4859]
if I've finished reading a book could be send to end of a file list so I'll no need to browse all the pages to find the remaining books.

**Comment by Frenzie** [comment]
Isn't that basically `sort by percent - unopened first`?

![Screenshot_2019-03-30_19-50-32](https://user-images.githubusercontent.com/202757/55280367-1738bb00-5325-11e9-9c14-01dfb380ab9a.png)

**Comment by hugleo** [comment]
Tried but I din't managed how to make it work. I finished reading a cbz file, koreader ask the options if I would like to go to the next file or go to file browser. I select go to file browser and the file order didn't change.

**Comment by Frenzie** [comment]
That seems to be a bug specific to whatever that DialogButton does.

**Comment by hugleo** [comment]
I've opened and read the second file of the list. Tried the top menu to change to file list again, tried to go back and forward in the file list browser. The order of the files didn't change.

**Comment by hugleo** [comment]
Very weird. I've found out that no only the sort by percent doesn't work as for file browser not showing any metadata.

So I installed koreader in my mobile that is also using mobile and for that is working normally. 
Both eink device and mobile are using the last nighty version. 

I don't think that I disabled some option or plugin by mistake isn't?

I take some pictures:

Mobile:

![Mobile](https://user-images.githubusercontent.com/4573505/55369023-2eb1a880-54cb-11e9-9c9c-f073dc61d7fa.jpg)

Likebook Mars Device:

![Device](https://user-images.githubusercontent.com/4573505/55369065-5b65c000-54cb-11e9-97de-baec3d61193f.png)

Option configured in both:

![Option](https://user-images.githubusercontent.com/4573505/55369099-7afce880-54cb-11e9-8c19-f08337e5029d.png)

**Comment by hugleo** [comment]
Not about the DialogButton bug but about my last info message is
Duplicate of #4872 since .sdr can't be created because of sd card permission handled.

**Comment by pazos** [comment]
no metadata and no timestamps because we're in a Read Only fs. Please use internal sdcard instead!

**Comment by poire-z** [comment]
Well, I think that since #4138, KOReader should work with books in read-only fs. At least, the settings are saved in `koreader/history/` , and they are read correctly when opening the book, and they are shown in History.

But there are a few other things (like FileChooser and the CoverBrowser views) that just use `DocSettings:hasSidecarFile()` to know if there is a "regular" sidecar file - and it has not been fixed/upgraded to also go look for these "old/legacy" saved settings in `koreader/history/` - that may be are no more "legacy"... Or may be we should add and use another method that go look for all the candidates, like open() does.
