### ISSUE TITLE
Battery Issue

### ISSUE THREAD

**Issue by FrantzUml** [koreader/koreader#4994]
* KOReader version: 2019.04
* Device: Kobo Forma

#### Issue
Installing last vesrion of KFMon and Koreader (april 2019) makes battery issue : my Kobo Forma reader is quickly discharged (20% when cropping a simple pdf file !!).

#### Steps to reproduce
- Open KoReader on Kobo Forma
- Open a pdf file (about 2Mb size)
- Makes a crop to reduce margins
- Close KoReader and go to Nickel
- Look at battery charge

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by NiLuJe** [comment]
The battery gauge is notoriously unreliable.

It may drop by large chunks for no apparent reason, and then stop decaying at a normal rate for a while to compensate.

Until you can actually confirm that something's really going awry (and that would probably take actual monitoring over a shell), I'm chalking that off to the usual battery gauge shenanigans.

**Comment by Frenzie** [comment]
That just means the battery level indicator is a bit wonky. Taxing your CPU for a few seconds isn't going to drain your battery by 20 %.

**Comment by AlanSP1** [comment]
Are you sure you get that 20% drop reliably, every time you do same steps?

It is quite normal that battery reading is NOT linear, that it can stuck at some percentage, then suddenly drop for large percentage, for no apparent reason. I get this on all my devices, but on different percentages and for different percentages.

**Comment by Frenzie** [comment]
For example, my H2O goes something like this:

* 100 (lasts for a few hours)
* 99 (_n_ - 9) → 90
* 90 (_n_ - 1 or 2) → 45 (but I'm pretty sure going from 60 down to 50 takes about as much time as going from 90 to 70 and from 50 to 40 combined, even if it's all still in steps of 1)
* 45 (_n_ - ~3) → 30
* 30 (_n_ - ~5) → 20
* 20 → dead (let's just say this surprised me a few times when it was new, because given how it took weeks to get down to 20, you don't exactly expect 20 to mean it can die any second)

That first step used to be 100 → 80, which may be indicative of battery wear & tear after nearly 5 years.

So basically the 40 percentage points between 85-45 are comparable to going from 95-15 on my phone.

Given how batteries work internally it wouldn't surprise me if that is quite literally true, just with the Kobo device failing to cleverly hide it from the user. The battery needs to shut off the device at, say, 20 % charge because otherwise you'd destroy it. Or perhaps that'll happen more or less automatically because while it may not be discharged, ti simply can't provide enough current. Either way, when your phone tells you it's at 0 % it still holds some charge so it won't get damaged — or in case of worse technical decisions, won't get damaged as much.

It's the same in Nickel, which is easy to test by doing something fairly computationally intense like web browsing. But on a site like Wikipedia or something, not a stupid heavy site like Twitter or Facebook. ;-)

**Comment by protist** [comment]
@Frenzie Could you please explain your itemised list? What do the _n_s mean? Is each item meant to be an equivalent interval?

I also have the H2O. I've also noticed inconsistencies in battery reporting, and I'm curious as to your experience.

**Comment by Frenzie** [comment]
> Is each item meant to be an equivalent interval?

Not at all. It refers only to the numbers displayed. Time-wise you can probably look at it as a kind of bell curve.

![Screenshot_20190505_094446](https://user-images.githubusercontent.com/202757/57190451-8b651080-6f1a-11e9-8abc-0c4f91de91ad.png)

NB The top may just as well lie at 65 or 55, or perhaps it doesn't actually look all that much like a (skewed) bell curve at all. The point is merely that you get _n_ - 1 from ~85 to 45 and that single points last longest somewhere between ~70 to 50.

Outside of that roughly 85 - 45 range you see a much more erratic progression of displayed numbers, but that might just mean the interval is really short and you would see the numbers come in an _n_ - 1 progression if you stored them every few seconds.

Physically speaking, the voltage will probably look something like this. (Based on no measurement data, of course. My H2O is fully intact.)

![path3715](https://user-images.githubusercontent.com/202757/57190701-cb79c280-6f1d-11e9-8064-121d89570f87.png)

**Comment by protist** [comment]
Ahhhhh. Thanks! I thought the arrows were referring to transitions, i.e. `45 (n - ~3) → 30` was talking about the transition from (a reported battery of) 45% to (a reported battery of) 30%. If I understand correctly, you are saying that a reported battery of 45% is equivalent to a "real-world" remaining time of 30%. I think we see similar things on our readers. (I still don't entirely understand what _n_ represents though?)

**Comment by Frenzie** [comment]
No, I'm saying that between ~45 and 30 the reported value (_n_) decreases by some number around 3.

n = 45
n - 3 = 45 - 3 = 42

And so forth.

**Comment by AlanSP1** [comment]
I think the most important thing to understand is, that reported battery percentage isn't actual battery remaining.

I have two devices (H20 and KA1) and both have differences in how they report battery. Why and how? I don't know, but for example my H20 "lasts" much longer in higher percentages (i.e. it takes longer time do show less battery percentage), but as it gets lower and lower, battery "drops" faster and faster. Below 20% is almost depleted battery, when I get to 40% on my H2O, I know I have maybe a day or two of reading time, so I usually charge it then.

On KA1, it's just the opposite. Higher percentages drop faster, and on lower reader last longer and I know that even when I'm below 10% I have enough reading time. I even, when I'm home (don't want to risk it on say beach, where I don't have charger handy) I sometimes keep reading with 0% (yes, zero, i.e. it should be completely depleted battery, but it isn't) for hours (yes, hours, once I read 5 hours with 0% showing. And then I just put it to charging, maybe having couple, maybe even more hours of reading time).

So, battery percentage is just an idea, vague suggestion and for each device (or maybe device type, not sure) you need to know what shown percentage actually means in real battery percentage.

**Comment by Frenzie** [comment]
I'll close this now.
