### ISSUE TITLE
Feature request: pop-up footnote, endnotes etc..

### ISSUE THREAD

**Issue by hiworld3** [koreader/koreader#5015]
* KOReader version: 2019.04
* Device: Android

Hi, could we possible to make the footnote, endnotes etc.. into a small pop-up window? just like the function in Kindle system, Kindle doesn't have this but added it like 4 or 5 years ago, really convenient, no need to jump back and forth in case of reading notes.

**Comment by Frenzie** [comment]
Try Settings → Taps & gestures → Links → Show footnotes in popup.

Alternatively there's also Style tweaks → Miscellaneous → In-page footnotes.

**Comment by hiworld3** [comment]
my lord, thank you

**Comment by hiworld3** [comment]
my lord, thank you

**Comment by Frenzie** [comment]
@poire-z Should we enable one of those by default?

**Comment by poire-z** [comment]
Not sure we should.
_In-page footnotes_ is too dependant on CSS to be made a default.
_Show footnotes in popup_ could, but is also dependant on HTML/CSS quality to be accurate (it may not work on some books, or show other footnotes text, or even whole chapters as footnotes - or need the _Show more links as footnotes_)
The current default of following the link is the only one that works 100% with a coherent behaviour.
(I also like to reward curious people that go browse the menu :)

(Personally, I don't use _Show footnotes in popup_, and prefer following links with the little markers - but I use _In-page footnotes_ when they work, in books where such footnotes aren't too big.)

**Comment by Frenzie** [comment]
> In-page footnotes is too dependant on CSS to be made a default.

I'm not really sure what the argument is there? It just means it wouldn't work in a document unless one of the supported standards is used. :-) E.g., `epub:type="footnote"` that maps to the ARIA role of `doc-footnote`. A footnote that isn't declared a footnote is just a link. That's true regardless whether you use CSS or something hard-coded in C++.

https://github.com/koreader/koreader/blob/b1215812cb99a1e9e8cbb2ce99da94eca12a3324/frontend/ui/data/css_tweaks.lua#L413-L424

I think in-page EPUB footnotes should be enabled by default.
In-page Wikipedia footnotes probably should be too because it's just so specific.
In-page classic classname footnotes are something I enable by default but that may be a bit risky to enable by default.

**Comment by poire-z** [comment]
> I'm not really sure what the argument is there? It just means it wouldn't work in a document unless one of the supported standards is used. :-) 

Except that when they work, when taping/swiping a footnote link, you jump or show them in a popup, over the in-page footnotes, which feels strange. Yes, it's the same when they don't work, but it feels like a bug when they work. There's many possible combinations that I'd rather leave to the user, and have a default that is consistent and natural.

The in-page footnotes are pretty, and available; you like them and so do I (but a bit less lately), but we don't _have to_ show off by enabling all the bells and whistles :) We're not making money nor fighting any competition. Showing what's possible with screenshots on the Wiki should be enough for people to know it's there. Or a changelog for long time users to tell them what's new if they haven't noticed that feature - but don't shuffle the habbits of those that are fine with the current stuff.)

Also, which to enable? The normal or the small?
I guess you like the normal (that you copied), but I hate it: it's too big, too much room taken, not distinguishable enough from the main text...
I prefer by far the small. But going smaller than the default font size might be too small/unreadable for some people...

> That's true regardless whether you use CSS or something hard-coded in C++.

We'd probably put the defaults in `cr3gui/data/epub.css`. But in that snippet, we use:
```css
    margin-top: 0 !important; 
    margin-bottom: 0 !important; 
```
to remove the inter footnote margins. These publisher margins make sense on a full page at the end of the book, but they add too much interspace when used as in-page footnotes. Remember these in-page foornotes are just slices of the (still kept and browsable) pages with footnotes at the end of the book or chapter, that are additionally reported to be shown on the main book pages.
Problem with that:
- you lose the original formatting - and I think the default should stay to keep the original formatting
- if done in cr3gui/data/epub.css, because of these `!important`, you just can't revert/disable it : the original embedded CSS margin-top/bottom for these block elements are lost and overwritten.

So, we would really need to enable it as a default via Style tweaks (so it can be disabled there -  and then just not inject anything with `!important`). There's (not yet) anything in redaerstyletweak.lua for enabling some tweaks by default, but I guess if you really want that, it should be done around there (possibly just by populating settings.reader.lua with `["style_tweaks"] = { ["footnote-inpage_wikipedia_smaller"] = true, and others },` with an additional setting to state the fact that we already installed the default tweaks - so the user can make that `style_tweaks` empty again. Or just having it empty `["style_tweaks"] = {}` , and not nil/inexistant, could be a flag of that fact.

> In-page Wikipedia footnotes probably should be too because it's just so specific.

I have it enabled because it's pretty. I often end up disabling it because the wikipedia footnotes are too often just references or a bunch of `John Blah, p53' that waste useful reading space.

**Comment by poire-z** [comment]
Btw, should we also add `margin-left: 0 !important; margin-right: 0 !important; ` to these in-page footnotes tweaks?
To avoid that kind of indentation of the footnotes, that I find a bit ugly (I guess up to this book, none of the books I read had footnotes with any margin-left :):

<kbd>![image](https://user-images.githubusercontent.com/24273478/57691348-417bd900-7644-11e9-8a3f-8b0667122402.png)</kbd>

**Comment by Frenzie** [comment]
You mean fr the outer footnote element? Sure, I don't see why not. But for inside the footnote I can imagine something like:

```
<p>blabla</p>
<blockquote>I'd like to be indented</blockquote>
<p>and not me</p>
```

**Comment by poire-z** [comment]
Yes, only for the outer block element that is considered the footnote container, of which we already cancel the top and bottom margins. Inner block elements would be kept untouched, as they are currently, and displayed with their margins.
OK, I'll test that for a bit and add them in some days.

**Comment by poire-z** [comment]
Mentionning another issue (so I can refer to that when I push a fix) with that same book and footnote, with **footnote popup** this time:

<kbd>![image](https://user-images.githubusercontent.com/24273478/57698240-76445c00-7655-11e9-9cfb-34737d355898.png)</kbd>

There is some unwanted extra margin top.

The HTML given to MuPDF in that case is:
```html
<aside class="ntb" epub:type="footnote" id="ntb-002">
<p class="txt_justif"><a href="../Text/p1chap3.xhtml#ap_ntb-002-1" class="calibre4">1</a>.&#160;Pièce spéciale, située au même étage, qui permet de faire sécher les objets ou vêtements liés à des affaires criminelles.</p>
</aside>
```

Remove the `id="ntb-002"` and it's all fine:

<kbd>![image](https://user-images.githubusercontent.com/24273478/57698431-ef43b380-7655-11e9-9043-2ca39e29c122.png)</kbd>

Proposed fix for that:
```diff
--- a/frontend/ui/widget/footnotewidget.lua
+++ b/frontend/ui/widget/footnotewidget.lua
@@ -172,10 +172,15 @@ function FootnoteWidget:init()
     -- There is something with its handling of <BR>:
     --   <div>abc<br/>def</div> : 2 lines, no space in between
     --   <div>abc<br anyattr="anyvalue"/>def</div> : 3 lines, empty line in between
     -- Remove any attribute, let a <br/> be a plain <br/>
     self.html = self.html:gsub([[<br[^>]*>]], [[<br/>]])
+    -- Elements with a id= attribute get a line above them (by some internal MuPDF
+    -- code, possibly generate_anchor() in html-layout.c).
+    -- Working around it with the following does not work: *[id] {margin-top: -1em;}
+    -- So, just rename the id= attribute, as we don't follow links in this popup.
+    self.html = self.html:gsub([[(<[^>]* )[iI][dD]=]], [[%1disabledID=]])

```

**Comment by Frenzie** [comment]
Really? How odd. :-)

**Comment by Frenzie** [comment]
> we don't have to show off by enabling all the bells and whistles :) 

I don't think of in-page footnotes as bells & whistles, unless you mean style tweaks themselves. Anything a paper book does effortlessly isn't bells & whistles, regardless how difficult it was to code. ;-)

As to the size, smaller is more traditional but whichever.

**Comment by poire-z** [comment]
So, please give some thoughts on the technical points/options I mentionned below that :)

**Comment by Frenzie** [comment]
I agree that the default styles shouldn't interfere with the document styles too much.

For the default enabled I'd go with your `["style_tweaks"] = { ["footnote-inpage_wikipedia_smaller"] = true, and others },` and then just overwrite it with the user settings the next line? Just a quick little for loop; it's not like it's likely to ever have more than 100 entries in that table and probably far fewer.

**Comment by poire-z** [comment]
> and then just overwrite it with the user settings the next line?

Then, there would be no way to disable them (or I would have to handle `global_tweak["some_name"] = false`, which is not fun).

But, we could have a set of default global tweaks to fill the global setting for new users - AND, given that I had the random good idea to remove the setting when its list is empty, it would also affect existing users that have not set any tweaks as globals (but it's a one time chance :).
This would work:
```diff
--- a/frontend/apps/reader/modules/readerstyletweak.lua
+++ b/frontend/apps/reader/modules/readerstyletweak.lua
@@ -311,2 +311,7 @@ end

+-- Default globally enabled style tweaks, for new users
+local DEFAULT_GLOBAL_STYLE_TWEAKS = {}
+DEFAULT_GLOBAL_STYLE_TWEAKS["footnote-inpage_fb2"] = true
+DEFAULT_GLOBAL_STYLE_TWEAKS["footnote-inpage_epub_smaller"] = true
+
 function ReaderStyleTweak:onReadSettings(config)
@@ -314,3 +319,3 @@ function ReaderStyleTweak:onReadSettings(config)
     self.doc_tweaks = config:readSetting("style_tweaks") or {}
-    self.global_tweaks = G_reader_settings:readSetting("style_tweaks") or {}
+    self.global_tweaks = G_reader_settings:readSetting("style_tweaks") or DEFAULT_GLOBAL_STYLE_TWEAKS
     self:updateCssText()
@@ -325,3 +330,3 @@ function ReaderStyleTweak:onSaveSettings()
     self.ui.doc_settings:saveSetting("style_tweaks", util.tableSize(self.doc_tweaks) > 0 and self.doc_tweaks or nil)
-    G_reader_settings:saveSetting("style_tweaks", util.tableSize(self.global_tweaks) > 0 and self.global_tweaks or nil)
+    G_reader_settings:saveSetting("style_tweaks", self.global_tweaks)
 end
```
Then, one can remove them, and the setting will be stored as `style_tweaks = {}` - and this won't trigger anymore (so: one time chance to select the right default global tweaks).

As for the default global tweaks, I had another look, and, for me, only these 2 are safe (the Wikipedia ones having `ol.references > li {}` might be triggered on random non-wikipedia books.

But this would be enough to show that `(2)` in the menu:
<kbd>![image](https://user-images.githubusercontent.com/24273478/75568621-e93b8980-5a53-11ea-8c21-5a430f24b244.png)</kbd>
and advertize a bit more that feature: people would follow that number, and see the other ones, and enable them at their own risk:
<kbd>![image](https://user-images.githubusercontent.com/24273478/75568590-da54d700-5a53-11ea-9f2d-2f293f77ab2b.png)</kbd>

**Comment by Frenzie** [comment]
Sounds good to me. :+1:
