### ISSUE TITLE
e-book disappeared

### ISSUE THREAD

**Issue by ekremg** [koreader/koreader#5018]
* KOReader version: v2019.04
* Device: zerofltebmc

#### Issue
I was reading an e-book in the EPUB format. Whenever I quit the app, it was fine as I could resume where I left. But this morning, my e-book disappeared. It was deleted from my device.
#### Steps to reproduce
Open an e-book and read it, except in this case, my e-book is gone.

**Comment by Frenzie** [comment]
That can't be an issue with KOReader, but it could potentially be helpful to add a few more details. How did you open this book?

**Comment by ekremg** [comment]
I opened it through Koreader. I browsed to where my e-books are. Until
yesterday, I had 4. I went to bed. This morning I opened it, I see only 2.

**Comment by pazos** [comment]
> I opened it through Koreader. I browsed to where my e-books are. Until
yesterday, I had 4. I went to bed. This morning I opened it, I see only 2.

Never had this issue and it seems almost imposible to me unless you deleted the file outside KOReader (in that case the .sdr folder should stay in the folder and the file present on your reading history).

**Comment by ekremg** [comment]
I never deleted it. The EPUB file went missing but the .sbr folder was there

**Comment by pazos** [comment]
@ekremg: keep in mind that android is a big mess in terms of shared storage access, so in order to confirm this bug you can try to reproduce it by storing all your books in a dedicated folder under `/sdcard`, for example in `/sdcard/ebooks`.

If you can reproduce it we will need logs `adb logcat KOReader:V *:S`

@Frenzie: probably now that we log everything tagged with "KOReader" we can have a function to dump logcat to a file. It seems handy for these kind of issues.

**Comment by Frenzie** [comment]
@pazos Sure, sounds good to me.

**Comment by pazos** [comment]
Closing as invalid. @ekremg: feel free to re-open if you can reproduce the issue.
