### ISSUE TITLE
Question for Kobo ver: Does updating of Kobo firmware affect the Koreader performace

### ISSUE THREAD

**Issue by hiworld3** [koreader/koreader#5038]
For example, a Kobo running a 2018 FW with latest koreader

and same Kobo running a 2019 FW with latest koreader

does the FW of Kobo affect the koreader performace? thanks, or koreader is kinda of more "standalone"?

another question, as for Kindle version, as far as I know, koreader does not affect by different kindle firmware versions (as long as after jailbreaked), is this true? thanks

**Comment by Frenzie** [comment]
> does the FW of Kobo affect the koreader performace? thanks, or koreader is kinda of more "standalone"?

There's the basic system (let's say Linux + busybox) and there's the built-in reader app (Nickel). Any so-called firmware updates almost exclusively target the latter, therefore it should make no difference whatsoever.

> another question, as for Kindle version, as far as I know, koreader does not affect by different kindle firmware versions (as long as after jailbreaked), is this true? thanks

I'm not sure I understand the question.

**Comment by NiLuJe** [comment]
There have been a *few* kernel updates over the years, which *do* matter, perhaps not in terms of performance, but in terms of bug fixes.

I'd still heartily recommend running a current FW version on Kobo, for the simple reason that there's no drawback attached to it, except the time spent installing it ;).

----

On Kindle, the situation is generally the same, except, there, updates to the underlying system are *vastly* more frequent, and often bring noticeable changes.

Tl give you a specific example, a Kindle PW2 running an older FW <= 5.5 will behave noticeable worse when in nightmode than one running newer FW.

But, there, there are some obvious drawbacks to some specific FW milestones, because of the specificies of jailbreaking.

**Comment by hiworld3** [comment]
thank you, both answers are so helpful. Alth now we can't install the koreader on kindle now, can't jailbreak the later fw which is the first step..

**Comment by Frenzie** [comment]
@NiLuJe 
> There have been a few kernel updates over the years, which do matter, perhaps not in terms of performance, but in terms of bug fixes.

Anything particular come to mind? I thought the Linux kernel & drivers stayed pretty much static on a per-model basis.

**Comment by NiLuJe** [comment]
I'm pretty sure the Aura being crashy with HW inversion has been fixed at one point or another.

The Mk. 7 kernels have so far been updated slightly more regularly, especially the Forma, to fix a number of potential crashes.
