### ISSUE TITLE
Plain text files don't show blank lines

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#5042]
* KOReader version: 2019.05
* Device: Kobo Aura One

#### Issue
KOReader removes blank lines when rendering plain text files.

#### Steps to reproduce
Create a plain text file called Test.txt with the following content:
```
Line 1

Line 2
Line 3


Line 4
```
Open it in KOReader:
![Reader_2019-May-26_172824](https://user-images.githubusercontent.com/1391883/58384734-23678e80-7fdd-11e9-8b24-87b9a8988a3c.png)
The blank lines aren't visible: there's no difference between zero, one and two newlines.

**Comment by poire-z** [comment]
I never really looked at the txt format handling in crengine, but it seems there's quite a bunch of code to detect various text files formats from the past century, with some embedded rules or formatting options.
That I really don't want to look at any more after a few minutes looking at it :)

Anyway, we seem to request support for "preformatted" text, which is managed by [this](https://github.com/koreader/crengine/blob/5710c9666170d791590b303cb6c393c4245cc8e0/crengine/src/lvxml.cpp#L2319-L2343)

As for everything, crengine converts stuff to HTML, and our text files ends up being like this:

<kbd>![image](https://user-images.githubusercontent.com/24273478/58385151-346bcc00-7fec-11e9-9c58-0abd0bf5cd28.png)</kbd>
(You can select some text and view the internal HTML.)

[With a style tweak](https://github.com/koreader/koreader/pull/3944#issuecomment-389069259) containing: `empty-line { padding-top: 1em; }`, you can make it behave as you want:

<kbd>![image](https://user-images.githubusercontent.com/24273478/58385177-962c3600-7fec-11e9-98a6-7ef299d1a410.png)</kbd>

You can even tweak the style of the PRE, if [the margins we use](https://github.com/koreader/crengine/blob/5710c9666170d791590b303cb6c393c4245cc8e0/cr3gui/data/epub.css#L116-L123) are too much, or if you prefer another font.

Now, dunno if we should add this style to our epub.css (which is now used for every format).
Or provide a few style tweaks specific to the text format, if we can think of some more.
(The obsoleted txt.css has `empty-line { height: 1em }` which does not seem to work.)

**Comment by Frenzie** [comment]
Hold on, I specifically added these lines because of the, ahem, "smart" handling of plain text. Did they break since?

https://github.com/koreader/koreader/blob/7c53fcd922add92538507b73bbce55af91dd4fef/frontend/apps/reader/modules/readertypeset.lua#L87-L90

**Comment by Frenzie** [comment]
Duplicate (of sorts) of #1607, cf. #2422 & #2702.

**Comment by poire-z** [comment]
> Did they break since?

Dunno how these EMPTY-LINEs looked 1 or 2 years ago. But they don't show better with `txt_preformatted = 0`.
Your change to have `txt_preformatted = 1` makes the simple code (generating PRE + EMPTY-LINE) be used, which I guess is the best. There is just no style applied to EMPTY-LINE tags (because there is none in epub.css - and may be because I at some point fixed the handling/ignoring of empty elements, or broke some support for `height:` , or something.)

**Comment by Frenzie** [comment]
My screenshot in #2702 clearly shows empty lines, but trying the same file today shows they have since disappeared.

![Screenshot_20190526_202458](https://user-images.githubusercontent.com/202757/58385669-6123e180-7ff4-11e9-835f-65e7e0d72286.png)

Were these files previously rendered with txt.css and now only with epub.css?

**Comment by poire-z** [comment]
> Were these files previously rendered with txt.css and now only with epub.css?

Yes, but txt.css is still available in the Obsolete> submenu.
And the newlines still do not show if you switch to use txt.css.

Probably since the moment I switched default/unknown elements to be `display:inline` instead of the previous default `display:block`.
Add: `empty-line { height: 1em; display: block }` to txt.css (or epub.css), and they should display as before.

It probably should be reintroduced, and I'd prefer if we go with padding-top instead of height (as I may sometime add support for a few rendering flags where support for height could be a toggable - but maybe that toggable height support could be an easy way to kill newlines when one doesn't want to see them.)

**Comment by Frenzie** [comment]
I'm not sure if I understand the argument against using height, but since the end result is the same I'm also very neutral on padding vs height. :-P

**Comment by poire-z** [comment]
> Yes, but txt.css is still available in the Obsolete> submenu.
And the newlines still do not show if you switch to use txt.css.

I think I was not on master branch when testing this: the empty lines are shown with txt.css.
Also, no need for `display:block`, as the empty-line element is hardcoded to be `display: block`.

So, I'll just add `height:1em` for it in epub.css (we already have height: used for HR, so, let's stay coherent and use height for EMPTY-LINE too).
