### ISSUE TITLE
koreader-deps-latest.tar.gz is corrupt

### ISSUE THREAD

**Issue by ZapperDJ** [koreader/koreader#5082]
* KOReader version:
* Device: Cervantes 2013

#### Issue
The iproute deb present on koreader-deps-latest.tar.gz is corrupt and it fails to install on the Cervantes 2013

**Comment by pazos** [comment]
@ZapperDJ: thanks for reporting. Removed duplicated packages (because the only change between version is the safemode tool)

Please review the changes in https://www.mobileread.com/forums/showpost.php?p=3760905&postcount=2. Feel free to suggest other, easier to understand, description because I'm not good with english :slightly_smiling_face:
