### ISSUE TITLE
using Joplin (opensource equivalent to Evernote) Feature request

### ISSUE THREAD

**Issue by lbesnard** [koreader/koreader#5086]
Hi, brand new user of koreader on my kobo glo. Thanks for this amazing opensource project.

I feel like [joplin](https://github.com/laurent22/joplin) could be used to upload notes as well. In the backend, Joplin can also use Nextcloud(another opensource cloud storage).

**Comment by kereviz** [comment]
Hi, i tinkered with Joplin a little, and I think to implement Evernote like functionality with Joplin we need to directly edit Joplins cloud stored user database, since Joplin doesn't have any Web API. To do that we need to:
1- authenticate with users cloud service (Dropbox, OneDrive, WebDAV, NextCloud)
2- download all database
3- add our notes (and hope we dont mess users other notes)
4- upload our database to cloud
5- also be careful not to delete notes from other Joplin apps trying to sync.

I think it's not much different from rewriting a note taking app from ground.

However, Joplin has an [API](https://joplinapp.org/api/) that can be used from local internet, it wont be same but better than nothing. I wrote a [small wrapper](https://gist.github.com/kereviz/f071924feb87fa09eed0dad25651576f) in lua for needed functions. 

Logic of uploading notes can be similar to Evernote: 

find guid of Koreader Notes folder
if folder does not exist create it 
check if title of the book exist
if not create it 
upload clipping

For UI, we can put a submenu which includes:
1- Address Settings
2- Auth Token Entry (maybe additional option to read from file)
3- Export to Joplin switch (like exporttoTXT or exporttohtml)

![Screenshot from 2019-09-10 12-44-02small](https://user-images.githubusercontent.com/24368325/64606488-09f12380-d3cf-11e9-8975-88816bbf7880.png)
![Screenshot from 2019-09-10 12-44-29smll](https://user-images.githubusercontent.com/24368325/64606510-15444f00-d3cf-11e9-8e93-df4e3ea49e90.png)
![Screenshot from 2019-09-10 12-44-45s](https://user-images.githubusercontent.com/24368325/64606515-17a6a900-d3cf-11e9-90dd-c659306e4cfb.png)


So whats your thoughts?

**Comment by Frenzie** [comment]
@kereviz Seems fine to me.

**Comment by lbesnard** [comment]
that sounds like a great way to do it!

**Comment by kereviz** [comment]
Sorry for late response. Before writing code it didn't occurred to me to check if it works on phone or e-reader. It turns out Joplin only listen on localhost, not 0.0.0.0 like most apps do. So it only works on same machine. I [wrote to Joplin's forum about this,](https://discourse.joplinapp.org/t/clipper-api-listens-only-localhost-requesting-to-include-local-addresses/3560) they said it's not secure but if there is pull request about changing IP in terminal version they could accept it. Still it only works on either you
-use terminal version of Joplin
-create a tunnel from external IP to localhost (eg. $socat tcp-listen:41185,reuseaddr,fork tcp:localhost:41184 on linux)

Either way it requires some manual steps . I [finished](https://github.com/kereviz/koreader/tree/joplin-support) basic things with it; there is some rough edges but it works. So I will create a how-to, share it or link of it on wiki.

**Comment by kereviz** [comment]
About annotations, it's little complicated. 

Basic overview of bookmark, highlight, clippings architecture is like this:

-readerhighlight.lua saves highlighted note to two tables in books sidecar file : highlight and bookmarks. highlight.text, bookmarks.note and bookmarks.text contains highlighted part.
 -when you edit/annotate/rename a bookmark  you change bookmark.text item in sidecar file. readerbookmark.lua doesn't send any info about new name of bookmark into readerhighlight.lua. highlight.text and bookmarks.note stays same. (a sidenote, it's actually renaming a bookmark, you change how your note shows up in bookmarks menu, actual note is still stored in seperate index of bookmark table)
-Evernote exporter's clip.lua parses highlight table , saves it to clipboard/evernote/evernote.sdr. This file is contains clippings of whole library. 
-So basically we save a note 4 times.
-Since bookmark and highlight tables have different structure we can't simply pass bookmark table to parser. It needs rewriting of clip.lua:parseHighlight. But I don't know if it's wise to change source of parsing from highlight to bookmarks ( images, page info etc.) .  

 ```
["bookmarks"] = {
 [4] = { --4 is sorting number in whole book
            ["page"] = "/body/DocFragment[4]/body/p[6]/text().0",
            ["highlighted"] = true,
            ["notes"] = "highlighted text",
            ["datetime"] = "2019-09-24 21:30:16",
            ["pos0"] = "/body/DocFragment[4]/body/p[6]/text().0",
            ["pos1"] = "/body/DocFragment[4]/body/p[7]/text().25",
            ["text"] = "Page 5 highlighted text and my annotations @ 2019-09-24 21:30:16"
        },
}

 ["highlight"] = {
[5] = {  --5 is page number
            [1] = {  --1 is notes number in page 
                ["datetime"] = "2019-09-24 21:30:16",
                ["drawer"] = "lighten",
                ["pos0"] = "/body/DocFragment[4]/body/p[6]/text().0",
                ["pos1"] = "/body/DocFragment[4]/body/p[7]/text().25",
                ["text"] = "highlighted text "
            }
        },
}

```

Also is /mnt/us/documents/My Clippings.txt Kindle's default clippings file?

**Comment by Frenzie** [comment]
> Also is /mnt/us/documents/My Clippings.txt Kindle's default clippings file?

I don't know about the file, but the rest of the path sure is. ;-)

**Comment by NiLuJe** [comment]
It's Kindle, I don't know if we ought to touch it on our end.

**Comment by NiLuJe** [comment]
(read: we shouldn't. Assume it's RO.)

**Comment by poire-z** [comment]
I don't know anything about evernote.
But about the `highlight` and `bookmarks` entries, I wrote a few posts about how they are used. Mentionning some of them just in case it makes things clearer to you:
https://github.com/koreader/koreader/issues/1095#issuecomment-458918504 https://github.com/koreader/koreader/issues/4670#issuecomment-467965581 https://github.com/koreader/koreader/issues/3415#issuecomment-338996571

One thing is that we can't really fix or change what is stored in what, because we must stay compatible with past bookmarks and highlights, and tools like KOHighlight that parse these files.
But I guess from elsewhere, if you're just reading them, I think we update both when adding/removing - it's just that bookmarked pages (no text selexted) only get into `bookmarks`.
