### ISSUE TITLE
Blank screen when reader wakes up (Pocketbook 740)

### ISSUE THREAD

**Issue by evgenybf** [koreader/koreader#5140]
* KOReader version:
koreader-pocketbook-arm-obreey-linux-gnueabi-v2019.07.zip

* Device:
    Pocketbook 740 (InkPad 3)
    Firmware: sw_20190709_U740_5.20.1010_user.zip

#### Issue
Screen stays blank when the device gets awaken from the sleep mode.

#### Steps to reproduce
- Open a book;
- Set screen saver option to "Leave screen as it is";
- Press the power button to put the device to sleep;
- Press the power button to wake it up.;
Result: The screen is blank. 

- Touch the screen or refresh it with a swipe. 
Result: Text of the book is visible now.

**Comment by NiLuJe** [comment]
From what I gather, the PB system does.... things when going to sleep.

This ought to be at least as fun to workaround as on Kindle... Yay?

**Comment by LucyOne** [comment]
It wouldn't be a problem, if the last step (touching the screen to show the text) wouldn't also go a page forward or backward.
Is there a way to disable the screensaver altogether on Pocketbooks?

**Comment by aceofknaves** [comment]
Seems like a race condition with the native PB screensaver. Or perhaps KR assumes that the screen is blank while native screensaver applies something in the meantime. I tried various combinations of screensavers and timeouts and the result vary.
If the screensaver is set to "Leave screen as it is" delay doesn't really matter. What happens is that it shows the screen for a split second then blanks the screen after which PB sets the screensaver image to it's default zzZZ thing. On resume, the screen is blank until manual action, which doesn't affect page position but is annoying since I'm never sure if the wake actually did anything until I remember to turn the page.
Other screensavers produce weird artifacts on screen. The way it works is that one (or both) of the screensavers blanks the screen, then both try to apply the background image in random order. The order varies, even if I set the delay. With no delay I counted three to four consecutive full page refreshes. With 1 sec. delay, usually only three. If the KR screensaver is set to something that affects the entire screen (like a stretch image) then it usually applies with no issues but it seems like the "book progress" option doesn't refresh the screen completely so the end result is usually a funny combination of both images, which IMHO is the worst option.

**Comment by Frenzie** [comment]
@LucyOne 
> Is there a way to disable the screensaver altogether on Pocketbooks?

Settings (gear symbol) → Screen → Screensaver

**Comment by NiLuJe** [comment]
For refrence, on Kobo, where there's a similar potential interaction, we basically SIGSTOP the WM (i.e., the process responsible for the refresh. Possibly combined with another SIGSTOP on the process responsible for writing the screensaver to the framebuffer).

I, err, wouldn't recommend that solution unless there isn't any other way :D.

**Comment by LucyOne** [comment]
> 
> 
> @LucyOne
> 
> > Is there a way to disable the screensaver altogether on Pocketbooks?
> 
> Settings (gear symbol) → Screen → Screensaver

Do you mean "Leave screen as is"? This shows a blank page when I go to the Pocketbook Homescreen and return again, which I assume is also the screensaver. Other than the six "Use ..." entries and the settings for the screensaver there isn't anything else.

**Comment by Frenzie** [comment]
@LucyOne KOReader doesn't change the screen with the "leave screen as is" setting. That would be the PocketBook system then.

**Comment by Frenzie** [comment]
But more important what do you mean "when I go to the PocketBook homescreen"? What does that have to do with suspending?

**Comment by LucyOne** [comment]
Following the same steps as the OP, my device shows the same behaviour. The same thing (blank page) also occurs when I leave KoReader without closing the book, that is pressing the home button to go to the home screen or switching applications via the task manager. When I return to KoReader, the page is blank. Other reading apps (native PB, CoolReader) show the text immediately when you return to them. This is what I would like KoReader to do also, staying awake in the background. There's is no need for a screensaver in KoReader as the device has its own sleep function.

**Comment by Frenzie** [comment]
Could you provide a link to the relevant CoolReader fork you're referring to for people who take an interest?

**Comment by LucyOne** [comment]
https://github.com/blchinezu/pocketbook-coolreader
