### ISSUE TITLE
Chapter does not start with a new page if destination anchor is used.

### ISSUE THREAD

**Issue by char11** [koreader/koreader#5141]
* KOReader version: 2019.07
* Device: Linux, Tolino

#### Issue
If at the beginning of the chapter there is a `<a>` tag with an id attribute, the chapter does not start with a new page.

#### Steps to reproduce
Edit any epub file, insert for example `<a id="ddd"></a>` after `<body>` tag at the beginning of second chapter and test.

**Comment by poire-z** [comment]
Not sure I get your issue right, as I can't produce a change by adding `<a id="ddd"></a>` where you suggest in some random multi html epub.
But, we did notice something that may be like what you notice in https://github.com/koreader/koreader/issues/4207#issuecomment-419668415 - which I somehow fixed - but some months ago I noticed some other kind of missing page break with empty elements (but at the end of a section this time if I remember right).

Anyway, since #5117 and https://github.com/koreader/crengine/pull/299, page splits should be better, so you may try with a recent nightly (> `v2019.07-13-g74518c7_2019-07-19`), and being sure to use another `Render mode` than `legacy`.
Can you try that?
If not, can you provide a simple EPUB with your tweaks (and sentences in there about what you expect to happen where ? :)

**Comment by char11** [comment]
On the recent nightly version is ok. I had to delete the sdr directory to make it work well. Thanks. :)
