### ISSUE TITLE
[feature request?] [pw4] [19.08 stable release] Ability to cancel dictionary lookups that are taking too long (fuzzy search turned off)

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5151]
* KOReader version: 19.08 stable
* Device: PW4

#### Steps to reproduce

1) perform a lookup.
2) get tired of how long its taking
3) want to go the next page, but i have to wait until the dialog pops up for 'item not found'  or the dictionary definition which in some cases has taken so long i thought my kindle crashed and had to soft-reset it. 

a speed demon the paperwhite is not.

**Comment by NiLuJe** [comment]
xref: https://www.mobileread.com/forums/showthread.php?t=321667

Feels like an underlying, possibly unrelated performance issue, because I can't reproduce on any device, including an older, slower PW2.

**Comment by poire-z** [comment]
I think we could have non-fuzzy lookup interruptible, by just using our invisible TrapWidget instead of the "Looking up..." InfoMessage.

We might as well bring https://github.com/koreader/koreader/issues/3588#issuecomment-357467866 in, so both fuzzy and non-fuzzy are also interruptible on Android.
If people with Android emulators can check if fuzzy lookups work and are interruptible, on various android versions, with just this:
```diff
- if Device:isAndroid() then
+ if false and Device:isAndroid() then
```
in
https://github.com/koreader/koreader/blob/e2961097e7b054d97928b6d188353335372b0db6/frontend/apps/reader/modules/readerdictionary.lua#L677-L681

**Comment by Frenzie** [comment]
> I think we could have non-fuzzy lookup interruptible, by just using our invisible TrapWidget instead of the "Looking up..." InfoMessage.

Might as well, though if there's a performance issue that makes non-fuzzy lookup slow I'm actually somewhat surprised the program itself is still usable.
