### ISSUE TITLE
Hyphenation for dash

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#5191]
Is it possible to make the hyphenation treat the dash (or em dash or ??? dash) characters like hyphens?

![Hyphen_sml](https://user-images.githubusercontent.com/24675403/62712138-f125d480-ba02-11e9-9fbf-8a2957860da0.png)

I don't know what kind of dash is in this screenshot, but it looks ugly.
Maybe it can be done using a "Style tweak"?

Also, does anyone knows where can I find a better hyphenation .pattern for English, since the default does not recognize (for splitting) a lot of words?

**Comment by poire-z** [comment]
> Maybe it can be done using a "Style tweak"?

Nope, that's not a CSS issue, but a line breaking/splitting issue.
The line splitting algo only splits on spaces (and CJK ideograms), and we have some rules to avoid wrap before or after some chars (when they are surrounded by spaces, like opening/closing quotes/parents).

There is indeed not much space chars in that part of the sentence, all the dashes and quotes are stuck together, making very long "words" (units of unbreakable chars).

We discussed splitting on em-dash in https://github.com/koreader/crengine/issues/295#issuecomment-502357711, where we found out that em-dash has many usages, and we may not always assume we can split after it, and that Firefox does not split after it.

But as I've been toying with using [libunibreak](https://github.com/adah1972/libunibreak) to decide about line breaks (instead of us having to decide and hardcode unicode chars where it's allowed or not), I gave your text a try, and it seems libunibreak would allow a break after em-dash, may be because it has quite more rules to decide about allowing the break depending on the context (previous and next chars, only).

Your sample text, that I managed to make it look as on your screenshot with the current crengine, would look like that with some crengine that would use libunibreak (very early work):

<kbd>![image](https://user-images.githubusercontent.com/24273478/62717128-9fca1500-ba03-11e9-8bcc-7b4a3633365d.png)</kbd>

So, that's quite encouraging to continue that work :) So, may be in a few weeks we'll have something better (but a bit slower...)

(No idea about any better hyphenation .pattern for English.)

**Comment by noembryo** [comment]
Maybe adding a rule in the Hyphenation .pattern for dashes?

**Comment by poire-z** [comment]
That won't work either.
A text sequence goes thru a `lStr_findWordBounds` function that gets subsequences of only **alpha** chars that are given to the hyphenation algorithm, so your dash is stripped out of what is asked to be hyphenated - it will not have any dash, so no use to include that in the pattern file.
(That caused some small issues, and the need for tweaks in the pattern file, with french words like `aujourd'hui` or `prud'homme`.)

**Comment by poire-z** [comment]
(A workaround currently if you're willing to edit the book HTML is to search-and-replace [em-dash](https://www.fileformat.info/info/unicode/char/2014/index.htm) to follow it up with a [zero width space](https://www.fileformat.info/info/unicode/char/200b/index.htm))

**Comment by noembryo** [comment]
Xmm, this would mean to edit some thousands of files.
I don't mind _that much_.. ;o)

**Comment by poire-z** [comment]
(And for your question at https://www.mobileread.com/forums/showthread.php?t=322078, that thingy is a hint that the book has some description in its metadata that you'll be able to read after holding and View book description. It's a bit better looking/meaning in the mosaic view where it's supposed to stand out on the right of the cover, like if a post-it was in it :) You can disable it in Display mode > Other settings Show hint for books with description.)

**Comment by noembryo** [comment]
Aaaa, that what it was!
I never thought of it...
Good to know, thank you.

**Comment by Frenzie** [comment]
@poire-z 

> I've been toying with using libunibreak

Nice! :-)

**Comment by Frenzie** [comment]
> (A workaround currently if you're willing to edit the book HTML is to search-and-replace em-dash to follow it up with a zero width space)

I think it looks nicer with a thin space or a hair space.
