### ISSUE TITLE
Add message overlay to any screensaver background

### ISSUE THREAD

**Issue by protist** [koreader/koreader#5199]
* KOReader version: KOReader 2019.08 "Starling"
* Device: Kobo H2O

#### Issue
The new [screensaver message](https://github.com/koreader/koreader/pull/5121) is great. It allows the screensaver to display book information in a message box. However, the message can only be displayed over the book's text. It would be excellent if the message could be:

1) displayed over the other screensaver "backgrounds", e.g. the cover view.
2) configured by the user to be arbitrarily positioned on the page.

#### Steps to reproduce
Attempt to use the screensaver message over a different "background" view.

**Comment by sladflob** [comment]
I think I'd like to have a stab at this, or at least part of it.

I just made some local changes so that the screensaver message is shown on top of the book's cover, if it has one. At the moment it's hard coded to always do it but to do it properly it needs a setting in Screen, Screensaver, Settings such as "Show last book/document's cover behind messages". The settings are a bit weird here as the existing background settings apply to both messages and images, but it might be strange to allow an image to be shown on top of the book cover? Or maybe not. Thoughts?

**Comment by Frenzie** [comment]
> it might be strange to allow an image to be shown on top of the book cover? Or maybe not. Thoughts?

I don't see why that would be strange. A combination of the book cover with some kind of progress indication is exactly how a paper book works.

**Comment by poire-z** [comment]
> Settings such as "Show last book/document's cover behind messages".

I'd rather see it turned the other way: "Show message over book cover/random image" :)

> The settings are a bit weird here as the existing background settings apply to both messages and images

The background (white or black) that can apply to images and covers is useful when the aspect ratio of the image is different than the one of the screen: it sets the color of the area not used by the cover.

> but it might be strange to allow an image to be shown on top of the book cover? Or maybe not. Thoughts?

"allow an image" - but aren't you talking about showing a message/progress info on top of the book cover?

For the settings UI, it could be just a matter of allowing _some_ multiple items to be checkbox'ed simultanesouly.
A matter of tweaking (and complexifying) the `checked_func` ~~and `enabled_func`~~ in `frontend/ui/elements/screensaver_menu.lua` ~~to allow the combinations that would be supported (and let that be discoverable by the user this way).~~ No, that would not work, all items need to be enabled so you can switch to them :)
But having 2 settings instead of a single one: one for mutually exclusive fullscreen background images and panels, one for little messages that can overlay fullscreen background stuff, could make sense.

**Comment by sladflob** [comment]
> I don't see why that would be strange. A combination of the book cover with some kind of progress indication is exactly how a paper book works.

Not strange if the image isn't full-screen, but strange (or at least redundant) if you have one full-screen image over the top of another.

**Comment by sladflob** [comment]
> But having 2 settings instead of a single one: one for mutually exclusive fullscreen background images and panels, one for little messages that can overlay fullscreen background stuff, could make sense.

So would this result in 6 settings entries, one set of three to choose if background is white, as-as or cover for images, and another set of three for messages?

Easiest option would be to just have one extra setting such as "Show cover behind messages and images", and if the stretch covers option is chosen then the user should be aware that they won't see the background (cover) image.

And maybe the full-screen option should only apply to images/covers when they are _not_ in the background... when a cover is used as a background image  then it's _always_ shown fullscreen?

**Comment by poire-z** [comment]
> if the stretch covers option is chosen then the user should be aware that they won't see the background (cover) image.

Why ? They will see the cover stretched :)

> the full-screen option should only apply to images/covers when they are not in the background... 

Images/covers are not currently _in_ the background. The background is the book page you were reading.

I'm a bit confused by what you say :) It's possible you don't fully get how things interact currently. So, trying to explain (from memory, I'm not really looking at the code to confirm my thoughs, so I may be wrong :)


Currently, we have one single setting for all types of screensaver:
```
G_reader_settings:saveSetting("screensaver_type", "cover")
G_reader_settings:saveSetting("screensaver_type", "bookstatus")
G_reader_settings:saveSetting("screensaver_type", "random_image")
G_reader_settings:saveSetting("screensaver_type", "document_cover")
G_reader_settings:saveSetting("screensaver_type", "image_file")
G_reader_settings:saveSetting("screensaver_type", "readingprogress")
G_reader_settings:saveSetting("screensaver_type", "message")
G_reader_settings:saveSetting("screensaver_type", "disable")
```
And other settings that are independant of the type, that may apply or not depending on the type selected:
```
G_reader_settings:saveSetting("screensaver_white_background", not whiteBackground())
G_reader_settings:saveSetting("screensaver_no_background", not noBackground())
G_reader_settings:saveSetting("screensaver_stretch_images", not stretchImages())
G_reader_settings:saveSetting("screensaver_message_position", "top")
G_reader_settings:saveSetting("screensaver_message_position", "middle")
G_reader_settings:saveSetting("screensaver_message_position", "bottom")
G_reader_settings:saveSetting("screensaver_delay", "disable")
G_reader_settings:saveSetting("screensaver_delay", "1")
G_reader_settings:saveSetting("screensaver_delay", "3")
G_reader_settings:saveSetting("screensaver_delay", "5")
G_reader_settings:saveSetting("screensaver_delay", "tap")
```

So, that's how (I think) the screensaver final result is set up:

There is an initial background: the book page you were on before invoking screensaver. Then:
- if `screensaver_no_background` => page stays as is
- else if `not screensaver_white_background` => full screen is painted black
- else if `screensaver_white_background` => full screen is painted white

Then, if `screensaver_type` = `cover, random_image, document_cover, image_file`:
- if `screensaver_stretch_images` => the image is resized to occupy the whole screen (so, actually the background set previously is fully covered and isn't seen)
- if `not screensaver_stretch_images` => the image stays as it is, and is drawn centered on the screen (so, one may actually see some bits of the background on the edges).
- (and you don't want to force `screensaver_stretch_images` to be always true, as it would distort the cover by loosing its aspect ratio).
- and that's if for these types.

Otherwise, if `screensaver_type` = `bookstatus, readingprogress`:
- as these are always fullscreen, they are drawn fullscreen (so, actually the background set previously is fully covered and isn't seen)
- and that's if for these types.

Otherwise, if `screensaver_type` = `message`:
- as this is small, it is drawn over the background set (or not) previously - at the position specified by `screensaver_message_position`
- and that's if.

Otherwise, if `screensaver_type` = `disable`:
- (not sure if background is set to anything black or white in that case) so possibly the book page stays at it is.

----
So, I'm not sure what you're thinking with images not full screen. Are you thinking of having a small static image (like a stamp) that could be put over cover, images, bookstatus, readingprogress ? I don't think that's a use case that we need to address.

The only thing that makes sense to me in this feature request is to have:
- one setting for these mutually exclusive:
```
G_reader_settings:saveSetting("screensaver_type", "cover")
G_reader_settings:saveSetting("screensaver_type", "bookstatus")
G_reader_settings:saveSetting("screensaver_type", "random_image")
G_reader_settings:saveSetting("screensaver_type", "document_cover")
G_reader_settings:saveSetting("screensaver_type", "image_file")
G_reader_settings:saveSetting("screensaver_type", "readingprogress")
G_reader_settings:saveSetting("screensaver_type", "disable")
```
- and one setting for this one that can overlay (being small) any of the previous one:
```
G_reader_settings:saveSetting("screensaver_type", "message")
```
So, this last one could just be moved out of `screensaver_type` and be made a `screensaver_show_message = true/false`.

Or am I missing some other way to see things ?

**Comment by sladflob** [comment]
Thanks for all that! I did understand most of the state info and behaviour, but I was approaching things more from the direction of providing an extra type of background (the book cover), rather than having the different screensavers as backgrounds for the message screensaver. This makes much more sense! Let me digest and have a go at it over the weekend.

**Comment by sladflob** [comment]
So here's what I have done locally... 

In the Screen/Screensaver menu
- swapped the _Leave screen as is_ and _Use message as screensaver_ menu items (because it seems more logical to structure them in that way
- changed _Use message as screensaver_ to be _Add message to screensaver_
- changed the _Add message to screensaver_ menu item so that it reflects/toggles a setting called screensaver_show_message

In frontend/ui/screensaver.lua, left show() pretty much as is in terms of it creating the appropriate widget based on the value of G_reader_settings:screensaver_type BUT now use the value of G_reader_settings:screensaver_show_message to determine whether or not to create a message widget. If it does create a message widget, AND it's already created another widget, then it uses OverlapGroup:new() to create a new widget with the message widget on top of the first one.

I tested the case where the user has screensaver_type == "message" - screensaver falls back to being an "as-is" screensaver and all boxes are unchecked in the Screen/Screensaver menu. I wasn't sure if this is ok or if it's worth adding some logic to convert screensaver_type == "message" to screensave_show_message == true but at least it doesn't do anything too weird.

I tried the various screensavers with the message on the top and they seem to work well. Tried making images stretched and unstretched and combinations of white and as-is backgrounds and this also works.

So if all that sounds ok I will create a PR?

**Comment by poire-z** [comment]
Sounds fine. Go ahead.

**Comment by protist** [comment]
Thanks for this @sladflob and others! I just upgraded to 2020.06 and the message overlay is working excellently.

I just had a comment on the placement. At the moment, all three options (place at top, middle, or bottom) will obscure the cover of the book. (Silly me, it's an overlay.) I'm unsure the best position to select, because the top often has the title, the middle has the main image, and the bottom has the author.

I was wondering if it would be possible to scale and shift the cover image slightly, then place the message at the bottom or top of the page, where it wouldn't obscure the cover at all? I'm not sure how hard this would be, but I very much appreciate the efforts so far!

**Comment by NiLuJe** [comment]
@protist: Possibly easier to simply make the message widget translucent (which is how Nickel does it, IIRC).

**Comment by protist** [comment]
Thanks @NiLuJe. Yes, I considered that, but I thought the readability and opacity required might be quite variable depending on the cover. I thought maybe a separate section might be cleaner.

**Comment by poire-z** [comment]
Probably solved/solvable with #6238 and #5121 . Re-open if not.

**Comment by drvenom123** [comment]
Is there a way to set the message on top or bottom of screen rather than smack in the middle?

**Comment by hius07** [comment]
Screensaver - Settings - Message settings - Message position

**Comment by Commodore64user** [comment]
Is there any way to adjust the size of the box to fit the amount of text in it (i have %c/%t and the box is waaay too large)? Also, to have the box (as when placed in the middle) but moved to the top/bottom instead of the banner style it currently has at top/bottom?  

Also, for smaller boxes maybe more options like: top-left, top-right etc, that way you can adjust according to book cover content.
