### ISSUE TITLE
Page flipping mode & Bookmark browsing mode: messy?

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5265]
* KOReader version: v2019.08-39-ga2dcfe9_2019-08-23/ 
* Device: KA1

#### Issue
I never use them myself so maybe I've missed something... but they seem to be mixed up with each other. 

When you go into page flipping mode the bookmark browsing mode box gets ticked. And you can only untick it by leaving page flipping mode.

On the other hand, if you go into bookmark browsing mode you can leave that mode with your chosen toggle page flipping gesture. But when you do that it looks like you can't get into page flipping mode again. It has trouble to find right zoom ("Zoom to fit page").

**Comment by gerhaher** [comment]
Better, but not 100 % correct yet.

If I tick the Bookmark browsing mode box I can untick with a Page flipping mode gesture.

**Comment by Frenzie** [comment]
In what sense is that not correct?

**Comment by Frenzie** [comment]
I mean, what would you expect it to do instead?

**Comment by gerhaher** [comment]
Isn't that two different features?

https://github.com/koreader/koreader/wiki/Tips-and-Tricks

**Comment by Frenzie** [comment]
It's more like a variation with slightly different controls than an entirely different mode. It's arguably obsolete since you can use page flipping + skim to, although then you have a dialog obscuring the action. Personally I much prefer the skim to dialog for any kind of flipping because it gives you precise controls, with the "page flipping mode" mostly being useful to quickly switch back & forth between full page view.

But sure, alternatively this here could just say `return` to do nothing, or instead get rid of the return to disable bookmark flipping and properly enter page flipping mode without potential weird interactions.

https://github.com/koreader/koreader/blob/a9f24815c657824838ae2e87fefa1f0faae02c1b/frontend/apps/reader/modules/readerpaging.lua#L276-L278
