### ISSUE TITLE
After shutdown from suspend: frontlight off when starting device

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5292]
* KOReader version: v2019.08-75-g258b13d_2019-08-30/ 
* Device: KA1

#### Issue
If you 
1. have frontlight on 
2. Sleep or power off device
3. Start device

Frontlight is now on.

But if you
1. have frontlight on
2. Sleep - and from there - power off device
3. Start device

Frontlight is now off.

**Comment by Frenzie** [comment]
Is this in relation to <https://github.com/koreader/koreader/pull/5280>?

**Comment by gerhaher** [comment]
I guess so.

**Comment by Frenzie** [comment]
It's just that I'd rather revert it than cause an extra maintenance burden.

**Comment by NiLuJe** [comment]
Yeah, there's a massive pile of kludges involved with keeping track of the FL on Kobo, because we can't read the current status off the HW (until Mk.7).

One of the many hacks keeping things "sane" (ha!) between suspend/resume must be interfering here.

I think I can speak for everyone in saying no-one wants to touch the FL code, so, err, yeah, +1 on dumping the trigger ;).

**Comment by Frenzie** [comment]
It's probably fairly simple.

1. Suspend.
2. Hardware resumes, but KOReader doesn't start resume process (i.e., frontlight stays off). I did it that way on purpose, otherwise you'd just get a bunch of weird flashes at best.
3. Shutdown (saves off FL state)

I'll probably take a look, but only a brief one. ;-)
