### ISSUE TITLE
Fine tune and set default in UI for everything

### ISSUE THREAD

**Issue by pblasi** [koreader/koreader#5312]
Hi,
We can fine tune T/B margins and font size in UI, but we can't fine tune L/R margins, Line Spacing, Contrast... Please add fine tuning to them (pop-up numerical keyboard to set desired value would be an option).  Then, having option to set this fine tuned value as default would be quite necessary (not only for the squared presets...)
Thanks!

**Comment by Frenzie** [comment]
People are working on it:
https://github.com/koreader/koreader/pull/5303 https://github.com/koreader/koreader/pull/5306

**Comment by NiLuJe** [comment]
Random UX thoughts for interested parties:

Add a vertical ellipsis button on the right of said widgets, which pops a SpinWidget up when tapped, and sets a FineTuneDefault on hold.
Possibly tweak the SpinWidget itself if it doesn't support popping up the keyboard (and make it honor safe clamping values).

Otherwise, the ButtonProgress fine tuning support may not work as-is for everything (the +/- value is fixed, which was fine for the margins, but may not be for stuff with a wider window of value (contrast/line spacing).

**Comment by pblasi** [comment]
To make it more simple, join features and avoid adding more visual stuff, my thought would be: Single tap on widget name, (since long tap is for info) to pop a window containing: 
-  actual value which is editable
- numerical keyboard
- "ok" button
- "set default" button
