### ISSUE TITLE
(FR) allow for remote device page turns

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5325]
My biggest gripe with reading for stretches while eating with the Kindle is that remote page turns are not possible afaik

This is a bit pie in the sky but would love the ability to use a wifi/Bluetooth clicker to advance the page without me needing to touch the screen. 

No idea how difficult to impossible this would be.  But a man can dream can he not ?

**Comment by Frenzie** [comment]
Basically a duplicate of #4813. Bluetooth is the same as USB OTG. Either the system/kernel can do it or it can't.

Wifi is something that could be done. We likely already compile or bundle relevant libraries to start a simple server. You can do it with LuaSocket, for example, but I'm not sure if it can do async. Presumably that's why we also bundle [Turbo](https://turbo.readthedocs.io/en/latest/) but it's disabled because it caused crashes when suspending, see https://github.com/koreader/koreader/commit/c7cac7b33386218f84fb108de214228e4c4747df. It's possible that this is no longer a problem anymore.

**Comment by poire-z** [comment]
Possible with #11457 (if your gadget speaks Wifi and HTTP).
