### ISSUE TITLE
File Browser and History

### ISSUE THREAD

**Issue by pblasi** [koreader/koreader#5348]
Since last update, book covers and icons are missing in File Browser and History. There's only text now (File name and size).

**Comment by Frenzie** [comment]
Since I mentioned something about disabling plugins in the release notes, is it possible that you disabled the CoverBrowser plugin?

**Comment by pblasi** [comment]
You're right, sorry. By the way, how can I simply quit file browser to return to actual book? Do I really need to select a book to quit file browser? Thanks!

**Comment by Frenzie** [comment]
You can use open last document in the hamburger menu, but I prefer the left, right, left multiswipe.

**Comment by pblasi** [comment]
Ok. "Exit/Close" button (which internally "opens last document") would be less confusing for standard user. Thanks!

**Comment by Frenzie** [comment]
That's a very strong claim. In terms of the metaphor, you don't "exit" your bookcase to whichever book you last put in. You exit it to the hallway, that is, the OS/application launcher or perhaps power off. That's also no different than how any program on your computer or a program like Nickel works.

That isn't to say that a reopen last book button couldn't be useful.

**Comment by pblasi** [comment]
The weird thing (again, for the standard non-programmer user) is you can go to "History", select any book in the list or QUIT by tapping the cross, which logically RETURNS to the open book. However, we cannot do this for the full list of books. We don't have a "Book Browser" which works similarly to "History", but we have a "File Browser" instead, which works with a different logic. That is what, from my simple user point of view, is confusing.

**Comment by pazos** [comment]
@pblasi: mainly there are two "apps" or modes: the file browser and the reader. Each one has its own menu but a bunch of things are accesible from the two apps.

If you go to the history and close it you go back to the application that opened the history (being that the file browser or the reader).

As you said we don't have a book browser (and some of us don't want it at all), so if you are in the reader mode and want to open a book that is not in the history you'll need to "switch" to the file manager mode and find the specific file you want to open.

**Comment by pblasi** [comment]
Yes, I can understand how it works. Just saying it's not logical not having access to a "book list" from the reader app when you do have access to a "history". Why someone wouldn't want  a "book list" next to "history"? It's just like "history", but a complete list. Why would it be bad in any way?

**Comment by pazos** [comment]
Some people store BIG collection of books in their devices. To have a "book list" we need to scan all the folders and look inside all the files for metadata. That can take ages in a device with thousands of books inside.

**Comment by Frenzie** [comment]
You can't conflate n=1 with "the standard user." Most people work with Windows Explorer every day. The normal GUI way is its own well-established decades old standard even without the underlying logic of the desktop/file cabinet/bookcase metaphor.

> We don't have a "Book Browser" which works similarly to "History", but we have a "File Browser" instead, which works with a different logic. That is what, from my simple user point of view, is confusing.

That means the history is (mildly) weird.

> Why would it be bad in any way?

Because it would break the internal logic of the metaphor, which would be confusing. Your history is a sheet of paper not unlike a bookmark, or perhaps a notebook on the side. Your bookcase is at a higher level. Exiting your bookcase means something very different than taking the book you just put in out again.

Logically speaking exiting the history should take you back to the file manager, but the experience is arguably improved by slightly bending the logic.

**Comment by pblasi** [comment]
I don't understand half of your words. That's a compliment to your writing and a criticism to my reading skills. But I really don't care about all technical stuff because I'm sure you have all the internally good reasons. So, let me take a couple steps back and just request (as a user) a new feature:
In File Browser, add a cross in top-right corner (same as in "History") which has function "open last document" so user can "quit" file browser and "return to actual open book". That would be functional and user would have the same feeling as tapping the cross in History.
Thanks and sorry for being so annoying.

**Comment by Frenzie** [comment]
Philosophical stuff, not technical stuff. ;-)

**Comment by pazos** [comment]
> In File Browser, add a cross in top-right corner (same as in "History") which has function "open last document" so user can "quit" file browser and "return to actual open book". That would be functional and user would have the same feeling as tapping the cross in History.

Is not your feature request but we have the option already in the same menu as history.

![Sin nombre](https://user-images.githubusercontent.com/975883/64526707-4f94ea00-d304-11e9-8ab9-9a0a0b720972.png)

I dunno if there is a gesture to open the last book but that could save you a few clicks if you heavily rely on this option.

**Comment by pblasi** [comment]
Yes, I know. Precisely, my idea is putting this option totally accessible in file browser (as a cross in top-right) which gives same result as tapping the cross in History. My point is user doesn't need to know there are different levels for history and file browser... but he/she can easily enter and quit history and file browser the same way.

**Comment by NiLuJe** [comment]
I would personally hate that with a fiery passion ^^.

**Comment by poire-z** [comment]
> Philosophical stuff, not technical stuff. ;-)

Technical stuff also :)
I wouldn't mind 3 independant layers, reader, file browser, history, that you could bring to front and easily change to another layer.
But the way it is architectured does not allow that: History is a Layer that can be put above others, unlike FileBrowser and Reader, which are apps.

> Precisely, my idea is putting this option totally accessible in file browser (as a cross in top-right) which gives same result as tapping the cross in History. 

Well, being an app (unlike History), FileBrowser have a top menu, and its top left and right corners are already taken by a Home and a Plus buttons. So, no obvious way to add a closing cross :) how did you see that when suggesting it?

> My point is user doesn't need to know there are different levels for history and file browser

Well, given how KOReader is done (which might not be the best or most user intuitive/friendly), that user has better know or gets to know that :)
Because when you launch File browser, you close your book, and when you re-open, it may takes a bit of time for opening. Which is not needed with History.

So, anyway, no one really bothers much with switching/closing/getting back to reader the way it works currently. Adding the closing cross would hide a bit of how we have all that working.
And changing all that to have 3 circular layers that don't close any other is quite a lot of work that looks like it's not worth the effort :)

**Comment by NiLuJe** [comment]
Oh, uh, good point, I, uh, forgot about that +... I'm not even sure I know what it does, actually xD.

**Comment by Frenzie** [comment]
> I would personally hate that with a fiery passion ^^.

Me too. A reopen last book icon might look like a book and it'd be in the same position as the "go to file browser" icon.

Also you can reassign the top right corner to "reopen last document".

**Comment by pblasi** [comment]
Understood! Thanks to all, gentlemen!
