### ISSUE TITLE
[Feature Request] Have footer use same font as current document

### ISSUE THREAD

**Issue by aartrost** [koreader/koreader#5358]
Hi all,

I know this is a pretty edge-casey request, but I really like using the progress/clock footer options centered in the document. In the native Kobo OS this looks very elegant because the text is rendered in the same font as the book itself. The KOreader footer always uses the Noto Sans making it stand out very harshly. Would it be possible to add a toggle that enables the footer to be rendered in the document's font? 

An example of the native footer:
![footer text](https://techcrunch.com/wp-content/uploads/2018/10/kobo-5.jpg?w=1390&crop=1)

A super nice bonus would be to have some control over the paddings, so that the footer can have some breathing room around it. I messed around a bit in the simulator and it can look really nice:

Page Progress | Current Time
------------ | -------------
![Screen Shot 2019-09-10 at 3 32 58 PM](https://user-images.githubusercontent.com/1044015/64655202-5d1fa200-d3e0-11e9-95a4-c0a4e4702131.png) | ![Screen Shot 2019-09-10 at 3 34 04 PM](https://user-images.githubusercontent.com/1044015/64655259-804a5180-d3e0-11e9-990e-0818cddce969.png)

**Comment by Frenzie** [comment]
Also pinging @robert00s ;-)

**Comment by robert00s** [comment]
> Would it be possible to add a toggle that enables the footer to be rendered in the document's font?

It will be very difficult to do because we use TextBoxWidget to show footer. Our widget support only some set of fonts. Whole document is rendered by CRE. 
When I try to change this line:
https://github.com/koreader/koreader/blob/3436e47367a8a4957c161d5bedca8660a4841066/frontend/apps/reader/modules/readerfooter.lua#L330 not all fonts are working :(

Example error with Droid Sans Mono font:
`01/01/20-21:13:58 ERROR #! Font  Droid Sans Mono  ( Droid Sans Mono ) not supported:  ./ffi/freetype.lua:142: Failed to load font './fonts/Droid Sans Mono', freetype error code: 1`


Pinging @poire-z Maybe you have some idea to render footer text with another method?

**Comment by poire-z** [comment]
You must have given a font name ("Droid Sans Mono") to getFace(), while it needs a file name ("DroidSansMono.ttf").

For cre, we indeed give it a font name, and we store that font name in settings - and cre open and registers all font so it knows the name(s) of/in each (there may be multiple font names in a single font file, dunno thus if that works in crengine, but that surely doesn't in frontend).

We can't currently know the font name from a font filename from frontend, and we can't currently get the font filename from a font name from crengine.
Wrote a small comment about what would be needed in:
https://github.com/koreader/koreader/blob/0f896765c371c64d2cbefb4299f6d5658bee79b7/frontend/ui/widget/footnotewidget.lua#L23-L38

But I think it's not worth the effort, and not really super needed (that might work with EPUBs, but not with PDFs, so we'll have differences - and even with EPUBs, you can't get the main or mean font size use for the book text, so you may always end up with a difference in size). (And what about EPUBs with embedded fonts, that we coult not use from frontend :)

May be the easiest solution to OP request would be to ~~add a nickname in Font.fontmap, like 
footerfont = "NotoSans-Regular.ttf", and use it instead of~~... we already have it: `ffont` :) But it's use for many other things.
Anyway, if we'd cleaned that up, or just add a `footerfont ="NotoSans-Regular.ttf",`, OP and those wanted another font (so, ok, not the one set for the book, but their single prefered font they would use with the book) could set it up via the existing font override mechanism.
I mentionned it in https://github.com/koreader/koreader/issues/5646#issuecomment-558869410, but I think I was wrong: it's not a fontmap.lua file to create, but a setting to add in settings.reader.lua, like:
```lua
    ["fontmap"] = {
        ["footerfont"] =  "NotoSans-Regular.ttf",
    },
```
(not tested)

**Comment by robert00s** [comment]
Oh, I understand it now why some fonts work, and some not :)
