### ISSUE TITLE
Can't control frontlight

### ISSUE THREAD

**Issue by ScrambleTheRamble** [koreader/koreader#5364]
* KOReader version: v2019.08
* Device: Boyue Likebook Mimas

#### Issue
Can't control frontlight

#### Steps to reproduce
Try to increase/decrease/toggle frontlight from koreader

Let me know if you need anything else/more and I'll try & provide it.

**Comment by pazos** [comment]
try 2019.09.03. See if the frontlight works (for white leds). Orange leds are not supported but PR are (very) welcome.

Probably your best bet is to use the system light control. You can swipe down to show the "navigation bar".

**Comment by pazos** [comment]
Please see https://www.mobileread.com/forums/showpost.php?p=3887814&postcount=4 that explains how frontlight works on KO and why, IMO, we should implement only sane behaviours and allow device owners to workaround device limitations.

**Comment by ScrambleTheRamble** [comment]
Pazos,

I see your point about hellish work arounds, maybe it would be best to only display that UI element based on a whitelist of known supported devices?

**Comment by Frenzie** [comment]
@ScrambleTheRamble So that would be basically all of them? I think you're looking for a blacklist instead. ;-)

**Comment by pazos** [comment]
@ScrambleTheRamble 

> I see your point about hellish work arounds, maybe it would be best to only display that UI element based on a whitelist of known supported devices?

I would say the only "supported" android device is the emulator. Features that need to be tested on devices (ie: light levels) are implemented using known android calls that work across the million android devices out there.

If your device use nonStandard lights then you need to workaround yourself. See https://github.com/koreader/koreader/pull/5331 as a great workaround for the Onyx Nova Pro.

But first try that: https://github.com/koreader/koreader/issues/5364#issuecomment-530560714 and report if it works. Until then we cannot help.

**Comment by ScrambleTheRamble** [comment]
Sorry, I misunderstood your comment. I thought you meant you wouldn't want to add work-arunds and such. 

I just tested with v2019.09.03 and I had the same behaviour. However, Koreader is able to modify the front light if **it** was already on.

The LikeBook Mimas has 2 types of light, 'cold (blue/white leds)' and 'warm' (yellow tint). Koreader only affects the warm light and only when it was already on.

**Comment by pazos** [comment]
@ScrambleTheRamble: thanks for the feedback.

> I thought you meant you wouldn't want to add work-arunds and such.

I'm fine with device owners doing workarounds as much as they like but **we cannot test them without the device in hand**. So the prerrequisites are: do not break "sane" devices.

Boyue (and other e-ink vendors) can play stupid games all they like as they don't need to pass the Android CTS. Sadly that would mean that things that are working now could become entirely broken in the next firmware version. 

In the case of the mimas some info can be found in: https://www.mobileread.com/forums/showpost.php?p=3890090&postcount=583.

Long story short: devices running non standard android lights won't be supported unless device owners port the needed bits to KOReader. They're three (general) ways to add support for lights on non standard android devices:

1. launch the system frontlight activity (ie: the one installed with the system, **not** one installed by the user) instead of the frontlight widget in KO.
2. implement support for the device using sysfs files: see #5331 as a great example
3. using `adb put` | `WRITE_SETTINGS` permission. 

Both options 1 and 2 are very welcomed, while 3 is, IMHO, not so good, because WRITE_SETTINGS is a very dangerous permission. A better approach for a device where 1 and 2 are impossible is to `root?` + `adb put`

Since fronlight control is not something important (you can always use the navigation bar and toggle from there or use a third party app to do the changes) I will label this issue as `won't fix` but leave them open for others to know. As always PR are welcome.
