### ISSUE TITLE
SSH Login DOES work; SFTP works too :)

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#5394]
* KOReader version: 2019.09-3
* Device: Kobo Clara HD

I first created a placeholder for this issue, then Frenzie replied, now I'm attaching screenshots :)

Thanks Frenzie; "root" definitely works!
- I can log in with "root" without the password (both with WinScp and Bitwize SSH client);
- I see the filesystem via SFTP; I can transfer my books and delete just transferred;
- now I have one more linux box :))) thanks!

#### Issue
root@IP, user@IP - are invalid user names in the documentation

#### Steps to reproduce
![photo_2019-09-17_23-06-47](https://user-images.githubusercontent.com/4983083/65075476-a99a4d00-d99f-11e9-9f17-d273545eddf1.jpg)
![photo_2019-09-17_23-06-38](https://user-images.githubusercontent.com/4983083/65075479-a99a4d00-d99f-11e9-8265-ea5cfcb0c23a.jpg)
![photo_2019-09-17_23-06-52](https://user-images.githubusercontent.com/4983083/65075481-aa32e380-d99f-11e9-8db6-d4659c1fc211.jpg)

**Comment by Frenzie** [comment]
You'll need to provide some information there if you want either help or a potential bug to be fixed. ;-)

For SSH keys (the secure method), here are the GitHub docs: https://help.github.com/en/articles/connecting-to-github-with-ssh

But since I only take my H2O online on my local wifi, I never even bothered with that and I just use "login without password". So then you use username `root` with no password as described [here](https://github.com/koreader/koreader/wiki/SSH).

Your quotes from May of 2018 are outdated because in July of 2018… well see for yourself. :-)
https://github.com/koreader/koreader-base/pull/712

**Comment by NiLuJe** [comment]
Note to self: Oh, that's going to be fun with the great dotfile shenanigan of 4.17...

**Comment by AlanSP1** [comment]
OK, if wiki documentation can be enhanced and corrected, to be better and simpler, please, edit it accordingly. I'm not sure how it does work as I didn't used it so far, but it looks very promising, maybe I myself start connecting this way to my device.

I write this because I'm not sure what right procedures and steps would be at the moment, so I can't edit wiki accordingly.
