### ISSUE TITLE
https://koreader.rocks/ is missing direct link to nightly download page

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#5410]
I always take latest nightly when I want latest version (usually not using OTA etc.). But, I always have problem to find direct link: http://build.koreader.rocks/download/nightly/

https://koreader.rocks/ page should also have direct link to nightly downloads page.

**Comment by Frenzie** [comment]
It's mentioned fairly early in the wiki page: https://github.com/koreader/koreader/wiki#connected-as-a-usb-mass-storage-device

I don't think there's a good argument for promoting it on the main landing page. It makes it more confusing (which one should I download) and if they choose wrong new users might shoot themselves in the foot.

Personally I'd also prefer if there were a link there but it's intentionally trying not to be distracting.

**Comment by AlanSP1** [comment]
I know it is on wiki here (which is great), but it looked strange to me that so important content (i.e. nightly builds page) isn't linked and you need to know that it is there and that you need to look elsewhere for link.

But, if you make this intentionally this way, OK. I would prefer link there, people who download nightly probably know a bit more than average Joe so it wouldn't be a problem.

Anyway, I thought this is omission, I always looked for direct link on landing page and just now thought to ask for it.

**Comment by Frenzie** [comment]
A separate download page just for stable vs development would introduce unnecessary friction in the download process. If there were a way to cleverly combine that with a friendlier platform selection it might be doable.

Unfortunately, while you can simply link to `https://github.com/koreader/koreader/releases/latest/download/koreader-2019.09.3-amd64.deb` (see [here](https://help.github.com/en/articles/linking-to-releases)) that isn't very useful since the version is still part of the asset filename.

It could be done with a little bit of JS. See https://getsharex.com/downloads/ for a somewhat bad example, which doesn't display any fallback links should the JS fail to load for some reason. They put their jQuery-tastic code up [over here](https://github.com/ShareX/sharex.github.io/blob/d2277bf70dee0a1025847a5bc23d480850b675a2/js/downloads.js).

**Comment by AlanSP1** [comment]
I was thinking about simple "Downloads" page, which links to:
https://github.com/koreader/koreader/releases (where download links now)
http://build.koreader.rocks/download/nightly/

And with a bit text to explain difference between these two versions. So, it would be one more static page. But there could be enough warning that nightly can be buggy.

**Comment by Frenzie** [comment]
Yeah, but that's just friction. :-/ Then you have to click twice instead of once.
