### ISSUE TITLE
Crash if open .djvu with cyrillic characters in path or name of file

### ISSUE THREAD

**Issue by CyberAndrew** [koreader/koreader#542]
When I try to open any .djvu book with cyrillic characters in name or path (for example "Книги\Михайлов ТФКП.djvu") koreader crashes.

Once i rename it to english characters, everything works OK and book loading normally.

**Issue**

1. Name a DjVu file with Cyrillic characters, for example `Михайлов ТФКП.djvu`.
2. Open DjVu file. It'll most likely crash KOReader.

**Comment by akamaus** [comment]
looks like this reaction is triggered by any cyrillic letter in file name. Can it be somehow related to locale settings on device?

**Comment by CyberAndrew** [comment]
2 years and still no fix :(
Can this solution https://github.com/koreader/kindlepdfviewer/issues/47 work here?

**Comment by Frenzie** [comment]
No, that line was simply carried over into the current koreader.sh: https://github.com/koreader/koreader/blob/a3c4254809240812faf6749fa4fe069fbea4f510/platform/kobo/koreader.sh#L2

I have no idea how to reproduce this issue btw. The filename in the OP seems to be invalid on FAT.

**Comment by robert00s** [comment]
Is this problem still exist?
I cannot reproduce it on emulator.

**Comment by CyberAndrew** [comment]
@robert00s Yes. Version is v2018.01.10-nightly

**Comment by Frenzie** [comment]
@CyberAndrew What are the steps required to reproduce it? Your example from the OP is something my computer simply refuses to create on NTFS or FAT, whether I try to do so in Windows XP, 7, 10 or Linux.

**Comment by CyberAndrew** [comment]
@Frenzie 
It seems your operating system does not support Russian characters.
Maybe you need to turn support of non-English languages in settings?
On Windows 10 go to Control panel -> Regional standarts -> Additionaly -> Language of programs not supporting unicode -> Russian (Russia) -> OK

**Comment by Frenzie** [comment]
@CyberAndrew The problem isn't the Russian characters. Those are perfectly fine. (Yes, I also tested it on my Kobo Aura H2O.) It's that `\` is an invalid character on Microsoft filesystems.

**Comment by CyberAndrew** [comment]
@Frenzie 
Hmm... the "\" symbol works perfectly on my Windows. For example, I can open path D:\Program Files\GPU-Z in my explorer without problem.
But if I put Russian symbol in any part of the name on my Kobo aura hd and Koreader (for example, 
sd/Books/Math/Sokolov -- works fine
sd/Books/Math/SokoЯlov -- it says "No engine for reading this file or file is invalid"

**Comment by Frenzie** [comment]
Oh, now I finally understand! This whole time I'd assumed `\М` was some kind of messed up escape sequence for some kind of invalid Unicode, but it's supposed to be a directory.

**Comment by Frenzie** [comment]
To be clear, this is something I tried last year on my H2O, possibly as part of looking into this issue. No directories involved. The djvu and epub files are different obviously; I gave them the same name for testing purposes only. I will no test with a directory as part of the mix as well as the new filename you provided, though given your problem description I do not expect it to make a difference.

![screenshot_2018-01-16_16-27-05](https://user-images.githubusercontent.com/202757/34996557-4615a630-fada-11e7-96ba-094d5009865b.png)

**Comment by Frenzie** [comment]
Hm, that's odd. Not only can I reproduce your crash now, but it even happens on the old file. Which obviously opened previously, given the presence of the `.sdr` directory to prove that I'm not misremembering. Something changed on my system since August and I don't know what.

**Comment by hwhw** [comment]
Sorry, I would love to be much more involved with Koreader development, alas, my time ist still so scarce. But as I'm seeing this issue, I think I can drop in:
The djvu document library has its own file handling abstraction and is, unfortunately, quite entangled with it. What's bad about that? Well, it also uses a UTF8 string library. Unfortunately, this means that all file names must be valid UTF8 encoded strings in order to have it working. I'm pretty sure this might be the culprit here... As the file system is often mounted as a FAT partition and for those, the charset to present to the VFS layer of the file system is a mount parameter, there are many things that can go wrong. Other than other tools like, say, the file manager on the PC, the library will just bail out when it isn't satisfied with the file name string. Lots of places to look at: the iocharset mount option on the ebook reader, the method of interfacing with the ebook reader, the iocharset mount option on the host machine and in the end, the actual octets the file name consists of. For starters, piping an ls through hexdump might present some hints. It was not a small task to disentangle the charset sensitivity from the djvulibre library, so I didn't even bother to start back then.

**Comment by Frenzie** [comment]
`/mnt/onboard` is mounted with `codepage=cp437,iocharset=iso8859-1,shortname=mixed,utf8` on Kobo.

My system does something slightly different:

```
/dev/sdf on /media/frans/KOBOeReader type vfat (rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)
```

> It was not a small task to disentangle the charset sensitivity from the djvulibre library, so I didn't even bother to start back then.

Besides some small bug fixes djvulibre hasn't changed much at all for a few years ago really. (And for the most part, why should it. :-) )

**Comment by hwhw** [comment]
The whole filename mangling business is a ridiculously compicated matter. Probably the best debug measure is to run a shell on the device and pipe the output of an "ls" through hexdump. Do *not* trust what your host PC shows you, is what I want to say.
