### ISSUE TITLE
[Proposal] Image viewer use the whole screen when opened

### ISSUE THREAD

**Issue by max-cw** [koreader/koreader#5444]
It's always bothered me that when opening a full-page picture in imageviewer widget, it is shown in a smaller size because the imageviewer use a significant vertical space for the buttons on the bottom. I made some simple changes to the imageviewer.lua as followed:

- When opened, the buttons are not drawn, and the picture take up the whole screen space.
- If the user taps the bottom quarter of the screen, the buttons are toggled.
- If the user taps the rest of the screen, the widget is closed.

I've been using this modified image viewer for a long time now and I think it works well. I would like to ask if the team thinks this is a reasonable idea. The code I have is based on the old version of koreader, but it should be easy to merge the change into the latest one.

**Comment by NiLuJe** [comment]
That certainly sounds sensible to me, feel free to fire a PR ;).

**Comment by robert00s** [comment]
:+1: 
I was also thinking about something similar.

**Comment by poire-z** [comment]
I kinda like the current display, I don't think the buttons height ever bothered me.
But no opposition to this proposal if people prefer that - as the hidden buttons would be easy to display, and not to hard to discover (if stuck, the user would just tap anywhere).
But you have to keep the current state (buttons shown/not shown) when some other gestures are done (zoomin/panning...)
Just don't forget the top caption that should still be shown by default if there is one (from images in Wikipedia lookup results) - and the rare case of animated gifs, where tap on left/right should still move among frames - with a little progress bar at bottom (that should be displayed even if the buttons are not - it's only with it that one can know it's an animated gif and there's more stuff to be seen).
(So that you don't spend time looking for some sample, here's an EPUB with such an animated gif  - a map of Europe in grey and pink on the first pages: [SaintEmpireRomainGermanique.FR.epub.zip](https://github.com/koreader/koreader/files/3682461/SaintEmpireRomainGermanique.FR.epub.zip))

**Comment by max-cw** [comment]
Thanks for the comments. And especially thanks @poire-z for the detailed one! Indeed, the animated gifs is something I did not notice before. I'm happy to report that I just re-applied my modification on the master and with minimum changes, I manage to make everything works! Everything you said is work as before. When it detected a list of images, I switched back to showing button by default, and disabled the button toggle/close onTap.

I'll fire a PR soon. Just need to figure out how. This will be my first PR on GitHub 😉(please be gentle!)
