### ISSUE TITLE
Kobo Forma (and others?): valid frontlight warmth should be 0,10,20,30,...,100

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#5471]
The Forma's ComfortLight (aka "warmth") only changes for 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100. However KOReader allows setting it to (for example) 25 via the frontlight dialogue or slide gestures. This should not be allowed.

This might also apply to the new Libra H2O. I have no way to check.

**Comment by NiLuJe** [comment]
That's why the buttons switch to +/- 10 instead of +/- 1 on those devices.

It's both to prevent making the UI layout code in that module even more insane, and also to keep the illusion of granularity on the warmth sliding gesture.

TL;DR: That's a non-issue in my book. I'm not against merging a patch that fixes itt in a clean and non-intrusive way, but I certainly won't do anything about it myself ;).

**Comment by pazos** [comment]
Affects:
 - Kobo Forma, Libra and Clara
 - BQ Cervantes 4

A non-issue for me too.

**Comment by Frenzie** [comment]
I'll close this since no one will work on this minor issue. Please feel free to submit a PR.
