### ISSUE TITLE
Feature Request: Enable the builtin led light ( if available ) during shutdown

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#5479]
* KOReader version:  v2019.09.3-64g5209494_2019-10-10
* Device: Kobo Aura H2O2

#### Issue
When issuing a shutdown, the screen immediately switches to the power off status while the shutdown procedure is still running for a while, therefore, if someone tries to press the on button again, he'd find it non-functional for a while.
At least in my device there's present a led which is lit during boot, which helps knowing that the device is working and not just dead. Setting it on before initializing the shutdown procedure should suffice, since once the device is powered off it'll naturally turn off as well the light.

**Comment by Frenzie** [comment]
I don't think Nickel does that on shutdown, does it? Curiously, I've never investigated the light.

**Comment by BrainDamage** [comment]
That is correct, I consider it a deficiency on Nickel as well

**Comment by pazos** [comment]
Probably a **cannot fix**. You're describing a known hardware limitation of netronix based ereaders. (They have two cores, one is the ARM SoC where linux run and the other one is based on MSP430 which controls the power/battery and most of the hardware and exposes stuff to linux via i2c)

Even when we can turn on the light at poweroff this won't change the thing because the led will be turned off a few seconds before the reset circuit becomes available again (which happens about 500ms after the msp430 PMIC receives a reset command from the linux core).

This affects Kobos, Cervantes and most Freescale/NTX e-books out there. I guess it will also affect Kindles (and maybe that's one of the reasons why lab126 choose to avoid poweroff).

Please test it on your device and tell us: turn the light on yourself (it is exposed as sysfs node) and issue a `poweroff`. I may be wrong.

**Comment by NiLuJe** [comment]
For reference:

On:

```
echo "ch 4" >| /sys/devices/platform/pmic_light.1/lit && echo "cur 1" >| /sys/devices/platform/pmic_light.1/lit && echo "dc 1" >| /sys/devices/platform/pmic_light.1/lit
```

Off:

```
echo "ch 4" >| /sys/devices/platform/pmic_light.1/lit && echo "cur 0" >| /sys/devices/platform/pmic_light.1/lit && echo "dc 0" >| /sys/devices/platform/pmic_light.1/lit
```

**Comment by BrainDamage** [comment]
I just tested it now through ssh and it worked like intended:
[root@(none) ~]# echo 'dc 1' > /sys/devices/platform/pmic_light.1/lit && poweroff
the led lit, and shut down at the same time as the screen backlight

I've also tested enabling just the led, and then issuing a shutdown from koreader, and the same behaviour happened.
I guess its usage is limited to the case of backlight being off or during daytime, but it does work

**Comment by pazos** [comment]
> the led lit, and shut down at the same time as the screen backlight

Two questions:
Are you able to turn the device again just after the led lit went off? 
How much time does the green led stays on? a second?

> I guess its usage is limited to the case of backlight being off or during daytime, but it does work

**Comment by pazos** [comment]
Ie: did a quick test with by buildroot based Aura HD: lights stayed on for a second, then went of for a second (until the last message was written to UART) and the power button didn't work for a while (between 0,5-2 seconds) Fun fact: turning off the device with the button in "pull down" position didn't work. It needs a cicle "pull up" -> "pull down" to turn the main board again.

**Comment by Frenzie** [comment]
> nobody

Nobody who isn't testing shutdown on real hardware anyway. ;-)

**Comment by BrainDamage** [comment]
> > the led lit, and shut down at the same time as the screen backlight
> 
> Two questions:
> Are you able to turn the device again just after the led lit went off?
yes, altough it requires me to hold the power button for half a second, then the led lights up again for the power on sequence
> How much time does the green led stays on? a second?
about 2-3 seconds ( it's also blue in my device, but I know it's a pointless remark )
> I think it is a rather useless feature as nobody would want to turn off a device just for turning it on again after less than a minute. 
I partially agree, but I defer the choice to the devs
Turning the led on when shutdown is called should be a rather simple piece of code, the main complexity coming to account the different types of hardware, but I imagine that interfacing with the led might be usable for other purposes.
So I guess this feature should be slave of a led interface being implemented, once that's in, this would be a trivial feature to add, extremely low priority otherwise.

**Comment by pazos** [comment]
> I partially agree, but I defer the choice to the devs
Turning the led on when shutdown is called should be a rather simple piece of code, the main complexity coming to account the different types of hardware, but I imagine that interfacing with the led might be usable for other purposes.
So I guess this feature should be slave of a led interface being implemented, once that's in, this would be a trivial feature to add, extremely low priority otherwise.

I think it is a better idea just to run a generic poweroff script on devices that can poweroff, a la #3033. 
It's not a matter of how hard is to implement this feature (AFAICT the led interface is the same in all devices that can poweroff) but having to decide where to put UI menus to configure it for something that isn't really useful and that tries to "fix" something out of scope for this program.

With a generic script, non overwritten by updates, each power user can append its own stuff.

But yeah, PR are welcome.

**Comment by NiLuJe** [comment]
Fun fact: enabling the LED manually seems to persist in weird and interesting ways across reboot/poweroff.

I'd inverted my final test command (i.e., [on instead of off](https://github.com/koreader/koreader/issues/5479#issuecomment-541244670)), and that seemed to make the LED *stay* on every time Nickel usually lights it up for a few moment (say, charging).

That was on the H2O, FWIW, never tried anything on the Forma.

**Comment by BrainDamage** [comment]
I guess I'll close this, it's too niche and accounting for all the hardware misbehaviour sounds like it's not worth the efforts.
