### ISSUE TITLE
Page Flipping mode and Table of content mode is very slow- PDF file

### ISSUE THREAD

**Issue by ocra98** [koreader/koreader#5489]
* KOReader version: v2019.08
* Device: likebook mars T80D Android 6.0.1

#### Issue
1. Flipping in "Page flipping" mode is slower than others mode (and also slower than "zoom fit page" mode- that has the same angle of view as it)
2. Open table of content is very slow (I think the Table of content is just a few kb txt ?)
--
ps:  This problem occurs on every **pdf** file, every size.

**Comment by Frenzie** [comment]
Probably a duplicate of #5378.

To make sure it's a device-specific issue, is there a problematic document you could share?

**Comment by ocra98** [comment]
> Probably a duplicate of #5378.
> 
> To make sure it's a device-specific issue, is there a problematic document you could share?

This problem occurs on every pdf file, every size.

**Comment by Frenzie** [comment]
You mean it doesn't occur on EPUB or DjVu, just PDF?

For example, djvu3spec.djvu from https://github.com/koreader/test-data contains a TOC, as do all (?) the EPUBs.

paper.pdf from there also contains a TOC. 

These TOCs are all supposed to display instantaneously of course.

> Flipping in "Page flipping" mode is slower than others mode (and also slower than "zoom fit page" mode- that has the same angle of view as it)

Incidentally, what do you mean by slower? It's not actually slower, but it will respond 300 ms slower (by default) because it enables double tap zooming. So any tap is delayed by 300 ms. (This is basically why I don't like double-tap based anything.)

**Comment by ocra98** [comment]
> You mean it doesn't occur on EPUB or DjVu, just PDF?
> 
> For example, djvu3spec.djvu from https://github.com/koreader/test-data contains a TOC, as do all (?) the EPUBs.
> 
> paper.pdf from there also contains a TOC.
> 
> These TOCs are all supposed to display instantaneously of course.
> 
> > Flipping in "Page flipping" mode is slower than others mode (and also slower than "zoom fit page" mode- that has the same angle of view as it)
> 
> Incidentally, what do you mean by slower? It's not actually slower, but it will respond 300 ms slower (by default) because it enables double tap zooming. So any tap is delayed by 300 ms. (This is basically why I don't like double-tap based anything.)

**Comment by ocra98** [comment]
> You mean it doesn't occur on EPUB or DjVu, just PDF?
> 
> For example, djvu3spec.djvu from https://github.com/koreader/test-data contains a TOC, as do all (?) the EPUBs.
> 
> paper.pdf from there also contains a TOC.
> 
> These TOCs are all supposed to display instantaneously of course.
> 
> > Flipping in "Page flipping" mode is slower than others mode (and also slower than "zoom fit page" mode- that has the same angle of view as it)
> 
> Incidentally, what do you mean by slower? It's not actually slower, but it will respond 300 ms slower (by default) because it enables double tap zooming. So any tap is delayed by 300 ms. (This is basically why I don't like double-tap based anything.)
With paper.pdf in "test-data folder":
- Flipping page (in Flipping mode): 1.2s (1200ms)
- Flipping page (in other modes): 0.7s
- Open Table of Content: 2.5s

**Comment by Frenzie** [comment]
I don't think there's really much reason to keep this open for now. Like I said it's a duplicate of #5378. Apparently (some) Likebook devices are oddly slow. I'm not inclined to think having the specific ways in which they're slow as separate issues will be helpful.

> Flipping page (in Flipping mode): 1.2s (1200ms)
Flipping page (in other modes: zoom modes, crop mode, reflow mode): 0.7s

That discrepancy sounds like it probably falls within the margin of error for 300 ms, assuming human measurement. That ~.7s is pretty slow though, depending on what you mean by that. You should see a more or less instantaneous response (at least not much slower than 1/30th of a second or so), but on E Ink it might take a while to actually finish updating the screen.

A page turn on the H2O might take that about that long to fully complete, for example, but only because the screen updates slowly.

> Open Table of Content: 2.5s

Yeah, that's just absurd. If anything it should be faster than a page turn, which should already be instantaneous in the first place.

**Comment by hugleo** [comment]
Same device here,

testing using paper.pdf

Didn't face any of those problems. Load of Table of Content is immediate.

**Comment by Frenzie** [comment]
@hugleo Thanks for testing! That's certainly confusing.

**Comment by Frenzie** [comment]
And yes, heavy scanned PDFs might take a little while to turn pages of course. But the discrepancy between flipping and regular shouldn't much exceed the 300 ms double tap detection delay. A too high-res scanned PDF (let's say over 600 DPI) would certainly profit from being reduced in resolution to something more appropriate to the device (but if you go through such trouble, `pdf2djvu` is a much more advantageous program to use).

**Comment by ocra98** [comment]
> Same device here,
> 
> testing using paper.pdf and another pdf composed of images (scanned text)
> 
> Flipping page really takes 1.x s sometimes, that's depends, but I think is the normal for some pdfs.
> 
> But table of contents definitely is instantaneous.

Thanks you very much brother.
I have reset the device. As a result, Koreader ran as fast as a rabbit.
I had something wrong in installing the previous version. Even opening KOreader's menu took a few seconds.
I thought open source software was not perfect. (hihi). I should have reset the device earlier.
Thank you very much. Thanks the development team.

**Comment by Frenzie** [comment]
I'd actually overlooked that you wrote v2019.08. For future reference it might be worth checking out the latest version to see if it fixed anything. :-)
