### ISSUE TITLE
How do you debug?

### ISSUE THREAD

**Issue by lhk** [koreader/koreader#5490]
* KOReader version: any
* Device: emulator

#### Issue

I would like to create a koreader plugin and am currently browsing the various ressources, trying to figure out how to set everything up.

How do you develop for koreader? Is there a setup that allows interactive debugging? So far, I could only find http://koreader.rocks/doc/modules/logger.html

**Comment by Frenzie** [comment]
The best one I know of is https://github.com/pkulchenko/MobDebug (graphically in [ZeroBrane](https://studio.zerobrane.com/doc-remote-debugging)), but except for some native code (where you should use gdb — or lldb or whatever) there's rarely a point to it imho.

**Comment by lhk** [comment]
@Frenzie thank you for the quick answer. 

If I may ask, what setup are you using yourself?
You say there's rarely a point to it, so do you develop just with a text editor?

**Comment by Frenzie** [comment]
As a quick addendum, if you want a call stack for example you can just call `error()`. The "recompile" step is instantaneous after all. It's also a poor man's "breakpoint," with the disadvantage that you can't continue on to the next breakpoint without commenting in/out and restarting. But because memory corruption isn't a thing (barring some FFI) it's a fairly small disadvantage.

> You say there's rarely a point to it, so do you develop just with a text editor?

I typically use Geany, but for the most part not its IDE features (besides that it helps for autocompletion with methods from other modules and the like).

Looks something like this:

![Screenshot_2019-10-13_12-27-02](https://user-images.githubusercontent.com/202757/66714262-e269ee00-edb4-11e9-833e-efbaf5f1bc56.png)

**Comment by poire-z** [comment]
Personally: emulator on linux, and just vim for editing (and git and branches for trying to not get lost).

And I use `require("logger").warn('mystuff", myvar)` for debugging (so I can `koreader|grep WARN` to only see my logs).
And I just quit KOReader and relaunch the emulator after each fix/change I want to test.

I have a wrapper for launching koreader with `./kodev run -h=610 -w=600 --no-build` to skip the build/install time - but you'll want to _not_ skip it when developping plugins, as they need to be copied in koreader-emulator-xxx/koreader/plugins/.
@Frenzie : which leads me to ask, is there a reason for plugins and frontend to be different:
```
ls koreader-emulator-x86_64-linux-gnu-debug/koreader/
frontend -> ../../frontend
plugins  -> ../../base/build/x86_64-linux-gnu-debug/plugins
```
(I might remember there was some .so at some point in some plugin, which could justify that - but I can't find any now.)

**Comment by Frenzie** [comment]
Evernote does, at the very least. And since that was also the very first plugin, it's been that way from the get-go. 

https://github.com/koreader/koreader/commit/5c1d5c3314d2c3a9ec0636d6663ae1088f2014db

**Comment by Frenzie** [comment]
Since what you wrote [on the forum](https://www.mobileread.com/forums/showpost.php?p=3903686&postcount=3) sounds like you'll be dabbling in GUI stuff, you might want to look into the wbuilder tool (`kodev wbuilder` as an easy shortcut). It allows you to call up widgets immediately for quick iterations without having to go through the regular menu.

**Comment by lhk** [comment]
oh that's a nice tip, thanks

**Comment by lhk** [comment]
thank you all for the feedback
