### ISSUE TITLE
Metadata extraction: books on History page not extracted

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5523]
* KOReader version: v2019.10-10-gf38073c_2019-10-23/  
* Device: KA1

#### Issue
Metadata for opened books are not extracted when using 'Extract and cache book information' and    then open History page 

#### Steps to reproduce
1. Open some books
2. Delete cache database and restart KOReader
3. Choose (for example) "Detailed list..." for both file manager and History
4. Extract
5. Open History

**Comment by poire-z** [comment]
Oh sh*t. Didn't think of that. Caused by #5435. Pinging @derungs .
Not so much related to "Extract and cache" (which does extract with the File browser cover sizetag - this seems to be fine).

Previously, we had 2 cover sizetag: `s` (list) and `M` (mosaic). Now, for list view, we have `sNN`, with NN the height in pixels of the items, now that we can change the number per page.
List view in File browser and History have some subtle geometry differences (well, not so subtle: bigger header in File browser than in History, making larger items in History).
So, now, covers in File browser are saved with eg `s51` (51 pixels height), while in History with `s56` (56 pixels), provoking a re-extraction each time you swith to a view and find the cover extracted by that other view...
So, I guess when in History, we should accept a saved s51 even if we request s56... which will be a kludge because previously, the code didn't have to care where it was used from...

**Comment by poire-z** [comment]
Or just use `s<nb_of_items_per_page` instead of `s<height_of_item>` for the detailed list sizetag.
So, we'll get s10 instead of s51 or s56 - extracted by Extract and cache will get s51 - and when viewed in History, there will be a small resize from 51 to 56 (but that's what was already happening previously).

**Comment by poire-z** [comment]
Related review comment discussion at https://github.com/koreader/koreader/pull/5435#discussion_r329341229.
