### ISSUE TITLE
FR: Support mdict

### ISSUE THREAD

**Issue by luckyfatpig** [koreader/koreader#5552]
hope to support mdict

**Comment by Frenzie** [comment]
This is a popular format in China?

**Comment by Frenzie** [comment]
I'll close this for now, while pointing out that on Android you can customize dictionary apps. Please see https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-dictionary-list Mdict already seems to be part of the standard list.

**Comment by epistularum** [comment]
I think he's referring to the actual dictionary format and not the app of the same name. It's a very popular format among enthusiast chinese custom dictionary makers.

https://downloads.freemdict.com/
https://www.pdawiki.com/forum/forum-4-1.html

I'm not sure if it's fine posting those links because it contains some copyright infringement so please let me know if that's an issue.

**Comment by Frenzie** [comment]
[PyGlossary](https://github.com/ilius/pyglossary) can convert MDict to StarDict.
