### ISSUE TITLE
bug? koreader crashed ; all settings appear to be gone

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5577]
* KOReader version: latest stable (10.3?)
* Device: latest paperwhite

#### Issue
when i tried to quit koreader it seemed to freeze so i held down the power button.  now when i  boot up i get first run messages and all my cool settings / logins (evernote, progress sync) etc seem to have evaporated.  

1) anyway to recover without having to manually set everything back up the way I like it?
2) in the future, should I be backing up the folder or settings in some way to prevent or mitigate something like this from happening again?

thanks!

##### `crash.log` (if applicable)

https://gist.github.com/arooni/62bc4ff146115eb912443605d41b1de6

**Comment by Frenzie** [comment]
Does this time correspond to around when it happened? Normally there should be a backup file.

```
11/07/19-14:47:37 WARN  Failed reading ./settings.reader.lua (probably corrupted).
11/07/19-14:47:37 WARN  no usable backup file for ./settings.reader.lua to read from
```

If you didn't immediately go looking for settings files and closed/started the program in the meantime then there's probably a new backup by now.

> in the future, should I be backing up the folder or settings in some way to prevent or mitigate something like this from happening again?

You should back up anything you don't want to lose, but I'm afraid I don't understand how you could lose your settings.

![Screenshot_2019-11-07_21-10-51](https://user-images.githubusercontent.com/202757/68423827-18777380-01a3-11ea-9d22-d08c70f70f9e.png)

Since you say you held down the power button, perhaps we're dealing with an extra volatile FAT32-type situation here?

**Comment by arooni** [comment]
yes definitely happened today.  

didn't think i needed to keep a backup of settings myself.  maybe i should start backing up everything in settings when i have it perfect.

and i have shut down/restarted holding the power button before without any negative consequences.  bad luck i suppose?

**Comment by poire-z** [comment]
> in the future, should I be backing up the folder or settings in some way 

It's good to keep a copy of `settings.reader.lua` from time to time. Even just copying it manually on the device itself, alongside the existing one, as `settings.reader.lua.BACKUP` (as it's not a name KOReader uses, it gets no chance to be corrupted in case of crash/had poweroff).

> I'm afraid I don't understand how you could lose your settings.

I've seen this happen. Wrote about that in https://github.com/koreader/koreader/pull/3625#issuecomment-473472574

**Comment by Frenzie** [comment]
Well, that's why LuaData goes a bit overboard on the same principle.

https://github.com/koreader/koreader/blob/9bc1c6f40d92c6dad450e5cf4fd3443b417d2e91/frontend/luadata.lua#L13

https://github.com/koreader/koreader/blob/9bc1c6f40d92c6dad450e5cf4fd3443b417d2e91/frontend/luadata.lua#L61-L70

https://github.com/koreader/koreader/blob/9bc1c6f40d92c6dad450e5cf4fd3443b417d2e91/frontend/luadata.lua#L139-L147

I never ported that to LuaSettings because it was a bit experimental and probably overkill, but if it's a thing that happens to some people I guess it's best to just copy over that code and/or refactor/abstract it slightly differently.

**Comment by NiLuJe** [comment]
Oh. Kindle. Definitely fat shenanigans. Specifically, the fuse proxy layer the Kindle uses.

That's also what caused the hang. In fact, nothing hanged, but the startup script got truncated, and failed to run properly, so it didn't resume the WM.

**Comment by NiLuJe** [comment]
You might find the actual content of the truncated file in one of the hidden fuse_hidden_xxxx file in the same folder...

**Comment by NiLuJe** [comment]
Even if we rename, there's a chance the proxy layer effectively breaks atomicity, and I don't have any great ideas to avoid that, except running from the raw FS, which we can't really do because it's noexec.

**Comment by Frenzie** [comment]
@NiLuJe That's still doubly confusing though. vfat has been in the kernel since… forever? At least the early 2000s iirc. Why FUSE? And even so, FUSE has worked perfectly fine and dependably in my experience, just a bit slow in a relative sense. In actual practice that means little more than some extra processing you don't notice anyway, except perhaps on something like a slow embedded ARM device.

**Comment by NiLuJe** [comment]
The Kindle exposés both a raw fat partition, and a synthetic one proxies by a custom fuse plug-in, at an offset. Everything uses the proxy, and it reacts badly to updating existing file, or removing file with locks or fds open (silently...).

**Comment by NiLuJe** [comment]
The original reasoning behind this madness might have been to handle USBMS in a specific way, but I'm pretty sure they've stated to regret that decision since then
..

**Comment by Frenzie** [comment]
They have a regular FAT mount… and then they layer FUSE on top of it? What's the goal there? Because I'm hoping reduced performance and reliability are nothing but unfortunate side effects. :-P

**Comment by NiLuJe** [comment]
My best guess would be usbsms, see above ;).

**Comment by Frenzie** [comment]
Ah, GH hadn't shown me that comment yet.

So it's a bit like that [MTP](https://en.wikipedia.org/wiki/Media_Transfer_Protocol) stuff which I rather tend to dislike, at least on Android where it's @#$@# terrible. (This might be Android's fault.) It seems to work okay on my '07/'08 era Sony Walkman.

I remain confused about the reliability though, even if I expect unnecessary battery drain and possibly reduced performance. I mean, if *I* wrote it I'm sure it wouldn't be the most reliable thing but I would assume some of those Kindle people can write a FUSE driver in their sleep…

**Comment by poire-z** [comment]
Corrupted/empty settings on crash/freeze should hopefully no more happen - and losing settings and annotations should now be limited to losing 15mn of annotations & page progress (that one can reduce to 5mn via the menu), thanks to #5678 and #5687, available in next nightly.
So, closing. Re-open if that happens again.
