### ISSUE TITLE
Icons update

### ISSUE THREAD

**Issue by aartrost** [koreader/koreader#5594]
Hi all,

Again, one of my half baked ideas ha. I've been enjoying KOReader a lot and I would love to help make some updates to the UI possible. I've been finding the current icons slightly ambiguous and non-homogeneous. If I were to purchase and donate a commercial license to an icon pack like this one: https://creativemarket.com/raul.taciu/381094-Simple-Line-Icons-Pro?u=watc, would there be any interest at all in the community to do an overhaul of the current icons so that we can give the UI a bit of an update?

I've done a super crude pass with some of the icons from the pack linked above with the emulator, and the more coherent appearance of the icons seems to work ok.

![Screen Shot 2019-11-14 at 1 17 11 PM](https://user-images.githubusercontent.com/1044015/68896797-19e3f700-06e1-11ea-832a-8834a0bbe9e6.png)

**Comment by NiLuJe** [comment]
Licensing is iffy in that it appears to prohibit redistribution (which, grante,d doesn't make much sense for graphics asset, but whatever).

Since we're FOSS, by definition, we'd be redistributing the parts we need.

That's a bit of a catch-22 here, but, as always, IANAL ;).

That said, I'm all for cleaner icons, that would indeed make sense now that most of our target devices have much higher density ;).

**Comment by Frenzie** [comment]
Btw, https://github.com/templarian has also created various other icon sets since.

**Comment by aartrost** [comment]
> Btw, https://github.com/templarian has also created various other icon sets since.

Those look great! If I can find some free time I'll go through those and see what icons could be used to replace current ones

**Comment by Frenzie** [comment]
To be clear, the current icons were taken from https://github.com/Templarian/WindowsIcons

1c40d127cda402e9f46f2a42baa326ca88bb99f8 doesn't list any specific reason for choosing these, although obvious being free & monochrome was a factor.

**Comment by poire-z** [comment]
(Please stick to pure black & white - any gray may cause some double drawing, so some little animation, on some eInk devices like my GloHD.)

**Comment by aartrost** [comment]
Gotcha! Yeah, with my testing in the emulator I ran into issues converting the PNGs to the palette required for rendering on the e-readers. I'll test beforehand to see if any pickings can be converted without issue.

**Comment by Frenzie** [comment]
@aartrost Btw, for preview type stuff it doesn't matter but for the real PR we need a difference approach to the resource bundle that includes higher res icons. The 64 × 64 and 48 × 48 sizes were originally intended for 167 DPI, so we should double that for modern devices.

This actually maps quite well to what's described in the Android docs: https://developer.android.com/training/multiscreen/screendensities

![devices-density_2x](https://user-images.githubusercontent.com/202757/68989924-3dc44b80-084d-11ea-9c2a-2d76e626cd53.png)

*    36x36 (0.75x) for low-density (ldpi)
*    48x48 (1.0x baseline) for medium-density (mdpi)
*    72x72 (1.5x) for high-density (hdpi)
*    96x96 (2.0x) for extra-high-density (xhdpi)
*    144x144 (3.0x) for extra-extra-high-density (xxhdpi)
*    192x192 (4.0x) for extra-extra-extra-high-density (xxxhdpi)

That being said, the amount of different sizes Android uses seems a bit excessive for our purposes and is presumably intended for more changes than just scaling.

I'd propose our baseline (same as Android mdpi), 2 × (same as Android xhidpi)., and possibly 4 ×. But you're more than welcome to try to change my mind on the details.

We could also consider just rendering the SVG image, but that'd definitely require some performance investigation. Downscaling a simple raster image is fairly cheap; rendering an SVG not necessarily.

Even if we don't render SVGs directly in the program, rendering SVGs to raster images at build time instead of including them in the repo might still be a good idea.

I hope that about covers all I'd like to tackle at the same time as replacing the icons.

PS Don't worry, I don't expect you to look into all that, unless you want to of course. ;-)

**Comment by poire-z** [comment]
FWIW, crengine exports a [convertSVGtoPNG()](https://github.com/koreader/crengine/blob/cb3b2da13b70d8bea86ef70bf959703b02f58962/crengine/src/lvimg.cpp#L1792-L1843) to cre.cpp, which uses it to [convert svg contained in the epub to png](https://github.com/koreader/koreader-base/blob/6c480198b00ec7ae4e8af25216e8a12fcabda9e6/cre.cpp#L2921-L2937). Currently, it does not accept a target w/h, just a zoom factor.
Looks easy to add another wrapper to cre.cpp that accept some file data from frontend and return some png data, and see how nanosvg would deal with SVG icons - before making a standalone libkoreader-svg.so - or extending/duplicating that `convertSVGtoPNG()` to size it to a target w/h.

**Comment by Frenzie** [comment]
It could also be rendered with MuPDF quite easily. It's just the potential performance impact compared to a simple rasterized image that might be worth keeping an eye on. :-)

**Comment by poire-z** [comment]
Oh, good if MuPDF does it :)
Well, we could convert them once after a koreader update, save them as resources_generated/home_dpi167_g12ba45cf.png, reuse that if available, could be all wrapped in imagewidget.lua:
https://github.com/koreader/koreader/blob/dc8696bd346988e2e1cc9714c3fd70477d79dbf0/frontend/ui/widget/imagewidget.lua#L130-L135
