### ISSUE TITLE
On Android the fontsize of footnotes is the same as main text

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#5622]
* KOReader version: v2019.11
* Device: Android tablet

#### Issue
The fontsize used for footnotes is the same as that used for the main text. I thought this was controlled by fb2.css file as part of crengine, but maybe it is ignored on Android?

**Comment by Frenzie** [comment]
Because you say fb2.css I assume you mean in an FB2 file? I shouldn't think any behavior is different in Android; perhaps there could be some relevance to the resolution/DPI of the device?

Btw, in EPUB there's also support for footnotes now, in Document → Style tweaks → Miscellaneous. I put regular & smaller side by side here.

<img src=https://user-images.githubusercontent.com/202757/69323927-dee54480-0c47-11ea-939b-9a27a00737c7.png width=45%><img src=https://user-images.githubusercontent.com/202757/69323928-dee54480-0c47-11ea-89c0-3272f3461b6b.png width=45%>

On top of that, there's also Settings → Taps & gestures → Links → Show footnotes in popups. Here shown overlaid on in-page footnotes but of course that doesn't make any sense.

<img src=https://user-images.githubusercontent.com/202757/69324043-0e944c80-0c48-11ea-9f00-cb65dad1428d.png width=45%>

**Comment by tigran123** [comment]
Thank you, I tried those Style tweaks options, but they do not make the footnotes text smaller (in an fb2 file on Android).

**Comment by poire-z** [comment]
We haven't tailored these style tweaks for FB2, we only really cared about HTML based documents like EPUB. (I hope our improvement to HTML rendering haven't break FB2...)

But fb2.css should be used with FB2 documents (check that it is in `Styles>`), and it has:
`body[name="notes"] { font-size: 70%; }`
and quick testing on some fb2 book (fb2.zip actually) I have (I even don't know what it's about:), it seems to work:
<kbd>![image](https://user-images.githubusercontent.com/24273478/69435378-bb9dc080-0d3f-11ea-97f9-ff2322233bf2.png)</kbd>
and following the links to the footnote pages show them all in a smaller font size:
<kbd>![image](https://user-images.githubusercontent.com/24273478/69435514-facc1180-0d3f-11ea-8a22-6eab54364f0e.png)</kbd>

If you don't have `Styles> Auto` checked, may be you're using another css than fb2.css - or if your FB2 documents have another suffix, fb2.css might not be picked.

**Comment by tigran123** [comment]
@poire-z  Thank you. Yes, I did have "Styles Auto" checked and that was the cause of the problem. Unchecking it and selecting "fb2.css" option solved the problem, i.e. now the footnotes are correct size (smaller than the main text). Closing the issue.

**Comment by poire-z** [comment]
> I did have "Styles Auto" checked and that was the cause of the problem. Unchecking it and selecting "fb2.css"

But why Auto did not select fb2.css ?! Do your FB2 books have another extension than `.fb2` ?

**Comment by tigran123** [comment]
They do have the standard `fb2.zip` extension, of course.

**Comment by poire-z** [comment]
Mhh, strange. Auto picks up fb2.css with the single fb2.zip I have.

https://github.com/koreader/koreader/blob/4740ab1fdca2bfcf24e4d5b31a4e9062346da034/frontend/document/credocument.lua#L99-L116
https://github.com/koreader/koreader/blob/4740ab1fdca2bfcf24e4d5b31a4e9062346da034/frontend/document/credocument.lua#L37-L47
Care checking what `unzip -qql your.fb2.zip` says ?

**Comment by tigran123** [comment]
In my case Auto selects "HTML/EPUB (epub.css)" which has the wrong footnote fontsize,
Here is a sample output:

```
$ unzip -qql /Books/fb2/Fiction/Russian-Classics/Tolstoy/Polnoe-Sobranie-Sochinenij/01_tom.fb2.zip 
  6753611  2017-04-28 10:31   01_tom.fb2
$ unzip -qql /Books/fb2/Urantia/The-British-Study-Edition-of-the-Urantia-Papers.fb2.zip 
  7789766  2015-01-15 16:25   The-British-Study-Edition-of-the-Urantia-Papers.fb2
```
