### ISSUE TITLE
File browser displays items on new rows centred

### ISSUE THREAD

**Issue by dontcrash** [koreader/koreader#5634]
**Current behaviour:**

![Before](https://user-images.githubusercontent.com/32660358/69489868-f5510180-0ece-11ea-9845-4c824d37b4af.png)

**Desired behaviour:**

![After](https://user-images.githubusercontent.com/32660358/69489867-f5510180-0ece-11ea-91dd-289005cb2710.png)

This could possibly be a setting that users can change to get the desired result?

**Comment by poire-z** [comment]
I'd like to say the current behaviour is a design choice (why not have things balanced? I quite like it that way) - but it's not, and there's a little inconsistency: when there is only 1 or 2 items, it's aligned to the left - while if there are 4 or 5, or 7 or 8 items, it's centered as on the "current" screenshot.
Couldn't find out why last time I checked - but I'll probably have a look again when looking at UI mirroring for arabic.
(Probably not worth a setting.)

**Comment by NiLuJe** [comment]
@poire-z: Ah, okay, I'd never noticed the inconsistency ;).

**Comment by poire-z** [comment]
I assume your https://github.com/koreader/koreader/pull/5638#issuecomment-557912189 was targetted to this issue here :)

> I, err, kind of liked the center alignment ;'(.

(I too.)
I guess centering could be preferable in History, for those that have only a few items and use it as a kind of home page - and centering makes it nicer - while left alignment kinda makes more sense in File browser (go enter an empty directory and have that `../` in the middle - that feels strange :)

That's doable (just use a CenterContainer instead of the added LeftContainer).

**Comment by NiLuJe** [comment]
Yeah, they were posted in the order I opened 'em, which turned out to be unfortunate here, since I got to the explanation last ;).
