### ISSUE TITLE
Saving multiple style sets, instead of one default

### ISSUE THREAD

**Issue by melikyuksel** [koreader/koreader#5635]
Right now, you can change the font, margins, etc., as well as style tweaks, and set them as default. But sometimes you have a book series, or a type of text like fiction, for which the default styles don’t work out. Maybe you want a different set of font, font size, and line spacing settings for these.

It would be cool to be able to save these settings as separate packs, and quickly apply them to multiple files.

**Comment by Frenzie** [comment]
Actually that was added recently, see #5428.

**Comment by melikyuksel** [comment]
Hmm, that’s the “Tweak document settings” plugin? It seems to be pretty hacky and based on folders, instead of through menus. And you’d have to have to keep your files in separate folders to apply the same styles to them (ideally it would be through a menu option — “Apply style set” or the like).

**Comment by pazos** [comment]
> Hmm, that’s the “Tweak document settings” plugin? It seems to be pretty hacky, through direct text editing, and based on folders, instead of through menus, per file. And you’d have to have to keep your files in separate folders to apply the same styles to them.

Advanced settings are hackish as hell too. That doesn't mean that they're not useful for some people.

> Ideally, what I meant would be through a menu option in each file — “Apply style set” or the like, with perhaps a way to apply a style set from the file browser through the long press menu. To create/edit a style set, you’d simply change the settings through the menus (and through the usual custom user styles if you wish) and have a menu option to “Save as style set” and give it a name, so it can be used by other documents. No messing with .lua files. Not a plugin, but an integral part of how styles work.

Pull Requests welcome :smile:. Mockups welcome too :+1:

**Comment by NiLuJe** [comment]
See also #5079 ;).

**Comment by melikyuksel** [comment]
@NiLuJe That’s perfect, exactly what I was hoping for. Is that developed?

**Comment by NiLuJe** [comment]
It's an open PR marked "WIP", so, err, not entirely? ^^.

**Comment by melikyuksel** [comment]
That would make sense. 😄

**Comment by melyux** [comment]
That PR has unfortunately morphed into something else. I don’t quite understand the Profiles feature it implemented. I can’t set style tweaks using Profiles, or even the font as far as I can tell. Every style tweak should be available to the Profile to enable/disable. And you have to enable and re-enable the Profile on demand instead of setting it once per book and having it use that Profile whenever you open it.

**Comment by pazos** [comment]
Adding complex options leads to complex behaviours. These kind of things add cognitive load to my brain and affect my hability to perform a task (ie: read a book).

I use KO since the 2013/14? and most of the features added are awesome. But made the program somehow harder to use. In the end I found my workflow:

- Disable as plugins except the ones I use (that's all of them except cover browser, wallabag, calibre and gestures).
- Setup gestures as I want (just a few of them, to make my brain happy)
- Setup the **two** or **three** styletweaks that I want in all my books as **defaults**
- When reading a new book, if something is broken or looks bad **to me**, spend a litle time tweaking it to my like, and move on.

Changing fonts, margins, style tweaks, etc, shouldn't happen all the time within the lifespan of a book. If something like that happens then we reached the feature creep stage and we should consider stopping adding new features :/

**Comment by melyux** [comment]
That’s true and I agree. All I really wanted were style tweak “packs”. So we could create different combinations of style tweaks and apply them to books through the Style tweaks menu.

You can do this manually using “User tweaks” by writing your own CSS, but it’d be nice to do it through the UI.

**Comment by hius07** [comment]
We have Profiles.
