### ISSUE TITLE
Shadow init files for Android

### ISSUE THREAD

**Issue by belanger** [koreader/koreader#5646]
On some devices, such as kobo, some changes to koreader can be made by editing lua files (for example, menu fonts can be changed by editing frontend/ui/font.lua.  In Android, these files are not accessible.  It would be nice (but not important) if these files could be shadowed in the user's koreader directory, or perhaps overridden (such as how default.persistent.lua in the user's koreader directory can override some options).

**Comment by poire-z** [comment]
(But then, if your shadowed edited font.lua would be used instead of our shiped one, you would miss the changes we would have made to this file - and depending on our changes, koreader may even crash because of incompatibilities, stuff added and expected that it would not find in your old file. If you notice the crash, you'd go copy our latest file and make your change again - but you may not notice it and get strange end hard to pinpoint issues until you think that may be the cause of them.)

Anyway, for your specific case, I think there's already a possible solution:
https://github.com/koreader/koreader/blob/397211644de48eb87742152a74c8f112f0b9d1cf/reader.lua#L146-L154

So, one can add its own font map in a `fontmap.lua` file somewhere in the mode search path that could contain:
```lua
return {
        -- default font for menu contents
        cfont = "Toto-Regular.ttf",
        -- default font for title
        tfont = "Toto-Bold.ttf"
}
```
But on android, I don't know if there's a writable directory already included in the default module search path.
(Or may be, you can edit it as `koreader/frontend/fontmap.lua` with the TextEditor plugin :)

**Comment by poire-z** [comment]
But on Android, you can use the patch.lua facility, to either patch font.lua directly, or add some `/sdcard/koreader/mymodules/` to the search path, with bits from https://github.com/koreader/koreader/issues/4831#issuecomment-548245804
May be a patch.lua with a single line like
`package.path = "/sdcard/koreader/mymodules/?.lua;" .. package.path`
and your stuff in `/sdcard/koreader/mymodules/fontmap.lua` would just work.

**Comment by belanger** [comment]
Thanks; I didn't realize there was a mechanism in place like patch.lua.
I'll give it a shot, and appreciate your help.
