### ISSUE TITLE
Fuzzy search not working for lookup

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#5714]
* KOReader version:latest
* Device:kobo clara hd

#### Issue
I have installed many dictionaries. Fuzzy search works for all except one. Fuzzy search is already checked.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Could you please give slightly more info? Ideally which dictionary, but for starters what you're searching for and what you're expecting to find.

**Comment by abdrau26** [comment]
Here is a link for the dictionary
http://download.huzheng.org/misc/stardict-AbuBakar_EnglUrduDictionary-2.4.2.tar.bz2
For example when I search "explained", all dictionaries come up with definition of "explain". But the dictionary do not show definition although it contains "explain"

**Comment by Frenzie** [comment]
I suspect that upper case may not be considered in fuzzy search.

![Screenshot_2019-12-31_15-34-45](https://user-images.githubusercontent.com/202757/71624477-15b55f80-2be3-11ea-8edb-4732e3bdab3a.png)

**Comment by poire-z** [comment]
It works when this dict is used alone:
<kbd>![image](https://user-images.githubusercontent.com/24273478/71624575-8ceaf380-2be3-11ea-8cc6-07512a8b94a9.png)</kbd>

It's probably because you have other dicts that have a definition for the exact word "explained".
As an exact definition is found, there's no need to go fuzzy and find other fuzzy definitions in any dict (the one where the exact word was found, and others).

If you have some dicts that have many more words than others (like words in plural, or with 'ed suffix), and they prevent you from seeing fuzzy results from other dicts (with less words, but may be more interesting text), you can create a secondary directory named "dict_ext" alongside the "dict" one you have your dicts in, and move these "huge" dictionaries in that dict_ext.
From one of my first contrubutions here (already 3 years...) #2393:
> stardict : do a 2nd query using dicts in data/dict_ext/ (if it exists) : I put in dict_ext/ the "English Wiktionary, Western languages" dict, which has definitions for mostly any declination of a word in all western languages. If I put it in dict/, it finds an exact definition that my other french dicts don't have, and masks the sometimes valuable french definition I would have had with fuzzy searches if that Wiktionary wasn't there. With that 2nd lookup, i get both.

**Comment by abdrau26** [comment]
@poire-z 
Thank you. It is working..
