### ISSUE TITLE
FR: Screensaver option for e-Ink android devices

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#5732]
* KOReader version: 2019.12
* Device: Tolino Epos 2

#### Issue
Is it possible to implement the screensaver option for e-Ink android reader?

**Comment by pazos** [comment]
Nope

**Comment by elvvis** [comment]
@pazos:
Why is that not possible?
I suppose on Android 4.4 the wallpaper is located at: 
/data/system/users/0/wallpaper 
Replace the 0 with the user id (take a look in /data/system/users).

By the way, the tolino reading app can save the book cover as screensaver.
Can't you introduce a whitelist for android devices that support this?

**Comment by pazos** [comment]
> Why is that not possible?

Because on android KOReader is just another application and applications do not mess with low-level system stuff like lockscreens and power routines. They normally can't unless the device is rooted.

> I suppose on Android 4.4 the wallpaper is located at:
/data/system/users/0/wallpaper
Replace the 0 with the user id (take a look in /data/system/users).

That's a specific configuration on a specific device. /data is not accesible on non rooted devices

> By the way, the tolino reading app can save the book cover as screensaver.
Can't you introduce a whitelist for android devices that support this?

No, I can't. I don't have any android e-ink device. I do help with development using emulators and a tablet. I'm willing to put effort to help users to add support for e-ink refreshes and other things, but I cannot do it myself.

You probably can hack a way to display a screensaver that works for your Tolino, but that's up to you, as a contributor. I wouldn't bother with that issue but I'm not you :smile:

**Comment by elvvis** [comment]
@pazos Ok, thank you for your answer. I'll take a look at the code, maybe there is a way.

**Comment by pazos** [comment]
@elvvis: you are welcome. 

I would suggest to work on a barebones app implementation that just displays a image from a file when the power button is pressed (and clear that image when the device is resumed if the system doesn't do that for you). 

If you manage to do that (i.e overwritting the image that tolino fw uses as a screensaver) from an app we can port it to https://github.com/koreader/android-luajit-launcher and tweak the screensaver to work on supported android devices.

**Comment by pazos** [comment]
@elvvis: see https://www.mobileread.com/forums/showthread.php?t=332401 for a workaround

**Comment by krammarkro** [comment]
> [@elvvis](https://github.com/elvvis): you are welcome.
> 
> I would suggest to work on a barebones app implementation that just displays a image from a file when the power button is pressed (and clear that image when the device is resumed if the system doesn't do that for you).
> 
I saw some transparent screensaver for koreader and I would really like to see something like that for Tolino. Can the app be a system app or does it need to be an normal app like koreader. 
Would it be possible to ship out the feature in the normal Build and check for root privilege or make another Build?

**Comment by pazos** [comment]
You're commenting on a very old ticket.

Since then a new plugin emerged: https://github.com/koreader/koreader/wiki/Coverimage

> I saw some transparent screensaver for koreader and I would really like to see something like that for Tolino

I'm not really sure if transparency is supported. If it isn't currently (using coverimage) it won't be possible. After all we just write an image. It is a duty of the firmware to draw the image on the surface.

> Would it be possible to ship out the feature in the normal Build and check for root privilege or make another Build?

Not at all. See above.
