### ISSUE TITLE
Pdb to stardict format

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#5733]
I have a ".pdb" file. Can i convert it into stardict format so that I may use it in  koreader. (Kobo clara hd)?

**Comment by Frenzie** [comment]
Are you asking how you can do that? (I don't know, but if you can turn it into the Stardict format, it should work.)

**Comment by abdrau26** [comment]
Yes i am asking for how to convert it into stardict format.

**Comment by poire-z** [comment]
No idea - and did not find any answer with a quick google search.
https://github.com/pettarin/penelope does not seem to support PDB.

**Comment by KenMaltby** [comment]
I would guess that a dictionary .pdb file would be a database file, are there internal files that you can repackage?

Luck;
Ken

**Comment by abdrau26** [comment]
I don't know what is meant by internal files and repackage. @KenMaltby

**Comment by NiLuJe** [comment]
He meant what does the raw markup looks like (assuming that stuff works roughly like a PRC).

**Comment by KenMaltby** [comment]
That's right.  It could also be an Oracle "Plugable Database".

**Comment by abdrau26** [comment]
I have shared the link of pdb file which I want to convert.
https://drive.google.com/file/d/1DGAGU6nABF697yuiSod0TdElr8YMCavZ/view?usp=drivesdk

**Comment by Frenzie** [comment]
The program "Palm DB-Editor" claims to be able to export to Excel/CSV.
http://www.mobyware.org/palm-os/db-editor-download-958.html

In turn this one says it can do CSV → StarDict
https://github.com/pettarin/penelope

I'll close this now because it doesn't seem like anyone here will be able to do better than my own couple minute search engine use. It's not that we don't want to help, but we don't know more than you do about the subject, and you'd stand a better chance of success elsewhere (MobileRead, perhaps).

**Comment by NiLuJe** [comment]
https://github.com/ilius/pyglossary can also handle the final step ;).
