### ISSUE TITLE
Screensaver message isn't used when no book is open

### ISSUE THREAD

**Issue by RenaKunisaki** [koreader/koreader#5741]
* KOReader version: 2019.12
* Device: Kobo Touch model N905C

#### Issue
Regardless of what message is set for the screensaver, the default "Sleeping" text appears instead.

#### Steps to reproduce
1. Change screen saver setting to "Use message as screen saver"
2. Change screen saver message to something other than default
3. Activate screen saver

**Comment by RenaKunisaki** [comment]
Specifically this happens when you don't have any book open. It looks like `Screensaver:expandSpecial` uses the fallback message in that case, which is always the default, since a custom message's variables wouldn't apply here.

Perhaps a solution is to allow setting the fallback message when no book is open.

**Comment by poire-z** [comment]
Or may be, to avoid another message menu item ("alt message when you use escape sequences but there is no book to use them on" :):
https://github.com/koreader/koreader/blob/0599c440cc934c1dceb5a2fed4aebb02bf01823e/frontend/ui/screensaver.lua#L411-L430
check in the `else` if there is any `%` in `ret` / `message` , and if none, use it instead of `fallback` - if there are, use `fallback` (better I guess than replacing the `%zzz` with `n/a`).

**Comment by RenaKunisaki** [comment]
That might not work if you have a literal `%` (I assume `%%` will work?) though I don't know how big a deal it is. I figured it doesn't need to be in the menu at all, just the config file.

**Comment by poire-z** [comment]
Then just look for any of `%%c` `%%t` `%%p` `%%T`. If any, use `fallback` - if none use `message`,

> I figured it doesn't need to be in the menu at all, just the config file.

You came up with that issue, others may - so let's solve it with the above trick - instead of having to document a hidden setting.
The use case we then don't address is people having a message with these escape codes, and wanting another message than the fallback if no book is opened - which I assumed is not your case and you have a message without any escape code.

**Comment by poire-z** [comment]
Might have been fixed/workarounded in #7113. Re-open if not.
