### ISSUE TITLE
Unreliable Gyro on Kobo Libra H2O

### ISSUE THREAD

**Issue by Dinth** [koreader/koreader#5767]
* KOReader version: 2019.12
* Device: Kobo Libra H2O 

#### Issue

Gyro works unreliable on Kobo Libra H2O. Its great to have automatic screen rotation, but rotating the reader slightly (like 5 degress) while reading in portrait makes screen rotate to landscape, but it takes a couple of 90 deg rotations for it to rotate back

**Comment by NiLuJe** [comment]
There's nothing much we can do (without an insane amount of efforts). We get the orientation swap even from the ntx driver. The tilt angle can be tweaked from Nickel's own developer settings (with more or less success, apparently).

The raw gyro events *are* available, but, hahahahahaha, not gonna touch that with a ten-foot pole ;).

FWIW, I don't have any particular issues with my own Forma. Then again, I very rarely depend on the gyro ;).

losing this because it's literally not our bug ;).
