### ISSUE TITLE
When you're not so close to WiFi ..

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#5787]
* KOReader version: 2019-12-27
* Device: Android (inkbook)

#### Issue

When you're not sitting next to wifi,  using online koreader functions can be very painfull:

https://youtu.be/mV6LyCLQtm8

often you have to click many times 
menu -> wallabag/newsdownloadr/send2ebook -> "retrievie articles from server" -> "turn on wifi" 
(and again, on example video this path was repeated around 7-8 , each 4 clicks, as above, gives 32 clicks) unit it really captures internet, and starts processing. That's horrible!

Year or 2 back I remember I did at least for newsDownloader or send2ebook callback function for enabling wifi that waited until it's connected (or terminates after 30sek) and then automaticly starts processing eg wallabag articles. 

But it seems it's not there anymore or is broken ? 
how about restoring that function and implementing it every where were you need to use "enable wifi" function ?

#### Steps to reproduce
described in issue

**Comment by pazos** [comment]
Hi @mwoz123: good to see you here again :grinning: 

I think I didn't touch the code of android.isWifiEnabled() and android.setWifiEnabled(). Anyways, these just toggle android system settings. android.isWifiEnabled() will return true if there's assoc with the ap. android.setWifiEnabled(bool) just allows/avoids connections to known ap's in the background. It should take a few seconds only unless you're outside the wifi range,

> Year or 2 back I remember I did at least for newsDownloader or send2ebook callback function for enabling wifi that waited until it's connected (or terminates after 30sek) and then automaticly starts processing eg wallabag articles.

I don't remember that. But could be :)


> But it seems it's not there anymore or is broken ?
how about restoring that function and implementing it every where were you need to use "enable wifi" function ?

Sure, please make it optional.

**Comment by Frenzie** [comment]
Is it the same install with the same settings? Otherwise you might just need to enable it.

**Comment by pazos** [comment]
I found the PR: https://github.com/koreader/koreader/pull/3482

**Comment by mwoz123** [comment]
@pazos thanks:)

Guy's please explain to me, cause I can't think of any use case when some clicks thought menu, selects one of online plug-ins and finally on "download something from internet " (wallabag/news downloader/send2ebook or any other network koreader plugin) 
and only would like to see the popup with question about turning on wifi, and turn it on, without any further actions? 
This means as he wanted to use internet function clicking again at least once same path (if he's lucky enough to get the connection in that time -> see my video)? 

It doesn't make sense for me, but maybe I overlooked a huge valid use case, that's obvious for you guys?

**Comment by NiLuJe** [comment]
Because turning on the radio is a *massive* battery drain, which is a concern on eInk readers.

Which means enabling WiFi silently would be... iffy. That's not even taking into account people that would burn you at the stake for even proposing to essentially turn on WiFi behind the user's back ;).

Also, we currently can't do that without quitting the menu and/or remember where we were in the menu, which indeed incurs quite a few taps to get back to where you were ;).

**Comment by mwoz123** [comment]
Ok why not then do the callback action once user confirm he wants to enable Wi-Fi?

Currently, after enabling wifi, user has to guess (e.g. in koreader file browser mode there's no wifi indicator) when he's online, which might not be easy->again see my video:p, and click manually again (once connected) same path?

**Comment by NiLuJe** [comment]
Because we can't (AFAIK) ^^. And because we'd have to, somehow, block until we have working network connectivity anyway ;).^

----

The lack of network indicator is tied to the same issue: no cheap, asynchronous way to be sure we're connected and/or have WiFi on on some platforms.

(Although, granted, that's a moot point for the FM, since no platforms currently adds an indicator there ;)).

**Comment by Frenzie** [comment]
Those menu actions could be rewritten slightly so as not to close in case of the "enable wifi" dialog.

@mwoz123 The default is pretty good for the likes of Kindle & Kobo; perhaps less on Android but at the same time on Android it's more of a system matter anyway. Your video's pretty weird to me tbh; I'm not entirely sure what else you expect to see if the device fails to connect, and it's also quite surprising that in the end it somehow succeeds. ;-)

**Comment by pazos** [comment]
The video:

- starts with wifi turned off [WIFI_STATE_DISABLED](https://developer.android.com/reference/android/net/wifi/WifiManager.html#WIFI_STATE_DISABLED)
- turns on the wifi for the first time[WIFI_STATE_ENABLING](https://developer.android.com/reference/android/net/wifi/WifiManager.html#WIFI_STATE_ENABLING)
- at the end of the video WIFI_STATE_ENABLING returns sucesfully and the system changes to [WIFI_STATE_ENABLED](https://developer.android.com/reference/android/net/wifi/WifiManager.html#WIFI_STATE_ENABLED)

Just the first call to android.setWifiEnabled(true) does something. The rest are being skipped because the wifi manager is already enabled.

Maybe showing a (skippable) toast each time we change network state can fix the repeat-until-work problem?

**Comment by Frenzie** [comment]
Yup, it should show some feedback. Especially when it successfully connects; enabling is less important because you just clicked that button after all.

I didn't mean to imply anything other than described above, just that I'm surprised the Wallabag sync worked in the end. The fact that it took more than 5-10 seconds means the connection is extremely bad and I'm just surprised actually communicating with the server back and forth seems to succeed at all.

**Comment by mwoz123** [comment]
I'd say it's minority when I'm able to get the connection right away. Often I've to repeat at least twice (from my bed/desk ~15m from router).

How about replacing this "turn on wifi" function with 
[NetworkMgr:turnOnWifiAndWaitForConnection ](https://github.com/koreader/koreader/pull/3482/files#diff-8a665adb55900a011d1c3928d7447e61R64)
and debate about timeout ? + Add UI to change default timeout setting. 

Proposed timeout settings:
- 0 seconds - no timeout - works as now, so first click "download whatever" -> and "turn on wifi" only enables Wifi (IMHO doesn't make sense, but I proposed it to keep with sync with current solution), & user have to click again "download .." to do real download once (he knows somehow he's) connected
- 5 sec - after "download whatever" & "turn on wifi" waits 5 seconds for internet connection if none then abort.
- 10sec - as above but for 10 sec
- 15 sec  as above but for 15 sec
- 30 sec

I propse 5 or 10 seconds as default timeout. What you think?

**Comment by pazos** [comment]
@mwoz123: if `turnOnWifiAndWaitForConnection` blocks for more than 5 seconds and the user touches the screen we get an ANR.

I understand your logic: if no wifi then block until timeout and do action. Sadly it won't change the output you see.

Plus: wifi state broadcast receiver and the permission to toggle wifi state were both deprecated. Since we're not using any advanced wifiManager thingies we can just remove the networkManager implementation and just forward the user to the WiFi settings, where status happens in realtime.

FWIW, I don't have any problems with current wifi implementation. It works fine on my tablets and on two e-ink devices i tested. But if I were to change a single thing of it, I would deprecate it, remove the [relevant permissions from the manifest](https://github.com/koreader/android-luajit-launcher/blob/master/app/manifest/base.xml#L7-L8) and just send the user to android settings.

I tuned a couple of friend's ebooks for doing that instead of using the NetworkManager at all, but I guess it can fail on some e-ink devices.

Does the command `adb shell am start -n com.android.settings/com.android.settings.wifi.WifiSettings` open the wifi settings on your device?.

**Comment by Frenzie** [comment]
I'm with @pazos, as I somewhat implied when I wrote "it's more of a system matter anyway."

**Comment by mwoz123** [comment]
> @mwoz123: if turnOnWifiAndWaitForConnection blocks for more than 5 seconds and the user touches the screen we get an ANR.

Could we go for threads then? 
Did a quick research and found looking fine library:
https://github.com/torch/threads/blob/master/README.md

All downloading functions could be run in background. 

It there a chance to use it?

**Comment by pazos** [comment]
> > @mwoz123: if turnOnWifiAndWaitForConnection blocks for more than 5 seconds and the user touches the screen we get an ANR.
> 
> Could we go for threads then?
> Did a quick research and found looking fine library:
> https://github.com/torch/threads/blob/master/README.md
> 
> All downloading functions could be run in background.
> 
> It there a chance to use it?

No without fixing the issue described in https://github.com/koreader/koreader/issues/2113#issuecomment-517858265 first.

My suggestion is:

![wifi](https://user-images.githubusercontent.com/975883/73363124-64b8e800-42a8-11ea-972f-4d785cb0582d.gif)


Give it a try to this apk: https://www.dropbox.com/s/tldxrgh459v9rpn/koreader-android-arm-noWifiPerm.apk?dl=0. If you want to see the sources first I will need a few days to clean up the mess because right now that branch includes a bunch of mimas QoL patches unrelated to that specific issue.

**Comment by pazos** [comment]
Another good thing of the ConnectivityManager vs WifiManager is that allows us to determine if the active network is wifi or mobile.

**Comment by pazos** [comment]
@mwoz123 @Cellaris: could you test the apk linked above and see if it launches android wifi settings fine?

It certanly works on Likebook devices but I want to test how it behaves on 4.0.3 - 4.2 devices before merging.

Thanks!

**Comment by Cellaris** [comment]
On the Inkbook Prime HD (Android 4.2.2) it works fine. It opens the system's Wi-Fi settings.

**Comment by mwoz123** [comment]
Sorry for late replay: I do confirm - opens system WiFi settings, koreader top menu is not closed.
