### ISSUE TITLE
pdf continuous view mode doesn't cover all the screen space (tall aspect ratio)

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#5876]
* KOReader version: v2020.02
* Device: hisense a5

#### Issue
When reading pdf in my Hisense a5 with continuous view mode. There is always a big blank space at the bottom. No matter how I adjust the configuration. It can't show any content at the bottom. I have photographed some photos. 
![4030e0c6a7efce1b6b83e6b4b851f3deb58f6500](https://user-images.githubusercontent.com/46492291/74723596-d1a31a80-5275-11ea-86ed-6111dcdc0070.jpg)
![715411d6277f9e2f879133760830e924b999f30c](https://user-images.githubusercontent.com/46492291/74723664-f26b7000-5275-11ea-968c-b449f52d0af9.jpg)
![3502711190ef76c6537ad5558a16fdfaae516700](https://user-images.githubusercontent.com/46492291/74723764-116a0200-5276-11ea-83c5-a7ea530e4960.jpg)

#### Steps to reproduce
1. Open a pdf file in koreader with my Hisense a5
2. Change the view mode to continuous
3. There will be a big blank space at the bottom

**Comment by Frenzie** [comment]
Likely an Android-specific issue, possibly related to https://github.com/koreader/koreader-base/pull/1029 for example.

**Comment by kingo132** [comment]
I tested this in the latest version V2020.02. The problem still exists.

**Comment by pazos** [comment]
@Frenzie: is not android specific. I can reproduce on cervantes and the emulator. But it isn't very noticeable on 4:3 devices.

Here is a screenshot of the emulator, started with `./kodev run --screen-width=600 --screen-height=1800 --screen-dpi=300`

![aaa](https://user-images.githubusercontent.com/975883/74736402-e8844580-5252-11ea-83a3-17ed04ec3fd6.png)

Affects continuos mode **without reflow**. Both page mode and continuous mode with reflow are not affected.

**Comment by Frenzie** [comment]
It looks like it's a somewhat recent regression. It doesn't seem to occur in v2019.02 or v2019.08.

**Comment by NiLuJe** [comment]
Possibly related to the status bar + PDF deadzone tweaks?

**Comment by yparitcher** [comment]
regression caused by #5657 b578d8aa8b403f738f601695e7f92e15aac795e1
I will look into this

**Comment by yparitcher** [comment]
caused by 
https://github.com/koreader/koreader/blob/611c423727bcc76b0211a42286e5cc0c4572b57b/frontend/apps/reader/modules/readerview.lua#L578-L579

This sets the visible_area to be limited to the page size even when the screen is taller or wider than 1 page.

when i comment it out it works fine.
This line is there from the beginning, does anyone know why? and is it needed?

**Comment by NiLuJe** [comment]
@yparitcher: Could it be related to the page overlap feature (i.e.,ti figure out which parts should be dimmed?).

**Comment by yparitcher** [comment]
not that i can tell (comenting it does not have an effect on the overlap)

**Comment by Frenzie** [comment]
Did you check if there are any weird results in paged mode if you get rid of it?

**Comment by yparitcher** [comment]
> Did you check if there are any weird results in paged mode if you get rid of it?

none as far as i can tell, but i didn't try every combination of options

**Comment by Frenzie** [comment]
It looks to me like it's a piece of code that assumes we're always in paged mode (i.e., visible_area <= page_area), possibly because continuous didn't exist when it was written, in which case having a visible area larger than the page area might potentially result in some kind of undefined behavior if the page is smaller than the screen. But if there are no adverse effects (includes the unit tests of course) I propose we stick it in for wider testing.

**Comment by NiLuJe** [comment]
What @Frenzie said, although I'd ideally like to have a better understanding of what all those various rectangles correspond to first ;).

(But what's indisputable is that this doesn't make sense if current view != paged).

**Comment by NiLuJe** [comment]
I'm also slightly unclear on what's happening here vs. what readerpaging/readerrolling are also doing on that front.

**Comment by Frenzie** [comment]
Well, it does have a comment. :-P

https://github.com/koreader/koreader/blob/611c423727bcc76b0211a42286e5cc0c4572b57b/frontend/apps/reader/modules/readerview.lua#L552-L555

**Comment by yparitcher** [comment]
https://github.com/koreader/koreader/blob/611c423727bcc76b0211a42286e5cc0c4572b57b/spec/unit/readerview_spec.lua#L50
and the next one fail due to explicitly setting visible area **w=566**
https://github.com/koreader/koreader/blob/611c423727bcc76b0211a42286e5cc0c4572b57b/spec/unit/readerview_spec.lua#L74-L78

https://github.com/koreader/koreader/blob/611c423727bcc76b0211a42286e5cc0c4572b57b/spec/unit/readerlink_spec.lua#L38
and its derivatives fail due to 
https://github.com/koreader/koreader/blob/611c423727bcc76b0211a42286e5cc0c4572b57b/frontend/apps/reader/modules/readerview.lua#L596-L598
now being false so the offset stays 0 instead of 22 so the touchpress for the link is off.

**Comment by Frenzie** [comment]
And git blame on that gives us https://github.com/koreader/koreader/commit/e98a89f8d57bf290330e23511d5d8c0cfde56294

**Comment by yparitcher** [comment]
these are expexted failures though

**Comment by Frenzie** [comment]
Sure, of course I don't mean the unit tests literally, just like links across page boundaries still working and such. :-)

**Comment by yparitcher** [comment]
> And git blame on that gives us [e98a89f](https://github.com/koreader/koreader/commit/e98a89f8d57bf290330e23511d5d8c0cfde56294) (but the line itself dates back further)

as i said before the line is from the first implementation  f685f68852bcc3493c902edc6d3615295529504e

**Comment by yparitcher** [comment]
Should I open a pr?

**Comment by Frenzie** [comment]
Please do!

**Comment by Frenzie** [comment]
PS Here's an excerpt from `git log --all --grep='scroll mode'` that shows scroll mode didn't exist when this code was written, which supports my hypothesis.

```
commit 75b1096a653ffbba5d3393258911015b359dd070
Merge: 660438ec 1c9388cd
Author: {Qingping,Dave} Hou <dave2008713@gmail.com>
Date:   Sun Apr 14 07:40:24 2013 -0700

    Merge pull request #65 from chrox/pan_scroll
    
    add panning of page in scroll mode

commit d24131b13bd2343652942514ad874d7415b77277
Author: chrox <chrox.huang@gmail.com>
Date:   Sun Apr 14 17:39:12 2013 +0800

    add panning of page in scroll mode

commit ce8eb15dd8c075ed1f09385abf92fac74ae3d844
Merge: 91b73ba7 418ba943
Author: {Qingping,Dave} Hou <dave2008713@gmail.com>
Date:   Sun Mar 10 21:44:19 2013 -0700

    Merge pull request #781 from chrox/pdf_scroll_mode
    
    add scroll mode for pdf/djvu reader

commit 63e5e7e577a0fb18b27f0b50400e38ef650b3a71
Author: chrox <chrox.huang@gmail.com>
Date:   Sun Mar 10 14:23:26 2013 +0800

    add scroll mode for pdf/djvu reader
```
