### ISSUE TITLE
On waking up, the previous book is opened

### ISSUE THREAD

**Issue by cwittern** [koreader/koreader#5877]
* KOReader version: Jan 2020
* Device: Boyue Likebook Ares

#### Issue
When the device is coming back from sleep, KOReader proceeds to open the book that was read before the current one
#### Steps to reproduce
1. Close cover or set device to sleep, sleep screen is shown
2. Open cover
3. The sleep screen gets replaced, the current book is on the screen.  Then KOReader proceeds to load the book that was read previously.  
##### `crash.log` (if applicable)

There is no crash, so I am not including the crash.log

**Comment by pazos** [comment]
Wait, I can reproduce it on a tablet. Somewhat related to open content uris. Latest uri gets replayed. Probably we need to set the newIntent to null in onPause().

To reproduce the error:

1. start a book from a file manager that sends a content schemed uri
2. with the app in the foreground press the power button to suspend the device
3. almost inmediatly (because showing the lockscreen in the middle would make the bug irreproducible) press the button again to wake up the device.
4. intent gets replayed, so it will try to open the last book opened from outside KO.

**Comment by pazos** [comment]
I guess it will affect e-ink readers mostly, where lockscreens aren't a thing. But phones and tablets that have some delay before showing the lockscreen will be affected too.

**Comment by Frenzie** [comment]
Duplicate of #5877
