### ISSUE TITLE
pdf shrink to a small size when I set Dewatermark on

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#5878]
* KOReader version: v2020.02
* Device: Hisense A5

#### Issue
When I'm viewing pdf on my Hisense A5, I set Dewatermark option on. The page will shrink to a small size, approximately half of the screen size. And the shrunk page automatically aligned to the left top corner. I photographed 2 photos. Hope you can understand what I mean.
![IMG_4184](https://user-images.githubusercontent.com/46492291/74723409-7a9d4580-5275-11ea-8ebc-265bc228d305.jpeg)
![IMG_4183](https://user-images.githubusercontent.com/46492291/74723440-87219e00-5275-11ea-9d91-dfec9743297a.jpeg)

#### Steps to reproduce
1. Open a pdf in koreader in Hisense A5
2. Turn on Dewatermark.
3. You will see the page shrink to the left top corner.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
I can't seem to reproduce the issue, but the option itself basically just treats light pixels as white so that they don't affect reflow in pages that are poorly scanned or contain watermarks. I wouldn't generally recommend turning it on because generally the best case scenario is that it wastes processing power.

It would be good to figure out how to trigger this issue though.

**Comment by yparitcher** [comment]
I get this in the emulator when viewing page 3 of the `paper.pdf` int the test submodule. With **page view** and **zoom to fit page width** even **without** dewatermark.
at regular 600x800

however the same pdf does not trigger on my KT4

can anyone else reproduce?

![Reader_2020-Feb-19_140124](https://user-images.githubusercontent.com/38916402/74866724-5008c680-5321-11ea-9cb3-497ae9232d16.png)

**Comment by yparitcher** [comment]
* with every third page, not just page 3

**Comment by yparitcher** [comment]
The problem went away when I deleted my cache, did something recent change the cache?

**Comment by poire-z** [comment]
> did something recent change the cache?

Not that I know of. But maybe that's a hint ! :)
It's quite possible it's reusing a previously rendered (in some other conditions) bitmap.
Rendered bitmaps get cached with a hash, consisting of a concatenation of various rendering properties (w, h, zoom, ...) see with `grep 'hash =' frontend/document/koptinterface.lua`
so it's possible we just forgot to include one property in it in some case, and so there's some kind of collision

**Comment by Frenzie** [comment]
Not recently, unless by recent you mean many months ago, but what @poire-z says is definitely a plausible scenario.

**Comment by yparitcher** [comment]
does it make sense that when i dynamically resized the emulator the cache got messed up?

**Comment by poire-z** [comment]
Well, the emulator resizing was added as a proof of concept, and I guess not much stuff has been tested/updated to see how they behave after a resize (I know about [some issue](https://github.com/koreader/koreader/issues/4752#issuecomment-573119439) when resizing change the w/h ratio from being portrait to landscape).
So, it probably does not make sense if the cache is messed up, but it's understandable if it is :)

**Comment by Frenzie** [comment]
I thought that was all covered by various w/h inclusions in the cache and I actually do it a fair bit these days. (But of course going back is probably less frequent than going forward.) I've been using the KOReader Debian package as my default PDF viewer because I've come across various PDFs on OAPEN that just don't work right in Evince.

This one for example: 

Egberts, Linde (ed.); Schroor, Meindert (ed.). *Waddenland Outstanding: History, Landscape and Cultural Heritage of the Wadden Sea Region* (2018). Amsterdam University Press, Amsterdam. <http://www.oapen.org/search?identifier=1005811>.

**Comment by kingo132** [comment]
> The problem went away when I deleted my cache, did something recent change the cache?

I tried to clear the cache, but the problem still exists.

**Comment by kingo132** [comment]
> I thought that was all covered by various w/h inclusions in the cache and I actually do it a fair bit these days. (But of course going back is probably less frequent than going forward.) I've been using the KOReader Debian package as my default PDF viewer because I've come across various PDFs on OAPEN that just don't work right in Evince.
> 
> This one for example:
> 
> Egberts, Linde (ed.); Schroor, Meindert (ed.). _Waddenland Outstanding: History, Landscape and Cultural Heritage of the Wadden Sea Region_ (2018). Amsterdam University Press, Amsterdam. http://www.oapen.org/search?identifier=1005811.

I tested this pdf, it still shrinks to a small size when the dewartermark option is on. And I'm testing using the newest version 202003.

**Comment by Frenzie** [comment]
Odd, I still can't reproduce. (Btw, are you still using your old cache?) But I was only saying that Evince, or perhaps rather Poppler, has trouble with a surprisingly large amounts of PDFs from OAPEN, which is why I've been resizing things in KOReader plenty. Compare,

![Screenshot_2020-03-11_17-11-42](https://user-images.githubusercontent.com/202757/76438587-75866e80-63bb-11ea-803e-ade8ed9dae98.png)

<img src=https://user-images.githubusercontent.com/202757/76438685-9cdd3b80-63bb-11ea-9a4b-dfab02276a4c.png width=45%><img src=https://user-images.githubusercontent.com/202757/76438689-9d75d200-63bb-11ea-9be9-38efcdc0c259.png width=45%>
