### ISSUE TITLE
File browser with metadata does not handle epub3 series information

### ISSUE THREAD

**Issue by Aszarsha** [koreader/koreader#5892]
* KOReader version: 2020.02
* Device: Kobo Libra H2O

#### Issue
-with-metadata file browser seems to fumble with epub3 series information.

In epub3, it seems that series information are stored as opf:meta flags and properties as follows (per Calibre metadata updating at least):
```
    <opf:meta property="belongs-to-collection" id="id-42">foobar</opf:meta>
    <opf:meta refines="#id-42" property="collection-type">series</opf:meta>
    <opf:meta refines="#id-42" property="group-position">quux</opf:meta>
```

#### Steps to reproduce
Upload an epub3 with series meta from Calibre (with "Send to device") and observe that the series information is not recognized (or at least displayed) in the -with-metadata file browser.

**Comment by Frenzie** [comment]
Cf. #4915. Pinging @poire-z; any interest?

**Comment by NiLuJe** [comment]
Actual spec: https://www.w3.org/publishing/epub3/epub-packages.html#sec-belongs-to-collection

**Comment by poire-z** [comment]
The sample tags above seem to match what some code added in that "thornyreader" fork is handling, and that I cut & pasted in https://github.com/koreader/crengine/issues/267#issuecomment-557507150 :)
So, might be as easy at re-reading it and pasting it at the right place in epubfmt.cpp.
Some sample epubs with variations of these tags could help (as I don't play much with calibre).

**Comment by Aszarsha** [comment]
> Cf. #4915. Pinging @poire-z; any interest?

It really seems to me that this issue have nothing to do with TOC and navigation as per #4915.

Here is a screenshot. Note that Scythe, Thunderhead and The Toll are all in the Arc of Scythe series; however, The Toll is in epub3 format and the other two are in epub2. At the bottom, the three Jemisin books are part of the (correctly specified inside the .opf) Broken Earth series, but are all epub3 and the series information does not appear.
![FileManager_2020-Feb-22_175603](https://user-images.githubusercontent.com/632292/75096194-6622bb00-559d-11ea-8947-521e5c060c77.png)

**Comment by NiLuJe** [comment]
Note that we don't actually purport to support ePub 3 at all, so, while that's an obviously visible issue, I wouldn't necessarily rely on ePub 3 behaving as they ought to in general ;).

**Comment by NiLuJe** [comment]
@poire-z: See the spec. It's fairly readable for once ;p.

Compared to the code you quoted, collection-type might be `series` OR `set`.

As for `group-position`, the example given in the OP is out of spec, it only supports unsigned integers or a series of unsigned decimals (i.e., 4 or 4.5.6.7, not IV).

**Comment by Aszarsha** [comment]
> Note that we don't actually claim to support ePub 3 at all, so, while that's an obviously visible issue, I wouldn't necessarily rely on ePub 3 behaving as they ought to in general ;).

Sure thing, I just though that a bug report would be better than a stealthy "feature"! ;-)

**Comment by Frenzie** [comment]
> It really seems to me that this issue have nothing to do with TOC and navigation as per #4915.

It's about handling EPUB3 metadata. Note that "cf." means "compare," not something like "duplicate."

**Comment by NiLuJe** [comment]
@poire-z: I'm also mildly confused as to why their code is split in two, mainly because I don't get what the first loop in the first branch is achieving, exactly ^^. (I suck at XPath ^^).

**Comment by poire-z** [comment]
> See the spec. It's fairly readable for once ;p.

You do find that readable ?! :)
Well, I don't, and I'm not gonna digest it :)

> I'm also mildly confused as to why their code is split in two, mainly because I don't get what the first loop in the first branch is achieving

(Well, from what I've seen of their code, it's often nor perfect, or quickly made to solve some issue or specific case, so don't assume this sample is right :)

May be authors can define multiple titles, give them ids, and later have series/content that "refines" a #id title, so the code then go grab that title from the list of titles, by id.

If that makes a little sense to you, and you have some sample epubs, feel free to have a go at it... (because just skimming that spec, I'm not motivated :)
Anyway, thornyreader sample code might be insterted just before https://github.com/koreader/crengine/blob/76a2f162860c2c059f946b69728931611ea73c12/crengine/src/epubfmt.cpp#L881 (they had actually refactored all that quite a bit, and this and our common `calibre:series` stuff ended up in a `GetEpubMetadata()` function).

> I suck at XPath

Well, there's not much. These loops:
```c
        for (int i = 1; i < 20; i++)
        {
            lString16 xpath = lString16("package/metadata/meta[") << fmt::decimal(i) << "]";
            ldomNode *item = dom->nodeFromXPath(xpath);
            if (!item)
            {
                break;
            }
            lString16 property = item->getAttributeValue("property");
            lString16 content = item->getText().trim();
```
are just there to access up to 20:
```
<package>
 <metadata>
   <meta property="some-property">some content</meta> <!-- up to 20 of that -->
   <meta>...</meta>
   <meta>...</meta>
   <meta>...</meta>
   <meta>...</meta> 
 </metadata>
</package>
```
(whatever the namespace might be, `<opf:meta>` or `<bla:meta>`)

**Comment by Frenzie** [comment]
I prefer the CSS spec. :-P

**Comment by NiLuJe** [comment]
@poire-z: I was specifically puzzled about what the hell title has to do with any of this, but that's probably because I actually have no idea how an OPF is supposed to look these days :D.

Otherwise, once you skim all the unreadable crap, it's essentially *one* property refined by two sub-props on its id (one of which is a string for which we only have to care about two very specific values, and the other is essentially an unsigned int (almost ;p)), which doesn't sound all that crazy :).

(Again, no idea how that looks in practice, though :D).

**Comment by poire-z** [comment]
Anyone's going/willing to read/work/test on this?
Or should I just pick that code, not read the specs, and hope it works and closes this issue? :)

**Comment by NiLuJe** [comment]
Might take a look at it sometimes this week, for shit'n giggles.

per spec, though, because I'm still not quite sure what that mess in the first branch is supposed to do, but it might be trying to handle an earlier version or a weird variant or something.

**Comment by NiLuJe** [comment]
Fixed (via https://github.com/koreader/crengine/pull/346 -> https://github.com/koreader/koreader-base/pull/1115 -> https://github.com/koreader/koreader/pull/6264).

Pinging @Aszarsha to double-check, because I didn't really have any "real" test data on hand ;).

**Comment by Aszarsha** [comment]
Sorry for the bad news : this is not solved in the 2020.06 release.
The sames examples I used before exhibit the same behavior (no series information showed).

**Comment by Frenzie** [comment]
Did you refresh their metadata? Hold on the file and pick "refresh cached book information" at the bottom. Otherwise it won't reload it.

**Comment by Aszarsha** [comment]
> Did you refresh their metadata? Hold on the file and pick "refresh cached book information" at the bottom. Otherwise it won't reload it.

I had not! Seems to works great now, awesome.
