### ISSUE TITLE
Enabling keyboard when available for text input

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#5902]
I find myself typing every time I want to search for a word in the Koreader dictionary on my Linux desktop. 
What would be needed to enable the keyboard for text input when the on-screen keyboard is displayed?

**Comment by Frenzie** [comment]
For SDL, see: https://wiki.libsdl.org/SDL_Keycode

Doing keyboard layouts ourselves sounds like a lot of wasted effort to me. ;-)

**Comment by pazos** [comment]
:+1:  for the feature and :+1: for a platform agnostic way (raw keycodes instead of sdl_keyscans) to be able to repurpose it for android. See #4671

Leaving Caps Lock and Fn aside, the rest of modifiers just modify other keys between `onKeyDown` and `onKeyUp`. So is just a matter of keeping track of modifiers used and apply given modifiers each time we issue `onKeyUp` in a normal key.

I dunno how to pass the "proccesed" key to text boxes, but if this is easy to do the rest would be a matter of trial and error.

For a very barebones implementation we can skip `Alt` and `Ctrl` keys and just use `Shift` and `Alt Gr` as modifiers.

**Comment by Markismus** [comment]
Not only for android: The Pocketbook InkPad 3 Pro has Bluetooth. I only used it for its intended purpose: audio, but it would have been really nice to use a my Bluetooth keyboard.

**Comment by poire-z** [comment]
Relevant, I don't know :) But as some starting point:
https://github.com/koreader/koreader/blob/master/frontend/device/input.lua
https://github.com/koreader/koreader-base/tree/master/ffi input*, SDL2.0.lua...
and probably some key up/down handling and remaping needed, and some bridge up to `InputText:addChars(c)`.

**Comment by poire-z** [comment]
Implemented by #7037, some upcoming fixes in #7183.
