### ISSUE TITLE
Can't connect to different wireless network

### ISSUE THREAD

**Issue by WeihuaGu** [koreader/koreader#5912]
koreader version: 2020.02
device kobo: aura hd

recommention:

now,connect wifi with gb2312 coding,tell me failed to initiate network control client

**Comment by Frenzie** [comment]
I believe the WPA protocol calls for up to 63 bytes, which is encoding agnostic, but is it realistically possible to enter characters that aren't UTF-8 on any OS?

Can you connect in Nickel? And what are the steps you mean by "connect wifi"?

**Comment by WeihuaGu** [comment]
![3fRE6K.jpg](https://s2.ax1x.com/2020/03/03/3fRE6K.jpg)

**Comment by WeihuaGu** [comment]
nick can connect

**Comment by WeihuaGu** [comment]
![3ffNJs.jpg](https://s2.ax1x.com/2020/03/03/3ffNJs.jpg)

**Comment by Frenzie** [comment]
The good news, this just looks like Unicode to me. That might make it a touch easier to investigate.

\xe6\x97\x85 = U+65C5 = 旅

See for example https://www.utf8-chartable.de/unicode-utf8-table.pl?start=25856&names=-&utf8=string-literal

**Comment by Frenzie** [comment]
Okay, I investigated it a little. The problem seems to be simply what the error message says and it's completely unrelated to Unicode or Chinese characters. I assume the socket to wpa_supplicant isn't closed properly. Connecting to a different network doesn't actually work and results in that error message. And when you open the connect to wifi dialog it autoconnects to the previous one so it's a catch 22.

**Comment by Frenzie** [comment]
@NiLuJe It's simpler than that. It's a bad side effect from #4616. The problem is that if you tap on a network in the manager window it calls `authenticateNetwork()` but because wifi was just disabled there's no socket to connect to.

A very quick workaround would be something like this, but since you worked on that perhaps you remember more about it.
```diff
diff --git a/frontend/ui/widget/networksetting.lua b/frontend/ui/widget/networksetting.lua
index 3d17297e..64ac6875 100644
--- a/frontend/ui/widget/networksetting.lua
+++ b/frontend/ui/widget/networksetting.lua
@@ -212,6 +212,9 @@ function NetworkItem:connect()
     local connected_item = self.setting_ui:getConnectedItem()
     if connected_item then connected_item:disconnect() end
 
+    if Device:isKobo() or Device:isCervantes() then
+        NetworkMgr:turnOnWifi()
+    end
     local success, err_msg = NetworkMgr:authenticateNetwork(self.info)
 
     local text
```

**Comment by Frenzie** [comment]
I just realized the above can't be quite right because it undoes the effect of connected_item:disconnect().
