### ISSUE TITLE
May koreader support mht file extension?

### ISSUE THREAD

**Issue by Jerry-Chow** [koreader/koreader#5921]
I found the latest version of koreader can not open mht files.
Anyone can help me?

**Comment by Frenzie** [comment]
To my knowledge that has never been supported. Also see https://github.com/koreader/koreader/issues/3516#issuecomment-346857723

**Comment by pazos** [comment]
No version can read these (I'm well aware because I started to use KO in 2014 while I was on a job where, sadly, some coworkers used to share entire pages on this mhtml thingy).

You can open them in Opera, use right click and save as a loooong, scrollable, pdf. That works really well if you plan to read them in KO.

See attachments (using https://willus.com/k2pdfopt/ as an example)

input (zipped .mht): 
[Willus.com's K2pdfopt.mht.zip](https://github.com/koreader/koreader/files/4300546/Willus.com.s.K2pdfopt.mht.zip)

output (pdf):
[Willus.com's K2pdfopt.pdf](https://github.com/koreader/koreader/files/4300566/Willus.com.s.K2pdfopt.pdf)

**Comment by poire-z** [comment]
I guess crengine (lvstream.cpp) could be made to parse/decode these MHT or EML mime archives, and expose it to the rest of the code as a container with files - but that looks not like fun :) and a lot of work for a very rare use case.
Some sample code: https://chromium.googlesource.com/chromium/src/+/HEAD/third_party/blink/renderer/platform/mhtml/mhtml_parser.cc

So, as we don't, may be just convert these MHT to EPUB from outside. May be calibre or MSWord can do that.
Some discussion https://www.mobileread.com/forums/showthread.php?t=274512
Many online converters seem to exist: https://www.google.com/search?hl=en&num=25&q=mhtml+to+epub

**Comment by pazos** [comment]
@poire-z: these mht to epub online converters produce a very bad output for most of the pages. See [Willus.com's K2pdfopt.epub.zip](https://github.com/koreader/koreader/files/4302159/Willus.com.s.K2pdfopt.epub.zip) (strip the zip suffix).

Another, minimal, sample code is [mht-rip](https://github.com/lsowen/mht-rip/blob/master/mht-rip.c), which decodes base64 encoded attachments to files. It's not intended for conversion but as a simple way to extract images and other content (flash?) from mht files.

**Comment by cvtsi2sd** [comment]
I'd like to add a use case for this feature: a very simple "send page to ebook reader" feature. Chrome (and Chromium-based) browsers on Android save a .mhtml file when asked to download a page; I have a SyncThing folder shared between phone, ebook reader and PC, so, if KOReader supported .mhtml, it should work pretty nicely for this use. ATM I'm using print to PDF, but generally the results are quite bad (many sites print decently only to A4, and that's way too small for my ebook reader).
