### ISSUE TITLE
In-page footnotes & epub3

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5925]
Q: Do in-page footnotes not work for epub3 in general?

I have an epub3 where the footnotes came all in one go, so to speak. Like this:
![Reader_2020-Mar-07_094321](https://user-images.githubusercontent.com/32645430/76140674-2fe54100-605d-11ea-8919-2027a0bcd952.png)
![Reader_2020-Mar-07_094334](https://user-images.githubusercontent.com/32645430/76140677-3378c800-605d-11ea-9668-169c43ae9b03.png)

**Comment by poire-z** [comment]
Depends on the quality of the book, and our style tweaks (which look like they might set `-cr-hint: footnote-inpage;` on the whole block of footnotes, instead of each individual footnote).
Which style tweaks have you enabled ? (if multiple in-page footnotes, try to disable some).

Your screenshot shows what's happening with link to footnote 1 - but what happens on later pages that link to footnote 2 and 3?
Also, select text around the footnote link > View HTML (scroll to show the part with the href) > Screenshot.
The, go to the page with footnotes, select text from before 1st footnote, up to some part of 2nd footnote > View HTML > Screenshot.

**Comment by gerhaher** [comment]
Thanks

Classic classnames footnotes enables them. 
Nothing happens on later pages.

If you wanna take a look at it, here is the book, scrambled:
[From Peoples Into Nations_ A Hi - John Connelly_scrambled.zip](https://github.com/koreader/koreader/files/4301692/From.Peoples.Into.Nations_.A.Hi.-.John.Connelly_scrambled.zip)

**Comment by poire-z** [comment]
_Teach a man to fish..._ :)

<kbd>![image](https://user-images.githubusercontent.com/24273478/76142197-8eb1b700-606b-11ea-83fd-dc888ba19412.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/76142160-46929480-606b-11ea-827a-bc69dfdf531f.png)</kbd>

(Just for info, the first screenshot (`role=doc-noteref`, EPUB2 footnote link) indicates these will probably work as popup footnotes.)

There are some bits of EPUB3 stuff (`epub:type=rearnotes`, plural) to indicate a section of footnotes, but each footnote is _not_ marked with the singular `epub:type=rearnote`; so our "EPUB footnotes" tweak will not catch them:
https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/ui/data/css_tweaks.lua#L641-L653
So, _bad book quality_ :)

So, ok, fallback to using classic classnames:
https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/ui/data/css_tweaks.lua#L714-L723
This will consider the full `<ol class=footnotes>` as being a single footnote - which is what you see.
So, our classic classnames caught a false positive (ok, footnotes plural sounds bad for catching a singular footnote, but it was asked in https://github.com/koreader/koreader/pull/5727#issuecomment-570217365).

So, you'll have to resort to disable classic classnames, and make a user style tweak.
You want to mark each indiividual footnote, so, in the above 2nd screenshot, each `<li role=listitem>` that is a child of the big `<ol class=footnotes>` - so, just catching any `LI` child of `OL.footnotes`.
Creating `koreader/styletweak/thatbook_footnotes.css` containing:
```css
ol.footnotes > li { -cr-hint: footnote-inpage; }
```
and enabling it, will have your footnotes correctly shown "in-page".

So, for some books, there's nothing sane (that won't harm when enabled on some other books) we can do - so the user has to know a bit about HTML and CSS, inspect the book content, and find out a CSS solution.

**Comment by poire-z** [comment]
@Norbi24 (assuming it's you), answering some of your questions in https://www.mobileread.com/forums/showthread.php?p=3973848#post3973848

> I thought something simpler - if a hyperlink in a page is found, then always display the block it points to as a footnote (if configured so)
But perhaps I am overlooking something ? 

I think you are :) Hyperlinks can be to something other than footnotes, like chapters, backlinks from footnotes to main text, and other internal links.
Think about in-book Table Of Content, that has hyperlinks to all chapters. With your simple solution, you'd have full chapters as footnotes of the TOC :)
So, we need some help to distinguish what's a link to a footnote, or what blocks can be considered a footnote that may be linked to.
If publishers have added the role= or type= attributes, they have helped us, we can trust them.
If not, we're a bit alone, and it's hard to guess (more on that below). Best to trust the user to set the correct CSS `-cr-hint: footnote-inpage` (and as this issue shows, it depends on where you put it to have the full single footnote, ans not a single part of it, or a block of multiple footnotes.

> I mean it anyway supports hyperlink in the page, pickups the html block they point to, but then attempts to match it agains the tweaked CSS class which contains the property cr-hint: footnote-inpage and if ok, they it shows it in the page
(this is at least my understanding)

Not exactly. Explaining how crengine (EPUB renderer of KOReader) does it:
crengine parses the full book content (at load time and on re-rendering). In that process, it gathers "lines" (with, for each line, the hyperlinks contained in that line). It flags the lines that happen to be inside a block with `-cr-hint: footnote-inpage` as "may be footnotes content".
Then, at the end of this process of rendering, it goes into a phase of "page splitting": making pages (limited to the screen height) from all the lines it has gathered. In that process, for each line that had hyperlinks, it looks if they link to some of the lines flagged as "may be footnotes content", and if yes, it goes on adding these targeted lines to the current page (so, filling the page from the top with main text lines, and filling it from the bottom with "may be footnotes content" lines, trying to do the right thing when they meet, reporting footnote content to the next page if needed...). These "may be footnotes content" lines are still rendered naturally (so, duplicated) at their place in the book.
These pages infos are then static, saved in the cache, and that's why it's fast turning pages.
(And that's why there are no footnote in-page in scroll mode, where the "pages" are not used.)

One error in what's "may be footnotes content", making it too big, and your book display is screwed.

> I was playing with the ALReader reading app, and it supports it also, but it has only one config checkbox to activate showing footnotes at the end of the page, and it works almost everywhere pretty fine.

Well, I don't know how ALReader works, so I can't say much.

But note that for "popup footnotes", we use some other method, and we indeed try to "guess" what's a footnote link or target:
https://github.com/koreader/koreader/blob/04ca12bb7fabca7004e42a8c2956c0cfd5fe72b5/frontend/apps/reader/modules/readerlink.lua#L965-L1071
and the real detection work in:
https://github.com/koreader/koreader-base/blob/fd8e6cfadea27f14188e5f12f2c342a828b0a9c2/cre.cpp#L2204-L2912
It's quite complicated, and may result in false positive and false negative - but then, it's just popup footnotes working or not, it will not do much harm.
If we were to use all that in crengine so it can make "pages" with them, and if it's wrong, it would cause a lot more harm :)

So, may be ALReader does something like that, and may be it doesn't have to build full "pages", and can tweak that dynamically, so a bit like our popup footnotes,
