### ISSUE TITLE
Suggestion: show only supported file types in one list in FM

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#5976]
Hi guys,

I have a suggestion for FM. I think it will be very useful to have a feature to show all supported file types KOReader can open in one list. 

One example is when you have many directories with sub-directories full of books. Then you show all supported books in one list, sort them by title/author/etc and can quickly choose a book. 

Moreover, if you can untick those formats you don’t want to show up like txt (e.g. if you have 100+ of txt files of saved highlights), that will be nice. 

Also, this list can show what directory this book is located at.

**Comment by pazos** [comment]
Hi @mergen3107. 

The Filemanager is like your computer file explorer. It shows files and directories containing other files in a hierarchical fashion.

What you suggest is a library or a collection. A list of elements that have properties.

A FM doesn't need a database because the filesystem is the database. (It actually uses one *if* you enable cover browser but is used for metadata, not for the elements themselves).

A Library needs a few steps:
  1. search recursively for entities of a given type (aka indexing)
  2. store properties on the database
  3. re-index after filesystem changes. 

Please read other open issues labeled as UX. As you can see there are a few opened issues that are better handled with a Library view, like #3864

Keep in mind that something like that needs to be implemented as a different app, not as an extension of the FM. Sadly this is not trivial, specially because some people (like me) would love to opt-out the library view entirely and stick with the good-old filesystem handling.

You're not alone. Other people like databases over filesystems too. You're very welcome to submit patches to implement a library view :+1:

**Comment by mergen3107** [comment]
I am sorry for probably misleading you. 
I didn’t mean a “Library” as a complete replacement for FM. I like FM as it is, it is classical and very familiar from other systems. 

What I meant is a button “Search only supported files” which essentially does a search through all filesystems but for wildcards of only supported extensions (*.epub, *.fb2.zip, etc) and shows them in a search results window, as a regular search would. 
 As for update state, this feature will depend on the FM’s list of files, as a regular search does. 

I understand that implementing wildcards is probably very difficult, hence this is only suggestion. I am not insisting on this feature, but I wanted to make sure I delivered the point I wanted to deliver in the first place :)

**Comment by NiLuJe** [comment]
That's essentially what the existing search does?

**Comment by mergen3107** [comment]
It can only search by filenames. I tried inputting wildcards like `*.epub`, but the search engine treats them as filename strings.
