### ISSUE TITLE
Frontlight: doesn't remember previously used value

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#5986]
* KOReader version: 2020.03.02
* Device: Kindle PW3

#### Issue
After exit, KOReader doesn't remember Frontlight value used before turning off.

#### Steps to reproduce
1) Kindle menu: set Frontlight (e.g. 10)
2) Open KOReader via KUAL
3) It sees the correct value of Frontlight (10), OK
4) Turn off Frontlight and try to toggle - resumes back to 10, OK
5) Turn off Frontlight via "Toggle" (in menu, or with gesture)
6) Exit KOReader
7) Return to KOReader via KUAL. Try to toggle Frontlight - it stays at 0, while gesture popup says "Frontlight off" each time.

So probably KOReader should remember the previously used value of Frontlight before exit?

**Comment by NiLuJe** [comment]
Isn't the PW3 the first device where 0 is actually possible on Kindle and actually means off?

I haven't looked at the Kindle FL code, but it's quite possible we originally assumed 0 wasn't a viable setting on the Kindle's side, and coopted it as meaning "off" for us. If that no longer holds true, off/on tracking goes wonky.

**Comment by mergen3107** [comment]
PW3 is actually the last device where stock menu’s “zero” is actually not complete “lights off”. It was PW4 AFAIK with proper “zero”. 

However, setting 0 in KOReader actually turns off Frontlight completely.

**Comment by hius07** [comment]
PW2. I see 2 issues with frontlight.

1. As above, KOReader doesn't save its internal Level upon exit.
Start KOReader, set Level=10, Toggle off, exit KOReader.
Start KOReader: now I cannot Toggle on because Level=10 wasn't saved, I need to set the Level again.

2. KOReader doesn't pass internal Level to the system upon exit.
Set Kindle Level=10, start KOReader (frontlight is on), Toggle off, exit KOReader.
Now the frontlight physically is off but Kindle Level scale shows 10.

**Comment by NiLuJe** [comment]
Both are by design (we trust the hardware on Kindle), although for 1., KOReader not detecting the on/off state properly is a bug.

I can't reproduce 2. on a PW2 on 5.9.7, the stock UI slider is properly set to 0.

**Comment by NiLuJe** [comment]
(And, no, we are *NOT* going to remember the last KOReader "on" value somewhere, because we do that on Kobo, and it's a massive headache).

**Comment by mergen3107** [comment]
I can't reproduce #2 on PW3 (5.9.7) neither: FrontLight is physically off and it shows "zero" in Kindle metric.

**Comment by hius07** [comment]
PW2 5.8.7, just repeated (2) and have the light is off, the slider is at 8.
OK, it's not a big issue for me.

**Comment by NiLuJe** [comment]
The only way this could be happening (2., I mean), is:

* Broken LIPC
* FW bug

As long as lipc is working, we're setting the fl the "official" way, so it's by design kept in sync with the stock FW.
If lipc is broken, we do it behind the system's back. But that should never actually happen in practice.

So, a couple questions:

* Are non-off states kept in sync properly?
* Does `lipc-get-prop com.lab126.powerd flIntensity` return something sensible?
* Have you used KPVBooklet in that power cycle? If yes, reboot, and try without.
* Reboot,  and try again ;p.

**Comment by hius07** [comment]
Rebooted the device (got back my top bar https://github.com/koreader/koreader/issues/5990).
Set Kindle light level to 10, start KOReader, Toggle off, exit KOReader: the light is off, Kindle slider shows 10.
Set slider to 0, start KOReader, set Frontlight to 10, exit KOReader: the light is on, Kindie slider shows 0.
KPVbooklet has never been installed.
In KOReader terminal lipc-get-prop shows 10.
Exit KOReader, in kterm lipc-get-prop shows 10 (which is correct). But the slider shows 0.

**Comment by NiLuJe** [comment]
Then FW 5.8.x being wonky it is, then ;).
