### ISSUE TITLE
Default file browser folder is wrong

### ISSUE THREAD

**Issue by mirh** [koreader/koreader#6026]
* KOReader version: 2020.03.2
* Device: Tolino Vision 4 HD (on android 4.4.2)

#### Issue
Title. Not sure if it's specific to my device, or all androids. 
Probably regressed after 87334801ea250c1a77304685e0d82685b08bab09

#### Steps to reproduce
Start the program for the first time
Instead of the sdcard you are greeted with /data/data/org.koreader.blalbla/

**Comment by pazos** [comment]
Cannot reproduce. Could you please attach the log file?

**Comment by mirh** [comment]
:/ 
I cannot reproduce this myself either. 
I deleted both the program data folder, and the koreader folder on the /sdcard. 

Perhaps having upgraded from ics to kitkat caused this? Is it possible that if the previously saved "home folder" is wrong/missing, the fallback is to /data?

**Comment by mergen3107** [comment]
Did you have your old config file before the update?
Maybe you accidentally set default home folder before?

**Comment by mirh** [comment]
I did some more tests, and if I could confirm my later theory. 
If I corrupt the value of the home directory (and/or the last viewed folder) inside the lua settings file in /sdcard/koreader, it falls back to /data/data/whatever.

**Comment by pazos** [comment]
> "home folder" is wrong/missing, the fallback is to /data?

Indeed, setting a home directory other than default will override [path](https://github.com/koreader/koreader/blob/master/platform/android/llapp_main.lua#L16). If the directory doesn't exist it won't be opened so `chdir` won't do anything. [android.dir](https://github.com/koreader/koreader/blob/master/platform/android/llapp_main.lua#L38) is always stored in private storage partition, under `/data`. That's not a bug, but a limitation of the platform.

**Comment by mirh** [comment]
?? Shouldn't you fallback again on /sdcard if the value is wrong, and only then as a last desperate chance go into private storage?

**Comment by mergen3107** [comment]
Maybe something related to mount order? For example, when /sdcard has not been mounted yet, KOReader tries to reach it?

**Comment by mirh** [comment]
I'm not wondering *why* this happened (as I said, I updated from 4.0 to 4.4, and this may have slightly changed mount points). 
I'm saying that it shouldn't have happened. 
Surely it shouldn't be impossible to be more cautious on opening, or catch a notfound exception?

**Comment by pazos** [comment]
> Shouldn't you fallback again on /sdcard if the value is wrong

The issue is not specific for android. It will happen on any other platform, for example:

on Kobos: it will start in `/mnt/onboard/.adds/koreader` instead of `/mnt/onboard`
on Cervantes: it will start in `/mnt/private/koreader` instead of `/mnt/public`
on Android: "" `/data/user/0/org.koreader.launcher/files` instead of primary shared storage.

> I'm saying that it shouldn't have happened.

Not against a fallback against an invalid `home_dir`, but removing that invalid home_dir is easy enough to not bother me :p. PR are welcome, please look at https://github.com/koreader/koreader/search?q=home_dir&unscoped_q=home_dir. 

Maybe @poire-z is interested in fixing this one :p 

> Maybe something related to mount order? For example, when /sdcard has not been mounted yet, KOReader tries to reach it?

nope

> catch a notfound exception?

Errr, nope. Again not platform specific. Not something java-like and not a bug recognizing the primary path.

**Comment by poire-z** [comment]
> Not against a fallback against an invalid home_dir, but removing that invalid home_dir setting is easy enough to not bother me 

Dunno if it would be a loss if the user has set it to a removable storage path, launched KOReader without that removable storage plugged in, and would lose it... but it could be as easy as adding in reader.lua so that it's removed on startup if it does not exist:

```lua
if G_reader_settings:readSetting("home_dir") and lfs.attributes(G_reader_settings:readSetting("home_dir"), "mode") ~= "directory" then
    G_reader_settings:delSetting("home_dir")
end
```
(we do check for the existence of `last_file` and show a message, dunno if that would be really needed for home_dir)

**Comment by mirh** [comment]
> Not against a fallback against an invalid home_dir, but removing that invalid home_dir setting is easy enough to not bother me :p. PR are welcome

Well, sure that. 
I was just baffled by the closure of the issue (which usually stands for "not a bug", as the tag it now has, rather than "cannot be hassled now").

**Comment by Frenzie** [comment]
The invalid tag seems a bit odd here, but I wouldn't say that about closure. An open issue distracts you if you're looking through issues. You could filter out wontfix labels but that's a lot of additional effort (it adds up over time) for no real added value.

In our case closure is just an organizational tool, not some kind of "this issue is closed, end of discussion" statement. Additional info or arguments are always welcome.

**Comment by poire-z** [comment]
@Frenzie : any opinion on removing the setting (so the default start dir is used by FileBrowser) when the directory it points to is not available/has been deleted?

**Comment by Frenzie** [comment]
Sounds a bit destructive to me. I'd be more inclined to put it here (along the lines of `if home_dir and lfs.attributes(home_dir)`):

https://github.com/koreader/koreader/blob/04ca12bb7fabca7004e42a8c2956c0cfd5fe72b5/frontend/apps/filemanager/filemanager.lua#L681-L715

**Comment by pazos** [comment]
If this is not invalid it is not android :smile:
