### ISSUE TITLE
Crash when trying to Export all notes in Evernote plugin

### ISSUE THREAD

**Issue by RCoeurjoly** [koreader/koreader#6050]
* KOReader version: v2019.11
* Device: Onyx Boox Max 2 pro 

#### Issue

Crash when trying to Export all notes in Evernote plugin

#### Steps to reproduce

Evernote>Export all notes in your library

##### crash log
Relevant result of `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`. : 

04-15 01:30:03.445 29935 29947 E KOReader: [NativeThread]: failed to run script: plugins/evernote.koplugin/clip.lua:259: bad argument #1 to 'insert' (table expected, got nil)
04-15 01:30:03.445 29935 29947 E KOReader: [NativeThread]: Stopping due to previous errors
--------- beginning of crash
04-15 01:30:03.470 29935 29946 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa4 in tid 29946 (Binder_2)
04-15 01:30:03.662   557   934 I ActivityManager: Process org.koreader.launcher (pid 29935) has died

**Comment by pazos** [comment]
Probably because you have a highlight stored on a sidecar folder (name.sdr) but the document (name.sufix) is not there.

https://github.com/koreader/koreader/blob/master/plugins/evernote.koplugin/clip.lua#L257-L260, or better yet `MyClipping:parseHighlight` doesn't guard agaisnt nil values

I might be totally wrong because it is the first time I read that code :worried:  Help wanted!

**Comment by RCoeurjoly** [comment]
Tried with the latest version of KOReader and I don't have that problem.
Closing.

**Comment by NiLuJe** [comment]
Gah, missed the version tag -_-".

**Comment by RCoeurjoly** [comment]
> Tried with the latest version of KOReader and I don't have that problem.
> Closing.

The version available in FDroid is v2019.11. Why isn't it tha latest? @NiLuJe
