### ISSUE TITLE
Character spacing is so large and messy when displaying Chinese

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#6078]
* KOReader version: V2020.04
* Device: Hisense A5

#### Issue
The character spacing is so large when displaying Chinese, no matter how I adjust the options, it is so large and messy. Here I took two screenshots both in KOReader and another reader called AlReader. You can see the difference. The character in AlReader is neater while it is messier in KOReader.

#### Steps to reproduce
1. Open a Chinese book in KOReader
2. Open the same book in AlReader
2. Compare the character spacing in two apps 

![WechatIMG13](https://user-images.githubusercontent.com/46492291/79823033-3ccbb300-83c5-11ea-8c3f-7ac627cb1f04.jpeg)
![WechatIMG14](https://user-images.githubusercontent.com/46492291/79823035-3e957680-83c5-11ea-9feb-f4f92b134787.jpeg)

**Comment by NiLuJe** [comment]
With which font, and which rendering setting (bottom menu, "B" tab)?

**Comment by poire-z** [comment]
One thing noticable is that on your first screenshot (AIReader), the text is not justified but left aligned: so, chinese characters are stacked near to each other.
On your 2nd screenshot (KOReader), text is justified: KOReader adds some space between chars to justify the text (and have the right side fully aligned.
You can disable text justification with `Style tweaks > Text > Text alignment > Left align all/most`.
Tell us how that works for you.

And if you have a bit of time and interest, you can read https://github.com/koreader/crengine/issues/307 "CJK (horizontal) layout" and give us some input about what we can do to improve (and/or not make worse) chinese text rendering :)
Here, on your first screenshot, I don't understand why the glyphs are not vertically aligned with each other:
![image](https://user-images.githubusercontent.com/24273478/79832147-15ff8380-83a9-11ea-8f46-6071e0923452.png)
Why is that? Does it bother you or not at all ?
(On the justified koreader screenshots, it's expected - as some chars like punctuation are pushed on the next line, so there is not the same nb of glyphs on each line, and the added spacing may so vary.)

**Comment by kingo132** [comment]
> With which font, and which rendering settings (bottom menu, "B" tab)?

The font I used is attached here. 
[jiaokeshuti.ttf.zip](https://github.com/koreader/koreader/files/4510475/jiaokeshuti.ttf.zip)

The settings are like this
![WechatIMG15](https://user-images.githubusercontent.com/46492291/79875907-e8ecb880-841c-11ea-87cb-34697d913eb2.jpeg)

**Comment by kingo132** [comment]
> ame n

I tested the option you give. It looks better now. However, there comes another problem. There are many empty spaces at the end of the line. It looks so wired. Here is the screenshot.
![WechatIMG16](https://user-images.githubusercontent.com/46492291/79876286-6ca6a500-841d-11ea-9da6-29af268d98b9.jpeg)

It doesn't bother me while the glyphs are not vertical aligned. However, it does bother me while the glyphs have large and irregular spacing, or the huge empty space at the end of the line. I think most Chinese reader thinks the same as me.
There is some kind of books in Taiwan or Hongkong written in Traditional Chinese. Their text is arranged vertically like the photo I attached below. Only this kind of book needs to align glyphs vertically. Otherwise, while the book is printed in a horizontal format, regular and appropriate spacing is the most important. I think the arrangement in AlReader is very good. And at least 90% percent of Chinese books are horizontal format.
![0164e25b963bc1a8012017ee19da80 jpg@800w_1l_2o_100sh](https://user-images.githubusercontent.com/46492291/79877577-fa36c480-841e-11ea-8e97-6c18438b4ff6.jpg)

By the way, the article you posted is so long. I will try to read it thoroughly. After that, I will see if I can give some opinion.

**Comment by poire-z** [comment]
> There are many empty spaces at the end of the line. It looks so wired. 

Yep, I think it's because these things in yellow should not appear at start of line as per chinese typography, when there's no room for them at end of line, they bring their preceeding char with them at the start of next line (so they don't appear themselves first on that line).
I think these rules make these blues box unbreakable, and when there is no room at end of line, they each go fully at start of line:
<kbd>![chinese](https://user-images.githubusercontent.com/24273478/79880775-baf17f00-83f0-11ea-8513-1315c48e5720.jpeg)</kbd>

2 things to test:
- enabling `[x] Hanging punctuation `, which push some chinese chars in the margins, so the little yellow thing might go in the right margin and prevent a bit what you see (there are many other bugs with hanging punctuation, but may be you'll be ok with them).
- try this morning (or better, tomorrow's) nightly: we have changed a bit of the line breaking rules 2 days ago - if you choose Hyphenation/Typography to be "English" or  some other language like Icelandic (and tomorrow, Chinese), you may get a bit less strict line breaking rules, and may be things will be nicer.

Please tell us how that works.

**Comment by poire-z** [comment]
> The Hanging punctuation option does not work, it will create another huge blank space on the right like the screenshot below.

Yes, that's how it works currently: it reduces the main width to get some padding on the side (which i don't think is a good idea) - so you might need to compensate by reducing koreader margins.
Also, if you keep "Text align most/all text", you'll always have holes on the right. You need to disable it to get back text justification to not have any holes on the right (the hole width will be distributed between the letters). In any case the variation in widths of little holes between letters will be less noticable that the varitions in width of the big hole on the right :)

> By the way, how can I download the morning or nightly build apks. I can't find it in any place of github repository of koreader.

http://build.koreader.rocks/download/nightly/

> I don't quite know the arrangement algorithm. But I think there may exist some way not only to avoid the punctuation appear at the beginning of the line, but also keeps the text neatly. I have used a lot of reading software, and rarely see such a large Chinese character spacing. Also, the printed books do not have large Chinese character spacing as well. You can see my photograph blow.

Well, crengine was made for western text. Some chinese developpers added some stuff to accomodate for chinese text a few years ago. But for some time, there have been no more active chinese devs, so it's a bit stalled on that front.
I'm french, I don't read chinese, I know a bit crengine, so I can help a bit at making it better, but I'll need input and feedback :)

> Or, could you try to make the punctuation not occupy the entire width of the glyphs, but narrow it a bit, so that you can leave more place for normal glyphs to fill in the blanks on the right. 

That's an option. But there:
<kbd>![image](https://user-images.githubusercontent.com/24273478/79893356-3c9ed800-8404-11ea-8b5a-b0112044ccb1.png)</kbd>.

We could reduce the width of the comma in yellow (but it is nearly centered in it's glyph, it will be no more if we reduce its width).
And (just asking you, chinese reader - but I guess we won't break it) would you accept a break in the blue box ?
We could reduce the widths of only punctuation, or all chars, there are various options.
But I don't know which is best. There's quite some litterature about it:
https://www.w3.org/TR/clreq/
And I'd rather like us to do it the right way, and not just make quick hacks :)

But looking at how it's done in books is interesting:

![image](https://user-images.githubusercontent.com/24273478/79894184-5ee52580-8405-11ea-970f-85747a6ec3af.png)

Looks like to make that ending period in yellow fit on the line, the publisher reduces the space between all glyphs on that line - but it didn't reduce the width of the comma in pink in the middle.

On this one, I can't say if they reduced some spaces between letters - can you?:

![image](https://user-images.githubusercontent.com/24273478/79894496-d1560580-8405-11ea-8477-fdb5a54f09c8.png)


So, dunno how that is/should be decided :) and how your word processors decide that. If you can think about simple rules, I'm all ears :)

> And currently, the option "Word Spacing" small, medium or large only takes effect in English books, there is no effect while in Chinese books.

Yep, that's expected: currently, it affects only real space characters - and you have none in chinese text I guess.

> I don't quite know the arrangement algorithm. 

In case you're interested and can read code: https://github.com/koreader/crengine/blob/65d4adf843b4c85627187d4e2f685b8f42dfa1f4/crengine/src/lvtextfm.cpp#L3027-L3591

There is code for CJK (Chinese Japanese Korean) that is not mine - but the comments around are mostly mine, trying to understand/document why it was done that way.

Also, you're using a quite large font size - so it's more prone to having holes - there's probably more options to cut the text into lines and avoid holes when using a smaller font.
Is that the normal font size / nb of char per line that chinese readers use ? (So that I know it's useless testing with a smaller font size :)

**Comment by kingo132** [comment]
> But for some time, there have been no more active chinese devs, so it's a bit stalled on that front.
Really sorry to hear this.

> And (just asking you, chinese reader - but I guess we won't break it) would you accept a break in the blue box ?
In Chinese text, everything can be break. Unlike English letter that can not split, the Chinese text is consisted by many single characters, they can be separated in any case. And as well is the punctuation, they also can be break. That doesn't brother me.
However, it's interesting that I can hardly find the line that is leading by punctuation in printed books. Maybe its some kind of arrangement rules. I don't know.

> On this one, I can't say if they reduced some spaces between letters - can you?:
It's also OK to reduce spaces between letters. So long as the spaces difference is not very large. Acctually, I didn't notice the space is reduced before you mentioned this. The change is subtle.
Or what brother me in KOReader is the large difference of all these spaces, and some spaces is too large. May be it can threshold the minimum and maximum width of the space, it should be better.

> Is that the normal font size / nb of char per line that chinese readers use ? (So that I know it's useless testing with a smaller font size :)
This is definitely normal font size. Many Chinese guys use larger size than me. My preference is a bit small than them because I want more character show in the same screen.
Look at their font size below.
![4bed2e738bd4b31c51b484dc90d6277f9f2ff8c9](https://user-images.githubusercontent.com/46492291/79930519-4f082880-847b-11ea-926b-ce9cd91536b5.jpg)
![d833c895d143ad4bcc59cba095025aafa40f065e](https://user-images.githubusercontent.com/46492291/79930520-516a8280-847b-11ea-9408-6bfca070cd09.jpg)
![d50735fae6cd7b89a5d69de5182442a7d9330e19](https://user-images.githubusercontent.com/46492291/79930523-52031900-847b-11ea-8dea-2c3a37cbeda1.jpg)

> In case you're interested and can read code:
I can read a bit, but it may take a long time to understand it from the beginning. I'll try, but I don't know what the result it may be.

**Comment by kingo132** [comment]
I installed the nightly build version koreader-android-arm-v2020.04.1-1-g6336927_2020-04-19.apk
It looks better but still some wired places.
![WechatIMG22](https://user-images.githubusercontent.com/46492291/79932893-18cda780-8481-11ea-9745-4259a09a587a.jpeg)
![WechatIMG23](https://user-images.githubusercontent.com/46492291/79932896-1a976b00-8481-11ea-9512-87e76f00ce06.jpeg)

**Comment by poire-z** [comment]
>  However, it's interesting that I can hardly find any lines that are lead by punctuation in printed books. Maybe its some kind of arrangement rules. I don't know.

Yes, that's the unicode line breaking algorithm (that we use since 2 days ago - instead of handmade rules) that decides/prevents that.
And it shows on **all** your screenshots :) whether koreader, aireader, or the phone pics.

![image](https://user-images.githubusercontent.com/24273478/79952220-61359700-847a-11ea-9cc4-5b880337655f.png)
All lines have 9 glyphs, except the 2nd that got 8 because of the comma on 3rd line that needed a preceeding char.

<kbd>![image](https://user-images.githubusercontent.com/24273478/79952551-e456ed00-847a-11ea-97d3-59f71a0b02f0.png)</kbd>

Again, same reason: unbreakable blue box.
But you only gave that hard text to KOReader :) all your other screenshots have simpler stuff :)
Can you try AIReader with that document, that has the blue boxes I highlighted, and play with font size and margins, so AIReader has to deal with them at start or end of line, to see how it does with them, if it has other strategies or if it has to do like us and can't prevent large holes on the right?
And if it does better, try to guess what strategies it uses (which widths it reduces, does it play with the previous line (that, we won't be able to do)...)

> I can read a bit, but it may take a long time to understand it from the beginning.

Don't bother getting into the code - it's hard.

If you can share that book (or just a HTML fragment of it), I'll have something to play with.

**Comment by kingo132** [comment]
> > However, it's interesting that I can hardly find any lines that are lead by punctuation in printed books. Maybe its some kind of arrangement rules. I don't know.
> 
> Yes, that's the unicode line breaking algorithm (that we use since 2 days ago - instead of handmade rules) that decides/prevents that.
> And it shows on **all** your screenshots :) whether koreader, aireader, or the phone pics.
> 
> ![image](https://user-images.githubusercontent.com/24273478/79952220-61359700-847a-11ea-9cc4-5b880337655f.png)
> All lines have 9 glyphs, except the 2nd that got 8 because of the comma on 3rd line that needed a preceeding char.
> 
> ![image](https://user-images.githubusercontent.com/24273478/79952551-e456ed00-847a-11ea-97d3-59f71a0b02f0.png)
> 
> Again, same reason: unbreakable blue box.
> But you only gave that hard text to KOReader :) all your other screenshots have simpler stuff :)
> Can you try AIReader with that document, that has the blue boxes I highlighted, and play with font size and margins, so AIReader has to deal with them at start or end of line, to see how it does with them, if it has other strategies or if it has to do like us and can't prevent large holes on the right?
> And if it does better, try to guess what strategies it uses (which widths it reduces, does it play with the previous line (that, we won't be able to do)...)
> 
> > I can read a bit, but it may take a long time to understand it from the beginning.
> 
> Don't bother getting into the code - it's hard.
> 
> If you can share that book (or just a HTML fragment of it), I'll have something to play with.

This is the book I'm reading.
[thequietamerican.epub.zip](https://github.com/koreader/koreader/files/4516454/thequietamerican.epub.zip)

I'll compare this book carefully in KOReader and AlReader and try to figure out some algorithm or detailed report. It may take a few days.

**Comment by poire-z** [comment]
Found some interesting resource on chinese typography, that I mentionned at https://github.com/koreader/crengine/issues/307#issuecomment-629619680.

**Comment by poire-z** [comment]
Can some chinese reader translate in english the titles of these 4 set of configurable glyphs:
<img width="952" alt="KisokuRule" src="https://user-images.githubusercontent.com/24273478/82118089-1fe09080-9775-11ea-9724-8426f5ba479c.png">
(from this article: https://www.thetype.com/2017/11/13290/ , at ~2/3 of document height)

I guess the 1st set is closing punctuations, the 2nd opening punctuation - but do the titles says a bit more what would be done for them?
What would be additionally done for the commas in the 3rd set, which are also present in the 1st set, vs. chars present only in the first set.
And what about the 4th set that contains chars not present in the others?

**Comment by cges30901** [comment]
1st set: characters that cannot be put at the beginning of line
2nd set: characters that cannot be put at the end of line
3rd set: hanging punctuation
4th set: see [this](https://www.thetype.com/2019/03/14918/#pozhehao-oneortwo) and [this](https://unicode.org/reports/tr14/#B2) (for example, one em dash at the end of line and the other at the beginning of next line)

**Comment by poire-z** [comment]
> The font I used is attached here. [jiaokeshuti.ttf.zip](https://github.com/koreader/koreader/files/4510475/jiaokeshuti.ttf.zip)

What's the deal with this font: it looks a bit odd to me, as it has "Simplified Chinese" left-aligned fullstop period and ideographic comma (in green), but it has "Traditional Chinese" centered fullwidth comma (in yellow):

![image](https://user-images.githubusercontent.com/24273478/170704093-06cfec06-8026-4e5a-a09e-cb137f907ea5.png)

No issue for me with what I'm trying to achieve, but I'm just curious : do you Chinese readers feel this is odd too ? Or are you minds just that flexible and you don't even notice that ? :)
Do you feel this is a bug in the font, or a stylistic choice ?

From #6162 : 
![image](https://user-images.githubusercontent.com/24273478/170705239-180a80a8-d46c-4047-bf13-155b021cf5c1.png)
