### ISSUE TITLE
Entry cleaned from history but stays in "Previous"/" Open last"

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#6126]
* KOReader version: git nightly
* Device: android

#### Issue
Cleaning last entry from history is not with sync with "open last". Still can be reached from that feature. 
"Open last" should be with sync with history. 

#### Steps to reproduce
Open book , remove it from history, use "Open last"/"previous" to oepn it again.

**Comment by Frenzie** [comment]
I'm not convinced it should, but pinging @poire-z.

**Comment by poire-z** [comment]
Well, I thought I would have taken care of that - but no, I just took care of updating "last file" when, from the history view, we "delete" a file.

Some quick tests, and I think this issue does (somehow) not happen when history is invoked from the reader - but only when invoked from file browser.
But yes, to me, it feels like a bug: i would expect that if I remove the first file from History, it is removed from Last/Previous. May be not when in Reader, where the book you would remove is the current book that is still opened.
Just a bit lazy to tackle it, so if other don't consider a bug, well, I might ignore it :)

**Comment by Frenzie** [comment]
> May be not when in Reader, where the book you would remove is the current book that is still opened.

Right, if I switch back from previous document to previous document I don't expect some third or fourth file to be opened *regardless what the history might say*.

But that seems to be the current behavior, because unlike last file, previous file isn't stored separately. So logically speaking one of the two should be changed for consistency, probably last file.

It's a total niche edge case really, but I quietly assumed exactly the reverse behavior. Such quiet assumptions might lie behind the inconsistency. :-)

**Comment by mwoz123** [comment]
I don't understand why it's a separate thing that developers have to care about in their PRs ? 
Wouldn't it be better if it was dependend on history or at least history implementation will take care about handling (returning/changing) previous document ?

**Comment by Frenzie** [comment]
That literally what I just said? ;-)

**Comment by poire-z** [comment]
So, do I understand correctly if I get it this way:
- all ReadHistory methods (that add/delete/move/rename some item to/from history) should ensure `lastfile` exists - which could mean ReadHistory is the only one that does `G_reader_settings:saveSetting("lastfile", file)`
- all other code do not, and just call these ReadHistory methods without caring about managing lastfile
- all other code can still use `G_reader_settings:readSetting("lastfile")` (because otherwise, that would be too many unrelated changes :)

**Comment by poire-z** [comment]
OK, did that ^ in #6128.
