### ISSUE TITLE
[Feature request]: Export function for cropped & reflowed .pdf documents

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#6130]
* KOReader version: 2020.04.1
* Device: Kindle PW4 

#### Issue
Dear developers,

As we have high quality of pdf crop & reflow function of Koreader, I pop up an idea if we can export that result to *.epub or *.mobi for sharing purpose.

I did search but haven't found a similar application that can crop & reflow as good as Koreader and also there was no converting to other file type function ( keep the crop & reflow result).

It's fantastic if Koreader is embed that function or if we have another script/ plugin to do that task.

Thank you.

**Comment by Frenzie** [comment]
It depends on K2pdfopt as a library. You'll actually get the best results by running it on your PC. :-)

https://www.willus.com/k2pdfopt/

**Comment by uphantom89** [comment]
I did try K2pdfopt, the result was amazing. thank you.

My purpose is to share that converted file to my friends, those whose don't have a Jailbreaked kindle. So, It is much better if we can share it in .mobi extension. I'm wondering if it is possible to do so with K2pdfopt ( moreover, reading a pdf on original reader of kindle is not a nice experience as it refreshed every page T.T )

Thanks

**Comment by hius07** [comment]
If you have *.epub, you can rename it to *.png and send to your Kindle email.
You will get azw3.

**Comment by Frenzie** [comment]
@uphantom89 Trying to convert a PDF to something like EPUB is really quite different. I imagine the most mature set of tools for that purpose would be something like PDF → Word → EPUB.

Unless you mean creating an EPUB with hundreds of images rather than text? That might be possible, though it seems to me that just living with a screen refresh every page turn is by far the easiest option. You might have better luck asking on the MobileRead Kindle forum.

**Comment by uphantom89** [comment]
Yap. I got what you mean, thank you for your advice, then I would close this issue
