### ISSUE TITLE
Building koreader for Android fails: brotli

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6178]
* KOReader version: git from 23.May.2020
* Device: Android

#### Issue
Building koreader for Android fails with "file <brotli/decode.h> not found"

#### Steps to reproduce
./kodev build   ... works
./kodev run  ... works
./kodev build android ... fails with " <brotli/decode.h> not found"

The host on which koreader for Android should be built is a Gentoo system. Kernel 5.6.14, stable and up to date.

##### solution
After changing koreader/base/thirdparty/freetype2/CMakeLists.txt from
```set(CFG_OPTS "-q --prefix=${BINARY_DIR} --disable-static --enable-shared --with-zlib=no --with-bzip2=no --with-png=no --with-harfbuzz=no --host=\"${CHOST}\"")```
to
```set(CFG_OPTS "-q --prefix=${BINARY_DIR} --disable-static --enable-shared --with-zlib=no --with-bzip2=no --with-png=no --with-harfbuzz=no --with-brotli=no --host=\"${CHOST}\"")```

**Comment by NiLuJe** [comment]
That's... interesting. I've never seen that automagic check fail when cross-compiling. I haven't checked, but it *may* be defaulted to on on Android (because Google), which could explain this?

In any case, it's a fairly harmless change that I completely agree with, so, feel free to PR that (or not, if you don't want to bother, just say so, I'll roll that in the next time I touch the thirdparty folder).

**Comment by zwim** [comment]
Hello NiLuJe,
please could you roll it in. (I am new to github.)
Thank you
