### ISSUE TITLE
Footnotes and links tweaking options

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#6180]
* KOReader version: 2020.05
* Device: Kindle PW3 (5.9.7)

Guys, I have a few questions (please refer to an example screenshot below).

1) Can I make smaller margin between the text body and footnotes overhead line? I think there is actually enough space for one more line of body text.
I tried to tweak `body[name="notes"] { font-size: 90%;}` with margin top/bottom, but it has no effect.

2) How can I tweak the size of footnote number in the text, e.g. `[67]` in the example below? It's HTML source code shows that this is:
`<a l:href="#67" type="note">[67]</a>`
I am a little confused what tag to refer to in the css document, because there is `a[type="note"] { vertical-align: 25%; font-size: 50%; }`, but it doesn't change anything.

Thank you!

![Reader_2020-May-20_013704](https://user-images.githubusercontent.com/6279855/82742876-39637880-9d31-11ea-8387-4f1387b890b3.png)

**Comment by hius07** [comment]
2. This works for me, in fb2.css
a[type="note"] { vertical-align: 25%; font-size: 50% **!important**; }

**Comment by poire-z** [comment]
1) Smallest interspace I get on some Wikipedia article (where the amount of headers on a page can make that spacing variable between pages):
<kbd>![image](https://user-images.githubusercontent.com/24273478/82747275-9d208c80-9d97-11ea-84c2-2bca46632957.png)</kbd>

[The code](https://github.com/koreader/crengine/blob/3ad652ce69d941e9f7e50a5b9dedad3111432f50/crengine/src/lvdocview.cpp#L1973-L2030) looks like it uses 1rem (1 x the font size you set via the bottom menu, no matter how the book CSS might reduce/increase it - although I think FB2 don't do that) for the height of this margin. The margin includes the small line, that it draws at 2/3.
That's hardcoded. I don't think 1 line of text is too much and need to be reduced :)

It might also depend on what's on next page, if you are preventing widows and orphans (dunno if FB2 use that - or if you have enabled that via style tweaks): the line that looks like it could fit might have been pushed on the next page for some reason.

Or you're just at a limit, and a few pixels less would have another line brought to this page. You can try adjusting the top or bottom margin (I often have to do that to kill some bottom blank line on some books).

> I tried to tweak body[name="notes"] { font-size: 90%;} with margin top/bottom, but it has no effect.

That would set one margin at the top and one at the bottom of the whole `<body name="notes">`. You would need to set it on each individual footnote in that.
But I don't think you need to, as it looks like your individual footnotes already have margin top and bottom = 0.

--

> 2 It's HTML source code shows that this is:
`<a l:href="#67" type="note">[67]</a>`
I am a little confused what tag to refer to in the css document, because there is `a[type="note"] { vertical-align: 25%; font-size: 50%; }`, but it doesn't change anything.

Feels like it should.

We have this in fb2.css:
`a[type="note"] { vertical-align: super; font-size: 70%; text-decoration: none }`

(So, strange you get it underlined :)

> This works for me, in fb2.css `a[type="note"] { vertical-align: 25%; font-size: 50% !important; }`

Assuming FB2 does not really style things in the book, you wouldn't need the `!important` - but if it does, you need it on both properties:
`a[type="note"] { vertical-align: 25% !important; font-size: 50% !important; }`

You could also set it via a user style tweak to avoid hacking fb2.css.

**Comment by mergen3107** [comment]
Thank you very much guys!
I double-checked my custom fb2.css file that I use. I had (somehow?) such tag:
`a {display: inline; text-decoration: underline;}`
So I just commented it out and it let the font size change, but not the vertical align. The latter didn’t change with and without `!important` thing. It did change however once I set not the percentage, but `top` option for vertical-align. Now it looks pretty without breaking the interline spacing :) 

Regarding orphans/widows, no, this screenshot is amidst whole lot of text, so this line is not the last one. 

I tried to play around with top/bottom margins, but I don’t see any change below point 10 for top and point 5 for bottom. 

You are correct @poire-z, maybe there isn’t just enough space for the text + line spacing. This thing doesn’t bother me in most of footnote cases

**Comment by mergen3107** [comment]
Hm, interesting. I tried to set 100% for footnote font size and it actually looks a bit smaller than the body text. Why is that? Where is the first multiplier?

**Comment by hius07** [comment]
> I tried to set 100% for footnote font size and it actually looks a bit smaller than the body text.

There is a checkbox "Keep regular font size" in the Styles - Miscellanious - In-page footnotes - In-page fb2 footnotes menu.

**Comment by mergen3107** [comment]
Thank you! This worked! 
So many things to overlook :D
