### ISSUE TITLE
Problem with "Time range statistics"

### ISSUE THREAD

**Issue by christian-ho** [koreader/koreader#6190]
* KOReader version: v2020.05 
* Device: Kobo Clara HD

#### Issue
When opening book statistics with `Reading statistics - Time range - All books`, the point `Last opened` is alway the actual time and date, instead of the date the book was last opened.
See attached screenshot.

![image](https://user-images.githubusercontent.com/57492542/82833153-8a07dc80-9ebd-11ea-84b8-406424c8f209.png)

Furthermore the Total Pages is always "1".

This only affects books that have been read since version 2020.04.
Earlier books are displayed correctly.

**Comment by poire-z** [comment]
Looks like it's also related to the thing with nb of highlights & notes being NULL in the sqlite DB.
Noticed at https://github.com/koreader/koreader/pull/6052#issuecomment-629610275, fix for a book when opening it by #6173.
But for some past books opened/created between April 14 and May 20, and not re-opened yet, they have NULL in the DB, and the Time range statistics will use that:
https://github.com/koreader/koreader/blob/16e42116ee3b70daf715f0913b9367a783f028be/plugins/statistics.koplugin/main.lua#L1144-L1149

The problem is with the last line, the rowexect call should return 6 values:
`"the title", "the authors", nil, nil, Correct_nb_of_pages, correct_last_open_ts`

But there's a thing with Lua that I think it has hit me may times (but I can't find any link or doc about it right now :/) is that when there is a `nil` in a sequence of values, Lua stops reading what's after it. (Or may be its inside the rowexec code that would not push the 6 values?)
So, we get here:
"the title", "the authors", nil, nil, nil, nil`.

`pages` and `last_open` being nil (although they have values in the DB) makes what's observed on the screenshot.

Possible solutions - I really don't know which is the less ugly :)
A) SQLite only:
`SELECT title, authors, IFNULL(notes,0), IFNULL(highlights,0), pages, last_open`

B) re-order the SQL, so bogus notes and highlights are last, and don't kill the other values:
`SELECT title, authors, pages, last_open, notes, highlights`
and fix notes, highlights to be 0 if they are nil

C) some magic with Lua unpack/select or else (that I couldn't figure after a few minutes trying :)

**Comment by NiLuJe** [comment]
Yeah, the 'nil in a table is bad and breaks stuff in fun and interesting ways' issue has been annoying me in the past, too ;p.

I don't *think* I experimented with the stuff detailed in http://lua-users.org/wiki/StoringNilsInTables (I essentially went with B and/or a variant of it to paper over the issue).

**Comment by christian-ho** [comment]
Yes, I just noticed: If there are some notes or highlights in the book, the `Last opened` date and the `Total pages` are displayed correctly.
