### ISSUE TITLE
Functionality for saving embedded fonts to the KOReader fonts dir?

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6220]
* KOReader version: 2020.05
* Device: Kobo Forma

Would it be possible to add functionality for saving fonts embedded in an ebook to a directory of the user's choice? This would permit the user to also use this font when displaying other ebooks.

**Comment by poire-z** [comment]
Seriously ?! :)
Sorry, too much complicated and uninteresting work for a rarely needed feature.
When you can just open on your computer the EPUB as a zip file and extract the font files yourself :)

Beware that often, publishers include a "subset" font file, that contains just the glyphs needed by the book - so it may give not-found glyphs on other books. So that feature might lead to disappointment.

**Comment by smartscripts-nl** [comment]
I know I can extract fonts from ebooks on my computer. It just seemed handy to me to be able to do this in KOReader.

**Comment by NiLuJe** [comment]
Yeah, ripping subsetted fonts would be a mighty waste of time ;).

Plus, font obfuscation, licensing, and all that jazz.
