### ISSUE TITLE
Is it possible to contribute to KOReader?

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6222]
* KOReader version: 2020.05
* Device: Kobo Forma

Is there a manual somewhere how to contribute to KOReader? And do you accept new contributors?

I've written some things I think other users might also enjoy. For example:

1. A widget with utility functions to be able to write plugins faster, with less verbose code.
2. A random quote dialog. Quotes can be saved as such when highlighting text. Great for inspirational quotes.
3. A crash log viewer, which tries to filter irrelevant notifications out.
4. A list manager widget, which makes writing "list managers" a breeze. I've used it for example for writing plugins for managing todo's and one for memo's.

Maybe I could send my code to someone? I've thought myself Lua looking at the KOReader source code, so it can be that my code contains sub-optimal patterns... 😉

**Comment by pazos** [comment]
> Is there a manual somewhere how to contribute to KOReader? 

http://koreader.rocks/doc/

> And do you accept new contributors?

Of course :smile: 

> I've written some things I think other users might also enjoy [...] Maybe I could send my code to someone?

You can send a pull request to this github repo. Keep in mind that it will need to be reviewed before being merged.

I usually keep little, too specific, changes for myself. Because I don't think they will be useful for other people or because I don't want to pass the review process (and adding a bunch of options that I don't need but somebody else does).

I would suggest you to do the same. Start by little things that annoy you and are easy to do, like #6221. But, as a rule of thumb, any pull request is welcome.

**Comment by Frenzie** [comment]
> Is there a manual somewhere how to contribute to KOReader? And do you accept new contributors?

Always! There isn't much to it besides opening a PR (one per change/feature) and being prepared to enter into a dialog about it and to make some adjustments.
