### ISSUE TITLE
How to adjust the contrast of pictures in epub books

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#6230]
* KOReader version: v2020.05
* Device: Hisense A5

#### Issue
I downloaded a lot of manga in epub format. However, I can not find the option to adjust the contrast of the image in the manga epub file. How can I do this? I don't want to convert these files into cbz, there are thousands of them.

**Comment by NiLuJe** [comment]
That's because you can't ;).

**Comment by kingo132** [comment]
Thanks, I think I have to convert them into cbz now.

**Comment by poire-z** [comment]
@NiLuJe : in case you ever think about adding contrast support for images into crengine, please don't use the current contrast bar/setting as-is (x) -  I have it set heavy for my text/font, and I don't want to get my images blackened because of that ! :)
(x): but it could be another toggle to allow images to be applied the contrast set for text.

**Comment by NiLuJe** [comment]
@poire-z: Wasn't in the cards, but I'll keep that in mind nonetheless ;).
