### ISSUE TITLE
Chinese characters on Japanese text in dictionary

### ISSUE THREAD

**Issue by Geniusssmit** [koreader/koreader#6231]
* KOReader version: 2020.05
* Device: Pocketbook 740

#### Issue
When you're looking up Japanese word in Japanese-Japanese dictionary, font used in dictionary window is Chinese. This issue is very common and possibly easy to solve. Thing with fonts is there is Japanese and Chinese fonts but for some reason it's quite common to see Japanese text with Chinese font.
![anki_O2n8Y4HeOA](https://user-images.githubusercontent.com/24941285/83787242-28552880-a69c-11ea-9010-4ca7a8078291.jpg)
As you can see, sometimes characters look very different.
Possible solution will be - allow users to change fonts used in dictionary window
Good Japanese fonts:
[japanese fonts.zip](https://github.com/koreader/koreader/files/4731528/japanese.fonts.zip)

#### Steps to reproduce
Look up Japanese word

**Comment by Geniusssmit** [comment]
![image](https://user-images.githubusercontent.com/24941285/83788264-9bab6a00-a69d-11ea-8312-f8f8bddbc074.png)

**Comment by NiLuJe** [comment]
Wild guess: only happens in HTML dictionaries, because MuPDF, and we ship Noto-CJK with SC as the default variant?

**Comment by Geniusssmit** [comment]
> Wild guess: only happens in HTML dictionaries, because MuPDF, and we ship Noto-CJK with SC as the default variant?

I don't know about html dictionaries. I found few EPWING dictionaries converted into stardict format

**Comment by poire-z** [comment]
To know what kind of dict you have, look at `yourstartdictdict.ifo` file. If it has `sametypesequence=h`, it will be shown as HTML by MuPDF - for any other letter (=g, =t...), it will use our text rendering code.

If HTML dict, yes, MuPDF will use default Simplified Chinese.
But if your dictionary is text, you can get Japanese glyphs.

Our NotoSansCJK font has all localized glyphs for Chinese, Japanese, and Korean - but it defaults to Chinese unless requested otherwise.
We can't know the language of dictionaries, so we can't ask the font to use japanese glyphs, and it will use the default chinese glyphs.

We will only request japanese glyphs when KOReader's UI language has been set to japanese.
OR (if you never read chinese) if you add manually into settings.reader.lua:

`xtext_alt_lang = "ja",`

https://github.com/koreader/koreader/blob/a753f332dee5b190124af6819737a22c93006dc6/frontend/ui/bidi.lua#L72-L80

Use that, and you'll see japanese glyphs by default in the UI (except when you read Chinese Wikipedia or translate something to Chinese).

**Comment by Geniusssmit** [comment]
> To know what kind of dict you have, look at

I have that
```StarDict's dict ifo file
version=2.4.2
wordcount=534710
idxfilesize=11759276
bookname=daijirin
sametypesequence=m
```

**Comment by Geniusssmit** [comment]
> add manually into settings.reader.lua:

Where exactly should I paste that line?

**Comment by poire-z** [comment]
Make a backup of settings.reader.lua, and add it near the top, don't forget a comma at the end.
```lua
-- we can read Lua syntax here!
return {
    ["xtext_alt_lang"] = "ja",                       (add that line, without this :)
    ["auto_book_status"] = false,
    ["screen_dpi"] = 120,
[...]
```

**Comment by Geniusssmit** [comment]
> Make a backup of settings.reader.lua, and add it near the top, don't forget a comma at the end.
> 
> ```lua
> -- we can read Lua syntax here!
> return {
>     ["xtext_alt_lang"] = "ja",                       (add that line, without this :)
>     ["auto_book_status"] = false,
>     ["screen_dpi"] = 120,
> [...]
> ```

That worked, thanks!
