### ISSUE TITLE
Hanging Punctuation does not work, only the hyphen hangs.

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6235]
* KOReader version: 2020.05
* Device: Tolino Epos 2, Linux-Emulator

#### Issue
Hanging punctuation does not work. Only the "hanging" of the hyphen can be  toggled.
If you want hanging punctuation, you want all small characters (e.g. . , -  : ; ) to hang a bit  - and not only the hyphen.
I do prefer hanging punctuation (at least in German) and I am using it in my publications.

Please see the pictures:

Here the Hanging Punctuation is **turned off**. Note the hyphens and commata
![Hanging Punctuation turned off](https://user-images.githubusercontent.com/36999612/83843445-45721180-a705-11ea-960a-31a95aa4a75b.png)

Here the Hanging Punctuation is **turned on**. Note the hyphens and commata
![Hanging Punctuation turned on](https://user-images.githubusercontent.com/36999612/83843457-4c008900-a705-11ea-9abc-dc9dc7b2f908.png)

## Solution
At least for German it is possible to activate the hanging of punctuation marks by the following patch

```
--- work/lvtextfm.cpp	2020-06-05 08:29:31.557364010 +0200
+++ koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp	2020-06-05 08:34:38.299067829 +0200
@@ -2987,12 +2986,13 @@
                         if ( word->flags & LTEXT_WORD_CAN_HYPH_BREAK_LINE_AFTER ) {
                             word->width -= font->getHyphenWidth(); // TODO: strange fix - need some other solution
                         }
-                        else if ( lastc=='.' || lastc==',' || lastc=='!' || lastc==':' || lastc==';' || lastc=='?') {
+                        else if ( lastc=='.' || lastc==',' || lastc=='!' || lastc==':' || lastc==';' || lastc=='-' || lastc=='<' /*|| lastc==0xAB *//*'«'*/ ) {
                             FONT_GUARD
-                            int w = font->getCharWidth(lastc);
+                            int w = (font->getCharWidth(lastc)+1)/2; // half of the character-width, rounded up integer divison no truncation
                             TR("floating: %c w=%d", lastc, w);
-                            if (frmline->width + w + wAlign + x >= maxWidth)
+//                            if (frmline->width + w + wAlign + x >= maxWidth)  // this line has to be removed!!!!
                                 word->width -= w; //fix russian "?" at line end
+                                
                         }
                         else if ( lastc==0x2019 || lastc==0x201d ||   // ’ ” right quotation marks
                                   lastc==0x3001 || lastc==0x3002 ||   // 、 。 ideographic comma and full stop
```

Some remarks to the patch:
1. I do not want the punctuation marks with their full character width. Instead it looks better if they hang only half of their width. This is done with
```
                          int w = (font->getCharWidth(lastc)+1)/2; 
```
"+1)/2" is for rounding the integer division up!!

2. The equation
```
 (frmline->width + w + wAlign + x >= maxWidth)  
```
is always false (at least for my German books). So remove it (at least in German) and hanging punctuation works.

At last two pictures with

**Optimized Hanging Punctuation:** I love this!
![HangingHyphenAndOptimizedHangingPunctuation](https://user-images.githubusercontent.com/36999612/83845291-da2a3e80-a708-11ea-9c72-255bb426c062.png)

**Full Hanging Punctuation:** does not look so good
![HangingHyphenAndHangingPunctuationFull](https://user-images.githubusercontent.com/36999612/83845340-f332ef80-a708-11ea-80b0-0985289497f2.png)

**Comment by Frenzie** [comment]
> I do not want the punctuation marks with their full character width. Instead it looks better if they hang only half of their width. This is done with

I agree with that. Also see what's by now somewhat of a standard document around here whenever this subject comes up: http://www.tug.org/TUGboat/Articles/tb25-1/thanh.pdf

A problem might be that the current implementation of hanging punctuation might be mainly for East Asian languages but @poire-z probably has a better handle on the details.

**Comment by poire-z** [comment]
Yes, our hanging punctuation handling has many issues (#2844).
Some details and experimentation at https://github.com/koreader/koreader/issues/2844#issuecomment-464483142 .
I have plans and thoughts to do that better (hang in the existing margin instead of adding some padding, delegate decision and hanging ratio to the new textlang.cpp so it can be tweaked by typography language, ...)
More thoughts and links in https://github.com/koreader/crengine/issues/307 ("Hanging punctuation / Optical margin alignment"), and I'm waiting for feedback on how it's expected for CJK in https://github.com/koreader/koreader/issues/6162.

I agree the ratio of hanging should depend on the character. That [microtypography thesis](http://www.pragma-ade.nl/pdftex/thesis.pdf) (by the same author of the link given by @Frenzie above) gives some ratios, that I think we could start with:

<kbd>![image](https://user-images.githubusercontent.com/24273478/83847793-24adba00-a70d-11ea-9f41-1280fbf018f4.png)</kbd>

**Comment by zwim** [comment]
Hi,
thank you for the microtypography thesis. For a proof of concept I have implemented the values from above. The layout looks really nice with now. Please keep on working on a sane implementation of the hanging punctuation. Of course, you do not see any effects on values with 50, because the character-width times factor is lower than zero on my Laptop-Screen. On a high-DPI e-ink Display it would look even better.

Screenshot with new character protruding factors (from the thesis).
![Bildschirmfoto_2020-06-05_19-20-56](https://user-images.githubusercontent.com/36999612/83905345-ca8b1400-a761-11ea-8a03-88a03a8191e6.png)

**Comment by poire-z** [comment]
I'm still wondering whether this hanging punctuation stuff should be done in the "processParagraph" step (**A**) (where we cut the source text to make lines that fit in the nominal width) like it is currently, or if we could just delay it to the "alignLine" step (**B**) (where we apply text alignment and word expansion, where we just position words on the x-axis on the line).

Doing it in **A** (as we do currently) would allow to notice we have a bit more width for this line, and possibly bring another char to this line - but given that we'll only gain at most (with the values above) 70% of the width of `"` and 70% of the width of the hyphen, we will never hardly gain much, at most the width of the letter `o` :)
It's also quite a bit more expensive doing it here, as we'd need to compute the extra width for a few chars by lines (all, or just those when we nearly reach the nominal width, I dunno yet).
Also, with **A**, toggling hanging punctuation would request a full re-render (because it can change the number of lines a paragraph will use).
But it needs to be done in **A** if we want to have it for CJK to possibly have it as a rescue tool to avoid breaking the line early and have to fill in for 2-3 CJK fullwidth chars with spaces. But with the nearly no comment about hanging punctuation in #6162, and the linked site stating its not super welcomed, we might drop it for CJK (if I manage to use the other rules like reducing punctuation widths to get a better fit).


Doing it in **B** is a lot simpler: the line is already cut, we would just have to get the extra width for the first and for the last characters, and align words on the nominal+extra width, so possibly expanding a bit the space characters in there to push some fraction of the first and of the last chars in the margin. Which might be hardly noticable given the small extra width.
Also, it would not need a full re-render (like font hinting and word expansion do not need it either).

Any thoughts ?

**Comment by zwim** [comment]
I have no opinion about CJK, so I won't give any suggestions.

For Latin letters and Arabic numbers:
Most of the times the extra-width will lead to bigger spaces (or word expansion) so **A** or **B** will show the same results. 

Let's think about the case where we gain the most space:

A `"` at the start of a line and a hyphen at the end: 
We have space for one letter more. The letter has to come from the other line. 
This is only possible if the word could be hyphenated at the letter after the actual hyphen too. Looking in the origin of the hyphenation patterns there are at least 2 percents of words that do have such hyphenation possibilities. Looking deeper might give another 1 percent.
I think in very rare cases the typesetting can be improved with Method **A**.

The overhead of re-rendering the whole document when toggling the hanging-hyphenation is not done regularly, so the time overhead should be no problem.

I would say: 

- Go for **B**, if it is much easier to implement as **A**. Then there is no need to drop CJK now.
Time, readers and comments will show, if the hanging punctuation can be improved.

- Go for **A**, if the effort is similar. The result will be better.

**Comment by poire-z** [comment]
I went playing with **B** with https://github.com/koreader/crengine/pull/355. Please follow up the discussion there.
Please grab it as a [patch](https://github.com/koreader/crengine/pull/355.patch) and have a try.
