### ISSUE TITLE
Screensavers on Kindles with Special Offers

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#6249]
KOReader screensavers are disabled on SO Kindles.
Is it by "commercial" or technical reasons?

**Comment by NiLuJe** [comment]
That's on purpose, yes ;).

**Comment by poire-z** [comment]
That's a bit short for an answer :/ But you can do shorter :) : 
A) Was there a technical limitation/impossibility ?
B) Or we could, but we deciced that if the device is SO, we should not propose our own screensaver to not override/kill _Amazon_'s business, for legal reasons and so that _they_ don't ever come at us?

And if B) only, even if we still don't ship a workaround (and we would still revert any user tweak on the next KOReader update), and neither tell how one could do it, how complicated would it be for a user to go at patching his own device to have it, so it's him who takes the legal responsability?

C) did I already think and ask too much with this post, and will _they_ come at me ? :/ :)

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader/pull/2734#issuecomment-292855929

**Comment by hius07** [comment]
I've been aware of Mobileread attitude to the question and was just curious about the KOReader team opinion.
Technically, on my PW2 with SO I switch off the ad screen with a script
```
#!/bin/sh

source /etc/upstart/functions
source /etc/upstart/blanket_functions
f_blanket_unload_module ad_screensaver
f_blanket_unload_module ad_screensaver_active
f_blanket_load_module screensaver

```
This gives me the KOReader screensaver (until reboot of the device).
BTW, the code is taken from the CoolReader start script.
