### ISSUE TITLE
Zsync(plugin) menu not visible on the file manager

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#6265]
* KOReader version: v2020.05
* Device: Xiaomi Mi A2 Lite(Android 8.1.0) - arm cortex a53 cpu

#### Issue
When going to tools(the third one) menu after `wallabang` I expect to see `zsync` entry. I couldn't find similar issue and at first glance, there isn't anything preventing android from adding zsync to menu. It's available to turn on/off in `Plugin Management`, although checking/unchecking it doesn't change anything.

**Comment by pazos** [comment]
The plugin is there but [just on the reader](https://github.com/koreader/koreader/blob/master/plugins/zsync.koplugin/main.lua#L19). I think that make some sense for "publishing a document", because the document published is the one opened,but the other option used to subscribe could be available on the FM as well.

I don't know if there's a technical reason for that.

**Comment by Galunid** [comment]
Makes sense, I was looking for "Subscribe button", because I wanted to share book from my reader and didn't realize it required document to be opened.
