### ISSUE TITLE
Sometimes dictionary window won't open

### ISSUE THREAD

**Issue by Geniusssmit** [koreader/koreader#6303]
* KOReader version: v2020.06-8-ga9d4e97_2020-06-19
* Device: Pocketbook 740

#### Issue
Sometimes dictionary window won't open until I click on in after looking up word. After clicking, it goes to the next dictionary.
#### Steps to reproduce
Happens sometimes if you try to not only press, but manually highlight any word and look it up
Video: https://drive.google.com/file/d/1SavwrrEYGIz3MUG3W5tOPsUDQ83Dx6Vi/view

**Comment by Frenzie** [comment]
It's unfortunately a known issue. See for example https://github.com/koreader/koreader/issues/5550 and https://github.com/koreader/koreader/pull/3540

The problem is PocketBook devices apparently enter suspend after the screen hasn't been touched for a second, so if looking up a term in the dictionary takes a tiny bit long than that, you'll get that.

**Comment by Geniusssmit** [comment]
is it possible to fix?

**Comment by Frenzie** [comment]
#3540 shows a possible workaround, but only someone who has a PocketBook device can properly work on it.

**Comment by Geniusssmit** [comment]
I see. Unfortunately I can't code myself, but I will test anything on my pocketbook 740

**Comment by pazos** [comment]
Duplicate of #3561
