### ISSUE TITLE
Question: Is it possible to make highlighting more responsive?

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#6381]
Today, out of curiosity I tried Plato for the first time and highlighting there is way more responsive. I'm not sure how it works in KOReader, but I wonder if it's possible to achieve a similar effect. While it could have problems with ghosting, I believe it would make a huge difference on android.

**Comment by Frenzie** [comment]
Suppressing the black flash would probably do most of the trick, but given that it's indeed somewhat slow on non-E Ink desktop/Android there might be a bigger performance bottleneck somewhere else.

**Comment by poire-z** [comment]
No real idea. I don't personally find it slow - or not slow enough for something that is not used that often.
Is it the same for PDF and EPUB ?
Might also be worth being sure feeling it after a KOReader restart - as memory usage can induce slowness.

A few thoughts:

Text selection in CRE gets the drawing-of-highlights-while-selection-in-progress done by crengine, so redrawing the whole page image. I believe this wouldn't add much slowness. If you'd like to have that done for CRE just like it is done for PDF, this seems to work (with some caveats, and the highlight boxes are a bit uglier - anyway, that's just for testing):
```diff
--- a/frontend/document/credocument.lua
+++ b/frontend/document/credocument.lua
@@ -310,3 +310,3 @@ function CreDocument:getWordFromPosition(pos)
     logger.dbg("CreDocument: get word box", word_box)
-    local text_range = self._document:getTextFromPositions(pos.x, pos.y, pos.x, pos.y)
+    local text_range = self._document:getTextFromPositions(pos.x, pos.y, pos.x, pos.y, false)
     logger.dbg("CreDocument: get text range", text_range)
@@ -338,6 +338,6 @@ end
 function CreDocument:getTextFromPositions(pos0, pos1)
-    local text_range = self._document:getTextFromPositions(pos0.x, pos0.y, pos1.x, pos1.y)
+    local text_range = self._document:getTextFromPositions(pos0.x, pos0.y, pos1.x, pos1.y, false)
     logger.dbg("CreDocument: get text range", text_range)
     if text_range then
-        -- local line_boxes = self:getScreenBoxesFromPositions(text_range.pos0, text_range.pos1)
+        local line_boxes = self:getScreenBoxesFromPositions(text_range.pos0, text_range.pos1, true)
         return {
@@ -346,3 +346,3 @@ function CreDocument:getTextFromPositions(pos0, pos1)
             pos1 = text_range.pos1,
-            --sboxes = line_boxes,     -- boxes on screen
+            sboxes = line_boxes,     -- boxes on screen
         }
@@ -1273,4 +1273,4 @@ function CreDocument:setupCallCache()
             elseif name == "highlightXPointer" then add_buffer_trash = true
-            elseif name == "getWordFromPosition" then add_buffer_trash = true
-            elseif name == "getTextFromPositions" then add_buffer_trash = true
+            elseif name == "getWordFromPosition" then no_wrap = true
+            elseif name == "getTextFromPositions" then no_wrap = true
             elseif name == "findText" then add_buffer_trash = true
```
With this, the drawing of the boxes is done by ReaderView. Many other things might then not work well, like selecting text on multiple pages.

It also looks like we refresh/redraw the whole page for each finger move/selection modification (`UIManager:setDirty(self.dialog, "ui")` in `ReaderHighlight:onHoldPan()` )- so this might add some overhead - I guess that we could guess the area being affected (the rect that contains all the line boxes, previous selection area + new selection area) and only refresh this small area (or just `UIManager:setDirty(each small area, "fast")` would have UIManager merge all these small rects into a biger one to refresh) - but on SDL, this will result in a full window redraw anyway I guess (dunno about Android - on eInk, it's possible the hardware would detect what has changed and what has not and either way won't cost much).
That might be what Plato is doing with `hub.send(Event::RenderRegion(rect, UpdateMode::Fast)).ok();` in 
https://github.com/baskerville/plato/blob/2ee3009b5306b3b4a36557367643bffd6528f0c6/src/view/reader/mod.rs#L2527-L2582

Anyway, that was just a quick look. I got the initial feeling, and still get it now, that this would need quite some work and quite possibly will cause many new bugs or edge cases to handle - and that I'd rather not touch something that work :)

But may be the issue is at another level, dunno.

**Comment by Galunid** [comment]
```
fast: low fidelity refresh (e.g., monochrome content).
      Should apply to most highlighting effects achieved through inversion.
      Note that if your highlighted element contains text,
      you might want to keep the unhighlight refresh as "ui" instead, for crisper text.
      (Or optimize that refresh away entirely, if you can get away with it).
```
I assume this is because we don't really 'invert', but draw(?), thus it doesn't work. I'm pretty certain that if I can change from drawing to inverting, it would work as planned. Any idea which function handles this? I took a look at `ReaderHighlight:onHoldPan`, which I assumed responsible, but I don't see where I can specify

**Comment by poire-z** [comment]
https://github.com/koreader/koreader/blob/a8da762955c230dd731cdc0d40244bd400c7509c/frontend/apps/reader/modules/readerhighlight.lua#L771
But we're still indicating it has to refresh self.dialog = ReaderUI = the full screen.

Might try commenting this one out, and add small ones into `ReaderView:drawTempHighlight(bb, x, y)` for each box : `UIManager:setDirty(box, "fast")` - or more generically in `ReaderView:drawHighlightRect()`

**Comment by poire-z** [comment]
> Also, it doesn't matter if it's epub/pdf and it's not problem with high memory.

So, keep testing/experimenting with PDFs - as it will put the crengine specifics out of the equation.

> Not sure if you're familiar with highlighting in Plato/MoonReader, but the text is highlighted almost instantly, there is no "lag". 

I'm not familiar with them.
Dunno about MoonReader, but if it's Android, it may use Android html layout facilities and have that done more natively - while we're just drawing bitmap and giving that to Android.
For Plato, we can look at its code - but I don't really read Rust and the part I linked to above is a bit obscure to me.
It might also be that Plato, when you extend the selection, just refresh/redraw the added (or removed) part since the previous movement/drawing - instead of refreshing the whole rectangle that enbody the full selection (which we would do with my individual setDirty for each small box suggestion above).

**Comment by NiLuJe** [comment]
For context, Plato's using a pure-black highlight, which means it can then do that with A2 updates.

On the other-hand, we're using a gray highlight, which prevents using A2, meaning it'll be a tad slower (especially on older devices), but which prevents ghosting.

I'm not a heavy highlighter, so I don't particularly care, and I'd tend towards preventing ghosting on that front.

What I do really like about Plato's highlight system is the selection mechanism: it's tap-based. You tap somewhere before the start of your HL? That's the new start of the HL. You tap somewhere after the end of your HL? That's the new end of you HL? (And vice-versa to make a HL smaller).

The lack of chrome makes it somewhat clunky to grok at first (i.e., there could be handles ala Nickel to hint that this can work), but it's extremely efficient in practice.

----

Nickel itself recently switched to black highlight w/ A2, and it's a hilarious mess of ghosting on a H2O, for instance ^^.

**Comment by Galunid** [comment]
Tested on Kobo Clara HD/Xiaomi A2 Lite/Kindle PW3/Emulator, I'm often highlighting stuff, so I kind of bugs me. I changed refresh mode on emulator to `fast`, but it was comparable to `ui` refresh speed. I assume A2 refresh is called `fast` in KOReader(probably in Plato too). Side note, `ReaderView:drawTempHighlight(bb, x, y)` takes `bb` as argument, I'm not sure where I can get it from, in `readerhighlight.lua`. I assume it's `BlitBuffer`, but I'm clueless as to what provides it. I have yet to get familiar with how UI is rendered.

**Comment by Frenzie** [comment]
@Galunid Refresh modes will have no impact on the emulator, only on an actual device. (Also see my original reply. :-) )

**Comment by NiLuJe** [comment]
On most probably only a meaningful one on a non-Android eInk device, at that ;).

**Comment by poire-z** [comment]
> takes bb as argument, I'm not sure where I can get it from, in readerhighlight.lua. I assume it's BlitBuffer, but I'm clueless as to what provides it. I have yet to get familiar with how UI is rendered.

It all starts there:
https://github.com/koreader/koreader/blob/9a5b659a468f51ac94ead904361553ca7f01e49e/frontend/ui/uimanager.lua#L1010-L1017
But that's not even true :) It starts when a widget calls UIManager:setDirty() :)

UIManager is where everything happens - and it's really tough to get into.
The main idea is that:
- Widgets must have a paintTo() method, but no widget calls it directly.
- Widgets, when something changes and has to be (re)drawn, use `UIManager:setDirty(the_region_that_needs_redraw, refresh_type)`
- UIManager just stores all the setDirty it has gotten
- Some code runs, other widgets change stuff, calls setDirty() too
- When KOReader gets idle (no code running), UIManager notices it has some stacked dirty region to refresh: it computes a single region that encompasses all these little regions (which often comes down to being the full screen): if then calls on all the widgets it knows off (those we called UIManager:show() on them) their paintTo(Screen.bb) methods
- Each top widget calls their paintTo(Screen.bb, x, y) on each of its own subwidgets (with x/y adusted to the x/y coordinates of the subwidget in the top widget coordinates) - recursively. For most widgets, the paintTo method is just inherited from some *Container widget, and just call its subchildren paintTo() - but some (rare) ones have a paintTo() method that actually draws some line or rectangle or text on the provided Screen.bb
- Once all that is done, UIManager gives the Screen.bb (I guess it's just shared with) to the hardware, and tells the hardware it has to refresh a (x,y,w,h) region with such mode (ui, fast, partial, full) - which might be multiple small regions, not sure if it's always coalesced into a single embodying one
- The hardware draws that region on the screen, and the user sees what has been changed at step 2 above :)

I have no experience with other UI/drawing stack, but I still find the above behaviour full of genius :)

It's optimized for eInk, so on Android and the emulator, the region stuff might be of no-use, and the full Screen.bb bitmap is always drawn/copied/transfered to the hardware buffer - so it might be you won't really notice some improvement on Android and the emulator.
Doing small setDirty for each new/old highlight parts might have some huge noticable effect only on eInk devices :/

So, on the emulator, your only visual help to guess your changes can have some improvement on eInk is to look at this when you highlight:
```
07/17/20-19:21:31 DEBUG refresh on physical rectangle 0 0 600 610
07/17/20-19:21:32 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
07/17/20-19:21:32 DEBUG refresh on physical rectangle 0 0 600 610
07/17/20-19:21:33 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
07/17/20-19:21:33 DEBUG refresh on physical rectangle 0 0 600 610
07/17/20-19:21:33 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
07/17/20-19:21:33 DEBUG refresh on physical rectangle 0 0 600 610
07/17/20-19:21:34 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
07/17/20-19:21:34 DEBUG refresh on physical rectangle 0 0 600 610
07/17/20-19:21:35 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
07/17/20-19:21:35 DEBUG refresh on physical rectangle 0 0 600 610
```
The above is possibly what makes it slow.
If you can get it to have small non-fullscreen rectangles like this, you might expect some speedup on eInk:
```
07/17/20-19:21:36 DEBUG _refresh: Enqueued ui update for region 26 219 100 12
07/17/20-19:21:36 DEBUG refresh on physical rectangle 26 219 100 12
```
But I don't think that from ReaderHighlight (that sets the setDirty) and ReaderView (that gets the painTo that will draw the highlight boxes), it's easy to guess the boxes differences (from new highlight vs previous highlight) to do the appropriate small setDirty. (Another idea I'd look at is to not just do any setDirty and find a trick so UIManager still draws, and ReaderView would when painting issue the setDirty - but I have no idea if it's a good idea :)

**Comment by Frenzie** [comment]
Btw, if you emulate reader flash, for example with `EMULATE_READER_FLASH=100 ./kodev run -s=kobo-aura-one` (or a value like 300 or 400 to make it even more obvious) you can also get some potential idea for how the full refresh can affect things.

**Comment by NiLuJe** [comment]
> (Another idea I'd look at is to not just do any setDirty and find a trick so UIManager still draws, and ReaderView would when painting issue the setDirty - but I have no idea if it's a good idea :)

There's `UIManager:widgetRepaint` for this kind of trickery (i.e., repainting a widget/subwidget, but not refreshing) ;). It's used very sparingly for icon highlights, IIRC.

FWIW, qeueing *many* small refreshes is not necessarily an issue. I think I've posted a strace of the Kindle virtual keyboard at one point, and it's doing *a lot* of those, and it's still snappy as hell.

What might be counter-intuitive is that a refresh is actually pretty cheap and fast. It's just what's visible on screen, and what might *feel slower. But it'll be faster than drawing in almost every case.

----

And, yeah, on eInk, Screen.bb is the hardware framebuffer. And since drawing is separate from refreshing the screen, we can do all kinds of fun things to cheat the performance impact of either ;).

**Comment by Galunid** [comment]
Thanks for your answers, I guess it's not about drawing, but about how often `onHoldPan` gets called
```
07/18/20-16:43:42 DEBUG onHoldPan called
07/18/20-16:43:42 DEBUG onHoldPan called
07/18/20-16:43:43 DEBUG onHoldPan called
07/18/20-16:43:43 DEBUG onHoldPan called
07/18/20-16:43:44 DEBUG onHoldPan called
07/18/20-16:43:44 DEBUG onHoldPan called
```
It seems the event gets called every 0.5 second if I move the mouse around. This is probably what causes the "lag" I referred to. Not sure if it's possible to increase the frequency of this event. I tried to recursively grep for `HoldPos` in frontend directory, but I didn't find anything useful. No idea if it's possible to decrease the interval to 0.25/0.1s and what the implications would be.

**Comment by poire-z** [comment]
Uh, if it's just that that will solve your feeling of slowness, you already have it :)
`Gear > Tap and gestures > Gestures interval > Pan delay interval`
which has a default of ... 500 ms :)

**Comment by Galunid** [comment]
Well yes, but actually no 😄. I tried to change that, but the `HoldPan` event is emitted every 0.5s, regardless of that setting(I set it to 100ms and 2000ms and neither was respected). Perhaps `Pan` and `HoldPan` are treated as separate events and there is no control over `HoldPan`?

**Comment by poire-z** [comment]
More adventures and parts of the code to discover :)
https://github.com/koreader/koreader/blob/62daa7b7839f6ecf4910939f46f1723586bb7943/frontend/apps/reader/modules/readerhighlight.lua#L77-L79
https://github.com/koreader/koreader/blob/62daa7b7839f6ecf4910939f46f1723586bb7943/frontend/ui/gesturerange.lua#L43-L54

**Comment by poire-z** [comment]
We have a setting that adapts some pan rate for eInk vs others:
```
frontend/apps/reader/readerui.lua:    local pan_rate = Screen.low_pan_rate and 2.0 or 30.0
frontend/ui/elements/screen_eink_opt_menu_table.lua:            checked_func = function() return Screen.low_pan_rate end,
frontend/ui/elements/screen_eink_opt_menu_table.lua:                Screen.low_pan_rate = not Screen.low_pan_rate
frontend/ui/elements/screen_eink_opt_menu_table.lua:                G_reader_settings:saveSetting("low_pan_rate", Screen.low_pan_rate)
frontend/ui/widget/frontlightwidget.lua:    rate = Screen.low_pan_rate and 3 or 30,     -- Widget update rate.
frontend/ui/widget/frontlightwidget.lua:        if Screen.low_pan_rate then
frontend/device/generic/device.lua:    local low_pan_rate = G_reader_settings:readSetting("low_pan_rate")
frontend/device/generic/device.lua:    if low_pan_rate ~= nil then
frontend/device/generic/device.lua:        self.screen.low_pan_rate = low_pan_rate
frontend/device/generic/device.lua:        self.screen.low_pan_rate = self.hasEinkScreen()
```
may be it should be used too for highlight pan

**Comment by Galunid** [comment]
Thanks a ton, works exactly as I want it. I played around a bit, and `20.0` is too much overkill. `10.0` gives fluent highlighting on emulator, `5.0` and `10.0` don't give any noticeable difference on my Kobo Clara HD, because of refresh rates, which can't keep up. It seems reasonable to check for `low_pan_rate` in `readerhighlight.lua` as it will give android/emulator 15 times speed boost when highlighting, which is pretty significant.

**Comment by Galunid** [comment]
I'll try to add another setting for `hold_pan` when highlighting sometime in the near future as well as make `readerhighlight.lua` respect `Screen.low_pan_rate` if it's desirable.
