### ISSUE TITLE
KOReader crash while downloading large files in kobo clara hd

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#6390]
* KOReader version: v2020.06
* Device: kobo clara hd

#### Issue
I'm downloading some books through ftp function in koreader. Some books are small, some are large, approximately 100 ~ 200 MB. Small files are fine, but when I tried to download the large file. The koreader will crash every time. I dumped the crash.log. It seem there's not enough memory. However, I think it's better to display some error message about low memory than just crash.

#### Steps to reproduce
1. Open the cloud storage functionality in the menu and connect to some ftp server
2. Download large file from the ftp server
3. KOReader crash after several seconds of stuck

##### `crash.log` (if applicable)
udhcpc (v1.22.0.kobo) started
Sending discover...
Sending discover...
Sending select for 192.168.50.188...
Lease of 192.168.50.188 obtained, lease time 86400
adding dns 192.168.50.1
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=3.046 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 3.046/3.046/3.046 ms
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=6.213 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 6.213/6.213/6.213 ms
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=24.635 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 24.635/24.635/24.635 ms
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=1.678 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.678/1.678/1.678 ms
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=6.440 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 6.440/6.440/6.440 ms
./luajit: not enough memory
!!!!
Uh oh, something went awry... (Crash n°1: 06/21/20 @ 00:24:15)
Running FW 4.21.15015 on Linux 4.1.15-00089-ga2737fc02713 (#34 SMP PREEMPT Fri Dec 27 17:47:13 CST 2019)
Attempting to restart KOReader . . .
!!!!

**Comment by NiLuJe** [comment]
Gah, keep forgetting Clopud Storage isn't a Plugin ;p.

Probably nothing much we can do about it, LuaSocket probably sinks the data in full into a memory buffer before flushing that to disk, so it's likely to require something like once or twice the filesize in available memory. Since the Clara probably only has something like 512MB of RAM, kablooey.

**Comment by NiLuJe** [comment]
(As such, flagging "cant fix", although it's probably technically fixable, but not without massive refactoring in code we don't own).

**Comment by poire-z** [comment]
May be it's only just us who do it wrong:
https://github.com/koreader/koreader/blob/62daa7b7839f6ecf4910939f46f1723586bb7943/frontend/apps/cloudstorage/ftpapi.lua#L23-L32

Because the ltn12 module seems to have sinks, pumps, marshmallows and unicorns, including:
> ltn12.sink.file(handle, message)
Creates a sink that sends data to a file. 

http://w3.impa.br/~diego/software/luasocket/old/luasocket-2.0-beta3/ltn12.html
http://lua-users.org/lists/lua-l/2013-12/msg00439.html
http://lua-users.org/wiki/FiltersSourcesAndSinks

(Not interested in investigating this, but this module looks fun :)

**Comment by Frenzie** [comment]
@NiLuJe LuaSocket isn't forced to keep it in memory, as @poire-z says that's just what it's told to do in this case.

Do it like this and it just writes it:
https://github.com/koreader/koreader/blob/62daa7b7839f6ecf4910939f46f1723586bb7943/frontend/ui/widget/opdsbrowser.lua#L559
