### ISSUE TITLE
Japanese keyboard dakuten and handakuten

### ISSUE THREAD

**Issue by gestra** [koreader/koreader#6402]
* KOReader version: v2020.07
* Device: Kobo Aura One, Linux AppImage

The dakuten (ﾞ) and handakuten (ﾟ) buttons on the Japanese keyboard layout don't work the way I'd expect. The dakuten and handakuten are usually placed at the top right corner of kana characters to alter their pronunciation, as in は->ば or は->ぱ.

The dakuten button inserts a standalone dakuten mark which is fairly useless.

The handakuten button changes they keyboard to dakuten (not handakuten) mode, adding dakuten to the characters it's usually attached to.

Thus there seems to be no way to type characters with handakuten attached. The way this probably should work is that the dakuten button toggles dakuten mode and the handakuten button toggles handakuten mode.

![dakuten](https://user-images.githubusercontent.com/6391580/87907628-a1061d80-ca6d-11ea-8955-f731e9a7e93c.png)

![handakuten](https://user-images.githubusercontent.com/6391580/87907677-b9763800-ca6d-11ea-895b-8f586ae3df7d.png)

**Comment by Frenzie** [comment]
Another option could be to use this one instead http://www.fileformat.info/info/unicode/char/3099/index.htm

You then type a character and press it afterward.
![Screenshot_20200720_092418](https://user-images.githubusercontent.com/202757/87910756-d2c9b500-ca6a-11ea-8432-cd1a7d191d04.png)

PS I'm definitely not saying that's how it should be. I don't know nearly enough about Japanese or Japanese input methods for that. Just making sure you know it's an option. ;-)

**Comment by poire-z** [comment]
(Disclaimer: I don't know what I'm talking about and if I make readable english with my use of hiragana, dakuten and handakuten :)

https://en.wikipedia.org/wiki/Dakuten_and_handakuten
```
U+3099 ◌゙ COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK
U+309A ◌゚ COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
```
It looks like there are straight unicode codepoint for the hiragana with dakuten - but not for them with handakuten:
https://www.compart.com/fr/unicode/scripts/Hira
 https://www.compart.com/fr/unicode/U+3061 ち
 https://www.compart.com/fr/unicode/U+3062 ぢ

https://github.com/koreader/koreader/blob/master/frontend/ui/data/keyboardlayouts/ja_keyboard.lua looks may be why it uses straight glith for the dakuten, but combining (not working) with the handakuten ?
It looks even more wrong, because clicking on the dakuten " key insert a non-combining one.
And clicking on the handakuten ° switches to a layout that actually shows ... dakuten'ed glyphs.

So, this might need fixing. And wondering if you'd prefer:
- dakuten to show a layout with all dakuten glyphs - and handakuten being combining: you type a hiragana, then the handakuten key, and it adds the handakuten to the hiragana glyph
- have both dakuten & handakuten be combining and work the same way: you type a normal hiragana, then either the dakuten or handakuten key to add it to the previous normal hiragana

**Comment by gestra** [comment]
I'm still only learning Japanese myself so you shouldn't give too much weight to my opinion. But I think I'd prefer both dakuten and handakuten to work the same way, so the latter option.

**Comment by poire-z** [comment]
https://www.wikiwand.com/en/Hiragana#/Unicode
> All combinations of hiragana with dakuten and handakuten used in modern Japanese are available as precomposed characters, and can also be produced by using a base hiragana followed by the combining dakuten and handakuten characters (U+3099 and U+309A, respectively). This method is used to add the diacritics to kana that are not normally used with them, for example applying the dakuten to a pure vowel or the handakuten to a kana not in the h-group. 

https://en.wikipedia.org/wiki/Dakuten_and_handakuten
> The combining characters are rarely used in full-width Japanese characters, as Unicode and all common multibyte Japanese encodings provide precomposed glyphs for all possible dakuten and handakuten character combinations in the standard hiragana and katakana ranges. However, combining characters are required in half-width kana, which does not provide any precomposed characters in order to fit within a single byte. 

And indeed there are pre-composed glyphs with handakuten:
<kbd>![image](https://user-images.githubusercontent.com/24273478/88053715-8a8abf80-cb5c-11ea-95e2-d75625e8c95b.png)</kbd>

So, if the handakuten does not really in practice combine with every glyph on the first panel, may be it does not deserve its own panel.
And if not all glyphs get the dakuten, may be the allowed/usual glyph+dakuten and glyph+handakuten can be made available on that same other panel.

And/or you could add 2 keys to get the combining dakuten & handakuten glyphs that one can add to any other hiragana glyph.

And/or, you could add them as popup of the regular hiragana keys, like we did for english and arabic with accentuated letters - that would be more practical I guess.

Anyway, as I don't understand japanese at all, and I can't really edit and type these characters I know nothing about, this would have to be done by someone who do :)
It's just a matter of studying how it's done in https://github.com/koreader/koreader/tree/master/frontend/ui/data/keyboardlayouts and trying to update ja_keyboard.lua.

**Comment by cyphar** [comment]
Actually, it might make sense to mirror the flick (godan) keyboard design, which is the keyboard most people use on mobile devices -- basically you would have a hold button to select each kana row. A lot of people also use the regular ascii keyboard to spell out kana phonetically but this makes little sense since we don't have an IME.

| Apple Keyboard | Android Keyboard (Old Photo) |
| --------------------- | ---------------------------------------- |
|<img height=400 src="https://user-images.githubusercontent.com/2888411/138576586-ddd2a41d-8e15-4c2f-9a11-b27a17240846.jpg">|<img height=400 src="https://user-images.githubusercontent.com/2888411/138576633-80e3de6e-ce38-4b0b-84c7-16110f10aff7.jpg">|

I've only ever seen the whole gojuuon keyboard (the current keyboard we use in KOReader) on devices with really bad Japanese input capabilities (Android TV for instance).
