### ISSUE TITLE
Issues with non-touch devices

### ISSUE THREAD

**Issue by Arvedui** [koreader/koreader#6463]
* KOReader version: 2020.07.1
* Device: Kindle 5

#### Issue
At two menu pages are not usable without touch screen.

1. Gear Symbol -> Status bar -> Settings  -> Sort items (On this one not even the back buttons works! **I cannot leave it without soft-reset!**)
2. Tool Icon -> Reading statistics -> Time range

I have not checked everything, so there may be more I'm not aware of.

#### Steps to reproduce
1. Take a ebook reader without touch screen
2. Enter one of the above page
3. Try to do something on that page

**Comment by Arvedui** [comment]
Additionally: I can not set date or time

**Comment by NiLuJe** [comment]
Sidebar: if there's no touchscreen, you don't have a Kindle 5 ;).

c.f., https://wiki.mobileread.com/wiki/Kindle_Serial_Numbers

**Comment by Arvedui** [comment]
Well serial says it is a kindle 4, but it definitively does not look like one, when comparing to the pictures on wikipedia.

**Comment by NiLuJe** [comment]
That's a Kindle 4, for reference: https://wiki.mobileread.com/wiki/Kindle_4 (there's also a black one, with a different S/N prefix).

**Comment by chrisman** [comment]
Kindle 4 No Touch here

In addition to the above, all "long press" features are inaccessible.

One large pain is there seems to be no way to highlight text or look up words

**Comment by fuckkgithub** [comment]
> Kindle 4 No Touch here
> 
> In addition to the above, all "long press" features are inaccessible.
> 
> One large pain is there seems to be no way to highlight text or look up words

YES! All the up/down arrow adjustment buttons (like the date settings) and nearly all of the long press functions don't work on non-touch devices. I've been pained by this for more than a year and bypassed it by manually editing config files. 

Just recently looked at the github issues and I'm not sure if this is first time someone has pointed this out, is it really? Has anyone been working on this?

**Comment by NiLuJe** [comment]
Not much, because the only non-touch device not woefully terrible by today's standard is pretty much the K4, so that's a fairly tiny user-base, and an even tinier (read: null) developer pool ;).

(I mean, I've got one, so I can help test stuff, but I *really* don't have the time to throw at this kind of stuff).

**Comment by fuckkgithub** [comment]
That's a shame. The K4 is great for what it is in my opinion. But I assumed the non-touch userbase wasn't so small.

**Comment by chrisman** [comment]
> > Kindle 4 No Touch here
> > In addition to the above, all "long press" features are inaccessible.
> > One large pain is there seems to be no way to highlight text or look up words
> 
> YES! All the up/down arrow adjustment buttons (like the date settings) and nearly all of the long press functions don't work on non-touch devices. I've been pained by this for more than a year and bypassed it by manually editing config files.
> 
> Just recently looked at the github issues and I'm not sure if this is first time someone has pointed this out, is it really? Has anyone been working on this?

@fuckkgithub do you have these configs in a place where you can share them as a reference?

I'm in a place where I need to do the same, or switch back to DuoKan 😬

**Comment by pazos** [comment]
> Not much, because the only non-touch device not woefully terrible by today's standard is pretty much the K4, so that's a fairly tiny user-base, and an even tinier (read: null) developer pool ;).

Agree. The other device with a very limited input is the Android Tv (an exoteric platform for an ereader). Somehow seems a good  start point as a NT device, since it has the minimum number of controls (5-dpad and back). 

See my suggestion in https://github.com/koreader/koreader/pull/6327#discussion_r450787837 (it leaves the ok/accept button empty on the reader, so it can be used for highlighting and other useful stuff)

**Comment by Frenzie** [comment]
In general, what @NiLuJe said. 

@chrisman 
If you're in a position to run the AppImage you could also use that to play around with relevant settings.

@pazos 
> Agree. The other device with a very limited input is the Android Tv (an exoteric platform for an ereader).

I can just run desktop KOReader with a controller from my couch. :-) But in that context I'm not bothered by a few more advanced settings missing here and there. Either way, I find a controller a slightly more natural way to test keyboard-only than forcefully ignoring your mouse.

**Comment by fuckkgithub** [comment]
> @fuckkgithub do you have these configs in a place where you can share them as a reference?
> 
> I'm in a place where I need to do the same, or switch back to DuoKan 😬

Unfortunately I made the edits on a much older Koreader version and some are obsolete now. I just updated Koreader and they were reset, I'll probably try downgrading (can I downgrade via the manual .zip update route?).
I don't have access to the backups at the moment, but unfortunately I edited them a while ago and I didn't document what I did at the time. They concerned things like default font, size, margin, DPI (I tried setting DPI to 167 but I don't think it worked), etc.
I might post a reference at some point, but what I basically did is either manually search through the configs, or (in Windows) enable indexing for the content inside the configs' filetype (.lua or something). Then, that allowed me to use Windows' search to look for the keywords inside the files ("margin", "DPI", etc.)

**Comment by fuckkgithub** [comment]
Also, when I updated the very old Koreader ver. to the latest ver. on my K4, the screensaver options have disappeared from the gear menu. Another reason which I hope that downgrading works somehow.

**Comment by iFUCKINGHATEcomputers** [comment]
@chrisman 
> @fuckkgithub do you have these configs in a place where you can share them as a reference?
> 
> I'm in a place where I need to do the same, or switch back to DuoKan 

Here's the surest way I've found so far, by comparing the differences between files:
1. You probably have some Android device lying around, so download the KOReader app from F-Droid

2. In the app, open a filetype you want to change the defaults for (an epub file, for example)

3. Set some default values for the settings you're interested in (by long pressing or whatever)

4. Exit the app (using the exit option from in-app menu, don't just close the app or it won't save your settings)

5. Connect your Android device to your PC and make a copy of the 'koreader' folder in your Android directory, then rename it 'koreader1' or something

6. Open the KOReader app again, set different default values for those same settings (this time the values should be the same as the ones you want on your e-reader)

7. Exit the app (again, using the exit option from in-app menu)

8. Make another copy of the 'koreader' folder in your Android, then rename it 'koreader2' or something

Now you have 2 folders, which have different files with different info within them - even though very few settings were changed, there could still be quite a few differences. You're trying to find which of those different values concern the settings you want.

There's a great visual 'diff' tool called [Meld](https://meldmerge.org/), which can compare differences between files and folders. It's open-source and available for Windows/Linux.

9. Open Meld, select 'Directory comparison', select your two koreader folders, and select 'Compare' - the two directories will be shown and the differing files highlighted

10. Most of my differing files have stuff do with file history, cache, statistics, etc - nothing relevant. After looking through them, I see that the one which concerns book settings is apparently 'settings.reader.lua'.

11. After opening 'settings.reader.lua', there's quite a bit of differences between the two - but nearly none of these  differences have anything to do with the settings I've just set (in my case, default font and contrast).

12. Since I know what I'm looking for (font and contrast) I look through the file for any similar words, and I find two lines which seem relevant - `["copt_font_gamma"] = some fuckin value,` and ` ["cre_font"] = "some fuckin font name",`.

13. I take note what those lines are, where exactly they've been inserted, and what the values are.

14. I connect my Kindle and open the KOReader settings file I want to edit (using Notepad++, and backing it up beforehand)

15. I either find those same lines and edit them , or if those lines don't exist in the file, I paste them in (making sure to insert them in the right location).

That's it. Now I can take note of these settings and know where to edit them if I need to change my defaults again.

**Comment by iFUCKINGHATEcomputers** [comment]
I see there's work being done on Android TV, does that mean there's going to be better support for 5-way dpads? If so, could it be ported?

**Comment by NiLuJe** [comment]
Err, what's wrong with dpads on Kindles?

**Comment by Frenzie** [comment]
Any improvements won't have to be ported since in the code all such scenarios are covered by flagging a device as having a d-pad. But I figure the chances of people using the program on PC or Kindle 4 NT contributing relevant code are significantly higher than those for Android TV.

@NiLuJe Probably talking about being unable to set defaults without involving a PC, see that big message right above after. ;-)

**Comment by imhlq** [comment]
Another problem with Kindle4 NT,
Cannot log in Evernote. Evernote -> Login -> Input username -> stuck here! cannot press any button to input password.

**Comment by pazos** [comment]
@Arvedui @imhlq @iFUCKINGHATEcomputers: I'm going to close this issue. Generic tickets make difficult to track issues and people willing to help need to read a ton of info to figure out which needs to be fixed.

 Please open separate tickets for each bug found. https://github.com/koreader/koreader/issues/6866 is a good example on how to report one issue per ticket.

Thanks!
