### ISSUE TITLE
In some cases the book cover covers the text

### ISSUE THREAD

**Issue by SvyatKV** [koreader/koreader#6490]
* KOReader version: 2020.07.1
* Device:  Устройство: Lenovo Tab3 7 Essential TB3-710I, Prestigio Prestigio Muze G3 LTE, TP-LINK Neffos C7

When in the settings in viewing mode I set continuous - "view mode = continuous", it happens that the book cover covers the text.
![1](https://user-images.githubusercontent.com/61149954/89728517-80126600-da36-11ea-9447-51b43066bf5b.jpg)
![Screenshot_20200809-074550](https://user-images.githubusercontent.com/61149954/89728557-b819a900-da36-11ea-876b-56b431709c4f.png)
![Screenshot_20200809-113009](https://user-images.githubusercontent.com/61149954/89728561-bd76f380-da36-11ea-88c0-04e12677d95c.png)

[Tom_1._Proizvedeniya_1889-1896.zip](https://github.com/koreader/koreader/files/5046917/Tom_1._Proizvedeniya_1889-1896.zip)
[Конан_Классическая_Сага.fb2.zip](https://github.com/koreader/koreader/files/5046918/_._.fb2.zip)

**Comment by poire-z** [comment]
Fortuantly not a DOM rendering issue: FB2 covers are not part of the DOM, and are rendered by LVDocView, around there:
```diff
--- a/crengine/src/lvdocview.cpp
+++ b/crengine/src/lvdocview.cpp
@@ -2327,9 +2327,13 @@ void LVDocView::Draw(LVDrawBuf & drawbuf, int position, int page, bool rotate, b
         drawbuf.setHidePartialGlyphs(false);
         drawPageBackground(drawbuf, 0, position);
         int cover_height = 0;
-               if (m_pages.length() > 0 && (m_pages[0]->flags & RN_PAGE_TYPE_COVER))
+        printf("scroll mode\n");
+               if (m_pages.length() > 0 && (m_pages[0]->flags & RN_PAGE_TYPE_COVER)) {
                        cover_height = m_pages[0]->height;
-               if (position < cover_height) {
+            printf("cover_height %d\n", cover_height);
+        }
+               if (false && position < cover_height) {
+            printf("position %d < cover_height %d\n", position, cover_height);
                        lvRect rc;
                        drawbuf.GetClipRect(&rc);
                        rc.top -= position;
@@ -2342,6 +2346,7 @@ void LVDocView::Draw(LVDrawBuf & drawbuf, int position, int page, bool rotate, b
                }
                DrawDocument(drawbuf, m_doc->getRootNode(), m_pageMargins.left, 0, drawbuf.GetWidth()
                                - m_pageMargins.left - m_pageMargins.right, drawbuf.GetHeight(), 0, -position,
+                               // - m_pageMargins.left - m_pageMargins.right, drawbuf.GetHeight(), 0, -position+cover_height,
                                drawbuf.GetHeight(), &m_markRanges, &m_bmkRanges);
        } else {
                int pc = getVisiblePageCount();
```
I'm not familiar with all this - but my idea there was to just shift position down by the cover_height - which somehow works. But it's not just to be done here: all `y` given to highlights/getRect() stuff should be shifted by that cover page height (or a page height)...

But I thing the easier and cleaner solution is to just not draw the cover in scroll mode :) 
@virxkane : any thoughts ?

**Comment by virxkane** [comment]
I'm still far from the computer, but I think users will not appreciate the lack of coverage.

**Comment by poire-z** [comment]
I spent some time trying to fix this, and came up with:
```diff
--- a/crengine/src/lvdocview.cpp
+++ b/crengine/src/lvdocview.cpp
@@ -2085,2 +2085,6 @@ void LVDocView::GetPos(lvRect & rc) {
                rc.bottom = _pos + GetHeight();
+               if ( !isPageMode() && m_pages.length() > 0 && (m_pages[0]->flags & RN_PAGE_TYPE_COVER) ) {
+                       rc.top -= m_pages[0]->height + m_pageMargins.bottom * 4;
+                       rc.bottom -= m_pages[0]->height + m_pageMargins.bottom * 4;
+               }
        }
@@ -2107,2 +2111,4 @@ int LVDocView::GetPos() {
                return m_pages[_page]->start;
+       if ( !isPageMode() && m_pages.length() > 0 && (m_pages[0]->flags & RN_PAGE_TYPE_COVER) )
+               return _pos - (m_pages[0]->height + m_pageMargins.bottom * 4);
        return _pos;
@@ -2342,2 +2348,4 @@ void LVDocView::Draw(LVDrawBuf & drawbuf, int position, int page, bool rotate, b
                }
+               if ( cover_height )
+                       position -= cover_height + m_pageMargins.bottom * 4;
                DrawDocument(drawbuf, m_doc->getRootNode(), m_pageMargins.left, 0, drawbuf.GetWidth()
@@ -2385,2 +2393,5 @@ bool LVDocView::windowToDocPoint(lvPoint & pt) {
                pt.y += _pos;
+               if (m_pages.length() > 0 && (m_pages[0]->flags & RN_PAGE_TYPE_COVER)) {
+                       pt.y -= m_pages[0]->height + m_pageMargins.bottom * 4;
+               }
                pt.x -= m_pageMargins.left;
@@ -2433,2 +2444,5 @@ bool LVDocView::docToWindowPoint(lvPoint & pt, bool isRectBottom, bool fitToPage
                pt.y -= _pos;
+               if (m_pages.length() > 0 && (m_pages[0]->flags & RN_PAGE_TYPE_COVER)) {
+                       pt.y += m_pages[0]->height + m_pageMargins.bottom * 4;
+               }
                pt.x += m_pageMargins.left;
```
Which fixes the drawing of the cover, and at least fix highlighted text (that we do in frontend - unlike CoolReader).

But there are so many other things that are broken (page links, following links near gesture, bad jump to the link target, bad position marker, messed up full text search, messed up text selection in scroll mode when crossing pages...).
In KOReader, there are a few y/pos things that we do in frontend, and I don't want to have to mess with the frontend code to have it deal with this peculiar FB2 cover situation: the cover is not part of the document roll, so it's drawn at 0, and the real document start (y=0) is somehow drawn at 0+cover_height - but we expect it to be 0 in so many things... so, many adjustments might be needed in crengine and in koreader frontend. So, I have the feeling that even if this is fixed in CoolReader, it might still not be fine with KOReader.
In page mode, we seem to be helped with the page splitting, that has assigned page 1 to the cover, and has page 2 start at document y=0.

The other option would be to make it part of the DOM, by inserting it as a proper image in a proper wrapper as the first child of the body (but then there is the `<description><annotation>` and `<date>` that are before the body - and before the `<coverpage>` - so the cover would no more be first, not even in page mode...

So, I would be fine with just not displaying it:
```diff
--- a/crengine/src/lvdocview.cpp
+++ b/crengine/src/lvdocview.cpp
@@ -2327,4 +2327,7 @@ void LVDocView::Draw(LVDrawBuf & drawbuf, int position, int page, bool rotate, b
         drawbuf.setHidePartialGlyphs(false);
         drawPageBackground(drawbuf, 0, position);
+        /* Don't draw FB2 cover in scroll mode, as having it not part of the document
+           height and having to shift the document start and adjust y/pos in many
+           places is quite complicated
         int cover_height = 0;
                if (m_pages.length() > 0 && (m_pages[0]->flags & RN_PAGE_TYPE_COVER))
@@ -2341,4 +2344,5 @@ void LVDocView::Draw(LVDrawBuf & drawbuf, int position, int page, bool rotate, b
                        drawCoverTo(&drawbuf, rc);
                }
+               */
                DrawDocument(drawbuf, m_doc->getRootNode(), m_pageMargins.left, 0, drawbuf.GetWidth()
                                - m_pageMargins.left - m_pageMargins.right, drawbuf.GetHeight(), 0, -position,

```
(as who really reads in scroll mode ?! when we have such a nice page mode with footnotes! :)

**Comment by poire-z** [comment]
Btw, there is an image colors issue with this file: the image in the screenshots above that we see mostly blue should be mostly yellow.
```diff
--- a/crengine/src/lvdocview.cpp
+++ b/crengine/src/lvdocview.cpp
@@ -1100,7 +1100,7 @@ void LVDocView::drawCoverTo(LVDrawBuf * drawBuf, lvRect & rc) {
         if (dst_dy > rc.height() * 6 / 8)
                        dst_dy = imgrc.height();
                //CRLog::trace("drawCoverTo() - drawing image");
-        LVColorDrawBuf buf2(src_dx, src_dy, 32);
+        LVColorDrawBuf buf2(src_dx, src_dy, 32); // colors ok if using 16...
         buf2.Draw(imgsrc, 0, 0, src_dx, src_dy, true);
         drawBuf->DrawRescaled(&buf2, imgrc.left + (imgrc.width() - dst_dx) / 2,
                 imgrc.top + (imgrc.height() - dst_dy) / 2, dst_dx, dst_dy, 0);
```
Here, the final drawBuf we provide is 32bpp.
If the intermediate buf2 is 32bpp, colors are bad.
If I make buf2 16bpp, colors are ok.
(Dunno if its an issue with DrawRescaled(), or something else.)
Pinging @NiLuJe for when you're back :)

**Comment by NiLuJe** [comment]
That's a similar code path than the one you recently nixed for background
images, right?

**Comment by poire-z** [comment]
Not really, it's drawn totally outside of the usual DOM rendering/drawing flow.
But indeed, in that commit you mention https://github.com/koreader/crengine/commit/0c343e1ae9953253fa0e2199a9c7a9c2bc0a9112 , I was previously using a 16bpp buffer just to avoid colors being messed up - so we did draw background images that way for months.
So I guess there should be no issue switching it from 32 to 16bpp for this edge case (yes, FB2, you are and always will be an edge case to me, you and your not friendly specs ! :).

I think in this commit, the issue was using an intermediate buffer, which we do also here - and we switch that to using just LVCreateStretchFilledTransform() to get an image (without using a buffer), and finally draw that "transformed" image on the final buffer.
May be we could also do the same here if LVCreateStretchFilledTransform() can do the same scaling as DrawRescaled().
But in the abstract, for a cover image (white bg, no transparency/alpha), is there a quality issue in using 16bpp instead of 32bpp ?

**Comment by NiLuJe** [comment]
It's a tad less efficient because of the pixel format conversion, but, then
again I don't particularly care about this specific use case ;p.
