### ISSUE TITLE
Incorrect display of verses

### ISSUE THREAD

**Issue by SvyatKV** [koreader/koreader#6494]
Incorrect display of verses.
On one page there is a title of the poem, in theory, the second verse should begin, regardless of whether there is a title or not (instead of the title there are three dots) on a new line.
![1](https://user-images.githubusercontent.com/61149954/89778072-8cb9bb80-db15-11ea-9075-82b9e9de62c5.png)
![2](https://user-images.githubusercontent.com/61149954/89778075-8deae880-db15-11ea-98de-ddd9d69c7b2c.png)
![3](https://user-images.githubusercontent.com/61149954/89778077-8e837f00-db15-11ea-9e7f-3fd7d9026242.png)
books
[Высоцкий. Избранное fb2.zip](https://github.com/koreader/koreader/files/5050546/fb2.zip)

**Comment by hius07** [comment]
I see no bugs here, perfect rendering of the verses in accordance with the book fb2 markup.

**Comment by SvyatKV** [comment]
> Я не вижу здесь никаких багов, идеальная визуализация стихов в соответствии с разметкой книги fb2.

I do not argue that the file may be correct.
Look at how it is implemented here, that is, the beginning of each verse starts on a new page

![Screenshot_20200810-151241](https://user-images.githubusercontent.com/61149954/89781770-9d216480-db1c-11ea-9d5a-ef24134f012e.png)

![Screenshot_20200810-151231](https://user-images.githubusercontent.com/61149954/89781764-9b57a100-db1c-11ea-8175-aa738bc8012d.png)

**Comment by hius07** [comment]
*** here are within `subtitle` tags and should not break the page in accordance with the fb2.css.

**Comment by Frenzie** [comment]
@hius07 Well, it's simply a matter of what CSS to apply to certain elements. Perhaps it should contain something like:

```css
poem { page-break-after: always; }
```

That's really the only question here. Of course it's being rendered perfectly as we tell it to be rendered. :-)

**Comment by hius07** [comment]
The last screenshots (with background) are from another book, not that attached to the first post.
It might be marked up differently and we don't know which tag breaks the page.

**Comment by Frenzie** [comment]
In any case, naively speaking (without having checked the FB2 specs) I would agree that `<subtitle>` doesn't sound like an element that should introduce a page break.

One could always add a userstyle with `subtitle {page-break-before: always !important}`.

**Comment by poire-z** [comment]
OK, so to explain the options you @SvyatKV have (and so that you can do a bit of debug/inspection before reaching us - and eventually posting screenshots of the HTML):

That's the code (you can select text across 2 poems and `View HTML` to see it on your device):
```html
       <v>last verse of previous poem</v>
      </stanza>
     </poem>
     <p><emphasis>1961</emphasis></p>
     <subtitle>* * *</subtitle>
     <poem>
      <stanza>
       <v>first verse of next poem</v>
```
In our fb2.css, we don't have anything else driving page breaks than:
```css
title, h1, h2 {
        page-break-before: always;
        page-break-inside: avoid;
        page-break-after: avoid;
}
ol title, ul title {
        page-break-before: auto;
}
subtitle, h3, h4, h5, h6 {
        page-break-inside: avoid;
        page-break-after: avoid;
}
```
So, we don't have anything forcing a page-break in that HTML snippet - but we have one requesting to avoid a page-break after SUBTITLE.
(Which I think is generally what's wanted: after a title / subtitle, there is the content, and we would not want the content to start far way from its title on a new page.)

So, you want a new page after each poem for this book (other books may be structured differently).
Fortunatly, with KOReader, you can have Book style tweaks or User style tweaks (top menu, 2nd item, Style tweaks > Book-specific tweak).
Make one with either
`subtitle {page-break-after: always;}`
or
`subtitle {page-break-before: always; }`
The first one will leave the `* * *` at the end of the previous poem.
The second one will have it at the top of a page with a new poem.

**Comment by hius07** [comment]
> `poem { page-break-after: always; }`

For this (poorly formatted) book it will cut the year from the verse.

**Comment by poire-z** [comment]
`poem { page-break-before: always; }` then :)
But it would put the title on previous page, if the poems have a better title than `* * *`. So yes, best to go with tweaking `subtitle`.
