### ISSUE TITLE
FR: [up scroll and down scroll button in lookup window]

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#6512]
up and down scroll is possible using gesture. But sometimes word down the gesture is selected. Also when the definition is too long (image attached herewith), using gesture is difficult in kobo clara hd. Rather it would be easy to press the down button as required.
Up and down scroll button in lookup window is requested.
![Screenshot_2020-08-17_001902](https://user-images.githubusercontent.com/59373108/90342369-2fe06880-e021-11ea-9760-a2f2a4cff765.jpg)

**Comment by poire-z** [comment]
> Up and down scroll button in lookup window is requested.

Up and down buttons are the half left and half right part of the window :) 
(We won't clutter this window with other buttons for that.)

> But sometimes word down the gesture is selected

That means your tap is too slow and interpreted as a long-press.
See what you have in `Gear > Taps and gestures > Gesture intervals > Hold interval`.
The default is 500ms - if that's too fast for you, you can try increasing it to 1000ms (so, when you long-press for less than 1s, it will still be a tap).

> Also when the definition is too long (image attached herewith), using gesture is difficult in kobo clara hd

Not sure about the relation between the length of the definition and the gesture being difficult.
If you mean it's taping multiple times that gets difficult because you have to extend your finger to reach the window (holding the device in one hand?), an option for you might be to use a bigger window, so you have more room to tap in (and less finger extension): check `Dictionary settings > [ ] Large window`

**Comment by poire-z** [comment]
Still doesn't feel like an issue :) Closing.
