### ISSUE TITLE
Is there any setting to let the epub comment show or display in the same page ??? not jump to the whole comment page 

### ISSUE THREAD

**Issue by whmzsu** [koreader/koreader#6538]
Is there any setting to let the epub explain comment show or display in the same page ??? not jump to the whole comment page

**Comment by whmzsu** [comment]
Thanks for the reply. The "Show footnotes in popup" function  under "Setting-->Taps and gestures-->Links" do meet my want . The function hide so deep. 
And btw: if the popup area  location is dynamic  depend on the origin text location,  it   will be much butter , for some time  the book origin text is  on the bottom of the page   and the popup area will cover it.

**Comment by Frenzie** [comment]
In-page footnotes are enabled by default. If they're not working on a particular book it's most likely a problem with the book's markup, but one that unfortunately pop-up footnotes can deal with slightly more elegantly since they're not exactly the same.

If you could share a scrambled copy of the book in question (see [here](https://www.mobileread.com/forums/showthread.php?t=267998)) we could investigate to see what's the case.

**Comment by whmzsu** [comment]
https://pan.baidu.com/s/1UUbOEagrP0TXzyHlTvBcKg     extract code: p4xm
The book is very big, so I upload to the net disk.
BTW: The book is one of  the four Chinese‘s  famous fictions  , named “Journey to the West“.
”

**Comment by Frenzie** [comment]
Thanks for the Google Drive, Baidu was hard to figure out. @poire-z would probably know why it's not working as in-page footnotes at a glance. Because it's all part of a list?

![Screenshot_20200829_160628](https://user-images.githubusercontent.com/202757/91638927-3dc7bd80-ea13-11ea-868d-b05963de5201.png)
![Screenshot_20200829_160653](https://user-images.githubusercontent.com/202757/91638928-3e605400-ea13-11ea-8288-3982805942f0.png)

**Comment by poire-z** [comment]
The `epub:type="footnote"` is wrongly set. It's set on the container of all footnotes. It should be set on the container of each individual footnote.

https://idpf.github.io/epub-vocabs/structure/#notes
> footnote
    Ancillary information, such as a citation or commentary, that provides additional context to a referenced passage of text.
    HTML usage context: On the aside element when identifying a **single** footnote, or on descendants of sectioning content when identifying **individual** footnotes in a group (refer to footnotes and endnotes).


So, I guess that for this book, may be it works for the first footnote link, which should show all the following footnotes :)

Solution: book style tweak, probably with:
```css
.duokan-footnote-item { -cr-hint: footnote-inpage; }
```
