### ISSUE TITLE
FR: [add screenshot to dispatcher]

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#6592]
From https://www.mobileread.com/forums/showpost.php?p=4028556&postcount=23

> I take screenshots on my Kindle and Poke2 with press the bottom left and top right corner at the same time. This does not work in my emulator, because I only have one mouse.

From https://www.mobileread.com/forums/showpost.php?p=4028573&postcount=24

> One thing I would like though is for KOReader to allow for taking the screenshot when the selected image is shown at full screen.

**Describe the solution you'd like**
Screenshot can be used with any gesture the user wants.

**Comment by Frenzie** [comment]
The reason I left the screenshot alone is because it gets quite complicated. Having the long diagonal swipe to take a screenshot override anything else is fine, but you can't just allow anything action to use the overriding full diagonal swipe, and you can't just limit it to the reader/filemanager or it'd be a bit useless.

So you can add the screenshot as an action to be used freely with any of the supported combinations, but it may not quite work as desired.

**Comment by KenMaltby** [comment]
Playing in KOReader's crop and zoom functions for the Reader (epub) on the cover page, I was able to take a screen shot that had the cover image fill most of the screen.
