### ISSUE TITLE
KOReader does not render MathML correctly in epub3 books, and does not fall back to altimg

### ISSUE THREAD

**Issue by ghost** [koreader/koreader#6678]
* KOReader version: v2020.09
* Device: Kobo Aura H20 2 v2

#### Issue
The EPUB 3 specification allows XHTML documents to contain MathML markup (http://idpf.org/epub/30/spec/epub30-contentdocs.html#sec-xhtml-mathml), and it describes how documents can use an `altimg` attribute on the `math` element to provide an alternate image to show for readers that don't support MathML (http://idpf.org/epub/30/spec/epub30-contentdocs.html#sec-xhtml-mathml-alt). However, KOReader completely ignores the MathML elements in EPUB 3 documents, and thus it neither renders the MathML content correctly, nor does it use the fallback image.

#### Steps to reproduce
Open an EPUB 3 document containing MathML (an example document is attached) in KOReader.

[mathml.zip](https://github.com/koreader/koreader/files/5248611/mathml.zip)

**Comment by NiLuJe** [comment]
We've discussed the MathML stuff in the past (although, err, I can't quite recall where :D), and it's (obviously) a bit tricky. @poire-z  will probably chime in with more details.

I was completely unaware of the altimg fallback, though, and that sounds much more reasonable ;).

**Comment by poire-z** [comment]
We already discussed and added support for some other alternative content mechanism in #4381 : `epub:switch/epub:case`.
And these specs say there should be 3 other ones ?! :/ `alttext`, `altimg` and `annotation-xml` (for xhtml fragments)... (and they ignore `altimg` when they state the precedence among these...)

Also, in your sample document, you provided a SVG file as altimg, and our SVG support is also quite limited (https://github.com/memononen/nanosvg which does not support text, so if the SVG uses text strings instead of strokes to draw the chars, they won't show).
Your sample SVG actually shows badly:
<kbd>![image](https://user-images.githubusercontent.com/24273478/93661666-d1603d00-fa59-11ea-8d1a-950f60800d05.png)</kbd>


We also toyed with the idea of using CSS to render MathML in https://github.com/koreader/koreader/issues/6346#issuecomment-653774141.
And I've been playing again with that these last days, as it's quite an aggressive test drive for our layout/rendering engine, as it nests inline tables and incomplete tables, and allowed me to fixed some bugs in there (https://github.com/koreader/crengine/pull/379).

I'm currently toying with having crengine enable that stylesheet when meeting a `<math>` element.
It's sufficient on some simple formulas, there are some bugs in the CSS, and some stuff that can't be handled via CSS, and a few of these that I could fix with tricks.
Currently, I can get:
<kbd>![image](https://user-images.githubusercontent.com/24273478/93661539-d670bc80-fa58-11ea-898b-30c088ba05dd.png)</kbd>
which looks quite nice (except for the bad vertical alignments, and parenthesis/fences not stretched) - but some other books with mathml look not as nice.

Anyway, @georgelemental : your small sample would display fine (as shown above) but I'm interested to know how that CSS trick would look with the bigger book you're probably wanting to read.
Can you try with this morning KOReader nightly build http://build.koreader.rocks/download/nightly/v2020.09-5-g4d53ec7_2020-09-18/ and dropping this in your `koreader/styletweaks/` directory:
[mathml_via_css.css.txt](https://github.com/koreader/koreader/files/5249256/mathml_via_css.css.txt)(remove the .txt extension) and enabling it via `Style tweaks> User style tweaks>`.
Just to know if that's a good enough solution (which I could improve maybe a bit, but it won't be perfect).

We have a style tweak for toggling `epub:switch/epub:case`.
If we were to provide this rudimentary MathML rendering, while still allowing switching to show one of the 3 other alt content mechanisms `alttext`, `altimg` and `annotation-xml` (because one of these might be better than the others), it would start getting complicated :)
And we don't even know which would be the best as the default (as seen, an SVG image might not be better)...

**Comment by georgelemental** [comment]
Concerning the specification: EPUB 3.1 [drops support for `epub:switch`](http://idpf.org/epub/31/spec/epub-changes.html#sec-cdoc-switch), and it [does not mention `alttext`](http://idpf.org/epub/31/spec/epub-contentdocs.html#sec-xhtml-mathml-alt). The spec appears to imply that `m:annotation-xml` and `alttext` are meant for screen readers, not visual display. So it seems that the most sensible priority order is MathML → `altimg` → `epub:switch`. To confuse things even further, [EPUB 3.2](https://www.w3.org/publishing/epub/epub-contentdocs.html#sec-xhtml-mathml-conf-content) does not mention either `alttext` or `altimg`. 

The nightly build with CSS styletweak works quite well overall, for my not-very-complex book. Applying a math font to the MathML with `math { font-family: "Latin Modern Math"; }` makes it work even better. The most visible issue is that exponents are too big.

The test page in [this sample epub](https://github.com/koreader/koreader/files/5250641/mathml.zip) renders like this in KOReader with the tweaks applied:  
![Reader_2020-09-19_172053](https://user-images.githubusercontent.com/11415479/93689630-5ec58080-fa9e-11ea-9417-fef05fa15f82.png)

While Firefox renders it like this:
![Screenshot from 2020-09-19 17-31-44-cropped](https://user-images.githubusercontent.com/11415479/93689592-173ef480-fa9e-11ea-908a-5afab273e530.jpg)

The actual MathML code is

```
  <m:math altimg="../Images/altimg.svg"><m:mstyle><m:mfrac><m:mrow><m:mn>2.5</m:mn>
  <m:mi>c</m:mi>
  <m:mi>m</m:mi></m:mrow>
  <m:mrow><m:mn>2</m:mn>
  <m:mrow><m:mo>(</m:mo>
  <m:mn>2.01</m:mn>
  <m:mspace width="mediummathspace"></m:mspace>
  <m:mo>⋅<!-- ⋅ --></m:mo>
  <m:mspace width="mediummathspace"></m:mspace>
  <m:msup><m:mn>10</m:mn>
  <m:mrow class="MJX-TeXAtom-ORD"><m:mo>−<!-- − --></m:mo>
  <m:mn>5</m:mn></m:mrow></m:msup>
  <m:mspace width="mediummathspace"></m:mspace>
  <m:mfrac><m:mrow><m:mi>c</m:mi>
  <m:msup><m:mi>m</m:mi>
  <m:mn>2</m:mn></m:msup></m:mrow>
  <m:mi>s</m:mi></m:mfrac>
  <m:mo>)</m:mo></m:mrow></m:mrow></m:mfrac></m:mstyle></m:math>
```

**Comment by poire-z** [comment]
A small hijack of this issue for mentionning something related to what I wrote:

> our SVG support is also quite limited (https://github.com/memononen/nanosvg which does not support text, so if the SVG uses text strings instead of strokes to draw the chars, they won't show).

From https://www.mobileread.com/forums/showthread.php?t=333748 
>  I also noticed that some of the overlayed text/images are not rendered correctly.

It's just that these "overlayed text/images" are actually a single SVG with rectangle and arrows, but also text like this, that nanosvg doesn't support:
```svg
<text class="TextShape">
<tspan class="TextParagraph" font-family="Times New Roman, serif" font-size="318px" font-style="italic" font-weight="400">
<tspan class="TextPosition" x="9170" y="9419">
<tspan fill="rgb(128,128,128)" stroke="none">0</tspan>
</tspan>
</tspan>
</text>
```

(I don't have any of the other issues mentionned: monospace works, and images are not full width.)

**Comment by poire-z** [comment]
> From https://www.mobileread.com/forums/showthread.php?t=333748
> 
> > I also noticed that some of the overlayed text/images are not rendered correctly.
> 
> It's just that these "overlayed text/images" are actually a single SVG with rectangle and arrows, but also text like this, that nanosvg doesn't support:

With #9510, the SVGs in this document now render perfectly:

![image](https://user-images.githubusercontent.com/24273478/189543169-74359ebc-d274-42c9-8070-cd3f4996affd.png)

![image](https://user-images.githubusercontent.com/24273478/189543197-88bee7db-ae14-4f8c-9f09-6196be145d6f.png)
