### ISSUE TITLE
Wikipedia integration defaults to "en" regardless of the ePub language

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6679]
* KOReader version: 2020.09 (and earlier)
* Device: Kobo Forma & reMarkable (and potentially all devices)

#### Issue
When doing a long press on text and choosing "Wikipedia" from the menu, it runs the highlighted text through "Wikipedia EN" ignoring the language tag in the ePub's `content.opf` file.

#### Example
If I open a German book – which is properly formatted (the OPF file contains: `<dc:language>de</dc:language>`) and long press over the word `Geschichte` in a paragraph, it searches the English version of Wikipedia and opens `The Neverending Story` entry. What it should do instead is open the `History` entry in German.

One could manually add the language code in the settings, but the "Translate" functionality from the same menu identifies the language tag successfully every single time already. Is there a way to make it so the Wikipedia plugin does the same thing?

Adding this as an option (or making it the default) would make KOReader an even more outstading language learning tool. I hope it is not too hard to implement.

**Comment by poire-z** [comment]
Some opinion of mine on that previously stated in https://github.com/koreader/koreader/issues/2476#issuecomment-270405792 .

I don't think it should be the default behaviour.
Wikipedia is mainly an encyclopedia, not a definitiion dictionary or translation dictionary.
I mainly read French, but can read English. If I read some English book/article mentionning a location or a person name (or even a concept like "Aufklarung"), I expect getting results from my main own language Wikipedia: French. If I lookup a german word like "erwartet", Wikipedia DE is as useless as Wikpedia FR or EN.

But one can set the languages codes one can read, and it's just easy to toggle from one to another depending on the book you're reading (would be even easier with something like in the screenshots of #4395): an english book with location and names: I would keep Wikipedia FR - and english book with lots of concepts in "-ism", I could switch to Wikipedia EN.
Best to let that decision to the user, rather than to pick that from book metadata (which might be wrong: some web french acticle I save as EPUB get lang=en in their EPUB metadata).

**Comment by gabyhk** [comment]
@poire-z Those are good points. I was not aware this had been discussed before. Making it the default behavior might be going too far and I was not counting on some files having the wrong metadata (or lacking the metadata altogether).

The way it is at the moment is probably already best for the general user. That drop-down menu idea does sound interesting though. Another option could be to add the ability to set the language per book (perhaps somewhere in the bottom menu) rather than globally. This setting would then drive the source language for the dictionary, the translator and wikipedia (each with a toggle).

**Comment by gabyhk** [comment]
@NiLuJe and @pazos While this request might not be popular enough for the main branch, I was wondering if either one of you could provide a quick hint. Which files would you recommend that I look at?

**** Example of Desired Behavior
1. Open book in Italian (`<dc:language>it</dc:language>`)
2. Long press on word `Firenze`
3. Choose Wikipedia from pop-up menu
4. **Wikipedia IT** is automatically invoked

**Comment by poire-z** [comment]
Might be just a matter of re-ordering stuff in (which is called on each book re-opening- `self.view.document:getProps().language` being the book metadata language):
https://github.com/koreader/koreader/blob/3e063498fc03d82ff0a16be58337b23aebd84fa7/frontend/apps/reader/modules/readerwikipedia.lua#L336-L376
Less likely something to do in:
https://github.com/koreader/koreader/blob/3e063498fc03d82ff0a16be58337b23aebd84fa7/frontend/apps/reader/modules/readerwikipedia.lua#L386-L402

**Comment by gabyhk** [comment]
@poire-z I really appreciate how helpful all of you are. Thank you so much!

**Comment by gbyl** [comment]
Closing this as I was unable to figure it out and it is highly unlikely to ever be implemented.

**Comment by poire-z** [comment]
This seems to work (still requiring the book language to be in the list of wikipedia languages you have set, meaning you can read them - and that it's a proper wikipedia lang tag - if the book states its language is "fra" instead of the correct "fr", we won't go asking fra.wikipedia.org that does not exist):
```diff
--- a/frontend/apps/reader/modules/readerwikipedia.lua
+++ b/frontend/apps/reader/modules/readerwikipedia.lua
@@ -336,18 +336,29 @@ end
 function ReaderWikipedia:initLanguages(word)
     if #self.wiki_languages > 0 then -- already done
         return
     end
     -- Fill self.wiki_languages with languages to propose
     local wikipedia_languages = G_reader_settings:readSetting("wikipedia_languages")
     if type(wikipedia_languages) == "table" and #wikipedia_languages > 0 then
         -- use this setting, no need to guess
         self.wiki_languages = wikipedia_languages
+        -- but if book language is among the list of languages the user has set,
+        -- move this language to be the first used
+        local book_lang = self.view.document:getProps().language
+        if book_lang and book_lang ~= "" then
+            for pos, lang in ipairs(self.wiki_languages) do
+                if book_lang == lang then
+                    table.insert(self.wiki_languages, 1, table.remove(self.wiki_languages, pos))
+                    break
+                end
+            end
+        end
     else
         -- guess some languages
         self.seen_lang = {}
         local addLanguage = function(lang)
             if lang and lang ~= "" then
                 -- convert "zh-CN" and "zh-TW" to "zh"
                 lang = lang:match("(.*)-") or lang
                 if lang == "C" then lang="en" end
                 lang = lang:lower()
```
This might look fine to be the default behaviour, but I'd rather not (I read english articles, I still want Wikipedia FR to be my main language).
Could be made an option if other people think it's nice to have.

**Comment by gbyl** [comment]
@poire-z I hope one day I understand Lua and the KOReader project well enough to contribute with development. Thanks a ton!
