### ISSUE TITLE
invalid screen size (notch on API < 28)

### ISSUE THREAD

**Issue by amirmp3** [koreader/koreader#6695]
Hi, I recently installed Koreader on my phone (Huawei Honor 8c). My device has the notch and it makes a problem with Koreader. 
The problem will be found on the bottom that notch does not let show the full height of software.

I hope it is obvious in these pictures that I have gotten when I set notch to show:
![PicsArt_09-22-01 28 45](https://user-images.githubusercontent.com/64708228/93825910-0e534c00-fc73-11ea-8b97-b73d26cdea85.jpg)

And when I set notch to hide:
![Screenshot_20200922-011921](https://user-images.githubusercontent.com/64708228/93825245-bbc56000-fc71-11ea-83c5-f0b79d41a756.jpg)

I still after installing the android version think koreader is great, so thanks for developing the project like this!

**Comment by Frenzie** [comment]
That's in 2020.09?

I thought this was taken care of in https://github.com/koreader/android-luajit-launcher/pull/150

**Comment by amirmp3** [comment]
I double checked and yeah it is in the last version 2020.9.

**Comment by amirmp3** [comment]
> That's in 2020.09?
> 
> I thought this was taken care of in [koreader/android-luajit-launcher#150](https://github.com/koreader/android-luajit-launcher/pull/150)

I double checked and yeah it is in the last version 2020.9.

**Comment by pazos** [comment]
> I thought this was taken care of in koreader/android-luajit-launcher#150

Indeed. It uses android APIs that are available since API28 (Android Pie). See this SO answer: https://stackoverflow.com/a/52063876.

Each vendor has a different API for older devices: https://stackoverflow.com/a/56609043

While these devices can be workarounded implementing custom classes for them that behave exactly like DisplayCutout, it's a **won't fix** on my end. Too much work for very little gain.

**Comment by Frenzie** [comment]
Strange, I'd expect a 2019 device to run Android 9? But agreed. ^_^
