### ISSUE TITLE
Different cover when sleep/power down

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#6701]
* KOReader version: 2020.09
* Device: KObo Glo
* Kobo Firmaware: 3.4.1
* KSM version: 7

I haven't found a setting for this and I'm not sure if this is a feature or a bug, but what is happening is this:

I take a screenshot and use it as cover.
When I put the reader to sleep it shows the screenshot as it should.
When I power off the reader it shows the book's cover.

Now, I don't know if this has to do with my strange/old configuration, but I **_do_** like this distinction.
But what I would also like, is to have an option to choose what it shows at these two different states..

**Comment by poire-z** [comment]
> But what I would also like, is to have an option to choose what it shows at these two different states..

It's not set'able via the menu (because it would be complicated to add menus to set it for reboot/poweroff), but you can set it manually.
See https://github.com/koreader/koreader/issues/4031#issuecomment-401416891 for similar issue and links to info (#3572, https://github.com/koreader/koreader/issues/2589#issuecomment-323927682).

> When I power off the reader it shows the book's cover.

It feels it should show the same as for sleep then. Unless you already had poweroff_screensaver_type = cover in your settings.reader.lua.

**Comment by noembryo** [comment]
>It's not set'able via the menu (because it would be complicated to add menus to set it for reboot/poweroff), but you can set it manually.

Oh, the setting is already there eh? Not surprised at all :p
Thank you for your help :o)
