### ISSUE TITLE
USBMS "Share storage via USB?" dialog doesn't work

### ISSUE THREAD

**Issue by potash** [koreader/koreader#6817]
* KOReader version: 2020.10.1 (with or without the #6582 USBMS.tar.gz)
* Device: Kobo Aura One

#### Issue
I plug into a USB host and the "Share storage via USB?" dialog appears. Regardless of whether I click "Cancel" or "Share" the dialog does not go away (and USBMS doesn't start, at least the host doesn't recognize it). I cannot access any koreader functions.  I don't see any output in `logread -F`. The only way I found to recover is to force power off.

#### Steps to reproduce

Connect to USB host, click "Cancel" or "Share" on "Share storage via USB?" dialog.

**Comment by NiLuJe** [comment]
What about KOReader's own `crash.log` (in verbose debug mode, if possible [Tools > More tools > Developer options].

Because that's basically a plain dumb popup like any other of its ilk, it doesn't do *anything* without further user input o_O.

**Comment by potash** [comment]
Clicking the either button causes the dialog to become partially transparent as if it were about to disappear but doesn't fully. Further clicks cause refreshes but no actions.

Last few hundred lines of [crash.log](https://github.com/koreader/koreader/files/5426540/crash.log) doesn't seem to show anything. I don't see a "Developer Options" under More Tools, do I need to enable it?

**Comment by NiLuJe** [comment]
The Developer options menu is only available in the file manager, not inside a document ;). (Restart KOreader aftyer enabling *verbose* debug logging).

And now I'm *definitely* interested in a log, because that sounds like a gesture detection going awry ;).

I'd also try again with tomorrow's nightly, see if the recent tweaks on said gesture detection on those quirky devices changed anything ;).

**Comment by pazos** [comment]
I found this on my Cervantes when I implemented the USB share dialog. This is something related to a bad cable or a bad usb socket on your computer. I ended up disabling the autoplug thingy as both my laptop and my computer have these bad usb sockets. In my desktop I can only trigger the bug when connecting the reader to the front panel USB, mainboard ones work as expected.

**Comment by NiLuJe** [comment]
@pazos: I assume the UsbPlugIn event was fired multiple times in your case?

Here, that's the second report on the exact same device (a KA1), and we all know how shitty its input handling is, so I was simply thinking it was tripping the gesture detector up somehow?

In any case, a verbose debug log will be enlightening in both cases ;).

**Comment by NiLuJe** [comment]
i.e., what should happen is simply this:

```
10/23/20-15:26:11 DEBUG key event => type: 1, code: 10010(UsbPlugIn), value: 1, time: 1953718629.537537570
10/23/20-15:26:11 DEBUG AutoSuspend: onInputEvent
10/23/20-15:26:11 DEBUG ImageWidget: _render'ing resources/info-i.png
10/23/20-15:26:11 DEBUG renderImageData: using MuPDF
10/23/20-15:26:11 DEBUG Mupdf.renderImage true cdata<struct BlitBuffer8>: 0x323addc0
10/23/20-15:26:11 DEBUG RenderImage:scaleBlitBuffer: scaling
10/23/20-15:26:11 DEBUG cache image|resources/info-i.png|||d
10/23/20-15:26:11 DEBUG show widget: table: 0x31c69678
10/23/20-15:26:11 DEBUG setDirty nil from widget table: 0x31c69678 w/ NO region 
10/23/20-15:26:11 DEBUG setDirty via a func from widget table: 0x31c69678
10/23/20-15:26:11 DEBUG painting widget: table: 0x323b1870
10/23/20-15:26:11 DEBUG blitFrom 120 617 0 0 101 101
10/23/20-15:26:11 DEBUG _refresh: Enqueued ui update for region 99 596 881 236 
# 10/23/20-15:26:11  triggering refresh {
    ["mode"] = "ui",
    ["region"] = {
        ["y"] = 596,
        ["w"] = 881,
        ["h"] = 236,
        ["x"] = 99
    }
}
10/23/20-15:26:11 DEBUG refresh: ui-mode 99 607 881 236
10/23/20-15:26:11 DEBUG mxc_update: 881x236 region @ (99, 607) with marker 6 (WFM: 257 & UPD: 0)
```

**Comment by potash** [comment]
@pazos interesting, though in my case the same cable has no problems when I launch USBMS first through the menu nor when using nickel...

@NiLuJe here's the verbose log, in this case I believe I hit "Share" "Cancel" "Cancel" "Share", as I said the dialog does not go away but it does seem to refresh each press. Let me know if you need any other info and thanks so much!

**Comment by NiLuJe** [comment]
Yep, hunch correct.

It's stuck in hold state for... shitty Kobo input reasons. (the timestamp mismatch between fake and real events probably doesn't help).

Do try today's nightly, as this sort of shenanigans have been tamed down a notch. (Check with and without having triggered a long-tap once somewhere before plugging the device).

**Comment by NiLuJe** [comment]
@poire-z: This *might* be similar in spirit to your "first tap detected as a old" once in a blue moon issue on Mk. 6 ;).

**Comment by poire-z** [comment]
May be (got it twice today, so it's blue moon day - didn't get it for at least a week...)
To be sure:

> The only way I found to recover is to force power off.

What still works for me in short press on the power button: KOReader can still put the device to sleep. Wait 20s to press again and wake it up, and touch works again for me.

Btw, in #6798, I removed `touch_probe_ev_epoch_time` for the Kobo Aura One. Dunno if that tweak to ev time also affected fake events - if fake events expected this to properly set their time.

Dunno about the hold event: try to set in Gesture intervals `Hold interval` to 2000 or 3000 (be sure it's currently not too low), so we can distinguish better what happens.

Might be if the first event got since start up:
10/24/20-13:55:36 DEBUG key event => type: 1, code: 10010(UsbPlugIn), value: 1, time: 1730176617.1882092389
has a real clock timestamp, others won't be adjusted with #6798 - although this event shouldn't reach GestureDetector.
What happens if you tap/hold a few times after startup before pluging the usb cable?

**Comment by potash** [comment]
While sleep does work when it's stuck like that, the dialog is still there on wake up and doesn't respond.

Anyway I tried it on stable with extra taps and long taps before plugging in and it worked! Then I updated to the nightly and it worked from a fresh start of koreader which was consistently breaking before. So I'm closing this issue.  

Thanks everyone!

**Comment by NiLuJe** [comment]
@poire-z: Yeah, I'm not *quite* sure what's tripping the hold state, to be quite honest.

I don't have the code in mind, but if whatever delta triggered the hold seems entirely too ludicrous (like it is here), maybe breaking the hold state sounds like a good idea?

AFAICT, we *never* set the timestamp anywhere for fake events, so, something, somewhere, must assume that NULL == epoch, although I'm not quite sure *which* bit...

The "good" news is, I *might* be able to replicate said shitty timestamps on my Forma, via an `EVIOCSCLOCKID` ioctl, whose sole purpose is just that: telling the kernel which clocksource to use for evdev timestamps.
But, of course, it's Linux 3.4+, so we can't actually use it to *fix* the issue on said broke-ass devices, because they're all running something older :/.

**Comment by poire-z** [comment]
> AFAICT, we never set the timestamp anywhere for fake events, so, something, somewhere, must assume that NULL == epoch, although I'm not quite sure which bit...

Or may be we just don't care about the timestamp: they happen, we process them - they don't need any timestamp, unlike touch gesture where we have delays, interval, timeouts to use timestamps with.

> maybe breaking the hold state sounds like a good idea? (Because after all, a "human-triggered" hold/swipe can't very well last for more than a dozen seconds, and that's already being quite generous ^^).

Well, one can spend more than that selecting text, panning to corner, getting into scroll mode, continue selecting, go to corner to advance a few pages in scroll mode :) 

But yes, I still suspect getting stuck in hold mode may be the cause of my stuck touch layer... I'll have to figure out a way to get more details if that happens - without the need to be in debug log mode (too fat logs, happens not often enough to be worth logging that much while waiting for it to happen...)

(I also can sometimes have taps not working for a few seconds... may be missing a "touch release" event could cause the stack to stay stuck in hold/press.)

**Comment by NiLuJe** [comment]
At a very, very quick glance, the fake events don't go through GestureManager.

On my H2O, even single taps go through `handleNonTap` (and then `handleDoubleTap` on release), so the timestamp fixing is always ran against actual input timestamps, which is good.

(And I also figured out what went wrong with my first tap issue on the H2O: the Phoenix protocl makes some assumptions about slot IDs, and very light taps have a slightly different pattern than others, the light pattern prevents a proper slot from being set, so the first tap is discarded as an "end of gesture" without a beginning).
