### ISSUE TITLE
FR: Need A Paragraph Change Preview Page 

### ISSUE THREAD

**Issue by TaChao** [koreader/koreader#6896]
Every change of paragraph would re-rander the whole document, It will take 10-15 mins for a new book setup.
Please add a page for this change, and  preview for multiple modifications。

**Comment by NiLuJe** [comment]
I'll let other people explain why this is not going to be possible because that's just not how CRe works ;p.

(The only remotely feasible thing would be to be able to enable to tweak multiple things *without* triggering a CRe update, *then* hit an "I'm done" button to batch all the changes in one go. That's... also extreely unlikely, because way, way not how things are implemented).

**Comment by poire-z** [comment]
Closing in favor of #9087 (where I wrote a bit more).
