### ISSUE TITLE
Crash when tapping on image

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6929]
* KOReader version: v2020.11-25-g4ed9f19b_2020-11-29 (after #6885)
* Device: Tolino

#### Issue
After opening an image PNG, JPG and tap on the right or left I get a crash.
It seems that this bug was introduced with #6885

#### Steps to reproduce
see above

##### `crash.log` (if applicable)
[log.txt](https://github.com/koreader/koreader/files/5614710/log.txt)

**Comment by Frenzie** [comment]
Only PDF/DjVu documents have a `document.configurable`.

**Comment by jperon** [comment]
Just submitted a quick fix [here](https://github.com/koreader/koreader/pull/6930), but while doing that, I noticed there's no bottom menu when opening images. As zoom could be useful with them, what should be done:

- add a bottom menu just for zooming;
- restore zoom submenu in top menu just for images?

**Comment by poire-z** [comment]
> restore zoom submenu in top menu just for images?

Anything but that I guess :)

Images could get a bottom menu, some things could be useful: portrait/landscape, crop, zoom... They could be even text, so why not reflow ? (Thinking about a single photo of a big user-manual "dépliant".)
But I don't know what's involved and how much work is that.

**Comment by Frenzie** [comment]
> add a bottom menu just for zooming;

That makes more sense, otherwise it's unpredictable.

There is a third solution/workaround btw, namely to open these with MuPDF by default instead.

**Comment by jperon** [comment]
So would we go for this third solution, or would it be better to keep picdocument as the default one and add a bottom menu?

**Comment by poire-z** [comment]
No real educated opinion :/ 
(But if I had one :), I'd say : go with MuPDF if it can handle all the image formats PicDocument does - just for simplicity and have one engine/backend less to care about, as nobody never really test stuff with PicDocument. But I don't know if PicDocument and its dedicated image libraries can do better than MuPDF.)

**Comment by Frenzie** [comment]
The libraries are either literally shared or otherwise functionally identical from an end user's perspective.

I think there are two main differences in current behavior worth mentioning:

1. You might disable dithering for Kopt/MuPDF, while PicDocument enforces it.
2. PicDocument supports animated GIFs, providing them as pages.

So for GIF MuPDF [doesn't look like a proper option](https://github.com/ArtifexSoftware/mupdf/blob/493a0af673476fb0a4c7297c813900d38f0e83bd/source/fitz/load-gif.c). Besides that, MuPDF already handles a lot of image formats that PicDocument does not.

https://github.com/koreader/koreader/blob/3d8342a98ceff7b8bce6462247eb1f97b1a266a1/frontend/document/pdfdocument.lua#L306-L326

**Comment by jperon** [comment]
So let's go for MuPDF by default, except for GIF ?

**Comment by Frenzie** [comment]
Works for me. That'd mean something like swapping 90 for 100 in pdfdocument and vice versa in picdocument. But let's wait for @NiLuJe to chime in too.

**Comment by Frenzie** [comment]
Or since it's a really simple change done in a minute you could just submit the PR and we'd discuss it there. Whichever you prefer.

**Comment by zwim** [comment]
@jperon: The fix works. Thank you. 

I would go with MuPDF and your fix.

**Comment by NiLuJe** [comment]
Yeah, the main visible difference is that Pic only does nearest neighbor scaling ;). And we handle the decoding ourselves in FFI.

So, yeah, probably makes sense to default to MuPDF :).
