### ISSUE TITLE
FR: Wrapping Indent

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6951]
I have been searching for the best way to export Linux manual pages to KOReader. For instance, the following line will produce a plain text version of the `rm` command:

`MANWIDTH=1000 && man rm | col -b  > rm.txt`

This is rendered as expected on programs like VSCode, Sublime, Atom, etc. KOReader, however, lacks an option to control the indentation of wrapped lines so all lines begin at column 1. Could we add **"Wrapping Indent"** for text files, so wrapped lines get the same indentation as the parent?

**Comment by poire-z** [comment]
TXT is hard to always get right. There's no formatting, so it's all free to interpretation and possibilities - and the code not knowing what the user expects.
There's already a lot of code in crengine to try to detect what kind of txt a file is, how to detect paragraphs from `\n` wrapped lines, what to do with blank lines... It's monstruous and I don't want to look at it :) 
Adding options would need more than the one you suggest - and it would be a lot of work for, strangely, a rare use cases (who really reads .txt files? not much issues about it, and our handling of txt is bad).

Best is to forget about txt.

As you're generating the documents, I think you should try to find some man2html or man2epub tools.
There, you could control the formatting in the process of converting - and our engine would give you the formatting you decided - instead of having to guess what's best for you :)

**Comment by gbyl** [comment]
@poire-z That makes perfect sense. I will try to generate files in other formats instead. I appreciate the explanation!
