### ISSUE TITLE
FR: An UI to set timezone

### ISSUE THREAD

**Issue by truongsinh** [koreader/koreader#7070]
**Does your feature request involve difficulty completing a task? Please describe.**
I don't think it's difficult, I can easily do it with Linux command (Remarkable 1)

**Describe the solution you'd like**
With remarkable 1, use `timedatectl list-timezones` to get the list of timezone, then `timedatectl set-timezone [timezone id]` (ref https://www.tecmint.com/set-time-timezone-and-synchronize-time-using-timedatectl-command/) . More general solution is to use `ln -s` (ref https://unix.stackexchange.com/a/110529/91713)

**Comment by pazos** [comment]
`os.date` will use the TZ you setup on your OS.

**Comment by NiLuJe** [comment]
Yep, we're already using localtime; if it's not the case, your setup is broken (and apparently fixing it the systemd way is what you quoted, but it's absolutely not our place).

**Comment by truongsinh** [comment]
Well, it's because I did not clarify what I mean. The feature request is to have a UI to set timezone. RM1 does not support setting the tz with its stock startup app, and KOreader does not have the UI to set tz either. I had to set the tz myselves, using CLI.

**Comment by NiLuJe** [comment]
It's, unfortunately, highly platform-specific, because you cannot assume the TZ db will be: sane, in standard locations, actually there at all, or a mix of all three (IIRC, it's super-weird on Kindle, too; and it's mildly non-standard on [Kobo](https://github.com/koreader/KoboUSBMS/blob/6063bb63e73bea0a316aa454c0e4cf5857b63935/usbms.c#L1418-L1473).
