### ISSUE TITLE
Regressions in dictionaries management

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#7109]
* KOReader version: last development version as of today, January 5. 
* Device: Kobo Mini

#### Issue
Until now, if you had several dictionaries installed and activated, you could choose the default dictionary for a determined book by searching a word, going to the prefered dictionary in the dictionary search window and then touching the menu bar. This feature doesn't work anymore. It is not possible to choose a default/prefered dictionary for a given book.

#### Steps to reproduce
See above.

**Comment by poire-z** [comment]
I removed it in #7029 - for some reasons explained around https://github.com/koreader/koreader/pull/6998#issuecomment-747935159 .
I'm not against putting it back, with may be some other way to enable it.
But can you tell us a bit more about:
- did this really work for you ? (I got the feeling it might mostly only work with Chinese, or languages that do not have uppercase/lowercase)
- why/how do you use it? what's your various use cases?
- any thought about another way to activate it that the bad tap on title bar?

**Comment by Frenzie** [comment]
I'll take the liberty of butting in. :-P

> (I got the feeling it might mostly only work with Chinese, or languages that do not have uppercase/lowercase)

I got the feeling it worked more often than not.

> why/how do you use it? what's your various use cases?

To set one a French dictionary like XMLLittré as default instead of an English one like GCIDE.

> any thought about another way to activate it that the bad tap on title bar?

Long press to set default might suit expectations created by the rest of the program, or just a little checkmark of some sort.

**Comment by retrue** [comment]
- Well, it always worked for me. Sometimes the first tap didn't work so I tapped again until I got the message of "This is the default dictionary for this document".

- About how I use it: I am Spanish but I read usually in English. I have installed five dictionaries but I only have active in options three of them: Spanish definitions, English definitions and English/Spanish. When I read in English and check the dictionary I always look first for the English definition. Only if the definition is not clear for me (for example, when looking for a word like _birch_ , that is "_A slender hardy tree which has thin peeling bark and bears catkins_"), I look at the Spanish translation.

- One solution would be adding an option at the bottom of the dictionary window, where _Wikipedia_, _Search_ and _Close_ are, but I feel it would be crowded. So, maybe an option in _Dictionary settings_ called _Default dictionary for this document_?
Or in a more general way, an option in _Dictionary settings/Manage dictionaries_ to arrange the preference order of search for dictionaries? Right now, the criterium to choose what dictionary shows first is the alphabetical name of the dictionary.

**Comment by poire-z** [comment]
> Or in a more general way, an option in Dictionary settings/Manage dictionaries to arrange the preference order of search for dictionaries? Right now, the criterium to choose what dictionary shows first is the alphabetical name of the dictionary.

You can order them in there, since #6751. But it's indeed global.

> I got the feeling it worked more often than not.

Well, I just realize we could have it work better if, instead of ordering the results by trying to match the result word vs the queried word (and move only the result at first place if it matches and is from the default dict), we would just move the default dict first in the ordered list of dict names with give to sdcv ! Except that we wouldn't have the (not working most often than working :) check for exact vs fuzzy matches the old code tried to do, stopping as soon as the result word is strictly different than the queried word (cf https://github.com/koreader/koreader/pull/6998#issuecomment-748021440).

> To set one a French dictionary like XMLLittré as default instead of an English one like GCIDE.

>  I have installed five dictionaries but I only have active in options three of them: Spanish definitions, English definitions and English/Spanish. [...] So, for me, having shown the English definitions first is most useful.

The previous behaviour allowed for moving first only one dict from your global ordered list - but it allowed doing that fast.
Dunno if that's just enough, or if we should go with the more complex idea described at https://github.com/koreader/koreader/issues/6007#issuecomment-604998768 - to allow a dedicated re-ordering per-book. Which would also be slower to setup than just a tap on your first dict lookup when you open a new book and see whether it's french or english and you need that.

(Please don't think/ask about having orderings per-language, and auto-switch depending on book language ! too much work... :)

**Comment by retrue** [comment]
Ordering dictionaries in general in the menu "Manage dictionaries" works for me. I use KOReader on a daily basis but I missed the ordering feature.
Still, an option to override the general settings for specific books (that is, stablishing a default dictionary) would be welcome, if you switch reading languages often or use technical dictionaries.
The long press on the name of the dictionary in the dictionary window would work, as Frenzie suggests. No problem there of setting default dictionary by mistake with a long press.

**Comment by Frenzie** [comment]
> Well, I just realize we could have it work better if, instead of ordering the results by trying to match the result word vs the queried word (and move only the result at first place if it matches and is from the default dict), we would just move the default dict first in the ordered list of dict names with give to sdcv ! Except that we wouldn't have the (not working most often than working :) check for exact vs fuzzy matches the old code tried to do, stopping as soon as the result word is strictly different than the queried word (cf #6998 (comment)).

Iirc fuzzy was mainly slow(er) in combination with synonyms, which should now be fixed. But yes, that'd be much more elegant.

> Dunno if that's just enough, or if we should go with the more complex idea described at #6007 (comment) - to allow a dedicated re-ordering per-book. Which would also be slower to setup than just a tap on your first dict lookup when you open a new book and see whether it's french or english and you need that.

What about a simpler GUI for the same thing? Not "set as default" but "move to top of priority queue." So the previous one for that document would be pushed down to second place.

**Comment by poire-z** [comment]
Been contemplating the dict menu and the dict result window for quite some time... but I don't feel any solution to be THE obvious one :) 

The tap or long-press on title also had the issue that you don't see that you have previously set (or not) a default dict for this document, and which was it (dunno how much that might be an issue, for me that do not use this feature, it was an error that I didn't see what enabled - but as it never really worked, no visual effect :)
We could to the dict name in the title a "star" icon/unicode char to display it, or the ① ② ... unicode symbols to act as the star and showing some order if we go with @Frenzie suggestion.
That might be a bit distracting thus.
But the most problematic issue is that you can't set as default for this book a dictionary that you have disabled in the global "Manage dict" list. You'd still have to enable them, maybe moving them at the end of the global order list - so you can move them to start with tap on title. (But then, there's my case: I have dicts for latin or greek, that I have disabled and rarely use, because they increase a lot lookup time on non-latin/non-greek words - and I don't want to enable them, even at the end.)

Asking some more questions just to get more thoughts:
@retrue : for your use cases of English/Spanish (and @Frenzie for English/French), was it really an issue to have the global order as `1 English, 2 Spanish, 3 Translation EN>ES` ? I mean, when you read spanish, you'll get 0 results from the English one (and vice versa when reading english). I know you might not get 0 results in real life :) but how often was that bothering? And how; when reading spanish: getting exact matches in english for spanish words? or not getting exact spanish matches, so fallback to fuzzy search returning fuzzy english and then fuzzy spanish?

@rtega regarding your related #6007 : did you know about the tap on title bar to move one (and only one) dict at first for the current document? If yes, did it work for you, or it did not and you abandonned this "feature"? If you didn't, would that had been enough? Or you really need to enable/disable/move first multiple dictionaries when switching languages?

**Comment by rtega** [comment]
I know of the feature and from time to time I use it. It's not a solution to my general problem.

I put my dictionaries in subdirectories per language (I use 8 languages regularly) and ordered per language in other subdirectories per dictionary. That way I'm certain they stay ordered.

Basically what would be ideal is having language groups in which you could chose to order the dictionaries and make the languages stick per document. You could yourself chose which dictionary to add to which language group. Adding or removing dictionaries to a language wouldn't mess up your previous books.

**Comment by poire-z** [comment]
I get it - but what would be ideal for you would require a lot of work (for a very rare use case, most people reading multiple languages would probably have one dict per secondary language and are fine enough with occasionally getting results from unrelevant dicts) - and (more important) possibly quite a bit tougher less obvious UI to manage all that, that would feel unwelcome to the common user.
So, your ideal might possibly find its way into a plugin - that could fetch available dicts, allow grouping and ordering, keep named sets (per language, per topic, technology, ...), and allow feeding the normal core list with any of these sets. (Not interesting in doing that, but it might be an interesting project, even for a newcomer to Lua/Koreader :) 
(I think my idea at https://github.com/koreader/koreader/issues/6007#issuecomment-604998768 is a too dumb intermediate to your ideal - and I see a few other issues with it, it would feel quite hard to understand and not be annoyed and feel half-done...)

Any more thought for the simpler use case of everybody else ? :)

**Comment by retrue** [comment]
Right now, having the order in manage dictionaries set as English, EN>ES, Spanish, fixes my problem. Because I don't start a new book until I finish the old one, I don't  need to switch often. Still, for people who switches often between books and languages, to set a default dictionary per book can be useful.
And I don't understand how the old feature worked so broken for you, poire-z. It always worked quite well for me.

**Comment by Frenzie** [comment]
> @retrue : for your use cases of English/Spanish (and @Frenzie for English/French), was it really an issue to have the global order as 1 English, 2 Spanish, 3 Translation EN>ES ?

I prefer looking up words in my paper Petit Robert or my paper Petit Larousse. Our form of electronic dictionary lacks the serendipity of seeing a nearby lemma. Is it really an issue? Well, kind of, the English functions as a fallback (because many a French word doubles as an extremely rare English word) so seeing it first makes it seem like it wasn't in the French dictionary.

But I wouldn't know if it was an issue because it wasn't with the way things worked, and I haven't read any sufficiently difficult 19th century French on my ereader the past few weeks.

> And I don't understand how the old feature worked so broken for you, poire-z. It always worked quite well for me.

+1 usually worked just fine

**Comment by poire-z** [comment]
> And I don't understand how the old feature worked so broken for you, poire-z. It always worked quite well for me.

Let's say my globally ordered dicts would return (the 2nd one has word in uppercase):
`1) House 2) HOUSE 3) House`
Setting the 3rd as the "default for this document" didn't work, because the dummy algo would stop looking for the result of the 3rd dict because "HOUSE" is no more exactly the queried word, so it considers all other next ones as fuzzy results that don't deserve to be put first because there were exact matches before.
I guess if I didn't have the 2nd one 2nd, or if I didn't choose to make the 3rd as the default, I wouldn't have noticed it was broken :) But looking at the algo, it feels broken.

**Comment by Frenzie** [comment]
Not disagreeing there. In our current sdcv it should just set the source order. ^_^

**Comment by poire-z** [comment]
So, may be the safest/easiest (and most fun) is to restore the feature, and use sdcv dict name ordering.

May be keep Tap (Long-Press interferes with MovableContainer).
Tap would toggle between `This dict name` and `① This dict name` (that's `(1)`), so one knows he has set one by error and can remove it.
If another dict was previously made default, it will become `② This other dict name` (that's `(2)`) - tap on it to remove if from the 2nd default (and lose its ②), re-tap on it to make it first default (and get ①).

Users of this will see these ① and ②, might be bothering or reasuring, dunno - but _I_ won't see them :)

It would look like this:
<kbd>![image](https://user-images.githubusercontent.com/24273478/103706175-b84dae80-4fac-11eb-8218-03c1b6eeb225.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/103706060-758bd680-4fac-11eb-8589-28ea8457d256.png)</kbd>

This might allow for a really quick ordering of dicts when opening new books, so that even if it is to be redone on each new book, it might feel not so tedious (and quite quicker than all the style tweaks adjustments I do on each new book :)

Would that feel ok ?

**Comment by Frenzie** [comment]
I'd prefer a move to top icon like a checkmark of some sort, but sure.

**Comment by retrue** [comment]
I don't mind either way, poire-z's or Frenzie's.

**Comment by Frenzie** [comment]
For me personally it doesn't matter, but otherwise it's very in the know. ;-)

**Comment by poire-z** [comment]
Done with circled numbers in #7114.

> I'd prefer a move to top icon like a checkmark of some sort, but sure.

It would have to be a "move**d** to top" icon :) as I don't want any icon that would invite me to use this feature and that I would always see - when I'm really not interested in the feature - so yes, it will have to be discovered.
And with a static "move**d** to top" icon, we wouldn't have the fun ordering game (or it would be even more fun as we'd be blind about the current ordering :)

**Comment by Frenzie** [comment]
> And with a static "moved to top" icon, we wouldn't have the fun ordering game

It wouldn't be static. ;-)

It'd be something more like:

Move to top (plus 2/3/4/etc.):
![arrow-up-bold-box-outline](https://user-images.githubusercontent.com/202757/104004901-9b7bcb80-51a4-11eb-865d-dcc48dae029d.png) ![arrow-up-drop-circle-outline](https://user-images.githubusercontent.com/202757/104006509-e0086680-51a6-11eb-9626-55de9032a71b.png) ![check-underline-circle-outline](https://user-images.githubusercontent.com/202757/104006512-e0a0fd00-51a6-11eb-9224-da81a2531eb5.png)

At the top (plus 1):
![arrow-up-bold-box](https://user-images.githubusercontent.com/202757/104006546-edbdec00-51a6-11eb-9060-ab5c138e5249.png) ![arrow-up-drop-circle](https://user-images.githubusercontent.com/202757/104006550-edbdec00-51a6-11eb-982e-6b6cef1ee532.png) ![check-underline-circle](https://user-images.githubusercontent.com/202757/104006551-ee568280-51a6-11eb-9435-26ed1f5a38eb.png)

I'd have to play with it to get a better feel for it, and I don't wish to invest that kind of time right now. But while I realize many people may not desire to read in 4+ languages as regularly as I do, I definitely think that ideally this would not be a hidden easter egg.

I suppose the alternative solution is to have a gigantic combined "Western languages" dictionary like you do. :-D

**Comment by poire-z** [comment]
@retrue: can you see how today's nightly works for you and your use cases?

I noticed that when looking up some word that won't be exactly matched in any dict, sdcv might not follow the ordering we give it, but may somehow group results by fuzzy matched terms.
Ex, when looking up "soufis" (plural), i'll get in this order:
```
Sofis (English GLU GCIDE)
Soubise (English GLU GCIDE)
(2) SOUFI (XML Littre, I set as 2nd preferred)
(1) soumis (Woaifayu FR, I set as 1st preferred)
(2) SOUMIS (XML Littre)
soumis (Petit Robert)
```
I don't think it would have been better with the old code - but not caring/investigating.
