### ISSUE TITLE
Custom folder for saving book cover

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#7151]
Device: Nook glowlight Plus 7.8" (2019)
Koreader version: Android 2020.12

Demand: save current reading book folder for setting as screensaver.
More detail: my ereader can only set screensaver image when I put the picture in the folder: ./system/usr/sleep.

I have root, and would like to save current reading book cover to that folder.

Please kindly advise on how to do that or can you spare your time to add a function which allow saving book cover to any folder?

**Comment by poire-z** [comment]
Should already be possible with the plugin "Cover Image" (#6813).

**Comment by uphantom89** [comment]
I did study this plugin before I raised this ticket.
the default saving folder is sdcard/suspend_others.jpg , I don't know how to change that.
Besides that, when I hit "Set system screen saver image" , I tried to look for the image but couldn't see any image file.

**Comment by poire-z** [comment]
Pinging @zwim who knows better what the plugin does.

**Comment by zwim** [comment]
@uphantom89: The plugin should do what you want, but it has to be configured.
I am not used to the nook, so we have to go the full way :)
1.) Do you have `adb`? 
2.) Look in your sdcard. Does `/sdcard/sleep/` exist? If not, please create the folder `sleep`. 
Then enter `/sdcard/sleep/cover.jpg` in the `Set system screensaver image` and check `Save book cover`.
Check with adb, if the file `/sdcard/sleep/cover.jpg` exists. If not, we have a problem.

If the file exists, cover image does, what is expected. Now its up to the android on your device to display the image.

![grafik](https://user-images.githubusercontent.com/36999612/104811257-9d740900-57fa-11eb-8144-b401385bc6ff.png)

3.) Do step 2 with `/usr/bin/sleep/` instead of `/sdcard/sleep`

Maybe this https://blog.the-ebook-reader.com/2014/01/22/how-to-set-custom-screensavers-on-nook-glowlight/ helps you (not the newest, but maybe?). Use `/sdcard/sleep/` as folder.

**Comment by uphantom89** [comment]
I follow your instruction and I did see book cover in the sdcard/sleep/ folder. But i did not trigger the screen saver as the firmware i used, it required to put the picture in the folder /system/usr/sleep 
I don't know where to change that screen saver rerference  link to the folder which you guided me :(

**Comment by zwim** [comment]
OK, that was the first step. Is your cover still in `/sdcard/sleep/cover.jpg`? Then you can try to generate a symbolic link in `/system/usr/sleep/` pointing to `/sdcard/sleep/cover.jpg`.

```
adb shell
su
mount -o remount,rw /system
ln -s /sdcard/sleep/cover.jpg /system/usr/sleep/suspend.jpg
mount -o remount,ro /system
```

**Comment by zwim** [comment]
If the above doesn't work for you, you could try https://help.barnesandnoble.com/app/answers/detail/a_id/936/~/nook-glowlight---customizing-the-screensaver. 
Try to manually put some images in the "Screensavers folder" and get the screensaver to work.
Then find the path of this " "Screensavers" folder found in the NOOK GlowLight™ directory." and post the path here.

**Comment by uphantom89** [comment]
Thank you very much for your detail instruction.
I followed it, there was a cover.jpg shortcut in the system/usr/sleep which link to sdcard/sleep. However, it seems that the system have trouble with understanding that shortcut, It reboot every time I hit the power button.

Ps: I used custom firmware of RyogoNA on xda forum so I couldn't try above B&N instruction link

**Comment by zwim** [comment]
That's bad. You should delete the link in `/system/usr/sleep`, so that your device does not reboot.

The problem is, that on Android you can not write to the `/system/` directory, as this is mounted read-only. 

As far as I am involved, I will NOT include any mechanism to mount the system directory read-write in KOReader. If system would be read-write, a user could overwrite critical parts of the system (and therefore bricking the device!).

If you want to get the cover-image work on your firmware, I can not help you. The best would be, to contact the author of your (custom) firmware, how use a custom sleep image (preferable on the sdcard). If you get an answer how to do that, then I can assist you further.

**Comment by uphantom89** [comment]
Yap, i got your point, thank you very much.
Maybe I will install stock firmware and utilize screensaver plugin of Koreader.
