### ISSUE TITLE
FR: Add Wiktionary support

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#7198]
#### Request
I know there are some Stardict versions of Wiktionary floating around, but they are a bit outdated and lack certain features such as etymology, examples, phonetics, translations. On the other hand, I love the Wikipedia integration. Is it possible to add the same integration for Wiktionary?

#### Alternative
In case that is not feasible, what is the best way to generate an offline Wiktionary? My understanding of the process is:
1. Download [Wiktionary dump](https://dumps.wikimedia.org/backup-index.html) xml file
2. Use [pyglossary](https://github.com/ilius/pyglossary) to convert to Stardict ifo/idx/dict
3. Tweak dictionary [CSS styling](https://github.com/koreader/koreader/wiki/Dictionary-support#html-encoding-within-stardict-dictionaries-supported)

Unfortunatey, I have found this process to be very much not for the average user, slow, prone to failure and at best it generates giant files (5GB+). Any workflow suggestions?

#### Aard2
I have read that aard2 slob files are supported https://github.com/koreader/koreader/issues/2333#issuecomment-508533940 but KOReader does not recognize [these dictionaries](https://github.com/itkach/slob/wiki/Dictionaries)

**Comment by pazos** [comment]
Adding new dict formats is quite an effort. Trying to support all of them or random ones is a bit out of scope for this project.

From the ones that actually have both documentation and an opensource implementation `slob` and `zim` are the two more apealing to me.

> Unfortunatey, I have found this process to be very much not for the average user, slow, prone to failure and at best it generates giant files (5GB+). Any workflow suggestions?

That's because they're huge dicts. Again `slob` and `zim` were written to deal with huge files. I can't talk about slob but zim files are mainly a header, an index and chunks of data compressed using LZMA. That makes possible to package the entire wikipedia without having hundreds of GB used.

> I have read that aard2 slob files are supported

The comment talks about the app `Aard2`, which is supported on android. The reMarkable and other e-ink devices don't have a way to run 3rd party apps.

**Comment by gbyl** [comment]
@pazos I totally misinterpreted your comment then. Thanks for clarifying. I agree that supporting random dictionary formats is out of the scope for this project. As for a potential Wiktionary integration, what would that entail?

**Comment by pazos** [comment]
I'm not sure if `wiktionary` is a think. AFAICT they're just zim files with the content of https://www.wiktionary.org/ instead of https://www.wikipedia.org/

Of course you can convert wikipedia/wiktionary to any other format but it will be slowww and the file will be big and mostly unusable on slow devices.

**Comment by NiLuJe** [comment]
The other solution is not handling off-line Wiktionary at all, but implementing an online Wiktionary scrapper similar to our current Wkipedia one ;).

**Comment by gbyl** [comment]
> Of course you can convert wikipedia/wiktionary to any other format but it will be slowww and the file will be big and mostly unusable on slow devices.

@pazos Yeah, I have learned this the hard way. Dictionary generation is a pain and there are no good guides out there.

> The other solution is not handling off-line Wiktionary at all, but implementing an online Wiktionary scrapper similar to our current Wkipedia one ;).

@NiLuJe You are right as usual! That is exactly what I was suggesting. What would the process of implementing the [Wiktionary API](https://en.wiktionary.org/w/api.php) look like?

**Comment by NiLuJe** [comment]
Not quite sure, because I'm not even sure we're actually using the API at all in the scrapper (@poire-z?) ;).

**Comment by poire-z** [comment]
I would expect wiktionary to not have reinvented the wheekeel and use the same API as wikipedia.
```diff
--- a/frontend/ui/wikipedia.lua
+++ b/frontend/ui/wikipedia.lua
@@ -21,3 +21,3 @@ local T = ffiutil.template
 local Wikipedia = {
-   wiki_server = "https://%s.wikipedia.org",
+   wiki_server = "https://%s.wiktionary.org",
    wiki_path = "/w/api.php",
```
shows that it works. The results are ugly though, and would probably need another kind of massage.

(But I really don't want to think about how this could be integrated UI and code wise in the already tortuous ReaderDict <> ReaderWikipedia roundabout.)

**Comment by gbyl** [comment]
> The results are ugly though, and would probably need another kind of massage.

@poire-z It works! Would you mind elaborating on what you mean by "massage"?

> (But I really don't want to think about how this could be integrated UI and code wise in the already tortuous ReaderDict <> ReaderWikipedia roundabout.)

How about we create a toggle `Use Wiktionary` under `Magnifying Glass Icon > Dictionary settings`? When activated, it would make the "Dictionary" button (from the long press menu) act as a Wiktionary search.

**Comment by poire-z** [comment]
> Would you mind elaborating on what you mean by "massage"?

A 3 definitions results becomes a 2 pages window because of the headings with the black symbols and empty lines all around. We'd probably want something more condensed.

> When activated, it would make the "Dictionary" button (from the long press menu) act as a Wiktionary search.

Easier said than done :) :

> But I really don't want to think about how this could be integrated UI and code wise in the already tortuous ReaderDict <> ReaderWikipedia roundabout.)

This Wiktionary could more easily been integrated as a Wikipedia replacement, having ReaderDict => ReaderWiktionary would be easy.
Having ReaderWiktionary => ReaderWikipedia is more complex, it would need hacks to the already twisted flow, buttons reorganising (language, full result, or show the full result initially, but then the API calls change from the Wikipedia, etc...)
Not impossible, but needs some thinking - and a bit unwilling to dive into that as it feels of little interest (from what I just saw, the results are a lot less worth than from proper dicts).

(Some other maybe uglier but easier solution would be to _not_ have it that naturally integrated, but just as a button in the highlight button dialog : <kbd>Dictionary</kbd> (that you wouldn't care about | <kbd>Wikipedia</kbd> | <kbd>Wiktionary</kbd>. Choosing Wiktionary, you'll get stuck to it (no way to go directly to Wkipedia): you'd have to close it to hit Wikipedia when back to that button table. And you'll get useless <kbd>Wiktionary full</kbd> and <kbd>Wiktionary Save as EPUB</kbd> so it would still need some hacks and duplication).

**Comment by gbyl** [comment]
> and a bit unwilling to dive into that as it feels of little interest (from what I just saw, the results are a lot less worth than from proper dicts)

I understand. It sounds like it would be more difficult than I thought. A proper Stardict dictionary would indeed be great, but from what I have read in several forums, most people have a hard time finding those. There is no unified repository and the quality can be very hit or miss. I thought Wiktionary in KOReader would be an excellent up-to-date, standardized option across languages for most users.

**Comment by gbyl** [comment]
> This Wiktionary could more easily been integrated as a Wikipedia replacement, having ReaderDict => ReaderWiktionary would be easy.
Having ReaderWiktionary => ReaderWikipedia is more complex […]

I'm curious, did you mean the opposite here? i.e. "ReaderWiktionary => ReaderWikipedia" would be the easy alternative?

>(Some other maybe uglier but easier solution would be to not have it that naturally integrated, but just as a button in the highlight button dialog : Dictionary (that you wouldn't care about | Wikipedia | Wiktionary.

Is there a quick and dirty way of replacing that Dictionary button in the highlight dialog with a tweaked duplicate of the Wikipedia button? I'm thinking of adding that for my custom KOReader.

**Comment by poire-z** [comment]
> I'm curious, did you mean the opposite here?

No, I did not :) I guess that's what you would like, but ReaderWiktionary => ReaderWikipedia is the not easy way.

> Is there a quick and dirty way of replacing that Dictionary button in the highlight dialog with a tweaked duplicate of the Wikipedia button

Really dirty:
```diff
--- a/frontend/apps/reader/modules/readerhighlight.lua
+++ b/frontend/apps/reader/modules/readerhighlight.lua
@@ -97,6 +97,7 @@ function ReaderHighlight:init()
                 text = _("Wikipedia"),
                 callback = function()
                     UIManager:scheduleIn(0.1, function()
+                        Wikipedia.wiki_server = "https://%s.wikipedia.org"
                         _self:lookupWikipedia()
                         -- We don't call _self:onClose(), we need the highlight
                         -- to still be there, as we may Highlight it from the
@@ -107,10 +108,15 @@ function ReaderHighlight:init()
         end,
         ["06_dictionary"] = function(_self)
             return {
-                text = _("Dictionary"),
+                text = _("Wiktionary"),
                 callback = function()
-                    _self:onHighlightDictLookup()
-                    -- We don't call _self:onClose(), same reason as above
+                    UIManager:scheduleIn(0.1, function()
+                        if self.selected_text then
+                            local Wikipedia = require("ui/wikipedia")
+                            Wikipedia.wiki_server = "https://%s.wiktionary.org"
+                            self.ui:handleEvent(Event:new("LookupWikipedia", cleanupSelectedText(self.selected_text.text)))
+                        end
+                    end)
                 end,
             }
         end,
```
You would have to hit in that button table <kbd>Wikipedia</kbd> to switch back the whole Wikipedia code to re-use wikipedia.org. There's no easy way to do that automatically once you're done with the Wiktionary windows.

**Comment by gbyl** [comment]
> No, I did not :) I guess that's what you would like, but ReaderWiktionary => ReaderWikipedia is the not easy way

Actually, "ReaderDict => ReaderWiktionary" is what I was suggesting from the beginning. In fact, the code you wrote above is exactly what I meant. Thanks!

I did have to add: 

```
if self.selected_text then
    local Wikipedia = require("ui/wikipedia")
    Wikipedia.wiki_server = "https://%s.wikipedia.org"
    self.ui:handleEvent(Event:new("LookupWikipedia", cleanupSelectedText(self.selected_text.text)))
end
```

instead of just

```
Wikipedia.wiki_server = "https://%s.wikipedia.org"
_self:lookupWikipedia()
```

because it was complaining about a variable being nil and crashing.

One last question: which file should I take a look at for the filtering of the Wiktionary output i.e. to generate a more condensed version?

**Comment by poire-z** [comment]
> Actually, "ReaderDict => ReaderWiktionary" is what I was suggesting from the beginning

If you're ready to sacrifice Wikipedia to just get Wiktionary instead, indeed, everything is simpler. You'd just need to use the 1 line change from https://github.com/koreader/koreader/issues/7198#issuecomment-766416273.
But that means you'd still get the stardict result first on a long press, so possibly empty. In your use case, would you still use stardict dicts, and just get Wiktionaries as a secondary choice - or would you just not have stardicts in the way?

> I did have to add:

Oh yes, I forgot `local Wikipedia = require("ui/wikipedia")`

> One last question: which file should I take a look at for the filtering of the Wiktionary output i.e. to generate a more condensed version?

It would be https://github.com/koreader/koreader/blob/master/frontend/ui/wikipedia.lua
Especially:
https://github.com/koreader/koreader/blob/a5768c741180b66551caded25213fa96c2947492/frontend/ui/wikipedia.lua#L584-L621
(beware, there is a similar section below with h1_sym  instead of th1_sym which is just used for the same prettification but in the Save as EPUB case.)

`\n` means a carriage return. If you'd like to strip some blank line you'd need to add some of them on the left, or remove on the right in the stuff like:
`text = text:gsub("\n=== ", "\n"..th3_sym.." ") `

If you manage to get something nice by hacking this, we could avoid the duplication by just having a frontend/ui/wiktionary.lua that would "extend" wikipedia.lua, with could contain just overrides of the functions you'd need to adapt.
And if you're really ready to sacrifice Wikipedia, we could just have a `[ ] Use Wiktionary instead of Wikipedia` so wiktionary.lua masquerades as wikipedia.lua.

(We get as results some plain text summary from the API: it looks to me that some content is stripped out, like translations - so you might not be super happy with the result you'll get... This happens also with Wikipedia: tables, lists may not be in the results and not even the "full" result.)

**Comment by gbyl** [comment]
>  In your use case, would you still use stardict dicts, and just get Wiktionaries as a secondary choice - or would you just not have stardicts in the way?

The latter. I was thinking of Wiktionary as a stardict dictionaries replacement. So rather a `[ ] Use Wiktionary instead of Dictionary` kind of toggle.

> If you manage to get something nice by hacking this, we could avoid the duplication by just having a frontend/ui/wiktionary.lua that would "extend" wikipedia.lua, with could contain just overrides of the functions you'd need to adapt.

That sounds like an interesting idea. I'll play with those settings and report back if I manage to get decent results.

> it looks to me that some content is stripped out, like translations - so you might not be super happy with the result you'll get... This happens also with Wikipedia: tables, lists may not be in the results and not even the "full" result.

Yeah, I noticed that too. I can do away with the translation section altogether since there is already a built-in translator. I see that bulleted and numbered lists aren't rendering correctly either. Tabs are suppressed. There are several awkward carriage returns. Some "quotations" get half-rendered — if you try the word "specious" you'll see what I mean.

I still think that prettyfying the Wiktionary output will be less frustrating than searching for a decent Stardict dictionary — especially since once accomplished, it has the potential to save a lot of headache for the average KOReader user.

**Comment by gbyl** [comment]
I was unable to get decent results no matter how hard I tried — to say nothing of results worthy of a PR. Definitely gives one a renewed sense of respect for those involved in the implementation of all things dictionaries for KOReader. Closing the issue as it seems to entail a disproportional amount of effort for a not highly requested feature.

**Comment by Frenzie** [comment]
That's too bad. Could you provide a sample Wiktionary query?
