### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#7243]
I just realized the screenshots haven't been updated with the new icons yet.

**Comment by SteadyQuad** [comment]
Created a PR for a new set of images for koreader-artwork. (The image named footnote is not actually of a proper footnote, but I suppose they images are mainly meant to give an impression of KOreader). I think koreader/README.md does not need to be modified as the png filenames did not change.

**Comment by poire-z** [comment]
> The image named footnote is not actually of a proper footnote, but I suppose they images are mainly meant to give an impression of KOreader

I guess it is meant to give the impression that KOReader has nice support for footnotes - so, not actually showing footnotes is a bit... not impressive :)

**Comment by Frenzie** [comment]
> (The image named footnote is not actually of a proper footnote, but I suppose they images are mainly meant to give an impression of KOreader). 

An impression of a *footnote*, yes. ;-)

**Comment by Frenzie** [comment]
Thanks for making the effort! 

I'm not super attached to the ereader Wikipedia page EPUB (created through KOReader itself), but something along those lines is a lot more neutral than a manual for a specific device. ^_^

**Comment by SteadyQuad** [comment]
> Thanks for making the effort!

No problem, looking forward to 2021.03, so I thought I'd help a bit.

Given the desire to highlight the footnote capabilities of KOreader like the current set, I have prepared a new set of images in the emulator. (previous set came directly from my Pocketbook device). 

Instead of the device manual document featured in the previous set, I have selected the Wikipedia page of Mullets (the fish) as a more neutral document. The page contains text, images and... footnotes!

Let me know if these are OK.

PS if v2021.03 is not named yet, might I suggest Magnificent Mullet?

**Comment by Frenzie** [comment]
> Let me know if these are OK.

At a quick glance the content seems fine, but the lower resolution's a bit blurry. You can run it at a better size with something like `-s=kobo-aura-one` as an argument.

Also since they're meant for online display the size should be controlled by pulling them through pngquant. Apologies for not mentioning that before.

> PS if v2021.03 is not named yet, might I suggest Magnificent Mullet?

:rofl: Why not. :-)

**Comment by poire-z** [comment]
Not really that fine :/

Not sure about the choice of this Wikipedia article - a fish ? why not something a bit less random, but still neutral, like Gutemberg or something related to book or typesetting?

But really not fine about the page it shows:
1) you're in scroll mode, with text of lines truncated (which does not look good, and we aim at pleasing): switch to page mode
2) you have a thumbnail float truncated - which is ok in scroll mode, but should not happen in page mode (the code tries to avoid that, but it might still happen: don't select a page where it happens).
3) you're not showing footnotes - I mean you're showing the a section at the end of the book with a bit of the last page of real content, and a bit of the first page with footnotes content.
What the previous screenshots are showing are "in-page footnotes", that you can enable via `Style tweaks>Misc>In-page footnotes> Wikipedia (small)` - which is a nice feature (that you may not know about) that is nice showing off (so that you and others can know about it): it should show footnote content only for the footnotes link visible in the page above.

And may be we should vary the font size and family, the margins... (the current ones are not to my taste, I would not buy KOReader when seeing them :)

Also, you don't need to open a new PR for each change, you can just update an existing one (git push -f).

**Comment by Frenzie** [comment]
No need to git push -f either, except traditionally when done.

**Comment by SteadyQuad** [comment]
> Not really that fine :/
You drive a hard bargain! ;-)

> Not sure about the choice of this Wikipedia article - a fish ? why not something a bit less random, but still neutral, like Gutemberg or something related to book or typesetting?

I browsed wikipedia for a random page that had a combination of text, images and footnotes that would fit in one screen (for visual appeal). I guess the Mullet just came out one top! (Personally I haven't had any bad experiences with them) I've been a fan of Project Gutenberg for a long time, but it's also a bit cliche to display on an ereader if you ask me. I'll see if I can find a subject closer to reading/books than Mullets though.

Regarding you 3 points:

1. I used scroll mode to fit text, image and footnotes on one page, but I'll switch to page mode instead. (You're referring to the ugly truncated lines at top and bottom, right?)
2. a truncated thumbnail: I'll try pagemode for this as well.
3. You're right I didn't know about this wikipedia footnote feature, now I know why you emphasized the footnotes. I saw them as just links. I'll try out the feature, it's specifically for wikipedia pages, right?

As for fonts, I'm a big fan of Ubuntu font for reading, looks nice, timeless yet modern enough, maybe I'll try that. I tried to keep the 3 images related in style: same content, font and settings. Wouldn't varying settings between images make them less coherent, like they belong to different apps? 

Lastly, I started a new PR because otherwise the history of rejected images would build up. I guess a final `git push -f` for the winning set of pictures would fix that.

I'll have one more go at a visually pleasing, icon-set showing, footnote optimized, set of screenshots with minimal amount of fish.

**Comment by SteadyQuad** [comment]
> At a quick glance the content seems fine, but the lower resolution's a bit blurry. You can run it at a better size with something like `-s=kobo-aura-one` as an argument.

To keep original and thumbnail images the same, I resized the originals to 600x800 thumbnails with lineair interpolation (which produced the sharpest resizeing) 600x800 is the same size as the current thumbnail images I think and I can't see that they're more blurry than the old ones). However, these 600x800 thumbnail images get resized by the README.md to a width of 200 (and to 250 for koreader.rocks), so 2 resizes might make them more blurry than necessary. I could resize directly to display width, see if that makes them a bit sharper. (width=250 for both README.md and website?)

> Also since they're meant for online display the size should be controlled by pulling them through pngquant. Apologies for not mentioning that before.

I'll optimize the next set.
 
> > PS if v2021.03 is not named yet, might I suggest Magnificent Mullet?
> 
> 🤣 Why not. :-)

🐟✔️

**Comment by poire-z** [comment]
>  I've been a fan of Project Gutenberg for a long time, but it's also a bit cliche to display on an ereader if you ask me

Was thinking rather about the person :) : 

<kbd>![image](https://user-images.githubusercontent.com/24273478/110864003-ccba6a00-82c1-11eb-9b83-a0d21e82e972.png)</kbd>
And the kind of page I'd like to see (although the more colorful images there are the merrier):
<kbd>![image](https://user-images.githubusercontent.com/24273478/110864158-04c1ad00-82c2-11eb-9534-171b0f6b9af9.png)</kbd>
but not that one (that get the bottom of the float truncated).
<kbd>![image](https://user-images.githubusercontent.com/24273478/110864341-3dfa1d00-82c2-11eb-8bef-9f4c4277e971.png)</kbd>

> (You're referring to the ugly truncated lines at top and bottom, right?)

Right.

> Wouldn't varying settings between images make them less coherent, like they belong to different apps?

Probably. But it would be nice to show variations for plain book pages, may be in additional screenshots?

> I'll try out the feature, it's specifically for wikipedia pages, right?

No, there are 3 variations of style tweaks: for Wikipedia (that we build, so we know the structure), for EPUB where the publisher has used some attributes to say things are link to footnotes or things are footnotes, but very little publishers do that well) - so a last ones with "classic classnames", that may work or not when the previous one doesn't. Or, and another one for russian FB2 books.
https://github.com/koreader/koreader/wiki/In-page-footnotes
https://github.com/koreader/koreader/pull/4440
https://github.com/koreader/koreader/pull/4454

> You drive a hard bargain! ;-)

Yes, but you won't find anything better at the other shops ! :)

**Comment by Frenzie** [comment]
> To keep original and thumbnail images the same, I resized the originals to 600x800 thumbnails with lineair interpolation (which produced the sharpest resizeing) 600x800 is the same size as the current thumbnail images I think and I can't see that they're more blurry than the old ones). However, these 600x800 thumbnail images get resized by the README.md to a width of 200 (and to 250 for koreader.rocks), so 2 resizes might make them more blurry than necessary. I could resize directly to display width, see if that makes them a bit sharper. (width=250 for both README.md and website?)

I'm talking about the originals, which are practically thumbnail size themselves. ;-)

First of, the thumbnails are usually rendered at significantly more pixels. At the most typical regular desktop scenario ~500×700. Then when you click on the thumbnail, you expect to see a sharp picture.
<img src=https://user-images.githubusercontent.com/202757/110902360-1331b800-8306-11eb-9aa0-f79060f5157b.png width=45%> <img src=https://user-images.githubusercontent.com/202757/110902365-13ca4e80-8306-11eb-9000-f8e0f5acc3d7.png width=45%>

Slightly less typical on a desktop, but far from uncommon, and regular for a phone, the thumbnails are currently undersized. I might let them pull in the full version, or possibly add a small or medium. Your screenshot is a small.

<img src=https://user-images.githubusercontent.com/202757/110903038-17120a00-8307-11eb-840b-f1e73ba11522.png width=45%>  <img src=https://user-images.githubusercontent.com/202757/110902807-baaeea80-8306-11eb-9a50-fb889a4fc109.jpg width=45%>

The small screenshot becomes blurry when you open it. That specifically is what I don't want to see.

<img src=https://user-images.githubusercontent.com/202757/110902367-1462e500-8306-11eb-8171-6c276e8a1a85.png width=45%>

**Comment by SteadyQuad** [comment]
Third time's hopefully a charm!

Thanks Frenzie and poire-z for the feedback. I'm using a 1920x1080 display, some of your screenshots are higher res, which would explain some difference in blurriness we perceive. I checked the README.md markdown source before, which specifies 200px for the 3 images, which is why I focussed on that small res as well. I now get that the final render on screen might actually be larger than 200px (altough it's pretty close to that on my 1920x1080 screen).

For this new set of screenshots I strechted the emulator to 1200x1600 (which wasn't trivial for my screen: the fresh emulator window gets clipped to screen height: 1080 in my case. I used `wmctrl` after that to force the window to be larger than my screen.

'releasenotes' for this iteration: 

- neurtral wikipedia page (with image, text and footnotes)
- shows proper inpage footnotes feature
- originals are now 1200x1600 (previously 750x1000)
- font: Bookerly
- set some margins (20px L/R)
- increased the height of the progressbar slightly, to keep it visible in the thumbnails
- included some extra widgets in the statusbar just for showing off
- did my best to optimize quality when resizing in Gimp from original size to thumbnail size, sharpening/darkening the resulting text/lines a bit (but not the picture that's in the wikipedia page).
- ran pngquant on the final pictures to minimize size

I didn't take note of the previous originals resolution but they're close:

filename | current (master) res | new res
-- | -- | --
koreader-dictionary.png | 1404x1872 | 1200x1600
koreader-footnotes.png | 1404x1872 | 1200x1600
koreader-menu.png | 1404x1872 | 1200x1600
koreader-dictionary-thumbnail.png | 600x800 | 600x800
koreader-footnotes-thumbnail.png | 600x800 | 600x800
koreader-menu-thumbnail.png | 600x800 | 600x800

**Comment by poire-z** [comment]
Fine with me (about what the screenshots show - no idea about image sizes and quality :)

**Comment by Frenzie** [comment]
That does actually still come out a little bit blurrier than the old screenshot because the number of available vertical pixels in a regular not fullscreen browser tab is typically above 1800 (as in roughly 2160-300), but it's probably fine.

1404x1872 isn't a well thought out size per se — it's just the size of the display on the Kobo Aura One. But it's also a good size for UHD monitors.

**Comment by SteadyQuad** [comment]
Not sure that anyone's going to even notice the difference, but since I'm such a big fan of KOReader I redid the screenshots in 1404x1872 instead of 1200x1600.

Thanks for your work on KOReader!

**Comment by SteadyQuad** [comment]
I see this is not merged yet, so took the opportunity to enhance sharpness of the thumbnail images slightly. For reference, I used this imagemagick command to produce the thumbnail images from the originals:
`convert koreader-footnotes.png -filter spline -resize 600x -unsharp 0x1+1.0+0.01  koreader-footnotes-thumbnail.png`

**Comment by Frenzie** [comment]
Pssht, I think you forgot to pngquant them afterward.

**Comment by SteadyQuad** [comment]
I understand you don't want to make use of todays special of 3x the bits for the same price? I stripped them.
