### ISSUE TITLE
boox poke 3

### ISSUE THREAD

**Issue by tnuser1200** [koreader/koreader#7264]
* KOReader version: 2021.01.1
* Device: boox poke 3

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

**Comment by pazos** [comment]
To be clear: android input behaviour is on par with **KOReader** behaviour on other OSes. If that's not true on a specific model we can't fix that.

**Comment by poire-z** [comment]
> turn page. read for few minutes. try turn page again by touching screen - that's it no response

Does it happen when you read for a few seconds instead of a few minutes before taping again?
In which case, it may be the system getting into standby to save battery - and it notices your first tap and is waken up by it - but the system does not forward it to KOReader ?
If true, and the system really doesn't forward the first tap to the foreground app, the only solution might be to prevent the system from going into standby when KOReader is at the foreground, via some system settings/menu?

Dunno if out stuff in `Top menu > Gear > Screen > Screen timeout` or `Gear > Device > Battery optimisations` can help with that.

**Comment by Galunid** [comment]
> Issue Touch screen sometimes need two touches. Only happens in KOReader

Actually it happens in other apps (at least on my Nova 2). The reason is that **Android** doesn't detect the tap. So it's either bug in onyx firmware, or you just need to tap harder. In any case, it's not KOReader related.
