### ISSUE TITLE
Inkbook Prime Frontlight control issues (it's hard to disable it)

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#7275]
* KOReader version: v2021.01-3-gf48820_21-01-26 (upgraded from most probably _202-05-19.apk; I also had _2020-11-08.apk but as far as I remember I didn't use it) 
* Device: Inkbook Prime (Android 4.4.2)

#### Issue

After upgrade  to nightly v2021.01-3-gf48820_21-01-26 in my Inkbook Prime earned an additional lower frontlight level, which is great - thanks for that:) 

But unfortunately, there're some issues in controlling disabling the frontlight - is there any way to make it better?
See video:
https://youtu.be/dx40ZwZCcyo

If not then I'm fine with it - as I wrote I now have the lower frontlight level - which I have had always wanted to have;)

#### Steps to reproduce:

on Inkbook Prime try to disable frontlight

**Comment by pazos** [comment]
Tapping bottom left toggles frontlight. Sliding left changes brightness.

If you're talking about the behaviour of the slider. That's an android dialog. Is not meant to tap it directly, but pressing the slider and then slide :)

Also see https://github.com/koreader/android-luajit-launcher/issues/290 (was a koreader issue that I moved to the other repo because it needs to be implemented there :))

**Comment by mwoz123** [comment]
> If you're talking about the behaviour of the slider. That's an android dialog. Is not meant to tap it directly, but pressing the slider and then slide :)

Thanks. Knowing that works much better :D 
I can now disable it as set it to low level

> Tapping bottom left toggles frontlight. Sliding left changes brightness.

Toggle sets to min level now (instead disabling), sliding left also can't disable it, but it's very minor issue now as I'm happy with Android dialog ;) 

@pazos  Thanks:)

**Comment by pazos** [comment]
> Toggle sets to min level now (instead disabling), sliding left also can't disable it, but it's very minor issue now as I'm happy with Android dialog ;)

That depends on the android implementation :p

We're just requesting the minimum possible level of brightness, which should be 0 on e-ink devices. If that doesn't happen is because most e-ink device implementations are broken and don't expose sane APIs. 

It still possible to opt-out of the generic light controller (which works on 100% on android lcd devices) and use a custom one. See https://github.com/koreader/android-luajit-launcher/tree/master/app/src/main/java/org/koreader/launcher/device/lights

I guess you can write your own controller based on `GenericController` but using [`System.getInt`](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/lights/TolinoWarmthController.kt#L88-L96) and [`System.putInt`](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/lights/TolinoWarmthController.kt#L108-L120) instead of windows attributes.

That should work for 99% of legacy e-ink devices.
