### ISSUE TITLE
FR: Minimum (or fixed) size for dogear mark

### ISSUE THREAD

**Issue by Jellby** [koreader/koreader#7364]
I like reading with minimalistic margins (the device screen is small enough to waste it with margins). Unfortunately, that makes the "dogear" mark for bookmarks really tiny and hard to see.

**Describe the solution you'd like**
I'd like a setting for minimum dogear size, or a fixed size, independent of the margins.

I use bookmarks seldom enough that possible overlapping with the text is not a concern for me, but for robustness, maybe the dogear mark could have a partial opacity, or invert the text underneath?

**Additional context**

Default bookmark with 5-size margins
![Screenshot_20210228_112052](https://user-images.githubusercontent.com/7943459/109415181-78f17c00-79b7-11eb-833f-abb59023069c.png)

15-size boommark with 5-size margins (mockup)
![Screenshot_20210228_112754](https://user-images.githubusercontent.com/7943459/109415357-780d1a00-79b8-11eb-9968-d5931f87ec61.png)

**Comment by NiLuJe** [comment]
Ping @poire-z for more comments, because I don't rightly recall everything that was said the last time this was discussed ;).

We can *probably* do all of the above:

* Enforce a minimum size
* Update the icon to use transparency, but only for the lower-left corner
* Tell IconWidget about that, like I did for the overlap arrow

(Only inverting the text would be complex, we could invert *the whole target square* before alpha-blending, but that would mean a weird corner with black background ^^).

**Comment by poire-z** [comment]
(I'm not sure we ever discussed that :) I might just have reduced the dogear size at to keep the text clean without asking :)

As we enforce a max size (a size enough to notice the dogear, if huge margins), the logical idea could be to enforce a min width (a size large enough to notice the dogear, even if it overrides the text).
Then, the 2nd option is to keep the text readable/guessable, so do it if it's cheap.

Not sure about inverting the text, that would feel ugly (and mean a part of the dogear would be full solid black ?)

Anyway, no real opinion. I let you small margin users decide what you prefer :)

**Comment by NiLuJe** [comment]
I vaguely recall an(old) inline discussion about the dogear look... somewhere ^^.

But, yeah, agreed, will do ;).

**Comment by Frenzie** [comment]
I think it was unscaled and @poire-z and I preferred how that accidentally
turned out on 300 dpi.
