### ISSUE TITLE
Uneven stretching of space at the beginning of paragraph

### ISSUE THREAD

**Issue by Jellby** [koreader/koreader#7366]
* KOReader version: v2021-02-20
* Device: emulator (and Kobo Aura)

#### Issue

When a paragraph begins with `. ` (period, space; this can happen when ellipses are typeset as `. . .`), the first space does not stretch like the other spaces to justify the line, creating a very ugly effect

#### Steps to reproduce

* Open [test.zip](https://github.com/koreader/koreader/files/6056630/test.zip) (rename to .epub if necessary).

* Render with justified text, hyphenation disabled.

![Screenshot_20210228_114656](https://user-images.githubusercontent.com/7943459/109415937-beb04380-79bb-11eb-8e17-fd3fd405a891.png)

Of course the huge spaces in the first line of the second paragraph are not nice, but that's an intended exaggeration here. The point is the circled ellipsis with an extremely uneven spacing.

**Comment by poire-z** [comment]
We have these:
https://github.com/koreader/crengine/blob/faffa087a4e64cdd00d0c0f373cbe729a84e3a0f/crengine/src/lvtextfm.cpp#L1916-L1936
https://github.com/koreader/crengine/blob/faffa087a4e64cdd00d0c0f373cbe729a84e3a0f/crengine/src/lvtextfm.cpp#L3733-L3742

> when ellipses are typeset as `. . .` 

Well, hard to do the right thing when publisher do crappy typesetting.
I guess for this case, we could add something like that in the first snippet:
```c
if ( k < len-2 && isLeftPunctuation(m_text[k+1] && flags[k+2] & LCHAR_IS_SPACE) {
 // give up any lock spacing when consecutive left punctuations...
}
else {
 // the stuff we do
}
```
But I have no idea is this will break other cases when it was the right thing to do...

**Comment by Jellby** [comment]
It can be argued that ellipses typeset with spaces (non-breaking of course) give a nicer (more consistent) look than using the `…` character.

And, by the way, using `…` shows a similar problem:
![Screenshot_20210228_123900](https://user-images.githubusercontent.com/7943459/109417026-1b166180-79c2-11eb-8336-32fedc4ef0c8.png)

In which situations is a period or an ellipsis a "left"/"opening" character? Is something similar done for "right"/"closing" marks? Perhaps not only the first space, but all spaces in sequence of `(left space)*` should be locked (e.g. nested quotes)

**Comment by poire-z** [comment]
> And, by the way, using … shows a similar problem:

I would not consider this a problem - rather the expected behaviour with the "locked spacing after leading punctuation" feature. I added it in https://github.com/koreader/crengine/pull/326 to fix this:
<kbd>![image](https://user-images.githubusercontent.com/24273478/73158578-86697200-40e4-11ea-8601-0d373fd5e438.png)</kbd>
(even more noticable when paragraphs of 2+ lines (so, first line justified) are mixed with 1-line paragraphs (so, not justified).
The question is then if we should loosen the list of "left punctuation", but I can imagine some documents prefixing each line with an ellipsis for some effect or meaning.

> In which situations is a period or an ellipsis a "left"/"opening" character?

I don't know :) a period could have been used as a cheap bullet - given that there is no other reason I can think of to start a line with period+space.
For the ellipsis, I don't know, is it really common in some languages (spanish?)? And what is it supposed to mean (hard to guess with your lorem ipsum...)

> Is something similar done for "right"/"closing" marks? 

It's less critical on the right, as chances of ending a justified line with such marks are low. And having consecutive such justified lines ending with such marks are low^².
Unlike with leading left punctuations, as any dialog do use such a char, a quote or a dash.


> Perhaps not only the first space, but all spaces in sequence of (left space)* should be locked (e.g. nested quotes)

That feels like the right way to handle this.
(And you'd be ok to have the first `. . .` narrow, and the others in the line and paragraph - including some that happens to be at start of a 2nd++ line after wrapping - be wider, with a variable width?)

**Comment by Jellby** [comment]
> I added it in [koreader/crengine#326](https://github.com/koreader/crengine/pull/326) to fix this:
> ![image](https://user-images.githubusercontent.com/24273478/73158578-86697200-40e4-11ea-8601-0d373fd5e438.png)

And I'd say the publisher should have used thin no-break spaces ;) But the true problem is that there seems to be no (portable) code for stretchable/non-stretchable spaces (as there is e.g. in LaTeX). I don't think spaces like what you have in French punctuation should *ever* be stretched...

> (even more noticable when paragraphs of 2+ lines (so, first line justified) are mixed with 1-line paragraphs (so, not justified).
> The question is then if we should loosen the list of "left punctuation", but I can imagine some documents prefixing each line with an ellipsis for some effect or meaning.

You could also have consecutive paragraphs starting with some short word (like "a") where uneven space would look bad, but I wouldn't say those spaces should be locked.

> For the ellipsis, I don't know, is it really common in some languages (spanish?)? And what is it supposed to mean (hard to guess with your lorem ipsum...)

That was actually an English text originally (In Spanish an ellipsis would be three dots without spaces in between). Example: https://books.google.es/books?id=2lPNDAZOx4kC&lpg=PP1&dq=wings%20pratchett&pg=PA14#v=onepage&q&f=false

> > Perhaps not only the first space, but all spaces in sequence of (left space)* should be locked (e.g. nested quotes)
> 
> That feels like the right way to handle this.
> (And you'd be ok to have the first `. . .` narrow, and the others in the line and paragraph - including some that happens to be at start of a 2nd++ line after wrapping - be wider, with a variable width?)

Yes, that would be less noticeable. But I'd advocate for removing period and ellipsis from the "left punctuation" list.

**Comment by Frenzie** [comment]
> But I'd advocate for removing period and ellipsis al least from the "left punctuation" list.

…what?!

;-)

**Comment by Jellby** [comment]
... for the purposes of spacing ;)  (i.e., the space before "for" should be the same width as the one after)

**Comment by poire-z** [comment]
> And I'd say the publisher should have used thin no-break spaces ;)

Probably - but we can try to do the right/best thing when the publisher has been negligent.

> But the true problem is that there seems to be no (portable) code for stretchable/non-stretchable spaces (as there is e.g. in LaTeX).

I don't get what you mean.
(In crengine, only regular space and non-break-spaces are candidate for condensation/stretching - all other unicode spaces have a fixed width per definition.)

> I don't think spaces like what you have in French punctuation should ever be stretched...

Well. I'm not sure. For this french bit `Vraiment ? : « " blah " n'est pas un mot !`, I guess I would be fine with expanding spaces all around. A constrained `t?:«"b` (with minimal locked spacing) in the middle would feel stranger if everything other spaces get large because of justification.

On that Google Books book:
<kbd>![image](https://user-images.githubusercontent.com/24273478/109423875-91768c00-79e1-11eb-97de-a0f79acba011.png)</kbd>
the space between dots have locked spacing - but not the one after.

And I personally would be bothered (as I was with unlocked spaces after « or -) that the space after is not locked if I were seeing a lot of them in a book in such small paragraphs.
Remove the "focus" lines, add a few short lines above it, and I would notice "blues" is not aligned with the first word of next lines:
<kbd>![image](https://user-images.githubusercontent.com/24273478/109424125-a0aa0980-79e2-11eb-898c-4e49db9b2ad8.png)</kbd>
(If this was poetry, it would look bad :)

**Comment by Jellby** [comment]
> > But the true problem is that there seems to be no (portable) code for stretchable/non-stretchable spaces (as there is e.g. in LaTeX).
> 
> I don't get what you mean.
> (In crengine, only regular space and non-break-spaces are candidate for condensation/stretching - all other unicode spaces have a fixed width per definition.)

I mean that ideally one should be able to say (when coding/writing the book) whether or not a particular space should be stretchable, just like one can say whether or not it's breakable.

> > I don't think spaces like what you have in French punctuation should ever be stretched...
> 
> Well. I'm not sure. For this french bit `Vraiment ? : « " blah " n'est pas un mot !`, I guess I would be fine with expanding spaces all around. A constrained `t?:«"b` (with minimal locked spacing) in the middle would feel stranger if everything other spaces get large because of justification.

As a non-native French, I'd expect something like:
```text
Vraiment ? :   « " blah "   n'est   pas   un   mot !
```
(i.e., stretch only the spaces that we'd keep in other languages), but I'm obviously not an authority :) Maybe to you the two spaces around `:` look the same? To me they are different types and they are allowed to be of different width.

> On that Google Books book:
> ![image](https://user-images.githubusercontent.com/24273478/109423875-91768c00-79e1-11eb-97de-a0f79acba011.png)
> the space between dots have locked spacing - but not the one after.

Exactly, which goes to further prove my point

> And I personally would be bothered (as I was with unlocked spaces after « or -) that the space after is not locked if I were seeing a lot of them in a book in such small paragraphs.

But that's more in the field of avoiding rivers and too different stretch factors in neighboring lines, it's not that this particular space is special. The same would happen if you have several consecutive short paragraphs starting with, say, "*Item:*".

> (If this was poetry, it would look bad :)

Absolutely. Never justify poetry (and I guess that goes for both meanings of "justify") :)

**Comment by poire-z** [comment]
> I mean that ideally one should be able to say (when coding/writing the book) whether or not a particular space should be stretchable, just like one can say whether or not it's breakable.

But a publisher/author/writer can just do that: use the thin-space, hair-space and the like if he doesn't want it stretched, and use the non-specified-width ones where he wants to allow condensing/stretching for justification. (Dunno if there's such a specified-width space the size of the regular space if one want a regular space widthed space to not stretch :)
So, he can do it. We're just trying to do what he has not done in the cases we can guess safely he has just not done it where he should have.

> Maybe to you the two spaces around : look the same? To me they are different types and they are allowed to be of different width.

Well, personally, not being such an aesthete regarding typography, I guess I would not care :) If the publisher did the job of using thin spaces, good for me and the more aesthet readers :) If not, I'm bearing these fine. It's harder to have the code make such typographical decisions (could be left to textlang.cpp if one would like to enhance that per language, like you did for em-dash).

> But that's more in the field of avoiding rivers and too different stretch factors in neighboring lines, it's not that this particular space is special.

Yes, I'm more sensitive to edges/margins/hanging punctuation and the overall page to look sharp. (That's what's left to the un-art-educated people like me: in a Rembrandt painting, I'd appreciate the sharp woody frame more than the canvas :)

> The same would happen if you have several consecutive short paragraphs starting with, say, "Item:".

Yes, but it's harder to make that decision after a word. The current code making that decision when the first word is a single char flagged as left punctuation is a quite obvious unrisky decision (until we meet cases where it's unwelcome, like this issue - and try to find another unrisky set of conditions).

> Exactly, which goes to further prove my point

What's your point exactly ? :) (I don't disagree with any of your points, we're just trying to find the best and safest way to handle the edge cases we notice.)

In that Google Book book, is it the Google renderer that does it like this ? Or the publisher that has put fixed-width spaces in between these dots, but not after?
In your first sample, I guess you'd prefer to see all ". . ." sized the same, and see no ". . .". And I guess you would not care much if the space after and initial ". . ." is locked, but stretched around the ones inside the text.
(But I'm fine just removing the period and ellipsis from the left punctuations set - as *i* don't see them often - and call it a day :)

**Comment by Jellby** [comment]
> But a publisher/author/writer can just do that: use the thin-space, hair-space and the like if he doesn't want it stretched, and use the non-specified-width ones where he wants to allow condensing/stretching for justification. (Dunno if there's such a specified-width space the size of the regular space if one want a regular space widthed space to not stretch :)

I don't think there is, at least I don't recall seeing it, But anyway, the stretchability of the spaces is, as far as I understand, not really specified anywhere. For instance, many renderers do not stretch a normal no-break space, and apparently some renderers stretch a thin space (and we can't really say they are non-compliant for that).

> > Exactly, which goes to further prove my point
> 
> What's your point exactly ? :) (I don't disagree with any of your points, we're just trying to find the best and safest way to handle the edge cases we notice.)

In this particular case, my point was that the space after an initial ellipsis or period is not special.

> In that Google Book book, is it the Google renderer that does it like this ? Or the publisher that has put fixed-width spaces in between these dots, but not after?

I think it's a scan of a printed book, at least my printed copy looks the same. Either the spaces between the dots are fixed-width or the whole ellipsis is a single very wide character. There are other instances where one can clearly see that the spaces outside the ellipsis are stretching, but the ones inside are not (or much less).

> In your first sample, I guess you'd prefer to see all ". . ." sized the same, and see no ". . .". And I guess you would not care much if the space after and initial ". . ." is locked, but stretched around the ones inside the text.

I might even prefer something like the book above: have all ". . ." with fixed spaces, I'm not sure. For the specific case case of an initial ellipsis, my preferences are:

1. All spaces stretched equally:
```
.   .   .   Lorem   ipsum
```

2. Fixed spaces between dots:
```
. . .   Lorem   ipsum
```

3. Fixed spaces after dots:

```
. . . Lorem   ipsum
```

4. Fixed space after first dot (current behavior)
```
. .   .   Lorem   ipsum
```

Any of 1-3 would be an improvent and I'd fine with it. The differences between space widths are usually not that large to make it bothersome, except for 4.

**Comment by poire-z** [comment]
Then, may be just drop the thing if the start of 2nd word is also a left punctuation (as then, we're not sure what's best):
```diff
- if ( k > 0 && isLeftPunctuation(m_text[k-1]) ) {
+ if ( k > 0 && isLeftPunctuation(m_text[k-1]) && (k+1>=len || !isLeftPunctuation(m_text[k+1]))  ) {
```

But this felt like a nice idea:

> Perhaps not only the first space, but all spaces in sequence of (left space)* should be locked (e.g. nested quotes)

**Comment by poire-z** [comment]
> Perhaps not only the first space, but all spaces in sequence of (left space)* should be locked (e.g. nested quotes)

Do'able without much risks with:
```diff
--- a/crengine/src/lvtextfm.cpp
+++ b/crengine/src/lvtextfm.cpp
@@ -1914,6 +1914,7 @@ public:
                             // remove, from the measured cumulative width, what we just, and previously, removed
                             widths[k] -= cumulative_width_removed;
                             if ( first_word_len >= 0 ) { // This is the space (or nbsp) after first word
+                                bool keep_checking = false;
                                 if ( first_word_len == 1 ) { // Previous word is a single char
                                     if ( k > 0 && isLeftPunctuation(m_text[k-1]) ) {
                                         // This space follows one of the common opening quotation marks or
@@ -1926,6 +1927,10 @@ public:
                                         // Also prevent that quotation mark or dash from getting
                                         // additional letter spacing for justification
                                         flags[k-1] |= LCHAR_LOCKED_SPACING;
+                                        // If what's coming next is also such a char, continue doing that
+                                        if ( k+1 < len && isLeftPunctuation(m_text[k+1]) ) {
+                                            keep_checking = true;
+                                        }
                                         //
                                         // Note: we do this check here, with the text still in logical
                                         // order, so we get that working with RTL text too (where, in
@@ -1933,7 +1938,10 @@ public:
                                         // first word - untested though).
                                     }
                                 }
-                                first_word_len = -1; // We don't need to deal with this anymore
+                                if ( keep_checking )
+                                    first_word_len = 0;
+                                else
+                                    first_word_len = -1; // We don't need to deal with this anymore
                             }
                         }
                         else {
```

That would give:

![image](https://user-images.githubusercontent.com/24273478/111626595-80ee5000-87ee-11eb-99fc-363b687f841a.png)

![image](https://user-images.githubusercontent.com/24273478/111626726-a4b19600-87ee-11eb-9c88-7bd0cfaa6dcc.png)

Is that OK?

**Comment by Jellby** [comment]
Good enough for me (until I find another failing case, I guess)

**Comment by poire-z** [comment]
> Well, personally, not being such an aesthete regarding typography, I guess I would not care :) If the publisher did the job of using thin spaces, good for me and the more aesthet readers :) If not, I'm bearing these fine.

I guess this has changed over the last 2 years and being spoiled by publishers (and KOReader) doing the right things: got a book from the Gutemberg project, which had english-like typography on french text: no spacing before `?` and `!` or after `«` and before `»` ... which was not bearable :)

Wondered if we could have that fixed by crengine (when lang=fr), but not fun, and may be too many rules to handle.
I also thought it could be nice to have the (my favorite) font handling that, ie. with kerning rules (so it would add some positive kerning between any non-space char and `?` - but I guess getting to understand and hack fonts would be another hell to enter.
So, I just ended up pre-processing the xhtml files of that book with https://github.com/brunobord/typographeur.
(If such bad books were more common, I could think about having hooks into crengine to call back into Lua where we could do these kind of regex fixes more easily.)

Anyway, in that book, I think I met another case related to what was discussed in this issue, and that we don't handle well: leading no-break-spaces used for indentation (for a poem there), that we would expand or shrink these leading spaces if the line ends up too long and split and so justified:

![image](https://github.com/koreader/koreader/assets/24273478/55bf939f-9da3-4e4c-bf65-b16b717fd3ea)

here, each line starts with `<br/>&nbsp;&nbsp;&nbsp;&nbsp;`.

I'll fix that with:
```diff
--- a/crengine/src/lvtextfm.cpp
+++ b/crengine/src/lvtextfm.cpp
@@ -2044,6 +2044,16 @@ public:
                             widths[k] -= cumulative_width_removed;
                             if ( first_word_len >= 0 ) { // This is the space (or nbsp) after first word
                                 bool keep_checking = false;
+                                if ( first_word_len == 0 ) { // No word yet on the left
+                                    // Leading space(s), probably no-break-space, which might be used
+                                    // as indentation (ie. with poetry): don't allow their width to
+                                    // be changed by text justification to keep similar lines aligned.
+                                    // (Note: in RTL paragraphs, this would seem to not be needed, may
+                                    // be because trailing spaces are part of the last word and won't
+                                    // be expanded in alignLine().)
+                                    flags[k] |= LCHAR_LOCKED_SPACING;
+                                    keep_checking = true;
+                                }
                                 if ( first_word_len == 1 ) { // Previous word is a single char
                                     if ( k > 0 && isLeftPunctuation(m_text[k-1]) ) {
                                         // This space follows one of the common opening quotation marks or
```
unless somebody thinks about cases where it might not be a good idea to do that.

**Comment by Frenzie** [comment]
> unless somebody thinks about cases where it might not be a good idea to do that.

An obvious potential issue is if there are a hundred `&nbsp;`, unless you meant something else.

**Comment by poire-z** [comment]
(It's just about stretching/shrinking nbsp when needed for text justification, so whether there are hundreds or a few it shouldn't matter.)

Another note about that french typography and using thin spaces and narrow no-break spaces:

I think they are hardly ever used in publishers' EPUBs, otherwise I would have noticed the following issue earlier (also may be because U+2009 and U+202F may not be there in all fonts, so safer for publishers to use a regular U+00A0 NBSP).

In my current preferred font, with a "units per em" of 2048, the regular and nbsp spaces have a width of 448 (~ 1/4.5 em) - and the thin/narrow spaces have a width of 409 (1/5 em, as per specs for non-French).

But what happens with our `Word Spacing medium`, when crengine needs to shrink spaces for text justification, is that the space might be `x 0.95 x 0.75`, so `448*0.95*0.75 = 319`, and our spaces could be a lot smaller than the fixed-width thin space ! So I can get stuff like:
`Comment ça va    ? Ca va bien   ! Parfait.`
I had to hack this font to make the thin & narrow spaces smaller from 409 to 256 (1/8 em as some references say it may need to be).

https://learn.microsoft.com/en-us/typography/develop/character-design-standards/whitespace
`https://github.com/googlefonts/roboto/issues/24#issuecomment-133564518`

**Comment by Frenzie** [comment]
> https://learn.microsoft.com/en-us/typography/develop/character-design-standards/whitespace

Sidenote, I just saw this https://legible-typography.com/en/
