### ISSUE TITLE
Font embolding

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7385]
Just as information.
Some of the CoolReader forks have a feature of step by step font embolding (in addition or even instead of gamma).

Here are the screenshots (in Russian Утолщение шрифта)
https://forum.vlasovsoft.net/viewtopic.php?f=6&t=2084

The feature has been implemented in
https://github.com/blchinezu/pocketbook-coolreader

**Comment by poire-z** [comment]
For reference, some implementation of the above via https://github.com/plotn/coolreader/commit/a322ad0c7b7ee3743c8b931c780e0cf86b781b27#diff-d10f8b67186064bb01506460412df17e6b5e26d3d484a3d8186ddc3a7df3058e

Not really interested - and it feels hacky, using some legacy CR font emboldening code that we no more use, that we stopped using since we use Harfbuzz, as it messed font metrics and fine glyph positionnning - I'm not sure such hacks can play well with HB (and/or work fine with cursive arabic).
We use a bit of these hacks, but only with fonts that don't come with bold instances:
https://github.com/koreader/crengine/blob/0cb481f39daf7024b39892a7af0477eebcfe6d90/crengine/src/lvfntman.cpp#L1359-L1404
Anyway, too ugly/edgy to play more with that kind of stuff.
Gamma feels a lot safer.

Another option is #4174 (support and use instances of the fonts with the ~9+ classic weights, but requires the user to have a font that comes with all these files :) Not interested either.

**Comment by hius07** [comment]
Thank you for the review.
