### ISSUE TITLE
font-family: sans-serif is ignored

### ISSUE THREAD

**Issue by tastytea** [koreader/koreader#7426]
* KOReader version: **2021.02**
* Device: **Emulator, PB632**

#### Issue

`font-family: sans-serif` is ignored. I deleted `~/.config/koreader` before testing and turned off style tweaks.

##### XHTML file

```xhtml
<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de">
<head>
  <style>
  body { font-family: serif; }
  .sans-serif { font-family: sans-serif; }
  </style>
</head>
<body>
  <p>The quick brown fox jumps over the lazy dog</p>
  <p class="sans-serif">The quick brown fox jumps over the lazy dog</p>
</body>
</html>
```

Test epub: [test.epub.zip](https://github.com/koreader/koreader/files/6171320/test.epub.zip) (rename to .epub)

##### Result in Calibre preview

![screenshot_2021-03-19T13:50:11](https://user-images.githubusercontent.com/3681516/111783449-8749fe00-88ba-11eb-9b98-34fe9a43dfca.png)

##### Result in KOReader

![screenshot_2021-03-19T13:50:04](https://user-images.githubusercontent.com/3681516/111783484-8e710c00-88ba-11eb-86fa-a440b21a1411.png)

**Comment by poire-z** [comment]
Some limitations in Freetype, that can't tell us if a font is Serif or Sans - and KOReader allows selecting a single font as the default font. Previous explanations around https://github.com/koreader/crengine/pull/216#issuecomment-567467571 and https://github.com/koreader/koreader/pull/6738#issuecomment-702807450

**Comment by gbyl** [comment]
Documenting a workaround here.

To get more than one font family to render on a single ePub, we can either embed the font or use one of the KOReader built-in fonts. However, generic `serif`, `sans-serif`, `monospace` parameters by themselves do not work. The font needs to be explicitly referenced in a CSS entry, for example:

```css
font-family: "Noto Sans", sans-serif;
font-family: "Noto Serif", serif;
font-family: "Droid Sans Mono", monospace;
```

**Comment by NiLuJe** [comment]
@poire-z: This was brought up on MobileRead a few days ago, what would your take be on something like this: https://www.mobileread.com/forums/showpost.php?p=4254017&postcount=8?

**Comment by poire-z** [comment]
(Also see https://github.com/koreader/crengine/pull/216)

> In the absence of a full-blown user option in KOReader would it be possible to just assign 'Noto Sans' as a default generic sans-serif font. It should suffice for English and other western European languages but I'm not sure about Cyrillic, Vietnamese etc.

Well, this could be really annoying: if the book has `body { font-family: sans-serif }`, you would get it all in NotoSans.
Also, I don't know how Indic/Chinese/Arabic... languages do it: I think some languages may even be more than us westerners enclined to set `sans-serif` to get easier to read glyphs for the youngsters...

I think about this issue every other trimester :) Last time was when I implemented the preferred monospace font selection.
I think in crengine we could make the serif/sans-serif separation in use by somehow tagging some font as one or the other - and it all come down to the frontend UI and how to make it clear and not annoying for the people who don't care, and not have them to have some fight to win somehow on every other new book opening...

Just now, I'm thinking that may be, like for monospace, one could long-press on a font to select it as the single `1st fallback | preferred monospace | preferred sans-serif | reset` (but go make a widget for that, + the setting(s), having it for this book only | all books... not fun :)
Then, users who don't care or wan't to quickly win the fight could just unset that sans-serif font.

And may be some people/scripts prefer sans-serif as their may font, and would like to be able to select one font as THE serif font :)
Again, the thinking should be more about how to present all that on the UI side, than the technical implementation in crengine I think.

**Comment by NiLuJe** [comment]
Yeah, something like the monospace stuff sounds like the most sensible approach then ;).

(Slightly related: Do *we*, in the frontend, programmatically know if a font is a Sans? Possibly with @ezdiy fontlist cache stuff?)

**Comment by poire-z** [comment]
There is this pessimist bit by @ezdiy :
https://github.com/koreader/koreader-base/blob/7fb47e46054ebf0499131db8f6fc006729795f3e/ffi/freetype.lua#L132-L167

But again, I wouldn't like any classification of my fonts, right or wrong, to prevent me using any of them as the main font (or THE serif font, or THE sans font, if we implement such a choice) no matter what the publisher decides bits should be sans or serif.
Also, "Ignore publisher fonts" should not be the solution to the fight: I don't want to lose real family font names (like using a XITS Math for math bits of text - or those selecting an embedded monospace font by name).
So, it feels it would be better to not do anything that would depend on "programmatical knowing if a font is Sans or not" - which would mean one technical issue less :)

**Comment by NiLuJe** [comment]
Oh, yeah, I was just thinking of a visual cue "this is probably a sans" in the font list like we do for monospace (I... think? :D), nothing more ;).

**Comment by poire-z** [comment]
> I think in crengine we could make the serif/sans-serif separation in use by somehow tagging some font as one or the other 

Some other thought I've been... thinking these last days.
What if we would not touch fonts and crengine internal handling of font_family (as the CSS enum and as the font flags), but we would just have crengine "replace" `serif`, `sans-serif`, `cursive` with a font name when it parses some CSS ?
We could then have (to make things clearer than having to long-press in the single font menu) a subsection Font families> with each [generic family name](https://drafts.csswg.org/css-fonts/#generic-font-families), and for each, our list of fonts duplicated, with 2 other entries: "Ignore" and "Default font".

```
Font settings>
Font families (4) >      (x)
--------
Bitter
Bookerly
...
```
( `(x)` : this number of active families would give a visual hint to the user that there's may be  something here to tweak when he would use the main font menu to choose a font, and be upset to not see it having any effect. )
```
About font families
--------
[x] Sans serif : Noto Sans >
[x] Serif : default font >
[x] Monospace : Droid Sans Mono >
[ ] Cursive : ignore >
[ ] Fantasy : Comic Sans MS >
[ ] Emoji : ignore >
[x] Math : FreeSerif >
[ ] Fangsong : default font >
```

```
Cursive font (no callback, for info)
--------
[ ] Default font
[x] Ignore
--------
[ ] Bitter
[ ] Bookerly
...
```

People would set their preferred font for each family (we would ship with nothing set, except Monospace), and this would be global.
And the checkbox would allow disabling this family for the current book - as the "win this fight quick" solution when families lovers meet a document where it's abused.

I'm not yet sure if we should have a `default font` and `ignore` distinction.
We also don't have TouchMenuItem which do both the checkbox and the submenu :/ (I think I already missed that possibility in the past).
Also, the monospace font is already handled in the main menu - so we'd have to decide where it should go - and kill one or the other.

It's a bit verbose on the menu items, but it looks to me it's the most flexible, for people who care about font families, and for those who don't give a flying glyph.

Thoughts ?

**Comment by NiLuJe** [comment]
> What if we would not touch fonts and crengine internal handling of font_family (as the CSS enum and as the font flags), but we would just have crengine "replace" `serif`, `sans-serif`, `cursive` with a font name when it parses some CSS ?

I *very nearly* asked if something like that wasn't already achievable via a CSS tweak the other day ;).

**Comment by NiLuJe** [comment]
> I'm not yet sure if we should have a `default font` and `ignore` distinction.

How would the two differ in practice? (i.e., would the net effect ever be different?).

**Comment by NiLuJe** [comment]
But, yeah, that sounds perfect ;).

**Comment by poire-z** [comment]
> > I'm not yet sure if we should have a `default font` and `ignore` distinction.
> 
> How would the two differ in practice? (i.e., would the net effect ever be different?).

Ignore would just ignore it, inheriting the font from the parent.
Default font would reset the font to the default font.

With `<span style="font-family: monospace">some code <span style="font-family: serif">some comment</span></span>`:
`Serif > ignore` would have it all monospace
`Serif > default font` would have "some comment" drawn with your default font

The current behaviour (as no tweak exists, and we don't handle these) would be "ignore" - except for this example with "monospace" which is the only family we distinguished from all others where "some comment" would not be drawn in monospace but with the default font.

I guess "default font" is the most expected - and the checkbox unchecked would mean "default font", so this might be simpler and graspable for a user, if we ignore "ignore" :)

**Comment by poire-z** [comment]
The logic would be different from what we have in Firefox:
![image](https://user-images.githubusercontent.com/24273478/190278606-69784d70-32c7-471f-896d-7d5bbe513e35.png)
where we set a font name to families, and then we decide which family is the default font. (and firefox allows doing this and differently for all languages, which we won't :)

**Comment by NiLuJe** [comment]
> I guess "default font" is the most expected - and the checkbox unchecked would mean "default font", so this might be simpler and graspable for a user, if we ignore "ignore" :)

Yeah, unless it's trivial to deal with, simpler is probably better here?

**Comment by poire-z** [comment]
I got to get this:

![image](https://user-images.githubusercontent.com/24273478/192329798-072d5e46-4250-4b77-aa0c-b1988cf65a5e.png)

![image](https://user-images.githubusercontent.com/24273478/192329878-068352a1-3a05-4874-be78-70b8040540c1.png)

![image](https://user-images.githubusercontent.com/24273478/192329966-978b1597-4cbd-4931-88a2-e48629ece4e9.png)

![image](https://user-images.githubusercontent.com/24273478/192330046-b590f55e-1f1d-49f0-883c-4e8281828d33.png)

![image](https://user-images.githubusercontent.com/24273478/192330130-164a0263-8270-433f-8362-83dc4bc34a1d.png)

![image](https://user-images.githubusercontent.com/24273478/192330241-d5a8cd0d-c349-4a72-b08f-3f17d40db3e4.png)
(I added this option to get to have 2 x 5 menu items :) and because often in books, you see `font-family: "Liberation Serif", serif` - and it's often Liberation or Libertinus, and if you happen to have these fonts installed, your serif font would not be used. This option allows you to have these font names ignored when there is a generic family name. It might be convenient for the family people.)

No long-press support in the font lists there: what you select with tap becomes your global font for this family, and will apply to all books. No way to set a specific Sans or Cursive font for a book. The idea is that, if one cares about this families distinction, he sets his preferred ones, and in most books he won't see them. But in some, he will have the surprise to see and enjoy them. If there's too much of them (ie `body { font-family: cursive }` :)) he can go there to uncheck the family and get the main font used (as before).
The only caveat for people who care is probably for Chinese and English readers, who won't be able to set a Sans CJK font on Chinese books, and a Latin Sans font for English. Well, they'll have to find another solution (ie. setting a Sans font as the first fallback).

When this get merged, we will all have this in this state:
![image](https://user-images.githubusercontent.com/24273478/192333734-0b0cab64-6bc8-4f20-8ebe-3fef697f10fa.png)

![image](https://user-images.githubusercontent.com/24273478/192333788-3b32324a-8e9d-4562-87d4-ce1732ded3f4.png)

![image](https://user-images.githubusercontent.com/24273478/192333838-5bed3e1d-4306-41c9-b43f-5a9ad6abe3e1.png)

so this should change nothing by default, until users set some stuff there.

All in all, this feels quite versatile and not bothering (except for adding a new menu item and having only 3 fonts in the 1st panel - i happen to have 4 preferred fonts starting with A/B/C thas were there :) I'll have to find the 4th in the 2nd panel now... but I'll be ok :) Should this `Font family fonts` be inside `Font settings>`, or is it just fine here ?)

The only categorisations of font I can do in crengine is for monospace, math (presence of OpenType math tables), and emoji (presence of the first emojis in Unicode, some smiling faces), so I can restrict the list for these to show only the fonts that can:

![image](https://user-images.githubusercontent.com/24273478/192331498-aca45b92-8c6f-402b-858b-bbd89ea3f2d7.png)

![image](https://user-images.githubusercontent.com/24273478/192331549-20673120-a7a9-4b27-a765-f3202d83f363.png)

![image](https://user-images.githubusercontent.com/24273478/192331685-b6c23086-1287-4fe0-b99e-4922ca74134e.png)

I added some symbols around these fonts in the main font list - but I don't think I'll keep these, it's a bit overcrowded, and is not really useful there:

![image](https://user-images.githubusercontent.com/24273478/192332020-e84633e8-98eb-48ed-b512-45a4ed555858.png)

Except for monospace (the `M`): I don't feel like killing the previous default monospace one can set with long-press on a Monospace font. It's fully redundant with this new menu - but technically, it's used differently in crengine (long-press sets a bias to a font score so it's find first when looking for a monospace font - selecting the family monospace font in this new menu just replaces 'monospace' with the selected font name. We'll see if people manage to find this redundancy and get confused :)

**Comment by hius07** [comment]
> Should this `Font family fonts` be inside `Font settings>`, or is it just fine here ?)

It is fine right here, not inside Font settings.

**Comment by NiLuJe** [comment]
> Should this `Font family fonts` be inside `Font settings>`, or is it just fine here

It feels fine here, yeah ;).

**Comment by NiLuJe** [comment]
That looks pretty neat, thanks!

(Ping @jackie_w in case she wants to comment on this ;)).

**Comment by poire-z** [comment]
![image](https://user-images.githubusercontent.com/24273478/192448173-c5791d82-4527-42d9-bd08-04a96bbeea5d.png)

@weijiuqiao : can you confirm/correct how this "fangsong" menu item should appear in this futur menu ? It's the only generic name specifically related to Chinese:
https://drafts.csswg.org/css-fonts/#generic-font-families
> This font family is used for Fang Song (仿宋) typefaces in Chinese. Fang Song is a relaxed, intermediate form between Song ([serif](https://drafts.csswg.org/css-fonts/#valdef-font-family-serif)) and Kai ([cursive](https://drafts.csswg.org/css-fonts/#valdef-font-family-cursive)). Typically, the horizontal lines are tilted, the endpoint flourishes are smaller, and there is less variation in stroke width, compared to a Song style. Fang Song is often used for official Chinese Government documents.

https://www.w3.org/TR/clreq/#imitation_song
Should we have it written:
Fang Song, Fang song, Fangsong, Fang Song Ti ?
仿宋体 or 仿宋 ?

Should it be translatable ? Probably not to be translated to English, but would it matter for Traditional Chinese ? Or is it mainly a Simplificed Chinese Government stuff ?

**Comment by poire-z** [comment]
> No long-press support in the font lists there: what you select with tap becomes your global font for this family, and will apply to all books. No way to set a specific Sans or Cursive font for a book. 

Well, that's a bit of a random lazy choice and limitation.
We could have (without much additional work):
- tap on font name to have it set for this family for this book only - long-press for global : this is consistent with all our other menus. So, when this is merged, people will tap and get it local. When in the next book(s), family fonts will be unset, and no font family font used - so it may take time for people to notice they should long-press to get it global. Unlike most other features, for font-family, you don't notice the book uses font-family and you would need these unless they are already set and affect the rendering and show up.
- tap on font name to have it global - long-press for local, so we can allow occasional tweaks per book (say if a publisher uses a small main font, and you need another smaller Sans font to match the sizes). This would be rather inconsistent with all our other menus, but may be more practical.
- stay with only Tap to have the setting global (like I described above)

Thoughts?

**Comment by weijiuqiao** [comment]
>Should we have it written:
Fang Song, Fang song, Fangsong, Fang Song Ti ?
仿宋体 or 仿宋 ?

"Fang Song" and "Fang Song Ti" looks better. 
仿宋体 and 仿宋 are both OK. The 体 here means typeface, so it's like Serif vs. Serif typeface. Not much difference.

>Should it be translatable ? Probably not to be translated to English, but would it matter for Traditional Chinese ? Or is it mainly a Simplificed Chinese Government stuff ?

Fang Song predates the current mainland gov, but it does seem to be used less in Taiwan. I googled a bit and found a [showcase](https://www.pinterest.com/pin/711850284827723790/) of a Fang Song typeface made by a Taiwanese designer, uploaded presumably by a Taiwanese person (tw locl character variation). So I'm confident that it wouldn't bother them :)

**Comment by NiLuJe** [comment]
> Thoughts?

I could definitely see the interest of having a local/global distinction, but I see your dilemma about the practicality of which should do what....

I'd probably still veer towards not breaking UX codes and go with tap -> local and long -> global, though ;).

**Comment by jackiew1** [comment]
> That looks pretty neat, thanks!
> 
> (Ping @jackiew1 in case she wants to comment on this ;)).

I'm reading with interest, but in all honesty, I haven't used KOReader enough to comment on the GUI ease of use proposals. 

Anything which means I no longer need to rewrite font-family CSS on-the-fly during a hacked send-to-device process would be considered a step forward by me. The work currently involved in getting font-families to work OK in KOReader is already minimal compared to what I have to do to get kepubs working OK in Kobo Nickel.

I'll be happy to test the Kobo and Android versions if/when they become available.

**Comment by poire-z** [comment]
> I'd probably still veer towards not breaking UX codes and go with tap -> local and long -> global, though ;).

Made a PR with that at #9583 - please followup discussion there.
