### ISSUE TITLE
Display "On hold" books

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#7435]
Since there is an option "On hold" in "Book Status", I think it would be useful if there was an overall display of "On hold" books such as "Favorites" or "History", so that we can have the books we want to read in the near future collected.

Thank you.

**Comment by mergen3107** [comment]
Not a solution per se, but I noticed interesting workaround.
Thanks to @Hzj-jie, we now have [Find History](https://github.com/koreader/contrib/tree/main/findhistory.koplugin) plugin.

What I did:
1) A long time agon, in File Manager went through list of my books and marked those that I have already finished (outside KOReader). 
2) Installed this plugin and used it. My History got populated with ALL the books I marked finished as well, because that action actually created an sdr directory with the status.
3) Now, if you change History View to Detailed with metadata and covers (that's in FM - Top Menu - First Tab - Display Mode - History Display mode) - you will see which books are On Hold or Finished as well.

**Comment by ichnilatis-gr** [comment]
>     2\. Installed this plugin and used it. My History got populated with ALL the books I marked finished as well, because that action actually created an sdr directory with the status.

@mergen3107 Thank you, but do you have any idea of [this](https://www.mobileread.com/forums/showthread.php?t=341826) "problem" I have?

>     3\. Now, if you change History View to Detailed with metadata and covers (that's in FM - Top Menu - First Tab - Display Mode - History Display mode) - you will see which books are On Hold or Finished as well.

Actually, I didn't see the indication "On hold" for books I had marked so.

**Comment by mergen3107** [comment]
@ichnilatis-gr 
I don’t think the plugin does anything to Pocketbook history specifically.

As far as I understood, it just searches for .sdr directories and adds those titles/filenames to KOReader history.lua file (IIRC). Those are created even for books which weren’t open, but were marked somehow (Finished, On Hold, Reading) — this “mark” is written in the .sdr directory. 

Then, if respective book exists it will also show up with the cover in the History view. By the way, do you have the option “Remove deleted books from history” option on? Maybe it is conflicting with the plugin? It is in the FM, top menu, somewhere in the first tab. Can’t see KOReader right now

**Comment by mergen3107** [comment]
> Actually, I didn't see the indication "On hold" for books I had marked so.

This is only seen in detailed view I think, not in cover mode
