### ISSUE TITLE
Cannot connect to wifi after disconnection 

### ISSUE THREAD

**Issue by zelomel** [koreader/koreader#7468]
* KOReader version: 2021.03-6
* Device: reMarkable 1

#### Issue

It is impossible to reconnect to wifi after a disconnection.
Wifi is ok if you switch from xochitl  with wifi activated to koreader but if you disconnect it is impossible to reconnect.
If you switch from xochitl  with wifi desactivated to koreader it is impossible to connect.

The connection process seems to be ok. The last message is "Associated with imac adress". The message freezes during 15 secondes and then wifi is disconnected. I see my remarkable connected into my router and then disconnected

#### Steps to reproduce

Disconnect and then try to connect

#

**Comment by pazos** [comment]
pinging @snelg, who implemented wifi on ReMarkable, IIRC

**Comment by snelg** [comment]
I have a reMarkable 2, not 1, so I might not be able to fully diagnose. But let's try.
How are you switching between xochitl and koreader? Are you using an app switcher like oxide, or are you using the middle-button listener?

**Comment by snelg** [comment]
Hmm, having issues on my rm2 as well. Downgraded to a clean install of KOReader 2021.02, and that didn't fix the problem.
I'm not sure if ReMarkable (the company) syncs software updates for both rm1 and rm2, but I upgraded xochitl to the new version 26 a few days ago. https://support.remarkable.com/hc/en-us/articles/360018428837-Software-release-2-6
Definitely possible that upgrade broke something. I'll keep testing.

**Comment by snelg** [comment]
I think I've figured the problem, but not sure what the cleanest solution is:

While it's attempting the network connection, `wpa_supplicant.lua` waits until it sees an "Auth Successful" event from WpaClient
https://github.com/koreader/koreader/blob/de543b348468820aef5015285e35cd740ea2a4e1/frontend/ui/network/wpa_supplicant.lua#L104

To decide whether an event is "Auth Successful", it looks at the text of the event message and does a simple pattern match
https://github.com/koreader/lj-wpaclient/blob/e4f0315b34ad434ee6e64db88a51e253e298e683/wpa_ctrl.lua#L22-L24

That pattern, `%w+: Key negotiation completed with (.+)` does not appear when I manually run `wpa_cli` and connect to my network. The string "Key negotiation" doesn't appear at all.

Here's the entire output when I do the final `enable network 0` command manually:
```
<3>CTRL-EVENT-SCAN-STARTED
<3>CTRL-EVENT-SCAN-RESULTS
<3>WPS-AP-AVAILABLE
<3>Trying to associate with SSID 'needabiggerboat'
<3>Associated with cc:40:d0:6c:f9:58
<3>CTRL-EVENT-CONNECTED - Connection to cc:40:d0:6c:f9:58 completed [id=0 id_str=]
<3>CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
```

I can't downgrade my reMarkable to the previous system version to 100% verify, but I'm guessing that "Key negotiation completed" message *used* to be in that output. But either way, it's not there now.

It seems like searching for `CTRL-EVENT-CONNECTED` in addition to (or instead of?) searching for "Key negotiation completed" should work, but I don't know if it would be best to
 1. patch `lj-wpaclient/wpa_ctrl.lua`
 2. patch `koreader/frontend/ui/network/wpa_supplicant.lua`
 3. monkey-patch inside `koreader/frontend/device/remarkable/device.lua` just in case fiddling with one of those other files affects other device that use `wpa_supplicant`

**Comment by snelg** [comment]
Welllll, it's still a pattern match, but at least it's a slightly less-weird pattern :)
https://github.com/koreader/lj-wpaclient/pull/7

**Comment by gbyl** [comment]
@snelg I can confirm the fix works for RM1 as well. Thank you!

**Comment by zelomel** [comment]
How do you install this fix ?

**Comment by gbyl** [comment]
@zelomel Navigate to `koreader/common/lj-wpaclient/wpa_ctrl.lua` and make the adjustments from the PR https://github.com/koreader/lj-wpaclient/pull/7/files

**Comment by zelomel** [comment]
@gbyl Thanks !
Everything 's fine

**Comment by gbyl** [comment]
fixed by https://github.com/koreader/lj-wpaclient/pull/7 and https://github.com/koreader/koreader-base/pull/1345
