### ISSUE TITLE
Changing the font size breaks the order of bookmarks when exporting 

### ISSUE THREAD

**Issue by DubininDmitry** [koreader/koreader#7469]
* KOReader version: 2021.03
* Device: Android

#### Issue
1. Bookmark a book
2. Change the font size in the book (for example, make it noticeably smaller)
3. Make another one after the last bookmark
4. Export bookmarks to file
Apparently, due to the change in the font, the program changes the number of pages in the book, which in turn leads to the fact that the bookmarks attached to the pages simply lose order (but it is important to note that they open correctly).
That is, when you export bookmarks in such books, the order of bookmarks breaks

The screenshot shows an example of exporting a similar document, where you can see that the chapter with a higher number has a smaller page when exporting. Also added a screen of book settings
![image](https://user-images.githubusercontent.com/8066458/113033807-f3f9ae00-9180-11eb-8eae-148e90e29199.png)
![image](https://user-images.githubusercontent.com/8066458/113034343-826e2f80-9181-11eb-858c-646b8cc26bcf.png)

**Comment by NiLuJe** [comment]
Thoroughly unfamiliar with the code, but I'm assuming highlights are indexed by page number, possibly to make their in-book display faster (e.g., only lookup *this* page instead of the whole array).

Which means I'd rather fix the export to sort by timestamp instead (and maybe store an actual epoch instead of a formatted date to make that easier).

(Not volunteering, I barely ever use the feature).

**Comment by NiLuJe** [comment]
Possibly to be added to the pile in #5794

**Comment by poire-z** [comment]
Probably fixed by #8616.
