### ISSUE TITLE
Bq Cervantes 4 : koreader doesn't start after updating to the latest dev. version 

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#7472]
Hi,
Yesterday evening, I updated my bq Cervantes 4 to the latest developper version of Koreader (I cannot remember the version number but I think it ended with a 6).
The update operation went fine but when Koreader restarted it entered into an infinite loop. The little dots scroll endlessly at the bottom of the screen but nothing happens. 
I restarted my device but it didn't solve the problem.
I also tried to connect to the device by Telnet in order to downgrade koreader manually. I followed the instructions found here : http://web.archive.org/web/20200720044821/https://blog.bq.com/es/bq-ereaders-developers-program/. I used Putty, chose Telnet, entered 192.168.4.1 as IP address and 23 as Port, but the connection was refused. I'm not sure that I proceeded correctly (I don't understand for example "Set your computer usb0 interface with another ip address in that range and you would be able to telnet it through USB interface".
So right now I'm stucked and I don't know how to solve the problem. 
Did I miss something ? Or can I force the device to launch the bq software instead of koreader ? Or is there another way than Telnet to access to the device ?
Any help highly appreciated :-)
Bruno

**Comment by NiLuJe** [comment]
We could really use a look at the crash.log ;).

**Comment by Brnoch** [comment]
Indeed :-)
But I don't know how to access to the crash.log.
When connected to the usb, I just have access to the "public" folders of the device. 
I hope that there is a solution to access the other ones and that the device is not definitely bricked...

**Comment by pazos** [comment]
@Brnoch: the device is almost indestructible software wise. And the safemode tool you have installed makes the process even easier.

Basically the device (when you press the home button **while** the dots are shown in the screen at boot and you see the funny [usbnet face](https://github.com/pazos/cervantes-safemode/blob/master/images/usbnet.png)) gets an ip 192.168.4.1/24 and you need to setup your computer with any other ip on the same subnet.

The steps change with your OS but should be pretty straightfoward. The USBnet should be recognized on Linux/Mac/Windows and you need to asign an ip like 192.168.4.2 and a subnet of 255.255.255.0. Then you can telnet 192.168.4.1 without problems.

I think you configured your host computer with the 192.168.4.1/24 ip and when you're trying to telnet that ip your're telneting your localhost, so the connection is refused.

There're plenty of ways to get yourself a working installation again once you have telnet running. The easiest is to use an sdcard and put there a zip with a KOReader release that works. Then repeat the [1st time install instructions](https://www.mobileread.com/forums/showpost.php?p=3760905&postcount=2)

Once you get that recovered please wait until https://github.com/koreader/koreader/issues/7485 is fixed to update again.

I also have the stock/hackers images available, in case you need them. But for this specific case these shouldn't be needed.

**Comment by Brnoch** [comment]
@pazos Thanks a lot Martin for these accurate and comforting explanations.
When I press the home button, I get the icon that appears when the USB mass storage is activated, like this:
![image](https://user-images.githubusercontent.com/8734788/113430469-8779eb80-93da-11eb-90bb-e5ca2b7b5acc.png)
I searched a lot over the internet but I didn't see how to check if the USBnet is correctly recognized on Windows 10. Should it appear on the avaialble networks list?

**Comment by pazos** [comment]
I think both of your @tjaderxyz and @Brnoch are using old versions of the safemode tool and [koreader standalone script](https://github.com/koreader/koreader/blob/master/platform/cervantes/koreader-standalone.sh)

The old behaviour was:  Between KOReader executions run `safemode` so the dots are displayed and the user can enter USBMS.

It was deprecated when I implemented the USB storage widget inside KOReader.

It is ok to have the old version as the basics are the same, but since you both need to recover a working installation using telnet I would suggest to move to the new version of these tools.

Anyways, in your setup, since KOReader crashes again and again you'll see the dots (again and again too :p) and pressing the home button will move you to USBMS storage mode. That's not the mode we need here. You'll need to:

1. (if you're in USBMS mode) press the home button to get out of it.
2. long press the power button until you see no more feedback on the screen
3. wait a few seconds (2-4s)
4. press the home button.
5. You'll see the splash screen (stock cervantes saying device is booting) and, when you see the dots, press the home button to switch to USBnet mode. Then it is a matter of setup the computer in the same subnet of the device (explained above) and extract a working version of KO.

Updating the `safemode`tool (and the koreader-standalone script) is handy but not mandatory. You'll get a new menu option as explained [here](https://www.mobileread.com/forums/showpost.php?p=3811318&postcount=6)

**Comment by Brnoch** [comment]
I succeeded in switching to the USBnet mode. And when the correct icon appears on the device, it appears as a COM4 in the serial port peripherals' list in the Device Manager of Windows 10.
I don't know then how to setup the computer in the same subnet of the device. 
I've googled extensively about this but the information is poor and rare about it :-(
I pictured that the device in USBnet mode would appear in the networks'list and that I could connect my computer to it and then manually set its IP as indicated... but it's not the case.

**Comment by pazos** [comment]
@Brnoch: windows is very bad dealing with drivers. But you are close to get it working. Please follow this guide https://evwiki.ensto.technology/display/CHWI/Install+RNDIS+Driver+for+Windows+to+be+able+to+connect+to+charge+controller

**Comment by NiLuJe** [comment]
Assuming USBNet is setup as an RNDIS gadget (as opposed to a CEC one), Windows 8.1+ won't need any driver, you should see a network interface in Windows's network interface thingy.

**Comment by tjaderxyz** [comment]
It showed up for me as a serial port instead of as a network interface for me as well in Windows 10. I went the easiest route for me and did it in a linux machine, where the network interface appeared right away.

I manually installed 2021.03 and everything seems to be working now.

Can we take it for granted that the fix will be included in 2021.04 or should we double check before updating to it when it is released?

**Comment by NiLuJe** [comment]
If you're in a position to easily handle breakage, I wouldn't mind you double-checking on today's nightly (which I'm fairly confident should be fixed for real this time ;)).

**Comment by NiLuJe** [comment]
As for the USBNet thing, that's... strange. Admittedly, it's been a while since I tried this on Windows, but I don't recall any hiccups on very similar boards :/.

**Comment by tjaderxyz** [comment]
Sure, now that I know the path to fix it I can test it. Please ping me here
or in the gitter room when it's out.

NiLuJe ***@***.***> schrieb am Sa., 3. Apr. 2021, 13:55:

**Comment by NiLuJe** [comment]
As I said, it's in today's nightly ;).

**Comment by poire-z** [comment]
And in KOReader's world, the night comes before the day :) So today's nightly has been build early this morning, available at http://build.koreader.rocks/download/nightly/

**Comment by Brnoch** [comment]
I finally managed to reinstall koreader on my cervantes. I struggled with Windows and didn't find the proper driver : they were rejected or didn't apply to the rndis gadget of the Cervantes. So this weekend I built a virtual Ubuntu machine and everything went fluessly (as far as it can be fluent for someone as ignorant as I am concerning Linux :-)
@pazos Thanks a lot for the help !

**Comment by Brnoch** [comment]
By the way, the developper version I installed yesterday afternoon runs as usual on the cervantes.

**Comment by pazos** [comment]
@Brnoch: you're welcome. Happy to help.

For future reference: https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware/rndis-usb-device-showing-as-com-serial-port-but/09fcc7db-6133-448d-9540-376dabcf7e38

Maybe you can try to run windows update while the device is present. It should work just fine. As much as I read that seem to be a relatively old problem that just affects some Win10 versions.

**Comment by Brnoch** [comment]
@Martín Windows is up to date as far as I know, and seemed to be sure that
the USB serial port driver was the best for the device... Don'k know why!

Le mar. 6 avr. 2021 à 13:38, Martín Fernández ***@***.***> a
écrit :
