### ISSUE TITLE
FR: Allow more than one instance of KOReader on Pocketbook

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#7517]
I am aware of the changes regarding multiple instances of KOReader [here](https://github.com/koreader/koreader/issues/6321) and [here](https://github.com/koreader/koreader/issues/6808). I would like to have some of this functionality back.

I often read books in their original and compare them with the translation. For this, I would like to be able to switch between two instances of KOReader showing different books. So if I tap on a book to open from the homescreen or the library, KOReader should recognize if the book is already open or not. If it is, it should use that instance. If not, it should open a second instance.

Pocketbooks have a handy task manager which can be used to switch between different applications or in that case different instances of one application. Currently, I use [CoolReader](https://github.com/blchinezu/pocketbook-coolreader/releases) or the built-in Pocketbook reading software together with KOReader to switch between different books. However, CoolReader is not developed anymore and happens to freeze sometimes so I have to restart the device. The Pocketbook reader is awfully sluggish.

If possible, this could be integrated as an option in one of the menus to activate if needed, something like "Allow multiple instances".

**Comment by NiLuJe** [comment]
Unlikely to ever happen without an interested party.

**Comment by Frenzie** [comment]
I assume it should be pretty simple to simply have two separate apps on PB? (Which isn't quite the same thing as what's being asked, but…)

**Comment by LucyOne** [comment]
> I assume it should be pretty simple to simply have two separate apps on PB? (Which isn't quite the same thing as what's being asked, but…)

You mean two installations of KOReader? How would that work?

**Comment by Frenzie** [comment]
It's just a shortcut and a plain folder I believe? In that case you can duplicate both the folder and the shortcut while adjusting the shortcut appropriately.

**Comment by MilaPi** [comment]
I'm sticking to an old 2019 version of Koreader purely for being able to have two instances of it running. 
I like to have my main book open at all times, and be able to read random short stuff in the meantime, newspapers, articles etc without having to reopen the main book constantly.

**Comment by MilaPi** [comment]
I'm sticking to an old 2019 version of Koreader purely for being able to have two instances of it running on my Pocketbook TL3.
I like to have my main book open at all times, and be able to read random short stuff in the meantime, newspapers, articles etc without having to reopen the main book constantly.
In newer versions, once new book is opened, the previous one is replaced with it instead of opening a new instance, like it was before.

**Comment by NiLuJe** [comment]
Sidebar: There's an "Open previous document" shortlink for that very workflow.

**Comment by Frenzie** [comment]
Yes, I actually use the default multiswipe (left, right, left) for the purpose of switching documents like that sometimes.

**Comment by Frenzie** [comment]
Haha, glad it helps. On Kobo there's no multitasking like that, so it's faster that way for sure.

**Comment by rjd22** [comment]
I'm closing this one. I've looked at it and it's certainly possible but since there are memory constraints not advisable to do so.

There are some manual way's to boot multiple instances like installing 2 koreaders on the devices.

But I feel like supporting this has little gain for a lot to pain like OOM errors and performance hits.
