### ISSUE TITLE
FR: Use app-specific data directory for internal files (required in Android 11)

### ISSUE THREAD

**Issue by Victor239** [koreader/koreader#7560]
**Does your feature request involve difficulty completing a task? Please describe.**
KOReader creates a new directory in shared storage which contains it's files. This is messy when there already exists an [app-specific data directory](https://developer.android.com/training/data-storage/app-specific) for it. Shared storage is for files the user should have direct access to e.g. plugins or the ebooks themselves. 

Additionally [this will be required](https://developer.android.com/about/versions/11/privacy/storage) anyway in Android 11 so it makes sense to do so now. 

**Describe the solution you'd like**
Use app-specific data directory for all KOReader internal files. Let the user configure a directory on shared storage where they keep plugins, or allow them to add them into the internal file storage via a file picker. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pazos** [comment]
> KOReader creates a new directory in shared storage which contains it's files.

That's not true. Most part of the assets are extracted into `filesDir`. 

>  This is messy when there already exists an app-specific data directory for it

Which is used for KOReader internal files. That path is not reachable on non-rooted devices. Their contents are wiped after an uninstall.

> Shared storage is for files the user should have direct access to e.g. plugins or the ebooks themselves.

We store persistent data there. That's the whole point. That makes possible for the user to customize stuff: from styletweaks, to plugins, dictionaries, trained tess data, fonts, scripts and even patches that change the runtime behaviour of the program.

> Additionally this will be required anyway in Android 11 so it makes sense to do so now.

Nah, we workaround it. The program still works fine bulding against latest API level. See https://github.com/koreader/android-luajit-launcher/pull/253. That could be an issue if we were at the Play Store, where we would need an approval from google. But that's not the case.

> Use app-specific data directory for all KOReader internal files. 

Done.

> Let the user configure a directory on shared storage where they keep plugins

Makes little sense to me to make the persistent path configurable. It is hardcoded in all platforms:

Linux: `$HOME/.config/koreader`
Mac: `$HOME/Library/Application Support`
Android: `/sdcard/koreader`

It is also easier to keep them as they're. Makes our help attempts more helpful :)


> or allow them to add them into the internal file storage via a file picker.

That's impossible. There's no way a file picker can navigate (read ^ write) a in-app internal data storage.

**Comment by Victor239** [comment]
> We store persistent data there. That's the whole point. That makes possible for the user to customize stuff: from styletweaks, to plugins, dictionaries, trained tess data, fonts, scripts and even patches that change the runtime behaviour of the program.

Ah I see. I saw a lot of random files like cache directories which I found odd as there's a dedicated cache directory for each app and random files like `statistics.sqlite3` which didn't seem like they're meant for end users. Understandable if you want this all to be persistent data editable by the user. 

Would it be possible to make a setting to move the folder from `/sdcard/koreader` to wherever the user likes? It's annoying when every new app decides they need a top-level directory for themselves, and is part of the reason why Scoped Storage was introduced in the first place to reduce this file clutter. On desktop platforms you can just use symlinks, but that's not possible on Android.

**Comment by pazos** [comment]
> Would it be possible to make a setting to move the folder from /sdcard/koreader to wherever the user likes?

Nope, that would require a custom build. (signed with your own keys). That's doable but you'll need to keep it updated yourself, as you won't be able to install APK updates signed by different keys.

If you want to try you'll need to edit https://github.com/koreader/koreader/blob/master/datastorage.lua#L14

**Comment by Victor239** [comment]
I don't mean for myself, as a feature request to make it configurable.

**Comment by pazos** [comment]
> I don't mean for myself, as a feature request to make it configurable.

Nope, is too much work for an anti-feature that could make debugging harder and breaks some wiki entries. https://github.com/koreader/koreader/search?q=%2Fsdcard&type=wikis

The `dataDir` path is ok hardcoded. It is meant for these kind of environments where the internal KOReader files are not writable/accesible from the user PoV. 

The program uses the `datastorage` module very early in the launch process and relies on writable storage ready to be used. The lack of writable storage would make the program crash.

The solution: make `datastorage` configurable on runtime is a PITA and would require hellish workarounds on platforms, like Android, were the filesystem API is not always granted. For the rest of the platforms it should be okay-ish but adds overhead on the first launch because the user needs to select the path before doing something with the program.

Also: users are users. They want to tweak the program but they don't always remind what they tweaked. So having a sane "path" hardcoded on each supported platform that **requires** it is the way to go.

**Comment by rileyinman** [comment]
Would there be any chance to reconsider this? As far as I can tell, enabling scoped storage for koreader is the main thing holding it back from being on the Play Store (#2040). The initial concern with publishing was that the application wasn't polished enough, but it certainly seems to be now (and the number of Android-specific issues are basically none). Android allows setting the directory at first launch using the SAF (Storage Access Framework), there's a pretty good example available [here](https://androidexplained.github.io/android/android11/scoped-storage/2020/09/29/file-saving-android-11.html). Other applications that use this setting have access to the name of the directory chosen by the user, which means the relevant wiki entries could be updated to tell the user where in settings the config directory is listed. That said, I'm not an active Android developer so I apologize if I'm missing something. I just would very much like to see this on the Play Store as it blows many other ebook readers out of the water.

**Comment by pazos** [comment]
> As far as I can tell, enabling scoped storage for koreader is the main thing holding it back from being on the Play Store

Not at all. The main thing holding a possible Play Store release is the lack of 64 bit version of the program (for both arm and x86, mandatory since 2019).

> The initial concern with publishing was that the application wasn't polished enough, but it certainly seems to be now.

We're on F-Droid. A much better store with much better policies. Play Store isn't important for most users here, AFAICT. Certainly  being there has some advantages (for me android vitals is nº1)

> Android allows setting the directory at first launch using the SAF (Storage Access Framework)

The thing with SAF is: it doesn't give access to the `File` API. The API available in every single operative system from DOS/Unix days. The API KOReader uses in all the platforms it supports.

> Would there be any chance to reconsider this?

Not really. We can't work without dealing with `File`'s. But that's not a show stopper for GPlay. In my own interpretation we're ok having full access to storage as we're both a `File management app` and a `Document management app`. Please check it out in https://support.google.com/googleplay/android-developer/answer/10467955?hl=en.

If that's not the case and Google rejects a future request then still **SAF is not an option** and the only way to circumvent this is being sandboxed in `filesDir`, where the `File` API will work forever. IMHO a sandboxed version of KO doesn't make much sense, so I would stay away from Gplay if that was the case.

**Comment by pazos** [comment]
BTW, SAF is supported since a long time ago. You can check it from the FM + button -> import here. It will open the system file picker where you can select one or more supported files. Then files are copied to current directory and you can deal with them.

To figure out how a sandboxed version of KOReader would look like you'll need to:

1. Imagine that your home dir is in /data/data/org.koreader.launcher/files/documents.
2. Imagine that you cannot leave your home dir.
3. Imagine that the only way to open a document involves copying it to the home dir.
4. Imagine that deleting the app will delete all the documents and all the settings of the program.

**Comment by rileyinman** [comment]
Okay, that all makes a lot of sense. As expected, you certainly had valid reasons and I thank you for helping me understand them 😄 For now I am also happy with the F-droid release, it coming to the Play Store would mostly benefit my ability to recommend it to less tech savvy relatives. I hope that you're able to procure the exception you need, and thanks again for all the hard work put into this application!
