### ISSUE TITLE
FR: get mathml enabled wikipedia articles

### ISSUE THREAD

**Issue by fradav** [koreader/koreader#7660]
**Does your feature request involve difficulty completing a task? Please describe.**
When getting wikipedia "full" article with maths formulae, all math snippets are converted to images. This is often a long process, and the final rendering is not very "clean" (various images alignement issues), they don't zomm porperly etc.

**Describe the solution you'd like**
Now that CRE could process mathml, there should be an option to get the entry with mathml, not server-rendered images.

**Comment by Frenzie** [comment]
That's pretty much what I suspected because I know for a fact that every math formula I've ever seen on Wikipedia is an image, not MathML but until you actually dive in there to make sure you're just armchair philosophizing. It could be that in the background most of them are not only defined as MathML but easily extracted. Oh well, too bad. :-)

**Comment by fradav** [comment]
Ok, I trust you on this, I close the ticket.
