### ISSUE TITLE
FR: Better position of progress indicator

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#7666]
**Does your feature request involve difficulty completing a task? Please describe.**
The progress indicator on the top (when a long renering occurs) can't almost not be seen, when you have the **top status** bar enabled in crengine

Open a large epub on a slow devise, watch at the top
![grafik](https://user-images.githubusercontent.com/36999612/117981493-5a9fe900-b335-11eb-8383-25ee1f326c5e.png)

**Describe the solution you'd like**
Move the progress indicator on cre-documents with enabled top status bar to an other position:
Maybe below the status bar in the middle of the screen.
https://github.com/koreader/koreader/blob/de6f2e84a38c071aee0e24e3836f2c47950cf20d/frontend/apps/reader/modules/readerrolling.lua#L1140-L1141

**Comment by poire-z** [comment]
Had a try, it's indeed drawn over the title/author, but it can be seen. May be it won't attract your eye as when no status bar when it's drawn over some blank margin.
You can try adding the height of the top status bar to `y` if enabled - with may be something for when initial loading and when no page yet displayed (as there is then no top status bar displayed, so having it separated from the top might look odd).

But surely not in the middle, I feels it should be anchored to some corner.

Btw, about this `y = Size.margin.small` shift, that I somehow requested in #5581 rather than having a thicker bar height: I often find this gap ugly, so I guess I finally wouldn't mind putting it on the height, having a thicker bar occupying this gap... Dunno how others feel.

**Comment by NiLuJe** [comment]
> Had a try, it's indeed drawn over the title/author, but it can be seen. May be it won't attract your eye as when no status bar when it's drawn over some blank margin.
> You can try adding the height of the top status bar to `y` if enabled - with may be something for when initial loading and when no page yet displayed (as there is then no top status bar displayed, so having it separated from the top might look odd).
> 
> But surely not in the middle, I feels it should be anchored to some corner.
> 
> Btw, about this `y = Size.margin.small` shift, that I somehow requested in #5581 rather than having a thicker bar height: I often find this gap ugly, so I guess I finally wouldn't mind putting it on the height, having a thicker bar occupying this gap... Dunno how others feel.

I probably wouldn't mind it being thicker, but I *would* also mind the gap if it were anchored to a potentially non-existing element (i.e., CRe's header) ;).
