### ISSUE TITLE
KOReader crashes when loading The Bible (am I not holy enough? xD)

### ISSUE THREAD

**Issue by MoreFoxBeans** [koreader/koreader#7703]
* KOReader version: v2021.04
* Device: Kobo Aura Edition 2

#### Issue
Crashing when loading a book (specifically The Bible, around 5000 pages)
At first the crash said something about JPEG ICC profiles but now it says something different.

#### Steps to reproduce
Get the free version of The Bible from Overdrive.
Run in through Obok De-DRM to get an EPUB.
Attempt to open it in KOReader.

##### `crash.log` (if applicable)
[Pastebin](https://pastebin.com/eUhC87FJ)

**Comment by NiLuJe** [comment]
It throws a SIGILL or a SIGBUS, which means it's probably tripping a nasty bug in CRe.

We'd know more with a backtrace (I imagine it'd be reproducible on the emu). In the meantime, since I happen to currently run a debug build on the H2O, if you can get me the file (PM on gitter or mobileread?), I can probably reproduce and get a backtrace to  @poire-z ;).

**Comment by MoreFoxBeans** [comment]
Here ya go:
https://github.com/MoreFoxBeans/Files/raw/main/ESV(r)%20Bible%20-%20Crossway.epub

**Comment by NiLuJe** [comment]
Might be an OOM kill in disguise, given the hilarious RAM consumption. Would have to check on the emu.

(I do get a real clear OOM on my end, though. Admittedly, I'm short 100MB because of a live gdb).

**Comment by poire-z** [comment]
It loads for me on the emulator, 7000 pages, 666 MB of RAM used (isn't that a sign ?! :)
![image](https://user-images.githubusercontent.com/24273478/118604269-446eae80-b7b5-11eb-8c67-66af87f78d5e.png)

Most Bibles will need a lot of RAM, because of cross refs links, lots of links and anchors, making a huge amount of little text nodes. (The CSS stylesheet is not that bad in this one.)
Can't make it crash when tuning settings.

**Comment by MoreFoxBeans** [comment]
It loads fine with the built-in reading software, so I guess the built-in one is only loading a little at a time whereas KOReader is loading it all at once?

**Comment by poire-z** [comment]
Yes. Not much we can do about that.
I must have written about it in some previous issues, but can't find any text.
So, here's the explanation from @NiLuJe : 
https://www.mobileread.com/forums/showthread.php?p=4001973#post4001973
(that I could find easily, I remembered "roll of papyrus" :)

**Comment by MoreFoxBeans** [comment]
That makes sense. So I guess I should split it into smaller chunks, maybe into each of the books or something.

**Comment by poire-z** [comment]
For reference, on my emulator:
This file:
```
loading took 40.625 seconds
rendering took 23.835 seconds

Elements: 1443547, 79200 KB
Text nodes: 793033, 23872 KB
Styles: 160, 5648 KB
Font instances: 27
Rects: 90240 KB
Cached rendered blocks: 1
Total nodes: 2236319, 34942 KB
Mutable elements: 496, 46 KB

Memory usage: 666 MB
Cache file size: 45 989 888
```

Another Bible I usually use for timing:
```
loading took 17.522 seconds
rendering took 5.363 seconds

Elements: 310519, 15488 KB
Text nodes: 357583, 14976 KB
Styles: 85, 1216 KB
Font instances: 17
Rects: 19456 KB
Cached rendered blocks: 1
Total nodes: 668102, 10439 KB
Mutable elements: 4873, 456 KB

Memory usage: 250 MB
Cache file size: 14 380 032
```

So, many wrapping HTML elements, ~4 times more than another Bible.

**Comment by NiLuJe** [comment]
Yeah, FWIW, I managed to get to something like > 90% rendering on the H2O (loading took 265s, wheee!) if I basically killed all the things, and then it started spinning like crazy without ever tripping an OOM kill until I forced a hard reboot ;).
