### ISSUE TITLE
Touchscreen not doing anything

### ISSUE THREAD

**Issue by thebiblelover7** [koreader/koreader#7749]
* KOReader version: 2021.04
* Device: Samsung Galaxy Book Flex Alpha
* OS: Arch Linux (Manjaro)

#### Issue
The touchscreen doesn't work with KOReader. I can use the touchscreen on any other application, but when I try to click on something with my finger, it acts as if nothing happened, the mouse cursor just moves to the place that I clicked. Clicking with a mouse or touchpad still works.

#### Steps to reproduce
Click on the screen with your finger.

**Comment by Frenzie** [comment]
The cursor? Could you expand on what exactly you're doing in which environment?

**Comment by adrielsand** [comment]
> The cursor? Could you expand on what exactly you're doing in which environment?

Sorry, for not being very specific. Just edited my Issue.

**Comment by adrielsand** [comment]
@Frenzie Anything else I should add?

**Comment by Frenzie** [comment]
Okay, so the name of the device is deceptive and it's not Android. That explains a lot, but it definitely raises many more questions, such as which DE, X11 vs Wayland, etc. Also are you running the AppImage, Docker, the emulator compiled directly on your system, …

While it presumably won't make a difference, please grab or build either the latest stable or [the latest nightly](http://build.koreader.rocks/download/nightly/v2021.05-42-gb938f31_2021-05-23/) so we're not talking about outdated things.

But tl;dr, I've never had a touch screen on desktop, but afaik this here is functional on Ubuntu Touch. I don't know what might be messing up or how.

https://github.com/koreader/koreader-base/blob/96c002d5260b09148def07913b5e4363d9a58c23/ffi/SDL2_0.lua#L272-L276

https://github.com/koreader/koreader-base/blob/96c002d5260b09148def07913b5e4363d9a58c23/ffi/SDL2_0.lua#L313-L327

The quickest way to look into it would be if you could do some quick experiments yourself (with `--appimage-extract`), since I assume Arch implies a certain level of technical know-how. ;-)
