### ISSUE TITLE
Android 11: can't run in secure folder

### ISSUE THREAD

**Issue by ptrm** [koreader/koreader#7819]
* KOReader version: v2021.05-76-gba070c24_2021-06-08/
* Device: Android 11

#### Issue

Happens since #7813

My google secure account settings disallow me to install apps from outside of Play / Galaxy stores, so I use Secure folder feature which I believe is samsung's rename of the standard multi user feature.

Ever since the last update, KOReader asks me to allow access to all files, which seems to be given in the following settings that pop up. Sometimes a crash ensues, sometimes just another prompt for file access, which after setting it continues to show.

On Boox with A10 it works fine. Cannot try it on primary-user A11, though. Previous nightly works fine on secondary user. Tried uninstalling koreader and doing a clean install of today's version, but results are the same.

#### Steps to reproduce
1. Install latest nightly in a seondary user's enviroment on Android 11.
2. Watch it continuosly ask for file permissions although all possible are given.

##### `crash.log` (if applicable)

[koreader.crash.log](https://github.com/koreader/koreader/files/6614791/koreader.crash.log)

https://user-images.githubusercontent.com/366258/121151369-93ec4b80-c844-11eb-97b3-baf7dc97fa7f.mp4

**Comment by pazos** [comment]
> My google secure account settings disallow me to install apps from outside of Play / Galaxy stores

Very good feature :wink: 

> Ever since the last update, KOReader asks me to allow access to all files, which seems to be given in the following settings that pop up. 

Yeah, `MANAGE_ALL_FILES` is required in Android 11. 

> Sometimes a crash ensues.

The crash shouldn't be there, is our bug (well, mine). Caused by https://github.com/koreader/android-luajit-launcher/blob/master/assets/android.lua#L2651 paired with the new crash reporter. I will fix that.

> Sometimes just another prompt for file access

That's the expected behaviour. The program won't start until is granted as an [external storage manager](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt#L99)

> Install latest nightly in a secondary user's enviroment on Android 11.

Secondary user has nothing to do with it. A secondary user external storage is something like `/storage/emulated/1` and the request to manage all files for each secondary user will grant permissions on each user external storage.

> Watch it continuosly ask for file permissions although all possible are given.

That's a bug on `Secure folder`. Maybe they call it a *security feature*, I don't know. You will be able to reproduce the issue on other apps that request the same permission, like [App manager](https://f-droid.org/en/packages/io.github.muntashirakon.AppManager/).

Try to report the issue to Samsung and get some feedback. I'm not against the idea of downgrading the targetSdk to Android10, but they need to get the bug sorted out anyways. `MANAGE_ALL_FILES` is the new `WRITE_STORAGE` permission, and the behaviour should be the same even inside `Secure folder` sandbox.

**Comment by ptrm** [comment]
Thanks for looking the crash first of all :)

>
> Yeah, `MANAGE_ALL_FILES` is required in Android 11.
> 
> Try to report the issue to Samsung and get some feedback. I'm not against the idea of downgrading the targetSdk to Android10, but they need to get the bug sorted out anyways. `MANAGE_ALL_FILES` is the new `WRITE_STORAGE` permission, and the behaviour should be the same even inside `Secure folder` sandbox.

To clarify:
![Screenshot_20210608-141257_FX](https://user-images.githubusercontent.com/366258/121183224-24865400-c864-11eb-829d-999e45879355.png)
Is the above striked through permission a misnamed 'MANAGE_ALL_FILES' or something completely else?

**Comment by ptrm** [comment]
The screenshot above is from FX file manager as `settings -> apps -> koreader` show no permissions at all in the main sections, as below:
![20210608_143143](https://user-images.githubusercontent.com/366258/121185427-5ac4d300-c866-11eb-94ee-4f85503cca81.jpg)

(Second view is `... -> All permissions`)

**Comment by pazos** [comment]
@ptrm

> Is the above striked through permission a misnamed 'MANAGE_ALL_FILES' or something completely else?

That's exactly the permission. But apps cannot request the permission directly. They need to tell the system they would want to use that permission using an intent: see https://developer.android.com/training/data-storage/manage-all-files#all-files-access

You can contact Samsung and see if they're going to support that feature inside their sandbox. There're no reasons to treat that permission differently.

> The screenshot above is from FX file manager as settings -> apps -> koreader show no permissions at all in the main sections, as below

App info show both insta-granted (like internet or download without notifications) and *dangerous* (like write external storage) permissions. That screen doesn't show **special permissions**.

KOReader uses two different special permissions: `WRITE_SETTINGS` and `MANAGE_EXTERNAL_STORAGE`. Each special permission has its own place in system settings (usually buried on app settings, security  or whatever). Special permissions cannot be granted like normal/dangerous permissions.

You can invoke the WRITE_SETTINGS permissions prompt from settings -> screen -> timeout and see what happens: you'll get a rationale and, when you click ok, you'll be forwarded to the system, which will show you a list of apps with that special permission enabled.

**Comment by ptrm** [comment]
Thanks for the info :) I will come back if I know something about secore folder's app permission management. In the meanwhile I will build the phone version myself, so no pushes to lower the targetsdk :)

Regarding own builds for 29 instead of 30: Is changing this line back to commented (https://github.com/koreader/android-luajit-launcher/compare/b1697e48fa87077ede7455b10fa212a43dfdde11...56e4fb5190eba52bcfb44f264b4454d725cd5021#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cdR23) and in build.gradle changing the compile-and targetSdk values enough to revert the issue on my phone?

**Comment by pazos** [comment]
> Regarding own builds for 29 instead of 30: is changing this line back to commented out and in build.gradle, changing the compile-and targetSdk values enough to revert the issue on my phone?

Something like that.
* In `build.gradle` compileSdk 30 and targetSdk 29.
* In `AndroidManifest.xml` remove `android:maxSdkVersion="29"` for the `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions.

Keep in mind you'll need to sign the APK with your own keys if building with `./kodev release android`.

**Comment by pazos** [comment]
@ptrm: could you check this version: https://www.dropbox.com/s/lnilrdcl2m6x0pl/ko-test-nocrash.apk?dl=0

It shouldn't crash even on secure folder. If the sandbox cannot grant permissions as an external storage manager the dialog: "Please allow the app to manage all files" should be repeated again and again.

In the same vein if you deny permissions on Android 4 - Android 10 you'll get a toast saying "Insufficient permissions". (no need to test that as I can do it myself :smile: )

**Comment by ptrm** [comment]
Confirm no crashes on Android 11 with the dropbox version :)

Though it still bugs me I have not seen such file access permission layout as this one below, but guess it's due to not many of apps I use being targeted at sdk 30 yet?
![Screenshot0](https://user-images.githubusercontent.com/366258/121459413-7be30c00-c9ab-11eb-9d76-95a6b89fe165.png)

**Comment by pazos** [comment]
> guess it's due to not many of apps I use being targeted at sdk 30 yet?

Yup, see https://support.google.com/googleplay/android-developer/answer/10467955

Also, google imposes restrictions about which apps can hold that permission. We're free of these restrictions because we're not in Gplay (but if we did we should be inside "allowed usercases": file & documents manager)

 > The permission request still loops in Secure Folder despite all things marked allow above

KOReader should be listed there and labeled "Not allowed". You press on it and allow it. That's it. That's the *bug*/*security feature* in `SecureFolder`.

Attached a video of the expected behaviour: 

https://user-images.githubusercontent.com/975883/121530682-f177c800-c9fd-11eb-9b17-4cd1606d7420.mp4

**Comment by ptrm** [comment]
Aaand after #7846 it works on Secure Folder, thanks ^^

The permission settings changed theur look again and show just once (with permission disabled by defeault)
![Screenshot_20210615-092001_Settings](https://user-images.githubusercontent.com/366258/122010160-1fbd2500-cdbb-11eb-886d-c8db52920767.png)

**Comment by pazos** [comment]
o_O totally unexpected output. But **hooray**
