### ISSUE TITLE
Faulty display of image links when inline links are on

### ISSUE THREAD

**Issue by roger64** [koreader/koreader#7894]
* KOReader version: 2021106000000
* Device: Kindle PW3

#### Issue
Faulty display of image links when inline links are on

#### Steps to reproduce
Hi
Since it was implemented in late 2019, I use nearly always the inline display for notes with ePub3 books and set this as a permanent option. However, I just observed today what could be a not-so-good side-effect of this option.

I have an ePub3 with some hundreds of inline notes nicely displayed. Very fine.
This book has also about ten images, listed in a page. I linked each entry of the list with the corresponding image further in the book. 

When I read the book with Koreader, I realize that it displays the image link as a pop-up endnote (with text) but it does not display the image on the screen as expected.

So it seems that I have to choose between 
1. - either a classical display of endnotes / good display of images from the list
2. - or a nice display of inline notes / faulty display of images from the list

Here is the code I am using:

**for inline notes**
``` HTML
<a class="noteanchor" epub:type="noteref" href="chapitre20.xhtml#ftn1" id="bodyftn1">[1]</a>

<aside class="ntb" epub:type="footnote" id="ftn1">
    <p class="note"><a class="notesymbol" href="chapitre9.xhtml#bodyftn1">1</a> text of the inline note.</p>
</aside>
```

**for plain images in the list**
``` HTML
<p class="Biblio"><a href="chapitre9.xhtml#Image1graphic">1. Title of the image</a></p>

<div style="text-align:center">
    <img alt="Image1" id="Image1graphic" class="frameGraphics" src="images/image003.png" style="width: 97.0%; height: auto;"/>
</div>
<p class="Caption">Map 1. Legend</p>
```

Calibre displays properly the link to the image and its viewer displays the notes as pop-ups.

</details>

**Comment by NiLuJe** [comment]
(Updated for formatting ;)).

**Comment by poire-z** [comment]
> When I read the book with Koreader, I realize that it displays the image link as a pop-up endnote (with text) but it does not display the image on the screen as expected.

Footnotes popups have the footnote content delegated to MuPDF for it to render the bit of HTML to display in the popup widget - so, no access to other elements like images in the EPUB.

> So it seems that I have to choose between
        - either a classical display of endnotes / good display of images from the list
        - or a nice display of inline notes / faulty display of images from the list

I'm not sure I understand what you're doing and complaining about :/
I assume that these means:
- **A** _a classical display of endnotes / good display of images from the list_ = no in-page footnotes, no popup: you're following ALL links to their other normal page in the book, and of course, they look alright just like a normal page
- **B** _a nice display of inline notes_ = in-page footnotes
- **C** _faulty display of images from the list_ = target of links to images displayed in a footnote popup - because it's indeed detected as a possible footnote - and faulty because of the above MuPDF HTML rendering, so no image and empty content

In-page footnotes are nearly orthogonal to follow links and popup footnotes.
You enable **B** with style tweaks.
You can disable **C** with `Gear > Taps and gestures > Links > Show footnotes in popup`, and you'll jump to the pages with your images.
You get **A** when both **B** and **C** are disabled.

So, in your _either a classical display of endnotes / good display of images from the list_, I assume you disable **C**.
But you could have both in-page footnotes enabled, and popups disabled, and you would get:
_a nice display of inline notes / good display of images from the list_

Is there something I'm missing?

The only thing I could see that we could do better is with your example
`<img alt="Image1" id="Image1graphic"`
We could detect that the target is an IMG, and so not consider it candidate for footnote popups.
But targeting the IMG itself looks odd and must be rare: publishers would probably target the IMG container by putting the `id=` on the DIV that contains it, and this change wouldn't help: we'll give the DIV content to MuPDF, which will display some empty content.

**Comment by roger64** [comment]
Sorry for being unclear and thanks for taking this.
Your interpretation of A, B and C is right.
Yes what I call "inline" notes are "in-page footnotes" (_notes de bas de page_).I did enable them by using style tweaks.

The code from the image I gave above comes from my odt converter (writer2xhtml). It did include an _id_ within the img tag.
I also tried to insert this _id_ within the div enclosing the img tag but the display stayed the same (no image displayed, pop-up text instead).

I hope this scrambled ePub3 can help.
[scrambled.zip](https://github.com/koreader/koreader/files/6724362/scrambled.zip)

**Comment by poire-z** [comment]
It's still unclear what you expect (from the book, and from me :)
Have you tried what I suggested: disabling footnote popups ?

Looked at your EPUB, enabled in-page EPUB footnotes, and I see no issue - even with your chapter8 (page 10):
![image](https://user-images.githubusercontent.com/24273478/123600741-3de14700-d7f7-11eb-838f-8972d6ccce56.png)
Even with:
![image](https://user-images.githubusercontent.com/24273478/123600854-581b2500-d7f7-11eb-8cae-e96e2974d666.png)
when I tap or swipe these links, I jump to the page (page 20, page 149) with the image: no popup.
`06/28/21-09:55:39 INFO  not a footnote: no decision made, default to not a footnote`

If I enable `Show more links as footnotes`, I get them displayed in a popup widget:
![image](https://user-images.githubusercontent.com/24273478/123601067-8862c380-d7f7-11eb-993c-c36c3de78ee9.png)

So, how have you these options, and what when you disable them?

**Comment by roger64** [comment]
I have exactly the second display of your ( [image]) which I find faulty. I expect the image.

I tried to reproduce your steps but my koreader menu is different from yours.
![Reader_2021-06-28_162640](https://user-images.githubusercontent.com/1344670/123604903-df838b00-d82d-11eb-94b3-e0b9a7bce744.png)

**Comment by poire-z** [comment]
> I have exactly the second display of your ( [image]) which I find faulty. I expect the image.

I explained why you don't and won't get the image in popup footnotes above:
_Footnotes popups have the footnote content delegated to MuPDF for it to render the bit of HTML to display in the popup widget - so, no access to other elements like images in the EPUB._

> I tried to reproduce your steps but my koreader menu is different from yours.

That's because you haven't read what I wrote :/ and you're focused on in-page footnotes, and you are not looking at the right menu:
`Gear > Taps and gestures > Links > Show footnotes in popup`
or in French:
`Engrenage > Touchers et gestes > Liens > Afficher les notes de pied de page dans une fenêtre conte...` , but disabling `Afficher plus de liens comme notes...` might just be enough.

**Comment by roger64** [comment]
Merci beaucoup. J'ai tout compris maintenant. :)

Sorry for giving trouble and thanks for your tremendous work. Koreader is a world of its own.
