### ISSUE TITLE
render_mode does not change in .lua file

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7901]
* KOReader version: 2021-06
* Device: Kindle PW3 (FW 5.9.7)

#### Issue
In reflowable documents, Render modes (`legacy`, `flat`, `book`, `web`) do not change in respective metadata.lua files after manually changing it while reading.
As a consequence, tweak documents setting does not work for `render_mode`.
Here is what I added in the end of `directory_defaults.lua`:
```
    ["/mnt/us/books/[manga] Vagabond"] = {
        ["render_mode"] = 0,
    },
```
The tweak is actually working and the metadata.lua will change the render_mode to whatever is in the tweak (even if I put a string instead of number). However that has not effect on the newly opened documents in that folder.

#### Steps to reproduce
Open and close a book so that metadata.lua file appears in the respective .sdr folder.
Check what render_mode was set to (e.g. `0`).
Open the book again and change Render mode to any other type other than what was default. 
Go to metadata.lua again - the render mode is still the same (`0`).

For the tweak:
Tweak the document default as above. Open books for the first time in `/mnt/books/[manga] Vagabond/`, which contains `Volume 1.epub`, `Volume 2.epub`, etc. Render mode is set to whatever is manually saved as a default (long tap). Metadata.lua shows `0` for any opened documents.

**Comment by poire-z** [comment]
Can't reproduce.
But that's because this `legacy|flat|book|web` is not saved as `render_mode`, but as `copt_block_rendering_mode`:

https://github.com/koreader/koreader/blob/dde732c17f25f109caa06bb4f5d333d6dbafd06f/frontend/apps/reader/modules/readertypeset.lua#L61-L77
https://github.com/koreader/koreader/blob/dde732c17f25f109caa06bb4f5d333d6dbafd06f/frontend/apps/reader/modules/readertypeset.lua#L362-L373

`render_mode` seems to be a DJVu thing (that existed before the above one, so the different name `block_rendering_mode` which makes sense in the implementation, even if for the UI, a simpler "render mode" was best):
https://github.com/koreader/koreader/blob/dde732c17f25f109caa06bb4f5d333d6dbafd06f/frontend/apps/reader/modules/readerview.lua#L902-L923

**Comment by mergen3107** [comment]
Thank you so much! It works!
