### ISSUE TITLE
Main menu design

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7926]
EDIT: **sublevel number rejected**.

Going down into the main menu it is difficult to trace at which level you are.
It might be useful to display the level.

![1](https://user-images.githubusercontent.com/62179190/124288341-bc244d00-db59-11eb-80a1-a11192b002b3.png)
--
![2](https://user-images.githubusercontent.com/62179190/124288350-c0506a80-db59-11eb-8091-708d976dca99.png)

**Comment by poire-z** [comment]
> It might be useful to display the level.

Dunno if that's really "useful" to know I'm at sublevel 6. You'd have to know you want to go back to level 3, and even if that helps you to know you could hit <kbd>^</kbd> 3 times quickly, the <kbd>^</kbd>s might not even be at the same vertical position.
Users would most probably wonder what these 1 and 6 mean...
So, more noise than usefulness to me :)

**Comment by Frenzie** [comment]
Something I was thinking about is to replace the current way of going "up" in a menu with a title and a left arrow on top, not unlike Firefox. You could perhaps also include the previous level in there. That would always show where you are and it would put the back arrow in a consistent location.

But in the end I figured the benefit would be minor for a fair bit of effort, and you'd lose some vertical height.

Alternatively you could implement traditional expending menus, but I consider the wide target area a feature, not a bug.

**Comment by NiLuJe** [comment]
Yeah, a breadcrumb "path" bar would solve that in a saner and more common way, but it would eat significant vertical space (and, would be "fun" to implement ^^).

**Comment by mergen3107** [comment]
Can I please add something else that I think is confusing in submenus? Sorry if this was discussed and answered before (I can only vaguely remember that I asked here or on MobileRead). 

Example case: Reader - Gear - Status bar - Settings - Go to page 2 - Alignment

Now, if I go up, Settings will open on page 1. 
I see two possible solutions:
A) show the current title of the menu
B) at least bring to the same page (page 2), ideally highlight/emphasize “Alignment” to indicate that this was the menu the user just came from

**Comment by hius07** [comment]
> Now, if I go up, Settings will open on page 1

Fixed in https://github.com/koreader/koreader/pull/7903

**Comment by mergen3107** [comment]
Oh wow? I still can reproduce it on Kindle, 2021-06 stable. Did I mis-checked some settings maybe?

**Comment by Frenzie** [comment]
It's only been in nightlies for a couple of days. ^-^

**Comment by mergen3107** [comment]
Ah, sorry, that fix is 3 days old. 
I should check it on nightly then

**Comment by mergen3107** [comment]
OK, back to the question of sub menu title then. 
You guys mentioned about wasted vertical space. But can’t we just move current “row” with arrow up and time/battery to the top and just add the title? On a single row not all title lengths will fit on many narrow devices though. However we could also do something like in FM, when it decreases the font size to make it fit anyway

**Comment by Frenzie** [comment]
I don't think having a full menu stack is all that important, or knowing at which exact depth you are.

I'm referring more to this kind of scenario.
![Screenshot_20210702_221048](https://user-images.githubusercontent.com/202757/124323940-657f3900-db82-11eb-9906-ba70570283ca.png)

My thinking was that it could say:

<kbd>ᐸ **One-finger swipe**</kbd>

Or in your thinking, something like:

<kbd>… ᐸ **Gesture manager** ᐸ **One-finger swipe**</kbd>

> But can’t we just move current “row” with arrow up and time/battery to the top and just add the title?

Page numbers don't make sense on top.

**Comment by hius07** [comment]
To continue discussing main menu design.
What about having the parent menu(s) titles in the upper line (not a working code yet, just approaching).

<kbd>![1](https://user-images.githubusercontent.com/62179190/127856137-3e6f2ee2-bd53-49bf-90ff-b49fd983126c.png)</kbd>

<kbd>![2](https://user-images.githubusercontent.com/62179190/127856150-64735d3f-6d92-4ab3-88b4-78422407c7c3.png)</kbd>

<kbd>![3](https://user-images.githubusercontent.com/62179190/127856157-295afe65-b748-4d88-a08c-65594987d85d.png)</kbd>

**Comment by Frenzie** [comment]
I've always been in favor of doing that, yes. :-)

**Comment by hius07** [comment]
What to write in the title bar?

(1 automatic) the title of the parent menu
Short, simple, but sometimes might be not enough clear.

(2 automatic) concatenated titles of all parent menus (if needed truncated at the left)
Might be long and overcrowded.

(3 manual) a special title added to all submenus
Can be rather short and clear, but require a lot of work to add titles to submenus.

**Comment by poire-z** [comment]
> I've always been in favor of doing that, yes. :-)

Nothing against that on principle.

> What about having the parent menu(s) titles in the upper line

But I don't like this idea (and the screenshots):
- I don't find it particularly pretty nor clear: is it a title or a menu item?
- It waste one row for valuable menu items: we always tried to limit the nb of sub-items to 10 so they all fit on one page. Adding that title that will occupy a slot and will limit usable number to 9 and/or generate new pages.
- The benefit of this title is minor to me: people have always done without it until now, and even it it's nice to have and a principle of good UI design, I believe we can still do without. (I believe our users should have a better-than-average attention span because, well, reading requires it :) so, when navigating menus, we should know where we're at without needing a GPS :)
- The benefit of not having it means more room to see the book content below and the effect of the setting. I admit most menu items are not related to the book content, so for most we don't care. But for `Fonts>` and `Style tweaks>` submenus, we're better without this title.
- It can't even be set as an toggable option - as then, we'll have to keep in mind there can be a variable limit or 9 or 10. Unless this title is an additional slot and it will only bother people having it with a 11th slot and less room to see below, and eventually some cropping of the last item (dunno if/how we handle that).
- I guess its position, between top level icons and the submenu items, is logically right vs any other place.
- It could (less logically) takes the place of the hour+battery in the menu bottom area - because we don't really need the time and batter when browsing the menu :) But I'm sure some people who don't use the footer may be used to opening the top menu to see the time :/

**Comment by NiLuJe** [comment]
I'm mildly torn about a "view only" approach. A full-blown breadcrumb w/ actual per-level navigation would be best, but much more complex, because `Menu` ;).

In keeping with a "read only" indicator, and to possibly address @poire-z's concerns about wasting a line (which I mostly share, although it's probably only a real issue in a very few percentage of our menus), we could perhaps shoe-horn it in the *center* of the footer, keeping both the UP arrow and the time/battery?

**Comment by mergen3107** [comment]
> we could perhaps shoe-horn it in the _center_ of the footer, or right next to the UP arrow, and still keep the time/battery?

What if we also move time/battery next to the top-right corner "hamburger" icon?

**Comment by NiLuJe** [comment]
> > we could perhaps shoe-horn it in the _center_ of the footer, or right next to the UP arrow, and still keep the time/battery?
> 
> What if we also move time/battery next to the top-right corner "hamburger" icon?

That might be trickier given the widget layout, but it might not be a bad idea of technically feasible ;).

Just looking at the screenshots above, I realized that I'd forgotten about the pagination buttons, so my earlier idea wasn't viable anyway ^^.
