### ISSUE TITLE
ftp based services not working (send2ebook, cloud storage) ?

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#7955]
* KOReader version: 2021.04-60
* Device: Inkbook Prime (android) 

#### Issue
Since couple months I'm not able to use ftp services (send2ebook, now also checked cloud storage but it aslo didn't work) on koreader.
I even switched provider to differnet ftp (drivehq.com) but it's the same  problem

#### Steps to reproduce
In the hostname I tried: 
`ftp://ftp.drivehq.com` 
`ftp.drivehq.com` 
`ftp://drivehq.com`
the first one should be valid and I'm able to use it with nautilus, but as there's some logic around the connection string in koreader I tried all combinations, but none works

![Zrzut ekranu z 2021-07-10 12-56-46](https://user-images.githubusercontent.com/4487025/125160658-674a8d00-e17e-11eb-821b-1216f3b86ba4.png)

on emulator :
`FtpApi:listFolder(connection_url .. ftp_config.folder, ftp_config.folder)`
this returns `false`

there's also minor issue that when openeing again settings it forgets folder, but when entered it makes use of it.

**Comment by NiLuJe** [comment]
I'm pretty sure you don't need to specifiy the protocol handler, for once.

**Comment by mwoz123** [comment]
ok now tried only 'drivehq.com` in hostname 

in emulator connection string looks like this: `ftp://mwoz123:XXXXXXXX@drivehq.com`
which seems incorrect and I'm not albe to connect without `ftp.` prefix in front of `drivehq.com`.

response for all scerious is  `false` (for `listFolder`). 

Difference is it keeps on waiting/hanging and looks much more like connection timeout (similarly it was for `ftp://drivehq.com`). Where as for  `ftp://ftp.drivehq.com` and `ftp.drivehq.com` response `false` is in around 1 sec

**Comment by pazos** [comment]
@mwoz123: send2ebook will be deprecated soon. Their companion app was archived because it didn't work and you're probably the only user here. Now it is possible to have user plugins (just copy the plugin to your plugins folder (ie: in android that would be `/sdcard/koreader/plugins`).

If  you're interested you can push the plugin to your own repo, like https://github.com/jperon/clock.koplugin. If not I will move it to https://github.com/koreader/contrib a few months after deprecation.

**Comment by NiLuJe** [comment]
I mean the protocol handler (`ftp://`), not the subdomain (`ftp.`) ;).
