### ISSUE TITLE
Lists and menus: cyclical page turns

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8010]
Do we allow cyclical page turns in lists (menu, kvp) and menus (touchmenu)?
Yes by swipes.
No by taps (left and right single chevrons are disabled on the first and the last page respectively).
It's a little bit inconsistent.

**Comment by poire-z** [comment]
> No by taps (left and right single chevrons are disabled on the first and the last page respectively).

Which looks nice, and give some visual feedback that you're on the first or on the last page.

> Yes by swipes.

Which is so convenient to overcome the above tap limitation :)

So, I'm personally fine with this little inconsistency.
Any alternative in mind?

**Comment by hius07** [comment]
> Any alternative in mind?

I thought of enabling single chevrons.
This would also show a user an ability of cyclical page turns.

Disabled double chevrons in lists would indicate first/last page.

**Comment by poire-z** [comment]
Feels it would look a little odd.
But why not if _you_ don't feel then that single vs double chevrons look unlinked / inconsistent :)
But let's wait for others' thoughts.

**Comment by mergen3107** [comment]
> > Any alternative in mind?
> 
> I thought of enabling single chevrons.
> This would also show a user an ability of cyclical page turns.
> 
> Disabled double chevrons in lists would indicate first/last page.

I like this idea too

**Comment by NiLuJe** [comment]
Would look a little odd. I'd be inclined to tweak the icon somehow rather than just lighting up the usual single chevron?

**Comment by offset-torque** [comment]
I have to join the conversation to point out that this is another instance of a common KOReader UI problem: 
**We don't have signifiers to let users know which actions are available.**

See, I just learned that we can do **"cyclic page turns by swiping"** from hius07 now. A user might discover this **accidentally** by swiping on the last page. Accidentally because nothing in the interface shows that user can continue in that direction. On the last page, buttons become disabled to deny user from turning the page further **(implying a linear navigation)**. But actually it is a circular navigation **(if you know the trick)**. I am a "tap-turner" instead of "swipe-turner" so I wouldn't discover this **even** by accidentally in a thousand years.

If navigation wraps around, a user logically expects page turn buttons to continue working. 
**Availability of those buttons is the signifier for user that he can continue turning in that direction.**

So yes this is the only logical conclusion to convey users that navigation is circular:
> hius07: I thought of enabling single chevrons.

**Comment by Frenzie** [comment]
> See, I just learned that we can do "cyclic page turns by swiping" from hius07 now. 

Which sounds like a bug to me tbh.

>

**Comment by poire-z** [comment]
> The button being disabled signifies you're at the end. That's a good thing.

I **agree**, something (this or else) should show we're **at the end or start** (although `Page 1/14` or `Page 14/14` shows **it**, but this needs a **few more milliseconds** of processing :)

>  I am a "tap-turner" instead of "swipe-turner" so I wouldn't discover this **even** by accidentally in a thousand years.

So ? You're a tap user, so you don't need to discover this. And it **adds nothing** you already don't have; you can cycle / go to first or last page with the double chevron.

> > So yes this is the only logical conclusion to convey users that navigation is circular:

> There's at least one other logical conclusion, namely to get rid of that cyclical swipe stuff.

So, because of some tap user **loud shouting**, you'll deprive swipe users to be able to go to first/last page ?
I don't like this kind of logic :)

We have other things "hidden", that we don't advertise or make shouting on the screen (like the >3s long-press). Most of these are non-essential, and can be discovered, by error or intuition. You're free to document them in a user manual/quick start guide - no need to shuffle or make the UI more heavy.

**Comment by Frenzie** [comment]
> So, because of some tap user loud shouting, you'll deprive swipe users to be able to go to first/last page ?
I don't like this kind of logic :)

Not exactly, I've just never liked the cyclical behavior. ;-) With the sidenote that I'm not so much talking about swipes as the page up/down behavior.

But I'm perfectly alright with erring on the side of keeping things the same. Tap users certainly aren't missing out on anything, so as you say the only reason to change anything would be swipe-internal.

**Comment by offset-torque** [comment]
> So, because of some tap user loud shouting

**Bold is used for emphasizing**. Shouting is CAPITAL LETTERS (since 1856 it seems, nothing new). It has its own wikipedia page even: [https://en.wikipedia.org/wiki/All_caps#Association_with_shouting](https://en.wikipedia.org/wiki/All_caps#Association_with_shouting)
Educate yourself before swinging accusations.

And I am a tap user because KOReader can't handle swipe properly (on my device at least). Half of my highlights ends not because I lift my finger but KOReader somehow decides to end it in the middle. I have to delete and re-highlight especially if it is a long paragraph.

> Most of these are non-essential, and can be discovered, by error or intuition

Just imagine a world where Microsoft or Apple had this attitude

> You're free to document them in a user manual/quick start guide

People don't read user manuals, even when they are obligated to. That's why UI should include action signifiers and discoverability in itself. You shouldn't deny things in UI to reveal that "actually it can be done" in the manual.

**Comment by Frenzie** [comment]
> Just imagine a world where Microsoft or Apple had this attitude

I'm not sure what your point is exactly, because I certainly don't have to imagine anything of the sort.

> People don't read user manuals, even when they are obligated to. That's why UI should include action signifiers and discoverability in itself. You shouldn't deny things in UI to reveal that "actually it can be done" in the manual.

I guess you're trying to make some philosophical point, but it's almost grotesque inapplicable to the situation of an alternative method of doing *the exact same thing*. xp

**Comment by poire-z** [comment]
> > Most of these are non-essential, and can be discovered, by error or intuition

> Just imagine a world where Microsoft or Apple had this attitude

Well, they do. Looking at my screen, I can change a window size by click and drag the border - nothing tells me I can (ok, the mouse cursor changes when I'm on it, but nothing tells me before that). I can move a window by dragging the title bar - and there is no little hand icon there telling me I can do that.

> That's why UI should include action signifiers and discoverability in itself

Well, Swipes actually cycling menu pages will be discovered easily - just the first time you try an additional one on the first or last page when you could expect it may not work but it actually does ! You see that once, you get it, no need to be reminded (you might expect and prefer to be blocked there, and not like our behaviour - but you'll know it).

There is a road that could be "don't make anything hidden/discoverable" that is not obviously indicated - that Kobo or Kindle embedded software may have taken (so, simple, easy for old people, no surprise, but possibly a bit cumbersome when doing some actions).
KOReader takes the other road: allow many stuff/shortcuts, for the best usability (while still trying to make the UI clear and obvious, so people can still do or get out with the UI indicators). At least, that's how I see it and expect it to be.
