### ISSUE TITLE
Unicode in CSS content property decoded incorrectly

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#8034]
* KOReader version: 2021.07-20
* Device: Kobo Clara/Emulator

#### Issue

A CSS rule in a style tag that has a "mid dot" Unicode char 0xb7 is decoded incorrectly:

![2021-07-28_061613_207x62_screenshot](https://user-images.githubusercontent.com/5386578/127267639-f9fa50ce-b39e-40a3-9567-3074b4b9fed3.png)

#### Steps to reproduce
Epub containing:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
  <title></title>
  <style>.foo:after{content:"·"; }></style>
</head>

<body>
  <p class="foo">foo</p>
</body>
</html>
```

[css_encoding.epub.zip](https://github.com/koreader/koreader/files/6890485/css_encoding.epub.zip)

What should happen: Just the character is used: `foo·`.

**Comment by poire-z** [comment]
The bug seems to be only for when it's in the HTML>HEAD>STYLE on a EPUB fragment.
No problem when it's in a linked css in an EPUB fragment, or when it's in the HTML>HEAD>STYLE of a plain HTML document.
The cause seems obvious (some lString8 headStyleText which should be lString32). I'll fix that with other CSS stuff in a few weeks.
