### ISSUE TITLE
FR: Ability to disable the clock in the top menu

### ISSUE THREAD

**Issue by nihilazo** [koreader/koreader#8123]
**Does your feature request involve difficulty completing a task? Please describe.**
no, it should be very simple to complete.

**Describe the solution you'd like**
I'd like the ability, with a configuration option, to disable the clock that shows next to the battery life indicator in the top menu when it is open.

**Additional context**
I often read before sleeping and I find having a clock there can interrupt my sleep cycle.

**Comment by zwim** [comment]
That is easy:
Go to the gears menu -> Status bar (last entry) -> Alt status bar (first entry)  and uncheck `Current Time` (4th entry).

**Comment by hius07** [comment]
> in the top menu

Is it alt satus bar or falling down main menu?

**Comment by mergen3107** [comment]
> in the top menu when it is open.

It looks like it is the top menu

**Comment by nihilazo** [comment]
> > in the top menu when it is open.
> 
> It looks like it is the top menu
yes, in the falling down main menu.

**Comment by zwim** [comment]
@nihilazo Is your issue is resolved? If yes, you can close it.

**Comment by nihilazo** [comment]
> @nihilazo Is your issue is resolved? If yes, you can close it.

no is isn't, the response was only for disabling the status bar clock not the one in the drop-down main menu.

**Comment by poire-z** [comment]
This would be easy to implement - but I'm not fond of adding a setting for this very strange wish.

> I often read before sleeping and I find having a clock there can interrupt my sleep cycle.

I don't really see the relation between seeing the hour and your sleep :) Would seeing the hour (too early, too late...) make you upset and prevent you from sleeping vs. not seeing it and going with your body flow ? Strange.
But:
- if that's bothering, just don't look at it :) when you open the menus
- or just don't open the menus - you shouldn't really need to when really reading... Why would you need to open the menu ? Most menu items can be associated to gestures, in case you really need some.

(Because then, we should also allow disabling showing the battery: I'm sure there are people with a condition that whenever they see a battery levell lose some %, they have the urge to charge the device to make it go up ! and having to charge it, they would be prevented from reading :)
