### ISSUE TITLE
Copycat / clones on Google Play

### ISSUE THREAD

**Issue by Poussinou** [koreader/koreader#8234]
Hi @koreader

I found this app developer on the Google Play Store : https://play.google.com/store/apps/dev?id=5322107491432881251

This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under AGPL license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by Frenzie** [comment]
You're not wrong; at a glance I think that's just Librera with some added ads. I'm sure they'd appreciate it if you reposted your message over there. https://github.com/foobnix/LibreraReader

**Comment by pazos** [comment]
We're free from copycats and we will be free unless:

- somebody makes the port to 64 bit ABIs
- somebody makes the useless effort to move from APKs to AABs

Even then that somebody needs to convince google that the app should be whitelisted to be able to use the full storage permission instead of the scoped storage mess.

IMHO a copycat of KO in the play store would be even desiderable for users that don't want to get the app from reputable sources. Our target audience should be fine without it :)
