### ISSUE TITLE
StatusBar shows when resuming to History screen on Kobo

### ISSUE THREAD

**Issue by git-help-eng** [koreader/koreader#8278]
Device:
Kobo ClaraHD
FW: 4.28.18220 (2021-08-07)

KOReader: 2021.09

Screensaver setting: "Leave screen as it is"

Steps to reproduce:
  1) open an epub 

  2) turn on the (lower) StatusBar

  3) go to the history screen

  4) suspend device

  5) resume device

Expected Result:
  StatusBar is not see at the bottom of the history screen.

Observed Result:
  StatusBar is seen at bottom of the History screen.  It displays the status of the last opened epub.

Other information:
  Further cycling between suspend/resume states without leaving the history screen shows that the StatusBar does not update its state and remains "fixed" on the screen.
  If going to the history screen immediately upon starting KOReader (without first going to the epub) then the observed result matches the expected result.

![statusBar_on_history_screen](https://user-images.githubusercontent.com/79425928/135139901-dab71202-652b-4667-8ef6-96ceff433cec.jpg)

**Comment by yparitcher** [comment]
I can't reproduce, but possibly caused by:
https://github.com/koreader/koreader/blob/2b87b1d8ed0b71e8830615106b6d8fba86e67182/frontend/apps/reader/modules/readerfooter.lua#L2252-L2274

maybe `self:onUpdateFooter(self.view.footer_visible)` should be replaced by:
https://github.com/koreader/koreader/blob/2b87b1d8ed0b71e8830615106b6d8fba86e67182/frontend/apps/reader/modules/readerfooter.lua#L2285

**Comment by NiLuJe** [comment]
@yparitcher: Haven't had time to test, but, yeah, that looks sensible ;).

**Comment by git-help-eng** [comment]
Yes, that looks good.  I'll submit a PR.

Thanks.

**Comment by git-help-eng** [comment]
This issue is resolved in PR #8289.
