### ISSUE TITLE
Drop Caps/Large Caps not displaying correctly.

### ISSUE THREAD

**Issue by fyoosh** [koreader/koreader#8284]
First time contributing a bug/issue so please do let me know if I've missed anything :)

* KOReader version: v2021.09
* Device: ONYX BOOX Poke 3

#### Issue
I'm seeing an issue with Drop Caps being displayed incorrectly on some EPUB files, while the same file displays correctly in NeoReader on the same device and offline in Calibre etc

Screenshots of example: 
 NeoReader on left. KOReader on right.
<img width="1149" alt="Drop caps issue 01" src="https://user-images.githubusercontent.com/90405298/135487278-1b340d1b-f17f-4324-ac58-9a2fceb7ecde.png">

<img width="1154" alt="Drop caps issue 02" src="https://user-images.githubusercontent.com/90405298/135487366-7c2331e9-34ba-40ca-95c5-50e02fef3efd.png">

#### Steps to reproduce
Zip of EPUB file used for this example:
[n+1 What Was the Hipster.epub.zip](https://github.com/koreader/koreader/files/7260756/n%2B1.What.Was.the.Hipster.epub.zip)

**Comment by poire-z** [comment]
Your EPUB looks fine on my side:
![image](https://user-images.githubusercontent.com/24273478/135490933-ec9acebd-9c9c-498c-8339-4451d93a85cb.png)

Not really drop caps as they don't drop in the line below - at least, that's how I understand the term "drop caps" :) but just a larger font size.
A bit strange this `line-height: 0` in the CSS, but it seems to cause no issue:
![image](https://user-images.githubusercontent.com/24273478/135491210-155fe4b2-06f2-4837-9239-a96f885a177e.png)

But the `font-size:22pt` makes it a fixed font size, that won't scale when you change KOReader's font size, so that may be the reason for you to see it smaller than the text around.
You can change Zoom/DPI in the bottom menu to have these 22pt (and everything CSS-fixed-units) become larger, or make specific style tweaks to change these 22pt to be a relative font size, ie.
`.drop-cap { font-size: 1.5em !important; }`

**Comment by fyoosh** [comment]
Oh, so is something in my current KOReader settings stopping it being displayed as you're seeing?

> You can change Zoom/DPI in the bottom menu to have these 22pt (and everything CSS-fixed-units) become larger

Could you explain this a little more for a newcomer? :)

**Comment by poire-z** [comment]
I won't rewrite what's written in KOReader :):

![image](https://user-images.githubusercontent.com/24273478/135494530-63efdead-5091-4507-859d-62073e0596a0.png)

NeoReader may use your own device DPI, so when seeing font-size=22pt, it will scale this up to, say, 60pixels.
KOReader doesn't use your device DPI and default to use 96dpi (because I think it's safer, to avoid having huge margins with Word documents), so it may use a font size of, say, 22pixels.
For books that use fixed CSS units (which is rather bad practice), you may then get smaller things - but you can yourself change this with the above bottom toggle to have it to your liking.

The drop caps in this book should have a fixed font size, in NeoReader and KOReader (if you increase your main font size, they shouldn't increase with it):
![image](https://user-images.githubusercontent.com/24273478/135495316-817ef028-901d-401e-9b20-3e47353b6159.png)

**Comment by fyoosh** [comment]
You explained well, I’m with you now. (I also didn’t realise there were info/help pop ups in app by holding menu items.)

I had dpi set at the default of 96, as you say, changing to 300dpi renders the large letters as seen in other apps. 

Thanks for your help!
