### ISSUE TITLE
Ginormous speed & rendering regression in CRe

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#8384]
* KOReader version: current nightly (2021.10.1-36)
* Device: Any

#### Issue

Noticed a weird regression when migrating the Forma to the Sage.

The Forma was running an older build (.08-48 or something, from the 9th of september), and the Sage is running a current build.
Rendering and re-rendering a book is hilariously slower (as in, easily in the hundredfold scale), and the line-height is hilariously larger.

#### Steps to reproduce

I'll try to bisect this afternoon, and will post a scrambled ePub later if it's reproducible there, just wanted to post an early warning in case @poire-z had any idea ;).

**Comment by Iron-E** [comment]
I too am noticing major slowdowns. Tried a random sample from my digital library of 7 PDFs, ranging from 6–300 pages: any scrolling (zoomed, continuous) will lag the otherwise highly performant application.

**Comment by Frenzie** [comment]
That's not related to crengine. PDF is a completely different format. Presumably what you're seeing is the next page being rendered. If you have enough memory on your device, you can set DHINTCOUNT higher.

https://github.com/koreader/koreader/blob/7887c9b1cf4b54b7333bf0fb8c1cccf5c5fe8f03/defaults.lua#L9-L11

**Comment by NiLuJe** [comment]
Sidebar: I'm not entirely sure things are entirely kosher with DHINTCOUNT > 1, though ^^.

**Comment by Iron-E** [comment]
Ah, sorry to sidetrack the issue. I'll try that fix, though I have 12gb RAM so hopefully that is enough 😅

I'll open a different issue if it persists.

**Comment by NiLuJe** [comment]
Cool, thanks for looking into it ;).

Yeah, the line-height is whacky as all hell when everything is parsed, but I've seen it before, but the fact that it actually *broke* image rendering was kind of weird ^^.

**Comment by poire-z** [comment]
> The main stylesheet is specified twice in the DOM, so it's possible that it is parsed twice

And it actually is parsed twice, but only when there is a single CSS specified in the HTML fragment:
```
parsing1 OEBPS/stylesheet.css
  Parse(OEBPS OEBPS/stylesheet.css)
parsing2 OEBPS/ @import url("stylesheet.css");
  Parse(OEBPS OEBPS/stylesheet.css)
```
When there are more than one, all is as expected:
```
parsing1 stylesheet.css
  Parse( stylesheet.css)
parsing2 OEBPS/Text/ @import url("../../page_styles.css");
  Parse( page_styles.css)
```

https://github.com/koreader/crengine/blob/5f6c5da61428535b76277a75efd5ae059125efa6/crengine/src/lvtinydom.cpp#L13861-L13862
```
stylesheetLinks.erase(0, 1);
stylesheetLinksMediaConditions.erase(0, 1);
```
Looks like this erase(pos, count) does not work as expected with (0, 1):
https://github.com/koreader/crengine/blob/5f6c5da61428535b76277a75efd5ae059125efa6/crengine/include/lvarray.h#L154-L167

That's the kind of in-place array stuff that I dislike having to undestand, but it is small, will look later (but if you @NiLuJe see an obvious error and its correction, please speak :)

**Comment by NiLuJe** [comment]
At a quick glance, the `_size` / \`_count` / `len`confusion is... confusing,  especially as they all appear to mean the same thing: the amount of *items* in the array, not it's size/length (which would imply storage space in bytes).

It vaguely looks like `reserve` doesn't update `count`, which could probably break the crazy shit `erase` is attempting to do? (which I'm not sure I get at first blush?).

**Comment by NiLuJe** [comment]
Oh, okay, `_size` is the amount of *allocated* elements, `_count` is the amount of *live* elements. #needsbetterdoc ;s

**Comment by NiLuJe** [comment]
What about a much simpler

```
for (int i = pos+count; i < _count; i--) {
    _array[i] = 0;
    _count--;
}
``` 

because I'm not sure I understand what the weird copy is all about... :?

**Comment by poire-z** [comment]
Yes, just _count matters, the amount of item in the array.
It's just that `for (i=pos+count; i<_count; i++)` becomes `for (i=0+1; i<1; i++)` which doesn't loop at all :)

**Comment by poire-z** [comment]
We must move the items initially after pos+count in the array at the places where we erased items : this doesn't just zero them, but it should shrink the array.

**Comment by NiLuJe** [comment]
https://github.com/llvm/llvm-project/blob/main/libcxx/include/vector

The STL is likely doing this insanely more efficiently :s.

**Comment by poire-z** [comment]
Well, rewinding/erasing, we were looking at the wrong object :/ It's not a LVArray but a LVString32Collection :)
https://github.com/koreader/crengine/blob/5f6c5da61428535b76277a75efd5ae059125efa6/crengine/src/lvstring.cpp#L1405-L1423

**Comment by poire-z** [comment]
Where more obviously, this check is wrong:
```c
    if (offset < 0 || offset + cnt >= count)
        return;
```

In our case, 0 + 1 >= 1 is true, so we don't do anything.

**Comment by poire-z** [comment]
A little confirmation and we're done (because my arithmetics rhymes with rhumatisms :)

**Comment by NiLuJe** [comment]
What about `erase(1, 1)` on an array of one item, though?

**Comment by NiLuJe** [comment]
The loops take care of this just right, it feels like we only really need to check for underflow?

**Comment by poire-z** [comment]
I wouldn't really mind about LVArray: the sanity check are debug only for performance reasons I guess, as LVArray might be used a lot - and I assume the current usages are fine if we never noticed any issue.

As for lString32Collection (the right check was already there in lString8Collection), lString32Collection::erase is rarely used: once in what we're focusing on, and another use in this CSS parsing code (_inProgress, to keep track of the CSS files we're parsing to avoid circular import - which might have some impact, the 1/3 below), and that's all - so probably why we didn't notice this bug before.

So, with:
```diff
--- a/crengine/src/lvstring.cpp
+++ b/crengine/src/lvstring.cpp
@@ -1408,3 +1408,3 @@ void lString32Collection::erase(int offset, int cnt)
         return;
-    if (offset < 0 || offset + cnt >= count)
+    if (offset < 0 || offset + cnt > count)
         return;
```
Your book loading time on my emulator goes from 21s to 7,7s, which is 1/3, better than the 1/2 I was expecting.
Can you check how bearable it feels on your device ? It's not much, but between 1mn and 20s, the difference is noticable.
I have less hope for other optimisations, but I'll have a look tomorrow at what cause the most slowdown.

**Comment by NiLuJe** [comment]
That `offset + cnt > count` check is still broken for the `erase(1, 1)` case on an array of count `1`, though, right?

I'll try to fire a build tomorrow night to test ;).

**Comment by poire-z** [comment]
I don't think so: with an array of size 1 (`[0] = "foo")`,
- there is nothing to erase at offset=1. So 1+1 > 1 is true and we return early.
- but we can erase(0,1), as 0+1 > 1 is false and we do the work.

**Comment by poire-z** [comment]
Can you tell a bit more about the rendering/drawing "regressions" you get with the other stylesheets applied (line height, images) ?
Are they noticable on the scrambled epub ?
If not, can you post some screenshots of what you get now vs. what you had before, so I can try to guess what CSS bit is at play ?

**Comment by NiLuJe** [comment]
> I don't think so: with an array of size 1 (`[0] = "foo")`,
> 
>     * there is nothing to erase at offset=1. So 1+1 > 1 is true and we return early.
> 
>     * but we can erase(0,1), as 0+1 > 1 is false and we do the work.

Duh'. Too much Lua :D.

**Comment by NiLuJe** [comment]
> Can you tell a bit more about the rendering/drawing "regressions" you get with the other stylesheets applied (line height, images) ? Are they noticable on the scrambled epub ? If not, can you post some screenshots of what you get now vs. what you had before, so I can try to guess what CSS bit is at play ?

The image stuff is not noticeable because of the scramble, unfortunately.

A quick glance at Calibre shows that the line-height is probably meant to be ginormous (although maybe not that much), but the images are not split across pages there.

----

Current master:

A page with most of an image:
![forma_img](https://user-images.githubusercontent.com/111974/140423086-a8aa4f0c-2b6f-4843-bd07-7e3cb02c8394.png)

The next, with the overflowed bit of the previous image on top:

![forma_img_overflow](https://user-images.githubusercontent.com/111974/140423099-fa91c4e0-0192-457a-8568-704130591337.png)

The first chapter's page:
![forma_text](https://user-images.githubusercontent.com/111974/140423108-9d1c4833-8870-4373-9a93-729d03dd0ec7.png)

----

The same on the Sage, so without the other CSS parsed:

![Reader_2021-11-04_223059](https://user-images.githubusercontent.com/111974/140423243-98dc0b0b-3b90-4cde-84aa-dc71533632ce.png)
![Reader_2021-11-04_223105](https://user-images.githubusercontent.com/111974/140423258-fb6f4c52-70a8-4115-bfef-f67d8a5b2f33.png)

----

So, possibly related to centering/positioning/alignment or something?

**Comment by NiLuJe** [comment]
Hmm. Not actually sure it's an overflow, it looks like a repeat of a couple of the last rows, which is... weirder?

**Comment by NiLuJe** [comment]
PM me somewhere and I'll get you the real file, if it helps?

**Comment by poire-z** [comment]
It might also be an effect of the line height on the image, vs. vertical-align, that we may not account for an image enforced max height, so having some bits of it on the next page.
(The real file might help, I've just sent you a mail.)

**Comment by poire-z** [comment]
> style-advance.css contains thousands of ".ancestors-classname1 .classname2" conditions, that are known to take some time to check (because we need to walk up the tree for each node that matches classname2 to see if it has a parent that match classname1). And the amount of initial classname match must also adds to the time needed, as many many nodes in this book have a classname, so lots of string comparisons.

The ancestor things does not really add much in the case of this book (no change if I remove all of them to let them be simple classnames checks).
It's the thousands classname checks that take time.

Some timings with style-advance.css only, if I `return false` at the places I put some durations:
```c
    case cssrt_class:         // E.class
        {
// 2.8s
            lString32 val = node->getAttributeValue(attr_class);
// 3.3s ( 3.2s with before: if (!node->hasAttribute(attr_class)) return false; )
            if ( val.empty() )
                return false;
// 3.3s
            // val.lowercase(); // className should be case sensitive
            // if ( val.length() != _value.length() )
            //     return false;
            //CRLog::trace("attr_class: %s %s", LCSTR(val), LCSTR(_value) );
            /*As I have eliminated leading and ending spaces in the attribute value, any space in
             *val means there are more than one classes */
            if (val.pos(" ") != -1) {
// 4.0s
                lString32 value_w_space_after = _value + " ";
                if (val.pos(value_w_space_after) == 0)
                    return true; // at start
                lString32 value_w_space_before = " " + _value;
                int pos = val.pos(value_w_space_before);
                if (pos != -1 && pos + value_w_space_before.length() == val.length())
                    return true; // at end
                lString32 value_w_spaces_before_after = " " + _value + " ";
                if (val.pos(value_w_spaces_before_after) != -1)
                    return true; // in between
                return false;
            }
// 4.1s
            return val == _value;
// 4.2s (3.6s with if (val.pos(" ") {} removed)
```
This bit of code is called `nb of classname checks * nb of nodes`, 15 787 696 times in this book with style-advance.css only ! And we reach the `val==value` check 7 953 092 times.

The `val == value` string comparison is surprisingly quite cheap - but the `val.pos(" ") != -1` is not. It might be optimized if we prepend a space when we know there is a space in there, so we only need to check the first char instead of all.

**Comment by poire-z** [comment]
I'm quite confused, or limited by my C++ skills...
We have in lvstring.h for lString32:
```c
    /// returns last character
    value_type lastChar() { return empty() ? 0 : at(length()-1); }
    /// returns first character
    value_type firstChar() { return empty() ? 0 : at(0); }
    /// returns character at specified position, with index bounds checking, fatal error if fails
    value_type & at( size_type pos ) { if ((unsigned)pos > (unsigned)pchunk->len) crFatalError(); return modify()[pos]; }
    /// returns character at specified position, without index bounds checking
    value_type operator [] ( size_type pos ) const { return pchunk->buf32[pos]; }
    /// returns reference to specified character position (lvalue)
    value_type & operator [] ( size_type pos ) { return modify()[pos]; }
    /// resizes string, copies if several references exist
    void  lock( size_type newsize );
    /// returns writable pointer to string buffer
    value_type * modify() { if (pchunk->nref>1) lock(pchunk->len); return pchunk->buf32; }
```
I tried to use:
```c
lString32 val = node->getAttributeValue(attr_class);
[...]
            // if (val.pos(" ") != -1) { // original
            // if (val.pos(' ') != -1) { // Already BETTER
            // if ( val.lastChar() == ' ' ) { // slower
            // if ( val[0] == ' ' ) { // slower
            // if ( (lChar32)val[0] == U' ' ) { // slower
            // if ( *(val.data()+val.length()-1) == ' ' ) { // GOOD
            if ( val[val.length()-1] == ' ' ) {  // slower
```
But if I use:
`const lString32 val = node->getAttributeValue(attr_class);
`
only then
```c
            // if ( *(val.data()+val.length()-1) == ' ' ) { // GOOD
            if ( val[val.length()-1] == ' ' ) {  // AS GOOD
```
So, it seems to mean that with a _non-const_ `lString32`, val[] would use the slower:
`    value_type & operator [] ( size_type pos ) { return modify()[pos]; }`
But with a `const lString32`, val[] would use the faster:
`    value_type operator [] ( size_type pos ) const { return pchunk->buf32[pos]; }`
making it equivalent to the pure C-pointer `if ( *(val.data()+val.length()-1) == ' ' ) `

I thought `value_type & operator [] ` would only be used when assigning, ie. `val[0] = 'a'`, and that when just reading `lChar32 c = val[0]`, the compiler would obviously use `value_type operator []`... but it seems not.

Does that make sense ?

That means we might improve a lot of things by using `const lString32` when just reading - but then, a lot of other methods won't work (ie. lastChar() won't work with a const lString32)...

> It might be optimized if we _append_ a space when we know there is a space in there, so we only need to check the _last_ char instead of all.

So, with a const and this, we go from 4.2s to 3.6s, which is a small improvement.

But we go from 4.2 to 3.8s with just `if (val.pos(' ') != -1) ` - pos of a char - instead of `if (val.pos(" ") != -1) ` - pos of a substring - without the need to append a space to the attribute and make this attribute a bit different from the original.

**Comment by NiLuJe** [comment]
Wheee, `const` magic ;).

I don't really do C++, but, yeah, AFAICT, the return by reference is plainly there so that it can work when the operator is called on an lvalue.

And, yeah, the fact that we have a return by value operator and that this isn't actually called on an lvalue makes me naïvely think that the by value operator should be the one being used, regardless of constness.

(In fact, there should *probably* be a by-value-and-const operator overload, c.f., https://en.cppreference.com/w/cpp/language/operators).

Regardless, const strictness is A Good Thing, and, besides making the programmer's intent much clearer, it also helps the compiler make the right decision. That's a win-win in my book ;).

**Comment by NiLuJe** [comment]
(Mutable strings are fun, but *expensive*, which is why most interpreted languages use immutable strings (e.g., Lua, Python). Some languages even make basically all the things immutable by default (Rust? ^^).

**Comment by poire-z** [comment]
About the rendering issues:

The large line-height is indeed specified as it shows, in style-reset.css:
```css
body {
  margin:         0;
  padding:        0;
  font-size:      100%;
  vertical-align: baseline;
  line-height:    1.75;
```
Previously, we ignored it as we didn't parse the @ import stylesheets.
Solution: `Ignore publisher line-heights` style tweak :)

----
 
> The next, with the overflowed bit of the previous image on top:
> Hmm. Not actually sure it's an overflow, it looks like a repeat of a couple of the last rows, which is... weirder?

You are right.

```html
<html class="hltr"> <!-- yeah, they even put classname on the HTML element ... -->
<body class="image-page">
<div class="main">
<p><img class="fit" src="../image/p000_01.jpg" alt=""/></p>
</div>
</body>
```
```css
.fit {
  display:            inline-block;
  page-break-inside:  avoid;
  max-height:         100%;
  max-width:          100%;
}
```

![image](https://user-images.githubusercontent.com/24273478/140619090-d2737e9f-a825-418d-9acf-e97b0bd975b7.png)

They make the image itself `display:inline-block`, which is a case we don't handle well:
- at the point of sizing blocks, we get the image WxH from its style, and we set this to the size of the inline-block, and we're done. At this point, the block height may be larger than the page height. Also, we don't support max-height in % as at this point, we don't know the container height (which should not be the page height).
- when drawing, we ensure the image does not overflow the page height (minus margin/padding/borders of its wrapper) and resize it (the resizeImage() func you worked on).

So, we end up with the inline-block container the size of the original images native size (1502x2048). It makes the unique line of the P paragraph h=2048. When drawing the image, we resize it to a bit less that your screen height, so it's full on the page. But we draw the paragraph line of 2048, and we just slice this too tall height. So, the bottom slice gets on the next page. But for such sliced lines, I guess we don't crop/clip it, so parts of the top slice is drawn in the top margin of this next page (I think we don't crop/clip it because of drop caps that can often overflow their container, so best to show it all).

![image](https://user-images.githubusercontent.com/24273478/140619504-5fbd350d-0e14-435b-9302-c368594c7609.png)
(I added `.fit { background-color: yellow; }`)

If we had the image inside another wrapper that would be itself `display:inline-block ` instead of the image, we would handle it better:

```html
<body class="image-page">
<div class="main">
<p>a<span class="fit"><img class="nope-no-fit" src="../image/tobira.jpg" alt=""/></span>b</p>
</div>
</body>
```

![image](https://user-images.githubusercontent.com/24273478/140619842-49cb7fad-68dc-401f-82ed-42806af8d8ee.png)


So, it's indeed a bug on our side, but somehow quite hard to solve, triggering only on the above case when images native size is larger than the screen. Couldn't find a non-messy way to solve this case.
So, solution for the case of tricky stuff we don't handle well: create a user style tweak you can enable on all this publisher's book to kill the `.fit { display: inline-block }`:

```css
.fit { display: block !important; }
body { line-height: inherit !important; }
```

**Comment by poire-z** [comment]
Some fixes and optimisations related to this book in https://github.com/koreader/crengine/pull/458.

**Comment by NiLuJe** [comment]
@poire-z: Many thanks for the detailed investigation!

(I guess you want to close this when the CRe bits hit front?).

**Comment by NiLuJe** [comment]
Finally had time to give it a try, and, yeah, it's still slow on device, but no longer unbearably so; and the style tweaks do the trick for the rest, thanks! ;).
