### ISSUE TITLE
Tolino Vision 6 Illumination Control

### ISSUE THREAD

**Issue by DominikSchmidbauer** [koreader/koreader#8429]
Illumination and light color can not be adjusted via the KOreader slider on the new Tolino Vision 6

**Comment by pazos** [comment]
It is a known issue for all e-ink android readers. See https://github.com/koreader/koreader/issues/5364 (a bit old, some stuff changed a lot).

Resumed in: If your device use non standard lights then you need to workaround yourself. We can't help without the device. 

Saying that: it should work with [`TolinoWarmthController`](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/lights/TolinoWarmthController.kt).

I'm not very fan of keeping a separate ticket for each device. I think we can push a `LightsTestActivity` and use a single ticket for all requests.  It seems to work fine in https://github.com/koreader/koreader/issues/4551. (the epd counterpart).

I'll see if I get a couple of free hours to play with it

**Comment by zwim** [comment]
@DominikSchmidbauer Thank you for your feedback.
Is the rest working? Screen refresh? No ghosting? Coverimage (screensaver)?

@pazos The Vision 6 seems to use Android 8.1 (all the other Tolinos have 4.4). The tolino reading app seems to be the same except the version number 15.1.0 vs 14.2.0.
I have asked the Tolino company very politly for a test device, but they are not interrested. Period.
Sorry I won't be of any help here, as I will definitly not buy a Vision 6. I like the bigger screen of my Epos2.

To your suggestion not to have a  ticket for every device: +1 
Maybe we should have one pinned ticket for EPD and one for other device quirks?

**Comment by zwim** [comment]
@DominikSchmidbauer Just a suggestion if @pazos does not find a solution (I strongly believe he will!).

Your name sounds familiar to me. If you live in Tyrol ("Unterland"), we could meet in person. You could lend me your device for a few days and we get that.

**Comment by DominikSchmidbauer** [comment]
Today I checked again and suddenly the brightness controller was working.

The rest looks quite good so far, but I haven't checked the coverimage so far, it's just the standard tolino image.

@zwim Yes, indeed. How do you know me?

**Comment by zwim** [comment]
@DominikSchmidbauer : I don't know you personally, but an other Schmidbauer.

**Comment by pazos** [comment]
Test activity updated with both epd and light tests. We won't keep tickets opened for each one of the unsupported devices/drivers.

If somebody with the device wants to write a driver for it please follow instructions in https://github.com/koreader/koreader/issues/8482:

> If you want to do the port yourself and need help please open a new ticket in https://github.com/koreader/android-luajit-launcher/issues and attach the report saved on your device in /sdcard/test.log

**Comment by t-8ch** [comment]
I looked at my device and this is the data (With firmware 15.2.0, unrooted):

Manufacturer: rakuten kobo inc
Brand: rakutenkobo
Model: tolinovision 6
Device: e70p14_android
Product: e70p14_android
Platform: virgo

The existing driver does not work out of the box, because the backlight devices have different names and for Android APIs Koreader is missing the necessary settings permissions.
It is however possible to configure both brightness and temperature without root permissions via ADB shell.
The backlight devices are `mxc_msp430.0` for brightness and `lm3630a_led` for color.
I can submit a patch to the existing `TolinoWarmthController` or submit a new driver that only contains the necessary logic for this device. (Without the calls to the Android APIs, shelling out to chmod, etc)

**Comment by pazos** [comment]
> I can submit a patch to the existing TolinoWarmthController or submit a new driver that only contains the necessary logic for this device. (Without the calls to the Android APIs, shelling out to chmod, etc)

A new driver would be great.

> It is however possible to configure both brightness and temperature without root permissions via ADB shell.

ADB shell has different SELinux context than unprivilegied apps. You can do a lot of things on adb shell that you won't be able to do in user apps.

Hopefully you won't need to write to sysfs nodes directly and just find the call used by the Tolino app that does that and the arguments needed for that call. If they implemented it using a Settings wrapper you might need to get runtime permissions for `WRITE_SETTINGS`. 

If they **wanted** to avoid 3rd party apps to use that feature (and implemented it well) it won't be possible without root. AFAIK nobody cared about restricting it in the first place.

**Comment by pazos** [comment]
FWIW these are the permissions granted for the shell https://github.com/aosp-mirror/platform_frameworks_base/blob/master/packages/Shell/AndroidManifest.xml#L25

😭

**Comment by Frenzie** [comment]
Heh, are any missing? 🤣

**Comment by ChristophHeilmann** [comment]
I don't understand the problem here. The system settings for the frontlight are screen_brightness and screen_brightness_color. Only a runtime permission is needed to change these settings.

**Comment by pazos** [comment]
> I don't understand the problem here. The system settings for the frontlight are screen_brightness and screen_brightness_color. Only a runtime permission is needed to change these settings.

The problem is always the same. The maintainer (me) doesn't have the specific device and relies on actual users of the device to add support for it.

Add support doesn't mean write the code yourself but document how the stuff works on that specific device (which you just did) and the parameters used as min/max brightness/warmth.

Ofc writting yourself a new controller and testing how it works makes my job much easier.

In that specific case it's a bit harder: the light controller interface exposes a boolean method `requiresPermission` (or similar, Im talking from memory) but it's not wired to the frontlight widget behaviour, mainly because no current driver relies on a runtime permission.

But if you get a new driver that works fine once you granted `WRITE_SETTINGS` permission elsewhere I will be happy to wire the stuff together so the fronlight widget/gestures will prompt you on the first run.

**Comment by cl0rm** [comment]
Issue still persists. Device is shown as unknown in the compatibilty tester

**Comment by cl0rm** [comment]
I have done further research:
the Device `/sys/devices/platform/soc/twi1/i2c-1/1-0038/backlight/lm3630a_led` works for controlling both brightness on color temperature on mine (tolino vision 6, latest firmware, no root).

To change:
brightness: write to `/sys/devices/platform/soc/twi1/i2c-1/1-0038/backlight/lm3630a_led/brightness` (range 0 to 100)
ct: write to `/sys/devices/platform/soc/twi1/i2c-1/1-0038/backlight/lm3630a_led/color` (range 0 to 10)

There are also symlinks to this device somewhere, but I don't exactly know where. Probably better use those to access it.

Now someone needs to make a module. I am capable of writing C code, but I have no idea about Java or even worse Kotlin.

**Comment by t-8ch** [comment]
I looked into how the stock reader does it and it works exactly as described in https://github.com/koreader/android-luajit-launcher/issues/351#issuecomment-1239256234

Looking at the source of `/dev/ntx_io` showed that it won't be of any help.
