### ISSUE TITLE
Can't highlight multiple pages when double column on

### ISSUE THREAD

**Issue by abdoulayeYATERA** [koreader/koreader#8602]
* KOReader version: 2021.12-2
* Device: Kobo forma

#### Issue
Can't highlight multiple pages when double column is on, next page not showing when highlight reaches bottom right.
Sometimes works for first page, but never goes beyond that.
#### Steps to reproduce
- Enable  double column
- Try to highlight multiple pages in one time.

**Comment by poire-z** [comment]
It's a current limitation and hard to solve:
https://github.com/koreader/koreader/blob/dd07112de7f8ac6048e6dc4306a169b1eddbf0d1/frontend/apps/reader/modules/readerhighlight.lua#L994-L999

But there is now an alternative for multi page selection since #8432: select start, the turn pages, the select end.

**Comment by abdoulayeYATERA** [comment]
Ok thanks poire !
I had auto long click to highlight that's why i did not notice that possibility.
Switched that to "Select and highlight".
Working great !
Thanks.
