### ISSUE TITLE
FR: saving highlights/notes directly in a sqlite db

### ISSUE THREAD

**Issue by Edo78** [koreader/koreader#8634]
**Does your feature request involve difficulty completing a task? Please describe.**
As far as I understand the current flow highlights are saved in a file eg `metadata.epub.lua`
Searching through all the notes from multiple books right now is tedious at best, even after exporting them (with multiple issues in the various type of exports.

**Describe the solution you'd like**
Saving highlights/notes directly in a sqlite db can create a single source of truth easily searchable through sql and having a sqlite db let third party devs play easily with data without having to create a plugin in lua

**Comment by poire-z** [comment]
> As far as I understand the current flow highlights are saved in a file eg metadata.epub.lua

And we like it that way :)
This was discussed some years ago, and you can read my opinions, and why it's good to have it that way at https://github.com/koreader/koreader/issues/4951#issuecomment-486960267. (The source of truth flies with the document, instead of being burried in a monolithic DB :)

A solution to your wish, that would not require us to rewrite anything, could be a plugin (that only people interested would activate) that has a single event listener `:onCloseDocument()` or `:onFlushSettings()`, and in it, save/update the highlights for the current book into a sqlite db of your prefered format. (The book key could be a hash, or a path, but you'd have to listen for events for filename moved/renamed/deleted that we may not send yet.)

**Comment by Edo78** [comment]
> This was discussed some years ago, and you can read my opinions, and why it's good to have it that way at #4951 (comment).

Thanks for pointing them out. I'm really new to koreader (I just received my kobo 3 days ago) so I'm not familiar at all with all the internal flows and this may explain why I disagree with some of your points but I'm not here to try to change your mind on that (not untile I learn how things actually works :wink: )

English isn't my first language so it may be that I need to rephrase my request. I'm not asking you to change everything, just to insert/update a record in a sqlite db when you already add/edit notes to the lua file.

> The source of truth flies with the document, instead of being burried in a monolithic DB

Then my issue is that the source of truth is sometimes ignored (as I reported in #8633 when the author isn't obtained from the metadata but from parsing the title).

> could be a plugin (that only people interested would activate) that has a single event listener :onCloseDocument() or :onFlushSettings(), and in it, save/update the highlights for the current book into a sqlite db of your prefered format

I'll try to learn something about those events and see what can I do. Thank you very much

**Comment by Frenzie** [comment]
> Then my issue is that the source of truth is sometimes ignored

It doesn't so much ignore it as predate it.

**Comment by Edo78** [comment]
> It doesn't so much ignore it as predate it.

Are there other flows that predate the source of truth?

**Comment by poire-z** [comment]
> Then my issue is that the source of truth is sometimes ignored (as I reported in #8633 when the author isn't obtained from the metadata but from parsing the title).

Well, that's a bug in this exporter plugin, that nobody has really cared about for years: it has access to the metadata.epub.lua, where highlights are stored - and so are the book metadata's authors and title (which might still be wrong if the metadata is wrong), so it could pick them from here.

> could be a plugin (that only people interested would activate) that has a single event listener :onCloseDocument() or :onFlushSettings(), and in it, save/update the highlights for the current book into a sqlite db of your prefered format

Just remembered :/ that I added some other events just some days ago, that could be used just for that:
https://github.com/koreader/koreader/commit/bc16b323950ccf8292d213ab17e1a6a900588836#diff-489ecdf0fa00063ecc5dff3753350c106ec18c86d056b4655f6bf12b7f96f283R843
that would make this process even simpler (individual updates when they happen - instead of full delete and insert always, if done only at book close time).

> English isn't my first language so it may be that I need to rephrase my request. I'm not asking you to change everything, just to insert/update a record in a sqlite db when you already add/edit notes to the lua file.

No worry :) I was just hinting the 2 extreme solutions, to highlight that the 2nd is the easiest: _insert/update a record in a sqlite db when you already add/edit notes to the lua file._ which is exactly what we could do with a plugin handling these events, having zero impact on the core code.

**Comment by Edo78** [comment]
Do you have some docs for onboarding developers willing to help?
To me highlights and notes are really important and I'm willing to help the project.

**Comment by Frenzie** [comment]
We have <http://koreader.rocks/doc/>, <https://github.com/koreader/koreader/blob/master/doc/Building.md> and the like, and you can talk with @dgarrett (and the rest of us) on [Gitter](https://gitter.im/koreader/koreader).

**Comment by Edo78** [comment]
> We have http://koreader.rocks/doc/, https://github.com/koreader/koreader/blob/master/doc/Building.md and the like, and you can talk with @dgarrett (and the rest of us) on [Gitter](https://gitter.im/koreader/koreader).

Thank you very much
