### ISSUE TITLE
Malfunction in highlight type change in pdf files

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8663]
* KOReader version: v2021.12.1-41
* Device: PB 628

#### Issue
In a pdf file, when we change the highlight type from Underline to Lighten or Invert, a line remains under the text. And when we change the type from Lighten to Underline, a shadow remains, while the text is underlined.

Is it possible to fix this problem?
Thanks!

**Comment by hius07** [comment]
I managed to make screenshots back then, but now on 2022.01 cannot reproduce, so cannot investigate it, sorry.

![1](https://user-images.githubusercontent.com/62179190/149779643-d8be7e07-d11c-48d0-af7f-609e33bbf9f6.png)

![2](https://user-images.githubusercontent.com/62179190/149779660-cdbfc642-7c66-42bb-83ba-0161503c3c24.png)

**Comment by poire-z** [comment]
Might be only when "save highlights into document" is enabled.
The highlight style at creation time that is written into the PDF seems to not be updated when we change highlight style in frontend. At least, I see nothing available in base/ffi/mupdf.lua and nothing specifically being done in editHighlightStyle() or pdfdocument.lua.
ffi stuff is complicated, dunno if it could just be a matter of delete the annotation with the old style and add it again with the new style.
(Previously related nightmare: #7928 :)

**Comment by ichnilatis-gr** [comment]
> I managed to make screenshots back then, but now on 2022.01 cannot reproduce, so cannot investigate it, sorry.
> 
> ![1](https://user-images.githubusercontent.com/62179190/149779643-d8be7e07-d11c-48d0-af7f-609e33bbf9f6.png)
> 
> ![2](https://user-images.githubusercontent.com/62179190/149779660-cdbfc642-7c66-42bb-83ba-0161503c3c24.png)

I can see a line under the second quote while it is highlighted, and in the first one there are two lines. Isn't that so?

**Comment by poire-z** [comment]
It **writes** the highlights you make in KOReader **into** the PDF file itself - so that when you copy the PDF on your PC or your phone, or send it to a buddy via mail, you can see these highlights without needing KOReader.

It is a nice feature, but it's complicated because there are 2 "databases" of highlights: the ones in KOReader metatadata.pdf.lua - and the ones in the PDF itself. It's hard to keep them in sync (ie. the bug you discover: we change the highlight style on the KOReader side, but not in the PDF itself), there is the double drawing (MuPDF draws the one inside the PDF, KOReader draws its own over, so the double different drawing, not the same underline position, etc... you notice in this issue) - and there is the fact that they could already be some highlights in the PDF, made elsewhere, that you can't update/delete from KOReader).

So, if you don't need this feature, best to disable it: you'll like in KOReader's highlights world only, where things are a bit more robust and tested.

**Comment by ichnilatis-gr** [comment]
The main reason I disabled it is the thought that it would be easier for KOReader to open a big book with lots of highlights. Isn't it? Nevertheless, maybe sometimes this feature is useful.
Thank you for your idea!
