### ISSUE TITLE
Ordered lists rendering without dots

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#8668]
* KOReader version: 2021.12.1-56

Ordered lists such as the one below are rendering as `1 First` instead of `1. First`. I have run tests on a fresh installation of KOReader for both epub and html files.

```html
<ol>
    <li>First</li>
    <li>Second</li>
    <li>Third</li>
</ol>
```

**Comment by poire-z** [comment]
It has been proposed and merged in upstream CoolReader, but I haven't picked it for KOReader.
Discussed in https://github.com/buggins/coolreader/pull/226.
My summary for our side at https://github.com/koreader/crengine/pull/411:
> Considered but not (yet) picked:
`(Upstream) Ordered list markers: add a decimal point suffix`
Because it feels ugly in Wikipedia EPUBs where in-page footnotes are such OL>LI (which are probably the use of the OL>LI I see every day :)
It would need either them to be right aligned (but still a bit ugly), or having such markers use font-variant: tabular-nums (which we can't set on LI markers only via CSS) so digts have a constant width and these decimal points would be aligned with each others (if the font supports that, which is not the case for most).

You're only the 2nd person mentionning that, and quite late since you've been using KOReader. In which context did you realized you missed them ? 
(My personnal feel is that I don't want them in Wikipedia EPUB footnotes, but we don't have enough support for other CSS properties to be able to customize list items and add/remove the dot or left/right aligned them, otherwise I would have just customized them in Wikipedia EPUBs...)

**Comment by Frenzie** [comment]
The initial value does seem to be defined with a . as a suffix.

https://drafts.csswg.org/css-counter-styles/#counter-style-suffix

But technically that only means it should do that if the stylesheet
specified initial as a value, not that we should agree with it otherwise in
our default stylesheet.

**Comment by gbyl** [comment]
> In which context did you realized you missed them ?

I only noticed the lack of dots recently working through a book that had many ordered lists. The standard seems to be the addition of the dot, so I thought I would report it.

**Comment by poire-z** [comment]
> recently working through a book that had many ordered lists

Were these ordered list "list-style-position: inside" ![image](https://user-images.githubusercontent.com/24273478/149635450-4dcd8d84-350a-4da8-9c60-df4c29cd1675.png) or "outside" ![image](https://user-images.githubusercontent.com/24273478/149635480-3443669d-134a-4eae-855f-d43fd6e016d5.png) ?

I get that when "inside", the absence of a dot can make it harder to read :/

And I guess we have a bug with "inside"... Spacing ok with Kerning "fast" or "good", but lost with Kerning "best":
![image](https://user-images.githubusercontent.com/24273478/149636226-2e84a1fa-c33d-4bac-a2fb-6e04f23caed5.png)


Browsers also align it towards the text, and would render it like the following:
![image](https://user-images.githubusercontent.com/24273478/149635561-a6420569-8878-4695-971d-d098529a5bba.png) I can't bear this misalignment of numbers :/

A trick would to use font-variant: tabular-nums, but all fonts don't support it, and I think we can't just use it for the list item marker, so it would apply to the content too (and numbers in content then feels too wide...):
![image](https://user-images.githubusercontent.com/24273478/149635643-14075ee3-3948-4a3e-a231-5171739295d3.png)

Some other screenshots of how we do currently (left aligned), and how we would do it with a dot but still left aligned in https://github.com/buggins/coolreader/pull/226 .

(I could hack another `-cr-hint: list-item-alt-style` to restore our current behaviour for Wikipedia EPUBs if I can't get over it - and otherwise do just as browsers do.)

But how do people feel about the browsers look vs our current one, vs the variations in these screenshots above ? Am I just being peculiar ? :)

**Comment by Frenzie** [comment]
With dots seems to be a touch more common but both are fine as long as we're talking about "outside".

**Comment by gbyl** [comment]
>Were these ordered list "list-style-position: inside"
>I get that when "inside", the absence of a dot can make it harder to read :/

Good catch! Yes, all lists were `list-style-position: inside`. I couldn't put my finger on exactly why it felt so off, but that is why.

>With dots seems to be a touch more common but both are fine as long as we're talking about "outside".

Yes, the strongest argument for adding the dot is that it is the standard everywhere else. But I also understand @poire-z point. Is there a way to somehow make the dots the default, but also add a style tweak option for users who prefer the dotless option?

**Comment by poire-z** [comment]
I guess I would not mind the dot if they were aligning.
I managed to hack to use the equivalent of "font-variant: tabular-nums" for the marker only, which, when right aligned (as browsers) would give:

![image](https://user-images.githubusercontent.com/24273478/149672076-e6ff9449-535d-4af5-b8d3-7c46121d196a.png) ![image](https://user-images.githubusercontent.com/24273478/149672092-1dd52555-eab9-4309-a550-67b0b938fc78.png)

Does it feel OK to have "wide" digits on the left, and "normal" digits on the text on the right? It looks like these are different fonts (but it's the same, with just alternative digit glyphs).

This would work only in Kerning mode "best" and when the font has such features (around 50% of them has, our most prefered have it I hope, mine do :) - or when it has such digits as their default (30-50% of those I tried have fixed width digits).
With kerning mode "fast" or "good", we'd get these ugly (but I get that with Firefox on Wikipedia pages...):

![image](https://user-images.githubusercontent.com/24273478/149672209-e58f8557-92d3-4a88-847c-409ec8a75f22.png) ![image](https://user-images.githubusercontent.com/24273478/149672190-a1124e0c-998c-4fbc-9662-99cb57a7aa7d.png)

Do some of you share my preference for the first set, or does it feel odd ? Wondering if it's worth the added (small) complexity. 
(It would be for all decimal list items, not just Wikipedia footnotes.)

**Comment by Frenzie** [comment]
I agree the top definitely looks better in this context.

**Comment by poire-z** [comment]
But right aligned, there is now the thing that for the first footnotes with 1 or 2 digits, when later ones have 3 digits, there is a feeling of wrong/excessive left padding when shows as footnotes:
![image](https://user-images.githubusercontent.com/24273478/149775550-2a149b8d-8526-43a5-aa2b-dc2b323c33f9.png)

So, I think that if I fix normal list items, I still need to add:
```
list-style-position: -cr-outside
list-style-position: -cr-outside-out
list-style-position: -cr-really-outside
```
(Can it be just named `-cr-outside` (meaning: some specific/legacy way of crengine to handle outside) ? or is that naively expected to predate and be equivalent to `outside` ?)

**Comment by Frenzie** [comment]
Prefixed is definitely not expected to be the same, but it would probably be a tad deceptive to some random person.

**Comment by poire-z** [comment]
OK, did some improvement to list markers.
One last request for taste and opinion:

When `list-style-position:outside`, I'm using a EN-SPACE after the dot - because using a space mostly always have the separation too small (and fonts can size their space quite differently, so this layout spacing could vary a lot between fonts) - and it gets similar to what we had before:

![image](https://user-images.githubusercontent.com/24273478/150013126-ee83a3e3-5b9b-4d74-bb3b-1bd59b894971.png) ![image](https://user-images.githubusercontent.com/24273478/150013186-069fa3ca-f3ed-48ac-88bd-7f3dd6c70ce3.png)

When `list-style-position:inside`, I wonder if I can still use EN-SPACE (so, making the first space of the now fully inline marker+sentence larger than the others), or if it's more expected that we use a space, so the `123.` actually looks like it was just the first word of the sentence. Using a larger EN-SPACE could help noticing it's a start of a list item when things get busy and there is no last short line helping noticing next comes a new list paragraph.

With EN-SPACE:
![image](https://user-images.githubusercontent.com/24273478/150013737-05e94e9f-618c-4430-81b2-23268636fd6a.png) ![image](https://user-images.githubusercontent.com/24273478/150013675-9e7ff3bc-63c7-4de2-9336-0b9f60944b0d.png)

With regular space:
![image](https://user-images.githubusercontent.com/24273478/150013961-31faf8ed-db4f-4bd5-904b-478933a4719d.png) ![image](https://user-images.githubusercontent.com/24273478/150014046-145210c3-e596-4024-b0e7-9eb17beb3522.png)

(The disc/circles come from FreeSans whatever the font is, and these glyphs have short left/right spacing, so I could consider keeping EN-space for them if you feel like I do that on the last left screenshots, they are too near the text.)

Thoughts?

**Comment by Frenzie** [comment]
Both seem fine to me. Can it still be controlled a bit as a style tweak with padding-left on the LI?

**Comment by poire-z** [comment]
padding-left controls the indentation of the whole thing, we can tweak that (although we don't do exactly as browsers: with no padding, they render outside the view - we don't).

But that wasn't my question, which was about these spacings, which are not tunable (neither in browsers):
![image](https://user-images.githubusercontent.com/24273478/150024135-9ca7698f-fad4-4d72-a390-ec79387728b0.png)

**Comment by Frenzie** [comment]
Sorry, I meant text-indent, not padding-left. (There are other tricks, but that's the easiest.) padding-left would be on the UL/OL.

As I said both are fine, en-space is probably a touch nicer, but ideally text-indent would also work. :-)

**Comment by poire-z** [comment]
Looks like browsers apply text-indent set on either the OL or the LI before the number/bullet, so it just pushes it all to the right, and does not impact the spacing between the number and the text.
Other tricks would be to use the counter/suffix stuff you mentionned and add more spaces to the suffix - but we don't support that.
Anyway, I'll go with ENSPACE for bullets outside & inside, with ENSPACE for numbers with outside, and regular space for numbers with inside.
(Because most real in-page footnotes don't bother with making it easier to catch with more space after the number: they just use a single regular space: `43) blah blah`.)

**Comment by Frenzie** [comment]
> Looks like browsers apply text-indent set on either the OL or the LI before the number/bullet, so it just pushes it all to the right, and does not impact the spacing between the number and the text.

Negative! ;-)

**Comment by Frenzie** [comment]
Like so:
```
<ol>
<li style="list-style-position: inside; text-indent: -5px;">Some text.
```

**Comment by poire-z** [comment]
Still just pushes the whole number+text into the left padding :)
![image](https://user-images.githubusercontent.com/24273478/150101545-112f8a82-9b8e-4fbd-a435-37572b6be9e1.png)

**Comment by Frenzie** [comment]
I must be misremembering the specific mid-2000s hack. More dependably you'd use additional elements in any case.
