### ISSUE TITLE
FR: Favorites Menu accessible with a gesture

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#8701]
**VERY SHORT SUMMARY:**
KOReader's gesture system is powerful but after some number of gestures it can get overwhelming. 
It needs a visual complimentary system, especially for new users.

**CONTEXT:**
I currently have these gestures defined:
- File manager
- Favorites
- History
- Show Bookmarks
- Show ToC
- Show Book map (new !)
- Toggle backlight
- Increase font size
- Decrease font size
- Next chapter
- Rotate screen
- Sleep
- Restart KOReader

I would add a few more but it becomes confusing (What was decrease font ? LEFT-DOWN or DOWN-LEFT ?)

**SOLUTION PROPOSAL:**
I am a Blender user (an open source 3D suite). 
It has a complex user interface and menu system.

**Its cheat sheet looks something like this:**
![blender-infographic-SM-1280](https://user-images.githubusercontent.com/84420582/150601976-945a1dc1-5f17-40c4-a4e6-4f75aa0b82a1.png)

But it has a very handy feature to deal with this complexity:
![Captura-de-pantalla-2020-02-20-07 02 59](https://user-images.githubusercontent.com/84420582/150602060-0d077cf3-2a06-44e4-9f7e-ab88af345758.jpg)

This is the `Quick Favorites` menu which shows up when you press Q. When Blender is first installed, this menu is empty.
Users can right click anything on the interface (menu, radio button, toggle etc.) and select "Add to Quick Favorites".
So users can populate this menu according to their usage patterns and reach it with a single key press.

**My proposal is:**
We can have a `Favorites` menu (in the reader view, like long-press menu) which is accessible with a gesture.
It can be populated with items already in the Gesture Manager.

This will:
- Allow single gesture access to several personalized items
- Save users from memorizing increasing number of gestures
- Won't clutter user interface with additional menus or toolbars

**What do you think ?**

**Comment by solarkite** [comment]
This is a great idea. I’m actually reluctant to make or modify too many gestures as it would get overwhelming. It’s relevant and applicable to the FR I made for a user defined “Quick View” menu. https://github.com/koreader/koreader/issues/8653#issue-1099422909

**Comment by offset-torque** [comment]
Thank you @solarkite, I just read your FR. Our motivation is the same as it seems. Actually your proposal was the first solution that came to my mind long time ago. But I didn't open a FR because it requires modifying main menu which comes with lots of discussions and friction as I witnessed in other issues (understandably).

And I think this one is easier for us (users) too. Navigating menus is not a pleasant experience on e-ink screens. With my method a flick of a finger (like swipe up, down, short swipe) is enough. No need to drop down the main menu, change tab, click sub menu item etc. It can be mapped to a button even (probably).

Also my proposal might piggyback on the Gesture Manager functionality so it might be quicker/easier to implement/maintain. But I am not a programmer so this might not be true.

**Comment by poire-z** [comment]
Probably an easier solution - if it pleases @solarkite - than his #8653 (moving/duplicating menu items around would be too complicated /kludgy / risky).
But it's limited to the menu items that do some actions and that can be associated to a gesture: no way to move in here the Font> menu or the Style tweaks>Pages> submenus.

Only having the Gesture Manager plugin propose and handle a new action showing the other actions that are associated feels a lot easier and simple.
It could even show the associated gesture on the right of the action name `History: ←↑→↓ `, so you learn while you use it and end up no longer needing it :)

**Comment by solarkite** [comment]
> Probably an easier solution - if it pleases @solarkite - than his #8653 (moving/duplicating menu items around would be too complicated /kludgy / risky). But it's limited to the menu items that do some actions and that can be associated to a gesture: no way to move in here the Font> menu or the Style tweaks>Pages> submenus.
> 
> Only having the Gesture Manager plugin propose and handle a new action showing the other actions that are associated feels a lot easier and simple. It could even show the associated gesture on the right of the action name `History: ←↑→↓ `, so you learn while you use it and end up no longer needing it :)

I don’t think of it as my suggestion. This is a collaboration of ideas. We are all developing  strongly similar ideas. The post I referred to was not asking to move or duplicate menu options. Rather a menu of options that point to the function. Important work has already been achieved with dispatcher to make this happen.  These options could also be listed with a “gesture function map” like you propose, combining @offset-torques proposal. I’m just following a line of thought that might empower users.
Anyway. My intent wasn’t to high jack @offset-torques suggestion. I just thought it would meld well with what I submitted.

**Comment by hius07** [comment]
Also https://github.com/koreader/koreader/issues/7788.

**Comment by ersi-dnd** [comment]
For me, the "Go to page" widget is a good starting point for a personal Favorites menu. It's nice to see the buttons there that already exist, namely Skim and % and Go to and Cancel, but at the same time in the same spot I am missing the following:
- TOC
- Bookmarks
- File Browser
- also the new awesome Page browser

Frankly, perhaps it would make sense to give users the ability to add any button they like, perhaps by having a small wrench button in the bottom right corner of the widget and the wrench button would open a huge list of available buttons the same way as the Gesture manager opens up a huge list of available gesture actions. And why not expose the small wrench button in every possible widget?

As to the Cancel button in the Go to page widget, I think it would make sense to be able to cancel all less-than-fullscreen popups by tapping anywhere outside of them. Go to page widget does not seem to work this way right now. 

(There is also a list of options to End of book action. I think the list should be much longer than it is, perhaps even the same list as in Gesture manager.)

Hopefully I am sensibly adding to the ongoing discussion. What I'm a bit worried about in these discussions is the increasing inconsistency in Koreader's interface. E.g. History and File browser are similar-looking whole-page things, but they do not behave the same way - you can access the top and bottom menus in the File browser, but not in History. The newly added Page browser and Book map add to the potentially confusing behaviour of fullscreen things. 

At some point someone should give some thought to the consistency: What makes sense as a floating widget, what as a fullscreen thing, and how to access the familiar top and bottom menus/widgets from any screen situation.

**Comment by hius07** [comment]
> Go to page widget does not seem to work this way right now.

Because tapping outside of it hides the keyboard (a good useful feature).

**Comment by poire-z** [comment]
> For me, the "Go to page" widget is a good starting point for a personal Favorites menu. 

You might think that because it has a few other buttons - but if we're making an action shortcut dialog/widget, I may not care about seeing a input field and "Go to page" :)
It's easier to create a new dedicated widget with buttons for actions.

> Frankly, perhaps it would make sense to give users the ability to add any button they like, perhaps by having a small wrench button in the bottom right corner of the widget and the wrench button would open a huge list of available buttons the same way as the Gesture manager opens up a huge list of available gesture actions. And why not expose the small wrench button in every possible widget?

Because that's very complicated :) and would add visual noise to every widget for people who may not care.

I think the idea of just having a gesture launching a dedicated widget (with no Go to input field and no wrench icon) in any context is just as fine, simpler, cleaner, less risky.
And populating with the existing gesture/actions as an initial implementation could be enough (later, if someone cares, it could be a add/sort widget (like for footer items) to make the list distinct, but that's much much work).

> Hopefully I am sensibly adding to the ongoing discussion. What I'm a bit worried about in these discussions is the increasing inconsistency in Koreader's interface. E.g. History and File browser are similar-looking whole-page things, but they do not behave the same way - you can access the top and bottom menus in the File browser, but not in History. The newly added Page browser and Book map add to the potentially confusing behaviour of fullscreen things.
At some point someone should give some thought to the consistency: What makes sense as a floating widget, what as a fullscreen thing, and how to access the familiar top and bottom menus/widgets from any screen situation.

It's not perfect, but many choices are tied to how things are/were coded. And updating all that for the consistency you wish for would be hard and risky work.
To make it clearer to you, and allow you to understand (and accept :) these ties:

- Reader and File browsers are "apps": they are the main content, they have a top menu.
- Other full screen widgets (History, ToC...) are not "apps", but just full screen widgets, displayed over the "app" they were launched from: they _can not_ have a top menu. They get a close/cross icon at top right (that "apps" do not).
- Other widgets are non full screen (and they may or not have a close/cross icon). Most are closable by tap outside. Those that have a text field are not as tap outside is useful to close the keyboard and see more of it.

**Comment by offset-torque** [comment]
@ersi-dnd 

**My 2 cents:** I think KOReader interface should stay as minimalist as possible. We have limited screen space, no color to differentiate between items and limited contrast ratio. Also we don't have visual helpers like drop shadows, blurred backgrounds to isolate front dialogs and no colorful icons. So we have to be careful about overloading UI.

> For me, the "Go to page" widget is a good starting point for a personal Favorites menu.

As a counter-point, I never ever use Skim Widget. We all have different usage patterns and that's OK. For example I make hundreds of highlights, other users might never highlight a thing. On the other hand I never add notes but there are heavy note takers. That's why we shouldn't limit Favorites menu to a specific part of UI/menu/widget.

Despite all differences, everyone using KOReader has a common point where they spend 99.99 percent of their time: **Reader view**.
My proposal is in fact just a **"customizable right-click menu"** for Reader view.

---

Here is a mock-up of what I imagined. Just a simple list of items. No buttons. No icons. Even with this large text, 15 items can comfortably fit on the screen. Just a flick of finger. No learning curve because user put them there so menu has a familiar logic.
![kobo favorites](https://user-images.githubusercontent.com/84420582/150638816-eaabdc23-62c4-4403-b5cf-777c851f26e9.png)

**Comment by solarkite** [comment]
> "customizable right-click menu"

I like the idea. I see where you are coming from. However, I’m not sure I could perform something like a right click on a kindle.

**Comment by poire-z** [comment]
> However, I’m not sure I could perform something like a right click on a kindle.

"right click" was just to relate that to how we do on computers I think. The idea with our gesture manager is that you could associate this to any gesture you prefer (long press in bottom right corder, swipe up+down, double tap...)

Had a quick try (25 lines of code) at building a widget from my gestures (using existing ButtonDialog, so the font is huge):
![image](https://user-images.githubusercontent.com/24273478/150640785-848f1815-3972-48cc-b1b8-3e85ca423cf3.png)

Even with a smaller font size, it would feel quite crowded... as there are many existing gestures that are somehow needed and we would rather not have the user to get rid of to get a widget there with a lot less buttons.
So, may be it's not a good idea to re-use existings gestures (that was the easy and fun idea) - and we should go towards a dedicated list of actions orthogonal to gestures (and building this select/add/order widget is quite a lot less fun and easy :/)

**Comment by solarkite** [comment]
> menu has a familiar logic.

@Frenzie suggested rightly that this functionality exists in profiles now https://github.com/koreader/koreader/pull/2601#issuecomment-1008371938
Perhaps part of the solution would be to elevate profiles or include profiles in a new main favorites menu option.

**Comment by hius07** [comment]
> building this select/add/order widget

It might be a new submenu `Quick menu` in the `Gesture manager` menu, we have already built list of actions in categories, with checkboxes.

**Comment by solarkite** [comment]
> Here is a mock-up

I think an easy way to meet your needs that comes close to you mock-up is to add a gesture option (@poire-z ‘s suggestion) that calls up the profiles menu. From there you could select from the user created options there.

**Comment by solarkite** [comment]
> > building this select/add/order widget
> 
> It might be a new submenu `Quick menu` in the `Gesture manager` menu, we have already built list of actions in categories, with checkboxes.

I was just thinking similarly :)

**Comment by hius07** [comment]
Profiles, yes, forgot about it.

**Comment by offset-torque** [comment]
@solarkite 

> I think an easy way to meet your needs that comes close to you mock-up is to add a gesture option (@poire-z ‘s suggestion) that calls up the profiles menu. From there you could select from the user created options there.

I really don't understand how Profiles can replace an on-screen quick access menu. Or am I missing something ?
Profiles are basically "a trigger for multiple actions" like a BASH script if I understood correctly. I can't be sure since there is no documentation, its wiki page just points to PR's.

**I want to clarify my intention:**

Aim of my proposed menu is giving users ability to perform their chosen actions
**1. Without diving into main menu**
**2. Without drawing complex shapes on the screen**

**1. Without diving into menu system**
If I have to go into the menu system for my `Favorite Menu` it means I already made two gestures
- One swipe to open `Top Bar`
- One tap to switch to tab containing `Favorite Menu`
- And one more tap on `Favorite Menu` to open its sub-menu that contain my selected actions.
- And one more tap on the action itself.

With 4 taps I can already reach anything on the main menu.
Why waste dev effort to create another menu which takes equal effort and time to reach as the original menus.

**2. Without drawing complex shapes on the screen like a Konami Code**
![konami code](https://user-images.githubusercontent.com/84420582/150644073-40b33db5-051b-4f66-8022-e6b2c7215c0f.jpg)
Easy gestures for frequently used items are perfect. Problem is infrequent actions like **Restart KOReader** which I might need after opening very large PDF's. I can define a longer multi-swipe (because shorter ones are already in use by more frequent actions) but when I need it next time I will already have forgotten or mix up the gesture combination. This puts a usability threshold on gestures depending on usage frequency/complexity.

To give an example from Blender, with the **Quick Favorites** menu, even a novice can be as fast as an expert (even faster) because expert has to press `Shift+Ctrl+Alt+S` + `Shift+Ctrl+Alt+G` while novice can do `Q+Click+Click` without even memorizing anything.

And as a side note, I am not proposing this (just) for myself. New users can struggle with setting and remembering all those gestures. Mobility limited users may have problem drawing complex swipes or double-taps. Giving them a menu with a simple swipe is the least we can do for usability.

**Comment by poire-z** [comment]
Profiles are mostly for combining multiple settings into a single action.
I'd rather not have a user have to create a profile with the single "History" action to be able to get that in a shortcut action widget :)

Most of the action stuff is in Dispatcher. Profiles and GesturesManager use Dispatcher to get that list (their name and what they do), so this other "action shortcuts" thingy could use Dispatcher and not depend on the others.
It would registers its onShowShorcutsMenu even handler into Dispatcher though, so it's available to be associated to a gesture (and a profile ! we're so flexible :)
So, logically, to keep that flexibility and make this new "favorite actions menu" standalone, simple and combinable, it should be made into its own plugin, actionshortcuts.koplugin.

> So, may be it's not a good idea to re-use existings gestures (that was the easy and fun idea) - and we should go towards a dedicated list of actions orthogonal to gestures 

But with that, it wouldn't be a learning tool to your gestures :/ you'd go use this new stuff because it's easier than learning/remembering your gestures - and you would never get to learn/remember gestures, which are so much easier and natural once you get used to them.

**Comment by solarkite** [comment]
> "action shortcuts”

I think you have a great idea to make an "action shortcuts“ that takes advantage of dispatcher.

**Comment by poire-z** [comment]
Yes, we have the nice submenus in Gesture Manager, organized by thematic.
But if we were to have this new thingy, and people having to select these actions for additions AND then sort them (unless we're fine with alphabetical sorting like on my screenshot above?), we'd have 3 options:
- use something like these submenu to select them (and alphabetical sorting)
- use something like these submenu to select them, and then a SortWidget (like footer items or dictionary selection) to sort them after selection
- use only the SortWidget and put all actions as a flat list in it (so, 23 pages of items :)

How do you imagine that part of the setup workflow ?

**Comment by offset-torque** [comment]
I share your fondness for gestures @poire-z. I love gestures. I am using them on my desktop (drawing with my right mouse button), in my browser, on my phone (things like double-finger up swipe to raise volume when screen is off), my tablet.

> But with that, it wouldn't be a learning tool to your gestures :/ you'd go use this new stuff because it's easier than learning/remembering your gestures - and you would never get to learn/remember gestures, which are so much easier and natural once you get used to them.

I don't think this will be the outcome. Even as the person opening this issue, I will still use gestures for many actions even if this feature is implemented because as you said **they are easier and more natural**. I think most users will use simpler gestures for daily usage and choose to use this menu to replace more complex/infrequent gestures.

**Comment by hius07** [comment]
> * use something like these submenu to select them, and then a SortWidget

👍

**Comment by solarkite** [comment]
> I really don't understand how Profiles can replace an on-screen quick access menu.

My suggestion was to activate the profiles menu with a gesture (that still needs to be built into Gestures) to pop up in an instant rather than tap through multiple menus to get there. Quick call up of user made choices in one gesture.

**Comment by ersi-dnd** [comment]
In contrast, I do not like gestures much. They work unreliably everywhere outside the Reader/Filebrowser (which is why I would like to get access to the main menus from anywhere in the app). For me it would make logical sense to combine things that are similar, e.g. Page browser is really Skim with previews; History is really a virtual file folder; Bookmarks are additional access points to Table of Contents etc. but I understand that due to earlier design choices these things may be hard to implement.

But I'm perfectly fine with a focused customisable menu, accessible with the same gesture from anywhere in the app. I have been very much missing this kind of access for the main menus, so hopefully it will work for the new customisable menu. I know I can trust whatever you will come up with.

**Comment by yparitcher** [comment]
> Most of the action stuff is in Dispatcher. Profiles and GesturesManager use Dispatcher to get that list (their name and what they do), so this other "action shortcuts" thingy could use Dispatcher and not depend on the others.
> It would registers its onShowShorcutsMenu even handler into Dispatcher though, so it's available to be associated to a gesture (and a profile ! we're so flexible :)
> So, logically, to keep that flexibility and make this new "favorite actions menu" standalone, simple and combinable, it should be made into its own plugin, actionshortcuts.koplugin.

This is why I made Dispatcher :)

So that everyone can make plugins to easily execute actions.
It would be relatively trivial to make a `actionshortcuts.koplugin` (modeled on profiles) that in stead of being a list in a menu are a list in a shortcut widget that can be called by a gesture

**Comment by yparitcher** [comment]
See #8713 for a trivial implementation based on dispatcher

**Comment by hius07** [comment]
Based on the draft by @yparitcher and @poire-z from https://github.com/koreader/koreader/pull/8713.

QuickMenu is a part of the Profile, no separate plugin.

List of profiles:
![01](https://user-images.githubusercontent.com/62179190/190692724-904fd5e4-eb31-44d8-adc9-d9100a32fdf9.png)

Long-press executes the profile actions (customizable). Tap opens profile's commands and settings.
![02](https://user-images.githubusercontent.com/62179190/190692896-f56e2bed-e82e-4d7b-b170-e9c6b96cd49c.png)

Execute: executes profile's actions (in the order, if sorted).
Show as QuickMenu on long-press: if checkbox is set, long-press on the profile in the profile list shows QuickMenu instead of execution.

Edit actions: opens usual Dispatcher list of actions.
![03](https://user-images.githubusercontent.com/62179190/190693522-61fea83f-6e2f-4012-ada4-7843abcc2714.png)

There are entries for Profiles execute and show menu 
![04](https://user-images.githubusercontent.com/62179190/190693610-74e1ecd8-1050-44e5-ae29-f68d05d0530d.png)

Sort actions
For sorted profiles the checkbox is set. Long-press resets sorting and clears the checkbox.
![05](https://user-images.githubusercontent.com/62179190/190693650-aa3e37ec-df70-49af-bde9-7df8d46629c6.png)

Rename profile
![06](https://user-images.githubusercontent.com/62179190/190693725-c2faaf56-9ffc-417d-8021-bd7be2c6acf5.png)

Profile QuickMenu (called via profiles menu or with a gesture)
![07](https://user-images.githubusercontent.com/62179190/190693888-1ca6ea2d-ba6b-47ba-a674-ee8c97f1cfb2.png)

Tried to make QuickMenu to look like the main touchmenu, not like usual buttondialogs.

**Comment by poire-z** [comment]
Looks neat and comprehensive !

**Comment by offset-torque** [comment]
Wow, that looks exactly like what I was proposing.
Reusing the **Profiles** plugin is clever.
Usual dispatcher is cool too, people will be instantly familiar with the system.

I was already adding a **Profiles** section to the **User Guide**.
I will expand that to include this **QuickMenu** too.

Thank you all for your ideas and extra thanks to **hius07** for implementing this 🙏
