### ISSUE TITLE
The splash screen on android is still white when night mode is enabled

### ISSUE THREAD

**Issue by hollow-owl** [koreader/koreader#8710]
* KOReader version: 2022.01
* Device: android

#### Issue
When night mode is set the splash screen is still white.

#### Steps to reproduce
1. set to night mode
2. close the app completely
3. open it again and get blinded for half a second

**Comment by pazos** [comment]
Benefits Android Q+ users with lcd devices and night mode enabled. Brightness level is inherited from system so the "get blinded" effect is only a matter of colors.

> When night mode is set the splash screen is still white.

Fixing this involves a fairly big amount of work because our night mode isn't related at all with android day/night modes. 

But a patch that makes the splashscreen follows system mode is trivial.

Anyway, patches welcome

**Comment by pazos** [comment]
Closing this ticket in favor of #8868

**Comment by resolritter** [comment]
@pazos I think this feature is different from https://github.com/koreader/koreader/issues/8868. That ticket seems to be about dynamically changing the views in reaction to ongoing changes in the system's settings (i.e. changes after the application has already started), while this one seems to be about starting the application with the more appropriate theme based on the existing system settings.

In https://github.com/koreader/android-luajit-launcher/blob/17901da600ec85b02d3f7dc0bd0ce0fc55a6aaec/app/src/main/res/drawable/splash_icon.xml#L3 (referenced in https://github.com/koreader/android-luajit-launcher/blob/17901da600ec85b02d3f7dc0bd0ce0fc55a6aaec/app/src/main/res/values/styles.xml#L24) the color is hardcoded to `@android:color/white`. I changed that value to `@android:color/black` and the background became black, as I wanted; that being said, changing the hardcoded value is not a solution since it should somehow be dynamic.

According to https://stackoverflow.com/a/51369555/8401696 there could be a `res/values-night/styles.xml` file, which would reference a `res/drawable/splash_icon-night.xml` file with the black background. Please bear in mind that I don't have experience with Android development, so I don't know if that would work in practice.

**Comment by pazos** [comment]
Hi, OP requested a splashscreen that follows app mode and that's not trivial.

A splashscreen that follows system settings is indeed trivial and the info you provided looks enough to implement it.

Patches welcome! ;)
