### ISSUE TITLE
Screen display divided into two parts

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8773]
* KOReader version: v2022.01-80
* Device: Pocketbook 628

#### Issue
As a follow-up to https://github.com/koreader/koreader/issues/8750#issuecomment-1025676597 I open a separate issue about this problem, giving some photos, as it can't be captured with screenshots.
The screen display is divided into two parts when rotation mode is set to +/- 90°  and, while the one changes with the turn of the page, the other remains stable.

@rjd22 told that he will look into it next week.

![IMGP9040 (Medium)](https://user-images.githubusercontent.com/76203123/152557283-4f1b2cc4-e258-4c8d-bdb1-99daf36d6800.JPG)

![IMGP9041 (Medium)](https://user-images.githubusercontent.com/76203123/152557425-91f4d756-bd71-4905-b0cf-90d667adf023.JPG)

![IMGP9042 (Medium)](https://user-images.githubusercontent.com/76203123/152557432-86cf0463-3c91-4a29-b507-0366f85e50c7.JPG)

![IMGP9043 (Medium)](https://user-images.githubusercontent.com/76203123/152557451-cce832cb-b91e-4624-a009-e49cf0f6fa36.JPG)

**Comment by ichnilatis-gr** [comment]
Unfortunately, if this bug is not fixed, the new versions for Pocketbook devices will be almost useless.
Dear @rjd22, is there any hope?

**Comment by rjd22** [comment]
@NiLuJe I hope you can point me in the right direction on what might be going wrong.

I've tested rotation on my pocketbook and the screen does rotate correctly. The first time a full refresh is done and everything shows up on the correct place. Touch also works correctly on the rotated screen.

What seems to go wrong is that it uses incorrect coordinates for refreshing the screen. But I'm not sure this is because the inkview library changes how it handles the coordinates or that koreader sends different coordinates when the screen is turned. To test this I replaced all `refreshPartial` implementations to do a full refresh and when doing so the rotation is working fine and touch works perfectly.

I hope you can nudge me on where it look or on how to debug this situation so I can make a fix.

**Comment by NiLuJe** [comment]
Possibly something like this is missing in the IV codepath?

https://github.com/koreader/koreader-base/blob/64bdeda85efe127357c9b969a8cc72b46521ad87/ffi/framebuffer_mxcfb.lua#L251-L253

**Comment by ichnilatis-gr** [comment]
> @ichnilatis-gr you need to be a bit more patient. I have limited time but I hope to have some time to fix it in the coming weeks. I have the same issue with my pocketbook so I will be able to test it luckily.

Sorry to bother you. I sent my message just as a reminder. Thank you for your efforts. I understand your difficulty about limited time; I have the same problem. I wish you good success.

**Comment by rjd22** [comment]
@ichnilatis-gr does this patch also fix the issue for you?

https://github.com/koreader/koreader-base/pull/1454/files

**Comment by hombretranquilo** [comment]
This solves the issue at least in my Inkpad3.

Thanks @rjd22

**Comment by ichnilatis-gr** [comment]
> @ichnilatis-gr does this patch also fix the issue for you?
> 
> https://github.com/koreader/koreader-base/pull/1454/files

Excuse me, how can I apply it to my device? Do I need to download a file? I don't know these things well...

**Comment by rjd22** [comment]
@ichnilatis-gr you can download the raw file here and replace it with the file on your pocketbook in the `application/koreader/ffi` path:

https://raw.githubusercontent.com/rjd22/koreader-base/4bf7030c3a93cc421296cc35c6577da507b8fb14/ffi/framebuffer_pocketbook.lua
