### ISSUE TITLE
Android Tablet Screen Dimming Problem

### ISSUE THREAD

**Issue by oldman63** [koreader/koreader#8778]
* KOReader version: Nightly 2022.01.80 arm
* Device: Samsung Galaxy Tab S6

Screen dimming problem
================

On Android Tablet, brightness cannot be "fully" controlled.
Moon Reader+ also allows for nagative brightness values, KOReader currently does not.

See the attached Screen Videos.

KOReader: https://photos.app.goo.gl/DaKv4utygWWpCaMr6
Moon Reader+: https://photos.app.goo.gl/1hnQzbnPq7NeYtNx5

**Comment by Frenzie** [comment]
I agree that the dragging action on the left works oddly, but it does allow for the full range. I understand some people like it that way, I don't know. ;-)

The ability to control the brightness from within the program pretty much only exists for a subset of E Ink devices. On regular Android you can easily pull down the brightness control from the top of the screen. Anyway, you can try the actual slider (either swipe down, left or through the top menu -> settings (gear) -> light, or assign it to a corner tap).

The "negative" brightness will be some kind of overlay. I would suggest one of those generic twilight filter type apps there so it's for the entire system rather than just one or two individual programs.
