### ISSUE TITLE
Please add editing statistics module possible

### ISSUE THREAD

**Issue by badrow** [koreader/koreader#8793]
Hi, I really love koreader and its plugins and i need a functioon which seems (for me as non developer) a bit simple to implement.
The calendar statistics view can be used as an agenda if you could just add the option to open in editing mode a day instead of just using it as a stats calendar.

Can someone please implement this ? Or fork the stats module to create an agenda app. I know it's a bit weird but it should be really cool if we can use our ereader as agenda.
Thanks

**Comment by roygbyte** [comment]
How do you imagine that entries would be added to the agenda? Would it be done using the on screen keyboard? Asking because it seems to me this would be a pretty tedious thing to have to do for tasks, appointments, etc. 
I've taken a look at the statistics view out of curiosity for other matters, and it is a bit more challenging than you'd think to tack on a day planner :)

**Comment by poire-z** [comment]
My thoughts at https://github.com/koreader/koreader/pull/5854#issuecomment-586579954 .
