### ISSUE TITLE
chroot without root

### ISSUE THREAD

**Issue by opk12** [koreader/koreader#8866]
Hello, I read the terminal emulator news from [the 2022.02 release](https://github.com/koreader/koreader/releases/tag/v2022.02). But if I do not have root, [serverfault](https://serverfault.com/q/135599) says that chroot won't work, so are there specialized instructions? Thanks

**Comment by opk12** [comment]
Hello, are there instructions to use proot (which does not require root)? Thanks

**Comment by Frenzie** [comment]
I think proot should work on 2.6 or higher, so binaries *may* be easy enough to find.

But the reason I mentioned chroot in the release notes is because it's one of the more convenient methods of doing certain things on Kobo and a few other devices. There is absolutely no reason to prefer chroot (or proot) if it's not! It's not some magical preferred method.

For many programs, you can easily get a compiled ARM binary that will Just Work™ (e.g., Syncthing). If you can't, you can also just grab precompiled Alpine/Arch/Debian/whatever packages directly. It depends on the specifics whether that's worthwhile without the convenience of the package manager, but that's generally easy enough to tell at a quick glance.

The only question is what you want to do. chroot isn't what you want to do. chroot is merely one possible solution to achieve it.
