### ISSUE TITLE
koreader doesn't ask for upgrade when cre_dom_version is newer

### ISSUE THREAD

**Issue by richo67** [koreader/koreader#8973]
* KOReader version: 202112010000 also latest 202203010000
* Device: Android, kindle pw5, linux appimage

#### Issue
I have some epubs with cre_dom_version 20200223, 20200824 but this version of koreader has cre_dom_version 20210904 and it is not reloading, regenerating these epubs to its 20210904.
I also had some older epubs with cre 2018* and 2017* and they all been nicely regenerated and updated

#### Steps to reproduce
Load epub with cre_dom_version 20200223 or 20200824 in koreader 2021.12.010000 (or latest 2022.03.01) and you will not get popup to regenerate because cre has changed.

**Comment by poire-z** [comment]
> and it is not reloading, regenerating these epubs to its 20210904

That is the expected behaviour.
The behaviour you see of proposing upgrades was added in #5897.
If was some obligatory step to migrate highlights, which was risky, so this question to the user.
The idea with these cre_dom_versions was to keep using some bits of code that were used when first opening a book so all highlights/xpath/current position stay consistent.
I dunno (I don't remember, don't really want to dig in :) if this is still relevant after this first upgrade that was supposed to migrate xpointers to something more stable across crengine changes.

But well I'm not super certain it would be safe to auto upgrade : if the HTML Parser changes with a cre_dom_version bump, it may build something completly different, so your highlights may get broken - and migrating this would be a lot more difficult that what was allowed with 20200223.

Here's what you miss with not upgrading:
https://github.com/koreader/crengine/blob/ada7342e8fad637b6b7e60613de316b4d4ab7dfc/crengine/src/lvtinydom.cpp#L72-L85

So, I guess it should stay with the old dom version: if your book opened fine and was readable in 2020, it can keep using 20200223. The changes in DOM parser are, to the user, little ones, so not stictly required - but they may help opening some books that were previously unopenable/unreadable. There are much more bigger and nicer changes that didn't require a cre_dom_version bump.

If we were auto upgrading, this cre_dom_version would have no purpose :)
If you really want to have your book updated, you can remove the cre_dom_version from all your metadata.epub.lua - but it's not worth the hassle :)

**Comment by richo67** [comment]
@poire-z Thank you for explaining this to me and for references. I have tried to understand it all but I am sure I didn't. Maybe you can simplify it for me to explain why document with cre_dom_version from 2017 is updated to latest 2021, but document having cre_dom_ 202009223 is not?

I am having two copies with highlights. One red by kindle koreader and one copy read by android/linux. I often continue reading on other device (syncing last position online using plugin for syncing it) I am using KoHighlights for syncing highlights and bookmarks. If they have different cre_dom it is not possible.

Would it be possible to sync highlights same way as last position (through some magic server on internet?) That would solve this cre issue. Which of course rising other question, is there a way to register highlights and bookmarks independently on koreader or at least on the CREngine?

**Comment by poire-z** [comment]
Because we _had to_ migrate older versions to at least 20200223.
We _don't need to_ migrate 20200223 or newer to anything even newer.
(For some good reason that I had since forgotten, that must be explained in the linked PR.)

And KOHighlight don't migrate between versions because doing so, highlights could be lost or invalid. That's the reason for the existence of this cre_dom_version.
The loss/invalidity of highlights is probably rare in real life, but it can happen, so the precautions we take.

So, you are indeed, because of using multiple devices, in a situation we can't handle automagically.
But if you backup your .sdr/ (so that you don't lost your highlights), you can update manually the cre_dom_version to one you prefer (the newest seen on all your devices, for example), and KOHighlight will be fine. You will probably not lose highlight, but there's no garantee. Your risk :)

(It's already painful - for me - to ensure crengine don't break past highlights on a same book open on a device. I'm not getting involved in syncing across devices with different cre_dom_versions.)

**Comment by richo67** [comment]
Thank you @poire-z for your explanations.
