### ISSUE TITLE
FR: equalized font sizes in FM detailed view

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9094]
**Does your feature request involve difficulty completing a task? Please describe.**
Some PDF files often have no author fields filled up. Their titles then have larger font sizes compared to files with authors.

**Describe the solution you'd like**
I would like to have an option to make equal font sizes (preferably smaller one) in FM in detailed view with covers and metadata, regardless of the author field presence.

**Describe alternatives you've considered**
In Classic mode everything is of consistent size. In detailed view with filenames and covers, it depends on the filename length. If it long, then it is smaller.

**Additional context**
Some of the books however are exceptions. For example, have a look at NRL Plasma Physics Formulary book, it has both title and author field, however the title has large fonts as other no-author books.

![Screenshot_20220512-164950](https://user-images.githubusercontent.com/6279855/168055558-89e1de22-f383-49dc-b6ed-fb3bb1ef2072.png)

Thank you for attention!

**Comment by mergen3107** [comment]
Thank you very much for explaining @poire-z !

It will be good enough for me if I just make these values the same, thank you :)

**Comment by jonnyl2** [comment]
I found this ticket because I am also somewhat bothered by the wildly varying font sizes in the detailed view. I tried the [above](https://github.com/koreader/koreader/issues/9094#issuecomment-1124908377) 'hack' and it works well for short titles, but as mentioned, the font sizes will still be reduced to get longer titles to fit.

![image](https://github.com/koreader/koreader/assets/95502269/40f83e66-d896-4933-b42e-62da56ee6123)

Is there a way to 1) make this hack into a user patch, and 2) set the title/ author names to truncate if they don't fit using the specified font size(s)?

**Comment by poire-z** [comment]
Plugins are not easily user-patchable (I don't think I ever need to patch a plugin, so I haven't investigated how this could be done, but it feels it needs some trick, as plugins are reloaded each time, and not only once like all other modules).

For the limitation to not go too low - or just not decrease it at all, I think it should be done around here, some hard `break` at some point. And may be plug a `height_overflow_show_ellipsis=true` to the TextBoxWidget instantiated above):
https://github.com/koreader/koreader/blob/84dd58f9df5afc0346ac3df98d714baed5e80bb9/plugins/coverbrowser.koplugin/listmenu.lua#L615-L626

**Comment by Frenzie** [comment]
> Since a user patches is likely not suitable to tweak this (I had suspected as much, as I couldn't find a single example user patch addressing a plugin)

I'm not sure if that follows. It just hasn't come up afaik.

**Comment by benoit-pierre** [comment]
After #10942, it's pretty easy to force truncating instead of decreasing font size:
```diff
--- i/plugins/coverbrowser.koplugin/listmenu.lua
+++ w/plugins/coverbrowser.koplugin/listmenu.lua
@@ -679,7 +679,7 @@ function ListMenuItem:update()
                     break
                 end
                 -- Don't go too low, and get out of this loop.
-                if fontsize_title <= 12 or fontsize_authors <= 10 then
+                if true or fontsize_title <= 12 or fontsize_authors <= 10 then
                     local title_height = wtitle:getSize().h
                     local title_line_height = wtitle:getLineHeight()
                     local title_min_height = 2 * title_line_height -- unscaled_size_check: ignore
```

**Comment by mergen3107** [comment]
> it's pretty easy to force truncating instead of decreasing font size

@benoit-pierre 
Thank you so much! I like how it looks like a lot!

I'll probably make plugin copy, edit it, and disable original one - if this change will not be added to the nightlies

**Comment by benoit-pierre** [comment]
Note that there are still instances where the font size is slightly reduced:
- multiline authors (instead of a `,` or `;` separated list)
- book is part of a series and "Show series metadata in separate line" is used

**Comment by benoit-pierre** [comment]
Updated patch:
```diff
--- i/plugins/coverbrowser.koplugin/listmenu.lua
+++ w/plugins/coverbrowser.koplugin/listmenu.lua
@@ -486,9 +486,17 @@ function ListMenuItem:update()
             local fontname_authors = "cfont"
             local fontsize_title = _fontSize(20, 24)
             local fontsize_authors = _fontSize(18, 22)
+            local reduced_fontsize_title = _fontSize(17, 21)
+            local reduced_fontsize_authors = _fontSize(15, 19)
             local wtitle, wauthors
             local title, authors
             local series_mode = BookInfoManager:getSetting("series_mode")
+            local allow_downsizing = false
+
+            if not allow_downsizing and series_mode == "series_in_separate_line" then
+                fontsize_title = reduced_fontsize_title
+                fontsize_authors = reduced_fontsize_title
+            end
 
             -- whether to use or not title and authors
             -- (We wrap each metadata text with BD.auto() to get for each of them
@@ -506,7 +514,7 @@ function ListMenuItem:update()
                 -- If multiple authors (crengine separates them with \n), we
                 -- can display them on multiple lines, but limit to 2, and
                 -- append "et al." to the 2nd if there are more
-                if authors and authors:find("\n") then
+                if allow_downsizing and authors and authors:find("\n") then
                     authors = util.splitToArray(authors, "\n")
                     for i=1, #authors do
                         authors[i] = BD.auto(authors[i])
@@ -518,8 +526,8 @@ function ListMenuItem:update()
                     end
                     authors = table.concat(authors, "\n")
                     -- as we'll fit 3 lines instead of 2, we can avoid some loops by starting from a lower font size
-                    fontsize_title = _fontSize(17, 21)
-                    fontsize_authors = _fontSize(15, 19)
+                    fontsize_title = reduced_fontsize_title
+                    fontsize_authors = reduced_fontsize_authors
                 elseif authors then
                     authors = BD.auto(authors)
                 end
@@ -548,8 +556,8 @@ function ListMenuItem:update()
                     elseif series_mode == "series_in_separate_line" then
                         authors = bookinfo.series .. "\n" .. authors
                         -- as we'll fit 3 lines instead of 2, we can avoid some loops by starting from a lower font size
-                        fontsize_title = _fontSize(17, 21)
-                        fontsize_authors = _fontSize(15, 19)
+                        fontsize_title = reduced_fontsize_title
+                        fontsize_authors = reduced_fontsize_authors
                     end
                 end
             end
@@ -610,7 +618,7 @@ function ListMenuItem:update()
                     break
                 end
                 -- Don't go too low, and get out of this loop.
-                if fontsize_title <= 12 or fontsize_authors <= 10 then
+                if not allow_downsizing or fontsize_title <= 12 or fontsize_authors <= 10 then
                     local title_height = wtitle:getSize().h
                     local title_line_height = wtitle:getLineHeight()
                     local title_min_height = 2 * title_line_height -- unscaled_size_check: ignore
```

**Comment by mergen3107** [comment]
Thanks! Haven't tried the new patch yet.
I got a questions about that `if true` fix above that.
This book, for example, has a lot of authors (> 10 for sure).
Was it supposed to be truncated or not?

[Поэзия Серебряного века (Сборник).fb2.zip](https://github.com/koreader/koreader/files/14891782/fb2.zip)

Currently it shows up like this (last book in the list):
![FileManager_2024-04-05_202101](https://github.com/koreader/koreader/assets/6279855/6ee26c63-abd7-47f1-b96c-a85aade48311)

**Comment by mergen3107** [comment]
> * book is part of a series and "Show series metadata in separate line" is used

Yeah, I usually append series to authors line

**Comment by mergen3107** [comment]
In your patch, wasn't this line supposed to end with "authors"? (in the beginning, in the "if not allow_downsizing" loop)

fontsize_authors = reduced_fontsize_title

**Comment by benoit-pierre** [comment]
Another update:
```diff
--- i/plugins/coverbrowser.koplugin/listmenu.lua
+++ w/plugins/coverbrowser.koplugin/listmenu.lua
@@ -489,6 +489,8 @@ function ListMenuItem:update()
             local wtitle, wauthors
             local title, authors
             local series_mode = BookInfoManager:getSetting("series_mode")
+            local fixed_font_size = BookInfoManager:getSetting("fixed_font_size")
+            local reduce_font_size = fixed_font_size and series_mode == "series_in_separate_line"
 
             -- whether to use or not title and authors
             -- (We wrap each metadata text with BD.auto() to get for each of them
@@ -518,8 +520,7 @@ function ListMenuItem:update()
                     end
                     authors = table.concat(authors, "\n")
                     -- as we'll fit 3 lines instead of 2, we can avoid some loops by starting from a lower font size
-                    fontsize_title = _fontSize(17, 21)
-                    fontsize_authors = _fontSize(15, 19)
+                    reduce_font_size = true
                 elseif authors then
                     authors = BD.auto(authors)
                 end
@@ -548,8 +549,7 @@ function ListMenuItem:update()
                     elseif series_mode == "series_in_separate_line" then
                         authors = bookinfo.series .. "\n" .. authors
                         -- as we'll fit 3 lines instead of 2, we can avoid some loops by starting from a lower font size
-                        fontsize_title = _fontSize(17, 21)
-                        fontsize_authors = _fontSize(15, 19)
+                        reduce_font_size = true
                     end
                 end
             end
@@ -557,6 +557,10 @@ function ListMenuItem:update()
                 -- Let's show this fact in place of the anyway empty authors slot
                 authors = T(_("(no book information: %1)"), _(bookinfo.unsupported))
             end
+            if reduce_font_size then
+                fontsize_title = _fontSize(17, 21)
+                fontsize_authors = _fontSize(15, 19)
+            end
             -- Build title and authors texts with decreasing font size
             -- till it fits in the space available
             local build_title = function(height)
@@ -610,7 +614,7 @@ function ListMenuItem:update()
                     break
                 end
                 -- Don't go too low, and get out of this loop.
-                if fontsize_title <= 12 or fontsize_authors <= 10 then
+                if fixed_font_size or fontsize_title <= 12 or fontsize_authors <= 10 then
                     local title_height = wtitle:getSize().h
                     local title_line_height = wtitle:getLineHeight()
                     local title_min_height = 2 * title_line_height -- unscaled_size_check: ignore
diff --git i/plugins/coverbrowser.koplugin/main.lua w/plugins/coverbrowser.koplugin/main.lua
index 6a3b2bc27..dc572a106 100644
--- i/plugins/coverbrowser.koplugin/main.lua
+++ w/plugins/coverbrowser.koplugin/main.lua
@@ -426,6 +426,16 @@ function CoverBrowser:addToMainMenu(menu_items)
                     BookInfoManager:toggleSetting("hide_file_info")
                     self:refreshFileManagerInstance()
                 end,
+            },
+            {
+                text = _("Fixed font size"),
+                checked_func = function()
+                    return BookInfoManager:getSetting("fixed_font_size")
+                end,
+                callback = function()
+                    BookInfoManager:toggleSetting("fixed_font_size")
+                    self:refreshFileManagerInstance()
+                end,
                 separator = true,
             },
             {
```

**Comment by benoit-pierre** [comment]
OK, this time I think I got it right.

**Comment by benoit-pierre** [comment]
Except no, so let's go to sleep and I'll revisit tomorrow :P.

**Comment by benoit-pierre** [comment]
This time I'm done:
```diff
--- i/plugins/coverbrowser.koplugin/listmenu.lua
+++ w/plugins/coverbrowser.koplugin/listmenu.lua
@@ -489,6 +489,8 @@ function ListMenuItem:update()
             local wtitle, wauthors
             local title, authors
             local series_mode = BookInfoManager:getSetting("series_mode")
+            local fixed_font_size = BookInfoManager:getSetting("fixed_font_size")
+            local reduce_font_size = fixed_font_size and series_mode == "series_in_separate_line"
 
             -- whether to use or not title and authors
             -- (We wrap each metadata text with BD.auto() to get for each of them
@@ -518,8 +520,7 @@ function ListMenuItem:update()
                     end
                     authors = table.concat(authors, "\n")
                     -- as we'll fit 3 lines instead of 2, we can avoid some loops by starting from a lower font size
-                    fontsize_title = _fontSize(17, 21)
-                    fontsize_authors = _fontSize(15, 19)
+                    reduce_font_size = reduce_font_size or not fixed_font_size
                 elseif authors then
                     authors = BD.auto(authors)
                 end
@@ -548,8 +549,7 @@ function ListMenuItem:update()
                     elseif series_mode == "series_in_separate_line" then
                         authors = bookinfo.series .. "\n" .. authors
                         -- as we'll fit 3 lines instead of 2, we can avoid some loops by starting from a lower font size
-                        fontsize_title = _fontSize(17, 21)
-                        fontsize_authors = _fontSize(15, 19)
+                        reduce_font_size = reduce_font_size or not fixed_font_size
                     end
                 end
             end
@@ -557,6 +557,10 @@ function ListMenuItem:update()
                 -- Let's show this fact in place of the anyway empty authors slot
                 authors = T(_("(no book information: %1)"), _(bookinfo.unsupported))
             end
+            if reduce_font_size then
+                fontsize_title = _fontSize(17, 21)
+                fontsize_authors = _fontSize(15, 19)
+            end
             -- Build title and authors texts with decreasing font size
             -- till it fits in the space available
             local build_title = function(height)
@@ -610,7 +614,7 @@ function ListMenuItem:update()
                     break
                 end
                 -- Don't go too low, and get out of this loop.
-                if fontsize_title <= 12 or fontsize_authors <= 10 then
+                if fixed_font_size or fontsize_title <= 12 or fontsize_authors <= 10 then
                     local title_height = wtitle:getSize().h
                     local title_line_height = wtitle:getLineHeight()
                     local title_min_height = 2 * title_line_height -- unscaled_size_check: ignore
diff --git i/plugins/coverbrowser.koplugin/main.lua w/plugins/coverbrowser.koplugin/main.lua
index 6a3b2bc27..dc572a106 100644
--- i/plugins/coverbrowser.koplugin/main.lua
+++ w/plugins/coverbrowser.koplugin/main.lua
@@ -426,6 +426,16 @@ function CoverBrowser:addToMainMenu(menu_items)
                     BookInfoManager:toggleSetting("hide_file_info")
                     self:refreshFileManagerInstance()
                 end,
+            },
+            {
+                text = _("Fixed font size"),
+                checked_func = function()
+                    return BookInfoManager:getSetting("fixed_font_size")
+                end,
+                callback = function()
+                    BookInfoManager:toggleSetting("fixed_font_size")
+                    self:refreshFileManagerInstance()
+                end,
                 separator = true,
             },
             {
```

Does not look pretty with "fixed font size" / "show series metadata in separate line" IMHO, when only some books are part of a series (maybe it would look better if not centered vertically?).

**Comment by poire-z** [comment]
I see this is progressing towards being a setting...
I don't mind as long as (I don't have to code it :) and) it stays as simple as the above, but I don't want this to become a gaz factory, as I think that people will realize in the end it's not a good idea :)

> On top of the original request, I would like to add on the following:
>  Let users select one font size each for title and author (or a range, if preferred), and **optionally** to shrink the font sizes to fit everything
>  Make the Shrink font size setting separate for File browser and History view (see point 3. above)

And the next things you'll want is the abality to tweak these per directory. Because you were fine with a fixed large font size for most things, but one day, you'll see that these new books have the valulable distinguishing things at the end of a somehow longer than normal title, and well, it doesn't look too good with your prefered fixed font size...
Good luck distinguishing these 3 documents in your History if truncated:
```
ULF waves observed in solar wind and on the ground under sandstorm at... (high latitudes)
ULF waves observed in solar wind and on the ground under sandstorm at... (mid latitudes)
ULF waves observed in solar wind and on the ground under sandstorm at... (low latitudes)
```


I think the current single behaviour is the best thing:
- we do as good as we can to show most of title & authors, keeping the ratio/boldness of the items similar when decreasing, so it does not look too patchworky.
- look at your paperbook shelves: the font size and title lengths on their spine are not constant as you wish it here. They show all of their text. And the various text size and lenghts (and text and spine colors) may help you finding the one you want.
- I think that for quick scans, the possible various font size/layouts/wrappings will make it easier to find a book, if you remember "it's the one with the smaller font size and short 2 lines", than having all items look similar and really having to scan/read the titles.

**Comment by offset-torque** [comment]
This problem is already solved in every file manager. 
There are 2 possible solutions for displaying long file names:
- Go multi-line
- Truncate the file name from the middle or end

For example in **Moon Reader** on my Android it is multi-line. So I can now see a book with two lines and after that comes an article with seven lines. They are not equal in height because font size is the same, but it is not important in this case. Titles are very bold so I can just skip from title to title.

KOReader uses multi-line too. But we have this problem because KOReader uses a static grid. And to go multi-line on a static grid, you have to shrink the font, which is the current solution.

I (speaking as an ordinary user) personally don't care how many items per page is there. I just want to set my font size to a comfortable one and that's it. Show me 10 items on a page if filenames are short, show me 5 if they are very long.

Imagine KOReader asking the user **"How many lines you want to see on a book page?"**. Well, the answer is **"I don't know, as many as you can fit on my screen at this font size"**. Imagine we make users choose a "number of lines setting" like 50 and shrink the font to fit this. And if they want to make the font bigger, they go into a convoluted menu to change "number of lines per page" setting. Doesn't make sense at all, right?

And I am not going into the accessibility aspect of this. UI font size should be consistent because I might see the "1 line title font size" ok but I have to get my glasses to see the "3 line font size". And on this interface, users can't just zoom in with pinch/spread gesture like a mobile phone.

Buuuut probably this widget is very limited so we are stuck with this and it will probably take lots of effort to switch to a **"dynamic number of items per page"** layout so here we are having this discussion trying to steer around the big elephant by cutting filenames and trying dynamic limited shrinkage strategies for different parts of UI.

(This is not a rant, just pointing out the obvious problem :)

**Comment by Frenzie** [comment]
@poire-z But "Shrink items to fit more text" or whatever it's called is already a setting?

> * Truncate the file name from the middle or end

We have an implementation of that as well, but the general consensus was that (within reason) we all preferred to see the full thing. That's why it feels at the same weight etc., it makes it easier to scan the list, and so on and so forth.

**Comment by poire-z** [comment]
> But "Shrink item font size to fit more text" is already a setting?

That's for the Classic mode, where we have only a single string (the filename) to truncate or shrink and display.
With detailed list, an item is a bit more complex, with stacked TextWidgets or TextBoxWidgets, and a width limited by the size of the "mandatory" on the right. So, if you want to do complex stuff as requested, it's a lot more involved (and ugly) - so the bit harcoded decisions/algorithm.

**Comment by jonnyl2** [comment]
>>[offset-torque] Buuuut probably this widget is very limited so we are stuck with this and it will probably take lots of effort to switch to a "dynamic number of items per page" layout so here we are having this discussion trying to steer around the big elephant by cutting filenames and trying dynamic limited shrinkage strategies for different parts of UI.

>Also that's not an elephant, that's just a different preference. No matter what you choose, people will complain.

@Frenzie, so would KOReader be easily able to support a dynamic number of items per page? I don't think that's necessarily a good idea for FM or History, because book title lengths aren't _that_ variable, and it's nice to see a consistent number of items per screen. However, on the Bookmarks list, I think a dynamic number would be both more usable and more aesthethic (with a cap at 1/2 or 1/3 of screen height per bookmark, probably). Highlight lengths ordinarily can range from a single word to several paragraphs long. Many short highlights mean lots of empty space on the Bookmarks screen, or alternatively, many long highlights will all be truncated early on in the text.

**Comment by Frenzie** [comment]
> so would KOReader be easily able to support a dynamic number of items per page?

I doubt it. That could mean you'd have to render dozens of pages just to be able to tell what the pages even are.

**Comment by offset-torque** [comment]
> **Frenzie -** We have an implementation of that as well, but the general consensus was that (within reason) we all preferred to see the full thing. 

I agree that, this is the correct default. I also use the full titles. Actually I can't even truncate if I want because of article title inflation. I just thought some users might prefer truncation to font size change. Especially if they only read books, loss is not that critical.

> **Frenzie -** Also that's not an elephant, that's just a different preference. 

Surely. I didn't mean that as "this is the correct way". But dynamic pagination is nearly default on all mobile interfaces in the form of scrolling. When you go to Twitter and press page down, you are technically navigating a dynamic pagination. All Android file managers are like this (and probably ios too). So people are very familiar with this concept. But of course we can't scroll on e-ink due to screen and probably GPU limitations (except newest devices). So maybe 2 e-ink generations later KOReader can adopt this and solve all this problems :)

> **Frenzie -** No matter what you choose, people will complain.

Yep :(

**Comment by jonnyl2** [comment]
I tried @benoit-pierre's patch and I think it looks great. Thank you! 

![FileManager_2024-04-11_145625 2](https://github.com/koreader/koreader/assets/95502269/77f3a3f3-43b5-4b24-9f57-75d4b7bf7706)

I would really like if this could be added as a setting.

Regarding @poire-z's points:

I'm okay without any further settings. The separate settings for FM/History was just an idea. I could live well without it. I also don't foresee needing different font size or truncation settings for different folders...

As far as distinguishing similar, truncated book titles goes, the solution is pretty simple (and such a scenario should be expected by anyone choosing a fixed font size): (1) Long-press on the title and either read the filename or the complete metadata title in the detail information; or (2) Deactivate the fixed font size setting. (3) Change font size/ items per page. In essence, the same things as one would do in the Classic mode. And for the Detailed view, there's even a a fourth option: (4) Add a custom title name to make it shorter (or move the important parts up front).

**Comment by benoit-pierre** [comment]
I think truncating of title & authors should be done in the middle, especially when `append series to xxx` is used.

**Comment by jonnyl2** [comment]
>I think truncating of title & authors should be done in the middle, especially when append series to xxx is used.

That's a good idea, that should probably work even better. Or perhaps at around the 2/3 mark of the title?

**Comment by mergen3107** [comment]
I wonder how it would look like in a mixed list of 2-row and 3-row titles

**Comment by poire-z** [comment]
No chance I think, this function is too big, the thing you want to tweak is right in the middle, and I can't find any "hook" around it where we could do that magic :/

But our user patch system supports having code executed just after an update/install, when the file starts with `0-` instead of `2-` - and I think one could just "patch" (a real oldschool patch, just modifying the file - not a monkey patch like we do in `2-`) to change/insert a few lines in plugins/coverbrowser/listmenu.lua - so you would just not have to do it manually.

**Comment by mickeydeagle** [comment]
@benoit-pierre thanks for directing me here and closing my duplicate issue. Thinking a little more about the UI here, not only do I think preventing text from scaling to fit should be a setting, but _ideally, it should be the only way the data gets displayed_. I can't think of another example offhand in a modern app where tabular data adjusts in size to fit a space (I can think of some antiquated examples of a font being replaced with a condensed cut to fit a few more characters, but never the font size). Especially with tabular data, it's important to establish good rhythm, i.e. consistent styling, so users can grok what they're seeing without being distracted by text of varying sizes. It's objectively added cognitive load to vary the size.

From a designer's perspective (independent of the required development work), the ideal solution would be to have two options for handling table/list data with long text:

1. The text wraps and the rows become variable in height. Pagination settings are adjusted to say something like "Approximate lines per page: 10".
2. The text gets truncated in a smart way, similar to how @benoit-pierre suggested. This is common in operating system GUIs, where text is cut exactly in half, and then trimmed from the inside to make room for an ellipsis (macOS example below).

<img width="420" alt="macOS-truncation" src="https://github.com/user-attachments/assets/a60624a1-bde7-4e82-b92f-eaa10e92bb91">

An additional, "hybrid" solution could be to have an affordance for a second line of text for a given bit of data, and, if that overflows, then also truncate. This would introduce some whitespace into the design, but it would keep rows consistent in height.

Either (or ideally both) of these would be a big improvement over the existing UI. As a relative newcomer to e-reader software, I think the KOReader library presentation in general is not as good as other products I've seen and used (however in almost every other category — at least the ones I find important — KOReader surpasses all others in the field). I would love to opine and advise on UI issues (or even contribute design resources/assets) if that's welcome.

**Comment by Frenzie** [comment]
> The text gets truncated in a smart way, similar to how [@benoit-pierre](https://github.com/benoit-pierre) suggested. This is common in operating system GUIs, where text is cut exactly in half, and then trimmed from the inside to make room for an ellipsis (macOS example below).

This is already supported ftr, or in any case I wrote it years ago. Probably only in KeyValuePage.

**Comment by Frenzie** [comment]
Note however that it's far from obvious that it's a better choice for the end user. It's just *a* choice, and a *simple* choice. It's a better choice from the perspective of the coder because it's easier to grok.

> Especially with tabular data, it's important to establish good rhythm, i.e. consistent styling, so users can grok what they're seeing without being distracted by text of varying sizes. It's objectively added cognitive load to vary the size.

This for example is just as wrong as it is right. You add the cognitive load of *having to read* as opposed to seeing instantaneously at a glance which is which.

I'm not in camp changing text but be extremely aware that the designer's perspective is not the user's perspective. The designer loves simplicity and cleanliness while the user wants usability.

**Comment by mickeydeagle** [comment]
>the designer's perspective is not the user's perspective. The designer loves simplicity and cleanliness while the user wants usability.

Not sure I follow this. Good designers prioritize usability over simplicity and cleanliness. Maybe you just know bad designers. 😉

**Comment by Frenzie** [comment]
Your words, not mine. ;-) The designer has to make choices. If the designer isn't convinced that there's a clear advantage the designer normally picks tidier over messier, the same way the engineer picks simpler over more complex. In this case the designer was convinced there was an advantage and I think we can acknowledge that it's there even if we might disagree it's sufficiently large, or that it might come with certain disadvantages that negate it.

Or in short, the screenshot in the OP looks nasty. But it's not nasty to actually use.

**Comment by poire-z** [comment]
> Good designers prioritize usability over simplicity and cleanliness. 

Thank you :)
We indeed _not_ choose simplicity (because resizing the font size to display most of the title/authors is not simple) and cleanliness (what you seem to wish with your taste for consistent "tabular data") over usability, which I described above in https://github.com/koreader/koreader/issues/9094#issuecomment-2040979245 (that you did :+1: ?) :

> I think the current single behaviour is the best thing:
> 
> * we do as good as we can to show most of title & authors, keeping the ratio/boldness of the items similar when decreasing, so it does not look too patchworky.
> * look at your paperbook shelves: the font size and title lengths on their spine are not constant as you wish it here. They show all of their text. And the various text size and lenghts (and text and spine colors) may help you finding the one you want.
> * I think that for quick scans, the possible various font size/layouts/wrappings will make it easier to find a book, if you remember "it's the one with the smaller font size and short 2 lines", than having all items look similar and really having to scan/read the titles.

About:

> Thinking a little more about the UI here, not only do I think preventing text from scaling to fit should be a setting, but _ideally, it should be the only way the data gets displayed_. I can't think of another example offhand in a modern app where tabular data adjusts in size to fit a space

_ideally the only way_ ? :)
You may consider books filename/metadata tabular data, and may be comparing it to file browsers.
I don't consider that tabular data, but book title/authors, book spines, as shown on a shelve. I would find a truncated title quite _not ideal_ (needing to long-press to see it whole).

And people should spend less than 1% of their reading life in file browser: they don't need to see a neat and tidy list of same font size/weight truncated titles that they would contemplate for hours. They need to see most of the title/authors so they can browse and find their next read.

> the ideal solution would be to have two options for handling table/list data with long text:
> 1. The text wraps and the rows become variable in height. Pagination settings are adjusted to say something like "Approximate lines per page: 10".

Variable item height, what about the cover on the left ? Same size and centered? Scaled to fill the variable height? (so, variable h/w across the view, and someone will be back opening an issue "equalized cover sizes in non-equalized item heights FM detailed view" :)). Not ideal at all.

> 2. The text gets truncated in a smart way, similar to how @benoit-pierre suggested. This is common in operating system GUIs, where text is cut exactly in half, and then trimmed from the inside to make room for an ellipsis (macOS example below).

Again, OS GUIs do what they want to display filenames (where usually filenames are short, and longs ones are usually crap/auto-generated ie. when saving a web page).
But we display books' metadata title/authors, which most often is right and relevant (and/or corrected by the user, as since a few months ago one can edit title/authors in Book information, if one wants to make them shorter).

**Comment by offset-torque** [comment]
What about this idea:
**"Each navigation page's font size is determined by the longest title and all titles on that page uses this font size"**

So for example if there is a very long title spanning 3 lines which requires **8pt** font size, all other items will be rendered in **8pt**. I think this might solve the aesthetics problem because font size difference is a local problem. It looks bad when neighboring items have different sizes. Maybe (sensitive) users wouldn't mind font size changes between navigation pages because their current list will always look fine. This setting will be optional of course. Users bothered by the font size difference can enable it.

**Advantages:**
- All titles will have the same size
- No truncated titles
- No need to change the number of rows

**Disadvantages:**
- One long title will make everything small
- Might be too much white space

**Comment by mickeydeagle** [comment]
Thanks for your thoughtful discourse. I appreciate your opinions on this.

>I described above in https://github.com/koreader/koreader/issues/9094#issuecomment-2040979245 (that you did 👍 ?) :

I was giving the thumbs up to "I see this is progressing towards being a setting...". I think more options are good in this are of the app. For example, @poire-z sees the list view as "book title/authors, book spines, as shown on a shelve" — I think it's ok to have a list option that behaves more like the mosaic view, where each line could appear somewhat unique (i.e. text scaled to fit); however, neglecting the option for standard font size for a list is still very confusing to me. You have to admit, while not an exact analogy, if I wrote an article and fiddled with each `h` tag's font size individually, it would be harder to quickly discern the hierarchy of the page.

>people should spend less than 1% of their reading life in file browser: they don't need to see a neat and tidy list of same font size/weight truncated titles that they would contemplate for hours

That's a bit presumptuous, and certainly doesn't consider all uses cases. I do browse my library quite a bit, and would still like to be able to adjust it for consistency. If I whacked my knee on the steering wheel of my car every time I got in and out of it, you could say, "well it only happens twice a day," but I'd still be pursuing a solution to my pain.

>Or in short, the screenshot in the OP looks nasty. But it's not nasty to actually use.

I think this sums up the consensus. However, if a client in my profession described my work this way, I would make my priority then to find a better solution: something equally — or more — easy to use that's specifically _not_ "nasty" looking. Nasty and usable are of course not mutually exclusive. Like, when I first discovered the file browser options for KOReader, I was convinced I had inadvertently messed up some settings or otherwise broke the interface myself. There seems to be so much visual care put into the other aspects of the product, that it stood out to me. I don't mean that in an insulting way; I think the file browser is remarkably bad _because_ the rest of the software is so good.

Anyway, in the meantime, I have discovered a workaround where I can still use my device's built-in library (which, for me is superior) and have KOReader open the files. This is the best of both worlds: a greatly improved file browsing experience and the power of KOReader for displaying the document exactly as I wish. And, again, thank you for commenting so much on a closed issue.

**Comment by jonnyl2** [comment]
>[poire-z] You may consider books filename/metadata tabular data, and may be comparing it to file browsers.
I don't consider that tabular data, but book title/authors, book spines, as shown on a shelve. 

Book spines are designed to look pretty on a book shelf and to help the reader pick out a book. The important information (author, main title) is printed in large letters, and everything else is either printed really tiny (e.g., publisher's name, or just a publisher's logo) or left out completely (e.g., subtitle, translator, year of release, edition number, etc.). The `Title` metadata field has no concept of main title and subtitle, or any other additional information that may be in this field. That makes it not really suitable for a 'bookshelf view' anyway, but much more so as an ordered list.

If I wanted the "bookshelf look," then I'd just go for the cover browser (mosaic) view, where I think noone has complained yet that the author names and book titles are differently sized on each book. But on a tabular list view (which indeed this is), just two font sizes (titles; authors) are so vastly more visually pleasing that I'm honestly a bit baffled that this issue is so contentious. (Especially given that the code is already available, adds only a few lines, the feature would be **optional**,  and as this thread shows, there is wide-spread demand for it within the community of users.)

>And people should spend less than 1% of their reading life in file browser: they don't need to see a neat and tidy list of same font size/weight truncated titles that they would contemplate for hours. They need to see most of the title/authors so they can browse and find their next read.

This may be the case if the user is looking at their books for the first time in the file browser. However, this happens to be the _only_  list view available for the History, which I (and I'm sure many others) use as the primary vehicle to keep track of started books and to select books to read. There really is no need to always see the full title and subtitle, sometimes publisher, year, etc., for each already known and previously opened book. The first few words of the title are plenty to select a book to continue reading. 

Even _if_ I spend less than 1% of the time in the History, I'd like to make this <1% pleasing to my eyes. I have been applying @benoit-pierre's patch since it was kindly made available a few months ago. It has worked great, and I have never once missed the full-length titles. But unfortunately, frequent changes in the coverbrowser plugin makes patching this very cumbersome. My last KOReader update once again broke the patch. 

Also @poire-z you were [okay with this](https://github.com/koreader/koreader/issues/9094#issuecomment-2040979245), as long as it stays as simple as the already provided patch:

>I don't mind as long as (I don't have to code it :) and) it stays as simple as the above

Noone wanted anything more than just a fixed font size _option_, which this patch would provide. Sure, some might like variable item heights, extra lines, different cover sizes, etc. But just this barebones patch, which is already available, solves the main issue. Why use the potential of users having additional requests in the future as an argument to not offer this basic option? Nothing could or would ever be added with this reasoning, but many (often much more niche) features are added frequently. 

The only discussion still unresolved was _where_ to truncate the titles. Personally, I think truncating the end of titles is best, but truncating the middle section for books part of a series (as suggested by @benoit-pierre) would be a sensible exception IMO. (But I'd probably also be happy with all titles truncated in the middle where necessary, but haven't tested that.)

**Comment by hius07** [comment]
I agree that option in the settings would be good.

**Comment by offset-torque** [comment]
In case our devs decide to add this option, I want to remind that, for scientific articles, end truncation is not very useful because most important part of the (sometimes very long) title is generally the last words. For example it is common to have many files in a directory starting exactly like this: **"A systematic review and meta-analysis of the relationship between..."** This is especially important for medical articles.

**Comment by jonnyl2** [comment]
@offset-torque: have you tested benoit-pierre's patch? In cases such as the ones you mention, there is probably not an ideal place to cut the title anyway, and you're better off just disabling the setting and showing the full titles. (Or use a reading device more suitable for reading scientific papers than a small-screen ereader ;).)

Here is a comparison with and without patch applied, on some medical science articles: 

![Untitled 5](https://github.com/user-attachments/assets/58334bb0-8398-4366-a16d-50e63fea7d61)

**Comment by offset-torque** [comment]
Thanks for your helpful reply **jonnyl2**. Now I know how the patch looks like on articles. I never used this patch because I got used to the view on the left and seeing the full titles is more useful for me than the uniform look. I made the previous comment not for myself but as a general reminder like "probably someone will request this in the future". 

> Or use a reading device more suitable for reading scientific papers than a small-screen ereader ;)

Totally agree with you here. Reading double column pdf articles with bad typesetting on a small, slow screen is really not my favorite activity :) 

Unfortunately I don't have many alternatives currently. Bigger e-ink readers are not much better and reading on tablets is not as pleasant as e-ink. I am hopeful for this product which apparently combines the best of both worlds (assuming that the company manages to stay afloat and price goes down with the scaling): https://daylightcomputer.com/product
