### ISSUE TITLE
"Lock auto rotation to current orientation" is unchecked, grayed out

### ISSUE THREAD

**Issue by amjoseph-nixpkgs** [koreader/koreader#9136]
* KOReader version: 2022.05.1
* Device: Oasis

#### Issue

On the Gear-menu, under Screen, the option "Lock auto rotation to current orientation" is unchecked.  I cannot check it because it is grayed out.

Whenever I tilt my device a bit the rotation jumps all over the place!  This is incredibly frustrating.  I do not want my device to do things simply because I tilted it one way or another.

#### Steps to reproduce

Go to Gear->Screen, observe grayedness.

Rotate device, see the UI jump around.

**Comment by a-m-joseph** [comment]
Also it would be nice if KOReader had some way of explaining *why* menu options are grayed out when they are grayed out.  Like, a long-press on the grayed option popping up a menu saying "this is grayed out because the stars are misaligned and you have blue eyes".

**Comment by NiLuJe** [comment]
It's unimplemented on Kindle, patches welcome ;).

**Comment by Frenzie** [comment]
Not showing would possibly make more sense in that case than grayed out?

**Comment by a-m-joseph** [comment]
> It's unimplemented on Kindle

That's weird.  Why would "ignore the gyroscope" be hardware-dependent?

Obviously "get the gyroscope data" is hardware-dependent, but you'd imagine that the "ignore it / don't request it" decision would only appear once in the codebase, not copy-pasted multiple times once for each device.  I haven't dug into the codebase yet because:

> patches welcome ;).

Yeah, when I get koreader to build on my own machine.  Which is not easy...

> Not showing would possibly make more sense in that case than grayed out?

Please no, that would be even more frustrating.  At least when I found a grayed out option I knew I could stop searching through the menus!

**Comment by a-m-joseph** [comment]
> Obviously "get the gyroscope data" is hardware-dependent

Although it looks like most devices hand you evdev events...

> you'd imagine that the "ignore it / don't request it" decision would only appear once

I don't see anything in [this block of code](https://github.com/koreader/koreader/blob/ae5b2d68ca402d72f243fb75c47d55ae6ebb49b7/frontend/device/input.lua#L875) that is device-specific.

Therefore, https://github.com/koreader/koreader/pull/9138

**Comment by Frenzie** [comment]
> Obviously "get the gyroscope data" is hardware-dependent, but you'd imagine that the "ignore it / don't request it" decision would only appear once in the codebase, not copy-pasted multiple times once for each device. I haven't dug into the codebase yet because:

I would imagine it's exactly the other way around, and as such that your patch can't work. But it can't hurt to try, it could be an oversight. ^_^

**Comment by NiLuJe** [comment]
That's because the gyro input events on Kobo are a bit of an odd duck, unlike on Kobo.

(Also, i'm the one who implemented that on kobo and I don't have an affected Kindle device ;)).

**Comment by NiLuJe** [comment]
As in, `adjustKindleOasisOrientation` should be updated to actually send sane `EV_MSC` events like on Kindle, and then one might re-use/refactor/duplicate `Input:toggleMiscEvNTX` to handle the ignore.

**Comment by NiLuJe** [comment]
Sidebar: Graying this out instead of hiding it was an incentive for random users to look into it and implement it ;).

Otherwise, yeah, hiding would make more sense.

**Comment by a-m-joseph** [comment]
> (Also, I'm the one who implemented that on Kobo and I don't have an affected Kindle device ;)).

Yeah I was using a Kobo Forma for the past year until the KOA3 jailbreak appeared.

I loved the big huge screen on the Forma but its physical buttons are so incredibly awful.  Especially the power button on the side, which you can't avoid because it doesn't have a magnetic cover-sensor like the Kindle.  I actually broke my fingernail trying to press it.  I cannot figure out what the Kobo engineers were thinking...  Also the KOA3 is noticeably faster.



> As in, `Input:adjustKindleOasisOrientation` (in `frontend/device/input.lua`) should be updated to actually send sane `EV_MSC` events like on Kobo, and then one might re-use/refactor/duplicate `Input:toggleMiscEvNTX` to handle the ignore, implementing a `toggleGSensor` in `Kindle`, (c.f., `Kobo:toggleGSensor`), at which point enabling the devcap flag `canToggleGSensor` on `Kindle` would be viable.

Ah, thank you *so much* for this pointer, that's the kind of response I was hoping to get.  I'll take it from here.  Should have a PR sometime next weekend.



> Sidebar: Graying this out instead of hiding it was an incentive for random users to look into it and implement it ;).

Definitely worked :)

**Comment by 2600box** [comment]
Just wanted to add my experience. I just installed Ladybug on my Kindle Oasis 3 on 5.14.2 . After waking from sleep, the gyro sends the auto rotation crazy. I was able restart, load KOReader and tick the "Lock rotation to current".
