### ISSUE TITLE
FR: Share Highlights

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#9150]
For Android-based devices (Likebook, Boox etc.) it is often swifter to 'share' highlights instead of `export`. For example, using the `share` button one can simply create a note in Joplin without a remote Joplin setup. If you agree, I can work on this.

## How will it work?
1. plugins must declare if they allow sharing, the menu will be generated based on that.
2. A menu item for `share` and a submenu for all available share options.
3. Upon selecting one, a function on that plugin will be called, probably `getShareContent` and sent using Android share intent.

Of course, it will be shown only in Android until other platforms start supporting share.

**Comment by pazos** [comment]
Uf, sounds a nightmare to implement.

Let me see if I understood you correctly:

When an user press "share to Joplin" the machinery of exporting to markdown will be run but the file stored in a cache dir. Then, when the file is created, we trigger the share intent passing the contents of the file as a bundle so other apps can consume it. Then when we're back in KO we just delete the cache file and back to normal life?

Sounds a bit messy but doable. Only local formats can be shared (no problem since Joplin is just markdown) and we don't need to check if each "target" app is installed on user device. We just share text/html/markdown if there's at least one app able to deal with the format (a runtime check once for each format is enough).

Another stopper: the current implementation of sharing text is good enough for dictionary definitions (its main dutty) or little highlights but not ok for full highlights export. We just need another function on the android backend to make it possible.

Not a fan, but not against it. The machinery that's able to pass blobs to other apps based on their mimetype is a cool thing to have. I would start with it.

**Comment by uroybd** [comment]
@pazos 

I can implement the basic with at least markdown export tomorrow. If you find it viable, we can proceed perhaps?

**Comment by pazos** [comment]
Again, using https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt#L258-L266 directly will work for little text files, not for the whole history.

> I can implement the basic with at least markdown export tomorrow. If you find it viable, we can proceed perhaps?

Please don't. First make sure you're able to send files of arbitrary sizes across process boundaries. Even if we only want to pass plain text we need that.

**Comment by uroybd** [comment]
By 'whole history' do you mean exports from all books? I was thinking share only for one book though. Even for that we need to think about file size. I'll check just that.

**Comment by pazos** [comment]
Actually, based on https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/CrashReportActivity.kt#L28-L36, looks viable for bigger texts than I would expect.

I remember I had to put the text into a temporary file instead of pasing it as part of the bundle but, once it reaches the crash report activity, it is shared ok with a send intent.

**Comment by uroybd** [comment]
> Actually, based on https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/CrashReportActivity.kt#L28-L36, looks viable for bigger texts than I would expect.
> 
> I remember I had to put the text into a temporary file instead of pasing it as part of the bundle but, once it reaches the crash report activity, it is shared ok with a send intent.

Yes, it has an 1mb limit I guess. One mb of export is quite large.

**Comment by uroybd** [comment]
So... if it shares okay with send intent, should I try sharing?

**Comment by pazos** [comment]
> So... if it shares okay with send intent, should I try sharing?

Why not :p.

I prefeer you to use your talent with stuff like https://github.com/koreader/koreader/issues/6974 or switching to rapidjson/pretty print on the json exporter. But you are you and you must follow your heart :)

**Comment by uroybd** [comment]
> > So... if it shares okay with send intent, should I try sharing?
> 
> Why not :p.
> 
> I prefeer you to use your talent with stuff like https://github.com/koreader/koreader/issues/6974 or switching to rapidjson/pretty print on the json exporter. But you are you and you must follow your heart :)
> 

Rapidjson seems like a easy thing. Epub meta parsing can be relatively tricky, I'll tend to them both soon. :)

**Comment by uroybd** [comment]
Implemented in #9153
