### ISSUE TITLE
Highlight menu does not show up when full stop is placed at line end

### ISSUE THREAD

**Issue by Atrate** [koreader/koreader#9169]
* KOReader version: 2022.05.1 (FDroid)
* Device: Onyx Boox Note 3

#### Issue
When trying to highlight a sentence/group of sentences that end with a full stop right at the rightmost edge of the screen, the highlight menu does not show up.

#### Steps to reproduce
1. Open an EPUB book (probably any reflowable)
2. Find a sentence that ends in a full stop right at the right margin, so that the next sentence starts in a new line\
3. Try highlighting that sentence up to and including the final full stop\
4. Get angry

#### Additional comments
Highlighting sentences with their corresponding punctuation at the end is very clunky and often takes multiple tries or requires editing the highlight via the provided buttons in edit mode. I see of no reason why KOReader shouldn't include the full stops automatically in highlights. Related issue: #4134, seems not to be solved fully.

**Comment by poire-z** [comment]
> I see of no reason why KOReader shouldn't include the full stops automatically in highlights

https://github.com/koreader/koreader/issues/6217#issuecomment-636513399
May be some heuristics depending on the length or how many words are in the selection.

Also #8857.

I think there are 2 issues you might have met:
- this thing about including punctuation or not - so if you end of the last word, it won't include the punctuation.
- but most probably the fact then when the highlight position is outside the page (that is, outside the inner page view, inside KOReader's margins), the highlighting process goes pfiouuu (because the final position, being outside, does not map to something in the book content, I think). If you try highlighting away from a smaller line, it would include the punctuation:
![image](https://user-images.githubusercontent.com/24273478/172006901-d3208ff8-b7c4-44e3-8938-adb13a710223.png)

**Comment by Atrate** [comment]
> but most probably the fact then when the highlight position is outside the page (that is, outside the inner page view, inside KOReader's margins), the highlighting process goes pfiouuu (because the final position, being outside, does not map to something in the book content, I think). If you try highlighting away from a smaller line, it would include the punctuation:

Indeed, that's exactly what happens, lines that end before the edge of the screen work fine.
