### ISSUE TITLE
 pt font-size is badly displayed

### ISSUE THREAD

**Issue by roger64** [koreader/koreader#9177]
* KOReader version: 2022.05
* Device:PW3 (Kindle)

#### I have converted a MOBI file to ePub using Calibre.  Three of the used styles in the css had a font -size  expressed with pt values. All three were displayed in the same faulty way (hardly legible), though they had different values (9pt, 13.5pt). 

Everything went OK when changing to em values.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
The bottom menu has a DPI setting, confusingly distinct from the other DPI. It has to do with not necessarily wanting scaling on images I think, but presumably pt is also affected.

**Comment by poire-z** [comment]
Yes, set that bottom menu to 300 dpi, and you'll get real sizes (and long-press on 300dpi to have it by default in you want that - but remember you did when you see things too large on some books).

I think we stick with having the default to 96dpi (and my gut feeling is to insist keeping it) because some books may more often use units in `pt` for margins (ie. any Word document), and with 300 dpi, we may often get really huge margins (possibly a few cm on each side) - and it's easier counteracting that generally with a default of 96dpi - and letting the the rarer cases of `pt` being used with font sizes and giving small font sizes to the user switching to 300 dpi only when needed (which I may have to do for one book every other 50 books I read).
