### ISSUE TITLE
FR: Copy button in Vocabulary builder

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9180]
My request may seem a little strange.
To learn new foreign words and expand my vocabulary I use the Anki app. As I have read and see in practice, it is easier and more useful to learn a new word in its context. You can see how the word works that way. So I tend to copy into Anki the whole sentence containing the word I want to learn.
As I don't have much time to add many words to Anki, I found the new "Vocabulary Builder" plugin in the nightly version very useful, which I use as a supplement.
Of course, using "Vocabulary Builder", it's not possible to see the word in its context. But I can have the word's source book open and look it up in the book. For this purpose it would be useful to have a copy button in the three-dot menu, otherwise it takes a long process.
Would that be easy? What do you think @weijiuqiao?

**Comment by weijiuqiao** [comment]
Glad that the plugin is useful to you, it's also my main tool to learn new words for now. Your request doesn't seem difficult to implement, but even with it, it still seems a bit too clumsy to get what you want: copy the word, close the plugin, open the target book (if not already open), search for the word, find the right one of possible many occurrences... 

What if we could have the context of word used readily available within the plugin? Theoretically it wouldn't be impossible. But I will need @poire-z and other core contributors to help assess how feasible and necessary it is. If it's quite possible, I'd be happy to add this feature.

Also, currently when a word has been reviewed (got it) for a certain number of times, its three-dot button is replaced with a delete button for quick deletion, since you might have remembered it already. I think this won't have to change even if we add more functions to the tree-dot, as it's presumably intended only for unfamiliar words. What do you think about this setup?

**Comment by poire-z** [comment]
> What if we could have the context of word used readily available within the plugin? Theoretically it wouldn't be impossible. But I will need help assess how feasible and necessary it is. If it's quite possible, I'd be happy to add this feature.

A few thoughts:
- define "context" :) a certain number of chars or words on each side (dunno if that number could be the same and give the same amount of "enough context" for all languages, ie. small CJK, long German...), the sentence, the paragraph ? Might change depending if small lines of dialog where a paragraph is super smal, or big paragraphs spanning multiple pages in essays.
- in PDFs, you can't grab any context I think, it's all just rectangles, you can't guess continuity
- in CRE, you could, you can move the start and end xpointers by char, word, sentence (but the `Is/Get/Next/SentenceStart/End()` functions are a bit limited and use only western punctuations - they are used by CoolReader text-to-speech, best to not touch them, or keep in mind how they are used to not break this) - and you could stop or cross paragraphs. It's all the methods of ldomXPointerEx, not super fun to hack. credocument.lua or base/cre.cpp provides proxy functions - might be enough to add more in there if the low-level stuff in crengine is enough.
- when lookup a word, you have the xpointer of start or end - we don't use them for a simple lookup, but you would need to pass them to your plugin to store and remember the position in the book
- you could also pass and store the xpointers of start and end of the context, with the text (if you don't want to need to open the book to fetch the text).
- I'd prefer all this to happen in the plugin - to avoid this to be done in readerdictionary or readerhighlight where it won't be used.
- (the vocabulary.sqlite3 that was made after my recent update was a few 100Kb sized - with context, it will get bigger, might want to store the context text compressed)
- for the necessity, I can't say as not using it (but I'll say "not useful" if you insist :) - I think there must be one or two github Issues where some people have requested somethinkg like that though.

**Comment by weijiuqiao** [comment]
> * define "context" :) a certain number of chars or words on each side (dunno if that number could be the same and give the same amount of "enough context" for all languages, ie. small CJK, long German...), the sentence, the paragraph ? Might change depending if small lines of dialog where a paragraph is super smal, or big paragraphs spanning multiple pages in essays.

I played a bit with Prev/Next/This/SentenceStart/End, and found that they often result in quite big sentences (and sometimes too small ones). So I'm thinking about a fixed number of words before and after the selected one, say 15 or 20. It still will have its own problems but I haven't got any other good ideas. (Limit the char count maybe? But if it's just a few German long words, then they wouldn't make a good context? Or maybe they do...)

> * in PDFs, you can't grab any context I think, it's all just rectangles, you can't guess continuity

So we are out of luck here.

> * in CRE, you could, you can move the start and end xpointers by char, word, sentence (but the `Is/Get/Next/SentenceStart/End()` functions are a bit limited and use only western punctuations - they are used by CoolReader text-to-speech, best to not touch them, or keep in mind how they are used to not break this) - and you could stop or cross paragraphs. It's all the methods of ldomXPointerEx, not super fun to hack. credocument.lua or base/cre.cpp provides proxy functions - might be enough to add more in there if the low-level stuff in crengine is enough.

I don't think I'll go down to the cpp code in this one :)

> * when lookup a word, you have the xpointer of start or end - we don't use them for a simple lookup, but you would need to pass them to your plugin to store and remember the position in the book
> * you could also pass and store the xpointers of start and end of the context, with the text (if you don't want to need to open the book to fetch the text).

On my kindle, opening up a book seems quite some heavy work with the loading (If cached, it's better?). So I'm not really 
considering the option to save positions instead of just the sentences. It would however save much storing space. If opening books and jumping to locations are actually lightweight, then it'll be an obvious better choice.

> * I'd prefer all this to happen in the plugin - to avoid this to be done in readerdictionary or readerhighlight where it won't be used.

Agree.

> * (the vocabulary.sqlite3 that was made after my recent update was a few 100Kb sized - with context, it will get bigger, might want to store the context text compressed)

Saving the context, if not pointers, should be an opt-in feature than default, then it should be alright. (Btw you have looked up quite a lot of words :) you know you can always clean the db in the plugin's menu. ) I haven't meddled with much with compression, seems a rabbit hole.

> * for the necessity, I can't say as not using it (but I'll say "not useful" if you insist :) - I think there must be one or two github Issues where some people have requested somethinkg like that though.

Haha, actually I personally think it's a useful thing to have, as I'd want to use it too.

**Comment by poire-z** [comment]
> So I'm not really considering the option to save positions instead of just the sentences. It would however save much storing space. If opening books and jumping to locations are actually lightweight, then it'll be an obvious better choice.

There's also the case where the user deletes the book once read (like I do), so you can't really rely for the book to be present - so indeed, better to save the text and forget about positions.

> I haven't meddled with much with compression, seems a rabbit hole.

Could just be a few added lines (search for "zstd" in plugins/coverbrowser.koplugin/bookinfomanager.lua, we use it to compress the rendered cover).
But if you want to allow this vocabulary.sqlite to be transfered and used/loaded by other apps/tools, best to keep it plain/uncompressed.

**Comment by ichnilatis-gr** [comment]
> Also, currently when a word has been reviewed (got it) for a certain number of times, its three-dot button is replaced with a delete button for quick deletion, since you might have remembered it already. I think this won't have to change even if we add more functions to the tree-dot, as it's presumably intended only for unfamiliar words. What do you think about this setup?

I have the experience of the Anki app, where the word repetition interval simply grows and the word is never deleted.
However, I have no problem with your choice. Anything added to the three-dot menu is for the word revision and will not be needed after having learned the word.

**Comment by ichnilatis-gr** [comment]
> What if we could have the context of word used readily available within the plugin?

I could never have imagined it would be possible!
Thank you!
