### ISSUE TITLE
FR: extract and show font name when Embedded Font is enabled

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9190]
**Does your feature request involve difficulty completing a task? Please describe.**
That's a minor thing, but I think this might improve the UX quite a bit.

**Describe the solution you'd like**
In the `Font` menu, show that 1) the font is currently overridden by embedded fonts; 2) the font name of the font from the embedded style. 

**Describe alternatives you've considered**
The only KOReader-way to see this is by knowing that this setting is enabled, and knowing how to use HTML viewer and then to see the appropriate style css, then to find the font.

**Additional context**
I understand that enabling Embedded fonts most of times involves multiple font names. So maybe there should be at least mentioning that the fonts are overridden?

Use case is simply: to make KOReader even more user friendly when selecting fonts. 

P.S. Also I think that styles and fonts toggles should be in the same place with general fonts and styles. The same goes for Alt Status bar

**Comment by poire-z** [comment]
It's not really that the main font is generically overriden - but that some HTML DOM nodes use some other font.

What we may know:
- that there are embedded fonts in the EPUB

What we can't easily know (in order of not-easyness):
- if these embedded fonts are really used
- to what/how much content they apply
- if the what/how much is big enough for the user to consider his main font is overriden

That is, some embedded fonts can be used for some small snippets of Greek - or just for titles - leaving the paragraphs of text intact. Or they can apply to these paragraphs, or only some of them.
So, counting, statistics, heuristics... not easy.
While it's quite easier for a user to notice something's not right/usual :) - and that embedded fonts might be used instead of my preferred one (and sometimes, I have doubts, is this my font at a smaller font size I'm not used to - or some other one? and rarely, it's not even an embedded font but just a font referenced by name that I happen to have in my font folder).

> P.S. Also I think that styles and fonts toggles should be in the same place with general fonts and styles. The same goes for Alt Status bar

Not opposed to that - but currently, they contribute to making the last panel 4 items just like all others. The day we need another bottom widget for CRE, these would be candidates to be moved away to leave room for the new stuff.

**Comment by mergen3107** [comment]
`What we can't easily know (in order of not-easyness):`
Ah, I see! Thanks, turns out I haven't such cases yet - all epubs with fonts I encountered replaced the whole sest of fonts in body, titles, etc.

So maybe just a mention in the font selection should included that `Embedded fonts` are enabled? What I initially try to counter is a situation when a user tries different settings, applies some fonts and then wonders why fonts don't change (much). 

`The day we need another bottom widget for CRE, these would be candidates to be moved away to leave room for the new stuff.`
I see. Thank you for explaining your stand point :)

**Comment by poire-z** [comment]
> So maybe just a mention in the font selection should included that Embedded fonts are enabled?

> What we may know:
    that there are embedded fonts in the EPUB

I guess that visually then, the Embedded fonts bottom toggle should go away (or stay, but that's duplicate functionality) - and in the font menu, between Settings> and the list of installed font, there could be a `[x] Allow embedded fonts` that would be disabled/grayed out when no embedded fonts are present - and enabled and toggable when there are.
(With the small caveat that the font menu opens on the page with your current main font - so this info may not jump to the face of the user - but browsing the font list pages, he would see it.)

**Comment by mergen3107** [comment]
`With the small caveat that the font menu opens on the page with your current main font`
Two thoughts here:
1) What if we "stick" that tick-mark option on each page? So that font list has still pages, but each of these contain the same setting. A little redundant, so how about
2) Move such setting to the top level, right below `Font` - so it will visible there (maybe in a common section separated by horizontal lines) to the one who goes after font selection.

**Comment by poire-z** [comment]
Both ideas would waste some space in these top menu for something that is usually not much of interest (and most often EPUB don't have embedded fonts - at least for most western languages books).

And because our bottom menu is painful - even moving a setting from it to the top menu would be painful - I can suggest the following (by just using what's possible with our bottom menu stuff):

- Keep the bottom toggle widget where it is
- Make it enabled only if there are embedded fonts in the book - so one can quickly see if there are or not. (Strangely, but that's good, we can see the help_text and even set a state as default even when it is disabled)
- And as a bonus, show in the help_text (when long press on "Embedded Fonts") the names of thesse embedded fonts:

When no embedded fonts:
![image](https://user-images.githubusercontent.com/24273478/173100687-f4d637e0-2683-4b37-ba73-bfcad632525a.png)

When embedded fonts:
![image](https://user-images.githubusercontent.com/24273478/173100864-ac5b1fe0-ebf3-497e-8d3d-5bec3d22ebd4.png)

![image](https://user-images.githubusercontent.com/24273478/173102047-032e059c-82d3-4efd-b2f2-a2bd5fe5fa9c.png)

We can also get "(not used)" when it happens you already have a font by that name in koreader's font folder (might be a bug that it is your font that is used and not the one embedded, but a minor bug I won't care about):
![image](https://user-images.githubusercontent.com/24273478/173101870-2879bff9-b2b2-48bb-a574-3616aae02600.png)

(I can see if the embedded font has been "instantiated" - and so is in use, even if it's for a single word in the whole book - and show "not used" if not.)
