### ISSUE TITLE
wifi status on bottom statusbar (pocketbook PB631)

### ISSUE THREAD

**Issue by EastEriq** [koreader/koreader#9191]
I would like to see the the status of wifi on the status bar. Under the cogwheel menu/ status bar/settings/prefix/icons I do see sample images with wifi and wifi off symbols, but there is no checkbox for it in  cogwheel/status bar. A pocketbook limitation, or a glitch?

**Comment by Frenzie** [comment]
Only on Android since it's blocking on other platforms, but also: https://github.com/koreader/koreader/pull/9185

**Comment by pazos** [comment]
Currently it requires `Device:hasFastWifiStatusQuery()`. Pocketbook isn't one of them.

**Comment by Frenzie** [comment]
Heh, I forgot we added it to some platforms other than Android.

**Comment by pazos** [comment]
Some platforms (most of them?) are using sysfs nodes to check if the wireless interface is associated with the AP.  I don't know if that's viable on pocketbook. (It should be exposed since 2.6.18 kernel but who knows with pocketbook).

If that's viable somebody needs to update the isWifiOn() function for pocketbook to use that and add the device definition for `hasFastWifiStatusQuery`. I also don't know how much time is the inkview call -- used currently-  blocking.
