### ISSUE TITLE
Koreader on Windows

### ISSUE THREAD

**Issue by chrox** [koreader/koreader#920]
I'm glad to announce that Koreader is ported to Windows. Though there are still some corner things to tweak and fix, Koreader for Windows can now open PDF and DJVU document without problem. I'll later send a PR on this.

The first Windows port is cross compiled with mingw-w64 on Ubuntu and run on Windows XP in VirtualBox.

![screenshot from 2014-09-23 21 29 01](https://cloud.githubusercontent.com/assets/751535/4372637/cc489bf6-4325-11e4-8de3-a31e1cccbde2.png)

**Comment by khariche** [comment]
Hi, would it be possible to have an updated windows port? or at least, does anybody know how to create, in windows, a file association to open all pdf files with koreader inside WSL (linux bash)?
Many thanks.

**Comment by Frenzie** [comment]
Never tried it, but there's https://github.com/4U6U57/wsl-open

**Comment by khariche** [comment]
Thank ou very much, but I think my request was not clear enough... in fact I want exactly the opposite : not opening linux files with windows applicatoins, but opening a pdf file from my windows explorer with koreader.

**Comment by ryanwwest** [comment]
I'd like this as well, this plus a good progress+annotations sync solution across devices would cover most bases since macos and linux already seem to be sort of supported...

**Comment by ryanwwest** [comment]
Got it working pretty well with WSL. Some issues (which aren't a huge deal): https://github.com/koreader/koreader/discussions/10372.

**Comment by richo67** [comment]
I have managed to run koreader quite easy under WSL1 and windows10:

- install [X11 server on windows](https://github.com/marchaesen/vcxsrv)
- install [koreader under wsl using deb package](https://github.com/koreader/koreader/releases)
- export following two variables under wsl shell `LIBGL_ALWAYS_INDIRECT` and `LIBGL_ALWAYS_SOFTWARE`
- start X11 on windows with at least _native opengl_ extra options turned on 
![image](https://github.com/koreader/koreader/assets/9590148/920f7319-6ced-4bfe-9fcb-9c896575c4ec)
- run koreader from the wsl shell `$ koreader`

**Comment by Frenzie** [comment]
You're likely aware, but in WSL2 you don't have to do anything. You can just run it.

**Comment by richo67** [comment]
@Frenzie I have read about it, but I like to use WSL1 to have direct access to files system and maybe I am just lazy :-) Anyway, I wrote it here for somebody who is also using WSL1.

**Comment by Agagamand** [comment]
> You're likely aware, but in WSL2 you don't have to do anything. You can just run it.

Windows 10 does not support WSL2.

**Comment by Frenzie** [comment]
That's not accurate.

**Comment by Agagamand** [comment]
> That's not accurate.

That's for sure. Or tell me how to install WSL2. I've tried.

It is also for sure that there is no need to install X11 server on windows.

**Comment by Frenzie** [comment]
Tried what?

This is the first search result for how to install: https://learn.microsoft.com/en-us/windows/wsl/install

There's one requirement:

> You must be running Windows 10 version 2004 and higher (Build 19041 and higher)

**Comment by Agagamand** [comment]
> There's one requirement:

On Win10 LTS (19044) it is impossible to install.

**Comment by Frenzie** [comment]
At which step does impossible happen? What does it say at the point where it fails?

**Comment by Korb** [comment]
> The first Windows port

Can you put a download link for the current version of the app for Windows in the first post? Because in this repository only versions for

> Cervantes, Kindle, Kobo, PocketBook and Android devices

are still published.

**Comment by Frenzie** [comment]
There's no current version. The open ticket is #7653.

**Comment by Svetloslav** [comment]
I agree there should not be an opened thread for a Windows port, since a true, native solution does not exist! All the Linux on Windows emulation is a waste of time. There are currently quite a few projects on Windows, which in functionality put in the dust any pseudo "emulation" through virtualization be it of Linux, or Android. For those on a tight budget, there is SumatraPDF, which is the Swiss army knife. It opens all electronic publications. For those inclined on a comfortable ebook reading on Windows desktop, laptop, or tablet can go to the edrlab Thorium reader project, actively developed with daily builds on git. There is calibre, in active development. And for small amounts of money there are other commercial products as well. Forget about koreader. Devs want to keep it into the linux realm, be it so, who cares.

**Comment by pazos** [comment]
>  And for small amounts of money there are other commercial products as well. Forget about koreader. Devs want to keep it into the linux realm, be it so, who cares.

The comment is right on spot. If a native port for windows becames reality is because a contributor or a maintainers adds a port. Not because a random user whines on the wrong ticket.

So fellow windows enthusiast: follow what he says, not what he does: stop whinning about proper support unless you want to commit it yourself. If want to cry please use a commercial product, which should give you an entitlement to whine via email to your masters.

If somebody has questions, not whinnings, please use the proper ticket.
