### ISSUE TITLE
Sync doesn't work. Linux AppImage

### ISSUE THREAD

**Issue by DarkRookie00** [koreader/koreader#9224]
* KOReader version: 2022.05.1
* Device: Linux AppImage

#### Issue 
Sync doesn't work. It doesn't seem to be able to push and pull. Was able to log in and register accounts, but when using the same account on a Kobo Sage and an Android, it never syncs from the desktop. Can between the ereader and phone

**Comment by pazos** [comment]
Sync works on the same file. The **exact same file**. You can check that with md5sum, sha1sum, sha256sum et all.

Syncing a file with a different hash will result in a new "book" to sync. Your other devices won't pull/push from/to your new "book" since they're pulling/pushing from/to a different file.

Any changes you did on a file will result on a different hash. Also calibre, in its default config, does mess with files when pushing.

**Comment by DarkRookie00** [comment]
OK. That is new. What setting in Calibre needs to be disabled to prevent changes when pushed.
