### ISSUE TITLE
Kobo Sage very slow on page turns

### ISSUE THREAD

**Issue by Justalurker1213** [koreader/koreader#9306]
* KOReader version: Latest Nightly 2022.06-27
* Device: Kobo Sage

#### Issue

Page turns feel very slow. In Nickel, page turns are near instant but KOreader takes a second or longer sometimes to turn pages. I attached a video.

##### `crash.log` (if applicable)
Attached

</details>

https://user-images.githubusercontent.com/22498617/177996473-388a51dc-74a4-4761-acbc-7275a087d11e.mp4

**Comment by scsmartt** [comment]
[crash.log](https://github.com/koreader/koreader/files/9072204/crash.log)

**Comment by scsmartt** [comment]
I tried to take a longer video but Github only allows 10MB so I had to trim it down a lot.

**Comment by poire-z** [comment]
Looks like there is a "update progress..." on each page turn, by the kosync plugin ("Progress sync") - which seems to do a HTTP request, so on each page turn, which may explain this delay (because I think, as everything else in KOReader, it's not threaded, so it blocks the app/ui/screenrefresh while the http request is being made).
Try disabling this plugin, to be sure it's not something related to the book. If it's then ok, good.
Then, may be decrease the frequency/rate of syncing (no idea how this plugin work and what settings are available).

**Comment by poire-z** [comment]
> The _only reason_ I use KOreader instead of Nickel though is for the progress sync

That hurts :/ :)

Well, I don't know how other users uses it, if they also get this slowness/blocking.
But I see in the plugin code there is a menu `Progress sync>` which contains `Sync every # pages` , and it seems it would properly sync on suspend/close document if you enable `Auto sync now and future` - which might be enough if you use sync because you use multiple devices - assuming you suspend one when about to use the other.

**Comment by mergen3107** [comment]
> That hurts :/ :)
> 
> Well, I don't know how other users uses it

Err, I just don’t use the plugin since my ereader is the only place I happily read books :D

**Comment by Frenzie** [comment]
With this in common/turbo/cdef.lua you can test `DUSE_TURBO_LIB = true` in defaults.persistent.lua.
[cdef.lua.zip](https://github.com/koreader/koreader/files/9074752/cdef.lua.zip)

**Comment by NiLuJe** [comment]
Quite likely fixed a few months ago with the KOSync cleanups.
