### ISSUE TITLE
Out of sequence entries break TOC

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#9319]
* KOReader version: all since https://github.com/koreader/koreader/pull/5907
* Device: all

#### Issue

See https://www.mobileread.com/forums/showthread.php?p=4237369 for more details.

<img src=https://user-images.githubusercontent.com/202757/178161572-8d4c27a3-bce1-4734-bf80-a113d385ef78.png width=45%> <img src=https://user-images.githubusercontent.com/202757/178161575-d0258f46-e95f-470c-8552-c1b5f26c0a5b.png width=45%>

#### Steps to reproduce

```
pdftk koreader-user-guide.pdf update_info bookmarks.txt output koreader-ug-with-toc.pdf
```

[toc.zip](https://github.com/koreader/koreader/files/9079842/toc.zip)

##### `crash.log` (if applicable)

```
07/10/22-22:37:07 DEBUG BOGUS TOC: 32 3 < 31 25 - 28 29
07/10/22-22:37:07 DEBUG   fix prev 31 25 => 1
07/10/22-22:37:07 DEBUG   fix prev 30 22 => 1
07/10/22-22:37:07 DEBUG   fix prev 29 21 => 1
07/10/22-22:37:07 DEBUG   fix prev 28 21 => 1
07/10/22-22:37:07 DEBUG   fix prev 27 21 => 1
07/10/22-22:37:07 DEBUG   fix prev 26 20 => 1
07/10/22-22:37:07 DEBUG   fix prev 25 19 => 1
07/10/22-22:37:07 DEBUG   fix prev 24 18 => 1
07/10/22-22:37:07 DEBUG   fix prev 23 17 => 1
07/10/22-22:37:07 DEBUG   fix prev 22 15 => 1
07/10/22-22:37:07 DEBUG   fix prev 21 15 => 1
07/10/22-22:37:07 DEBUG   fix prev 20 15 => 1
07/10/22-22:37:07 DEBUG   fix prev 19 14 => 1
07/10/22-22:37:07 DEBUG   fix prev 18 14 => 1
07/10/22-22:37:07 DEBUG   fix prev 17 13 => 1
07/10/22-22:37:07 DEBUG   fix prev 16 12 => 1
07/10/22-22:37:07 DEBUG   fix prev 15 12 => 1
07/10/22-22:37:07 DEBUG   fix prev 14 11 => 1
07/10/22-22:37:07 DEBUG   fix prev 13 9 => 1
07/10/22-22:37:07 DEBUG   fix prev 12 9 => 1
07/10/22-22:37:07 DEBUG   fix prev 11 8 => 1
07/10/22-22:37:07 DEBUG   fix prev 10 8 => 1
07/10/22-22:37:07 DEBUG   fix prev 9 7 => 1
07/10/22-22:37:07 DEBUG   fix prev 8 7 => 1
07/10/22-22:37:07 DEBUG   fix prev 7 6 => 1
07/10/22-22:37:07 DEBUG   fix prev 6 5 => 1
07/10/22-22:37:07 DEBUG   fix prev 5 5 => 1
07/10/22-22:37:07 DEBUG   fix prev 4 5 => 1
```

As far as I can tell commenting out the offending lines works just fine. Perhaps the issue was EPUB/crengine exclusive?

https://github.com/koreader/koreader/blob/22fe3933c34481169fec04796363142773b576c8/frontend/apps/reader/modules/readertoc.lua#L175-L178

<img src=https://user-images.githubusercontent.com/202757/178161524-f1b43d7a-f0f7-46de-8b5a-fef923b6a1eb.png width=45%> <img src=https://user-images.githubusercontent.com/202757/178161527-e79fdf76-fcf7-4716-a897-411a2fc9fdb8.png width=45%>
All entries work as expected and go to the correct page.

**Comment by poire-z** [comment]
There are 2 sequences of toc entries with increasing page numbers in this TOC: one pointing to all images, and then restarting to page 1, pointing to headings.
This might be fine for any other PDF reader that "just" displau the TOC as it is in some panel.
But KOReader uses the TOC for other things, like page left in current chapter, ticks... and it expects the TOC to be a single sequence of items pointing to increasing page numbers.
That's why it does this quick check at start, to see if the TOC entries are correct and increasing - and if not, it tries to fix them (because it needs them increasing), and may fix it in unexpected ways in some cases where there is no real solution (although in the case of this book, it does the right thing: the 2nd sequence of headings works - luck :)

We can't even just make a single sequence from these 2 sequences: it would be quite fragmented, and moreover, we wouldn't be able to keep the "depth", the nested structure of the TOC - I think fixing this would be impossible.
So, yes, KOReader expects the TOC to be a single sequence: this nice double-TOC can not work.

**Comment by Frenzie** [comment]
Closing for now then, but it seems to me the better solution would be to feed those other things a "corrected" shadow TOC. :-)

**Comment by poire-z** [comment]
I guess you could keep the original toc (before fixing) as self.real_toc, and use it only for the onShowToc() - but there is still the issue that if multiple branches of the tree contain the current page, which part of the tree to focus on and expand.
(Anyway, not willing to think about it until I meet such a book where I would care :)
