### ISSUE TITLE
Ghost input at the bottom left on Pocketbook

### ISSUE THREAD

**Issue by Danar435** [koreader/koreader#9324]
* KOReader version: 2022.06
* Device: PB970

#### Issue
This happens only when I use KoReader. While reading, the screen would register a tap at the bottom left, usually in quick succession from each other, and would trigger the function assigned to it. Crash.log looks something like this:

```
07/05/22-09:13:32 DEBUG single tap detected in slot 1 {
    ["y"] = 1199,
    ["w"] = 0,
    ["h"] = 0,
    ["x"] = 0,
}
```

When I press the home button, the same ghost input carries over to the PB OS. A temporary solution I've come up with is to put the device in sleep mode and back. But that's extremely cumbersome. This wasn't a big problem until recently, now seems to happen every 5 minutes. I have full screen refresh assigned to it, and making it do nothing is not a clean solution. I've already tried a clean install and formatting with no luck. 

#### Steps to reproduce
It happens randomly when reading

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/9095123/crash.log)

**Comment by NiLuJe** [comment]
The stock OS may have some sort of debouncing in place to avoid spurious inputs like that ;).

The simple TL;DR fact of it is: if we see an input event, then it means that there was an actual hardware input event ;).

**Comment by pazos** [comment]
> if we see an input event, then it means that there was an actual hardware input event ;).

:100: x :100: 

Smells like a hw failure. They're not that rare on touchscreens.

I guess it can be workarounded with something like https://github.com/koreader/koreader/search?q=self.input.adjustTouchTranslate.

**Comment by offset-torque** [comment]
This sounds very much like the Ghost Touch / Phantom Touch problem seen in cell phones/tablets. 

Generally it has three causes:
- Problematic charger (if it happens when plugged in)
- Screen protector (if it started after installing the protector)
- Hardware failure of the digitizer controller or the electrical circuit providing it (and rarely the flex cables and connectors)

If it is under warranty I highly suggest replacement because increasing severity you are witnessing points to a hw failure.
