### ISSUE TITLE
FR: Support RPM rather than solely DEB.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [koreader/koreader#9341]
**Does your feature request involve difficulty completing a task? Please describe:**

Installation of this into any of Red Hat's and SUSE's operating-systems, of which the immensely popular Fedora family and openSUSE are each one respective constituent, is inferior to the expierience that is provided to Debian and derivatives of it by the ".deb"-file that is provided.

This is because AppImage does not provide automatic replacement of itself when more recent versions are available without manual invocation of the ".AppImage"-file, files that it creates are difficult to know to remove during uninstallation, and it is unable to utilize any native libraries to fulfill dependencies.

This reasons are identical to why the ".deb"-files exist.

**Describe the solution you'd like:**

Please provide one ".RPM"-file to allow consistent installation into operating-systems that are designed to utilize RPM as their format of package-manager.

**Describe alternatives you've considered:**

One ".AppImage"-file is available at "http://github.com/koreader/koreader/releases/download/v2022.06/koreader-appimage-x86_64-linux-gnu-v2022.06.AppImage" and Flatpak and Snap are being considered at "https://github.com/koreader/koreader/issues/6349".

**Additional context:**

"http://github.com/koreader/koreader/issues/9305" appears to demonstrate that updates of ".AppImage"-files are currently inadequate, especially because "http://github.com/koreader/koreader/issues/9305#issuecomment-1178370636" appears to demonstrate that they do not (currently) support delta updates, whereas dnf already does.

**Comment by pazos** [comment]
That is not our duty.

We provide the debian package for convenience and because it costed us nothing (ie: our build environment is actually based on debian).

Also Debian is, by far, the most used distro outside x86_64 linux workstations (ie: raspberry pi & clones, chromebooks w/ linux support...). So makes sense to have a package ready for those who want to tinker with those esoteric boards :p 

But we won't attempt to provide support for each linux distro. There're many, requires too much work, no benefit for us and, most importantly: it is trivial to repackage the `.deb` package on your distro favorite package, as you can see in https://aur.archlinux.org/packages/koreader-bin

See also other related topics, where we talk about better appimage integration https://github.com/koreader/koreader/issues/9305 or releasing a generic `tar.gz` linux (buried in https://github.com/koreader/koreader/issues/9268)

Also see the Flatpak FR: https://github.com/koreader/koreader/issues/6349. This is also interesting if you don't particulary care about disk size or app launch time, and will work on all linux platforms. Is still way inferior to appimages, IMHO.

**Comment by pazos** [comment]
Closing this one. In the mean time @BEEDELLROKEJULIANLOCKHART and other RH/Centos/Suse/Fedora users are suggested to use `alien` agaisnt the debian package.

`sudo alien -r path/to/koreader.deb`
