### ISSUE TITLE
crengine: footnote line showed up too early

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9364]
* KOReader version: 2022.06 with fix from #9326
* Device: Onyx Boox Kon-Tiki 2

#### Issue
There is a footnote link at the very end of a page. The line is second to the last, so that's why I think the line of the footnote tried to be drawn. However, the line itself is meaningless. I think it would be better to not allow a single line to be drawn, making no page breaks between the line and the footnote text.

See screenshots:
Page 1
![f1](https://user-images.githubusercontent.com/6279855/180601384-9318ade0-963b-42f8-9a9b-b9558e58dfad.png)

Page 2:
![f2](https://user-images.githubusercontent.com/6279855/180601386-649d2e04-2d92-47f4-ac92-8ba9e72735b8.png)

**Comment by poire-z** [comment]
I think we should handle this case well, because otherwise, we would see that more often - and I never did.
So, I believe this is something with this book's footnotes styling, like each of them having some top margin - and this top margin actually makes a "footnote line" to display (a blank slice). At the point when we are handling footnotes, we don't know if a slice is actually some vertical padding/margin/border, some text, some empty line... and we also don't ensure break avoid/always between lines, which would be "AVOID" between some top margin and the first line of text (because it's complicated with footnotes, and also because we don't want to really ensure widows&orphans with in-page footnotes).
Or I have missed something with the alt/top status bar (that I often forget to test with it enabled...)

So, either it's some bad CSS selector for inpage-footnotes, and you grab some uneeded neighbour content.
Or it's the styling of each inpage footnotes, and, as we can't know that from the side of the code, it's left to the user to counteract it with style tweaks. You can try the new ones in "footnote fix-up", like "disable block margins".

**Comment by mergen3107** [comment]
@poire-z 
OK, thank you! 
I'll try to play around with style tweaks and check the actual footnotes' style.
Yes, this is a very uncommon occasion :D

**Comment by mergen3107** [comment]
I don’t think this happens too often to me. One thing that helps sometimes is to enable/disable widows/orphans in style tweaks.
