### ISSUE TITLE
Koreader freezing occassionaly on Nova Air C

### ISSUE THREAD

**Issue by scsmartt** [koreader/koreader#9396]
* KOReader version: 2022.07
* Device: Onyx Boox Nova Air C

#### Issue
Sometimes when I open Koreader, I get a white blank screen and nothing happens for about 5 minutes then it will load.
It also freezes for between 2 and 5 minutes when I try to go back to the file browser from within a book.
[crash.log](https://github.com/koreader/koreader/files/9233445/crash.log)

**Comment by scsmartt** [comment]
[crash.log](https://github.com/koreader/koreader/files/9230161/crash.log)

**Comment by pazos** [comment]
No log was attached.

If KO worked ok on previous versions it would be a matter of reverting bits of https://github.com/koreader/android-luajit-launcher/commit/9dc203e776c25c55970124fef6c00a470898f29d

**Comment by scsmartt** [comment]
I thought I attached it in the comment above but I will attach again here.

I only recently got the device so I do not know if it worked OK in previous versions unfortunately.
[crash.log](https://github.com/koreader/koreader/files/9233441/crash.log)

**Comment by mergen3107** [comment]
The file is again empty

**Comment by scsmartt** [comment]
Sorry about that. Not sure what happened there.

[crash.log](https://github.com/koreader/koreader/files/9233650/crash.log)

**Comment by pazos** [comment]
Hi. The crash.log shows issues that I've seen before on other onyx/qualcomm devices. There's a crash on the gpu stack that happens outside the program, but it is probably triggered by [`android.lib.ANativeWindow_unlockAndPost(android.app.window)`](https://github.com/koreader/koreader-base/blob/master/ffi/framebuffer_android.lua#L155).

It doesn't look like the culprit here. I have no clue. 

Probably running `pidcat org.koreader.launcher` and executing the app in a long session until you can reproduce the issue would give us some info. Pinging @ilyats, who also has this device.

Also a reminder that Onyx Boox is broken by design, so probably nothing to fix if this is not a regression caused by https://github.com/koreader/android-luajit-launcher/commit/9dc203e776c25c55970124fef6c00a470898f29d or https://github.com/koreader/android-luajit-launcher/commit/503e295cfc4e73edbc56463888dd4f27e8c73b6f

**Comment by ilyats** [comment]
I have previous model, Nova 3 Color, not Nova Air C

**Comment by pazos** [comment]
> I have previous model, Nova 3 Color, not Nova Air C

Sorry about that. The models are dancing in my mind and I'm not particulary good with fact checking :smile:

**Comment by mallomar** [comment]
@pazos Just checked with my wife. She hasn't had this problem on her Nova Air C.

**Comment by pazos** [comment]
Thanks!

Issues that happen randomly, without steps to reproduce and aren't being observed on the same device by other users are perfect candidates to be left in the void. Please ping me if somebody else is able to reproduce and attach a log, as requested in https://github.com/koreader/koreader/issues/9396#issuecomment-1203825431, so I can reopen.
