### ISSUE TITLE
FR: Automatically disable dictionaries based on document language 

### ISSUE THREAD

**Issue by rogarb** [koreader/koreader#9410]
Use case/issue
-------------
I read documents in different languages and I installed several dictionaries: language-specific dictionaries and language-to-language dictionaries.

When performing a dictionary lookup, this can lead to a lot of entries, which many are irrelevant, as all the dictionaries are activated, and also increase lookup time.

Feature request
-----------
Instead of manually selecting the enabled dictionaries per document, I would like an option to automatically select the dictionaries corresponding to the document language. It could also be a possible solution for the issue #6007.

Possible solution 
-------------------
So I came up with a [patch](https://github.com/koreader/koreader/compare/master...rogarb:koreader:dict_filtering), where the feature can be activated through a new option in the Dictionary settings.

This basically builds a languages table out of the dictionary name and then compares these languages to the language field of the document (and doesn't do anything if the document field is not present).

Issues so far
---------------
 * the StarDict format used by KOreader doesn't seem to support specifying the dictionary language => I chose to detect it through the dictionary name
 * the language field used in ebooks doesn't seem to be standardized or even always specified => I assumed it is a language code, i.e. "en" or "en_US"
 * in the current implementation, the automatically deactivated dictionaries still appear as active (i.e. ticked in the menu) and can't be reactivated for the current document without deactivating the feature. I am still thinking how to handle it.

Next
------
Feedback? 
Is the feature of interest for the project?
Problems that I didn't see?

**Comment by poire-z** [comment]
This feature would not be for me - and I'm quite fine with the lookup time and having many results, and when looking up a foreign word, it usually is found in the few foregn dicts I have and their results come first.
Anyway, some thoughts and ideas if we were to have that:

Among my 15 dictionaries, only 1 has a language code in its title. And only some of my foreign languages dicts have that language natural name in their title - and most have the French naming for that language (ie. Allemand, not Deutch nor German).
So, parsing the title is probably going to frustrate many users that would need to update the title in the .ifo.
So, if you want to allow better results, you could require the user to edit the .ifo of their dicts to add the missing "languages=" tag with the lang code(s) they want to associate to this dict. You could explain that in a help_text or in a `About matching languages only` top menu item.
We could also match the title against those of the dicts proposed for download in https://github.com/koreader/koreader/blob/master/frontend/ui/data/dictionaries.lua, and update their .ifo on download, or as a one-time migration for already downloaded dicts.

Once your user has a `languages=` for most/all its dict, and as we parse all the ifo, we could gather all the lang met and setup a menu of checkboxes (multiple choices) allowed listing all the available languages.
When opening a book with a language tag, just enable that language checkbox. Otherwise, enable all. Then, allow the user to check/uncheck the ones he want/want not - and save that as a "this book" setting.
(We have some data about lang codes found in books, and their mapping to a main language code at https://github.com/koreader/koreader/blob/9cba1904eecd33c15a71bbd6e63ee122a6aba510/frontend/apps/reader/modules/readertypography.lua#L31-L57.)

**Comment by rogarb** [comment]
Hi,

Sorry for the delay, I put aside Koreader and my ebook reader for a while, and didn't work on this issue at all. I am closing the issue as it didn't raise interest, might reopen it in the future if I happen to work on it.

Cheers

**Comment by Ceynou** [comment]
Is there a different solution to this day, the patch doesn't seem to work, and I don't mind having to edit ifo files for the name to start(or include) XX-XX language code.
I would prefer a GUI solution, is no one interested in this? I read in four language for now, so I need all the language dictionary installed like 20 of them, looking up a word takes ages.

**Comment by Frenzie** [comment]
You mean the patch no longer applies to master?

**Comment by Ceynou** [comment]
I applied the changes manually at the right places, I don't think I know how to do it conventionally, but that way it probably won't break what's already there(?)
[readerdictionary.txt](https://github.com/koreader/koreader/files/10688556/readerdictionary.txt)

**Comment by poire-z** [comment]
> I would prefer a GUI solution, is no one interested in this?

It doesn't feel obvious how we could do that, given the many little things at play:
- most users don't care (and are fine with results from all dicts, given that most of the time, you'll get those from the target language dicts which are the only ones that have what you request :)
- some books don't have lang= metadata
- dictionaries don't announces their language(s) (so it needs user hacks to them)
- depending on your book, say it annouces at FR=French, it may have DE=German quotes you want to be able to decypher, so your one rule may not even be all you want all the time

So, I think this is best left to [user-patches](https://github.com/koreader/koreader/wiki/User-patches), and users possibly adapting it to their needs, possibly having multiple ones, that they could toggle (now that we have a Patch manager) - and these user patches could be shared so other users with the same kind of workflow/mind as yours could just pick it.

For example by overriding https://github.com/koreader/koreader/blob/0e53631f48dfe23bb6dbb577692a489632968100/frontend/apps/reader/modules/readerdictionary.lua#L178-L204, calling the original one, and adding some user code at the end, to do some additional cleanup.
If I were to do one for me, I would decide that instead of hacking the .ifo, I could create empty filenames in the dict directory, named `fr` `en` `de` if that dict is fine with French, English and German.
Then, in the user patch, I would query the doc language (cf `Translator:getDocumentLanguage()`)  (strippint out anything but the first part), and if not empty, for each ifo in the list of usable ifo, get the dict dir, check for `dict_dir/<lang>`, and if present, keep that dict. If no dict "kept", reuse the original full list.

**Comment by Ceynou** [comment]
The obvious way would be the have a GUI setting similar to dictionary list where you can check and uncheck them but for the language of the current book, then it will output a setting file with the path of the dictionaries and why not custom names, a file that will be read when you do a lookup.I barely know anything in programming, but lua is more familiar to me so I might try at some point.On Feb 9, 2023 12:34 PM, poire-z ***@***.***> wrote:

I would prefer a GUI solution, is no one interested in this?

It doesn't feel obvious how we could do that, given the many little things at play:
most users don't care (and are fine with results from all dicts, given that most of the time, you'll get those from the target language dicts which are the only ones that have what you request :)some books don't have lang= metadatadictionaries don't announces their language(s) (so it needs user hacks to them)depending on your book, say it annouces at FR=French, it may have DE=German quotes you want to be able to decypher, so your one rule may not even be all you want all the time
So, I think this is best left to user-patches, and users possibly adapting it to their needs, possibly having multiple ones, that they could toggle (now that we have a Patch manager) - and these user patches could be shared so other users with the same kind of workflow/mind as yours could just pick it.
For example by overriding https://github.com/koreader/koreader/blob/0e53631f48dfe23bb6dbb577692a489632968100/frontend/apps/reader/modules/readerdictionary.lua#L178-L204, calling the original one, and adding some user code at the end, to do some additional cleanup.
If I were to do one for me, I would decide that instead of hacking the .ifo, I could create empty filenames in the dict directory, named fr en de if that dict is fine with French, English and German.
Then, in the user patch, I would query the doc language (cf Translator:getDocumentLanguage())  (strippint out anything but the first part), and if not empty, for each ifo in the list of usable ifo, get the dict dir, check for dict_dir/<lang>, and if present, keep that dict. If no dict "kept", reuse the original full list.

**Comment by NiLuJe** [comment]
You'll hit a roadblock because of the aforementioned points:

> * some books don't have lang= metadata
> 
> * dictionaries don't announces their language(s) (so it needs user hacks to them)

**Comment by Ceynou** [comment]
> You'll hit a roadblock because of the aforementioned points (specifically the lack of standardized dictionary metadata):
> 
> > * some books don't have lang= metadata
> > * dictionaries don't announces their language(s) (so it needs user hacks to them)

Like I said, you choose the dictionaries you want to enable based on the language of the book not of the dictionaries, so it only depends on user input
