### ISSUE TITLE
Crash after opening very large CBZ

### ISSUE THREAD

**Issue by mrtambour** [koreader/koreader#9430]
* KOReader version: 2022.06
* Device: Kindle Paperwhite 5

**Issue**

Koreader crashed after opening very large CBZ and bricked Kindle Paperwhite 5. The CBZ is 450MB

**Steps to reproduce**

Open large CBZ in continuous mode 

Scroll down a bit

Switch to page view mode

Go forward a page or two

I can't provide logs because the Kindle is bricked and its been stuck in a bootloop for about 24 hours now. The steps above were the last things that I did before it froze for a second and then the kindle restarted.

**Comment by NiLuJe** [comment]
There's no sensible reason for that to affect the stock OS, but, yes, that would definitely crash a Kindle (probably any 512MB device, actually), because MµPDF doesn't do mmap'ed IO, so the whole thing has to fit in RAM.

**Comment by NiLuJe** [comment]
Do try an actual cold, hard reboot, because I suspect the OOM kill initially only caused a framework restart, which may not actually work given the stuff we kill on startup (and given the other stuff the OOM killer may have murderized).

Been a while, but that involves a cold poweroff by long (as in, long-ass, ~15s) pressing the power button; and then a powerup a few dozen seconds later.

You may or may not need a shell (either SSH if enabled at boot), or serial (if that's even a thing on a PW5?), depending on how badly the framework failure counter racked up points.

**Comment by Frenzie** [comment]
> but, yes, that would definitely crash a Kindle (probably any 512MB device, actually), because MuPDF doesn't do mmap'ed IO, so the whole thing has to fit in RAM.

Huh? I've read a whole bunch of 450 MB CBZ files from Humble... or did I opt for the PDF...

**Comment by NiLuJe** [comment]
Huh, I *may* be mixing up CBZ vs. PDF behavior...

In any case, it would *definitely* OOM a Kindle, because Kindle ;).

**Comment by mrtambour** [comment]
Ive tried tried holding the power button for 15, 30, 45 seconds and it just keeps turning off and on on its own. The screen just keeps going blank and then the kindle tree image shows up and after a while it goes white and the image shows up again all in a loop.  I think I might just let it run out of battery and try again after charging. Thank you for the info though everyone.
