### ISSUE TITLE
FR: Add Slovak virtual keyboard

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#9440]
Hello KOReader team,

I have created Slovak virtual keyboard. Below are screens with preview of layouts. I have tested it on PocketBook Touch Lux 3 (626). Could you please validate the .lua files and merge it with KOReader?

Thanks

[SK_virtual_keyboard_source_files.zip](https://github.com/koreader/koreader/files/9338449/SK_virtual_keyboard_source_files.zip)

**Standard:**
![SK_standard](https://user-images.githubusercontent.com/29783895/184672207-3461ef70-7919-47d1-92e9-eb111fbbd884.jpg)

**Standard + shift:**
![SK_standard_shift](https://user-images.githubusercontent.com/29783895/184672416-d58514a3-8694-45bc-8857-f48bdae7c556.jpg)

**Special:**
![SK_special](https://user-images.githubusercontent.com/29783895/184672514-efd7dc8e-53f2-4176-b2fe-f97424ad1ecf.jpg)

**Special + shift:**
![SK_special_shift](https://user-images.githubusercontent.com/29783895/184672564-6b0c292a-2923-482b-8a98-34c6f2562240.jpg)

**Special (greek):**
![SK_special_greek](https://user-images.githubusercontent.com/29783895/184673142-9759ef78-0264-4ed7-a601-0001517ea5e1.jpg)

**Special (greek) + shift:**
![SK_special_greek_shift](https://user-images.githubusercontent.com/29783895/184673181-0f7d7f9f-eaa9-419f-b5d3-f1faac8d380c.jpg)

**Comment by Frenzie** [comment]
The files look fine to me at a glance. You don't want to try a PR yourself?

**Comment by poire-z** [comment]
I haven't looked at the files, but from the pictures, it looks like a quite alien keyboard layout, compared to all the other recent ones (en, fr, es, de, ru...) that @mergen3107 updated some months ago, see #8089 (and earlier discussions in #7972).
I mean someone switching to the slovak keyboard, for easier access to slovak letters, should get the same symbols we get in the EN and RU keyboards in the other layout, and the same kind of keypopups (at least, the one on the numbers - you could reorganize the ones on the letters so usual sloval variations of the `o` or `a` are used instead of the `ô` or `à` we may have favorized in FR for example).
And there probably should be the number digits in the first row on the first layer.
If slovak users need to imput greek, the logic is for them to switch to the Greek keyboard. If it's a very common task, you could add some greek letters in the keyboard popup (ie. alpha as swipe south from the <kbd>a</kbd> - may be you don't need all the variations Greek users can get from the Greek keyboard).

You made a slovak keyboard to your liking (with a lot of empty keys :) but it's quite alien and different and not koreader-standard :/
There are others old not-yet-made-standard layouts, but I'm not sure we want to add another one to this set of old ones. (Some very foreign ones like Japanese, Korean or Indian can probably not be made standard - but Slovak feels not that remote :)

(Unless other sloval readers can confirm this is the kind of layout they get on a computer physical keyboard, and it's really what they wish to have on KOReader :)

**Comment by offset-torque** [comment]
I can confirm that **`standard`** and **`standard+shift`** keys are accurate.
On a standard SK layout, first row looks like this:
![sk keyboard layout](https://user-images.githubusercontent.com/84420582/184757135-3ed3f292-adcd-4092-bcbe-e7d4bb9b93c2.jpg)


Green characters are what you get when you press that keys (without SHIFT).
You get the numbers with SHIFT.
Red ones are not relevant.
(They belong to Czech language but all physical keyboards are CZ/SK hybrid layout.)

So in terms of expectation, I guess we can say this is what a Slovak user would expect coming from a computer.

About keeping the number row, PC keyboards generally have a numpad so losing this row is not a big deal.
But here we have to consider benefit of entering numbers vs special characters and for that I think we need input from users who use the SK layout daily.

---

In this KOReader layout, users have to open `special` layout for some characters, colored red in the image (green ones are available on the number keys). Incorporating red ones into the popups too might be faster and more streamlined (assuming number row is kept for letters - otherwise all special characters should also go to popups).


**NOTE:** **`special`** layout is missing one character it seems (y with dlzen).

![sk special layout colorized](https://user-images.githubusercontent.com/84420582/184767834-4edb8dc8-51fb-4e4c-9ba3-de026f946146.jpg)

**Comment by sonix-github** [comment]
Hello KOReader team,

thanks for comments. I have reworked the layout. So now are "Slovak" only 2 layouts Standard and Standard + shift. Other are visually almost the same as for English layout except for "Slovak" letters in popups are interchanged so now are "Slovak" letters moved to east/west. And on first row I added all special "Slovak" letters to popups also.

Could you please check if it is now OK?

Thanks

@offset-torque Yes, you are right `ý` was missing in Special layout

[SK_virtual_keyboard_source_files_updated.zip](https://github.com/koreader/koreader/files/9354031/SK_virtual_keyboard_source_files_updated.zip)

**Standard:**
![SK_standard](https://user-images.githubusercontent.com/29783895/184970290-7a9f93a5-0330-4a19-8935-d2bc2085355e.jpg)

**Standard + shift:**
![SK_standard_shift](https://user-images.githubusercontent.com/29783895/184970334-53734802-3402-4cad-8fbc-7b890c6ca2c2.jpg)

**Comment by sonix-github** [comment]
> You don't want to try a PR yourself?

@Frenzie I can try it. But I have very very little experience with it. But firstly I am going to read about it how to do it :)

**Comment by poire-z** [comment]
I won't ever use this keyboard, but, even if better than the first iteration, it still feels a bit too different from the other western languages layouts:
- numbers in the top row of the standard first layout, for ease of access
- the shift and symbol keys named "shift" and "symbol" - probably because that talks to you better than our icons for them - but well, it adds to the "alien" feeling :) is that really needed for other slovak users ?

Anyway, I'll let @offset-torque have the final word and validates if the access to this set of "accentuated" slovak letters is really more worth to a slovak users than numbers/digits.

**Comment by offset-torque** [comment]
I am currently out of the city. I will post a detailed response once I get back to a computer (~2 days).

**Comment by offset-torque** [comment]
**DISCLOSURE:** I occasionally read Slovak texts on my Kobo and never took notes in that language.
I will try to emulate a native Slovak KOReader user's perspective.

- I agree with @poire-z's points. Details below.


**1. Shift and Symbol keys:**

There is no need to change **Shift**. There is no need to spell it.
That is a pretty standard symbol at this point. All PC and mobile keyboards have it.

**Symbol** can be more controversial but I still suggest using the same character in the English keyboard for familiarity and unity. I agree, that symbol might not be very descriptive of the function, but users has to learn it only once so that is not a big cognitive effort. Also it is shared across other keyboards so it will be less confusing when switching between ENG and SVK for example.


**2. Number row and accentuated characters (AC):**

Here I suggest switching standard and shifted layouts (I am referring to your last post).
Which means: **Numbers on tap and AC on swipe up**

Numbers can be useful when taking notes. They are used when referring to chapters, page numbers, entering dates etc. 
So keeping the number row accessible as default is a good idea. 
Slovak characters can still be entered with a swipe up easily.
A swipe up is nearly equivalent to a tap (user effort and delay wise).
It won't be a burden for users who want to use AC, and we won't deny direct number access to the other users.

**So my suggested Slovak standard layout would look like this:**

![svk_suggested_layout](https://user-images.githubusercontent.com/84420582/185788107-a2ab8a54-18bd-469b-b77e-75174380c4ff.png)


**But also I am curious about this: "Will that number row AC really speed up the text entry in Slovak ?"**
Because if a user wants to take accurate notes with the accentuated Slovak characters, they will still need 8 more characters that is not available on the number row. So they will still have to spend extra effort to be able to enter accurate text (via long tap and select). Only half of the AC could be entered quicker with the number row.

**Comment by poire-z** [comment]
> **So my suggested Slovak standard layout would look like this:**
> 
> ![svk_suggested_layout](https://user-images.githubusercontent.com/84420582/185788107-a2ab8a54-18bd-469b-b77e-75174380c4ff.png)

I guess you meant the first row of the Slovak standard layout, with numbers - the remaining rows staying with **lowercase** letters (unlike on this screenshot), right ?

**Comment by Frenzie** [comment]
> There is no need to change Shift. There is no need to spell it.
That is a pretty standard symbol at this point. All PC and mobile keyboards have it.

You say that as if it wasn't already pretty standard in the 1950s, long before those new-fangled "PC" things. ;-)

**Comment by offset-torque** [comment]
> I guess you meant the first row of the Slovak standard layout, with numbers - the remaining rows staying with lowercase letters (unlike on this screenshot), right ?

Yep, surely. I forgot to mention that. I took that image from the OP's last post that's why it is uppercase.
Basically all I am saying is **"Numbers = tap / accented = swipe up"**. No other changes (except that **shift** and **symbol**).

> You say that as if it wasn't already pretty standard in the 1950s, long before those new-fangled "PC" things. ;-)

I think electric typewriters were still spelling **SHIFT**. Later they started writing **SHIFT+Arrow** together around 386 times and later.
Then single arrow started increasing and mobile keyboards with their cramped layout dealt the death blow to the spelling.
But my point was **"our user demographic definitely recognizes the SHIFT arrow"** :)

**Comment by Frenzie** [comment]
> I think electric typewriters were still spelling SHIFT. Later they started writing SHIFT+Arrow together around 386 times and later.

They did all of those things. Some typewriters would say shift in their respective languages, some would leave it English, some said something like upper case or lower case, many would just leave it empty with a *down* arrow for shift lock, some would use an up arrow for shift lock, some would leave the modifiers all empty. From some point onward there was a bit more uniformity. Hopefully [Shift Happens](https://mwichary.medium.com/shift-happens-5b049f5a93a8) will lay it all out. :-)

For example, here are three of my typewriters (all post-WW2). Only the last one there happens to demonstrate the standard shift key.
<img src=https://user-images.githubusercontent.com/202757/185793453-98e868e7-a4d8-45a6-bea4-d07fd1ede1b6.jpg width=30%> <img src=https://user-images.githubusercontent.com/202757/185793455-2f354259-b63a-4d57-ac9e-7da16a1dd846.jpg width=30%> <img src=https://user-images.githubusercontent.com/202757/185793452-4b30a77f-3e7d-49e2-bf96-972194dc84cf.jpg width=30%>

I just noticed that the Dell XPS I'm typing this on has a key with only "Shift" written on it and up arrow symbol — quite an odd duck among the computer keyboards I own.

> But my point was "our user demographic definitely recognizes the SHIFT arrow" :)

My point is significantly beyond that. ;-P You'd be hard-pressed to find someone who doesn't know what that key does regardless whether you leave it empty or put some nonsense on it . ^_^

**Comment by sonix-github** [comment]
I have just made pull request with new virtual keyboard for Slovak language. I have stripped down all unnecessary customization so it has mainly re-arranged key popups.

**Comment by pazos** [comment]
Done in #9656
