### ISSUE TITLE
EPUB incorrectly rendered (first letter capitalized *without* using ::first-letter)

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#9476]
* KOReader version:2022.08
* Device: Kobo Clara HD (should be device independent)

#### Issue
First letter is incorrectly rendered in KOReader
Calibre rendered
![calibre](https://user-images.githubusercontent.com/10298730/188335790-7aa4aef8-1661-4d71-b3c0-cd381e83a550.png)
KOReader rendered
![image](https://user-images.githubusercontent.com/10298730/188335943-7413583f-efa4-4ce7-99f8-ffc14425c291.png)

#### Steps to reproduce
Open epub file (tactically renamed to .zip as github doesn't allow epubs), go to the first chapter
[The Myth of Sisyphus and Other Essays - Albert Camus_scrambled.zip](https://github.com/koreader/koreader/files/9485626/The.Myth.of.Sisyphus.and.Other.Essays.-.Albert.Camus_scrambled.zip)

**Comment by poire-z** [comment]
Most of the indentation and mis-centering issues like this one comes from our epub.css that sets `text-indent: 1.2em` on `<P>` (the most bothering to me is when they use various `<P class=title/author>` to center the author/title/subtitle on the title page... that I too often get mis-centered and a bif off to the right...)
html5.css doesn't indent `<P>`, like browsers.
Some publishers assume their books will only be read on web browser engines based readers, so they don't bother "resetting" the styles, and this happens.
Solution for us: switch to `Style> HTML5 (html5.css)` - and you get the same as calibre:
![image](https://user-images.githubusercontent.com/24273478/188338826-ed4574bd-f239-4152-b9fe-c4709eaeb4a0.png)

The smaller font size and bigger gap above and below the first letter could possibly be because you have some style tweaks enabled ? I get similar to your bad screenshots if I enable "Ignore publisher line heights":
![image](https://user-images.githubusercontent.com/24273478/188338868-74ece8e8-fc2c-4274-ade9-eb6f2a16a48b.png)

**Comment by Galunid** [comment]
Awesome, thanks. Disabling all style tweaks and switching to `html5.css` did indeed fix this.
