### ISSUE TITLE
"Waking up" message no longer clears automatically after the update

### ISSUE THREAD

**Issue by esnovo** [koreader/koreader#9482]
* KOReader version: 2022.08

* Device: Kindle paperwhite (10th Gen)

#### Issue

Whenever the Kindle Paperwhite resumes the "_waking up_" message doesn't clear automatically as before, can only remove it once I advance/recede pages.

#### Steps to reproduce

Just resume/wake up the device

**Comment by NiLuJe** [comment]
Usual questions that I forgot to ask on Gitter: which FW version is it running, and what are your ScreenSaver settings?

**Comment by NiLuJe** [comment]
Possibly introduced by https://github.com/koreader/koreader/commit/e3228abb19eb6f926c3adb0d55109c53b2ac4ae6 from https://github.com/koreader/koreader/pull/9377 as a fix for the non-issue in https://github.com/koreader/koreader/issues/9285 ;).

**Comment by esnovo** [comment]
Running firmware 5.11.2 (3541840032)

ScreeSaver settings as follows:

- [ ] Leave screen as it is
- [ ] Covers and images settings > Black background
- [ ] Message Settings > Leave background as-is behind message
- [ ] Message Settings > Message Position > Middle
- [ ] Keep the screensaver on screen after wakeup > Disable

**Comment by NiLuJe** [comment]
Oooh, wait, by "Waking up message", you mean the banner shown at the bottom of the screen that only appears if the device actually entered deep sleep, right?

**Comment by esnovo** [comment]
That's the one, from the deep sleep indeed :)

This only happened after the update to 2022.08 didn't have the issue with  2022.07 and it was using the FW version. Could a kindle restart make a difference?

**Comment by NiLuJe** [comment]
Nope, it's definitely since the aforementioned commit. We just don't have
any way of knowing on resume if it was from deep sleep or not, so I don't
really have a nice way to handle this without an extra refresh...

**Comment by NiLuJe** [comment]
Or... do we? :}.

It's been a while, but if I find the actual timeout value that trips a deep sleep, I can just deal with that on resume, as we do know the amount of time we slept for...

(Might even go sneaky and just do a tiny non-flashing refresh at the bottom of the screen, because I doubt I'll find the actual dimensions of the banner, as I'm not quite sure what's responsible for it...).

**Comment by yparitcher** [comment]
I only register my kindles (connect to amazon for a few seconds, before i nuke the global internet via iptables) to get rid of this deep sleep (first thing i do when getting them). If my batter lasts a few weeks either way why have a few second delay on each wakeup.

I have not tested much with deep sleep, but during my screensaver related tests i think that the lipc event tracks what type of sleep was entered.

I am rerunning my script
`lipc-wait-event -m com.lab126.powerd "*" | while read event; do echo `date "+%Y-%m%d %I:%M:%S %p"` $event >> /mnt/us/tc/waiteventlog; done`

on my shelf display kindle, that has the deep sleep, as i never wake it up (rtc based refreshes only) and will get back in a day or two with the results

**Comment by NiLuJe** [comment]
It might be as early as the T2 timeout, because I just left it during dinner break, and it kicked in (and it slept for 1h20 almost on the dot) ;p.

My original plan was to actually trigger this issue to get an idea of the exact region affected so I could sneak in a non-flashing AUTO somewhere, but of course, screen was cold enough that it got caught in the standard refresh, so, that didn't work out ;p.

**Comment by NiLuJe** [comment]
Or... not. Might be 1H then.

**Comment by NiLuJe** [comment]
Yup, looks like 1H:

```
[40384.569265] .(1)[1455:powerd]PM: suspend entry 2022-09-05 19:30:33.168711528 UTC
[40486.265619] .(1)[6464:echo]PM: suspend entry 2022-09-05 20:32:03.503035668 UTC
```

**Comment by NiLuJe** [comment]
Okay, snapshotting script is `/usr/sbin/snapshot`, and the "waking up" banner is stored in `/tmp/hibernate.bmp.gz`
