### ISSUE TITLE
Autowarmth ends night mode ever 60s on kobo libra 2 and v2022.08

### ISSUE THREAD

**Issue by dfrein** [koreader/koreader#9498]
With koreader v2022.08 the autowarmth function does no longer work as expected on kobo libra 2: during the evening when the plugin controls light color, night mode will be switched off every 60 seconds. Therefore night mode and autowarmth cannot be used at the same time.

In additon, I've observed some flickering in backlight color, but I am unable to reproduce this today. But the new code also resets backlight warmth every minute back, even if a warmer color was manually chosen. If I rememver correctly, this was not the case in v2022.07.

Nothing is added to crash.log

**Comment by NiLuJe** [comment]
Does the actual "Nightmode" checkmark in the menu get unchecked when nightmode dies, or not?

**Comment by dfrein** [comment]
Yes, the "nightmode" checkmark gets unchecked (after opening the menu again)

**Comment by NiLuJe** [comment]
Then I defer to @zwim ;).

**Comment by zwim** [comment]
> With koreader v2022.08 the autowarmth function does no longer work as expected on kobo libra 2: during the evening when the plugin controls light color, night mode will be switched off every 60 seconds. Therefore night mode and autowarmth cannot be used at the same time.

This is the expected behavior. Namely, it overrides user settings (warmth and night mode), when it is active. It controls color and night mode. So if there are some calculated changes scheduled for warmth,  night mode is set/unset - according to the settings in the "Warmth and night mode settings" menu.

If you want the plugin to turn on/off night mode at a certain time you can set this in the "Warmth and night mode settings" menu.


![grafik](https://user-images.githubusercontent.com/36999612/189434938-5b8ed94a-78cb-4ad6-b1cf-c7b43574828d.png)



IIRC "Night mode on" in the AutoWarmth plugin implicitly sets warmth to maximum. So now it is not possible to set warmth to half and enable night mode (but this could be changed if it is really, really neccesary, as the UI might get confusing then).

>But the new code also resets backlight warmth every minute back, even if a warmer color was manually chosen. If I rememver correctly, this was not the case in v2022.07.

Same answer here. The change does not always happen on a full minute. It depends on calculations and your settings.

If you don't want AutoWarmth control the warmth and night mode of your frontlight, it is possible to implement a gesture to stop AutoWarmth changing anything for a certain time. But after that time, the warmth and night mode **might jump** to the then calculated value, which would be very verry annoying (that's why I haven't implemented it yet).

If your problem only hangs on night mode, I could educate AutoWarmth not to touch night mode at all (as a user selectable option).

 > In additon, I've observed some flickering in backlight color, but I am unable to reproduce this today. 

This should not happen. Maybe once after a resume from sleep. But I haven't observed that on a Sage.

**Comment by dfrein** [comment]
Thank you very much for explaning the expected behaviour, but in my opinion autowarmth and night mode have completely different use cases, at least for me: in my understanding autwarmth should help to adapt backlight color to usually more warm colors after sunset and in addition the reduction in blue light will help get sleepy. The night mode instead is suited for dark environments, and to reduce "blinding" by the reader. The warmth of the surrounding light can be predicted very well (like autowarmth already does), but it cannot be predicted when I decide to switch of my bedside lamp and want to activate night mode :-) 

> If your problem only hangs on night mode, I could educate AutoWarmth not to touch night mode at all (as a user selectable option).

IMHO, there should at least be an option to leave night mode untouched, otherwise autowarmth makes no longer any sense for me, as the manual night mode is much more important for me (I really liked the old behaviour, including the fact that night mode was reverted at midnight). Therefore a user selectable setting not to touch night mode would be very welcome.

> Same answer here. The change does not always happen on a full minute. It depends on calculations and your settings.

For me its always exactly every 60 seconds, at the same time the clock switches to the next minute (tested between evening and midnight).

I'm still trying to understand AutoWarmth's expert mode, which does not  seem to be working reliable for me, or it is working in a completely different way which I do not understand: night mode seems to stay active in AutoWarmth expert mode, and warmth will not be forced back to the plugin setting every minute.

BTW, my kobo reader has crashed a couple of times now during testing night mode and autowarmth settings while reading and swiping to the next page when both night mode and autowarmth were activated at the same time (completely rebooting the whole system without helpful information in crash.log), but I have not found a way to specifically trigger these crashes.

**Comment by NiLuJe** [comment]
It's a Libra 2, which is unfortunately [a crashy mess](https://github.com/koreader/koreader/issues/8414) :/.

**Comment by dfrein** [comment]
Thank you for providing an option to disable control of night mode via AutoWamth, I will test that with one of the next nightly builds. Now I switched to the expert mode, which currently (on v2022.08) already can be set up not to interfere with night mode.
