### ISSUE TITLE
Translation has not been available in China since about one day ago

### ISSUE THREAD

**Issue by suiahae** [koreader/koreader#9574]
* KOReader version: v2022.08
* Device: KindlePaperWhite5

#### Issue
Since about one day ago, translation function has not been available in China.

##### `crash.log` 

<details>
  <summary>crash.log</summary>

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 09/29/22-11:16:17
 [*] Version: v2022.08

ffi.load: blitbuffer
09/29/22-11:16:17 INFO  initializing for device KindlePaperWhite5
......
......
......
ffi.load: libs/libutf8proc.so.2
PING 192.168.43.1 (192.168.43.1): 56 data bytes
64 bytes from 192.168.43.1: seq=0 ttl=64 time=39.586 ms

--- 192.168.43.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 39.586/39.586/39.586 ms
09/29/22-11:16:20 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
......
......
......
09/29/22-11:16:50 INFO  TOC had 1 bogus page numbers: fixed 1 items to keep them ordered.
error in subprocess:	frontend/ui/translator.lua:389: Network is unreachable
stack traceback:
	[C]: in function 'error'
	frontend/ui/translator.lua:389: in function 'task'
	frontend/ui/trapper.lua:564: in function 'func'
	./ffi/util.lua:343: in function <./ffi/util.lua:314>
	[C]: in function 'xpcall'
	./ffi/util.lua:314: in function 'runInSubProcess'
	frontend/ui/trapper.lua:545: in function 'dismissableRunInSubprocess'
	frontend/ui/translator.lua:507: in function '_showTranslation'
	frontend/ui/translator.lua:494: in function <frontend/ui/translator.lua:493>
	[C]: in function 'xpcall'
	frontend/ui/trapper.lua:48: in function <frontend/ui/trapper.lua:45>
error in subprocess:	frontend/ui/translator.lua:389: Network is unreachable
stack traceback:
	[C]: in function 'error'
	frontend/ui/translator.lua:389: in function 'task'
	frontend/ui/trapper.lua:564: in function 'func'
	./ffi/util.lua:343: in function <./ffi/util.lua:314>
	[C]: in function 'xpcall'
	./ffi/util.lua:314: in function 'runInSubProcess'
	frontend/ui/trapper.lua:545: in function 'dismissableRunInSubprocess'
	frontend/ui/translator.lua:507: in function '_showTranslation'
	frontend/ui/translator.lua:494: in function <frontend/ui/translator.lua:493>
	[C]: in function 'xpcall'
	frontend/ui/trapper.lua:48: in function <frontend/ui/trapper.lua:45>
error in subprocess:	frontend/ui/translator.lua:389: Network is unreachable
stack traceback:
	[C]: in function 'error'
	frontend/ui/translator.lua:389: in function 'task'
	frontend/ui/trapper.lua:564: in function 'func'
	./ffi/util.lua:343: in function <./ffi/util.lua:314>
	[C]: in function 'xpcall'
	./ffi/util.lua:314: in function 'runInSubProcess'
	frontend/ui/trapper.lua:545: in function 'dismissableRunInSubprocess'
	frontend/ui/translator.lua:507: in function '_showTranslation'
	frontend/ui/translator.lua:494: in function <frontend/ui/translator.lua:493>
	[C]: in function 'xpcall'
	frontend/ui/trapper.lua:48: in function <frontend/ui/trapper.lua:45>
09/29/22-11:19:10 INFO  no dialog left to show
09/29/22-11:19:10 INFO  quitting uimanager
lipc-wait-event exited normally with status: 0
......
......
Same errors
......
......
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 09/30/22-14:42:46
 [*] Version: v2022.08

ffi.load: blitbuffer
09/30/22-14:42:47 INFO  initializing for device KindlePaperWhite5
......
......
......
ffi.load: libs/libutf8proc.so.2
PING 192.168.1.1 (192.168.1.1): 56 data bytes

--- 192.168.1.1 ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss0
09/30/22-14:42:52 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
......
......
......
09/30/22-14:43:01 INFO  TOC had 1 bogus page numbers: fixed 1 items to keep them ordered.
error in subprocess:	frontend/ui/translator.lua:389: Network is unreachable
stack traceback:
	[C]: in function 'error'
	frontend/ui/translator.lua:389: in function 'task'
	frontend/ui/trapper.lua:564: in function 'func'
	./ffi/util.lua:343: in function <./ffi/util.lua:314>
	[C]: in function 'xpcall'
	./ffi/util.lua:314: in function 'runInSubProcess'
	frontend/ui/trapper.lua:545: in function 'dismissableRunInSubprocess'
	frontend/ui/translator.lua:507: in function '_showTranslation'
	frontend/ui/translator.lua:494: in function <frontend/ui/translator.lua:493>
	[C]: in function 'xpcall'
	frontend/ui/trapper.lua:48: in function <frontend/ui/trapper.lua:45>
09/30/22-14:53:20 INFO  Inhibiting user input
......
......

```
</details>

**Comment by Frenzie** [comment]
I don't think we have much sway over either Google or the Great Firewall. ^_^

**Comment by suiahae** [comment]
It may be more appropriate to change this issue to functional requirements. 

For example to provide the option to change the Google Translate address, or to customize the translation interface (api?), or use HOSTS file? May be ;;

**Comment by poire-z** [comment]
`frontend/ui/translator.lua:389: Network is unreachable`

Are you sure you're online and your wifi works (try a wikipedia lookup) ?
Do other chinese users experience the same issue ?

Because if I try bogus URLs (invalid hostname, wrong port on a firewalled server I know), I get some other errors:
```
error in subprocess: frontend/ui/translator.lua:389: host or service not provided, or not known
error in subprocess: frontend/ui/translator.lua:389: Cannot assign requested address
error in subprocess: frontend/ui/translator.lua:389: timeout
```

And before _change this issue to functional requirements_ and having us do some work :) may be try:
- to narrow down the issue. The code would call for example:
https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=fr&dt=t&q=alea%20jacta%20est
https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=zh&dt=t&q=alea%20jacta%20est
and get a json.txt. Does this work manually in a browser for you ? If not, does this web browser dev tools/network tells more ?
- to negotiate with your governement to calm down that Great Firewall
- and only if these fail :) we might thing about doing the work (some attempts at https://github.com/koreader/koreader/pull/9040#issuecomment-1118759739, but not done well and no followup)

**Comment by suiahae** [comment]
I can use kindle built-in browser to access Internet, so I think I'm online and my wifi works.

Since I didn't find the kindle Chinese forum, I can't be sure if there are people with the same troubles in koreader.

**BUT I just learned that** around the time I had this problem, many people were also having trouble accessing Google Translate!!!

After research, some people found that it can be solved by adding entries about `translate.googleapis.com` and `translate.google.com` in the HOSTS file. Like this:
```
180.163.151.162  translate.googleapis.com
203.208.40.66 translate.googleapis.com
203.208.40.66 translate.google.com
```
- When I try to open both `translate.googleapis.com` pages mentioned above, all I get is ERR_CONNECTION_TIMED_OUT instead of json.txt.
- It is not possible here ;;;;;;;

**Comment by poire-z** [comment]
What about the same url in cleared text `http://` instead of encrypted/secure `https://`
http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=fr&dt=t&q=alea%20jacta%20est
http://translate.google.cn/translate_a/single?client=gtx&sl=auto&tl=fr&dt=t&q=alea%20jacta%20est
https://translate.google.cn/translate_a/single?client=gtx&sl=auto&tl=fr&dt=t&q=alea%20jacta%20est

If one of these work, you can specify an alternate address by manually adding in your settings.reader.lua:
```
"trans_server" = "https://translate.googleapis.com/",
"trans_server" = "http://translate.googleapis.com/", -- in case cleared text works
"trans_server" = "https://translate.google.cn/", -- doesn't work for me, but may be for you
```
(The last url is used in https://github.com/lingyv/google-cn-translate-api - but it hasn't been updated for 4 years).

It seems Google won't work if we use an IP address (we would need to add a HTTP header `Host: translate.googleapis.com` when this trans_server looks like it's an IP address):
```
"trans_server" = "https://180.163.151.162/",
"trans_server" = "https://203.208.40.66/",
```

Anyway, may be just wait until Google sort that out with your government :) unless it's just a technical issue that they will probably sort out.

**Comment by suiahae** [comment]
Except for adding items in the HOSTS file, the above addresses are not accessible, 404 or something.

After adding this items about `translate.googleapis.com` and `translate.google.com` in the HOSTS file, 
```
180.163.151.162  translate.googleapis.com
203.208.40.66 translate.googleapis.com
203.208.40.66 translate.google.com
```
I can get a json.txt very smoothly by accessing https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=fr&dt=t&q=alea%20jacta%20est

**Comment by poire-z** [comment]
Ok, just for fun, I made a [user patch](https://github.com/koreader/koreader/issues?q=label%3A%22User+patch+available%22) that you (and people in the same situation) could use - meaning users can help themselves, and it's not yet a general issue that would need us to implement something (with all the added UI work).

Download [2-translator-http-override.lua.txt](https://github.com/koreader/koreader/files/9689910/2-translator-http-override.lua.txt) , remove the .txt extension, and drop it in koreader/patches/ (create this patches/ directory manually).
Its content:
```lua
-- To be used if a DNS lookup for translate.googleapis.com would fail

local Translator = require("ui/translator")
local http = require("socket.http")

Translator.getTransServer = function()
    -- Change this with a usable/working IP address (that would work if added to a HOSTS file)
    return "https://180.163.151.162/"
end

local orig_http_request = http.request
local hacked_http_request = function(reqt)
    -- Keep this unchanged
    reqt["host"] = "translate.googleapis.com"
    return orig_http_request(reqt)
end

local orig_translator_loadPage = Translator.loadPage
Translator.loadPage = function(self, text, target_lang, source_lang)
    http.request = hacked_http_request
    local result = orig_translator_loadPage(self, text, target_lang, source_lang)
    http.request = orig_http_request
    return result
end
```

Remember to backup & remove this file when the problem is fixed.

**Comment by suiahae** [comment]
Thanks a lot for your help [poire-z](https://github.com/poire-z), however the bad news is that it didn't work for me. Here is the test I did:

It may be due to the complex network environment or other reasons, when I fill in the HOSTS file with `translate.googleapis.com` and the corresponding IP address(`180.163.151.162`), I can get a json.txt very smoothly by accessing `https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=fr&dt=t&q=alea%20jacta%20est`.

However, when I go directly to `https://180.163.151.162/translate_a/single?client=gtx&sl=auto&tl=fr&dt=t&q=alea%20jacta%20est`, I first get the `NET::ERR_CERT_AUTHORITY_INVALID` error, hit continue, and then get the `404` error.

**Comment by suiahae** [comment]
Then I looked into kindle OS and found out that it is based on linux. So I added `180.163.151.162 translate.googleapis.com` in /etc/hosts and it worked! ! !
