### ISSUE TITLE
Kobo Nia :: Power/sleep button not working/enabled    [proof of concept fix available]

### ISSUE THREAD

**Issue by 3to8-decoder** [koreader/koreader#9590]
* KOReader version: 2022.08
* Device: Kobo Nia

#### Issue
power button that does put Kobo Nia to sleep, nor does it awake it.
It does work in nickel and plato.
The magnetic sleep cover does work btw.

#### Steps to reproduce
Install Koreader on Kobo Nia and try to press the sleep/power button, nothing happens :P

#### easy way to solve it:
I found that in /.adds/koreader/frontend/kobo/device.lua,
some touch screen stuff was mapped to /dev/input/event0 and event1,
power_dev was mapped to nil, and (presumably) later picked up generically, but that doesn't work for the Nia for some reason.
Anyhow, using the terminal emulator I quickly found out by doing `$ ls /dev/input` that there was an event2,
and by using `# cat /dev/input/event2` and pressing the power/sleep button found out that the power button was mapped to it.

```
-- Kobo Nia:
--- @fixme: Mostly untested, assume it's Clara-ish for now.
local KoboLuna = Kobo:new{
    model = "Kobo_luna",
    isMk7 = yes,
    canToggleChargingLED = yes,
    hasFrontlight = yes,
    touch_phoenix_protocol = true,
    display_dpi = 212,
    power_dev = "/dev/input/event2",
}
``` 

Adding that last line to the Nia block solved it for me.
Now it works perfectly. But I assume that after Koreader update this change is gone,
hence the issue.

**Comment by 3to8-decoder** [comment]
Pull request: https://github.com/koreader/koreader/pull/9591

**Comment by Micrard** [comment]
What is the Nia block ? in which file do I find this ? Where do I add this fix ? I don't understand. In device.lua ?

**Comment by Micrard** [comment]
I found the file ! I think it is called device.lua, in the Kobo folder, right ?

But when I do cat and try to edit it, the part I wanna edit disappears on the top of the screen and I have no way to access it. How do I edit the file ?

**Comment by Frenzie** [comment]
For future reference, you can always just plug the device using USB and edit files that way. I'm not sure if anyone's used this `ed` thing since the late '70s or early '80s, heh. :-)

But if you want to edit files over Telnet or SSH using the terminal, some form of `vi` is still commonly used and available pretty much anywhere, so it might be worth learning some basic keyboard shortcuts for that (e.g., [here](https://gist.github.com/javiervidal/3871062)). More important, you can just use your favorite FTP client and many a file manager to connect over FISH or SSH FTP. And finally, of course there's rsync as well.
