### ISSUE TITLE
2 finger tap broke in latest release

### ISSUE THREAD

**Issue by vsim3** [koreader/koreader#9679]
* KOReader version: KOReader 2022.10
* Device: Kindle PW3 5.15.3

#### Issue

![screenshot-8b36fdee](https://user-images.githubusercontent.com/50333987/197757042-4664bce3-ae6d-4380-b21a-cc862dcaa8b1.png)

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/9861235/crash.log)

**Comment by poire-z** [comment]
Your screenshot is a bit surprising :)
Do you mean you actuall did 2 simultaneous taps, a tap on each button at the same moment? Iin the hope I imagine to get both the left and right margins increased simultaneously, and have both changes done in a single rendering instead of rendering first after the left margin change, and again after the right margin change?
If yes, did that really work ?!
If it did, it's possible we didn't even think about having it work and pure chance :)
If we broke it, well, that's because we didn't know about it :)

Anyway, that would not be what we consider a 2-finger tap (taps  with 2 fingers anywhere, and it's a gesture you can associate some action to be performed).

So, even if an image is worth a thousand words, please add some words to your screenshot :) What do you do, what do you expect, what happened before and what happens now. Thanks.

**Comment by vsim3** [comment]
Yeah, i used to press them both at same time the dialog show increment by 5 > Apply.
It works at least in koreader-kindlepw2-v2022.07-20-g39b0ca2f_2022-08-19.zip.

Apologize if my message not being clear, i have got some health issue things can become confusing and English is really hard

**Comment by poire-z** [comment]
Oh, right, this widget does not apply immediately when you tap on the arrows and increment the values - you actually need to tap Apply. So, it's not that bothering if simultaneous taps don't apply, you could just do one after the other - because there is no explicite support in the code to handle that case.

It's possible that @NiLuJe 's _fairly drastic changes that needed more time for testing, such as a big rewrite of gestures and multitouch_ #9463 (as @Frenzie wrote it in the Release notes) did make this trick no longer work.
If it worked, it was not a wanted feature, it was just luck :) And it it does not work after we cleaned up the mess, it's probably for the best (for us, may be not for you :/ Will you get used to changing your habits ? :)

**Comment by vsim3** [comment]
Fine by me, i just learned about it recently anyway :)
I'll open another one for gesture to exit screensaver later.

**Comment by NiLuJe** [comment]
Yeah, definitely worked by chance, this behavior should now be detected either as a proper double tap/hold if it passes the constraints, or as a single tap on... whichever finger hit first.
