### ISSUE TITLE
KOReader crash on android phone when turning the screen off and back on

### ISSUE THREAD

**Issue by KrokusPokus** [koreader/koreader#9727]
* KOReader version: 2022.10-55
* Device: Samsung Galaxy M21 (Android)

#### Issue
If I have KOReader visible/active and then turn off the phone's screen, I will get a `KOReader crashed` window when turning the screen back on again. This happens without fail every single time.
The only workaround I found is to **not** let KOReader be the active/foreground application when turning off the screen.

#### Steps to reproduce
1. Have KOReader in foreground
2. Turn off screen
3. Turn on screen

##### `crash.log` (if applicable)
The `KOReader crashed` screen let me copy this:
[crash.txt](https://github.com/koreader/koreader/files/9914652/crash.txt)
Don't know if that's the same thing as a `crash.log`

**Comment by NiLuJe** [comment]
We're talking about turning the *screen* off, right, not shutting down the phone?

**Comment by KrokusPokus** [comment]
> We're talking about turning the _screen_ off, right, not shutting down the phone?

Correct.

**Comment by pazos** [comment]
In https://github.com/koreader/koreader/issues/8482 there's a known condition called "Broken lifecycle" that tries to cover exactly that but it is aimed at eink devices made by broken companies.  I doubt very much that samsung fits in there. So, instead of go that route I would like a full log to know what happens under the hood.

If you're comfortable with `adb` and have no problem installing `pidcat` then I would love to see what `pidcat org.koreader.launcher` has to offer. (`pidcat org.koreader.launcher.fdroid` if you're downloaded the app from fdroid)

If not then please force a crash, restart the program and go to help -> report a bug and attach the log file generated there.

**Comment by KrokusPokus** [comment]
I never used `adb`, so for now, let's try the second route:
[crash.log.zip](https://github.com/koreader/koreader/files/9920271/crash.log.zip)

**Comment by pazos** [comment]
> I never used `adb`, so for now, let's try the second route: [crash.log.zip](https://github.com/koreader/koreader/files/9920271/crash.log.zip)

Sadly there're no traces of crashes in that log.

While android devices are almost perfect log machines, they usually report to their masters and not to random app developers, unless they sold their soul to your device's masters.

Happily enough contributors here didn't sell their soul nor their users souls, so big brother won't be able to tell us what's happening. In this specific case dumping the log ring to a file isn't enough and you'll need to get a log while reproducing the bug you're reporting.

**Comment by KrokusPokus** [comment]
I reinstalled KOReader and the issue now doesn't occur anymore.
(I actually went through all the older 2022 versions, starting with `2022.01`, to try find out which version actually introduced the issue, but eventually ended up at `2022.10` again, still with no crashes. So the initial process of uninstalling to be able to install the `2022.01` release probably was the actual fix...  Weird issue.)

This can be closed now, I guess.
