### ISSUE TITLE
"Select and highlight mode" works on the second try in PDF documents

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#9729]
I am using the **Select and highlight mode** as default (you touch the first and the last word of a highlight) and there is an interesting behavior. This only happens in PDF files. 
Generally when the highlight ends at the last line of the page, it gives this error:

`Fragments must be within one page`

Curious behavior is, when I try again it highlights the passage normally.
This is not new by the way, I am using it like this since the implementation I think.
But I realized that a user might think the feature is broken if they don't try again like I did.
Because sometimes it even does this when the selection ends one line above the last one.

So either:
- Author (@hius07) and/or other devs can have a look at it (I think this might be hard to fix with all that weird specs of PDF)
- **OR** I can explain this in the guide and instruct users to **"try highlighting again if this happens"** so they will be aware that sometimes it takes a second try to highlight the passages in this mode.

**Comment by hius07** [comment]
What are the pdf view settings (reflow, zoom)?

**Comment by offset-torque** [comment]
I just tried with two different books that gave the same error:
- One book with **Reflow ON**
- Another book with **Reflow OFF / Zoom to page width**

I think it is not about a specific book because I experienced this with very different books (old, new, proper/awful PDF). I suspect that I am the one reporting this because I am the only user of this highlight type :))

It is interesting that after the successful highlight (second one) I can't repeat the error on the same page, I have to go to another page to replicate the issue. It is like KOReader is learning the end of the page.

**Comment by hius07** [comment]
Sorry, cannot reprodue in my books.
I've tried with Reflow off, Zoom to page full, View Mode both "page" and "continuous".

**Comment by offset-torque** [comment]
I just reproduced the problem on the PC version too.
One reason I can think, my **Long press on text** is directly assigned to **Select and highlight**.
(Please disregard the aspect ratio, it is intentionally squeezed to make the video size smaller)
When I deleted the higlight and tried the same passage again, it highlighted without a complaint as I described above.

https://user-images.githubusercontent.com/84420582/199554498-8dcac803-2edc-4cbc-847b-51cf49677e1d.mp4

**Comment by hius07** [comment]
Still cannot reproduce.
Can you investigate more please: remove txt extension from the attached file and replace
koreader/frontend/apps/reader/modules/readerhighlight.lua
Catch the bug and send me crash.log (no need to turn debug mode on).
[readerhighlight.lua.txt](https://github.com/koreader/koreader/files/9923145/readerhighlight.lua.txt)

**Comment by offset-torque** [comment]
> Catch the bug and send me crash.log (no need to turn debug mode on).

I suppose when I replace this file and replicate the bug, it will automatically append the necessary info to the crash.log.

> replace koreader/frontend/apps/reader/modules/readerhighlight.lua

Is there a chance that I will mess up my installation.
I am actively using the device and don't want to backup/reinstall KOReader (especially for this rare and low-priority bug).
I guess backing up the original **readerhighlight.lua** and putting it back after obtaining the **crash.log** would be ok.

**Comment by hius07** [comment]
Yes, exactly.

**Comment by Australian-Infomaniac** [comment]
Forgive me that I haven't yet read the whole post, but I came here to report this same little bug.
After it's happened maybe a hundred times on PDFs on Kobo Forma, I thought it was time to say something! 
(Love the highlight method btw!)

**Comment by offset-torque** [comment]
OK I followed your instructions **hius07**. I think this is the relevant part in the **crash.log**

```
INFO  setting zoom mode to contentwidth 
INFO  1 Current page 308 
INFO  1 Highlight page 308 
INFO  2 Current page 308 
INFO  2 Highlight page 308 
INFO  1 Current page 311 
INFO  1 Highlight page 310 
INFO  2 Current page 311 
INFO  2 Highlight page 310
```

What we see is a succesful highlight  **308** (because it worked ok on the first try)
And a failed highlight **310-311**

PDF is in the **continuous mode** which I suspect might be the culprit.
Maybe continuous mode confuses the current/previous page while passing it (or smt like that :)

**Comment by hius07** [comment]
Thank you, what is the correct page you are highlighting at, 310 or 311?

**Comment by offset-torque** [comment]
Since it is in continuous mode, page divider is in the middle of the screen.
Status bar shows 311.

**Comment by hius07** [comment]
So on the second successful try the highlight page number became 311 (in the crash.log)?

**Comment by offset-torque** [comment]
Sorry I wasn't clear enough I guess.
First I tried on page 308 which it highlighted ok.
So I skipped a page and tried again to show the error.

This log includes only the **error popup** part which I thought you need by itself.
But I think you want **failure+success**.
If yes, I can capture that part too.

**Comment by hius07** [comment]
Yes. And what would be the page number if you were in the page mode?

**Comment by hius07** [comment]
Okay, can reproduce
```
11/09/22-08:55:44 INFO  1 Current page 4 
11/09/22-08:55:44 INFO  1 Highlight page 3 
11/09/22-08:55:48 INFO  2 Current page 4 
11/09/22-08:55:48 INFO  2 Highlight page 3 
11/09/22-08:55:52 INFO  2 Current page 3 
11/09/22-08:55:52 INFO  2 Highlight page 3 

```
Initial current page number is incorrect (actual page number is 3 in page mode).

**Comment by Australian-Infomaniac** [comment]
'CONTINUOUS' ONLY:
I can confirm that it doesn't seem to happen on 'page' view mode.
I did several tests and re-tests on the same passage.

**Comment by Australian-Infomaniac** [comment]
Here's my log.
PARAMETERS: 
* horizontal mode (which I get to with a gesture)
* A PDF (which has a watermark, FWIW...NOT de-watermarked)
* Continuous page view
* Long press on text:
- select and highlight
- TICKED: 'dictionary on single word selection'
_______________________
Other notes: 
*** SOMETIMES when it makes the error, it does jump to the next page and I have to bring it back. But this could just be because it thinks I've TAPPED rather than selected.**
* Its INCREDIBLY slow to respond after I do the first highlight. Assume because of watermarking. (PS does DE-watermark make it respond quicker?)
* I have had quite a few freezes in general
_______________________

 [*] Current time: 11/10/22-03:09:33
 [*] Version: v2022.10

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
11/10/22-03:09:34 INFO  initializing for device Kobo_frost 
11/10/22-03:09:34 INFO  framebuffer resolution: {
  h = 1920,
  w = 1440
} --[[table: 0x76b3f9f8]] 
[ko-input] Forked off fake event generator (pid: 3529)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
11/10/22-03:09:36 INFO  Loading plugins from directory: plugins 
ffi.load: sqlite3
11/10/22-03:09:37 WARN  TrackLines HELLO 
11/10/22-03:09:40 INFO  opening file /mnt/onboard/MyBooks-Forma/- LAW Current/Property/Terminations/Relos/2021.3.28 258/20 Kuru.pdf 
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
11/10/22-03:09:41 WARN  TrackLines HELLO 
11/10/22-03:09:41 INFO  setting zoom mode to contentwidth 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
warning: unknown link uri '[REDACTED]'
**11/10/22-03:10:09 INFO  1 Current page 7** 
11/10/22-03:10:09 INFO  1 Highlight page 7 
11/10/22-03:10:30 WARN  TrackLines on page update 
11/10/22-03:10:30 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:30 WARN  TrackLines on page update 
11/10/22-03:10:30 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:38 WARN  TrackLines on page update 
11/10/22-03:10:38 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:45 WARN  TrackLines on page update 
11/10/22-03:10:45 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:53 WARN  TrackLines on page update 
11/10/22-03:10:53 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:53 WARN  TrackLines on page update 
11/10/22-03:10:53 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:54 WARN  TrackLines on page update 
11/10/22-03:10:54 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:57 WARN  TrackLines on page update 
11/10/22-03:10:57 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:57 WARN  TrackLines on page update 
11/10/22-03:10:57 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:11:00 INFO  2 Current page 8 
11/10/22-03:11:00 INFO  2 Highlight page 7 
11/10/22-03:11:00 WARN  TrackLines on page update 
11/10/22-03:11:00 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:11:00 WARN  TrackLines on page update 
11/10/22-03:11:00 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:11:00 WARN  TrackLines on page update 
11/10/22-03:11:00 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:11:04 INFO  2 Current page 7 
11/10/22-03:11:04 INFO  2 Highlight page 7 
11/10/22-03:11:17 WARN  TrackLines on page update 
11/10/22-03:11:17 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 

THEN I WENT TO THE NEXT PAGE

**Comment by Australian-Infomaniac** [comment]
Here's my log.
PARAMETERS: 
* horizontal mode (which I get to with a gesture)
* A PDF (which has a watermark, FWIW...NOT de-watermarked)
* Continuous page view
* Long press on text:
- select and highlight
- TICKED: 'dictionary on single word selection'
_______________________
Other notes: 
*** SOMETIMES when it makes the error, it does jump to the next page and I have to bring it back. But this could just be because it thinks I've TAPPED rather than selected.**
* Its INCREDIBLY slow to respond after I do the first highlight. Assume because of watermarking. (PS does DE-watermark make it respond quicker?)
* I have had quite a few freezes in general
_______________________

 [*] Current time: 11/10/22-03:09:33
 [*] Version: v2022.10

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
11/10/22-03:09:34 INFO  initializing for device Kobo_frost 
11/10/22-03:09:34 INFO  framebuffer resolution: {
  h = 1920,
  w = 1440
} --[[table: 0x76b3f9f8]] 
[ko-input] Forked off fake event generator (pid: 3529)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
11/10/22-03:09:36 INFO  Loading plugins from directory: plugins 
ffi.load: sqlite3
11/10/22-03:09:37 WARN  TrackLines HELLO 
11/10/22-03:09:40 INFO  opening file /mnt/onboard/MyBooks-Forma/- LAW Current/Property/Terminations/Relos/2021.3.28 258/20 Kuru.pdf 
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
11/10/22-03:09:41 WARN  TrackLines HELLO 
11/10/22-03:09:41 INFO  setting zoom mode to contentwidth 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:09:41 WARN  TrackLines on page update 
11/10/22-03:09:41 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
warning: unknown link uri '[REDACTED]'
**11/10/22-03:10:09 INFO  1 Current page 7** 
11/10/22-03:10:09 INFO  1 Highlight page 7 
11/10/22-03:10:30 WARN  TrackLines on page update 
11/10/22-03:10:30 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:30 WARN  TrackLines on page update 
11/10/22-03:10:30 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:38 WARN  TrackLines on page update 
11/10/22-03:10:38 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:45 WARN  TrackLines on page update 
11/10/22-03:10:45 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:53 WARN  TrackLines on page update 
11/10/22-03:10:53 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:53 WARN  TrackLines on page update 
11/10/22-03:10:53 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:54 WARN  TrackLines on page update 
11/10/22-03:10:54 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:57 WARN  TrackLines on page update 
11/10/22-03:10:57 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:10:57 WARN  TrackLines on page update 
11/10/22-03:10:57 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:11:00 INFO  2 Current page 8 
11/10/22-03:11:00 INFO  2 Highlight page 7 
11/10/22-03:11:00 WARN  TrackLines on page update 
11/10/22-03:11:00 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:11:00 WARN  TrackLines on page update 
11/10/22-03:11:00 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:11:00 WARN  TrackLines on page update 
11/10/22-03:11:00 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 
11/10/22-03:11:04 INFO  2 Current page 7 
11/10/22-03:11:04 INFO  2 Highlight page 7 
11/10/22-03:11:17 WARN  TrackLines on page update 
11/10/22-03:11:17 ERROR failed to call event handler onPageUpdate plugins/track_lines.koplugin/main.lua:255: attempt to index field 'left_line' (a nil value) 

THEN I WENT TO THE NEXT PAGE

**Comment by hius07** [comment]
> track_lines.koplugin

What is it? Some old unsupported plugin?

**Comment by hius07** [comment]
Thanks to all, I understand the nature of the issue and will try to fix it soonest.

**Comment by Australian-Infomaniac** [comment]
> What is it? Some old unsupported plugin?

Yeah I think so. I think I've disabled that and some others.
It was a good idea that wasn't quite implemented properly - a single line across the screen that you could move down as you read, to make it easier to keep track.

>Thanks to all, I understand the nature of the issue and will try to fix it soonest.

Thanks so much!
I just want to say: Koreader is an incredible piece of soft-kit!
I discover amazing useful new features every week!
(One example: highlight exports. Incredibly useful for research!)

**Comment by offset-torque** [comment]
**Australian-Infomaniac**, if you haven't seen it yet, have a look at the **User Guide**.
Especially we have a **Tips** section there and I am preparing a big update to the guide, so keep an eye on it ;)

And thanks for your efforts **hius07**
