### ISSUE TITLE
[Kobo Libra 2] Failed to allocate ZSTD decompression buffer

### ISSUE THREAD

**Issue by oxillix** [koreader/koreader#9771]
- KOReader version: 2022.10
- Device: Kobo Libra 2

#### Issue
KoReader crashes when trying to launch it. Tried rebooting my kobo.

#### Steps to reproduce:
I updated KoReader to 2022.10 with KoReader itself a couple weeks ago.
Happened yesterday morning at random, I had some occasional freezes before. No idea how to reproduce this.

```
[ko-input] Forked off fake event generator (pid: 7445)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
./luajit: ./ffi/zstd.lua:41: Failed to allocate ZSTD decompression buffer (1.844674407371e+19 bytes)
stack traceback:
	[C]: in function 'assert'
	./ffi/zstd.lua:41: in function 'zstd_uncompress'
	frontend/persist.lua:123: in function 'deserialize'
	frontend/persist.lua:223: in function 'load'
	frontend/fontlist.lua:173: in function 'getFontList'
	frontend/ui/font.lua:279: in function 'getFace'
	frontend/ui/widget/textboxwidget.lua:92: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/button.lua:29: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/buttontable.lua:2: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/buttondialogtitle.lua:2: in main chunk
	[C]: in function 'require'
	frontend/apps/filemanager/filemanagerconverter.lua:5: in main chunk
	[C]: in function 'require'
	frontend/ui/quickstart.lua:4: in main chunk
	[C]: in function 'require'
	./reader.lua:285: in main chunk
	[C]: at 0x000140bd
!!!!
Uh oh, something went awry... (Crash n°1: 11/10/22 @ 08:41:56)
Running FW 4.34.20097 on Linux 4.1.15-00838-g349fbf5767c (#90 SMP PREEMPT Thu Sep 15 15:12:23 CST 2022)
Attempting to restart KOReader . . .
!!!!
```

Other user reported similar issue recently on reddit:
https://www.reddit.com/r/koreader/comments/ypewtt/koreader_keeps_crashing/

Please tell me what other logfiles I have to include
[crash.log](https://github.com/koreader/koreader/files/9990409/crash.log)

**Comment by NiLuJe** [comment]
This is caused by a filesystem corruption, most likely because of a hard-reboot, given the specific device.

We've hardened some on-disk cache files against this eventuality in b656b9f5af2b3a97314070fc39af99852ce92c90 (via #9691), but this won't help on an already-corrupt file, for that, see https://github.com/koreader/koreader/issues/9552#issuecomment-1287148583 (and the following comment for the actually more likely culprit ;)).

**Comment by poire-z** [comment]
2 or 3 similar reports (unless they all are the same?) of an issue when loading the cached fontlist, because of filesystem corruption: that feels a bit too much, and an epidemy of bad luck. Sure we can just ignore them?

**Comment by oxillix** [comment]
The issue was indeed a corrupted cache/fontlist/fontinfo.dat, deleting it fixed the problem. The issue has been reported on both Libra 2 and Clara 2E.

**Comment by NiLuJe** [comment]
@poire-z: All the reports happened on crashy devices, so I'm cautiously optimistic about chalking it up to that so far ;).

**Comment by ezuk** [comment]
Just another report of this happening, on a Clara 2E. Deleting cache/fontlist/fontinfo.dat fixed it.

**Comment by LinusCDE** [comment]
> 

Had this issue happening when updating koreader for testing purposes. My last installed version was from 2022-08 and it didn't happen on my other device which likely had a never version before.

This seems to be an issue of migrating / re-creating the file when the last version of it was produced by an older koreader version as the older version ran fine with it. See https://github.com/toltec-dev/toltec/pull/681#issuecomment-1546168998 for more links and testfiles.

**Comment by NiLuJe** [comment]
The issue encountered by the OP happens specifically when upgrading with a malformed cache file, period.

What you're describing looks different: an update from < 20220914 should have wiped the cache in order to handle the format change sanely, which should render the whole point moot.

The only thing I can think of would be some dependency ordering changes since, that would cause something to attempt to load the old cache *before* migration. I'd be happy to check your logs to test that theory ;).

**Comment by NiLuJe** [comment]
According to https://github.com/toltec-dev/toltec/pull/681#pullrequestreview-1424991337, it looks like your device was attempting to run migration steps that predates 2022-08 by *a lot*, which... is very strange, as you should have been on a much higher timestamps.

Were the config files manually moved around between devices? (e.g., via some sort of syncing mechanism, perhaps?)

**Comment by NiLuJe** [comment]
In any case, as a TL;DR: Dropping the cache on install like what @Eems did is perfectly fine by me ;).

**Comment by LinusCDE** [comment]
> Were the config files manually moved around between devices? (e.g., via some sort of syncing mechanism, perhaps?)

I didn't move them.

So is the crash happening as as result of a wrong migration attempting to change it? Because the older version ran fine with the supposedly old migration. If the file is loaded and corrupt I assume that version crashing as well, which it didn't.

The other device I have simply had a never version of koreader when testing the update. It seemed to re-create / update the file, so it's at least releated to some migration not running if the file is too old or has not been updated in between those versions.

**Comment by NiLuJe** [comment]
> So is the crash happening as as result of a wrong migration attempting to change it? Because the older version ran fine with the supposedly old migration. If the file is loaded and corrupt I assume that version crashing as well, which it didn't.

The older version hadn't moved to zstd, so it was able to parse the cache just fine.

The issue here is that you have an old cache, in an incompatible format, that is attempted to be read as the newer format, because, for some reason (wrong timestamp for the installed version, which doesn't make sense, except maybe for repeated migration failures in the past), it's running the full gamut of migration steps instead of only the required ones.

That results in undefined behavior, as that's just not the way this was intended to go, at all.

A sane migration from 2022-08 to anything newer should land you, as the first step, in the "delete the old incompatible cache" branch.

**Comment by NiLuJe** [comment]
> (wrong timestamp for the installed version, which doesn't make sense, except maybe for repeated migration failures in the past)

You might want to check your logs prior to the update to see if you're seeing repeated migration steps on every startup?
