### ISSUE TITLE
We could not open a file by Koreader in another app, for instance, onedrive. 

### ISSUE THREAD

**Issue by dongyang-cs** [koreader/koreader#9787]
I guess need to apply for permission of managing all files and storage. 

`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />`

**Comment by alfod** [comment]
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />

**Comment by alfod** [comment]
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />

**Comment by pazos** [comment]
Hi, @alfod 

The symptom is the there but the cause is not the the one you highlighted.

We actually use a trick that makes advantage of Android roots: Linux. It lets us "guess" the absolute path on any file encoded as a content uri. See https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/extensions/UriExtensions.kt#L14-L44

The trick works well when the DocumentProvider delivers an uri that points to a local file that's in a place that KOReader can read.

The trick won't work if:

- The content is not a file.
- The content is not local (ie: cloud services)
- The content is placed under other app private directories as we can't read there.

The reason to use the trick in the first place is:

- We can't support reading files in place using android pseudo filesystem features.
- We don't want to duplicate a file just because an user opens it with KOReader.

I'm open to suggestions about options to deal with the issue but I don't want to loose the current behaviour (open files in place without making a hardcopy).

Keep in mind that the other alternative would be making a copy of the document when you open it.

You can already do that from KO FM, in the plus button, pressing import and selecting the documents from the desired provider. Have a look at that and tell me if the same behaviour would work for you when opening files from other apps.

**Comment by Radoom** [comment]
Not sure I understand the problem, but from a pure "user perspective" ... "every other app can do it" . 
Example : source app is Signal. I receive an attachment (say pdf) from a contact. Click it. Signal ( or rather android)  brings up a list of suitable apps (e.g. MuPDF, OfficeDocsViewer, EpsonPrintApp, and KOreader, and maybe more / others). ALL my examples can access that pdf, only KoReader can't and throws me into its file manager.... Why exactly? And what can I do about it?

**Comment by pazos** [comment]
Please spend a few minutes reading the comment above yours. It is explained for zero knowledge end users.

> And what can I do about it?

Provide feedback about the only possible workaround other than removing KO from the app picker entirely. (Again, please read my previous answer)

**Comment by Radoom** [comment]
Hi pazos, I did read that comment of yours. Twice. Wouldn't consider myself as a total "zero knowledge end user"... but didn't really get the point in your explanation (what in turn obviously qualifies me as "zero knowledge..." then - so be it).

I don't really understand the suggestion you make in your last sentence (FM, plus button, import? from where?) to be honest. How should that solve the problem (for the average zero-knowledge user)? How can I "import" whatever Signal as the source has placed (somewhere, I don't even know where...). 

Being the zero-knowledge end user: All those other apps don't seem to have a problem with getting access to the file that Signal "hands" to them (in whatever way it does it; something with "content://org.thoughcrime.securesms.part/part/(some number and what not - can't see the whole string)"). So, what "bad stuff" are they doing that you can't (or: "don't want to"?)? 

Would I mind if your app duplicates that "handed over" attachment file just do display it? No, definitely not.
Do I (as a zero knowledge user) mind complicating things (compared to those other apps). Yes :-) sorry to be frank. 

Don't get me wrong, KOreader is awesome, yaw breaking in many features. Just this  "(non-)integration" ... sort of doesn't qualify it to be used everywhere and always, which really is a pitty!

**Comment by Radoom** [comment]
"We can't support reading files in place using android pseudo filesystem features." - why "can't"?

**Comment by NiLuJe** [comment]
Because we need a hard file for a lot of various technical reasons.

**Comment by pazos** [comment]
> I don't really understand the suggestion you make in your last sentence (FM, plus button, import? from where?) to be honest. How should that solve the problem (for the average zero-knowledge user)? How can I "import" whatever Signal as the source has placed (somewhere, I don't even know where...).

#  Have a look at that and tell me if the same behaviour would work for you when opening files from other apps.

Seriously. **Have a look at the import option**. Import some *random* file from *somewhere*. See it imported to KO. Does the same behaviour **work for you** when you choose KOReader in the app picker to open some given document from some other app?

> You say you don't want to duplicate files, right? Apparently this is then what those other readers/viewers do when signal hands them a file, yes?

Not ideally. They should be able to open the file in place using a parcelFileDescriptor or some other android ~~shit~~ stuff.

> "We can't support reading files in place using android pseudo filesystem features." - why "can't"?

If we explain you why, why do you think knowing that would prevent you to ask why?

> How about letting the user chose in that case? 

That is what I was asking in the first place. Feedback.

Your suggestion isn't possible. We should import the file just after the app is resumed by the intent that delivers the content that we need to evaluate if we want to import. That happens before we have some sort on window to draw to ask users what they want to do.

The only viable way of importing in place is to add a setting to choose between import and ignore and follow the setting each time the app is resumed by an intent with content scheme.

**Comment by Lemonnonioiiii** [comment]
> We actually use a trick that makes advantage of Android roots: Linux. It lets us "guess" the absolute path on any file encoded as a content uri. See https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/extensions/UriExtensions.kt#L14-L44

I encountered the same problem of not being able to open pdf file by koreader in another app, and I am reading the answer here but I don't understand this part. Is this extension something I could install on my android device to solve this problem? If yes, how could I install it? 😳

**Comment by pazos** [comment]
> > We actually use a trick that makes advantage of Android roots: Linux. It lets us "guess" the absolute path on any file encoded as a content uri. See https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/extensions/UriExtensions.kt#L14-L44
> 
> I encountered the same problem of not being able to open pdf file by koreader in another app, and I am reading the answer here but I don't understand this part. Is this extension something I could install on my android device to solve this problem? If yes, how could I install it? 😳

@Lemonnonioiiii: that's what make possible opening documents from any other app as long as the documents are in a public place (ie: Downloads)

The problem here is caused by 

> The content is placed under other app private directories as we can't read there.

The file path is resolved fine but we can't read there, so we will need to make a copy somewhere under our control.

**Comment by diego-treitos** [comment]
I am also experience this problem. First of all let me thank you for your app, I think it is awesome. However I'd like to add a couple of things regarding this issue:

1. At least for me, this is a deal-breaker. If I cannot use KOReader to open attachments, I will choose a different application. I doubt that I am the only one that thinks this way so I think you should have this into consideration if you want to attract people into using your app (although maybe having more people using your app is not important for you, which is fine).

2. From a user point of view, this issue feels like a bug. The main problem is that you are redirected to the file manager instead of showing any meaningful information to the user that "opening files from a different app is not supported". **IMHO this would be the very least to do to deal with this issue**.

3. I think having a temporal copy of the file would be a fine price to pay to have this feature. You could even limit the copy only to files below certain size and you could delete the temporal copy after KOReader is closed or even after certain time.

4. Another option would be to offer the user to save the file somewhere and then either open the filemanager in that path or directly open the file. This way the user can always opt out to not save the file, not creating that copy.

**Comment by pazos** [comment]
All the code involved lies in https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/extensions/UriExtensions.kt

And the suggested solution would be to call `toFile` method of an Uri if its `absolutePath` method returns null or a string that contains `Android/data`. I would also suggest to pass a path that's static, like both the external files/cache dir.

Since nobody yet provided me the feedback I was asking for in my first comment I'm going to move aside and let other users to fix the issue.

**Comment by diego-treitos** [comment]
I am sorry but I am not an Android developer so I am not sure what you are talking about.

If I could suggest you how to solve it from a development point of view, I could probably submit a PR...

The suggestions and feedback that I offered were merely from a user point of view and unfortunately I cannot provide you with any other kind.

@pazos Grazas de tódolos xeitos e sinto non poder axudar co código 😉

**Comment by Radoom** [comment]
@Pazos sorry, but I don't really understand the suggestion you ask feedback for. I think you mean this statement,  right?: 
"Have a look at the import option. Import some random file from somewhere. See it imported to KO. Does the same behaviour work for you when you choose KOReader in the app picker to open some given document from some other app?"
I'm not sure I understand the way you are describing.
This :?
1) go into koreader file manager
2) navigate to a "target" folder (where I want koreader to put a file into)
3) select "+" and then "import here"
 4) android file browser comes up
5) select a "source" file from somewhere (eg my downloads folder; or eventually the place where source app like signal would have dropped the attachment this is all about)
6) koreader "imports" it into the "target" folder selected in step 2
7) select that "imported" file from where koreader placed (i.e. copied!?) it to
8) file opens for reading.
What I don't understand in your question is"Does the same behaviour work for you when you choose KOReader in the app picker to open some given document from some other app?" - how would I go all these steps after selecting Koreader in the app picker popup showing when clicking an attachment in the "source" app? 
If you mean to then go all the steps 1-8 above before reading the attachment...no, sorry, that wouldn't work for me (nor diego-treitos, I'd guess; nor any other "user-type user" ).
But maybe I just don't get what way you really mean?
I'm happy to give all the feedback you need ... but have to understand your suggestion :-)

**Comment by pazos** [comment]
My phone did update to Android 14 and refuses to open any file via an intent, even when its path is guessed correctly :/

So, I'm going to attempt this.

To avoid breaking workflows I'm going to keep a compatibility mode that does:

1. try to guess the path
2. if the path is guessed and belongs to public storage then open it directly
3. if no path is guessed or not in public storage then make a copy if it*

For android 13 onwards we skip 1 and 2 and go straight with the copy*


* the copy is going to be, by default, in cache dir (/sdcard/Android/data/org.koreader.launcher{.fdroid}) with an option to change it to both the home dir, as defined by the user, or a custom path.

The cache dir is the proper way to do it but has a few drawbacks. It's storage is managed by the OS and it will get pruned automatically when the filesystem is low on space. 

It shouldn't matter for the files themselves, since they are already placed on a different path on the filesystem, but affects metadata.

So people that want to preserve/archive metadata for long periods of time will be better switching to centralized metadata or changing the import/copy path to some other public directory.
