### ISSUE TITLE
FR: [Add Chinese pinyin input method（添加中文拼音输入法）]

### ISSUE THREAD

**Issue by Benjamin-Watson0** [koreader/koreader#9833]
**Does your feature request involve difficulty completing a task? Please describe.**
Add Chinese pinyin input method,I think the Stroke count method is too few, at least I've never used it and can't master it.

添加中文拼音输入法，使用笔画输入法的人太少了，至少我没用过，我尝试了并发现很难掌握。（这能实现吗，期待中国人的回复）

**Comment by weijiuqiao** [comment]
Technically it's not hard now that we have a generic ime. I think we can do at least one of the following here:
1. ship a minimal pinyin ime with a mapping table under 1MB (won't be very easy to use but can get by)
2. have users download a more fledged version that's many MBs larger. (This data will need to reside in koreader.rock's server cause github is not easy to reach within the wall.)

What do you think? Pinging @Frenzie @poire-z @NiLuJe

**Comment by poire-z** [comment]
How would these 1MB or ++MBs files compress when put in a zip?

I know not much about pinyin, but does it need an IME ? Can't it be inputed with an english like keyboard with maybe easier diacritics access ? Or do one type on roman letters, and the output is stroked chinese ?

(But, aren't we an elite program, and we should enforce/teach users to learn centuries old input methods, and their History - from before the Roman Empire took over and started romanizing every native languages ? :)

**Comment by Frenzie** [comment]
What order of magnitude many MBs are we talking about and also how's the licensing and such? But sure, we can probably find a place for that somewhere.

**Comment by weijiuqiao** [comment]
I tried the <1MB (910k) data converted from this repo [rime-pinyin](https://github.com/rime/rime-pinyin-simp) (Apache licensed) and the experience is much better than I expected. One just need to type word by word instead of a whole sentence (there is mapping data about 23mb that can mostly let you do it).

Pinyin is a romanization for Chinese and you just type the roman letters and the ime converts them into characters. Because of the many homophones (sadly the tone marks are left-out somehow when typing in pinyin), modern IMEs (at least for simplified) lets you type by sentence and give back the most reasonable result (which we don't have to do).

>How would these 1MB or ++MBs files compress when put in a zip?

537kb and 14mb respectively.

Because pinyin is just for simplified, in the future there might be FRs asking for zhuyin, the traditional counterpart. Besides, there are also other types of methods based purely on the shapes (wubi, cangjie, etc) which are of course only used by much fewer people. The stroke-order method is however universal that can be used to type simplified, traditional and even Japanese ones and can act as a nice fallback.

**Comment by pazos** [comment]
> But sure, we can probably find a place for that somewhere.

Just a reminder than packaging the translations as binary `.mo` files would save us about 300kb per language, IIRC :)

**Comment by Frenzie** [comment]
I meant on the server. And binary .mo files, well, there are countless disadvantages associated with that.

1. A user can't quickly experiment
2. A user can't quickly experiment
3. A user can't quickly experiment
4. @pazos will have to write the code to parse binary .mo files because we have no such thing ;-)
5. Real GetText is a bit slow and fairly large, goto 4

Anyway, I don't think that's true. The .mo files may be some 200 kB smaller, but a compressed .mo and a compressed .po are virtually the same size, maybe some 20 kB difference.

**Comment by NiLuJe** [comment]
We could *probably* whip up some custom zstd magic to compress our own .po files, FWIW ;).

**Comment by Frenzie** [comment]
I don't think we need to save a couple of MB that badly, but a priori that does sound more interesting. You'd easily get at least 2 MB of savings out of that one (or even over 3 MB with higher compression if that doesn't affect decompression times too much), vs maybe 1 MB with .mo files.

Anyway, my main point was that we're talking about savings in the order a megabyte, not in the order of 10 megabytes as implied by speaking of 200-300 kB per translation language. If that were the case then easy editability would definitely have to go. ;-)

**Comment by weijiuqiao** [comment]
Off topic, I found that many fonts are in the kindle_fonts_blacklist, and have uncommented a couple to use on my voyage (mostly "STSongMedium" which is quite good quality and a pity to be blacklisted). There doesn't seem to be any issue? Would it be OK to have it released? 🤔

**Comment by NiLuJe** [comment]
@weijiuqiao: Depending on FW versions, there were historically a lot of issues about broken metadata that made CRe drop some of the weights. This *might* behave better since all the weight work done by @poire-z, but I haven't really checked.

Does CRe shout at you about duplicate fonts in the logs?

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader/issues/5950

**Comment by weijiuqiao** [comment]
> Does CRe shout at you about duplicate fonts in the logs?

No, and there’s no complaint about the specific font in the logs either.

**Comment by Benjamin-Watson0** [comment]
Although I can't understand your discussion, it seems that this is not easy to achieve.😵‍💫

**Comment by NiLuJe** [comment]
Which device and FW version are you testing on?

**Comment by weijiuqiao** [comment]
>Which device and FW version are you testing on?

Kindle Voyage 5.13.6

I also dug out my old kindle and tested, no issue or complaints either:
Kindle Paperwhite 2, on 5.6.1

**Comment by weijiuqiao** [comment]
I turned off blacklist on the paperwhite2, no complaints in logs but a couple fonts are blank in the font-selection menu. They also result in blank pages when applied.

**Comment by weijiuqiao** [comment]
>They also result in blank pages when applied.

The blank ones are: HYMyeongJo, HYGothic, Song T (name visible in the parent menu). Their glyphs are blank but the fallback glyphs are shown.

Turned off blacklist on my Voyage too, this time some errors(EmberBold-Itatic, EmberBold-Regular, Caecilias, KindleBlackBox, Noto-Naskh)  No blank menu (the fonts that resulted in them on the paperwhite are gone), Amazon Ember works no problem (bold is bold and regular is regular).

**Comment by weijiuqiao** [comment]
>this time some errors(EmberBold-Itatic, EmberBold-Regular, Caecilias, KindleBlackBox, Noto-Naskh)

Apologies, the errors are on the paperwhite, too. I didn't get to the latest page.

**Comment by amitbha** [comment]
How about support speech input method via plugin? 
能否以插件的形式的支持语音输入？现有的笔画输入法作修正用，毕竟词库感人

**Comment by NiLuJe** [comment]
@weijiuqiao: IIRC, the first two are OTA-only for CJK devices, so I've never seen them myself ;o).

The rest does sound familiar, and is the reason behind the blacklist. The exact amount of breakage fluctuates between FW versions, which is why the blacklist is fairly wide :/.

**Comment by Frenzie** [comment]
@NiLuJe Even if you bought a cheap Chinese book for testing?

**Comment by NiLuJe** [comment]
I'm not quite sure how the evil overlord decides whether you're eligible for the CJK font OTA ;o).

At the very least, I assume it requires the device to be setup in a matching language, and, yeah, it probably requires attempting to open a book that would need the extra coverage.

**Comment by agugu2000** [comment]
We use normal keyboard（just like English user）to type PinYin.Each letter represents  a pronunciation.26 letters can make all pronunciations.Almost all 1.4 billion people from chinese mainland can type Pinyin.
Hoping PinYin be supported.Thanks a lot!

**Comment by pomoke** [comment]
On Android and Linux, can we use system IME ?

**Comment by NiLuJe** [comment]
@pomoke: No.
