### ISSUE TITLE
Export highlights - Share as text crashes

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9988]
* KOReader version: 2022.11-69
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
I’ve finished a book and made 7 highlights. 

Tried “Share as” in the Export highlights plugin, but it crashed. 

Exporting as txt worked though.

**Comment by mergen3107** [comment]
Still crashes. I’ll try to get logs over weekend.

**Comment by mergen3107** [comment]
[Expcrash1_logcat.txt](https://github.com/koreader/koreader/files/10828487/Expcrash1_logcat.txt)
[Expcrash1_crashlog.log](https://github.com/koreader/koreader/files/10828488/Expcrash1_crashlog.log)
[Expcrash1_bomb.txt](https://github.com/koreader/koreader/files/10828489/Expcrash1_bomb.txt)

This is the crash when I hit Share as text. There are three or two highlights.

Anything jumps out?

**Comment by poire-z** [comment]
`02-24 15:16:00.779 E/NativeThread( 3350): Failed to run script: [string "android.lua"]:2481: bad argument #2 to 'NewStringUTF' (cannot convert 'bool' to 'const char *')`

`local _title = jni.env[0].NewStringUTF(jni.env, title)`

https://github.com/koreader/android-luajit-launcher/blob/17901da600ec85b02d3f7dc0bd0ce0fc55a6aaec/assets/android.lua#L2476-L2494

https://github.com/koreader/koreader/blob/5c9ba533532a452240b4e99fcbfb4995f38fa1c0/frontend/apps/reader/modules/readerhighlight.lua#L157-L170

We don't pass a title from there - dunno what happens with `jni.env[0].NewStringUTF(jni.env, title)` when title is nil.
@pazos ? May be there's been some refactoring here or there since ?

**Comment by pazos** [comment]
Thanks for the logs and the research!. Will give it a look soon :)

**Comment by mergen3107** [comment]
[ExpCrash3.log](https://github.com/koreader/koreader/files/11133269/ExpCrash3.log)
@pazos 
Here is bomb crash log using the same button on 2023.03-27 . There have been some PRs regarding Export plugin, don't know if they are relevant to this issue.

**Comment by hius07** [comment]
Can we change
https://github.com/koreader/koreader/blob/3d5775241deb34aaa1160e81e1a543a1dcb4a5bd/frontend/device/android/device.lua#L103-L105
to
`android.sendText(text, reason, title or "KOReader", mimetype)`

**Comment by Frenzie** [comment]
Or potentially just ""? (I'd have to check what happens further down.)

**Comment by pazos** [comment]
@mergen3107: is this still an issue?

**Comment by mergen3107** [comment]
@pazos 
I’ll double check later this evening.

**Comment by mergen3107** [comment]
Yes, this is still an issue. It crashes as soons as I hit any format in the Share menu.

**Comment by mergen3107** [comment]
Export folder is the default one (clipboard inside koreader on the internal storage)

**Comment by mergen3107** [comment]
Exporting works though. 
Is the share function expecting some Android package? I disabled a bunch on mine long time ago. 

However, the usual Share context works outside KOReader, e.g., in TotalCommander

**Comment by mergen3107** [comment]
@hius07 @Frenzie 
Sorry guys, I must have forgotten this ticket (was going through my old ones).

I replaced it with `android.sendText(text, reason, title or "", mimetype)` and it now works!
Was able to test it on Onyx Boox Kon-Tiki 2.

I'll make a PR.

Thank you so much!

**Comment by pazos** [comment]
Commenting here since I'm trying to grasp what happens here. If @mergen3107 patch on https://github.com/koreader/koreader/pull/11238 fixes the issue without providing a `mimetype` then something fishy happens.

Quoting myself from the PR: 

> I don't remember anymore but I think I tested that jni.env[0].NewStringUTF(jni.env, nil) produces a null string when I implemented this. Otherwise the issue you're experiencing could be reproduced if there's no reason or no mimetype.

And re-reading @poire-z comment:

> `02-24 15:16:00.779 E/NativeThread( 3350): Failed to run script: [string "android.lua"]:2481: bad argument #2 to 'NewStringUTF' (cannot convert 'bool' to 'const char *')`

> We don't pass a title from there - dunno what happens with jni.env[0].NewStringUTF(jni.env, title) when title is nil.
@pazos ? May be there's been some refactoring here or there since ?

Indeed, I did a refactor in https://github.com/koreader/koreader/pull/9193/files.

My questions:
How on earth is nil interpreted as bool when passed as 3rd parameter but as nil when passed as 4th?
Are we inheriting a boolean field from `self` named `title`?

If that's the case avoiding `self`references in `doSharetext` and invoking `Device.doShareText(text)` should be enough to fix the issue.

**Comment by poire-z** [comment]
> How on earth is nil interpreted as bool when passed as 3rd parameter but as nil when passed as 4th?

Haven't looked at the code involved - but I remember I had met some cases with Lua where a `nil` as a parameter stopped the parsing/usage of any followup parameter.
I haven't met this for some time - so I'm not sure when or with what kind of constructs it can happen. But at the time, my trick was to use .`.., param_that_could_be_nil or false, other_param...` so I get a real `false`, that avoided that obscure issue.

**Comment by NiLuJe** [comment]
> but I remember I had met some cases with Lua where a `nil` as a parameter stopped the parsing/usage of any followup parameter.

Usually when iterating an array or varargs are involved, hence our `t = table.pack(...)` => `table.unpack(t, 1, t.n)` trickery in Event

**Comment by NiLuJe** [comment]
What's happening here looks much simpler: Lua doesn't really have a ternary operator, the `$conditional and assignment` syntax really means `$conditional and true or false`:

```
> msg_title = type(title) == "string" and title
> print(type(msg_title))
```

vs.

```
> msg_title = type(title) == "string" and title or nil
> print(type(msg_title))
nil
```

**Comment by NiLuJe** [comment]
From: https://github.com/koreader/koreader/blob/9d94ab38f34e60a3635607413e60868daef25d75/plugins/exporter.koplugin/base.lua#L155-L157

**Comment by pazos** [comment]
> From:
> 
> https://github.com/koreader/koreader/blob/9d94ab38f34e60a3635607413e60868daef25d75/plugins/exporter.koplugin/base.lua#L155-L157

Ah, makes sense.

I was looking at the wrong invokation, at https://github.com/koreader/koreader/blob/5a4e70a19da4e77bdd80f2335145004466fbce6b/frontend/apps/reader/modules/readerhighlight.lua#L159-L172 but I just tested and it doesn't crash there.

So, everything is fine backend-wise, and that chunk of code can be rewritten as

```lua
function BaseExporter:shareText(text, title)
    local reason = _("Share") .. " " .. self.name
    Device:doShareText(text, reason, msg_title, self.mimetype)
end
```

Pinging @mergen3107: could you check that you cannot reproduce the issue with the change above?

**Comment by mergen3107** [comment]
@pazos 
I can check, but not very soon - once I have my hands again on the Onyx Boox (or other Android KOReader)

**Comment by mergen3107** [comment]
@pazos 
Yes, it works!
First, I undid changes proposed in #11238 
Then only applied this mod to `base.lua` - no crash.

**Comment by mergen3107** [comment]
Thank you @pazos and everyone who helped!
