### ISSUE TITLE
Screensaver options missing

### ISSUE THREAD

**Issue by jenkshields** [koreader/koreader#9992]
* KOReader version: 2022.11
* Device: Kindle Voyager 3G US

#### Issue
Screensaver settings are missing from koreader. This is not a special offers device - I’ve installed the screensaver hack with no problem, but the screensaver hack won’t pick up book covers from koreader.

**Comment by NiLuJe** [comment]
The ScreenSaver hack has nothing to do with KOReader, and will never pick up KOReader stuff, ever.

If you end don't see KOReader's own ScreenSaver settings and actually end up seeing the stock/hack screensavers instead, then your device *is* flagged as Special Offers. Check your Kindle state on your Amazon account.

**Comment by jenkshields** [comment]
Thanks for confirming that - there’s no special offers listed at all in my kindle settings on amazon, but I’ll reach out to customer service and see if I can sort it at their end.

**Comment by NiLuJe** [comment]
Note that you shouldn't have a working ScreenSavers hack either if that were the case...

**Comment by NiLuJe** [comment]
Which leads me to the pernenial "Have you tried turning it off and on again?" ;o).

(But, seriously, try that, with a forced sync before and after the reboot).

**Comment by NiLuJe** [comment]
In particular, was the device *purchased* with Special Offers enabled? (Or are they enabled on another device on that account, or were they ever enabled on *any* device, past or present, on that account?).

**Comment by jenkshields** [comment]
That’s what I figured!

I bought it second hand about four years ago so I don’t remember if it had special offers, or if the owner before me had - I’ve never seen an ad on it, but I’m in NZ and I’m not sure how often ads are shown here. The stock screensaver does have ‘swipe to unlock’ which I think I’ve read is a SO screensaver feature?

I’ll give rebooting it a try - what do you mean by force sync?

**Comment by NiLuJe** [comment]
> The stock screensaver does have ‘swipe to unlock’ which I think I’ve read is a SO screensaver feature?

Yeah, that is *definitely* SO ;o). (Which means you are *not* seeing the screensavers hack either).

> what do you mean by force sync?

I meant forcing a sync via the actual button instead of relying on background synchronization.

----

You should see the actual status on the "My Devices" section (or whatever it has been renamed to these days) of your Amazon account (... assuming SO are supported in your location; if not, CS should be able to deal with it).

**Comment by jenkshields** [comment]
Oh, that’s real interesting! The screensaver hack is definitely working, which I didn’t think was possible!

I’ll reach out to CS to disable SO, thanks for your help!

**Comment by Monirzadeh** [comment]
@NiLuJe I run KOReader in `no framework` mode.
In this specific situation, it shows me just default boring screensaver (without ads).
I am not sure, but somehow default special offer screensaver program not start in this mode.
If special offer possess is the problem (that block screensaver functionality), maybe we can activate that in this mode.

**Comment by NiLuJe** [comment]
That's somewhat expected, and not something I'm willing to linger on.

**Comment by Monirzadeh** [comment]
> That's somewhat expected, and not something I'm willing to linger on.

Ok, no problem, but just one more thing to ask.
For now, one of my device is special offers that I can test that but KOReader detect my device as spacial offer and not show screensaver settings.
Is there any hidden config or any other way to temporarily disable this functionality (disable screensaver if it is a spacial offer device)?

**Comment by Monirzadeh** [comment]
> That's somewhat expected, and not something I'm willing to linger on.

@jenkshields @NiLuJe 
I confirm that work fine on my device as I think.
Now we can use screensaver on special offers device too.
I test that on my device and for now it is more like a hack (not test all aspect of that, maybe some random bugs appear that I am not aware of them yer).

Maybe later I can do more test and make that as a feature.
@NiLuJe Is it possible that this feature made legal issue for KOReader?

Anyway, for anybody else that has the same question or tend to make that work just because it is possible:
1. change this line to `true`
https://github.com/koreader/koreader/blob/8d133507ad696e58e5e763999bbafcacef367b92/frontend/device/kindle/device.lua#L208
2. Load KOReader in `no framework`
3. enjoy your Journey
5. learn about how things work and find bugs
6. find that posses handle special offer functionality
7. write script to kill that, then load KOReader automatically
8. send a pull request.

I AM NOT RESPONSIBLE FOR ANY DAMAGE TO YOUR DEVICE

**Comment by poire-z** [comment]
> Maybe later I can do more test and make that as a feature.
Is it possible that this feature make legal issue for KOReader?

I personally would not mind, but I think some of us (past or present) didn't/don't want to get Amazon angry (as if Amazon would care :), and so prefer to play gentle as per their rules.

So, to be safe, you could just provide a [User patch](https://github.com/koreader/koreader/wiki/User-patches) so users themselves would make that decision for their own use, and just download it and drop it on their device.
`2-i-m-not-special-need-no-offers.lua`
```lua
local Device = require("device")
Device.supportsScreensaver = function() return true end
Device.powerd:initWakeupMgr() -- this would be needed I guess
```
(I don't own a Kindle, so the above is not garanteed and just to get you started :)

**Comment by NiLuJe** [comment]
Yeah, my stance on that is still very much a hard nope. (And if there is *one* thing that Amazon does care about in this ecosystem, it is very very much breaking SO).

**Comment by zeussesions** [comment]
Copying the sh script to the root of my device worked for me. I got this off a tiktok so idk how permanent this solution is but it worked
[script](https://drive.google.com/file/d/1JE6nst4O_BPK1kbO7V2HTmm4AhI8wItF/view?fbclid=IwY2xjawJM2F1leHRuA2FlbQIxMQABHcqEQrG7KWd4fP)

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
> Copying the sh script to the root of my device worked for me. I got this off a tiktok so idk how permanent this solution is but it worked [script](https://drive.google.com/file/d/1JE6nst4O_BPK1kbO7V2HTmm4AhI8wItF/view?fbclid=IwY2xjawJM2F1leHRuA2FlbQIxMQABHcqEQrG7KWd4fP)

Thank you, works like a charm!
